# -*- coding: utf-8 -*-
"""BÔNUS 2 — PILATES SECA BARRIGA EM CASA. 12 exercícios (fotos 159-170).
Foco no core (abdômen profundo) + postura. Feito no chão/tapete, sem aparelhos.
Cada exercício: foco, nível, séries, tempo, passo a passo, respiração, dica, prompt.
Linguagem simples; sempre com variação mais fácil para iniciantes/idosos.
"""

EXERCICIOS = [
{
 "nome": "Respiração do Pilates (Ativar o Abdômen)",
 "foco": "Aprender a contrair o abdômen profundo — a base de todos os exercícios.",
 "nivel": "Iniciante", "series": "5 respirações", "tempo": "2 min",
 "hook": "Antes de tudo, aprenda a ligar o abdômen por dentro — é isso que faz o Pilates funcionar e a barriga ficar mais firme.",
 "passos": [
   "Deite de costas, com os joelhos dobrados e os pés apoiados no chão, na largura do quadril. Deixe os braços ao lado do corpo.",
   "Coloque as mãos sobre a barriga. Puxe o ar pelo nariz, enchendo a barriga como um balão.",
   "Solte o ar devagar pela boca e, ao mesmo tempo, puxe o umbigo para dentro, na direção da coluna, como se fosse fechar o zíper de uma calça apertada.",
   "Segure essa contração por 3 segundos, sentindo a barriga firme, e relaxe.",
   "Repita 5 vezes, sempre soltando o ar e puxando o umbigo para dentro."],
 "respiracao": "Puxe o ar pelo nariz enchendo a barriga; solte pela boca esvaziando e contraindo o abdômen. Nunca prenda a respiração.",
 "dica": "Esse 'puxar o umbigo para dentro' é o segredo do Pilates. Você vai usar essa mesma contração em todos os outros exercícios — é ela que trabalha o músculo mais profundo da barriga, o que segura tudo no lugar e afina a cintura.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat with knees bent and hands on the belly, calm home setting, soft natural light, fitness demonstration, neutral clothing, full body visible, no text, no writing, 1:1 square.",
},
{
 "nome": "Báscula de Quadril",
 "foco": "Aquecer a coluna e ativar a parte baixa do abdômen.",
 "nivel": "Iniciante", "series": "2 séries de 10", "tempo": "3 min",
 "hook": "Um movimento pequeno e suave que solta a lombar e acorda a parte de baixo da barriga.",
 "passos": [
   "Continue deitado de costas, joelhos dobrados e pés no chão.",
   "Solte o ar e puxe o umbigo para dentro, girando a bacia de leve para trás, de forma que a lombar (parte baixa das costas) encoste totalmente no chão.",
   "Puxe o ar e volte devagar, deixando um pequeno vão entre a lombar e o chão.",
   "Faça o movimento bem devagar, como se estivesse desenhando com o quadril, sem forçar.",
   "Repita 10 vezes, descanse e faça mais uma série de 10."],
 "respiracao": "Solte o ar ao encostar a lombar no chão; puxe o ar ao voltar. O movimento acompanha a respiração.",
 "dica": "É um aquecimento perfeito para quem tem a lombar sensível. O movimento é curto de propósito — quem manda é a contração da barriga, não a força das costas.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat performing a gentle pelvic tilt, knees bent, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "O Cem (The Hundred)",
 "foco": "O exercício mais famoso do Pilates para o abdômen inteiro.",
 "nivel": "Intermediário", "series": "1 série (contar até 100)", "tempo": "3 min",
 "hook": "O clássico que aquece o corpo todo e faz o abdômen queimar — de leve, mas queima.",
 "passos": [
   "Deite de costas, dobre os joelhos e levante as pernas até que fiquem dobradas em 90 graus (canela paralela ao chão), como se estivesse sentado numa cadeira de cabeça para baixo.",
   "Solte o ar, puxe o umbigo para dentro e levante levemente a cabeça e os ombros do chão, olhando para a barriga. Estenda os braços retos ao lado do corpo, um palmo acima do chão.",
   "Comece a balançar os braços para cima e para baixo, com movimentos curtos e firmes, como se batesse na água.",
   "Conte cinco balanços enquanto puxa o ar e cinco enquanto solta o ar.",
   "Continue até completar 100 balanços (ou pare antes se cansar). Depois abaixe a cabeça e as pernas e descanse."],
 "respiracao": "Puxe o ar por 5 balanços e solte o ar por 5 balanços, sem parar de bombear os braços.",
 "dica": "Variação mais fácil: mantenha os pés apoiados no chão e só levante a cabeça e os ombros. Comece com 30 ou 50 balanços e vá aumentando até chegar aos 100 com o tempo.",
 "prompt": "Square photograph of a person on a yoga mat doing the Pilates hundred exercise, head and shoulders lifted, legs bent at 90 degrees, arms pumping beside the body, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Elevação Alternada de Pernas",
 "foco": "Parte baixa da barriga e controle do movimento.",
 "nivel": "Iniciante", "series": "2 séries de 12", "tempo": "3 min",
 "hook": "Um movimento controlado que trabalha exatamente aquela região baixa da barriga, a mais teimosa.",
 "passos": [
   "Deite de costas, joelhos dobrados e pés apoiados no chão. Mantenha a lombar encostada no chão o tempo todo.",
   "Solte o ar, puxe o umbigo para dentro e levante um pé do chão, trazendo o joelho na direção da barriga, até a coxa ficar em pé (90 graus).",
   "Puxe o ar e desça o pé devagar até tocar o chão de novo, com controle.",
   "Alterne: agora levante a outra perna do mesmo jeito.",
   "Faça 12 vezes com cada perna, mantendo a barriga sempre contraída. Descanse e repita a série."],
 "respiracao": "Solte o ar ao subir a perna; puxe o ar ao descer. O abdômen fica firme o tempo inteiro.",
 "dica": "O importante não é a velocidade, é o controle: quanto mais devagar você desce a perna, mais a barriga trabalha. Se sentir a lombar arquear e sair do chão, suba menos a perna.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat lifting one bent knee toward the chest, core engaged, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Abdominal Curto (Elevação do Tronco)",
 "foco": "Parte de cima e do meio da barriga.",
 "nivel": "Iniciante", "series": "3 séries de 12", "tempo": "4 min",
 "hook": "O abdominal de sempre, mas feito com controle do Pilates — sobe pouco e trabalha muito.",
 "passos": [
   "Deite de costas, joelhos dobrados e pés no chão. Cruze os braços sobre o peito ou apoie as mãos atrás da cabeça, sem puxar o pescoço.",
   "Solte o ar, puxe o umbigo para dentro e enrole o tronco para cima, tirando a cabeça e os ombros do chão, como se fosse aproximar as costelas do quadril.",
   "Suba só até as pontas das omoplatas saírem do chão (não precisa sentar). Segure 1 segundo no alto.",
   "Puxe o ar e desça devagar, enrolando a coluna de volta ao chão, vértebra por vértebra.",
   "Repita 12 vezes, descanse e faça 3 séries no total."],
 "respiracao": "Solte o ar ao subir (é aí que a barriga se contrai mais); puxe o ar ao descer.",
 "dica": "Não puxe o pescoço com as mãos — o olhar vai para a barriga e o queixo fica afastado do peito, com espaço para uma laranja. Quem levanta o corpo é o abdômen, não o pescoço.",
 "prompt": "Square photograph of a person on a yoga mat doing a small controlled crunch, shoulders lifted, hands crossed on chest, knees bent, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Prancha Frontal",
 "foco": "Abdômen inteiro, lombar e postura — o exercício mais completo do core.",
 "nivel": "Intermediário", "series": "3 vezes segurando 20–40 s", "tempo": "4 min",
 "hook": "Parada, mas poderosa: segurar a prancha fortalece toda a barriga e as costas de uma vez só.",
 "passos": [
   "Fique de bruços e apoie os antebraços no chão, com os cotovelos embaixo dos ombros. As mãos ficam à frente.",
   "Estenda as pernas para trás e apoie as pontas dos pés no chão.",
   "Solte o ar, puxe o umbigo para dentro e levante o corpo, deixando-o reto como uma tábua, dos calcanhares até a cabeça.",
   "Mantenha o quadril na linha do corpo — nem levantado como um morro, nem caído para o chão. Olhe para o chão para não forçar o pescoço.",
   "Segure de 20 a 40 segundos, respirando normalmente. Desça, descanse e repita 3 vezes."],
 "respiracao": "Continue respirando normal e devagar durante toda a prancha. Não prenda o ar.",
 "dica": "Variação mais fácil: apoie os joelhos no chão (prancha de joelhos). Comece segurando 15 segundos e vá aumentando aos poucos. Se a lombar doer, é sinal de que o quadril caiu — levante-o um pouco.",
 "prompt": "Square photograph of a person holding a forearm plank on a yoga mat, straight body line, core engaged, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Prancha Lateral",
 "foco": "Os músculos laterais da barriga (oblíquos) — afina a cintura.",
 "nivel": "Intermediário", "series": "2 vezes de cada lado, 15–30 s", "tempo": "4 min",
 "hook": "É o exercício que desenha a lateral do abdômen e marca a cintura.",
 "passos": [
   "Deite de lado, com o corpo reto. Apoie o antebraço de baixo no chão, com o cotovelo embaixo do ombro.",
   "Empilhe uma perna sobre a outra (um pé em cima do outro).",
   "Solte o ar, puxe o umbigo para dentro e levante o quadril do chão, deixando o corpo reto e apoiado só no antebraço e na lateral do pé.",
   "Estenda o braço de cima para o teto ou apoie a mão na cintura. Segure de 15 a 30 segundos.",
   "Desça com controle, vire para o outro lado e repita. Faça 2 vezes de cada lado."],
 "respiracao": "Respire normal e devagar enquanto segura a posição.",
 "dica": "Variação mais fácil: dobre os joelhos e apoie a parte de baixo das pernas no chão, levantando só o quadril. A cintura é o que mais trabalha aqui — segure firme.",
 "prompt": "Square photograph of a person holding a side plank on a yoga mat, body straight, supported on one forearm, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Ponte de Glúteos",
 "foco": "Glúteos, parte de trás das coxas e abdômen — e alivia a lombar.",
 "nivel": "Iniciante", "series": "3 séries de 12", "tempo": "3 min",
 "hook": "Levanta o bumbum, fortalece o abdômen por trás e ainda deixa a postura mais bonita.",
 "passos": [
   "Deite de costas, joelhos dobrados e pés apoiados no chão, na largura do quadril. Braços ao lado do corpo.",
   "Solte o ar, puxe o umbigo para dentro e levante o quadril do chão, apertando os glúteos, até o corpo formar uma linha reta dos joelhos aos ombros.",
   "Segure 2 segundos no alto, mantendo os glúteos e a barriga firmes.",
   "Puxe o ar e desça o quadril devagar, enrolando a coluna de volta ao chão, vértebra por vértebra.",
   "Repita 12 vezes, faça 3 séries."],
 "respiracao": "Solte o ar ao subir o quadril; puxe o ar ao descer.",
 "dica": "Suba apertando bem os glúteos, não empurrando a lombar. É um dos poucos exercícios que fortalece a barriga e ainda alivia dores nas costas — ótimo para quem passa o dia sentado.",
 "prompt": "Square photograph of a person on a yoga mat doing a glute bridge, hips lifted, knees bent, shoulders on the mat, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Desenrolar da Coluna (Roll Up)",
 "foco": "Abdômen inteiro e flexibilidade da coluna.",
 "nivel": "Intermediário", "series": "2 séries de 8", "tempo": "4 min",
 "hook": "Sentar e deitar enrolando a coluna devagar — parece simples, mas o abdômen faz todo o trabalho.",
 "passos": [
   "Deite de costas com as pernas estendidas e os braços esticados para trás, acima da cabeça.",
   "Puxe o ar e traga os braços para a frente, apontando para o teto.",
   "Solte o ar, puxe o umbigo para dentro e comece a sentar bem devagar, enrolando a coluna: primeiro a cabeça, depois os ombros, as costas, até sentar e alcançar os pés com as mãos.",
   "Puxe o ar no alto e, soltando o ar, desça do mesmo jeito devagar, enrolando a coluna de volta ao chão, vértebra por vértebra.",
   "Repita 8 vezes, com o máximo de controle. Faça 2 séries."],
 "respiracao": "Solte o ar enquanto sobe e enquanto desce (é quando a barriga trabalha); puxe o ar nas pausas.",
 "dica": "Variação mais fácil: dobre um pouco os joelhos e, se precisar, dê um impulso pequeno com os braços. O importante é subir e descer devagar — quem faz força é a barriga, não o pescoço nem os braços.",
 "prompt": "Square photograph of a person on a yoga mat performing a Pilates roll up, spine curling up to reach toward the feet, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Abdominal Bicicleta",
 "foco": "Os oblíquos (laterais da barriga) e o abdômen inteiro.",
 "nivel": "Intermediário", "series": "3 séries de 20 (10 de cada lado)", "tempo": "4 min",
 "hook": "O movimento de pedalar que desenha as laterais da barriga e acelera o coração de leve.",
 "passos": [
   "Deite de costas, mãos atrás da cabeça (sem puxar o pescoço). Levante as pernas com os joelhos dobrados em 90 graus.",
   "Solte o ar, puxe o umbigo para dentro e levante a cabeça e os ombros do chão.",
   "Gire o tronco levando o cotovelo direito na direção do joelho esquerdo, enquanto estica a perna direita para a frente.",
   "Volte ao centro e faça para o outro lado: cotovelo esquerdo na direção do joelho direito, esticando a perna esquerda.",
   "Continue alternando, como se pedalasse uma bicicleta devagar. Faça 20 no total (10 de cada lado), 3 séries."],
 "respiracao": "Solte o ar a cada giro do tronco; puxe o ar ao passar pelo centro.",
 "dica": "Faça devagar e com controle, não na pressa — o giro do tronco é o que trabalha a lateral da barriga. Quanto mais você estica a perna para longe, mais difícil e mais eficiente fica.",
 "prompt": "Square photograph of a person on a yoga mat doing a bicycle crunch, torso rotated, one elbow toward the opposite knee, other leg extended, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Superman (Extensão de Costas)",
 "foco": "Costas e postura — equilibra o corpo e deixa a barriga mais reta em pé.",
 "nivel": "Iniciante", "series": "3 séries de 10", "tempo": "3 min",
 "hook": "Depois de tanto abdominal, este fortalece as costas e melhora a postura — o que já deixa a barriga parecer mais reta.",
 "passos": [
   "Deite de bruços (barriga para baixo), com os braços estendidos para a frente e as pernas esticadas para trás.",
   "Solte o ar, puxe o umbigo levemente para dentro e levante ao mesmo tempo os braços, o peito e as pernas do chão, alguns centímetros, como o Super-Homem voando.",
   "Segure 2 segundos no alto, olhando para o chão para não forçar o pescoço.",
   "Puxe o ar e desça devagar, relaxando.",
   "Repita 10 vezes, faça 3 séries."],
 "respiracao": "Solte o ar ao levantar; puxe o ar ao descer. Movimento suave, sem solavancos.",
 "dica": "Não precisa levantar alto — poucos centímetros já trabalham as costas. Fortalecer as costas é essencial: costas fortes seguram você ereto, e uma boa postura por si só já faz a barriga parecer menor.",
 "prompt": "Square photograph of a person lying face down on a yoga mat lifting arms, chest and legs off the floor in a superman back extension, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Alongamento Final",
 "foco": "Relaxar a coluna e o abdômen depois do treino.",
 "nivel": "Todos", "series": "Segurar 30 s cada", "tempo": "3 min",
 "hook": "Para encerrar, um alongamento gostoso que relaxa a barriga e as costas que você acabou de trabalhar.",
 "passos": [
   "Fique de quatro (mãos e joelhos no chão). Sente o bumbum sobre os calcanhares e estenda os braços para a frente, deitando o tronco sobre as coxas (postura de descanso). Encoste a testa no chão e respire fundo por 30 segundos.",
   "Volte a deitar de costas. Abrace um joelho de cada vez, puxando-o na direção do peito, e segure 30 segundos de cada lado — isso relaxa a lombar.",
   "Por fim, deitado de costas com os braços abertos, deixe os dois joelhos caírem devagar para um lado e depois para o outro, girando de leve a coluna, 30 segundos para cada lado.",
   "Respire fundo durante todo o alongamento, sem pressa.",
   "Levante-se devagar quando terminar."],
 "respiracao": "Respire fundo e devagar, soltando o ar a cada alongamento e deixando o corpo relaxar mais um pouco.",
 "dica": "Nunca pule o alongamento: ele relaxa os músculos que trabalharam, evita dores no dia seguinte e melhora a flexibilidade. É o momento de sentir o corpo e fechar o treino em paz.",
 "prompt": "Square photograph of a person on a yoga mat in child's pose stretching, arms extended forward, forehead near the floor, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
]
