# -*- coding: utf-8 -*-
"""BONUS 3 — 50 HABITOS Y EJERCICIOS. ESPANHOL (America Latina).

Traducao literal de `exercicios_habitos_en.py`. Convencoes em
GLOSSARIO-TRADUCAO.md: tratamento por "tu", vocabulario LatAm com foco
Mexico (caminadora, sentadilla, cuerda, barandal).
⛔⛔ METRICO — e AQUI o EN e' imperial de verdade: `1.2/2/2.5/3 miles` volta
   para `2/3/4/5 km` e `2 quarts` volta para `2 litros`. Os valores metricos
   vem do de/fr, nunca de milha -> km de volta.
⚠️ `knees in line with your feet` NAO se converte: ali "feet" sao os pes do
   corpo, nao a unidade. O DE confirma (`Füße`).
⛔ 11 temas, 50 itens: 8 de tipo "exercicio" (nome/img/onde/gasto/plano/dica)
   e 3 de tipo "habito" (titulo/desc).
"""

TEMAS = [
{
 "tema": "Caminar y correr", "tipo": "exercicio",
 "intro": "La forma más simple y barata de quemar grasa — en la calle, en el parque o en la caminadora.",
 "itens": [
   {"nome": "Caminata", "img": 171,
    "onde": "Calle, parque o caminadora",
    "gasto": "~150 calorías en 30 minutos",
    "plano": "Semana 1-2: 2 km a un ritmo cómodo, 4 o 5 veces por semana. · Semana 3-4: 3 km, apretando el paso. · Semana 5-6: 4 km, con subidas o 3 % de inclinación en la caminadora. · Semana 7 en adelante: 5 km o 45 minutos a paso fuerte.",
    "dica": "Mantén un ritmo en el que todavía puedas hablar, pero con esfuerzo. En la caminadora, usa una inclinación ligera para quemar más sin correr."},
   {"nome": "Caminata rápida", "img": 172,
    "onde": "Calle o caminadora",
    "gasto": "~200 calorías en 30 minutos",
    "plano": "Cuando ya hagas los 5 km con seguridad, alterna 3 minutos a paso fuerte + 2 minutos normal, durante 30 a 40 minutos. Ve alargando poco a poco los tramos rápidos.",
    "dica": "Bombea los brazos doblados a 90 grados y da pasos firmes. Quema casi tanto como un trote, sin impacto en las rodillas."},
   {"nome": "Trote (método caminar-correr)", "img": 173,
    "onde": "Calle, parque o caminadora",
    "gasto": "~250 calorías en 30 minutos",
    "plano": "Semana 1-2: 1 minuto de trote + 2 minutos de caminata, durante 20 minutos. · Semana 3-4: 2 minutos de trote + 1 minuto. · Semana 5-6: 3 minutos de trote + 1 minuto. · Después: acorta las pausas hasta correr sin parar.",
    "dica": "Toma el trote con calma — si te falta el aire, baja el ritmo. Así es como tu cuerpo aprende a correr sin sufrir."},
   {"nome": "Carrera continua", "img": 174,
    "onde": "Calle, parque o caminadora",
    "gasto": "~300 calorías en 30 minutos",
    "plano": "Cuando puedas correr 20 minutos sin parar, agrega 5 minutos por semana hasta llegar a 40-45 minutos. Una vez por semana, haz un tramo más rápido.",
    "dica": "Un buen par de tenis hace toda la diferencia para tus rodillas. Corre a un ritmo en el que puedas respirar por la nariz la mayor parte del tiempo."},
 ]},
{
 "tema": "Ciclismo", "tipo": "exercicio",
 "intro": "Quema mucha grasa y es suave con las rodillas — ideal para quien carga peso de más.",
 "itens": [
   {"nome": "Bicicleta al aire libre", "img": 175,
    "onde": "Calle, ciclovía o parque",
    "gasto": "~250 calorías en 30 minutos",
    "plano": "Semana 1-2: 20 minutos en plano. · Semana 3-4: 30 minutos, con subidas pequeñas. · Semana 5 en adelante: de 40 a 60 minutos, variando el ritmo.",
    "dica": "Ajusta el asiento: tu pierna debe quedar casi estirada con el pedal abajo. Eso protege tu rodilla y te deja andar más tiempo."},
   {"nome": "Bicicleta fija", "img": 176,
    "onde": "Casa o gimnasio",
    "gasto": "~250 calorías en 30 minutos",
    "plano": "Semana 1-2: 20 minutos con resistencia ligera. · Semana 3-4: 30 minutos, subiendo la resistencia. · Después: 40 minutos alternando 2 minutos fuerte + 3 minutos ligero.",
    "dica": "Perfecta para los días de lluvia. Sube la resistencia poco a poco para no estar pedaleando 'en el aire'."},
   {"nome": "Spinning", "img": 177,
    "onde": "Gimnasio",
    "gasto": "~350 calorías en 30 minutos",
    "plano": "Empieza con 1 clase por semana y sube a 2 o 3. Sigue al instructor, pero respeta tu propio límite en la resistencia.",
    "dica": "Una de las clases que más calorías quema. Toma agua durante la clase y empieza con menos resistencia — sube a tu propio ritmo."},
 ]},
{
 "tema": "Natación y ejercicio en el agua", "tipo": "exercicio",
 "intro": "El agua sostiene el peso de tu cuerpo, así que casi no hay impacto — buenísimo para quien tiene dolor en las articulaciones.",
 "itens": [
   {"nome": "Natación", "img": 178,
    "onde": "Alberca",
    "gasto": "~300 calorías en 30 minutos",
    "plano": "Semana 1-2: nada 20 minutos con pausas en la orilla. · Semana 3-4: acorta las pausas, llega a 30 minutos. · Después: 40 minutos continuos, variando los estilos.",
    "dica": "Trabaja todo tu cuerpo sin sobrecargar rodillas ni columna. Una o dos clases ayudan muchísimo con la respiración."},
   {"nome": "Aquaeróbics", "img": 179,
    "onde": "Alberca",
    "gasto": "~200 calorías en 30 minutos",
    "plano": "De 1 a 3 clases por semana. La intensidad sube conforme empujas los movimientos con más fuerza contra el agua.",
    "dica": "Hecho con energía, quema bastante y fortalece las piernas con cero impacto. Excelente para quien carga mucho peso de más."},
 ]},
{
 "tema": "Entrenamiento por intervalos (quema rápida)", "tipo": "exercicio",
 "intro": "Poco tiempo, grandes resultados: alterna esfuerzo fuerte con un descanso corto. Quema grasa durante y por horas después.",
 "itens": [
   {"nome": "Saltar la cuerda", "img": 180,
    "onde": "Casa, patio o gimnasio",
    "gasto": "~350 calorías en 30 minutos",
    "plano": "Semana 1-2: 30 segundos saltando + 1 minuto de descanso, durante 10 minutos. · Semana 3-4: 1 minuto + 1 minuto, durante 15 minutos. · Después: 2 minutos + 1 minuto, durante 20 minutos.",
    "dica": "De las mayores quemas por minuto, y la cuerda es muy barata. Salta bajito, lo justo para que pase la cuerda."},
   {"nome": "HIIT (Tabata)", "img": 181,
    "onde": "Casa o gimnasio",
    "gasto": "~350 calorías en 30 minutos",
    "plano": "4 ejercicios (saltos de tijera, sentadillas, correr en el lugar, plancha): 20 segundos fuerte + 10 segundos de descanso en cada uno, 4 rondas. Empieza con 10 minutos y sube a 20.",
    "dica": "Corto e intenso. Tu cuerpo sigue quemando grasa por horas después. De 2 a 3 veces por semana ya alcanza para tener resultados."},
   {"nome": "Subir escaleras", "img": 182,
    "onde": "Edificio, plaza o escaladora",
    "gasto": "~300 calorías en 30 minutos",
    "plano": "Semana 1-2: sube y baja durante 5 minutos, descansa, repite 3 veces. · Después: bloques de 8 a 10 minutos. Baja siempre despacio para cuidar tus rodillas.",
    "dica": "Trabaja fuerte piernas y glúteos mientras quema grasa. Usa el barandal para bajar con seguridad."},
   {"nome": "Saltos de tijera", "img": 183,
    "onde": "Casa o gimnasio",
    "gasto": "~250 calorías en 30 minutos",
    "plano": "Semana 1-2: 30 segundos + 30 segundos de descanso, 8 rondas. · Semana 3-4: 45 segundos + 20 segundos. · Después: 1 minuto + 20 segundos, 10 rondas.",
    "dica": "Un gran calentamiento y una quema al mismo tiempo. Abre brazos y piernas juntos, a un ritmo parejo."},
   {"nome": "Burpees", "img": 184,
    "onde": "Casa o gimnasio",
    "gasto": "~350 calorías en 30 minutos",
    "plano": "Semana 1-2: 5 burpees, descansa, 4 rondas (sin el salto si lo necesitas). · Después: de 8 a 10 por ronda, con el salto.",
    "dica": "Sentadilla, pon las manos abajo, avienta las piernas hacia atrás, regresa y salta. Es intenso y trabaja todo tu cuerpo — ve a tu propio ritmo."},
   {"nome": "Correr en el lugar (rodillas altas)", "img": 185,
    "onde": "Casa",
    "gasto": "~250 calorías en 30 minutos",
    "plano": "Semana 1-2: 30 segundos + 30 segundos de descanso, 8 veces. · Después: 1 minuto + 30 segundos, 10 veces.",
    "dica": "Corre en el lugar levantando bien las rodillas. Cabe en cualquier rincón, sin salir de casa."},
 ]},
{
 "tema": "Clases y baile", "tipo": "exercicio",
 "intro": "Quien lo disfruta no lo abandona. Queman mucha grasa sin que se sienta un sacrificio.",
 "itens": [
   {"nome": "Baile (Zumba, dance fitness)", "img": 186,
    "onde": "Casa o gimnasio", "gasto": "~300 calorías en 30 minutos",
    "plano": "Empieza con 20 minutos siguiendo videos o una clase y sube a 45-60 minutos. De 3 a 5 veces por semana.",
    "dica": "Ni siquiera se siente como ejercicio. Escoge canciones que te encanten y no dejes de moverte — el sudor llega solo."},
   {"nome": "Boxeo / Muay Thai", "img": 187,
    "onde": "Gimnasio o costal en casa", "gasto": "~350 calorías en 30 minutos",
    "plano": "1 clase por semana hasta llegar a 3; o 3 rondas de 2 minutos en el costal, agregando rondas poco a poco.",
    "dica": "Libera el estrés y quema muchísimo. La técnica llega con las clases — no necesitas llegar sabiendo."},
   {"nome": "Clase de step", "img": 188,
    "onde": "Gimnasio", "gasto": "~300 calorías en 30 minutos",
    "plano": "1 clase por semana hasta llegar a 3, siguiendo la coreografía sobre la plataforma.",
    "dica": "Subes y bajas de una plataforma al ritmo de la música. Trabaja fuerte las piernas y tu resistencia."},
   {"nome": "Mini trampolín", "img": 189,
    "onde": "Gimnasio o casa", "gasto": "~300 calorías en 30 minutos",
    "plano": "Semana 1-2: 15 minutos. · Después: de 30 a 40 minutos de clase.",
    "dica": "Divertido y de bajo impacto para tus articulaciones. Mantén el abdomen firme para sostener el equilibrio."},
 ]},
{
 "tema": "Máquinas de cardio del gimnasio", "tipo": "exercicio",
 "intro": "Queman mucha grasa con bajo impacto y te dejan controlar la resistencia, el tiempo y la intensidad.",
 "itens": [
   {"nome": "Elíptica", "img": 190,
    "onde": "Gimnasio", "gasto": "~300 calorías en 30 minutos",
    "plano": "Semana 1-2: 20 minutos con resistencia ligera. · Semana 3-4: 30 minutos, subiendo la resistencia. · Después: 40 minutos alternando 2 minutos fuerte + 3 minutos ligero.",
    "dica": "Mueve brazos y piernas al mismo tiempo, con cero impacto. Excelente para quien siente dolor de rodillas al correr."},
   {"nome": "Remadora", "img": 191,
    "onde": "Gimnasio", "gasto": "~300 calorías en 30 minutos",
    "plano": "Semana 1-2: 5 minutos remando + descanso, 3 veces. · Después: de 20 a 30 minutos continuos, enfocándote en la técnica.",
    "dica": "Trabaja casi todos los músculos a la vez. La fuerza viene de las piernas empujando, no solo de los brazos jalando."},
 ]},
{
 "tema": "Pesas en el gimnasio", "tipo": "exercicio",
 "intro": "El músculo quema calorías incluso en reposo. Levantar pesas acelera tu metabolismo y evita que la piel quede flácida.",
 "itens": [
   {"nome": "Rutina de cuerpo completo (principiante)", "img": 192,
    "onde": "Gimnasio", "gasto": "~200 calorías en 30 minutos",
    "plano": "3 veces por semana, 1 ejercicio para cada parte: piernas, espalda, pecho, hombros y abdomen. 3 series de 12. Cada 2 semanas, agrega un poco de peso.",
    "dica": "Al principio, concéntrate en aprender bien el movimiento con poco peso. Pide a un entrenador que te la arme y te corrija — eso previene lesiones."},
   {"nome": "Rutina de piernas y glúteos", "img": 193,
    "onde": "Gimnasio", "gasto": "~250 calorías en 30 minutos",
    "plano": "De 1 a 2 veces por semana: sentadillas, prensa de piernas, extensión de piernas y hip thrust. De 3 a 4 series de 12 a 15.",
    "dica": "Las piernas son los músculos más grandes de tu cuerpo — entrenarlas quema mucha energía y te ayuda a adelgazar más rápido."},
   {"nome": "Rutina de brazos, espalda y pecho", "img": 194,
    "onde": "Gimnasio", "gasto": "~180 calorías en 30 minutos",
    "plano": "De 1 a 2 veces por semana: jalón al pecho, remo, press de banca y press de hombros. 3 series de 12.",
    "dica": "Fortalecer el tren superior mejora tu postura y te da forma mientras la grasa se va."},
 ]},
{
 "tema": "Fuerza en casa (sin equipo)", "tipo": "exercicio",
 "intro": "Sin gimnasio y sin pesas: tu propio cuerpo es la carga. Arma un circuito y gana músculo en casa.",
 "itens": [
   {"nome": "Sentadilla", "img": 195,
    "onde": "Casa", "gasto": "piernas y glúteos",
    "plano": "Semana 1-2: 3 series de 10. · Semana 3-4: 3 series de 15. · Después: sostén un objeto pesado (un garrafón de agua, una mochila) para agregar carga.",
    "dica": "Baja como si te fueras a sentar en una silla, las rodillas en línea con los pies, la espalda recta. Es la reina de los ejercicios de pierna."},
   {"nome": "Lagartija", "img": 196,
    "onde": "Casa", "gasto": "pecho, brazos y core",
    "plano": "Semana 1-2: con las rodillas en el piso, 3 series de 8. · Semana 3-4: 3 series de 12. · Después: con las piernas estiradas.",
    "dica": "Si todavía te cuesta, pon las manos sobre una mesa o una pared. Lo que importa es empezar desde donde puedes."},
   {"nome": "Desplante", "img": 197,
    "onde": "Casa", "gasto": "piernas y equilibrio",
    "plano": "Semana 1-2: 3 series de 8 con cada pierna. · Después: 3 series de 12, y más adelante sosteniendo un peso en las manos.",
    "dica": "Da un paso al frente y dobla las dos rodillas hasta que la de atrás casi toque el piso. Trabaja una pierna a la vez."},
   {"nome": "Plancha y abdominales", "img": 198,
    "onde": "Casa", "gasto": "todo el abdomen",
    "plano": "Mantén la plancha de 20 a 40 segundos, 3 veces, y haz 3 series de 15 abdominales. (Ve el Bono 2 de Pilates para más opciones de core.)",
    "dica": "Fortalecer el abdomen hace tu panza más firme y mejora tu postura. Combínalo con cardio para ver la diferencia."},
   {"nome": "Banda de resistencia", "img": 199,
    "onde": "Casa", "gasto": "todo el cuerpo",
    "plano": "3 series de 12 a 15 en cada movimiento (sentadilla, remo, curl, abducción de pierna). Cambia a una banda más fuerte cuando se vuelva fácil.",
    "dica": "Barata y cabe en una maleta. Reemplaza las pesas del gimnasio en casa y es excelente para tus brazos y tu espalda."},
   {"nome": "Subida al escalón", "img": 200,
    "onde": "Casa", "gasto": "piernas y glúteos",
    "plano": "Semana 1-2: 3 series de 10 con cada pierna. · Después: 3 series de 15, y más adelante sosteniendo un peso.",
    "dica": "Sube y baja de un escalón o una silla firme. Es cardio y fuerza al mismo tiempo, y trabaja fuerte los glúteos."},
 ]},
{
 "tema": "Movimiento en la vida diaria", "tipo": "habito", "img": 201,
 "intro": "No solo tu entrenamiento quema calorías. Estos hábitos suben cuánto quemas durante todo el día, sin apartar tiempo para ello.",
 "itens": [
   {"titulo": "Ponte la meta de 8,000 pasos al día",
    "desc": "Usa tu celular para contarlos. Tener un número que alcanzar te hace caminar muchísimo más sin darte cuenta."},
   {"titulo": "Usa las escaleras en lugar del elevador",
    "desc": "Decisiones pequeñas como esta suman mucha energía quemada al final del día."},
   {"titulo": "Estaciónate más lejos o bájate una parada antes",
    "desc": "Agrega pasos a tu día sin tener que apartar un tiempo especial para caminar."},
   {"titulo": "Levántate cada hora si trabajas sentada",
    "desc": "Quedarte quieta mucho tiempo hace más lento a tu cuerpo. Levántate, estírate y camina un poco."},
   {"titulo": "Camina mientras hablas por teléfono",
    "desc": "Convierte el tiempo que pasas quieta en tiempo en movimiento, sin esfuerzo extra."},
   {"titulo": "Haz el quehacer con energía",
    "desc": "Limpiar, cocinar y ordenar también queman calorías — tómalo como movimiento, no solo como una tarea."},
 ]},
{
 "tema": "Alimentación y porciones", "tipo": "habito", "img": 202,
 "intro": "Ningún entrenamiento compensa comer sin control. Estos hábitos, junto con las recetas de este libro, son los que de verdad hacen que la grasa se vaya.",
 "itens": [
   {"titulo": "Incluye proteína en cada comida",
    "desc": "Huevo, pollo, pescado, carne magra o frijoles. Es el nutriente que más te llena y protege tu músculo mientras pierdes grasa."},
   {"titulo": "Empieza el plato por la ensalada y las verduras",
    "desc": "Llenan el estómago con pocas calorías, así comes menos de lo demás sin pasar hambre."},
   {"titulo": "Usa platos más chicos y sírvete una sola vez",
    "desc": "Decide la porción antes de comer. La misma comida se ve como más en un plato chico y te sientes satisfecha con menos."},
   {"titulo": "No tomes tus calorías",
    "desc": "El refresco y el jugo de caja son azúcar pura y no te llenan. Prefiere agua, té o los jugos detox de este libro."},
   {"titulo": "No comas directo del paquete",
    "desc": "Sírvete una porción en un tazón. Comiendo del paquete pierdes la cuenta y comes mucho más de lo que necesitas."},
   {"titulo": "Come despacio y mastica bien",
    "desc": "Tu cerebro tarda unos 20 minutos en avisarte que ya estás satisfecha. Comer rápido te hace comer de más."},
   {"titulo": "No te saltes comidas",
    "desc": "El hambre acumulada lleva a excederte en la siguiente comida. Comer con horario evita perder el control."},
   {"titulo": "Ten colaciones saludables listas",
    "desc": "Fruta, yogur natural o un puñado de nueces te salvan del hambre de emergencia sin caer en la comida chatarra."},
 ]},
{
 "tema": "Agua, sueño y descanso", "tipo": "habito", "img": 203,
 "intro": "Es durante el descanso cuando tu cuerpo cambia. Dormir mal y vivir deshidratada sabotea cualquier dieta.",
 "itens": [
   {"titulo": "Toma por lo menos 2 litros de agua al día",
    "desc": "Tu cuerpo confunde la sed con el hambre. Bien hidratada, picas menos y tu metabolismo funciona mejor."},
   {"titulo": "Empieza tu día con un vaso de agua",
    "desc": "Después de horas de sueño, tu cuerpo despierta deshidratado. El agua despierta tu sistema."},
   {"titulo": "Duerme de 7 a 8 horas por noche",
    "desc": "Las malas noches aumentan tu hambre y tu antojo de dulce del día siguiente. Dormir bien también te ayuda a bajar de peso."},
   {"titulo": "Tómate un té de manzanilla en la noche (Receta 147)",
    "desc": "Te ayuda a relajarte y a conciliar el sueño, mejorando tu descanso y tu control sobre el apetito."},
   {"titulo": "Descansa por lo menos un día a la semana",
    "desc": "El músculo crece y tu cuerpo se recupera durante el descanso. Entrenar todos los días sin parar estorba tus resultados."},
   {"titulo": "Estírate al despertar y después de entrenar",
    "desc": "Mejora tu flexibilidad, previene el dolor muscular y prepara tu cuerpo para moverse más durante el día."},
 ]},
]
