# -*- coding: utf-8 -*-
"""BÔNUS 3 — 50 HÁBITOS E EXERCÍCIOS. INGLÊS (mercado US).

Tradução literal de `exercicios_habitos.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "you", DISTÂNCIA EM MILHAS (2 km = 1.2 mi · 3 km = 2 mi ·
4 km = 2.5 mi · 5 km = 3 mi) e volume de água em QUARTS (2 L ≈ 2 quarts).
⛔ O campo `prompt` NÃO é replicado aqui, igual ao DE: a foto é a mesma do PT
(fotos 171-203). O campo `img` FICA — é ele que aponta para o arquivo.
50 itens: 30 EXERCÍCIOS reais com progressão + 20 HÁBITOS úteis. Numeração 1..50.
"""

TEMAS = [
{
 "tema": "Walking and Running", "tipo": "exercicio",
 "intro": "The simplest and cheapest way to burn fat — on the street, in the park or on the treadmill.",
 "itens": [
  {"nome": "Walking", "img": 171, "onde": "Street, park or treadmill", "gasto": "~150 calories in 30 minutes",
   "plano": "Week 1-2: 1.2 miles at a comfortable pace, 4 to 5 times a week. · Week 3-4: 2 miles, picking up the pace. · Week 5-6: 2.5 miles, with hills or a 3% incline on the treadmill. · Week 7+: 3 miles or 45 minutes at a strong pace.",
   "dica": "Keep a pace where you can still talk, but with effort. On the treadmill, use a slight incline to burn more without running."},
  {"nome": "Power Walking", "img": 172, "onde": "Street or treadmill", "gasto": "~200 calories in 30 minutes",
   "plano": "Once you are comfortable with 3 miles, alternate 3 minutes at a strong pace + 2 minutes normal, for 30 to 40 minutes. Slowly increase the fast stretches.",
   "dica": "Pump your arms bent at 90 degrees and take firm steps. It burns almost as much as a jog, with no impact on your knees."},
  {"nome": "Jogging (Walk-Run Method)", "img": 173, "onde": "Street, park or treadmill", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 1 minute of jogging + 2 minutes of walking, for 20 minutes. · Week 3-4: 2 minutes jogging + 1 minute. · Week 5-6: 3 minutes jogging + 1 minute. · Then: shorten the breaks until you run without stopping.",
   "dica": "Take the jog slowly — if you run out of breath, slow down. That is how your body learns to run without suffering."},
  {"nome": "Continuous Running", "img": 174, "onde": "Street, park or treadmill", "gasto": "~300 calories in 30 minutes",
   "plano": "When you can run 20 minutes without stopping, add 5 minutes a week until you reach 40-45 minutes. Once a week, do a faster stretch.",
   "dica": "A good pair of shoes makes all the difference for your knees. Run at a pace where you can breathe through your nose most of the time."},
 ],
},
{
 "tema": "Cycling", "tipo": "exercicio",
 "intro": "It burns a lot of fat and goes easy on your knees — ideal for anyone carrying extra weight.",
 "itens": [
  {"nome": "Outdoor Cycling", "img": 175, "onde": "Street, bike path or park", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes on flat ground. · Week 3-4: 30 minutes, with small hills. · Week 5+: 40 to 60 minutes, varying the pace.",
   "dica": "Adjust the saddle: your leg should be almost straight with the pedal at the bottom. That protects your knee and lets you ride longer."},
  {"nome": "Stationary Bike", "img": 176, "onde": "Home or gym", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes on light resistance. · Week 3-4: 30 minutes, raising the resistance. · Then: 40 minutes alternating 2 minutes hard + 3 minutes light.",
   "dica": "Perfect for rainy days. Raise the resistance little by little so you are not pedaling 'into thin air'."},
  {"nome": "Spinning", "img": 177, "onde": "Gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Start with 1 class a week and build up to 2 or 3. Follow the instructor, but respect your own limit on the resistance.",
   "dica": "One of the classes that burns the most calories. Drink water during it and start with lower resistance — build up at your own pace."},
 ],
},
{
 "tema": "Swimming and Water Exercise", "tipo": "exercicio",
 "intro": "The water holds your body weight, so there is almost no impact — great for anyone with joint pain.",
 "itens": [
  {"nome": "Swimming", "img": 178, "onde": "Pool", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: swim 20 minutes with breaks at the wall. · Week 3-4: shorten the breaks, reach 30 minutes. · Then: 40 continuous minutes, varying the strokes.",
   "dica": "It works your whole body without overloading your knees and your spine. One or two lessons help a lot with your breathing."},
  {"nome": "Water Aerobics", "img": 179, "onde": "Pool", "gasto": "~200 calories in 30 minutes",
   "plano": "1 to 3 classes a week. The intensity goes up as you push the movements harder against the water.",
   "dica": "Done with energy, it burns plenty and strengthens your legs with zero impact. Excellent for anyone carrying a lot of extra weight."},
 ],
},
{
 "tema": "Interval Training (Fast Burn)", "tipo": "exercicio",
 "intro": "Little time, big results: it alternates hard effort with a short rest. It burns fat during and for hours afterward.",
 "itens": [
  {"nome": "Jump Rope", "img": 180, "onde": "Home, yard or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds jumping + 1 minute rest, for 10 minutes. · Week 3-4: 1 minute + 1 minute, for 15 minutes. · Then: 2 minutes + 1 minute, for 20 minutes.",
   "dica": "One of the biggest burns per minute, and the rope is very cheap. Jump low, just enough for the rope to pass."},
  {"nome": "HIIT (Tabata)", "img": 181, "onde": "Home or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "4 exercises (jumping jacks, squats, running in place, plank): 20 seconds hard + 10 seconds rest on each, 4 rounds. Start with 10 minutes and build up to 20.",
   "dica": "Short and intense. Your body keeps burning fat for hours afterward. 2 to 3 times a week is already enough for results."},
  {"nome": "Stair Climbing", "img": 182, "onde": "Building, plaza or stair machine", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: go up and down for 5 minutes, rest, repeat 3 times. · Then: blocks of 8 to 10 minutes. Always come down slowly to spare your knees.",
   "dica": "It works your legs and your glutes hard while burning fat. Use the handrail to come down safely."},
  {"nome": "Jumping Jacks", "img": 183, "onde": "Home or gym", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds + 30 seconds rest, 8 rounds. · Week 3-4: 45 seconds + 20 seconds. · Then: 1 minute + 20 seconds, 10 rounds.",
   "dica": "A great warm-up and a burn at the same time. Open your arms and legs together, at a steady rhythm."},
  {"nome": "Burpees", "img": 184, "onde": "Home or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Week 1-2: 5 burpees, rest, 4 rounds (without the jump if you need to). · Then: 8 to 10 per round, with the jump.",
   "dica": "Squat, put your hands down, throw your legs back, come back and jump. It is intense and works your whole body — go at your own pace."},
  {"nome": "Running in Place (High Knees)", "img": 185, "onde": "Home", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds + 30 seconds rest, 8 times. · Then: 1 minute + 30 seconds, 10 times.",
   "dica": "Run in place lifting your knees high. It fits in any little corner, without leaving home."},
 ],
},
{
 "tema": "Classes and Dance", "tipo": "exercicio",
 "intro": "People who enjoy it do not quit. They burn a lot of fat without feeling like a sacrifice.",
 "itens": [
  {"nome": "Dance (Zumba, Dance Fitness)", "img": 186, "onde": "Home or gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Start with 20 minutes following videos or a class and build up to 45-60 minutes. 3 to 5 times a week.",
   "dica": "It does not even feel like exercise. Pick songs you love and do not stop moving — the sweat comes on its own."},
  {"nome": "Boxing / Muay Thai", "img": 187, "onde": "Gym or a bag at home", "gasto": "~350 calories in 30 minutes",
   "plano": "1 class a week up to 3; or 3 rounds of 2 minutes on the bag, adding rounds little by little.",
   "dica": "It releases stress and burns a lot. The technique comes with the classes — you do not need to arrive knowing it."},
  {"nome": "Step Class", "img": 188, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "1 class a week up to 3, following the choreography on the platform.",
   "dica": "You step up and down from a platform in time with the music. It works your legs and your stamina hard."},
  {"nome": "Mini Trampoline (Rebounding)", "img": 189, "onde": "Gym or home", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 15 minutes. · Then: 30 to 40 minutes of class.",
   "dica": "Fun and low impact on your joints. Keep your abs firm to hold your balance."},
 ],
},
{
 "tema": "Gym Cardio Machines", "tipo": "exercicio",
 "intro": "They burn a lot of fat with low impact and let you control resistance, time and intensity.",
 "itens": [
  {"nome": "Elliptical (Cross-Trainer)", "img": 190, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes on light resistance. · Week 3-4: 30 minutes, raising the resistance. · Then: 40 minutes alternating 2 minutes hard + 3 minutes light.",
   "dica": "It moves your arms and legs at the same time, with zero impact. Great for anyone whose knees hurt when running."},
  {"nome": "Rowing Machine", "img": 191, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 5 minutes rowing + rest, 3 times. · Then: 20 to 30 continuous minutes, focusing on your technique.",
   "dica": "It works almost every muscle at once. The power comes from your legs pushing, not just your arms pulling."},
 ],
},
{
 "tema": "Weight Training at the Gym", "tipo": "exercicio",
 "intro": "Muscle burns calories even at rest. Lifting speeds up your metabolism and stops your skin from going loose.",
 "itens": [
  {"nome": "Full Body Workout (Beginner)", "img": 192, "onde": "Gym", "gasto": "~200 calories in 30 minutes",
   "plano": "3 times a week, 1 exercise for each part: legs, back, chest, shoulders and abs. 3 sets of 12. Every 2 weeks, add a little weight.",
   "dica": "At the start, focus on learning the right movement with light weight. Ask a trainer to set it up and correct you — it prevents injury."},
  {"nome": "Leg and Glute Workout", "img": 193, "onde": "Gym", "gasto": "~250 calories in 30 minutes",
   "plano": "1 to 2 times a week: squats, leg press, leg extension and hip thrust. 3 to 4 sets of 12 to 15.",
   "dica": "Your legs are the biggest muscles in your body — training them burns a lot of energy and helps you slim down faster."},
  {"nome": "Arm, Back and Chest Workout", "img": 194, "onde": "Gym", "gasto": "~180 calories in 30 minutes",
   "plano": "1 to 2 times a week: lat pulldown, row, bench press and shoulder press. 3 sets of 12.",
   "dica": "Strengthening your upper body improves your posture and shapes you while the fat comes off."},
 ],
},
{
 "tema": "Strength at Home (No Equipment)", "tipo": "exercicio",
 "intro": "No gym and no weights: your own body is the load. Build a circuit and gain muscle at home.",
 "itens": [
  {"nome": "Squat", "img": 195, "onde": "Home", "gasto": "legs and glutes",
   "plano": "Week 1-2: 3 sets of 10. · Week 3-4: 3 sets of 15. · Then: hold a heavy object (a water jug, a backpack) to add load.",
   "dica": "Go down as if you were sitting in a chair, knees in line with your feet, back straight. It is the king of leg exercises."},
  {"nome": "Push-Up", "img": 196, "onde": "Home", "gasto": "chest, arms and core",
   "plano": "Week 1-2: with your knees on the floor, 3 sets of 8. · Week 3-4: 3 sets of 12. · Then: with your legs straight.",
   "dica": "If it is still hard, put your hands on a table or a wall. What matters is starting from where you can."},
  {"nome": "Lunge", "img": 197, "onde": "Home", "gasto": "legs and balance",
   "plano": "Week 1-2: 3 sets of 8 with each leg. · Then: 3 sets of 12, and after that holding a weight in your hands.",
   "dica": "Take a step forward and bend both knees until the back one almost touches the floor. It works one leg at a time."},
  {"nome": "Plank and Crunches", "img": 198, "onde": "Home", "gasto": "the whole abdomen",
   "plano": "Hold the plank 20 to 40 seconds, 3 times, and do 3 sets of 15 crunches. (See Bonus 2 on Pilates for more core options.)",
   "dica": "Strengthening your abs makes your belly firmer and improves your posture. Combine it with cardio to see the difference."},
  {"nome": "Resistance Band", "img": 199, "onde": "Home", "gasto": "the whole body",
   "plano": "3 sets of 12 to 15 on each movement (squat, row, curl, leg abduction). Move to a stronger band when it gets easy.",
   "dica": "Cheap and it fits in a suitcase. It replaces gym weights at home and is great for your arms and your back."},
  {"nome": "Step-Up", "img": 200, "onde": "Home", "gasto": "legs and glutes",
   "plano": "Week 1-2: 3 sets of 10 with each leg. · Then: 3 sets of 15, and after that holding a weight.",
   "dica": "Step up and down from a step or a sturdy chair. It is cardio and strength at the same time, and it works your glutes hard."},
 ],
},
{
 "tema": "Movement in Everyday Life", "tipo": "habito", "img": 201,
 "intro": "It is not only your workout that burns calories. These habits raise how much you burn all day long, without setting aside time for it.",
 "itens": [
  {"titulo": "Set a goal of 8,000 steps a day", "desc": "Use your phone to count them. Having a number to hit makes you walk a lot more without noticing."},
  {"titulo": "Take the stairs instead of the elevator", "desc": "Small choices like this add up to a lot of energy burned by the end of the day."},
  {"titulo": "Park further away or get off one stop early", "desc": "Add steps to your day without having to set aside special time to walk."},
  {"titulo": "Stand up every hour if you work sitting down", "desc": "Staying still for a long time slows your body down. Stand up, stretch and walk a little."},
  {"titulo": "Walk while you are on the phone", "desc": "Turn time spent standing still into time spent moving, with no extra effort."},
  {"titulo": "Do your housework with energy", "desc": "Cleaning, cooking and tidying up also burn calories — treat it as movement, not just a chore."},
 ],
},
{
 "tema": "Food and Portions", "tipo": "habito", "img": 202,
 "intro": "No workout makes up for eating out of control. These habits, together with the recipes in this book, are what really make the fat come off.",
 "itens": [
  {"titulo": "Have protein at every meal", "desc": "Egg, chicken, fish, lean meat or beans. It is the nutrient that fills you up most and protects your muscle while you lose fat."},
  {"titulo": "Start your plate with the salad and the vegetables", "desc": "They fill your stomach with few calories, so you eat less of the rest without going hungry."},
  {"titulo": "Use smaller plates and serve yourself only once", "desc": "Decide the portion before you eat. The same food looks like more on a small plate and you feel satisfied with less."},
  {"titulo": "Do not drink your calories", "desc": "Soda and boxed juice are pure sugar and do not fill you up. Go for water, tea or the detox juices in this book."},
  {"titulo": "Do not eat straight from the package", "desc": "Portion it into a bowl. Eating from the package, you lose track and eat far more than you need."},
  {"titulo": "Eat slowly and chew well", "desc": "Your brain takes about 20 minutes to tell you that you are full. Eating fast makes you overeat."},
  {"titulo": "Do not skip meals", "desc": "Built-up hunger leads to overdoing it at the next meal. Eating on schedule prevents losing control."},
  {"titulo": "Keep healthy snacks ready", "desc": "Fruit, plain yogurt or a handful of nuts save you from emergency hunger without falling into junk food."},
 ],
},
{
 "tema": "Water, Sleep and Rest", "tipo": "habito", "img": 203,
 "intro": "It is during rest that your body changes. Sleeping badly and living dehydrated sabotages any diet.",
 "itens": [
  {"titulo": "Drink at least 2 quarts of water a day", "desc": "Your body confuses thirst with hunger. Well hydrated, you snack less and your metabolism works better."},
  {"titulo": "Start your day with a glass of water", "desc": "After hours of sleep, your body wakes up dehydrated. Water wakes your system up."},
  {"titulo": "Sleep 7 to 8 hours a night", "desc": "Bad nights increase your hunger and your craving for sweets the next day. Sleeping well also helps you lose weight."},
  {"titulo": "Have a chamomile tea at night (Recipe 147)", "desc": "It helps you relax and fall asleep, improving your rest and your control over your appetite."},
  {"titulo": "Rest at least one day a week", "desc": "Muscle grows and your body recovers during rest. Training every single day without stopping gets in the way of your results."},
  {"titulo": "Stretch when you wake up and after your workouts", "desc": "It improves your flexibility, prevents soreness and gets your body ready to move more during the day."},
 ],
},
]
