# -*- coding: utf-8 -*-
"""BÔNUS 3 — 50 GEWOHNHEITEN UND ÜBUNGEN. ALEMÃO.

Tradução literal de `exercicios_habitos.py`. Convenções em GLOSSARIO-TRADUCAO.md.
50 itens: 30 EXERCÍCIOS reais com progressão + 20 HÁBITOS úteis. Numeração 1..50.
⛔ O campo `prompt` não é replicado: as fotos são as mesmas do PT (171-203).
Estrutura idêntica ao PT:
  tema exercicio: {tema, intro, tipo:'exercicio', itens:[{nome,onde,gasto,plano,dica,img}]}
  tema habito:    {tema, intro, tipo:'habito', img, itens:[{titulo,desc}]}
"""

TEMAS = [
{
 "tema": "Gehen und Laufen", "tipo": "exercicio",
 "intro": "Die einfachste und günstigste Art, Fett zu verbrennen — auf der Straße, im Park oder auf dem Laufband.",
 "itens": [
  {"nome": "Gehen", "img": 171, "onde": "Straße, Park oder Laufband", "gasto": "~150 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 2 km in angenehmem Tempo, 4- bis 5-mal die Woche. · Woche 3-4: 3 km, mit schnellerem Schritt. · Woche 5-6: 4 km, mit Steigungen oder 3 % Neigung auf dem Laufband. · Ab Woche 7: 5 km oder 45 Minuten in zügigem Tempo.",
   "dica": "Halte ein Tempo, bei dem du dich noch unterhalten kannst, aber mit Anstrengung. Nutze auf dem Laufband eine leichte Neigung, um mehr zu verbrauchen, ohne zu laufen."},
  {"nome": "Zügiges Gehen (Power Walk)", "img": 172, "onde": "Straße oder Laufband", "gasto": "~200 Kalorien in 30 Minuten",
   "plano": "Wenn du die 5 km sicher schaffst, wechsle 3 Minuten in zügigem Tempo mit 2 Minuten normal ab, 30 bis 40 Minuten lang. Verlängere die schnellen Abschnitte nach und nach.",
   "dica": "Bewege die im rechten Winkel angewinkelten Arme kräftig mit und mach feste Schritte. Das verbraucht fast so viel wie leichtes Joggen, ohne die Knie zu belasten."},
  {"nome": "Leichtes Joggen (Geh-Lauf-Methode)", "img": 173, "onde": "Straße, Park oder Laufband", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 1 Minute joggen + 2 Minuten gehen, 20 Minuten lang. · Woche 3-4: 2 Minuten joggen + 1 Minute. · Woche 5-6: 3 Minuten joggen + 1 Minute. · Danach: verkürze die Pausen, bis du durchläufst.",
   "dica": "Jogge langsam — wenn dir die Luft ausgeht, werde langsamer. So lernt der Körper zu laufen, ohne zu leiden."},
  {"nome": "Dauerlauf", "img": 174, "onde": "Straße, Park oder Laufband", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Wenn du 20 Minuten am Stück laufen kannst, steigere jede Woche um 5 Minuten, bis du 40 bis 45 Minuten erreichst. Einmal die Woche baust du einen schnelleren Abschnitt ein.",
   "dica": "Gute Laufschuhe machen für die Knie den ganzen Unterschied. Lauf in einem Tempo, in dem du die meiste Zeit durch die Nase atmen kannst."},
 ],
},
{
 "tema": "Radfahren", "tipo": "exercicio",
 "intro": "Verbrennt viel Fett und ist schonend für die Knie — ideal für alle mit Übergewicht.",
 "itens": [
  {"nome": "Fahrrad im Freien", "img": 175, "onde": "Straße, Radweg oder Park", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 20 Minuten in flachem Gelände. · Woche 3-4: 30 Minuten, mit kleinen Steigungen. · Ab Woche 5: 40 bis 60 Minuten, mit wechselndem Tempo.",
   "dica": "Stelle den Sattel richtig ein: Das Bein ist am unteren Pedal fast gestreckt. Das schont das Knie und du kannst länger fahren."},
  {"nome": "Heimtrainer", "img": 176, "onde": "Zu Hause oder im Fitnessstudio", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 20 Minuten bei leichtem Widerstand. · Woche 3-4: 30 Minuten, mit steigendem Widerstand. · Danach: 40 Minuten im Wechsel aus 2 Minuten schwer + 3 Minuten leicht.",
   "dica": "Perfekt für Regentage. Erhöhe den Widerstand nach und nach, damit du nicht „ins Leere“ trittst."},
  {"nome": "Spinning", "img": 177, "onde": "Fitnessstudio", "gasto": "~350 Kalorien in 30 Minuten",
   "plano": "Fang mit 1 Kurs pro Woche an und geh auf 2 oder 3. Folge dem Trainer, aber achte beim Widerstand auf deine eigene Grenze.",
   "dica": "Einer der Kurse, die am meisten Kalorien verbrennen. Trink währenddessen Wasser und fang mit weniger Widerstand an — steigere dich in deinem Tempo."},
 ],
},
{
 "tema": "Schwimmen und Wassergymnastik", "tipo": "exercicio",
 "intro": "Das Wasser trägt das Körpergewicht, es gibt also fast keine Belastung — hervorragend für alle mit Gelenkschmerzen.",
 "itens": [
  {"nome": "Schwimmen", "img": 178, "onde": "Schwimmbad", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 20 Minuten schwimmen, mit Pausen am Beckenrand. · Woche 3-4: kürzere Pausen, komm auf 30 Minuten. · Danach: 40 Minuten am Stück, mit wechselnden Stilen.",
   "dica": "Trainiert den ganzen Körper, ohne Knie und Wirbelsäule zu überlasten. Ein oder zwei Kursstunden helfen sehr bei der Atmung."},
  {"nome": "Wassergymnastik", "img": 179, "onde": "Schwimmbad", "gasto": "~200 Kalorien in 30 Minuten",
   "plano": "1 bis 3 Kurse pro Woche. Die Intensität steigt, je kräftiger du die Bewegungen gegen das Wasser ausführst.",
   "dica": "Mit Schwung ausgeführt verbrennt sie ordentlich und kräftigt die Beine ganz ohne Belastung. Ausgezeichnet bei starkem Übergewicht."},
 ],
},
{
 "tema": "Intervalltraining (schnelles Verbrennen)", "tipo": "exercicio",
 "intro": "Wenig Zeit, viel Wirkung: Wechsel aus starker Anstrengung und kurzer Pause. Verbrennt Fett währenddessen und noch Stunden danach.",
 "itens": [
  {"nome": "Seilspringen", "img": 180, "onde": "Zu Hause, im Hof oder im Fitnessstudio", "gasto": "~350 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 30 Sekunden springen + 1 Minute Pause, 10 Minuten lang. · Woche 3-4: 1 Minute + 1 Minute, 15 Minuten lang. · Danach: 2 Minuten + 1 Minute, 20 Minuten lang.",
   "dica": "Eine der höchsten Verbrennungen pro Minute, und das Seil kostet fast nichts. Spring niedrig, nur so hoch, dass das Seil durchkommt."},
  {"nome": "HIIT (Tabata)", "img": 181, "onde": "Zu Hause oder im Fitnessstudio", "gasto": "~350 Kalorien in 30 Minuten",
   "plano": "4 Übungen (Hampelmann, Kniebeuge, Laufen auf der Stelle, Plank): je 20 Sekunden kräftig + 10 Sekunden Pause, 4 Runden. Fang mit 10 Minuten an und geh auf 20.",
   "dica": "Kurz und intensiv. Der Körper verbrennt noch Stunden danach Fett. 2- bis 3-mal pro Woche bringt schon Ergebnisse."},
  {"nome": "Treppensteigen", "img": 182, "onde": "Haus, Platz oder Stepper", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 5 Minuten hoch und runter, Pause, 3 Mal wiederholen. · Danach: Blöcke von 8 bis 10 Minuten. Geh immer langsam herunter, um das Knie zu schonen.",
   "dica": "Trainiert Beine und Po stark und verbrennt dabei Fett. Nutze zum Heruntergehen sicherheitshalber das Geländer."},
  {"nome": "Hampelmann (Jumping Jack)", "img": 183, "onde": "Zu Hause oder im Fitnessstudio", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 30 Sekunden + 30 Sekunden Pause, 8 Runden. · Woche 3-4: 45 Sekunden + 20 Sekunden. · Danach: 1 Minute + 20 Sekunden, 10 Runden.",
   "dica": "Hervorragendes Aufwärmen und Verbrennen zugleich. Öffne Arme und Beine gleichzeitig, in gleichmäßigem Rhythmus."},
  {"nome": "Burpee", "img": 184, "onde": "Zu Hause oder im Fitnessstudio", "gasto": "~350 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 5 Burpees, Pause, 4 Runden (ohne Sprung, wenn nötig). · Danach: 8 bis 10 pro Runde, mit Sprung.",
   "dica": "In die Hocke, Hände aufstützen, Beine nach hinten werfen, zurückkommen und springen. Er ist intensiv und trainiert den ganzen Körper — geh in deinem Tempo."},
  {"nome": "Laufen auf der Stelle (hohe Knie)", "img": 185, "onde": "Zu Hause", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 30 Sekunden + 30 Sekunden Pause, 8 Mal. · Danach: 1 Minute + 30 Sekunden, 10 Mal.",
   "dica": "Lauf auf der Stelle und hebe die Knie hoch. Das passt in jede Ecke, ganz ohne das Haus zu verlassen."},
 ],
},
{
 "tema": "Kurse und Tanz", "tipo": "exercicio",
 "intro": "Wer Spaß hat, hört nicht auf. Diese Kurse verbrennen viel Fett, ohne sich nach Verzicht anzufühlen.",
 "itens": [
  {"nome": "Tanzen (Zumba, Tanzfitness)", "img": 186, "onde": "Zu Hause oder im Fitnessstudio", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Fang mit 20 Minuten nach Videos oder im Kurs an und komm auf 45 bis 60 Minuten. 3- bis 5-mal pro Woche.",
   "dica": "Fühlt sich gar nicht nach Sport an. Wähle Musik, die du liebst, und hör nicht auf, dich zu bewegen — der Schweiß kommt von allein."},
  {"nome": "Boxen / Muay Thai", "img": 187, "onde": "Fitnessstudio oder Boxsack zu Hause", "gasto": "~350 Kalorien in 30 Minuten",
   "plano": "1 Kurs pro Woche bis zu 3; oder 3 Runden à 2 Minuten am Sack, mit nach und nach mehr Runden.",
   "dica": "Baut Stress ab und verbrennt sehr viel. Die Technik kommt mit den Kursen — du musst nichts können, wenn du anfängst."},
  {"nome": "Step-Aerobic", "img": 188, "onde": "Fitnessstudio", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "1 Kurs pro Woche bis zu 3, und folge dabei der Choreografie auf dem Stepbrett.",
   "dica": "Du steigst im Takt der Musik auf ein Brett hoch und wieder herunter. Das trainiert Beine und Ausdauer stark."},
  {"nome": "Trampolin (Jumping Fitness)", "img": 189, "onde": "Fitnessstudio oder zu Hause", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 15 Minuten. · Danach: 30 bis 40 Minuten Kurs.",
   "dica": "Macht Spaß und belastet die Gelenke wenig. Halte den Bauch fest angespannt, um das Gleichgewicht zu halten."},
 ],
},
{
 "tema": "Ausdauergeräte im Fitnessstudio", "tipo": "exercicio",
 "intro": "Sie verbrennen viel Fett bei geringer Belastung und lassen dich Widerstand, Zeit und Intensität selbst steuern.",
 "itens": [
  {"nome": "Crosstrainer", "img": 190, "onde": "Fitnessstudio", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 20 Minuten bei leichtem Widerstand. · Woche 3-4: 30 Minuten, mit steigendem Widerstand. · Danach: 40 Minuten im Wechsel aus 2 Minuten kräftig + 3 Minuten leicht.",
   "dica": "Bewegt Arme und Beine gleichzeitig, ganz ohne Belastung. Hervorragend für alle, denen beim Laufen die Knie wehtun."},
  {"nome": "Rudergerät", "img": 191, "onde": "Fitnessstudio", "gasto": "~300 Kalorien in 30 Minuten",
   "plano": "Woche 1-2: 5 Minuten rudern + Pause, 3 Mal. · Danach: 20 bis 30 Minuten am Stück, mit Blick auf die Technik.",
   "dica": "Trainiert fast alle Muskeln auf einmal. Die Kraft kommt aus den Beinen, die drücken, nicht nur aus den Armen, die ziehen."},
 ],
},
{
 "tema": "Krafttraining im Fitnessstudio", "tipo": "exercicio",
 "intro": "Muskeln verbrennen Kalorien sogar im Ruhezustand. Krafttraining bringt den Stoffwechsel in Schwung und verhindert schlaffe Haut.",
 "itens": [
  {"nome": "Ganzkörpertraining (Anfänger)", "img": 192, "onde": "Fitnessstudio", "gasto": "~200 Kalorien in 30 Minuten",
   "plano": "3-mal pro Woche, je 1 Übung für jeden Bereich: Beine, Rücken, Brust, Schulter und Bauch. 3 Sätze à 12. Erhöhe alle 2 Wochen das Gewicht ein wenig.",
   "dica": "Konzentriere dich am Anfang darauf, die richtige Bewegung mit leichtem Gewicht zu lernen. Bitte den Trainer, den Plan zu erstellen und dich zu korrigieren — das verhindert Verletzungen."},
  {"nome": "Bein- und Po-Training", "img": 193, "onde": "Fitnessstudio", "gasto": "~250 Kalorien in 30 Minuten",
   "plano": "1- bis 2-mal pro Woche: Kniebeuge, Beinpresse, Beinstrecker und Hüftheben. 3 bis 4 Sätze à 12 bis 15.",
   "dica": "Die Beine sind die größten Muskeln des Körpers — sie zu trainieren verbraucht viel Energie und hilft, schneller abzunehmen."},
  {"nome": "Arm-, Rücken- und Brusttraining", "img": 194, "onde": "Fitnessstudio", "gasto": "~180 Kalorien in 30 Minuten",
   "plano": "1- bis 2-mal pro Woche: Latzug, Rudern, Bankdrücken und Schulterdrücken. 3 Sätze à 12.",
   "dica": "Den Oberkörper zu kräftigen verbessert die Haltung und formt den Körper, während das Fett verschwindet."},
 ],
},
{
 "tema": "Krafttraining zu Hause (ohne Geräte)", "tipo": "exercicio",
 "intro": "Ohne Fitnessstudio und ohne Gewichte: Der eigene Körper ist die Last. Bau dir einen Zirkel und gewinne zu Hause Muskeln.",
 "itens": [
  {"nome": "Kniebeuge", "img": 195, "onde": "Zu Hause", "gasto": "Beine und Po",
   "plano": "Woche 1-2: 3 Sätze à 10. · Woche 3-4: 3 Sätze à 15. · Danach: halte einen schweren Gegenstand (Wasserkanister, Rucksack), um die Last zu erhöhen.",
   "dica": "Geh nach unten, als würdest du dich auf einen Stuhl setzen, die Knie in Richtung der Füße, der Rücken gerade. Sie ist die Königin der Beinübungen."},
  {"nome": "Liegestütz", "img": 196, "onde": "Zu Hause", "gasto": "Brust, Arme und Körpermitte",
   "plano": "Woche 1-2: mit den Knien auf dem Boden, 3 Sätze à 8. · Woche 3-4: 3 Sätze à 12. · Danach: mit gestreckten Beinen.",
   "dica": "Wenn es noch zu schwer ist, stütze die Hände auf einem Tisch oder an der Wand ab. Wichtig ist, dort anzufangen, wo du stehst."},
  {"nome": "Ausfallschritt", "img": 197, "onde": "Zu Hause", "gasto": "Beine und Gleichgewicht",
   "plano": "Woche 1-2: 3 Sätze à 8 mit jedem Bein. · Danach: 3 Sätze à 12, und später mit einem Gewicht in den Händen.",
   "dica": "Mach einen Schritt nach vorn und beuge beide Knie, bis das hintere fast den Boden berührt. Das trainiert ein Bein nach dem anderen."},
  {"nome": "Plank und Crunch", "img": 198, "onde": "Zu Hause", "gasto": "der ganze Bauch",
   "plano": "Halte den Plank 20 bis 40 Sekunden, 3 Mal, und mach 3 Sätze à 15 Crunches. (Sieh dir Bonus 2 mit Pilates für mehr Übungen für die Körpermitte an.)",
   "dica": "Den Bauch zu kräftigen macht ihn fester und verbessert die Haltung. Kombiniere das mit Ausdauertraining, um den Unterschied zu sehen."},
  {"nome": "Fitnessband", "img": 199, "onde": "Zu Hause", "gasto": "der ganze Körper",
   "plano": "3 Sätze à 12 bis 15 bei jeder Bewegung (Kniebeuge, Rudern, Bizepscurl, Beine öffnen). Wechsle zu einem stärkeren Band, wenn es leicht wird.",
   "dica": "Günstig und passt in den Koffer. Es ersetzt zu Hause die Gewichte aus dem Studio und ist hervorragend für Arme und Rücken."},
  {"nome": "Step-ups auf die Bank", "img": 200, "onde": "Zu Hause", "gasto": "Beine und Po",
   "plano": "Woche 1-2: 3 Sätze à 10 mit jedem Bein. · Danach: 3 Sätze à 15, und später mit Gewicht.",
   "dica": "Steig auf eine Stufe oder einen festen Stuhl hoch und wieder herunter. Das ist Ausdauer und Kraft zugleich und trainiert den Po sehr stark."},
 ],
},
{
 "tema": "Bewegung im Alltag", "tipo": "habito", "img": 201,
 "intro": "Nicht nur das Training verbrennt Kalorien. Diese Gewohnheiten erhöhen deinen Verbrauch den ganzen Tag, ohne dass du dir dafür Zeit nehmen musst.",
 "itens": [
  {"titulo": "Setze dir das Ziel von 8.000 Schritten am Tag", "desc": "Nutze dein Handy zum Zählen. Eine Zahl zu haben, die du erreichen willst, lässt dich viel mehr laufen, ohne dass du es merkst."},
  {"titulo": "Nimm die Treppe statt den Aufzug", "desc": "Solche kleinen Entscheidungen summieren sich am Ende des Tages zu einem ordentlichen Energieverbrauch."},
  {"titulo": "Park weiter weg oder steig eine Haltestelle früher aus", "desc": "So sammelst du Schritte, ohne dir extra Zeit fürs Gehen nehmen zu müssen."},
  {"titulo": "Steh jede Stunde auf, wenn du sitzend arbeitest", "desc": "Lange still zu sitzen bremst den Körper. Steh auf, streck dich und geh ein paar Schritte."},
  {"titulo": "Geh herum, während du telefonierst", "desc": "Mach aus einer stehenden Zeit eine Zeit in Bewegung, ganz ohne zusätzliche Anstrengung."},
  {"titulo": "Erledige die Hausarbeit mit Schwung", "desc": "Putzen, Kochen und Aufräumen verbrennen ebenfalls Kalorien — sieh es als Bewegung, nicht nur als Pflicht."},
 ],
},
{
 "tema": "Ernährung und Portionen", "tipo": "habito", "img": 202,
 "intro": "Kein Training gleicht eine unkontrollierte Ernährung aus. Diese Gewohnheiten sorgen zusammen mit den Rezepten aus dem Buch dafür, dass das Fett wirklich verschwindet.",
 "itens": [
  {"titulo": "Hab bei jeder Mahlzeit Eiweiß dabei", "desc": "Ei, Hähnchen, Fisch, mageres Fleisch oder Bohnen. Es ist der Nährstoff, der am meisten sättigt und den Muskel erhält, während du Fett verlierst."},
  {"titulo": "Fang den Teller mit Salat und Gemüse an", "desc": "Sie füllen den Magen mit wenigen Kalorien, du isst also weniger vom Rest, ohne zu hungern."},
  {"titulo": "Nimm kleinere Teller und nimm dir nur einmal", "desc": "Entscheide über die Portion, bevor du isst. Dieselbe Menge wirkt auf einem kleinen Teller nach mehr, und du bist mit weniger zufrieden."},
  {"titulo": "Trink deine Kalorien nicht", "desc": "Limonade und Saft aus der Packung sind purer Zucker und sättigen nicht. Nimm lieber Wasser, Tee oder die Detox-Säfte aus dem Buch."},
  {"titulo": "Iss nicht direkt aus der Packung", "desc": "Füll dir eine Portion in eine Schüssel. Aus der Packung verlierst du den Überblick und isst viel mehr, als du brauchst."},
  {"titulo": "Iss langsam und kau gut", "desc": "Das Gehirn braucht etwa 20 Minuten, um zu melden, dass du satt bist. Schnell zu essen führt dazu, zu viel zu essen."},
  {"titulo": "Lass keine Mahlzeit aus", "desc": "Angesammelter Hunger führt bei der nächsten Mahlzeit zum Übertreiben. Zu festen Zeiten zu essen verhindert den Kontrollverlust."},
  {"titulo": "Hab gesunde Snacks schon fertig", "desc": "Obst, Naturjoghurt oder eine Handvoll Nüsse retten dich vor dem Notfallhunger, ohne dass du zu Ungesundem greifst."},
 ],
},
{
 "tema": "Wasser, Schlaf und Erholung", "tipo": "habito", "img": 203,
 "intro": "In der Erholung verändert sich der Körper. Schlecht zu schlafen und ständig zu wenig zu trinken sabotiert jede Diät.",
 "itens": [
  {"titulo": "Trink mindestens 2 Liter Wasser am Tag", "desc": "Der Körper verwechselt Durst mit Hunger. Gut versorgt naschst du weniger und der Stoffwechsel arbeitet besser."},
  {"titulo": "Beginne den Tag mit einem Glas Wasser", "desc": "Nach Stunden Schlaf wacht der Körper mit Flüssigkeitsmangel auf. Das Wasser weckt den Organismus."},
  {"titulo": "Schlaf 7 bis 8 Stunden pro Nacht", "desc": "Schlecht durchschlafene Nächte steigern am nächsten Tag den Hunger und die Lust auf Süßes. Gut zu schlafen hilft ebenfalls beim Abnehmen."},
  {"titulo": "Trink abends einen Kamillentee (Rezept 147)", "desc": "Er hilft beim Entspannen und beim Einschlafen und verbessert so die Erholung und die Kontrolle über den Appetit."},
  {"titulo": "Ruh dich mindestens einen Tag pro Woche aus", "desc": "Der Muskel wächst und der Körper erholt sich in der Ruhe. Jeden Tag ohne Pause zu trainieren stört das Ergebnis."},
  {"titulo": "Dehn dich nach dem Aufwachen und nach dem Training", "desc": "Das verbessert die Beweglichkeit, verhindert Schmerzen und bereitet den Körper darauf vor, sich tagsüber mehr zu bewegen."},
 ],
},
]
