# -*- coding: utf-8 -*-
"""BONUS 3 — 50 ABITUDINI ED ESERCIZI. ITALIANO.

Traducao literal de `exercicios_habitos_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md.

⛔⛔ METRICO — e AQUI o EN e' imperial de verdade: `1.2/2/2.5/3 miles` volta
   para `2/3/4/5 km` e `2 quarts` volta para `2 litri`. Os numeros metricos
   vem do pt/de/fr, que ja' os validaram, nunca de milha -> km de volta.
⚠️ `knees in line with your feet` NAO se converte: ali "feet" sao os pes do
   corpo, nao a unidade. O DE confirma (`Füße`).
⛔ 11 temas: 8 de `exercicio` (30 itens) + 3 de `habito` (20 itens) = 50.
   Os temas de habito levam `img` no tema; os de exercicio, em cada item.
"""

TEMAS = [
{
 "tema": "Camminare e correre", "tipo": "exercicio",
 "intro": "Il modo più semplice ed economico di bruciare grasso — per strada, al parco o sul tapis roulant.",
 "itens": [
   {"nome": "Camminata", "img": 171,
    "onde": "Strada, parco o tapis roulant", "gasto": "~150 calorie in 30 minuti",
    "plano": "Settimana 1-2: 2 km a passo comodo, 4-5 volte a settimana. · Settimana 3-4: 3 km, aumentando il passo. · Settimana 5-6: 4 km, con salite o una pendenza del 3% sul tapis roulant. · Settimana 7+: 5 km o 45 minuti a passo sostenuto.",
    "dica": "Tieni un ritmo in cui riesci ancora a parlare, ma con fatica. Sul tapis roulant, usa una leggera pendenza per bruciare di più senza correre."},
   {"nome": "Camminata veloce", "img": 172,
    "onde": "Strada o tapis roulant", "gasto": "~200 calorie in 30 minuti",
    "plano": "Quando ti trovi bene con 5 km, alterna 3 minuti a passo sostenuto + 2 minuti normali, per 30-40 minuti. Aumenta piano piano i tratti veloci.",
    "dica": "Muovi le braccia piegate a 90 gradi e fai passi decisi. Brucia quasi quanto una corsetta, senza impatto sulle ginocchia."},
   {"nome": "Corsetta (metodo cammina-corri)", "img": 173,
    "onde": "Strada, parco o tapis roulant", "gasto": "~250 calorie in 30 minuti",
    "plano": "Settimana 1-2: 1 minuto di corsa + 2 minuti di cammino, per 20 minuti. · Settimana 3-4: 2 minuti di corsa + 1 minuto. · Settimana 5-6: 3 minuti di corsa + 1 minuto. · Poi: accorcia le pause finché non corri senza fermarti.",
    "dica": "Prendi la corsa con calma — se ti manca il fiato, rallenta. È così che il corpo impara a correre senza soffrire."},
   {"nome": "Corsa continua", "img": 174,
    "onde": "Strada, parco o tapis roulant", "gasto": "~300 calorie in 30 minuti",
    "plano": "Quando riesci a correre 20 minuti senza fermarti, aggiungi 5 minuti a settimana finché non arrivi a 40-45 minuti. Una volta a settimana, fai un tratto più veloce.",
    "dica": "Un buon paio di scarpe fa tutta la differenza per le tue ginocchia. Corri a un ritmo in cui riesci a respirare dal naso per la maggior parte del tempo."},
 ]},
{
 "tema": "Ciclismo", "tipo": "exercicio",
 "intro": "Brucia tantissimo grasso ed è delicato con le ginocchia — ideale per chi porta qualche chilo di troppo.",
 "itens": [
   {"nome": "Bici all'aperto", "img": 175,
    "onde": "Strada, pista ciclabile o parco", "gasto": "~250 calorie in 30 minuti",
    "plano": "Settimana 1-2: 20 minuti in pianura. · Settimana 3-4: 30 minuti, con piccole salite. · Settimana 5+: 40-60 minuti, variando il ritmo.",
    "dica": "Regola la sella: la gamba deve essere quasi dritta con il pedale in basso. Questo protegge il ginocchio e ti permette di pedalare più a lungo."},
   {"nome": "Cyclette", "img": 176,
    "onde": "Casa o palestra", "gasto": "~250 calorie in 30 minuti",
    "plano": "Settimana 1-2: 20 minuti a resistenza leggera. · Settimana 3-4: 30 minuti, alzando la resistenza. · Poi: 40 minuti alternando 2 minuti duri + 3 minuti leggeri.",
    "dica": "Perfetta per i giorni di pioggia. Alza la resistenza poco a poco, così non pedali «a vuoto»."},
   {"nome": "Spinning", "img": 177,
    "onde": "Palestra", "gasto": "~350 calorie in 30 minuti",
    "plano": "Inizia con 1 lezione a settimana e arriva a 2 o 3. Segui l'istruttore, ma rispetta il tuo limite sulla resistenza.",
    "dica": "Una delle lezioni che bruciano di più. Bevi acqua durante e inizia con una resistenza più bassa — aumenta al tuo ritmo."},
 ]},
{
 "tema": "Nuoto ed esercizi in acqua", "tipo": "exercicio",
 "intro": "L'acqua sostiene il peso del corpo, quindi l'impatto è quasi nullo — ottimo per chi ha dolori articolari.",
 "itens": [
   {"nome": "Nuoto", "img": 178,
    "onde": "Piscina", "gasto": "~300 calorie in 30 minuti",
    "plano": "Settimana 1-2: nuota 20 minuti con pause al bordo. · Settimana 3-4: accorcia le pause, arriva a 30 minuti. · Poi: 40 minuti continui, variando gli stili.",
    "dica": "Lavora tutto il corpo senza sovraccaricare le ginocchia e la colonna. Una o due lezioni aiutano moltissimo con la respirazione."},
   {"nome": "Acquagym", "img": 179,
    "onde": "Piscina", "gasto": "~200 calorie in 30 minuti",
    "plano": "Da 1 a 3 lezioni a settimana. L'intensità sale man mano che spingi i movimenti con più forza contro l'acqua.",
    "dica": "Fatta con energia, brucia parecchio e rafforza le gambe con zero impatto. Eccellente per chi porta molti chili di troppo."},
 ]},
{
 "tema": "Allenamento a intervalli (brucia veloce)", "tipo": "exercicio",
 "intro": "Poco tempo, grandi risultati: alterna uno sforzo intenso a una pausa breve. Brucia grasso durante e per ore dopo.",
 "itens": [
   {"nome": "Salto con la corda", "img": 180,
    "onde": "Casa, cortile o palestra", "gasto": "~350 calorie in 30 minuti",
    "plano": "Settimana 1-2: 30 secondi di salto + 1 minuto di pausa, per 10 minuti. · Settimana 3-4: 1 minuto + 1 minuto, per 15 minuti. · Poi: 2 minuti + 1 minuto, per 20 minuti.",
    "dica": "Uno dei consumi più alti al minuto, e la corda costa pochissimo. Salta basso, giusto quanto basta perché la corda passi."},
   {"nome": "HIIT (Tabata)", "img": 181,
    "onde": "Casa o palestra", "gasto": "~350 calorie in 30 minuti",
    "plano": "4 esercizi (jumping jack, squat, corsa sul posto, plank): 20 secondi intensi + 10 secondi di pausa per ciascuno, 4 giri. Inizia con 10 minuti e arriva a 20.",
    "dica": "Corto e intenso. Il corpo continua a bruciare grasso per ore dopo. 2-3 volte a settimana bastano già per avere risultati."},
   {"nome": "Salire le scale", "img": 182,
    "onde": "Palazzo, piazza o macchina per le scale", "gasto": "~300 calorie in 30 minuti",
    "plano": "Settimana 1-2: sali e scendi per 5 minuti, riposa, ripeti 3 volte. · Poi: blocchi da 8-10 minuti. Scendi sempre lentamente per risparmiare le ginocchia.",
    "dica": "Lavora forte le gambe e i glutei mentre brucia grasso. Usa il corrimano per scendere in sicurezza."},
   {"nome": "Jumping jack", "img": 183,
    "onde": "Casa o palestra", "gasto": "~250 calorie in 30 minuti",
    "plano": "Settimana 1-2: 30 secondi + 30 secondi di pausa, 8 giri. · Settimana 3-4: 45 secondi + 20 secondi. · Poi: 1 minuto + 20 secondi, 10 giri.",
    "dica": "Un ottimo riscaldamento e allo stesso tempo un consumo. Apri braccia e gambe insieme, a ritmo costante."},
   {"nome": "Burpee", "img": 184,
    "onde": "Casa o palestra", "gasto": "~350 calorie in 30 minuti",
    "plano": "Settimana 1-2: 5 burpee, riposa, 4 giri (senza il salto se ti serve). · Poi: 8-10 per giro, con il salto.",
    "dica": "Accovacciati, appoggia le mani, lancia le gambe indietro, torna su e salta. È intenso e lavora tutto il corpo — vai al tuo ritmo."},
   {"nome": "Corsa sul posto (ginocchia alte)", "img": 185,
    "onde": "Casa", "gasto": "~250 calorie in 30 minuti",
    "plano": "Settimana 1-2: 30 secondi + 30 secondi di pausa, 8 volte. · Poi: 1 minuto + 30 secondi, 10 volte.",
    "dica": "Corri sul posto alzando molto le ginocchia. Ci sta in qualsiasi angolino, senza uscire di casa."},
 ]},
{
 "tema": "Corsi e ballo", "tipo": "exercicio",
 "intro": "Chi si diverte non molla. Bruciano tanto grasso senza che sembri un sacrificio.",
 "itens": [
   {"nome": "Ballo (Zumba, dance fitness)", "img": 186,
    "onde": "Casa o palestra", "gasto": "~300 calorie in 30 minuti",
    "plano": "Inizia con 20 minuti seguendo video o una lezione e arriva a 45-60 minuti. Da 3 a 5 volte a settimana.",
    "dica": "Non sembra nemmeno esercizio. Scegli canzoni che ami e non smettere di muoverti — il sudore arriva da solo."},
   {"nome": "Boxe / Muay Thai", "img": 187,
    "onde": "Palestra o un sacco a casa", "gasto": "~350 calorie in 30 minuti",
    "plano": "1 lezione a settimana fino a 3; oppure 3 riprese da 2 minuti al sacco, aggiungendo riprese poco a poco.",
    "dica": "Scarica lo stress e brucia tantissimo. La tecnica arriva con le lezioni — non devi presentarti sapendola già."},
   {"nome": "Step", "img": 188,
    "onde": "Palestra", "gasto": "~300 calorie in 30 minuti",
    "plano": "1 lezione a settimana fino a 3, seguendo la coreografia sulla pedana.",
    "dica": "Sali e scendi da una pedana a tempo di musica. Lavora forte le gambe e la resistenza."},
   {"nome": "Mini trampolino (rebounding)", "img": 189,
    "onde": "Palestra o casa", "gasto": "~300 calorie in 30 minuti",
    "plano": "Settimana 1-2: 15 minuti. · Poi: 30-40 minuti di lezione.",
    "dica": "Divertente e a basso impatto sulle articolazioni. Tieni gli addominali sodi per mantenere l'equilibrio."},
 ]},
{
 "tema": "Macchine cardio della palestra", "tipo": "exercicio",
 "intro": "Bruciano tanto grasso con poco impatto e ti fanno controllare resistenza, tempo e intensità.",
 "itens": [
   {"nome": "Ellittica", "img": 190,
    "onde": "Palestra", "gasto": "~300 calorie in 30 minuti",
    "plano": "Settimana 1-2: 20 minuti a resistenza leggera. · Settimana 3-4: 30 minuti, alzando la resistenza. · Poi: 40 minuti alternando 2 minuti duri + 3 minuti leggeri.",
    "dica": "Muove braccia e gambe allo stesso tempo, con zero impatto. Ottima per chi sente male alle ginocchia quando corre."},
   {"nome": "Vogatore", "img": 191,
    "onde": "Palestra", "gasto": "~300 calorie in 30 minuti",
    "plano": "Settimana 1-2: 5 minuti di voga + pausa, 3 volte. · Poi: 20-30 minuti continui, concentrandoti sulla tecnica.",
    "dica": "Lavora quasi tutti i muscoli insieme. La spinta arriva dalle gambe che spingono, non solo dalle braccia che tirano."},
 ]},
{
 "tema": "Pesi in palestra", "tipo": "exercicio",
 "intro": "Il muscolo brucia calorie anche a riposo. Sollevare pesi accelera il metabolismo ed evita che la pelle resti molle.",
 "itens": [
   {"nome": "Allenamento total body (principianti)", "img": 192,
    "onde": "Palestra", "gasto": "~200 calorie in 30 minuti",
    "plano": "3 volte a settimana, 1 esercizio per ogni parte: gambe, schiena, petto, spalle e addominali. 3 serie da 12. Ogni 2 settimane, aggiungi un po' di peso.",
    "dica": "All'inizio, concentrati sull'imparare il movimento giusto con poco peso. Chiedi a un istruttore di impostarlo e correggerti — previene gli infortuni."},
   {"nome": "Allenamento gambe e glutei", "img": 193,
    "onde": "Palestra", "gasto": "~250 calorie in 30 minuti",
    "plano": "1-2 volte a settimana: squat, leg press, leg extension e hip thrust. Da 3 a 4 serie da 12 a 15.",
    "dica": "Le gambe sono i muscoli più grandi del corpo — allenarle consuma tantissima energia e ti aiuta a dimagrire più in fretta."},
   {"nome": "Allenamento braccia, schiena e petto", "img": 194,
    "onde": "Palestra", "gasto": "~180 calorie in 30 minuti",
    "plano": "1-2 volte a settimana: lat machine, rematore, panca piana e military press. 3 serie da 12.",
    "dica": "Rafforzare la parte alta del corpo migliora la postura e ti dà forma mentre il grasso se ne va."},
 ]},
{
 "tema": "Forza a casa (senza attrezzi)", "tipo": "exercicio",
 "intro": "Niente palestra e niente pesi: il carico è il tuo stesso corpo. Costruisci un circuito e metti muscolo a casa.",
 "itens": [
   {"nome": "Squat", "img": 195,
    "onde": "Casa", "gasto": "gambe e glutei",
    "plano": "Settimana 1-2: 3 serie da 10. · Settimana 3-4: 3 serie da 15. · Poi: tieni in mano un oggetto pesante (una tanica d'acqua, uno zaino) per aggiungere carico.",
    "dica": "Scendi come se ti stessi sedendo su una sedia, ginocchia in linea con i piedi, schiena dritta. È il re degli esercizi per le gambe."},
   {"nome": "Piegamenti sulle braccia", "img": 196,
    "onde": "Casa", "gasto": "petto, braccia e core",
    "plano": "Settimana 1-2: con le ginocchia a terra, 3 serie da 8. · Settimana 3-4: 3 serie da 12. · Poi: con le gambe distese.",
    "dica": "Se è ancora difficile, appoggia le mani su un tavolo o su un muro. Quello che conta è iniziare da dove riesci."},
   {"nome": "Affondo", "img": 197,
    "onde": "Casa", "gasto": "gambe ed equilibrio",
    "plano": "Settimana 1-2: 3 serie da 8 per gamba. · Poi: 3 serie da 12, e più avanti tenendo un peso in mano.",
    "dica": "Fai un passo in avanti e piega entrambe le ginocchia finché quello dietro non sfiora quasi il pavimento. Lavora una gamba per volta."},
   {"nome": "Plank e crunch", "img": 198,
    "onde": "Casa", "gasto": "tutto l'addome",
    "plano": "Tieni il plank 20-40 secondi, 3 volte, e fai 3 serie da 15 crunch. (Vedi il Bonus 2 sul Pilates per altre opzioni per il core.)",
    "dica": "Rafforzare gli addominali rende la pancia più soda e migliora la postura. Combinalo con il cardio per vedere la differenza."},
   {"nome": "Elastico di resistenza", "img": 199,
    "onde": "Casa", "gasto": "tutto il corpo",
    "plano": "3 serie da 12 a 15 per ogni movimento (squat, rematore, curl, abduzione della gamba). Passa a un elastico più duro quando diventa facile.",
    "dica": "Economico e sta in una valigia. Sostituisce i pesi della palestra a casa ed è ottimo per le braccia e la schiena."},
   {"nome": "Salita sul gradino", "img": 200,
    "onde": "Casa", "gasto": "gambe e glutei",
    "plano": "Settimana 1-2: 3 serie da 10 per gamba. · Poi: 3 serie da 15, e più avanti tenendo un peso.",
    "dica": "Sali e scendi da un gradino o da una sedia stabile. È cardio e forza allo stesso tempo, e lavora forte i glutei."},
 ]},
{
 "tema": "Movimento nella vita di tutti i giorni", "tipo": "habito", "img": 201,
 "intro": "Non è solo il tuo allenamento a bruciare calorie. Queste abitudini alzano quanto consumi durante tutta la giornata, senza doverci dedicare del tempo.",
 "itens": [
   {"titulo": "Datti l'obiettivo di 8.000 passi al giorno",
    "desc": "Usa il telefono per contarli. Avere un numero da raggiungere ti fa camminare molto di più senza accorgertene."},
   {"titulo": "Prendi le scale invece dell'ascensore",
    "desc": "Piccole scelte come questa sommano tantissima energia bruciata alla fine della giornata."},
   {"titulo": "Parcheggia più lontano o scendi una fermata prima",
    "desc": "Aggiungi passi alla tua giornata senza dover ritagliare un tempo apposta per camminare."},
   {"titulo": "Alzati ogni ora se lavori seduta",
    "desc": "Restare ferma a lungo rallenta il corpo. Alzati, allungati e cammina un po'."},
   {"titulo": "Cammina mentre parli al telefono",
    "desc": "Trasforma il tempo che passi ferma in tempo in movimento, senza sforzo in più."},
   {"titulo": "Fai le faccende di casa con energia",
    "desc": "Pulire, cucinare e mettere in ordine bruciano anche loro calorie — prendilo come movimento, non solo come un dovere."},
 ]},
{
 "tema": "Alimentazione e porzioni", "tipo": "habito", "img": 202,
 "intro": "Nessun allenamento compensa il mangiare senza controllo. Queste abitudini, insieme alle ricette di questo libro, sono ciò che fa davvero andare via il grasso.",
 "itens": [
   {"titulo": "Metti proteine a ogni pasto",
    "desc": "Uovo, pollo, pesce, carne magra o legumi. È il nutriente che sazia di più e protegge il muscolo mentre perdi grasso."},
   {"titulo": "Inizia il piatto dall'insalata e dalle verdure",
    "desc": "Riempiono lo stomaco con poche calorie, così mangi meno del resto senza soffrire la fame."},
   {"titulo": "Usa piatti più piccoli e serviti una volta sola",
    "desc": "Decidi la porzione prima di mangiare. Lo stesso cibo sembra di più in un piatto piccolo e ti senti soddisfatta con meno."},
   {"titulo": "Non bere le tue calorie",
    "desc": "Le bibite gassate e i succhi confezionati sono zucchero puro e non saziano. Preferisci acqua, tè o i succhi detox di questo libro."},
   {"titulo": "Non mangiare direttamente dalla confezione",
    "desc": "Mettine una porzione in una ciotola. Mangiando dalla confezione perdi il conto e mangi molto più di quanto ti serve."},
   {"titulo": "Mangia lentamente e mastica bene",
    "desc": "Il cervello ci mette circa 20 minuti ad avvisarti che sei sazia. Mangiare in fretta ti fa mangiare troppo."},
   {"titulo": "Non saltare i pasti",
    "desc": "La fame accumulata porta a esagerare al pasto successivo. Mangiare a orari regolari evita di perdere il controllo."},
   {"titulo": "Tieni pronti degli spuntini sani",
    "desc": "Frutta, yogurt naturale o una manciata di frutta secca ti salvano dalla fame d'emergenza senza cadere nel cibo spazzatura."},
 ]},
{
 "tema": "Acqua, sonno e riposo", "tipo": "habito", "img": 203,
 "intro": "È durante il riposo che il corpo cambia. Dormire male e vivere disidratata sabota qualsiasi dieta.",
 "itens": [
   {"titulo": "Bevi almeno 2 litri di acqua al giorno",
    "desc": "Il corpo confonde la sete con la fame. Ben idratata, spizzichi meno e il metabolismo funziona meglio."},
   {"titulo": "Inizia la giornata con un bicchiere d'acqua",
    "desc": "Dopo ore di sonno, il corpo si sveglia disidratato. L'acqua sveglia il tuo sistema."},
   {"titulo": "Dormi dalle 7 alle 8 ore a notte",
    "desc": "Le notti storte aumentano la fame e la voglia di dolce del giorno dopo. Dormire bene aiuta anche a dimagrire."},
   {"titulo": "Bevi una tisana di camomilla la sera (Ricetta 147)",
    "desc": "Ti aiuta a rilassarti e a prendere sonno, migliorando il riposo e il controllo sull'appetito."},
   {"titulo": "Riposa almeno un giorno a settimana",
    "desc": "Il muscolo cresce e il corpo si recupera durante il riposo. Allenarsi tutti i giorni senza fermarsi ostacola i tuoi risultati."},
   {"titulo": "Allungati al risveglio e dopo l'allenamento",
    "desc": "Migliora la flessibilità, previene i dolori muscolari e prepara il corpo a muoversi di più durante la giornata."},
 ]},
]
