# -*- coding: utf-8 -*-
"""BÔNUS 3 — 50 HABITUDES ET EXERCICES. FRANCÊS.

Tradução literal de `exercicios_habitos.py`. Convenções em GLOSSARIO-TRADUCAO.md.
50 itens: 30 EXERCÍCIOS reais com progressão + 20 HÁBITOS úteis. Numeração 1..50.
⛔ O campo `prompt` não é replicado: as fotos são as mesmas do PT (171-203).
Estrutura idêntica ao PT:
  tema exercicio: {tema, intro, tipo:'exercicio', itens:[{nome,onde,gasto,plano,dica,img}]}
  tema habito:    {tema, intro, tipo:'habito', img, itens:[{titulo,desc}]}
"""

TEMAS = [
{
 "tema": "Marche et course", "tipo": "exercicio",
 "intro": "La façon la plus simple et la moins chère de brûler des graisses — dans la rue, au parc ou sur un tapis de course.",
 "itens": [
  {"nome": "Marche", "img": 171, "onde": "Rue, parc ou tapis de course", "gasto": "~150 calories en 30 minutes",
   "plano": "Semaine 1-2 : 2 km à un rythme confortable, 4 à 5 fois par semaine. · Semaine 3-4 : 3 km, en accélérant le pas. · Semaine 5-6 : 4 km, avec des montées ou 3 % d'inclinaison sur le tapis. · À partir de la semaine 7 : 5 km ou 45 minutes à bon rythme.",
   "dica": "Garde un rythme où tu peux encore parler, mais avec effort. Sur le tapis, utilise une légère inclinaison pour dépenser plus sans courir."},
  {"nome": "Marche rapide (power walk)", "img": 172, "onde": "Rue ou tapis de course", "gasto": "~200 calories en 30 minutes",
   "plano": "Une fois les 5 km bien assurés, alterne 3 minutes à bon rythme + 2 minutes normal, pendant 30 à 40 minutes. Allonge peu à peu les portions rapides.",
   "dica": "Balance les bras pliés à angle droit et fais des pas fermes. Ça dépense presque autant qu'un petit footing, sans impact sur les genoux."},
  {"nome": "Footing léger (méthode marche-course)", "img": 173, "onde": "Rue, parc ou tapis de course", "gasto": "~250 calories en 30 minutes",
   "plano": "Semaine 1-2 : 1 minute de footing + 2 minutes de marche, pendant 20 minutes. · Semaine 3-4 : 2 minutes de footing + 1 minute. · Semaine 5-6 : 3 minutes de footing + 1 minute. · Ensuite : réduis les pauses jusqu'à courir en continu.",
   "dica": "Vas-y doucement sur le footing — si tu manques d'air, ralentis. C'est ainsi que le corps apprend à courir sans souffrir."},
  {"nome": "Course continue", "img": 174, "onde": "Rue, parc ou tapis de course", "gasto": "~300 calories en 30 minutes",
   "plano": "Quand tu tiens 20 minutes de course sans t'arrêter, ajoute 5 minutes par semaine jusqu'à atteindre 40-45 minutes. Une fois par semaine, fais une portion plus rapide.",
   "dica": "De bonnes chaussures font toute la différence pour les genoux. Cours à un rythme qui te permet de respirer par le nez la plupart du temps."},
 ],
},
{
 "tema": "Vélo", "tipo": "exercicio",
 "intro": "Il brûle beaucoup de graisses et ménage les genoux — idéal pour qui est en surpoids.",
 "itens": [
  {"nome": "Vélo en extérieur", "img": 175, "onde": "Rue, piste cyclable ou parc", "gasto": "~250 calories en 30 minutes",
   "plano": "Semaine 1-2 : 20 minutes sur terrain plat. · Semaine 3-4 : 30 minutes, avec de petites montées. · À partir de la semaine 5 : 40 à 60 minutes, en variant le rythme.",
   "dica": "Règle la selle : la jambe est presque tendue quand la pédale est en bas. Cela protège le genou et te permet de pédaler plus longtemps."},
  {"nome": "Vélo d'appartement", "img": 176, "onde": "À la maison ou en salle", "gasto": "~250 calories en 30 minutes",
   "plano": "Semaine 1-2 : 20 minutes à faible résistance. · Semaine 3-4 : 30 minutes, en augmentant la résistance. · Ensuite : 40 minutes en alternant 2 minutes dur + 3 minutes facile.",
   "dica": "Parfait pour les jours de pluie. Augmente la résistance petit à petit pour ne pas pédaler « dans le vide »."},
  {"nome": "Spinning", "img": 177, "onde": "Salle de sport", "gasto": "~350 calories en 30 minutes",
   "plano": "Commence par 1 cours par semaine et va jusqu'à 2 ou 3. Suis le coach, mais respecte ta limite sur la résistance.",
   "dica": "L'un des cours qui brûlent le plus de calories. Bois de l'eau pendant et commence avec une résistance plus faible — progresse à ton rythme."},
 ],
},
{
 "tema": "Natation et exercices dans l'eau", "tipo": "exercicio",
 "intro": "L'eau porte le poids du corps, il n'y a donc presque aucun impact — excellent pour qui a mal aux articulations.",
 "itens": [
  {"nome": "Natation", "img": 178, "onde": "Piscine", "gasto": "~300 calories en 30 minutes",
   "plano": "Semaine 1-2 : nage 20 minutes avec des pauses au bord. · Semaine 3-4 : réduis les pauses, arrive à 30 minutes. · Ensuite : 40 minutes en continu, en variant les nages.",
   "dica": "Ça travaille tout le corps sans surcharger les genoux ni la colonne. Un ou deux cours aident beaucoup pour la respiration."},
  {"nome": "Aquagym", "img": 179, "onde": "Piscine", "gasto": "~200 calories en 30 minutes",
   "plano": "1 à 3 cours par semaine. L'intensité monte à mesure que tu fais les mouvements avec plus de force contre l'eau.",
   "dica": "Faite avec énergie, elle brûle beaucoup et renforce les jambes sans aucun impact. Excellente en cas de fort surpoids."},
 ],
},
{
 "tema": "Entraînement fractionné (brûlage rapide)", "tipo": "exercicio",
 "intro": "Peu de temps, beaucoup de résultat : on alterne effort intense et courte pause. Ça brûle des graisses pendant et des heures après.",
 "itens": [
  {"nome": "Corde à sauter", "img": 180, "onde": "À la maison, dans la cour ou en salle", "gasto": "~350 calories en 30 minutes",
   "plano": "Semaine 1-2 : 30 secondes de saut + 1 minute de pause, pendant 10 minutes. · Semaine 3-4 : 1 minute + 1 minute, pendant 15 minutes. · Ensuite : 2 minutes + 1 minute, pendant 20 minutes.",
   "dica": "L'un des plus gros brûlages par minute, et la corde ne coûte presque rien. Saute bas, juste assez pour laisser passer la corde."},
  {"nome": "HIIT (Tabata)", "img": 181, "onde": "À la maison ou en salle", "gasto": "~350 calories en 30 minutes",
   "plano": "4 exercices (jumping jack, squat, course sur place, planche) : 20 secondes à fond + 10 secondes de pause pour chacun, 4 tours. Commence par 10 minutes et va jusqu'à 20.",
   "dica": "Court et intense. Le corps continue de brûler des graisses des heures après. 2 à 3 fois par semaine donnent déjà des résultats."},
  {"nome": "Monter les escaliers", "img": 182, "onde": "Immeuble, place ou stepper", "gasto": "~300 calories en 30 minutes",
   "plano": "Semaine 1-2 : monte et descends 5 minutes, repose-toi, répète 3 fois. · Ensuite : des blocs de 8 à 10 minutes. Descends toujours lentement pour ménager le genou.",
   "dica": "Ça travaille beaucoup les jambes et les fesses tout en brûlant des graisses. Utilise la rampe pour descendre en sécurité."},
  {"nome": "Jumping jack", "img": 183, "onde": "À la maison ou en salle", "gasto": "~250 calories en 30 minutes",
   "plano": "Semaine 1-2 : 30 secondes + 30 secondes de pause, 8 tours. · Semaine 3-4 : 45 secondes + 20 secondes. · Ensuite : 1 minute + 20 secondes, 10 tours.",
   "dica": "Excellent échauffement et brûlage en même temps. Ouvre les bras et les jambes ensemble, à un rythme régulier."},
  {"nome": "Burpee", "img": 184, "onde": "À la maison ou en salle", "gasto": "~350 calories en 30 minutes",
   "plano": "Semaine 1-2 : 5 burpees, pause, 4 tours (sans le saut si besoin). · Ensuite : 8 à 10 par tour, avec le saut.",
   "dica": "Tu t'accroupis, tu poses les mains, tu envoies les jambes en arrière, tu reviens et tu sautes. C'est intense et ça travaille tout le corps — vas-y à ton rythme."},
  {"nome": "Course sur place (genoux hauts)", "img": 185, "onde": "À la maison", "gasto": "~250 calories en 30 minutes",
   "plano": "Semaine 1-2 : 30 secondes + 30 secondes de pause, 8 fois. · Ensuite : 1 minute + 30 secondes, 10 fois.",
   "dica": "Cours sur place en levant bien les genoux. Ça tient dans n'importe quel coin, sans sortir de chez toi."},
 ],
},
{
 "tema": "Cours et danse", "tipo": "exercicio",
 "intro": "Qui s'amuse n'abandonne pas. Ils brûlent beaucoup de graisses sans donner l'impression d'un sacrifice.",
 "itens": [
  {"nome": "Danse (Zumba, fitness dansé)", "img": 186, "onde": "À la maison ou en salle", "gasto": "~300 calories en 30 minutes",
   "plano": "Commence par 20 minutes en suivant des vidéos ou un cours et va jusqu'à 45-60 minutes. 3 à 5 fois par semaine.",
   "dica": "Ça ne ressemble même pas à du sport. Choisis des musiques que tu adores et n'arrête pas de bouger — la transpiration vient toute seule."},
  {"nome": "Boxe / Muay Thaï", "img": 187, "onde": "Salle de sport ou sac à la maison", "gasto": "~350 calories en 30 minutes",
   "plano": "1 cours par semaine jusqu'à 3 ; ou 3 rounds de 2 minutes au sac, en augmentant les rounds petit à petit.",
   "dica": "Ça évacue le stress et ça brûle beaucoup. La technique vient avec les cours — tu n'as pas besoin d'arriver en sachant faire."},
  {"nome": "Cours de step", "img": 188, "onde": "Salle de sport", "gasto": "~300 calories en 30 minutes",
   "plano": "1 cours par semaine jusqu'à 3, en suivant la chorégraphie sur la marche.",
   "dica": "Tu montes et tu descends d'une marche au rythme de la musique. Ça travaille beaucoup les jambes et le souffle."},
  {"nome": "Trampoline (jumping fitness)", "img": 189, "onde": "Salle de sport ou à la maison", "gasto": "~300 calories en 30 minutes",
   "plano": "Semaine 1-2 : 15 minutes. · Ensuite : 30 à 40 minutes de cours.",
   "dica": "Amusant et peu traumatisant pour les articulations. Garde le ventre bien contracté pour tenir l'équilibre."},
 ],
},
{
 "tema": "Machines de cardio en salle", "tipo": "exercicio",
 "intro": "Elles brûlent beaucoup de graisses avec peu d'impact et te laissent contrôler la résistance, la durée et l'intensité.",
 "itens": [
  {"nome": "Vélo elliptique", "img": 190, "onde": "Salle de sport", "gasto": "~300 calories en 30 minutes",
   "plano": "Semaine 1-2 : 20 minutes à faible résistance. · Semaine 3-4 : 30 minutes, en montant la résistance. · Ensuite : 40 minutes en alternant 2 minutes intense + 3 minutes facile.",
   "dica": "Il fait travailler les bras et les jambes en même temps, sans aucun impact. Excellent pour qui a mal aux genoux en courant."},
  {"nome": "Rameur", "img": 191, "onde": "Salle de sport", "gasto": "~300 calories en 30 minutes",
   "plano": "Semaine 1-2 : 5 minutes de rame + pause, 3 fois. · Ensuite : 20 à 30 minutes en continu, en soignant la technique.",
   "dica": "Il travaille presque tous les muscles d'un coup. La force vient des jambes qui poussent, pas seulement des bras qui tirent."},
 ],
},
{
 "tema": "Musculation en salle", "tipo": "exercicio",
 "intro": "Le muscle brûle des calories même au repos. Faire de la force accélère le métabolisme et évite que la peau ne se relâche.",
 "itens": [
  {"nome": "Entraînement du corps entier (débutant)", "img": 192, "onde": "Salle de sport", "gasto": "~200 calories en 30 minutes",
   "plano": "3 fois par semaine, 1 exercice pour chaque partie : jambes, dos, poitrine, épaules et abdominaux. 3 séries de 12. Toutes les 2 semaines, augmente un peu la charge.",
   "dica": "Au début, concentre-toi sur le bon mouvement avec une charge légère. Demande au coach de te faire le programme et de te corriger — ça évite les blessures."},
  {"nome": "Entraînement jambes et fessiers", "img": 193, "onde": "Salle de sport", "gasto": "~250 calories en 30 minutes",
   "plano": "1 à 2 fois par semaine : squat, presse à cuisses, extension des jambes et relevé de hanches. 3 à 4 séries de 12 à 15.",
   "dica": "Les jambes sont les plus gros muscles du corps — les entraîner dépense beaucoup d'énergie et aide à s'affiner plus vite."},
  {"nome": "Entraînement bras, dos et poitrine", "img": 194, "onde": "Salle de sport", "gasto": "~180 calories en 30 minutes",
   "plano": "1 à 2 fois par semaine : tirage vertical, rowing, développé couché et développé épaules. 3 séries de 12.",
   "dica": "Renforcer le haut du corps améliore la posture et dessine la silhouette pendant que la graisse s'en va."},
 ],
},
{
 "tema": "Renforcement à la maison (sans matériel)", "tipo": "exercicio",
 "intro": "Sans salle et sans poids : ton propre corps est la charge. Monte un circuit et gagne du muscle à la maison.",
 "itens": [
  {"nome": "Squat", "img": 195, "onde": "À la maison", "gasto": "jambes et fessiers",
   "plano": "Semaine 1-2 : 3 séries de 10. · Semaine 3-4 : 3 séries de 15. · Ensuite : tiens un objet lourd (bidon d'eau, sac à dos) pour augmenter la charge.",
   "dica": "Descends comme si tu allais t'asseoir sur une chaise, les genoux dans l'axe des pieds, le dos droit. C'est le roi des exercices de jambes."},
  {"nome": "Pompe", "img": 196, "onde": "À la maison", "gasto": "poitrine, bras et centre du corps",
   "plano": "Semaine 1-2 : avec les genoux au sol, 3 séries de 8. · Semaine 3-4 : 3 séries de 12. · Ensuite : avec les jambes tendues.",
   "dica": "Si c'est encore difficile, appuie les mains sur une table ou un mur. L'important est de commencer là où tu en es."},
  {"nome": "Fente avant", "img": 197, "onde": "À la maison", "gasto": "jambes et équilibre",
   "plano": "Semaine 1-2 : 3 séries de 8 avec chaque jambe. · Ensuite : 3 séries de 12, puis en tenant un poids dans les mains.",
   "dica": "Fais un pas en avant et plie les deux genoux jusqu'à ce que celui de derrière frôle le sol. Ça travaille une jambe à la fois."},
  {"nome": "Planche et abdominaux", "img": 198, "onde": "À la maison", "gasto": "tout le ventre",
   "plano": "Tiens la planche 20 à 40 secondes, 3 fois, et fais 3 séries de 15 crunchs. (Regarde le Bonus 2 de Pilates pour plus d'options pour le centre du corps.)",
   "dica": "Renforcer les abdominaux rend le ventre plus ferme et améliore la posture. Combine avec du cardio pour voir la différence."},
  {"nome": "Élastique de fitness", "img": 199, "onde": "À la maison", "gasto": "tout le corps",
   "plano": "3 séries de 12 à 15 à chaque mouvement (squat, rowing, curl biceps, ouverture des jambes). Passe à un élastique plus fort quand ça devient facile.",
   "dica": "Pas cher et il tient dans une valise. Il remplace les poids de la salle à la maison et il est excellent pour les bras et le dos."},
  {"nome": "Montée sur banc (step-up)", "img": 200, "onde": "À la maison", "gasto": "jambes et fessiers",
   "plano": "Semaine 1-2 : 3 séries de 10 avec chaque jambe. · Ensuite : 3 séries de 15, puis en tenant un poids.",
   "dica": "Monte et descends d'une marche ou d'une chaise stable. C'est du cardio et de la force en même temps, et ça travaille beaucoup les fesses."},
 ],
},
{
 "tema": "Bouger au quotidien", "tipo": "habito", "img": 201,
 "intro": "Il n'y a pas que l'entraînement qui brûle des calories. Ces habitudes augmentent ta dépense toute la journée, sans y consacrer de temps.",
 "itens": [
  {"titulo": "Fixe-toi l'objectif de 8 000 pas par jour", "desc": "Utilise ton téléphone pour compter. Avoir un chiffre à atteindre te fait marcher bien plus sans même t'en rendre compte."},
  {"titulo": "Prends l'escalier plutôt que l'ascenseur", "desc": "De petits choix comme celui-là additionnent une belle dépense d'énergie en fin de journée."},
  {"titulo": "Gare-toi plus loin ou descends un arrêt avant", "desc": "Tu ajoutes des pas à ta journée sans avoir à réserver un moment spécial pour marcher."},
  {"titulo": "Lève-toi toutes les heures si tu travailles assis", "desc": "Rester longtemps immobile ralentit le corps. Lève-toi, étire-toi et marche un peu."},
  {"titulo": "Marche pendant que tu téléphones", "desc": "Transforme un temps immobile en temps en mouvement, sans effort supplémentaire."},
  {"titulo": "Fais le ménage avec entrain", "desc": "Nettoyer, cuisiner et ranger brûlent aussi des calories — vois-le comme du mouvement, pas seulement comme une corvée."},
 ],
},
{
 "tema": "Alimentation et portions", "tipo": "habito", "img": 202,
 "intro": "Aucun entraînement ne compense une alimentation incontrôlée. Ces habitudes, avec les recettes du livre, font vraiment partir la graisse.",
 "itens": [
  {"titulo": "Mets des protéines à chaque repas", "desc": "Œuf, poulet, poisson, viande maigre ou haricots. C'est le nutriment qui rassasie le plus et qui préserve le muscle pendant que tu perds de la graisse."},
  {"titulo": "Commence ton assiette par la salade et les légumes", "desc": "Ils remplissent l'estomac pour peu de calories, tu manges donc moins du reste sans avoir faim."},
  {"titulo": "Prends des assiettes plus petites et sers-toi une seule fois", "desc": "Décide de la portion avant de manger. La même quantité paraît plus grande dans une petite assiette et tu es satisfait avec moins."},
  {"titulo": "Ne bois pas tes calories", "desc": "Les sodas et les jus en brique sont du sucre pur et ne rassasient pas. Préfère l'eau, le thé ou les jus détox du livre."},
  {"titulo": "Ne mange pas directement dans le paquet", "desc": "Sers-toi une portion dans un bol. Dans le paquet, tu perds la notion et tu manges bien plus que nécessaire."},
  {"titulo": "Mange lentement et mâche bien", "desc": "Le cerveau met environ 20 minutes à signaler que tu es rassasié. Manger vite fait manger trop."},
  {"titulo": "Ne saute pas de repas", "desc": "La faim accumulée mène à l'excès au repas suivant. Manger à des horaires réguliers évite de perdre le contrôle."},
  {"titulo": "Aie des en-cas sains déjà prêts", "desc": "Un fruit, un yaourt nature ou une poignée de noix te sauvent de la faim d'urgence sans tomber dans le n'importe quoi."},
 ],
},
{
 "tema": "Eau, sommeil et repos", "tipo": "habito", "img": 203,
 "intro": "C'est dans le repos que le corps se transforme. Mal dormir et vivre déshydraté sabote n'importe quel régime.",
 "itens": [
  {"titulo": "Bois au moins 2 litres d'eau par jour", "desc": "Le corps confond la soif avec la faim. Bien hydraté, tu grignotes moins et le métabolisme fonctionne mieux."},
  {"titulo": "Commence la journée par un verre d'eau", "desc": "Après des heures de sommeil, le corps se réveille déshydraté. L'eau réveille l'organisme."},
  {"titulo": "Dors 7 à 8 heures par nuit", "desc": "Des nuits mal dormies augmentent la faim et l'envie de sucré le lendemain. Bien dormir fait aussi maigrir."},
  {"titulo": "Bois une tisane de camomille le soir (recette 147)", "desc": "Elle aide à se détendre et à trouver le sommeil, ce qui améliore le repos et le contrôle de l'appétit."},
  {"titulo": "Repose-toi au moins un jour par semaine", "desc": "Le muscle grandit et le corps récupère pendant le repos. S'entraîner tous les jours sans pause nuit au résultat."},
  {"titulo": "Étire-toi au réveil et après les séances", "desc": "Cela améliore la souplesse, évite les douleurs et prépare le corps à bouger davantage dans la journée."},
 ],
},
]
