# -*- coding: utf-8 -*-
"""BONUS 2 — BELLY-SLIMMING PILATES AT HOME. 12 exercises (photos 159-170). English.
Core (deep abdominals) + posture. Done on the floor/mat, no equipment.
Each exercise: foco, nivel, series, tempo, passos, respiracao, dica, prompt.
Simple language; always with an easier variation for beginners/older adults.
"""

EXERCICIOS = [
{
 "nome": "Pilates Breathing (Activating the Core)",
 "foco": "Learning to contract the deep abdominals — the base of every exercise.",
 "nivel": "Beginner", "series": "5 breaths", "tempo": "2 min",
 "hook": "First of all, learn to switch on the core from the inside — that is what makes Pilates work and the belly firmer.",
 "passos": [
   "Lie on your back, knees bent and feet flat on the floor, hip-width apart. Let your arms rest by your sides.",
   "Place your hands on your belly. Breathe in through your nose, filling your belly like a balloon.",
   "Breathe out slowly through your mouth and, at the same time, pull your navel in toward your spine, as if closing the zipper of tight pants.",
   "Hold that contraction for 3 seconds, feeling the belly firm, and relax.",
   "Repeat 5 times, always breathing out and pulling the navel in."],
 "respiracao": "Breathe in through your nose filling the belly; breathe out through your mouth emptying and contracting the core. Never hold your breath.",
 "dica": "This 'pull the navel in' is the secret of Pilates. You will use this same contraction in every other exercise — it is what works the deepest belly muscle, the one that holds everything in place and slims the waist.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat with knees bent and hands on the belly, calm home setting, soft natural light, fitness demonstration, neutral clothing, full body visible, no text, no writing, 1:1 square.",
},
{
 "nome": "Pelvic Tilt",
 "foco": "Warming up the spine and activating the lower belly.",
 "nivel": "Beginner", "series": "2 sets of 10", "tempo": "3 min",
 "hook": "A small, gentle movement that loosens the lower back and wakes up the lower belly.",
 "passos": [
   "Stay lying on your back, knees bent and feet on the floor.",
   "Breathe out and pull your navel in, tilting your pelvis slightly backward so your lower back presses fully into the floor.",
   "Breathe in and return slowly, leaving a small gap between your lower back and the floor.",
   "Do the movement very slowly, as if drawing with your hips, without forcing.",
   "Repeat 10 times, rest and do another set of 10."],
 "respiracao": "Breathe out as your lower back presses into the floor; breathe in as you return. The movement follows the breath.",
 "dica": "It is a perfect warm-up for anyone with a sensitive lower back. The movement is short on purpose — the belly contraction is in charge, not the back's strength.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat performing a gentle pelvic tilt, knees bent, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "The Hundred",
 "foco": "The most famous Pilates exercise for the whole belly.",
 "nivel": "Intermediate", "series": "1 set (count to 100)", "tempo": "3 min",
 "hook": "The classic that warms up the whole body and makes the core burn — gently, but it burns.",
 "passos": [
   "Lie on your back, bend your knees and lift your legs until they are bent at 90 degrees (shins parallel to the floor), as if sitting in an upside-down chair.",
   "Breathe out, pull your navel in and lift your head and shoulders slightly off the floor, looking at your belly. Extend your arms straight beside your body, a hand's width above the floor.",
   "Start swinging your arms up and down, with short, firm movements, as if tapping the water.",
   "Count five swings while you breathe in and five while you breathe out.",
   "Continue until you complete 100 swings (or stop earlier if you tire). Then lower your head and legs and rest."],
 "respiracao": "Breathe in for 5 swings and out for 5 swings, without stopping the arm pumping.",
 "dica": "Easier variation: keep your feet on the floor and just lift your head and shoulders. Start with 30 or 50 swings and build up to 100 over time.",
 "prompt": "Square photograph of a person on a yoga mat doing the Pilates hundred exercise, head and shoulders lifted, legs bent at 90 degrees, arms pumping beside the body, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Alternating Leg Lift",
 "foco": "Lower belly and movement control.",
 "nivel": "Beginner", "series": "2 sets of 12", "tempo": "3 min",
 "hook": "A controlled movement that works exactly that lower belly area, the most stubborn one.",
 "passos": [
   "Lie on your back, knees bent and feet flat on the floor. Keep your lower back pressed into the floor the whole time.",
   "Breathe out, pull your navel in and lift one foot off the floor, bringing the knee toward your belly until the thigh is upright (90 degrees).",
   "Breathe in and lower the foot slowly until it touches the floor again, with control.",
   "Alternate: now lift the other leg the same way.",
   "Do 12 times with each leg, keeping the belly always contracted. Rest and repeat the set."],
 "respiracao": "Breathe out as you lift the leg; breathe in as you lower it. The core stays firm the whole time.",
 "dica": "What matters is not speed, it is control: the slower you lower the leg, the more the belly works. If you feel your lower back arch and leave the floor, lift the leg less.",
 "prompt": "Square photograph of a person lying on their back on a yoga mat lifting one bent knee toward the chest, core engaged, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Small Crunch (Chest Lift)",
 "foco": "Upper and middle belly.",
 "nivel": "Beginner", "series": "3 sets of 12", "tempo": "4 min",
 "hook": "The usual crunch, but done with Pilates control — it rises a little and works a lot.",
 "passos": [
   "Lie on your back, knees bent and feet on the floor. Cross your arms over your chest or rest your hands behind your head, without pulling your neck.",
   "Breathe out, pull your navel in and curl your torso up, lifting your head and shoulders off the floor, as if bringing your ribs toward your hips.",
   "Rise only until the tips of your shoulder blades leave the floor (you do not need to sit up). Hold 1 second at the top.",
   "Breathe in and lower slowly, rolling your spine back to the floor, vertebra by vertebra.",
   "Repeat 12 times, rest and do 3 sets in total."],
 "respiracao": "Breathe out as you rise (that is when the belly contracts most); breathe in as you lower.",
 "dica": "Do not pull your neck with your hands — your gaze goes to your belly and your chin stays away from your chest, with room for an orange. It is the belly that lifts the body, not the neck.",
 "prompt": "Square photograph of a person on a yoga mat doing a small controlled crunch, shoulders lifted, hands crossed on chest, knees bent, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Front Plank",
 "foco": "The whole belly, lower back and posture — the most complete core exercise.",
 "nivel": "Intermediate", "series": "3 times, hold 20–40 s", "tempo": "4 min",
 "hook": "Still, but powerful: holding the plank strengthens the whole belly and back at once.",
 "passos": [
   "Lie face down and rest your forearms on the floor, elbows under your shoulders. Your hands are in front.",
   "Extend your legs back and rest the balls of your feet on the floor.",
   "Breathe out, pull your navel in and lift your body, keeping it straight like a board, from heels to head.",
   "Keep your hips in line with your body — not lifted like a hill, not sagging toward the floor. Look at the floor so you do not strain your neck.",
   "Hold for 20 to 40 seconds, breathing normally. Lower, rest and repeat 3 times."],
 "respiracao": "Keep breathing normally and slowly throughout the plank. Do not hold your breath.",
 "dica": "Easier variation: rest your knees on the floor (knee plank). Start by holding 15 seconds and build up gradually. If your lower back hurts, it is a sign your hips sagged — lift them a little.",
 "prompt": "Square photograph of a person holding a forearm plank on a yoga mat, straight body line, core engaged, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Side Plank",
 "foco": "The side belly muscles (obliques) — slims the waist.",
 "nivel": "Intermediate", "series": "2 times each side, 15–30 s", "tempo": "4 min",
 "hook": "It is the exercise that shapes the side of the belly and defines the waist.",
 "passos": [
   "Lie on your side, body straight. Rest your bottom forearm on the floor, elbow under your shoulder.",
   "Stack one leg on top of the other (one foot on the other).",
   "Breathe out, pull your navel in and lift your hips off the floor, keeping your body straight and supported only on your forearm and the side of your foot.",
   "Extend the top arm toward the ceiling or rest the hand on your waist. Hold for 15 to 30 seconds.",
   "Lower with control, turn to the other side and repeat. Do 2 times on each side."],
 "respiracao": "Breathe normally and slowly while holding the position.",
 "dica": "Easier variation: bend your knees and rest the lower part of your legs on the floor, lifting only your hips. The waist works the most here — hold firm.",
 "prompt": "Square photograph of a person holding a side plank on a yoga mat, body straight, supported on one forearm, calm home setting, soft natural light, fitness demonstration, neutral clothing, no text, no writing, 1:1 square.",
},
{
 "nome": "Glute Bridge",
 "foco": "Glutes, back of the thighs and belly — and it relieves the lower back.",
 "nivel": "Beginner", "series": "3 sets of 12", "tempo": "3 min",
 "hook": "It lifts the backside, strengthens the belly from behind and even improves posture.",
 "passos": [
   "Lie on your back, knees bent and feet flat on the floor, hip-width apart. Arms by your sides.",
   "Breathe out, pull your navel in and lift your hips off the floor, squeezing your glutes, until your body forms a straight line from knees to shoulders.",
   "Hold 2 seconds at the top, keeping your glutes and belly firm.",
   "Breathe in and lower your hips slowly, rolling your spine back to the floor, vertebra by vertebra.",
   "Repeat 12 times, do 3 sets."],
 "respiracao": "Breathe out as you lift the hips; breathe in as you lower.",
 "dica": "Rise by squeezing your glutes well, not by pushing your lower back. It is one of the few exercises that strengthens the belly and also relieves back pain — great for anyone who sits all day.",
 "prompt": "Square photograph of a person on a yoga mat doing a glute bridge, hips lifted, knees bent, shoulders on the mat, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Spine Roll Up",
 "foco": "The whole belly and spine flexibility.",
 "nivel": "Intermediate", "series": "2 sets of 8", "tempo": "4 min",
 "hook": "Sitting up and lying down by slowly rolling the spine — it looks simple, but the belly does all the work.",
 "passos": [
   "Lie on your back with legs extended and arms stretched overhead, behind your head.",
   "Breathe in and bring your arms forward, pointing at the ceiling.",
   "Breathe out, pull your navel in and start to sit up very slowly, rolling your spine: first your head, then your shoulders, your back, until you are sitting and reaching your feet with your hands.",
   "Breathe in at the top and, breathing out, lower the same way slowly, rolling your spine back to the floor, vertebra by vertebra.",
   "Repeat 8 times, with maximum control. Do 2 sets."],
 "respiracao": "Breathe out as you rise and as you lower (that is when the belly works); breathe in on the pauses.",
 "dica": "Easier variation: bend your knees a little and, if needed, give a small push with your arms. What matters is rising and lowering slowly — it is the belly that does the work, not the neck or arms.",
 "prompt": "Square photograph of a person on a yoga mat performing a Pilates roll up, spine curling up to reach toward the feet, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Bicycle Crunch",
 "foco": "The obliques (side belly) and the whole belly.",
 "nivel": "Intermediate", "series": "3 sets of 20 (10 each side)", "tempo": "4 min",
 "hook": "The pedaling movement that shapes the sides of the belly and lifts your heart rate a little.",
 "passos": [
   "Lie on your back, hands behind your head (without pulling your neck). Lift your legs with knees bent at 90 degrees.",
   "Breathe out, pull your navel in and lift your head and shoulders off the floor.",
   "Rotate your torso, bringing your right elbow toward your left knee, while extending your right leg forward.",
   "Return to the center and do the other side: left elbow toward the right knee, extending the left leg.",
   "Keep alternating, as if slowly pedaling a bicycle. Do 20 in total (10 each side), 3 sets."],
 "respiracao": "Breathe out with each torso rotation; breathe in as you pass through the center.",
 "dica": "Do it slowly and with control, not in a rush — the torso rotation is what works the side of the belly. The further you extend the leg away, the harder and more effective it gets.",
 "prompt": "Square photograph of a person on a yoga mat doing a bicycle crunch, torso rotated, one elbow toward the opposite knee, other leg extended, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Superman (Back Extension)",
 "foco": "Back and posture — it balances the body and makes the belly look flatter when standing.",
 "nivel": "Beginner", "series": "3 sets of 10", "tempo": "3 min",
 "hook": "After so many crunches, this one strengthens the back and improves posture — which already makes the belly look flatter.",
 "passos": [
   "Lie face down (belly down), with your arms extended forward and your legs stretched back.",
   "Breathe out, pull your navel in slightly and lift your arms, chest and legs off the floor at the same time, a few inches, like Superman flying.",
   "Hold 2 seconds at the top, looking at the floor so you do not strain your neck.",
   "Breathe in and lower slowly, relaxing.",
   "Repeat 10 times, do 3 sets."],
 "respiracao": "Breathe out as you lift; breathe in as you lower. A smooth movement, with no jerks.",
 "dica": "You do not need to lift high — a few inches already work the back. Strengthening the back is essential: a strong back holds you upright, and good posture alone already makes the belly look smaller.",
 "prompt": "Square photograph of a person lying face down on a yoga mat lifting arms, chest and legs off the floor in a superman back extension, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
{
 "nome": "Final Stretch",
 "foco": "Relaxing the spine and belly after the workout.",
 "nivel": "All levels", "series": "Hold 30 s each", "tempo": "3 min",
 "hook": "To finish, a pleasant stretch that relaxes the belly and back you just worked.",
 "passos": [
   "Get on all fours (hands and knees on the floor). Sit your backside onto your heels and extend your arms forward, resting your torso over your thighs (resting pose). Bring your forehead to the floor and breathe deeply for 30 seconds.",
   "Return to lying on your back. Hug one knee at a time, pulling it toward your chest, and hold 30 seconds each side — this relaxes the lower back.",
   "Finally, lying on your back with arms open, let both knees drop slowly to one side and then the other, gently rotating the spine, 30 seconds each side.",
   "Breathe deeply throughout the stretch, without rushing.",
   "Get up slowly when you finish."],
 "respiracao": "Breathe deeply and slowly, breathing out with each stretch and letting the body relax a bit more.",
 "dica": "Never skip the stretch: it relaxes the muscles that worked, prevents next-day soreness and improves flexibility. It is the moment to feel your body and close the workout in peace.",
 "prompt": "Square photograph of a person on a yoga mat in child's pose stretching, arms extended forward, forehead near the floor, calm home setting, soft natural light, fitness demonstration, no text, no writing, 1:1 square.",
},
]
