# -*- coding: utf-8 -*-
"""BONUS 3 — 50 HABITS AND EXERCISES. English (US market).
50 items: 30 real EXERCISES with progression + 20 useful HABITS. Numbered 1..50.
Each EXERCISE has its OWN photo (individual card): photos 171-200.
The habits come in 3 sections, each with 1 theme photo: 201-203.
US units: miles / calories / minutes / seconds. No abbreviations.
"""

TEMAS = [
{
 "tema": "Walking and Running", "tipo": "exercicio",
 "intro": "The simplest and cheapest way to burn fat — on the street, in the park or on the treadmill.",
 "itens": [
  {"nome": "Walking", "img": 171, "onde": "Street, park or treadmill", "gasto": "~150 calories in 30 minutes",
   "plano": "Week 1-2: 1.2 miles at a comfortable pace, 4 to 5 times a week. · Week 3-4: 2 miles, picking up the pace. · Week 5-6: 2.5 miles, with hills or a 3% incline on the treadmill. · Week 7 and on: 3 miles or 45 minutes at a brisk pace.",
   "dica": "Keep a pace where you can talk, but with effort. On the treadmill, use a slight incline to burn more without running.",
   "prompt": "Square ultra-realistic photograph of a person walking briskly on a park path in athletic wear, morning light, motion, healthy lifestyle, no text, no writing, 1:1 square."},
  {"nome": "Power Walk", "img": 172, "onde": "Street or treadmill", "gasto": "~200 calories in 30 minutes",
   "plano": "After you settle into 3 miles, alternate 3 minutes at a brisk pace + 2 minutes normal, for 30 to 40 minutes. Gradually increase the fast stretches.",
   "dica": "Pump your arms bent at 90 degrees and take firm steps. It burns almost like jogging, with no impact on the knees.",
   "prompt": "Square ultra-realistic photograph of a person power walking fast with arms bent, athletic wear, outdoor path, motion, no text, no writing, 1:1 square."},
  {"nome": "Jogging (Walk-Run Method)", "img": 173, "onde": "Street, park or treadmill", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 1 minute of jogging + 2 minutes of walking, for 20 minutes. · Week 3-4: 2 minutes jog + 1 minute. · Week 5-6: 3 minutes jog + 1 minute. · After that: shorten the breaks until you run continuously.",
   "dica": "Go slow on the jog — if you run out of breath, ease off. That is how the body learns to run without suffering.",
   "prompt": "Square ultra-realistic photograph of a person lightly jogging on a park path, relaxed pace, athletic wear, daylight, no text, no writing, 1:1 square."},
  {"nome": "Continuous Running", "img": 174, "onde": "Street, park or treadmill", "gasto": "~300 calories in 30 minutes",
   "plano": "When you can run 20 minutes without stopping, add 5 minutes per week until you reach 40-45 minutes. Once a week, do a faster stretch.",
   "dica": "A good pair of shoes makes all the difference for the knees. Run at a pace where you can breathe through your nose most of the time.",
   "prompt": "Square ultra-realistic photograph of a person running outdoors on a road or park, steady pace, athletic wear, dynamic motion, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Cycling", "tipo": "exercicio",
 "intro": "It burns lots of fat and is gentle on the knees — ideal for anyone carrying extra weight.",
 "itens": [
  {"nome": "Outdoor Bike", "img": 175, "onde": "Street, bike lane or park", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes on flat ground. · Week 3-4: 30 minutes, with small hills. · Week 5 and on: 40 to 60 minutes, varying the pace.",
   "dica": "Adjust the seat: your leg almost straightens at the bottom of the pedal stroke. This protects the knee and lets you ride longer.",
   "prompt": "Square ultra-realistic photograph of a person riding a road bike outdoors on a cycle path, athletic wear, daylight, motion, no text, no writing, 1:1 square."},
  {"nome": "Stationary Bike", "img": 176, "onde": "Home or gym", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes at light resistance. · Week 3-4: 30 minutes, increasing the resistance. · After that: 40 minutes alternating 2 minutes hard + 3 minutes easy.",
   "dica": "Perfect for rainy days. Increase the resistance gradually so you are not pedaling 'against nothing'.",
   "prompt": "Square ultra-realistic photograph of a person exercising on a stationary bike at home, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Spinning", "img": 177, "onde": "Gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Start with 1 class a week and build up to 2 or 3. Follow the instructor, but respect your own limit on the resistance.",
   "dica": "One of the classes that burns the most calories. Drink water during it and start with lighter resistance — progress at your own pace.",
   "prompt": "Square ultra-realistic photograph of a person in a spinning class on an indoor cycling bike, gym studio, focused, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Swimming and Water Exercises", "tipo": "exercicio",
 "intro": "The water supports the body's weight, so there is almost no impact — great for anyone with joint pain.",
 "itens": [
  {"nome": "Swimming", "img": 178, "onde": "Pool", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: swim 20 minutes with breaks at the wall. · Week 3-4: shorten the breaks, reach 30 minutes. · After that: 40 continuous minutes, varying the strokes.",
   "dica": "It works the whole body without overloading the knees and spine. One or two lessons help a lot with your breathing.",
   "prompt": "Square ultra-realistic photograph of a person swimming freestyle laps in a clean pool, splashing water, bright light, no text, no writing, 1:1 square."},
  {"nome": "Water Aerobics", "img": 179, "onde": "Pool", "gasto": "~200 calories in 30 minutes",
   "plano": "1 to 3 classes a week. The intensity rises as you make the movements with more force against the water.",
   "dica": "Done with energy, it burns plenty and strengthens the legs with zero impact. Excellent for people carrying a lot of extra weight.",
   "prompt": "Square ultra-realistic photograph of people doing water aerobics in a pool, active movement, bright daylight, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Interval Training (Fast Burn)", "tipo": "exercicio",
 "intro": "Little time, big results: it alternates hard effort with short rest. It burns fat during and for hours afterward.",
 "itens": [
  {"nome": "Jump Rope", "img": 180, "onde": "Home, yard or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds jumping + 1 minute rest, for 10 minutes. · Week 3-4: 1 minute + 1 minute, for 15 minutes. · After that: 2 minutes + 1 minute, for 20 minutes.",
   "dica": "One of the biggest burns per minute, and a rope is very cheap. Jump low, just enough to clear the rope.",
   "prompt": "Square ultra-realistic photograph of a person skipping with a jump rope, mid-jump, athletic wear, home or gym, motion, no text, no writing, 1:1 square."},
  {"nome": "HIIT (Tabata)", "img": 181, "onde": "Home or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "4 exercises (jumping jacks, squats, running in place, plank): 20 seconds hard + 10 seconds rest on each, 4 rounds. Start with 10 minutes and reach 20.",
   "dica": "Short and intense. The body keeps burning fat for hours afterward. 2 to 3 times a week already gets results.",
   "prompt": "Square ultra-realistic photograph of a person doing an intense bodyweight interval workout on a mat, sweating, athletic wear, no text, no writing, 1:1 square."},
  {"nome": "Climbing Stairs", "img": 182, "onde": "Building, plaza or stair machine", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: go up and down for 5 minutes, rest, repeat 3 times. · After that: blocks of 8 to 10 minutes. Always go down slowly to spare the knee.",
   "dica": "It works the legs and backside hard while burning fat. Use the handrail to go down safely.",
   "prompt": "Square ultra-realistic photograph of a person climbing a flight of stairs for exercise, athletic wear, motion, daylight, no text, no writing, 1:1 square."},
  {"nome": "Jumping Jack", "img": 183, "onde": "Home or gym", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds + 30 seconds rest, 8 rounds. · Week 3-4: 45 seconds + 20 seconds. · After that: 1 minute + 20 seconds, 10 rounds.",
   "dica": "Great warm-up and burn at the same time. Open your arms and legs together, at a steady rhythm.",
   "prompt": "Square ultra-realistic photograph of a person doing a jumping jack, arms and legs spread mid-air, on a mat at home, motion, no text, no writing, 1:1 square."},
  {"nome": "Burpee", "img": 184, "onde": "Home or gym", "gasto": "~350 calories in 30 minutes",
   "plano": "Week 1-2: 5 burpees, rest, 4 rounds (skip the jump if you need to). · After that: 8 to 10 per round, with the jump.",
   "dica": "Squat, plant your hands, kick your legs back, come back and jump. It is intense and works the whole body — go at your own pace.",
   "prompt": "Square ultra-realistic photograph of a person doing a burpee exercise on a mat, dynamic movement, athletic wear, home gym, no text, no writing, 1:1 square."},
  {"nome": "Running in Place (High Knees)", "img": 185, "onde": "Home", "gasto": "~250 calories in 30 minutes",
   "plano": "Week 1-2: 30 seconds + 30 seconds rest, 8 times. · After that: 1 minute + 30 seconds, 10 times.",
   "dica": "Run in place lifting your knees high. It fits in any little corner, without leaving home.",
   "prompt": "Square ultra-realistic photograph of a person running in place with high knees at home, athletic wear, motion, bright room, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Classes and Dance", "tipo": "exercicio",
 "intro": "People who have fun do not quit. They burn lots of fat without feeling like a sacrifice.",
 "itens": [
  {"nome": "Dance (Zumba, Rhythms)", "img": 186, "onde": "Home or gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Start with 20 minutes following videos or a class and reach 45-60 minutes. 3 to 5 times a week.",
   "dica": "It hardly feels like exercise. Pick songs you love and do not stop moving — the sweat comes on its own.",
   "prompt": "Square ultra-realistic photograph of a person dancing energetically in a dance fitness workout, bright studio, motion, no text, no writing, 1:1 square."},
  {"nome": "Boxing / Muay Thai", "img": 187, "onde": "Gym or a bag at home", "gasto": "~350 calories in 30 minutes",
   "plano": "1 class a week up to 3; or 3 rounds of 2 minutes on the bag, adding rounds gradually.",
   "dica": "It releases stress and burns a lot. The technique comes with the classes — you do not need to arrive knowing it.",
   "prompt": "Square ultra-realistic photograph of a person hitting a punching bag in a boxing workout, gloves, gym, dynamic, no text, no writing, 1:1 square."},
  {"nome": "Step Class", "img": 188, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "1 class a week up to 3, following the choreography on the platform.",
   "dica": "You step up and down from a platform to the beat of the music. It works the legs and stamina hard.",
   "prompt": "Square ultra-realistic photograph of a person doing a step aerobics workout on a step platform, gym studio, motion, no text, no writing, 1:1 square."},
  {"nome": "Mini Trampoline (Jump)", "img": 189, "onde": "Gym or home", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 15 minutes. · After that: 30 to 40 minutes of class.",
   "dica": "Fun and low impact on the joints. Keep your core firm to hold your balance.",
   "prompt": "Square ultra-realistic photograph of a person jumping on a small fitness trampoline, athletic wear, bright studio, motion, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Gym Cardio Machines", "tipo": "exercicio",
 "intro": "They burn lots of fat with low impact and let you control resistance, time and intensity.",
 "itens": [
  {"nome": "Elliptical (Cross-Trainer)", "img": 190, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 20 minutes at light resistance. · Week 3-4: 30 minutes, raising the resistance. · After that: 40 minutes alternating 2 minutes hard + 3 minutes easy.",
   "dica": "It moves your arms and legs at the same time, with zero impact. Great for anyone whose knees hurt when running.",
   "prompt": "Square ultra-realistic photograph of a person using an elliptical cross-trainer machine in a bright gym, athletic wear, no text, no writing, 1:1 square."},
  {"nome": "Rowing Machine", "img": 191, "onde": "Gym", "gasto": "~300 calories in 30 minutes",
   "plano": "Week 1-2: 5 minutes rowing + rest, 3 times. · After that: 20 to 30 continuous minutes, focusing on technique.",
   "dica": "It works almost every muscle at once. The power comes from the legs pushing, not just the arms pulling.",
   "prompt": "Square ultra-realistic photograph of a person using an indoor rowing machine in a gym, mid-stroke, athletic wear, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Strength Training at the Gym", "tipo": "exercicio",
 "intro": "Muscle burns calories even at rest. Lifting speeds up the metabolism and keeps the skin from sagging.",
 "itens": [
  {"nome": "Full Body Workout (Beginner)", "img": 192, "onde": "Gym", "gasto": "~200 calories in 30 minutes",
   "plano": "3 times a week, 1 exercise for each area: legs, back, chest, shoulders and belly. 3 sets of 12. Every 2 weeks, add a little weight.",
   "dica": "At first, focus on learning the right movement with light weight. Ask the instructor to set it up and correct you — it prevents injury.",
   "prompt": "Square ultra-realistic photograph of a person doing a full body strength workout with dumbbells in a gym, focused, bright interior, no text, no writing, 1:1 square."},
  {"nome": "Legs and Glutes Workout", "img": 193, "onde": "Gym", "gasto": "~250 calories in 30 minutes",
   "plano": "1 to 2 times a week: squat, leg press, leg extension and hip thrust. 3 to 4 sets of 12 to 15.",
   "dica": "The legs are the biggest muscles in the body — training them burns lots of energy and helps you slim down faster.",
   "prompt": "Square ultra-realistic photograph of a person doing a leg press or squat in a gym, focused, athletic wear, bright interior, no text, no writing, 1:1 square."},
  {"nome": "Arms, Back and Chest Workout", "img": 194, "onde": "Gym", "gasto": "~180 calories in 30 minutes",
   "plano": "1 to 2 times a week: lat pulldown, row, bench press and shoulder press. 3 sets of 12.",
   "dica": "Strengthening the upper body improves posture and shapes the body while the fat comes off.",
   "prompt": "Square ultra-realistic photograph of a person doing a lat pulldown or bench press in a gym, focused, athletic wear, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Strength at Home (No Equipment)", "tipo": "exercicio",
 "intro": "No gym and no weights: your own body is the load. Build a circuit and gain muscle at home.",
 "itens": [
  {"nome": "Squat", "img": 195, "onde": "Home", "gasto": "legs and glutes",
   "plano": "Week 1-2: 3 sets of 10. · Week 3-4: 3 sets of 15. · After that: hold a heavy object (water jug, backpack) to add load.",
   "dica": "Lower as if sitting in a chair, knees in line with your feet, spine straight. It is the king of leg exercises.",
   "prompt": "Square ultra-realistic photograph of a person doing a bodyweight squat on a mat at home, proper form, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Push-Up", "img": 196, "onde": "Home", "gasto": "chest, arms and core",
   "plano": "Week 1-2: with your knees on the floor, 3 sets of 8. · Week 3-4: 3 sets of 12. · After that: with your legs straight.",
   "dica": "If it is still hard, rest your hands on a table or wall. What matters is starting from where you can.",
   "prompt": "Square ultra-realistic photograph of a person doing a push-up on a mat at home, straight body, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Lunge", "img": 197, "onde": "Home", "gasto": "legs and balance",
   "plano": "Week 1-2: 3 sets of 8 with each leg. · After that: 3 sets of 12, and then holding a weight in your hands.",
   "dica": "Step forward and bend both knees until the back one almost touches the floor. It works one leg at a time.",
   "prompt": "Square ultra-realistic photograph of a person doing a forward lunge on a mat at home, proper form, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Plank and Crunch", "img": 198, "onde": "Home", "gasto": "whole belly",
   "plano": "Hold the plank 20 to 40 seconds, 3 times, and do 3 sets of 15 crunches. (See the Bonus 2 Pilates for more core options.)",
   "dica": "Strengthening the belly makes it firmer and improves posture. Combine it with cardio to see the difference.",
   "prompt": "Square ultra-realistic photograph of a person holding a forearm plank on a mat at home, straight body, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Resistance Band", "img": 199, "onde": "Home", "gasto": "whole body",
   "plano": "3 sets of 12 to 15 on each movement (squat, row, curl, leg openers). Switch to a stronger band when it gets easy.",
   "dica": "Cheap and it fits in a suitcase. It replaces the gym weights at home and is great for the arms and back.",
   "prompt": "Square ultra-realistic photograph of a person exercising with a resistance band at home, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Step-Up", "img": 200, "onde": "Home", "gasto": "legs and glutes",
   "plano": "Week 1-2: 3 sets of 10 with each leg. · After that: 3 sets of 15, and then holding a weight.",
   "dica": "Step up and down from a sturdy step or chair. It is cardio and strength at once, and works the backside hard.",
   "prompt": "Square ultra-realistic photograph of a person doing step-ups onto a sturdy bench or step at home, athletic wear, bright room, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Movement in Daily Life", "tipo": "habito", "img": 201,
 "intro": "It is not only the workout that burns calories. These habits raise your daily burn all day long, without setting aside time for it.",
 "prompt": "Square ultra-realistic photograph of a person taking the stairs and walking outdoors in daily life, active lifestyle, daylight, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Aim for 8,000 steps a day", "desc": "Use your phone to count. Having a number to hit makes you walk a lot more without noticing."},
  {"titulo": "Take the stairs instead of the elevator", "desc": "Small choices like this add up to a lot of energy burned by the end of the day."},
  {"titulo": "Park farther away or get off one stop earlier", "desc": "Add steps to your day without having to set aside a special time to walk."},
  {"titulo": "Stand up every hour if you work sitting down", "desc": "Sitting still for a long time slows the body down. Stand up, stretch and walk a little."},
  {"titulo": "Walk while you talk on the phone", "desc": "Turn still time into moving time, with no extra effort."},
  {"titulo": "Do your housework with energy", "desc": "Cleaning, cooking and tidying also burn calories — treat them as movement, not just a chore."},
 ],
},
{
 "tema": "Food and Portions", "tipo": "habito", "img": 202,
 "intro": "No workout makes up for out-of-control eating. These habits, with the book's recipes, are what truly make the fat come off.",
 "prompt": "Square ultra-realistic photograph of a balanced healthy plate with grilled protein, vegetables and a small portion of rice, a glass of water, on a light table, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Have protein at every meal", "desc": "Egg, chicken, fish, lean meat or beans. It is the nutrient that fills you most and preserves muscle while you lose fat."},
  {"titulo": "Start your plate with salad and vegetables", "desc": "They fill your stomach for few calories, so you eat less of the rest without going hungry."},
  {"titulo": "Use smaller plates and serve yourself once", "desc": "Decide the portion before you eat. The same food looks like more on a small plate and you feel satisfied with less."},
  {"titulo": "Do not drink your calories", "desc": "Soda and boxed juice are pure sugar and do not fill you. Choose water, tea or the book's detox drinks."},
  {"titulo": "Do not eat straight from the package", "desc": "Portion it into a bowl. Eating from the package, you lose track and eat far more than you need."},
  {"titulo": "Eat slowly and chew well", "desc": "The brain takes about 20 minutes to signal that you are satisfied. Eating fast makes you overeat."},
  {"titulo": "Do not skip meals", "desc": "Built-up hunger leads to overeating at the next meal. Eating on schedule prevents losing control."},
  {"titulo": "Keep healthy snacks ready", "desc": "Fruit, plain yogurt or a handful of nuts save you from emergency hunger without falling into junk."},
 ],
},
{
 "tema": "Water, Sleep and Rest", "tipo": "habito", "img": 203,
 "intro": "It is during rest that the body transforms. Sleeping poorly and living dehydrated sabotages any diet.",
 "prompt": "Square ultra-realistic photograph of a peaceful bedroom with a person sleeping well and a glass of water on the nightstand, calm evening light, restful mood, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Drink at least 8 glasses of water a day", "desc": "The body confuses thirst with hunger. Well hydrated, you snack less and your metabolism works better."},
  {"titulo": "Start the day with a glass of water", "desc": "After hours of sleep, the body wakes up dehydrated. Water wakes up the system."},
  {"titulo": "Sleep 7 to 8 hours a night", "desc": "Poorly slept nights increase hunger and the sweet craving the next day. Sleeping well also helps you lose weight."},
  {"titulo": "Have a chamomile tea at night (Recipe 147)", "desc": "It helps you relax and fall asleep, improving rest and appetite control."},
  {"titulo": "Rest at least one day a week", "desc": "Muscle grows and the body recovers during rest. Training every day without stopping hurts your results."},
  {"titulo": "Stretch when you wake up and after workouts", "desc": "It improves flexibility, prevents soreness and prepares the body to move more during the day."},
 ],
},
]
