# -*- coding: utf-8 -*-
"""BÔNUS 3 — 50 HÁBITOS E EXERCÍCIOS.
50 itens: 30 EXERCÍCIOS reais com progressão + 20 HÁBITOS úteis. Numeração 1..50.
⭐ CADA EXERCÍCIO tem a SUA foto (card individual): fotos 171-200.
   Os hábitos vêm em 3 seções, cada uma com 1 foto de tema: 201-203.
Estrutura:
  tema exercicio: {tema, intro, tipo:'exercicio', itens:[{nome,onde,gasto,plano,dica,img}]}
  tema habito:    {tema, intro, tipo:'habito', img, itens:[{titulo,desc}]}
"""

TEMAS = [
{
 "tema": "Caminhada e Corrida", "tipo": "exercicio",
 "intro": "O jeito mais simples e barato de queimar gordura — na rua, no parque ou na esteira.",
 "itens": [
  {"nome": "Caminhada", "img": 171, "onde": "Rua, parque ou esteira", "gasto": "~150 calorias em 30 minutos",
   "plano": "Semana 1-2: 2 km em ritmo confortável, 4 a 5 vezes na semana. · Semana 3-4: 3 km, acelerando o passo. · Semana 5-6: 4 km, com subidas ou inclinação 3% na esteira. · Semana 7+: 5 km ou 45 minutos em ritmo forte.",
   "dica": "Mantenha um ritmo em que dá para conversar, mas com esforço. Na esteira, use inclinação leve para gastar mais sem correr.",
   "prompt": "Square ultra-realistic photograph of a person walking briskly on a park path in athletic wear, morning light, motion, healthy lifestyle, no text, no writing, 1:1 square."},
  {"nome": "Caminhada Acelerada (Power Walk)", "img": 172, "onde": "Rua ou esteira", "gasto": "~200 calorias em 30 minutos",
   "plano": "Depois de firmar os 5 km, alterne 3 minutos em ritmo forte + 2 minutos normal, por 30 a 40 minutos. Aumente aos poucos os trechos rápidos.",
   "dica": "Bombeie os braços dobrados a 90 graus e dê passos firmes. Gasta quase como um trote, sem impacto nos joelhos.",
   "prompt": "Square ultra-realistic photograph of a person power walking fast with arms bent, athletic wear, outdoor path, motion, no text, no writing, 1:1 square."},
  {"nome": "Trote (Método Caminhar-Correr)", "img": 173, "onde": "Rua, parque ou esteira", "gasto": "~250 calorias em 30 minutos",
   "plano": "Semana 1-2: 1 minuto de trote + 2 minutos de caminhada, por 20 minutos. · Semana 3-4: 2 minutos trote + 1 minuto. · Semana 5-6: 3 minutos trote + 1 minuto. · Depois: reduza as pausas até correr contínuo.",
   "dica": "Vá devagar no trote — se ficar sem fôlego, diminua. É assim que o corpo aprende a correr sem sofrimento.",
   "prompt": "Square ultra-realistic photograph of a person lightly jogging on a park path, relaxed pace, athletic wear, daylight, no text, no writing, 1:1 square."},
  {"nome": "Corrida Contínua", "img": 174, "onde": "Rua, parque ou esteira", "gasto": "~300 calorias em 30 minutos",
   "plano": "Quando aguentar 20 minutos correndo sem parar, aumente 5 minutos por semana até chegar a 40-45 minutos. Uma vez por semana, faça um trecho mais rápido.",
   "dica": "Um bom tênis faz toda a diferença nos joelhos. Corra em ritmo que dê para respirar pelo nariz na maior parte do tempo.",
   "prompt": "Square ultra-realistic photograph of a person running outdoors on a road or park, steady pace, athletic wear, dynamic motion, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Pedalar", "tipo": "exercicio",
 "intro": "Queima muita gordura e pega leve nos joelhos — ideal para quem tem sobrepeso.",
 "itens": [
  {"nome": "Bicicleta ao Ar Livre", "img": 175, "onde": "Rua, ciclovia ou parque", "gasto": "~250 calorias em 30 minutos",
   "plano": "Semana 1-2: 20 minutos em terreno plano. · Semana 3-4: 30 minutos, com pequenas subidas. · Semana 5+: 40 a 60 minutos, variando o ritmo.",
   "dica": "Ajuste o selim: a perna quase estica no pedal embaixo. Isso protege o joelho e você pedala por mais tempo.",
   "prompt": "Square ultra-realistic photograph of a person riding a road bike outdoors on a cycle path, athletic wear, daylight, motion, no text, no writing, 1:1 square."},
  {"nome": "Bicicleta Ergométrica", "img": 176, "onde": "Casa ou academia", "gasto": "~250 calorias em 30 minutos",
   "plano": "Semana 1-2: 20 minutos em carga leve. · Semana 3-4: 30 minutos, aumentando a resistência. · Depois: 40 minutos alternando 2 minutos pesado + 3 minutos leve.",
   "dica": "Perfeita para dias de chuva. Aumente a carga aos poucos para não pedalar 'no vazio'.",
   "prompt": "Square ultra-realistic photograph of a person exercising on a stationary bike at home, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Spinning", "img": 177, "onde": "Academia", "gasto": "~350 calorias em 30 minutos",
   "plano": "Comece com 1 aula por semana e vá até 2 ou 3. Acompanhe o professor, mas respeite o seu limite na carga.",
   "dica": "Uma das aulas que mais queimam calorias. Beba água durante e comece com carga menor — evolua no seu tempo.",
   "prompt": "Square ultra-realistic photograph of a person in a spinning class on an indoor cycling bike, gym studio, focused, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Natação e Exercícios na Água", "tipo": "exercicio",
 "intro": "A água sustenta o peso do corpo, então quase não há impacto — ótimo para quem tem dor nas articulações.",
 "itens": [
  {"nome": "Natação", "img": 178, "onde": "Piscina", "gasto": "~300 calorias em 30 minutos",
   "plano": "Semana 1-2: nade 20 minutos com pausas nas bordas. · Semana 3-4: reduza as pausas, chegue a 30 minutos. · Depois: 40 minutos contínuos, variando os estilos.",
   "dica": "Trabalha o corpo inteiro sem sobrecarregar joelhos e coluna. Uma ou duas aulas ajudam muito na respiração.",
   "prompt": "Square ultra-realistic photograph of a person swimming freestyle laps in a clean pool, splashing water, bright light, no text, no writing, 1:1 square."},
  {"nome": "Hidroginástica", "img": 179, "onde": "Piscina", "gasto": "~200 calorias em 30 minutos",
   "plano": "1 a 3 aulas por semana. A intensidade sobe conforme você faz os movimentos com mais força contra a água.",
   "dica": "Feita com energia, queima bastante e fortalece as pernas com zero impacto. Excelente para grandes sobrepesos.",
   "prompt": "Square ultra-realistic photograph of people doing water aerobics in a pool, active movement, bright daylight, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Treino Intervalado (Queima Rápida)", "tipo": "exercicio",
 "intro": "Pouco tempo, muito resultado: alterna esforço forte com descanso curto. Queima gordura durante e horas depois.",
 "itens": [
  {"nome": "Pular Corda", "img": 180, "onde": "Casa, quintal ou academia", "gasto": "~350 calorias em 30 minutos",
   "plano": "Semana 1-2: 30 segundos pulando + 1 minuto descanso, por 10 minutos. · Semana 3-4: 1 minuto + 1 minuto, por 15 minutos. · Depois: 2 minutos + 1 minuto, por 20 minutos.",
   "dica": "Uma das maiores queimas por minuto, e a corda é baratíssima. Pule baixo, só o suficiente para passar a corda.",
   "prompt": "Square ultra-realistic photograph of a person skipping with a jump rope, mid-jump, athletic wear, home or gym, motion, no text, no writing, 1:1 square."},
  {"nome": "HIIT (Tabata)", "img": 181, "onde": "Casa ou academia", "gasto": "~350 calorias em 30 minutos",
   "plano": "4 exercícios (polichinelo, agachamento, corrida parada, prancha): 20 segundos forte + 10 segundos pausa em cada, 4 rodadas. Comece com 10 minutos e chegue a 20.",
   "dica": "Curto e intenso. O corpo continua queimando gordura horas depois. 2 a 3 vezes por semana já dá resultado.",
   "prompt": "Square ultra-realistic photograph of a person doing an intense bodyweight interval workout on a mat, sweating, athletic wear, no text, no writing, 1:1 square."},
  {"nome": "Subir Escadas", "img": 182, "onde": "Prédio, praça ou máquina de escada", "gasto": "~300 calorias em 30 minutos",
   "plano": "Semana 1-2: suba e desça 5 minutos, descanse, repita 3 vezes. · Depois: blocos de 8 a 10 minutos. Desça sempre devagar para poupar o joelho.",
   "dica": "Trabalha muito as pernas e o bumbum enquanto queima gordura. Use o corrimão para descer com segurança.",
   "prompt": "Square ultra-realistic photograph of a person climbing a flight of stairs for exercise, athletic wear, motion, daylight, no text, no writing, 1:1 square."},
  {"nome": "Polichinelo (Jumping Jack)", "img": 183, "onde": "Casa ou academia", "gasto": "~250 calorias em 30 minutos",
   "plano": "Semana 1-2: 30 segundos + 30 segundos descanso, 8 rodadas. · Semana 3-4: 45 segundos + 20 segundos. · Depois: 1 minuto + 20 segundos, 10 rodadas.",
   "dica": "Ótimo aquecimento e queima ao mesmo tempo. Abra braços e pernas juntos, num ritmo constante.",
   "prompt": "Square ultra-realistic photograph of a person doing a jumping jack, arms and legs spread mid-air, on a mat at home, motion, no text, no writing, 1:1 square."},
  {"nome": "Burpee", "img": 184, "onde": "Casa ou academia", "gasto": "~350 calorias em 30 minutos",
   "plano": "Semana 1-2: 5 burpees, descanse, 4 rodadas (sem o salto se precisar). · Depois: 8 a 10 por rodada, com salto.",
   "dica": "Agacha, apoia as mãos, joga as pernas para trás, volta e pula. É intenso e trabalha o corpo todo — vá no seu ritmo.",
   "prompt": "Square ultra-realistic photograph of a person doing a burpee exercise on a mat, dynamic movement, athletic wear, home gym, no text, no writing, 1:1 square."},
  {"nome": "Corrida Estacionária (Joelhos Altos)", "img": 185, "onde": "Casa", "gasto": "~250 calorias em 30 minutos",
   "plano": "Semana 1-2: 30 segundos + 30 segundos descanso, 8 vezes. · Depois: 1 minuto + 30 segundos, 10 vezes.",
   "dica": "Corra no lugar levantando bem os joelhos. Cabe em qualquer cantinho, sem sair de casa.",
   "prompt": "Square ultra-realistic photograph of a person running in place with high knees at home, athletic wear, motion, bright room, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Aulas e Dança", "tipo": "exercicio",
 "intro": "Quem se diverte não desiste. Queimam muita gordura sem parecer sacrifício.",
 "itens": [
  {"nome": "Dança (Zumba, Ritmos)", "img": 186, "onde": "Casa ou academia", "gasto": "~300 calorias em 30 minutos",
   "plano": "Comece com 20 minutos seguindo vídeos ou aula e chegue a 45-60 minutos. 3 a 5 vezes por semana.",
   "dica": "Nem parece exercício. Escolha músicas que você ama e não pare de se mexer — o suor vem sozinho.",
   "prompt": "Square ultra-realistic photograph of a person dancing energetically in a dance fitness workout, bright studio, motion, no text, no writing, 1:1 square."},
  {"nome": "Boxe / Muay Thai", "img": 187, "onde": "Academia ou saco em casa", "gasto": "~350 calorias em 30 minutos",
   "plano": "1 aula por semana até 3; ou 3 rounds de 2 minutos no saco, aumentando os rounds aos poucos.",
   "dica": "Descarrega o estresse e queima muito. A técnica vem com as aulas — não precisa chegar sabendo.",
   "prompt": "Square ultra-realistic photograph of a person hitting a punching bag in a boxing workout, gloves, gym, dynamic, no text, no writing, 1:1 square."},
  {"nome": "Aula de Step", "img": 188, "onde": "Academia", "gasto": "~300 calorias em 30 minutos",
   "plano": "1 aula por semana até 3, acompanhando a coreografia na plataforma.",
   "dica": "Sobe e desce de uma plataforma no ritmo da música. Trabalha muito as pernas e o fôlego.",
   "prompt": "Square ultra-realistic photograph of a person doing a step aerobics workout on a step platform, gym studio, motion, no text, no writing, 1:1 square."},
  {"nome": "Cama Elástica (Jump)", "img": 189, "onde": "Academia ou casa", "gasto": "~300 calorias em 30 minutos",
   "plano": "Semana 1-2: 15 minutos. · Depois: 30 a 40 minutos de aula.",
   "dica": "Divertido e de baixo impacto nas juntas. Segure o abdômen firme para manter o equilíbrio.",
   "prompt": "Square ultra-realistic photograph of a person jumping on a small fitness trampoline, athletic wear, bright studio, motion, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Máquinas de Cardio da Academia", "tipo": "exercicio",
 "intro": "Queimam muita gordura com baixo impacto e deixam você controlar carga, tempo e intensidade.",
 "itens": [
  {"nome": "Elíptico (Transport)", "img": 190, "onde": "Academia", "gasto": "~300 calorias em 30 minutos",
   "plano": "Semana 1-2: 20 minutos em carga leve. · Semana 3-4: 30 minutos, subindo a resistência. · Depois: 40 minutos alternando 2 minutos forte + 3 minutos leve.",
   "dica": "Mexe braços e pernas ao mesmo tempo, com zero impacto. Ótimo para quem sente dor nos joelhos ao correr.",
   "prompt": "Square ultra-realistic photograph of a person using an elliptical cross-trainer machine in a bright gym, athletic wear, no text, no writing, 1:1 square."},
  {"nome": "Máquina de Remo", "img": 191, "onde": "Academia", "gasto": "~300 calorias em 30 minutos",
   "plano": "Semana 1-2: 5 minutos remando + descanso, 3 vezes. · Depois: 20 a 30 minutos contínuos, focando na técnica.",
   "dica": "Trabalha quase todos os músculos de uma vez. A força vem das pernas empurrando, não só dos braços puxando.",
   "prompt": "Square ultra-realistic photograph of a person using an indoor rowing machine in a gym, mid-stroke, athletic wear, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Musculação na Academia", "tipo": "exercicio",
 "intro": "Músculo queima calorias até parado. Fazer força acelera o metabolismo e evita que a pele fique flácida.",
 "itens": [
  {"nome": "Treino do Corpo Inteiro (Iniciante)", "img": 192, "onde": "Academia", "gasto": "~200 calorias em 30 minutos",
   "plano": "3 vezes por semana, 1 exercício para cada parte: pernas, costas, peito, ombro e abdômen. 3 séries de 12. A cada 2 semanas, aumente um pouco a carga.",
   "dica": "No começo, foque em aprender o movimento certo com carga leve. Peça o professor para montar e corrigir — evita lesão.",
   "prompt": "Square ultra-realistic photograph of a person doing a full body strength workout with dumbbells in a gym, focused, bright interior, no text, no writing, 1:1 square."},
  {"nome": "Treino de Pernas e Glúteos", "img": 193, "onde": "Academia", "gasto": "~250 calorias em 30 minutos",
   "plano": "1 a 2 vezes por semana: agachamento, leg press, cadeira extensora e elevação de quadril. 3 a 4 séries de 12 a 15.",
   "dica": "As pernas são os maiores músculos do corpo — treiná-las gasta muita energia e ajuda a secar mais rápido.",
   "prompt": "Square ultra-realistic photograph of a person doing a leg press or squat in a gym, focused, athletic wear, bright interior, no text, no writing, 1:1 square."},
  {"nome": "Treino de Braços, Costas e Peito", "img": 194, "onde": "Academia", "gasto": "~180 calorias em 30 minutos",
   "plano": "1 a 2 vezes por semana: puxada, remada, supino e desenvolvimento de ombro. 3 séries de 12.",
   "dica": "Fortalecer a parte de cima melhora a postura e desenha o corpo enquanto a gordura vai saindo.",
   "prompt": "Square ultra-realistic photograph of a person doing a lat pulldown or bench press in a gym, focused, athletic wear, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Força em Casa (Sem Aparelho)", "tipo": "exercicio",
 "intro": "Sem academia e sem peso: o próprio corpo é a carga. Monte um circuito e ganhe músculo em casa.",
 "itens": [
  {"nome": "Agachamento", "img": 195, "onde": "Casa", "gasto": "pernas e glúteos",
   "plano": "Semana 1-2: 3 séries de 10. · Semana 3-4: 3 séries de 15. · Depois: segure um objeto pesado (galão de água, mochila) para aumentar a carga.",
   "dica": "Desça como se fosse sentar numa cadeira, joelhos na direção dos pés, coluna reta. É o rei dos exercícios de perna.",
   "prompt": "Square ultra-realistic photograph of a person doing a bodyweight squat on a mat at home, proper form, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Flexão de Braço", "img": 196, "onde": "Casa", "gasto": "peito, braços e core",
   "plano": "Semana 1-2: com os joelhos no chão, 3 séries de 8. · Semana 3-4: 3 séries de 12. · Depois: com as pernas esticadas.",
   "dica": "Se ainda for difícil, apoie as mãos numa mesa ou parede. O importante é começar de onde você consegue.",
   "prompt": "Square ultra-realistic photograph of a person doing a push-up on a mat at home, straight body, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Afundo (Passada)", "img": 197, "onde": "Casa", "gasto": "pernas e equilíbrio",
   "plano": "Semana 1-2: 3 séries de 8 com cada perna. · Depois: 3 séries de 12, e depois segurando um peso nas mãos.",
   "dica": "Dê um passo à frente e dobre os dois joelhos até o de trás quase tocar o chão. Trabalha uma perna por vez.",
   "prompt": "Square ultra-realistic photograph of a person doing a forward lunge on a mat at home, proper form, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Prancha e Abdominal", "img": 198, "onde": "Casa", "gasto": "abdômen inteiro",
   "plano": "Segure a prancha 20 a 40 segundos, 3 vezes, e faça 3 séries de 15 abdominais. (Veja o Bônus 2 de Pilates para mais opções de core.)",
   "dica": "Fortalecer o abdômen deixa a barriga mais firme e melhora a postura. Combine com o cardio para ver a diferença.",
   "prompt": "Square ultra-realistic photograph of a person holding a forearm plank on a mat at home, straight body, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Faixa Elástica", "img": 199, "onde": "Casa", "gasto": "corpo inteiro",
   "plano": "3 séries de 12 a 15 em cada movimento (agachamento, remada, rosca, abrir as pernas). Troque por uma faixa mais forte quando ficar fácil.",
   "dica": "Barata e cabe na mala. Substitui os pesos da academia em casa e é ótima para os braços e as costas.",
   "prompt": "Square ultra-realistic photograph of a person exercising with a resistance band at home, athletic wear, bright room, no text, no writing, 1:1 square."},
  {"nome": "Subida no Banco (Step-up)", "img": 200, "onde": "Casa", "gasto": "pernas e glúteos",
   "plano": "Semana 1-2: 3 séries de 10 com cada perna. · Depois: 3 séries de 15, e depois segurando peso.",
   "dica": "Suba e desça de um degrau ou cadeira firme. É cardio e força ao mesmo tempo, e trabalha muito o bumbum.",
   "prompt": "Square ultra-realistic photograph of a person doing step-ups onto a sturdy bench or step at home, athletic wear, bright room, no text, no writing, 1:1 square."},
 ],
},
{
 "tema": "Movimento no Dia a Dia", "tipo": "habito", "img": 201,
 "intro": "Não é só o treino que queima calorias. Estes hábitos aumentam o seu gasto o dia inteiro, sem separar um tempo para isso.",
 "prompt": "Square ultra-realistic photograph of a person taking the stairs and walking outdoors in daily life, active lifestyle, daylight, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Tenha a meta de 8 mil passos por dia", "desc": "Use o celular para contar. Ter um número para bater faz você andar bem mais sem perceber."},
  {"titulo": "Suba escadas em vez de usar o elevador", "desc": "Pequenas escolhas assim somam bastante gasto de energia no fim do dia."},
  {"titulo": "Estacione mais longe ou desça um ponto antes", "desc": "Some passos ao seu dia sem precisar separar um tempo especial para caminhar."},
  {"titulo": "Levante-se a cada 1 hora se trabalha sentado", "desc": "Ficar muito tempo parado desacelera o corpo. Levante, estique-se e ande um pouco."},
  {"titulo": "Caminhe enquanto fala ao telefone", "desc": "Transforme um tempo parado num tempo em movimento, sem esforço extra."},
  {"titulo": "Faça as tarefas de casa com energia", "desc": "Limpar, cozinhar e arrumar também queimam calorias — encare como movimento, não só obrigação."},
 ],
},
{
 "tema": "Alimentação e Porções", "tipo": "habito", "img": 202,
 "intro": "Nenhum treino compensa uma alimentação descontrolada. Estes hábitos, com as receitas do livro, fazem a gordura sair de verdade.",
 "prompt": "Square ultra-realistic photograph of a balanced healthy plate with grilled protein, vegetables and a small portion of rice, a glass of water, on a light table, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Tenha proteína em todas as refeições", "desc": "Ovo, frango, peixe, carne magra ou feijão. É o nutriente que mais sacia e preserva o músculo enquanto você perde gordura."},
  {"titulo": "Comece o prato pela salada e pelos vegetais", "desc": "Eles enchem o estômago com poucas calorias, então você come menos do resto sem passar fome."},
  {"titulo": "Use pratos menores e sirva uma vez só", "desc": "Decida a porção antes de comer. A mesma comida parece mais num prato pequeno e você se satisfaz com menos."},
  {"titulo": "Não beba as suas calorias", "desc": "Refrigerante e suco de caixinha são açúcar puro e não saciam. Prefira água, chá ou os sucos detox do livro."},
  {"titulo": "Não coma direto do pacote", "desc": "Porcione numa tigela. Comendo do pacote, você perde a noção e come muito mais do que precisa."},
  {"titulo": "Coma devagar e mastigue bem", "desc": "O cérebro leva cerca de 20 minutos para avisar que você está satisfeito. Comer rápido faz comer demais."},
  {"titulo": "Não pule refeições", "desc": "A fome acumulada leva ao exagero na refeição seguinte. Comer nos horários evita o descontrole."},
  {"titulo": "Tenha lanches saudáveis já prontos", "desc": "Fruta, iogurte natural ou um punhado de castanhas salvam você da fome de emergência sem cair na besteira."},
 ],
},
{
 "tema": "Água, Sono e Descanso", "tipo": "habito", "img": 203,
 "intro": "É no descanso que o corpo se transforma. Dormir mal e viver desidratado sabota qualquer dieta.",
 "prompt": "Square ultra-realistic photograph of a peaceful bedroom with a person sleeping well and a glass of water on the nightstand, calm evening light, restful mood, no text, no writing, 1:1 square.",
 "itens": [
  {"titulo": "Beba pelo menos 2 litros de água por dia", "desc": "O corpo confunde sede com fome. Bem hidratado, você belisca menos e o metabolismo funciona melhor."},
  {"titulo": "Comece o dia com um copo de água", "desc": "Depois de horas dormindo, o corpo acorda desidratado. A água desperta o organismo."},
  {"titulo": "Durma de 7 a 8 horas por noite", "desc": "Noites mal dormidas aumentam a fome e a vontade de doce no dia seguinte. Dormir bem também emagrece."},
  {"titulo": "Tome um chá de camomila à noite (Receita 147)", "desc": "Ajuda a relaxar e a pegar no sono, melhorando o descanso e o controle do apetite."},
  {"titulo": "Descanse pelo menos um dia por semana", "desc": "O músculo cresce e o corpo se recupera no descanso. Treinar todo dia sem parar atrapalha o resultado."},
  {"titulo": "Alongue-se ao acordar e depois dos treinos", "desc": "Melhora a flexibilidade, evita dores e prepara o corpo para se mover mais durante o dia."},
 ],
},
]
