# -*- coding: utf-8 -*-
"""30 receitas de CAFÉ DA MANHÃ (001-030). INGLÊS (mercado US).

Tradução literal de `receitas_cafe.py`. Convenções fixadas em GLOSSARIO-TRADUCAO.md:
tratamento por "you", medidas caseiras americanas (cup/tbsp/tsp/pinch/handful/slice),
peso de iogurte e queijo em oz, forno em °F.
⛔ O grama e o mililitro do PT viram XÍCARA e OZ: o leitor americano não pesa
ingrediente de café da manhã. A escada das porcoes8 é preservada com
"1/2 cup + 1 tbsp" em vez de arredondar duas faixas para o mesmo valor.
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/001-030,
sem texto na imagem), e prompt duplicado é prompt que diverge.
porcoes8 na ordem: Mulher 120-155/156-185/186-220/220+ lb · Homem 155-185/186-220/221-265/265+ lb
Metas (kcal): 300/370/420/470 · 450/510/560/620
"""

RECEITAS = [
{
 "nome": "Banana Oat Pancakes",
 "hook": "Three ingredients you already have at home, ready in 10 minutes — and they keep you full until lunch.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 325,
 "ings": ["1 ripe banana", "1/2 cup rolled oats (about 4 tbsp)", "1 egg",
          "1 pinch of cinnamon", "1 pinch of baking powder (optional, makes them fluffier)",
          "a little oil or cooking spray for the pan"],
 "passos": [
   "Peel the banana and put it on a deep plate. Mash it well with a fork until it turns into a smooth purée, with no big lumps.",
   "Add the egg and stir until everything is well mixed.",
   "Add the oats, the cinnamon and the baking powder. Stir and let it rest for 3 minutes — the oats soak up the moisture and the batter firms up, which makes it easier to flip later.",
   "Heat a nonstick pan over medium-low heat and brush it with a little oil (or use spray).",
   "With a spoon, drop small portions of batter into the pan, about the size of half your palm. Small pancakes flip much more easily than big ones.",
   "Let them cook for 2 to 3 minutes, until small bubbles appear on top and the edges set. Flip them carefully and brown the other side for another 1 to 2 minutes.",
   "Serve warm. If you like, finish with banana slices, a handful of berries or 1 tsp of honey."],
 "porcoes8": ["3/4 banana · 1/3 cup oats · 1 egg",
              "1 banana · 1/2 cup oats · 1 egg · 1 handful of berries",
              "1 banana · 1/2 cup + 1 tbsp oats · 1 egg · 1 tsp peanut butter",
              "1 banana · 2/3 cup oats · 1 egg · 1 tbsp peanut butter",
              "1 banana · 2/3 cup oats · 2 eggs · 1 tsp peanut butter",
              "1 large banana · 2/3 cup + 1 tbsp oats · 2 eggs · 1 tbsp peanut butter",
              "1 large banana · 3/4 cup oats · 2 eggs · 1 tbsp peanut butter · berries",
              "1 large banana · 3/4 cup + 2 tbsp oats · 2 eggs · 1.5 tbsp peanut butter"],
 "dica": "Oats are rich in fiber, which slows down digestion and keeps you full for hours — that is what prevents the mid-morning hunger that makes you snack. The banana brings natural sweetness with no added sugar, and the egg brings protein to protect your muscle while you lose fat.",
},
{
 "nome": "Scrambled Eggs with Spinach and Wholegrain Toast",
 "hook": "The classic breakfast that fills the plate with protein and fiber in less than 10 minutes.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["2 eggs", "1 large handful of fresh spinach leaves", "1 slice of wholegrain bread",
          "1 tsp olive oil", "salt and pepper to taste", "1 small tomato (optional)"],
 "passos": [
   "Wash the spinach and drain it well. If the leaves are big, cut them in half.",
   "Crack the eggs into a bowl, season with salt and pepper and beat them lightly with a fork.",
   "Heat the olive oil in a nonstick pan over medium heat. Add the spinach and stir for 1 minute, just until it wilts (the leaves go soft).",
   "Turn the heat down, pour the beaten eggs over the spinach and leave them for 30 seconds without stirring.",
   "With a spatula, push the eggs slowly from the bottom to the center, until they are creamy and still moist. Turn off the heat before they dry out.",
   "Toast the slice of wholegrain bread. Serve the eggs on top or beside it, with tomato slices if you like."],
 "porcoes8": ["1 egg + 1 white · 1/2 slice of bread · spinach, as much as you want",
              "2 eggs · 1 slice of bread · spinach, as much as you want",
              "2 eggs · 1 slice of bread · a little more olive oil",
              "2 eggs + 1 white · 1 slice of bread · 1 tsp grated cheese",
              "3 eggs · 1 slice of bread · 1 tsp olive oil",
              "3 eggs · 2 slices of bread · spinach, as much as you want",
              "3 eggs · 2 slices of bread · 1 tbsp grated cheese",
              "4 eggs · 2 slices of bread · 1 tbsp grated cheese"],
 "dica": "Eggs are a complete protein and very filling — people who eat eggs at breakfast feel less hungry through the day. Spinach adds volume and fiber with almost no calories, so you fill the plate and your stomach without blowing your calories.",
},
{
 "nome": "Greek Yogurt with Berries and Oats",
 "hook": "Built in layers, with no cooking at all — protein and fiber in a pretty glass in 3 minutes.",
 "tempo": "3 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1 cup of plain Greek yogurt with no sugar (about 6 oz)", "1 handful of berries (strawberry, blueberry or raspberry)",
          "3 tbsp rolled oats", "1 tsp honey (optional)", "cinnamon to taste"],
 "passos": [
   "If you use strawberries, wash them and cut them into small pieces. The other berries can go in whole.",
   "In a glass or a cup, put half of the yogurt at the bottom.",
   "Spread half of the berries and half of the oats on top.",
   "Repeat: the rest of the yogurt, then the berries and oats that are left.",
   "Finish with a pinch of cinnamon and, if you like, the drizzle of honey. Serve right away, while the oats are still crunchy."],
 "porcoes8": ["4 oz yogurt · berries · 2 tbsp oats",
              "6 oz yogurt · berries · 3 tbsp oats",
              "6 oz yogurt · berries · 3 tbsp oats · 1 tsp honey",
              "7 oz yogurt · berries · 4 tbsp oats · 1 tsp honey",
              "7 oz yogurt · berries · 4 tbsp oats · 1 tbsp nuts",
              "9 oz yogurt · berries · 4 tbsp oats · 1 tbsp nuts",
              "9 oz yogurt · berries · 5 tbsp oats · 1 tbsp nuts",
              "10 oz yogurt · berries · 6 tbsp oats · 1 tbsp nuts"],
 "dica": "Greek yogurt has almost twice the protein of regular yogurt, which keeps you full longer. With no added sugar, the sweetness comes from the fruit — and the oats bring fiber and crunch, turning a quick snack into a meal that holds you.",
},
{
 "nome": "Egg White Omelette with Tomato and Cottage Cheese",
 "hook": "Light, fluffy and full of protein — the breakfast for anyone who wants to lose weight without going hungry.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["3 egg whites + 1 whole egg", "1 small tomato, chopped", "2 tbsp cottage cheese",
          "chopped chives or parsley", "salt and pepper to taste", "cooking spray"],
 "passos": [
   "Chop the tomato into small cubes and pat off the extra liquid with a paper towel, so the omelette does not go soggy.",
   "In a bowl, put the egg whites, the whole egg, salt and pepper. Beat with a fork for 30 seconds, until it foams lightly.",
   "Heat a nonstick pan over medium heat and spray it with oil. Spread the chopped tomato on the bottom for 1 minute.",
   "Pour the beaten eggs on top and tilt the pan to spread them evenly.",
   "When the edges set (1 to 2 minutes), spread the cottage cheese over half of the omelette.",
   "With the spatula, fold the omelette in half, covering the cottage cheese. Leave it for another minute and serve with the herbs on top."],
 "porcoes8": ["2 whites + 1 egg · 1 tbsp cottage cheese",
              "3 whites + 1 egg · 2 tbsp cottage cheese",
              "3 whites + 1 egg · 2 tbsp cottage cheese · 1/2 slice of bread",
              "3 whites + 1 egg · 3 tbsp cottage cheese · 1 slice of bread",
              "3 whites + 2 eggs · 2 tbsp cottage cheese · 1 slice of bread",
              "4 whites + 2 eggs · 3 tbsp cottage cheese · 1 slice of bread",
              "4 whites + 2 eggs · 3 tbsp cottage cheese · 2 slices of bread",
              "5 whites + 2 eggs · 4 tbsp cottage cheese · 2 slices of bread"],
 "dica": "Egg whites are almost pure protein, with very little fat and very few calories — perfect for raising the protein of your breakfast without weighing it down. The cottage cheese comes in creamy and also rich in protein, and the tomato brings flavor and volume for almost no calories.",
},
{
 "nome": "Overnight Oats with Apple and Cinnamon",
 "hook": "You put it together at night and in the morning it is already waiting in the fridge — no rush, no stove.",
 "tempo": "5 min + fridge", "rende": "1 serving", "kcal_base": 350,
 "ings": ["1/2 cup rolled oats", "2/3 cup milk (or plant drink)", "1/2 apple, cut into small cubes",
          "1 tbsp plain yogurt", "cinnamon to taste", "1 tsp honey (optional)"],
 "passos": [
   "In a jar with a lid, mix the oats, the milk and the yogurt.",
   "Add half of the chopped apple and a good pinch of cinnamon. Stir well.",
   "Close the jar and put it in the fridge for at least 4 hours, or overnight.",
   "In the morning the oats will be creamy and soft. Stir again.",
   "Top with the rest of the fresh apple and more cinnamon. If you like, add the drizzle of honey. Eat it cold, straight from the jar."],
 "porcoes8": ["1/3 cup oats · 1/2 cup milk · 1/2 apple",
              "1/2 cup oats · 2/3 cup milk · 1/2 apple",
              "1/2 cup + 1 tbsp oats · 2/3 cup milk · 1/2 apple · 1 tsp honey",
              "2/3 cup oats · 3/4 cup milk · 1 apple · 1 tsp honey",
              "2/3 cup oats · 3/4 cup milk · 1 apple · 1 tbsp nuts",
              "2/3 cup + 1 tbsp oats · 1 cup milk · 1 apple · 1 tbsp nuts",
              "3/4 cup oats · 1 cup milk · 1 apple · 1 tbsp nuts",
              "3/4 cup + 2 tbsp oats · 1 1/4 cups milk · 1 apple · 1.5 tbsp nuts"],
 "dica": "Soaking the oats does not change the calories, but it makes the fiber easier to digest and the meal creamier and more filling. Since it is ready in the fridge, you do not skip breakfast when you are in a rush — and skipping meals is what makes many people overeat at the end of the day.",
},
{
 "nome": "Avocado Toast with Egg",
 "hook": "Creamy, savory and the kind that really fills you up — ready in 8 minutes.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["1 slice of wholegrain bread", "1/2 ripe avocado (or 1/4 of a large avocado)", "1 egg",
          "juice of 1/2 lemon", "salt, pepper and chili flakes to taste", "cooking spray"],
 "passos": [
   "Toast the slice of wholegrain bread until it is firm and golden.",
   "In a small bowl, mash the avocado with a fork, add the lemon juice, salt and pepper. Mix until it turns into a cream.",
   "Heat a nonstick pan, spray it with oil and fry the egg over medium heat, the way you like it (fried with a runny yolk or scrambled).",
   "Spread the avocado cream over the toast.",
   "Put the egg on top and finish with a pinch of chili flakes. Serve immediately."],
 "porcoes8": ["1/2 slice of bread · 1/4 avocado · 1 egg",
              "1 slice of bread · 1/2 avocado · 1 egg",
              "1 slice of bread · 1/2 avocado · 1 egg · green leaves",
              "1 slice of bread · 1/2 avocado · 2 eggs",
              "1 slice of bread · 1/2 avocado · 2 eggs · green leaves",
              "2 slices of bread · 1/2 avocado · 2 eggs",
              "2 slices of bread · 1 small avocado · 2 eggs",
              "2 slices of bread · 1 small avocado · 3 eggs"],
 "dica": "Avocado has good fat, which keeps you full for a long time and makes the meal creamy without butter. Together with the egg and the wholegrain bread, you have good fat, protein and fiber on the same toast — the combination that holds hunger back for hours.",
},
{
 "nome": "Oat Porridge with Banana and Peanut Butter",
 "hook": "Warm and comforting, the breakfast that tastes like dessert but works in your favor.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["1/2 cup rolled oats", "3/4 cup milk (or plant drink)", "1/2 banana, mashed",
          "1 tsp peanut butter", "cinnamon to taste", "1/2 banana in slices for the top"],
 "passos": [
   "In a small pot, put the oats, the milk and the mashed banana.",
   "Cook over medium-low heat, stirring all the time with a spoon so it does not stick to the bottom.",
   "After 4 to 5 minutes the mixture thickens and turns creamy. If you want it thinner, add a little more milk.",
   "Turn off the heat, add the cinnamon and stir.",
   "Pour it into a bowl, top with the banana slices and the peanut butter. Serve warm."],
 "porcoes8": ["1/3 cup oats · 3/4 cup milk · 1/2 banana · no peanut butter",
              "1/2 cup oats · 3/4 cup milk · 1 banana · 1 tsp peanut butter",
              "1/2 cup + 1 tbsp oats · 3/4 cup milk · 1 banana · 1 tsp peanut butter",
              "2/3 cup oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "2/3 cup oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "2/3 cup + 1 tbsp oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "3/4 cup oats · 1 cup milk · 1 banana · 1.5 tbsp peanut butter",
              "3/4 cup + 2 tbsp oats · 1 1/4 cups milk · 1 banana · 2 tbsp peanut butter"],
 "dica": "Cooked oats form a gel in your stomach that holds hunger back. The banana sweetens with no sugar and gives back energy, and the peanut butter brings good fat and protein — just watch the amount, because it is high in calories: one spoon already does the job.",
},
{
 "nome": "Banana and Berry Smoothie Bowl",
 "hook": "Thick enough for a spoon, cold and colorful — it looks like ice cream, but it works for your weight loss.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1 frozen banana in slices", "1 handful of frozen berries",
          "3 tbsp plain yogurt", "3 tbsp milk (or plant drink)",
          "2 tbsp oats and fresh fruit for the top"],
 "passos": [
   "Use the banana already frozen (cut it into slices the night before and freeze it) — that is what makes the smoothie thick without ice.",
   "In the blender, put the banana, the frozen berries, the yogurt and the milk.",
   "Blend on high (top speed), stopping to stir with a spoon when it gets stuck. Add milk only one spoon at a time, the minimum needed to blend. The texture has to stay thick, like ice cream.",
   "Pour it into a bowl.",
   "Top with the oats and the fresh fruit in neat rows. Eat right away, with a spoon, before it melts."],
 "porcoes8": ["1 banana · berries · 2 tbsp yogurt · 1 tbsp oats",
              "1 banana · berries · 3 tbsp yogurt · 2 tbsp oats",
              "1 banana · berries · 3 tbsp yogurt · 2 tbsp oats · seeds",
              "1 banana · berries · 4 tbsp yogurt · 3 tbsp oats",
              "1 banana · berries · 4 tbsp yogurt · 3 tbsp oats · 1 tbsp nuts",
              "1 large banana · berries · 5 tbsp yogurt · 3 tbsp oats · nuts",
              "1 large banana · berries · 5 tbsp yogurt · 4 tbsp oats · nuts",
              "2 bananas · berries · 6 tbsp yogurt · 4 tbsp oats · nuts"],
 "dica": "Freezing the fruit gives you an ice-cream texture with no sugar and no cream. The yogurt adds protein, and eating with a spoon, slowly, lets your brain register that you are full — very different from drinking a blended juice through a straw in seconds.",
},
{
 "nome": "Boiled Eggs with Avocado and Tomato",
 "hook": "No pan, no mess — protein and good fat on a plate you put together in minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "1/2 avocado", "1 tomato", "juice of 1/2 lemon", "salt, pepper and olive oil to taste",
          "green leaves to taste"],
 "passos": [
   "Put the eggs in a pot, cover them with cold water and put it on the heat. From the moment it boils, count 8 to 9 minutes for a firm yolk.",
   "Meanwhile, cut the avocado and the tomato into slices and arrange them on the plate over some green leaves.",
   "Drain the eggs and run them under cold water for 1 minute — that makes them easier to peel.",
   "Peel the eggs, cut them in half and put them on the plate.",
   "Drizzle everything with the lemon juice and a little olive oil, season with salt and pepper and serve."],
 "porcoes8": ["1 egg · 1/4 avocado · tomato",
              "2 eggs · 1/2 avocado · tomato",
              "2 eggs · 1/2 avocado · tomato · 1/2 slice of bread",
              "2 eggs · 1/2 avocado · tomato · 1 slice of bread",
              "3 eggs · 1/2 avocado · tomato · 1 slice of bread",
              "3 eggs · 1/2 avocado · tomato · 2 slices of bread",
              "3 eggs · 1 small avocado · tomato · 2 slices of bread",
              "4 eggs · 1 small avocado · tomato · 2 slices of bread"],
 "dica": "A boiled egg is the most practical protein there is: you can cook several at once and keep them in the fridge. With avocado and tomato, you put together a complete breakfast of good fat and fiber without turning on the stove in the morning.",
},
{
 "nome": "Protein Oat and Egg White Pancakes",
 "hook": "The pancake for training days: more protein, same simplicity.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["1/2 cup rolled oats", "3 egg whites (or 2 whites + 1 egg)", "1/2 banana, mashed",
          "1 pinch of baking powder", "cinnamon to taste", "cooking spray"],
 "passos": [
   "If you want a smoother batter, blend the oats until they turn into a flour. If you like it rustic, use them as flakes.",
   "In a bowl, mix the oats, the egg whites, the mashed banana, the baking powder and the cinnamon until everything is well mixed.",
   "Let it rest for 3 minutes so the oats take in the moisture.",
   "Heat the nonstick pan over medium-low heat and spray it with oil.",
   "Make small pancakes. Leave them 2 minutes on each side, flipping when small bubbles appear.",
   "Serve with fresh fruit on top. Skip the sugary syrups — the banana already sweetens it."],
 "porcoes8": ["2 whites · 1/3 cup oats · 1/2 banana",
              "3 whites · 1/2 cup oats · 1/2 banana",
              "3 whites · 1/2 cup + 1 tbsp oats · 1/2 banana · fruit",
              "2 whites + 1 egg · 2/3 cup oats · 1 banana",
              "3 whites + 1 egg · 2/3 cup oats · 1 banana",
              "3 whites + 1 egg · 2/3 cup + 1 tbsp oats · 1 banana · fruit",
              "4 whites + 1 egg · 3/4 cup oats · 1 banana · fruit",
              "4 whites + 2 eggs · 3/4 cup + 2 tbsp oats · 1 banana · fruit"],
 "dica": "Swapping part of the eggs for egg whites raises the protein and lowers the fat — good for anyone who wants definition. Protein is also the most filling nutrient, so this pancake holds hunger back with fewer calories than the traditional sweet version.",
},
{
 "nome": "Chia Pudding with Fruit",
 "hook": "You mix it in 2 minutes, the fridge does the rest, and you wake up to a healthy dessert.",
 "tempo": "5 min + fridge", "rende": "1 serving", "kcal_base": 280,
 "ings": ["3 tbsp chia seeds", "3/4 cup milk (or plant drink)",
          "1/2 tsp vanilla extract (optional)", "chopped fruit to taste for the top",
          "1 tsp honey (optional)"],
 "passos": [
   "In a jar with a lid, put the chia, the milk and the vanilla. Stir well for 30 seconds.",
   "Wait 5 minutes and stir again — this second stir breaks up the lumps that form and is the secret to a smooth pudding.",
   "Close the jar and put it in the fridge for at least 4 hours, or overnight.",
   "The chia takes in the liquid and forms a pudding with a jelly-like texture.",
   "Before serving, stir, top with chopped fruit and, if you like, the drizzle of honey."],
 "porcoes8": ["2 tbsp chia · 2/3 cup milk · fruit",
              "3 tbsp chia · 3/4 cup milk · fruit",
              "3 tbsp chia · 3/4 cup milk · fruit · 1 tsp honey",
              "3 tbsp chia · 1 cup milk · fruit · 1 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 1 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 2 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 2 tbsp granola · nuts",
              "5 tbsp chia · 1 1/4 cups milk · fruit · 2 tbsp granola · nuts"],
 "dica": "Chia takes in many times its own weight in liquid and swells in your stomach, giving a feeling of fullness that lasts. It is also rich in fiber and omega-3 — one of the most filling ingredients per calorie there is.",
},
{
 "nome": "Baked Egg Muffins with Vegetables",
 "hook": "You bake one batch and have breakfast ready all week — just heat it up and eat.",
 "tempo": "25 min", "rende": "6 muffins (2 per serving)", "kcal_base": 220,
 "ings": ["6 eggs", "1/2 bell pepper, chopped", "1 handful of chopped spinach", "2 tbsp grated cheese",
          "salt and pepper to taste", "a little oil (or spray) so the food does not stick"],
 "passos": [
   "Preheat the oven to 350 °F and brush a little oil (or spray) on the muffin pan, so the eggs do not stick.",
   "Chop the bell pepper and the spinach into small pieces.",
   "In a bowl, beat the eggs with salt and pepper. Add the vegetables and the cheese and mix.",
   "Divide the mixture between the 6 cups, filling each one about 3/4 of the way.",
   "Bake for 18 to 20 minutes, until they set and turn lightly golden. A toothpick in the center should come out clean.",
   "Let them cool a little before taking them out. Keep them in the fridge for up to 4 days and heat them when you eat."],
 "porcoes8": ["1 muffin + green leaves",
              "2 muffins",
              "2 muffins · 1/2 slice of bread",
              "2 muffins · 1 slice of bread",
              "3 muffins · 1 slice of bread",
              "3 muffins · 2 slices of bread",
              "3 muffins · 2 slices of bread · 1/4 avocado",
              "4 muffins · 2 slices of bread · 1/4 avocado"],
 "dica": "Having food ready is what stops the wrong decision when morning hunger hits. These muffins are protein and vegetables in a controlled portion — you can freeze them and always have a breakfast that holds you, without improvising with what you should not eat.",
},
{
 "nome": "Toast with Ricotta, Strawberry and Honey",
 "hook": "Sweet and creamy like a treat, but with protein and no heavy sugar.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["1 slice of wholegrain bread", "3 tbsp ricotta", "4 strawberries in slices",
          "1 tsp honey", "lemon zest and mint (optional)"],
 "passos": [
   "Toast the slice of bread until it is firm.",
   "In a bowl, mash the ricotta with a fork until it is creamy. If it is dry, add a little milk.",
   "Spread the ricotta over the toast, covering the whole surface.",
   "Arrange the strawberry slices on top.",
   "Finish with the drizzle of honey and, if you like, lemon zest and a few mint leaves. Serve right away."],
 "porcoes8": ["1/2 slice of bread · 2 tbsp ricotta · strawberries",
              "1 slice of bread · 3 tbsp ricotta · strawberries · 1 tsp honey",
              "1 slice of bread · 3 tbsp ricotta · strawberries · honey",
              "1 slice of bread · 4 tbsp ricotta · strawberries · honey · nuts",
              "1 slice of bread · 4 tbsp ricotta · strawberries · 1 boiled egg",
              "2 slices of bread · 4 tbsp ricotta · strawberries · honey",
              "2 slices of bread · 5 tbsp ricotta · strawberries · nuts",
              "2 slices of bread · 6 tbsp ricotta · strawberries · nuts · 1 egg"],
 "dica": "Ricotta is a lean, creamy cheese that is rich in protein — it kills the craving for something sweet without the heavy cream of store-bought fillings. The strawberry brings sweetness and freshness, and 1 tsp of honey sweetens enough without turning your breakfast into a sugar bomb.",
},
{
 "nome": "Warm Oats with Cocoa and Banana",
 "hook": "The taste of chocolate at breakfast, with no sugar and no guilt.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 350,
 "ings": ["1/2 cup rolled oats", "3/4 cup milk (or plant drink)", "1 tbsp 100% cocoa powder",
          "1 banana", "cinnamon to taste", "sweetener or 1 tsp honey (optional)"],
 "passos": [
   "In a small pot, mix the oats, the milk and the cocoa powder before turning on the heat — that way the cocoa dissolves without lumps.",
   "Cook over medium-low heat, stirring all the time.",
   "Mash half of the banana and add it to the pot; keep the other half in slices.",
   "Cook for 4 to 5 minutes, until it thickens and turns creamy.",
   "Taste it and adjust the sweetness with sweetener or 1 tsp of honey, if you need to.",
   "Serve in a bowl with the banana slices and a pinch of cinnamon on top."],
 "porcoes8": ["1/3 cup oats · 3/4 cup milk · 1 tbsp cocoa · 1/2 banana",
              "1/2 cup oats · 3/4 cup milk · 1 tbsp cocoa · 1 banana",
              "1/2 cup + 1 tbsp oats · 3/4 cup milk · 1 tbsp cocoa · 1 banana",
              "2/3 cup oats · 1 cup milk · 1 tbsp cocoa · 1 banana · nuts",
              "2/3 cup oats · 1 cup milk · cocoa · 1 banana · 1 tsp peanut butter",
              "2/3 cup + 1 tbsp oats · 1 cup milk · cocoa · 1 banana · 1 tbsp peanut butter",
              "3/4 cup oats · 1 cup milk · cocoa · 1 banana · peanut butter",
              "3/4 cup + 2 tbsp oats · 1 1/4 cups milk · cocoa · 1 banana · peanut butter"],
 "dica": "100% cocoa gives you the chocolate flavor without the sugar of drinking chocolate — and it still has antioxidants. Killing the craving for sweets at breakfast prevents the attack on the chocolate bar later, which is where many diets fall apart.",
},
{
 "nome": "Mushroom and Spinach Omelette",
 "hook": "Earthy and full of flavor, it fills the plate with nutrients for very few calories.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 260,
 "ings": ["2 eggs", "1 handful of sliced mushrooms (button mushrooms)", "1 handful of spinach",
          "1 tsp olive oil", "salt, pepper and chopped garlic to taste"],
 "passos": [
   "Slice the mushrooms and wash the spinach.",
   "Heat the olive oil in a nonstick pan over medium-high heat. Fry the mushrooms in a little oil for 3 to 4 minutes, without stirring too much, until they brown and release their water.",
   "Add the garlic and the spinach and stir for 1 minute, just until it wilts (the leaves go soft). Season with salt and pepper.",
   "Beat the eggs in a bowl and pour them over the vegetables. Turn the heat down.",
   "Let the base set for 1 to 2 minutes, fold the omelette in half and serve."],
 "porcoes8": ["1 egg + 1 white · veggies, as much as you want",
              "2 eggs · veggies, as much as you want",
              "2 eggs · veggies · 1/2 slice of bread",
              "2 eggs · veggies · 1 slice of bread",
              "3 eggs · veggies · 1 slice of bread",
              "3 eggs · veggies · 2 slices of bread",
              "3 eggs · veggies · 2 slices of bread · cheese",
              "4 eggs · veggies · 2 slices of bread · cheese"],
 "dica": "Mushrooms and spinach bring volume, flavor and nutrients for almost no calories — you fill the plate and your stomach. The eggs complete it with filling protein, making a generous meal that still fits comfortably into your diet.",
},
{
 "nome": "Yogurt with Homemade Granola and Blueberries",
 "hook": "You make the granola at home with no sugar and use it all week — crunchy and done right.",
 "tempo": "5 min (+ granola ready)", "rende": "1 serving", "kcal_base": 330,
 "ings": ["1 cup of plain Greek yogurt (about 6 oz)", "3 tbsp homemade granola with no sugar",
          "1 handful of blueberries", "cinnamon to taste",
          "(granola: oats + chopped nuts + cinnamon, baked at 325 °F for 15 min)"],
 "passos": [
   "For the homemade granola: mix rolled oats with chopped nuts and cinnamon, spread it on a baking sheet and bake at 325 °F for 12 to 15 minutes, stirring halfway through. Let it cool so it goes crunchy and keep it in a jar.",
   "In a glass, put the yogurt.",
   "Cover it with the homemade granola.",
   "Spread the blueberries on top and finish with a pinch of cinnamon.",
   "Serve right away, so the granola does not go soft."],
 "porcoes8": ["4 oz yogurt · 2 tbsp granola · blueberries",
              "6 oz yogurt · 3 tbsp granola · blueberries",
              "6 oz yogurt · 3 tbsp granola · blueberries",
              "7 oz yogurt · 4 tbsp granola · blueberries",
              "7 oz yogurt · 4 tbsp granola · blueberries",
              "9 oz yogurt · 4 tbsp granola · blueberries",
              "9 oz yogurt · 5 tbsp granola · blueberries",
              "10 oz yogurt · 6 tbsp granola · blueberries"],
 "dica": "Store-bought granola is usually full of sugar and oil — making it at home cuts that out and you control what goes in. With Greek yogurt rich in protein and blueberries, it becomes a crunchy, filling breakfast without the hidden sugars of the industrial versions.",
},
{
 "nome": "Wholegrain Wrap with Scrambled Eggs and Vegetables",
 "hook": "Roll it and go — the breakfast for anyone running out the door who still refuses to eat badly.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["1 wholegrain tortilla/wrap", "2 eggs", "1/2 tomato, chopped", "1 handful of spinach",
          "1 tbsp grated cheese", "salt, pepper and cooking spray"],
 "passos": [
   "Chop the tomato and set it aside. Wash the spinach.",
   "Beat the eggs with salt and pepper. Heat the pan with cooking spray over medium heat.",
   "Add the spinach and the tomato for 1 minute, then pour in the eggs and stir until they form creamy scrambled eggs.",
   "Warm the tortilla for 20 seconds on each side in a dry pan, just to soften it.",
   "Put the eggs in the center of the tortilla, sprinkle the cheese and fold the sides inward.",
   "Roll it tight like a burrito and cut it in half. You can eat it in your hand, on the run."],
 "porcoes8": ["1 wrap · 1 egg + 1 white · veggies",
              "1 wrap · 2 eggs · veggies · cheese",
              "1 wrap · 2 eggs · veggies · cheese",
              "1 wrap · 2 eggs · veggies · 1/4 avocado",
              "1 wrap · 3 eggs · veggies · cheese",
              "1 large wrap · 3 eggs · veggies · cheese · 1/4 avocado",
              "1 large wrap · 3 eggs · veggies · cheese · 1/2 avocado",
              "1 large wrap · 4 eggs · veggies · cheese · 1/2 avocado"],
 "dica": "Being able to carry your breakfast in your hand is what stops you from skipping the meal on a busy day. Filled with egg and vegetables, this wrap gives you protein and fiber in a practical format — much better than solving your hunger at a bakery with a sweet roll.",
},
{
 "nome": "Apple and Cinnamon Pancakes",
 "hook": "It smells like apple pie and fits your diet — the comfort of a sweet breakfast without sabotaging your day.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1/2 cup rolled oats", "1 egg", "1/2 apple, grated", "cinnamon to taste",
          "1 pinch of baking powder", "cooking spray", "1/2 apple in thin slices for the top"],
 "passos": [
   "Grate half of the apple on the coarse side of the grater and keep the other half in slices.",
   "In a bowl, mix the oats, the egg, the grated apple, the cinnamon and the baking powder until everything is well mixed.",
   "Let it rest for 3 minutes so the oats take in the moisture.",
   "Heat the nonstick pan over medium-low heat and spray it with oil.",
   "Make small pancakes, leaving them 2 to 3 minutes on each side.",
   "Meanwhile, brown the apple slices in the same pan with a pinch of cinnamon. Serve them over the pancakes."],
 "porcoes8": ["1/3 cup oats · 1 egg · 1/2 apple",
              "1/2 cup oats · 1 egg · 1/2 apple",
              "1/2 cup + 1 tbsp oats · 1 egg · 1/2 apple · nuts",
              "2/3 cup oats · 1 egg · 1 apple · nuts",
              "2/3 cup oats · 2 eggs · 1 apple",
              "2/3 cup + 1 tbsp oats · 2 eggs · 1 apple · nuts",
              "3/4 cup oats · 2 eggs · 1 apple · nuts",
              "3/4 cup + 2 tbsp oats · 2 eggs · 1 apple · 1 tbsp peanut butter"],
 "dica": "The apple brings sweetness and fiber, and the cinnamon lifts the flavor without a pinch of sugar — studies suggest it may even help control appetite. This is the version that kills the craving for sweet pie without the refined carbs that make you gain weight.",
},
{
 "nome": "Wholegrain Toast with Peanut Butter and Banana",
 "hook": "The 5-minute classic that combines energy, good fat and natural sweetness.",
 "tempo": "5 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1 slice of wholegrain bread", "1 tbsp peanut butter", "1 banana in slices",
          "cinnamon to taste", "1 pinch of chia seeds (optional)"],
 "passos": [
   "Toast the slice of bread until it is firm.",
   "Spread the peanut butter over the toast while it is still warm — it melts a little and is easier to spread.",
   "Cover it with the banana slices.",
   "Sprinkle cinnamon and, if you like, the chia seeds on top.",
   "Serve immediately. To take it with you, cut it in half and build it like a sandwich."],
 "porcoes8": ["1/2 slice of bread · 1 tsp peanut butter · 1/2 banana",
              "1 slice of bread · 1 tbsp peanut butter · 1 banana",
              "1 slice of bread · 1 tbsp peanut butter · 1 banana · chia",
              "1 slice of bread · 1.5 tbsp peanut butter · 1 banana",
              "1 slice of bread · 1.5 tbsp peanut butter · 1 banana · 1 boiled egg",
              "2 slices of bread · 2 tbsp peanut butter · 1 banana",
              "2 slices of bread · 2 tbsp peanut butter · 1 banana · 1 egg",
              "2 slices of bread · 2.5 tbsp peanut butter · 1 banana · 1 egg"],
 "dica": "Peanut butter has good fat and protein, which keep you full for a long time — but it is high in calories, so the amount matters: 1 tbsp is already enough. On wholegrain bread with banana, you get steady energy for the whole morning, without the sugar spike and crash.",
},
{
 "nome": "Poached Eggs with Asparagus and Toast",
 "hook": "As elegant as a restaurant breakfast, simple enough for an ordinary day.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "1 handful of asparagus", "1 slice of wholegrain bread", "1 tsp vinegar (for the water)",
          "salt, pepper and olive oil to taste"],
 "passos": [
   "Wash the asparagus and cut off the hard base. Cook it in boiling salted water for 3 minutes, drain and set aside.",
   "In a pot, heat water until it is almost boiling (with small bubbles, not bubbling hard) and add the vinegar.",
   "Crack each egg into a cup. Make a whirlpool in the water with a spoon and slide the egg in very slowly at the center — the movement wraps the white around the yolk.",
   "Cook for 3 minutes for a soft yolk. Take it out with a slotted spoon and rest it on a paper towel.",
   "Toast the bread. Build it with the asparagus underneath, the poached eggs on top, a little olive oil, salt and pepper."],
 "porcoes8": ["1 egg · asparagus · 1/2 slice of bread",
              "2 eggs · asparagus · 1 slice of bread",
              "2 eggs · asparagus · 1 slice of bread · cheese",
              "2 eggs · asparagus · 1 slice of bread · 1/4 avocado",
              "3 eggs · asparagus · 1 slice of bread",
              "3 eggs · asparagus · 2 slices of bread",
              "3 eggs · asparagus · 2 slices of bread · 1/4 avocado",
              "4 eggs · asparagus · 2 slices of bread · 1/4 avocado"],
 "dica": "A poached egg is cooked in water only, with no oil, which keeps the calories low. Asparagus is rich in fiber and water and has practically no calories — a breakfast that looks sophisticated and still plays in favor of the scale.",
},
{
 "nome": "Oats with Pear and Walnuts",
 "hook": "Creamy, lightly sweetened by the pear and with the crunch of the walnuts.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 350,
 "ings": ["1/2 cup rolled oats", "3/4 cup milk (or plant drink)", "1/2 pear, chopped",
          "3 walnuts, chopped", "cinnamon to taste", "1 tsp honey (optional)"],
 "passos": [
   "In a small pot, put the oats and the milk and cook over medium-low heat, stirring.",
   "After 3 minutes, add half of the chopped pear and cook for another 2 minutes, until it thickens.",
   "Turn off the heat and add the cinnamon.",
   "Serve in a bowl and top with the rest of the fresh pear and the chopped walnuts.",
   "If you need to, sweeten it with 1 tsp of honey."],
 "porcoes8": ["1/3 cup oats · 3/4 cup milk · 1/2 pear · 2 walnuts",
              "1/2 cup oats · 3/4 cup milk · 1/2 pear · 3 walnuts",
              "1/2 cup + 1 tbsp oats · 3/4 cup milk · 1/2 pear · 3 walnuts",
              "2/3 cup oats · 1 cup milk · 1 pear · 3 walnuts",
              "2/3 cup oats · 1 cup milk · 1 pear · 4 walnuts",
              "2/3 cup + 1 tbsp oats · 1 cup milk · 1 pear · 4 walnuts",
              "3/4 cup oats · 1 cup milk · 1 pear · 5 walnuts",
              "3/4 cup + 2 tbsp oats · 1 1/4 cups milk · 1 pear · 5 walnuts"],
 "dica": "The pear is rich in fiber and sweetens naturally, so you do not need sugar. Walnuts have good fat that brings fullness and crunch — but they are high in calories, so a few pieces already do the job without blowing the calories of your breakfast.",
},
{
 "nome": "Greek Yogurt with Peach and Almonds",
 "hook": "Creamy and lightly sweet from the peach, with the crunch of the almonds — ready in 3 minutes.",
 "tempo": "3 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["1 cup of plain Greek yogurt (about 6 oz)", "1 peach in slices (or 1/2 can with no syrup)",
          "1 tbsp flaked almonds", "cinnamon to taste", "1 tsp honey (optional)"],
 "passos": [
   "If the peach is fresh, wash it and cut it into thin slices. If it is canned, choose one with no sugary syrup and drain it well.",
   "Put the yogurt in a glass.",
   "Arrange the peach slices on top.",
   "Sprinkle the flaked almonds and the cinnamon.",
   "If you need more sweetness, add 1 tsp of honey. Serve right away."],
 "porcoes8": ["4 oz yogurt · peach · 1/2 tbsp almonds",
              "6 oz yogurt · peach · 1 tbsp almonds",
              "6 oz yogurt · peach · 1 tbsp almonds · honey",
              "7 oz yogurt · peach · 1 tbsp almonds · 2 tbsp oats",
              "7 oz yogurt · peach · 1.5 tbsp almonds · 2 tbsp oats",
              "9 oz yogurt · peach · 1.5 tbsp almonds · 3 tbsp oats",
              "9 oz yogurt · peach · 2 tbsp almonds · 3 tbsp oats",
              "10 oz yogurt · peach · 2 tbsp almonds · 4 tbsp oats"],
 "dica": "The peach is sweet and low in calories, which satisfies the craving for sugar in a light way. With protein-rich Greek yogurt and a handful of almonds, you combine protein and good fat for a fullness that carries you through the morning.",
},
{
 "nome": "Wholegrain Turkey and Cheese Sandwich",
 "hook": "Savory, practical and full of protein — the quick breakfast for anyone who does not like sweet in the morning.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["2 slices of wholegrain bread", "2 slices of turkey breast", "1 slice of white cheese",
          "lettuce leaves", "tomato slices", "1 tsp mustard or light cream cheese"],
 "passos": [
   "If you like it warm, heat the slices of bread in a dry pan for 1 minute on each side.",
   "Spread the mustard or the light cream cheese on one slice of bread.",
   "Build the layers: turkey, cheese, tomato and lettuce.",
   "Close it with the other slice of bread and press it down lightly.",
   "Cut it diagonally and serve. To take it with you, wrap it in parchment paper."],
 "porcoes8": ["1 slice of bread (open) · 1 turkey · cheese",
              "2 slices of bread · 2 turkey · cheese",
              "2 slices of bread · 2 turkey · cheese",
              "2 slices of bread · 3 turkey · cheese · 1/4 avocado",
              "2 slices of bread · 3 turkey · cheese · 1 boiled egg",
              "2 slices of bread · 4 turkey · cheese · 1 egg",
              "3 slices of bread · 4 turkey · cheese · 1 egg",
              "3 slices of bread · 5 turkey · 2 cheese · 1 egg"],
 "dica": "Turkey breast is one of the leanest meats there is, almost pure protein, without the fat of cured meats like salami and bologna. On wholegrain bread with salad, it is a savory breakfast that holds you with few calories and no sugar.",
},
{
 "nome": "Vegetable Omelette",
 "hook": "Colorful and full of flavor, it uses what you have in the fridge and fills the plate.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 260,
 "ings": ["2 eggs", "1/4 bell pepper, chopped", "1/4 onion, chopped", "1/2 tomato, chopped",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Chop the bell pepper, the onion and the tomato into small cubes.",
   "Heat the olive oil in a nonstick pan over medium heat. Fry the onion and the bell pepper in a little oil, stirring, for 2 to 3 minutes, until they go soft.",
   "Add the tomato and fry for another minute. Season with salt and pepper.",
   "Beat the eggs and pour them over the vegetables. Tilt the pan to spread them.",
   "When the base sets (2 minutes), fold the omelette in half, cook for another minute and serve with the herbs."],
 "porcoes8": ["1 egg + 1 white · veggies, as much as you want",
              "2 eggs · veggies, as much as you want",
              "2 eggs · veggies · 1/2 slice of bread",
              "2 eggs · veggies · 1 slice of bread",
              "3 eggs · veggies · 1 slice of bread",
              "3 eggs · veggies · 2 slices of bread",
              "3 eggs · veggies · 2 slices of bread · cheese",
              "4 eggs · veggies · 2 slices of bread · cheese"],
 "dica": "Filling the omelette with vegetables raises the volume and the fiber for very few calories, so you eat a generous plate with no guilt. It is also a smart way to eat more vegetables early in the morning, which helps you hit your fiber target for the day.",
},
{
 "nome": "Green Smoothie with Spinach, Banana and Apple",
 "hook": "Green, cold and lightly sweet — you do not even taste the spinach, but your body thanks you.",
 "tempo": "5 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["1 large handful of spinach", "1/2 banana", "1/2 apple", "3/4 cup cold water (or plant milk)",
          "1 tbsp oats", "juice of 1/2 lemon", "ice to taste"],
 "passos": [
   "Wash the spinach well.",
   "In the blender, put the liquid first, then the spinach — blending the leaves with the liquid first stops you from getting chunks.",
   "Blend for 30 seconds, until the spinach breaks down.",
   "Add the banana, the apple (without seeds), the oats, the lemon juice and the ice.",
   "Blend on high (top speed) until it is smooth and well mixed. Serve right away, very cold."],
 "porcoes8": ["spinach · 1/2 banana · 1/2 apple · 1 tbsp oats",
              "spinach · 1/2 banana · 1/2 apple · 1 tbsp oats",
              "spinach · 1 banana · 1/2 apple · 2 tbsp oats",
              "spinach · 1 banana · 1/2 apple · 2 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 2 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 3 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 3 tbsp oats · yogurt · nuts",
              "spinach · 1 banana · 1 apple · 4 tbsp oats · yogurt · nuts"],
 "dica": "Blending spinach with fruit is a painless way to eat leaves in the morning — the sweet taste of the banana and the apple hides the green. It is light in calories and rich in water and fiber, great for starting the day hydrated and full.",
},
{
 "nome": "Scrambled Eggs with Mushrooms and Cheese",
 "hook": "Creamy and comforting, the savory breakfast that holds you with the taste of real food.",
 "tempo": "9 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "1 handful of sliced mushrooms", "1 tbsp grated cheese",
          "1 tsp olive oil", "salt, pepper and chives to taste"],
 "passos": [
   "Slice the mushrooms. Heat the olive oil in a pan over medium-high heat and brown the mushrooms for 3 to 4 minutes.",
   "Beat the eggs with salt and pepper.",
   "Turn the heat down, pour the eggs over the mushrooms and leave them for 30 seconds without touching.",
   "Push them gently from the bottom to the center with the spatula, forming creamy eggs.",
   "Before they finish cooking, add the grated cheese and stir. Turn off the heat with the eggs still moist and finish with chives."],
 "porcoes8": ["1 egg + 1 white · mushrooms · cheese",
              "2 eggs · mushrooms · cheese",
              "2 eggs · mushrooms · cheese · 1/2 slice of bread",
              "2 eggs · mushrooms · cheese · 1 slice of bread",
              "3 eggs · mushrooms · cheese · 1 slice of bread",
              "3 eggs · mushrooms · cheese · 2 slices of bread",
              "3 eggs · mushrooms · 2 tbsp cheese · 2 slices of bread",
              "4 eggs · mushrooms · 2 tbsp cheese · 2 slices of bread"],
 "dica": "Mushrooms bring an umami flavor that makes the meal taste richer without extra fat. With eggs and a touch of cheese, it is a creamy, protein-rich breakfast — far more filling than bread with butter grabbed on the run.",
},
{
 "nome": "Oat Pancakes with Blueberries",
 "hook": "The blueberries burst warm inside the batter — natural sweetness, with no added sugar.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1/2 cup rolled oats", "1 egg", "1/2 banana, mashed", "1 handful of blueberries",
          "1 pinch of baking powder", "cinnamon to taste", "cooking spray"],
 "passos": [
   "In a bowl, mix the oats, the egg, the mashed banana, the baking powder and the cinnamon.",
   "Let it rest for 3 minutes so the batter firms up.",
   "Add half of the blueberries to the batter, gently, so you do not crush them.",
   "Heat the nonstick pan over medium-low heat, spray it with oil and make small pancakes.",
   "Leave them 2 to 3 minutes on each side, flipping when small bubbles appear.",
   "Serve with the rest of the fresh blueberries on top."],
 "porcoes8": ["1/3 cup oats · 1 egg · 1/2 banana · blueberries",
              "1/2 cup oats · 1 egg · 1/2 banana · blueberries",
              "1/2 cup + 1 tbsp oats · 1 egg · 1/2 banana · blueberries",
              "2/3 cup oats · 1 egg · 1 banana · blueberries",
              "2/3 cup oats · 2 eggs · 1 banana · blueberries",
              "2/3 cup + 1 tbsp oats · 2 eggs · 1 banana · blueberries · nuts",
              "3/4 cup oats · 2 eggs · 1 banana · blueberries · nuts",
              "3/4 cup + 2 tbsp oats · 2 eggs · 1 banana · blueberries · 1 tbsp peanut butter"],
 "dica": "Blueberries are rich in antioxidants and low in calories, sweetening the pancake naturally. Since the base is oats, egg and banana — with no white flour and no sugar — you get a breakfast that satisfies the craving for sweets without the ingredients that make you gain weight.",
},
{
 "nome": "Yogurt with Chia, Honey and Kiwi",
 "hook": "Refreshing and full of fiber, the breakfast that gets your gut moving and fills you up at the same time.",
 "tempo": "4 min", "rende": "1 serving", "kcal_base": 290,
 "ings": ["1 cup of plain Greek yogurt (about 6 oz)", "1 tbsp chia seeds",
          "1 kiwi in slices", "1 tsp honey", "mint (optional)"],
 "passos": [
   "In a glass, mix the yogurt with the chia and let it rest for 5 minutes — the chia swells lightly and thickens the yogurt.",
   "Peel the kiwi and cut it into slices.",
   "Arrange the kiwi slices over the yogurt.",
   "Finish with the drizzle of honey and, if you like, a few mint leaves.",
   "Serve cold."],
 "porcoes8": ["4 oz yogurt · 1 tbsp chia · kiwi",
              "6 oz yogurt · 1 tbsp chia · kiwi · honey",
              "6 oz yogurt · 1 tbsp chia · kiwi · honey",
              "7 oz yogurt · 1 tbsp chia · kiwi · 2 tbsp oats",
              "7 oz yogurt · 1.5 tbsp chia · kiwi · 2 tbsp oats",
              "9 oz yogurt · 1.5 tbsp chia · kiwi · 3 tbsp oats",
              "9 oz yogurt · 2 tbsp chia · kiwi · 3 tbsp oats · nuts",
              "10 oz yogurt · 2 tbsp chia · kiwi · 4 tbsp oats · nuts"],
 "dica": "Chia and kiwi together are rich in fiber, which helps your gut work and makes fullness last longer. The Greek yogurt brings protein, and 1 tsp of honey sweetens without going overboard — a light breakfast that also takes care of your digestion.",
},
{
 "nome": "Wholegrain Toast with Cottage Cheese and Tomato",
 "hook": "Fresh and savory, with protein in the cheese and almost no calories in the tomato.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["1 slice of wholegrain bread", "3 tbsp cottage cheese", "1 tomato in slices",
          "oregano, salt, pepper and olive oil to taste", "basil leaves (optional)"],
 "passos": [
   "Toast the slice of bread until it is firm and crunchy.",
   "Spread the cottage cheese over the toast, covering the whole surface.",
   "Put the tomato slices on top.",
   "Season with a pinch of salt, pepper, oregano and a little olive oil.",
   "Finish with basil leaves, if you have them. Serve right away."],
 "porcoes8": ["1/2 slice of bread · 2 tbsp cottage cheese · tomato",
              "1 slice of bread · 3 tbsp cottage cheese · tomato",
              "1 slice of bread · 3 tbsp cottage cheese · tomato · 1 boiled egg",
              "1 slice of bread · 4 tbsp cottage cheese · tomato · 1 egg",
              "1 slice of bread · 4 tbsp cottage cheese · tomato · 2 eggs",
              "2 slices of bread · 4 tbsp cottage cheese · tomato · 1 egg",
              "2 slices of bread · 5 tbsp cottage cheese · tomato · 2 eggs",
              "2 slices of bread · 6 tbsp cottage cheese · tomato · 2 eggs"],
 "dica": "Cottage cheese is lean and rich in protein, and it kills hunger with few calories. On wholegrain bread with tomato, it becomes a healthy bruschetta — savory, fresh and much lighter than bread with greasy cream cheese.",
},
{
 "nome": "Oat Bowl with Baked Apple and Cinnamon",
 "hook": "The smell of baked apple with cinnamon turns plain oats into comfort on a cold day.",
 "tempo": "15 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["1/2 cup rolled oats", "3/4 cup milk (or plant drink)", "1 apple in cubes",
          "cinnamon stick or ground cinnamon", "1 tsp honey (optional)", "1 tbsp walnuts (optional)"],
 "passos": [
   "Cut the apple into cubes, with the skin on. In a nonstick pan, brown the cubes over medium heat with plenty of cinnamon for 5 to 7 minutes, stirring, until they caramelize (go soft and golden in the fruit's own sugar).",
   "Meanwhile, cook the oats with the milk in a pot, stirring, for 4 to 5 minutes, until it thickens.",
   "Pour the oats into a bowl.",
   "Top with the warm baked apple.",
   "If you like, finish with the drizzle of honey and the chopped walnuts. Serve warm."],
 "porcoes8": ["1/3 cup oats · 3/4 cup milk · 1/2 apple",
              "1/2 cup oats · 3/4 cup milk · 1 apple",
              "1/2 cup + 1 tbsp oats · 3/4 cup milk · 1 apple · honey",
              "2/3 cup oats · 1 cup milk · 1 apple · walnuts",
              "2/3 cup oats · 1 cup milk · 1 apple · walnuts",
              "2/3 cup + 1 tbsp oats · 1 cup milk · 1 apple · walnuts",
              "3/4 cup oats · 1 cup milk · 1 apple · walnuts",
              "3/4 cup + 2 tbsp oats · 1 1/4 cups milk · 1 apple · walnuts · honey"],
 "dica": "Baking the apple releases its natural sweetness and lifts the cinnamon, so you do not need sugar. It is a breakfast that comforts like a warm dessert, but with fiber from the fruit and the oats that holds hunger back for hours.",
},
]
