# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). ITALIANO.

Traducao literal de `receitas_jantar_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md.
⛔ METRICO: `1 lb`->`500 g` · `14 oz`->`400 g` · `4/5/6 cups of water`->
   `1 / 1,2 / 1,5 litri` · `400 °F`->`200 °C` · `350 °F`->`180 °C`.
⛔ O campo `prompt` NAO e' replicado: a foto e' a mesma (fotos/NNN, sem texto).
"""

RECEITAS = [
{
 "nome": "Vellutata di zucca con pollo sfilacciato",
 "hook": "Cremosa, arancione e avvolgente — una zuppa che scalda la tua sera e porta comunque le proteine del pollo per saziarti davvero.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 340,
 "ings": ["1 pezzo grande di zucca a cubetti (circa 500 g)",
          "1 filetto di petto di pollo (circa 150 g)", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe e zenzero grattugiato q.b.",
          "erbe fresche per completare", "1 litro di acqua"],
 "passos": [
   "In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando, finché non diventano trasparenti.",
   "Aggiungi i cubetti di zucca, il filetto di pollo intero e l'acqua. Porta a bollore e cuoci per 20 minuti, finché la zucca non è molto morbida.",
   "Tira fuori il pollo, fallo intiepidire e sfilaccialo con due forchette. Mettilo da parte.",
   "Con un frullatore a immersione (quello a bastoncino) o in un frullatore normale, frulla la zucca con il brodo finché non diventa una crema liscia. Attenta al liquido bollente.",
   "Rimetti la crema nella pentola, aggiungi il pollo sfilacciato, lo zenzero, sale e pepe e scalda per 3 minuti. Servi con erbe fresche sopra."],
 "porcoes8": ["1 mestolo · poco pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo · 1 fetta di pane",
              "2 mestoli · pollo extra · 1 fetta di pane",
              "3 mestoli · pollo · 1 fetta di pane",
              "3 mestoli · pollo extra · 2 fette di pane",
              "3 mestoli grandi · doppio pollo · 2 fette di pane"],
 "dica": "La zucca ha tanta acqua e fibre, che riempiono lo stomaco con pochissime calorie. Il calore della zuppa ti fa mangiare più lentamente, e il pollo sfilacciato trasforma la crema leggera in un pasto completo che tiene a bada la fame fino all'ora di dormire, senza pesantezza.",
},
{
 "nome": "Filetto di pollo in salsa di senape con verdure al vapore",
 "hook": "Una salsa cremosa di senape e yogurt veste a festa il pollo — leggera, elegante e veloce da fare per cena.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 400,
 "ings": ["1 filetto di petto di pollo (circa 150 g)",
          "1 cucchiaio di yogurt naturale senza zucchero",
          "1 cucchiaino di senape", "100 g di broccoli, carota e fagiolini",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe ed erbe fresche q.b."],
 "passos": [
   "Taglia le verdure a pezzi simili tra loro. Cuocile a vapore (o in una pentola coperta con un dito d'acqua) per 6 minuti, finché non sono tenere ma ancora sode e colorate.",
   "Condisci il pollo con sale, pepe e l'aglio. Scalda una padella antiaderente con l'olio d'oliva a fuoco medio e cuoci il filetto 4-5 minuti per lato, finché non è dorato e bianco dentro.",
   "In una ciotolina, mescola lo yogurt, la senape, il succo di limone, sale e pepe, finché non diventa una salsa cremosa.",
   "Metti il pollo nel piatto, versaci sopra la salsa alla senape e servi con le verdure di lato.",
   "Spolvera le erbe fresche e servi caldo."],
 "porcoes8": ["120 g di pollo · verdure",
              "150 g di pollo · verdure",
              "150 g di pollo · verdure · 2 cucchiai di riso",
              "170 g di pollo · verdure · 2 cucchiai di riso",
              "170 g di pollo · verdure · 3 cucchiai di riso",
              "200 g di pollo · verdure · 3 cucchiai di riso",
              "220 g di pollo · verdure · 4 cucchiai di riso",
              "250 g di pollo · verdure · 4 cucchiai di riso"],
 "dica": "La salsa cremosa arriva dallo yogurt, non dalla panna o dal burro, e questo taglia moltissimi grassi. La senape porta un sapore deciso con quasi zero calorie. Cuocere le verdure a vapore conserva i nutrienti e non usa olio — una cena leggera che sembra da ristorante.",
},
{
 "nome": "Pesce al cartoccio con verdure",
 "hook": "Il pesce cuoce nel suo stesso vapore dentro la carta, e viene incredibilmente tenero — e il cartoccio lo apri a tavola, caldo e profumato.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 380,
 "ings": ["1 filetto di pesce bianco (nasello, merluzzo o tilapia, circa 150 g)",
          "½ zucchina a rondelle sottili", "½ carota a striscioline sottili",
          "pomodorini, tagliati", "1 spicchio d'aglio a fettine",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe ed erbe (timo o origano) q.b.",
          "1 foglio grande di carta da forno"],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la zucchina e la carota a fettine sottili, così cuociono nello stesso tempo del pesce.",
   "Al centro di un foglio grande di carta da forno, fai un letto con le verdure. Condisci con un po' di sale, pepe e metà dell'olio d'oliva.",
   "Metti sopra il filetto di pesce. Condisci con sale, pepe, l'aglio, le erbe, il succo di limone e il resto dell'olio d'oliva.",
   "Chiudi la carta a cartoccio: unisci le estremità e ripiega bene i bordi, lasciando un po' d'aria dentro, per formare un pacchetto sigillato.",
   "Inforna per 18-20 minuti. Aprilo con attenzione (esce vapore bollente) e servilo nella carta o spostalo in un piatto."],
 "porcoes8": ["120 g di pesce · verdure",
              "150 g di pesce · verdure",
              "150 g di pesce · verdure · 1 patata piccola",
              "170 g di pesce · verdure · 1 patata",
              "170 g di pesce · verdure · 1 patata",
              "200 g di pesce · verdure · 1 patata",
              "220 g di pesce · verdure · 1 patata grande",
              "250 g di pesce · verdure · 2 patate piccole"],
 "dica": "Cuocere al cartoccio non usa quasi grassi: il pesce e le verdure cuociono nel loro stesso vapore, mantenendo il sapore e restando tenerissimi. È uno dei modi più leggeri e sani di cuocere il pesce, perfetto per una cena senza pesantezza e senza padelle da lavare.",
},
{
 "nome": "Pasticcio di pollo con purè di cavolfiore",
 "hook": "Tutta la coccola di un pasticcio gratinato, ma la copertura è purè di cavolfiore — cremoso, leggero e con molte meno calorie.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 380,
 "ings": ["1 cavolfiore medio",
          "2 filetti di petto di pollo cotti e sfilacciati (circa 300 g)",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 pomodoro, a pezzetti", "1 cucchiaino di olio d'oliva",
          "2 cucchiai di formaggio grattugiato magro",
          "sale, pepe ed erbe fresche q.b."],
 "passos": [
   "Taglia il cavolfiore a pezzi e cuocilo in acqua bollente per 12 minuti, finché non è molto morbido. Scolalo molto bene (il cavolfiore trattiene acqua) e schiaccialo con la forchetta, con un pizzico di sale, finché non diventa un purè cremoso.",
   "In una padella, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi il pollo sfilacciato e il pomodoro, aggiusta di sale e pepe e cuoci per 5 minuti, finché non diventa un ripieno morbido.",
   "In una pirofila, stendi il pollo sul fondo e coprilo con il purè di cavolfiore.",
   "Spolvera sopra il formaggio grattugiato.",
   "Inforna a fuoco medio-alto (200 °C) per 15 minuti, finché la superficie non è leggermente dorata. Spolvera le erbe fresche e servi."],
 "porcoes8": ["½ porzione · insalata",
              "1 porzione · insalata",
              "1 porzione · insalata",
              "1 porzione · pollo extra · insalata",
              "1 porzione · pollo extra · insalata",
              "1 porzione grande · insalata",
              "1 porzione grande · pollo extra · insalata",
              "porzione doppia · insalata"],
 "dica": "Il cavolfiore al posto della patata taglia buona parte delle calorie e dei carboidrati, mantenendo la cremosità del purè. Il pollo sfilacciato porta proteine e sazietà. È il piatto avvolgente ideale per chi vuole mangiare qualcosa di caldo e leggero prima di dormire.",
},
{
 "nome": "Zuppa di verdure con manzo magro",
 "hook": "La zuppa che sa di quella della nonna: pezzi di manzo tenero e verdure in un brodo saporito che riempie la pancia e scalda l'anima.",
 "tempo": "50 min", "rende": "3 porzioni", "kcal_base": 360,
 "ings": ["250 g di manzo magro a cubetti (geretto o girello)",
          "1 patata a cubetti", "1 carota a cubetti", "1 zucchina a cubetti",
          "1 pomodoro, a pezzetti", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe ed erbe fresche q.b.", "1,5 litri di acqua"],
 "passos": [
   "In una pentola, scalda l'olio d'oliva e fai rosolare i cubetti di manzo su tutti i lati, mescolando, per 5 minuti.",
   "Aggiungi la cipolla e l'aglio e fai soffriggere per 2 minuti. Aggiungi il pomodoro e mescola per altri 2 minuti.",
   "Versa l'acqua, aggiusta di sale e pepe, copri e cuoci a fuoco medio-basso per 30 minuti, finché la carne non inizia a diventare tenera.",
   "Aggiungi la patata, la carota e la zucchina e cuoci per altri 15 minuti, finché la carne non è tenerissima e le verdure non sono cotte.",
   "Aggiusta di sale, spolvera le erbe fresche e servi ben caldo."],
 "porcoes8": ["1 mestolo · poca carne",
              "2 mestoli · carne",
              "2 mestoli · carne",
              "2 mestoli · carne · 1 fetta di pane",
              "2 mestoli · carne extra · 1 fetta di pane",
              "3 mestoli · carne · 1 fetta di pane",
              "3 mestoli · carne extra · 2 fette di pane",
              "3 mestoli grandi · doppia carne · 2 fette di pane"],
 "dica": "Le zuppe con tanto liquido e verdure riempiono lo stomaco con poche calorie, e mangiarle calde ti fa mangiare lentamente e sentire sazia prima. Il manzo magro porta proteine, rendendo la zuppa sostanziosa quanto basta per essere una cena completa.",
},
{
 "nome": "Salmone con salsa allo yogurt e aneto e verdure",
 "hook": "Il salmone rosa riceve una fresca salsa allo yogurt e aneto — sofisticato, leggero e fatto in venti minuti.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 430,
 "ings": ["1 filetto di salmone (circa 150 g)",
          "2 cucchiai di yogurt naturale senza zucchero", "aneto tritato",
          "100 g di broccoli e carota", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e aglio tritato q.b."],
 "passos": [
   "Taglia i broccoli a cimette e la carota a rondelle. Cuocili a vapore per 6 minuti, finché non sono teneri ma ancora sodi.",
   "Condisci il salmone con sale, pepe, l'aglio e il succo di limone.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio. Metti il salmone dal lato della pelle e lascialo 4 minuti, poi giralo e lascialo altri 3 minuti, finché non schiarisce e non si sfalda con la forchetta.",
   "Prepara la salsa: mescola lo yogurt, l'aneto tritato, un po' di sale e qualche goccia di limone.",
   "Componi il piatto con il salmone, le verdure di lato e la salsa allo yogurt sopra o a parte."],
 "porcoes8": ["120 g di salmone · verdure",
              "150 g di salmone · verdure",
              "150 g di salmone · verdure · 1 patata piccola",
              "170 g di salmone · verdure · 1 patata",
              "170 g di salmone · verdure · 1 patata",
              "200 g di salmone · verdure · 1 patata",
              "220 g di salmone · verdure · 1 patata grande",
              "250 g di salmone · verdure · 2 patate piccole"],
 "dica": "Il salmone porta il grasso buono (omega-3) che sazia e fa bene al cuore. La salsa allo yogurt e aneto sostituisce le salse cremose e grasse con una versione fresca e ricca di proteine. Con le verdure al vapore, è una cena leggera, bella e completa.",
},
{
 "nome": "Pollo al limone con verdure arrosto",
 "hook": "Il pollo resta succoso e appena agrumato, arrostito insieme a verdure che caramellano ai bordi — una teglia sola, zero lavoro.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 420,
 "ings": ["2 cosce di pollo senza pelle (o 2 filetti, circa 300 g)",
          "1 zucchina a pezzi", "1 peperone a pezzi", "1 cipolla a spicchi",
          "pomodorini", "2 spicchi d'aglio", "1 cucchiaino di olio d'oliva",
          "succo di 1 limone", "sale, pepe e origano q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Su una teglia, distribuisci la zucchina, il peperone, la cipolla, i pomodorini e gli spicchi d'aglio.",
   "Condisci le verdure con sale, pepe, origano e metà dell'olio d'oliva, e mescola.",
   "Condisci il pollo con sale, pepe, il succo di limone e il resto dell'olio d'oliva. Metti i pezzi tra le verdure.",
   "Inforna per 35 minuti, girando a metà cottura, finché il pollo non è dorato e cotto dentro (il liquido che esce quando lo punzecchi esce trasparente) e le verdure non sono morbide con i bordi dorati.",
   "Servi direttamente dalla teglia, irrorando con i succhi al limone che si sono formati."],
 "porcoes8": ["1 coscia · verdure",
              "1 coscia · verdure",
              "1 coscia grande · verdure",
              "2 cosce · verdure",
              "2 cosce · verdure",
              "2 cosce · verdure · 1 patata",
              "2 cosce · verdure · 1 patata grande",
              "3 cosce · verdure · 1 patata grande"],
 "dica": "Arrostire senza pelle e con poco olio mantiene il pollo leggero, e il limone porta freschezza senza calorie aggiunte. Le verdure arrosto diventano dolci e saporite da sole, così non ti servono salse pesanti. Una cena pratica, colorata e leggera fatta in una sola teglia.",
},
{
 "nome": "Polpette di tacchino con zucchine al sugo",
 "hook": "Polpette leggere di tacchino che nuotano in un sugo di pomodoro fresco, su nastri di zucchina — la pasta che non pesa sulla bilancia.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 380,
 "ings": ["250 g di macinato di petto di tacchino (o di pollo)", "1 uovo",
          "2 cucchiai di avena", "2 zucchine grandi",
          "3 pomodori maturi, a pezzetti (o passata di pomodoro)",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati",
          "1 cucchiaino di olio d'oliva", "sale, pepe e basilico q.b."],
 "passos": [
   "In una ciotola, mescola il macinato di tacchino, l'uovo, l'avena, metà dell'aglio, sale e pepe. Impasta con le mani e forma delle palline grandi come una noce.",
   "Scalda l'olio d'oliva in una pentola larga e fai rosolare le polpette su tutti i lati, girandole con delicatezza, per 5 minuti. Toglile e mettile da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e il resto dell'aglio per 2 minuti. Aggiungi i pomodori a pezzetti, sale e pepe e cuoci per 10 minuti, finché non diventa un sugo.",
   "Rimetti le polpette nel sugo e cuoci per altri 8 minuti, finché non sono cotte dentro.",
   "Con un pelapatate, ricava nastri sottili di zucchina (come tagliatelle). Metti i nastri crudi nel piatto e versaci sopra le polpette calde con il sugo — il calore ammorbidisce la zucchina. Spolvera il basilico."],
 "porcoes8": ["3 polpette · zucchina",
              "4 polpette · zucchina",
              "4 polpette · zucchina · 2 cucchiai di riso",
              "5 polpette · zucchina · 2 cucchiai di riso",
              "5 polpette · zucchina · 3 cucchiai di riso",
              "6 polpette · zucchina · 3 cucchiai di riso",
              "7 polpette · zucchina · 4 cucchiai di riso",
              "8 polpette · zucchina · 4 cucchiai di riso"],
 "dica": "Sostituire la pasta con i nastri di zucchina taglia quasi tutti i carboidrati e riempie il piatto di fibre e acqua. Le polpette di tacchino sono magre e ricche di proteine, e un sugo di pomodoro fatto al momento, senza zucchero, mantiene la cena saporita e leggerissima.",
},
{
 "nome": "Filetto di pesce in crosta di erbe con purè di patate",
 "hook": "Una crosta di erbe croccante fuori, pesce tenero dentro — sembra il piatto di uno chef, ma è semplice e leggero.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 410,
 "ings": ["1 filetto di pesce bianco (nasello, merluzzo o tilapia, circa 150 g)",
          "2 cucchiai di pangrattato integrale",
          "prezzemolo ed erba cipollina tritati finemente", "1 patata media",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "1 spicchio d'aglio, tritato", "sale e pepe q.b."],
 "passos": [
   "Sbuccia e cuoci la patata in acqua bollente per 15 minuti, finché non è molto morbida. Scolala e schiacciala con la forchetta, con un pizzico di sale, finché non diventa un purè liscio.",
   "Accendi il forno a fuoco medio-alto (200 °C). Condisci il pesce con sale, pepe, l'aglio e il succo di limone.",
   "In una ciotolina, mescola il pangrattato con il prezzemolo, l'erba cipollina e un po' di olio d'oliva, formando un composto umido.",
   "Metti il pesce su una teglia e copri la superficie con il pangrattato alle erbe, premendo leggermente perché si attacchi.",
   "Inforna per 15-18 minuti, finché la crosta non è dorata e croccante e il pesce non si sfalda. Servi con il purè di patate."],
 "porcoes8": ["120 g di pesce · ½ porzione di purè",
              "150 g di pesce · 1 porzione di purè",
              "150 g di pesce · 1 porzione di purè",
              "170 g di pesce · 1 porzione di purè",
              "170 g di pesce · 1 porzione di purè",
              "200 g di pesce · 1 porzione grande di purè",
              "220 g di pesce · porzione grande di purè",
              "250 g di pesce · porzione doppia di purè"],
 "dica": "La crosta di erbe con appena un po' di pangrattato dà croccantezza senza frittura, mantenendo il pesce leggero e pieno di sapore. Il pesce bianco è magrissimo e ricco di proteine, e il purè nella misura giusta consola senza esagerare — una cena bella e leggera.",
},
{
 "nome": "Bistecca alla griglia con insalata di ceci",
 "hook": "Una bistecca cotta al punto giusto accanto a un'insalata tiepida di ceci — doppia proteina che sazia senza appesantire la cena.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 440,
 "ings": ["1 bistecca di manzo magra (circa 120 g)", "80 g di ceci cotti",
          "½ pomodoro a cubetti", "cipolla rossa tritata", "foglie verdi",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Condisci la bistecca con sale e pepe su entrambi i lati.",
   "Scalda una padella antiaderente a fuoco alto con qualche goccia di olio d'oliva. Cuoci la bistecca 2-3 minuti per lato, senza spostarla, finché non è dorata fuori e cotta come piace a te. Falla riposare 2 minuti prima di tagliarla.",
   "In una ciotola, mescola i ceci, il pomodoro, la cipolla rossa e il prezzemolo.",
   "Condisci l'insalata con l'olio d'oliva, il succo di limone, sale e pepe.",
   "Servi la bistecca a fette su un letto di foglie verdi, con l'insalata di ceci di lato."],
 "porcoes8": ["100 g di carne · 55 g di ceci · insalata",
              "120 g di carne · 80 g di ceci · insalata",
              "130 g di carne · 80 g di ceci · insalata",
              "150 g di carne · 110 g di ceci · insalata",
              "150 g di carne · 110 g di ceci · insalata",
              "170 g di carne · 125 g di ceci · insalata",
              "200 g di carne · 165 g di ceci · insalata",
              "220 g di carne · 165 g di ceci · insalata"],
 "dica": "I ceci aggiungono fibre e proteine vegetali alle proteine della carne, e questo rende il piatto molto saziante con poche calorie. Cuocere la bistecca magra senza olio e servirla con un'insalata fresca è una cena leggera, piena di sapore, che tiene a bada la fame per ore.",
},
{
 "nome": "Vellutata di broccoli con pollo",
 "hook": "Verde, vellutata e piena di sapore — una crema di broccoli che prende corpo dal pollo e diventa una cena completa.",
 "tempo": "30 min", "rende": "3 porzioni", "kcal_base": 330,
 "ings": ["1 broccolo", "1 filetto di petto di pollo (circa 150 g)",
          "1 patata piccola (dà cremosità)", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe e noce moscata q.b.", "1 litro di acqua"],
 "passos": [
   "In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando.",
   "Aggiungi la patata a cubetti, il filetto di pollo intero e l'acqua. Cuoci per 15 minuti.",
   "Tira fuori il pollo, fallo intiepidire e sfilaccialo. Mettilo da parte. Aggiungi nella pentola i broccoli (solo le cimette) e cuoci per altri 5 minuti, finché non sono teneri ma ancora verdi.",
   "Frulla la zuppa con un frullatore a immersione (a bastoncino) o in un frullatore normale finché non è una crema liscia. Attenta al liquido bollente.",
   "Rimetti la crema nella pentola, aggiungi il pollo sfilacciato, aggiusta di sale, pepe e un tocco di noce moscata e scalda per 3 minuti. Servi."],
 "porcoes8": ["1 mestolo · poco pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo · 1 fetta di pane",
              "2 mestoli · pollo extra · 1 fetta di pane",
              "3 mestoli · pollo · 1 fetta di pane",
              "3 mestoli · pollo extra · 2 fette di pane",
              "3 mestoli grandi · doppio pollo · 2 fette di pane"],
 "dica": "Il broccolo è una delle verdure più nutrienti e meno caloriche, e frullato diventa una crema vellutata senza bisogno di panna. Un pezzetto di patata porta la cremosità, e il pollo sfilacciato completa la zuppa con proteine, mantenendo la cena leggera e saziante.",
},
{
 "nome": "Wrap di tacchino con insalata",
 "hook": "Fette di petto di tacchino, foglie fresche e un tocco cremoso, arrotolati in una piadina morbida — una cena leggera da mangiare con le mani.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 360,
 "ings": ["1 piadina integrale",
          "4 fette di petto di tacchino (affettato magro)",
          "1 cucchiaio di fiocchi di latte (o formaggio spalmabile light)",
          "foglie di lattuga", "½ pomodoro a fettine",
          "carota grattugiata", "cetriolo a striscioline",
          "sale, pepe e senape q.b."],
 "passos": [
   "Scalda la piadina 20 secondi in padella, giusto perché diventi morbida e facile da arrotolare.",
   "Spalma i fiocchi di latte (o il formaggio spalmabile light) su tutta la piadina, come fosse burro.",
   "Metti al centro le foglie di lattuga, le fette di tacchino, il pomodoro, la carota grattugiata e il cetriolo.",
   "Condisci con un po' di sale, pepe e senape.",
   "Ripiega i lati verso l'interno e arrotola stretto, dal basso verso l'alto. Taglia a metà in diagonale e servi."],
 "porcoes8": ["3 fette di tacchino · ½ piadina · insalata",
              "4 fette di tacchino · 1 piadina · insalata",
              "4 fette di tacchino · 1 piadina · insalata",
              "5 fette di tacchino · 1 piadina · insalata",
              "5 fette di tacchino · 1 piadina · insalata",
              "6 fette di tacchino · 1 piadina grande · insalata",
              "6 fette di tacchino · 2 piadine · insalata",
              "8 fette di tacchino · 2 piadine · insalata"],
 "dica": "Il petto di tacchino è una carne magra e pratica, piena di proteine. Sostituire il formaggio spalmabile normale con i fiocchi di latte o una versione light e riempire il wrap di foglie e verdure ti dà una cena leggera, veloce e saziante, perfetta per i giorni in cui non hai voglia di cucinare.",
},
{
 "nome": "Spezzatino di pollo con verdure",
 "hook": "Pezzi di pollo tenero in un brodo denso e saporito, con verdure che si sciolgono in bocca — cibo di pentola che ti abbraccia.",
 "tempo": "40 min", "rende": "3 porzioni", "kcal_base": 390,
 "ings": ["2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 patata a cubetti", "1 carota a rondelle", "1 zucchina a cubetti",
          "1 pomodoro, a pezzetti", "1 cipolla, tritata",
          "2 spicchi d'aglio, tritati", "1 cucchiaino di olio d'oliva",
          "sale, pepe, curcuma ed erbe fresche q.b."],
 "passos": [
   "Condisci i cubetti di pollo con sale, pepe e un po' di curcuma.",
   "In una pentola, scalda l'olio d'oliva e fai rosolare i cubetti di pollo per 5 minuti, mescolando. Aggiungi la cipolla e l'aglio e fai soffriggere per 2 minuti.",
   "Aggiungi il pomodoro e mescola per 2 minuti, finché non inizia a disfarsi.",
   "Aggiungi la patata e la carota e copri con l'acqua (quanto basta a coprire tutto). Aggiusta di sale e cuoci per 15 minuti.",
   "Aggiungi la zucchina e cuoci per altri 8 minuti, finché tutto non è tenero e il brodo non ha corpo. Spolvera le erbe fresche e servi da solo o con un po' di riso."],
 "porcoes8": ["½ porzione · senza riso",
              "1 porzione · senza riso",
              "1 porzione · 2 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione grande · 4 cucchiai di riso",
              "porzione grande · 5 cucchiai di riso",
              "porzione doppia · 5 cucchiai di riso"],
 "dica": "Lo spezzatino cuoce tutto nella stessa pentola con pochi grassi, e il brodo del pollo stesso insaporisce le verdure. È un piatto sostanzioso che sazia con poche calorie, ottimo per cena perché è caldo, avvolgente e leggero allo stesso tempo.",
},
{
 "nome": "Burger di tonno con insalata",
 "hook": "Fatto con il tonno in scatola, questo burger è economico, pieno di proteine e pronto in un attimo — una cena leggera e pratica.",
 "tempo": "20 min", "rende": "2 porzioni", "kcal_base": 380,
 "ings": ["2 scatolette di tonno al naturale, scolate", "1 uovo",
          "3 cucchiai di avena", "½ cipolla, tritata finemente",
          "prezzemolo tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe e succo di ½ limone q.b.",
          "foglie verdi, pomodoro e cetriolo per l'insalata"],
 "passos": [
   "Scola bene il tonno, premendolo per far uscire il liquido. In una ciotola, mescola il tonno, l'uovo, l'avena, la cipolla, il prezzemolo, sale, pepe e il succo di limone.",
   "Schiaccia tutto con la forchetta finché non sta insieme. Se è troppo morbido, aggiungi ancora un po' di avena.",
   "Forma due dischi con le mani, appiattendoli bene.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio. Metti i burger e lasciali 4 minuti per lato, senza spostarli, finché non sono dorati e sodi. Girali con delicatezza.",
   "Servi con un'insalata abbondante di foglie, pomodoro e cetriolo di lato."],
 "porcoes8": ["1 burger · insalata",
              "1 burger · insalata",
              "1 burger · insalata · ½ panino",
              "2 burger · insalata",
              "2 burger · insalata",
              "2 burger · insalata · 1 panino",
              "2 burger · insalata · 1 panino",
              "3 burger · insalata · 1 panino"],
 "dica": "Il tonno in scatola è una fonte di proteine economica e pratica, e legato con uovo e avena (invece che con tanto pane) diventa un burger magro e saziante. Cotto in padella senza frittura e servito con tanta insalata, è una cena leggera ed economica che riempie la pancia.",
},
{
 "nome": "Manzo brasato con verdure",
 "hook": "Un pezzo di manzo che cuoce lentamente finché non si sfalda, con verdure imbevute di brodo — la cena della domenica, nella misura giusta.",
 "tempo": "1 h 20 min", "rende": "3 porzioni", "kcal_base": 440,
 "ings": ["400 g di manzo magro in un pezzo (geretto, girello o fesa)",
          "2 carote a pezzi grandi", "2 patate a pezzi grandi",
          "1 cipolla a spicchi", "2 spicchi d'aglio", "1 pomodoro, a pezzetti",
          "1 foglia di alloro", "1 cucchiaino di olio d'oliva",
          "sale, pepe e rosmarino q.b."],
 "passos": [
   "Condisci il pezzo di manzo con sale e pepe. In una pentola alta, scalda l'olio d'oliva e fai rosolare il manzo su tutti i lati, girandolo, per circa 6 minuti (questa rosolatura dà tantissimo sapore al brodo).",
   "Aggiungi la cipolla, l'aglio e il pomodoro e fai soffriggere per 2 minuti. Aggiungi la foglia di alloro e acqua calda fino a coprire metà del manzo.",
   "Copri e cuoci a fuoco basso per 50 minuti, girando il manzo a metà cottura. Se l'acqua si asciuga troppo, aggiungi ancora un po' di acqua calda.",
   "Aggiungi le carote e le patate e cuoci per altri 25 minuti, finché il manzo non è così tenero da sfaldarsi e le verdure non sono cotte.",
   "Togli la foglia di alloro. Affetta o sfilaccia il manzo e servi con le verdure e il brodo sopra."],
 "porcoes8": ["½ porzione di carne · verdure",
              "1 porzione di carne · verdure",
              "1 porzione di carne · verdure",
              "1 porzione · verdure · 1 patata extra",
              "1 porzione · verdure · 1 patata extra",
              "1 porzione grande · verdure",
              "porzione grande · verdure · patata extra",
              "porzione doppia · verdure"],
 "dica": "La cottura lenta rende teneri i tagli magri ed economici senza bisogno di grassi, e il brodo che si forma insaporisce le verdure in modo naturale. Servito con la carne nella misura giusta e tante verdure, è un piatto avvolgente del fine settimana che rientra perfettamente nella tua dieta.",
},
{
 "nome": "Pollo ripieno di ricotta e spinaci",
 "hook": "Il filetto di pollo si apre come una tasca e accoglie un ripieno cremoso di ricotta e spinaci — sorprendente, succoso e leggero.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 400,
 "ings": ["2 filetti spessi di petto di pollo (circa 300 g)",
          "4 cucchiai di ricotta", "1 manciata abbondante di spinaci",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e noce moscata q.b.",
          "stuzzicadenti"],
 "passos": [
   "In una padella, scalda qualche goccia di olio d'oliva e salta gli spinaci con l'aglio per 1 minuto, giusto finché non appassiscono (le foglie si ammorbidiscono). Falli raffreddare e tritali.",
   "In una ciotola, mescola la ricotta, gli spinaci tritati, sale, pepe e un tocco di noce moscata, formando un ripieno cremoso.",
   "Con un coltello, fai un taglio sul fianco di ogni filetto, aprendo una tasca (senza tagliare da parte a parte). Condisci il pollo con sale, pepe e il succo di limone.",
   "Riempi le tasche con il composto di ricotta e chiudi l'apertura con uno o due stuzzicadenti.",
   "Scalda il resto dell'olio d'oliva in una padella a fuoco medio e fai rosolare i filetti 5-6 minuti per lato, finché non sono dorati e cotti dentro. Togli gli stuzzicadenti prima di servire, con un'insalata di lato."],
 "porcoes8": ["1 filetto piccolo · insalata",
              "1 filetto · insalata",
              "1 filetto · insalata · 2 cucchiai di riso",
              "1 filetto grande · insalata · 2 cucchiai di riso",
              "1 filetto grande · insalata · 3 cucchiai di riso",
              "1 filetto grande · insalata · 4 cucchiai di riso",
              "2 filetti · insalata · 4 cucchiai di riso",
              "2 filetti · insalata · 5 cucchiai di riso"],
 "dica": "La ricotta è un formaggio magro e cremoso, pieno di proteine e povero di grassi, ideale per farcire senza appesantire. Gli spinaci portano fibre e nutrienti per quasi zero calorie. Il risultato è un pollo succoso e sofisticato, leggero quanto basta per cena.",
},
{
 "nome": "Zuppa di pesce con verdure",
 "hook": "Un brodo profumato con pezzi di pesce bianco e verdure — leggero, pieno del gusto del mare e avvolgente in una serata fredda.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 340,
 "ings": ["400 g di filetto di pesce bianco a pezzi (nasello o merluzzo)",
          "1 patata a cubetti", "1 carota a cubetti", "1 pomodoro, a pezzetti",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe, coriandolo o prezzemolo q.b.", "1,2 litri di acqua"],
 "passos": [
   "In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi il pomodoro e mescola per altri 2 minuti, finché non si disfa.",
   "Aggiungi l'acqua, la patata e la carota. Aggiusta di sale e pepe e cuoci per 15 minuti, finché le verdure non sono morbide.",
   "Aggiungi i pezzi di pesce (il pesce cuoce in fretta, quindi entra alla fine) e cuoci per 6-8 minuti, giusto finché il pesce non è bianco e tenero, senza sfaldarsi troppo.",
   "Aggiungi il succo di limone e aggiusta di sale.",
   "Spolvera il coriandolo o il prezzemolo e servi ben caldo."],
 "porcoes8": ["1 mestolo · pesce",
              "2 mestoli · pesce",
              "2 mestoli · pesce",
              "2 mestoli · pesce · 1 fetta di pane",
              "2 mestoli · pesce extra · 1 fetta di pane",
              "3 mestoli · pesce · 1 fetta di pane",
              "3 mestoli · pesce extra · 2 fette di pane",
              "3 mestoli grandi · doppio pesce · 2 fette di pane"],
 "dica": "Il pesce bianco è magrissimo e cuoce in pochi minuti, mantenendo la zuppa leggera e piena di proteine. Il brodo con le verdure riempie lo stomaco con pochissime calorie, e il tocco di limone esalta il sapore senza troppo sale — una cena calda e leggera.",
},
{
 "nome": "Scaloppine di tacchino ai funghi",
 "hook": "Fettine sottili di tacchino in una cremosa salsa ai funghi — una cena che sembra costosa, fatta con pochi grassi in venti minuti.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 400,
 "ings": ["2 filetti sottili di petto di tacchino (circa 300 g)",
          "70 g di funghi champignon a fettine", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato",
          "3 cucchiai di yogurt naturale senza zucchero",
          "1 cucchiaino di olio d'oliva", "sale, pepe e prezzemolo q.b.",
          "riso o purè per servire"],
 "passos": [
   "Condisci i filetti sottili di tacchino con sale e pepe.",
   "Scalda una padella antiaderente con metà dell'olio d'oliva a fuoco medio-alto e fai rosolare i filetti 2-3 minuti per lato, finché non sono dorati e cotti. Toglili e mettili da parte.",
   "Nella stessa padella, con il resto dell'olio d'oliva, fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi i funghi e cuoci per 4 minuti, finché non appassiscono (si ammorbidiscono) e rilasciano la loro acqua.",
   "Abbassa la fiamma, spegni e aggiungi lo yogurt, mescolando — a fuoco spento non impazzisce (non fa grumi). Aggiusta di sale e pepe.",
   "Rimetti i filetti in padella per farli avvolgere dalla salsa. Spolvera il prezzemolo e servi con un po' di riso o purè."],
 "porcoes8": ["1 filetto · 2 cucchiai di riso",
              "1 filetto · 3 cucchiai di riso",
              "1 filetto grande · 3 cucchiai di riso",
              "1 filetto grande · 4 cucchiai di riso",
              "1 filetto grande · 4 cucchiai di riso",
              "2 filetti · 4 cucchiai di riso",
              "2 filetti · 5 cucchiai di riso",
              "2 filetti · 6 cucchiai di riso"],
 "dica": "Il tacchino è una carne bianca magra e ricca di proteine. La salsa cremosa arriva dallo yogurt, non dalla panna, e questo taglia moltissimi grassi. I funghi portano un sapore intenso e corpo alla salsa con pochissime calorie — una cena sofisticata e leggera.",
},
{
 "nome": "Uova al forno in salsa di pomodoro con pollo",
 "hook": "Uova cotte dentro una salsa di pomodoro saporita, con pezzetti di pollo — una cena calda e diversa, dalla padella alla tavola.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 370,
 "ings": ["4 uova",
          "1 filetto di petto di pollo cotto e sfilacciato (circa 120 g)",
          "3 pomodori maturi, a pezzetti (o passata di pomodoro)",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "½ peperone, a pezzetti", "1 cucchiaino di olio d'oliva",
          "sale, pepe, paprika ed erbe fresche q.b.",
          "pane integrale per servire"],
 "passos": [
   "In una padella che possa andare in forno (o in una padella alta), scalda l'olio d'oliva e fai soffriggere la cipolla, l'aglio e il peperone per 3 minuti, mescolando.",
   "Aggiungi i pomodori a pezzetti, la paprika, sale e pepe e cuoci per 8 minuti, finché non diventa un sugo ricco. Aggiungi il pollo sfilacciato e mescola.",
   "Con un cucchiaio, forma dei piccoli incavi nel sugo. Rompi un uovo in ogni incavo, senza mescolare, così i tuorli restano interi.",
   "Copri la padella e cuoci a fuoco basso per 6-8 minuti, finché gli albumi non si rassodano e i tuorli non sono come piacciono a te. (Oppure inforna a fuoco medio per 10 minuti.)",
   "Spolvera le erbe fresche e servi nella padella stessa, con fette di pane integrale di lato."],
 "porcoes8": ["1 uovo · pollo · sugo",
              "2 uova · pollo · sugo",
              "2 uova · pollo · 1 fetta di pane",
              "2 uova · pollo extra · 1 fetta di pane",
              "2 uova · pollo extra · 1 fetta di pane",
              "2 uova · pollo · 2 fette di pane",
              "3 uova · pollo extra · 2 fette di pane",
              "3 uova · doppio pollo · 2 fette di pane"],
 "dica": "Le uova sono una proteina completa e molto saziante, e cotte nel sugo di pomodoro restano leggere, senza frittura. Il pollo aggiunge ancora più proteine e il sugo riempie il piatto con il volume dei pomodori. È una cena calda, economica e avvolgente che sazia per bene.",
},
{
 "nome": "Spiedini di gamberi e verdure",
 "hook": "Gamberi rosa e verdure colorate infilzati insieme, cotti alla griglia finché non si dorano — leggeri, belli e con un'aria di festa.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 360,
 "ings": ["250 g di gamberi grandi puliti", "1 peperone a quadrotti",
          "1 cipolla a pezzi", "1 zucchina a rondelle spesse", "pomodorini",
          "2 spicchi d'aglio, tritati", "1 cucchiaino di olio d'oliva",
          "succo di 1 limone", "sale, pepe e paprika q.b.",
          "stecchini per spiedini"],
 "passos": [
   "Condisci i gamberi con sale, pepe, paprika, l'aglio e il succo di limone. Lasciali insaporire per 10 minuti.",
   "Componi gli spiedini alternando un gambero, un quadrotto di peperone, un pezzo di cipolla, una rondella di zucchina e un pomodorino, finché lo stecchino non è pieno.",
   "Spennella gli spiedini con l'olio d'oliva.",
   "Scalda una padella grande o una piastra a fuoco medio-alto. Metti gli spiedini e girali ogni 2 minuti, per circa 8 minuti in tutto, giusto finché i gamberi non diventano rosa e non si arricciano. Non cuocerli troppo, o diventano gommosi.",
   "Servi gli spiedini con un'insalata o un po' di riso."],
 "porcoes8": ["1 spiedino · insalata",
              "2 spiedini · insalata",
              "2 spiedini · insalata · 2 cucchiai di riso",
              "2 spiedini · insalata · 3 cucchiai di riso",
              "2 spiedini · insalata · 3 cucchiai di riso",
              "3 spiedini · insalata · 3 cucchiai di riso",
              "3 spiedini · insalata · 4 cucchiai di riso",
              "3 spiedini grandi · insalata · 4 cucchiai di riso"],
 "dica": "Il gambero è quasi tutto proteine, con pochissimi grassi e poche calorie. Infilzato con verdure colorate e cotto alla griglia senza olio, diventa una cena leggera, di effetto e saporita, che controlla la porzione in modo naturale e funziona anche per le occasioni speciali.",
},
{
 "nome": "Salmone alla griglia con asparagi",
 "hook": "Due stelle in un piatto solo: il salmone succoso e gli asparagi croccanti — una cena elegante e leggera pronta in quindici minuti.",
 "tempo": "18 min", "rende": "1 porzione", "kcal_base": 420,
 "ings": ["1 filetto di salmone (circa 150 g)", "1 mazzo di asparagi",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e scorza di limone q.b."],
 "passos": [
   "Lava gli asparagi e spezza l'estremità dura di ciascuno (si spezza da sola nel punto giusto quando la pieghi).",
   "Condisci il salmone con sale, pepe, l'aglio e il succo di limone.",
   "Scalda una padella antiaderente con metà dell'olio d'oliva a fuoco medio. Metti il salmone dal lato della pelle e lascialo 4 minuti, giralo e lascialo altri 3 minuti, finché non schiarisce e non si sfalda.",
   "Nello stesso tempo, in un'altra padella (o nella stessa, dopo aver tolto il salmone), salta gli asparagi con il resto dell'olio d'oliva a fuoco alto per 4 minuti, mescolando, finché non sono verdi e teneri ma ancora croccanti.",
   "Componi il piatto con il salmone e gli asparagi. Completa con la scorza di limone sopra."],
 "porcoes8": ["120 g di salmone · asparagi",
              "150 g di salmone · asparagi",
              "150 g di salmone · asparagi · 1 patata piccola",
              "170 g di salmone · asparagi · 1 patata",
              "170 g di salmone · asparagi · 1 patata",
              "200 g di salmone · asparagi · 1 patata",
              "220 g di salmone · asparagi · 1 patata grande",
              "250 g di salmone · asparagi · 2 patate piccole"],
 "dica": "Il salmone porta proteine e omega-3, il grasso buono che sazia e protegge il cuore. Gli asparagi sono leggeri, pieni di fibre e aiutano a sgonfiare, con pochissime calorie. Cotti insieme con poco olio, fanno una cena elegante, leggera e nutriente.",
},
{
 "nome": "Carne macinata saltata con zucchine",
 "hook": "Un salto veloce di carne con zucchine e un uovo sopra — fatto in padella in pochi minuti, sazia senza bisogno di riso.",
 "tempo": "20 min", "rende": "2 porzioni", "kcal_base": 380,
 "ings": ["250 g di carne macinata magra di manzo",
          "2 zucchine a cubetti piccoli", "1 pomodoro, a pezzetti",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato", "2 uova",
          "1 cucchiaino di olio d'oliva", "sale, pepe ed erbe fresche q.b."],
 "passos": [
   "Scalda l'olio d'oliva in una padella a fuoco medio e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando.",
   "Aggiungi la carne macinata e mescola, sgranandola con il cucchiaio, finché non perde tutto il colore rosato.",
   "Aggiungi il pomodoro e i cubetti di zucchina, aggiusta di sale e pepe e cuoci per 8 minuti, mescolando ogni tanto, finché la zucchina non è morbida e non rilascia i suoi succhi.",
   "Nel frattempo, cuoci le uova a parte, all'occhio di bue o sode (cuocile in padella con pochissimo olio oppure lessale per 6 minuti per un tuorlo morbido).",
   "Servi il saltato caldo con un uovo sopra ogni porzione e le erbe fresche spolverate sopra."],
 "porcoes8": ["½ porzione · 1 uovo",
              "1 porzione · 1 uovo",
              "1 porzione · 1 uovo · 2 cucchiai di riso",
              "1 porzione · 1 uovo · 3 cucchiai di riso",
              "1 porzione · 2 uova · 3 cucchiai di riso",
              "1 porzione grande · 2 uova · 3 cucchiai di riso",
              "porzione grande · 2 uova · 4 cucchiai di riso",
              "porzione doppia · 2 uova · 4 cucchiai di riso"],
 "dica": "La zucchina a cubetti si mescola alla carne e dà volume al piatto con pochissime calorie, aiutandoti a mangiare meno carne senza sentirne la mancanza. L'uovo sopra aggiunge proteine e cremosità. Senza riso o con pochissimo, è una cena leggera, veloce e molto saziante.",
},
{
 "nome": "Pollo alla pizzaiola con insalata",
 "hook": "Il gusto della pizza senza la base: il pollo alla griglia riceve salsa di pomodoro, formaggio filante e origano — toglie la voglia e non appesantisce.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 400,
 "ings": ["2 filetti di petto di pollo (circa 300 g)",
          "120 ml di passata di pomodoro fatta in casa",
          "3 cucchiai di mozzarella magra grattugiata",
          "fettine di pomodoro", "1 cucchiaino di olio d'oliva",
          "origano, sale e pepe q.b.", "foglie verdi per l'insalata"],
 "passos": [
   "Condisci i filetti di pollo con sale e pepe.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio e cuoci i filetti 4-5 minuti per lato, finché non sono dorati e bianchi dentro.",
   "Abbassa la fiamma. Copri ogni filetto con la passata di pomodoro, una o due fettine di pomodoro e la mozzarella grattugiata. Spolvera l'origano.",
   "Copri la padella e lasciala 3-4 minuti, giusto finché il formaggio non si scioglie (è questo il trucco per una gratinatura senza forno).",
   "Servi con un'insalata verde fresca di lato."],
 "porcoes8": ["100 g di pollo · poco formaggio · insalata",
              "130 g di pollo · formaggio · insalata",
              "150 g di pollo · formaggio · insalata",
              "150 g di pollo · formaggio · 2 cucchiai di riso",
              "150 g di pollo · formaggio · 3 cucchiai di riso",
              "170 g di pollo · formaggio · 3 cucchiai di riso",
              "200 g di pollo · formaggio · 4 cucchiai di riso",
              "220 g di pollo · formaggio extra · 4 cucchiai di riso"],
 "dica": "Togli la voglia di pizza con il sapore della salsa di pomodoro, del formaggio e dell'origano, ma senza la base e senza i grassi. Il pollo alla griglia dà proteine magre e sazietà, e un po' di formaggio fuso basta per il piacere di una gratinatura. Leggero e appagante.",
},
{
 "nome": "Pesce in padella con verdure",
 "hook": "Tutto in una padella sola: il pesce si dora da un lato mentre le verdure saltano dall'altro — una cena leggera, veloce e senza disordine.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 380,
 "ings": ["1 filetto di pesce bianco (nasello, merluzzo o tilapia, circa 150 g)",
          "1 zucchina a mezzelune", "½ peperone a striscioline", "pomodorini",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Condisci il pesce con sale, pepe, l'aglio e il succo di limone.",
   "Scalda una padella grande con metà dell'olio d'oliva a fuoco medio-alto. Da un lato, metti il filetto e lascialo 3-4 minuti per lato, girandolo con delicatezza, finché non è dorato e non si sfalda.",
   "Dall'altro lato della padella (o dopo aver tolto il pesce), metti il resto dell'olio d'oliva e salta la zucchina, il peperone e i pomodorini per 4-5 minuti, mescolando, finché non sono teneri ma ancora sodi.",
   "Aggiusta le verdure di sale e pepe.",
   "Componi il piatto con il pesce e le verdure saltate. Spolvera il prezzemolo e completa con ancora un po' di limone."],
 "porcoes8": ["120 g di pesce · verdure",
              "150 g di pesce · verdure",
              "150 g di pesce · verdure · 1 patata piccola",
              "170 g di pesce · verdure · 1 patata",
              "170 g di pesce · verdure · 1 patata",
              "200 g di pesce · verdure · 1 patata",
              "220 g di pesce · verdure · 1 patata grande",
              "250 g di pesce · verdure · 2 patate piccole"],
 "dica": "Il pesce bianco è leggero e cuoce in pochi minuti, e fatto nella stessa padella delle verdure usa pochissimo olio. Le verdure saltate portano colore, fibre e volume per quasi zero calorie. È una delle cene più veloci, leggere e pratiche che esistano.",
},
{
 "nome": "Petto di tacchino alla griglia con purè di zucca",
 "hook": "Il tacchino magro su un purè di zucca arancione e naturalmente dolce — una cena leggera dall'aria accogliente.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 390,
 "ings": ["1 filetto di petto di tacchino (circa 150 g)",
          "1 pezzo di zucca a cubetti (circa 300 g)",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe, salvia o rosmarino q.b.",
          "foglie verdi per l'insalata"],
 "passos": [
   "Cuoci la zucca in acqua bollente per 15 minuti, finché non è molto morbida. Scolala molto bene e schiacciala con la forchetta, con un pizzico di sale, finché non diventa un purè liscio e cremoso.",
   "Condisci il tacchino con sale, pepe, l'aglio e il succo di limone.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio e cuoci il filetto 3-4 minuti per lato, finché non è dorato e bianco dentro.",
   "Se ti va, completa il tacchino con un po' di salvia o rosmarino in padella negli ultimi secondi, per profumarlo.",
   "Componi il piatto con il purè di zucca, il tacchino a fette sopra e un'insalata verde di lato."],
 "porcoes8": ["120 g di tacchino · ½ porzione di purè · insalata",
              "150 g di tacchino · 1 porzione di purè · insalata",
              "150 g di tacchino · 1 porzione di purè · insalata",
              "170 g di tacchino · 1 porzione di purè · insalata",
              "170 g di tacchino · 1 porzione di purè · insalata",
              "200 g di tacchino · 1 porzione grande di purè · insalata",
              "220 g di tacchino · porzione grande di purè · insalata",
              "250 g di tacchino · porzione doppia di purè · insalata"],
 "dica": "Il petto di tacchino è ancora più magro del pollo, pieno di proteine. La zucca fa un purè cremoso e dolce con pochissime calorie, togliendo la voglia di qualcosa di dolce e riempiendo il piatto di fibre. Una cena leggera, avvolgente e colorata.",
},
{
 "nome": "Minestra di pollo con pastina",
 "hook": "La solita minestra di pollo, rinforzata con tanto pollo e verdure — la cena che abbraccia, cura e rientra comunque nella tua dieta.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 360,
 "ings": ["1 filetto di petto di pollo (circa 150 g)",
          "50 g di pastina (capellini o stelline)",
          "1 carota a cubetti piccoli", "1 gambo di sedano, tritato (facoltativo)",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di olio d'oliva", "sale, pepe ed erbe fresche q.b.",
          "1,2 litri di acqua"],
 "passos": [
   "In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando.",
   "Aggiungi il filetto di pollo intero, la carota, il sedano e l'acqua. Aggiusta di sale e cuoci per 15 minuti, finché il pollo non è cotto.",
   "Tira fuori il pollo, fallo intiepidire e sfilaccialo. Rimetti il pollo sfilacciato nella pentola.",
   "Aggiungi la pastina e cuoci per altri 8-10 minuti, finché la pasta non è morbida (mescola ogni tanto perché non attacchi sul fondo).",
   "Aggiusta di sale, spolvera le erbe fresche e servi ben calda."],
 "porcoes8": ["1 mestolo · pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo",
              "2 mestoli · pollo extra",
              "2 mestoli · pollo extra · pasta extra",
              "3 mestoli · pollo",
              "3 mestoli · pollo extra · pasta extra",
              "3 mestoli grandi · doppio pollo"],
 "dica": "La minestra di pollo è leggera e avvolgente: il brodo con le verdure riempie lo stomaco con poche calorie e il pollo dà le proteine che saziano. Con poca pasta e tanto pollo e verdure, diventa una cena completa e calda, ideale per le sere fredde o per i giorni senza appetito.",
},
{
 "nome": "Gamberi al curry leggero con verdure",
 "hook": "Gamberi immersi in una salsa dorata di curry e latte di cocco light — profumata, cremosa e sorprendentemente leggera.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 380,
 "ings": ["300 g di gamberi puliti", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 peperone a striscioline",
          "1 cucchiaino di curry in polvere",
          "120 ml di latte di cocco light", "1 pomodoro, a pezzetti",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e coriandolo q.b.", "riso per servire"],
 "passos": [
   "Condisci i gamberi con sale, pepe e il succo di limone. Lasciali insaporire per 5 minuti.",
   "Scalda l'olio d'oliva in una padella a fuoco medio e fai soffriggere la cipolla, l'aglio e il peperone per 3 minuti, mescolando.",
   "Aggiungi il curry e mescola per 30 secondi, perché la spezia liberi il suo aroma. Aggiungi il pomodoro e cuoci per 3 minuti, finché non si disfa.",
   "Aggiungi il latte di cocco light e porta a un bollore leggero. Metti i gamberi e cuoci per 3-4 minuti, giusto finché non diventano rosa. Non cuocerli troppo, o diventano gommosi.",
   "Spolvera il coriandolo e servi su una piccola porzione di riso."],
 "porcoes8": ["120 g di gamberi · 2 cucchiai di riso",
              "150 g di gamberi · 3 cucchiai di riso",
              "150 g di gamberi · 3 cucchiai di riso",
              "170 g di gamberi · 4 cucchiai di riso",
              "170 g di gamberi · 4 cucchiai di riso",
              "200 g di gamberi · 4 cucchiai di riso",
              "220 g di gamberi · 5 cucchiai di riso",
              "250 g di gamberi · 5 cucchiai di riso"],
 "dica": "Il gambero è quasi proteina pura e cuoce in fretta. Il latte di cocco light dà cremosità alla salsa con molti meno grassi della panna, e il curry la profuma e dà la sensazione di un piatto speciale. Con un po' di riso, è una cena leggera e piena di sapore.",
},
{
 "nome": "Spezzatino di manzo con patate",
 "hook": "Cubetti di manzo che si sfaldano in un brodo denso con la patata — lo spezzatino che consola in una serata fredda, nella porzione giusta.",
 "tempo": "1 h", "rende": "3 porzioni", "kcal_base": 430,
 "ings": ["300 g di manzo magro a cubetti (geretto o cappello del prete magro)",
          "2 patate a cubetti grandi", "1 carota a rondelle",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati",
          "1 pomodoro, a pezzetti", "1 foglia di alloro",
          "1 cucchiaino di olio d'oliva", "sale, pepe ed erbe fresche q.b."],
 "passos": [
   "Condisci i cubetti di manzo con sale e pepe. In una pentola, scalda l'olio d'oliva e fai rosolare la carne su tutti i lati, mescolando, per 6 minuti.",
   "Aggiungi la cipolla e l'aglio e fai soffriggere per 2 minuti. Aggiungi il pomodoro e la foglia di alloro e mescola per 2 minuti.",
   "Copri con acqua calda, metti il coperchio e cuoci a fuoco basso per 35 minuti, finché la carne non inizia a diventare tenera. Se si asciuga, aggiungi altra acqua calda.",
   "Aggiungi la patata e la carota e cuoci per altri 20 minuti, finché la carne non si sfalda e la patata non è morbida (la patata aiuta ad addensare il brodo).",
   "Togli la foglia di alloro, spolvera le erbe fresche e servi caldo, da solo o con un po' di riso."],
 "porcoes8": ["½ porzione · senza riso",
              "1 porzione · senza riso",
              "1 porzione · 2 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione grande · 4 cucchiai di riso",
              "porzione grande · 5 cucchiai di riso",
              "porzione doppia · 5 cucchiai di riso"],
 "dica": "La cottura lenta rende teneri i tagli magri ed economici, e la patata addensa il brodo in modo naturale, così non ti servono farina o panna. È un piatto sostanzioso che sazia con calorie controllate — la coccola di uno spezzatino senza uscire dalla dieta.",
},
{
 "nome": "Frittata al forno con prosciutto magro e verdure",
 "hook": "Una frittata alta e soffice cotta al forno, farcita di verdure e prosciutto magro — la tagli a fette e sfama tutta la famiglia.",
 "tempo": "30 min", "rende": "3 porzioni", "kcal_base": 360,
 "ings": ["6 uova",
          "4 fette di prosciutto magro (di tacchino), a pezzetti",
          "½ peperone, a pezzetti", "1 pomodoro, a pezzetti",
          "una manciata di spinaci",
          "2 cucchiai di formaggio grattugiato magro",
          "1 cucchiaino di olio d'oliva", "erba cipollina, sale e pepe q.b."],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Ungi una pirofila piccola con l'olio d'oliva.",
   "In una ciotola, sbatti le uova con sale e pepe per 30 secondi.",
   "Aggiungi alle uova il prosciutto a pezzetti, il peperone, il pomodoro, gli spinaci e l'erba cipollina, e mescola.",
   "Versa il composto nella pirofila e spolvera sopra il formaggio grattugiato.",
   "Inforna per 20-25 minuti, finché la frittata non si gonfia, si rassoda al centro e diventa leggermente dorata in superficie. Tagliala a fette e servi calda o tiepida, con un'insalata."],
 "porcoes8": ["1 fetta · insalata",
              "1 fetta grande · insalata",
              "1 fetta grande · insalata · 1 fetta di pane",
              "2 fette · insalata · 1 fetta di pane",
              "2 fette · insalata · 1 fetta di pane",
              "2 fette grandi · insalata · 1 fetta di pane",
              "2 fette grandi · insalata · 2 fette di pane",
              "3 fette · insalata · 2 fette di pane"],
 "dica": "Le uova sono una proteina completa e molto saziante, e cotte al forno non hanno bisogno di frittura. Il prosciutto magro di tacchino aggiunge sapore e proteine con pochi grassi, e le verdure portano volume e fibre. Rende parecchio, si conserva bene ed è una cena leggera e pratica.",
},
{
 "nome": "Tilapia al forno con pomodoro e cipolla",
 "hook": "Filetti di pesce bianco cotti sotto un letto di pomodoro e cipolla che diventano una salsa naturale — leggeri, succosi e senza sforzo.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 370,
 "ings": ["2 filetti di tilapia (o altro pesce bianco, circa 300 g)",
          "2 pomodori a fettine", "1 cipolla a fettine",
          "1 spicchio d'aglio a fettine", "1 cucchiaino di olio d'oliva",
          "succo di 1 limone", "sale, pepe, origano e prezzemolo q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). In una pirofila, distribuisci sul fondo metà delle fettine di pomodoro e cipolla, formando un letto.",
   "Condisci i filetti di pesce con sale, pepe, l'aglio, l'origano e il succo di limone. Mettili sul letto di pomodoro e cipolla.",
   "Copri i filetti con il resto del pomodoro e della cipolla e condisci con l'olio d'oliva.",
   "Inforna per 20-25 minuti, finché il pesce non si sfalda e il pomodoro e la cipolla non sono morbidi, rilasciando una salsa naturale.",
   "Spolvera il prezzemolo e servi con la salsa sopra, insieme a un'insalata o a un po' di riso."],
 "porcoes8": ["120 g di pesce · verdure",
              "150 g di pesce · verdure",
              "150 g di pesce · verdure · 2 cucchiai di riso",
              "170 g di pesce · verdure · 3 cucchiai di riso",
              "170 g di pesce · verdure · 3 cucchiai di riso",
              "200 g di pesce · verdure · 3 cucchiai di riso",
              "220 g di pesce · verdure · 4 cucchiai di riso",
              "250 g di pesce · verdure · 4 cucchiai di riso"],
 "dica": "Il pesce bianco è magrissimo e ricco di proteine, e cuocerlo sotto pomodoro e cipolla crea una salsa naturale senza grassi, mantenendo il filetto succoso. È una cena leggera, economica e piena di sapore che si fa praticamente da sola in forno.",
},
{
 "nome": "Polpettine di pollo in brodo",
 "hook": "Morbide polpettine di pollo cotte in un brodo leggero con le verdure — una minestra divertente e completa che sazia e scalda.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 350,
 "ings": ["300 g di macinato di petto di pollo", "1 uovo",
          "2 cucchiai di avena", "1 carota a cubetti piccoli",
          "1 patata a cubetti piccoli", "1 zucchina a cubetti piccoli",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di olio d'oliva", "sale, pepe ed erbe fresche q.b.",
          "1,2 litri di acqua"],
 "passos": [
   "In una ciotola, mescola il macinato di pollo, l'uovo, l'avena, sale e pepe. Impasta con le mani e forma delle palline piccole, grandi come una noce.",
   "In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi l'acqua, la carota e la patata, aggiusta di sale e cuoci per 10 minuti.",
   "Cala con attenzione le polpettine crude nel brodo bollente, una a una. Non mescolare per 3 minuti, così si rassodano.",
   "Aggiungi la zucchina e cuoci per altri 10 minuti, finché le polpettine non sono cotte dentro e le verdure non sono morbide.",
   "Aggiusta di sale, spolvera le erbe fresche e servi ben calda."],
 "porcoes8": ["3 polpettine · 1 mestolo di brodo",
              "4 polpettine · 2 mestoli",
              "4 polpettine · 2 mestoli",
              "5 polpettine · 2 mestoli · 1 fetta di pane",
              "5 polpettine · 2 mestoli · 1 fetta di pane",
              "6 polpettine · 3 mestoli · 1 fetta di pane",
              "7 polpettine · 3 mestoli · 2 fette di pane",
              "8 polpettine · 3 mestoli · 2 fette di pane"],
 "dica": "Le polpettine di pollo danno le proteine che saziano, e cotte dentro la minestra rendono il brodo più saporito. Tutto quel liquido e le verdure riempiono lo stomaco con poche calorie. È una cena completa, leggera e avvolgente che piace anche a chi non ama le minestre liquide.",
},
{
 "nome": "Gamberi alla griglia con insalata verde",
 "hook": "Gamberi rosolati nell'aglio su un'insalata fresca e croccante — una cena leggera ed elegante pronta in quindici minuti.",
 "tempo": "15 min", "rende": "1 porzione", "kcal_base": 330,
 "ings": ["150 g di gamberi grandi puliti", "foglie verdi miste",
          "½ pomodoro a cubetti", "½ cetriolo a rondelle",
          "cipolla rossa a fettine sottili", "2 spicchi d'aglio, tritati",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Asciuga bene i gamberi con la carta da cucina e condiscili con sale, pepe e metà del succo di limone.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio-alto. Aggiungi l'aglio e mescola per 30 secondi, giusto finché non profuma.",
   "Metti i gamberi e cuocili 2-3 minuti per lato, giusto finché non diventano rosa e dorati. Non cuocerli troppo.",
   "In una ciotola grande o in un piatto, componi l'insalata con le foglie verdi, il pomodoro, il cetriolo e la cipolla rossa. Condiscila con il resto del limone, sale e pepe.",
   "Metti i gamberi caldi sopra l'insalata, spolvera il prezzemolo e servi subito."],
 "porcoes8": ["120 g di gamberi · insalata",
              "150 g di gamberi · insalata",
              "150 g di gamberi · insalata · 1 fetta di pane",
              "170 g di gamberi · insalata · 1 fetta di pane",
              "170 g di gamberi · insalata · 2 cucchiai di riso",
              "200 g di gamberi · insalata · 3 cucchiai di riso",
              "220 g di gamberi · insalata · 3 cucchiai di riso",
              "250 g di gamberi · insalata · 4 cucchiai di riso"],
 "dica": "Il gambero è quasi proteina pura, con pochissime calorie, quindi riempie il piatto senza appesantirti. Rosolato nell'aglio e servito su un'insalata fresca e croccante, è una delle cene più leggere possibili — ideale per la sera, quando il corpo consuma meno energia.",
},
{
 "nome": "Pesce in umido con latte di cocco e verdure",
 "hook": "Un umido di pesce cremoso e profumato con un tocco di latte di cocco — leggero come il mare, avvolgente come un abbraccio.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 390,
 "ings": ["300 g di filetto di pesce bianco a pezzi grandi",
          "1 peperone a striscioline", "1 pomodoro, a pezzetti",
          "1 cipolla a striscioline", "2 spicchi d'aglio, tritati",
          "120 ml di latte di cocco light", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e coriandolo q.b."],
 "passos": [
   "Condisci i pezzi di pesce con sale, pepe, l'aglio e il succo di limone. Lasciali insaporire per 5 minuti.",
   "In una pentola larga, scalda l'olio d'oliva e fai un letto con la cipolla, il peperone e il pomodoro. Falli saltare per 3 minuti, mescolando.",
   "Metti i pezzi di pesce sopra le verdure (non mescolare troppo, così il pesce non si sfalda).",
   "Versaci sopra il latte di cocco light, copri la pentola e cuoci a fuoco medio-basso per 10-12 minuti, finché il pesce non è bianco e tenero e il brodo non ha corpo.",
   "Spolvera il coriandolo e servi con una piccola porzione di riso, per sfruttare il brodo."],
 "porcoes8": ["120 g di pesce · 2 cucchiai di riso",
              "150 g di pesce · 3 cucchiai di riso",
              "150 g di pesce · 3 cucchiai di riso",
              "170 g di pesce · 4 cucchiai di riso",
              "170 g di pesce · 4 cucchiai di riso",
              "200 g di pesce · 4 cucchiai di riso",
              "220 g di pesce · 5 cucchiai di riso",
              "250 g di pesce · 5 cucchiai di riso"],
 "dica": "Il pesce bianco è magro e ricco di proteine, e il latte di cocco light dà cremosità al brodo con molti meno grassi della panna. Le verdure rilasciano acqua e formano una salsa leggera e profumata. È un umido avvolgente e leggero, perfetto per cena.",
},
{
 "nome": "Spiedini di manzo e verdure",
 "hook": "Cubetti di manzo succoso alternati a verdure colorate, cotti alla griglia finché non si dorano — il gusto della brace nella misura giusta.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 420,
 "ings": ["250 g di manzo magro a cubetti (controfiletto o fesa)",
          "1 peperone a quadrotti", "1 cipolla a pezzi",
          "1 zucchina a rondelle spesse", "pomodorini",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe e paprika q.b.", "stecchini per spiedini"],
 "passos": [
   "Condisci i cubetti di manzo con sale, pepe, paprika e l'aglio. Lasciali insaporire per 10 minuti.",
   "Componi gli spiedini alternando un cubetto di manzo, un quadrotto di peperone, un pezzo di cipolla, una rondella di zucchina e un pomodorino, finché lo stecchino non è pieno.",
   "Spennella gli spiedini con l'olio d'oliva.",
   "Scalda una padella grande o una piastra a fuoco medio-alto. Metti gli spiedini e girali ogni 3 minuti, per circa 12 minuti in tutto, finché il manzo non è dorato fuori e cotto come piace a te.",
   "Servi gli spiedini con un'insalata o un po' di riso."],
 "porcoes8": ["1 spiedino · insalata",
              "2 spiedini · insalata",
              "2 spiedini · insalata · 2 cucchiai di riso",
              "2 spiedini · insalata · 3 cucchiai di riso",
              "2 spiedini · insalata · 3 cucchiai di riso",
              "3 spiedini · insalata · 3 cucchiai di riso",
              "3 spiedini · insalata · 4 cucchiai di riso",
              "3 spiedini grandi · insalata · 4 cucchiai di riso"],
 "dica": "Gli spiedini tolgono la voglia di grigliata in modo leggero: il manzo magro dà proteine e le verdure colorate riempiono lo stecchino di fibre e poche calorie. Infilzarli aiuta a controllare la porzione in modo naturale, e cuocerli senza olio mantiene tutto saporito e leggero.",
},
{
 "nome": "Insalata tiepida con pollo, uovo e patate",
 "hook": "Patate dorate, pollo alla griglia e uovo, tutti tiepidi su foglie fresche — un'insalata che è una cena completa e accogliente.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 420,
 "ings": ["1 filetto di petto di pollo (circa 130 g)",
          "1 patata piccola a cubetti", "2 uova sode", "foglie verdi",
          "pomodorini", "cipolla rossa a fettine",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e senape q.b."],
 "passos": [
   "Cuoci i cubetti di patata in acqua bollente salata per 12 minuti, finché non sono morbidi. Scolali. Se li vuoi dorati, saltali per 3 minuti in padella con qualche goccia di olio d'oliva.",
   "Cuoci le uova per 9 minuti, passale sotto l'acqua fredda, sbucciale e tagliale a metà.",
   "Condisci il pollo con sale e pepe e cuocilo in una padella antiaderente 4-5 minuti per lato, finché non è dorato. Taglialo a striscioline.",
   "In una ciotola o in un piatto, fai un letto di foglie verdi e mettici sopra i pomodorini e la cipolla.",
   "Disponi sopra la patata tiepida, le striscioline di pollo e le uova. Prepara un condimento mescolando l'olio d'oliva, il succo di limone, la senape, sale e pepe, versalo e servi subito."],
 "porcoes8": ["100 g di pollo · ½ patata · 1 uovo",
              "130 g di pollo · 1 patata piccola · 2 uova",
              "130 g di pollo · 1 patata · 2 uova",
              "150 g di pollo · 1 patata · 2 uova",
              "150 g di pollo · 1 patata · 2 uova",
              "170 g di pollo · 1 patata grande · 2 uova",
              "200 g di pollo · 1 patata grande · 3 uova",
              "220 g di pollo · 2 patate piccole · 3 uova"],
 "dica": "È un'insalata che sazia come un pasto caldo: il pollo e l'uovo danno doppia proteina, la patata nella misura giusta porta energia e le foglie riempiono il piatto di fibre. Servita tiepida, è avvolgente e leggera allo stesso tempo — ideale per cena.",
},
]
