# -*- coding: utf-8 -*-
"""35 receitas de ALMOÇO (031-065). Português.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+  ·  Homem 70-85/86-100/101-120/120+
Metas (kcal): 360/440/500/560  ·  540/610/680/750
Cada receita tem 'prompt' = foto quadrada, ultrarrealista, SEM texto.
Vocabulário simples (sem jargão de cozinha); proteínas e carboidratos bem variados.
"""

RECEITAS = [
{
 "nome": "Frango Grelhado com Arroz Integral e Brócolis",
 "hook": "O prato mais simples do mundo e um dos que mais emagrece: proteína magra, um carboidrato do bem e vegetal à vontade.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 470,
 "ings": ["1 filé de peito de frango (≈ 150 g)", "4 colheres de sopa de arroz integral cozido",
          "1 prato de brócolis", "1 dente de alho picado", "1 colher de chá de azeite",
          "suco de ½ limão", "sal e pimenta a gosto"],
 "passos": [
   "Tempere o frango dos dois lados com sal, pimenta, o alho e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Corte o brócolis em pequenos buquês. Ferva água numa panela, coloque o brócolis e deixe só 3 minutos, até ficar verde vivo e macio mas ainda firme. Escorra.",
   "Aqueça uma frigideira que não gruda em fogo médio-alto com o azeite. Coloque o frango e deixe 4 a 5 minutos de cada lado, sem ficar mexendo, até dourar por fora e ficar branco por dentro.",
   "Para saber se está pronto, faça um corte no meio do filé: a carne tem que estar branquinha, sem parte rosada.",
   "Esquente o arroz integral já cozido. Monte o prato com o arroz, o frango fatiado e o brócolis ao lado.",
   "Se quiser, regue o brócolis com um fio de azeite e mais um pouco de limão."],
 "porcoes8": ["100 g frango · 3 col. arroz · brócolis à vontade",
              "120 g frango · 4 col. arroz · brócolis à vontade",
              "130 g frango · 5 col. arroz · brócolis à vontade",
              "150 g frango · 5 col. arroz · 1 fio de azeite",
              "150 g frango · 5 col. arroz · brócolis à vontade",
              "170 g frango · 6 col. arroz · brócolis à vontade",
              "200 g frango · 7 col. arroz · 1 fio de azeite",
              "220 g frango · 8 col. arroz · 1 fio de azeite"],
 "dica": "O peito de frango é quase pura proteína, que sacia muito e ajuda a preservar o músculo enquanto você perde gordura. O arroz integral tem fibra e libera energia devagar, então você não sente aquela fome que bate uma hora depois. O brócolis enche o prato com quase nenhuma caloria.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast sliced on a white plate, next to a portion of brown rice and steamed green broccoli, a wedge of lemon on the side, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Filé de Tilápia com Purê de Batata-Doce",
 "hook": "Peixe leve e um purê naturalmente adocicado — um almoço que parece de restaurante e cabe na dieta.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 440,
 "ings": ["1 filé de tilápia (≈ 150 g)", "1 batata-doce média", "1 colher de chá de azeite",
          "suco de ½ limão", "cheiro-verde picado", "sal, pimenta e páprica a gosto",
          "folhas verdes para a salada"],
 "passos": [
   "Descasque a batata-doce e corte em pedaços. Cozinhe em água fervente por 15 minutos, até ficar bem macia (um garfo entra sem esforço). Escorra.",
   "Amasse a batata ainda quente com um garfo, junte uma pitada de sal e metade do azeite, e misture até virar um purê liso.",
   "Tempere a tilápia com sal, pimenta, páprica e o suco de limão.",
   "Aqueça uma frigideira que não gruda com o restante do azeite em fogo médio. Coloque o filé e deixe 3 a 4 minutos de cada lado, virando com cuidado uma vez só, até dourar e soltar fácil da frigideira.",
   "Monte o prato com o purê, o filé por cima e uma porção de folhas verdes ao lado. Finalize com o cheiro-verde."],
 "porcoes8": ["120 g peixe · ½ batata-doce · salada",
              "150 g peixe · 1 batata-doce pequena · salada",
              "150 g peixe · 1 batata-doce média · salada",
              "170 g peixe · 1 batata-doce média · 1 fio de azeite",
              "170 g peixe · 1 batata-doce média · salada",
              "200 g peixe · 1 batata-doce grande · salada",
              "220 g peixe · 1 batata-doce grande · 1 fio de azeite",
              "250 g peixe · 1 batata-doce grande · 1 fio de azeite"],
 "dica": "A tilápia é um peixe magro, cheio de proteína e com pouquíssima gordura. A batata-doce sacia por horas e, mesmo sendo um carboidrato, libera energia bem devagar — por isso é a queridinha de quem quer emagrecer sem perder disposição.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared white fish fillet on a bed of orange sweet potato mash, with a side of green salad and a wedge of lemon, on a light plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Posta de Atum Grelhada com Legumes e Batata",
 "hook": "O atum fresco vira um bife do mar: firme por fora, suculento por dentro, e pronto em poucos minutos.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 450,
 "ings": ["1 posta (bife) de atum fresco (≈ 150 g)", "1 batata pequena em rodelas", "1 xícara de vagem e cenoura",
          "1 dente de alho picado", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e orégano a gosto"],
 "passos": [
   "Cozinhe as rodelas de batata em água fervente com sal por 10 minutos, até ficarem macias mas sem desmanchar. Escorra.",
   "Corte a vagem em pedaços e a cenoura em rodelas. Cozinhe no vapor ou em pouca água fervente por 5 minutos, até ficarem macias mas ainda firmes.",
   "Tempere a posta de atum com sal, pimenta, o alho, o orégano e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo alto. Coloque a posta e deixe 2 a 3 minutos de cada lado — o atum fica ótimo levemente rosado no centro; se preferir bem passado, deixe mais 1 minuto de cada lado.",
   "Monte o prato com a batata, os legumes e a posta de atum por cima. Regue com mais um pouco de limão e sirva."],
 "porcoes8": ["120 g atum · ½ batata · legumes",
              "150 g atum · 1 batata pequena · legumes",
              "150 g atum · 1 batata · legumes",
              "170 g atum · 1 batata · 1 fio de azeite",
              "170 g atum · 1 batata · legumes",
              "200 g atum · 1 batata grande · legumes",
              "220 g atum · 1 batata grande · 1 fio de azeite",
              "250 g atum · 2 batatas pequenas · 1 fio de azeite"],
 "dica": "O atum fresco é uma das carnes mais magras do mar: muita proteína, ômega-3 (a gordura boa) e pouquíssima gordura ruim. Grelhado rápido em fogo alto, fica suculento sem precisar de óleo, e com legumes e um pouco de batata vira um almoço nobre e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled fresh tuna steak, seared outside and pink inside, with roasted potato slices, green beans and carrot, a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Wrap Integral de Frango Desfiado",
 "hook": "Um enroladinho prático para levar ao trabalho, recheado de frango e salada — mata a fome sem pesar.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 420,
 "ings": ["1 tortilha integral (ou pão folha integral)", "1 filé de frango cozido e desfiado (≈ 120 g)",
          "1 colher de sopa de iogurte natural sem açúcar", "folhas de alface", "½ tomate em rodelas",
          "cenoura ralada", "sal, pimenta e um pouco de mostarda a gosto"],
 "passos": [
   "Cozinhe o peito de frango em água com sal por cerca de 15 minutos, até ficar branco por dentro. Deixe amornar e desfie com dois garfos, puxando a carne em fios.",
   "Numa tigela, misture o frango desfiado com o iogurte, a mostarda, sal e pimenta, até virar um recheio cremoso.",
   "Esquente a tortilha por 20 segundos numa frigideira, só para ficar macia e fácil de enrolar.",
   "Espalhe as folhas de alface no centro da tortilha. Coloque o frango cremoso, o tomate e a cenoura ralada por cima.",
   "Dobre as duas laterais para dentro e enrole apertado, de baixo para cima. Corte ao meio na diagonal e sirva."],
 "porcoes8": ["100 g frango · ½ tortilha · salada",
              "120 g frango · 1 tortilha · salada",
              "130 g frango · 1 tortilha · salada",
              "150 g frango · 1 tortilha · 1 col. cheia iogurte",
              "150 g frango · 1 tortilha · salada",
              "170 g frango · 1 tortilha grande · salada",
              "200 g frango · 2 tortilhas · salada",
              "220 g frango · 2 tortilhas · salada"],
 "dica": "Trocar a maionese pelo iogurte natural corta boa parte das calorias e ainda soma proteína. O frango desfiado espalha bem e dá a sensação de recheio farto com pouca gordura, e a tortilha integral tem mais fibra que o pão branco, segurando a fome por mais tempo.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain wrap cut in half, filled with shredded chicken, lettuce, tomato and grated carrot, on a wooden board, a few fresh vegetables beside it, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salmão Assado com Legumes no Forno",
 "hook": "Tudo numa assadeira só: o peixe mais nobre para o coração, dourado junto com legumes coloridos.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 490,
 "ings": ["1 posta de salmão (≈ 150 g)", "1 batata pequena em rodelas", "1 abobrinha em rodelas",
          "½ pimentão em tiras", "tomatinhos", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e alecrim a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a batata em rodelas finas — assim ela assa no mesmo tempo do peixe.",
   "Numa assadeira, espalhe a batata, a abobrinha, o pimentão e os tomatinhos. Tempere com sal, pimenta, alecrim e metade do azeite, e misture.",
   "Leve ao forno por 10 minutos, só para a batata começar a amaciar.",
   "Tire a assadeira, abra um espaço no meio e coloque o salmão. Tempere o peixe com sal, pimenta, o suco de limão e o restante do azeite.",
   "Volte ao forno por mais 15 minutos, até o salmão ficar mais claro e se soltar em lascas quando você cutuca com o garfo. Sirva na própria assadeira ou montado no prato."],
 "porcoes8": ["120 g salmão · ½ batata · legumes",
              "150 g salmão · 1 batata pequena · legumes",
              "150 g salmão · 1 batata · legumes",
              "170 g salmão · 1 batata · 1 fio de azeite",
              "170 g salmão · 1 batata · legumes",
              "200 g salmão · 1 batata grande · legumes",
              "220 g salmão · 1 batata grande · 1 fio de azeite",
              "250 g salmão · 2 batatas pequenas · 1 fio de azeite"],
 "dica": "O salmão é rico em gordura boa (ômega-3), que ajuda o coração e ainda dá muita saciedade. Assar tudo junto na mesma assadeira quase não usa óleo e deixa os legumes com sabor concentrado — um prato completo, bonito e leve com o mínimo de esforço.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked salmon fillet on a roasting tray surrounded by roasted potato slices, zucchini, red pepper and cherry tomatoes, sprig of rosemary and a lemon wedge, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Escondidinho de Batata-Doce com Carne Moída Magra",
 "hook": "O conforto de um escondidinho cremoso, mas com purê de batata-doce e carne magra — pura satisfação, sem culpa.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 460,
 "ings": ["2 batatas-doces médias", "250 g de carne moída magra (patinho)", "1 cebola picada",
          "1 dente de alho picado", "1 tomate picado", "1 colher de chá de azeite",
          "sal, pimenta e cheiro-verde a gosto", "1 colher de sopa de queijo ralado magro"],
 "passos": [
   "Descasque as batatas-doces, corte em pedaços e cozinhe em água fervente por 15 minutos, até ficarem bem macias. Escorra e amasse com um garfo, com uma pitada de sal, até virar um purê liso.",
   "Numa frigideira, aqueça o azeite e frite a cebola e o alho em fogo médio, mexendo, por 2 minutos, até ficarem transparentes.",
   "Junte a carne moída e mexa, quebrando os pedaços com a colher, até perder toda a cor rosada.",
   "Acrescente o tomate, sal e pimenta e cozinhe por mais 5 minutos, até apurar. Desligue e junte o cheiro-verde.",
   "Num refratário, espalhe metade do purê no fundo, a carne no meio e o restante do purê por cima. Polvilhe o queijo ralado.",
   "Leve ao forno médio-alto (200 °C) por 15 minutos, até a superfície ficar levemente dourada. Sirva quente."],
 "porcoes8": ["½ porção · salada verde",
              "1 porção · salada verde",
              "1 porção · salada verde",
              "1 porção · 1 col. queijo a mais",
              "1 porção + carne extra · salada",
              "1 porção grande · salada",
              "1 porção grande + carne · salada",
              "porção dupla de carne · salada"],
 "dica": "A batata-doce troca a batata comum do escondidinho por uma versão com mais fibra, que sacia mais. A carne magra dá proteína de sobra sem o excesso de gordura da carne gorda. É o tipo de prato reconfortante que engana a vontade de comer besteira.",
 "prompt": "Square ultra-realistic overhead food photograph of a sweet potato and ground beef shepherd's pie in a white baking dish, golden top, a spoon lifting a portion, a small green salad beside it, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salada Completa de Atum, Grão-de-Bico e Ovo",
 "hook": "Sem fogão: uma salada de verdade, que enche o prato e a barriga, montada em cinco minutos.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 400,
 "ings": ["1 lata de atum em água, escorrido", "½ xícara de grão-de-bico cozido", "2 ovos cozidos",
          "folhas verdes variadas", "½ tomate em cubos", "½ pepino em rodelas", "cebola roxa em fatias finas",
          "1 colher de chá de azeite", "suco de ½ limão", "sal e pimenta a gosto"],
 "passos": [
   "Cozinhe os ovos: coloque numa panela com água, ferva e conte 9 minutos. Passe em água fria, descasque e corte ao meio.",
   "Escorra bem o atum e o grão-de-bico.",
   "Num prato ou tigela grande, espalhe as folhas verdes. Por cima, distribua o tomate, o pepino e a cebola.",
   "Coloque o atum no centro, o grão-de-bico em volta e os ovos nas laterais.",
   "Regue com o azeite e o suco de limão, tempere com sal e pimenta e sirva."],
 "porcoes8": ["½ lata atum · ⅓ xíc. grão · 1 ovo",
              "1 lata atum · ½ xíc. grão · 2 ovos",
              "1 lata atum · ½ xíc. grão · 2 ovos",
              "1 lata atum · ⅔ xíc. grão · 2 ovos · abacate",
              "1 lata atum · ⅔ xíc. grão · 2 ovos",
              "1½ lata atum · ¾ xíc. grão · 2 ovos",
              "1½ lata atum · 1 xíc. grão · 3 ovos · abacate",
              "2 latas atum · 1 xíc. grão · 3 ovos · abacate"],
 "dica": "É uma bomba de proteína (atum, ovo e grão-de-bico juntos) que quase não dá trabalho. A proteína e a fibra da salada seguram a fome por horas, e por ser tudo fresco e sem cozinhar em óleo, o prato fica leve mesmo bem servido.",
 "prompt": "Square ultra-realistic overhead food photograph of a big fresh salad bowl with canned tuna, chickpeas, halved boiled eggs, mixed green leaves, cherry tomato, cucumber and red onion, drizzle of olive oil and lemon, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Strogonoff de Frango Leve com Arroz",
 "hook": "O strogonoff cremoso de sempre, mas trocando o creme de leite por iogurte — mesma delícia, metade das calorias.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["2 filés de peito de frango em cubos (≈ 300 g)", "1 cebola picada", "1 dente de alho picado",
          "1 xícara de cogumelos fatiados", "1 colher de sopa de extrato de tomate",
          "4 colheres de sopa de iogurte natural sem açúcar", "1 colher de chá de azeite",
          "sal, pimenta e mostarda a gosto", "arroz branco ou integral para servir"],
 "passos": [
   "Tempere os cubos de frango com sal e pimenta.",
   "Aqueça o azeite numa panela em fogo médio-alto e doure os cubos de frango por fora, mexendo de vez em quando, por 5 minutos. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o alho por 2 minutos, mexendo, até ficarem transparentes. Junte os cogumelos e cozinhe por mais 3 minutos, até murcharem (ficarem molinhos).",
   "Volte o frango à panela, junte o extrato de tomate e a mostarda, misture e deixe 3 minutos.",
   "Desligue o fogo. Só então junte o iogurte e mexa — fora do fogo ele não talha (não vira grumos). Acerte o sal e sirva sobre o arroz."],
 "porcoes8": ["½ porção · 3 col. arroz",
              "1 porção · 4 col. arroz",
              "1 porção · 5 col. arroz",
              "1 porção · 5 col. arroz · frango extra",
              "1 porção · 5 col. arroz",
              "1 porção grande · 6 col. arroz",
              "porção + frango · 7 col. arroz",
              "porção dupla · 8 col. arroz"],
 "dica": "O segredo é o iogurte natural no lugar do creme de leite: você mantém a cremosidade e o sabor, mas corta gordura e ainda ganha proteína. O frango dá saciedade e os cogumelos acrescentam volume e sabor com pouquíssima caloria.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy chicken stroganoff with mushrooms served over white rice on a white plate, garnished with parsley, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peito de Peru com Cuscuz de Legumes",
 "hook": "O cuscuz fica pronto só com água quente — o almoço mais rápido e fofo para dias corridos.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 430,
 "ings": ["1 filé de peito de peru (≈ 150 g)", "½ xícara de cuscuz marroquino (aquele de bolinhas pequenas)",
          "½ xícara de água quente", "½ abobrinha em cubinhos", "½ pimentão em cubinhos", "tomatinhos cortados",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta e hortelã a gosto"],
 "passos": [
   "Coloque o cuscuz numa tigela, junte uma pitada de sal e a água quente (a água deve cobrir o cuscuz por um dedo). Tampe com um prato e deixe 5 minutos.",
   "Solte o cuscuz com um garfo, passando por toda a tigela, até ficar soltinho, sem grudar.",
   "Tempere o peito de peru com sal e pimenta. Aqueça uma frigideira que não gruda com metade do azeite e grelhe o peru por 3 a 4 minutos de cada lado, até dourar e ficar branco por dentro.",
   "Junte ao cuscuz os cubinhos de abobrinha, pimentão e tomate crus, o restante do azeite, o suco de limão e a hortelã. Misture.",
   "Sirva o cuscuz com o peito de peru fatiado por cima."],
 "porcoes8": ["120 g peru · ⅓ xíc. cuscuz · legumes",
              "150 g peru · ½ xíc. cuscuz · legumes",
              "150 g peru · ½ xíc. cuscuz · legumes",
              "170 g peru · ⅔ xíc. cuscuz · 1 fio de azeite",
              "170 g peru · ⅔ xíc. cuscuz · legumes",
              "200 g peru · ¾ xíc. cuscuz · legumes",
              "220 g peru · 1 xíc. cuscuz · 1 fio de azeite",
              "250 g peru · 1 xíc. cuscuz · 1 fio de azeite"],
 "dica": "O peito de peru é ainda mais magro que o frango e cheio de proteína. O cuscuz marroquino cozinha só com água quente, sem gordura, e misturado com legumes crus vira um prato leve, colorido e refrescante — perfeito para o almoço.",
 "prompt": "Square ultra-realistic overhead food photograph of fluffy couscous mixed with diced zucchini, pepper and tomato, topped with sliced grilled turkey breast, fresh mint, on a white plate, light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chili de Carne com Feijão Preto",
 "hook": "Um ensopado picante e encorpado que aquece a alma — feijão, carne magra e muito sabor numa panela só.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 450,
 "ings": ["300 g de carne moída magra", "1 xícara de feijão preto cozido (ou de lata, escorrido)",
          "1 cebola picada", "2 dentes de alho picados", "1 pimentão picado", "2 tomates picados (ou molho de tomate)",
          "1 colher de chá de azeite", "1 colher de chá de cominho em pó", "sal, pimenta e páprica a gosto"],
 "passos": [
   "Aqueça o azeite numa panela em fogo médio. Frite a cebola, o alho e o pimentão por 3 minutos, mexendo, até amaciarem.",
   "Junte a carne moída e mexa, quebrando os pedaços com a colher, até perder toda a cor rosada.",
   "Acrescente o cominho, a páprica, sal e pimenta e misture bem, para os temperos soltarem o aroma.",
   "Junte os tomates picados e o feijão preto. Se ficar muito seco, coloque meia xícara de água.",
   "Abaixe o fogo e deixe cozinhar em fogo baixo por 15 a 20 minutos, mexendo de vez em quando, até engrossar num ensopado cremoso. Sirva puro ou com um pouco de arroz."],
 "porcoes8": ["½ porção · salada",
              "1 porção · salada",
              "1 porção · 2 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção grande · 4 col. arroz",
              "1 porção grande · 5 col. arroz",
              "porção dupla · 5 col. arroz"],
 "dica": "O feijão preto é campeão em fibra e proteína vegetal, e junto com a carne magra deixa o prato muito saciante com poucas calorias. É um cozido que rende, guarda bem na geladeira e mata a fome de comida quente e temperada sem sair da linha.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty beef and black bean chili in a rustic bowl, topped with chopped coriander, a spoon resting in it, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Macarrão Integral ao Sugo com Almôndegas de Peru",
 "hook": "Sim, dá para comer macarrão emagrecendo — na versão integral, com molho fresco e almôndegas magras.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 480,
 "ings": ["150 g de macarrão integral (peso seco)", "250 g de peito de peru moído (ou frango moído)",
          "3 tomates maduros picados (ou molho de tomate)", "1 cebola picada", "2 dentes de alho picados",
          "1 ovo", "2 colheres de sopa de aveia", "1 colher de chá de azeite", "sal, pimenta e manjericão a gosto"],
 "passos": [
   "Numa tigela, misture o peru moído, o ovo, a aveia, metade do alho, sal e pimenta. Amasse com as mãos até dar liga e enrole bolinhas do tamanho de uma noz.",
   "Aqueça o azeite numa panela larga e doure as almôndegas por todos os lados, girando com cuidado, por uns 5 minutos. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o restante do alho por 2 minutos. Junte os tomates picados, sal e pimenta e cozinhe por 10 minutos, mexendo, até virar um molho.",
   "Volte as almôndegas ao molho e deixe cozinhar por mais 8 minutos, até ficarem cozidas por dentro.",
   "Enquanto isso, cozinhe o macarrão em água fervente com sal pelo tempo da embalagem, até ficar cozido mas ainda firme. Escorra.",
   "Misture o macarrão ao molho com as almôndegas, salpique o manjericão e sirva."],
 "porcoes8": ["⅔ porção macarrão · 3 almôndegas",
              "1 porção · 4 almôndegas",
              "1 porção · 4 almôndegas",
              "1 porção · 5 almôndegas",
              "1 porção · 5 almôndegas",
              "1 porção grande · 6 almôndegas",
              "porção grande · 7 almôndegas",
              "porção dupla · 8 almôndegas"],
 "dica": "O macarrão integral tem mais fibra e sacia mais que o comum, e as almôndegas de peru dão proteína magra no lugar da carne gorda. Um molho de tomate feito na hora, sem açúcar e sem industrializados, deixa o prato saboroso e muito mais leve.",
 "prompt": "Square ultra-realistic overhead food photograph of wholewheat spaghetti with fresh tomato sauce and turkey meatballs, sprinkled with fresh basil, in a white bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Omelete Recheado com Legumes",
 "hook": "Um almoço leve para dias sem tempo: fofo, quentinho e cheio de proteína, pronto na frigideira em dez minutos.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 360,
 "ings": ["3 ovos", "½ tomate em cubinhos", "½ pimentão em cubinhos", "punhado de espinafre",
          "1 colher de sopa de queijo branco em cubos", "1 colher de chá de azeite",
          "cebolinha, sal e pimenta a gosto", "1 fatia de pão integral (opcional)"],
 "passos": [
   "Quebre os ovos numa tigela, tempere com sal e pimenta e bata com um garfo por 30 segundos, até ficar homogêneo (bem misturado).",
   "Aqueça o azeite numa frigideira que não gruda em fogo médio-baixo. Junte o pimentão e o espinafre e mexa por 1 minuto, só até o espinafre murchar (ficar mole).",
   "Espalhe os legumes pela frigideira e despeje os ovos por cima. Deixe 1 minuto sem mexer, até a borda firmar.",
   "Coloque o tomate e o queijo sobre metade da omelete. Com uma espátula, dobre a outra metade por cima, formando uma meia-lua.",
   "Deixe mais 1 minuto, só até o queijo amaciar. Salpique cebolinha e sirva, com a fatia de pão se quiser."],
 "porcoes8": ["2 ovos · legumes · ½ pão",
              "3 ovos · legumes · 1 fatia pão",
              "3 ovos · legumes · 1 fatia pão",
              "3 ovos · 2 col. queijo · 1 fatia pão",
              "3 ovos · legumes · 1 fatia pão",
              "4 ovos · legumes · 1 fatia pão",
              "4 ovos · 2 col. queijo · 2 fatias pão",
              "5 ovos · legumes · 2 fatias pão"],
 "dica": "Os ovos são proteína de altíssima qualidade e muito saciante — quem come ovos no almoço costuma beliscar menos à tarde. Recheado com legumes, o omelete ganha volume, cor e fibra sem quase somar calorias, virando uma refeição completa e rápida.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded omelette filled with tomato, pepper, spinach and white cheese on a white plate, chives on top, a slice of wholegrain toast beside it, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bife de Patinho com Arroz, Feijão e Couve",
 "hook": "O prato de todo dia, do jeito que a gente ama — só que na medida certa, com a carne magra e a couve refogada leve.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 500,
 "ings": ["1 bife de patinho (carne magra, ≈ 130 g)", "4 colheres de sopa de arroz cozido",
          "4 colheres de sopa de feijão cozido", "2 folhas de couve cortadas em tiras finas",
          "1 dente de alho picado", "1 colher de chá de azeite", "sal e pimenta a gosto"],
 "passos": [
   "Tempere o bife com sal e pimenta dos dois lados.",
   "Aqueça uma frigideira que não gruda em fogo alto com poucas gotas de azeite. Coloque o bife e deixe 2 a 3 minutos de cada lado, sem mexer, até dourar por fora e ficar do ponto que você gosta por dentro.",
   "Corte a couve em tiras bem finas. Numa frigideira, aqueça o restante do azeite e frite o alho por 30 segundos, só até cheirar.",
   "Junte a couve e mexa em fogo alto por 1 a 2 minutos, só até murchar um pouco (ficar mais mole) e continuar verde. Tempere com sal.",
   "Esquente o arroz e o feijão. Monte o prato com o arroz, o feijão, o bife e a couve ao lado."],
 "porcoes8": ["100 g carne · 3 col. arroz · 3 col. feijão",
              "130 g carne · 4 col. arroz · 4 col. feijão",
              "130 g carne · 5 col. arroz · 4 col. feijão",
              "150 g carne · 5 col. arroz · 5 col. feijão",
              "150 g carne · 5 col. arroz · 5 col. feijão",
              "170 g carne · 6 col. arroz · 5 col. feijão",
              "200 g carne · 7 col. arroz · 6 col. feijão",
              "220 g carne · 8 col. arroz · 6 col. feijão"],
 "dica": "Dá para comer o prato tradicional de arroz, feijão e carne sem sair da dieta: a chave é escolher um corte magro como o patinho, medir o arroz e o feijão e caprichar na couve, que enche o prato com fibra e quase nenhuma caloria. O feijão ainda dá fibra e proteína que seguram a fome.",
 "prompt": "Square ultra-realistic overhead food photograph of a plate with a grilled lean beef steak, white rice, brown beans and sautéed collard greens in thin strips, on a light wooden table, soft natural light, homestyle and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bife Acebolado com Purê de Batata e Salada",
 "hook": "O bife com cebola dourada é conforto puro — sobre um purê leve e ao lado de uma salada fresca, cabe direitinho na dieta.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 500,
 "ings": ["1 bife de patinho ou alcatra (carne magra, ≈ 130 g)", "2 batatas médias", "1 cebola em fatias",
          "1 colher de chá de azeite", "sal e pimenta a gosto", "folhas verdes e tomate para a salada",
          "suco de ½ limão"],
 "passos": [
   "Descasque e cozinhe as batatas em água fervente por 15 minutos, até ficarem bem macias. Escorra e amasse com um garfo, com uma pitada de sal, até virar um purê liso. Se quiser mais cremoso, junte um pouco da água do cozimento.",
   "Tempere o bife com sal e pimenta dos dois lados.",
   "Aqueça uma frigideira que não gruda em fogo alto com poucas gotas de azeite. Coloque o bife e deixe 2 a 3 minutos de cada lado, sem mexer, até dourar por fora e ficar no ponto que você gosta. Tire e deixe de lado.",
   "Na mesma frigideira, coloque as fatias de cebola e o restante do azeite. Mexa em fogo médio por 5 minutos, até a cebola ficar macia e dourada (bem docinha).",
   "Cubra o bife com a cebola dourada. Monte o prato com o purê, o bife acebolado e uma salada verde temperada com limão."],
 "porcoes8": ["100 g carne · ½ porção purê · salada",
              "130 g carne · 1 porção purê · salada",
              "130 g carne · 1 porção purê · salada",
              "150 g carne · 1 porção purê · salada",
              "150 g carne · 1 porção purê · salada",
              "170 g carne · 1 porção grande purê · salada",
              "200 g carne · porção grande purê · salada",
              "220 g carne · porção dupla purê · salada"],
 "dica": "Escolhendo um corte magro e grelhando sem óleo, o bife vira proteína quase pura. A cebola dourada dá muito sabor com pouquíssima caloria e dispensa molhos gordurosos. Com o purê na medida certa e bastante salada, o prato satisfaz sem pesar.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled lean beef steak topped with golden caramelized onions, served with creamy mashed potato and a fresh green salad with tomato, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Camarão Salteado com Legumes e Arroz",
 "hook": "Camarão fica pronto num piscar de olhos e é leve como poucos — um almoço rápido com cara de sofisticado.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 430,
 "ings": ["150 g de camarão limpo", "4 colheres de sopa de arroz integral cozido", "½ abobrinha em meias-luas",
          "½ pimentão em tiras", "1 dente de alho picado", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Tempere o camarão com sal, pimenta, o alho e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Aqueça uma frigideira grande com metade do azeite em fogo alto. Junte a abobrinha e o pimentão e mexa por 3 minutos, até ficarem macios mas ainda firmes. Tire e deixe de lado.",
   "Na mesma frigideira, coloque o restante do azeite e o camarão. Salteie (mexa em fogo alto) por 2 a 3 minutos, só até o camarão ficar rosado e enrolar. Cuidado para não passar do ponto, senão fica borrachudo.",
   "Volte os legumes à frigideira, junte o arroz integral já cozido e misture por 1 minuto, só para aquecer tudo.",
   "Salpique salsinha e sirva na hora."],
 "porcoes8": ["120 g camarão · 3 col. arroz · legumes",
              "150 g camarão · 4 col. arroz · legumes",
              "150 g camarão · 5 col. arroz · legumes",
              "170 g camarão · 5 col. arroz · 1 fio de azeite",
              "170 g camarão · 5 col. arroz · legumes",
              "200 g camarão · 6 col. arroz · legumes",
              "220 g camarão · 7 col. arroz · 1 fio de azeite",
              "250 g camarão · 8 col. arroz · 1 fio de azeite"],
 "dica": "O camarão é quase todo proteína, com muito pouca gordura e poucas calorias, então dá para comer bem servido sem pesar. Salteado rápido em fogo alto com legumes, mantém a textura firme e o sabor, num prato leve que fica pronto em minutos.",
 "prompt": "Square ultra-realistic overhead food photograph of sautéed shrimp with zucchini and red pepper over brown rice, garnished with parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango Xadrez Leve com Arroz Integral",
 "hook": "O clássico chinês em casa, na versão magra: frango em cubos e legutes crocantes num molho leve e brilhante.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 460,
 "ings": ["2 filés de peito de frango em cubos (≈ 300 g)", "1 pimentão em cubos", "1 cebola em cubos",
          "1 talo de salsão em pedaços (opcional)", "1 dente de alho picado", "1 colher de sopa de molho de soja light",
          "1 colher de chá de amido de milho", "1 colher de chá de azeite", "arroz integral para servir"],
 "passos": [
   "Tempere os cubos de frango com um pouco do molho de soja e o alho. Deixe pegar gosto por 5 minutos.",
   "Dissolva o amido de milho em meia xícara de água com o restante do molho de soja. Misture bem e deixe de lado — é o que vai engrossar o molho.",
   "Aqueça uma frigideira grande com metade do azeite em fogo alto. Doure os cubos de frango por 5 minutos, mexendo, até ficarem brancos por dentro. Tire e deixe de lado.",
   "Na mesma frigideira, coloque o restante do azeite e junte o pimentão, a cebola e o salsão. Mexa em fogo alto por 3 minutos, até ficarem macios mas ainda crocantes.",
   "Volte o frango, mexa a mistura de amido e despeje na frigideira. Mexa por 1 a 2 minutos, até o molho engrossar e ficar brilhante, cobrindo tudo. Sirva sobre o arroz integral."],
 "porcoes8": ["½ porção · 3 col. arroz",
              "1 porção · 4 col. arroz",
              "1 porção · 5 col. arroz",
              "1 porção · 5 col. arroz · frango extra",
              "1 porção · 5 col. arroz",
              "1 porção grande · 6 col. arroz",
              "porção + frango · 7 col. arroz",
              "porção dupla · 8 col. arroz"],
 "dica": "Fazer em casa você controla o óleo e o açúcar que os restaurantes exageram. O frango dá proteína magra, os legumes entram crocantes com pouca caloria e um toque só de amido dá aquele molho bonito sem engordar o prato.",
 "prompt": "Square ultra-realistic overhead food photograph of a light chicken stir-fry with diced pepper, onion and celery in a glossy sauce, served over brown rice, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bowl Mexicano de Carne, Feijão Preto e Milho",
 "hook": "Todas as cores e sabores do México numa tigela — farto, temperado e surpreendentemente leve.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 490,
 "ings": ["250 g de carne moída magra", "1 xícara de feijão preto cozido", "½ xícara de milho",
          "4 colheres de sopa de arroz cozido", "1 tomate em cubos", "½ abacate em fatias",
          "folhas verdes", "1 dente de alho picado", "1 colher de chá de azeite",
          "cominho, sal, pimenta e coentro a gosto", "suco de ½ limão"],
 "passos": [
   "Aqueça o azeite numa frigideira e frite o alho por 30 segundos. Junte a carne moída e mexa, quebrando os pedaços, até perder a cor rosada.",
   "Tempere a carne com cominho, sal e pimenta e cozinhe por mais 3 minutos. Junte o feijão preto e o milho e aqueça por 2 minutos.",
   "Numa tigela, faça uma cama de folhas verdes e coloque o arroz de um lado.",
   "Distribua por cima a carne com feijão e milho, o tomate e as fatias de abacate.",
   "Regue com o suco de limão, salpique coentro e sirva."],
 "porcoes8": ["½ porção · 3 col. arroz · ¼ abacate",
              "1 porção · 4 col. arroz · ¼ abacate",
              "1 porção · 4 col. arroz · ½ abacate",
              "1 porção · 5 col. arroz · ½ abacate",
              "1 porção · 5 col. arroz · ½ abacate",
              "1 porção grande · 6 col. arroz · ½ abacate",
              "porção grande · 7 col. arroz · ½ abacate",
              "porção dupla · 8 col. arroz · abacate"],
 "dica": "É um prato completo numa tigela só: proteína da carne, fibra do feijão e do milho, e a gordura boa do abacate, que dá cremosidade e saciedade. Bem temperado, satisfaz a vontade de comida de boteco sem o excesso de gordura.",
 "prompt": "Square ultra-realistic overhead food photograph of a Mexican burrito bowl with seasoned ground beef, black beans, corn, rice, tomato, avocado slices and green leaves, lime wedge, in a bowl, on a light wooden table, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salada de Frango Grelhado com Manga",
 "hook": "Doce, salgada e refrescante: o frango grelhado quentinho encontra a manga docinha numa salada que não parece dieta.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 400,
 "ings": ["1 filé de peito de frango (≈ 130 g)", "folhas verdes variadas", "½ manga em cubos",
          "½ pepino em rodelas", "cebola roxa em fatias finas", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e hortelã a gosto"],
 "passos": [
   "Tempere o frango com sal e pimenta. Aqueça uma frigideira que não gruda em fogo médio-alto e grelhe o filé por 4 a 5 minutos de cada lado, até dourar e ficar branco por dentro. Deixe amornar e corte em tiras.",
   "Descasque a manga e corte a polpa em cubos. Corte o pepino em rodelas e a cebola em fatias bem finas.",
   "Numa tigela grande ou prato fundo, espalhe as folhas verdes.",
   "Distribua por cima os cubos de manga, o pepino, a cebola e as tiras de frango.",
   "Faça o molho misturando o azeite, o suco de limão, sal e pimenta. Regue a salada, salpique hortelã e sirva."],
 "porcoes8": ["100 g frango · ¼ manga · salada",
              "130 g frango · ½ manga · salada",
              "130 g frango · ½ manga · salada",
              "150 g frango · ½ manga · 1 fio de azeite",
              "150 g frango · ½ manga · salada",
              "170 g frango · ½ manga · 1 col. castanhas",
              "200 g frango · 1 manga · castanhas",
              "220 g frango · 1 manga · castanhas"],
 "dica": "A manga entra como um doce natural, sem açúcar adicionado, e satisfaz a vontade de doce dentro de uma refeição salgada. O frango grelhado dá a proteína que sacia, e o volume de folhas e legumes enche o prato com pouquíssima caloria. Uma salada que é refeição completa.",
 "prompt": "Square ultra-realistic overhead food photograph of a fresh salad with grilled chicken strips, mango cubes, cucumber, red onion and mixed green leaves, mint on top, lemon dressing, in a bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Filé de Frango ao Curry Leve com Arroz",
 "hook": "Um molho dourado e perfumado que transforma o frango de sempre — cremoso sem creme, com leite de coco light.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["2 filés de peito de frango em cubos (≈ 300 g)", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de curry em pó", "½ xícara de leite de coco light (ou leite comum)",
          "1 tomate picado", "1 colher de chá de azeite", "sal e pimenta a gosto", "arroz para servir"],
 "passos": [
   "Tempere os cubos de frango com sal, pimenta e metade do curry.",
   "Aqueça o azeite numa panela em fogo médio e doure os cubos de frango por fora, mexendo, por 5 minutos. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o alho por 2 minutos. Junte o restante do curry e mexa por 30 segundos, só para o tempero soltar o cheiro.",
   "Acrescente o tomate e cozinhe por 3 minutos, até desmanchar. Volte o frango e junte o leite de coco.",
   "Cozinhe em fogo baixo por 8 a 10 minutos, mexendo de vez em quando, até o molho engrossar e o frango ficar macio. Sirva sobre o arroz."],
 "porcoes8": ["½ porção · 3 col. arroz",
              "1 porção · 4 col. arroz",
              "1 porção · 5 col. arroz",
              "1 porção · 5 col. arroz · frango extra",
              "1 porção · 5 col. arroz",
              "1 porção grande · 6 col. arroz",
              "porção + frango · 7 col. arroz",
              "porção dupla · 8 col. arroz"],
 "dica": "O leite de coco light dá cremosidade ao molho com muito menos gordura que o creme de leite. O curry perfuma e dá a sensação de um prato especial, o que ajuda a comer devagar e ficar satisfeito com uma porção controlada de frango e arroz.",
 "prompt": "Square ultra-realistic overhead food photograph of a light chicken curry in a golden sauce served over white rice in a bowl, garnished with coriander, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sardinha Assada com Batata e Salada",
 "hook": "Barata, cheia de ômega-3 e pronta em minutos — a sardinha é uma das melhores amigas de quem quer emagrecer com pouco dinheiro.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 450,
 "ings": ["3 a 4 sardinhas frescas limpas (ou 1 lata de sardinha em água)", "1 batata pequena em rodelas",
          "1 colher de chá de azeite", "suco de ½ limão", "1 dente de alho picado",
          "sal, pimenta e orégano a gosto", "folhas verdes e tomate para a salada"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a batata em rodelas finas, tempere com sal, metade do azeite e espalhe numa assadeira.",
   "Leve a batata ao forno por 10 minutos, para começar a amaciar.",
   "Tempere as sardinhas com sal, pimenta, alho, orégano e o suco de limão.",
   "Tire a assadeira, coloque as sardinhas entre as batatas e regue com o restante do azeite.",
   "Volte ao forno por mais 15 minutos, até as sardinhas ficarem douradas e a batata macia. Sirva com uma salada verde fresca ao lado.",
   "Se usar sardinha de lata, pule o forno para o peixe: só asse a batata e monte o prato com a sardinha escorrida e a salada."],
 "porcoes8": ["2 sardinhas · ½ batata · salada",
              "3 sardinhas · 1 batata pequena · salada",
              "3 sardinhas · 1 batata · salada",
              "4 sardinhas · 1 batata · 1 fio de azeite",
              "4 sardinhas · 1 batata · salada",
              "4 sardinhas · 1 batata grande · salada",
              "5 sardinhas · 1 batata grande · 1 fio de azeite",
              "6 sardinhas · 2 batatas pequenas · salada"],
 "dica": "A sardinha é um peixinho poderoso: muito ômega-3 (a gordura boa que faz bem ao coração), proteína e cálcio, por um preço baixíssimo. Assada com um pouco de batata e uma salada fresca, vira um almoço completo, nutritivo e econômico.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-baked sardines with sliced roasted potatoes, a fresh green salad with tomato and a lemon wedge, on a light plate, wooden table, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Berinjela Recheada com Carne Moída",
 "hook": "A própria berinjela vira a tigela — recheada de carne temperada e gratinada, é bonita e engana qualquer vontade de comilança.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 420,
 "ings": ["1 berinjela grande", "200 g de carne moída magra", "1 cebola picada", "1 dente de alho picado",
          "1 tomate picado", "1 colher de chá de azeite", "2 colheres de sopa de queijo ralado magro",
          "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a berinjela ao meio no comprimento. Com uma colher, retire parte do miolo, formando duas 'barquinhas'. Pique o miolo retirado.",
   "Coloque as barquinhas numa assadeira, regue com um pouco de azeite e asse por 10 minutos, só para amaciar.",
   "Enquanto isso, numa frigideira, frite a cebola e o alho no restante do azeite por 2 minutos. Junte a carne moída e mexa até perder a cor rosada.",
   "Acrescente o tomate, o miolo picado da berinjela, sal e pimenta e cozinhe por 5 minutos, até formar um recheio macio.",
   "Recheie as barquinhas de berinjela com a carne, polvilhe o queijo ralado por cima e volte ao forno por 15 minutos, até gratinar (o queijo derreter e dourar). Salpique salsinha e sirva."],
 "porcoes8": ["½ berinjela · salada",
              "1 berinjela recheada · salada",
              "1 berinjela · 2 col. arroz",
              "1 berinjela · carne extra · salada",
              "1 berinjela · carne extra · 2 col. arroz",
              "1 berinjela grande · 3 col. arroz",
              "1 berinjela · carne dupla · 4 col. arroz",
              "berinjela + porção extra de carne · 4 col. arroz"],
 "dica": "A berinjela tem muita água e fibra, então enche o estômago com pouquíssima caloria — recheada, dá volume ao prato e sacia. A carne magra entra com a proteína, e um pouco de queijo por cima mata a vontade de gratinado sem exageros.",
 "prompt": "Square ultra-realistic overhead food photograph of two baked stuffed eggplant halves filled with seasoned ground beef and melted cheese, sprinkled with parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salada Caesar Fit com Frango Grelhado",
 "hook": "A salada Caesar cremosa que você ama, com um molho de iogurte esperto — toda a cremosidade, nenhuma culpa.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 400,
 "ings": ["1 filé de frango grelhado em tiras (≈ 130 g)", "folhas de alface romana", "1 fatia de pão integral em cubos",
          "2 colheres de sopa de iogurte natural sem açúcar", "1 colher de chá de mostarda",
          "1 colher de chá de queijo ralado", "suco de ½ limão", "1 dente de alho amassado", "sal e pimenta a gosto"],
 "passos": [
   "Tempere o frango com sal e pimenta e grelhe numa frigideira que não gruda por 4 minutos de cada lado, até dourar e ficar branco por dentro. Corte em tiras.",
   "Faça os croutons: espalhe os cubos de pão integral numa assadeira e leve ao forno médio por 8 minutos, até ficarem crocantes (ou toste numa frigideira sem óleo).",
   "Prepare o molho: numa tigelinha, misture o iogurte, a mostarda, o queijo ralado, o suco de limão, o alho amassado, sal e pimenta, até virar um creme.",
   "Rasgue a alface com as mãos e coloque numa tigela grande. Regue com o molho e misture para cobrir as folhas.",
   "Coloque as tiras de frango e os croutons por cima e sirva na hora, para o pão continuar crocante."],
 "porcoes8": ["100 g frango · salada · poucos croutons",
              "130 g frango · salada · croutons",
              "130 g frango · salada · croutons",
              "150 g frango · salada · 1 col. queijo a mais",
              "150 g frango · salada · croutons",
              "170 g frango · salada · croutons",
              "200 g frango · salada · croutons extras",
              "220 g frango · salada · croutons extras"],
 "dica": "O molho Caesar tradicional é uma bomba de maionese e óleo. Trocando por iogurte com mostarda e limão, você mantém a cremosidade e o gostinho marcante com muito menos gordura. O frango grelhado transforma a salada numa refeição de verdade, cheia de proteína.",
 "prompt": "Square ultra-realistic overhead food photograph of a Caesar salad with grilled chicken strips, romaine lettuce, wholegrain croutons and a creamy dressing, grated cheese on top, in a bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tiras de Carne com Pimentão e Arroz",
 "hook": "Carne em tiras finas salteada com pimentões coloridos — cheirosa, temperada e pronta na frigideira em minutos.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["250 g de carne magra em tiras finas (alcatra ou patinho)", "1 pimentão vermelho em tiras",
          "1 pimentão amarelo em tiras", "1 cebola em tiras", "1 dente de alho picado",
          "1 colher de chá de azeite", "suco de ½ limão", "cominho, sal, pimenta e coentro a gosto",
          "arroz para servir"],
 "passos": [
   "Tempere as tiras de carne com sal, pimenta, cominho, o alho e o suco de limão. Deixe pegar gosto por 10 minutos.",
   "Aqueça uma frigideira grande com metade do azeite em fogo alto. Coloque a carne aos poucos (não toda de uma vez, senão solta água) e doure rápido, mexendo, por 3 minutos. Tire e deixe de lado.",
   "Na mesma frigideira, com o restante do azeite, junte a cebola e os pimentões. Mexa em fogo alto por 4 minutos, até ficarem macios mas ainda firmes e coloridos.",
   "Volte a carne à frigideira e misture por 1 minuto, só para juntar os sabores.",
   "Salpique coentro e sirva sobre uma porção de arroz. Fica ótimo também enrolado numa tortilha integral."],
 "porcoes8": ["½ porção · 3 col. arroz",
              "1 porção · 4 col. arroz",
              "1 porção · 5 col. arroz",
              "1 porção · 5 col. arroz · carne extra",
              "1 porção · 5 col. arroz",
              "1 porção grande · 6 col. arroz",
              "porção + carne · 7 col. arroz",
              "porção dupla · 8 col. arroz"],
 "dica": "Cortar a carne em tiras finas rende mais: uma porção pequena parece muito mais no prato. Salteada rápido em fogo alto com pimentões, fica suculenta e cheia de sabor sem precisar de molho gorduroso. Os pimentões dão cor, vitamina e fibra por quase nenhuma caloria.",
 "prompt": "Square ultra-realistic overhead food photograph of sautéed beef strips with colorful red and yellow pepper strips and onion, served over white rice, garnished with coriander, in a bowl, on a light wooden table, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Hambúrguer Caseiro de Carne Magra com Salada",
 "hook": "O hambúrguer que mata a vontade e ainda emagrece — feito em casa com carne magra, sem pão gorduroso.",
 "tempo": "20 min", "rende": "2 porções", "kcal_base": 440,
 "ings": ["250 g de carne moída magra", "½ cebola bem picada", "1 dente de alho picado",
          "sal, pimenta e salsinha a gosto", "1 colher de chá de azeite", "2 pães integrais para hambúrguer",
          "folhas de alface, tomate e cebola em rodelas para montar"],
 "passos": [
   "Numa tigela, misture a carne moída com a cebola picada, o alho, sal, pimenta e salsinha. Amasse com as mãos só até dar liga, sem trabalhar demais (senão o hambúrguer fica duro).",
   "Divida a carne em duas partes e modele dois discos, achatando bem com as mãos. Faça uma leve covinha no centro de cada um com o polegar — isso evita que inchem no meio.",
   "Aqueça uma frigideira que não gruda com poucas gotas de azeite em fogo médio-alto. Coloque os hambúrgueres e deixe 3 a 4 minutos de cada lado, sem apertar com a espátula, até dourar por fora e ficar no ponto por dentro.",
   "Se quiser, toste levemente o pão integral aberto na frigideira.",
   "Monte: pão, alface, o hambúrguer, o tomate e a cebola. Feche e sirva. Para uma versão ainda mais leve, coma o hambúrguer sem o pão, com uma salada bem servida ao lado."],
 "porcoes8": ["1 hambúrguer · sem pão · salada",
              "1 hambúrguer · ½ pão · salada",
              "1 hambúrguer · 1 pão · salada",
              "1 hambúrguer · 1 pão · salada",
              "1 hambúrguer grande · 1 pão · salada",
              "1 hambúrguer grande · 1 pão · salada",
              "2 hambúrgueres · 1 pão · salada",
              "2 hambúrgueres · 1 pão · salada"],
 "dica": "O problema do hambúrguer de lanchonete é a carne gorda, o molho e a fritura. Feito em casa com carne magra e grelhado sem óleo, ele vira proteína pura. Comendo com bastante salada e pouco (ou nenhum) pão, você mata a vontade sem estourar as calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of a homemade lean beef burger in a wholegrain bun with lettuce, tomato and onion, a fresh side salad, on a wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peixe Branco com Legumes e Cuscuz",
 "hook": "Um filé branco delicado sobre cuscuz fofo — leve, elegante e pronto antes de você perceber.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 420,
 "ings": ["1 filé de peixe branco (merluza, pescada ou tilápia, ≈ 150 g)", "½ xícara de cuscuz marroquino",
          "½ xícara de água quente", "1 xícara de legumes picados (vagem, cenoura, ervilha)",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Coloque o cuscuz numa tigela com uma pitada de sal, cubra com a água quente, tampe com um prato e deixe 5 minutos. Depois solte com um garfo até ficar soltinho.",
   "Cozinhe os legumes picados no vapor ou em pouca água fervente por 5 minutos, até ficarem macios mas ainda firmes. Escorra.",
   "Tempere o peixe com sal, pimenta e o suco de limão.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio. Coloque o filé e deixe 3 a 4 minutos de cada lado, virando com cuidado uma vez, até dourar e se soltar em lascas com o garfo.",
   "Misture os legumes ao cuscuz. Monte o prato com o cuscuz de legumes e o filé por cima. Salpique salsinha e sirva."],
 "porcoes8": ["120 g peixe · ⅓ xíc. cuscuz · legumes",
              "150 g peixe · ½ xíc. cuscuz · legumes",
              "150 g peixe · ½ xíc. cuscuz · legumes",
              "170 g peixe · ⅔ xíc. cuscuz · 1 fio de azeite",
              "170 g peixe · ⅔ xíc. cuscuz · legumes",
              "200 g peixe · ¾ xíc. cuscuz · legumes",
              "220 g peixe · 1 xíc. cuscuz · 1 fio de azeite",
              "250 g peixe · 1 xíc. cuscuz · 1 fio de azeite"],
 "dica": "Peixes brancos como merluza e pescada são magríssimos e leves, ideais para o almoço de quem quer emagrecer. O cuscuz marroquino cozinha só com água quente, sem gordura, e com os legumes vira um acompanhamento colorido, fofo e cheio de fibra.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared white fish fillet over couscous mixed with green beans, carrot and peas, a lemon wedge and parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Espetinho de Frango e Legumes com Arroz",
 "hook": "Coloridos e divertidos de montar, os espetinhos assam por igual e deixam qualquer almoço com clima de festa.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 450,
 "ings": ["2 filés de peito de frango em cubos (≈ 300 g)", "1 pimentão em quadrados", "1 cebola em pedaços",
          "1 abobrinha em rodelas grossas", "tomatinhos", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e páprica a gosto", "arroz para servir", "palitos de espeto"],
 "passos": [
   "Tempere os cubos de frango com sal, pimenta, páprica e o suco de limão. Deixe pegar gosto por 10 minutos.",
   "Monte os espetos alternando um cubo de frango, um pedaço de pimentão, um de cebola, uma rodela de abobrinha e um tomatinho, até encher o palito.",
   "Pincele os espetos com o azeite.",
   "Aqueça uma frigideira grande ou grelha em fogo médio-alto. Coloque os espetos e vá girando a cada 3 minutos, até o frango dourar por todos os lados e ficar branco por dentro (uns 12 minutos no total).",
   "Sirva os espetinhos sobre uma porção de arroz."],
 "porcoes8": ["1 espeto · 3 col. arroz",
              "2 espetos · 4 col. arroz",
              "2 espetos · 5 col. arroz",
              "2 espetos · 5 col. arroz · frango extra",
              "2 espetos · 5 col. arroz",
              "3 espetos · 6 col. arroz",
              "3 espetos · 7 col. arroz",
              "3 espetos grandes · 8 col. arroz"],
 "dica": "Os espetinhos ajudam a controlar a porção de forma natural e ainda misturam bastante legume à proteína. O frango magro grelhado dá saciedade sem gordura, e os legumes coloridos enchem o prato com fibra e vitaminas por quase nenhuma caloria.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled chicken and vegetable skewers with pepper, onion, zucchini and cherry tomato, served over rice on a plate, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salada de Batata Fit com Ovo e Atum",
 "hook": "A salada de batata cremosa das festas, sem a maionese pesada — vira almoço completo e leve.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 410,
 "ings": ["2 batatas médias em cubos", "2 ovos cozidos", "1 lata de atum em água, escorrido",
          "3 colheres de sopa de iogurte natural sem açúcar", "1 colher de chá de mostarda",
          "cebola roxa e cheiro-verde picados", "sal, pimenta e suco de ½ limão a gosto"],
 "passos": [
   "Cozinhe os cubos de batata em água fervente com sal por 12 a 15 minutos, até ficarem macios mas sem desmanchar (um garfo entra com facilidade). Escorra e deixe esfriar um pouco.",
   "Cozinhe os ovos por 9 minutos, passe em água fria, descasque e corte em pedaços.",
   "Prepare o molho: misture o iogurte, a mostarda, o suco de limão, sal e pimenta numa tigela grande.",
   "Junte à tigela a batata morna, o atum escorrido, os ovos, a cebola roxa e o cheiro-verde.",
   "Misture com cuidado, para não desmanchar a batata. Prove o sal e sirva na hora ou gelado."],
 "porcoes8": ["½ porção · ½ lata atum · 1 ovo",
              "1 porção · 1 lata atum · 2 ovos",
              "1 porção · 1 lata atum · 2 ovos",
              "1 porção · 1 lata atum · 2 ovos · salada verde",
              "1 porção · 1 lata atum · 2 ovos",
              "1 porção grande · 1½ lata atum · 2 ovos",
              "porção grande · 1½ lata atum · 3 ovos",
              "porção dupla · 2 latas atum · 3 ovos"],
 "dica": "Trocar a maionese pelo iogurte com mostarda corta muita gordura e ainda soma proteína. O atum e o ovo transformam uma salada de batata em refeição completa e saciante. A batata gelada até forma uma fibra especial que alimenta as bactérias boas do intestino.",
 "prompt": "Square ultra-realistic overhead food photograph of a healthy potato salad with tuna, chopped boiled egg, red onion and herbs in a creamy yogurt dressing, in a white bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango Assado no Forno com Legumes de Raiz",
 "hook": "Coloca tudo numa assadeira e deixa o forno trabalhar — o frango sai douradinho e os legumes ficam macios e adocicados.",
 "tempo": "45 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["2 sobrecoxas de frango sem pele (ou 2 filés grossos, ≈ 300 g)", "1 batata em pedaços",
          "1 cenoura em pedaços grandes", "1 pedaço de abóbora em cubos", "1 cebola em gomos",
          "2 dentes de alho", "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta e alecrim a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a batata, a cenoura, a abóbora e a cebola em pedaços grandes e parecidos, para assarem por igual.",
   "Numa assadeira grande, espalhe os legumes e os dentes de alho. Tempere com sal, pimenta, alecrim e metade do azeite, e misture com as mãos.",
   "Tempere o frango com sal, pimenta, o suco de limão e o restante do azeite. Coloque as peças entre os legumes.",
   "Leve ao forno por 35 a 40 minutos, virando os legumes na metade do tempo, até o frango ficar dourado e cozido por dentro (o líquido que escorre ao furar tem que sair transparente) e os legumes macios.",
   "Sirva direto da assadeira, com todo o caldinho que se formou no fundo."],
 "porcoes8": ["1 sobrecoxa · ½ porção legumes",
              "1 sobrecoxa · 1 porção legumes",
              "1 sobrecoxa grande · 1 porção legumes",
              "2 sobrecoxas · 1 porção legumes",
              "2 sobrecoxas · 1 porção legumes",
              "2 sobrecoxas · 1 porção grande legumes",
              "2 sobrecoxas · porção grande legumes",
              "3 sobrecoxas · porção dupla legumes"],
 "dica": "Assar sem pele e sem óleo demais deixa o frango leve, e o próprio caldo que ele solta tempera os legumes sem precisar de gordura. A abóbora e a cenoura ficam docinhas ao assar, matando a vontade de doce, e enchem o prato com fibra e vitamina por poucas calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-roasted chicken thighs with root vegetables, potato, carrot, pumpkin and onion on a roasting tray, sprig of rosemary, golden and juicy, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango à Parmegiana Fit Assado com Salada",
 "hook": "A parmegiana crocante e gratinada dos seus sonhos, assada no forno em vez de frita — todo o prazer, sem a fritura.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["2 filés de peito de frango finos (≈ 300 g)", "1 ovo", "4 colheres de sopa de farinha de rosca integral",
          "1 xícara de molho de tomate caseiro", "3 colheres de sopa de queijo muçarela magro ralado",
          "sal, pimenta e orégano a gosto", "folhas verdes para a salada"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Tempere os filés finos com sal e pimenta.",
   "Bata o ovo num prato fundo. Coloque a farinha de rosca em outro prato, misturada com orégano.",
   "Passe cada filé primeiro no ovo, depois na farinha de rosca, apertando para cobrir bem os dois lados.",
   "Coloque os filés numa assadeira que não gruda (ou forrada com papel-manteiga) e asse por 15 minutos, virando na metade, até a casquinha ficar dourada e crocante.",
   "Cubra cada filé com o molho de tomate e o queijo ralado. Volte ao forno por mais 8 minutos, até o queijo derreter e borbulhar.",
   "Sirva com uma salada verde fresca ao lado."],
 "porcoes8": ["100 g frango · pouco queijo · salada",
              "130 g frango · queijo · salada",
              "150 g frango · queijo · salada",
              "150 g frango · queijo · 3 col. arroz",
              "150 g frango · queijo · 3 col. arroz",
              "170 g frango · queijo · 4 col. arroz",
              "200 g frango · queijo · 5 col. arroz",
              "220 g frango · queijo extra · 5 col. arroz"],
 "dica": "A parmegiana engorda por causa da fritura e do excesso de queijo. Empanada com farinha integral e assada no forno, ela fica crocante com uma fração da gordura. Um pouco de queijo magro por cima mata a vontade de gratinado, e a salada equilibra o prato.",
 "prompt": "Square ultra-realistic overhead food photograph of an oven-baked chicken parmigiana with tomato sauce and melted cheese, crispy golden coating, a fresh green salad beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bowl de Arroz, Edamame e Salmão",
 "hook": "Inspirado no poke havaiano: fresco, colorido e nutritivo, monta-se numa tigela e sacia sem pesar.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 480,
 "ings": ["1 posta de salmão em cubos (≈ 130 g)", "4 colheres de sopa de arroz cozido", "½ xícara de edamame (soja verde) cozido",
          "½ pepino em cubinhos", "½ cenoura ralada", "½ abacate em fatias", "1 colher de sopa de molho de soja light",
          "gergelim, suco de ½ limão e cebolinha a gosto"],
 "passos": [
   "Cozinhe o edamame em água fervente por 4 minutos, escorra e, se estiver na vagem, retire os grãozinhos.",
   "Tempere os cubos de salmão com o molho de soja e o suco de limão. Deixe pegar gosto por 5 minutos. (Se preferir cozido, grelhe rapidamente os cubos numa frigideira por 3 minutos.)",
   "Numa tigela, coloque o arroz de um lado como base.",
   "Disponha por cima, em grupos separados, o salmão, o edamame, o pepino, a cenoura ralada e o abacate.",
   "Regue com um pouco mais de molho de soja, salpique gergelim e cebolinha e sirva."],
 "porcoes8": ["100 g salmão · 3 col. arroz · ¼ abacate",
              "130 g salmão · 4 col. arroz · ½ abacate",
              "130 g salmão · 5 col. arroz · ½ abacate",
              "150 g salmão · 5 col. arroz · ½ abacate",
              "150 g salmão · 5 col. arroz · ½ abacate",
              "170 g salmão · 6 col. arroz · ½ abacate",
              "200 g salmão · 7 col. arroz · abacate",
              "220 g salmão · 8 col. arroz · abacate"],
 "dica": "É um prato completo e equilibrado: proteína e ômega-3 do salmão, proteína vegetal do edamame, gordura boa do abacate e a fibra dos legumes crus. Montado em tigela, fica bonito e saciante, provando que comida saudável pode ser uma festa para os olhos.",
 "prompt": "Square ultra-realistic overhead food photograph of a poke-style bowl with salmon cubes, rice, edamame, cucumber, grated carrot and avocado slices, sesame seeds on top, in a bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sopa Substanciosa de Legumes com Frango Desfiado",
 "hook": "Uma sopa que é refeição de verdade: encorpada de frango e legumes, esquenta o corpo e sacia sem pesar.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 380,
 "ings": ["1 filé de peito de frango (≈ 150 g)", "1 batata em cubos", "1 cenoura em cubos",
          "1 abobrinha em cubos", "½ xícara de milho ou ervilha", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto", "1 litro de água"],
 "passos": [
   "Numa panela grande, aqueça o azeite e frite a cebola e o alho por 2 minutos, mexendo, até ficarem transparentes.",
   "Junte o filé de frango inteiro e a água. Deixe ferver e cozinhe por 15 minutos, até o frango ficar cozido.",
   "Retire o frango, deixe amornar e desfie com dois garfos. Deixe de lado.",
   "Na mesma água, junte a batata, a cenoura, a abobrinha e o milho. Tempere com sal e pimenta e cozinhe por 12 a 15 minutos, até os legumes ficarem macios.",
   "Volte o frango desfiado à panela, ajuste o sal e cozinhe por mais 3 minutos. Salpique cheiro-verde e sirva bem quente."],
 "porcoes8": ["1 concha · frango · sem batata extra",
              "2 conchas · frango · legumes",
              "2 conchas · frango · legumes",
              "2 conchas · frango extra · 1 fatia pão",
              "2 conchas · frango extra · 1 fatia pão",
              "3 conchas · frango · 1 fatia pão",
              "3 conchas · frango extra · 2 fatias pão",
              "3 conchas grandes · frango duplo · 2 fatias pão"],
 "dica": "Sopas são ótimas para emagrecer: o volume de líquido e legumes enche o estômago com pouquíssimas calorias, e o calor faz comer mais devagar. Com o frango desfiado, ela deixa de ser só uma entrada e vira uma refeição completa, leve e reconfortante.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty chicken and vegetable soup with shredded chicken, potato, carrot, zucchini and corn in a broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Panqueca Salgada de Aveia Recheada com Frango",
 "hook": "A massa leva só ovo e aveia, bate em segundos e vira uma panqueca dourada recheada de frango cremoso.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 400,
 "ings": ["1 ovo", "3 colheres de sopa de aveia", "3 colheres de sopa de água", "1 pitada de sal",
          "1 filé de frango cozido e desfiado (≈ 100 g)", "2 colheres de sopa de molho de tomate",
          "1 colher de sopa de iogurte natural", "1 colher de chá de azeite", "orégano a gosto"],
 "passos": [
   "Numa tigela, bata com um garfo o ovo, a aveia, a água e o sal até virar uma massa lisa. Deixe descansar 3 minutos para a aveia absorver o líquido.",
   "Aqueça uma frigideira que não gruda com metade do azeite em fogo médio. Despeje a massa e espalhe girando a frigideira, formando um disco fino.",
   "Deixe 2 minutos, até a borda soltar, vire com cuidado e doure o outro lado por mais 1 minuto. Tire a panqueca.",
   "Misture o frango desfiado com o molho de tomate, o iogurte e o orégano, e aqueça rapidamente na frigideira.",
   "Recheie a panqueca com o frango, dobre ao meio ou enrole e sirva quente, com uma salada ao lado se quiser."],
 "porcoes8": ["1 panqueca · 80 g frango",
              "1 panqueca · 100 g frango",
              "1 panqueca · 120 g frango",
              "1 panqueca · 120 g frango · salada",
              "1 panqueca · 130 g frango · salada",
              "2 panquecas · 150 g frango",
              "2 panquecas · 170 g frango · salada",
              "2 panquecas · 200 g frango · salada"],
 "dica": "A massa de ovo e aveia troca a farinha branca por fibra e proteína, saciando muito mais que uma panqueca comum. Recheada com frango desfiado e um molho leve de iogurte, vira uma refeição prática, gostosa e completa, ótima também para o jantar.",
 "prompt": "Square ultra-realistic overhead food photograph of a savory oat pancake filled with shredded chicken in tomato sauce, folded on a plate, a small salad beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Camarão ao Alho com Legumes e Arroz",
 "hook": "Camarões rosados dourados no alho, perfumando a cozinha inteira — um almoço de fim de semana leve e especial.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 430,
 "ings": ["150 g de camarão limpo", "4 colheres de sopa de arroz cozido", "1 xícara de brócolis e vagem",
          "2 dentes de alho picados", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Seque bem os camarões com papel-toalha e tempere com sal, pimenta e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Corte o brócolis em buquês e a vagem em pedaços. Cozinhe no vapor ou em pouca água fervente por 4 minutos, até ficarem verdes e macios mas ainda firmes. Escorra.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio. Junte o alho picado e mexa por 30 segundos, só até cheirar e começar a dourar — cuidado para não queimar, senão fica amargo.",
   "Coloque os camarões e salteie (mexa em fogo médio-alto) por 2 a 3 minutos, só até ficarem rosados e enrolarem. Não passe do ponto, senão ficam borrachudos.",
   "Junte os legumes e o arroz já cozido à frigideira e misture por 1 minuto, para pegar o sabor do alho. Salpique salsinha e sirva na hora."],
 "porcoes8": ["120 g camarão · 3 col. arroz · legumes",
              "150 g camarão · 4 col. arroz · legumes",
              "150 g camarão · 5 col. arroz · legumes",
              "170 g camarão · 5 col. arroz · 1 fio de azeite",
              "170 g camarão · 5 col. arroz · legumes",
              "200 g camarão · 6 col. arroz · legumes",
              "220 g camarão · 7 col. arroz · 1 fio de azeite",
              "250 g camarão · 8 col. arroz · 1 fio de azeite"],
 "dica": "O camarão é quase todo proteína, com pouquíssima gordura e poucas calorias, então dá para se servir bem sem culpa. Dourado no alho, ganha muito sabor com só um fio de azeite, e com os legumes e uma porção medida de arroz vira um prato leve com cara de restaurante.",
 "prompt": "Square ultra-realistic overhead food photograph of garlic shrimp sautéed golden, served with steamed broccoli, green beans and white rice, parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Almôndegas de Carne ao Molho com Purê de Batata",
 "hook": "Almôndegas macias num molho de tomate encorpado, sobre um purê leve — o abraço quente que a dieta permite.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 490,
 "ings": ["250 g de carne moída magra", "1 ovo", "2 colheres de sopa de aveia", "1 dente de alho picado",
          "3 tomates picados (ou molho de tomate)", "1 cebola picada", "2 batatas médias",
          "1 colher de chá de azeite", "sal, pimenta e manjericão a gosto"],
 "passos": [
   "Descasque e cozinhe as batatas em água fervente por 15 minutos, até ficarem bem macias. Escorra e amasse com um garfo, com uma pitada de sal, até virar um purê liso. Se quiser mais cremoso, junte um pouco da água do cozimento.",
   "Numa tigela, misture a carne moída, o ovo, a aveia, metade do alho, sal e pimenta. Amasse com as mãos e enrole bolinhas do tamanho de uma noz.",
   "Aqueça o azeite numa panela e doure as almôndegas por todos os lados, girando com cuidado, por 5 minutos. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o restante do alho por 2 minutos. Junte os tomates, sal e pimenta e cozinhe por 8 minutos, até virar molho.",
   "Volte as almôndegas ao molho e cozinhe por mais 8 minutos, até ficarem cozidas por dentro. Salpique manjericão.",
   "Sirva as almôndegas com o molho sobre o purê de batata."],
 "porcoes8": ["3 almôndegas · ½ porção purê",
              "4 almôndegas · 1 porção purê",
              "4 almôndegas · 1 porção purê",
              "5 almôndegas · 1 porção purê",
              "5 almôndegas · 1 porção purê",
              "6 almôndegas · 1 porção grande purê",
              "7 almôndegas · porção grande purê",
              "8 almôndegas · porção dupla purê"],
 "dica": "As almôndegas levam aveia no lugar de mais pão, o que dá liga com fibra em vez de amido branco. Feitas com carne magra e cozidas no molho (não fritas), ficam suculentas e leves. O purê de batata comum, na medida certa, é reconfortante e sacia bem.",
 "prompt": "Square ultra-realistic overhead food photograph of tender beef meatballs in tomato sauce served over creamy mashed potato, garnished with basil, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Risoto Leve de Frango e Legumes",
 "hook": "A cremosidade do risoto sem manteiga nem excesso de queijo — o arroz solta o próprio creme e abraça o frango e os legumes.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 480,
 "ings": ["1 xícara de arroz (arbóreo ou comum)", "2 filés de peito de frango em cubos (≈ 300 g)",
          "1 cenoura em cubinhos", "½ xícara de ervilha", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de azeite", "1 colher de sopa de queijo ralado", "sal, pimenta e salsinha a gosto",
          "caldo de legumes caseiro ou água quente (uns 3 copos)"],
 "passos": [
   "Tempere os cubos de frango com sal e pimenta. Aqueça o azeite numa panela e doure o frango por 5 minutos, mexendo. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o alho por 2 minutos. Junte o arroz e mexa por 1 minuto, só para envolver os grãos no tempero.",
   "Comece a juntar o caldo quente aos poucos, uma concha de cada vez, mexendo sempre. Só coloque mais caldo quando o anterior tiver quase secado.",
   "Na metade do cozimento (uns 10 minutos), junte a cenoura e a ervilha. Continue mexendo e colocando caldo.",
   "Quando o arroz estiver macio e cremoso (uns 18 a 20 minutos no total), volte o frango, junte o queijo ralado e mexa. Desligue, salpique salsinha e sirva na hora."],
 "porcoes8": ["½ porção · frango",
              "1 porção · frango",
              "1 porção · frango",
              "1 porção · frango extra",
              "1 porção · frango extra",
              "1 porção grande · frango",
              "porção grande · frango extra",
              "porção dupla · frango extra"],
 "dica": "O risoto tradicional leva muita manteiga e queijo. Aqui, a cremosidade vem do próprio amido do arroz liberado ao mexer, com só um toque de queijo. Com bastante frango e legumes, o prato fica encorpado e satisfatório, provando que dá para comer risoto sem culpa.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy chicken and vegetable risotto with carrot and peas, garnished with parsley and a little grated cheese, in a shallow bowl, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
