# -*- coding: utf-8 -*-
"""BREAKFAST recipes (001-030). English (US market).
porcoes8 order: Woman 120-155/155-185/185-220/220+ lb · Man 155-185/185-220/220-265/265+ lb
Targets (cal): 300/370/420/470 · 450/510/560/620
US units: cups / tablespoons (tbsp) / teaspoons (tsp) / oz / °F.
Photos are shared with the PT edition (same fotos/001..030).
"""

RECEITAS = [
{
 "nome": "Banana Oat Pancakes",
 "hook": "Three ingredients you already have at home, ready in 10 minutes — and they hold your hunger until lunch.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 325,
 "ings": ["1 ripe banana", "½ cup rolled oats", "1 egg",
          "1 pinch of cinnamon", "1 pinch of baking powder (optional, makes them fluffier)",
          "a little oil or spray for the pan"],
 "passos": [
   "Peel the banana and put it in a deep dish. Mash it well with a fork until it becomes a smooth purée, with no big lumps.",
   "Add the egg and stir until everything is well combined.",
   "Add the oats, cinnamon and baking powder. Stir and let it rest for 3 minutes — the oats soak up the moisture and the batter firms up, which makes it easier to flip later.",
   "Heat a nonstick pan over medium-low heat and add a little oil (or spray).",
   "With a spoon, drop small portions of batter, about half the size of your hand. Small pancakes flip much more easily than big ones.",
   "Cook for 2 to 3 minutes, until little bubbles appear on top and the edges set. Flip carefully and brown the other side for another 1 to 2 minutes.",
   "Serve warm. If you like, finish with banana slices, a handful of berries or a teaspoon of honey."],
 "porcoes8": ["¾ banana · ⅓ cup oats · 1 egg",
              "1 banana · ½ cup oats · 1 egg · 1 handful of berries",
              "1 banana · ½ cup oats · 1 egg · 1 tsp peanut butter",
              "1 banana · ⅔ cup oats · 1 egg · 1 tbsp peanut butter",
              "1 banana · ⅔ cup oats · 2 eggs · 1 tsp peanut butter",
              "1 large banana · ⅔ cup oats · 2 eggs · 1 tbsp peanut butter",
              "1 large banana · ¾ cup oats · 2 eggs · 1 tbsp peanut butter · berries",
              "1 large banana · ¾ cup oats · 2 eggs · 1½ tbsp peanut butter"],
 "dica": "Oats are rich in fiber, which slows digestion and keeps you full for hours — that is what prevents the mid-morning hunger that makes you snack. The banana gives natural sweetness with no added sugar, and the egg brings protein to protect your muscle while you lose fat.",
 "prompt": "Square ultra-realistic overhead food photograph of a small stack of golden banana-oat pancakes on a white ceramic plate, topped with fresh banana slices and a few blueberries, a light drizzle of honey, a scatter of rolled oats beside the plate on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Scrambled Eggs with Spinach and Whole-Grain Toast",
 "hook": "The classic breakfast that fills your plate with protein and fiber in under 10 minutes.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["2 eggs", "1 large handful of fresh spinach leaves", "1 slice of whole-grain bread",
          "1 teaspoon of olive oil", "salt and pepper to taste", "1 small tomato (optional)"],
 "passos": [
   "Wash the spinach and drain it well. If the leaves are large, cut them in half.",
   "Crack the eggs into a bowl, season with salt and pepper and beat lightly with a fork.",
   "Heat the olive oil in a nonstick pan over medium heat. Add the spinach and stir for 1 minute, just until it wilts (the leaves go soft).",
   "Lower the heat, pour the beaten eggs over the spinach and leave for 30 seconds without stirring.",
   "With a spatula, push the eggs from the bottom to the center, slowly, until they are creamy and still moist. Turn off the heat before they dry out.",
   "Toast the slice of whole-grain bread. Serve the eggs on top or beside it, with tomato slices if you like."],
 "porcoes8": ["1 egg + 1 white · ½ slice bread · spinach freely",
              "2 eggs · 1 slice bread · spinach freely",
              "2 eggs · 1 slice bread · extra drizzle of olive oil",
              "2 eggs + 1 white · 1 slice bread · 1 tsp grated cheese",
              "3 eggs · 1 slice bread · 1 tsp olive oil",
              "3 eggs · 2 slices bread · spinach freely",
              "3 eggs · 2 slices bread · 1 tbsp grated cheese",
              "4 eggs · 2 slices bread · 1 tbsp grated cheese"],
 "dica": "Eggs are a complete protein and very filling — people who eat eggs at breakfast feel less hungry through the day. Spinach adds volume and fiber for almost no calories, so you fill your plate and your stomach without blowing your calories.",
 "prompt": "Square ultra-realistic overhead food photograph of soft scrambled eggs with wilted spinach on a white plate, one slice of toasted wholegrain bread and a few cherry tomatoes beside it, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Greek Yogurt with Berries and Oats",
 "hook": "Layered, with no cooking — protein and fiber in a pretty glass in 3 minutes.",
 "tempo": "3 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["¾ cup (6 oz) plain Greek yogurt, unsweetened", "1 handful of berries (strawberry, blueberry or raspberry)",
          "3 tablespoons rolled oats", "1 teaspoon honey (optional)", "cinnamon to taste"],
 "passos": [
   "If using strawberries, wash and cut into small pieces. Other berries can go in whole.",
   "In a glass, put half the yogurt at the bottom.",
   "Spread half the berries and half the oats on top.",
   "Repeat: the rest of the yogurt, then the remaining berries and oats.",
   "Finish with a pinch of cinnamon and, if you like, the drizzle of honey. Serve right away, while the oats are still crunchy."],
 "porcoes8": ["½ cup yogurt · berries · 2 tbsp oats",
              "¾ cup yogurt · berries · 3 tbsp oats",
              "¾ cup yogurt · berries · 3 tbsp oats · 1 tsp honey",
              "1 cup yogurt · berries · 4 tbsp oats · 1 tsp honey",
              "1 cup yogurt · berries · 4 tbsp oats · 1 tbsp nuts",
              "1¼ cup yogurt · berries · 4 tbsp oats · 1 tbsp nuts",
              "1¼ cup yogurt · berries · 5 tbsp oats · 1 tbsp nuts",
              "1½ cup yogurt · berries · 6 tbsp oats · 1 tbsp nuts"],
 "dica": "Greek yogurt has almost double the protein of regular yogurt, which keeps you full longer. With no added sugar, the sweetness comes from the fruit — and the oats add fiber and crunch, turning a quick snack into a meal that holds you.",
 "prompt": "Square ultra-realistic overhead food photograph of a layered Greek yogurt parfait in a clear glass, with fresh strawberries, blueberries and rolled oats, a light drizzle of honey and a dusting of cinnamon, on a light marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Egg-White Omelette with Tomato and Cottage Cheese",
 "hook": "Light, fluffy and packed with protein — breakfast for anyone who wants to slim down without going hungry.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["3 egg whites + 1 whole egg", "1 small tomato, diced", "2 tablespoons cottage cheese",
          "chopped chives or parsley", "salt and pepper to taste", "oil spray"],
 "passos": [
   "Dice the tomato and blot off the extra liquid with a paper towel, so the omelette does not go soggy.",
   "In a bowl, combine the egg whites, the whole egg, salt and pepper. Beat with a fork for 30 seconds, until slightly foamy.",
   "Heat a nonstick pan over medium heat and spray with oil. Spread the diced tomato on the bottom for 1 minute.",
   "Pour the beaten eggs on top and tilt the pan to spread them evenly.",
   "When the edges set (1 to 2 minutes), spread the cottage cheese over half the omelette.",
   "With the spatula, fold the omelette in half, covering the cottage cheese. Leave 1 more minute and serve with the herbs on top."],
 "porcoes8": ["2 whites + 1 egg · 1 tbsp cottage",
              "3 whites + 1 egg · 2 tbsp cottage",
              "3 whites + 1 egg · 2 tbsp cottage · ½ slice bread",
              "3 whites + 1 egg · 3 tbsp cottage · 1 slice bread",
              "3 whites + 2 eggs · 2 tbsp cottage · 1 slice bread",
              "4 whites + 2 eggs · 3 tbsp cottage · 1 slice bread",
              "4 whites + 2 eggs · 3 tbsp cottage · 2 slices bread",
              "5 whites + 2 eggs · 4 tbsp cottage · 2 slices bread"],
 "dica": "Egg whites are almost pure protein, with very little fat and calories — perfect for boosting the protein at breakfast without weighing you down. Cottage cheese comes in creamy and also high in protein, and the tomato adds flavor and volume for almost no calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded fluffy egg-white omelette with diced tomato and cottage cheese on a white plate, sprinkled with chopped chives, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Overnight Oats with Apple and Cinnamon",
 "hook": "You put it together at night and in the morning it is ready in the fridge — no rush, no stove.",
 "tempo": "5 min + fridge", "rende": "1 serving", "kcal_base": 350,
 "ings": ["½ cup rolled oats", "⅔ cup milk (or plant milk)", "½ apple, diced",
          "1 tablespoon plain yogurt", "cinnamon to taste", "1 teaspoon honey (optional)"],
 "passos": [
   "In a jar with a lid, mix the oats, the milk and the yogurt.",
   "Add half the diced apple and a good pinch of cinnamon. Stir well.",
   "Close the jar and refrigerate for at least 4 hours, or overnight.",
   "In the morning, the oats will be creamy and soft. Stir again.",
   "Top with the rest of the fresh apple and more cinnamon. If you like, add the drizzle of honey. Eat it cold, straight from the jar."],
 "porcoes8": ["⅓ cup oats · ½ cup milk · ½ apple",
              "½ cup oats · ⅔ cup milk · ½ apple",
              "½ cup oats · ⅔ cup milk · ½ apple · 1 tsp honey",
              "⅔ cup oats · ¾ cup milk · 1 apple · 1 tsp honey",
              "⅔ cup oats · ¾ cup milk · 1 apple · 1 tbsp nuts",
              "⅔ cup oats · 1 cup milk · 1 apple · 1 tbsp nuts",
              "¾ cup oats · 1 cup milk · 1 apple · 1 tbsp nuts",
              "¾ cup oats · 1 cup milk · 1 apple · 1½ tbsp nuts"],
 "dica": "Soaking the oats does not change the calories, but it makes the fiber easier to digest and the meal creamier and more filling. Since it is ready in the fridge, you will not skip breakfast in the morning rush — and skipping meals is what makes many people overeat later in the day.",
 "prompt": "Square ultra-realistic overhead food photograph of overnight oats in a glass jar topped with fresh diced apple and a dusting of cinnamon, a spoon resting beside it on a light wooden table, soft natural morning light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Avocado Toast with Egg",
 "hook": "Creamy, savory and truly filling — ready in 8 minutes.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["1 slice of whole-grain bread", "½ ripe avocado (or ¼ of a large avocado)", "1 egg",
          "juice of ½ lemon", "salt, pepper and chili flakes to taste", "oil spray"],
 "passos": [
   "Toast the slice of whole-grain bread until firm and golden.",
   "In a small bowl, mash the avocado with a fork, add the lemon juice, salt and pepper. Mix into a creamy spread.",
   "Heat a nonstick pan, spray with oil and fry the egg over medium heat, however you like it (fried with a runny yolk, or scrambled).",
   "Spread the avocado cream over the toast.",
   "Place the egg on top and finish with a pinch of chili flakes. Serve immediately."],
 "porcoes8": ["½ slice bread · ¼ avocado · 1 egg",
              "1 slice bread · ½ avocado · 1 egg",
              "1 slice bread · ½ avocado · 1 egg · greens",
              "1 slice bread · ½ avocado · 2 eggs",
              "1 slice bread · ½ avocado · 2 eggs · greens",
              "2 slices bread · ½ avocado · 2 eggs",
              "2 slices bread · 1 small avocado · 2 eggs",
              "2 slices bread · 1 small avocado · 3 eggs"],
 "dica": "Avocado has good fat, which keeps you full for a long time and makes the meal creamy without butter. With the egg and the whole-grain bread, you get good fat, protein and fiber on the same toast — the combination that holds hunger for hours.",
 "prompt": "Square ultra-realistic overhead food photograph of avocado toast on wholegrain bread topped with a fried egg with runny yolk, sprinkled with chili flakes and cracked pepper, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oatmeal Porridge with Banana and Peanut Butter",
 "hook": "Warm and comforting, the breakfast that tastes like dessert but works in your favor.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["½ cup rolled oats", "¾ cup milk (or plant milk)", "½ banana, mashed",
          "1 teaspoon peanut butter", "cinnamon to taste", "½ banana, sliced, to top"],
 "passos": [
   "In a small pot, combine the oats, the milk and the mashed banana.",
   "Cook over medium-low heat, stirring constantly with a spoon so it does not stick to the bottom.",
   "After 4 to 5 minutes, the mixture thickens and turns creamy. If you want it thinner, add a little more milk.",
   "Turn off the heat, add the cinnamon and stir.",
   "Pour into a bowl, top with the banana slices and the peanut butter. Serve warm."],
 "porcoes8": ["⅓ cup oats · ¾ cup milk · ½ banana · no peanut butter",
              "½ cup oats · ¾ cup milk · 1 banana · 1 tsp peanut butter",
              "½ cup oats · ¾ cup milk · 1 banana · 1 tsp peanut butter",
              "⅔ cup oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "⅔ cup oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "⅔ cup oats · 1 cup milk · 1 banana · 1 tbsp peanut butter",
              "¾ cup oats · 1 cup milk · 1 banana · 1½ tbsp peanut butter",
              "¾ cup oats · 1¼ cup milk · 1 banana · 2 tbsp peanut butter"],
 "dica": "Cooked oats form a gel in your stomach that slows hunger. The banana sweetens with no sugar and restores energy, and the peanut butter brings good fat and protein — just watch the amount, because it is calorie-dense: one spoon already does the job.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of creamy oatmeal porridge topped with banana slices and a swirl of peanut butter, dusted with cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Banana and Berry Smoothie Bowl",
 "hook": "Thick enough to eat with a spoon, cold and colorful — it looks like ice cream, but it works for your weight loss.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1 frozen banana, sliced", "1 handful of frozen berries",
          "3 tablespoons plain yogurt", "3 tablespoons milk (or plant milk)",
          "2 tablespoons oats and fresh fruit to top"],
 "passos": [
   "Use the banana already frozen (slice it the night before and freeze) — that is what makes the smoothie thick without ice.",
   "In the blender, combine the banana, the frozen berries, the yogurt and the milk.",
   "Blend on high, stopping to stir with a spoon when it gets stuck. Add milk just one spoon at a time, the minimum needed to blend. The texture should be thick, like ice cream.",
   "Pour into a bowl.",
   "Top with the oats and fresh fruit in neat rows. Eat right away, with a spoon, before it melts."],
 "porcoes8": ["1 banana · berries · 2 tbsp yogurt · 1 tbsp oats",
              "1 banana · berries · 3 tbsp yogurt · 2 tbsp oats",
              "1 banana · berries · 3 tbsp yogurt · 2 tbsp oats · seeds",
              "1 banana · berries · 4 tbsp yogurt · 3 tbsp oats",
              "1 banana · berries · 4 tbsp yogurt · 3 tbsp oats · 1 tbsp nuts",
              "1 large banana · berries · 5 tbsp yogurt · 3 tbsp oats · nuts",
              "1 large banana · berries · 5 tbsp yogurt · 4 tbsp oats · nuts",
              "2 bananas · berries · 6 tbsp yogurt · 4 tbsp oats · nuts"],
 "dica": "Freezing the fruit gives an ice-cream texture with no sugar and no cream. The yogurt adds protein, and eating it slowly with a spoon lets your brain register fullness — very different from drinking a blended juice through a straw in seconds.",
 "prompt": "Square ultra-realistic overhead food photograph of a thick berry-banana smoothie bowl topped with neat rows of fresh strawberries, blueberries and rolled oats, in a light ceramic bowl on a marble surface, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Boiled Eggs with Avocado and Tomato",
 "hook": "No pan, no mess — protein and good fat on a plate, put together in minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "½ avocado", "1 tomato", "juice of ½ lemon", "salt, pepper and olive oil to taste",
          "green leaves to taste"],
 "passos": [
   "Put the eggs in a pot, cover with cold water and set over heat. From the moment it boils, count 8 to 9 minutes for a firm yolk.",
   "Meanwhile, slice the avocado and tomato and arrange on the plate over some green leaves.",
   "Drain the eggs and run them under cold water for 1 minute — this makes them easier to peel.",
   "Peel the eggs, cut them in half and place on the plate.",
   "Drizzle everything with the lemon juice and a little olive oil, season with salt and pepper and serve."],
 "porcoes8": ["1 egg · ¼ avocado · tomato",
              "2 eggs · ½ avocado · tomato",
              "2 eggs · ½ avocado · tomato · ½ slice bread",
              "2 eggs · ½ avocado · tomato · 1 slice bread",
              "3 eggs · ½ avocado · tomato · 1 slice bread",
              "3 eggs · ½ avocado · tomato · 2 slices bread",
              "3 eggs · 1 small avocado · tomato · 2 slices bread",
              "4 eggs · 1 small avocado · tomato · 2 slices bread"],
 "dica": "A boiled egg is the most practical protein there is: you can cook several at once and keep them in the fridge. With avocado and tomato, you put together a full breakfast of good fat and fiber without turning on the stove in the morning.",
 "prompt": "Square ultra-realistic overhead food photograph of halved boiled eggs with sliced avocado and tomato on a bed of green leaves, drizzled with olive oil, on a white plate on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Protein Oat and Egg-White Pancakes",
 "hook": "The training-day pancake: more protein, same ease.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["½ cup rolled oats", "3 egg whites (or 2 whites + 1 egg)", "½ banana, mashed",
          "1 pinch of baking powder", "cinnamon to taste", "oil spray"],
 "passos": [
   "If you prefer a smoother batter, blend the oats until they become a flour. If you like it rustic, use them as flakes.",
   "In a bowl, mix the oats, the egg whites, the mashed banana, the baking powder and the cinnamon until well combined.",
   "Let it rest for 3 minutes so the oats hydrate.",
   "Heat the nonstick pan over medium-low heat and spray with oil.",
   "Make small pancakes. Cook 2 minutes per side, flipping when little bubbles appear.",
   "Serve with fresh fruit on top. Skip sugary syrups — the banana already sweetens."],
 "porcoes8": ["2 whites · ⅓ cup oats · ½ banana",
              "3 whites · ½ cup oats · ½ banana",
              "3 whites · ½ cup oats · ½ banana · fruit",
              "2 whites + 1 egg · ⅔ cup oats · 1 banana",
              "3 whites + 1 egg · ⅔ cup oats · 1 banana",
              "3 whites + 1 egg · ⅔ cup oats · 1 banana · fruit",
              "4 whites + 1 egg · ¾ cup oats · 1 banana · fruit",
              "4 whites + 2 eggs · ¾ cup oats · 1 banana · fruit"],
 "dica": "Swapping part of the eggs for whites raises the protein and lowers the fat — good for anyone chasing definition. Protein is also the most filling nutrient, so this pancake holds hunger with fewer calories than the traditional sweet version.",
 "prompt": "Square ultra-realistic overhead food photograph of a stack of protein oat pancakes topped with fresh strawberries and blueberries on a white plate, on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chia Pudding with Fruit",
 "hook": "You mix it in 2 minutes, the fridge does the rest, and you wake up to a healthy dessert.",
 "tempo": "5 min + fridge", "rende": "1 serving", "kcal_base": 280,
 "ings": ["3 tablespoons chia seeds", "¾ cup milk (or plant milk)",
          "½ teaspoon vanilla extract (optional)", "chopped fruit to top",
          "1 teaspoon honey (optional)"],
 "passos": [
   "In a jar with a lid, combine the chia, the milk and the vanilla. Stir well for 30 seconds.",
   "Wait 5 minutes and stir again — this second stir breaks up the lumps that form and is the secret to a smooth pudding.",
   "Close the jar and refrigerate for at least 4 hours, or overnight.",
   "The chia soaks up the liquid and sets into a pudding with a gel-like texture.",
   "Before serving, stir, top with chopped fruit and, if you like, the drizzle of honey."],
 "porcoes8": ["2 tbsp chia · ⅔ cup milk · fruit",
              "3 tbsp chia · ¾ cup milk · fruit",
              "3 tbsp chia · ¾ cup milk · fruit · 1 tsp honey",
              "3 tbsp chia · 1 cup milk · fruit · 1 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 1 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 2 tbsp granola",
              "4 tbsp chia · 1 cup milk · fruit · 2 tbsp granola · nuts",
              "5 tbsp chia · 1¼ cup milk · fruit · 2 tbsp granola · nuts"],
 "dica": "Chia soaks up many times its own weight in liquid and swells in your stomach, giving a lasting feeling of fullness. It is also rich in fiber and omega-3 — one of the most filling ingredients per calorie there is.",
 "prompt": "Square ultra-realistic overhead food photograph of chia pudding in a glass jar topped with fresh raspberries, blueberries and kiwi slices, a spoon beside it on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Egg Muffins with Vegetables",
 "hook": "You bake one batch and have breakfast ready all week — just reheat and eat.",
 "tempo": "25 min", "rende": "6 muffins (2 per serving)", "kcal_base": 220,
 "ings": ["6 eggs", "½ bell pepper, chopped", "1 handful of chopped spinach", "2 tablespoons grated cheese",
          "salt and pepper to taste", "a little oil (or spray) so the food does not stick"],
 "passos": [
   "Preheat the oven to 350°F and lightly oil (or spray) a muffin tin, so the eggs do not stick.",
   "Finely chop the bell pepper and spinach into small pieces.",
   "In a bowl, beat the eggs with salt and pepper. Add the vegetables and the cheese and mix.",
   "Divide the mixture between the 6 cups, filling each about 3/4 full.",
   "Bake for 18 to 20 minutes, until set and lightly golden. A toothpick in the center should come out clean.",
   "Let them cool a little before unmolding. Keep in the fridge for up to 4 days and reheat when you eat."],
 "porcoes8": ["1 muffin + green leaves",
              "2 muffins",
              "2 muffins · ½ slice bread",
              "2 muffins · 1 slice bread",
              "3 muffins · 1 slice bread",
              "3 muffins · 2 slices bread",
              "3 muffins · 2 slices bread · ¼ avocado",
              "4 muffins · 2 slices bread · ¼ avocado"],
 "dica": "Having food ready is what stops the wrong choice when morning hunger hits. These muffins are protein and vegetables in a controlled portion — you can freeze them and always have a filling breakfast on hand, without improvising with what you should not.",
 "prompt": "Square ultra-realistic overhead food photograph of baked egg muffins with bell pepper, spinach and cheese, arranged on a white plate on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Toast with Ricotta, Strawberry and Honey",
 "hook": "Sweet and creamy like a treat, but with protein and no heavy sugar.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["1 slice of whole-grain bread", "3 tablespoons ricotta", "4 strawberries, sliced",
          "1 teaspoon honey", "lemon zest and mint (optional)"],
 "passos": [
   "Toast the slice of bread until firm.",
   "In a bowl, mash the ricotta with a fork until creamy. If it is dry, add a splash of milk.",
   "Spread the ricotta over the toast, covering the whole surface.",
   "Arrange the strawberry slices on top.",
   "Finish with the drizzle of honey and, if you like, lemon zest and mint leaves. Serve right away."],
 "porcoes8": ["½ slice bread · 2 tbsp ricotta · strawberries",
              "1 slice bread · 3 tbsp ricotta · strawberries · 1 tsp honey",
              "1 slice bread · 3 tbsp ricotta · strawberries · honey",
              "1 slice bread · 4 tbsp ricotta · strawberries · honey · nuts",
              "1 slice bread · 4 tbsp ricotta · strawberries · 1 boiled egg",
              "2 slices bread · 4 tbsp ricotta · strawberries · honey",
              "2 slices bread · 5 tbsp ricotta · strawberries · nuts",
              "2 slices bread · 6 tbsp ricotta · strawberries · nuts · 1 egg"],
 "dica": "Ricotta is a lean, creamy, high-protein cheese — it kills the craving for something sweet without the calorie-heavy cream of store-bought fillings. The strawberry adds sweetness and freshness, and a teaspoon of honey sweetens just enough without turning breakfast into a sugar bomb.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of wholegrain toast spread with ricotta cheese, topped with fresh strawberry slices and a drizzle of honey, garnished with mint, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Warm Oatmeal with Cocoa and Banana",
 "hook": "A chocolate taste at breakfast, with no sugar and no guilt.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 350,
 "ings": ["½ cup rolled oats", "¾ cup milk (or plant milk)", "1 tablespoon 100% cocoa powder",
          "1 banana", "cinnamon to taste", "sweetener or 1 teaspoon honey (optional)"],
 "passos": [
   "In a small pot, mix the oats, the milk and the cocoa powder before turning on the heat — this way the cocoa dissolves without clumping.",
   "Cook over medium-low heat, stirring constantly.",
   "Mash half the banana and add it to the pot; keep the other half in slices.",
   "Cook for 4 to 5 minutes, until it thickens and turns creamy.",
   "Taste and adjust the sweetness with sweetener or a teaspoon of honey, if needed.",
   "Serve in a bowl with the banana slices and a pinch of cinnamon on top."],
 "porcoes8": ["⅓ cup oats · ¾ cup milk · 1 tbsp cocoa · ½ banana",
              "½ cup oats · ¾ cup milk · 1 tbsp cocoa · 1 banana",
              "½ cup oats · ¾ cup milk · 1 tbsp cocoa · 1 banana",
              "⅔ cup oats · 1 cup milk · 1 tbsp cocoa · 1 banana · nuts",
              "⅔ cup oats · 1 cup milk · cocoa · 1 banana · 1 tsp peanut butter",
              "⅔ cup oats · 1 cup milk · cocoa · 1 banana · 1 tbsp peanut butter",
              "¾ cup oats · 1 cup milk · cocoa · 1 banana · peanut butter",
              "¾ cup oats · 1¼ cup milk · cocoa · 1 banana · peanut butter"],
 "dica": "100% cocoa gives the chocolate flavor without the sugar of chocolate milk mixes — and it even has antioxidants. Killing the sweet craving right at breakfast prevents the raid on the chocolate bar later, which is where many diets fall apart.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of chocolate oatmeal made with cocoa, topped with banana slices and a dusting of cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mushroom and Spinach Omelette",
 "hook": "Earthy and tasty, it fills your plate with nutrients for very few calories.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 260,
 "ings": ["2 eggs", "1 handful of sliced mushrooms (button mushrooms)", "1 handful of spinach",
          "1 teaspoon olive oil", "salt, pepper and chopped garlic to taste"],
 "passos": [
   "Slice the mushrooms and wash the spinach.",
   "Heat the olive oil in a nonstick pan over medium-high heat. Fry the mushrooms in a little oil for 3 to 4 minutes, without stirring too much, until they brown and release their water.",
   "Add the garlic and the spinach and stir for 1 minute, just until it wilts (the leaves go soft). Season with salt and pepper.",
   "Beat the eggs in a bowl and pour over the vegetables. Lower the heat.",
   "Let the base set for 1 to 2 minutes, fold the omelette in half and serve."],
 "porcoes8": ["1 egg + 1 white · vegetables freely",
              "2 eggs · vegetables freely",
              "2 eggs · vegetables · ½ slice bread",
              "2 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 2 slices bread",
              "3 eggs · vegetables · 2 slices bread · cheese",
              "4 eggs · vegetables · 2 slices bread · cheese"],
 "dica": "Mushrooms and spinach add volume, flavor and nutrients for almost no calories — you fill your plate and your stomach. The eggs complete it with filling protein, making a hearty meal that still fits comfortably in your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded omelette with sautéed mushrooms and spinach on a white plate, garnished with fresh herbs, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Yogurt with Homemade Granola and Blueberries",
 "hook": "You make the granola sugar-free at home and use it all week — crunchy and done right.",
 "tempo": "5 min (+ granola ready)", "rende": "1 serving", "kcal_base": 330,
 "ings": ["¾ cup (6 oz) plain Greek yogurt", "3 tablespoons homemade sugar-free granola",
          "1 handful of blueberries", "cinnamon to taste",
          "(granola: oats + chopped nuts + cinnamon, baked at 325°F for 15 min)"],
 "passos": [
   "For the homemade granola: mix rolled oats with chopped nuts and cinnamon, spread on a baking sheet and bake at 325°F for 12 to 15 minutes, stirring halfway. Let it cool to get crunchy and keep in a jar.",
   "In a glass, add the yogurt.",
   "Top with the homemade granola.",
   "Scatter the blueberries on top and finish with a pinch of cinnamon.",
   "Serve right away, so the granola does not go soft."],
 "porcoes8": ["½ cup yogurt · 2 tbsp granola · blueberries",
              "¾ cup yogurt · 3 tbsp granola · blueberries",
              "¾ cup yogurt · 3 tbsp granola · blueberries",
              "1 cup yogurt · 4 tbsp granola · blueberries",
              "1 cup yogurt · 4 tbsp granola · blueberries",
              "1¼ cup yogurt · 4 tbsp granola · blueberries",
              "1¼ cup yogurt · 5 tbsp granola · blueberries",
              "1½ cup yogurt · 6 tbsp granola · blueberries"],
 "dica": "Store-bought granola is usually full of sugar and oil — making it at home cuts that and you control what goes in. With high-protein Greek yogurt and blueberries, it becomes a crunchy, filling breakfast without the hidden sugars of the packaged versions.",
 "prompt": "Square ultra-realistic overhead food photograph of a bowl of Greek yogurt topped with homemade golden granola and fresh blueberries, on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Grain Wrap with Scrambled Eggs and Vegetables",
 "hook": "Roll it and go — breakfast for anyone rushing out, who still will not give up eating well.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["1 whole-grain tortilla/wrap", "2 eggs", "½ tomato, chopped", "1 handful of spinach",
          "1 tablespoon grated cheese", "salt, pepper and oil spray"],
 "passos": [
   "Chop the tomato and set aside. Wash the spinach.",
   "Beat the eggs with salt and pepper. Heat the pan with oil spray over medium heat.",
   "Add the spinach and tomato for 1 minute, then pour in the eggs and stir until you get creamy scrambled eggs.",
   "Warm the tortilla for 20 seconds per side in a dry pan, just to soften it.",
   "Place the eggs in the center of the tortilla, sprinkle the cheese and fold the sides in.",
   "Roll it up tight like a burrito and cut in half. You can eat it in your hand, on the go."],
 "porcoes8": ["1 wrap · 1 egg + 1 white · vegetables",
              "1 wrap · 2 eggs · vegetables · cheese",
              "1 wrap · 2 eggs · vegetables · cheese",
              "1 wrap · 2 eggs · vegetables · ¼ avocado",
              "1 wrap · 3 eggs · vegetables · cheese",
              "1 large wrap · 3 eggs · vegetables · cheese · ¼ avocado",
              "1 large wrap · 3 eggs · vegetables · cheese · ½ avocado",
              "1 large wrap · 4 eggs · vegetables · cheese · ½ avocado"],
 "dica": "Being able to eat breakfast in your hand is what keeps you from skipping the meal on a busy day. Filled with egg and vegetables, this wrap gives protein and fiber in a practical form — much better than fixing your hunger with a sweet pastry at a bakery.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain wrap filled with scrambled eggs, spinach and tomato, cut in half to show the filling, on a light wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Apple and Cinnamon Pancakes",
 "hook": "It smells like apple pie and fits your diet — the comfort of a sweet breakfast without sabotaging your day.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["½ cup rolled oats", "1 egg", "½ apple, grated", "cinnamon to taste",
          "1 pinch of baking powder", "oil spray", "½ apple, thinly sliced, to top"],
 "passos": [
   "Grate half the apple on the coarse grater and keep the other half in slices.",
   "In a bowl, mix the oats, the egg, the grated apple, the cinnamon and the baking powder until well combined.",
   "Let it rest for 3 minutes so the oats hydrate.",
   "Heat the nonstick pan over medium-low heat and spray with oil.",
   "Make small pancakes, cooking 2 to 3 minutes per side.",
   "Meanwhile, brown the apple slices in the same pan with a pinch of cinnamon. Serve on top of the pancakes."],
 "porcoes8": ["⅓ cup oats · 1 egg · ½ apple",
              "½ cup oats · 1 egg · ½ apple",
              "½ cup oats · 1 egg · ½ apple · nuts",
              "⅔ cup oats · 1 egg · 1 apple · nuts",
              "⅔ cup oats · 2 eggs · 1 apple",
              "⅔ cup oats · 2 eggs · 1 apple · nuts",
              "¾ cup oats · 2 eggs · 1 apple · nuts",
              "¾ cup oats · 2 eggs · 1 apple · 1 tbsp peanut butter"],
 "dica": "The apple brings sweetness and fiber, and the cinnamon boosts the flavor without a pinch of sugar — studies suggest it may even help control appetite. It is the version that kills the craving for sweet pie without the refined carbs that put on weight.",
 "prompt": "Square ultra-realistic overhead food photograph of apple-cinnamon oat pancakes topped with caramelized apple slices and a dusting of cinnamon, on a white plate on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Grain Toast with Peanut Butter and Banana",
 "hook": "The 5-minute classic that combines energy, good fat and natural sweetness.",
 "tempo": "5 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["1 slice of whole-grain bread", "1 tablespoon peanut butter", "1 banana, sliced",
          "cinnamon to taste", "1 pinch of chia seeds (optional)"],
 "passos": [
   "Toast the slice of bread until firm.",
   "Spread the peanut butter over the still-warm toast — it melts a little and is easier to spread.",
   "Top with the banana slices.",
   "Sprinkle cinnamon and, if you like, the chia seeds on top.",
   "Serve immediately. To take it with you, cut in half and put it together like a sandwich."],
 "porcoes8": ["½ slice bread · 1 tsp peanut butter · ½ banana",
              "1 slice bread · 1 tbsp peanut butter · 1 banana",
              "1 slice bread · 1 tbsp peanut butter · 1 banana · chia",
              "1 slice bread · 1½ tbsp peanut butter · 1 banana",
              "1 slice bread · 1½ tbsp peanut butter · 1 banana · 1 boiled egg",
              "2 slices bread · 2 tbsp peanut butter · 1 banana",
              "2 slices bread · 2 tbsp peanut butter · 1 banana · 1 egg",
              "2 slices bread · 2½ tbsp peanut butter · 1 banana · 1 egg"],
 "dica": "Peanut butter has good fat and protein that give lasting fullness — but it is calorie-dense, so the amount matters: one tablespoon is enough. Over whole-grain bread and banana, you get steady energy for the whole morning, without the spike and crash of sugar.",
 "prompt": "Square ultra-realistic overhead food photograph of wholegrain toast spread with peanut butter, topped with banana slices, chia seeds and a dusting of cinnamon, on a light wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Poached Eggs with Asparagus and Toast",
 "hook": "Elegant like a restaurant breakfast, simple enough for an ordinary day.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "1 handful of asparagus", "1 slice of whole-grain bread",
          "1 teaspoon vinegar (for the water)", "salt, pepper and olive oil to taste"],
 "passos": [
   "Wash the asparagus and trim the tough base. Cook in boiling salted water for 3 minutes, drain and set aside.",
   "In a pot, heat water until almost boiling (small bubbles, not a rolling boil) and add the vinegar.",
   "Crack each egg into a cup. Make a whirlpool in the water with a spoon and slide the egg in very slowly at the center — the motion wraps the white around the yolk.",
   "Cook for 3 minutes for a soft yolk. Remove with a slotted spoon and rest on paper towel.",
   "Toast the bread. Assemble with the asparagus underneath, the poached eggs on top, a drizzle of olive oil, salt and pepper."],
 "porcoes8": ["1 egg · asparagus · ½ slice bread",
              "2 eggs · asparagus · 1 slice bread",
              "2 eggs · asparagus · 1 slice bread · cheese",
              "2 eggs · asparagus · 1 slice bread · ¼ avocado",
              "3 eggs · asparagus · 1 slice bread",
              "3 eggs · asparagus · 2 slices bread",
              "3 eggs · asparagus · 2 slices bread · ¼ avocado",
              "4 eggs · asparagus · 2 slices bread · ¼ avocado"],
 "dica": "A poached egg is cooked in water alone, with no oil, which keeps the calories low. Asparagus is rich in fiber and water and has almost no calories — a breakfast that looks fancy and still works in your favor on the scale.",
 "prompt": "Square ultra-realistic overhead food photograph of two poached eggs with runny yolks on a slice of wholegrain toast, with green asparagus spears alongside, drizzled with olive oil and cracked pepper, on a white plate, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oatmeal with Pear and Walnuts",
 "hook": "Creamy, lightly sweetened by the pear and with the crunch of walnuts.",
 "tempo": "8 min", "rende": "1 serving", "kcal_base": 350,
 "ings": ["½ cup rolled oats", "¾ cup milk (or plant milk)", "½ pear, chopped",
          "3 walnuts, chopped", "cinnamon to taste", "1 teaspoon honey (optional)"],
 "passos": [
   "In a small pot, combine the oats and the milk and set over medium-low heat, stirring.",
   "After 3 minutes, add half the chopped pear and cook 2 more minutes, until it thickens.",
   "Turn off the heat and add the cinnamon.",
   "Serve in a bowl and top with the rest of the fresh pear and the chopped walnuts.",
   "If needed, sweeten with a teaspoon of honey."],
 "porcoes8": ["⅓ cup oats · ¾ cup milk · ½ pear · 2 walnuts",
              "½ cup oats · ¾ cup milk · ½ pear · 3 walnuts",
              "½ cup oats · ¾ cup milk · ½ pear · 3 walnuts",
              "⅔ cup oats · 1 cup milk · 1 pear · 3 walnuts",
              "⅔ cup oats · 1 cup milk · 1 pear · 4 walnuts",
              "⅔ cup oats · 1 cup milk · 1 pear · 4 walnuts",
              "¾ cup oats · 1 cup milk · 1 pear · 5 walnuts",
              "¾ cup oats · 1¼ cup milk · 1 pear · 5 walnuts"],
 "dica": "The pear is rich in fiber and sweetens naturally, so you do not need sugar. Walnuts have good fat that gives fullness and crunch — but they are calorie-dense, so a few pieces already do the job without blowing the calories of breakfast.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of creamy oatmeal topped with fresh pear slices and chopped walnuts, dusted with cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Greek Yogurt with Peach and Almonds",
 "hook": "Creamy and sweet from the peach, with the crunch of almonds — ready in 3 minutes.",
 "tempo": "3 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["¾ cup (6 oz) plain Greek yogurt", "1 peach, sliced (or ½ can with no syrup)",
          "1 tablespoon sliced almonds", "cinnamon to taste", "1 teaspoon honey (optional)"],
 "passos": [
   "If the peach is fresh, wash and cut into thin slices. If canned, choose one with no sugary syrup and drain it well.",
   "Put the yogurt in a glass.",
   "Arrange the peach slices on top.",
   "Sprinkle the sliced almonds and the cinnamon.",
   "If you need more sweetness, add a teaspoon of honey. Serve right away."],
 "porcoes8": ["½ cup yogurt · peach · ½ tbsp almonds",
              "¾ cup yogurt · peach · 1 tbsp almonds",
              "¾ cup yogurt · peach · 1 tbsp almonds · honey",
              "1 cup yogurt · peach · 1 tbsp almonds · 2 tbsp oats",
              "1 cup yogurt · peach · 1½ tbsp almonds · 2 tbsp oats",
              "1¼ cup yogurt · peach · 1½ tbsp almonds · 3 tbsp oats",
              "1¼ cup yogurt · peach · 2 tbsp almonds · 3 tbsp oats",
              "1½ cup yogurt · peach · 2 tbsp almonds · 4 tbsp oats"],
 "dica": "The peach is sweet and low in calories, satisfying the sugar craving in a light way. With high-protein Greek yogurt and a handful of almonds, you combine protein and good fat for a fullness that carries you through the morning.",
 "prompt": "Square ultra-realistic overhead food photograph of Greek yogurt topped with fresh peach slices and toasted flaked almonds, dusted with cinnamon, in a light ceramic bowl on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Grain Turkey and Cheese Sandwich",
 "hook": "Savory, practical and high in protein — the quick breakfast for anyone who does not like sweet in the morning.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["2 slices of whole-grain bread", "2 slices of turkey breast", "1 slice of white cheese",
          "lettuce leaves", "tomato slices", "1 teaspoon mustard or light cream cheese"],
 "passos": [
   "If you like it warm, heat the bread slices in a dry pan for 1 minute per side.",
   "Spread the mustard or light cream cheese on one slice of bread.",
   "Build the layers: turkey, cheese, tomato and lettuce.",
   "Close with the other slice of bread and press lightly.",
   "Cut diagonally and serve. To take it with you, wrap it in parchment paper."],
 "porcoes8": ["1 slice bread (open) · 1 turkey · cheese",
              "2 slices bread · 2 turkey · cheese",
              "2 slices bread · 2 turkey · cheese",
              "2 slices bread · 3 turkey · cheese · ¼ avocado",
              "2 slices bread · 3 turkey · cheese · 1 boiled egg",
              "2 slices bread · 4 turkey · cheese · 1 egg",
              "3 slices bread · 4 turkey · cheese · 1 egg",
              "3 slices bread · 5 turkey · 2 cheese · 1 egg"],
 "dica": "Turkey breast is one of the leanest meats there is, almost pure protein, without the fat of cold cuts like salami and bologna. On whole-grain bread with salad, it is a savory breakfast that holds you with few calories and no sugar.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain turkey and cheese sandwich with lettuce and tomato, cut diagonally to show the filling, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vegetable Omelette",
 "hook": "Colorful and full of flavor, it uses whatever you have in the fridge and fills your plate.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 260,
 "ings": ["2 eggs", "¼ bell pepper, chopped", "¼ onion, chopped", "½ tomato, chopped",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Chop the bell pepper, onion and tomato into small cubes.",
   "Heat the olive oil in a nonstick pan over medium heat. Fry the onion and bell pepper in a little oil, stirring, for 2 to 3 minutes, until soft.",
   "Add the tomato and fry 1 more minute. Season with salt and pepper.",
   "Beat the eggs and pour over the vegetables. Tilt the pan to spread them.",
   "When the base sets (2 minutes), fold the omelette in half, cook 1 more minute and serve with fresh herbs."],
 "porcoes8": ["1 egg + 1 white · vegetables freely",
              "2 eggs · vegetables freely",
              "2 eggs · vegetables · ½ slice bread",
              "2 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 2 slices bread",
              "3 eggs · vegetables · 2 slices bread · cheese",
              "4 eggs · vegetables · 2 slices bread · cheese"],
 "dica": "Filling the omelette with vegetables raises the volume and fiber for very few calories, so you eat a hearty plate with no guilt. It is also a smart way to eat more vegetables first thing in the morning, which helps you hit your fiber goal for the day.",
 "prompt": "Square ultra-realistic overhead food photograph of a colorful vegetable omelette with bell pepper, onion and tomato, folded on a white plate, garnished with fresh parsley, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Green Smoothie with Spinach, Banana and Apple",
 "hook": "Green, cold and sweet — you do not even taste the spinach, but your body thanks you.",
 "tempo": "5 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["1 large handful of spinach", "½ banana", "½ apple", "¾ cup cold water (or plant milk)",
          "1 tablespoon oats", "juice of ½ lemon", "ice to taste"],
 "passos": [
   "Wash the spinach well.",
   "In the blender, put the liquid first, then the spinach — blending the leaves with the liquid first prevents chunks.",
   "Blend for 30 seconds, until the spinach breaks down.",
   "Add the banana, the apple (seeds removed), the oats, the lemon juice and the ice.",
   "Blend on high until smooth and well combined. Serve right away, nice and cold."],
 "porcoes8": ["spinach · ½ banana · ½ apple · 1 tbsp oats",
              "spinach · ½ banana · ½ apple · 1 tbsp oats",
              "spinach · 1 banana · ½ apple · 2 tbsp oats",
              "spinach · 1 banana · ½ apple · 2 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 2 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 3 tbsp oats · yogurt",
              "spinach · 1 banana · 1 apple · 3 tbsp oats · yogurt · nuts",
              "spinach · 1 banana · 1 apple · 4 tbsp oats · yogurt · nuts"],
 "dica": "Blending spinach with fruit is a painless way to eat leaves in the morning — the sweet taste of banana and apple hides the green. It is light in calories and rich in water and fiber, great for starting the day hydrated and full.",
 "prompt": "Square ultra-realistic photograph of a tall glass of green spinach-banana-apple smoothie on a light wooden table, with fresh spinach leaves and half an apple beside it, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Scrambled Eggs with Mushrooms and Cheese",
 "hook": "Creamy and comforting, the savory breakfast that holds you with the taste of real food.",
 "tempo": "9 min", "rende": "1 serving", "kcal_base": 300,
 "ings": ["2 eggs", "1 handful of sliced mushrooms", "1 tablespoon grated cheese",
          "1 teaspoon olive oil", "salt, pepper and chives to taste"],
 "passos": [
   "Slice the mushrooms. Heat the olive oil in a pan over medium-high heat and brown the mushrooms for 3 to 4 minutes.",
   "Beat the eggs with salt and pepper.",
   "Lower the heat, pour the eggs over the mushrooms and leave 30 seconds without stirring.",
   "Gently push from the bottom to the center with the spatula, forming creamy eggs.",
   "Before they finish cooking, add the grated cheese and stir. Turn off with the eggs still moist and finish with chives."],
 "porcoes8": ["1 egg + 1 white · mushrooms · cheese",
              "2 eggs · mushrooms · cheese",
              "2 eggs · mushrooms · cheese · ½ slice bread",
              "2 eggs · mushrooms · cheese · 1 slice bread",
              "3 eggs · mushrooms · cheese · 1 slice bread",
              "3 eggs · mushrooms · cheese · 2 slices bread",
              "3 eggs · mushrooms · 2 tbsp cheese · 2 slices bread",
              "4 eggs · mushrooms · 2 tbsp cheese · 2 slices bread"],
 "dica": "Mushrooms bring an umami flavor that makes the meal feel richer without extra fat. With eggs and a touch of cheese, it is a creamy, high-protein breakfast — far more filling than bread and butter in a rush.",
 "prompt": "Square ultra-realistic overhead food photograph of creamy scrambled eggs with sautéed mushrooms and melted cheese on a white plate, sprinkled with chives, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oat Pancakes with Blueberries",
 "hook": "The blueberries burst warm in the batter — natural sweetness, no added sugar.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 320,
 "ings": ["½ cup rolled oats", "1 egg", "½ banana, mashed", "1 handful of blueberries",
          "1 pinch of baking powder", "cinnamon to taste", "oil spray"],
 "passos": [
   "In a bowl, mix the oats, the egg, the mashed banana, the baking powder and the cinnamon.",
   "Let it rest for 3 minutes so the batter firms up.",
   "Fold half the blueberries into the batter, gently, so they do not get crushed.",
   "Heat the nonstick pan over medium-low heat, spray with oil and make small pancakes.",
   "Cook 2 to 3 minutes per side, flipping when little bubbles appear.",
   "Serve with the rest of the fresh blueberries on top."],
 "porcoes8": ["⅓ cup oats · 1 egg · ½ banana · blueberries",
              "½ cup oats · 1 egg · ½ banana · blueberries",
              "½ cup oats · 1 egg · ½ banana · blueberries",
              "⅔ cup oats · 1 egg · 1 banana · blueberries",
              "⅔ cup oats · 2 eggs · 1 banana · blueberries",
              "⅔ cup oats · 2 eggs · 1 banana · blueberries · nuts",
              "¾ cup oats · 2 eggs · 1 banana · blueberries · nuts",
              "¾ cup oats · 2 eggs · 1 banana · blueberries · 1 tbsp peanut butter"],
 "dica": "Blueberries are rich in antioxidants and low in calories, sweetening the pancake naturally. Since the base is oats, egg and banana — with no white flour or sugar — you get a breakfast that satisfies the sweet craving without the ingredients that put on weight.",
 "prompt": "Square ultra-realistic overhead food photograph of a stack of oat pancakes studded with blueberries, topped with fresh blueberries and a dusting of cinnamon, on a white plate on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Yogurt with Chia, Honey and Kiwi",
 "hook": "Refreshing and full of fiber, the breakfast that gets your gut moving and fills you up at the same time.",
 "tempo": "4 min", "rende": "1 serving", "kcal_base": 290,
 "ings": ["¾ cup (6 oz) plain Greek yogurt", "1 tablespoon chia seeds", "1 kiwi, sliced",
          "1 teaspoon honey", "mint (optional)"],
 "passos": [
   "In a glass, mix the yogurt with the chia and let it rest 5 minutes — the chia swells slightly and thickens the yogurt.",
   "Peel the kiwi and cut into slices.",
   "Arrange the kiwi slices over the yogurt.",
   "Finish with the drizzle of honey and, if you like, mint leaves.",
   "Serve chilled."],
 "porcoes8": ["½ cup yogurt · 1 tbsp chia · kiwi",
              "¾ cup yogurt · 1 tbsp chia · kiwi · honey",
              "¾ cup yogurt · 1 tbsp chia · kiwi · honey",
              "1 cup yogurt · 1 tbsp chia · kiwi · 2 tbsp oats",
              "1 cup yogurt · 1½ tbsp chia · kiwi · 2 tbsp oats",
              "1¼ cup yogurt · 1½ tbsp chia · kiwi · 3 tbsp oats",
              "1¼ cup yogurt · 2 tbsp chia · kiwi · 3 tbsp oats · nuts",
              "1½ cup yogurt · 2 tbsp chia · kiwi · 4 tbsp oats · nuts"],
 "dica": "Chia and kiwi together are rich in fiber, which helps your gut work and prolongs fullness. Greek yogurt brings protein, and a teaspoon of honey sweetens without overdoing it — a light breakfast that also takes care of digestion.",
 "prompt": "Square ultra-realistic overhead food photograph of Greek yogurt with chia seeds topped with fresh kiwi slices and a drizzle of honey, garnished with mint, in a glass bowl on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Grain Toast with Cottage Cheese and Tomato",
 "hook": "Fresh and savory, with protein in the cheese and almost no calories in the tomato.",
 "tempo": "6 min", "rende": "1 serving", "kcal_base": 250,
 "ings": ["1 slice of whole-grain bread", "3 tablespoons cottage cheese", "1 tomato, sliced",
          "oregano, salt, pepper and olive oil to taste", "basil leaves (optional)"],
 "passos": [
   "Toast the slice of bread until firm and crisp.",
   "Spread the cottage cheese over the toast, covering the whole surface.",
   "Place the tomato slices on top.",
   "Season with a pinch of salt, pepper, oregano and a drizzle of olive oil.",
   "Finish with basil leaves, if you have them. Serve right away."],
 "porcoes8": ["½ slice bread · 2 tbsp cottage · tomato",
              "1 slice bread · 3 tbsp cottage · tomato",
              "1 slice bread · 3 tbsp cottage · tomato · 1 boiled egg",
              "1 slice bread · 4 tbsp cottage · tomato · 1 egg",
              "1 slice bread · 4 tbsp cottage · tomato · 2 eggs",
              "2 slices bread · 4 tbsp cottage · tomato · 1 egg",
              "2 slices bread · 5 tbsp cottage · tomato · 2 eggs",
              "2 slices bread · 6 tbsp cottage · tomato · 2 eggs"],
 "dica": "Cottage cheese is lean and high in protein, killing hunger with few calories. On whole-grain bread with tomato, it becomes a healthy bruschetta — savory, fresh and much lighter than bread with greasy cream cheese.",
 "prompt": "Square ultra-realistic overhead food photograph of wholegrain toast topped with cottage cheese and fresh tomato slices, sprinkled with oregano and basil leaves, drizzled with olive oil, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oatmeal Bowl with Baked Apple and Cinnamon",
 "hook": "The smell of baked apple with cinnamon turns plain oatmeal into a cold-day comfort.",
 "tempo": "15 min", "rende": "1 serving", "kcal_base": 340,
 "ings": ["½ cup rolled oats", "¾ cup milk (or plant milk)", "1 apple, cubed",
          "cinnamon stick or ground cinnamon", "1 teaspoon honey (optional)", "1 tablespoon walnuts (optional)"],
 "passos": [
   "Cut the apple into cubes, with the skin. In a nonstick pan, brown the cubes over medium heat with plenty of cinnamon for 5 to 7 minutes, stirring, until they caramelize (soft and golden in the fruit's own sugar).",
   "Meanwhile, cook the oats with the milk in a pot, stirring, for 4 to 5 minutes, until it thickens.",
   "Pour the oatmeal into a bowl.",
   "Top with the warm baked apple.",
   "If you like, finish with the drizzle of honey and the chopped walnuts. Serve warm."],
 "porcoes8": ["⅓ cup oats · ¾ cup milk · ½ apple",
              "½ cup oats · ¾ cup milk · 1 apple",
              "½ cup oats · ¾ cup milk · 1 apple · honey",
              "⅔ cup oats · 1 cup milk · 1 apple · walnuts",
              "⅔ cup oats · 1 cup milk · 1 apple · walnuts",
              "⅔ cup oats · 1 cup milk · 1 apple · walnuts",
              "¾ cup oats · 1 cup milk · 1 apple · walnuts",
              "¾ cup oats · 1¼ cup milk · 1 apple · walnuts · honey"],
 "dica": "Baking the apple releases its natural sweetness and brings out the cinnamon, so you do not need sugar. It is a breakfast that comforts like a warm dessert, but with fiber from the fruit and oats that hold hunger for hours.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of oatmeal topped with caramelized baked apple cubes, chopped walnuts and a cinnamon stick, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
