# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). INGLÊS (mercado US). Todas FIT e SEM AÇÚCAR.

Tradução literal de `receitas_sobremesa.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "you", medidas caseiras americanas, chocolate e iogurte em OZ,
forno em °F.
⛔ `Brigadeiro` e `pudim` não existem no repertório do leitor americano: viram
descrição do que a coisa É (fudge balls, milk flan), nunca o nome brasileiro
transliterado — nome que o leitor não reconhece é receita que ele não faz.
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/101-120).
porcoes8 na ordem: Mulher 120-155/156-185/186-220/220+ lb · Homem 155-185/186-220/221-265/265+ lb
Metas (kcal): 120/150/170/190 · 180/200/230/260 (porções pequenas de sobremesa)
"""

RECEITAS = [
{
 "nome": "Fit Sugar-Free Chocolate Cake",
 "hook": "Fluffy, moist and really chocolatey — the cake that kills the craving for sweets without a pinch of sugar, made with real cocoa.",
 "tempo": "40 min", "rende": "8 slices", "kcal_base": 150,
 "ings": ["3 eggs", "1 very ripe banana, mashed", "4 tbsp 100% cocoa powder (with no sugar)",
          "5 tbsp oats blended into flour (or wholewheat flour)",
          "baking sweetener to taste (the kind made for the oven) — or 2 tbsp honey",
          "1/2 cup milk (or plant drink)", "1 tbsp oil", "1 tsp baking powder"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Spread a little oil in a small pan and dust it with some cocoa, so the cake does not stick.",
   "In a bowl, beat the eggs with the sweetener (or the honey) using a fork or a whisk, for 1 minute, until it is foamy.",
   "Add the mashed banana, the milk and the oil and mix well.",
   "Add the cocoa powder and the blended oats (or the flour) and stir until it is a smooth batter, with no dry spots.",
   "Last, add the baking powder and mix lightly, just to bring it together (stirring too much after the baking powder makes the cake heavy).",
   "Pour it into the pan and bake for 30 minutes. To know if it is done, stick a toothpick in the center: if it comes out clean, the cake is baked.",
   "Let it cool a little before taking it out and cutting it. It is great with berries on top."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice · berries",
              "1 slice · 1 tbsp yogurt",
              "1 slice",
              "1 medium slice",
              "1 slice · berries",
              "1 large slice · berries"],
 "dica": "Pure cocoa gives you all the chocolate flavor without the sugar and the fat of drinking chocolate. The banana sweetens naturally and keeps the cake moist, the oats bring fiber and the eggs bring protein. It is proof that you can eat chocolate cake and keep losing weight, as long as the slice is the right size.",
},
{
 "nome": "Chocolate Avocado Mousse",
 "hook": "As creamy as the traditional mousse, but the secret is avocado — nobody guesses, and it has no cream and no sugar.",
 "tempo": "10 min + fridge", "rende": "2 glasses", "kcal_base": 170,
 "ings": ["1 ripe avocado (or 1/2 large avocado)", "3 tbsp 100% cocoa powder",
          "baking sweetener to taste — or 2 tbsp honey", "3 tbsp milk (or plant drink)",
          "1 pinch of cinnamon", "1 pinch of salt", "70% chocolate shavings to decorate (optional)"],
 "passos": [
   "Cut the avocado in half, take out the pit and scoop out the flesh with a spoon. Use only the very soft, green part.",
   "Put the avocado flesh in the blender or the hand blender cup, together with the cocoa, the sweetener (or honey), the milk, the cinnamon and the salt.",
   "Blend at top speed until it turns into a smooth, glossy cream, with no lumps. If it is too thick, add a little more milk.",
   "Taste it and adjust the sweetness to your liking.",
   "Divide it between two glasses and put it in the fridge for at least 30 minutes, to set and chill. Serve with chocolate shavings on top."],
 "porcoes8": ["1/2 small glass",
              "1 small glass",
              "1 glass",
              "1 glass · chocolate shavings",
              "1 glass",
              "1 medium glass",
              "1 glass · chocolate shavings",
              "1 large glass · shavings"],
 "dica": "Avocado gives the creaminess of the mousse with good fat instead of cream, and it is very filling. Pure cocoa brings the chocolate flavor with no sugar. It is a rich and satisfying dessert that, in a small portion, fits easily into your diet.",
},
{
 "nome": "Fit Cocoa Fudge Balls",
 "hook": "The party sweet in a version with no sugar and no condensed milk — rolled, chocolatey and just the right size for the craving.",
 "tempo": "20 min + fridge", "rende": "10 balls", "kcal_base": 130,
 "ings": ["6 pitted dates (that very sweet dried fruit)", "3 tbsp 100% cocoa powder",
          "2 tbsp milk (or plant drink)", "1 tbsp peanut butter",
          "extra cocoa powder for rolling", "1 pinch of salt"],
 "passos": [
   "Soak the dates in warm water for 10 minutes, so they soften. Drain them.",
   "In the hand blender cup or the blender, blend the dates with the cocoa, the milk, the peanut butter and the salt, until it turns into a thick, even dough (well mixed). If you need to, stop and push the dough to the middle with a spoon.",
   "The dough should be firm enough to roll. If it is soft, put it in the fridge for 20 minutes.",
   "With lightly damp hands, take small portions and roll balls the size of a walnut.",
   "Roll each ball in the cocoa powder to coat it. Keep them in the fridge and serve them cold."],
 "porcoes8": ["1 ball",
              "1 to 2 balls",
              "2 balls",
              "2 balls",
              "2 balls",
              "2 to 3 balls",
              "3 balls",
              "3 balls"],
 "dica": "Dates replace the sugar and the condensed milk with natural sweetness and plenty of fiber, which holds the craving for sweets back. Pure cocoa gives the chocolate flavor and the peanut butter the creaminess. One or two little balls kill the craving without blowing your calories.",
},
{
 "nome": "Chocolate Mug Cake",
 "hook": "Craving something sweet at night? In three minutes, in the microwave, you have a warm little chocolate cake just for you.",
 "tempo": "5 min", "rende": "1 mug", "kcal_base": 190,
 "ings": ["1 egg", "2 tbsp oats blended into flour", "1 tbsp 100% cocoa powder",
          "baking sweetener to taste — or 1 tbsp honey", "2 tbsp milk",
          "1/2 tsp baking powder", "1 pinch of salt"],
 "passos": [
   "In a large mug (microwave safe), crack the egg and beat it with a fork.",
   "Add the blended oats, the cocoa, the sweetener (or honey), the milk and the salt. Mix well, until it is a smooth batter, with no dry spots at the edges.",
   "Last, add the baking powder and stir lightly.",
   "Put the mug in the microwave on high (full power) for 1 minute 30 seconds to 2 minutes. The cake rises and sets; if it is still wet in the center, give it another 20 seconds.",
   "Be careful, the mug comes out hot. Let it cool for 1 minute and eat it straight from the mug. It is great with fruit on top."],
 "porcoes8": ["1/2 mug",
              "1 small mug",
              "1 mug",
              "1 mug · fruit",
              "1 mug",
              "1 mug",
              "1 mug · fruit",
              "1 mug · fruit · 1 tbsp peanut butter"],
 "dica": "Made on the spot and in a single mug portion, this little cake naturally controls how much you eat — there is no whole cake left tempting you on the table. With oats, egg and pure cocoa, it is sweet, warm and comforting with no sugar, ideal for a nighttime craving.",
},
{
 "nome": "Strawberry Yogurt Mousse",
 "hook": "Pink, velvety and refreshing — a strawberry mousse that takes only three ingredients and no sugar at all.",
 "tempo": "10 min + fridge", "rende": "3 glasses", "kcal_base": 120,
 "ings": ["2 cups of strawberries (fresh or frozen)", "1 cup of plain yogurt with no sugar (about 6 oz)",
          "1 tbsp unflavored gelatin", "sweetener to taste — or 1 tbsp honey",
          "3 tbsp hot water", "chopped strawberries to decorate"],
 "passos": [
   "Wash the strawberries and take off the green leaves. Keep a few to decorate.",
   "In a cup, dissolve the unflavored gelatin in the hot water, stirring well until it is clear, with no little grains. Let it cool a little.",
   "In the blender, blend the strawberries with the yogurt and the sweetener (or honey) until it turns into a smooth, pink cream.",
   "With the blender running on low speed, add the dissolved gelatin and blend for another 30 seconds, just to mix it in.",
   "Divide it between glasses and put it in the fridge for at least 2 hours, until it sets. Serve with chopped strawberries on top."],
 "porcoes8": ["1/2 glass",
              "1 small glass",
              "1 glass",
              "1 glass · strawberries",
              "1 glass",
              "1 medium glass",
              "1 glass · strawberries",
              "1 large glass · strawberries"],
 "dica": "Strawberries are sweet and full of vitamin C with very few calories, and plain yogurt adds protein and creaminess with no sugar. The gelatin gives the mousse texture with no cream. A light, pretty and refreshing dessert that satisfies the craving for something sweet.",
},
{
 "nome": "Creamy Banana Nice Cream",
 "hook": "A real ice cream, creamy and cold, made only from bananas — no sugar, no milk, no ice cream machine.",
 "tempo": "5 min + freezer", "rende": "2 servings", "kcal_base": 120,
 "ings": ["3 ripe bananas", "1 tbsp 100% cocoa powder OR 1 handful of berries (optional, for flavor)",
          "1 pinch of cinnamon", "1 tsp peanut butter (optional)"],
 "passos": [
   "Peel the bananas, cut them into rounds and put them in a bag or a container. Freeze them for at least 3 hours, until they are really hard.",
   "Take the frozen rounds out and put them in a powerful blender or the hand blender cup.",
   "Blend at top speed. At first it turns into little pieces; keep blending (stopping to push the banana to the middle) until it turns into a smooth cream, just like machine-made ice cream.",
   "If you want flavor, add the cocoa or the berries and blend a little more.",
   "Serve right away, nice and creamy, with a pinch of cinnamon — or put it in the freezer for 1 hour to make it firmer, like tub ice cream."],
 "porcoes8": ["1/2 serving",
              "1 small serving",
              "1 serving",
              "1 serving · 1 tbsp peanut butter",
              "1 serving",
              "1 medium serving",
              "1 serving · fruit",
              "1 large serving · fruit · peanut butter"],
 "dica": "Frozen and blended, the banana releases its own natural sugar and turns into a cream just like ice cream, with no need for sugar, milk or heavy cream. It is sweet, cold and satisfying, with the fiber and the potassium of the fruit — the perfect dessert for hot days with no guilt.",
},
{
 "nome": "Fit Milk Flan",
 "hook": "The same creamy flan, with that golden caramel — only with no sugar and much lighter, made with milk and eggs.",
 "tempo": "50 min", "rende": "6 slices", "kcal_base": 130,
 "ings": ["3 eggs", "2 cups skim milk (or plant drink)", "baking sweetener to taste (the kind made for the oven)",
          "1 tsp vanilla extract", "caramel-style baking sweetener (optional, for the topping)",
          "hot water for the water bath"],
 "passos": [
   "Turn the oven to medium heat (350 °F). If you want the caramel, melt a little caramel-style sweetener in a small pan and spread it on the bottom (or skip the caramel).",
   "In the blender, blend the eggs, the milk, the sweetener and the vanilla for 1 minute, until it is well mixed.",
   "Pour the mixture into the pan.",
   "Put the pan inside a larger baking tray and fill the tray with hot water up to half the height of the pan (this is the water bath: the water makes the flan bake evenly and stay creamy).",
   "Bake for 40 minutes, until it sets but still wobbles slightly in the center. Let it cool and then put it in the fridge for 3 hours before turning it out."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · fruit",
              "1 slice",
              "1 medium slice",
              "1 slice · fruit",
              "1 large slice · fruit"],
 "dica": "Swapping condensed milk and sugar for skim milk and sweetener, the flan keeps its creaminess and flavor with a fraction of the calories. The eggs and the milk also bring protein. In a small slice, it is a classic dessert that fits your diet.",
},
{
 "nome": "Oat and Banana Cookies",
 "hook": "Two ingredients, one bowl and twenty minutes: soft, lightly sweet little cookies, with no sugar and no white flour.",
 "tempo": "20 min", "rende": "12 cookies", "kcal_base": 110,
 "ings": ["2 very ripe bananas", "1 1/2 cups rolled oats", "1 pinch of cinnamon",
          "1 tbsp raisins or 70% chocolate chips (optional)", "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Line a baking tray with parchment paper.",
   "In a bowl, mash the bananas well with a fork, until they turn into a purée with no big lumps.",
   "Add the oats, the cinnamon, the salt and, if you like, the raisins or the chopped chocolate. Mix until it forms a sticky dough.",
   "With a spoon, put small portions on the tray and flatten each one with the back of the spoon, giving it a cookie shape.",
   "Bake for 12 to 15 minutes, until the edges are golden and firm. Let them cool on the tray (they firm up as they cool) and serve."],
 "porcoes8": ["1 cookie",
              "2 cookies",
              "2 cookies",
              "2 cookies · fruit",
              "2 cookies",
              "3 cookies",
              "3 cookies",
              "3 to 4 cookies"],
 "dica": "The ripe banana sweetens and binds with no need for sugar or white flour, and the oats bring fiber that fills you up. They are natural cookies, great for a snack or dessert, that kill the craving for sweets in a light way — but count how many you eat, because they are easy to overdo.",
},
{
 "nome": "Baked Apple with Cinnamon and Walnuts",
 "hook": "The apple goes soft and fragrant with cinnamon, with a crunchy walnut filling — a warm dessert that comforts like a pie, without the crust.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 130,
 "ings": ["2 apples", "ground cinnamon to taste", "1 tbsp chopped walnuts (or other nuts)",
          "1 tbsp rolled oats", "1 tsp honey (optional)", "1 pinch of ground cloves (optional)"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Wash the apples and, with a knife, take out the core from the center (the seed part), making a hole, without going all the way through the bottom.",
   "In a small bowl, mix the chopped walnuts, the oats, the cinnamon and, if you like, the honey and the cloves.",
   "Fill the hole of each apple with this mixture, pressing lightly.",
   "Put the apples on a baking tray with a finger of water in the bottom (so they do not dry out) and dust more cinnamon on top.",
   "Bake for 25 to 30 minutes, until the apple is very soft (a fork goes in easily) and the filling is golden. Serve warm, on its own or with a spoon of plain yogurt."],
 "porcoes8": ["1/2 apple",
              "1 apple",
              "1 apple",
              "1 apple · 1 tbsp yogurt",
              "1 apple",
              "1 apple · extra walnuts",
              "1 apple · yogurt",
              "2 apples · yogurt"],
 "dica": "Baking the apple concentrates the fruit's natural sweetness, so it goes sweet with no sugar. Cinnamon lifts the flavor and helps control the craving for sweets, and the walnuts bring good fat and crunch. It is the comfort of an apple pie with a fraction of the calories.",
},
{
 "nome": "Homemade Fruit Jelly",
 "hook": "Colorful, wobbly and refreshing, with pieces of real fruit inside — the lightest dessert there is.",
 "tempo": "10 min + fridge", "rende": "4 glasses", "kcal_base": 70,
 "ings": ["1 tbsp unflavored gelatin", "2 cups natural fruit juice with no sugar (orange, grape or strawberry)",
          "1/2 cup water", "1 cup chopped fruit (strawberry, kiwi, mango or grapes)", "sweetener to taste (optional)"],
 "passos": [
   "In a small pot, put the water and sprinkle the unflavored gelatin over it. Let it rest for 2 minutes (the gelatin swells, which is called blooming).",
   "Put it over low heat and stir for 1 minute, just until the gelatin dissolves completely, without boiling. Turn it off.",
   "Add the natural fruit juice (and the sweetener, if you like) and mix well.",
   "Put the chopped fruit in the bottom of glasses or a dish and pour the liquid over it.",
   "Put it in the fridge for at least 4 hours, until it is firm. Serve very cold."],
 "porcoes8": ["1/2 glass",
              "1 small glass",
              "1 glass",
              "1 glass · extra fruit",
              "1 glass",
              "1 medium glass",
              "1 glass · fruit",
              "1 large glass · fruit"],
 "dica": "Made with natural juice instead of the powder full of sugar and coloring, homemade jelly has practically no calories and still carries pieces of real fruit. It is the ideal dessert for when you want something sweet and cold without weighing on your diet at all.",
},
{
 "nome": "Oat Bar with Dried Fruit",
 "hook": "The homemade cereal bar, chewy and lightly sweet, without the sugars and syrups of the store-bought ones — perfect for your bag.",
 "tempo": "30 min", "rende": "8 bars", "kcal_base": 150,
 "ings": ["2 cups rolled oats", "2 ripe bananas, mashed", "3 tbsp chopped dried fruit (raisins, apricot or dates)",
          "2 tbsp chopped nuts", "1 tbsp honey (optional)", "1 pinch of cinnamon and salt"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Line a small rectangular pan with parchment paper.",
   "In a bowl, mash the bananas well until they turn into a purée.",
   "Add the oats, the chopped dried fruit, the nuts, the cinnamon, the salt and, if you like, the honey. Mix until it forms a sticky, even dough.",
   "Pour the dough into the pan and press it down well with the back of a spoon, leaving a firm and even layer (the tighter you press, the less the bar crumbles).",
   "Bake for 20 minutes, until the edges are golden. Let it cool completely in the pan before cutting it into bars (if you cut it hot, it crumbles)."],
 "porcoes8": ["1 bar",
              "1 bar",
              "1 bar",
              "1 bar · fruit",
              "1 bar",
              "1 to 2 bars",
              "2 bars",
              "2 bars"],
 "dica": "Supermarket bars usually have more sugar and syrup than a candy. Made at home with oats, banana and dried fruit, the bar sweetens naturally and brings fiber and energy that hold hunger back. Great for a snack or a practical dessert, but eat one at a time.",
},
{
 "nome": "Frozen Yogurt Bark with Berries",
 "hook": "A crisp sheet of frozen yogurt scattered with fruit, that you break into pieces — pretty, fun and with no sugar.",
 "tempo": "5 min + freezer", "rende": "4 servings", "kcal_base": 100,
 "ings": ["1 large tub of plain Greek yogurt with no sugar (about 12 oz)", "1 cup of berries (strawberry, blueberry, raspberry)",
          "1 tbsp honey (optional)", "1 tbsp chopped nuts (optional)", "70% chocolate shavings (optional)"],
 "passos": [
   "Line a baking tray or a shallow dish with parchment paper.",
   "In a bowl, mix the Greek yogurt with the honey (if you use it), until it is very smooth.",
   "Spread the yogurt over the parchment paper, making a layer about half a finger thick.",
   "Scatter the berries on top (cut the strawberries), the nuts and the chocolate shavings, spreading them over the whole surface.",
   "Freeze for 3 to 4 hours, until it is really hard. Break or cut it into uneven pieces and serve right away (it melts fast). Keep the rest in the freezer."],
 "porcoes8": ["1 small piece",
              "1 piece",
              "1 to 2 pieces",
              "2 pieces",
              "2 pieces",
              "2 pieces",
              "2 to 3 pieces",
              "3 pieces"],
 "dica": "Greek yogurt brings protein and creaminess with no sugar, and frozen it turns into a cold, crisp treat. The berries sweeten naturally and fill it with antioxidants. It is a refreshing, light dessert, great for summer and for the urge to nibble on something sweet.",
},
{
 "nome": "Fit Chocolate Truffles",
 "hook": "Small, intense and chocolatey — the truffle that melts in your mouth with no sugar at all, for moments of a strong craving.",
 "tempo": "20 min + fridge", "rende": "10 truffles", "kcal_base": 120,
 "ings": ["3.5 oz 70% chocolate (or darker)", "4 tbsp hot milk (or plant drink)",
          "2 tbsp unsweetened grated coconut", "100% cocoa powder for rolling", "1 pinch of salt"],
 "passos": [
   "Chop the 70% chocolate into small pieces and put it in a bowl.",
   "Heat the milk until it almost boils and pour it over the chocolate. Wait 1 minute and stir until the chocolate melts completely, turning into a smooth, glossy cream (this is the ganache).",
   "Add the grated coconut and the salt and mix. Put it in the fridge for 1 hour, until the mixture is firm enough to roll.",
   "With your hands, take small portions and roll balls the size of a large olive.",
   "Roll each truffle in the cocoa powder to coat it. Keep them in the fridge and serve them cold."],
 "porcoes8": ["1 truffle",
              "1 truffle",
              "1 to 2 truffles",
              "2 truffles",
              "2 truffles",
              "2 truffles",
              "2 to 3 truffles",
              "3 truffles"],
 "dica": "Chocolate that is 70% or darker has little sugar and a lot of cocoa, which is rich in antioxidants. In a small truffle, it satisfies the intense craving for chocolate with far less sugar than a regular candy. One or two solve the craving without sabotaging your diet.",
},
{
 "nome": "Fit Carrot Cake with Cocoa Glaze",
 "hook": "The fluffy carrot cake of your childhood, with a chocolate glaze — no sugar, but with all the warmth and the flavor.",
 "tempo": "45 min", "rende": "8 slices", "kcal_base": 160,
 "ings": ["2 medium carrots, chopped", "3 eggs", "3 tbsp oil", "baking sweetener to taste (the kind made for the oven)",
          "1 1/2 cups oats blended into flour (or wholewheat flour)", "1 tsp baking powder",
          "Glaze: 2 tbsp 100% cocoa powder + 2 tbsp milk + sweetener to taste"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Spread a little oil in a pan and dust it with some flour.",
   "In the blender, blend the chopped carrots, the eggs, the oil and the sweetener until it turns into a smooth, orange cream.",
   "Move it to a bowl, add the blended oats (or flour) and mix. Last, add the baking powder and stir lightly.",
   "Pour it into the pan and bake for 30 minutes, until a toothpick stuck in the center comes out clean.",
   "Make the glaze: in a small pot, mix the cocoa, the milk and the sweetener and heat over low heat for 2 minutes, stirring, until it turns into a glossy cream. Spread it over the cake while it is still warm."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · fruit",
              "1 slice",
              "1 medium slice",
              "1 slice · fruit",
              "1 large slice"],
 "dica": "The carrot keeps the cake moist and naturally sweet, and also adds vitamin A. Swapping sugar for sweetener and white flour for oats, the cake stays light and full of fiber. The pure cocoa glaze gives the chocolate touch without the sugar of a traditional frosting.",
},
{
 "nome": "Lemon Mousse",
 "hook": "Tart in just the right measure, creamy and cold — a refreshing lemon mousse that cleans your palate and has no sugar.",
 "tempo": "10 min + fridge", "rende": "3 glasses", "kcal_base": 120,
 "ings": ["1 cup of plain yogurt with no sugar (about 6 oz)", "juice of 2 lemons", "zest of 1 lemon",
          "1 tbsp unflavored gelatin", "3 tbsp hot water",
          "sweetener to taste — or 2 tbsp honey"],
 "passos": [
   "Wash 1 lemon well and take the zest only from the green part of the peel (the white part is bitter). Squeeze the 2 lemons for the juice.",
   "In a cup, dissolve the unflavored gelatin in the hot water, stirring until it is clear. Let it cool a little.",
   "In a bowl, mix the yogurt, the lemon juice, the zest and the sweetener (or honey), until it is creamy.",
   "Add the dissolved gelatin and mix well and fast, so no little lumps form.",
   "Divide it between glasses and put it in the fridge for at least 2 hours, until it sets. Serve cold, with more lemon zest on top."],
 "porcoes8": ["1/2 glass",
              "1 small glass",
              "1 glass",
              "1 glass · fruit",
              "1 glass",
              "1 medium glass",
              "1 glass · fruit",
              "1 large glass · fruit"],
 "dica": "Lemon brings freshness and a strong flavor that tricks the craving for sweets without needing much sweetener. Plain yogurt brings protein and creaminess, and the gelatin sets the mousse with no cream. A light, refreshing dessert with close to zero fat.",
},
{
 "nome": "Fit Berry Cheesecake (No Bake)",
 "hook": "Creamy, with a crunchy base and a fruit topping, put together with no oven — the cheesecake of your dreams in a light, sugar-free version.",
 "tempo": "20 min + fridge", "rende": "6 slices", "kcal_base": 170,
 "ings": ["Base: 1 cup oats + 1 mashed banana + 1 tsp cinnamon",
          "Cream: 1 cup ricotta (or cottage cheese) + 1/2 tub plain yogurt + sweetener to taste + juice of 1/2 lemon",
          "1 tbsp unflavored gelatin + 3 tbsp hot water",
          "Topping: 1 cup of berries + sweetener to taste"],
 "passos": [
   "Base: mix the oats, the mashed banana and the cinnamon until it forms a dough. Press it into the bottom of a small pan (ideally a springform one), making a firm layer. Put it in the freezer for 10 minutes.",
   "Dissolve the gelatin in the hot water, stirring until it is clear. Let it cool a little.",
   "Cream: in the blender, blend the ricotta, the yogurt, the sweetener and the lemon juice until it is a very smooth cream. Add the gelatin and blend for another 20 seconds.",
   "Pour the cream over the base and smooth the surface. Put it in the fridge for at least 3 hours, until it sets.",
   "Topping: in a small pot, cook the berries with the sweetener over low heat for 5 minutes, mashing them a little, until it turns into a jam. Let it cool and spread it over the cheesecake before serving."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · extra topping",
              "1 slice",
              "1 medium slice",
              "1 slice · topping",
              "1 large slice · topping"],
 "dica": "Ricotta and cottage cheese give the creaminess of cream cheese with much less fat and more protein. The oat and banana base replaces the buttery biscuit, and the cooked fruit topping needs no sugar. A real cheesecake that fits your diet, in a controlled slice.",
},
{
 "nome": "Homemade Fruit Popsicles",
 "hook": "Refreshing and full of real fruit, these homemade popsicles are the perfect dessert for the heat — and they do not have a drop of sugar.",
 "tempo": "10 min + freezer", "rende": "6 popsicles", "kcal_base": 60,
 "ings": ["2 cups chopped fruit (strawberry, mango, kiwi or watermelon)", "1 cup natural juice with no sugar (or coconut water)",
          "1 tub of plain yogurt with no sugar (optional, for creamy popsicles)", "sweetener to taste (optional)",
          "popsicle molds and sticks"],
 "passos": [
   "Chop the fruit into small pieces, so they fit in the molds.",
   "Choose the style: for fruit popsicles, use only the fruit and the natural juice; for creamy popsicles, blend the fruit with the yogurt in the blender.",
   "Put some pieces of fruit in the bottom of each mold (it looks pretty) and fill it up with the juice or the blended cream, leaving a finger of space at the top (the liquid swells as it freezes).",
   "Stick a stick in the center of each popsicle.",
   "Freeze for at least 5 hours, until they are really firm. To unmold them, run the mold quickly under warm water."],
 "porcoes8": ["1 popsicle",
              "1 popsicle",
              "1 popsicle",
              "1 to 2 popsicles",
              "1 popsicle",
              "1 to 2 popsicles",
              "2 popsicles",
              "2 popsicles"],
 "dica": "Store-bought popsicles are almost only water, sugar and coloring. Made at home with real fruit and natural juice, the popsicle becomes a refreshing dessert full of vitamins and with practically no calories — the best way to kill the craving for something cold in the heat with no guilt.",
},
{
 "nome": "Apple and Cinnamon Muffins",
 "hook": "Fluffy, fragrant and with pieces of apple — afternoon muffins that look like a sin, but are light and sugar-free.",
 "tempo": "35 min", "rende": "6 muffins", "kcal_base": 140,
 "ings": ["2 eggs", "1 grated apple + 1/2 apple in small cubes", "1 1/2 cups oats blended into flour",
          "3 tbsp oil", "baking sweetener to taste (the kind made for the oven)", "1/2 cup milk",
          "1 tsp cinnamon", "1 tsp baking powder", "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Line a muffin pan with paper liners (or spread a little oil in the cups).",
   "In a bowl, beat the eggs with the sweetener and the oil for 1 minute. Add the milk and the grated apple and mix.",
   "Add the blended oats, the cinnamon and the salt and stir until it is an even batter. Add the apple cubes and the baking powder and mix lightly.",
   "Divide the batter between the liners, filling them two thirds of the way (they rise).",
   "Bake for 20 to 25 minutes, until they are golden and a toothpick comes out clean. Let them cool a little and serve."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 tbsp yogurt",
              "1 muffin",
              "1 to 2 muffins",
              "2 muffins",
              "2 muffins"],
 "dica": "The grated apple keeps the muffins moist and naturally sweet, so you do not need sugar. The oats bring fiber that fills you up and the cinnamon lifts the sweetness of the fruit. They are great for a snack or dessert, in a one-unit portion, killing the craving for bakery food in a light way.",
},
{
 "nome": "Apple and Oat Crumble",
 "hook": "Soft apple underneath, a crunchy oat crumb on top — the comfort of a warm pie, put together in minutes and with no sugar.",
 "tempo": "40 min", "rende": "4 servings", "kcal_base": 160,
 "ings": ["3 apples in cubes", "juice of 1/2 lemon", "1 tsp cinnamon",
          "Crumb: 1 cup rolled oats + 2 tbsp chopped nuts + 2 tbsp coconut oil (or regular oil) + sweetener to taste",
          "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350 °F). In a bowl, mix the apple cubes with the lemon juice and the cinnamon and spread them in the bottom of a baking dish.",
   "Make the crumb: in another bowl, mix the oats, the nuts, the oil, the sweetener and the salt, rubbing with your fingertips until it forms a moist, clumpy crumb.",
   "Spread the crumb over the apples, covering the whole surface.",
   "Bake for 25 to 30 minutes, until the apple bubbles at the sides and the crumb is golden and crisp.",
   "Let it cool for 5 minutes and serve. It is delicious with a spoon of plain yogurt or banana nice cream on top."],
 "porcoes8": ["1/2 serving",
              "1 small serving",
              "1 serving",
              "1 serving · yogurt",
              "1 serving",
              "1 medium serving",
              "1 serving · yogurt",
              "1 large serving · yogurt"],
 "dica": "The baked apple releases its own sweetness, and the cinnamon reinforces the flavor with no sugar. The oat and nut crumb gives the crunch of a pie with fiber and good fat instead of butter and white flour. It is the comfort of a warm baked dessert, in the right portion.",
},
{
 "nome": "Baked Pear with Spices",
 "hook": "The pear goes soft and juicy, perfumed with cinnamon and cloves — an elegant, warm dessert, sweetened only by the fruit.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 110,
 "ings": ["2 firm pears", "cinnamon stick (or ground)", "2 cloves", "orange zest (optional)",
          "1 tsp honey (optional)", "1 tbsp chopped walnuts or almonds"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Wash the pears, cut them in half lengthwise and take out the core from the center with a small spoon, making a hollow.",
   "Put the pear halves on a baking tray, cut side up. Dust cinnamon over them and put a clove and a little orange zest in each hollow.",
   "If you like, drip a few drops of honey on each pear.",
   "Put a finger of water in the bottom of the tray (so they do not dry out) and bake for 25 minutes, until the pear is very soft (a fork goes in easily).",
   "Take out the cloves, sprinkle the chopped nuts on top and serve warm, on its own or with a spoon of plain yogurt."],
 "porcoes8": ["1 half",
              "1 pear (2 halves)",
              "1 pear",
              "1 pear · yogurt",
              "1 pear",
              "1 pear · extra nuts",
              "1 pear · yogurt",
              "2 pears · yogurt"],
 "dica": "Baking the pear concentrates the natural sugar of the fruit, leaving it sweet with no need for added sugar. The spices bring a comforting aroma that satisfies your palate, and the nuts add good fat and crunch. A warm, light and sophisticated dessert.",
},
]
