# -*- coding: utf-8 -*-
"""30 receitas de CAFE DA MANHA (001-030). ESPANHOL (America Latina).

Traducao literal de `receitas_cafe_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario LatAm com foco Mexico (aguacate, platano,
jitomate, camote, crema de cacahuate, fresa, frutos rojos).
⛔ METRICO: g, ml, °C — como pt/de/fr. O EN e' o unico imperial do produto;
os numeros metricos vem do de/fr, NUNCA de oz/cup -> g de volta. A escada das
8 faixas so' sobrevive em grama: 30/40/45/50/50/55/60/70 g.
⛔ A colher fica caseira (cucharada / cucharadita), como no de/fr — o que se
converte e' o imperial, nao a medida de colher.
⛔ O campo `prompt` NAO e' replicado aqui: a foto e' a mesma do PT (fotos/001-030,
sem texto na imagem), e prompt duplicado e' prompt que diverge.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
Metas (kcal): 300/370/420/470 · 450/510/560/620
"""

RECEITAS = [
{
 "nome": "Panqueques de plátano y avena",
 "hook": "Tres ingredientes que ya tienes en casa, listos en 10 minutos — y te mantienen satisfecha hasta el almuerzo.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 325,
 "ings": ["1 plátano maduro", "40 g de avena en hojuelas (unas 4 cucharadas)", "1 huevo",
          "1 pizca de canela", "1 pizca de polvo para hornear (opcional, los hace más esponjosos)",
          "un poco de aceite o aceite en aerosol para el sartén"],
 "passos": [
   "Pela el plátano y ponlo en un plato hondo. Aplástalo bien con un tenedor hasta que quede un puré suave, sin grumos grandes.",
   "Agrega el huevo y revuelve hasta que todo quede bien mezclado.",
   "Agrega la avena, la canela y el polvo para hornear. Revuelve y deja reposar 3 minutos — la avena absorbe la humedad y la mezcla se pone más firme, lo que después facilita voltearlos.",
   "Calienta un sartén antiadherente a fuego medio-bajo y úntalo con un poco de aceite (o usa el aerosol).",
   "Con una cuchara, pon porciones pequeñas de mezcla en el sartén, del tamaño de media palma de tu mano. Los panqueques pequeños se voltean mucho más fácil que los grandes.",
   "Déjalos cocinar de 2 a 3 minutos, hasta que aparezcan burbujas pequeñas arriba y las orillas se firmen. Voltéalos con cuidado y dora el otro lado 1 o 2 minutos más.",
   "Sírvelos calientes. Si quieres, termina con rebanadas de plátano, un puñado de frutos rojos o 1 cucharadita de miel."],
 "porcoes8": ["¾ plátano · 30 g de avena · 1 huevo",
              "1 plátano · 40 g de avena · 1 huevo · 1 puñado de frutos rojos",
              "1 plátano · 45 g de avena · 1 huevo · 1 cucharadita de crema de cacahuate",
              "1 plátano · 50 g de avena · 1 huevo · 1 cucharada de crema de cacahuate",
              "1 plátano · 50 g de avena · 2 huevos · 1 cucharadita de crema de cacahuate",
              "1 plátano grande · 55 g de avena · 2 huevos · 1 cucharada de crema de cacahuate",
              "1 plátano grande · 60 g de avena · 2 huevos · 1 cucharada de crema de cacahuate · frutos rojos",
              "1 plátano grande · 70 g de avena · 2 huevos · 1,5 cucharadas de crema de cacahuate"],
 "dica": "La avena es rica en fibra, que hace más lenta la digestión y te mantiene satisfecha por horas — eso es lo que evita el hambre de media mañana que te hace picar algo. El plátano aporta dulzor natural sin azúcar añadida, y el huevo aporta proteína para proteger tu músculo mientras pierdes grasa.",
},
{
 "nome": "Huevos revueltos con espinaca y pan integral tostado",
 "hook": "El desayuno clásico que llena el plato de proteína y fibra en menos de 10 minutos.",
 "tempo": "8 min", "rende": "1 porción", "kcal_base": 340,
 "ings": ["2 huevos", "1 puñado grande de hojas frescas de espinaca", "1 rebanada de pan integral",
          "1 cucharadita de aceite de oliva", "sal y pimienta al gusto", "1 jitomate pequeño (opcional)"],
 "passos": [
   "Lava la espinaca y escúrrela bien. Si las hojas están grandes, córtalas a la mitad.",
   "Rompe los huevos en un tazón, sazona con sal y pimienta y bátelos ligeramente con un tenedor.",
   "Calienta el aceite de oliva en un sartén antiadherente a fuego medio. Agrega la espinaca y revuelve 1 minuto, solo hasta que se marchite (las hojas se ponen suaves).",
   "Baja el fuego, vierte los huevos batidos sobre la espinaca y déjalos 30 segundos sin revolver.",
   "Con una espátula, empuja los huevos despacio desde el fondo hacia el centro, hasta que queden cremosos y todavía húmedos. Apaga el fuego antes de que se resequen.",
   "Tuesta la rebanada de pan integral. Sirve los huevos encima o a un lado, con rebanadas de jitomate si quieres."],
 "porcoes8": ["1 huevo + 1 clara · ½ rebanada de pan · espinaca, todo lo que quieras",
              "2 huevos · 1 rebanada de pan · espinaca, todo lo que quieras",
              "2 huevos · 1 rebanada de pan · un poco más de aceite de oliva",
              "2 huevos + 1 clara · 1 rebanada de pan · 1 cucharadita de queso rallado",
              "3 huevos · 1 rebanada de pan · 1 cucharadita de aceite de oliva",
              "3 huevos · 2 rebanadas de pan · espinaca, todo lo que quieras",
              "3 huevos · 2 rebanadas de pan · 1 cucharada de queso rallado",
              "4 huevos · 2 rebanadas de pan · 1 cucharada de queso rallado"],
 "dica": "Los huevos son una proteína completa y muy saciante — quienes desayunan huevo sienten menos hambre durante el día. La espinaca agrega volumen y fibra casi sin calorías, así llenas el plato y el estómago sin disparar tus calorías.",
},
{
 "nome": "Yogur griego con frutos rojos y avena",
 "hook": "Armado en capas, sin cocinar nada — proteína y fibra en un vaso bonito en 3 minutos.",
 "tempo": "3 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["1 vaso de yogur griego natural sin azúcar (unos 170 g)",
          "1 puñado de frutos rojos (fresa, arándano o frambuesa)",
          "3 cucharadas de avena en hojuelas", "1 cucharadita de miel (opcional)",
          "canela al gusto"],
 "passos": [
   "Si usas fresas, lávalas y córtalas en trozos pequeños. Los demás frutos rojos pueden ir enteros.",
   "En un vaso o una taza, pon la mitad del yogur en el fondo.",
   "Reparte encima la mitad de los frutos rojos y la mitad de la avena.",
   "Repite: el resto del yogur, y encima los frutos rojos y la avena que quedan.",
   "Termina con una pizca de canela y, si quieres, el chorrito de miel. Sirve de inmediato, mientras la avena sigue crujiente."],
 "porcoes8": ["120 g de yogur · frutos rojos · 2 cucharadas de avena",
              "170 g de yogur · frutos rojos · 3 cucharadas de avena",
              "170 g de yogur · frutos rojos · 3 cucharadas de avena · 1 cucharadita de miel",
              "200 g de yogur · frutos rojos · 4 cucharadas de avena · 1 cucharadita de miel",
              "200 g de yogur · frutos rojos · 4 cucharadas de avena · 1 cucharada de nueces",
              "250 g de yogur · frutos rojos · 4 cucharadas de avena · 1 cucharada de nueces",
              "250 g de yogur · frutos rojos · 5 cucharadas de avena · 1 cucharada de nueces",
              "300 g de yogur · frutos rojos · 6 cucharadas de avena · 1 cucharada de nueces"],
 "dica": "El yogur griego tiene casi el doble de proteína que el yogur común, lo que te mantiene satisfecha por más tiempo. Sin azúcar añadida, el dulzor viene de la fruta — y la avena aporta fibra y textura crujiente, convirtiendo un antojo rápido en una comida que sí te sostiene.",
},
{
 "nome": "Omelette de claras con jitomate y queso cottage",
 "hook": "Ligero, esponjoso y lleno de proteína — el desayuno para quien quiere bajar de peso sin pasar hambre.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 250,
 "ings": ["3 claras de huevo + 1 huevo entero", "1 jitomate pequeño, picado",
          "2 cucharadas de queso cottage", "cebollín o perejil picado",
          "sal y pimienta al gusto", "aceite en aerosol"],
 "passos": [
   "Pica el jitomate en cubos pequeños y sécale el líquido de más con una servilleta de papel, para que el omelette no quede aguado.",
   "En un tazón, pon las claras, el huevo entero, sal y pimienta. Bate con un tenedor 30 segundos, hasta que espume ligeramente.",
   "Calienta un sartén antiadherente a fuego medio y rocíalo con aceite. Reparte el jitomate picado en el fondo durante 1 minuto.",
   "Vierte los huevos batidos encima e inclina el sartén para repartirlos parejo.",
   "Cuando las orillas se firmen (1 o 2 minutos), reparte el queso cottage sobre la mitad del omelette.",
   "Con la espátula, dobla el omelette a la mitad, cubriendo el queso cottage. Déjalo un minuto más y sirve con las hierbas encima."],
 "porcoes8": ["2 claras + 1 huevo · 1 cucharada de queso cottage",
              "3 claras + 1 huevo · 2 cucharadas de queso cottage",
              "3 claras + 1 huevo · 2 cucharadas de queso cottage · ½ rebanada de pan",
              "3 claras + 1 huevo · 3 cucharadas de queso cottage · 1 rebanada de pan",
              "3 claras + 2 huevos · 2 cucharadas de queso cottage · 1 rebanada de pan",
              "4 claras + 2 huevos · 3 cucharadas de queso cottage · 1 rebanada de pan",
              "4 claras + 2 huevos · 3 cucharadas de queso cottage · 2 rebanadas de pan",
              "5 claras + 2 huevos · 4 cucharadas de queso cottage · 2 rebanadas de pan"],
 "dica": "Las claras son casi proteína pura, con muy poca grasa y muy pocas calorías — perfectas para subir la proteína de tu desayuno sin hacerlo pesado. El queso cottage entra cremoso y también rico en proteína, y el jitomate aporta sabor y volumen por casi nada de calorías.",
},
{
 "nome": "Avena remojada con manzana y canela",
 "hook": "La armas en la noche y en la mañana ya te está esperando en el refrigerador — sin prisas y sin estufa.",
 "tempo": "5 min + refrigerador", "rende": "1 porción", "kcal_base": 350,
 "ings": ["40 g de avena en hojuelas", "150 ml de leche (o bebida vegetal)",
          "½ manzana, cortada en cubos pequeños", "1 cucharada de yogur natural",
          "canela al gusto", "1 cucharadita de miel (opcional)"],
 "passos": [
   "En un frasco con tapa, mezcla la avena, la leche y el yogur.",
   "Agrega la mitad de la manzana picada y una buena pizca de canela. Revuelve bien.",
   "Cierra el frasco y mételo al refrigerador por lo menos 4 horas, o toda la noche.",
   "En la mañana la avena estará cremosa y suave. Revuelve otra vez.",
   "Corona con el resto de la manzana fresca y más canela. Si quieres, agrega el chorrito de miel. Cómela fría, directo del frasco."],
 "porcoes8": ["30 g de avena · 120 ml de leche · ½ manzana",
              "40 g de avena · 150 ml de leche · ½ manzana",
              "45 g de avena · 150 ml de leche · ½ manzana · 1 cucharadita de miel",
              "50 g de avena · 180 ml de leche · 1 manzana · 1 cucharadita de miel",
              "50 g de avena · 180 ml de leche · 1 manzana · 1 cucharada de nueces",
              "55 g de avena · 200 ml de leche · 1 manzana · 1 cucharada de nueces",
              "60 g de avena · 220 ml de leche · 1 manzana · 1 cucharada de nueces",
              "70 g de avena · 250 ml de leche · 1 manzana · 1,5 cucharadas de nueces"],
 "dica": "Remojar la avena no cambia las calorías, pero hace la fibra más fácil de digerir y la comida más cremosa y saciante. Como ya está lista en el refrigerador, no te saltas el desayuno cuando andas con prisa — y saltarse comidas es lo que hace que mucha gente coma de más al final del día.",
},
{
 "nome": "Pan tostado con aguacate y huevo",
 "hook": "Cremoso, salado y de los que de verdad llenan — listo en 8 minutos.",
 "tempo": "8 min", "rende": "1 porción", "kcal_base": 340,
 "ings": ["1 rebanada de pan integral", "½ aguacate maduro (o ¼ de un aguacate grande)",
          "1 huevo", "jugo de ½ limón", "sal, pimienta y hojuelas de chile al gusto",
          "aceite en aerosol"],
 "passos": [
   "Tuesta la rebanada de pan integral hasta que quede firme y dorada.",
   "En un tazón pequeño, aplasta el aguacate con un tenedor, agrega el jugo de limón, sal y pimienta. Mezcla hasta que quede una crema.",
   "Calienta un sartén antiadherente, rocíalo con aceite y fríe el huevo a fuego medio, como más te guste (estrellado con la yema líquida o revuelto).",
   "Unta la crema de aguacate sobre el pan tostado.",
   "Pon el huevo encima y termina con una pizca de hojuelas de chile. Sirve de inmediato."],
 "porcoes8": ["½ rebanada de pan · ¼ aguacate · 1 huevo",
              "1 rebanada de pan · ½ aguacate · 1 huevo",
              "1 rebanada de pan · ½ aguacate · 1 huevo · hojas verdes",
              "1 rebanada de pan · ½ aguacate · 2 huevos",
              "1 rebanada de pan · ½ aguacate · 2 huevos · hojas verdes",
              "2 rebanadas de pan · ½ aguacate · 2 huevos",
              "2 rebanadas de pan · 1 aguacate pequeño · 2 huevos",
              "2 rebanadas de pan · 1 aguacate pequeño · 3 huevos"],
 "dica": "El aguacate tiene grasa buena, que te mantiene satisfecha por mucho tiempo y hace la comida cremosa sin mantequilla. Junto con el huevo y el pan integral, tienes grasa buena, proteína y fibra en el mismo pan tostado — la combinación que detiene el hambre por horas.",
},
{
 "nome": "Avena caliente con plátano y crema de cacahuate",
 "hook": "Calientita y reconfortante, el desayuno que sabe a postre pero juega a tu favor.",
 "tempo": "8 min", "rende": "1 porción", "kcal_base": 380,
 "ings": ["40 g de avena en hojuelas", "200 ml de leche (o bebida vegetal)",
          "½ plátano, aplastado", "1 cucharadita de crema de cacahuate",
          "canela al gusto", "½ plátano en rebanadas para encima"],
 "passos": [
   "En una olla pequeña, pon la avena, la leche y el plátano aplastado.",
   "Cocina a fuego medio-bajo, revolviendo todo el tiempo con una cuchara para que no se pegue al fondo.",
   "Después de 4 o 5 minutos la mezcla espesa y queda cremosa. Si la quieres más líquida, agrega un poco más de leche.",
   "Apaga el fuego, agrega la canela y revuelve.",
   "Viértela en un tazón, corona con las rebanadas de plátano y la crema de cacahuate. Sirve caliente."],
 "porcoes8": ["30 g de avena · 180 ml de leche · ½ plátano · sin crema de cacahuate",
              "40 g de avena · 200 ml de leche · 1 plátano · 1 cucharadita de crema de cacahuate",
              "45 g de avena · 200 ml de leche · 1 plátano · 1 cucharadita de crema de cacahuate",
              "50 g de avena · 220 ml de leche · 1 plátano · 1 cucharada de crema de cacahuate",
              "50 g de avena · 220 ml de leche · 1 plátano · 1 cucharada de crema de cacahuate",
              "55 g de avena · 250 ml de leche · 1 plátano · 1 cucharada de crema de cacahuate",
              "60 g de avena · 250 ml de leche · 1 plátano · 1,5 cucharadas de crema de cacahuate",
              "70 g de avena · 300 ml de leche · 1 plátano · 2 cucharadas de crema de cacahuate"],
 "dica": "La avena cocida forma un gel en el estómago que detiene el hambre. El plátano endulza sin azúcar y devuelve energía, y la crema de cacahuate aporta grasa buena y proteína — solo cuida la cantidad, porque es alta en calorías: una cucharada ya cumple su función.",
},
{
 "nome": "Smoothie bowl de plátano y frutos rojos",
 "hook": "Espeso para comerse con cuchara, frío y colorido — parece helado, pero juega a favor de tu peso.",
 "tempo": "6 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["1 plátano congelado en rebanadas", "1 puñado de frutos rojos congelados",
          "3 cucharadas de yogur natural", "50 ml de leche (o bebida vegetal)",
          "2 cucharadas de avena y fruta fresca para encima"],
 "passos": [
   "Usa el plátano ya congelado (córtalo en rebanadas la noche anterior y congélalo) — eso es lo que hace el smoothie espeso sin hielo.",
   "En la licuadora, pon el plátano, los frutos rojos congelados, el yogur y la leche.",
   "Licúa a velocidad máxima, deteniéndote para revolver con una cuchara cuando se atore. Agrega leche solo de cucharada en cucharada, lo mínimo necesario para licuar. La textura tiene que quedar espesa, como de helado.",
   "Viértelo en un tazón.",
   "Corona con la avena y la fruta fresca en hileras parejas. Cómelo de inmediato, con cuchara, antes de que se derrita."],
 "porcoes8": ["1 plátano · frutos rojos · 2 cucharadas de yogur · 1 cucharada de avena",
              "1 plátano · frutos rojos · 3 cucharadas de yogur · 2 cucharadas de avena",
              "1 plátano · frutos rojos · 3 cucharadas de yogur · 2 cucharadas de avena · semillas",
              "1 plátano · frutos rojos · 4 cucharadas de yogur · 3 cucharadas de avena",
              "1 plátano · frutos rojos · 4 cucharadas de yogur · 3 cucharadas de avena · 1 cucharada de nueces",
              "1 plátano grande · frutos rojos · 5 cucharadas de yogur · 3 cucharadas de avena · nueces",
              "1 plátano grande · frutos rojos · 5 cucharadas de yogur · 4 cucharadas de avena · nueces",
              "2 plátanos · frutos rojos · 6 cucharadas de yogur · 4 cucharadas de avena · nueces"],
 "dica": "Congelar la fruta te da una textura de helado sin azúcar y sin crema. El yogur suma proteína, y comer con cuchara, despacio, le da tiempo a tu cerebro de registrar que ya estás satisfecha — muy diferente de tomarse un jugo licuado con popote en segundos.",
},
{
 "nome": "Huevos cocidos con aguacate y jitomate",
 "hook": "Sin sartén y sin batidero — proteína y grasa buena en un plato que armas en minutos.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["2 huevos", "½ aguacate", "1 jitomate", "jugo de ½ limón",
          "sal, pimienta y aceite de oliva al gusto", "hojas verdes al gusto"],
 "passos": [
   "Pon los huevos en una olla, cúbrelos con agua fría y ponla al fuego. Desde el momento en que hierve, cuenta de 8 a 9 minutos para una yema firme.",
   "Mientras tanto, corta el aguacate y el jitomate en rebanadas y acomódalos en el plato sobre unas hojas verdes.",
   "Escurre los huevos y ponlos bajo el chorro de agua fría 1 minuto — así se pelan más fácil.",
   "Pela los huevos, córtalos a la mitad y ponlos en el plato.",
   "Rocía todo con el jugo de limón y un poco de aceite de oliva, sazona con sal y pimienta y sirve."],
 "porcoes8": ["1 huevo · ¼ aguacate · jitomate",
              "2 huevos · ½ aguacate · jitomate",
              "2 huevos · ½ aguacate · jitomate · ½ rebanada de pan",
              "2 huevos · ½ aguacate · jitomate · 1 rebanada de pan",
              "3 huevos · ½ aguacate · jitomate · 1 rebanada de pan",
              "3 huevos · ½ aguacate · jitomate · 2 rebanadas de pan",
              "3 huevos · 1 aguacate pequeño · jitomate · 2 rebanadas de pan",
              "4 huevos · 1 aguacate pequeño · jitomate · 2 rebanadas de pan"],
 "dica": "Un huevo cocido es la proteína más práctica que existe: puedes cocer varios de una vez y guardarlos en el refrigerador. Con aguacate y jitomate armas un desayuno completo de grasa buena y fibra sin prender la estufa en la mañana.",
},
{
 "nome": "Panqueques proteicos de avena y clara de huevo",
 "hook": "El panqueque para los días de entrenamiento: más proteína, la misma sencillez.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["40 g de avena en hojuelas", "3 claras de huevo (o 2 claras + 1 huevo)",
          "½ plátano, aplastado", "1 pizca de polvo para hornear",
          "canela al gusto", "aceite en aerosol"],
 "passos": [
   "Si quieres una mezcla más suave, licúa la avena hasta que se haga harina. Si te gusta rústica, úsala en hojuelas.",
   "En un tazón, mezcla la avena, las claras, el plátano aplastado, el polvo para hornear y la canela hasta que todo quede bien mezclado.",
   "Deja reposar 3 minutos para que la avena absorba la humedad.",
   "Calienta el sartén antiadherente a fuego medio-bajo y rocíalo con aceite.",
   "Haz panqueques pequeños. Déjalos 2 minutos de cada lado, volteándolos cuando aparezcan burbujas pequeñas.",
   "Sirve con fruta fresca encima. Sáltate los jarabes azucarados — el plátano ya endulza."],
 "porcoes8": ["2 claras · 30 g de avena · ½ plátano",
              "3 claras · 40 g de avena · ½ plátano",
              "3 claras · 45 g de avena · ½ plátano · fruta",
              "2 claras + 1 huevo · 50 g de avena · 1 plátano",
              "3 claras + 1 huevo · 50 g de avena · 1 plátano",
              "3 claras + 1 huevo · 55 g de avena · 1 plátano · fruta",
              "4 claras + 1 huevo · 60 g de avena · 1 plátano · fruta",
              "4 claras + 2 huevos · 70 g de avena · 1 plátano · fruta"],
 "dica": "Cambiar parte de los huevos por claras sube la proteína y baja la grasa — bueno para quien busca definición. La proteína también es el nutriente que más sacia, así que este panqueque detiene el hambre con menos calorías que la versión dulce tradicional.",
},
{
 "nome": "Pudín de chía con fruta",
 "hook": "Lo mezclas en 2 minutos, el refrigerador hace el resto y despiertas con un postre saludable.",
 "tempo": "5 min + refrigerador", "rende": "1 porción", "kcal_base": 280,
 "ings": ["3 cucharadas de semillas de chía", "200 ml de leche (o bebida vegetal)",
          "½ cucharadita de extracto de vainilla (opcional)",
          "fruta picada al gusto para encima", "1 cucharadita de miel (opcional)"],
 "passos": [
   "En un frasco con tapa, pon la chía, la leche y la vainilla. Revuelve bien 30 segundos.",
   "Espera 5 minutos y revuelve otra vez — este segundo revuelto deshace los grumos que se forman y es el secreto de un pudín parejo.",
   "Cierra el frasco y mételo al refrigerador por lo menos 4 horas, o toda la noche.",
   "La chía absorbe el líquido y forma un pudín con textura de gelatina.",
   "Antes de servir, revuelve, corona con fruta picada y, si quieres, el chorrito de miel."],
 "porcoes8": ["2 cucharadas de chía · 150 ml de leche · fruta",
              "3 cucharadas de chía · 200 ml de leche · fruta",
              "3 cucharadas de chía · 200 ml de leche · fruta · 1 cucharadita de miel",
              "3 cucharadas de chía · 220 ml de leche · fruta · 1 cucharada de granola",
              "4 cucharadas de chía · 220 ml de leche · fruta · 1 cucharada de granola",
              "4 cucharadas de chía · 250 ml de leche · fruta · 2 cucharadas de granola",
              "4 cucharadas de chía · 250 ml de leche · fruta · 2 cucharadas de granola · nueces",
              "5 cucharadas de chía · 300 ml de leche · fruta · 2 cucharadas de granola · nueces"],
 "dica": "La chía absorbe muchas veces su propio peso en líquido y se hincha en el estómago, dando una sensación de saciedad que dura. También es rica en fibra y omega-3 — uno de los ingredientes más saciantes por caloría que existen.",
},
{
 "nome": "Muffins de huevo al horno con verduras",
 "hook": "Horneas una tanda y tienes desayuno listo toda la semana — solo calientas y comes.",
 "tempo": "25 min", "rende": "6 muffins (2 por porción)", "kcal_base": 220,
 "ings": ["6 huevos", "½ pimiento, picado", "1 puñado de espinaca picada",
          "2 cucharadas de queso rallado", "sal y pimienta al gusto",
          "un poco de aceite (o aerosol) para que no se pegue"],
 "passos": [
   "Precalienta el horno a 180 °C y unta un poco de aceite (o rocía aerosol) en el molde para muffins, para que los huevos no se peguen.",
   "Pica el pimiento y la espinaca en trozos pequeños.",
   "En un tazón, bate los huevos con sal y pimienta. Agrega las verduras y el queso y mezcla.",
   "Reparte la mezcla en los 6 huecos, llenando cada uno hasta unas ¾ partes.",
   "Hornea de 18 a 20 minutos, hasta que cuajen y queden ligeramente dorados. Un palillo en el centro debe salir limpio.",
   "Déjalos enfriar un poco antes de sacarlos. Guárdalos en el refrigerador hasta 4 días y caliéntalos al comerlos."],
 "porcoes8": ["1 muffin + hojas verdes",
              "2 muffins",
              "2 muffins · ½ rebanada de pan",
              "2 muffins · 1 rebanada de pan",
              "3 muffins · 1 rebanada de pan",
              "3 muffins · 2 rebanadas de pan",
              "3 muffins · 2 rebanadas de pan · ¼ aguacate",
              "4 muffins · 2 rebanadas de pan · ¼ aguacate"],
 "dica": "Tener comida lista es lo que frena la decisión equivocada cuando pega el hambre de la mañana. Estos muffins son proteína y verduras en una porción controlada — puedes congelarlos y siempre tener un desayuno que te sostiene, sin improvisar con lo que no deberías comer.",
},
{
 "nome": "Pan tostado con ricotta, fresa y miel",
 "hook": "Dulce y cremoso como un antojo, pero con proteína y sin azúcar pesada.",
 "tempo": "6 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["1 rebanada de pan integral", "3 cucharadas de ricotta",
          "4 fresas en rebanadas", "1 cucharadita de miel",
          "ralladura de limón y menta (opcional)"],
 "passos": [
   "Tuesta la rebanada de pan hasta que quede firme.",
   "En un tazón, aplasta la ricotta con un tenedor hasta que quede cremosa. Si está seca, agrega un poco de leche.",
   "Unta la ricotta sobre el pan tostado, cubriendo toda la superficie.",
   "Acomoda las rebanadas de fresa encima.",
   "Termina con el chorrito de miel y, si quieres, ralladura de limón y unas hojas de menta. Sirve de inmediato."],
 "porcoes8": ["½ rebanada de pan · 2 cucharadas de ricotta · fresas",
              "1 rebanada de pan · 3 cucharadas de ricotta · fresas · 1 cucharadita de miel",
              "1 rebanada de pan · 3 cucharadas de ricotta · fresas · miel",
              "1 rebanada de pan · 4 cucharadas de ricotta · fresas · miel · nueces",
              "1 rebanada de pan · 4 cucharadas de ricotta · fresas · 1 huevo cocido",
              "2 rebanadas de pan · 4 cucharadas de ricotta · fresas · miel",
              "2 rebanadas de pan · 5 cucharadas de ricotta · fresas · nueces",
              "2 rebanadas de pan · 6 cucharadas de ricotta · fresas · nueces · 1 huevo"],
 "dica": "La ricotta es un queso magro y cremoso rico en proteína — mata el antojo de algo dulce sin la crema pesada de los rellenos de tienda. La fresa aporta dulzor y frescura, y 1 cucharadita de miel endulza lo suficiente sin convertir tu desayuno en una bomba de azúcar.",
},
{
 "nome": "Avena tibia con cacao y plátano",
 "hook": "El sabor a chocolate en el desayuno, sin azúcar y sin culpa.",
 "tempo": "8 min", "rende": "1 porción", "kcal_base": 350,
 "ings": ["40 g de avena en hojuelas", "200 ml de leche (o bebida vegetal)",
          "1 cucharada de cacao en polvo 100 %", "1 plátano",
          "canela al gusto", "endulzante o 1 cucharadita de miel (opcional)"],
 "passos": [
   "En una olla pequeña, mezcla la avena, la leche y el cacao en polvo antes de prender el fuego — así el cacao se disuelve sin grumos.",
   "Cocina a fuego medio-bajo, revolviendo todo el tiempo.",
   "Aplasta la mitad del plátano y agrégala a la olla; deja la otra mitad en rebanadas.",
   "Cocina de 4 a 5 minutos, hasta que espese y quede cremosa.",
   "Pruébala y ajusta el dulzor con endulzante o 1 cucharadita de miel, si lo necesitas.",
   "Sirve en un tazón con las rebanadas de plátano y una pizca de canela encima."],
 "porcoes8": ["30 g de avena · 180 ml de leche · 1 cucharada de cacao · ½ plátano",
              "40 g de avena · 200 ml de leche · 1 cucharada de cacao · 1 plátano",
              "45 g de avena · 200 ml de leche · 1 cucharada de cacao · 1 plátano",
              "50 g de avena · 220 ml de leche · 1 cucharada de cacao · 1 plátano · nueces",
              "50 g de avena · 220 ml de leche · cacao · 1 plátano · 1 cucharadita de crema de cacahuate",
              "55 g de avena · 250 ml de leche · cacao · 1 plátano · 1 cucharada de crema de cacahuate",
              "60 g de avena · 250 ml de leche · cacao · 1 plátano · crema de cacahuate",
              "70 g de avena · 300 ml de leche · cacao · 1 plátano · crema de cacahuate"],
 "dica": "El cacao 100 % te da el sabor a chocolate sin el azúcar del chocolate en polvo — y encima tiene antioxidantes. Matar el antojo de dulce en el desayuno evita el ataque a la barra de chocolate más tarde, que es donde muchas dietas se caen.",
},
{
 "nome": "Omelette de champiñones y espinaca",
 "hook": "Con sabor a tierra y muy sabroso, llena el plato de nutrientes por muy pocas calorías.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 260,
 "ings": ["2 huevos", "1 puñado de champiñones en rebanadas",
          "1 puñado de espinaca", "1 cucharadita de aceite de oliva",
          "sal, pimienta y ajo picado al gusto"],
 "passos": [
   "Rebana los champiñones y lava la espinaca.",
   "Calienta el aceite de oliva en un sartén antiadherente a fuego medio-alto. Fríe los champiñones en un poco de aceite de 3 a 4 minutos, sin revolver mucho, hasta que se doren y suelten su agua.",
   "Agrega el ajo y la espinaca y revuelve 1 minuto, solo hasta que se marchite (las hojas se ponen suaves). Sazona con sal y pimienta.",
   "Bate los huevos en un tazón y viértelos sobre las verduras. Baja el fuego.",
   "Deja que la base cuaje 1 o 2 minutos, dobla el omelette a la mitad y sirve."],
 "porcoes8": ["1 huevo + 1 clara · verduras, todo lo que quieras",
              "2 huevos · verduras, todo lo que quieras",
              "2 huevos · verduras · ½ rebanada de pan",
              "2 huevos · verduras · 1 rebanada de pan",
              "3 huevos · verduras · 1 rebanada de pan",
              "3 huevos · verduras · 2 rebanadas de pan",
              "3 huevos · verduras · 2 rebanadas de pan · queso",
              "4 huevos · verduras · 2 rebanadas de pan · queso"],
 "dica": "Los champiñones y la espinaca aportan volumen, sabor y nutrientes por casi nada de calorías — llenas el plato y el estómago. Los huevos lo completan con proteína saciante, formando una comida generosa que aun así entra cómodamente en tu dieta.",
},
{
 "nome": "Yogur con granola casera y arándanos",
 "hook": "Haces la granola en casa sin azúcar y la usas toda la semana — crujiente y bien hecha.",
 "tempo": "5 min (+ granola lista)", "rende": "1 porción", "kcal_base": 330,
 "ings": ["1 vaso de yogur griego natural (unos 170 g)",
          "3 cucharadas de granola casera sin azúcar", "1 puñado de arándanos",
          "canela al gusto",
          "(granola: avena + nueces picadas + canela, horneadas a 160 °C por 15 min)"],
 "passos": [
   "Para la granola casera: mezcla avena en hojuelas con nueces picadas y canela, extiéndela en una charola y hornea a 160 °C de 12 a 15 minutos, revolviendo a la mitad del tiempo. Déjala enfriar para que quede crujiente y guárdala en un frasco.",
   "En un vaso, pon el yogur.",
   "Cúbrelo con la granola casera.",
   "Reparte los arándanos encima y termina con una pizca de canela.",
   "Sirve de inmediato, para que la granola no se ablande."],
 "porcoes8": ["120 g de yogur · 2 cucharadas de granola · arándanos",
              "170 g de yogur · 3 cucharadas de granola · arándanos",
              "170 g de yogur · 3 cucharadas de granola · arándanos",
              "200 g de yogur · 4 cucharadas de granola · arándanos",
              "200 g de yogur · 4 cucharadas de granola · arándanos",
              "250 g de yogur · 4 cucharadas de granola · arándanos",
              "250 g de yogur · 5 cucharadas de granola · arándanos",
              "300 g de yogur · 6 cucharadas de granola · arándanos"],
 "dica": "La granola de tienda suele venir llena de azúcar y aceite — hacerla en casa elimina eso y tú controlas lo que lleva. Con yogur griego rico en proteína y arándanos, se vuelve un desayuno crujiente y saciante sin los azúcares escondidos de las versiones industriales.",
},
{
 "nome": "Wrap integral con huevos revueltos y verduras",
 "hook": "Lo enrollas y te vas — el desayuno para quien sale corriendo y aun así se niega a comer mal.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 340,
 "ings": ["1 tortilla integral / wrap", "2 huevos", "½ jitomate, picado",
          "1 puñado de espinaca", "1 cucharada de queso rallado",
          "sal, pimienta y aceite en aerosol"],
 "passos": [
   "Pica el jitomate y resérvalo. Lava la espinaca.",
   "Bate los huevos con sal y pimienta. Calienta el sartén con aceite en aerosol a fuego medio.",
   "Agrega la espinaca y el jitomate 1 minuto, luego vierte los huevos y revuelve hasta que formen huevos revueltos cremosos.",
   "Calienta la tortilla 20 segundos de cada lado en un sartén seco, solo para suavizarla.",
   "Pon los huevos en el centro de la tortilla, espolvorea el queso y dobla los lados hacia adentro.",
   "Enróllala apretada como un burrito y córtala a la mitad. Puedes comerla en la mano, sobre la marcha."],
 "porcoes8": ["1 wrap · 1 huevo + 1 clara · verduras",
              "1 wrap · 2 huevos · verduras · queso",
              "1 wrap · 2 huevos · verduras · queso",
              "1 wrap · 2 huevos · verduras · ¼ aguacate",
              "1 wrap · 3 huevos · verduras · queso",
              "1 wrap grande · 3 huevos · verduras · queso · ¼ aguacate",
              "1 wrap grande · 3 huevos · verduras · queso · ½ aguacate",
              "1 wrap grande · 4 huevos · verduras · queso · ½ aguacate"],
 "dica": "Poder llevarte el desayuno en la mano es lo que evita que te saltes la comida en un día ocupado. Relleno de huevo y verduras, este wrap te da proteína y fibra en un formato práctico — mucho mejor que resolver el hambre en una panadería con un pan dulce.",
},
{
 "nome": "Panqueques de manzana y canela",
 "hook": "Huele a pay de manzana y entra en tu dieta — el consuelo de un desayuno dulce sin sabotear tu día.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["40 g de avena en hojuelas", "1 huevo", "½ manzana, rallada",
          "canela al gusto", "1 pizca de polvo para hornear", "aceite en aerosol",
          "½ manzana en rebanadas delgadas para encima"],
 "passos": [
   "Ralla la mitad de la manzana por el lado grueso del rallador y deja la otra mitad en rebanadas.",
   "En un tazón, mezcla la avena, el huevo, la manzana rallada, la canela y el polvo para hornear hasta que todo quede bien mezclado.",
   "Deja reposar 3 minutos para que la avena absorba la humedad.",
   "Calienta el sartén antiadherente a fuego medio-bajo y rocíalo con aceite.",
   "Haz panqueques pequeños, dejándolos de 2 a 3 minutos de cada lado.",
   "Mientras tanto, dora las rebanadas de manzana en el mismo sartén con una pizca de canela. Sírvelas sobre los panqueques."],
 "porcoes8": ["30 g de avena · 1 huevo · ½ manzana",
              "40 g de avena · 1 huevo · ½ manzana",
              "45 g de avena · 1 huevo · ½ manzana · nueces",
              "50 g de avena · 1 huevo · 1 manzana · nueces",
              "50 g de avena · 2 huevos · 1 manzana",
              "55 g de avena · 2 huevos · 1 manzana · nueces",
              "60 g de avena · 2 huevos · 1 manzana · nueces",
              "70 g de avena · 2 huevos · 1 manzana · 1 cucharada de crema de cacahuate"],
 "dica": "La manzana aporta dulzor y fibra, y la canela levanta el sabor sin una pizca de azúcar — hay estudios que sugieren que incluso puede ayudar a controlar el apetito. Esta es la versión que mata el antojo de pay dulce sin los carbohidratos refinados que te hacen subir de peso.",
},
{
 "nome": "Pan integral tostado con crema de cacahuate y plátano",
 "hook": "El clásico de 5 minutos que combina energía, grasa buena y dulzor natural.",
 "tempo": "5 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["1 rebanada de pan integral", "1 cucharada de crema de cacahuate",
          "1 plátano en rebanadas", "canela al gusto",
          "1 pizca de semillas de chía (opcional)"],
 "passos": [
   "Tuesta la rebanada de pan hasta que quede firme.",
   "Unta la crema de cacahuate sobre el pan tostado mientras sigue caliente — se derrite un poco y se unta más fácil.",
   "Cúbrelo con las rebanadas de plátano.",
   "Espolvorea canela y, si quieres, las semillas de chía encima.",
   "Sirve de inmediato. Para llevártelo, córtalo a la mitad y ármalo como sándwich."],
 "porcoes8": ["½ rebanada de pan · 1 cucharadita de crema de cacahuate · ½ plátano",
              "1 rebanada de pan · 1 cucharada de crema de cacahuate · 1 plátano",
              "1 rebanada de pan · 1 cucharada de crema de cacahuate · 1 plátano · chía",
              "1 rebanada de pan · 1,5 cucharadas de crema de cacahuate · 1 plátano",
              "1 rebanada de pan · 1,5 cucharadas de crema de cacahuate · 1 plátano · 1 huevo cocido",
              "2 rebanadas de pan · 2 cucharadas de crema de cacahuate · 1 plátano",
              "2 rebanadas de pan · 2 cucharadas de crema de cacahuate · 1 plátano · 1 huevo",
              "2 rebanadas de pan · 2,5 cucharadas de crema de cacahuate · 1 plátano · 1 huevo"],
 "dica": "La crema de cacahuate tiene grasa buena y proteína, que te mantienen satisfecha por mucho tiempo — pero es alta en calorías, así que la cantidad importa: 1 cucharada ya es suficiente. Sobre pan integral con plátano, obtienes energía pareja para toda la mañana, sin el pico de azúcar y la caída.",
},
{
 "nome": "Huevos poché con espárragos y pan tostado",
 "hook": "Tan elegante como un desayuno de restaurante, tan simple como para un día cualquiera.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["2 huevos", "1 puñado de espárragos", "1 rebanada de pan integral",
          "1 cucharadita de vinagre (para el agua)",
          "sal, pimienta y aceite de oliva al gusto"],
 "passos": [
   "Lava los espárragos y corta la base dura. Cuécelos en agua hirviendo con sal 3 minutos, escúrrelos y resérvalos.",
   "En una olla, calienta agua hasta que esté casi hirviendo (con burbujas pequeñas, sin hervir fuerte) y agrega el vinagre.",
   "Rompe cada huevo en una taza. Haz un remolino en el agua con una cuchara y desliza el huevo muy despacio en el centro — el movimiento envuelve la clara alrededor de la yema.",
   "Cocina 3 minutos para una yema suave. Sácalo con una espumadera y déjalo sobre una servilleta de papel.",
   "Tuesta el pan. Ármalo con los espárragos abajo, los huevos poché encima, un poco de aceite de oliva, sal y pimienta."],
 "porcoes8": ["1 huevo · espárragos · ½ rebanada de pan",
              "2 huevos · espárragos · 1 rebanada de pan",
              "2 huevos · espárragos · 1 rebanada de pan · queso",
              "2 huevos · espárragos · 1 rebanada de pan · ¼ aguacate",
              "3 huevos · espárragos · 1 rebanada de pan",
              "3 huevos · espárragos · 2 rebanadas de pan",
              "3 huevos · espárragos · 2 rebanadas de pan · ¼ aguacate",
              "4 huevos · espárragos · 2 rebanadas de pan · ¼ aguacate"],
 "dica": "Un huevo poché se cocina solo en agua, sin aceite, lo que mantiene bajas las calorías. Los espárragos son ricos en fibra y agua y prácticamente no tienen calorías — un desayuno que se ve sofisticado y aun así juega a favor de la báscula.",
},
{
 "nome": "Avena con pera y nueces",
 "hook": "Cremosa, endulzada apenas por la pera y con el crujido de las nueces.",
 "tempo": "8 min", "rende": "1 porción", "kcal_base": 350,
 "ings": ["40 g de avena en hojuelas", "200 ml de leche (o bebida vegetal)",
          "½ pera, picada", "3 nueces, picadas", "canela al gusto",
          "1 cucharadita de miel (opcional)"],
 "passos": [
   "En una olla pequeña, pon la avena y la leche y cocina a fuego medio-bajo, revolviendo.",
   "Después de 3 minutos, agrega la mitad de la pera picada y cocina 2 minutos más, hasta que espese.",
   "Apaga el fuego y agrega la canela.",
   "Sirve en un tazón y corona con el resto de la pera fresca y las nueces picadas.",
   "Si lo necesitas, endúlzala con 1 cucharadita de miel."],
 "porcoes8": ["30 g de avena · 180 ml de leche · ½ pera · 2 nueces",
              "40 g de avena · 200 ml de leche · ½ pera · 3 nueces",
              "45 g de avena · 200 ml de leche · ½ pera · 3 nueces",
              "50 g de avena · 220 ml de leche · 1 pera · 3 nueces",
              "50 g de avena · 220 ml de leche · 1 pera · 4 nueces",
              "55 g de avena · 250 ml de leche · 1 pera · 4 nueces",
              "60 g de avena · 250 ml de leche · 1 pera · 5 nueces",
              "70 g de avena · 300 ml de leche · 1 pera · 5 nueces"],
 "dica": "La pera es rica en fibra y endulza de forma natural, así que no necesitas azúcar. Las nueces tienen grasa buena que aporta saciedad y textura crujiente — pero son altas en calorías, así que unas cuantas ya cumplen su función sin disparar las calorías de tu desayuno.",
},
{
 "nome": "Yogur griego con durazno y almendras",
 "hook": "Cremoso y apenas dulce por el durazno, con el crujido de las almendras — listo en 3 minutos.",
 "tempo": "3 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["1 vaso de yogur griego natural (unos 170 g)",
          "1 durazno en rebanadas (o ½ lata sin almíbar)",
          "1 cucharada de almendras en hojuelas", "canela al gusto",
          "1 cucharadita de miel (opcional)"],
 "passos": [
   "Si el durazno es fresco, lávalo y córtalo en rebanadas delgadas. Si es de lata, elige uno sin almíbar azucarado y escúrrelo bien.",
   "Pon el yogur en un vaso.",
   "Acomoda las rebanadas de durazno encima.",
   "Espolvorea las almendras en hojuelas y la canela.",
   "Si necesitas más dulzor, agrega 1 cucharadita de miel. Sirve de inmediato."],
 "porcoes8": ["120 g de yogur · durazno · ½ cucharada de almendras",
              "170 g de yogur · durazno · 1 cucharada de almendras",
              "170 g de yogur · durazno · 1 cucharada de almendras · miel",
              "200 g de yogur · durazno · 1 cucharada de almendras · 2 cucharadas de avena",
              "200 g de yogur · durazno · 1,5 cucharadas de almendras · 2 cucharadas de avena",
              "250 g de yogur · durazno · 1,5 cucharadas de almendras · 3 cucharadas de avena",
              "250 g de yogur · durazno · 2 cucharadas de almendras · 3 cucharadas de avena",
              "300 g de yogur · durazno · 2 cucharadas de almendras · 4 cucharadas de avena"],
 "dica": "El durazno es dulce y bajo en calorías, lo que satisface el antojo de azúcar de forma ligera. Con yogur griego rico en proteína y un puñado de almendras, combinas proteína y grasa buena para una saciedad que te lleva hasta el mediodía.",
},
{
 "nome": "Sándwich integral de pavo y queso",
 "hook": "Salado, práctico y lleno de proteína — el desayuno rápido para quien no le gusta lo dulce en la mañana.",
 "tempo": "6 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["2 rebanadas de pan integral", "2 rebanadas de pechuga de pavo",
          "1 rebanada de queso blanco", "hojas de lechuga",
          "rebanadas de jitomate", "1 cucharadita de mostaza o queso crema light"],
 "passos": [
   "Si lo quieres caliente, calienta las rebanadas de pan en un sartén seco 1 minuto de cada lado.",
   "Unta la mostaza o el queso crema light en una rebanada de pan.",
   "Arma las capas: pavo, queso, jitomate y lechuga.",
   "Ciérralo con la otra rebanada de pan y presiónalo ligeramente.",
   "Córtalo en diagonal y sirve. Para llevártelo, envuélvelo en papel encerado."],
 "porcoes8": ["1 rebanada de pan (abierto) · 1 rebanada de pavo · queso",
              "2 rebanadas de pan · 2 rebanadas de pavo · queso",
              "2 rebanadas de pan · 2 rebanadas de pavo · queso",
              "2 rebanadas de pan · 3 rebanadas de pavo · queso · ¼ aguacate",
              "2 rebanadas de pan · 3 rebanadas de pavo · queso · 1 huevo cocido",
              "2 rebanadas de pan · 4 rebanadas de pavo · queso · 1 huevo",
              "3 rebanadas de pan · 4 rebanadas de pavo · queso · 1 huevo",
              "3 rebanadas de pan · 5 rebanadas de pavo · 2 rebanadas de queso · 1 huevo"],
 "dica": "La pechuga de pavo es una de las carnes más magras que existen, casi proteína pura, sin la grasa de los embutidos como el salami y la mortadela. Sobre pan integral con ensalada, es un desayuno salado que te sostiene con pocas calorías y sin azúcar.",
},
{
 "nome": "Omelette de verduras",
 "hook": "Colorido y lleno de sabor, aprovecha lo que tienes en el refrigerador y llena el plato.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 260,
 "ings": ["2 huevos", "¼ pimiento, picado", "¼ cebolla, picada",
          "½ jitomate, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto"],
 "passos": [
   "Pica el pimiento, la cebolla y el jitomate en cubos pequeños.",
   "Calienta el aceite de oliva en un sartén antiadherente a fuego medio. Fríe la cebolla y el pimiento en un poco de aceite, revolviendo, de 2 a 3 minutos, hasta que se suavicen.",
   "Agrega el jitomate y fríe un minuto más. Sazona con sal y pimienta.",
   "Bate los huevos y viértelos sobre las verduras. Inclina el sartén para repartirlos.",
   "Cuando la base cuaje (2 minutos), dobla el omelette a la mitad, cocina un minuto más y sirve con las hierbas."],
 "porcoes8": ["1 huevo + 1 clara · verduras, todo lo que quieras",
              "2 huevos · verduras, todo lo que quieras",
              "2 huevos · verduras · ½ rebanada de pan",
              "2 huevos · verduras · 1 rebanada de pan",
              "3 huevos · verduras · 1 rebanada de pan",
              "3 huevos · verduras · 2 rebanadas de pan",
              "3 huevos · verduras · 2 rebanadas de pan · queso",
              "4 huevos · verduras · 2 rebanadas de pan · queso"],
 "dica": "Rellenar el omelette de verduras sube el volumen y la fibra por muy pocas calorías, así comes un plato generoso sin culpa. También es una forma inteligente de comer más verduras temprano en la mañana, lo que te ayuda a alcanzar tu meta de fibra del día.",
},
{
 "nome": "Smoothie verde con espinaca, plátano y manzana",
 "hook": "Verde, frío y apenas dulce — ni siquiera se siente la espinaca, pero tu cuerpo lo agradece.",
 "tempo": "5 min", "rende": "1 porción", "kcal_base": 250,
 "ings": ["1 puñado grande de espinaca", "½ plátano", "½ manzana",
          "200 ml de agua fría (o leche vegetal)", "1 cucharada de avena",
          "jugo de ½ limón", "hielo al gusto"],
 "passos": [
   "Lava bien la espinaca.",
   "En la licuadora, pon primero el líquido y después la espinaca — licuar las hojas con el líquido primero evita que queden trocitos.",
   "Licúa 30 segundos, hasta que la espinaca se deshaga.",
   "Agrega el plátano, la manzana (sin semillas), la avena, el jugo de limón y el hielo.",
   "Licúa a velocidad máxima hasta que quede terso y bien mezclado. Sirve de inmediato, bien frío."],
 "porcoes8": ["espinaca · ½ plátano · ½ manzana · 1 cucharada de avena",
              "espinaca · ½ plátano · ½ manzana · 1 cucharada de avena",
              "espinaca · 1 plátano · ½ manzana · 2 cucharadas de avena",
              "espinaca · 1 plátano · ½ manzana · 2 cucharadas de avena · yogur",
              "espinaca · 1 plátano · 1 manzana · 2 cucharadas de avena · yogur",
              "espinaca · 1 plátano · 1 manzana · 3 cucharadas de avena · yogur",
              "espinaca · 1 plátano · 1 manzana · 3 cucharadas de avena · yogur · nueces",
              "espinaca · 1 plátano · 1 manzana · 4 cucharadas de avena · yogur · nueces"],
 "dica": "Licuar la espinaca con fruta es una forma indolora de comer hojas verdes en la mañana — el sabor dulce del plátano y la manzana esconde lo verde. Es ligero en calorías y rico en agua y fibra, ideal para empezar el día hidratada y satisfecha.",
},
{
 "nome": "Huevos revueltos con champiñones y queso",
 "hook": "Cremosos y reconfortantes, el desayuno salado que te sostiene con sabor a comida de verdad.",
 "tempo": "9 min", "rende": "1 porción", "kcal_base": 300,
 "ings": ["2 huevos", "1 puñado de champiñones en rebanadas",
          "1 cucharada de queso rallado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y cebollín al gusto"],
 "passos": [
   "Rebana los champiñones. Calienta el aceite de oliva en un sartén a fuego medio-alto y dora los champiñones de 3 a 4 minutos.",
   "Bate los huevos con sal y pimienta.",
   "Baja el fuego, vierte los huevos sobre los champiñones y déjalos 30 segundos sin tocarlos.",
   "Empújalos suavemente desde el fondo hacia el centro con la espátula, formando huevos cremosos.",
   "Antes de que terminen de cocinarse, agrega el queso rallado y revuelve. Apaga el fuego con los huevos todavía húmedos y termina con cebollín."],
 "porcoes8": ["1 huevo + 1 clara · champiñones · queso",
              "2 huevos · champiñones · queso",
              "2 huevos · champiñones · queso · ½ rebanada de pan",
              "2 huevos · champiñones · queso · 1 rebanada de pan",
              "3 huevos · champiñones · queso · 1 rebanada de pan",
              "3 huevos · champiñones · queso · 2 rebanadas de pan",
              "3 huevos · champiñones · 2 cucharadas de queso · 2 rebanadas de pan",
              "4 huevos · champiñones · 2 cucharadas de queso · 2 rebanadas de pan"],
 "dica": "Los champiñones aportan un sabor umami que hace que la comida sepa más rica sin grasa extra. Con huevos y un toque de queso, es un desayuno cremoso y rico en proteína — mucho más saciante que un pan con mantequilla agarrado a las prisas.",
},
{
 "nome": "Panqueques de avena con arándanos",
 "hook": "Los arándanos revientan calientes dentro de la mezcla — dulzor natural, sin azúcar añadida.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 320,
 "ings": ["40 g de avena en hojuelas", "1 huevo", "½ plátano, aplastado",
          "1 puñado de arándanos", "1 pizca de polvo para hornear",
          "canela al gusto", "aceite en aerosol"],
 "passos": [
   "En un tazón, mezcla la avena, el huevo, el plátano aplastado, el polvo para hornear y la canela.",
   "Deja reposar 3 minutos para que la mezcla se ponga más firme.",
   "Agrega la mitad de los arándanos a la mezcla, con cuidado, para no aplastarlos.",
   "Calienta el sartén antiadherente a fuego medio-bajo, rocíalo con aceite y haz panqueques pequeños.",
   "Déjalos de 2 a 3 minutos de cada lado, volteándolos cuando aparezcan burbujas pequeñas.",
   "Sirve con el resto de los arándanos frescos encima."],
 "porcoes8": ["30 g de avena · 1 huevo · ½ plátano · arándanos",
              "40 g de avena · 1 huevo · ½ plátano · arándanos",
              "45 g de avena · 1 huevo · ½ plátano · arándanos",
              "50 g de avena · 1 huevo · 1 plátano · arándanos",
              "50 g de avena · 2 huevos · 1 plátano · arándanos",
              "55 g de avena · 2 huevos · 1 plátano · arándanos · nueces",
              "60 g de avena · 2 huevos · 1 plátano · arándanos · nueces",
              "70 g de avena · 2 huevos · 1 plátano · arándanos · 1 cucharada de crema de cacahuate"],
 "dica": "Los arándanos son ricos en antioxidantes y bajos en calorías, y endulzan el panqueque de forma natural. Como la base es avena, huevo y plátano — sin harina blanca y sin azúcar — obtienes un desayuno que satisface el antojo de dulce sin los ingredientes que te hacen subir de peso.",
},
{
 "nome": "Yogur con chía, miel y kiwi",
 "hook": "Refrescante y lleno de fibra, el desayuno que pone tu intestino a trabajar y al mismo tiempo te llena.",
 "tempo": "4 min", "rende": "1 porción", "kcal_base": 290,
 "ings": ["1 vaso de yogur griego natural (unos 170 g)",
          "1 cucharada de semillas de chía", "1 kiwi en rebanadas",
          "1 cucharadita de miel", "menta (opcional)"],
 "passos": [
   "En un vaso, mezcla el yogur con la chía y deja reposar 5 minutos — la chía se hincha ligeramente y espesa el yogur.",
   "Pela el kiwi y córtalo en rebanadas.",
   "Acomoda las rebanadas de kiwi sobre el yogur.",
   "Termina con el chorrito de miel y, si quieres, unas hojas de menta.",
   "Sirve frío."],
 "porcoes8": ["120 g de yogur · 1 cucharada de chía · kiwi",
              "170 g de yogur · 1 cucharada de chía · kiwi · miel",
              "170 g de yogur · 1 cucharada de chía · kiwi · miel",
              "200 g de yogur · 1 cucharada de chía · kiwi · 2 cucharadas de avena",
              "200 g de yogur · 1,5 cucharadas de chía · kiwi · 2 cucharadas de avena",
              "250 g de yogur · 1,5 cucharadas de chía · kiwi · 3 cucharadas de avena",
              "250 g de yogur · 2 cucharadas de chía · kiwi · 3 cucharadas de avena · nueces",
              "300 g de yogur · 2 cucharadas de chía · kiwi · 4 cucharadas de avena · nueces"],
 "dica": "La chía y el kiwi juntos son ricos en fibra, lo que ayuda a que tu intestino funcione y hace que la saciedad dure más. El yogur griego aporta proteína, y 1 cucharadita de miel endulza sin excederse — un desayuno ligero que además cuida tu digestión.",
},
{
 "nome": "Pan integral tostado con queso cottage y jitomate",
 "hook": "Fresco y salado, con proteína en el queso y casi nada de calorías en el jitomate.",
 "tempo": "6 min", "rende": "1 porción", "kcal_base": 250,
 "ings": ["1 rebanada de pan integral", "3 cucharadas de queso cottage",
          "1 jitomate en rebanadas",
          "orégano, sal, pimienta y aceite de oliva al gusto",
          "hojas de albahaca (opcional)"],
 "passos": [
   "Tuesta la rebanada de pan hasta que quede firme y crujiente.",
   "Unta el queso cottage sobre el pan tostado, cubriendo toda la superficie.",
   "Pon las rebanadas de jitomate encima.",
   "Sazona con una pizca de sal, pimienta, orégano y un poco de aceite de oliva.",
   "Termina con hojas de albahaca, si tienes. Sirve de inmediato."],
 "porcoes8": ["½ rebanada de pan · 2 cucharadas de queso cottage · jitomate",
              "1 rebanada de pan · 3 cucharadas de queso cottage · jitomate",
              "1 rebanada de pan · 3 cucharadas de queso cottage · jitomate · 1 huevo cocido",
              "1 rebanada de pan · 4 cucharadas de queso cottage · jitomate · 1 huevo",
              "1 rebanada de pan · 4 cucharadas de queso cottage · jitomate · 2 huevos",
              "2 rebanadas de pan · 4 cucharadas de queso cottage · jitomate · 1 huevo",
              "2 rebanadas de pan · 5 cucharadas de queso cottage · jitomate · 2 huevos",
              "2 rebanadas de pan · 6 cucharadas de queso cottage · jitomate · 2 huevos"],
 "dica": "El queso cottage es magro y rico en proteína, y mata el hambre con pocas calorías. Sobre pan integral con jitomate, se convierte en una bruschetta saludable — salada, fresca y mucho más ligera que un pan con queso crema grasoso.",
},
{
 "nome": "Bowl de avena con manzana al horno y canela",
 "hook": "El olor a manzana horneada con canela convierte una avena simple en consuelo para un día frío.",
 "tempo": "15 min", "rende": "1 porción", "kcal_base": 340,
 "ings": ["40 g de avena en hojuelas", "200 ml de leche (o bebida vegetal)",
          "1 manzana en cubos", "raja de canela o canela molida",
          "1 cucharadita de miel (opcional)", "1 cucharada de nueces (opcional)"],
 "passos": [
   "Corta la manzana en cubos, con cáscara. En un sartén antiadherente, dora los cubos a fuego medio con bastante canela de 5 a 7 minutos, revolviendo, hasta que se caramelicen (queden suaves y doraditos en el propio azúcar de la fruta).",
   "Mientras tanto, cocina la avena con la leche en una olla, revolviendo, de 4 a 5 minutos, hasta que espese.",
   "Vierte la avena en un tazón.",
   "Corona con la manzana horneada caliente.",
   "Si quieres, termina con el chorrito de miel y las nueces picadas. Sirve caliente."],
 "porcoes8": ["30 g de avena · 180 ml de leche · ½ manzana",
              "40 g de avena · 200 ml de leche · 1 manzana",
              "45 g de avena · 200 ml de leche · 1 manzana · miel",
              "50 g de avena · 220 ml de leche · 1 manzana · nueces",
              "50 g de avena · 220 ml de leche · 1 manzana · nueces",
              "55 g de avena · 250 ml de leche · 1 manzana · nueces",
              "60 g de avena · 250 ml de leche · 1 manzana · nueces",
              "70 g de avena · 300 ml de leche · 1 manzana · nueces · miel"],
 "dica": "Hornear la manzana libera su dulzor natural y realza la canela, así que no necesitas azúcar. Es un desayuno que reconforta como un postre caliente, pero con la fibra de la fruta y de la avena que detiene el hambre por horas.",
},
]
