# -*- coding: utf-8 -*-
"""35 receitas de ALMOÇO (031-065). INGLÊS (mercado US).

Tradução literal de `receitas_almoco.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "you", medidas caseiras americanas (cup/tbsp/tsp), carne e peixe
em OZ, forno em °F.
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/031-065).
porcoes8 na ordem: Mulher 120-155/156-185/186-220/220+ lb · Homem 155-185/186-220/221-265/265+ lb
Metas (kcal): 360/440/500/560 · 540/610/680/750
"""

RECEITAS = [
{
 "nome": "Grilled Chicken with Brown Rice and Broccoli",
 "hook": "The simplest plate in the world and one of the best for losing weight: lean protein, a good carb and vegetables as much as you want.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 470,
 "ings": ["1 chicken breast fillet (about 5 oz)", "4 tbsp cooked brown rice",
          "1 plate of broccoli", "1 clove of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt and pepper to taste"],
 "passos": [
   "Season the chicken on both sides with salt, pepper, the garlic and the lemon juice. Let it take in the flavor for 5 minutes.",
   "Cut the broccoli into small florets. Boil water in a pot, add the broccoli and leave it only 3 minutes, until it is bright green and tender but still firm. Drain it.",
   "Heat a nonstick pan over medium-high heat with the olive oil. Put the chicken in and leave it 4 to 5 minutes on each side, without moving it, until it is golden outside and white inside.",
   "To know if it is done, cut into the middle of the fillet: the meat has to be white all the way through, with no pink part.",
   "Warm up the already cooked brown rice. Build the plate with the rice, the sliced chicken and the broccoli on the side.",
   "If you like, drizzle the broccoli with a little olive oil and some more lemon."],
 "porcoes8": ["3.5 oz chicken · 3 tbsp rice · broccoli, as much as you want",
              "4 oz chicken · 4 tbsp rice · broccoli, as much as you want",
              "4.5 oz chicken · 5 tbsp rice · broccoli, as much as you want",
              "5 oz chicken · 5 tbsp rice · a little olive oil",
              "5 oz chicken · 5 tbsp rice · broccoli, as much as you want",
              "6 oz chicken · 6 tbsp rice · broccoli, as much as you want",
              "7 oz chicken · 7 tbsp rice · a little olive oil",
              "8 oz chicken · 8 tbsp rice · a little olive oil"],
 "dica": "Chicken breast is almost pure protein, which is very filling and helps protect your muscle while you lose fat. Brown rice has fiber and releases energy slowly, so you do not get that hunger that hits an hour later. Broccoli fills the plate with almost no calories.",
},
{
 "nome": "Tilapia Fillet with Sweet Potato Mash",
 "hook": "Light fish and a naturally sweet mash — a lunch that looks like a restaurant dish and fits your diet.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 440,
 "ings": ["1 tilapia fillet (about 5 oz)", "1 medium sweet potato", "1 tsp olive oil",
          "juice of 1/2 lemon", "chopped fresh herbs", "salt, pepper and paprika to taste",
          "green leaves for the salad"],
 "passos": [
   "Peel the sweet potato and cut it into pieces. Cook it in boiling water for 15 minutes, until it is very soft (a fork goes in with no effort). Drain it.",
   "Mash the potato while it is still hot with a fork, add a pinch of salt and half of the olive oil, and mix until it turns into a smooth mash.",
   "Season the tilapia with salt, pepper, paprika and the lemon juice.",
   "Heat a nonstick pan with the rest of the olive oil over medium heat. Put the fillet in and leave it 3 to 4 minutes on each side, turning it carefully only once, until it is golden and comes off the pan easily.",
   "Build the plate with the mash, the fillet on top and a portion of green leaves on the side. Finish with the fresh herbs."],
 "porcoes8": ["4 oz fish · 1/2 sweet potato · salad",
              "5 oz fish · 1 small sweet potato · salad",
              "5 oz fish · 1 medium sweet potato · salad",
              "6 oz fish · 1 medium sweet potato · a little olive oil",
              "6 oz fish · 1 medium sweet potato · salad",
              "7 oz fish · 1 large sweet potato · salad",
              "8 oz fish · 1 large sweet potato · a little olive oil",
              "9 oz fish · 1 large sweet potato · a little olive oil"],
 "dica": "Tilapia is a lean fish, full of protein and with very little fat. Sweet potato keeps you full for hours and, even though it is a carb, it releases energy very slowly — that is why it is the favorite of anyone who wants to lose weight without losing energy.",
},
{
 "nome": "Grilled Tuna Steak with Vegetables and Potato",
 "hook": "Fresh tuna turns into a steak from the sea: firm outside, juicy inside, and ready in a few minutes.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 450,
 "ings": ["1 fresh tuna steak (about 5 oz)", "1 small potato in slices", "1 cup of green beans and carrot",
          "1 clove of garlic, chopped", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and oregano to taste"],
 "passos": [
   "Cook the potato slices in boiling salted water for 10 minutes, until they are soft but not falling apart. Drain them.",
   "Cut the green beans into pieces and the carrot into rounds. Cook them in a steamer or in a little boiling water for 5 minutes, until they are tender but still firm.",
   "Season the tuna steak with salt, pepper, the garlic, the oregano and the lemon juice. Let it take in the flavor for 5 minutes.",
   "Heat a nonstick pan with the olive oil over high heat. Put the steak in and leave it 2 to 3 minutes on each side — tuna is great slightly pink in the center; if you prefer it well done, leave it 1 minute more on each side.",
   "Build the plate with the potato, the vegetables and the tuna steak on top. Drizzle with a little more lemon and serve."],
 "porcoes8": ["4 oz tuna · 1/2 potato · vegetables",
              "5 oz tuna · 1 small potato · vegetables",
              "5 oz tuna · 1 potato · vegetables",
              "6 oz tuna · 1 potato · a little olive oil",
              "6 oz tuna · 1 potato · vegetables",
              "7 oz tuna · 1 large potato · vegetables",
              "8 oz tuna · 1 large potato · a little olive oil",
              "9 oz tuna · 2 small potatoes · a little olive oil"],
 "dica": "Fresh tuna is one of the leanest meats from the sea: plenty of protein, omega-3 (the good fat) and very little bad fat. Grilled fast over high heat, it stays juicy with no oil, and with vegetables and a little potato it becomes a fine, light lunch.",
},
{
 "nome": "Wholegrain Wrap with Shredded Chicken",
 "hook": "A practical roll to take to work, filled with chicken and salad — it kills your hunger without weighing you down.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 wholegrain tortilla (or wholegrain flatbread)", "1 cooked and shredded chicken fillet (about 4 oz)",
          "1 tbsp plain yogurt with no sugar", "lettuce leaves", "1/2 tomato in slices",
          "grated carrot", "salt, pepper and a little mustard to taste"],
 "passos": [
   "Cook the chicken breast in salted water for about 15 minutes, until it is white inside. Let it cool a little and shred it with two forks, pulling the meat into strands.",
   "In a bowl, mix the shredded chicken with the yogurt, the mustard, salt and pepper, until it turns into a creamy filling.",
   "Warm the tortilla for 20 seconds in a pan, just so it goes soft and easy to roll.",
   "Spread the lettuce leaves in the center of the tortilla. Put the creamy chicken, the tomato and the grated carrot on top.",
   "Fold the two sides inward and roll it tight, from bottom to top. Cut it in half diagonally and serve."],
 "porcoes8": ["3.5 oz chicken · 1/2 tortilla · salad",
              "4 oz chicken · 1 tortilla · salad",
              "4.5 oz chicken · 1 tortilla · salad",
              "5 oz chicken · 1 tortilla · 1 heaped tbsp yogurt",
              "5 oz chicken · 1 tortilla · salad",
              "6 oz chicken · 1 large tortilla · salad",
              "7 oz chicken · 2 tortillas · salad",
              "8 oz chicken · 2 tortillas · salad"],
 "dica": "Swapping mayonnaise for plain yogurt cuts a good part of the calories and still adds protein. Shredded chicken spreads well and gives the feeling of a generous filling with little fat, and the wholegrain tortilla has more fiber than white bread, holding hunger back for longer.",
},
{
 "nome": "Oven-Baked Salmon with Vegetables",
 "hook": "Everything on one tray: the finest fish for your heart, browned together with colorful vegetables.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 490,
 "ings": ["1 salmon fillet (about 5 oz)", "1 small potato in slices", "1 zucchini in rounds",
          "1/2 bell pepper in strips", "cherry tomatoes", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and rosemary to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the potato into thin slices — that way it bakes in the same time as the fish.",
   "On a baking tray, spread the potato, the zucchini, the bell pepper and the cherry tomatoes. Season with salt, pepper, rosemary and half of the olive oil, and mix.",
   "Bake for 10 minutes, just so the potato starts to soften.",
   "Take the tray out, open a space in the middle and put the salmon in. Season the fish with salt, pepper, the lemon juice and the rest of the olive oil.",
   "Put it back in the oven for another 15 minutes, until the salmon turns lighter in color and flakes apart when you poke it with a fork. Serve it straight from the tray or plated."],
 "porcoes8": ["4 oz salmon · 1/2 potato · vegetables",
              "5 oz salmon · 1 small potato · vegetables",
              "5 oz salmon · 1 potato · vegetables",
              "6 oz salmon · 1 potato · a little olive oil",
              "6 oz salmon · 1 potato · vegetables",
              "7 oz salmon · 1 large potato · vegetables",
              "8 oz salmon · 1 large potato · a little olive oil",
              "9 oz salmon · 2 small potatoes · a little olive oil"],
 "dica": "Salmon is rich in good fat (omega-3), which helps your heart and also keeps you very full. Baking everything together on the same tray uses almost no oil and leaves the vegetables with a concentrated flavor — a complete, pretty and light plate with the least effort.",
},
{
 "nome": "Sweet Potato Shepherd's Pie with Lean Ground Beef",
 "hook": "The comfort of a creamy shepherd's pie, but with sweet potato mash and lean meat — pure satisfaction, no guilt.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 460,
 "ings": ["2 medium sweet potatoes", "9 oz lean ground beef", "1 onion, chopped",
          "1 clove of garlic, chopped", "1 tomato, chopped", "1 tsp olive oil",
          "salt, pepper and fresh herbs to taste", "1 tbsp grated low-fat cheese"],
 "passos": [
   "Peel the sweet potatoes, cut them into pieces and cook them in boiling water for 15 minutes, until they are very soft. Drain and mash them with a fork, with a pinch of salt, until it turns into a smooth mash.",
   "In a pan, heat the olive oil and fry the onion and the garlic over medium heat, stirring, for 2 minutes, until they turn clear.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the tomato, salt and pepper and cook for another 5 minutes, until it reduces. Turn it off and add the fresh herbs.",
   "In a baking dish, spread half of the mash on the bottom, the meat in the middle and the rest of the mash on top. Sprinkle the grated cheese.",
   "Bake at medium-high heat (400 °F) for 15 minutes, until the surface is lightly golden. Serve hot."],
 "porcoes8": ["1/2 serving · green salad",
              "1 serving · green salad",
              "1 serving · green salad",
              "1 serving · 1 more tbsp cheese",
              "1 serving + extra meat · salad",
              "1 large serving · salad",
              "1 large serving + meat · salad",
              "double portion of meat · salad"],
 "dica": "Sweet potato swaps the regular potato of the pie for a version with more fiber, which fills you up more. Lean meat gives plenty of protein without the excess fat of fatty cuts. It is the kind of comforting plate that tricks the craving for junk food.",
},
{
 "nome": "Complete Salad with Tuna, Chickpeas and Egg",
 "hook": "No stove: a real salad that fills the plate and your belly, put together in five minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 can of tuna in water, drained", "1/2 cup cooked chickpeas", "2 boiled eggs",
          "mixed green leaves", "1/2 tomato in cubes", "1/2 cucumber in rounds", "red onion in thin slices",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt and pepper to taste"],
 "passos": [
   "Cook the eggs: put them in a pot with water, bring it to a boil and count 9 minutes. Run them under cold water, peel them and cut them in half.",
   "Drain the tuna and the chickpeas well.",
   "On a plate or in a large bowl, spread the green leaves. On top, arrange the tomato, the cucumber and the onion.",
   "Put the tuna in the center, the chickpeas around it and the eggs on the sides.",
   "Drizzle with the olive oil and the lemon juice, season with salt and pepper and serve."],
 "porcoes8": ["1/2 can tuna · 1/3 cup chickpeas · 1 egg",
              "1 can tuna · 1/2 cup chickpeas · 2 eggs",
              "1 can tuna · 1/2 cup chickpeas · 2 eggs",
              "1 can tuna · 2/3 cup chickpeas · 2 eggs · avocado",
              "1 can tuna · 2/3 cup chickpeas · 2 eggs",
              "1.5 cans tuna · 3/4 cup chickpeas · 2 eggs",
              "1.5 cans tuna · 1 cup chickpeas · 3 eggs · avocado",
              "2 cans tuna · 1 cup chickpeas · 3 eggs · avocado"],
 "dica": "It is a protein bomb (tuna, egg and chickpeas together) that takes almost no work. The protein and the fiber of the salad hold hunger back for hours, and since everything is fresh and not cooked in oil, the plate stays light even when it is generous.",
},
{
 "nome": "Light Chicken Stroganoff with Rice",
 "hook": "The same creamy stroganoff, but swapping the cream for yogurt — same delight, half the calories.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 chicken breast fillets in cubes (about 10 oz)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 cup of sliced mushrooms", "1 tbsp tomato paste",
          "4 tbsp plain yogurt with no sugar", "1 tsp olive oil",
          "salt, pepper and mustard to taste", "white or brown rice to serve"],
 "passos": [
   "Season the chicken cubes with salt and pepper.",
   "Heat the olive oil in a pot over medium-high heat and brown the chicken cubes on the outside, stirring now and then, for 5 minutes. Take them out and set them aside.",
   "In the same pot, fry the onion and the garlic for 2 minutes, stirring, until they turn clear. Add the mushrooms and cook for another 3 minutes, until they wilt (go soft).",
   "Put the chicken back in the pot, add the tomato paste and the mustard, mix and leave it for 3 minutes.",
   "Turn off the heat. Only then add the yogurt and stir — off the heat it does not curdle (turn into lumps). Check the salt and serve over the rice."],
 "porcoes8": ["1/2 serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "The secret is plain yogurt instead of cream: you keep the creaminess and the flavor, but you cut fat and still gain protein. The chicken brings fullness and the mushrooms add volume and flavor with very few calories.",
},
{
 "nome": "Turkey Breast with Vegetable Couscous",
 "hook": "The couscous is ready with hot water alone — the fastest and fluffiest lunch for busy days.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["1 turkey breast fillet (about 5 oz)", "1/2 cup couscous (the small-bead kind)",
          "1/2 cup hot water", "1/2 zucchini in small cubes", "1/2 bell pepper in small cubes", "cherry tomatoes, cut",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper and mint to taste"],
 "passos": [
   "Put the couscous in a bowl, add a pinch of salt and the hot water (the water should cover the couscous by about a finger). Cover it with a plate and leave it 5 minutes.",
   "Loosen the couscous with a fork, going through the whole bowl, until it is fluffy and not sticking together.",
   "Season the turkey breast with salt and pepper. Heat a nonstick pan with half of the olive oil and grill the turkey for 3 to 4 minutes on each side, until it is golden and white inside.",
   "Add to the couscous the raw cubes of zucchini, bell pepper and tomato, the rest of the olive oil, the lemon juice and the mint. Mix.",
   "Serve the couscous with the sliced turkey breast on top."],
 "porcoes8": ["4 oz turkey · 1/3 cup couscous · vegetables",
              "5 oz turkey · 1/2 cup couscous · vegetables",
              "5 oz turkey · 1/2 cup couscous · vegetables",
              "6 oz turkey · 2/3 cup couscous · a little olive oil",
              "6 oz turkey · 2/3 cup couscous · vegetables",
              "7 oz turkey · 3/4 cup couscous · vegetables",
              "8 oz turkey · 1 cup couscous · a little olive oil",
              "9 oz turkey · 1 cup couscous · a little olive oil"],
 "dica": "Turkey breast is even leaner than chicken and full of protein. Couscous cooks with hot water alone, with no fat, and mixed with raw vegetables it becomes a light, colorful and refreshing plate — perfect for lunch.",
},
{
 "nome": "Beef Chili with Black Beans",
 "hook": "A spicy, hearty stew that warms your soul — beans, lean meat and lots of flavor in one pot.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 450,
 "ings": ["10 oz lean ground beef", "1 cup cooked black beans (or canned, drained)",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 bell pepper, chopped", "2 tomatoes, chopped (or tomato sauce)",
          "1 tsp olive oil", "1 tsp ground cumin", "salt, pepper and paprika to taste"],
 "passos": [
   "Heat the olive oil in a pot over medium heat. Fry the onion, the garlic and the bell pepper for 3 minutes, stirring, until they soften.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the cumin, the paprika, salt and pepper and mix well, so the spices release their aroma.",
   "Add the chopped tomatoes and the black beans. If it gets too dry, add half a cup of water.",
   "Turn the heat down and let it cook over low heat for 15 to 20 minutes, stirring now and then, until it thickens into a creamy stew. Serve it on its own or with a little rice."],
 "porcoes8": ["1/2 serving · salad",
              "1 serving · salad",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "1 large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "Black beans are champions in fiber and plant protein, and together with the lean meat they make the plate very filling with few calories. It is a stew that goes a long way, keeps well in the fridge and kills the craving for warm, well-seasoned food without going off track.",
},
{
 "nome": "Wholewheat Pasta in Tomato Sauce with Turkey Meatballs",
 "hook": "Yes, you can eat pasta and still lose weight — in the wholewheat version, with fresh sauce and lean meatballs.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 480,
 "ings": ["5 oz wholewheat pasta (dry weight)", "9 oz ground turkey breast (or ground chicken)",
          "3 ripe tomatoes, chopped (or tomato sauce)", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 egg", "2 tbsp oats", "1 tsp olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "In a bowl, mix the ground turkey, the egg, the oats, half of the garlic, salt and pepper. Knead it with your hands until it holds together and roll balls the size of a walnut.",
   "Heat the olive oil in a wide pot and brown the meatballs on all sides, turning them carefully, for about 5 minutes. Take them out and set them aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the chopped tomatoes, salt and pepper and cook for 10 minutes, stirring, until it turns into a sauce.",
   "Put the meatballs back into the sauce and let them cook for another 8 minutes, until they are done inside.",
   "Meanwhile, cook the pasta in boiling salted water for the time on the package, until it is cooked but still firm. Drain it.",
   "Mix the pasta into the sauce with the meatballs, sprinkle the basil and serve."],
 "porcoes8": ["2/3 serving pasta · 3 meatballs",
              "1 serving · 4 meatballs",
              "1 serving · 4 meatballs",
              "1 serving · 5 meatballs",
              "1 serving · 5 meatballs",
              "1 large serving · 6 meatballs",
              "large serving · 7 meatballs",
              "double serving · 8 meatballs"],
 "dica": "Wholewheat pasta has more fiber and fills you up more than the regular kind, and turkey meatballs give lean protein instead of fatty meat. A tomato sauce made fresh, with no sugar and nothing processed, keeps the plate tasty and much lighter.",
},
{
 "nome": "Omelette Filled with Vegetables",
 "hook": "A light lunch for days with no time: fluffy, warm and full of protein, ready in the pan in ten minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 360,
 "ings": ["3 eggs", "1/2 tomato in small cubes", "1/2 bell pepper in small cubes", "a handful of spinach",
          "1 tbsp white cheese in cubes", "1 tsp olive oil",
          "chives, salt and pepper to taste", "1 slice of wholegrain bread (optional)"],
 "passos": [
   "Crack the eggs into a bowl, season with salt and pepper and beat them with a fork for 30 seconds, until they are even (well mixed).",
   "Heat the olive oil in a nonstick pan over medium-low heat. Add the bell pepper and the spinach and stir for 1 minute, just until the spinach wilts (goes soft).",
   "Spread the vegetables around the pan and pour the eggs on top. Leave it 1 minute without stirring, until the edge sets.",
   "Put the tomato and the cheese over half of the omelette. With a spatula, fold the other half on top, making a half-moon.",
   "Leave it another minute, just until the cheese softens. Sprinkle chives and serve, with the slice of bread if you like."],
 "porcoes8": ["2 eggs · vegetables · 1/2 bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · 2 tbsp cheese · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "4 eggs · vegetables · 1 slice bread",
              "4 eggs · 2 tbsp cheese · 2 slices bread",
              "5 eggs · vegetables · 2 slices bread"],
 "dica": "Eggs are a very high quality protein and very filling — people who eat eggs at lunch usually snack less in the afternoon. Filled with vegetables, the omelette gains volume, color and fiber with almost no extra calories, becoming a complete and quick meal.",
},
{
 "nome": "Lean Beef Steak with Rice, Beans and Collard Greens",
 "hook": "The everyday plate, the way we love it — only in the right measure, with lean meat and lightly sautéed collard greens.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["1 lean beef steak (about 4.5 oz)", "4 tbsp cooked rice",
          "4 tbsp cooked beans", "2 collard green leaves cut into thin strips",
          "1 clove of garlic, chopped", "1 tsp olive oil", "salt and pepper to taste"],
 "passos": [
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Put the steak in and leave it 2 to 3 minutes on each side, without moving it, until it is golden outside and done the way you like inside.",
   "Cut the collard greens into very thin strips. In a pan, heat the rest of the olive oil and fry the garlic for 30 seconds, just until it smells good.",
   "Add the collard greens and stir over high heat for 1 to 2 minutes, just until they wilt a little (go softer) and stay green. Season with salt.",
   "Warm up the rice and the beans. Build the plate with the rice, the beans, the steak and the collard greens on the side."],
 "porcoes8": ["3.5 oz meat · 3 tbsp rice · 3 tbsp beans",
              "4.5 oz meat · 4 tbsp rice · 4 tbsp beans",
              "4.5 oz meat · 5 tbsp rice · 4 tbsp beans",
              "5 oz meat · 5 tbsp rice · 5 tbsp beans",
              "5 oz meat · 5 tbsp rice · 5 tbsp beans",
              "6 oz meat · 6 tbsp rice · 5 tbsp beans",
              "7 oz meat · 7 tbsp rice · 6 tbsp beans",
              "8 oz meat · 8 tbsp rice · 6 tbsp beans"],
 "dica": "You can eat the traditional plate of rice, beans and meat without leaving your diet: the key is choosing a lean cut, measuring the rice and the beans and being generous with the collard greens, which fill the plate with fiber and almost no calories. The beans also bring fiber and protein that hold hunger back.",
},
{
 "nome": "Steak with Onions, Mashed Potato and Salad",
 "hook": "Steak with golden onions is pure comfort — over a light mash and beside a fresh salad, it fits your diet just right.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["1 lean beef steak (about 4.5 oz)", "2 medium potatoes", "1 onion in slices",
          "1 tsp olive oil", "salt and pepper to taste", "green leaves and tomato for the salad",
          "juice of 1/2 lemon"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until they are very soft. Drain and mash them with a fork, with a pinch of salt, until it turns into a smooth mash. If you want it creamier, add a little of the cooking water.",
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Put the steak in and leave it 2 to 3 minutes on each side, without moving it, until it is golden outside and done the way you like. Take it out and set it aside.",
   "In the same pan, put the onion slices and the rest of the olive oil. Stir over medium heat for 5 minutes, until the onion is soft and golden (nice and sweet).",
   "Cover the steak with the golden onions. Build the plate with the mash, the steak with onions and a green salad dressed with lemon."],
 "porcoes8": ["3.5 oz meat · 1/2 serving mash · salad",
              "4.5 oz meat · 1 serving mash · salad",
              "4.5 oz meat · 1 serving mash · salad",
              "5 oz meat · 1 serving mash · salad",
              "5 oz meat · 1 serving mash · salad",
              "6 oz meat · 1 large serving mash · salad",
              "7 oz meat · large serving mash · salad",
              "8 oz meat · double serving mash · salad"],
 "dica": "Choosing a lean cut and grilling it with no oil turns the steak into almost pure protein. Golden onions bring a lot of flavor with very few calories and mean you do not need greasy sauces. With the mash in the right measure and plenty of salad, the plate satisfies without weighing you down.",
},
{
 "nome": "Sautéed Shrimp with Vegetables and Rice",
 "hook": "Shrimp is ready in the blink of an eye and is as light as it gets — a quick lunch that looks sophisticated.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["5 oz cleaned shrimp", "4 tbsp cooked brown rice", "1/2 zucchini in half-moons",
          "1/2 bell pepper in strips", "1 clove of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the shrimp with salt, pepper, the garlic and the lemon juice. Let it take in the flavor for 5 minutes.",
   "Heat a large pan with half of the olive oil over high heat. Add the zucchini and the bell pepper and stir for 3 minutes, until they are tender but still firm. Take them out and set them aside.",
   "In the same pan, put the rest of the olive oil and the shrimp. Sauté (stir over high heat) for 2 to 3 minutes, just until the shrimp turns pink and curls up. Be careful not to overcook it, or it goes rubbery.",
   "Put the vegetables back in the pan, add the already cooked brown rice and mix for 1 minute, just to warm everything through.",
   "Sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · 3 tbsp rice · vegetables",
              "5 oz shrimp · 4 tbsp rice · vegetables",
              "5 oz shrimp · 5 tbsp rice · vegetables",
              "6 oz shrimp · 5 tbsp rice · a little olive oil",
              "6 oz shrimp · 5 tbsp rice · vegetables",
              "7 oz shrimp · 6 tbsp rice · vegetables",
              "8 oz shrimp · 7 tbsp rice · a little olive oil",
              "9 oz shrimp · 8 tbsp rice · a little olive oil"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories, so you can eat a generous portion without weighing yourself down. Sautéed fast over high heat with vegetables, it keeps a firm texture and its flavor, in a light plate that is ready in minutes.",
},
{
 "nome": "Light Chicken Stir-Fry with Brown Rice",
 "hook": "The Chinese classic at home, in the lean version: cubed chicken and crisp vegetables in a light, glossy sauce.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 460,
 "ings": ["2 chicken breast fillets in cubes (about 10 oz)", "1 bell pepper in cubes", "1 onion in cubes",
          "1 celery stalk in pieces (optional)", "1 clove of garlic, chopped", "1 tbsp light soy sauce",
          "1 tsp cornstarch", "1 tsp olive oil", "brown rice to serve"],
 "passos": [
   "Season the chicken cubes with a little of the soy sauce and the garlic. Let them take in the flavor for 5 minutes.",
   "Dissolve the cornstarch in half a cup of water with the rest of the soy sauce. Mix well and set it aside — that is what will thicken the sauce.",
   "Heat a large pan with half of the olive oil over high heat. Brown the chicken cubes for 5 minutes, stirring, until they are white inside. Take them out and set them aside.",
   "In the same pan, put the rest of the olive oil and add the bell pepper, the onion and the celery. Stir over high heat for 3 minutes, until they are tender but still crisp.",
   "Put the chicken back, stir the cornstarch mixture and pour it into the pan. Stir for 1 to 2 minutes, until the sauce thickens and turns glossy, coating everything. Serve over the brown rice."],
 "porcoes8": ["1/2 serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Making it at home lets you control the oil and the sugar that restaurants overdo. The chicken gives lean protein, the vegetables come in crisp with few calories and just a touch of starch gives that pretty sauce without fattening the plate.",
},
{
 "nome": "Mexican Bowl with Beef, Black Beans and Corn",
 "hook": "All the colors and flavors of Mexico in one bowl — generous, well seasoned and surprisingly light.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 490,
 "ings": ["9 oz lean ground beef", "1 cup cooked black beans", "1/2 cup corn",
          "4 tbsp cooked rice", "1 tomato in cubes", "1/2 avocado in slices",
          "green leaves", "1 clove of garlic, chopped", "1 tsp olive oil",
          "cumin, salt, pepper and coriander to taste", "juice of 1/2 lemon"],
 "passos": [
   "Heat the olive oil in a pan and fry the garlic for 30 seconds. Add the ground beef and stir, breaking up the pieces, until it loses its pink color.",
   "Season the meat with cumin, salt and pepper and cook for another 3 minutes. Add the black beans and the corn and warm through for 2 minutes.",
   "In a bowl, make a bed of green leaves and put the rice on one side.",
   "Arrange on top the meat with beans and corn, the tomato and the avocado slices.",
   "Drizzle with the lemon juice, sprinkle coriander and serve."],
 "porcoes8": ["1/2 serving · 3 tbsp rice · 1/4 avocado",
              "1 serving · 4 tbsp rice · 1/4 avocado",
              "1 serving · 4 tbsp rice · 1/2 avocado",
              "1 serving · 5 tbsp rice · 1/2 avocado",
              "1 serving · 5 tbsp rice · 1/2 avocado",
              "1 large serving · 6 tbsp rice · 1/2 avocado",
              "large serving · 7 tbsp rice · 1/2 avocado",
              "double serving · 8 tbsp rice · avocado"],
 "dica": "It is a complete plate in a single bowl: protein from the meat, fiber from the beans and the corn, and the good fat of the avocado, which brings creaminess and fullness. Well seasoned, it satisfies the craving for bar food without the excess fat.",
},
{
 "nome": "Grilled Chicken Salad with Mango",
 "hook": "Sweet, savory and refreshing: the warm grilled chicken meets the sweet mango in a salad that does not feel like a diet.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 chicken breast fillet (about 4.5 oz)", "mixed green leaves", "1/2 mango in cubes",
          "1/2 cucumber in rounds", "red onion in thin slices", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and mint to taste"],
 "passos": [
   "Season the chicken with salt and pepper. Heat a nonstick pan over medium-high heat and grill the fillet for 4 to 5 minutes on each side, until it is golden and white inside. Let it cool a little and cut it into strips.",
   "Peel the mango and cut the flesh into cubes. Cut the cucumber into rounds and the onion into very thin slices.",
   "In a large bowl or deep plate, spread the green leaves.",
   "Arrange on top the mango cubes, the cucumber, the onion and the chicken strips.",
   "Make the dressing by mixing the olive oil, the lemon juice, salt and pepper. Drizzle it over the salad, sprinkle mint and serve."],
 "porcoes8": ["3.5 oz chicken · 1/4 mango · salad",
              "4.5 oz chicken · 1/2 mango · salad",
              "4.5 oz chicken · 1/2 mango · salad",
              "5 oz chicken · 1/2 mango · a little olive oil",
              "5 oz chicken · 1/2 mango · salad",
              "6 oz chicken · 1/2 mango · 1 tbsp nuts",
              "7 oz chicken · 1 mango · nuts",
              "8 oz chicken · 1 mango · nuts"],
 "dica": "The mango comes in as a natural sweet, with no added sugar, and satisfies the craving for something sweet inside a savory meal. The grilled chicken gives the protein that fills you up, and the volume of leaves and vegetables fills the plate with very few calories. A salad that is a complete meal.",
},
{
 "nome": "Chicken Fillet in Light Curry with Rice",
 "hook": "A golden, fragrant sauce that transforms the usual chicken — creamy with no cream, using light coconut milk.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 chicken breast fillets in cubes (about 10 oz)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp curry powder", "1/2 cup light coconut milk (or regular milk)",
          "1 tomato, chopped", "1 tsp olive oil", "salt and pepper to taste", "rice to serve"],
 "passos": [
   "Season the chicken cubes with salt, pepper and half of the curry.",
   "Heat the olive oil in a pot over medium heat and brown the chicken cubes on the outside, stirring, for 5 minutes. Take them out and set them aside.",
   "In the same pot, fry the onion and the garlic for 2 minutes. Add the rest of the curry and stir for 30 seconds, just so the spice releases its smell.",
   "Add the tomato and cook for 3 minutes, until it breaks down. Put the chicken back and add the coconut milk.",
   "Cook over low heat for 8 to 10 minutes, stirring now and then, until the sauce thickens and the chicken is tender. Serve over the rice."],
 "porcoes8": ["1/2 serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Light coconut milk gives creaminess to the sauce with much less fat than cream. The curry perfumes it and gives the feeling of a special dish, which helps you eat slowly and feel satisfied with a controlled portion of chicken and rice.",
},
{
 "nome": "Baked Sardines with Potato and Salad",
 "hook": "Cheap, full of omega-3 and ready in minutes — sardines are one of the best friends of anyone losing weight on a budget.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 450,
 "ings": ["3 to 4 fresh cleaned sardines (or 1 can of sardines in water)", "1 small potato in slices",
          "1 tsp olive oil", "juice of 1/2 lemon", "1 clove of garlic, chopped",
          "salt, pepper and oregano to taste", "green leaves and tomato for the salad"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the potato into thin slices, season with salt and half of the olive oil and spread it on a baking tray.",
   "Bake the potato for 10 minutes, to start softening it.",
   "Season the sardines with salt, pepper, garlic, oregano and the lemon juice.",
   "Take the tray out, put the sardines between the potatoes and drizzle with the rest of the olive oil.",
   "Put it back in the oven for another 15 minutes, until the sardines are golden and the potato is soft. Serve with a fresh green salad on the side.",
   "If you use canned sardines, skip the oven for the fish: just bake the potato and build the plate with the drained sardines and the salad."],
 "porcoes8": ["2 sardines · 1/2 potato · salad",
              "3 sardines · 1 small potato · salad",
              "3 sardines · 1 potato · salad",
              "4 sardines · 1 potato · a little olive oil",
              "4 sardines · 1 potato · salad",
              "4 sardines · 1 large potato · salad",
              "5 sardines · 1 large potato · a little olive oil",
              "6 sardines · 2 small potatoes · salad"],
 "dica": "The sardine is a powerful little fish: lots of omega-3 (the good fat that is great for your heart), protein and calcium, for a very low price. Baked with a little potato and a fresh salad, it becomes a complete, nourishing and cheap lunch.",
},
{
 "nome": "Eggplant Stuffed with Ground Beef",
 "hook": "The eggplant itself becomes the bowl — stuffed with seasoned meat and browned on top, it is pretty and fools any craving for a big meal.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["1 large eggplant", "7 oz lean ground beef", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tomato, chopped", "1 tsp olive oil", "2 tbsp grated low-fat cheese",
          "salt, pepper and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the eggplant in half lengthwise. With a spoon, take out part of the middle, making two 'boats'. Chop the part you took out.",
   "Put the boats on a baking tray, drizzle with a little olive oil and bake for 10 minutes, just to soften them.",
   "Meanwhile, in a pan, fry the onion and the garlic in the rest of the olive oil for 2 minutes. Add the ground beef and stir until it loses its pink color.",
   "Add the tomato, the chopped eggplant middle, salt and pepper and cook for 5 minutes, until it makes a soft filling.",
   "Fill the eggplant boats with the meat, sprinkle the grated cheese on top and put them back in the oven for 15 minutes, until the top browns (the cheese melts and goes golden). Sprinkle parsley and serve."],
 "porcoes8": ["1/2 eggplant · salad",
              "1 stuffed eggplant · salad",
              "1 eggplant · 2 tbsp rice",
              "1 eggplant · extra meat · salad",
              "1 eggplant · extra meat · 2 tbsp rice",
              "1 large eggplant · 3 tbsp rice",
              "1 eggplant · double meat · 4 tbsp rice",
              "eggplant + extra portion of meat · 4 tbsp rice"],
 "dica": "Eggplant has a lot of water and fiber, so it fills your stomach with very few calories — stuffed, it gives volume to the plate and fills you up. The lean meat brings the protein, and a little cheese on top kills the craving for a browned, cheesy dish without going overboard.",
},
{
 "nome": "Fit Caesar Salad with Grilled Chicken",
 "hook": "The creamy Caesar salad you love, with a smart yogurt dressing — all the creaminess, none of the guilt.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 grilled chicken fillet in strips (about 4.5 oz)", "romaine lettuce leaves", "1 slice of wholegrain bread in cubes",
          "2 tbsp plain yogurt with no sugar", "1 tsp mustard",
          "1 tsp grated cheese", "juice of 1/2 lemon", "1 clove of garlic, crushed", "salt and pepper to taste"],
 "passos": [
   "Season the chicken with salt and pepper and grill it in a nonstick pan for 4 minutes on each side, until it is golden and white inside. Cut it into strips.",
   "Make the croutons: spread the wholegrain bread cubes on a baking tray and bake at medium heat for 8 minutes, until they are crisp (or toast them in a pan with no oil).",
   "Prepare the dressing: in a small bowl, mix the yogurt, the mustard, the grated cheese, the lemon juice, the crushed garlic, salt and pepper, until it turns into a cream.",
   "Tear the lettuce with your hands and put it in a large bowl. Drizzle with the dressing and toss to coat the leaves.",
   "Put the chicken strips and the croutons on top and serve right away, so the bread stays crisp."],
 "porcoes8": ["3.5 oz chicken · salad · a few croutons",
              "4.5 oz chicken · salad · croutons",
              "4.5 oz chicken · salad · croutons",
              "5 oz chicken · salad · 1 more tbsp cheese",
              "5 oz chicken · salad · croutons",
              "6 oz chicken · salad · croutons",
              "7 oz chicken · salad · extra croutons",
              "8 oz chicken · salad · extra croutons"],
 "dica": "The traditional Caesar dressing is a bomb of mayonnaise and oil. Swapping it for yogurt with mustard and lemon keeps the creaminess and the strong taste with much less fat. The grilled chicken turns the salad into a real meal, full of protein.",
},
{
 "nome": "Beef Strips with Bell Pepper and Rice",
 "hook": "Thin strips of beef sautéed with colorful peppers — fragrant, well seasoned and ready in the pan in minutes.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["9 oz lean beef in thin strips", "1 red bell pepper in strips",
          "1 yellow bell pepper in strips", "1 onion in strips", "1 clove of garlic, chopped",
          "1 tsp olive oil", "juice of 1/2 lemon", "cumin, salt, pepper and coriander to taste",
          "rice to serve"],
 "passos": [
   "Season the beef strips with salt, pepper, cumin, the garlic and the lemon juice. Let them take in the flavor for 10 minutes.",
   "Heat a large pan with half of the olive oil over high heat. Put the meat in a little at a time (not all at once, or it releases water) and brown it fast, stirring, for 3 minutes. Take it out and set it aside.",
   "In the same pan, with the rest of the olive oil, add the onion and the peppers. Stir over high heat for 4 minutes, until they are tender but still firm and colorful.",
   "Put the meat back in the pan and mix for 1 minute, just to bring the flavors together.",
   "Sprinkle coriander and serve over a portion of rice. It is also great rolled in a wholegrain tortilla."],
 "porcoes8": ["1/2 serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra meat",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + meat · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Cutting the meat into thin strips goes further: a small portion looks like much more on the plate. Sautéed fast over high heat with peppers, it stays juicy and full of flavor with no need for a greasy sauce. The peppers bring color, vitamins and fiber for almost no calories.",
},
{
 "nome": "Homemade Lean Beef Burger with Salad",
 "hook": "The burger that kills the craving and still helps you lose weight — made at home with lean meat, without the greasy bun.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 440,
 "ings": ["9 oz lean ground beef", "1/2 onion, finely chopped", "1 clove of garlic, chopped",
          "salt, pepper and parsley to taste", "1 tsp olive oil", "2 wholegrain burger buns",
          "lettuce leaves, tomato and onion in rounds to build it"],
 "passos": [
   "In a bowl, mix the ground beef with the chopped onion, the garlic, salt, pepper and parsley. Knead it with your hands only until it holds together, without working it too much (or the burger goes tough).",
   "Divide the meat in two and shape two discs, flattening them well with your hands. Make a light dimple in the center of each one with your thumb — that stops them from puffing up in the middle.",
   "Heat a nonstick pan with a few drops of olive oil over medium-high heat. Put the burgers in and leave them 3 to 4 minutes on each side, without pressing them with the spatula, until they are golden outside and done the way you like inside.",
   "If you like, lightly toast the wholegrain bun, cut open, in the pan.",
   "Build it: bun, lettuce, the burger, the tomato and the onion. Close it and serve. For an even lighter version, eat the burger with no bun, with a generous salad on the side."],
 "porcoes8": ["1 burger · no bun · salad",
              "1 burger · 1/2 bun · salad",
              "1 burger · 1 bun · salad",
              "1 burger · 1 bun · salad",
              "1 large burger · 1 bun · salad",
              "1 large burger · 1 bun · salad",
              "2 burgers · 1 bun · salad",
              "2 burgers · 1 bun · salad"],
 "dica": "The problem with a fast-food burger is the fatty meat, the sauce and the frying. Made at home with lean meat and grilled with no oil, it becomes pure protein. Eating it with plenty of salad and little (or no) bread, you kill the craving without blowing your calories.",
},
{
 "nome": "White Fish with Vegetables and Couscous",
 "hook": "A delicate white fillet over fluffy couscous — light, elegant and ready before you notice.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 white fish fillet (hake, whiting or tilapia, about 5 oz)", "1/2 cup couscous",
          "1/2 cup hot water", "1 cup chopped vegetables (green beans, carrot, peas)",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Put the couscous in a bowl with a pinch of salt, cover it with the hot water, cover it with a plate and leave it 5 minutes. Then loosen it with a fork until it is fluffy.",
   "Cook the chopped vegetables in a steamer or in a little boiling water for 5 minutes, until they are tender but still firm. Drain them.",
   "Season the fish with salt, pepper and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat. Put the fillet in and leave it 3 to 4 minutes on each side, turning it carefully once, until it is golden and flakes apart with a fork.",
   "Mix the vegetables into the couscous. Build the plate with the vegetable couscous and the fillet on top. Sprinkle parsley and serve."],
 "porcoes8": ["4 oz fish · 1/3 cup couscous · vegetables",
              "5 oz fish · 1/2 cup couscous · vegetables",
              "5 oz fish · 1/2 cup couscous · vegetables",
              "6 oz fish · 2/3 cup couscous · a little olive oil",
              "6 oz fish · 2/3 cup couscous · vegetables",
              "7 oz fish · 3/4 cup couscous · vegetables",
              "8 oz fish · 1 cup couscous · a little olive oil",
              "9 oz fish · 1 cup couscous · a little olive oil"],
 "dica": "White fish like hake and whiting are extremely lean and light, ideal for the lunch of anyone who wants to lose weight. Couscous cooks with hot water alone, with no fat, and with the vegetables it becomes a colorful, fluffy side full of fiber.",
},
{
 "nome": "Chicken and Vegetable Skewers with Rice",
 "hook": "Colorful and fun to build, the skewers cook evenly and give any lunch a party feel.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 450,
 "ings": ["2 chicken breast fillets in cubes (about 10 oz)", "1 bell pepper in squares", "1 onion in pieces",
          "1 zucchini in thick rounds", "cherry tomatoes", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and paprika to taste", "rice to serve", "skewer sticks"],
 "passos": [
   "Season the chicken cubes with salt, pepper, paprika and the lemon juice. Let them take in the flavor for 10 minutes.",
   "Build the skewers alternating a cube of chicken, a piece of bell pepper, one of onion, a round of zucchini and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or a griddle over medium-high heat. Put the skewers on and turn them every 3 minutes, until the chicken is golden on all sides and white inside (about 12 minutes in total).",
   "Serve the skewers over a portion of rice."],
 "porcoes8": ["1 skewer · 3 tbsp rice",
              "2 skewers · 4 tbsp rice",
              "2 skewers · 5 tbsp rice",
              "2 skewers · 5 tbsp rice · extra chicken",
              "2 skewers · 5 tbsp rice",
              "3 skewers · 6 tbsp rice",
              "3 skewers · 7 tbsp rice",
              "3 large skewers · 8 tbsp rice"],
 "dica": "Skewers help you control the portion naturally and also mix plenty of vegetables into the protein. Lean grilled chicken brings fullness with no fat, and the colorful vegetables fill the plate with fiber and vitamins for almost no calories.",
},
{
 "nome": "Fit Potato Salad with Egg and Tuna",
 "hook": "The creamy potato salad from parties, without the heavy mayonnaise — it becomes a complete and light lunch.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 410,
 "ings": ["2 medium potatoes in cubes", "2 boiled eggs", "1 can of tuna in water, drained",
          "3 tbsp plain yogurt with no sugar", "1 tsp mustard",
          "chopped red onion and fresh herbs", "salt, pepper and juice of 1/2 lemon to taste"],
 "passos": [
   "Cook the potato cubes in boiling salted water for 12 to 15 minutes, until they are soft but not falling apart (a fork goes in easily). Drain them and let them cool a little.",
   "Cook the eggs for 9 minutes, run them under cold water, peel them and cut them into pieces.",
   "Prepare the dressing: mix the yogurt, the mustard, the lemon juice, salt and pepper in a large bowl.",
   "Add to the bowl the warm potato, the drained tuna, the eggs, the red onion and the fresh herbs.",
   "Mix carefully, so you do not break up the potato. Check the salt and serve right away or cold."],
 "porcoes8": ["1/2 serving · 1/2 can tuna · 1 egg",
              "1 serving · 1 can tuna · 2 eggs",
              "1 serving · 1 can tuna · 2 eggs",
              "1 serving · 1 can tuna · 2 eggs · green salad",
              "1 serving · 1 can tuna · 2 eggs",
              "1 large serving · 1.5 cans tuna · 2 eggs",
              "large serving · 1.5 cans tuna · 3 eggs",
              "double serving · 2 cans tuna · 3 eggs"],
 "dica": "Swapping mayonnaise for yogurt with mustard cuts a lot of fat and still adds protein. The tuna and the egg turn a potato salad into a complete and filling meal. Chilled potato even forms a special fiber that feeds the good bacteria in your gut.",
},
{
 "nome": "Oven-Roasted Chicken with Root Vegetables",
 "hook": "Put everything on a tray and let the oven work — the chicken comes out golden and the vegetables go soft and sweet.",
 "tempo": "45 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 skinless chicken thighs (or 2 thick fillets, about 10 oz)", "1 potato in pieces",
          "1 carrot in large pieces", "1 piece of pumpkin in cubes", "1 onion in wedges",
          "2 cloves of garlic", "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper and rosemary to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the potato, the carrot, the pumpkin and the onion into large, similar pieces, so they roast evenly.",
   "On a large baking tray, spread the vegetables and the cloves of garlic. Season with salt, pepper, rosemary and half of the olive oil, and mix with your hands.",
   "Season the chicken with salt, pepper, the lemon juice and the rest of the olive oil. Put the pieces among the vegetables.",
   "Bake for 35 to 40 minutes, turning the vegetables halfway through, until the chicken is golden and cooked inside (the liquid that runs out when you pierce it has to come out clear) and the vegetables are soft.",
   "Serve straight from the tray, with all the juices that formed at the bottom."],
 "porcoes8": ["1 thigh · 1/2 portion vegetables",
              "1 thigh · 1 portion vegetables",
              "1 large thigh · 1 portion vegetables",
              "2 thighs · 1 portion vegetables",
              "2 thighs · 1 portion vegetables",
              "2 thighs · 1 large portion vegetables",
              "2 thighs · large portion vegetables",
              "3 thighs · double portion vegetables"],
 "dica": "Roasting with no skin and not too much oil keeps the chicken light, and the juices it releases season the vegetables with no need for fat. Pumpkin and carrot go sweet as they roast, killing the craving for something sweet, and they fill the plate with fiber and vitamins for few calories.",
},
{
 "nome": "Fit Baked Chicken Parmigiana with Salad",
 "hook": "The crispy, cheesy parmigiana of your dreams, baked in the oven instead of fried — all the pleasure, none of the frying.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 thin chicken breast fillets (about 10 oz)", "1 egg", "4 tbsp wholegrain breadcrumbs",
          "1 cup homemade tomato sauce", "3 tbsp grated low-fat mozzarella",
          "salt, pepper and oregano to taste", "green leaves for the salad"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Season the thin fillets with salt and pepper.",
   "Beat the egg in a deep plate. Put the breadcrumbs in another plate, mixed with oregano.",
   "Dip each fillet first in the egg, then in the breadcrumbs, pressing to coat both sides well.",
   "Put the fillets on a nonstick baking tray (or one lined with parchment paper) and bake for 15 minutes, turning them halfway, until the coating is golden and crisp.",
   "Cover each fillet with the tomato sauce and the grated cheese. Put it back in the oven for another 8 minutes, until the cheese melts and bubbles.",
   "Serve with a fresh green salad on the side."],
 "porcoes8": ["3.5 oz chicken · a little cheese · salad",
              "4.5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · 3 tbsp rice",
              "5 oz chicken · cheese · 3 tbsp rice",
              "6 oz chicken · cheese · 4 tbsp rice",
              "7 oz chicken · cheese · 5 tbsp rice",
              "8 oz chicken · extra cheese · 5 tbsp rice"],
 "dica": "Parmigiana makes you gain weight because of the frying and the excess cheese. Breaded with wholegrain crumbs and baked in the oven, it comes out crisp with a fraction of the fat. A little low-fat cheese on top kills the craving for a cheesy dish, and the salad balances the plate.",
},
{
 "nome": "Rice, Edamame and Salmon Bowl",
 "hook": "Inspired by the Hawaiian poke: fresh, colorful and nourishing, built in a bowl and filling without weighing you down.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 480,
 "ings": ["1 salmon fillet in cubes (about 4.5 oz)", "4 tbsp cooked rice", "1/2 cup cooked edamame (green soybeans)",
          "1/2 cucumber in small cubes", "1/2 carrot, grated", "1/2 avocado in slices", "1 tbsp light soy sauce",
          "sesame seeds, juice of 1/2 lemon and chives to taste"],
 "passos": [
   "Cook the edamame in boiling water for 4 minutes, drain it and, if it is in the pod, take out the little beans.",
   "Season the salmon cubes with the soy sauce and the lemon juice. Let them take in the flavor for 5 minutes. (If you prefer it cooked, quickly grill the cubes in a pan for 3 minutes.)",
   "In a bowl, put the rice on one side as the base.",
   "Arrange on top, in separate groups, the salmon, the edamame, the cucumber, the grated carrot and the avocado.",
   "Drizzle with a little more soy sauce, sprinkle sesame seeds and chives and serve."],
 "porcoes8": ["3.5 oz salmon · 3 tbsp rice · 1/4 avocado",
              "4.5 oz salmon · 4 tbsp rice · 1/2 avocado",
              "4.5 oz salmon · 5 tbsp rice · 1/2 avocado",
              "5 oz salmon · 5 tbsp rice · 1/2 avocado",
              "5 oz salmon · 5 tbsp rice · 1/2 avocado",
              "6 oz salmon · 6 tbsp rice · 1/2 avocado",
              "7 oz salmon · 7 tbsp rice · avocado",
              "8 oz salmon · 8 tbsp rice · avocado"],
 "dica": "It is a complete and balanced plate: protein and omega-3 from the salmon, plant protein from the edamame, good fat from the avocado and the fiber of the raw vegetables. Built in a bowl, it looks beautiful and filling, proving that healthy food can be a feast for the eyes.",
},
{
 "nome": "Hearty Vegetable Soup with Shredded Chicken",
 "hook": "A soup that is a real meal: packed with chicken and vegetables, it warms your body and fills you up without weighing you down.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 380,
 "ings": ["1 chicken breast fillet (about 5 oz)", "1 potato in cubes", "1 carrot in cubes",
          "1 zucchini in cubes", "1/2 cup corn or peas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste", "4 cups of water"],
 "passos": [
   "In a large pot, heat the olive oil and fry the onion and the garlic for 2 minutes, stirring, until they turn clear.",
   "Add the whole chicken fillet and the water. Bring it to a boil and cook for 15 minutes, until the chicken is done.",
   "Take the chicken out, let it cool a little and shred it with two forks. Set it aside.",
   "In the same water, add the potato, the carrot, the zucchini and the corn. Season with salt and pepper and cook for 12 to 15 minutes, until the vegetables are soft.",
   "Put the shredded chicken back in the pot, check the salt and cook for another 3 minutes. Sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · chicken · no extra potato",
              "2 ladles · chicken · vegetables",
              "2 ladles · chicken · vegetables",
              "2 ladles · extra chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Soups are great for losing weight: the volume of liquid and vegetables fills your stomach with very few calories, and the heat makes you eat more slowly. With the shredded chicken, it stops being just a starter and becomes a complete, light and comforting meal.",
},
{
 "nome": "Savory Oat Pancake Filled with Chicken",
 "hook": "The batter takes only egg and oats, blends in seconds and turns into a golden pancake filled with creamy chicken.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 egg", "3 tbsp oats", "3 tbsp water", "1 pinch of salt",
          "1 cooked and shredded chicken fillet (about 3.5 oz)", "2 tbsp tomato sauce",
          "1 tbsp plain yogurt", "1 tsp olive oil", "oregano to taste"],
 "passos": [
   "In a bowl, beat with a fork the egg, the oats, the water and the salt until it turns into a smooth batter. Let it rest for 3 minutes so the oats take in the liquid.",
   "Heat a nonstick pan with half of the olive oil over medium heat. Pour in the batter and spread it by turning the pan, making a thin disc.",
   "Leave it 2 minutes, until the edge comes loose, turn it carefully and brown the other side for another minute. Take the pancake out.",
   "Mix the shredded chicken with the tomato sauce, the yogurt and the oregano, and warm it quickly in the pan.",
   "Fill the pancake with the chicken, fold it in half or roll it and serve hot, with a salad on the side if you like."],
 "porcoes8": ["1 pancake · 3 oz chicken",
              "1 pancake · 3.5 oz chicken",
              "1 pancake · 4 oz chicken",
              "1 pancake · 4 oz chicken · salad",
              "1 pancake · 4.5 oz chicken · salad",
              "2 pancakes · 5 oz chicken",
              "2 pancakes · 6 oz chicken · salad",
              "2 pancakes · 7 oz chicken · salad"],
 "dica": "A batter of egg and oats swaps white flour for fiber and protein, filling you up much more than a regular pancake. Filled with shredded chicken and a light yogurt sauce, it becomes a practical, tasty and complete meal, great for dinner too.",
},
{
 "nome": "Garlic Shrimp with Vegetables and Rice",
 "hook": "Pink shrimp browned in garlic, filling the whole kitchen with its smell — a light and special weekend lunch.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["5 oz cleaned shrimp", "4 tbsp cooked rice", "1 cup of broccoli and green beans",
          "2 cloves of garlic, chopped", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and parsley to taste"],
 "passos": [
   "Dry the shrimp well with paper towel and season it with salt, pepper and the lemon juice. Let it take in the flavor for 5 minutes.",
   "Cut the broccoli into florets and the green beans into pieces. Cook them in a steamer or in a little boiling water for 4 minutes, until they are green and tender but still firm. Drain them.",
   "Heat a nonstick pan with the olive oil over medium heat. Add the chopped garlic and stir for 30 seconds, just until it smells good and starts to turn golden — be careful not to burn it, or it goes bitter.",
   "Put the shrimp in and sauté (stir over medium-high heat) for 2 to 3 minutes, just until it turns pink and curls up. Do not overcook it, or it goes rubbery.",
   "Add the vegetables and the already cooked rice to the pan and mix for 1 minute, to take in the garlic flavor. Sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · 3 tbsp rice · vegetables",
              "5 oz shrimp · 4 tbsp rice · vegetables",
              "5 oz shrimp · 5 tbsp rice · vegetables",
              "6 oz shrimp · 5 tbsp rice · a little olive oil",
              "6 oz shrimp · 5 tbsp rice · vegetables",
              "7 oz shrimp · 6 tbsp rice · vegetables",
              "8 oz shrimp · 7 tbsp rice · a little olive oil",
              "9 oz shrimp · 8 tbsp rice · a little olive oil"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories, so you can help yourself generously with no guilt. Browned in garlic, it gains a lot of flavor with just a little olive oil, and with the vegetables and a measured portion of rice it becomes a light plate that looks like restaurant food.",
},
{
 "nome": "Beef Meatballs in Sauce with Mashed Potato",
 "hook": "Soft meatballs in a rich tomato sauce, over a light mash — the warm hug your diet allows.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 490,
 "ings": ["9 oz lean ground beef", "1 egg", "2 tbsp oats", "1 clove of garlic, chopped",
          "3 tomatoes, chopped (or tomato sauce)", "1 onion, chopped", "2 medium potatoes",
          "1 tsp olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until they are very soft. Drain and mash them with a fork, with a pinch of salt, until it turns into a smooth mash. If you want it creamier, add a little of the cooking water.",
   "In a bowl, mix the ground beef, the egg, the oats, half of the garlic, salt and pepper. Knead it with your hands and roll balls the size of a walnut.",
   "Heat the olive oil in a pot and brown the meatballs on all sides, turning them carefully, for 5 minutes. Take them out and set them aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the tomatoes, salt and pepper and cook for 8 minutes, until it turns into a sauce.",
   "Put the meatballs back into the sauce and cook for another 8 minutes, until they are done inside. Sprinkle basil.",
   "Serve the meatballs with the sauce over the mashed potato."],
 "porcoes8": ["3 meatballs · 1/2 serving mash",
              "4 meatballs · 1 serving mash",
              "4 meatballs · 1 serving mash",
              "5 meatballs · 1 serving mash",
              "5 meatballs · 1 serving mash",
              "6 meatballs · 1 large serving mash",
              "7 meatballs · large serving mash",
              "8 meatballs · double serving mash"],
 "dica": "The meatballs use oats instead of more bread, which binds them with fiber instead of white starch. Made with lean meat and cooked in the sauce (not fried), they stay juicy and light. Regular mashed potato, in the right measure, is comforting and filling.",
},
{
 "nome": "Light Chicken and Vegetable Risotto",
 "hook": "The creaminess of risotto with no butter and no excess cheese — the rice releases its own cream and wraps around the chicken and the vegetables.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 480,
 "ings": ["1 cup of rice (arborio or regular)", "2 chicken breast fillets in cubes (about 10 oz)",
          "1 carrot in small cubes", "1/2 cup peas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp olive oil", "1 tbsp grated cheese", "salt, pepper and parsley to taste",
          "homemade vegetable stock or hot water (about 3 cups)"],
 "passos": [
   "Season the chicken cubes with salt and pepper. Heat the olive oil in a pot and brown the chicken for 5 minutes, stirring. Take it out and set it aside.",
   "In the same pot, fry the onion and the garlic for 2 minutes. Add the rice and stir for 1 minute, just to coat the grains in the seasoning.",
   "Start adding the hot stock a little at a time, one ladle at a time, stirring all the while. Only add more stock when the previous one has almost dried up.",
   "Halfway through cooking (about 10 minutes), add the carrot and the peas. Keep stirring and adding stock.",
   "When the rice is soft and creamy (about 18 to 20 minutes in total), put the chicken back, add the grated cheese and stir. Turn it off, sprinkle parsley and serve right away."],
 "porcoes8": ["1/2 serving · chicken",
              "1 serving · chicken",
              "1 serving · chicken",
              "1 serving · extra chicken",
              "1 serving · extra chicken",
              "1 large serving · chicken",
              "large serving · extra chicken",
              "double serving · extra chicken"],
 "dica": "Traditional risotto takes a lot of butter and cheese. Here, the creaminess comes from the rice's own starch released by stirring, with just a touch of cheese. With plenty of chicken and vegetables, the plate is hearty and satisfying, proving you can eat risotto with no guilt.",
},
]
