# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). Português.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+  ·  Homem 70-85/86-100/101-120/120+
Metas (kcal): 340/420/480/540  ·  520/590/650/720
Jantar = mais leve que o almoço (peixe, sopas, assados). Sem vegetariano.
Proteínas: 11 frango · 9 peixe · 6 carne · 4 peru · 3 camarão · 2 ovo.
Cada receita tem 'prompt' = foto quadrada, ultrarrealista, SEM texto.
"""

RECEITAS = [
{
 "nome": "Sopa de Abóbora com Frango Desfiado",
 "hook": "Cremosa, alaranjada e reconfortante — uma sopa que aquece à noite e ainda traz proteína do frango para saciar de verdade.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 340,
 "ings": ["1 pedaço grande de abóbora em cubos (≈ 500 g)", "1 filé de peito de frango (≈ 150 g)",
          "1 cebola picada", "1 dente de alho picado", "1 colher de chá de azeite",
          "sal, pimenta e gengibre ralado a gosto", "cheiro-verde para finalizar", "1 litro de água"],
 "passos": [
   "Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos, mexendo, até ficarem transparentes.",
   "Junte a abóbora em cubos, o filé de frango inteiro e a água. Deixe ferver e cozinhe por 20 minutos, até a abóbora ficar bem macia.",
   "Retire o frango, deixe amornar e desfie com dois garfos. Deixe de lado.",
   "Com um mixer (aquele bastão de bater) ou no liquidificador, bata a abóbora com o caldo até virar um creme liso. Cuidado com o líquido quente.",
   "Volte o creme à panela, junte o frango desfiado, o gengibre, sal e pimenta e aqueça por 3 minutos. Sirva com cheiro-verde por cima."],
 "porcoes8": ["1 concha · pouco frango",
              "2 conchas · frango",
              "2 conchas · frango",
              "2 conchas · frango · 1 fatia pão",
              "2 conchas · frango extra · 1 fatia pão",
              "3 conchas · frango · 1 fatia pão",
              "3 conchas · frango extra · 2 fatias pão",
              "3 conchas grandes · frango duplo · 2 fatias pão"],
 "dica": "A abóbora tem muita água e fibra, o que enche o estômago com pouquíssimas calorias. O calor da sopa faz comer mais devagar, e o frango desfiado transforma o creme leve numa refeição completa que segura a fome até a hora de dormir, sem peso.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy orange pumpkin soup topped with shredded chicken and chopped parsley, in a rustic bowl, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Filé de Frango ao Molho de Mostarda com Legumes no Vapor",
 "hook": "Um molho cremoso de mostarda e iogurte veste o frango de gala — leve, elegante e pronto rápido para o jantar.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 400,
 "ings": ["1 filé de peito de frango (≈ 150 g)", "1 colher de sopa de iogurte natural sem açúcar",
          "1 colher de chá de mostarda", "1 xícara de brócolis, cenoura e vagem", "1 dente de alho picado",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta e cheiro-verde a gosto"],
 "passos": [
   "Corte os legumes em pedaços parecidos. Cozinhe no vapor (ou numa panela com um dedo de água tampada) por 6 minutos, até ficarem macios mas ainda firmes e coloridos.",
   "Tempere o frango com sal, pimenta e o alho. Aqueça uma frigideira que não gruda com o azeite em fogo médio e grelhe o filé por 4 a 5 minutos de cada lado, até dourar e ficar branco por dentro.",
   "Numa tigelinha, misture o iogurte, a mostarda, o suco de limão, sal e pimenta, até virar um molho cremoso.",
   "Coloque o frango no prato, regue com o molho de mostarda e sirva com os legumes ao lado.",
   "Salpique cheiro-verde e sirva quente."],
 "porcoes8": ["120 g frango · legumes",
              "150 g frango · legumes",
              "150 g frango · legumes · 2 col. arroz",
              "170 g frango · legumes · 2 col. arroz",
              "170 g frango · legumes · 3 col. arroz",
              "200 g frango · legumes · 3 col. arroz",
              "220 g frango · legumes · 4 col. arroz",
              "250 g frango · legumes · 4 col. arroz"],
 "dica": "O molho cremoso vem do iogurte, não de creme de leite ou manteiga, cortando muita gordura. A mostarda dá sabor forte com quase nenhuma caloria. Cozinhar os legumes no vapor preserva os nutrientes e não usa óleo — um jantar leve que parece de restaurante.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast with a creamy mustard yogurt sauce, served with steamed broccoli, carrot and green beans, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peixe Assado no Papelote com Legumes",
 "hook": "O peixe cozinha no próprio vapor dentro do papel, ficando incrivelmente macio — e você abre o embrulho na mesa, quentinho e cheiroso.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 380,
 "ings": ["1 filé de peixe branco (pescada, merluza ou tilápia, ≈ 150 g)", "½ abobrinha em rodelas finas",
          "½ cenoura em tiras finas", "tomatinhos cortados", "1 dente de alho fatiado", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e ervas (tomilho ou orégano) a gosto", "1 folha grande de papel-manteiga"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a abobrinha e a cenoura em fatias finas, para cozinharem no mesmo tempo do peixe.",
   "No centro de uma folha grande de papel-manteiga, faça uma cama com os legumes. Tempere com um pouco de sal, pimenta e metade do azeite.",
   "Coloque o filé de peixe por cima. Tempere com sal, pimenta, o alho, as ervas, o suco de limão e o restante do azeite.",
   "Feche o papel como um embrulho: junte as pontas e dobre bem as bordas, deixando um espaço de ar dentro, para virar um pacotinho fechado.",
   "Leve ao forno por 18 a 20 minutos. Abra com cuidado (sai vapor quente) e sirva no próprio papel ou passe para o prato."],
 "porcoes8": ["120 g peixe · legumes",
              "150 g peixe · legumes",
              "150 g peixe · legumes · 1 batata pequena",
              "170 g peixe · legumes · 1 batata",
              "170 g peixe · legumes · 1 batata",
              "200 g peixe · legumes · 1 batata",
              "220 g peixe · legumes · 1 batata grande",
              "250 g peixe · legumes · 2 batatas pequenas"],
 "dica": "Cozinhar no papelote quase não usa gordura: o peixe e os legumes cozinham no próprio vapor, mantendo o sabor e ficando muito macios. É um dos jeitos mais leves e saudáveis de preparar peixe, perfeito para um jantar sem peso e sem sujar panela.",
 "prompt": "Square ultra-realistic overhead food photograph of a white fish fillet baked in open parchment paper with zucchini, carrot, cherry tomato and herbs, steam rising, a lemon wedge, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Escondidinho de Frango com Purê de Couve-flor",
 "hook": "Todo o conforto de um escondidinho gratinado, mas a cobertura é purê de couve-flor — cremoso, leve e com muito menos calorias.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 380,
 "ings": ["1 couve-flor média", "2 filés de peito de frango cozidos e desfiados (≈ 300 g)", "1 cebola picada",
          "1 dente de alho picado", "1 tomate picado", "1 colher de chá de azeite",
          "2 colheres de sopa de queijo ralado magro", "sal, pimenta e cheiro-verde a gosto"],
 "passos": [
   "Corte a couve-flor em pedaços e cozinhe em água fervente por 12 minutos, até ficar bem macia. Escorra muito bem (couve-flor guarda água) e amasse com um garfo, com uma pitada de sal, até virar um purê cremoso.",
   "Numa frigideira, aqueça o azeite e frite a cebola e o alho por 2 minutos. Junte o frango desfiado e o tomate, tempere com sal e pimenta e cozinhe por 5 minutos, até formar um recheio macio.",
   "Num refratário, espalhe o frango no fundo e cubra com o purê de couve-flor.",
   "Polvilhe o queijo ralado por cima.",
   "Leve ao forno médio-alto (200 °C) por 15 minutos, até a superfície ficar levemente dourada. Salpique cheiro-verde e sirva."],
 "porcoes8": ["½ porção · salada",
              "1 porção · salada",
              "1 porção · salada",
              "1 porção · frango extra · salada",
              "1 porção · frango extra · salada",
              "1 porção grande · salada",
              "1 porção grande · frango extra · salada",
              "porção dupla · salada"],
 "dica": "A couve-flor no lugar da batata corta boa parte das calorias e do carboidrato, mantendo a cremosidade do purê. O frango desfiado dá proteína e saciedade. É o prato reconfortante ideal para o jantar de quem quer comer quentinho e leve antes de dormir.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken shepherd's pie topped with creamy cauliflower mash, golden gratin top, a spoon lifting a portion, in a white dish, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sopa de Legumes com Carne Magra",
 "hook": "A sopa que parece que a vó fez: pedaços de carne macia e legumes num caldo temperado, que enche a barriga e aquece a alma.",
 "tempo": "50 min", "rende": "3 porções", "kcal_base": 360,
 "ings": ["250 g de carne magra em cubos (músculo ou patinho)", "1 batata em cubos", "1 cenoura em cubos",
          "1 abobrinha em cubos", "1 tomate picado", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto", "1,5 litro de água"],
 "passos": [
   "Numa panela, aqueça o azeite e doure os cubos de carne por todos os lados, mexendo, por 5 minutos.",
   "Junte a cebola e o alho e frite por 2 minutos. Acrescente o tomate e mexa por mais 2 minutos.",
   "Coloque a água, tempere com sal e pimenta, tampe e cozinhe em fogo médio-baixo por 30 minutos, até a carne começar a amaciar.",
   "Junte a batata, a cenoura e a abobrinha e cozinhe por mais 15 minutos, até a carne ficar bem macia e os legumes cozidos.",
   "Prove o sal, salpique cheiro-verde e sirva bem quente."],
 "porcoes8": ["1 concha · pouca carne",
              "2 conchas · carne",
              "2 conchas · carne",
              "2 conchas · carne · 1 fatia pão",
              "2 conchas · carne extra · 1 fatia pão",
              "3 conchas · carne · 1 fatia pão",
              "3 conchas · carne extra · 2 fatias pão",
              "3 conchas grandes · carne dupla · 2 fatias pão"],
 "dica": "Sopas com muito líquido e legumes enchem o estômago com poucas calorias, e comê-las quentes faz a gente comer devagar e sentir saciedade mais cedo. A carne magra entra com proteína, deixando a sopa substanciosa o suficiente para ser um jantar completo.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty beef and vegetable soup with tender beef cubes, potato, carrot and zucchini in a broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salmão com Molho de Iogurte e Endro e Legumes",
 "hook": "O salmão rosado ganha um molho fresquinho de iogurte com endro — sofisticado, leve e feito em vinte minutos.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 430,
 "ings": ["1 posta de salmão (≈ 150 g)", "2 colheres de sopa de iogurte natural sem açúcar", "endro (dill) picado",
          "1 xícara de brócolis e cenoura", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e alho picado a gosto"],
 "passos": [
   "Corte o brócolis em buquês e a cenoura em rodelas. Cozinhe no vapor por 6 minutos, até ficarem macios mas ainda firmes.",
   "Tempere o salmão com sal, pimenta, o alho e o suco de limão.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio. Coloque o salmão com a pele para baixo e deixe 4 minutos, depois vire e deixe mais 3 minutos, até ficar mais claro e se soltar em lascas com o garfo.",
   "Prepare o molho: misture o iogurte, o endro picado, um pouco de sal e algumas gotas de limão.",
   "Monte o prato com o salmão, os legumes ao lado e o molho de iogurte por cima ou à parte."],
 "porcoes8": ["120 g salmão · legumes",
              "150 g salmão · legumes",
              "150 g salmão · legumes · 1 batata pequena",
              "170 g salmão · legumes · 1 batata",
              "170 g salmão · legumes · 1 batata",
              "200 g salmão · legumes · 1 batata",
              "220 g salmão · legumes · 1 batata grande",
              "250 g salmão · legumes · 2 batatas pequenas"],
 "dica": "O salmão traz a gordura boa (ômega-3) que sacia e faz bem ao coração. O molho de iogurte com endro substitui molhos cremosos gordurosos por uma versão fresca e proteica. Com legumes no vapor, é um jantar leve, bonito e completo.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared salmon fillet with a creamy yogurt dill sauce, served with steamed broccoli and carrot, a lemon wedge, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango ao Limão com Legumes Assados",
 "hook": "O frango fica suculento e levemente cítrico, assado junto com legumes que caramelizam nas pontas — uma assadeira, zero trabalho.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 420,
 "ings": ["2 sobrecoxas de frango sem pele (ou 2 filés, ≈ 300 g)", "1 abobrinha em pedaços", "1 pimentão em pedaços",
          "1 cebola em gomos", "tomatinhos", "2 dentes de alho", "1 colher de chá de azeite",
          "suco de 1 limão", "sal, pimenta e orégano a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Numa assadeira, espalhe a abobrinha, o pimentão, a cebola, os tomatinhos e os dentes de alho.",
   "Tempere os legumes com sal, pimenta, orégano e metade do azeite, e misture.",
   "Tempere o frango com sal, pimenta, o suco de limão e o restante do azeite. Coloque as peças entre os legumes.",
   "Leve ao forno por 35 minutos, virando na metade do tempo, até o frango ficar dourado e cozido por dentro (o líquido que escorre ao furar sai transparente) e os legumes macios com as pontas douradas.",
   "Sirva direto da assadeira, regando com o caldinho de limão que se formou."],
 "porcoes8": ["1 sobrecoxa · legumes",
              "1 sobrecoxa · legumes",
              "1 sobrecoxa grande · legumes",
              "2 sobrecoxas · legumes",
              "2 sobrecoxas · legumes",
              "2 sobrecoxas · legumes · 1 batata",
              "2 sobrecoxas · legumes · 1 batata grande",
              "3 sobrecoxas · legumes · 1 batata grande"],
 "dica": "Assar sem pele e com pouco óleo mantém o frango leve, e o limão dá frescor sem somar calorias. Os legumes assados ficam doces e saborosos por conta própria, dispensando molhos pesados. Um jantar prático, colorido e leve feito numa assadeira só.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-roasted lemon chicken thighs with zucchini, pepper, onion and cherry tomatoes on a roasting tray, golden and juicy, lemon wedges, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Almôndegas de Peru com Abobrinha ao Molho",
 "hook": "Almôndegas leves de peru nadando num molho de tomate fresco, sobre fitas de abobrinha — a massa que não pesa na balança.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 380,
 "ings": ["250 g de peito de peru moído (ou frango moído)", "1 ovo", "2 colheres de sopa de aveia",
          "2 abobrinhas grandes", "3 tomates maduros picados (ou molho de tomate)", "1 cebola picada",
          "2 dentes de alho picados", "1 colher de chá de azeite", "sal, pimenta e manjericão a gosto"],
 "passos": [
   "Numa tigela, misture o peru moído, o ovo, a aveia, metade do alho, sal e pimenta. Amasse com as mãos e enrole bolinhas do tamanho de uma noz.",
   "Aqueça o azeite numa panela larga e doure as almôndegas por todos os lados, girando com cuidado, por 5 minutos. Tire e deixe de lado.",
   "Na mesma panela, frite a cebola e o restante do alho por 2 minutos. Junte os tomates picados, sal e pimenta e cozinhe por 10 minutos, até virar molho.",
   "Volte as almôndegas ao molho e cozinhe por mais 8 minutos, até ficarem cozidas por dentro.",
   "Com um descascador de legumes, faça fitas finas da abobrinha (como se fosse macarrão). Coloque as fitas cruas no prato e despeje as almôndegas quentes com o molho por cima — o calor amacia a abobrinha. Salpique manjericão."],
 "porcoes8": ["3 almôndegas · abobrinha",
              "4 almôndegas · abobrinha",
              "4 almôndegas · abobrinha · 2 col. arroz",
              "5 almôndegas · abobrinha · 2 col. arroz",
              "5 almôndegas · abobrinha · 3 col. arroz",
              "6 almôndegas · abobrinha · 3 col. arroz",
              "7 almôndegas · abobrinha · 4 col. arroz",
              "8 almôndegas · abobrinha · 4 col. arroz"],
 "dica": "Trocar o macarrão por fitas de abobrinha corta quase todo o carboidrato e enche o prato com fibra e água. As almôndegas de peru são magras e proteicas, e o molho de tomate feito na hora, sem açúcar, deixa o jantar saboroso e muito leve.",
 "prompt": "Square ultra-realistic overhead food photograph of turkey meatballs in fresh tomato sauce served over zucchini noodles, sprinkled with basil, in a white bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Filé de Peixe com Crosta de Ervas e Purê de Batata",
 "hook": "Uma casquinha crocante de ervas por fora, o peixe macio por dentro — parece prato de chef, mas é simples e leve.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 410,
 "ings": ["1 filé de peixe branco (pescada, merluza ou tilápia, ≈ 150 g)", "2 colheres de sopa de farinha de rosca integral",
          "salsinha e cebolinha bem picadas", "1 batata média", "1 colher de chá de azeite",
          "suco de ½ limão", "1 dente de alho picado", "sal e pimenta a gosto"],
 "passos": [
   "Descasque e cozinhe a batata em água fervente por 15 minutos, até ficar bem macia. Escorra e amasse com um garfo, com uma pitada de sal, até virar um purê liso.",
   "Ligue o forno em temperatura média-alta (200 °C). Tempere o peixe com sal, pimenta, o alho e o suco de limão.",
   "Numa tigelinha, misture a farinha de rosca com a salsinha, a cebolinha e um fio de azeite, formando uma farofinha úmida.",
   "Coloque o peixe numa assadeira e cubra a parte de cima com a farofa de ervas, apertando de leve para grudar.",
   "Asse por 15 a 18 minutos, até a crosta ficar dourada e crocante e o peixe se soltar em lascas. Sirva com o purê de batata."],
 "porcoes8": ["120 g peixe · ½ porção purê",
              "150 g peixe · 1 porção purê",
              "150 g peixe · 1 porção purê",
              "170 g peixe · 1 porção purê",
              "170 g peixe · 1 porção purê",
              "200 g peixe · 1 porção grande purê",
              "220 g peixe · porção grande purê",
              "250 g peixe · porção dupla purê"],
 "dica": "A crosta de ervas com um pouquinho de farinha de rosca dá crocância sem fritura, deixando o peixe leve e cheio de sabor. O peixe branco é magríssimo e proteico, e o purê na medida certa conforta sem exageros — um jantar bonito e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of a herb-crusted white fish fillet with a golden crispy top, served with creamy mashed potato and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bife Grelhado com Salada de Grão-de-Bico",
 "hook": "Um bife no ponto ao lado de uma salada morna de grão-de-bico — proteína dupla que sacia sem pesar no jantar.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 440,
 "ings": ["1 bife de patinho ou alcatra (carne magra, ≈ 120 g)", "½ xícara de grão-de-bico cozido",
          "½ tomate em cubos", "cebola roxa picada", "folhas verdes", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Tempere o bife com sal e pimenta dos dois lados.",
   "Aqueça uma frigideira que não gruda em fogo alto com poucas gotas de azeite. Grelhe o bife por 2 a 3 minutos de cada lado, sem mexer, até dourar por fora e ficar no ponto que você gosta. Deixe descansar 2 minutos antes de cortar.",
   "Numa tigela, misture o grão-de-bico, o tomate, a cebola roxa e a salsinha.",
   "Tempere a salada com o azeite, o suco de limão, sal e pimenta.",
   "Sirva o bife fatiado sobre uma cama de folhas verdes, com a salada de grão-de-bico ao lado."],
 "porcoes8": ["100 g carne · ⅓ xíc. grão · salada",
              "120 g carne · ½ xíc. grão · salada",
              "130 g carne · ½ xíc. grão · salada",
              "150 g carne · ⅔ xíc. grão · salada",
              "150 g carne · ⅔ xíc. grão · salada",
              "170 g carne · ¾ xíc. grão · salada",
              "200 g carne · 1 xíc. grão · salada",
              "220 g carne · 1 xíc. grão · salada"],
 "dica": "O grão-de-bico soma fibra e proteína vegetal à proteína da carne, o que deixa o prato muito saciante com poucas calorias. Grelhar o bife magro sem óleo e servi-lo com uma salada fresca é um jantar leve, cheio de sabor e que segura a fome por horas.",
 "prompt": "Square ultra-realistic overhead food photograph of a sliced grilled lean beef steak on green leaves, with a warm chickpea salad with tomato and red onion beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sopa Cremosa de Brócolis com Frango",
 "hook": "Verdinha, aveludada e cheia de sabor — uma sopa cremosa de brócolis que ganha corpo com o frango e vira jantar completo.",
 "tempo": "30 min", "rende": "3 porções", "kcal_base": 330,
 "ings": ["1 maço de brócolis", "1 filé de peito de frango (≈ 150 g)", "1 batata pequena (dá cremosidade)",
          "1 cebola picada", "1 dente de alho picado", "1 colher de chá de azeite",
          "sal, pimenta e noz-moscada a gosto", "1 litro de água"],
 "passos": [
   "Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos, mexendo.",
   "Junte a batata em cubos, o filé de frango inteiro e a água. Cozinhe por 15 minutos.",
   "Retire o frango, deixe amornar e desfie. Deixe de lado. Junte o brócolis (só os buquês) à panela e cozinhe por mais 5 minutos, até ficar macio mas ainda verde.",
   "Bata a sopa com um mixer (bastão de bater) ou no liquidificador até ficar um creme liso. Cuidado com o líquido quente.",
   "Volte o creme à panela, junte o frango desfiado, tempere com sal, pimenta e um toque de noz-moscada e aqueça por 3 minutos. Sirva."],
 "porcoes8": ["1 concha · pouco frango",
              "2 conchas · frango",
              "2 conchas · frango",
              "2 conchas · frango · 1 fatia pão",
              "2 conchas · frango extra · 1 fatia pão",
              "3 conchas · frango · 1 fatia pão",
              "3 conchas · frango extra · 2 fatias pão",
              "3 conchas grandes · frango duplo · 2 fatias pão"],
 "dica": "O brócolis é um dos vegetais mais nutritivos e de menor caloria, e batido vira um creme aveludado sem precisar de creme de leite. Um pedacinho de batata dá a cremosidade, e o frango desfiado completa a sopa com proteína, deixando o jantar leve e saciante.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy green broccoli soup topped with shredded chicken, in a rustic bowl, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Wrap de Peru com Salada",
 "hook": "Fatias de peito de peru, folhas fresquinhas e um toque cremoso, enrolados num pão macio — jantar leve para comer com as mãos.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 360,
 "ings": ["1 tortilha integral", "4 fatias de peito de peru (fiambre magro)", "1 colher de sopa de queijo cottage (ou requeijão light)",
          "folhas de alface", "½ tomate em rodelas", "cenoura ralada", "pepino em tiras",
          "sal, pimenta e mostarda a gosto"],
 "passos": [
   "Esquente a tortilha por 20 segundos numa frigideira, só para ficar macia e fácil de enrolar.",
   "Espalhe o queijo cottage (ou requeijão light) por toda a tortilha, como se fosse manteiga.",
   "Coloque no centro as folhas de alface, as fatias de peru, o tomate, a cenoura ralada e o pepino.",
   "Tempere com um pouco de sal, pimenta e mostarda.",
   "Dobre as laterais para dentro e enrole apertado, de baixo para cima. Corte ao meio na diagonal e sirva."],
 "porcoes8": ["3 fatias peru · ½ tortilha · salada",
              "4 fatias peru · 1 tortilha · salada",
              "4 fatias peru · 1 tortilha · salada",
              "5 fatias peru · 1 tortilha · salada",
              "5 fatias peru · 1 tortilha · salada",
              "6 fatias peru · 1 tortilha grande · salada",
              "6 fatias peru · 2 tortilhas · salada",
              "8 fatias peru · 2 tortilhas · salada"],
 "dica": "O peito de peru é uma carne magra e prática, cheia de proteína. Trocando o requeijão comum por cottage ou versão light e enchendo o wrap de folhas e legumes, você tem um jantar leve, rápido e saciante, perfeito para dias em que não quer cozinhar.",
 "prompt": "Square ultra-realistic overhead food photograph of a turkey wrap cut in half, filled with turkey slices, lettuce, tomato, grated carrot and cucumber, on a wooden board, fresh vegetables beside it, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ensopado de Frango com Legumes",
 "hook": "Pedaços de frango macio num caldo grosso e temperado, com legumes que desmancham na boca — comida de panela que aconchega.",
 "tempo": "40 min", "rende": "3 porções", "kcal_base": 390,
 "ings": ["2 filés de peito de frango em cubos (≈ 300 g)", "1 batata em cubos", "1 cenoura em rodelas",
          "1 abobrinha em cubos", "1 tomate picado", "1 cebola picada", "2 dentes de alho picados",
          "1 colher de chá de azeite", "sal, pimenta, cúrcuma (açafrão-da-terra) e cheiro-verde a gosto"],
 "passos": [
   "Tempere os cubos de frango com sal, pimenta e um pouco de cúrcuma.",
   "Numa panela, aqueça o azeite e doure os cubos de frango por 5 minutos, mexendo. Junte a cebola e o alho e frite por 2 minutos.",
   "Acrescente o tomate e mexa por 2 minutos, até começar a desmanchar.",
   "Junte a batata e a cenoura e cubra com água (o suficiente para cobrir tudo). Tempere com sal e cozinhe por 15 minutos.",
   "Junte a abobrinha e cozinhe por mais 8 minutos, até tudo ficar macio e o caldo encorpar. Salpique cheiro-verde e sirva puro ou com um pouco de arroz."],
 "porcoes8": ["½ porção · sem arroz",
              "1 porção · sem arroz",
              "1 porção · 2 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção grande · 4 col. arroz",
              "porção grande · 5 col. arroz",
              "porção dupla · 5 col. arroz"],
 "dica": "O ensopado cozinha tudo na mesma panela com pouca gordura, e o próprio caldo do frango tempera os legumes. É um prato substancioso que sacia com poucas calorias, ótimo para o jantar por ser quentinho, reconfortante e leve ao mesmo tempo.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken stew with potato, carrot and zucchini in a golden broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Hambúrguer de Atum com Salada",
 "hook": "Feito de atum de lata, esse hambúrguer é econômico, cheio de proteína e fica pronto num instante — jantar leve e prático.",
 "tempo": "20 min", "rende": "2 porções", "kcal_base": 380,
 "ings": ["2 latas de atum em água, escorrido", "1 ovo", "3 colheres de sopa de aveia", "½ cebola bem picada",
          "salsinha picada", "1 colher de chá de azeite", "sal, pimenta e suco de ½ limão a gosto",
          "folhas verdes, tomate e pepino para a salada"],
 "passos": [
   "Escorra bem o atum, apertando para tirar o líquido. Numa tigela, misture o atum, o ovo, a aveia, a cebola, a salsinha, sal, pimenta e o suco de limão.",
   "Amasse tudo com um garfo até dar liga. Se ficar mole, junte mais um pouco de aveia.",
   "Modele com as mãos dois discos, achatando bem.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio. Coloque os hambúrgueres e deixe 4 minutos de cada lado, sem mexer, até dourar e firmar. Vire com cuidado.",
   "Sirva com uma salada bem servida de folhas, tomate e pepino ao lado."],
 "porcoes8": ["1 hambúrguer · salada",
              "1 hambúrguer · salada",
              "1 hambúrguer · salada · ½ pão",
              "2 hambúrgueres · salada",
              "2 hambúrgueres · salada",
              "2 hambúrgueres · salada · 1 pão",
              "2 hambúrgueres · salada · 1 pão",
              "3 hambúrgueres · salada · 1 pão"],
 "dica": "O atum de lata é uma fonte de proteína barata e prática, e ligado com ovo e aveia (no lugar de muito pão) vira um hambúrguer magro e saciante. Grelhado sem fritura e servido com bastante salada, é um jantar leve e econômico que enche a barriga.",
 "prompt": "Square ultra-realistic overhead food photograph of two homemade tuna patties, golden seared, served with a fresh salad of green leaves, tomato and cucumber, a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Carne Assada de Panela com Legumes",
 "hook": "Um pedaço de carne que cozinha devagar até desmanchar, com legumes embebidos no caldo — o jantar de domingo, na medida certa.",
 "tempo": "1 h 20 min", "rende": "3 porções", "kcal_base": 440,
 "ings": ["400 g de carne magra em peça (músculo, lagarto ou coxão)", "2 cenouras em pedaços grandes",
          "2 batatas em pedaços grandes", "1 cebola em gomos", "2 dentes de alho", "1 tomate picado",
          "1 folha de louro", "1 colher de chá de azeite", "sal, pimenta e alecrim a gosto"],
 "passos": [
   "Tempere a peça de carne com sal e pimenta. Numa panela funda, aqueça o azeite e doure a carne por todos os lados, girando, por uns 6 minutos (esse dourado dá muito sabor ao caldo).",
   "Junte a cebola, o alho e o tomate e frite por 2 minutos. Acrescente a folha de louro e água quente até cobrir metade da carne.",
   "Tampe e cozinhe em fogo baixo por 50 minutos, virando a carne na metade do tempo. Se a água secar muito, junte mais um pouco quente.",
   "Junte as cenouras e as batatas e cozinhe por mais 25 minutos, até a carne ficar tão macia que desmancha e os legumes cozidos.",
   "Retire a folha de louro. Fatie ou desfie a carne e sirva com os legumes e o caldo por cima."],
 "porcoes8": ["½ porção carne · legumes",
              "1 porção carne · legumes",
              "1 porção carne · legumes",
              "1 porção · legumes · 1 batata extra",
              "1 porção · legumes · 1 batata extra",
              "1 porção grande · legumes",
              "porção grande · legumes · batata extra",
              "porção dupla · legumes"],
 "dica": "O cozimento lento amacia cortes magros e baratos sem precisar de gordura, e o caldo que se forma tempera os legumes naturalmente. Servido com a carne na medida e muitos legumes, é um prato reconfortante de fim de semana que cabe direitinho na dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a slow-cooked pot roast beef, tender and sliced, with carrots, potatoes and onion in a rich broth, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango Recheado com Ricota e Espinafre",
 "hook": "O filé de frango abre como um bolso e guarda um recheio cremoso de ricota e espinafre — surpreendente, suculento e leve.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 400,
 "ings": ["2 filés de peito de frango grossos (≈ 300 g)", "4 colheres de sopa de ricota", "1 punhado grande de espinafre",
          "1 dente de alho picado", "1 colher de chá de azeite", "suco de ½ limão",
          "sal, pimenta e noz-moscada a gosto", "palitos de dente"],
 "passos": [
   "Numa frigideira, aqueça poucas gotas de azeite e refogue o espinafre com o alho por 1 minuto, só até murchar (as folhas ficarem moles). Deixe esfriar e pique.",
   "Numa tigela, misture a ricota, o espinafre picado, sal, pimenta e um toque de noz-moscada, formando um recheio cremoso.",
   "Com uma faca, faça um corte na lateral de cada filé, abrindo um bolso (sem cortar até o fim). Tempere o frango com sal, pimenta e o suco de limão.",
   "Recheie os bolsos com a mistura de ricota e feche a abertura com um ou dois palitos de dente.",
   "Aqueça o restante do azeite numa frigideira em fogo médio e doure os filés por 5 a 6 minutos de cada lado, até ficarem dourados e cozidos por dentro. Retire os palitos antes de servir, com uma salada ao lado."],
 "porcoes8": ["1 filé pequeno · salada",
              "1 filé · salada",
              "1 filé · salada · 2 col. arroz",
              "1 filé grande · salada · 2 col. arroz",
              "1 filé grande · salada · 3 col. arroz",
              "1 filé grande · salada · 4 col. arroz",
              "2 filés · salada · 4 col. arroz",
              "2 filés · salada · 5 col. arroz"],
 "dica": "A ricota é um queijo magro e cremoso, cheio de proteína e com pouca gordura, ideal para rechear sem pesar. O espinafre entra com fibra e nutrientes por quase nenhuma caloria. O resultado é um frango suculento e sofisticado, leve o suficiente para o jantar.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken breast stuffed with ricotta and spinach, sliced to show the creamy filling, with a fresh green salad, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sopa de Peixe com Legumes",
 "hook": "Um caldo perfumado com pedaços de peixe branco e legumes — leve, cheio de sabor do mar e reconfortante numa noite fria.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 340,
 "ings": ["400 g de filé de peixe branco em pedaços (pescada ou merluza)", "1 batata em cubos", "1 cenoura em cubos",
          "1 tomate picado", "1 cebola picada", "2 dentes de alho picados", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta, coentro ou salsinha a gosto", "1,2 litro de água"],
 "passos": [
   "Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos. Junte o tomate e mexa por mais 2 minutos, até desmanchar.",
   "Acrescente a água, a batata e a cenoura. Tempere com sal e pimenta e cozinhe por 15 minutos, até os legumes ficarem macios.",
   "Junte os pedaços de peixe (peixe cozinha rápido, por isso entra no fim) e cozinhe por 6 a 8 minutos, só até o peixe ficar branco e macio, sem desmanchar demais.",
   "Junte o suco de limão e prove o sal.",
   "Salpique coentro ou salsinha e sirva bem quente."],
 "porcoes8": ["1 concha · peixe",
              "2 conchas · peixe",
              "2 conchas · peixe",
              "2 conchas · peixe · 1 fatia pão",
              "2 conchas · peixe extra · 1 fatia pão",
              "3 conchas · peixe · 1 fatia pão",
              "3 conchas · peixe extra · 2 fatias pão",
              "3 conchas grandes · peixe duplo · 2 fatias pão"],
 "dica": "O peixe branco é magríssimo e cozinha em minutos, deixando a sopa leve e cheia de proteína. O caldo com legumes enche o estômago com pouquíssimas calorias, e o toque de limão realça o sabor sem sal em excesso — um jantar quentinho e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of a light fish soup with chunks of white fish, potato, carrot and tomato in a fragrant broth, in a rustic bowl, coriander on top, a lemon wedge, on a light wooden table, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Escalope de Peru ao Molho de Champignon",
 "hook": "Fatias finas de peru num molho cremoso de cogumelos — um jantar que parece caro, feito com pouca gordura em vinte minutos.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 400,
 "ings": ["2 filés finos de peito de peru (≈ 300 g)", "1 xícara de cogumelos (champignon) fatiados", "1 cebola picada",
          "1 dente de alho picado", "3 colheres de sopa de iogurte natural sem açúcar", "1 colher de chá de azeite",
          "sal, pimenta e salsinha a gosto", "arroz ou purê para servir"],
 "passos": [
   "Tempere os filés finos de peru com sal e pimenta.",
   "Aqueça uma frigideira que não gruda com metade do azeite em fogo médio-alto e doure os filés por 2 a 3 minutos de cada lado, até ficarem dourados e cozidos. Tire e deixe de lado.",
   "Na mesma frigideira, com o restante do azeite, frite a cebola e o alho por 2 minutos. Junte os cogumelos e cozinhe por 4 minutos, até murcharem (ficarem molinhos) e soltarem a água.",
   "Abaixe o fogo, desligue e junte o iogurte, mexendo — fora do fogo ele não talha (não vira grumos). Acerte o sal e a pimenta.",
   "Volte os filés à frigideira para se cobrirem do molho. Salpique salsinha e sirva com um pouco de arroz ou purê."],
 "porcoes8": ["1 filé · 2 col. arroz",
              "1 filé · 3 col. arroz",
              "1 filé grande · 3 col. arroz",
              "1 filé grande · 4 col. arroz",
              "1 filé grande · 4 col. arroz",
              "2 filés · 4 col. arroz",
              "2 filés · 5 col. arroz",
              "2 filés · 6 col. arroz"],
 "dica": "O peru é uma carne branca magra e proteica. O molho cremoso vem do iogurte, não do creme de leite, cortando muita gordura. Os cogumelos dão sabor intenso e corpo ao molho com pouquíssima caloria — um jantar sofisticado e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of thin turkey escalopes in a creamy mushroom sauce, garnished with parsley, served with a little rice, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ovos ao Forno no Molho de Tomate com Frango",
 "hook": "Ovos cozidos dentro de um molho de tomate temperado, com pedacinhos de frango — um jantar quentinho e diferente, direto da frigideira à mesa.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 370,
 "ings": ["4 ovos", "1 filé de peito de frango cozido e desfiado (≈ 120 g)", "3 tomates maduros picados (ou molho de tomate)",
          "1 cebola picada", "1 dente de alho picado", "½ pimentão picado", "1 colher de chá de azeite",
          "sal, pimenta, páprica e cheiro-verde a gosto", "pão integral para servir"],
 "passos": [
   "Numa frigideira que possa ir ao forno (ou funda), aqueça o azeite e frite a cebola, o alho e o pimentão por 3 minutos, mexendo.",
   "Junte os tomates picados, a páprica, sal e pimenta e cozinhe por 8 minutos, até virar um molho encorpado. Junte o frango desfiado e misture.",
   "Com uma colher, faça pequenos buracos no molho. Quebre um ovo dentro de cada buraco, sem misturar, para as gemas ficarem inteiras.",
   "Tampe a frigideira e cozinhe em fogo baixo por 6 a 8 minutos, até as claras firmarem e as gemas ficarem no ponto que você gosta. (Ou leve ao forno médio por 10 minutos.)",
   "Salpique cheiro-verde e sirva na própria frigideira, com fatias de pão integral para acompanhar."],
 "porcoes8": ["1 ovo · frango · molho",
              "2 ovos · frango · molho",
              "2 ovos · frango · 1 fatia pão",
              "2 ovos · frango extra · 1 fatia pão",
              "2 ovos · frango extra · 1 fatia pão",
              "2 ovos · frango · 2 fatias pão",
              "3 ovos · frango extra · 2 fatias pão",
              "3 ovos · frango duplo · 2 fatias pão"],
 "dica": "Os ovos são proteína completa e muito saciante, e cozidos no molho de tomate ficam leves, sem fritura. O frango soma ainda mais proteína e o molho enche o prato com o volume dos tomates. É um jantar quentinho, barato e reconfortante que sacia bem.",
 "prompt": "Square ultra-realistic overhead food photograph of baked eggs in a spiced tomato sauce with shredded chicken and pepper in a skillet, sprinkled with parsley, a slice of wholegrain bread beside it, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Espetinho de Camarão com Legumes",
 "hook": "Camarões rosados e legumes coloridos espetados juntos, grelhados até dourar — leve, bonito e com clima de festa.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 360,
 "ings": ["250 g de camarão limpo e grande", "1 pimentão em quadrados", "1 cebola em pedaços",
          "1 abobrinha em rodelas grossas", "tomatinhos", "2 dentes de alho picados", "1 colher de chá de azeite",
          "suco de 1 limão", "sal, pimenta e páprica a gosto", "palitos de espeto"],
 "passos": [
   "Tempere os camarões com sal, pimenta, páprica, o alho e o suco de limão. Deixe pegar gosto por 10 minutos.",
   "Monte os espetos alternando um camarão, um quadrado de pimentão, um pedaço de cebola, uma rodela de abobrinha e um tomatinho, até encher o palito.",
   "Pincele os espetos com o azeite.",
   "Aqueça uma frigideira grande ou grelha em fogo médio-alto. Coloque os espetos e vá girando a cada 2 minutos, por uns 8 minutos no total, só até os camarões ficarem rosados e enrolarem. Não deixe passar do ponto, senão ficam borrachudos.",
   "Sirva os espetinhos com uma salada ou um pouco de arroz."],
 "porcoes8": ["1 espeto · salada",
              "2 espetos · salada",
              "2 espetos · salada · 2 col. arroz",
              "2 espetos · salada · 3 col. arroz",
              "2 espetos · salada · 3 col. arroz",
              "3 espetos · salada · 3 col. arroz",
              "3 espetos · salada · 4 col. arroz",
              "3 espetos grandes · salada · 4 col. arroz"],
 "dica": "O camarão é quase todo proteína, com pouquíssima gordura e poucas calorias. Espetado com legumes coloridos e grelhado sem óleo, vira um jantar leve, vistoso e saboroso, que controla a porção de forma natural e agrada até em ocasiões especiais.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled shrimp and vegetable skewers with pepper, onion, zucchini and cherry tomato, on a white plate with a lemon wedge, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salmão Grelhado com Aspargos",
 "hook": "Duas estrelas num prato só: o salmão suculento e os aspargos crocantes — um jantar chique, leve e pronto em quinze minutos.",
 "tempo": "18 min", "rende": "1 porção", "kcal_base": 420,
 "ings": ["1 posta de salmão (≈ 150 g)", "1 maço de aspargos", "1 dente de alho picado", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e raspas de limão a gosto"],
 "passos": [
   "Lave os aspargos e quebre a ponta dura de baixo de cada um (ela se rompe naturalmente no ponto certo quando você dobra).",
   "Tempere o salmão com sal, pimenta, o alho e o suco de limão.",
   "Aqueça uma frigideira que não gruda com metade do azeite em fogo médio. Coloque o salmão com a pele para baixo e deixe 4 minutos, vire e deixe mais 3 minutos, até ficar mais claro e se soltar em lascas.",
   "Ao mesmo tempo, noutra frigideira (ou na mesma, depois de tirar o salmão), salteie os aspargos com o restante do azeite em fogo alto por 4 minutos, mexendo, até ficarem verdes e macios mas ainda crocantes.",
   "Monte o prato com o salmão e os aspargos. Finalize com raspas de limão por cima."],
 "porcoes8": ["120 g salmão · aspargos",
              "150 g salmão · aspargos",
              "150 g salmão · aspargos · 1 batata pequena",
              "170 g salmão · aspargos · 1 batata",
              "170 g salmão · aspargos · 1 batata",
              "200 g salmão · aspargos · 1 batata",
              "220 g salmão · aspargos · 1 batata grande",
              "250 g salmão · aspargos · 2 batatas pequenas"],
 "dica": "O salmão traz proteína e ômega-3, a gordura boa que sacia e protege o coração. Os aspargos são leves, cheios de fibra e ajudam a desinchar, com pouquíssima caloria. Grelhados juntos com pouco óleo, formam um jantar elegante, leve e nutritivo.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled salmon fillet with sautéed green asparagus spears, lemon zest on top, a lemon wedge, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Carne Moída Refogada com Abobrinha (Picadinho)",
 "hook": "Um picadinho rápido de carne com abobrinha e ovo por cima — feito na frigideira em minutos, sacia sem precisar de arroz.",
 "tempo": "20 min", "rende": "2 porções", "kcal_base": 380,
 "ings": ["250 g de carne moída magra", "2 abobrinhas em cubinhos", "1 tomate picado", "1 cebola picada",
          "1 dente de alho picado", "2 ovos", "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto"],
 "passos": [
   "Aqueça o azeite numa frigideira em fogo médio e frite a cebola e o alho por 2 minutos, mexendo.",
   "Junte a carne moída e mexa, quebrando os pedaços com a colher, até perder toda a cor rosada.",
   "Acrescente o tomate e a abobrinha em cubinhos, tempere com sal e pimenta e cozinhe por 8 minutos, mexendo de vez em quando, até a abobrinha ficar macia e soltar o próprio caldo.",
   "Enquanto isso, frite ou cozinhe os ovos à parte (frite com pouquíssimo óleo ou cozinhe por 6 minutos para gema mole).",
   "Sirva o picadinho quente com um ovo por cima de cada porção e cheiro-verde salpicado."],
 "porcoes8": ["½ porção · 1 ovo",
              "1 porção · 1 ovo",
              "1 porção · 1 ovo · 2 col. arroz",
              "1 porção · 1 ovo · 3 col. arroz",
              "1 porção · 2 ovos · 3 col. arroz",
              "1 porção grande · 2 ovos · 3 col. arroz",
              "porção grande · 2 ovos · 4 col. arroz",
              "porção dupla · 2 ovos · 4 col. arroz"],
 "dica": "A abobrinha em cubos se mistura à carne e dá volume ao prato com pouquíssima caloria, ajudando a comer menos carne sem sentir falta. O ovo por cima soma proteína e cremosidade. Sem arroz ou com pouco, é um jantar leve, rápido e muito saciante.",
 "prompt": "Square ultra-realistic overhead food photograph of a ground beef and zucchini sauté topped with a fried egg, sprinkled with parsley, on a white plate, light wooden table, soft natural light, homestyle and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frango à Pizzaiolo com Salada",
 "hook": "O gostinho de pizza sem a massa: o frango grelhado ganha molho de tomate, queijo derretido e orégano — mata a vontade e não pesa.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 400,
 "ings": ["2 filés de peito de frango (≈ 300 g)", "½ xícara de molho de tomate caseiro", "3 colheres de sopa de muçarela magra ralada",
          "rodelas de tomate", "1 colher de chá de azeite", "orégano, sal e pimenta a gosto",
          "folhas verdes para a salada"],
 "passos": [
   "Tempere os filés de frango com sal e pimenta.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio e grelhe os filés por 4 a 5 minutos de cada lado, até dourar e ficar branco por dentro.",
   "Abaixe o fogo. Cubra cada filé com o molho de tomate, uma ou duas rodelas de tomate e a muçarela ralada. Polvilhe orégano.",
   "Tampe a frigideira e deixe 3 a 4 minutos, só até o queijo derreter (esse é o truque para gratinar sem forno).",
   "Sirva com uma salada verde fresca ao lado."],
 "porcoes8": ["100 g frango · pouco queijo · salada",
              "130 g frango · queijo · salada",
              "150 g frango · queijo · salada",
              "150 g frango · queijo · 2 col. arroz",
              "150 g frango · queijo · 3 col. arroz",
              "170 g frango · queijo · 3 col. arroz",
              "200 g frango · queijo · 4 col. arroz",
              "220 g frango · queijo extra · 4 col. arroz"],
 "dica": "Você mata a vontade de pizza com o sabor de molho de tomate, queijo e orégano, mas sem a massa e a gordura. O frango grelhado dá proteína magra e saciedade, e um pouco de queijo derretido é suficiente para o prazer do gratinado. Leve e satisfatório.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast topped with tomato sauce, melted mozzarella and oregano, with tomato slices, a fresh green salad beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peixe Grelhado com Legumes na Frigideira",
 "hook": "Tudo numa frigideira só: o peixe doura de um lado enquanto os legumes saltam do outro — jantar leve, rápido e sem bagunça.",
 "tempo": "20 min", "rende": "1 porção", "kcal_base": 380,
 "ings": ["1 filé de peixe branco (pescada, merluza ou tilápia, ≈ 150 g)", "1 abobrinha em meias-luas",
          "½ pimentão em tiras", "tomatinhos", "1 dente de alho picado", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Tempere o peixe com sal, pimenta, o alho e o suco de limão.",
   "Aqueça uma frigideira grande com metade do azeite em fogo médio-alto. De um lado, coloque o filé e deixe 3 a 4 minutos de cada lado, virando com cuidado, até dourar e se soltar em lascas.",
   "Do outro lado da frigideira (ou depois de tirar o peixe), coloque o restante do azeite e salteie a abobrinha, o pimentão e os tomatinhos por 4 a 5 minutos, mexendo, até ficarem macios mas ainda firmes.",
   "Tempere os legumes com sal e pimenta.",
   "Monte o prato com o peixe e os legumes salteados. Salpique salsinha e finalize com mais um pouco de limão."],
 "porcoes8": ["120 g peixe · legumes",
              "150 g peixe · legumes",
              "150 g peixe · legumes · 1 batata pequena",
              "170 g peixe · legumes · 1 batata",
              "170 g peixe · legumes · 1 batata",
              "200 g peixe · legumes · 1 batata",
              "220 g peixe · legumes · 1 batata grande",
              "250 g peixe · legumes · 2 batatas pequenas"],
 "dica": "O peixe branco é leve e cozinha em minutos, e feito na mesma frigideira dos legumes usa pouquíssimo óleo. Os legumes salteados dão cor, fibra e volume por quase nenhuma caloria. É um dos jantares mais rápidos, leves e práticos que existem.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-grilled white fish fillet with sautéed zucchini, pepper and cherry tomatoes, parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peito de Peru Grelhado com Purê de Abóbora",
 "hook": "O peru magro sobre um purê de abóbora naturalmente docinho e alaranjado — um jantar leve com cara de aconchego.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 390,
 "ings": ["1 filé de peito de peru (≈ 150 g)", "1 pedaço de abóbora em cubos (≈ 300 g)", "1 dente de alho picado",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta, sálvia ou alecrim a gosto",
          "folhas verdes para a salada"],
 "passos": [
   "Cozinhe a abóbora em água fervente por 15 minutos, até ficar bem macia. Escorra muito bem e amasse com um garfo, com uma pitada de sal, até virar um purê liso e cremoso.",
   "Tempere o peru com sal, pimenta, o alho e o suco de limão.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio e grelhe o filé por 3 a 4 minutos de cada lado, até dourar e ficar branco por dentro.",
   "Se gostar, finalize o peru com um pouco de sálvia ou alecrim na frigideira nos últimos segundos, para perfumar.",
   "Monte o prato com o purê de abóbora, o peru fatiado por cima e uma salada verde ao lado."],
 "porcoes8": ["120 g peru · ½ porção purê · salada",
              "150 g peru · 1 porção purê · salada",
              "150 g peru · 1 porção purê · salada",
              "170 g peru · 1 porção purê · salada",
              "170 g peru · 1 porção purê · salada",
              "200 g peru · 1 porção grande purê · salada",
              "220 g peru · porção grande purê · salada",
              "250 g peru · porção dupla purê · salada"],
 "dica": "O peito de peru é ainda mais magro que o frango, cheio de proteína. A abóbora faz um purê cremoso e docinho com pouquíssimas calorias, matando a vontade de doce e enchendo o prato com fibra. Um jantar leve, reconfortante e colorido.",
 "prompt": "Square ultra-realistic overhead food photograph of sliced grilled turkey breast over a smooth orange pumpkin mash, with a small green salad, sage on top, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sopa de Frango com Macarrão (Canja Reforçada)",
 "hook": "A canja de sempre, turbinada com bastante frango e legumes — o jantar que abraça, cura e ainda cabe na dieta.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 360,
 "ings": ["1 filé de peito de frango (≈ 150 g)", "½ xícara de macarrão pequeno (aletria ou tipo argolinha)",
          "1 cenoura em cubinhos", "1 talo de salsão picado (opcional)", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto", "1,2 litro de água"],
 "passos": [
   "Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos, mexendo.",
   "Junte o filé de frango inteiro, a cenoura, o salsão e a água. Tempere com sal e cozinhe por 15 minutos, até o frango ficar cozido.",
   "Retire o frango, deixe amornar e desfie. Volte o frango desfiado à panela.",
   "Junte o macarrão pequeno e cozinhe por mais 8 a 10 minutos, até o macarrão ficar macio (mexa de vez em quando para não grudar no fundo).",
   "Prove o sal, salpique cheiro-verde e sirva bem quente."],
 "porcoes8": ["1 concha · frango",
              "2 conchas · frango",
              "2 conchas · frango",
              "2 conchas · frango extra",
              "2 conchas · frango extra · macarrão extra",
              "3 conchas · frango",
              "3 conchas · frango extra · macarrão extra",
              "3 conchas grandes · frango duplo"],
 "dica": "A canja é leve e reconfortante: o caldo com legumes enche o estômago com poucas calorias e o frango dá a proteína que sacia. Com pouco macarrão e muito frango e legume, ela vira um jantar completo e quentinho, ideal para noites frias ou dias sem apetite.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken noodle soup with shredded chicken, small pasta, carrot and celery in a golden broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Camarão ao Curry Leve com Legumes",
 "hook": "Camarões banhados num molho dourado de curry e leite de coco light — perfumado, cremoso e surpreendentemente leve.",
 "tempo": "25 min", "rende": "2 porções", "kcal_base": 380,
 "ings": ["300 g de camarão limpo", "1 cebola picada", "1 dente de alho picado", "1 pimentão em tiras",
          "1 colher de chá de curry em pó", "½ xícara de leite de coco light", "1 tomate picado",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta e coentro a gosto", "arroz para servir"],
 "passos": [
   "Tempere os camarões com sal, pimenta e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Aqueça o azeite numa frigideira em fogo médio e frite a cebola, o alho e o pimentão por 3 minutos, mexendo.",
   "Junte o curry e mexa por 30 segundos, para o tempero soltar o aroma. Acrescente o tomate e cozinhe por 3 minutos, até desmanchar.",
   "Junte o leite de coco light e deixe ferver de leve. Coloque os camarões e cozinhe por 3 a 4 minutos, só até ficarem rosados. Não passe do ponto, senão ficam borrachudos.",
   "Salpique coentro e sirva sobre uma porção pequena de arroz."],
 "porcoes8": ["120 g camarão · 2 col. arroz",
              "150 g camarão · 3 col. arroz",
              "150 g camarão · 3 col. arroz",
              "170 g camarão · 4 col. arroz",
              "170 g camarão · 4 col. arroz",
              "200 g camarão · 4 col. arroz",
              "220 g camarão · 5 col. arroz",
              "250 g camarão · 5 col. arroz"],
 "dica": "O camarão é quase pura proteína e cozinha rápido. O leite de coco light dá cremosidade ao molho com bem menos gordura que o creme de leite, e o curry perfuma e dá a sensação de um prato especial. Com pouco arroz, é um jantar leve e cheio de sabor.",
 "prompt": "Square ultra-realistic overhead food photograph of shrimp in a light golden coconut curry sauce with pepper, served with a little white rice, coriander on top, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ensopado de Carne com Batata",
 "hook": "Cubos de carne que se desmancham num caldo grosso com batata — o ensopado que conforta numa noite fria, na porção certa.",
 "tempo": "1 h", "rende": "3 porções", "kcal_base": 430,
 "ings": ["300 g de carne magra em cubos (músculo ou acém magro)", "2 batatas em cubos grandes", "1 cenoura em rodelas",
          "1 cebola picada", "2 dentes de alho picados", "1 tomate picado", "1 folha de louro",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto"],
 "passos": [
   "Tempere os cubos de carne com sal e pimenta. Numa panela, aqueça o azeite e doure a carne por todos os lados, mexendo, por 6 minutos.",
   "Junte a cebola e o alho e frite por 2 minutos. Acrescente o tomate e a folha de louro e mexa por 2 minutos.",
   "Cubra com água quente, tampe e cozinhe em fogo baixo por 35 minutos, até a carne começar a amaciar. Se secar, junte mais água quente.",
   "Junte a batata e a cenoura e cozinhe por mais 20 minutos, até a carne desmanchar e a batata ficar macia (a batata ajuda a engrossar o caldo).",
   "Retire a folha de louro, salpique cheiro-verde e sirva quente, puro ou com um pouco de arroz."],
 "porcoes8": ["½ porção · sem arroz",
              "1 porção · sem arroz",
              "1 porção · 2 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção · 3 col. arroz",
              "1 porção grande · 4 col. arroz",
              "porção grande · 5 col. arroz",
              "porção dupla · 5 col. arroz"],
 "dica": "O cozimento lento amacia cortes magros e baratos, e a batata engrossa o caldo naturalmente, dispensando farinha ou creme. É um prato substancioso que sacia bastante com calorias controladas — o conforto de um ensopado sem sair da linha.",
 "prompt": "Square ultra-realistic overhead food photograph of a beef stew with tender beef chunks, potato and carrot in a thick broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Omelete de Forno com Presunto Magro e Legumes",
 "hook": "Uma omelete alta e fofa assada no forno, recheada de legumes e presunto magro — corta em fatias e rende para a família.",
 "tempo": "30 min", "rende": "3 porções", "kcal_base": 360,
 "ings": ["6 ovos", "4 fatias de presunto magro (de peru) picadas", "½ pimentão picado", "1 tomate picado",
          "punhado de espinafre", "2 colheres de sopa de queijo ralado magro", "1 colher de chá de azeite",
          "cebolinha, sal e pimenta a gosto"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Pincele um refratário pequeno com o azeite.",
   "Numa tigela, bata os ovos com sal e pimenta por 30 segundos.",
   "Junte aos ovos o presunto picado, o pimentão, o tomate, o espinafre e a cebolinha, e misture.",
   "Despeje a mistura no refratário e polvilhe o queijo ralado por cima.",
   "Leve ao forno por 20 a 25 minutos, até a omelete inflar, firmar no centro e dourar levemente por cima. Corte em fatias e sirva quente ou morno, com uma salada."],
 "porcoes8": ["1 fatia · salada",
              "1 fatia grande · salada",
              "1 fatia grande · salada · 1 fatia pão",
              "2 fatias · salada · 1 fatia pão",
              "2 fatias · salada · 1 fatia pão",
              "2 fatias grandes · salada · 1 fatia pão",
              "2 fatias grandes · salada · 2 fatias pão",
              "3 fatias · salada · 2 fatias pão"],
 "dica": "Os ovos são proteína completa e muito saciante, e assados no forno dispensam a fritura. O presunto magro de peru soma sabor e proteína com pouca gordura, e os legumes dão volume e fibra. Rende bastante, guarda bem e é um jantar leve e prático.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked oven omelette (frittata) with lean ham, pepper, tomato and spinach, cut into slices, in a baking dish, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tilápia ao Forno com Tomate e Cebola",
 "hook": "Filés de peixe branco assados sob uma cama de tomate e cebola que viram um molho natural — leve, suculento e sem esforço.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 370,
 "ings": ["2 filés de tilápia (ou outro peixe branco, ≈ 300 g)", "2 tomates em rodelas", "1 cebola em rodelas",
          "1 dente de alho fatiado", "1 colher de chá de azeite", "suco de 1 limão",
          "sal, pimenta, orégano e salsinha a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Num refratário, espalhe metade das rodelas de tomate e cebola no fundo, formando uma cama.",
   "Tempere os filés de peixe com sal, pimenta, o alho, o orégano e o suco de limão. Coloque-os sobre a cama de tomate e cebola.",
   "Cubra os filés com o restante do tomate e da cebola e regue com o azeite.",
   "Leve ao forno por 20 a 25 minutos, até o peixe se soltar em lascas e o tomate e a cebola ficarem macios, soltando um molho natural.",
   "Salpique salsinha e sirva com o molho por cima, acompanhado de uma salada ou um pouco de arroz."],
 "porcoes8": ["120 g peixe · legumes",
              "150 g peixe · legumes",
              "150 g peixe · legumes · 2 col. arroz",
              "170 g peixe · legumes · 3 col. arroz",
              "170 g peixe · legumes · 3 col. arroz",
              "200 g peixe · legumes · 3 col. arroz",
              "220 g peixe · legumes · 4 col. arroz",
              "250 g peixe · legumes · 4 col. arroz"],
 "dica": "O peixe branco é magríssimo e proteico, e assar sob tomate e cebola cria um molho natural sem gordura, mantendo o filé suculento. É um jantar leve, barato e cheio de sabor, que praticamente se faz sozinho no forno.",
 "prompt": "Square ultra-realistic overhead food photograph of baked white fish fillets topped with tomato and onion slices forming a natural sauce, sprinkled with parsley and oregano, in a white dish, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Almôndegas de Frango na Sopa",
 "hook": "Bolinhas macias de frango cozidas num caldo leve com legumes — uma sopa divertida e completa, que sacia e aquece.",
 "tempo": "35 min", "rende": "3 porções", "kcal_base": 350,
 "ings": ["300 g de peito de frango moído", "1 ovo", "2 colheres de sopa de aveia", "1 cenoura em cubinhos",
          "1 batata em cubinhos", "1 abobrinha em cubinhos", "1 cebola picada", "1 dente de alho picado",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto", "1,2 litro de água"],
 "passos": [
   "Numa tigela, misture o frango moído, o ovo, a aveia, sal e pimenta. Amasse com as mãos e enrole bolinhas pequenas do tamanho de uma noz.",
   "Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos. Junte a água, a cenoura e a batata, tempere com sal e cozinhe por 10 minutos.",
   "Com cuidado, coloque as almôndegas cruas dentro do caldo fervente, uma a uma. Não mexa por 3 minutos, para elas firmarem.",
   "Junte a abobrinha e cozinhe por mais 10 minutos, até as almôndegas ficarem cozidas por dentro e os legumes macios.",
   "Prove o sal, salpique cheiro-verde e sirva bem quente."],
 "porcoes8": ["3 almôndegas · 1 concha caldo",
              "4 almôndegas · 2 conchas",
              "4 almôndegas · 2 conchas",
              "5 almôndegas · 2 conchas · 1 fatia pão",
              "5 almôndegas · 2 conchas · 1 fatia pão",
              "6 almôndegas · 3 conchas · 1 fatia pão",
              "7 almôndegas · 3 conchas · 2 fatias pão",
              "8 almôndegas · 3 conchas · 2 fatias pão"],
 "dica": "As almôndegas de frango dão a proteína que sacia, e cozidas dentro da sopa deixam o caldo mais gostoso. O muito líquido e os legumes enchem o estômago com poucas calorias. É um jantar completo, leve e reconfortante, que agrada até quem não gosta de sopa rala.",
 "prompt": "Square ultra-realistic overhead food photograph of a light soup with small chicken meatballs, carrot, potato and zucchini in a clear broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Camarão Grelhado com Salada de Folhas",
 "hook": "Camarões dourados no alho sobre uma salada fresca e crocante — um jantar leve, elegante e pronto em quinze minutos.",
 "tempo": "15 min", "rende": "1 porção", "kcal_base": 330,
 "ings": ["150 g de camarão limpo e grande", "folhas verdes variadas", "½ tomate em cubos", "½ pepino em rodelas",
          "cebola roxa em fatias finas", "2 dentes de alho picados", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e salsinha a gosto"],
 "passos": [
   "Seque bem os camarões com papel-toalha e tempere com sal, pimenta e metade do suco de limão.",
   "Aqueça uma frigideira que não gruda com o azeite em fogo médio-alto. Junte o alho e mexa por 30 segundos, só até cheirar.",
   "Coloque os camarões e grelhe por 2 a 3 minutos de cada lado, só até ficarem rosados e dourados. Não passe do ponto.",
   "Numa tigela grande ou prato, monte a salada com as folhas verdes, o tomate, o pepino e a cebola roxa. Tempere com o restante do limão, sal e pimenta.",
   "Coloque os camarões quentes por cima da salada, salpique salsinha e sirva na hora."],
 "porcoes8": ["120 g camarão · salada",
              "150 g camarão · salada",
              "150 g camarão · salada · 1 fatia pão",
              "170 g camarão · salada · 1 fatia pão",
              "170 g camarão · salada · 2 col. arroz",
              "200 g camarão · salada · 3 col. arroz",
              "220 g camarão · salada · 3 col. arroz",
              "250 g camarão · salada · 4 col. arroz"],
 "dica": "O camarão é quase pura proteína, com pouquíssimas calorias, então enche o prato sem pesar. Dourado no alho e servido sobre uma salada fresca e crocante, é um dos jantares mais leves possíveis — ideal para a noite, quando o corpo gasta menos energia.",
 "prompt": "Square ultra-realistic overhead food photograph of golden garlic grilled shrimp served over a fresh salad of green leaves, tomato, cucumber and red onion, a lemon wedge, in a bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Peixe Ensopado com Leite de Coco e Legumes",
 "hook": "Um ensopado cremoso e perfumado de peixe com um toque de leite de coco — leve como o mar, reconfortante como um abraço.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 390,
 "ings": ["300 g de filé de peixe branco em pedaços grandes", "1 pimentão em tiras", "1 tomate picado", "1 cebola em tiras",
          "2 dentes de alho picados", "½ xícara de leite de coco light", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e coentro a gosto"],
 "passos": [
   "Tempere os pedaços de peixe com sal, pimenta, o alho e o suco de limão. Deixe pegar gosto por 5 minutos.",
   "Numa panela larga, aqueça o azeite e faça uma cama com a cebola, o pimentão e o tomate. Refogue por 3 minutos, mexendo.",
   "Coloque os pedaços de peixe por cima dos legumes (não mexa muito, para o peixe não desmanchar).",
   "Regue com o leite de coco light, tampe e cozinhe em fogo médio-baixo por 10 a 12 minutos, até o peixe ficar branco e macio e o caldo encorpar.",
   "Salpique coentro e sirva com uma porção pequena de arroz, para aproveitar o caldo."],
 "porcoes8": ["120 g peixe · 2 col. arroz",
              "150 g peixe · 3 col. arroz",
              "150 g peixe · 3 col. arroz",
              "170 g peixe · 4 col. arroz",
              "170 g peixe · 4 col. arroz",
              "200 g peixe · 4 col. arroz",
              "220 g peixe · 5 col. arroz",
              "250 g peixe · 5 col. arroz"],
 "dica": "O peixe branco é magro e proteico, e o leite de coco light dá cremosidade ao caldo com bem menos gordura que o creme de leite. Os legumes soltam água e formam um molho leve e perfumado. É um ensopado reconfortante e leve, perfeito para o jantar.",
 "prompt": "Square ultra-realistic overhead food photograph of a fish stew with chunks of white fish, pepper, onion and tomato in a light coconut broth, in a rustic bowl, coriander on top, a little rice beside it, on a light wooden table, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Espetinho de Carne com Legumes",
 "hook": "Cubos de carne suculentos alternados com legumes coloridos, grelhados até dourar — sabor de churrasco na medida certa.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 420,
 "ings": ["250 g de carne magra em cubos (alcatra ou patinho)", "1 pimentão em quadrados", "1 cebola em pedaços",
          "1 abobrinha em rodelas grossas", "tomatinhos", "1 dente de alho picado", "1 colher de chá de azeite",
          "sal, pimenta e páprica a gosto", "palitos de espeto"],
 "passos": [
   "Tempere os cubos de carne com sal, pimenta, páprica e o alho. Deixe pegar gosto por 10 minutos.",
   "Monte os espetos alternando um cubo de carne, um quadrado de pimentão, um pedaço de cebola, uma rodela de abobrinha e um tomatinho, até encher o palito.",
   "Pincele os espetos com o azeite.",
   "Aqueça uma frigideira grande ou grelha em fogo médio-alto. Coloque os espetos e vá girando a cada 3 minutos, por uns 12 minutos no total, até a carne dourar por fora e ficar no ponto que você gosta.",
   "Sirva os espetinhos com uma salada ou um pouco de arroz."],
 "porcoes8": ["1 espeto · salada",
              "2 espetos · salada",
              "2 espetos · salada · 2 col. arroz",
              "2 espetos · salada · 3 col. arroz",
              "2 espetos · salada · 3 col. arroz",
              "3 espetos · salada · 3 col. arroz",
              "3 espetos · salada · 4 col. arroz",
              "3 espetos grandes · salada · 4 col. arroz"],
 "dica": "Os espetinhos matam a vontade de churrasco de forma leve: a carne magra dá proteína e os legumes coloridos enchem o espeto com fibra e pouca caloria. Espetar ajuda a controlar a porção naturalmente, e grelhar sem óleo mantém tudo saboroso e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled beef and vegetable skewers with pepper, onion, zucchini and cherry tomato, on a white plate with a fresh salad, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salada Quente de Frango, Ovo e Batata",
 "hook": "Batatas douradas, frango grelhado e ovo, tudo morno sobre folhas fresquinhas — uma salada que é jantar completo e aconchegante.",
 "tempo": "30 min", "rende": "1 porção", "kcal_base": 420,
 "ings": ["1 filé de peito de frango (≈ 130 g)", "1 batata pequena em cubos", "2 ovos cozidos",
          "folhas verdes", "tomatinhos", "cebola roxa em fatias", "1 colher de chá de azeite",
          "suco de ½ limão", "sal, pimenta e mostarda a gosto"],
 "passos": [
   "Cozinhe os cubos de batata em água fervente com sal por 12 minutos, até ficarem macios. Escorra. Se quiser dourar, salteie por 3 minutos numa frigideira com poucas gotas de azeite.",
   "Cozinhe os ovos por 9 minutos, passe em água fria, descasque e corte ao meio.",
   "Tempere o frango com sal e pimenta e grelhe numa frigideira que não gruda por 4 a 5 minutos de cada lado, até dourar. Corte em tiras.",
   "Numa tigela ou prato, faça uma cama de folhas verdes e coloque os tomatinhos e a cebola.",
   "Distribua por cima a batata morna, o frango em tiras e os ovos. Faça um molho misturando o azeite, o suco de limão, a mostarda, sal e pimenta, regue e sirva na hora."],
 "porcoes8": ["100 g frango · ½ batata · 1 ovo",
              "130 g frango · 1 batata pequena · 2 ovos",
              "130 g frango · 1 batata · 2 ovos",
              "150 g frango · 1 batata · 2 ovos",
              "150 g frango · 1 batata · 2 ovos",
              "170 g frango · 1 batata grande · 2 ovos",
              "200 g frango · 1 batata grande · 3 ovos",
              "220 g frango · 2 batatas pequenas · 3 ovos"],
 "dica": "É uma salada que sacia como uma refeição quente: o frango e o ovo dão proteína dobrada, a batata na medida certa traz energia e as folhas enchem o prato com fibra. Servida morna, é reconfortante e leve ao mesmo tempo — ideal para o jantar.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm salad with grilled chicken strips, golden potato cubes, halved boiled eggs, green leaves, cherry tomatoes and red onion, mustard dressing, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
