# -*- coding: utf-8 -*-
"""30 receitas de CAFE DA MANHA (001-030). ITALIANO.

Traducao literal de `receitas_cafe_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario de cozinha italiana de verdade (fiocchi
d'avena, fiocchi di latte, frutti di bosco, padella antiaderente).
⛔ METRICO, e a Italia pesa MAIS que os outros: a cozinha italiana e' de
balanca. g, ml, °C, kg, km — como pt/de/fr/es. O EN e' o unico imperial do
produto; os numeros metricos vem do pt/de/fr, nunca de oz -> g de volta.
   `1/2 cup rolled oats` -> `40 g di fiocchi d'avena` · `6 oz` -> `170 g`
   `350 °F` -> `180 °C` · `325 °F` -> `160 °C`
⛔ O campo `prompt` NAO e' replicado: a foto e' a mesma (fotos/NNN, sem texto).
"""

RECEITAS = [
{
 "nome": "Pancake di banana e avena",
 "hook": "Tre ingredienti che hai già in casa, pronti in 10 minuti — e ti tengono sazia fino a pranzo.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 325,
 "ings": ["1 banana matura", "40 g di fiocchi d'avena (circa 4 cucchiai)", "1 uovo",
          "1 pizzico di cannella", "1 pizzico di lievito per dolci (facoltativo, li rende più soffici)",
          "un po' di olio o olio spray per la padella"],
 "passos": [
   "Sbuccia la banana e mettila in un piatto fondo. Schiacciala bene con la forchetta finché non diventa una purea liscia, senza grumi grossi.",
   "Aggiungi l'uovo e mescola finché tutto non è ben amalgamato.",
   "Aggiungi l'avena, la cannella e il lievito. Mescola e lascia riposare 3 minuti — l'avena assorbe l'umidità e l'impasto si compatta, il che rende più facile girarli dopo.",
   "Scalda una padella antiaderente a fuoco medio-basso e ungila con un po' di olio (o usa lo spray).",
   "Con un cucchiaio, versa piccole porzioni di impasto nella padella, grandi più o meno come mezzo palmo della mano. I pancake piccoli si girano molto più facilmente di quelli grandi.",
   "Falli cuocere per 2-3 minuti, finché non compaiono bollicine in superficie e i bordi non si rassodano. Girali con delicatezza e fai dorare l'altro lato per altri 1-2 minuti.",
   "Servi caldi. Se ti va, completa con fettine di banana, una manciata di frutti di bosco o 1 cucchiaino di miele."],
 "porcoes8": ["¾ banana · 30 g di avena · 1 uovo",
              "1 banana · 40 g di avena · 1 uovo · 1 manciata di frutti di bosco",
              "1 banana · 45 g di avena · 1 uovo · 1 cucchiaino di burro di arachidi",
              "1 banana · 50 g di avena · 1 uovo · 1 cucchiaio di burro di arachidi",
              "1 banana · 50 g di avena · 2 uova · 1 cucchiaino di burro di arachidi",
              "1 banana grande · 55 g di avena · 2 uova · 1 cucchiaio di burro di arachidi",
              "1 banana grande · 60 g di avena · 2 uova · 1 cucchiaio di burro di arachidi · frutti di bosco",
              "1 banana grande · 70 g di avena · 2 uova · 1,5 cucchiai di burro di arachidi"],
 "dica": "L'avena è ricca di fibre, che rallentano la digestione e ti tengono sazia per ore — è questo che evita la fame di metà mattina che ti fa spizzicare. La banana porta dolcezza naturale senza zuccheri aggiunti, e l'uovo porta proteine per proteggere il muscolo mentre perdi grasso.",
},
{
 "nome": "Uova strapazzate con spinaci e pane integrale tostato",
 "hook": "La colazione classica che riempie il piatto di proteine e fibre in meno di 10 minuti.",
 "tempo": "8 min", "rende": "1 porzione", "kcal_base": 340,
 "ings": ["2 uova", "1 manciata abbondante di foglie di spinaci freschi",
          "1 fetta di pane integrale", "1 cucchiaino di olio d'oliva",
          "sale e pepe q.b.", "1 pomodoro piccolo (facoltativo)"],
 "passos": [
   "Lava gli spinaci e scolali bene. Se le foglie sono grandi, tagliale a metà.",
   "Rompi le uova in una ciotola, condisci con sale e pepe e sbattile leggermente con la forchetta.",
   "Scalda l'olio d'oliva in una padella antiaderente a fuoco medio. Aggiungi gli spinaci e mescola per 1 minuto, giusto finché non appassiscono (le foglie si ammorbidiscono).",
   "Abbassa la fiamma, versa le uova sbattute sugli spinaci e lasciale 30 secondi senza mescolare.",
   "Con una spatola, spingi le uova lentamente dal fondo verso il centro, finché non sono cremose e ancora umide. Spegni il fuoco prima che si asciughino.",
   "Tosta la fetta di pane integrale. Servi le uova sopra o accanto, con fettine di pomodoro se ti va."],
 "porcoes8": ["1 uovo + 1 albume · ½ fetta di pane · spinaci, quanti ne vuoi",
              "2 uova · 1 fetta di pane · spinaci, quanti ne vuoi",
              "2 uova · 1 fetta di pane · un po' più di olio d'oliva",
              "2 uova + 1 albume · 1 fetta di pane · 1 cucchiaino di formaggio grattugiato",
              "3 uova · 1 fetta di pane · 1 cucchiaino di olio d'oliva",
              "3 uova · 2 fette di pane · spinaci, quanti ne vuoi",
              "3 uova · 2 fette di pane · 1 cucchiaio di formaggio grattugiato",
              "4 uova · 2 fette di pane · 1 cucchiaio di formaggio grattugiato"],
 "dica": "Le uova sono una proteina completa e molto saziante — chi mangia uova a colazione sente meno fame durante la giornata. Gli spinaci aggiungono volume e fibre con quasi zero calorie, così riempi il piatto e lo stomaco senza far saltare le tue calorie.",
},
{
 "nome": "Yogurt greco con frutti di bosco e avena",
 "hook": "Costruito a strati, senza nessuna cottura — proteine e fibre in un bel bicchiere in 3 minuti.",
 "tempo": "3 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["1 vasetto di yogurt greco naturale senza zucchero (circa 170 g)",
          "1 manciata di frutti di bosco (fragola, mirtillo o lampone)",
          "3 cucchiai di fiocchi d'avena", "1 cucchiaino di miele (facoltativo)",
          "cannella q.b."],
 "passos": [
   "Se usi le fragole, lavale e tagliale a pezzetti. Gli altri frutti di bosco possono andare interi.",
   "In un bicchiere o in una tazza, metti metà dello yogurt sul fondo.",
   "Distribuisci sopra metà dei frutti di bosco e metà dell'avena.",
   "Ripeti: il resto dello yogurt, poi i frutti di bosco e l'avena rimasti.",
   "Completa con un pizzico di cannella e, se ti va, il filo di miele. Servi subito, finché l'avena è ancora croccante."],
 "porcoes8": ["120 g di yogurt · frutti di bosco · 2 cucchiai di avena",
              "170 g di yogurt · frutti di bosco · 3 cucchiai di avena",
              "170 g di yogurt · frutti di bosco · 3 cucchiai di avena · 1 cucchiaino di miele",
              "200 g di yogurt · frutti di bosco · 4 cucchiai di avena · 1 cucchiaino di miele",
              "200 g di yogurt · frutti di bosco · 4 cucchiai di avena · 1 cucchiaio di noci",
              "250 g di yogurt · frutti di bosco · 4 cucchiai di avena · 1 cucchiaio di noci",
              "250 g di yogurt · frutti di bosco · 5 cucchiai di avena · 1 cucchiaio di noci",
              "300 g di yogurt · frutti di bosco · 6 cucchiai di avena · 1 cucchiaio di noci"],
 "dica": "Lo yogurt greco ha quasi il doppio delle proteine dello yogurt normale, e questo ti tiene sazia più a lungo. Senza zuccheri aggiunti, la dolcezza arriva dalla frutta — e l'avena porta fibre e croccantezza, trasformando uno spuntino veloce in un pasto che ti sostiene.",
},
{
 "nome": "Omelette di albumi con pomodoro e fiocchi di latte",
 "hook": "Leggera, soffice e piena di proteine — la colazione per chi vuole dimagrire senza soffrire la fame.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 250,
 "ings": ["3 albumi + 1 uovo intero", "1 pomodoro piccolo, tagliato a pezzetti",
          "2 cucchiai di fiocchi di latte", "erba cipollina o prezzemolo tritati",
          "sale e pepe q.b.", "olio spray"],
 "passos": [
   "Taglia il pomodoro a cubetti piccoli e tampona il liquido in eccesso con la carta da cucina, così l'omelette non diventa molliccia.",
   "In una ciotola, metti gli albumi, l'uovo intero, sale e pepe. Sbatti con la forchetta per 30 secondi, finché non fa una leggera schiuma.",
   "Scalda una padella antiaderente a fuoco medio e spruzzala con l'olio. Distribuisci il pomodoro a pezzetti sul fondo per 1 minuto.",
   "Versa sopra le uova sbattute e inclina la padella per distribuirle in modo uniforme.",
   "Quando i bordi si rassodano (1-2 minuti), distribuisci i fiocchi di latte su metà dell'omelette.",
   "Con la spatola, piega l'omelette a metà, coprendo i fiocchi di latte. Lasciala ancora un minuto e servi con le erbe sopra."],
 "porcoes8": ["2 albumi + 1 uovo · 1 cucchiaio di fiocchi di latte",
              "3 albumi + 1 uovo · 2 cucchiai di fiocchi di latte",
              "3 albumi + 1 uovo · 2 cucchiai di fiocchi di latte · ½ fetta di pane",
              "3 albumi + 1 uovo · 3 cucchiai di fiocchi di latte · 1 fetta di pane",
              "3 albumi + 2 uova · 2 cucchiai di fiocchi di latte · 1 fetta di pane",
              "4 albumi + 2 uova · 3 cucchiai di fiocchi di latte · 1 fetta di pane",
              "4 albumi + 2 uova · 3 cucchiai di fiocchi di latte · 2 fette di pane",
              "5 albumi + 2 uova · 4 cucchiai di fiocchi di latte · 2 fette di pane"],
 "dica": "Gli albumi sono quasi proteina pura, con pochissimi grassi e pochissime calorie — perfetti per alzare le proteine della colazione senza appesantirla. I fiocchi di latte arrivano cremosi e anche loro ricchi di proteine, e il pomodoro porta sapore e volume per quasi zero calorie.",
},
{
 "nome": "Avena in ammollo con mela e cannella",
 "hook": "La prepari la sera e la mattina ti aspetta già pronta in frigo — niente fretta, niente fornelli.",
 "tempo": "5 min + frigo", "rende": "1 porzione", "kcal_base": 350,
 "ings": ["40 g di fiocchi d'avena", "150 ml di latte (o bevanda vegetale)",
          "½ mela, tagliata a cubetti piccoli", "1 cucchiaio di yogurt naturale",
          "cannella q.b.", "1 cucchiaino di miele (facoltativo)"],
 "passos": [
   "In un barattolo con il coperchio, mescola l'avena, il latte e lo yogurt.",
   "Aggiungi metà della mela a pezzetti e un bel pizzico di cannella. Mescola bene.",
   "Chiudi il barattolo e mettilo in frigo per almeno 4 ore, o tutta la notte.",
   "Al mattino l'avena sarà cremosa e morbida. Mescola di nuovo.",
   "Completa con il resto della mela fresca e altra cannella. Se ti va, aggiungi il filo di miele. Mangiala fredda, direttamente dal barattolo."],
 "porcoes8": ["30 g di avena · 120 ml di latte · ½ mela",
              "40 g di avena · 150 ml di latte · ½ mela",
              "45 g di avena · 150 ml di latte · ½ mela · 1 cucchiaino di miele",
              "50 g di avena · 180 ml di latte · 1 mela · 1 cucchiaino di miele",
              "50 g di avena · 180 ml di latte · 1 mela · 1 cucchiaio di noci",
              "55 g di avena · 200 ml di latte · 1 mela · 1 cucchiaio di noci",
              "60 g di avena · 220 ml di latte · 1 mela · 1 cucchiaio di noci",
              "70 g di avena · 250 ml di latte · 1 mela · 1,5 cucchiai di noci"],
 "dica": "Mettere l'avena in ammollo non cambia le calorie, ma rende le fibre più facili da digerire e il pasto più cremoso e saziante. Visto che è già pronta in frigo, non salti la colazione quando hai fretta — e saltare i pasti è ciò che porta molte persone a mangiare troppo a fine giornata.",
},
{
 "nome": "Pane tostato con avocado e uovo",
 "hook": "Cremoso, salato e di quelli che saziano davvero — pronto in 8 minuti.",
 "tempo": "8 min", "rende": "1 porzione", "kcal_base": 340,
 "ings": ["1 fetta di pane integrale", "½ avocado maturo (o ¼ di un avocado grande)",
          "1 uovo", "succo di ½ limone",
          "sale, pepe e peperoncino in scaglie q.b.", "olio spray"],
 "passos": [
   "Tosta la fetta di pane integrale finché non è soda e dorata.",
   "In una ciotolina, schiaccia l'avocado con la forchetta, aggiungi il succo di limone, sale e pepe. Mescola finché non diventa una crema.",
   "Scalda una padella antiaderente, spruzzala con l'olio e cuoci l'uovo a fuoco medio, come piace a te (all'occhio di bue con il tuorlo morbido oppure strapazzato).",
   "Spalma la crema di avocado sul pane tostato.",
   "Metti l'uovo sopra e completa con un pizzico di peperoncino in scaglie. Servi subito."],
 "porcoes8": ["½ fetta di pane · ¼ avocado · 1 uovo",
              "1 fetta di pane · ½ avocado · 1 uovo",
              "1 fetta di pane · ½ avocado · 1 uovo · foglie verdi",
              "1 fetta di pane · ½ avocado · 2 uova",
              "1 fetta di pane · ½ avocado · 2 uova · foglie verdi",
              "2 fette di pane · ½ avocado · 2 uova",
              "2 fette di pane · 1 avocado piccolo · 2 uova",
              "2 fette di pane · 1 avocado piccolo · 3 uova"],
 "dica": "L'avocado ha grassi buoni, che ti tengono sazia a lungo e rendono il pasto cremoso senza burro. Insieme all'uovo e al pane integrale, hai grassi buoni, proteine e fibre sulla stessa fetta — la combinazione che tiene a bada la fame per ore.",
},
{
 "nome": "Porridge di avena con banana e burro di arachidi",
 "hook": "Caldo e avvolgente, la colazione che sa di dolce ma gioca a tuo favore.",
 "tempo": "8 min", "rende": "1 porzione", "kcal_base": 380,
 "ings": ["40 g di fiocchi d'avena", "200 ml di latte (o bevanda vegetale)",
          "½ banana, schiacciata", "1 cucchiaino di burro di arachidi",
          "cannella q.b.", "½ banana a fettine per la superficie"],
 "passos": [
   "In un pentolino, metti l'avena, il latte e la banana schiacciata.",
   "Cuoci a fuoco medio-basso, mescolando sempre con un cucchiaio perché non attacchi sul fondo.",
   "Dopo 4-5 minuti il composto si addensa e diventa cremoso. Se lo vuoi più liquido, aggiungi ancora un po' di latte.",
   "Spegni il fuoco, aggiungi la cannella e mescola.",
   "Versalo in una ciotola, completa con le fettine di banana e il burro di arachidi. Servi caldo."],
 "porcoes8": ["30 g di avena · 180 ml di latte · ½ banana · senza burro di arachidi",
              "40 g di avena · 200 ml di latte · 1 banana · 1 cucchiaino di burro di arachidi",
              "45 g di avena · 200 ml di latte · 1 banana · 1 cucchiaino di burro di arachidi",
              "50 g di avena · 220 ml di latte · 1 banana · 1 cucchiaio di burro di arachidi",
              "50 g di avena · 220 ml di latte · 1 banana · 1 cucchiaio di burro di arachidi",
              "55 g di avena · 250 ml di latte · 1 banana · 1 cucchiaio di burro di arachidi",
              "60 g di avena · 250 ml di latte · 1 banana · 1,5 cucchiai di burro di arachidi",
              "70 g di avena · 300 ml di latte · 1 banana · 2 cucchiai di burro di arachidi"],
 "dica": "L'avena cotta forma un gel nello stomaco che tiene a bada la fame. La banana dolcifica senza zucchero e restituisce energia, e il burro di arachidi porta grassi buoni e proteine — controlla solo la quantità, perché è molto calorico: un cucchiaio fa già il suo lavoro.",
},
{
 "nome": "Smoothie bowl di banana e frutti di bosco",
 "hook": "Denso da mangiare col cucchiaio, freddo e colorato — sembra gelato, ma lavora per il tuo dimagrimento.",
 "tempo": "6 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["1 banana congelata a fettine", "1 manciata di frutti di bosco congelati",
          "3 cucchiai di yogurt naturale", "50 ml di latte (o bevanda vegetale)",
          "2 cucchiai di avena e frutta fresca per la superficie"],
 "passos": [
   "Usa la banana già congelata (tagliala a fettine la sera prima e mettila in freezer) — è questo che rende lo smoothie denso senza ghiaccio.",
   "Nel frullatore, metti la banana, i frutti di bosco congelati, lo yogurt e il latte.",
   "Frulla alla massima velocità, fermandoti a mescolare con un cucchiaio quando si blocca. Aggiungi latte solo un cucchiaio alla volta, il minimo necessario per frullare. La consistenza deve restare densa, come un gelato.",
   "Versalo in una ciotola.",
   "Completa con l'avena e la frutta fresca disposte in file ordinate. Mangialo subito, con il cucchiaio, prima che si sciolga."],
 "porcoes8": ["1 banana · frutti di bosco · 2 cucchiai di yogurt · 1 cucchiaio di avena",
              "1 banana · frutti di bosco · 3 cucchiai di yogurt · 2 cucchiai di avena",
              "1 banana · frutti di bosco · 3 cucchiai di yogurt · 2 cucchiai di avena · semi",
              "1 banana · frutti di bosco · 4 cucchiai di yogurt · 3 cucchiai di avena",
              "1 banana · frutti di bosco · 4 cucchiai di yogurt · 3 cucchiai di avena · 1 cucchiaio di noci",
              "1 banana grande · frutti di bosco · 5 cucchiai di yogurt · 3 cucchiai di avena · noci",
              "1 banana grande · frutti di bosco · 5 cucchiai di yogurt · 4 cucchiai di avena · noci",
              "2 banane · frutti di bosco · 6 cucchiai di yogurt · 4 cucchiai di avena · noci"],
 "dica": "Congelare la frutta ti dà una consistenza da gelato senza zucchero e senza panna. Lo yogurt aggiunge proteine, e mangiare col cucchiaio, lentamente, permette al cervello di registrare che sei sazia — molto diverso dal bere un frullato con la cannuccia in pochi secondi.",
},
{
 "nome": "Uova sode con avocado e pomodoro",
 "hook": "Niente padella, niente disordine — proteine e grassi buoni in un piatto che metti insieme in pochi minuti.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["2 uova", "½ avocado", "1 pomodoro", "succo di ½ limone",
          "sale, pepe e olio d'oliva q.b.", "foglie verdi q.b."],
 "passos": [
   "Metti le uova in una pentola, coprile con acqua fredda e metti sul fuoco. Dal momento in cui bolle, conta 8-9 minuti per un tuorlo sodo.",
   "Nel frattempo, taglia l'avocado e il pomodoro a fette e disponili nel piatto sopra qualche foglia verde.",
   "Scola le uova e passale sotto l'acqua fredda per 1 minuto — così si sbucciano più facilmente.",
   "Sbuccia le uova, tagliale a metà e mettile nel piatto.",
   "Condisci tutto con il succo di limone e un po' di olio d'oliva, aggiusta di sale e pepe e servi."],
 "porcoes8": ["1 uovo · ¼ avocado · pomodoro",
              "2 uova · ½ avocado · pomodoro",
              "2 uova · ½ avocado · pomodoro · ½ fetta di pane",
              "2 uova · ½ avocado · pomodoro · 1 fetta di pane",
              "3 uova · ½ avocado · pomodoro · 1 fetta di pane",
              "3 uova · ½ avocado · pomodoro · 2 fette di pane",
              "3 uova · 1 avocado piccolo · pomodoro · 2 fette di pane",
              "4 uova · 1 avocado piccolo · pomodoro · 2 fette di pane"],
 "dica": "L'uovo sodo è la proteina più pratica che ci sia: puoi cuocerne diverse in una volta e tenerle in frigo. Con avocado e pomodoro, metti insieme una colazione completa di grassi buoni e fibre senza accendere i fornelli la mattina.",
},
{
 "nome": "Pancake proteici di avena e albume",
 "hook": "Il pancake per i giorni di allenamento: più proteine, stessa semplicità.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["40 g di fiocchi d'avena", "3 albumi (o 2 albumi + 1 uovo)",
          "½ banana, schiacciata", "1 pizzico di lievito per dolci",
          "cannella q.b.", "olio spray"],
 "passos": [
   "Se vuoi un impasto più liscio, frulla l'avena finché non diventa farina. Se ti piace rustico, usala in fiocchi.",
   "In una ciotola, mescola l'avena, gli albumi, la banana schiacciata, il lievito e la cannella finché tutto non è ben amalgamato.",
   "Lascia riposare 3 minuti perché l'avena assorba l'umidità.",
   "Scalda la padella antiaderente a fuoco medio-basso e spruzzala con l'olio.",
   "Fai dei pancake piccoli. Lasciali 2 minuti per lato, girandoli quando compaiono le bollicine.",
   "Servi con frutta fresca sopra. Lascia stare gli sciroppi zuccherati — la banana dolcifica già."],
 "porcoes8": ["2 albumi · 30 g di avena · ½ banana",
              "3 albumi · 40 g di avena · ½ banana",
              "3 albumi · 45 g di avena · ½ banana · frutta",
              "2 albumi + 1 uovo · 50 g di avena · 1 banana",
              "3 albumi + 1 uovo · 50 g di avena · 1 banana",
              "3 albumi + 1 uovo · 55 g di avena · 1 banana · frutta",
              "4 albumi + 1 uovo · 60 g di avena · 1 banana · frutta",
              "4 albumi + 2 uova · 70 g di avena · 1 banana · frutta"],
 "dica": "Sostituire parte delle uova con gli albumi alza le proteine e abbassa i grassi — ottimo per chi cerca definizione. Le proteine sono anche il nutriente più saziante, quindi questo pancake tiene a bada la fame con meno calorie della versione dolce tradizionale.",
},
{
 "nome": "Budino di chia con frutta",
 "hook": "Lo mescoli in 2 minuti, il frigo fa il resto, e ti svegli con un dolce sano già pronto.",
 "tempo": "5 min + frigo", "rende": "1 porzione", "kcal_base": 280,
 "ings": ["3 cucchiai di semi di chia", "200 ml di latte (o bevanda vegetale)",
          "½ cucchiaino di estratto di vaniglia (facoltativo)",
          "frutta a pezzetti q.b. per la superficie", "1 cucchiaino di miele (facoltativo)"],
 "passos": [
   "In un barattolo con il coperchio, metti la chia, il latte e la vaniglia. Mescola bene per 30 secondi.",
   "Aspetta 5 minuti e mescola di nuovo — questa seconda mescolata rompe i grumi che si formano ed è il segreto di un budino liscio.",
   "Chiudi il barattolo e mettilo in frigo per almeno 4 ore, o tutta la notte.",
   "La chia assorbe il liquido e forma un budino dalla consistenza gelatinosa.",
   "Prima di servire, mescola, completa con la frutta a pezzetti e, se ti va, il filo di miele."],
 "porcoes8": ["2 cucchiai di chia · 150 ml di latte · frutta",
              "3 cucchiai di chia · 200 ml di latte · frutta",
              "3 cucchiai di chia · 200 ml di latte · frutta · 1 cucchiaino di miele",
              "3 cucchiai di chia · 220 ml di latte · frutta · 1 cucchiaio di granola",
              "4 cucchiai di chia · 220 ml di latte · frutta · 1 cucchiaio di granola",
              "4 cucchiai di chia · 250 ml di latte · frutta · 2 cucchiai di granola",
              "4 cucchiai di chia · 250 ml di latte · frutta · 2 cucchiai di granola · noci",
              "5 cucchiai di chia · 300 ml di latte · frutta · 2 cucchiai di granola · noci"],
 "dica": "La chia assorbe molte volte il suo peso in liquido e si gonfia nello stomaco, dando un senso di sazietà che dura. È anche ricca di fibre e omega-3 — uno degli ingredienti più sazianti per caloria che ci siano.",
},
{
 "nome": "Muffin di uova al forno con verdure",
 "hook": "Ne inforni una teglia e hai la colazione pronta per tutta la settimana — basta scaldare e mangiare.",
 "tempo": "25 min", "rende": "6 muffin (2 a porzione)", "kcal_base": 220,
 "ings": ["6 uova", "½ peperone, tagliato a pezzetti",
          "1 manciata di spinaci tritati", "2 cucchiai di formaggio grattugiato",
          "sale e pepe q.b.", "un po' di olio (o spray) perché non attacchi"],
 "passos": [
   "Preriscalda il forno a 180 °C e ungi con un po' di olio (o spray) lo stampo da muffin, così le uova non attaccano.",
   "Taglia il peperone e gli spinaci a pezzetti piccoli.",
   "In una ciotola, sbatti le uova con sale e pepe. Aggiungi le verdure e il formaggio e mescola.",
   "Dividi il composto nei 6 stampini, riempiendo ciascuno per circa ¾.",
   "Inforna per 18-20 minuti, finché non si rassodano e prendono un colore dorato. Uno stecchino infilato al centro deve uscire pulito.",
   "Falli intiepidire un po' prima di sformarli. Conservali in frigo fino a 4 giorni e scaldali al momento di mangiarli."],
 "porcoes8": ["1 muffin + foglie verdi",
              "2 muffin",
              "2 muffin · ½ fetta di pane",
              "2 muffin · 1 fetta di pane",
              "3 muffin · 1 fetta di pane",
              "3 muffin · 2 fette di pane",
              "3 muffin · 2 fette di pane · ¼ avocado",
              "4 muffin · 2 fette di pane · ¼ avocado"],
 "dica": "Avere il cibo già pronto è ciò che ferma la decisione sbagliata quando arriva la fame del mattino. Questi muffin sono proteine e verdure in una porzione controllata — puoi congelarli e avere sempre una colazione che ti sostiene, senza improvvisare con quello che non dovresti mangiare.",
},
{
 "nome": "Pane tostato con ricotta, fragole e miele",
 "hook": "Dolce e cremoso come una coccola, ma con proteine e senza zuccheri pesanti.",
 "tempo": "6 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["1 fetta di pane integrale", "3 cucchiai di ricotta",
          "4 fragole a fettine", "1 cucchiaino di miele",
          "scorza di limone e menta (facoltativo)"],
 "passos": [
   "Tosta la fetta di pane finché non è soda.",
   "In una ciotola, schiaccia la ricotta con la forchetta finché non è cremosa. Se è asciutta, aggiungi un po' di latte.",
   "Spalma la ricotta sul pane tostato, coprendo tutta la superficie.",
   "Disponi sopra le fettine di fragola.",
   "Completa con il filo di miele e, se ti va, scorza di limone e qualche foglia di menta. Servi subito."],
 "porcoes8": ["½ fetta di pane · 2 cucchiai di ricotta · fragole",
              "1 fetta di pane · 3 cucchiai di ricotta · fragole · 1 cucchiaino di miele",
              "1 fetta di pane · 3 cucchiai di ricotta · fragole · miele",
              "1 fetta di pane · 4 cucchiai di ricotta · fragole · miele · noci",
              "1 fetta di pane · 4 cucchiai di ricotta · fragole · 1 uovo sodo",
              "2 fette di pane · 4 cucchiai di ricotta · fragole · miele",
              "2 fette di pane · 5 cucchiai di ricotta · fragole · noci",
              "2 fette di pane · 6 cucchiai di ricotta · fragole · noci · 1 uovo"],
 "dica": "La ricotta è un formaggio magro e cremoso, ricco di proteine — toglie la voglia di dolce senza la panna pesante delle creme confezionate. La fragola porta dolcezza e freschezza, e 1 cucchiaino di miele dolcifica quanto basta senza trasformare la colazione in una bomba di zucchero.",
},
{
 "nome": "Avena tiepida con cacao e banana",
 "hook": "Il gusto del cioccolato a colazione, senza zucchero e senza sensi di colpa.",
 "tempo": "8 min", "rende": "1 porzione", "kcal_base": 350,
 "ings": ["40 g di fiocchi d'avena", "200 ml di latte (o bevanda vegetale)",
          "1 cucchiaio di cacao amaro in polvere 100 %", "1 banana",
          "cannella q.b.", "dolcificante o 1 cucchiaino di miele (facoltativo)"],
 "passos": [
   "In un pentolino, mescola l'avena, il latte e il cacao in polvere prima di accendere il fuoco — così il cacao si scioglie senza grumi.",
   "Cuoci a fuoco medio-basso, mescolando sempre.",
   "Schiaccia metà della banana e aggiungila nel pentolino; tieni l'altra metà a fettine.",
   "Cuoci per 4-5 minuti, finché non si addensa e diventa cremosa.",
   "Assaggia e aggiusta la dolcezza con il dolcificante o 1 cucchiaino di miele, se ti serve.",
   "Servi in una ciotola con le fettine di banana e un pizzico di cannella sopra."],
 "porcoes8": ["30 g di avena · 180 ml di latte · 1 cucchiaio di cacao · ½ banana",
              "40 g di avena · 200 ml di latte · 1 cucchiaio di cacao · 1 banana",
              "45 g di avena · 200 ml di latte · 1 cucchiaio di cacao · 1 banana",
              "50 g di avena · 220 ml di latte · 1 cucchiaio di cacao · 1 banana · noci",
              "50 g di avena · 220 ml di latte · cacao · 1 banana · 1 cucchiaino di burro di arachidi",
              "55 g di avena · 250 ml di latte · cacao · 1 banana · 1 cucchiaio di burro di arachidi",
              "60 g di avena · 250 ml di latte · cacao · 1 banana · burro di arachidi",
              "70 g di avena · 300 ml di latte · cacao · 1 banana · burro di arachidi"],
 "dica": "Il cacao 100 % ti dà il sapore del cioccolato senza lo zucchero delle bevande al cacao — e mantiene gli antiossidanti. Togliere la voglia di dolce a colazione evita l'assalto alla tavoletta più tardi, che è dove molte diete si sfasciano.",
},
{
 "nome": "Omelette con funghi e spinaci",
 "hook": "Saporita e piena di gusto, riempie il piatto di nutrienti per pochissime calorie.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 260,
 "ings": ["2 uova", "1 manciata di funghi champignon a fettine",
          "1 manciata di spinaci", "1 cucchiaino di olio d'oliva",
          "sale, pepe e aglio tritato q.b."],
 "passos": [
   "Affetta i funghi e lava gli spinaci.",
   "Scalda l'olio d'oliva in una padella antiaderente a fuoco medio-alto. Fai rosolare i funghi in poco olio per 3-4 minuti, senza mescolare troppo, finché non si dorano e rilasciano la loro acqua.",
   "Aggiungi l'aglio e gli spinaci e mescola per 1 minuto, giusto finché non appassiscono (le foglie si ammorbidiscono). Aggiusta di sale e pepe.",
   "Sbatti le uova in una ciotola e versale sopra le verdure. Abbassa la fiamma.",
   "Lascia rassodare la base per 1-2 minuti, piega l'omelette a metà e servi."],
 "porcoes8": ["1 uovo + 1 albume · verdure, quante ne vuoi",
              "2 uova · verdure, quante ne vuoi",
              "2 uova · verdure · ½ fetta di pane",
              "2 uova · verdure · 1 fetta di pane",
              "3 uova · verdure · 1 fetta di pane",
              "3 uova · verdure · 2 fette di pane",
              "3 uova · verdure · 2 fette di pane · formaggio",
              "4 uova · verdure · 2 fette di pane · formaggio"],
 "dica": "Funghi e spinaci portano volume, sapore e nutrienti per quasi zero calorie — riempi il piatto e lo stomaco. Le uova completano con proteine sazianti, per un pasto abbondante che rientra comunque comodamente nella tua dieta.",
},
{
 "nome": "Yogurt con granola fatta in casa e mirtilli",
 "hook": "La granola la fai in casa senza zucchero e la usi tutta la settimana — croccante e fatta come si deve.",
 "tempo": "5 min (+ granola pronta)", "rende": "1 porzione", "kcal_base": 330,
 "ings": ["1 vasetto di yogurt greco naturale (circa 170 g)",
          "3 cucchiai di granola fatta in casa senza zucchero",
          "1 manciata di mirtilli", "cannella q.b.",
          "(granola: avena + noci tritate + cannella, in forno a 160 °C per 15 min)"],
 "passos": [
   "Per la granola fatta in casa: mescola i fiocchi d'avena con le noci tritate e la cannella, stendili su una teglia e inforna a 160 °C per 12-15 minuti, mescolando a metà cottura. Falla raffreddare perché diventi croccante e conservala in un barattolo.",
   "In un bicchiere, metti lo yogurt.",
   "Coprilo con la granola fatta in casa.",
   "Distribuisci sopra i mirtilli e completa con un pizzico di cannella.",
   "Servi subito, così la granola non si ammorbidisce."],
 "porcoes8": ["120 g di yogurt · 2 cucchiai di granola · mirtilli",
              "170 g di yogurt · 3 cucchiai di granola · mirtilli",
              "170 g di yogurt · 3 cucchiai di granola · mirtilli",
              "200 g di yogurt · 4 cucchiai di granola · mirtilli",
              "200 g di yogurt · 4 cucchiai di granola · mirtilli",
              "250 g di yogurt · 4 cucchiai di granola · mirtilli",
              "250 g di yogurt · 5 cucchiai di granola · mirtilli",
              "300 g di yogurt · 6 cucchiai di granola · mirtilli"],
 "dica": "La granola del supermercato di solito è piena di zucchero e olio — farla in casa elimina tutto questo e sei tu a controllare cosa ci va dentro. Con lo yogurt greco ricco di proteine e i mirtilli, diventa una colazione croccante e saziante, senza gli zuccheri nascosti delle versioni industriali.",
},
{
 "nome": "Wrap integrale con uova strapazzate e verdure",
 "hook": "Arrotoli e vai — la colazione per chi corre fuori di casa ma si rifiuta ancora di mangiare male.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 340,
 "ings": ["1 piadina integrale / wrap", "2 uova", "½ pomodoro, a pezzetti",
          "1 manciata di spinaci", "1 cucchiaio di formaggio grattugiato",
          "sale, pepe e olio spray"],
 "passos": [
   "Taglia il pomodoro a pezzetti e mettilo da parte. Lava gli spinaci.",
   "Sbatti le uova con sale e pepe. Scalda la padella con l'olio spray a fuoco medio.",
   "Aggiungi gli spinaci e il pomodoro per 1 minuto, poi versa le uova e mescola finché non formano uova strapazzate cremose.",
   "Scalda la piadina 20 secondi per lato in una padella asciutta, giusto per ammorbidirla.",
   "Metti le uova al centro della piadina, spolvera il formaggio e ripiega i lati verso l'interno.",
   "Arrotolala stretta come un burrito e tagliala a metà. Puoi mangiarla in mano, di corsa."],
 "porcoes8": ["1 wrap · 1 uovo + 1 albume · verdure",
              "1 wrap · 2 uova · verdure · formaggio",
              "1 wrap · 2 uova · verdure · formaggio",
              "1 wrap · 2 uova · verdure · ¼ avocado",
              "1 wrap · 3 uova · verdure · formaggio",
              "1 wrap grande · 3 uova · verdure · formaggio · ¼ avocado",
              "1 wrap grande · 3 uova · verdure · formaggio · ½ avocado",
              "1 wrap grande · 4 uova · verdure · formaggio · ½ avocado"],
 "dica": "Poter portare la colazione in mano è ciò che ti impedisce di saltare il pasto in una giornata piena. Farcito con uovo e verdure, questo wrap ti dà proteine e fibre in un formato pratico — molto meglio che risolvere la fame al bar con una brioche.",
},
{
 "nome": "Pancake di mela e cannella",
 "hook": "Profuma di torta di mele e rientra nella tua dieta — la coccola di una colazione dolce senza sabotarti la giornata.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["40 g di fiocchi d'avena", "1 uovo", "½ mela, grattugiata",
          "cannella q.b.", "1 pizzico di lievito per dolci", "olio spray",
          "½ mela a fettine sottili per la superficie"],
 "passos": [
   "Grattugia metà della mela con il lato a fori grandi della grattugia e tieni l'altra metà a fettine.",
   "In una ciotola, mescola l'avena, l'uovo, la mela grattugiata, la cannella e il lievito finché tutto non è ben amalgamato.",
   "Lascia riposare 3 minuti perché l'avena assorba l'umidità.",
   "Scalda la padella antiaderente a fuoco medio-basso e spruzzala con l'olio.",
   "Fai dei pancake piccoli, lasciandoli 2-3 minuti per lato.",
   "Nel frattempo, fai dorare le fettine di mela nella stessa padella con un pizzico di cannella. Servile sopra i pancake."],
 "porcoes8": ["30 g di avena · 1 uovo · ½ mela",
              "40 g di avena · 1 uovo · ½ mela",
              "45 g di avena · 1 uovo · ½ mela · noci",
              "50 g di avena · 1 uovo · 1 mela · noci",
              "50 g di avena · 2 uova · 1 mela",
              "55 g di avena · 2 uova · 1 mela · noci",
              "60 g di avena · 2 uova · 1 mela · noci",
              "70 g di avena · 2 uova · 1 mela · 1 cucchiaio di burro di arachidi"],
 "dica": "La mela porta dolcezza e fibre, e la cannella esalta il sapore senza un pizzico di zucchero — alcuni studi suggeriscono che possa perfino aiutare a controllare l'appetito. Questa è la versione che toglie la voglia di torta senza i carboidrati raffinati che fanno ingrassare.",
},
{
 "nome": "Pane integrale tostato con burro di arachidi e banana",
 "hook": "Il classico da 5 minuti che unisce energia, grassi buoni e dolcezza naturale.",
 "tempo": "5 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["1 fetta di pane integrale", "1 cucchiaio di burro di arachidi",
          "1 banana a fettine", "cannella q.b.",
          "1 pizzico di semi di chia (facoltativo)"],
 "passos": [
   "Tosta la fetta di pane finché non è soda.",
   "Spalma il burro di arachidi sul pane tostato mentre è ancora caldo — si scioglie un po' ed è più facile da stendere.",
   "Coprilo con le fettine di banana.",
   "Spolvera la cannella e, se ti va, i semi di chia sopra.",
   "Servi subito. Per portarlo con te, taglialo a metà e chiudilo come un panino."],
 "porcoes8": ["½ fetta di pane · 1 cucchiaino di burro di arachidi · ½ banana",
              "1 fetta di pane · 1 cucchiaio di burro di arachidi · 1 banana",
              "1 fetta di pane · 1 cucchiaio di burro di arachidi · 1 banana · chia",
              "1 fetta di pane · 1,5 cucchiai di burro di arachidi · 1 banana",
              "1 fetta di pane · 1,5 cucchiai di burro di arachidi · 1 banana · 1 uovo sodo",
              "2 fette di pane · 2 cucchiai di burro di arachidi · 1 banana",
              "2 fette di pane · 2 cucchiai di burro di arachidi · 1 banana · 1 uovo",
              "2 fette di pane · 2,5 cucchiai di burro di arachidi · 1 banana · 1 uovo"],
 "dica": "Il burro di arachidi ha grassi buoni e proteine, che ti tengono sazia a lungo — ma è molto calorico, quindi la quantità conta: 1 cucchiaio basta già. Sul pane integrale con la banana, ottieni energia costante per tutta la mattina, senza il picco di zucchero e il crollo che segue.",
},
{
 "nome": "Uova in camicia con asparagi e pane tostato",
 "hook": "Elegante come una colazione al ristorante, semplice quanto basta per un giorno qualunque.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["2 uova", "1 manciata di asparagi", "1 fetta di pane integrale",
          "1 cucchiaino di aceto (per l'acqua)",
          "sale, pepe e olio d'oliva q.b."],
 "passos": [
   "Lava gli asparagi e taglia la base dura. Cuocili in acqua bollente salata per 3 minuti, scolali e mettili da parte.",
   "In una pentola, scalda l'acqua finché non è quasi al bollore (con bollicine piccole, non a bollore pieno) e aggiungi l'aceto.",
   "Rompi ogni uovo in una tazza. Crea un vortice nell'acqua con un cucchiaio e fai scivolare l'uovo molto lentamente al centro — il movimento avvolge l'albume intorno al tuorlo.",
   "Cuoci per 3 minuti per un tuorlo morbido. Toglilo con una schiumarola e appoggialo su carta da cucina.",
   "Tosta il pane. Componi con gli asparagi sotto, le uova in camicia sopra, un po' di olio d'oliva, sale e pepe."],
 "porcoes8": ["1 uovo · asparagi · ½ fetta di pane",
              "2 uova · asparagi · 1 fetta di pane",
              "2 uova · asparagi · 1 fetta di pane · formaggio",
              "2 uova · asparagi · 1 fetta di pane · ¼ avocado",
              "3 uova · asparagi · 1 fetta di pane",
              "3 uova · asparagi · 2 fette di pane",
              "3 uova · asparagi · 2 fette di pane · ¼ avocado",
              "4 uova · asparagi · 2 fette di pane · ¼ avocado"],
 "dica": "L'uovo in camicia si cuoce solo nell'acqua, senza olio, e questo tiene basse le calorie. Gli asparagi sono ricchi di fibre e acqua e non hanno praticamente calorie — una colazione che sembra sofisticata e gioca comunque a favore della bilancia.",
},
{
 "nome": "Avena con pera e noci",
 "hook": "Cremosa, dolcificata appena dalla pera e con la croccantezza delle noci.",
 "tempo": "8 min", "rende": "1 porzione", "kcal_base": 350,
 "ings": ["40 g di fiocchi d'avena", "200 ml di latte (o bevanda vegetale)",
          "½ pera, a pezzetti", "3 noci, tritate", "cannella q.b.",
          "1 cucchiaino di miele (facoltativo)"],
 "passos": [
   "In un pentolino, metti l'avena e il latte e cuoci a fuoco medio-basso, mescolando.",
   "Dopo 3 minuti, aggiungi metà della pera a pezzetti e cuoci per altri 2 minuti, finché non si addensa.",
   "Spegni il fuoco e aggiungi la cannella.",
   "Servi in una ciotola e completa con il resto della pera fresca e le noci tritate.",
   "Se ti serve, dolcifica con 1 cucchiaino di miele."],
 "porcoes8": ["30 g di avena · 180 ml di latte · ½ pera · 2 noci",
              "40 g di avena · 200 ml di latte · ½ pera · 3 noci",
              "45 g di avena · 200 ml di latte · ½ pera · 3 noci",
              "50 g di avena · 220 ml di latte · 1 pera · 3 noci",
              "50 g di avena · 220 ml di latte · 1 pera · 4 noci",
              "55 g di avena · 250 ml di latte · 1 pera · 4 noci",
              "60 g di avena · 250 ml di latte · 1 pera · 5 noci",
              "70 g di avena · 300 ml di latte · 1 pera · 5 noci"],
 "dica": "La pera è ricca di fibre e dolcifica in modo naturale, così non ti serve zucchero. Le noci hanno grassi buoni che portano sazietà e croccantezza — ma sono molto caloriche, quindi pochi pezzi fanno già il loro lavoro senza far saltare le calorie della colazione.",
},
{
 "nome": "Yogurt greco con pesca e mandorle",
 "hook": "Cremoso e appena dolce grazie alla pesca, con la croccantezza delle mandorle — pronto in 3 minuti.",
 "tempo": "3 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["1 vasetto di yogurt greco naturale (circa 170 g)",
          "1 pesca a fettine (o ½ barattolo senza sciroppo)",
          "1 cucchiaio di mandorle a lamelle", "cannella q.b.",
          "1 cucchiaino di miele (facoltativo)"],
 "passos": [
   "Se la pesca è fresca, lavala e tagliala a fettine sottili. Se è in barattolo, scegline una senza sciroppo zuccherato e scolala bene.",
   "Metti lo yogurt in un bicchiere.",
   "Disponi sopra le fettine di pesca.",
   "Spolvera le mandorle a lamelle e la cannella.",
   "Se ti serve più dolcezza, aggiungi 1 cucchiaino di miele. Servi subito."],
 "porcoes8": ["120 g di yogurt · pesca · ½ cucchiaio di mandorle",
              "170 g di yogurt · pesca · 1 cucchiaio di mandorle",
              "170 g di yogurt · pesca · 1 cucchiaio di mandorle · miele",
              "200 g di yogurt · pesca · 1 cucchiaio di mandorle · 2 cucchiai di avena",
              "200 g di yogurt · pesca · 1,5 cucchiai di mandorle · 2 cucchiai di avena",
              "250 g di yogurt · pesca · 1,5 cucchiai di mandorle · 3 cucchiai di avena",
              "250 g di yogurt · pesca · 2 cucchiai di mandorle · 3 cucchiai di avena",
              "300 g di yogurt · pesca · 2 cucchiai di mandorle · 4 cucchiai di avena"],
 "dica": "La pesca è dolce e povera di calorie, e questo soddisfa la voglia di zucchero in modo leggero. Con lo yogurt greco ricco di proteine e una manciata di mandorle, unisci proteine e grassi buoni per una sazietà che ti porta avanti tutta la mattina.",
},
{
 "nome": "Panino integrale con tacchino e formaggio",
 "hook": "Salato, pratico e pieno di proteine — la colazione veloce per chi non ama il dolce al mattino.",
 "tempo": "6 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["2 fette di pane integrale", "2 fette di petto di tacchino",
          "1 fetta di formaggio bianco", "foglie di lattuga",
          "fettine di pomodoro", "1 cucchiaino di senape o formaggio spalmabile light"],
 "passos": [
   "Se lo preferisci caldo, scalda le fette di pane in una padella asciutta per 1 minuto per lato.",
   "Spalma la senape o il formaggio spalmabile light su una fetta di pane.",
   "Componi gli strati: tacchino, formaggio, pomodoro e lattuga.",
   "Chiudi con l'altra fetta di pane e premi leggermente.",
   "Taglialo in diagonale e servi. Per portarlo con te, avvolgilo nella carta da forno."],
 "porcoes8": ["1 fetta di pane (aperto) · 1 fetta di tacchino · formaggio",
              "2 fette di pane · 2 fette di tacchino · formaggio",
              "2 fette di pane · 2 fette di tacchino · formaggio",
              "2 fette di pane · 3 fette di tacchino · formaggio · ¼ avocado",
              "2 fette di pane · 3 fette di tacchino · formaggio · 1 uovo sodo",
              "2 fette di pane · 4 fette di tacchino · formaggio · 1 uovo",
              "3 fette di pane · 4 fette di tacchino · formaggio · 1 uovo",
              "3 fette di pane · 5 fette di tacchino · 2 fette di formaggio · 1 uovo"],
 "dica": "Il petto di tacchino è una delle carni più magre che esistano, quasi proteina pura, senza i grassi dei salumi come il salame e la mortadella. Sul pane integrale con l'insalata, è una colazione salata che ti sostiene con poche calorie e senza zucchero.",
},
{
 "nome": "Omelette di verdure",
 "hook": "Colorata e piena di sapore, usa quello che hai in frigo e riempie il piatto.",
 "tempo": "10 min", "rende": "1 porzione", "kcal_base": 260,
 "ings": ["2 uova", "¼ peperone, a pezzetti", "¼ cipolla, a pezzetti",
          "½ pomodoro, a pezzetti", "1 cucchiaino di olio d'oliva",
          "sale, pepe ed erbe fresche q.b."],
 "passos": [
   "Taglia il peperone, la cipolla e il pomodoro a cubetti piccoli.",
   "Scalda l'olio d'oliva in una padella antiaderente a fuoco medio. Fai soffriggere la cipolla e il peperone in poco olio, mescolando, per 2-3 minuti, finché non si ammorbidiscono.",
   "Aggiungi il pomodoro e fai andare per un altro minuto. Aggiusta di sale e pepe.",
   "Sbatti le uova e versale sopra le verdure. Inclina la padella per distribuirle.",
   "Quando la base si rassoda (2 minuti), piega l'omelette a metà, cuoci per un altro minuto e servi con le erbe."],
 "porcoes8": ["1 uovo + 1 albume · verdure, quante ne vuoi",
              "2 uova · verdure, quante ne vuoi",
              "2 uova · verdure · ½ fetta di pane",
              "2 uova · verdure · 1 fetta di pane",
              "3 uova · verdure · 1 fetta di pane",
              "3 uova · verdure · 2 fette di pane",
              "3 uova · verdure · 2 fette di pane · formaggio",
              "4 uova · verdure · 2 fette di pane · formaggio"],
 "dica": "Riempire l'omelette di verdure alza il volume e le fibre per pochissime calorie, così mangi un piatto abbondante senza sensi di colpa. È anche un modo intelligente di mangiare più verdura già di prima mattina, il che ti aiuta a raggiungere l'obiettivo di fibre della giornata.",
},
{
 "nome": "Smoothie verde con spinaci, banana e mela",
 "hook": "Verde, freddo e appena dolce — gli spinaci non si sentono nemmeno, ma il tuo corpo ti ringrazia.",
 "tempo": "5 min", "rende": "1 porzione", "kcal_base": 250,
 "ings": ["1 manciata abbondante di spinaci", "½ banana", "½ mela",
          "200 ml di acqua fredda (o latte vegetale)", "1 cucchiaio di avena",
          "succo di ½ limone", "ghiaccio q.b."],
 "passos": [
   "Lava bene gli spinaci.",
   "Nel frullatore, metti prima il liquido, poi gli spinaci — frullare le foglie con il liquido per primo evita che restino pezzetti.",
   "Frulla per 30 secondi, finché gli spinaci non si sfaldano.",
   "Aggiungi la banana, la mela (senza semi), l'avena, il succo di limone e il ghiaccio.",
   "Frulla alla massima velocità finché non è liscio e ben amalgamato. Servi subito, ben freddo."],
 "porcoes8": ["spinaci · ½ banana · ½ mela · 1 cucchiaio di avena",
              "spinaci · ½ banana · ½ mela · 1 cucchiaio di avena",
              "spinaci · 1 banana · ½ mela · 2 cucchiai di avena",
              "spinaci · 1 banana · ½ mela · 2 cucchiai di avena · yogurt",
              "spinaci · 1 banana · 1 mela · 2 cucchiai di avena · yogurt",
              "spinaci · 1 banana · 1 mela · 3 cucchiai di avena · yogurt",
              "spinaci · 1 banana · 1 mela · 3 cucchiai di avena · yogurt · noci",
              "spinaci · 1 banana · 1 mela · 4 cucchiai di avena · yogurt · noci"],
 "dica": "Frullare gli spinaci con la frutta è un modo indolore di mangiare foglie al mattino — il gusto dolce della banana e della mela nasconde il verde. È leggero in calorie e ricco di acqua e fibre, ottimo per iniziare la giornata idratata e sazia.",
},
{
 "nome": "Uova strapazzate con funghi e formaggio",
 "hook": "Cremose e avvolgenti, la colazione salata che ti sostiene con il sapore del cibo vero.",
 "tempo": "9 min", "rende": "1 porzione", "kcal_base": 300,
 "ings": ["2 uova", "1 manciata di funghi champignon a fettine",
          "1 cucchiaio di formaggio grattugiato", "1 cucchiaino di olio d'oliva",
          "sale, pepe ed erba cipollina q.b."],
 "passos": [
   "Affetta i funghi. Scalda l'olio d'oliva in una padella a fuoco medio-alto e fai dorare i funghi per 3-4 minuti.",
   "Sbatti le uova con sale e pepe.",
   "Abbassa la fiamma, versa le uova sopra i funghi e lasciale 30 secondi senza toccarle.",
   "Spingile delicatamente dal fondo verso il centro con la spatola, formando uova cremose.",
   "Prima che finiscano di cuocere, aggiungi il formaggio grattugiato e mescola. Spegni il fuoco con le uova ancora umide e completa con l'erba cipollina."],
 "porcoes8": ["1 uovo + 1 albume · funghi · formaggio",
              "2 uova · funghi · formaggio",
              "2 uova · funghi · formaggio · ½ fetta di pane",
              "2 uova · funghi · formaggio · 1 fetta di pane",
              "3 uova · funghi · formaggio · 1 fetta di pane",
              "3 uova · funghi · formaggio · 2 fette di pane",
              "3 uova · funghi · 2 cucchiai di formaggio · 2 fette di pane",
              "4 uova · funghi · 2 cucchiai di formaggio · 2 fette di pane"],
 "dica": "I funghi portano un sapore umami che rende il pasto più ricco senza grassi in più. Con le uova e un tocco di formaggio, è una colazione cremosa e ricca di proteine — molto più saziante del pane e burro afferrato di corsa.",
},
{
 "nome": "Pancake di avena con mirtilli",
 "hook": "I mirtilli scoppiano caldi dentro l'impasto — dolcezza naturale, senza zuccheri aggiunti.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 320,
 "ings": ["40 g di fiocchi d'avena", "1 uovo", "½ banana, schiacciata",
          "1 manciata di mirtilli", "1 pizzico di lievito per dolci",
          "cannella q.b.", "olio spray"],
 "passos": [
   "In una ciotola, mescola l'avena, l'uovo, la banana schiacciata, il lievito e la cannella.",
   "Lascia riposare 3 minuti perché l'impasto si compatti.",
   "Aggiungi metà dei mirtilli all'impasto, delicatamente, per non schiacciarli.",
   "Scalda la padella antiaderente a fuoco medio-basso, spruzzala con l'olio e fai dei pancake piccoli.",
   "Lasciali 2-3 minuti per lato, girandoli quando compaiono le bollicine.",
   "Servi con il resto dei mirtilli freschi sopra."],
 "porcoes8": ["30 g di avena · 1 uovo · ½ banana · mirtilli",
              "40 g di avena · 1 uovo · ½ banana · mirtilli",
              "45 g di avena · 1 uovo · ½ banana · mirtilli",
              "50 g di avena · 1 uovo · 1 banana · mirtilli",
              "50 g di avena · 2 uova · 1 banana · mirtilli",
              "55 g di avena · 2 uova · 1 banana · mirtilli · noci",
              "60 g di avena · 2 uova · 1 banana · mirtilli · noci",
              "70 g di avena · 2 uova · 1 banana · mirtilli · 1 cucchiaio di burro di arachidi"],
 "dica": "I mirtilli sono ricchi di antiossidanti e poveri di calorie, e dolcificano il pancake in modo naturale. Visto che la base è avena, uovo e banana — senza farina bianca e senza zucchero — ottieni una colazione che soddisfa la voglia di dolce senza gli ingredienti che fanno ingrassare.",
},
{
 "nome": "Yogurt con chia, miele e kiwi",
 "hook": "Fresco e pieno di fibre, la colazione che mette in moto l'intestino e sazia allo stesso tempo.",
 "tempo": "4 min", "rende": "1 porzione", "kcal_base": 290,
 "ings": ["1 vasetto di yogurt greco naturale (circa 170 g)",
          "1 cucchiaio di semi di chia", "1 kiwi a fettine",
          "1 cucchiaino di miele", "menta (facoltativo)"],
 "passos": [
   "In un bicchiere, mescola lo yogurt con la chia e lascia riposare 5 minuti — la chia si gonfia leggermente e addensa lo yogurt.",
   "Sbuccia il kiwi e taglialo a fettine.",
   "Disponi le fettine di kiwi sopra lo yogurt.",
   "Completa con il filo di miele e, se ti va, qualche foglia di menta.",
   "Servi freddo."],
 "porcoes8": ["120 g di yogurt · 1 cucchiaio di chia · kiwi",
              "170 g di yogurt · 1 cucchiaio di chia · kiwi · miele",
              "170 g di yogurt · 1 cucchiaio di chia · kiwi · miele",
              "200 g di yogurt · 1 cucchiaio di chia · kiwi · 2 cucchiai di avena",
              "200 g di yogurt · 1,5 cucchiai di chia · kiwi · 2 cucchiai di avena",
              "250 g di yogurt · 1,5 cucchiai di chia · kiwi · 3 cucchiai di avena",
              "250 g di yogurt · 2 cucchiai di chia · kiwi · 3 cucchiai di avena · noci",
              "300 g di yogurt · 2 cucchiai di chia · kiwi · 4 cucchiai di avena · noci"],
 "dica": "Chia e kiwi insieme sono ricchi di fibre, che aiutano l'intestino a lavorare e fanno durare più a lungo la sazietà. Lo yogurt greco porta proteine, e 1 cucchiaino di miele dolcifica senza esagerare — una colazione leggera che si prende cura anche della tua digestione.",
},
{
 "nome": "Pane integrale tostato con fiocchi di latte e pomodoro",
 "hook": "Fresco e salato, con le proteine del formaggio e quasi zero calorie nel pomodoro.",
 "tempo": "6 min", "rende": "1 porzione", "kcal_base": 250,
 "ings": ["1 fetta di pane integrale", "3 cucchiai di fiocchi di latte",
          "1 pomodoro a fettine", "origano, sale, pepe e olio d'oliva q.b.",
          "foglie di basilico (facoltativo)"],
 "passos": [
   "Tosta la fetta di pane finché non è soda e croccante.",
   "Spalma i fiocchi di latte sul pane tostato, coprendo tutta la superficie.",
   "Metti sopra le fettine di pomodoro.",
   "Condisci con un pizzico di sale, pepe, origano e un po' di olio d'oliva.",
   "Completa con foglie di basilico, se le hai. Servi subito."],
 "porcoes8": ["½ fetta di pane · 2 cucchiai di fiocchi di latte · pomodoro",
              "1 fetta di pane · 3 cucchiai di fiocchi di latte · pomodoro",
              "1 fetta di pane · 3 cucchiai di fiocchi di latte · pomodoro · 1 uovo sodo",
              "1 fetta di pane · 4 cucchiai di fiocchi di latte · pomodoro · 1 uovo",
              "1 fetta di pane · 4 cucchiai di fiocchi di latte · pomodoro · 2 uova",
              "2 fette di pane · 4 cucchiai di fiocchi di latte · pomodoro · 1 uovo",
              "2 fette di pane · 5 cucchiai di fiocchi di latte · pomodoro · 2 uova",
              "2 fette di pane · 6 cucchiai di fiocchi di latte · pomodoro · 2 uova"],
 "dica": "I fiocchi di latte sono magri e ricchi di proteine, e uccidono la fame con poche calorie. Sul pane integrale con il pomodoro, diventano una bruschetta sana — salata, fresca e molto più leggera del pane con il formaggio spalmabile grasso.",
},
{
 "nome": "Bowl di avena con mela al forno e cannella",
 "hook": "Il profumo della mela al forno con la cannella trasforma una semplice avena in una coccola nei giorni freddi.",
 "tempo": "15 min", "rende": "1 porzione", "kcal_base": 340,
 "ings": ["40 g di fiocchi d'avena", "200 ml di latte (o bevanda vegetale)",
          "1 mela a cubetti", "stecca di cannella o cannella in polvere",
          "1 cucchiaino di miele (facoltativo)", "1 cucchiaio di noci (facoltativo)"],
 "passos": [
   "Taglia la mela a cubetti, con la buccia. In una padella antiaderente, fai dorare i cubetti a fuoco medio con abbondante cannella per 5-7 minuti, mescolando, finché non caramellano (si ammorbidiscono e si dorano nello zucchero della frutta stessa).",
   "Nel frattempo, cuoci l'avena con il latte in un pentolino, mescolando, per 4-5 minuti, finché non si addensa.",
   "Versa l'avena in una ciotola.",
   "Completa con la mela al forno ancora calda.",
   "Se ti va, finisci con il filo di miele e le noci tritate. Servi caldo."],
 "porcoes8": ["30 g di avena · 180 ml di latte · ½ mela",
              "40 g di avena · 200 ml di latte · 1 mela",
              "45 g di avena · 200 ml di latte · 1 mela · miele",
              "50 g di avena · 220 ml di latte · 1 mela · noci",
              "50 g di avena · 220 ml di latte · 1 mela · noci",
              "55 g di avena · 250 ml di latte · 1 mela · noci",
              "60 g di avena · 250 ml di latte · 1 mela · noci",
              "70 g di avena · 300 ml di latte · 1 mela · noci · miele"],
 "dica": "Cuocere la mela al forno libera la sua dolcezza naturale ed esalta la cannella, così non ti serve zucchero. È una colazione che consola come un dolce caldo, ma con le fibre della frutta e dell'avena che tengono a bada la fame per ore.",
},
]
