# -*- coding: utf-8 -*-
"""30 receitas de SUCO/BEBIDA (121-150). ESPANHOL (America Latina).

Traducao literal de `receitas_suco_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario LatAm com foco Mexico (jengibre, sandia,
licuadora, colador, jamaica).
⛔ METRICO: ml, °C — como pt/de/fr. As constantes P e V vem do de/fr, NUNCA
de oz de volta: o EN traz "7 oz"/"10 oz" e o de/fr ja tem 200/300 ml.
⛔ `livre: True` troca a tabela de porcoes pela faixa "a vontade" — sao as
10 bebidas de quase zero caloria (aguas detox e chas).
⛔ O campo `prompt` NAO e replicado: a foto e a mesma do PT (fotos/121-150).
Metas (kcal): 90/110/130/150 · 130/150/170/190
"""

# porção padrão para sucos (metas 90/110/130/150 · 130/150/170/190)
P = ["1 vaso (200 ml)", "1 vaso (250 ml)", "1 vaso grande (300 ml)", "1 vaso grande · ½ fruta",
     "1 vaso grande (300 ml)", "1 vaso grande (350 ml)", "1 vaso grande · ½ fruta", "2 vasos o 1 fruta más"]
# porção padrão para vitaminas (mais encorpadas, dá para somar aveia)
V = ["1 vaso (200 ml)", "1 vaso (250 ml)", "1 vaso grande (300 ml)", "1 vaso · 1 cucharada de avena",
     "1 vaso grande (300 ml)", "1 vaso grande (350 ml)", "1 vaso grande · 1 cucharada de avena", "1 vaso grande · 2 cucharadas de avena"]

RECEITAS = [
{
 "nome": "Jugo verde detox",
 "hook": "El detox clásico de la mañana: ligero, refrescante y lleno de clorofila para darle a tu cuerpo ese empujón.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 90,
 "ings": ["1 hoja de kale (o 1 puñado de espinaca)",
          "1 manzana verde en trozos", "jugo de ½ limón",
          "1 trocito de jengibre", "200 ml de agua fría",
          "hielo al gusto"],
 "passos": [
   "Lava bien el kale y la manzana. Quítale el tallo grueso al kale.",
   "Pon todo en la licuadora con el agua fría y licúa a velocidad máxima 1 minuto, hasta que quede completamente líquido.",
   "Si lo prefieres sin trocitos, cuélalo con un colador. Sirve de inmediato, con hielo."],
 "porcoes8": P,
 "dica": "Las hojas verdes tienen mucha fibra y agua con muy pocas calorías, ayudando a desinflamar y a dar saciedad. Tomarlo antes del desayuno te hidrata y prepara tu cuerpo para el día. Sin azúcar, es una de las bebidas más ligeras que existen.",
},
{
 "nome": "Jugo de pepino, limón y menta",
 "hook": "Pura frescura en un vaso — el pepino refresca, el limón despierta y la menta perfuma. Hidratación que ayuda a desinflamar.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 70,
 "ings": ["½ pepino en trozos", "jugo de 1 limón", "5 hojas de menta",
          "250 ml de agua fría", "hielo al gusto"],
 "passos": [
   "Lava el pepino y córtalo en trozos (puedes dejarle la cáscara si es delgada).",
   "Licúa el pepino, el jugo de limón, la menta y el agua en la licuadora 1 minuto.",
   "Cuélalo si lo quieres más limpio y sirve bien frío, con hielo."],
 "porcoes8": P,
 "dica": "El pepino es casi todo agua y ayuda a hidratarte y a reducir la retención de líquidos (esa sensación de hinchazón). Con limón y menta, se vuelve una bebida súper refrescante con prácticamente cero calorías — buenísima para tomar durante el día en lugar de refresco.",
},
{
 "nome": "Jugo de piña con menta y jengibre",
 "hook": "Dulce, tropical y bueno para la digestión — la piña con jengibre es el jugo que refresca y además ayuda a calmar la inflamación.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 110,
 "ings": ["2 rebanadas de piña en trozos", "5 hojas de menta",
          "1 trocito de jengibre", "200 ml de agua fría",
          "hielo al gusto"],
 "passos": [
   "Corta la piña en trozos, quitándole la cáscara y el corazón duro del centro.",
   "Licúa la piña, la menta, el jengibre y el agua en la licuadora 1 minuto, hasta que quede parejo.",
   "Cuélalo si quieres y sirve bien frío, con hielo y una hoja de menta."],
 "porcoes8": P,
 "dica": "La piña tiene enzimas que ayudan a la digestión y es rica en agua y vitamina C. El jengibre acelera ligeramente tu metabolismo y calma la inflamación. Es un jugo naturalmente dulce, así que no necesita azúcar — la fruta ya hace ese trabajo.",
},
{
 "nome": "Jugo de remolacha, zanahoria y naranja",
 "hook": "Rojo intenso y lleno de energía — la remolacha con naranja es un jugo que te levanta y le da color a tu día.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 120,
 "ings": ["½ remolacha cruda pequeña en trozos", "1 zanahoria en trozos",
          "jugo de 2 naranjas", "100 ml de agua", "hielo al gusto"],
 "passos": [
   "Pela la remolacha y la zanahoria y córtalas en trozos pequeños.",
   "Exprime las naranjas. Licúa la remolacha, la zanahoria, el jugo de naranja y el agua en la licuadora 2 minutos, hasta que quede completamente líquido.",
   "Cuélalo con un colador (la remolacha y la zanahoria dejan fibras) y sirve frío."],
 "porcoes8": P,
 "dica": "La remolacha mejora la circulación y da energía, la zanahoria aporta vitamina A y la naranja vitamina C. Juntas hacen un jugo naturalmente dulce y nutritivo. Como tiene azúcar natural de la fruta y de la remolacha, vale la pena respetar la porción del vaso.",
},
{
 "nome": "Jugo de sandía con limón",
 "hook": "Hidratación en forma de jugo: la sandía es casi todo agua, dulce en la medida justa y de lo más refrescante que hay.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 80,
 "ings": ["2 rebanadas grandes de sandía sin cáscara",
          "jugo de ½ limón", "5 hojas de menta (opcional)",
          "hielo al gusto"],
 "passos": [
   "Corta la sandía en cubos y sácale las semillas más grandes.",
   "Licúa la sandía con el jugo de limón (y la menta, si quieres) en la licuadora 30 segundos — la sandía suelta mucha agua, así que casi no necesitas agregar líquido.",
   "Sirve de inmediato, bien frío, con hielo."],
 "porcoes8": P,
 "dica": "La sandía es más de 90 % agua, así que hidrata muchísimo y llena el estómago con pocas calorías. Es naturalmente dulce y refrescante, perfecta para matar el antojo de algo dulce y frío en el calor sin salirte de tu dieta.",
},
{
 "nome": "Jugo de zanahoria, manzana y jengibre",
 "hook": "Dulce, anaranjado y con un toque picosito de jengibre — un jugo que fortalece tus defensas y despierta tu cuerpo.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 110,
 "ings": ["1 zanahoria en trozos", "1 manzana en trozos",
          "1 trocito de jengibre", "200 ml de agua", "hielo al gusto"],
 "passos": [
   "Pela la zanahoria y corta la manzana en trozos, sacándole las semillas.",
   "Licúa la zanahoria, la manzana, el jengibre y el agua en la licuadora 2 minutos, hasta que quede completamente líquido.",
   "Cuélalo con un colador y sirve frío."],
 "porcoes8": P,
 "dica": "La zanahoria y la manzana aportan dulzor natural y bastante fibra, mientras que el jengibre da ese toque termogénico que ayuda a tu metabolismo. Es un jugo cargado de vitaminas, ideal para empezar el día con energía y sin necesidad de azúcar.",
},
{
 "nome": "Jugo verde con espinaca, piña y pepino",
 "hook": "Verde y dulce al mismo tiempo — la piña esconde la espinaca y ni te das cuenta de que estás tomando algo tan saludable.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 100,
 "ings": ["1 puñado de espinaca", "1 rebanada de piña en trozos",
          "½ pepino en trozos", "jugo de ½ limón",
          "200 ml de agua fría", "hielo al gusto"],
 "passos": [
   "Lava bien la espinaca y el pepino.",
   "Licúa la espinaca, la piña, el pepino, el limón y el agua en la licuadora 1 minuto, hasta que quede bien verde y líquido.",
   "Cuélalo si quieres y sirve frío."],
 "porcoes8": P,
 "dica": "La espinaca es extremadamente rica en hierro y nutrientes con casi nada de calorías, y la piña hace el jugo dulce y sabroso sin azúcar. El pepino hidrata y ayuda a desinflamar. Es una forma fácil y rica de comer más verdes.",
},
{
 "nome": "Jugo de naranja con zanahoria y jengibre",
 "hook": "Tu dosis diaria de vitamina C en un vaso bien anaranjado — levanta tus defensas y te da energía para el día.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 110,
 "ings": ["jugo de 3 naranjas", "1 zanahoria en trozos",
          "1 trocito de jengibre", "hielo al gusto"],
 "passos": [
   "Exprime las naranjas para sacar el jugo.",
   "Pela la zanahoria y córtala en trozos pequeños. Licúa la zanahoria, el jugo de naranja y el jengibre en la licuadora 2 minutos.",
   "Cuélalo con un colador y sirve bien frío, con hielo."],
 "porcoes8": P,
 "dica": "La naranja y la zanahoria están llenas de vitamina C y A, y el jengibre suma un toque que ayuda a la circulación y al metabolismo. Es un jugo energizante y naturalmente dulce — solo recuerda respetar la porción, ya que el azúcar de la fruta suma calorías.",
},
{
 "nome": "Jugo natural de uva con limón",
 "hook": "Morado intenso y lleno de antioxidantes — las uvas se convierten en un jugo naturalmente dulce que le hace bien a tu corazón.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 120,
 "ings": ["1 racimo pequeño de uvas moradas sin semilla (unos 225 g)",
          "jugo de ½ limón", "150 ml de agua fría", "hielo al gusto"],
 "passos": [
   "Lava bien las uvas y sepáralas de los tallos.",
   "Licúa las uvas con el limón y el agua en la licuadora 1 minuto, hasta que se deshagan.",
   "Cuélalo con un colador, presionando bien para sacar todo el jugo, y sirve frío."],
 "porcoes8": P,
 "dica": "Las uvas moradas son ricas en antioxidantes que protegen tu corazón y tu piel. Hecho al momento y sin azúcar, el jugo natural de uva es muy distinto al de caja — solo recuerda que la uva es una fruta muy dulce, así que la porción del vaso importa.",
},
{
 "nome": "Jugo detox con manzana, kale y apio",
 "hook": "Extremadamente ligero y desinflamante — la combinación verde que limpia tu sistema y funciona muy bien antes de las comidas.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 90,
 "ings": ["1 manzana verde en trozos", "1 hoja de kale",
          "1 tallo de apio", "jugo de ½ limón",
          "200 ml de agua fría", "hielo al gusto"],
 "passos": [
   "Lava el kale, la manzana y el apio. Quítale el tallo grueso al kale.",
   "Licúa la manzana, el kale, el apio, el limón y el agua en la licuadora 1 minuto.",
   "Cuélalo y sirve bien frío."],
 "porcoes8": P,
 "dica": "El apio es diurético y ayuda a eliminar el exceso de líquidos, el kale aporta fibra y nutrientes y la manzana endulza de forma natural. Es un jugo verde ligero y desinflamante, buenísimo para acompañar una rutina de bajar de peso.",
},
{
 "nome": "Smoothie de plátano con avena y canela",
 "hook": "Cremoso y reconfortante, este smoothie te sostiene toda la mañana — el desayuno líquido para los días ocupados.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 190,
 "ings": ["1 plátano", "2 cucharadas de avena",
          "200 ml de leche (o bebida vegetal)", "1 pizca de canela",
          "hielo al gusto"],
 "passos": [
   "Pela el plátano (si está muy maduro, endulza más).",
   "Licúa el plátano, la avena, la leche y la canela en la licuadora 1 minuto, hasta que quede cremoso.",
   "Sirve de inmediato, con una pizca de canela encima. Si lo quieres más frío, agrega hielo y licúa otra vez."],
 "porcoes8": V,
 "dica": "El plátano con avena es una pareja que te mantiene satisfecha por horas gracias a la fibra, y la leche aporta proteína. Es un smoothie que funciona como comida líquida completa — perfecto para el desayuno o una colación cuando andas con prisa, sin necesidad de azúcar.",
},
{
 "nome": "Smoothie de fresa con yogur",
 "hook": "Rosado y cremoso, con el dulzor natural de las fresas — un smoothie que parece malteada, pero es ligero y lleno de proteína.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 150,
 "ings": ["150 g de fresas (frescas o congeladas)",
          "1 vaso de yogur natural sin azúcar (unos 170 g)",
          "100 ml de leche (o agua)",
          "endulzante al gusto (opcional)", "hielo al gusto"],
 "passos": [
   "Lava las fresas y quítales las hojitas verdes.",
   "Licúa las fresas, el yogur y la leche en la licuadora 1 minuto, hasta que quede una crema tersa y rosada.",
   "Pruébalo y, si quieres, endúlzalo un poco. Sirve frío."],
 "porcoes8": V,
 "dica": "El yogur natural aporta proteína y cremosidad sin azúcar, y las fresas endulzan de forma natural con muy pocas calorías. Es un smoothie saciante y refrescante que mata el antojo de una malteada de forma ligera y nutritiva.",
},
{
 "nome": "Smoothie de frutos rojos mixtos",
 "hook": "Morado, lleno de antioxidantes y cargado de sabor — una mezcla de frutos rojos licuada hasta quedar cremosa, buenísima para tu piel y para la saciedad.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 140,
 "ings": ["140 g de frutos rojos mixtos (fresa, arándano, frambuesa)",
          "1 vaso de yogur natural sin azúcar",
          "100 ml de leche (o agua)",
          "endulzante al gusto (opcional)", "hielo al gusto"],
 "passos": [
   "Si los frutos rojos están congelados, úsalos directo del congelador (hacen el smoothie más frío y cremoso).",
   "Licúa los frutos rojos, el yogur y la leche en la licuadora 1 minuto, hasta que quede una crema tersa.",
   "Pruébalo, endúlzalo si quieres y sirve de inmediato."],
 "porcoes8": V,
 "dica": "Los frutos rojos son campeones en antioxidantes, que combaten el envejecimiento, y son bajos en azúcar. Con yogur, se convierten en un smoothie cremoso y rico en proteína que te llena y es una de las colaciones más saludables que existen.",
},
{
 "nome": "Smoothie verde con plátano y espinaca",
 "hook": "Verde por fuera, dulce por dentro — el plátano esconde la espinaca y entrega una bebida cremosa llena de nutrientes.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 160,
 "ings": ["1 plátano", "1 puñado de espinaca", "½ manzana en trozos",
          "200 ml de leche (o agua de coco)", "hielo al gusto"],
 "passos": [
   "Lava bien la espinaca.",
   "Licúa el plátano, la espinaca, la manzana y la leche en la licuadora 1 minuto, hasta que quede verde y cremoso.",
   "Sirve de inmediato, bien frío."],
 "porcoes8": V,
 "dica": "Es una forma deliciosa de comer más hojas verdes: el plátano y la manzana endulzan de forma natural y esconden la espinaca, que entra llena de hierro y fibra. Cremoso y saciante, funciona como un desayuno líquido nutritivo.",
},
{
 "nome": "Smoothie de aguacate",
 "hook": "Extremadamente cremoso y reconfortante, con la grasa buena del aguacate — un smoothie que de verdad llena y alimenta tu piel.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 190,
 "ings": ["½ aguacate maduro", "200 ml de leche (o bebida vegetal)",
          "endulzante al gusto — o 1 cucharadita de miel",
          "1 pizca de canela o unas gotas de limón", "hielo al gusto"],
 "passos": [
   "Saca la pulpa del aguacate con una cuchara, usando solo la parte bien suave.",
   "Licúa el aguacate, la leche y el endulzante (o la miel) en la licuadora 1 minuto, hasta que quede una crema tersa y sedosa.",
   "Sirve frío, con una pizca de canela o unas gotas de limón."],
 "porcoes8": V,
 "dica": "El aguacate tiene grasa buena que llena mucho y le hace bien a tu corazón y a tu piel. Licuado con leche, se convierte en un smoothie cremoso y nutritivo que detiene el hambre por horas. Como es más alto en calorías, es una gran opción de colación en porción de un vaso.",
},
{
 "nome": "Smoothie de mango con yogur",
 "hook": "Tropical, dorado y cremoso — el mango se convierte en un smoothie dulce que sabe a postre y refresca al instante.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 150,
 "ings": ["1 mango maduro en cubos (o 165 g congelado)",
          "1 vaso de yogur natural sin azúcar",
          "100 ml de leche (o agua)", "hielo al gusto"],
 "passos": [
   "Pela el mango y corta la pulpa en cubos.",
   "Licúa el mango, el yogur y la leche en la licuadora 1 minuto, hasta que quede una crema tersa y dorada.",
   "Sirve bien frío."],
 "porcoes8": V,
 "dica": "El mango es naturalmente dulce y está lleno de vitamina A y C, así que no necesita azúcar. Con yogur, el smoothie gana proteína y cremosidad, volviéndose una colación refrescante y saciante — solo respeta la porción, ya que el mango es una fruta dulce.",
},
{
 "nome": "Smoothie de pera con avena",
 "hook": "Suave y delicado, la pera aporta un dulzor ligero a la avena cremosa — un smoothie tranquilo y reconfortante.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 170,
 "ings": ["1 pera madura en trozos", "2 cucharadas de avena",
          "200 ml de leche (o bebida vegetal)", "1 pizca de canela",
          "hielo al gusto"],
 "passos": [
   "Lava la pera y córtala en trozos, sacándole el corazón con las semillas.",
   "Licúa la pera, la avena, la leche y la canela en la licuadora 1 minuto, hasta que quede cremoso.",
   "Sirve de inmediato, con una pizca de canela encima."],
 "porcoes8": V,
 "dica": "La pera es una fruta suave llena de fibra, y con avena hace un smoothie que te mantiene satisfecha un buen rato. La leche suma proteína. Es una bebida ligera y reconfortante, buenísima para el desayuno o una colación que detiene el hambre.",
},
{
 "nome": "Smoothie de plátano y cacao",
 "hook": "El sabor a chocolate en un smoothie cremoso y sin azúcar — la respuesta perfecta al antojo de dulce de la tarde.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 180,
 "ings": ["1 plátano", "1 cucharada de cacao en polvo 100 %",
          "200 ml de leche (o bebida vegetal)",
          "1 cucharadita de crema de cacahuate (opcional)",
          "hielo al gusto"],
 "passos": [
   "Pela el plátano (si está muy maduro, endulza más).",
   "Licúa el plátano, el cacao, la leche y la crema de cacahuate en la licuadora 1 minuto, hasta que quede una crema tersa y chocolatosa.",
   "Sirve bien frío, con hielo."],
 "porcoes8": V,
 "dica": "El cacao puro da el sabor a chocolate sin azúcar, y el plátano lo endulza y hace el smoothie cremoso. Es la forma más rica de matar el antojo de chocolate de la tarde de manera nutritiva, con la fibra de la fruta y la proteína de la leche.",
},
{
 "nome": "Smoothie de manzana con canela y avena",
 "hook": "El sabor de un pay de manzana en un vaso cremoso — avena, manzana y canela licuadas en una colación que reconforta.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 170,
 "ings": ["1 manzana en trozos", "2 cucharadas de avena",
          "200 ml de leche (o bebida vegetal)",
          "1 cucharadita de canela", "hielo al gusto"],
 "passos": [
   "Corta la manzana en trozos, sacándole las semillas (puedes dejarle la cáscara).",
   "Licúa la manzana, la avena, la leche y la canela en la licuadora 1 minuto y medio, hasta que quede cremoso y la manzana esté completamente deshecha.",
   "Sirve de inmediato, con un poco más de canela encima."],
 "porcoes8": V,
 "dica": "La manzana con canela y avena sabe a postre, pero juntas hacen un smoothie lleno de fibra que te mantiene satisfecha por horas. La canela ayuda a controlar el antojo de dulce. Es una colación cremosa, sabrosa y ligera, sin nada de azúcar añadida.",
},
{
 "nome": "Smoothie de melón con menta",
 "hook": "Verde pálido, dulce y ultra refrescante — el melón con menta es pura hidratación en un smoothie ligero.",
 "tempo": "5 min", "rende": "1 vaso grande", "kcal_base": 110,
 "ings": ["3 rebanadas de melón sin cáscara, en cubos",
          "5 hojas de menta",
          "½ envase de yogur natural (o 100 ml de agua)",
          "hielo al gusto"],
 "passos": [
   "Corta el melón en cubos, sacándole las semillas.",
   "Licúa el melón, la menta y el yogur (o el agua) en la licuadora 1 minuto, hasta que quede terso.",
   "Sirve bien frío, con una hoja de menta."],
 "porcoes8": V,
 "dica": "El melón es rico en agua y ayuda a hidratarte y a desinflamar, con muy pocas calorías. Licuado con menta queda refrescante y ligero; con un poco de yogur, gana cremosidad y proteína. Un smoothie perfecto para los días calurosos.",
},
{
 "nome": "Agua detox con pepino, limón y menta",
 "hook": "El agua que da ganas de tomar: ligera, aromática y refrescante, para mantenerte hidratada todo el día sin aburrirte.",
 "tempo": "5 min + refrigerador", "rende": "1 jarra", "kcal_base": 10,
 "livre": True,
 "ings": ["1 litro de agua", "½ pepino en rodajas delgadas",
          "½ limón en rodajas", "6 hojas de menta", "hielo al gusto"],
 "passos": [
   "Lava el pepino, el limón y la menta.",
   "En una jarra, pon el agua, las rodajas de pepino y limón y las hojas de menta.",
   "Mete al refrigerador por lo menos 1 hora, para que el agua tome el sabor. Sirve fría durante el día; puedes rellenarla con más agua conforme la tomas."],
 "dica": "Cambiar el refresco y los jugos azucarados por agua saborizada es uno de los hábitos que más ayuda a bajar de peso. El pepino, el limón y la menta aportan sabor sin calorías, haciendo el agua más rica y ayudándote a mantenerte hidratada todo el día.",
},
{
 "nome": "Agua detox con jengibre y limón",
 "hook": "Un agua tibia o fría con un toque picosito que despierta tu metabolismo apenas empieza la mañana.",
 "tempo": "5 min", "rende": "1 vaso", "kcal_base": 8,
 "livre": True,
 "ings": ["1 vaso de agua (tibia o fría)", "jugo de ½ limón",
          "unas rebanadas delgadas de jengibre",
          "hielo al gusto (si es fría)"],
 "passos": [
   "Corta el jengibre en rebanadas muy delgadas.",
   "Mezcla el agua, el jugo de limón y el jengibre en un vaso.",
   "Déjalo reposar 5 minutos para que el jengibre suelte su sabor. Tómalo en la mañana, en ayunas, tibio o frío."],
 "dica": "Tomar agua con limón y jengibre en ayunas ayuda a despertar tu cuerpo y tu digestión. El jengibre tiene un ligero efecto termogénico (acelera un poco tu metabolismo). Sin azúcar, es un ritual matutino simple que apoya la pérdida de peso.",
},
{
 "nome": "Agua detox con frutos rojos",
 "hook": "Rosada y bonita en la jarra, con frutitas flotando — un agua saborizada que parece bebida de spa.",
 "tempo": "5 min + refrigerador", "rende": "1 jarra", "kcal_base": 15,
 "livre": True,
 "ings": ["1 litro de agua",
          "1 puñado de frutos rojos (fresa, arándano, frambuesa)",
          "½ limón en rodajas", "hojas de menta", "hielo al gusto"],
 "passos": [
   "Lava los frutos rojos y corta las fresas a la mitad.",
   "En una jarra, pon el agua, la fruta, las rodajas de limón y la menta. Machaca ligeramente la fruta con una cuchara para que suelte su color y sabor.",
   "Mete al refrigerador de 1 a 2 horas y sirve fría."],
 "dica": "Los frutos rojos aportan color, sabor y antioxidantes al agua con casi nada de calorías. Es una forma bonita y rica de tomar más agua durante el día, reemplazando las bebidas azucaradas y ayudando con la hidratación y con bajar de peso.",
},
{
 "nome": "Agua de coco con limón y menta",
 "hook": "La hidratación natural del agua de coco, reforzada con limón y menta — refrescante y llena de minerales.",
 "tempo": "3 min", "rende": "1 vaso grande", "kcal_base": 45,
 "livre": True,
 "ings": ["1 vaso grande de agua de coco", "jugo de ½ limón",
          "5 hojas de menta", "hielo al gusto"],
 "passos": [
   "Mezcla el agua de coco con el jugo de limón en un vaso.",
   "Agrega las hojas de menta y el hielo y revuelve.",
   "Sirve bien fría, de preferencia la natural (el agua de coco de caja suele traer azúcar añadida — busca la natural)."],
 "dica": "El agua de coco repone minerales e hidrata muy bien, con pocas calorías cuando es natural. Con limón y menta queda todavía más refrescante. Es excelente después de hacer ejercicio o en días calurosos, en lugar de las bebidas deportivas azucaradas.",
},
{
 "nome": "Té verde con limón y jengibre",
 "hook": "El aliado número 1 de quien baja de peso: el té verde acelera tu metabolismo, y el limón y el jengibre le dan un empujón extra.",
 "tempo": "8 min", "rende": "1 taza", "kcal_base": 5,
 "livre": True,
 "ings": ["240 ml de agua", "1 cucharadita de té verde (o 1 bolsita)",
          "unas rebanadas de jengibre", "jugo de ½ limón"],
 "passos": [
   "Hierve el agua y apaga el fuego. Espera 1 minuto (el agua demasiado caliente amarga el té verde).",
   "Agrega el té verde y las rebanadas de jengibre, tápalo y déjalo reposar 3 minutos.",
   "Cuélalo, agrega el jugo de limón y tómalo tibio. También puedes tomarlo frío, durante el día."],
 "dica": "El té verde es uno de los alimentos más estudiados para bajar de peso: tiene sustancias que ayudan a acelerar el metabolismo y a quemar grasa. Con jengibre y limón, el efecto se refuerza. Sin azúcar, es una bebida libre que puedes tomar todos los días.",
},
{
 "nome": "Té de jamaica frío",
 "hook": "Rojo rubí y ligeramente ácido, la jamaica es famosa por ayudar a desinflamar — deliciosa fría en el calor.",
 "tempo": "10 min + refrigerador", "rende": "1 jarra", "kcal_base": 5,
 "livre": True,
 "ings": ["1 litro de agua",
          "2 cucharadas de flor de jamaica seca (o 2 bolsitas)",
          "rodajas de limón", "hojas de menta", "hielo al gusto"],
 "passos": [
   "Hierve el agua y apágala. Agrega la jamaica, tápala y déjala reposar de 5 a 7 minutos.",
   "Cuélala y déjala enfriar. Métela al refrigerador.",
   "Sirve bien fría, con rodajas de limón, menta y hielo."],
 "dica": "El té de jamaica es conocido por ayudar a reducir la retención de líquidos (la hinchazón) y es rico en antioxidantes. Frío y sin azúcar, es una bebida refrescante y libre, buenísima para reemplazar refrescos y jugos procesados durante el día.",
},
{
 "nome": "Té de manzanilla con canela",
 "hook": "Tibio y reconfortante, el té que te calma antes de dormir — y dormir bien también ayuda a bajar de peso.",
 "tempo": "8 min", "rende": "1 taza", "kcal_base": 5,
 "livre": True,
 "ings": ["240 ml de agua",
          "1 cucharada de flores de manzanilla (o 1 bolsita)",
          "1 raja de canela (o 1 pizca molida)"],
 "passos": [
   "Hierve el agua y apaga el fuego.",
   "Agrega la manzanilla y la canela, tápalo y déjalo reposar 5 minutos.",
   "Cuélalo y tómalo tibio, de preferencia en la noche, antes de dormir."],
 "dica": "La manzanilla calma y ayuda a relajarte, mejorando tu sueño. Dormir bien es un factor que mucha gente olvida al bajar de peso: las malas noches aumentan el hambre y el antojo de dulce del día siguiente. Este té es un ritual nocturno que apoya tu dieta.",
},
{
 "nome": "Infusión de jengibre, limón y canela",
 "hook": "Una infusión termogénica y aromática que calienta tu cuerpo y le da ese empujón a tu metabolismo.",
 "tempo": "10 min", "rende": "1 taza grande", "kcal_base": 8,
 "livre": True,
 "ings": ["300 ml de agua", "varias rebanadas de jengibre",
          "1 raja de canela", "jugo de ½ limón"],
 "passos": [
   "En una olla pequeña, hierve el agua con las rebanadas de jengibre y la raja de canela 5 minutos, a fuego bajo.",
   "Apágala, tápala y déjala reposar otros 3 minutos.",
   "Cuélala, agrega el jugo de limón y tómala tibia."],
 "dica": "El jengibre y la canela tienen un ligero efecto termogénico, es decir, ayudan a que tu cuerpo gaste un poco más de energía. Es una infusión tibia y reconfortante, sin azúcar, que va muy bien en días fríos y le da ese apoyo extra a tu metabolismo.",
},
{
 "nome": "Té de menta con limón",
 "hook": "Fresco y bueno para la digestión, el té de menta calma tu estómago después de comer — ligero y aromático.",
 "tempo": "8 min", "rende": "1 taza", "kcal_base": 4,
 "livre": True,
 "ings": ["240 ml de agua",
          "1 puñado de hojas frescas de menta (o 1 bolsita)",
          "jugo de ½ limón"],
 "passos": [
   "Hierve el agua y apaga el fuego.",
   "Agrega las hojas de menta, tápalo y déjalo reposar 5 minutos.",
   "Cuélalo, agrega el jugo de limón y tómalo tibio o frío, de preferencia después de las comidas."],
 "dica": "La menta ayuda a la digestión y reduce esa sensación de estómago pesado después de comer. Un té digestivo sin azúcar después de las comidas es un hábito simple que te ayuda a evitar picar dulces justo después.",
},
{
 "nome": "Té de hinojo",
 "hook": "Suave y naturalmente dulce, el hinojo calma tu estómago y reduce los gases — un té reconfortante después de comer.",
 "tempo": "8 min", "rende": "1 taza", "kcal_base": 4,
 "livre": True,
 "ings": ["240 ml de agua",
          "1 cucharadita de semillas de hinojo — o 1 bolsita"],
 "passos": [
   "Machaca ligeramente las semillas de hinojo (así sueltan más aroma).",
   "Hierve el agua y apágala. Agrega el hinojo, tápalo y déjalo reposar 5 minutos.",
   "Cuélalo y tómalo tibio, de preferencia después de las comidas o en la noche."],
 "dica": "El hinojo es conocido por calmar el estómago y reducir los gases y la hinchazón abdominal. Naturalmente dulce, no necesita azúcar. Es un té digestivo reconfortante, buenísimo para terminar una comida de forma ligera.",
},
]
