# -*- coding: utf-8 -*-
"""LUNCH recipes (031-065). English (US market).
porcoes8 order: Woman 120-155/155-185/185-220/220+ lb · Man 155-185/185-220/220-265/265+ lb
Targets (cal): 360/440/500/560 · 540/610/680/750
US units: oz for meat/fish · cups / tbsp / tsp · °F. Photos shared with the PT edition.
"""

RECEITAS = [
{
 "nome": "Grilled Chicken with Brown Rice and Broccoli",
 "hook": "The simplest plate in the world and one of the best for losing weight: lean protein, a good carb and vegetables freely.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 470,
 "ings": ["1 chicken breast fillet (about 5 oz)", "4 tablespoons cooked brown rice",
          "1 plate of broccoli", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt and pepper to taste"],
 "passos": [
   "Season the chicken on both sides with salt, pepper, the garlic and the lemon juice. Let it take on flavor for 5 minutes.",
   "Cut the broccoli into small florets. Boil water in a pot, add the broccoli and leave just 3 minutes, until bright green and tender but still firm. Drain.",
   "Heat a nonstick pan over medium-high heat with the olive oil. Add the chicken and leave 4 to 5 minutes per side, without stirring, until golden outside and white inside.",
   "To check it is done, cut into the middle of the fillet: the meat should be white, with no pink part.",
   "Warm the already-cooked brown rice. Build the plate with the rice, the sliced chicken and the broccoli beside it.",
   "If you like, drizzle the broccoli with a little olive oil and a bit more lemon."],
 "porcoes8": ["3.5 oz chicken · 3 tbsp rice · broccoli freely",
              "4 oz chicken · 4 tbsp rice · broccoli freely",
              "4.5 oz chicken · 5 tbsp rice · broccoli freely",
              "5 oz chicken · 5 tbsp rice · drizzle of olive oil",
              "5 oz chicken · 5 tbsp rice · broccoli freely",
              "6 oz chicken · 6 tbsp rice · broccoli freely",
              "7 oz chicken · 7 tbsp rice · drizzle of olive oil",
              "8 oz chicken · 8 tbsp rice · drizzle of olive oil"],
 "dica": "Chicken breast is almost pure protein, which is very filling and helps preserve muscle while you lose fat. Brown rice has fiber and releases energy slowly, so you do not feel the hunger that hits an hour later. Broccoli fills the plate for almost no calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast sliced on a white plate, next to a portion of brown rice and steamed green broccoli, a wedge of lemon on the side, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tilapia Fillet with Sweet Potato Mash",
 "hook": "Light fish and a naturally sweet mash — a lunch that looks like a restaurant and fits your diet.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 440,
 "ings": ["1 tilapia fillet (about 5 oz)", "1 medium sweet potato", "1 teaspoon olive oil",
          "juice of ½ lemon", "chopped fresh herbs", "salt, pepper and paprika to taste",
          "green leaves for the salad"],
 "passos": [
   "Peel the sweet potato and cut into pieces. Cook in boiling water for 15 minutes, until very soft (a fork goes in easily). Drain.",
   "Mash the potato while still hot with a fork, add a pinch of salt and half the olive oil, and mix into a smooth mash.",
   "Season the tilapia with salt, pepper, paprika and the lemon juice.",
   "Heat a nonstick pan with the rest of the olive oil over medium heat. Add the fillet and leave 3 to 4 minutes per side, flipping carefully just once, until golden and it releases easily from the pan.",
   "Build the plate with the mash, the fillet on top and a portion of green leaves on the side. Finish with the fresh herbs."],
 "porcoes8": ["4 oz fish · ½ sweet potato · salad",
              "5 oz fish · 1 small sweet potato · salad",
              "5 oz fish · 1 medium sweet potato · salad",
              "6 oz fish · 1 medium sweet potato · drizzle of olive oil",
              "6 oz fish · 1 medium sweet potato · salad",
              "7 oz fish · 1 large sweet potato · salad",
              "8 oz fish · 1 large sweet potato · drizzle of olive oil",
              "9 oz fish · 1 large sweet potato · drizzle of olive oil"],
 "dica": "Tilapia is a lean fish, full of protein and with very little fat. Sweet potato fills you for hours and, even being a carb, releases energy very slowly — that is why it is the favorite of anyone who wants to lose weight without losing energy.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared white fish fillet on a bed of orange sweet potato mash, with a side of green salad and a wedge of lemon, on a light plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Tuna Steak with Vegetables and Potato",
 "hook": "Fresh tuna becomes a steak from the sea: firm outside, juicy inside, and ready in minutes.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 450,
 "ings": ["1 fresh tuna steak (about 5 oz)", "1 small potato, sliced", "1 cup green beans and carrot",
          "1 clove of garlic, chopped", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and oregano to taste"],
 "passos": [
   "Cook the potato slices in boiling salted water for 10 minutes, until soft but not falling apart. Drain.",
   "Cut the green beans into pieces and the carrot into rounds. Steam or cook in a little boiling water for 5 minutes, until soft but still firm.",
   "Season the tuna steak with salt, pepper, the garlic, the oregano and the lemon juice. Let it take on flavor for 5 minutes.",
   "Heat a nonstick pan with the olive oil over high heat. Add the steak and leave 2 to 3 minutes per side — tuna is great slightly pink in the center; if you prefer it well done, leave 1 more minute per side.",
   "Build the plate with the potato, the vegetables and the tuna steak on top. Drizzle with a bit more lemon and serve."],
 "porcoes8": ["4 oz tuna · ½ potato · vegetables",
              "5 oz tuna · 1 small potato · vegetables",
              "5 oz tuna · 1 potato · vegetables",
              "6 oz tuna · 1 potato · drizzle of olive oil",
              "6 oz tuna · 1 potato · vegetables",
              "7 oz tuna · 1 large potato · vegetables",
              "8 oz tuna · 1 large potato · drizzle of olive oil",
              "9 oz tuna · 2 small potatoes · drizzle of olive oil"],
 "dica": "Fresh tuna is one of the leanest meats from the sea: lots of protein, omega-3 (the good fat) and very little bad fat. Grilled fast over high heat, it stays juicy with no oil, and with vegetables and a bit of potato it becomes a fine, light lunch.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled fresh tuna steak, seared outside and pink inside, with roasted potato slices, green beans and carrot, a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Grain Shredded Chicken Wrap",
 "hook": "A handy roll to take to work, filled with chicken and salad — it kills hunger without weighing you down.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 whole-grain tortilla (or flatbread)", "1 cooked and shredded chicken fillet (about 4 oz)",
          "1 tablespoon plain unsweetened yogurt", "lettuce leaves", "½ tomato, sliced",
          "grated carrot", "salt, pepper and a little mustard to taste"],
 "passos": [
   "Cook the chicken breast in salted water for about 15 minutes, until white inside. Let it cool a little and shred with two forks, pulling the meat into strands.",
   "In a bowl, mix the shredded chicken with the yogurt, the mustard, salt and pepper, into a creamy filling.",
   "Warm the tortilla for 20 seconds in a pan, just to make it soft and easy to roll.",
   "Spread the lettuce leaves in the center of the tortilla. Add the creamy chicken, the tomato and the grated carrot on top.",
   "Fold both sides in and roll it up tight, from the bottom. Cut in half on the diagonal and serve."],
 "porcoes8": ["3.5 oz chicken · ½ tortilla · salad",
              "4 oz chicken · 1 tortilla · salad",
              "4.5 oz chicken · 1 tortilla · salad",
              "5 oz chicken · 1 tortilla · 1 heaping tbsp yogurt",
              "5 oz chicken · 1 tortilla · salad",
              "6 oz chicken · 1 large tortilla · salad",
              "7 oz chicken · 2 tortillas · salad",
              "8 oz chicken · 2 tortillas · salad"],
 "dica": "Swapping mayo for plain yogurt cuts a lot of calories and adds protein. Shredded chicken spreads well and gives the feeling of a generous filling with little fat, and the whole-grain tortilla has more fiber than white bread, holding hunger longer.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain wrap cut in half, filled with shredded chicken, lettuce, tomato and grated carrot, on a wooden board, a few fresh vegetables beside it, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Salmon with Roasted Vegetables",
 "hook": "All on one tray: the finest fish for your heart, roasted golden with colorful vegetables.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 490,
 "ings": ["1 salmon steak (about 5 oz)", "1 small potato, sliced", "1 zucchini, sliced",
          "½ bell pepper, in strips", "cherry tomatoes", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and rosemary to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the potato into thin slices — that way it roasts in the same time as the fish.",
   "On a roasting tray, spread the potato, the zucchini, the pepper and the cherry tomatoes. Season with salt, pepper, rosemary and half the olive oil, and mix.",
   "Bake for 10 minutes, just for the potato to start softening.",
   "Take out the tray, open a space in the middle and place the salmon. Season the fish with salt, pepper, the lemon juice and the rest of the olive oil.",
   "Return to the oven for 15 more minutes, until the salmon turns lighter and flakes when you poke it with a fork. Serve on the tray or plated."],
 "porcoes8": ["4 oz salmon · ½ potato · vegetables",
              "5 oz salmon · 1 small potato · vegetables",
              "5 oz salmon · 1 potato · vegetables",
              "6 oz salmon · 1 potato · drizzle of olive oil",
              "6 oz salmon · 1 potato · vegetables",
              "7 oz salmon · 1 large potato · vegetables",
              "8 oz salmon · 1 large potato · drizzle of olive oil",
              "9 oz salmon · 2 small potatoes · drizzle of olive oil"],
 "dica": "Salmon is rich in good fat (omega-3), which helps the heart and is very filling. Roasting everything on one tray uses almost no oil and gives the vegetables a concentrated flavor — a complete, pretty, light dish with minimal effort.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked salmon fillet on a roasting tray surrounded by roasted potato slices, zucchini, red pepper and cherry tomatoes, sprig of rosemary and a lemon wedge, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sweet Potato and Lean Ground Beef Shepherd's Pie",
 "hook": "The comfort of a creamy shepherd's pie, but with sweet potato mash and lean beef — pure satisfaction, no guilt.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 460,
 "ings": ["2 medium sweet potatoes", "9 oz lean ground beef", "1 onion, chopped",
          "1 clove of garlic, chopped", "1 tomato, chopped", "1 teaspoon olive oil",
          "salt, pepper and fresh herbs to taste", "1 tablespoon low-fat grated cheese"],
 "passos": [
   "Peel the sweet potatoes, cut into pieces and cook in boiling water for 15 minutes, until very soft. Drain and mash with a fork, with a pinch of salt, into a smooth mash.",
   "In a pan, heat the olive oil and fry the onion and garlic over medium heat, stirring, for 2 minutes, until translucent.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the tomato, salt and pepper and cook 5 more minutes, until reduced. Turn off and add the fresh herbs.",
   "In a baking dish, spread half the mash on the bottom, the beef in the middle and the rest of the mash on top. Sprinkle the grated cheese.",
   "Bake at medium-high heat (400°F) for 15 minutes, until the top is lightly golden. Serve hot."],
 "porcoes8": ["½ serving · green salad",
              "1 serving · green salad",
              "1 serving · green salad",
              "1 serving · 1 extra tbsp cheese",
              "1 serving + extra beef · salad",
              "1 large serving · salad",
              "1 large serving + beef · salad",
              "double portion of beef · salad"],
 "dica": "Sweet potato swaps the regular potato of a shepherd's pie for a version with more fiber, which fills you more. Lean beef gives plenty of protein without the excess fat of fatty meat. It is the kind of comforting dish that beats the urge to eat junk.",
 "prompt": "Square ultra-realistic overhead food photograph of a sweet potato and ground beef shepherd's pie in a white baking dish, golden top, a spoon lifting a portion, a small green salad beside it, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Complete Tuna, Chickpea and Egg Salad",
 "hook": "No stove: a real salad that fills your plate and your belly, put together in five minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 can of tuna in water, drained", "½ cup cooked chickpeas", "2 boiled eggs",
          "mixed green leaves", "½ tomato, diced", "½ cucumber, sliced", "red onion, thinly sliced",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt and pepper to taste"],
 "passos": [
   "Cook the eggs: put them in a pot with water, bring to a boil and count 9 minutes. Run under cold water, peel and cut in half.",
   "Drain the tuna and the chickpeas well.",
   "On a large plate or bowl, spread the green leaves. On top, arrange the tomato, the cucumber and the onion.",
   "Put the tuna in the center, the chickpeas around it and the eggs on the sides.",
   "Drizzle with the olive oil and the lemon juice, season with salt and pepper and serve."],
 "porcoes8": ["½ can tuna · ⅓ cup chickpeas · 1 egg",
              "1 can tuna · ½ cup chickpeas · 2 eggs",
              "1 can tuna · ½ cup chickpeas · 2 eggs",
              "1 can tuna · ⅔ cup chickpeas · 2 eggs · avocado",
              "1 can tuna · ⅔ cup chickpeas · 2 eggs",
              "1½ can tuna · ¾ cup chickpeas · 2 eggs",
              "1½ can tuna · 1 cup chickpeas · 3 eggs · avocado",
              "2 cans tuna · 1 cup chickpeas · 3 eggs · avocado"],
 "dica": "It is a protein bomb (tuna, egg and chickpeas together) that takes almost no effort. The protein and fiber in the salad hold hunger for hours, and since everything is fresh and not cooked in oil, the dish stays light even when generously served.",
 "prompt": "Square ultra-realistic overhead food photograph of a big fresh salad bowl with canned tuna, chickpeas, halved boiled eggs, mixed green leaves, cherry tomato, cucumber and red onion, drizzle of olive oil and lemon, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Light Chicken Stroganoff with Rice",
 "hook": "The creamy stroganoff you know, but swapping the heavy cream for yogurt — same delight, half the calories.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 chicken breast fillets, cubed (about 10 oz)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 cup sliced mushrooms", "1 tablespoon tomato paste",
          "4 tablespoons plain unsweetened yogurt", "1 teaspoon olive oil",
          "salt, pepper and mustard to taste", "white or brown rice to serve"],
 "passos": [
   "Season the chicken cubes with salt and pepper.",
   "Heat the olive oil in a pot over medium-high heat and brown the chicken cubes on the outside, stirring now and then, for 5 minutes. Remove and set aside.",
   "In the same pot, fry the onion and garlic for 2 minutes, stirring, until translucent. Add the mushrooms and cook 3 more minutes, until they soften.",
   "Return the chicken to the pot, add the tomato paste and the mustard, mix and leave 3 minutes.",
   "Turn off the heat. Only then add the yogurt and stir — off the heat it does not curdle. Adjust the salt and serve over the rice."],
 "porcoes8": ["½ serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "The secret is plain yogurt instead of heavy cream: you keep the creaminess and flavor but cut the fat and gain protein. The chicken is filling and the mushrooms add volume and flavor for very few calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy chicken stroganoff with mushrooms served over white rice on a white plate, garnished with parsley, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Turkey Breast with Vegetable Couscous",
 "hook": "The couscous is ready with just hot water — the fastest, fluffiest lunch for busy days.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["1 turkey breast fillet (about 5 oz)", "½ cup couscous (the small-bead kind)",
          "½ cup hot water", "½ zucchini, diced", "½ bell pepper, diced", "cherry tomatoes, cut",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper and mint to taste"],
 "passos": [
   "Put the couscous in a bowl, add a pinch of salt and the hot water (the water should cover the couscous by a finger). Cover with a plate and leave 5 minutes.",
   "Fluff the couscous with a fork, going through the whole bowl, until loose and not sticky.",
   "Season the turkey with salt and pepper. Heat a nonstick pan with half the olive oil and grill the turkey for 3 to 4 minutes per side, until golden and white inside.",
   "Add to the couscous the raw diced zucchini, pepper and tomato, the rest of the olive oil, the lemon juice and the mint. Mix.",
   "Serve the couscous with the sliced turkey breast on top."],
 "porcoes8": ["4 oz turkey · ⅓ cup couscous · vegetables",
              "5 oz turkey · ½ cup couscous · vegetables",
              "5 oz turkey · ½ cup couscous · vegetables",
              "6 oz turkey · ⅔ cup couscous · drizzle of olive oil",
              "6 oz turkey · ⅔ cup couscous · vegetables",
              "7 oz turkey · ¾ cup couscous · vegetables",
              "8 oz turkey · 1 cup couscous · drizzle of olive oil",
              "9 oz turkey · 1 cup couscous · drizzle of olive oil"],
 "dica": "Turkey breast is even leaner than chicken and full of protein. Couscous cooks with just hot water, no fat, and mixed with raw vegetables it becomes a light, colorful, refreshing dish — perfect for lunch.",
 "prompt": "Square ultra-realistic overhead food photograph of fluffy couscous mixed with diced zucchini, pepper and tomato, topped with sliced grilled turkey breast, fresh mint, on a white plate, light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef and Black Bean Chili",
 "hook": "A spicy, hearty stew that warms your soul — beans, lean beef and lots of flavor in one pot.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 450,
 "ings": ["10 oz lean ground beef", "1 cup cooked black beans (or canned, drained)",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 bell pepper, chopped",
          "2 tomatoes, chopped (or tomato sauce)", "1 teaspoon olive oil", "1 teaspoon ground cumin",
          "salt, pepper and paprika to taste"],
 "passos": [
   "Heat the olive oil in a pot over medium heat. Fry the onion, garlic and pepper for 3 minutes, stirring, until soft.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the cumin, the paprika, salt and pepper and mix well, so the seasonings release their aroma.",
   "Add the chopped tomatoes and the black beans. If it gets too dry, add half a cup of water.",
   "Lower the heat and simmer for 15 to 20 minutes, stirring now and then, until it thickens into a creamy stew. Serve on its own or with a little rice."],
 "porcoes8": ["½ serving · salad",
              "1 serving · salad",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "1 large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "Black beans are champions in fiber and plant protein, and together with lean beef they make the dish very filling with few calories. It is a stew that goes a long way, keeps well in the fridge and beats the craving for warm, seasoned food.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty beef and black bean chili in a rustic bowl, topped with chopped coriander, a spoon resting in it, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Whole-Wheat Pasta in Tomato Sauce with Turkey Meatballs",
 "hook": "Yes, you can eat pasta while losing weight — in the whole-wheat version, with fresh sauce and lean meatballs.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 480,
 "ings": ["5 oz whole-wheat pasta (dry weight)", "9 oz ground turkey breast (or ground chicken)",
          "3 ripe tomatoes, chopped (or tomato sauce)", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 egg", "2 tablespoons oats", "1 teaspoon olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "In a bowl, mix the ground turkey, the egg, the oats, half the garlic, salt and pepper. Knead with your hands until it holds together and roll walnut-sized balls.",
   "Heat the olive oil in a wide pot and brown the meatballs on all sides, turning carefully, for about 5 minutes. Remove and set aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the chopped tomatoes, salt and pepper and cook for 10 minutes, stirring, until it becomes a sauce.",
   "Return the meatballs to the sauce and cook for 8 more minutes, until cooked through.",
   "Meanwhile, cook the pasta in boiling salted water for the time on the package, until cooked but still firm. Drain.",
   "Mix the pasta into the sauce with the meatballs, sprinkle the basil and serve."],
 "porcoes8": ["⅔ serving pasta · 3 meatballs",
              "1 serving · 4 meatballs",
              "1 serving · 4 meatballs",
              "1 serving · 5 meatballs",
              "1 serving · 5 meatballs",
              "1 large serving · 6 meatballs",
              "large serving · 7 meatballs",
              "double serving · 8 meatballs"],
 "dica": "Whole-wheat pasta has more fiber and fills you more than the regular kind, and turkey meatballs give lean protein instead of fatty meat. A tomato sauce made fresh, with no sugar and nothing processed, keeps the dish tasty and much lighter.",
 "prompt": "Square ultra-realistic overhead food photograph of wholewheat spaghetti with fresh tomato sauce and turkey meatballs, sprinkled with fresh basil, in a white bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vegetable-Filled Omelette",
 "hook": "A light lunch for days with no time: fluffy, warm and full of protein, ready in the pan in ten minutes.",
 "tempo": "12 min", "rende": "1 serving", "kcal_base": 360,
 "ings": ["3 eggs", "½ tomato, diced", "½ bell pepper, diced", "handful of spinach",
          "1 tablespoon white cheese, cubed", "1 teaspoon olive oil",
          "chives, salt and pepper to taste", "1 slice of whole-grain bread (optional)"],
 "passos": [
   "Crack the eggs into a bowl, season with salt and pepper and beat with a fork for 30 seconds, until well combined.",
   "Heat the olive oil in a nonstick pan over medium-low heat. Add the pepper and the spinach and stir for 1 minute, just until the spinach wilts.",
   "Spread the vegetables across the pan and pour the eggs on top. Leave 1 minute without stirring, until the edge sets.",
   "Put the tomato and cheese on half the omelette. With a spatula, fold the other half over, forming a half-moon.",
   "Leave 1 more minute, just until the cheese softens. Sprinkle chives and serve, with the slice of bread if you like."],
 "porcoes8": ["2 eggs · vegetables · ½ bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "3 eggs · 2 tbsp cheese · 1 slice bread",
              "3 eggs · vegetables · 1 slice bread",
              "4 eggs · vegetables · 1 slice bread",
              "4 eggs · 2 tbsp cheese · 2 slices bread",
              "5 eggs · vegetables · 2 slices bread"],
 "dica": "Eggs are a top-quality, very filling protein — people who eat eggs at lunch tend to snack less in the afternoon. Filled with vegetables, the omelette gains volume, color and fiber for almost no extra calories, becoming a complete, quick meal.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded omelette filled with tomato, pepper, spinach and white cheese on a white plate, chives on top, a slice of wholegrain toast beside it, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Lean Beef Steak with Rice, Beans and Collard Greens",
 "hook": "The everyday plate, the way we love it — just in the right amount, with lean beef and lightly sautéed greens.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["1 lean beef steak (about 4.5 oz)", "4 tablespoons cooked rice",
          "4 tablespoons cooked beans", "2 collard leaves, cut into thin strips",
          "1 clove of garlic, chopped", "1 teaspoon olive oil", "salt and pepper to taste"],
 "passos": [
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Add the steak and leave 2 to 3 minutes per side, without moving it, until golden outside and cooked to your liking inside.",
   "Cut the collard greens into very thin strips. In a pan, heat the rest of the olive oil and fry the garlic for 30 seconds, just until fragrant.",
   "Add the greens and stir over high heat for 1 to 2 minutes, just until slightly wilted and still green. Season with salt.",
   "Warm the rice and beans. Build the plate with the rice, the beans, the steak and the greens on the side."],
 "porcoes8": ["3.5 oz beef · 3 tbsp rice · 3 tbsp beans",
              "4.5 oz beef · 4 tbsp rice · 4 tbsp beans",
              "4.5 oz beef · 5 tbsp rice · 4 tbsp beans",
              "5 oz beef · 5 tbsp rice · 5 tbsp beans",
              "5 oz beef · 5 tbsp rice · 5 tbsp beans",
              "6 oz beef · 6 tbsp rice · 5 tbsp beans",
              "7 oz beef · 7 tbsp rice · 6 tbsp beans",
              "8 oz beef · 8 tbsp rice · 6 tbsp beans"],
 "dica": "You can eat the traditional plate of rice, beans and beef without leaving your diet: the key is choosing a lean cut, measuring the rice and beans and going big on the greens, which fill the plate with fiber and almost no calories. The beans also give fiber and protein that hold hunger.",
 "prompt": "Square ultra-realistic overhead food photograph of a plate with a grilled lean beef steak, white rice, brown beans and sautéed collard greens in thin strips, on a light wooden table, soft natural light, homestyle and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef Steak with Onions, Mashed Potato and Salad",
 "hook": "Steak with golden onions is pure comfort — over a light mash and beside a fresh salad, it fits your diet just right.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["1 lean beef steak (about 4.5 oz)", "2 medium potatoes", "1 onion, sliced",
          "1 teaspoon olive oil", "salt and pepper to taste", "green leaves and tomato for the salad",
          "juice of ½ lemon"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until very soft. Drain and mash with a fork, with a pinch of salt, into a smooth mash. For creamier, add a little of the cooking water.",
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Add the steak and leave 2 to 3 minutes per side, without moving it, until golden outside and cooked to your liking. Remove and set aside.",
   "In the same pan, add the onion slices and the rest of the olive oil. Stir over medium heat for 5 minutes, until the onion is soft and golden (nice and sweet).",
   "Cover the steak with the golden onions. Build the plate with the mash, the steak with onions and a green salad dressed with lemon."],
 "porcoes8": ["3.5 oz beef · ½ serving mash · salad",
              "4.5 oz beef · 1 serving mash · salad",
              "4.5 oz beef · 1 serving mash · salad",
              "5 oz beef · 1 serving mash · salad",
              "5 oz beef · 1 serving mash · salad",
              "6 oz beef · 1 large serving mash · salad",
              "7 oz beef · large serving mash · salad",
              "8 oz beef · double serving mash · salad"],
 "dica": "Choosing a lean cut and grilling with no oil turns the steak into almost pure protein. Golden onions bring lots of flavor for very few calories and skip greasy sauces. With the mash in the right amount and plenty of salad, the plate satisfies without weighing you down.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled lean beef steak topped with golden caramelized onions, served with creamy mashed potato and a fresh green salad with tomato, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sautéed Shrimp with Vegetables and Rice",
 "hook": "Shrimp is ready in the blink of an eye and light as few things are — a quick lunch that looks fancy.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["5 oz peeled shrimp", "4 tablespoons cooked brown rice", "½ zucchini, in half-moons",
          "½ bell pepper, in strips", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the shrimp with salt, pepper, the garlic and the lemon juice. Let it take on flavor for 5 minutes.",
   "Heat a large pan with half the olive oil over high heat. Add the zucchini and pepper and stir for 3 minutes, until soft but still firm. Remove and set aside.",
   "In the same pan, add the rest of the olive oil and the shrimp. Sauté (stir over high heat) for 2 to 3 minutes, just until the shrimp turn pink and curl. Be careful not to overcook, or they get rubbery.",
   "Return the vegetables to the pan, add the already-cooked brown rice and mix for 1 minute, just to warm everything.",
   "Sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · 3 tbsp rice · vegetables",
              "5 oz shrimp · 4 tbsp rice · vegetables",
              "5 oz shrimp · 5 tbsp rice · vegetables",
              "6 oz shrimp · 5 tbsp rice · drizzle of olive oil",
              "6 oz shrimp · 5 tbsp rice · vegetables",
              "7 oz shrimp · 6 tbsp rice · vegetables",
              "8 oz shrimp · 7 tbsp rice · drizzle of olive oil",
              "9 oz shrimp · 8 tbsp rice · drizzle of olive oil"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories, so you can serve yourself well without weighing you down. Sautéed fast over high heat with vegetables, it keeps a firm texture and flavor, in a light dish ready in minutes.",
 "prompt": "Square ultra-realistic overhead food photograph of sautéed shrimp with zucchini and red pepper over brown rice, garnished with parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Light Chicken Stir-Fry with Brown Rice",
 "hook": "The Chinese classic at home, in the lean version: cubed chicken and crunchy vegetables in a light, glossy sauce.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 460,
 "ings": ["2 chicken breast fillets, cubed (about 10 oz)", "1 bell pepper, cubed", "1 onion, cubed",
          "1 celery stalk, in pieces (optional)", "1 clove of garlic, chopped", "1 tablespoon light soy sauce",
          "1 teaspoon cornstarch", "1 teaspoon olive oil", "brown rice to serve"],
 "passos": [
   "Season the chicken cubes with a little of the soy sauce and the garlic. Let it take on flavor for 5 minutes.",
   "Dissolve the cornstarch in half a cup of water with the rest of the soy sauce. Mix well and set aside — this is what thickens the sauce.",
   "Heat a large pan with half the olive oil over high heat. Brown the chicken cubes for 5 minutes, stirring, until white inside. Remove and set aside.",
   "In the same pan, add the rest of the olive oil and the pepper, onion and celery. Stir over high heat for 3 minutes, until soft but still crunchy.",
   "Return the chicken, stir the cornstarch mixture and pour it into the pan. Stir for 1 to 2 minutes, until the sauce thickens and turns glossy, coating everything. Serve over the brown rice."],
 "porcoes8": ["½ serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Making it at home, you control the oil and sugar that restaurants overdo. The chicken gives lean protein, the vegetables come in crunchy with few calories, and just a touch of cornstarch gives that pretty sauce without fattening the dish.",
 "prompt": "Square ultra-realistic overhead food photograph of a light chicken stir-fry with diced pepper, onion and celery in a glossy sauce, served over brown rice, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mexican Bowl with Beef, Black Beans and Corn",
 "hook": "All the colors and flavors of Mexico in one bowl — hearty, seasoned and surprisingly light.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 490,
 "ings": ["9 oz lean ground beef", "1 cup cooked black beans", "½ cup corn",
          "4 tablespoons cooked rice", "1 tomato, diced", "½ avocado, sliced",
          "green leaves", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "cumin, salt, pepper and coriander to taste", "juice of ½ lemon"],
 "passos": [
   "Heat the olive oil in a pan and fry the garlic for 30 seconds. Add the ground beef and stir, breaking up the pieces, until it loses its pink color.",
   "Season the beef with cumin, salt and pepper and cook 3 more minutes. Add the black beans and the corn and warm for 2 minutes.",
   "In a bowl, make a bed of green leaves and put the rice on one side.",
   "On top, arrange the beef with beans and corn, the tomato and the avocado slices.",
   "Drizzle with the lemon juice, sprinkle coriander and serve."],
 "porcoes8": ["½ serving · 3 tbsp rice · ¼ avocado",
              "1 serving · 4 tbsp rice · ¼ avocado",
              "1 serving · 4 tbsp rice · ½ avocado",
              "1 serving · 5 tbsp rice · ½ avocado",
              "1 serving · 5 tbsp rice · ½ avocado",
              "1 large serving · 6 tbsp rice · ½ avocado",
              "large serving · 7 tbsp rice · ½ avocado",
              "double serving · 8 tbsp rice · avocado"],
 "dica": "It is a complete dish in one bowl: protein from the beef, fiber from the beans and corn, and the good fat of avocado, which adds creaminess and fullness. Well seasoned, it satisfies the craving for indulgent food without the excess fat.",
 "prompt": "Square ultra-realistic overhead food photograph of a Mexican burrito bowl with seasoned ground beef, black beans, corn, rice, tomato, avocado slices and green leaves, lime wedge, in a bowl, on a light wooden table, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Chicken Salad with Mango",
 "hook": "Sweet, savory and refreshing: warm grilled chicken meets sweet mango in a salad that does not feel like a diet.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 chicken breast fillet (about 4.5 oz)", "mixed green leaves", "½ mango, diced",
          "½ cucumber, sliced", "red onion, thinly sliced", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and mint to taste"],
 "passos": [
   "Season the chicken with salt and pepper. Heat a nonstick pan over medium-high heat and grill the fillet for 4 to 5 minutes per side, until golden and white inside. Let it cool a little and cut into strips.",
   "Peel the mango and cut the flesh into cubes. Cut the cucumber into rounds and the onion into very thin slices.",
   "In a large bowl or deep plate, spread the green leaves.",
   "On top, arrange the mango cubes, the cucumber, the onion and the chicken strips.",
   "Make the dressing by mixing the olive oil, the lemon juice, salt and pepper. Drizzle over the salad, sprinkle mint and serve."],
 "porcoes8": ["3.5 oz chicken · ¼ mango · salad",
              "4.5 oz chicken · ½ mango · salad",
              "4.5 oz chicken · ½ mango · salad",
              "5 oz chicken · ½ mango · drizzle of olive oil",
              "5 oz chicken · ½ mango · salad",
              "6 oz chicken · ½ mango · 1 tbsp nuts",
              "7 oz chicken · 1 mango · nuts",
              "8 oz chicken · 1 mango · nuts"],
 "dica": "The mango comes in as a natural sweet, with no added sugar, and satisfies the sweet craving inside a savory meal. The grilled chicken gives the filling protein, and the volume of leaves and vegetables fills the plate for very few calories. A salad that is a complete meal.",
 "prompt": "Square ultra-realistic overhead food photograph of a fresh salad with grilled chicken strips, mango cubes, cucumber, red onion and mixed green leaves, mint on top, lemon dressing, in a bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Light Chicken Curry with Rice",
 "hook": "A golden, fragrant sauce that transforms your usual chicken — creamy without cream, with light coconut milk.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 chicken breast fillets, cubed (about 10 oz)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon curry powder", "½ cup light coconut milk (or regular milk)",
          "1 tomato, chopped", "1 teaspoon olive oil", "salt and pepper to taste", "rice to serve"],
 "passos": [
   "Season the chicken cubes with salt, pepper and half the curry.",
   "Heat the olive oil in a pot over medium heat and brown the chicken cubes on the outside, stirring, for 5 minutes. Remove and set aside.",
   "In the same pot, fry the onion and garlic for 2 minutes. Add the rest of the curry and stir for 30 seconds, just so the seasoning releases its aroma.",
   "Add the tomato and cook for 3 minutes, until it breaks down. Return the chicken and add the coconut milk.",
   "Cook over low heat for 8 to 10 minutes, stirring now and then, until the sauce thickens and the chicken is tender. Serve over the rice."],
 "porcoes8": ["½ serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra chicken",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + chicken · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Light coconut milk gives the sauce creaminess with far less fat than heavy cream. The curry perfumes it and gives the feeling of a special dish, which helps you eat slowly and feel satisfied with a controlled portion of chicken and rice.",
 "prompt": "Square ultra-realistic overhead food photograph of a light chicken curry in a golden sauce served over white rice in a bowl, garnished with coriander, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Sardines with Potato and Salad",
 "hook": "Cheap, full of omega-3 and ready in minutes — sardines are one of the best friends of anyone who wants to lose weight on a budget.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 450,
 "ings": ["3 to 4 fresh sardines, cleaned (or 1 can of sardines in water)", "1 small potato, sliced",
          "1 teaspoon olive oil", "juice of ½ lemon", "1 clove of garlic, chopped",
          "salt, pepper and oregano to taste", "green leaves and tomato for the salad"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the potato into thin slices, season with salt, half the olive oil and spread on a roasting tray.",
   "Bake the potato for 10 minutes, to start softening.",
   "Season the sardines with salt, pepper, garlic, oregano and the lemon juice.",
   "Take out the tray, place the sardines among the potatoes and drizzle with the rest of the olive oil.",
   "Return to the oven for 15 more minutes, until the sardines are golden and the potato soft. Serve with a fresh green salad on the side.",
   "If using canned sardines, skip the oven for the fish: just roast the potato and build the plate with the drained sardines and the salad."],
 "porcoes8": ["2 sardines · ½ potato · salad",
              "3 sardines · 1 small potato · salad",
              "3 sardines · 1 potato · salad",
              "4 sardines · 1 potato · drizzle of olive oil",
              "4 sardines · 1 potato · salad",
              "4 sardines · 1 large potato · salad",
              "5 sardines · 1 large potato · drizzle of olive oil",
              "6 sardines · 2 small potatoes · salad"],
 "dica": "The sardine is a powerful little fish: lots of omega-3 (the good fat that helps the heart), protein and calcium, for a very low price. Baked with a bit of potato and a fresh salad, it becomes a complete, nutritious and economical lunch.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-baked sardines with sliced roasted potatoes, a fresh green salad with tomato and a lemon wedge, on a light plate, wooden table, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Eggplant Stuffed with Ground Beef",
 "hook": "The eggplant itself becomes the bowl — stuffed with seasoned beef and gratinated, it is pretty and beats any craving to overeat.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["1 large eggplant", "7 oz lean ground beef", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tomato, chopped", "1 teaspoon olive oil", "2 tablespoons low-fat grated cheese",
          "salt, pepper and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the eggplant in half lengthwise. With a spoon, scoop out part of the center, forming two 'boats'. Chop the scooped-out flesh.",
   "Put the boats on a roasting tray, drizzle with a little olive oil and bake for 10 minutes, just to soften.",
   "Meanwhile, in a pan, fry the onion and garlic in the rest of the olive oil for 2 minutes. Add the ground beef and stir until it loses its pink color.",
   "Add the tomato, the chopped eggplant flesh, salt and pepper and cook for 5 minutes, until it forms a soft filling.",
   "Fill the eggplant boats with the beef, sprinkle the grated cheese on top and return to the oven for 15 minutes, until gratinated (the cheese melts and browns). Sprinkle parsley and serve."],
 "porcoes8": ["½ eggplant · salad",
              "1 stuffed eggplant · salad",
              "1 eggplant · 2 tbsp rice",
              "1 eggplant · extra beef · salad",
              "1 eggplant · extra beef · 2 tbsp rice",
              "1 large eggplant · 3 tbsp rice",
              "1 eggplant · double beef · 4 tbsp rice",
              "eggplant + extra portion of beef · 4 tbsp rice"],
 "dica": "Eggplant has lots of water and fiber, so it fills your stomach for very few calories — stuffed, it adds volume to the plate and satisfies. Lean beef brings the protein, and a bit of cheese on top beats the craving for something gratinated without overdoing it.",
 "prompt": "Square ultra-realistic overhead food photograph of two baked stuffed eggplant halves filled with seasoned ground beef and melted cheese, sprinkled with parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Caesar Salad with Grilled Chicken",
 "hook": "The creamy Caesar salad you love, with a smart yogurt dressing — all the creaminess, none of the guilt.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 grilled chicken fillet, in strips (about 4.5 oz)", "romaine lettuce leaves",
          "1 slice of whole-grain bread, cubed", "2 tablespoons plain unsweetened yogurt",
          "1 teaspoon mustard", "1 teaspoon grated cheese", "juice of ½ lemon",
          "1 clove of garlic, crushed", "salt and pepper to taste"],
 "passos": [
   "Season the chicken with salt and pepper and grill in a nonstick pan for 4 minutes per side, until golden and white inside. Cut into strips.",
   "Make the croutons: spread the whole-grain bread cubes on a tray and bake at medium heat for 8 minutes, until crisp (or toast in a dry pan).",
   "Prepare the dressing: in a small bowl, mix the yogurt, the mustard, the grated cheese, the lemon juice, the crushed garlic, salt and pepper, into a cream.",
   "Tear the lettuce with your hands and put it in a large bowl. Drizzle with the dressing and toss to coat the leaves.",
   "Put the chicken strips and the croutons on top and serve right away, so the bread stays crunchy."],
 "porcoes8": ["3.5 oz chicken · salad · few croutons",
              "4.5 oz chicken · salad · croutons",
              "4.5 oz chicken · salad · croutons",
              "5 oz chicken · salad · 1 extra tbsp cheese",
              "5 oz chicken · salad · croutons",
              "6 oz chicken · salad · croutons",
              "7 oz chicken · salad · extra croutons",
              "8 oz chicken · salad · extra croutons"],
 "dica": "The traditional Caesar dressing is a bomb of mayo and oil. Swapping it for yogurt with mustard and lemon, you keep the creaminess and the bold taste with much less fat. The grilled chicken turns the salad into a real meal, full of protein.",
 "prompt": "Square ultra-realistic overhead food photograph of a Caesar salad with grilled chicken strips, romaine lettuce, wholegrain croutons and a creamy dressing, grated cheese on top, in a bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef Strips with Bell Pepper and Rice",
 "hook": "Thin beef strips sautéed with colorful peppers — fragrant, seasoned and ready in the pan in minutes.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["9 oz lean beef, in thin strips (sirloin or round)", "1 red bell pepper, in strips",
          "1 yellow bell pepper, in strips", "1 onion, in strips", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "juice of ½ lemon", "cumin, salt, pepper and coriander to taste",
          "rice to serve"],
 "passos": [
   "Season the beef strips with salt, pepper, cumin, the garlic and the lemon juice. Let it take on flavor for 10 minutes.",
   "Heat a large pan with half the olive oil over high heat. Add the beef a little at a time (not all at once, or it releases water) and brown fast, stirring, for 3 minutes. Remove and set aside.",
   "In the same pan, with the rest of the olive oil, add the onion and the peppers. Stir over high heat for 4 minutes, until soft but still firm and colorful.",
   "Return the beef to the pan and mix for 1 minute, just to bring the flavors together.",
   "Sprinkle coriander and serve over a portion of rice. It is also great rolled in a whole-grain tortilla."],
 "porcoes8": ["½ serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · extra beef",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "serving + beef · 7 tbsp rice",
              "double serving · 8 tbsp rice"],
 "dica": "Cutting the beef into thin strips goes further: a small portion looks like much more on the plate. Sautéed fast over high heat with peppers, it stays juicy and full of flavor with no greasy sauce. The peppers add color, vitamins and fiber for almost no calories.",
 "prompt": "Square ultra-realistic overhead food photograph of sautéed beef strips with colorful red and yellow pepper strips and onion, served over white rice, garnished with coriander, in a bowl, on a light wooden table, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Homemade Lean Beef Burger with Salad",
 "hook": "The burger that beats the craving and still helps you slim down — made at home with lean beef, no greasy bun.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 440,
 "ings": ["9 oz lean ground beef", "½ onion, finely chopped", "1 clove of garlic, chopped",
          "salt, pepper and parsley to taste", "1 teaspoon olive oil", "2 whole-grain burger buns",
          "lettuce, tomato and onion slices to build"],
 "passos": [
   "In a bowl, mix the ground beef with the chopped onion, the garlic, salt, pepper and parsley. Knead with your hands just until it holds together, without overworking it (or the burger turns tough).",
   "Divide the beef in two and shape two patties, pressing flat with your hands. Make a small dimple in the center of each with your thumb — this stops them puffing up in the middle.",
   "Heat a nonstick pan with a few drops of olive oil over medium-high heat. Add the burgers and leave 3 to 4 minutes per side, without pressing with the spatula, until golden outside and cooked to your liking inside.",
   "If you like, lightly toast the whole-grain buns, cut open, in the pan.",
   "Build it: bun, lettuce, the burger, tomato and onion. Close and serve. For an even lighter version, eat the burger without the bun, with a generous salad on the side."],
 "porcoes8": ["1 burger · no bun · salad",
              "1 burger · ½ bun · salad",
              "1 burger · 1 bun · salad",
              "1 burger · 1 bun · salad",
              "1 large burger · 1 bun · salad",
              "1 large burger · 1 bun · salad",
              "2 burgers · 1 bun · salad",
              "2 burgers · 1 bun · salad"],
 "dica": "The problem with a fast-food burger is the fatty meat, the sauce and the frying. Made at home with lean beef and grilled with no oil, it becomes pure protein. Eating it with plenty of salad and little (or no) bun, you beat the craving without blowing your calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a homemade lean beef burger in a wholegrain bun with lettuce, tomato and onion, a fresh side salad, on a wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "White Fish with Vegetables and Couscous",
 "hook": "A delicate white fillet over fluffy couscous — light, elegant and ready before you notice.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 white fish fillet (hake, whiting or tilapia, about 5 oz)", "½ cup couscous",
          "½ cup hot water", "1 cup chopped vegetables (green beans, carrot, peas)",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Put the couscous in a bowl with a pinch of salt, cover with the hot water, cover with a plate and leave 5 minutes. Then fluff with a fork until loose.",
   "Steam the chopped vegetables or cook in a little boiling water for 5 minutes, until soft but still firm. Drain.",
   "Season the fish with salt, pepper and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat. Add the fillet and leave 3 to 4 minutes per side, flipping carefully once, until golden and it flakes with a fork.",
   "Mix the vegetables into the couscous. Build the plate with the vegetable couscous and the fillet on top. Sprinkle parsley and serve."],
 "porcoes8": ["4 oz fish · ⅓ cup couscous · vegetables",
              "5 oz fish · ½ cup couscous · vegetables",
              "5 oz fish · ½ cup couscous · vegetables",
              "6 oz fish · ⅔ cup couscous · drizzle of olive oil",
              "6 oz fish · ⅔ cup couscous · vegetables",
              "7 oz fish · ¾ cup couscous · vegetables",
              "8 oz fish · 1 cup couscous · drizzle of olive oil",
              "9 oz fish · 1 cup couscous · drizzle of olive oil"],
 "dica": "White fish like hake and whiting are very lean and light, ideal for the lunch of anyone who wants to lose weight. Couscous cooks with just hot water, no fat, and with the vegetables it becomes a colorful, fluffy side full of fiber.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared white fish fillet over couscous mixed with green beans, carrot and peas, a lemon wedge and parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken and Vegetable Skewers with Rice",
 "hook": "Colorful and fun to put together, the skewers roast evenly and give any lunch a party feel.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 450,
 "ings": ["2 chicken breast fillets, cubed (about 10 oz)", "1 bell pepper, in squares", "1 onion, in pieces",
          "1 zucchini, in thick rounds", "cherry tomatoes", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and paprika to taste", "rice to serve", "skewer sticks"],
 "passos": [
   "Season the chicken cubes with salt, pepper, paprika and the lemon juice. Let it take on flavor for 10 minutes.",
   "Build the skewers alternating a chicken cube, a piece of pepper, one of onion, a zucchini round and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or grill over medium-high heat. Add the skewers and turn every 3 minutes, until the chicken is golden on all sides and white inside (about 12 minutes total).",
   "Serve the skewers over a portion of rice."],
 "porcoes8": ["1 skewer · 3 tbsp rice",
              "2 skewers · 4 tbsp rice",
              "2 skewers · 5 tbsp rice",
              "2 skewers · 5 tbsp rice · extra chicken",
              "2 skewers · 5 tbsp rice",
              "3 skewers · 6 tbsp rice",
              "3 skewers · 7 tbsp rice",
              "3 large skewers · 8 tbsp rice"],
 "dica": "Skewers help control the portion naturally and mix plenty of vegetables with the protein. The lean grilled chicken is filling with no fat, and the colorful vegetables fill the plate with fiber and vitamins for almost no calories.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled chicken and vegetable skewers with pepper, onion, zucchini and cherry tomato, served over rice on a plate, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Potato Salad with Egg and Tuna",
 "hook": "The creamy potato salad from parties, without the heavy mayo — it becomes a complete, light lunch.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 410,
 "ings": ["2 medium potatoes, cubed", "2 boiled eggs", "1 can of tuna in water, drained",
          "3 tablespoons plain unsweetened yogurt", "1 teaspoon mustard",
          "red onion and fresh herbs, chopped", "salt, pepper and juice of ½ lemon to taste"],
 "passos": [
   "Cook the potato cubes in boiling salted water for 12 to 15 minutes, until soft but not falling apart (a fork goes in easily). Drain and let cool a little.",
   "Cook the eggs for 9 minutes, run under cold water, peel and cut into pieces.",
   "Prepare the dressing: mix the yogurt, the mustard, the lemon juice, salt and pepper in a large bowl.",
   "Add to the bowl the warm potato, the drained tuna, the eggs, the red onion and the fresh herbs.",
   "Mix carefully, so the potato does not fall apart. Taste for salt and serve right away or chilled."],
 "porcoes8": ["½ serving · ½ can tuna · 1 egg",
              "1 serving · 1 can tuna · 2 eggs",
              "1 serving · 1 can tuna · 2 eggs",
              "1 serving · 1 can tuna · 2 eggs · green salad",
              "1 serving · 1 can tuna · 2 eggs",
              "1 large serving · 1½ can tuna · 2 eggs",
              "large serving · 1½ can tuna · 3 eggs",
              "double serving · 2 cans tuna · 3 eggs"],
 "dica": "Swapping mayo for yogurt with mustard cuts a lot of fat and adds protein. The tuna and egg turn a potato salad into a complete, filling meal. Chilled potato even forms a special fiber that feeds the good bacteria in your gut.",
 "prompt": "Square ultra-realistic overhead food photograph of a healthy potato salad with tuna, chopped boiled egg, red onion and herbs in a creamy yogurt dressing, in a white bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oven-Roasted Chicken with Root Vegetables",
 "hook": "Put everything on one tray and let the oven work — the chicken comes out golden and the vegetables soft and sweet.",
 "tempo": "45 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 skinless chicken thighs (or 2 thick fillets, about 10 oz)", "1 potato, in pieces",
          "1 carrot, in large pieces", "1 piece of squash, cubed", "1 onion, in wedges",
          "2 cloves of garlic", "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper and rosemary to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the potato, carrot, squash and onion into large, similar pieces, so they roast evenly.",
   "On a large roasting tray, spread the vegetables and the garlic cloves. Season with salt, pepper, rosemary and half the olive oil, and mix with your hands.",
   "Season the chicken with salt, pepper, the lemon juice and the rest of the olive oil. Place the pieces among the vegetables.",
   "Bake for 35 to 40 minutes, turning the vegetables halfway, until the chicken is golden and cooked through (the juice that runs out when pierced comes out clear) and the vegetables soft.",
   "Serve straight from the tray, with all the juices that formed on the bottom."],
 "porcoes8": ["1 thigh · ½ serving vegetables",
              "1 thigh · 1 serving vegetables",
              "1 large thigh · 1 serving vegetables",
              "2 thighs · 1 serving vegetables",
              "2 thighs · 1 serving vegetables",
              "2 thighs · 1 large serving vegetables",
              "2 thighs · large serving vegetables",
              "3 thighs · double serving vegetables"],
 "dica": "Roasting without skin and without too much oil keeps the chicken light, and the juice it releases seasons the vegetables with no need for fat. Squash and carrot turn sweet as they roast, beating the sweet craving, and fill the plate with fiber and vitamins for few calories.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-roasted chicken thighs with root vegetables, potato, carrot, pumpkin and onion on a roasting tray, sprig of rosemary, golden and juicy, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Baked Chicken Parmigiana with Salad",
 "hook": "The crispy, gratinated parmigiana of your dreams, baked instead of fried — all the pleasure, none of the frying.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["2 thin chicken breast fillets (about 10 oz)", "1 egg", "4 tablespoons whole-grain breadcrumbs",
          "1 cup homemade tomato sauce", "3 tablespoons low-fat grated mozzarella",
          "salt, pepper and oregano to taste", "green leaves for the salad"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Season the thin fillets with salt and pepper.",
   "Beat the egg in a deep plate. Put the breadcrumbs on another plate, mixed with oregano.",
   "Dip each fillet first in the egg, then in the breadcrumbs, pressing to coat both sides well.",
   "Put the fillets on a nonstick tray (or lined with parchment) and bake for 15 minutes, turning halfway, until the coating is golden and crispy.",
   "Cover each fillet with the tomato sauce and the grated cheese. Return to the oven for 8 more minutes, until the cheese melts and bubbles.",
   "Serve with a fresh green salad on the side."],
 "porcoes8": ["3.5 oz chicken · little cheese · salad",
              "4.5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · 3 tbsp rice",
              "5 oz chicken · cheese · 3 tbsp rice",
              "6 oz chicken · cheese · 4 tbsp rice",
              "7 oz chicken · cheese · 5 tbsp rice",
              "8 oz chicken · extra cheese · 5 tbsp rice"],
 "dica": "Parmigiana gets fattening because of the frying and the excess cheese. Breaded with whole-grain crumbs and baked in the oven, it comes out crispy with a fraction of the fat. A bit of low-fat cheese on top beats the craving for something gratinated, and the salad balances the plate.",
 "prompt": "Square ultra-realistic overhead food photograph of an oven-baked chicken parmigiana with tomato sauce and melted cheese, crispy golden coating, a fresh green salad beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Rice, Edamame and Salmon Bowl",
 "hook": "Inspired by the Hawaiian poke: fresh, colorful and nourishing, put together in a bowl and filling without weighing you down.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 480,
 "ings": ["1 salmon steak, cubed (about 4.5 oz)", "4 tablespoons cooked rice", "½ cup cooked edamame (green soybeans)",
          "½ cucumber, diced", "½ carrot, grated", "½ avocado, sliced", "1 tablespoon light soy sauce",
          "sesame seeds, juice of ½ lemon and chives to taste"],
 "passos": [
   "Cook the edamame in boiling water for 4 minutes, drain and, if in the pod, take out the beans.",
   "Season the salmon cubes with the soy sauce and the lemon juice. Let it take on flavor for 5 minutes. (If you prefer it cooked, quickly grill the cubes in a pan for 3 minutes.)",
   "In a bowl, put the rice on one side as a base.",
   "Arrange on top, in separate groups, the salmon, the edamame, the cucumber, the grated carrot and the avocado.",
   "Drizzle with a bit more soy sauce, sprinkle sesame seeds and chives and serve."],
 "porcoes8": ["3.5 oz salmon · 3 tbsp rice · ¼ avocado",
              "4.5 oz salmon · 4 tbsp rice · ½ avocado",
              "4.5 oz salmon · 5 tbsp rice · ½ avocado",
              "5 oz salmon · 5 tbsp rice · ½ avocado",
              "5 oz salmon · 5 tbsp rice · ½ avocado",
              "6 oz salmon · 6 tbsp rice · ½ avocado",
              "7 oz salmon · 7 tbsp rice · avocado",
              "8 oz salmon · 8 tbsp rice · avocado"],
 "dica": "It is a complete, balanced dish: protein and omega-3 from the salmon, plant protein from the edamame, good fat from the avocado and the fiber of the raw vegetables. Put together in a bowl, it is pretty and filling, proving healthy food can be a feast for the eyes.",
 "prompt": "Square ultra-realistic overhead food photograph of a poke-style bowl with salmon cubes, rice, edamame, cucumber, grated carrot and avocado slices, sesame seeds on top, in a bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Hearty Vegetable Soup with Shredded Chicken",
 "hook": "A soup that is a real meal: hearty with chicken and vegetables, it warms the body and fills you without weighing you down.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 380,
 "ings": ["1 chicken breast fillet (about 5 oz)", "1 potato, cubed", "1 carrot, cubed",
          "1 zucchini, cubed", "½ cup corn or peas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste", "4 cups (1 quart) water"],
 "passos": [
   "In a large pot, heat the olive oil and fry the onion and garlic for 2 minutes, stirring, until translucent.",
   "Add the whole chicken fillet and the water. Bring to a boil and cook for 15 minutes, until the chicken is cooked.",
   "Remove the chicken, let it cool a little and shred with two forks. Set aside.",
   "In the same water, add the potato, the carrot, the zucchini and the corn. Season with salt and pepper and cook for 12 to 15 minutes, until the vegetables are soft.",
   "Return the shredded chicken to the pot, adjust the salt and cook for 3 more minutes. Sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · chicken · no extra potato",
              "2 ladles · chicken · vegetables",
              "2 ladles · chicken · vegetables",
              "2 ladles · extra chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Soups are great for losing weight: the volume of liquid and vegetables fills your stomach for very few calories, and the heat makes you eat more slowly. With the shredded chicken, it stops being just a starter and becomes a complete, light and comforting meal.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty chicken and vegetable soup with shredded chicken, potato, carrot, zucchini and corn in a broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Savory Oat Pancake Stuffed with Chicken",
 "hook": "The batter is just egg and oats, mixes in seconds and becomes a golden pancake stuffed with creamy chicken.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 egg", "3 tablespoons oats", "3 tablespoons water", "1 pinch of salt",
          "1 cooked and shredded chicken fillet (about 3.5 oz)", "2 tablespoons tomato sauce",
          "1 tablespoon plain yogurt", "1 teaspoon olive oil", "oregano to taste"],
 "passos": [
   "In a bowl, beat with a fork the egg, the oats, the water and the salt until you get a smooth batter. Let it rest 3 minutes so the oats absorb the liquid.",
   "Heat a nonstick pan with half the olive oil over medium heat. Pour in the batter and spread it by tilting the pan, forming a thin disc.",
   "Leave 2 minutes, until the edge releases, flip carefully and brown the other side for 1 more minute. Remove the pancake.",
   "Mix the shredded chicken with the tomato sauce, the yogurt and the oregano, and warm quickly in the pan.",
   "Fill the pancake with the chicken, fold it in half or roll it and serve hot, with a salad on the side if you like."],
 "porcoes8": ["1 pancake · 3 oz chicken",
              "1 pancake · 3.5 oz chicken",
              "1 pancake · 4 oz chicken",
              "1 pancake · 4 oz chicken · salad",
              "1 pancake · 4.5 oz chicken · salad",
              "2 pancakes · 5 oz chicken",
              "2 pancakes · 6 oz chicken · salad",
              "2 pancakes · 7 oz chicken · salad"],
 "dica": "The egg-and-oat batter swaps white flour for fiber and protein, filling you far more than a regular pancake. Stuffed with shredded chicken and a light yogurt sauce, it becomes a practical, tasty and complete meal, great for dinner too.",
 "prompt": "Square ultra-realistic overhead food photograph of a savory oat pancake filled with shredded chicken in tomato sauce, folded on a plate, a small salad beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Garlic Shrimp with Vegetables and Rice",
 "hook": "Pink shrimp browned in garlic, filling the whole kitchen with aroma — a light, special weekend lunch.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["5 oz peeled shrimp", "4 tablespoons cooked rice", "1 cup broccoli and green beans",
          "2 cloves of garlic, chopped", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and parsley to taste"],
 "passos": [
   "Dry the shrimp well with paper towel and season with salt, pepper and the lemon juice. Let it take on flavor for 5 minutes.",
   "Cut the broccoli into florets and the green beans into pieces. Steam or cook in a little boiling water for 4 minutes, until green and soft but still firm. Drain.",
   "Heat a nonstick pan with the olive oil over medium heat. Add the chopped garlic and stir for 30 seconds, just until fragrant and starting to brown — careful not to burn it, or it turns bitter.",
   "Add the shrimp and sauté (stir over medium-high heat) for 2 to 3 minutes, just until pink and curled. Do not overcook, or they get rubbery.",
   "Add the vegetables and the already-cooked rice to the pan and mix for 1 minute, to pick up the garlic flavor. Sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · 3 tbsp rice · vegetables",
              "5 oz shrimp · 4 tbsp rice · vegetables",
              "5 oz shrimp · 5 tbsp rice · vegetables",
              "6 oz shrimp · 5 tbsp rice · drizzle of olive oil",
              "6 oz shrimp · 5 tbsp rice · vegetables",
              "7 oz shrimp · 6 tbsp rice · vegetables",
              "8 oz shrimp · 7 tbsp rice · drizzle of olive oil",
              "9 oz shrimp · 8 tbsp rice · drizzle of olive oil"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories, so you can serve yourself well with no guilt. Browned in garlic, it gains lots of flavor with just a drizzle of olive oil, and with the vegetables and a measured portion of rice it becomes a light dish with a restaurant feel.",
 "prompt": "Square ultra-realistic overhead food photograph of garlic shrimp sautéed golden, served with steamed broccoli, green beans and white rice, parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef Meatballs in Sauce with Mashed Potato",
 "hook": "Tender meatballs in a hearty tomato sauce, over a light mash — the warm hug your diet allows.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 490,
 "ings": ["9 oz lean ground beef", "1 egg", "2 tablespoons oats", "1 clove of garlic, chopped",
          "3 tomatoes, chopped (or tomato sauce)", "1 onion, chopped", "2 medium potatoes",
          "1 teaspoon olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until very soft. Drain and mash with a fork, with a pinch of salt, into a smooth mash. For creamier, add a little of the cooking water.",
   "In a bowl, mix the ground beef, the egg, the oats, half the garlic, salt and pepper. Knead with your hands and roll walnut-sized balls.",
   "Heat the olive oil in a pot and brown the meatballs on all sides, turning carefully, for 5 minutes. Remove and set aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the tomatoes, salt and pepper and cook for 8 minutes, until it becomes a sauce.",
   "Return the meatballs to the sauce and cook for 8 more minutes, until cooked through. Sprinkle basil.",
   "Serve the meatballs with the sauce over the mashed potato."],
 "porcoes8": ["3 meatballs · ½ serving mash",
              "4 meatballs · 1 serving mash",
              "4 meatballs · 1 serving mash",
              "5 meatballs · 1 serving mash",
              "5 meatballs · 1 serving mash",
              "6 meatballs · 1 large serving mash",
              "7 meatballs · large serving mash",
              "8 meatballs · double serving mash"],
 "dica": "The meatballs use oats instead of more bread, which binds them with fiber rather than white starch. Made with lean beef and cooked in the sauce (not fried), they stay juicy and light. Regular mashed potato, in the right amount, is comforting and filling.",
 "prompt": "Square ultra-realistic overhead food photograph of tender beef meatballs in tomato sauce served over creamy mashed potato, garnished with basil, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Light Chicken and Vegetable Risotto",
 "hook": "The creaminess of risotto with no butter and no excess cheese — the rice releases its own cream and hugs the chicken and vegetables.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 480,
 "ings": ["1 cup rice (arborio or regular)", "2 chicken breast fillets, cubed (about 10 oz)",
          "1 carrot, diced", "½ cup peas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "1 tablespoon grated cheese", "salt, pepper and parsley to taste",
          "homemade vegetable stock or hot water (about 3 cups)"],
 "passos": [
   "Season the chicken cubes with salt and pepper. Heat the olive oil in a pot and brown the chicken for 5 minutes, stirring. Remove and set aside.",
   "In the same pot, fry the onion and garlic for 2 minutes. Add the rice and stir for 1 minute, just to coat the grains in the seasoning.",
   "Start adding the hot stock a little at a time, one ladle at a time, stirring constantly. Only add more stock when the previous one has almost dried up.",
   "Halfway through cooking (about 10 minutes), add the carrot and the peas. Keep stirring and adding stock.",
   "When the rice is soft and creamy (about 18 to 20 minutes total), return the chicken, add the grated cheese and stir. Turn off, sprinkle parsley and serve right away."],
 "porcoes8": ["½ serving · chicken",
              "1 serving · chicken",
              "1 serving · chicken",
              "1 serving · extra chicken",
              "1 serving · extra chicken",
              "1 large serving · chicken",
              "large serving · extra chicken",
              "double serving · extra chicken"],
 "dica": "Traditional risotto uses lots of butter and cheese. Here, the creaminess comes from the rice's own starch released as you stir, with just a touch of cheese. With plenty of chicken and vegetables, the dish is hearty and satisfying, proving you can eat risotto with no guilt.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy chicken and vegetable risotto with carrot and peas, garnished with parsley and a little grated cheese, in a shallow bowl, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
