# -*- coding: utf-8 -*-
"""BONUS 1 — VEGETARIAN DIET: 8 NEW recipes (photos 151-158). English (US market).
Lacto-ovo vegetarian; protein from legumes, tofu, eggs and cheese.
ALMOCOS -> type 'almoco' (targets 360/440/500/560 · 540/610/680/750), photos 151-154
JANTARES -> type 'jantar' (targets 340/420/480/540 · 520/590/650/720), photos 155-158
US units: oz / cups / tbsp / tsp / °F.
"""

ALMOCOS = [
{
 "nome": "Chickpea Bowl with Rice and Roasted Vegetables",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A colorful, hearty bowl with no meat at all — chickpeas hold the whole afternoon like a protein plate.",
 "tempo": "35 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["½ cup cooked chickpeas (or canned, drained)", "4 tablespoons cooked brown rice",
          "1 zucchini, in pieces", "½ bell pepper, in pieces", "½ red onion, in pieces", "cherry tomatoes",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper, turmeric and oregano to taste", "green leaves"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the zucchini, pepper and onion into similar, bite-sized pieces.",
   "On a roasting tray, spread the vegetables and the cherry tomatoes, season with salt, pepper, oregano and half the olive oil, and mix with your hands.",
   "Bake for 20 to 25 minutes, until the vegetables are soft and golden at the edges. Turn halfway.",
   "In a pan, heat the rest of the olive oil and sauté the chickpeas with the turmeric, salt and pepper for 3 minutes, stirring, just to take on flavor and brown a little.",
   "Build the bowl: a bed of green leaves, the rice on one side, the chickpeas and the roasted vegetables on top. Drizzle with the lemon juice and serve."],
 "porcoes8": ["⅓ cup chickpeas · 3 tbsp rice · vegetables",
              "½ cup chickpeas · 4 tbsp rice · vegetables",
              "½ cup chickpeas · 5 tbsp rice · vegetables",
              "⅔ cup chickpeas · 5 tbsp rice · drizzle of olive oil",
              "⅔ cup chickpeas · 5 tbsp rice · vegetables",
              "¾ cup chickpeas · 6 tbsp rice · 1 tbsp nuts",
              "1 cup chickpeas · 7 tbsp rice · avocado",
              "1 cup chickpeas · 8 tbsp rice · avocado"],
 "dica": "Chickpeas combine protein and fiber that fill you like a meat plate, and together with brown rice they form a complete protein (the legume + grain duo vegetarians use). Roasting the vegetables concentrates the flavor with no fat, keeping the dish light and full of taste.",
 "prompt": "Square ultra-realistic overhead food photograph of a colorful vegetarian bowl with chickpeas, brown rice, roasted zucchini, pepper, red onion and cherry tomatoes on green leaves, in a white bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Lentil Shepherd's Pie with Mashed Potato",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "All the comfort of a gratinated shepherd's pie, with a seasoned lentil filling instead of meat — creamy and full of plant protein.",
 "tempo": "45 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["1 cup cooked lentils", "2 medium potatoes", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 tomato, chopped", "1 carrot, grated", "1 teaspoon olive oil",
          "2 tablespoons grated cheese", "salt, pepper, turmeric and fresh herbs to taste"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until very soft. Drain and mash with a fork, with a pinch of salt, into a smooth mash.",
   "In a pan, heat the olive oil and fry the onion and garlic for 2 minutes. Add the grated carrot and the tomato and cook for 3 minutes.",
   "Add the cooked lentils, the turmeric, salt and pepper and cook 5 more minutes, mashing the lentils a little with the spoon, into a hearty filling.",
   "In a baking dish, spread half the mash on the bottom, the lentil filling in the middle and the rest of the mash on top. Sprinkle the grated cheese.",
   "Bake at medium-high heat (400°F) for 15 minutes, until the top is golden. Sprinkle fresh herbs and serve."],
 "porcoes8": ["½ serving · salad",
              "1 serving · salad",
              "1 serving · salad",
              "1 serving · 1 extra tbsp cheese · salad",
              "1 serving · extra lentils · salad",
              "1 large serving · salad",
              "1 large serving · extra lentils · salad",
              "double serving · salad"],
 "dica": "Lentils are rich in iron, fiber and plant protein, a trio that is very filling — in the pie, they replace meat easily. With the mashed potato in the right amount and a bit of gratinated cheese, it is a comforting dish that beats the craving for heavy food.",
 "prompt": "Square ultra-realistic overhead food photograph of a lentil shepherd's pie topped with golden mashed potato gratin in a white baking dish, a spoon lifting a portion, a small salad beside it, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vegetable Frittata",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A tall, fluffy omelette, baked with colorful vegetables and cheese — egg protein in a dish you cut into slices that pleases everyone.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["5 eggs", "1 zucchini, diced", "½ bell pepper, chopped", "1 tomato, chopped", "handful of spinach",
          "3 tablespoons white cheese, cubed", "1 teaspoon olive oil",
          "chives, salt and pepper to taste", "green leaves for the salad"],
 "passos": [
   "Turn the oven to medium heat (350°F). In an oven-safe pan, heat the olive oil and sauté the zucchini and pepper for 4 minutes, stirring, until soft.",
   "Add the spinach and stir for 1 minute, just until it wilts. Spread the vegetables across the pan.",
   "In a bowl, beat the eggs with salt and pepper. Add the tomato, the cheese and the chives and mix.",
   "Pour the eggs over the vegetables in the pan and leave 2 minutes on the heat, just to set the edge.",
   "Put the pan in the oven for 15 minutes, until the frittata puffs up, sets in the center and browns on top. Cut into slices and serve with a green salad."],
 "porcoes8": ["1 slice · salad",
              "1 large slice · salad",
              "1 large slice · salad · 2 tbsp rice",
              "2 slices · salad · 2 tbsp rice",
              "2 slices · salad · 3 tbsp rice",
              "2 large slices · salad · 3 tbsp rice",
              "2 large slices · salad · 4 tbsp rice",
              "3 slices · salad · 4 tbsp rice"],
 "dica": "Eggs are a complete, very filling protein, ideal for a vegetarian lunch with no legumes. Baked with vegetables and a bit of cheese, the frittata goes a long way, keeps well in the fridge and beats hunger in a light, nourishing way.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked vegetable frittata with zucchini, pepper, tomato and spinach, cut into slices in a skillet, a fresh green salad beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vegetarian Bean and Chickpea Chili",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A spicy, hearty stew with no meat at all — proof that vegetarian food also fills the plate and the belly.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 460,
 "ings": ["1 cup cooked red beans", "1 cup cooked chickpeas", "½ cup corn",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 bell pepper, chopped", "2 tomatoes, chopped (or tomato sauce)",
          "1 teaspoon olive oil", "1 teaspoon cumin", "salt, pepper and paprika to taste",
          "rice to serve"],
 "passos": [
   "Heat the olive oil in a pot over medium heat. Fry the onion, garlic and pepper for 3 minutes, stirring, until soft.",
   "Add the cumin, the paprika, salt and pepper and stir for 30 seconds, so the seasonings release their aroma.",
   "Add the chopped tomatoes and cook for 5 minutes, until they break down into a sauce.",
   "Add the red beans, the chickpeas and the corn. If it gets dry, add half a cup of water.",
   "Lower the heat and cook for 15 minutes, stirring now and then, until it thickens into a creamy stew. Serve with a little rice."],
 "porcoes8": ["½ serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · avocado",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "large serving · 7 tbsp rice · avocado",
              "double serving · 8 tbsp rice"],
 "dica": "Beans and chickpeas together form a very complete plant protein, with a mountain of fiber that fills you for hours. Served with rice, it completes the protein. It is a cheap dish that goes a long way and proves you can eat well with no meat.",
 "prompt": "Square ultra-realistic overhead food photograph of a vegetarian red bean and chickpea chili with corn and pepper in a rustic bowl, a little rice beside it, coriander on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
]

JANTARES = [
{
 "nome": "Hearty Lentil Soup with Vegetables",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "A soup that is a real meal: the lentils make the broth hearty and full of protein, warming and filling on a cold night.",
 "tempo": "40 min", "rende": "3 servings", "kcal_base": 380,
 "ings": ["1 cup dry lentils", "1 potato, cubed", "1 carrot, cubed", "1 celery stalk, chopped (optional)",
          "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped", "1 teaspoon olive oil",
          "salt, pepper, turmeric and fresh herbs to taste", "5 cups water"],
 "passos": [
   "Rinse the lentils. In a pot, heat the olive oil and fry the onion and garlic for 2 minutes, stirring.",
   "Add the tomato, the carrot, the potato and the celery and stir for 2 minutes.",
   "Add the lentils, the turmeric, salt, pepper and the water. Bring to a boil.",
   "Lower the heat and cook for 25 to 30 minutes, stirring now and then, until the lentils and vegetables are very soft and the broth thickens. If it dries too much, add a bit of hot water.",
   "Taste for salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · no bread",
              "2 ladles · no bread",
              "2 ladles · 1 slice bread",
              "2 ladles · 1 slice bread",
              "2 ladles · 1 slice bread",
              "3 ladles · 1 slice bread",
              "3 ladles · 2 slices bread",
              "3 large ladles · 2 slices bread"],
 "dica": "Lentils are one of the legumes richest in protein and iron, and in the soup they make the broth hearty enough to be a complete dinner with no meat. The lots of liquid and vegetables fill your stomach for few calories — light, warm and comforting.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty lentil soup with potato, carrot and tomato in a thick broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Tofu with Vegetables and Rice",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "The golden tofu soaks up the seasoning and turns delicious — a meat-free option that truly fills you and is light for the evening.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["5 oz firm tofu, sliced", "4 tablespoons cooked brown rice", "1 cup broccoli and carrot",
          "1 tablespoon light soy sauce", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "grated ginger (optional)", "salt and pepper to taste"],
 "passos": [
   "Dry the tofu slices well with paper towel, pressing lightly — the drier it is, the better it browns.",
   "Season the tofu with the soy sauce, the garlic and the ginger. Let it take on flavor for 5 minutes.",
   "Heat a nonstick pan with half the olive oil over medium-high heat. Grill the tofu slices for 3 to 4 minutes per side, without moving them, until a golden crust forms. Remove and set aside.",
   "Cut the broccoli into florets and the carrot into rounds. In the same pan, with the rest of the olive oil, sauté the vegetables for 4 minutes, until soft but still firm.",
   "Build the plate with the brown rice, the vegetables and the grilled tofu on top. Drizzle with a bit more soy sauce if you like."],
 "porcoes8": ["4 oz tofu · 3 tbsp rice · vegetables",
              "5 oz tofu · 4 tbsp rice · vegetables",
              "5 oz tofu · 5 tbsp rice · vegetables",
              "6 oz tofu · 5 tbsp rice · drizzle of olive oil",
              "6 oz tofu · 5 tbsp rice · vegetables",
              "7 oz tofu · 6 tbsp rice · vegetables",
              "8 oz tofu · 7 tbsp rice · 1 tbsp nuts",
              "9 oz tofu · 8 tbsp rice · nuts"],
 "dica": "Tofu is made from soy and brings plant protein with little fat, one of the best options to vary from meat. Well dried and grilled, it gains texture and soaks up the seasonings. With vegetables and brown rice, it becomes a complete, light dinner full of fiber.",
 "prompt": "Square ultra-realistic overhead food photograph of golden pan-grilled tofu slices with sautéed broccoli and carrot over brown rice, in a bowl, sesame and soy glaze, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Eggplant Stuffed with Chickpeas and Cheese",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "The eggplant itself becomes the bowl, stuffed with seasoned chickpeas and gratinated with cheese — pretty, hearty and meat-free.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["1 large eggplant", "1 cup cooked chickpeas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tomato, chopped", "1 teaspoon olive oil", "2 tablespoons low-fat grated cheese",
          "salt, pepper, cumin and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the eggplant in half lengthwise. With a spoon, scoop out part of the center, forming two 'boats'. Chop the scooped-out flesh.",
   "Put the boats on a roasting tray, drizzle with a little olive oil and bake for 10 minutes, just to soften.",
   "In a pan, heat the rest of the olive oil and fry the onion and garlic for 2 minutes. Add the tomato, the chopped eggplant flesh, the chickpeas, the cumin, salt and pepper and cook for 6 minutes, mashing the chickpeas a little, into a soft filling.",
   "Fill the boats with the chickpea mixture and sprinkle the grated cheese on top.",
   "Return to the oven for 15 minutes, until gratinated (the cheese melts and browns). Sprinkle parsley and serve."],
 "porcoes8": ["½ eggplant · salad",
              "1 stuffed eggplant · salad",
              "1 eggplant · 2 tbsp rice",
              "1 eggplant · extra chickpeas · salad",
              "1 eggplant · extra chickpeas · 2 tbsp rice",
              "1 large eggplant · 3 tbsp rice",
              "1 eggplant · double chickpeas · 4 tbsp rice",
              "eggplant + extra portion · 4 tbsp rice"],
 "dica": "Eggplant has lots of water and fiber, so it fills the plate for very few calories. Chickpeas bring the plant protein that replaces meat, and a bit of gratinated cheese beats the craving for something gratinated. A pretty, hearty and light vegetarian dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of two baked stuffed eggplant halves filled with seasoned chickpeas and melted cheese, sprinkled with parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chickpea Curry with Rice",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "A golden, fragrant sauce wrapping the chickpeas — creamy with light coconut milk, it is a vegetarian dinner full of flavor.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 440,
 "ings": ["2 cups cooked chickpeas", "1 onion, chopped", "2 cloves of garlic, chopped", "1 tomato, chopped",
          "1 teaspoon curry powder", "½ cup light coconut milk", "handful of spinach (optional)",
          "1 teaspoon olive oil", "salt, pepper and coriander to taste", "rice to serve"],
 "passos": [
   "Heat the olive oil in a pan over medium heat and fry the onion and garlic for 2 minutes, stirring.",
   "Add the curry and stir for 30 seconds, for the seasoning to release its aroma. Add the tomato and cook for 3 minutes, until it breaks down.",
   "Add the chickpeas and the light coconut milk and mix. Season with salt and pepper.",
   "Cook over low heat for 10 minutes, stirring now and then, until the sauce thickens. If you like, add the spinach in the last 2 minutes, just until it wilts.",
   "Sprinkle coriander and serve over a portion of rice."],
 "porcoes8": ["⅔ cup chickpeas · 3 tbsp rice",
              "1 cup chickpeas · 4 tbsp rice",
              "1 cup chickpeas · 5 tbsp rice",
              "1 cup chickpeas · 5 tbsp rice · spinach",
              "1 cup chickpeas · 5 tbsp rice",
              "1½ cup chickpeas · 6 tbsp rice",
              "1½ cup chickpeas · 7 tbsp rice",
              "2 cups chickpeas · 8 tbsp rice"],
 "dica": "Chickpeas are rich in protein and fiber, and in the curry they turn creamy and full of flavor. Light coconut milk gives the sauce its richness with far less fat than heavy cream. With rice, it forms a complete protein — a comforting, nourishing vegetarian dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a chickpea curry in a golden coconut sauce with spinach, served with white rice in a bowl, coriander on top, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
