# -*- coding: utf-8 -*-
"""30 receitas de CAFÉ DA MANHÃ (001-030). ALEMÃO.

Tradução literal de `receitas_cafe.py`. Convenções fixadas em GLOSSARIO-TRADUCAO.md:
tratamento por "du", medidas caseiras em EL/TL/Prise/Handvoll/Scheibe, e a
xícara convertida em PESO (não existe "Tasse" como medida na cozinha alemã).
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/001-030,
sem texto na imagem), e prompt duplicado é prompt que diverge.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 300/370/420/470 · 450/510/560/620
"""

RECEITAS = [
{
 "nome": "Bananen-Haferflocken-Pfannkuchen",
 "hook": "Drei Zutaten, die du schon zu Hause hast, in 10 Minuten fertig — und sie halten dich bis zum Mittagessen satt.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 325,
 "ings": ["1 reife Banane", "40 g Haferflocken (ca. 4 EL)", "1 Ei",
          "1 Prise Zimt", "1 Prise Backpulver (nach Wunsch, macht sie lockerer)",
          "etwas Öl oder Ölspray für die Pfanne"],
 "passos": [
   "Schäle die Banane und gib sie auf einen tiefen Teller. Zerdrücke sie gut mit einer Gabel, bis ein glattes Mus entsteht, ohne große Stücke.",
   "Gib das Ei dazu und rühre, bis alles gut vermischt ist.",
   "Gib die Haferflocken, den Zimt und das Backpulver dazu. Rühre um und lass den Teig 3 Minuten ruhen — die Haferflocken ziehen die Feuchtigkeit an und der Teig wird fester, so lässt er sich später leichter wenden.",
   "Erhitze eine beschichtete Pfanne bei mittlerer bis kleiner Hitze und streiche etwas Öl darauf (oder nimm Ölspray).",
   "Gib mit einem Löffel kleine Portionen Teig in die Pfanne, etwa so groß wie eine halbe Handfläche. Kleine Pfannkuchen lassen sich viel leichter wenden als große.",
   "Lass sie 2 bis 3 Minuten backen, bis oben kleine Bläschen entstehen und die Ränder fest werden. Wende sie vorsichtig und backe die andere Seite 1 bis 2 Minuten goldbraun.",
   "Serviere sie warm. Wenn du magst, gib noch Bananenscheiben, eine Handvoll Beeren oder 1 TL Honig darüber."],
 "porcoes8": ["¾ Banane · 30 g Haferflocken · 1 Ei",
              "1 Banane · 40 g Haferflocken · 1 Ei · 1 Handvoll Beeren",
              "1 Banane · 45 g Haferflocken · 1 Ei · 1 TL Erdnussmus",
              "1 Banane · 50 g Haferflocken · 1 Ei · 1 EL Erdnussmus",
              "1 Banane · 50 g Haferflocken · 2 Eier · 1 TL Erdnussmus",
              "1 große Banane · 55 g Haferflocken · 2 Eier · 1 EL Erdnussmus",
              "1 große Banane · 60 g Haferflocken · 2 Eier · 1 EL Erdnussmus · Beeren",
              "1 große Banane · 70 g Haferflocken · 2 Eier · 1,5 EL Erdnussmus"],
 "dica": "Hafer ist reich an Ballaststoffen, die die Verdauung verlangsamen und stundenlang satt halten — genau das verhindert den Hunger am Vormittag, der dich zum Naschen bringt. Die Banane bringt natürliche Süße ohne zugesetzten Zucker, und das Ei liefert Eiweiß, damit dein Muskel erhalten bleibt, während du Fett verlierst.",
},
{
 "nome": "Rührei mit Spinat und Vollkorntoast",
 "hook": "Das klassische Frühstück, das den Teller in weniger als 10 Minuten mit Eiweiß und Ballaststoffen füllt.",
 "tempo": "8 Min.", "rende": "1 Portion", "kcal_base": 340,
 "ings": ["2 Eier", "1 große Handvoll frische Spinatblätter", "1 Scheibe Vollkornbrot",
          "1 TL Olivenöl", "Salz und Pfeffer nach Geschmack", "1 kleine Tomate (nach Wunsch)"],
 "passos": [
   "Wasche den Spinat und lass ihn gut abtropfen. Wenn die Blätter groß sind, schneide sie einmal durch.",
   "Schlage die Eier in eine Schüssel, würze sie mit Salz und Pfeffer und verquirle sie leicht mit einer Gabel.",
   "Erhitze das Olivenöl in einer beschichteten Pfanne bei mittlerer Hitze. Gib den Spinat dazu und rühre 1 Minute, nur bis die Blätter zusammenfallen.",
   "Stelle die Hitze kleiner, gieße die verquirlten Eier über den Spinat und lass sie 30 Sekunden stehen, ohne zu rühren.",
   "Schiebe die Eier mit einem Pfannenwender langsam vom Rand zur Mitte, bis sie cremig und noch leicht feucht sind. Nimm die Pfanne vom Herd, bevor sie zu trocken werden.",
   "Toaste die Scheibe Vollkornbrot. Serviere das Rührei darauf oder daneben, wenn du magst mit Tomatenscheiben."],
 "porcoes8": ["1 Ei + 1 Eiweiß · ½ Scheibe Brot · Spinat, so viel du magst",
              "2 Eier · 1 Scheibe Brot · Spinat, so viel du magst",
              "2 Eier · 1 Scheibe Brot · etwas mehr Olivenöl",
              "2 Eier + 1 Eiweiß · 1 Scheibe Brot · 1 TL geriebener Käse",
              "3 Eier · 1 Scheibe Brot · 1 TL Olivenöl",
              "3 Eier · 2 Scheiben Brot · Spinat, so viel du magst",
              "3 Eier · 2 Scheiben Brot · 1 EL geriebener Käse",
              "4 Eier · 2 Scheiben Brot · 1 EL geriebener Käse"],
 "dica": "Eier sind vollwertiges Eiweiß und machen sehr satt — wer morgens Eier isst, hat über den Tag weniger Hunger. Der Spinat bringt Volumen und Ballaststoffe bei fast keinen Kalorien, du füllst also Teller und Magen, ohne die Kalorien zu sprengen.",
},
{
 "nome": "Griechischer Joghurt mit Beeren und Haferflocken",
 "hook": "In Schichten gebaut, ohne zu kochen — Eiweiß und Ballaststoffe in einem schönen Glas, in 3 Minuten.",
 "tempo": "3 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["1 Becher griechischer Naturjoghurt ohne Zucker (ca. 170 g)", "1 Handvoll Beeren (Erdbeeren, Heidelbeeren oder Himbeeren)",
          "3 EL Haferflocken", "1 TL Honig (nach Wunsch)", "Zimt nach Geschmack"],
 "passos": [
   "Wenn du Erdbeeren nimmst, wasche sie und schneide sie in kleine Stücke. Die anderen Beeren kannst du ganz lassen.",
   "Gib die Hälfte des Joghurts in ein Glas oder eine Schale.",
   "Verteile die Hälfte der Beeren und die Hälfte der Haferflocken darüber.",
   "Wiederhole das: der restliche Joghurt, danach die übrigen Beeren und Haferflocken.",
   "Streue zum Schluss eine Prise Zimt darüber und, wenn du magst, den Honig. Iss es gleich, solange die Haferflocken noch knusprig sind."],
 "porcoes8": ["120 g Joghurt · Beeren · 2 EL Haferflocken",
              "170 g Joghurt · Beeren · 3 EL Haferflocken",
              "170 g Joghurt · Beeren · 3 EL Haferflocken · 1 TL Honig",
              "200 g Joghurt · Beeren · 4 EL Haferflocken · 1 TL Honig",
              "200 g Joghurt · Beeren · 4 EL Haferflocken · 1 EL Nüsse",
              "250 g Joghurt · Beeren · 4 EL Haferflocken · 1 EL Nüsse",
              "250 g Joghurt · Beeren · 5 EL Haferflocken · 1 EL Nüsse",
              "300 g Joghurt · Beeren · 6 EL Haferflocken · 1 EL Nüsse"],
 "dica": "Griechischer Joghurt hat fast doppelt so viel Eiweiß wie normaler Joghurt, und das hält länger satt. Ohne zugesetzten Zucker kommt die Süße aus den Beeren — und die Haferflocken bringen Ballaststoffe und Biss, so wird aus einem schnellen Snack eine Mahlzeit, die trägt.",
},
{
 "nome": "Eiweiß-Omelett mit Tomate und Hüttenkäse",
 "hook": "Leicht, locker und voller Eiweiß — das Frühstück für alle, die abnehmen wollen, ohne zu hungern.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 250,
 "ings": ["3 Eiweiß (das Klare vom Ei) + 1 ganzes Ei", "1 kleine Tomate, gewürfelt", "2 EL Hüttenkäse",
          "gehackter Schnittlauch oder Petersilie", "Salz und Pfeffer nach Geschmack", "Ölspray"],
 "passos": [
   "Schneide die Tomate in kleine Würfel und tupfe sie mit Küchenpapier ab, damit das Omelett nicht weich wird.",
   "Gib das Eiweiß, das ganze Ei, Salz und Pfeffer in eine Schüssel. Verquirle alles 30 Sekunden mit einer Gabel, bis es leicht schäumt.",
   "Erhitze eine beschichtete Pfanne bei mittlerer Hitze und sprühe etwas Öl hinein. Verteile die Tomatenwürfel 1 Minute lang auf dem Pfannenboden.",
   "Gieße die verquirlten Eier darüber und kippe die Pfanne leicht, damit sich alles gleichmäßig verteilt.",
   "Wenn die Ränder fest werden (nach 1 bis 2 Minuten), verteile den Hüttenkäse auf einer Hälfte des Omeletts.",
   "Klappe das Omelett mit dem Pfannenwender über den Hüttenkäse. Lass es noch 1 Minute stehen und serviere es mit den Kräutern obendrauf."],
 "porcoes8": ["2 Eiweiß + 1 Ei · 1 EL Hüttenkäse",
              "3 Eiweiß + 1 Ei · 2 EL Hüttenkäse",
              "3 Eiweiß + 1 Ei · 2 EL Hüttenkäse · ½ Scheibe Brot",
              "3 Eiweiß + 1 Ei · 3 EL Hüttenkäse · 1 Scheibe Brot",
              "3 Eiweiß + 2 Eier · 2 EL Hüttenkäse · 1 Scheibe Brot",
              "4 Eiweiß + 2 Eier · 3 EL Hüttenkäse · 1 Scheibe Brot",
              "4 Eiweiß + 2 Eier · 3 EL Hüttenkäse · 2 Scheiben Brot",
              "5 Eiweiß + 2 Eier · 4 EL Hüttenkäse · 2 Scheiben Brot"],
 "dica": "Das Eiweiß vom Ei ist fast reines Protein, mit sehr wenig Fett und Kalorien — perfekt, um das Frühstück eiweißreicher zu machen, ohne dass es schwer wird. Der Hüttenkäse bringt Cremigkeit und ebenfalls viel Eiweiß, und die Tomate gibt Geschmack und Volumen für fast keine Kalorien.",
},
{
 "nome": "Overnight-Haferflocken mit Apfel und Zimt",
 "hook": "Du rührst sie abends an und morgens stehen sie fertig im Kühlschrank — keine Eile, kein Herd.",
 "tempo": "5 Min. + Kühlschrank", "rende": "1 Portion", "kcal_base": 350,
 "ings": ["40 g Haferflocken", "150 ml Milch (oder Pflanzendrink)", "½ Apfel, klein gewürfelt",
          "1 EL Naturjoghurt", "Zimt nach Geschmack", "1 TL Honig (nach Wunsch)"],
 "passos": [
   "Vermische die Haferflocken, die Milch und den Joghurt in einem Glas mit Deckel.",
   "Gib die Hälfte der Apfelwürfel und eine gute Prise Zimt dazu. Rühre gut um.",
   "Verschließe das Glas und stelle es für mindestens 4 Stunden in den Kühlschrank, oder über Nacht.",
   "Am Morgen sind die Haferflocken cremig und weich. Rühre noch einmal um.",
   "Gib den restlichen frischen Apfel und noch etwas Zimt darüber. Wenn du magst, kommt jetzt der Honig dazu. Iss es kalt, direkt aus dem Glas."],
 "porcoes8": ["30 g Haferflocken · 120 ml Milch · ½ Apfel",
              "40 g Haferflocken · 150 ml Milch · ½ Apfel",
              "45 g Haferflocken · 150 ml Milch · ½ Apfel · 1 TL Honig",
              "50 g Haferflocken · 180 ml Milch · 1 Apfel · 1 TL Honig",
              "50 g Haferflocken · 180 ml Milch · 1 Apfel · 1 EL Nüsse",
              "55 g Haferflocken · 200 ml Milch · 1 Apfel · 1 EL Nüsse",
              "60 g Haferflocken · 220 ml Milch · 1 Apfel · 1 EL Nüsse",
              "70 g Haferflocken · 250 ml Milch · 1 Apfel · 1,5 EL Nüsse"],
 "dica": "Die Haferflocken einweichen zu lassen ändert nichts an den Kalorien, macht die Ballaststoffe aber leichter verdaulich und die Mahlzeit cremiger und sättigender. Weil alles schon fertig im Kühlschrank steht, lässt du das Frühstück in der Hektik nicht aus — und eine ausgelassene Mahlzeit ist genau das, was viele abends zu viel essen lässt.",
},
{
 "nome": "Avocadobrot mit Ei",
 "hook": "Cremig, herzhaft und richtig sättigend — in 8 Minuten fertig.",
 "tempo": "8 Min.", "rende": "1 Portion", "kcal_base": 340,
 "ings": ["1 Scheibe Vollkornbrot", "½ reife Avocado (oder ¼ einer großen Avocado)", "1 Ei",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Chiliflocken nach Geschmack", "Ölspray"],
 "passos": [
   "Toaste die Scheibe Vollkornbrot, bis sie fest und goldbraun ist.",
   "Zerdrücke die Avocado in einer kleinen Schüssel mit der Gabel, gib den Zitronensaft, Salz und Pfeffer dazu. Rühre, bis eine Creme entsteht.",
   "Erhitze eine beschichtete Pfanne, sprühe etwas Öl hinein und brate das Ei bei mittlerer Hitze so, wie du es magst (als Spiegelei mit weichem Eigelb oder als Rührei).",
   "Streiche die Avocadocreme auf den Toast.",
   "Lege das Ei darauf und streue zum Schluss eine Prise Chiliflocken darüber. Serviere es sofort."],
 "porcoes8": ["½ Scheibe Brot · ¼ Avocado · 1 Ei",
              "1 Scheibe Brot · ½ Avocado · 1 Ei",
              "1 Scheibe Brot · ½ Avocado · 1 Ei · Blattsalat",
              "1 Scheibe Brot · ½ Avocado · 2 Eier",
              "1 Scheibe Brot · ½ Avocado · 2 Eier · Blattsalat",
              "2 Scheiben Brot · ½ Avocado · 2 Eier",
              "2 Scheiben Brot · 1 kleine Avocado · 2 Eier",
              "2 Scheiben Brot · 1 kleine Avocado · 3 Eier"],
 "dica": "Die Avocado enthält gutes Fett, das lange satt macht und die Mahlzeit cremig werden lässt, ganz ohne Butter. Zusammen mit dem Ei und dem Vollkornbrot hast du gutes Fett, Eiweiß und Ballaststoffe auf einer Scheibe — die Kombination, die den Hunger stundenlang fernhält.",
},
{
 "nome": "Haferbrei mit Banane und Erdnussmus",
 "hook": "Warm und wohltuend: das Frühstück, das nach Nachtisch schmeckt, aber für dich arbeitet.",
 "tempo": "8 Min.", "rende": "1 Portion", "kcal_base": 380,
 "ings": ["40 g Haferflocken", "200 ml Milch (oder Pflanzendrink)", "½ Banane, zerdrückt",
          "1 TL Erdnussmus", "Zimt nach Geschmack", "½ Banane in Scheiben zum Belegen"],
 "passos": [
   "Gib die Haferflocken, die Milch und die zerdrückte Banane in einen kleinen Topf.",
   "Erhitze alles bei mittlerer bis kleiner Hitze und rühre immer wieder mit einem Löffel um, damit nichts am Boden ansetzt.",
   "Nach 4 bis 5 Minuten wird die Masse dick und cremig. Wenn du es flüssiger magst, gib noch etwas Milch dazu.",
   "Nimm den Topf vom Herd, gib den Zimt dazu und rühre um.",
   "Fülle alles in eine Schüssel, lege die Bananenscheiben darauf und gib das Erdnussmus darüber. Serviere es warm."],
 "porcoes8": ["30 g Haferflocken · 180 ml Milch · ½ Banane · ohne Mus",
              "40 g Haferflocken · 200 ml Milch · 1 Banane · 1 TL Erdnussmus",
              "45 g Haferflocken · 200 ml Milch · 1 Banane · 1 TL Erdnussmus",
              "50 g Haferflocken · 220 ml Milch · 1 Banane · 1 EL Erdnussmus",
              "50 g Haferflocken · 220 ml Milch · 1 Banane · 1 EL Erdnussmus",
              "55 g Haferflocken · 250 ml Milch · 1 Banane · 1 EL Erdnussmus",
              "60 g Haferflocken · 250 ml Milch · 1 Banane · 1,5 EL Erdnussmus",
              "70 g Haferflocken · 300 ml Milch · 1 Banane · 2 EL Erdnussmus"],
 "dica": "Gekochter Hafer bildet im Magen ein Gel, das den Hunger hinauszögert. Die Banane süßt ohne Zucker und bringt Energie zurück, und das Erdnussmus liefert gutes Fett und Eiweiß — pass nur bei der Menge auf, denn es hat viele Kalorien: ein Löffel reicht schon.",
},
{
 "nome": "Smoothie-Bowl mit Banane und Beeren",
 "hook": "Dick zum Löffeln, eiskalt und bunt — sieht aus wie Eis, arbeitet aber für dein Abnehmen.",
 "tempo": "6 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["1 gefrorene Banane in Scheiben", "1 Handvoll gefrorene Beeren",
          "3 EL Naturjoghurt", "50 ml Milch (oder Pflanzendrink)",
          "2 EL Haferflocken und frisches Obst zum Belegen"],
 "passos": [
   "Nimm die Banane schon gefroren (schneide sie am Abend vorher in Scheiben und friere sie ein) — das macht den Smoothie dick, ganz ohne Eiswürfel.",
   "Gib die Banane, die gefrorenen Beeren, den Joghurt und die Milch in den Mixer.",
   "Mixe auf höchster Stufe und halte zwischendurch an, um mit einem Löffel umzurühren, wenn er stockt. Gib die Milch nur löffelweise dazu, so wenig wie möglich. Die Masse soll dick sein, wie Speiseeis.",
   "Fülle alles in eine Schüssel.",
   "Belege sie in schönen Reihen mit den Haferflocken und dem frischen Obst. Iss sie sofort mit dem Löffel, bevor sie schmilzt."],
 "porcoes8": ["1 Banane · Beeren · 2 EL Joghurt · 1 EL Haferflocken",
              "1 Banane · Beeren · 3 EL Joghurt · 2 EL Haferflocken",
              "1 Banane · Beeren · 3 EL Joghurt · 2 EL Haferflocken · Samen",
              "1 Banane · Beeren · 4 EL Joghurt · 3 EL Haferflocken",
              "1 Banane · Beeren · 4 EL Joghurt · 3 EL Haferflocken · 1 EL Nüsse",
              "1 große Banane · Beeren · 5 EL Joghurt · 3 EL Haferflocken · Nüsse",
              "1 große Banane · Beeren · 5 EL Joghurt · 4 EL Haferflocken · Nüsse",
              "2 Bananen · Beeren · 6 EL Joghurt · 4 EL Haferflocken · Nüsse"],
 "dica": "Gefrorenes Obst gibt die Eis-Textur ganz ohne Zucker und Sahne. Der Joghurt bringt Eiweiß dazu, und langsam mit dem Löffel zu essen lässt dein Gehirn die Sättigung wirklich wahrnehmen — ganz anders, als einen Smoothie in Sekunden durch den Strohhalm zu trinken.",
},
{
 "nome": "Gekochte Eier mit Avocado und Tomate",
 "hook": "Ohne Pfanne, ohne Chaos — Eiweiß und gutes Fett auf einem Teller, in wenigen Minuten angerichtet.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["2 Eier", "½ Avocado", "1 Tomate", "Saft von ½ Zitrone", "Salz, Pfeffer und Olivenöl nach Geschmack",
          "Blattsalat nach Geschmack"],
 "passos": [
   "Gib die Eier in einen Topf, bedecke sie mit kaltem Wasser und stelle ihn auf den Herd. Ab dem Kochen zählst du 8 bis 9 Minuten für ein festes Eigelb.",
   "Schneide währenddessen die Avocado und die Tomate in Scheiben und lege sie auf dem Teller auf etwas Blattsalat an.",
   "Gieße die Eier ab und halte sie 1 Minute unter kaltes Wasser — so lassen sie sich leichter pellen.",
   "Pelle die Eier, halbiere sie und lege sie auf den Teller.",
   "Beträufle alles mit dem Zitronensaft und etwas Olivenöl, würze mit Salz und Pfeffer und serviere."],
 "porcoes8": ["1 Ei · ¼ Avocado · Tomate",
              "2 Eier · ½ Avocado · Tomate",
              "2 Eier · ½ Avocado · Tomate · ½ Scheibe Brot",
              "2 Eier · ½ Avocado · Tomate · 1 Scheibe Brot",
              "3 Eier · ½ Avocado · Tomate · 1 Scheibe Brot",
              "3 Eier · ½ Avocado · Tomate · 2 Scheiben Brot",
              "3 Eier · 1 kleine Avocado · Tomate · 2 Scheiben Brot",
              "4 Eier · 1 kleine Avocado · Tomate · 2 Scheiben Brot"],
 "dica": "Das gekochte Ei ist das praktischste Eiweiß überhaupt: Du kannst gleich mehrere auf einmal kochen und im Kühlschrank aufbewahren. Mit Avocado und Tomate hast du ein vollständiges Frühstück mit gutem Fett und Ballaststoffen, ohne morgens den Herd anzumachen.",
},
{
 "nome": "Eiweiß-Pfannkuchen mit Haferflocken",
 "hook": "Der Pfannkuchen für Trainingstage: mehr Eiweiß, gleich einfach.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["40 g Haferflocken", "3 Eiweiß (das Klare vom Ei) (oder 2 Eiweiß + 1 Ei)", "½ Banane, zerdrückt",
          "1 Prise Backpulver", "Zimt nach Geschmack", "Ölspray"],
 "passos": [
   "Wenn du den Teig feiner magst, mixe die Haferflocken im Mixer zu Mehl. Magst du ihn rustikal, lass sie ganz.",
   "Vermische die Haferflocken, das Eiweiß, die zerdrückte Banane, das Backpulver und den Zimt in einer Schüssel, bis alles gut vermischt ist.",
   "Lass den Teig 3 Minuten ruhen, damit die Haferflocken quellen.",
   "Erhitze die beschichtete Pfanne bei mittlerer bis kleiner Hitze und sprühe etwas Öl hinein.",
   "Backe kleine Pfannkuchen. Lass sie 2 Minuten je Seite und wende sie, wenn kleine Bläschen entstehen.",
   "Serviere sie mit frischem Obst darüber. Verzichte auf gezuckerte Sirupe — die Banane süßt schon genug."],
 "porcoes8": ["2 Eiweiß · 30 g Haferflocken · ½ Banane",
              "3 Eiweiß · 40 g Haferflocken · ½ Banane",
              "3 Eiweiß · 45 g Haferflocken · ½ Banane · Obst",
              "2 Eiweiß + 1 Ei · 50 g Haferflocken · 1 Banane",
              "3 Eiweiß + 1 Ei · 50 g Haferflocken · 1 Banane",
              "3 Eiweiß + 1 Ei · 55 g Haferflocken · 1 Banane · Obst",
              "4 Eiweiß + 1 Ei · 60 g Haferflocken · 1 Banane · Obst",
              "4 Eiweiß + 2 Eier · 70 g Haferflocken · 1 Banane · Obst"],
 "dica": "Einen Teil der Eier durch Eiweiß zu ersetzen erhöht das Protein und senkt das Fett — gut für alle, die Form zeigen wollen. Eiweiß ist außerdem der Nährstoff, der am besten sättigt, also hält dieser Pfannkuchen den Hunger mit weniger Kalorien fern als die klassische süße Variante.",
},
{
 "nome": "Chiapudding mit Obst",
 "hook": "Du rührst es in 2 Minuten an, der Kühlschrank macht den Rest, und du wachst mit einem gesunden Nachtisch auf.",
 "tempo": "5 Min. + Kühlschrank", "rende": "1 Portion", "kcal_base": 280,
 "ings": ["3 EL Chiasamen", "200 ml Milch (oder Pflanzendrink)",
          "½ TL Vanillearoma (nach Wunsch)", "gewürfeltes Obst nach Geschmack zum Belegen",
          "1 TL Honig (nach Wunsch)"],
 "passos": [
   "Gib die Chiasamen, die Milch und das Vanillearoma in ein Glas mit Deckel. Rühre 30 Sekunden gut um.",
   "Warte 5 Minuten und rühre noch einmal um — dieses zweite Umrühren löst die Klümpchen auf, die sich bilden, und ist das Geheimnis für einen glatten Pudding.",
   "Verschließe das Glas und stelle es für mindestens 4 Stunden in den Kühlschrank, oder über Nacht.",
   "Die Chiasamen nehmen die Flüssigkeit auf und es entsteht ein Pudding mit geleeartiger Textur.",
   "Rühre vor dem Servieren um, belege ihn mit gewürfeltem Obst und gib, wenn du magst, den Honig darüber."],
 "porcoes8": ["2 EL Chiasamen · 150 ml Milch · Obst",
              "3 EL Chiasamen · 200 ml Milch · Obst",
              "3 EL Chiasamen · 200 ml Milch · Obst · 1 TL Honig",
              "3 EL Chiasamen · 220 ml Milch · Obst · 1 EL Granola",
              "4 EL Chiasamen · 220 ml Milch · Obst · 1 EL Granola",
              "4 EL Chiasamen · 250 ml Milch · Obst · 2 EL Granola",
              "4 EL Chiasamen · 250 ml Milch · Obst · 2 EL Granola · Nüsse",
              "5 EL Chiasamen · 300 ml Milch · Obst · 2 EL Granola · Nüsse"],
 "dica": "Chiasamen nehmen ein Vielfaches ihres eigenen Gewichts an Flüssigkeit auf und quellen im Magen, das gibt ein lang anhaltendes Sättigungsgefühl. Dazu sind sie reich an Ballaststoffen und Omega-3 — eine der sättigendsten Zutaten pro Kalorie, die es gibt.",
},
{
 "nome": "Gebackene Eier-Muffins mit Gemüse",
 "hook": "Einmal backen und die ganze Woche Frühstück fertig haben — nur noch aufwärmen und essen.",
 "tempo": "25 Min.", "rende": "6 Muffins (2 pro Portion)", "kcal_base": 220,
 "ings": ["6 Eier", "½ Paprika, gewürfelt", "1 Handvoll gehackter Spinat", "2 EL geriebener Käse",
          "Salz und Pfeffer nach Geschmack", "etwas Öl (oder Ölspray), damit nichts kleben bleibt"],
 "passos": [
   "Heize den Backofen auf 180 °C vor und streiche etwas Öl in die Muffinform (oder nimm Ölspray), damit die Eier nicht kleben bleiben.",
   "Hacke die Paprika und den Spinat in kleine Stücke.",
   "Verquirle die Eier in einer Schüssel mit Salz und Pfeffer. Gib das Gemüse und den Käse dazu und rühre um.",
   "Verteile die Masse auf die 6 Mulden und fülle jede etwa zu drei Vierteln.",
   "Backe sie 18 bis 20 Minuten, bis sie fest sind und leicht goldbraun werden. Ein Holzstäbchen in der Mitte soll sauber herauskommen.",
   "Lass sie lauwarm werden, bevor du sie aus der Form löst. Im Kühlschrank halten sie bis zu 4 Tage, wärme sie vor dem Essen auf."],
 "porcoes8": ["1 Muffin + Blattsalat",
              "2 Muffins",
              "2 Muffins · ½ Scheibe Brot",
              "2 Muffins · 1 Scheibe Brot",
              "3 Muffins · 1 Scheibe Brot",
              "3 Muffins · 2 Scheiben Brot",
              "3 Muffins · 2 Scheiben Brot · ¼ Avocado",
              "4 Muffins · 2 Scheiben Brot · ¼ Avocado"],
 "dica": "Fertiges Essen im Haus zu haben verhindert die falsche Entscheidung im Morgenhunger. Diese Muffins sind Eiweiß und Gemüse in einer festen Portionsgröße — du kannst sie einfrieren und hast immer ein Frühstück zur Hand, das trägt, ohne mit dem zu improvisieren, was du eigentlich nicht essen willst.",
},
{
 "nome": "Brot mit Ricotta, Erdbeeren und Honig",
 "hook": "Süß und cremig wie eine kleine Nascherei, aber mit Eiweiß und ohne schweren Zucker.",
 "tempo": "6 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["1 Scheibe Vollkornbrot", "3 EL Ricotta", "4 Erdbeeren in Scheiben",
          "1 TL Honig", "Zitronenschale und Minze (nach Wunsch)"],
 "passos": [
   "Toaste die Scheibe Brot, bis sie fest ist.",
   "Zerdrücke den Ricotta in einer Schüssel mit der Gabel, bis er cremig ist. Wenn er zu trocken ist, gib etwas Milch dazu.",
   "Streiche den Ricotta auf den Toast und bedecke die ganze Fläche.",
   "Verteile die Erdbeerscheiben darauf.",
   "Gib zum Schluss den Honig darüber und, wenn du magst, etwas Zitronenschale und ein paar Minzblättchen. Serviere es sofort."],
 "porcoes8": ["½ Scheibe Brot · 2 EL Ricotta · Erdbeeren",
              "1 Scheibe Brot · 3 EL Ricotta · Erdbeeren · 1 TL Honig",
              "1 Scheibe Brot · 3 EL Ricotta · Erdbeeren · Honig",
              "1 Scheibe Brot · 4 EL Ricotta · Erdbeeren · Honig · Nüsse",
              "1 Scheibe Brot · 4 EL Ricotta · Erdbeeren · 1 gekochtes Ei",
              "2 Scheiben Brot · 4 EL Ricotta · Erdbeeren · Honig",
              "2 Scheiben Brot · 5 EL Ricotta · Erdbeeren · Nüsse",
              "2 Scheiben Brot · 6 EL Ricotta · Erdbeeren · Nüsse · 1 Ei"],
 "dica": "Ricotta ist ein magerer, cremiger Käse mit viel Eiweiß — er stillt die Lust auf Süßes ohne die kalorienreiche Creme aus fertigen Aufstrichen. Die Erdbeere bringt Süße und Frische, und ein Teelöffel Honig süßt genug, ohne das Frühstück in eine Zuckerbombe zu verwandeln.",
},
{
 "nome": "Warme Haferflocken mit Kakao und Banane",
 "hook": "Schokoladengeschmack zum Frühstück, ohne Zucker und ohne schlechtes Gewissen.",
 "tempo": "8 Min.", "rende": "1 Portion", "kcal_base": 350,
 "ings": ["40 g Haferflocken", "200 ml Milch (oder Pflanzendrink)", "1 EL 100 % Kakaopulver",
          "1 Banane", "Zimt nach Geschmack", "Süßstoff oder 1 TL Honig (nach Wunsch)"],
 "passos": [
   "Vermische die Haferflocken, die Milch und das Kakaopulver in einem kleinen Topf, bevor du den Herd anmachst — so löst sich der Kakao ohne Klümpchen auf.",
   "Erhitze alles bei mittlerer bis kleiner Hitze und rühre immer wieder um.",
   "Zerdrücke die Hälfte der Banane und gib sie in den Topf; die andere Hälfte schneidest du in Scheiben und legst sie beiseite.",
   "Koche alles 4 bis 5 Minuten, bis es dick und cremig wird.",
   "Probiere und stelle die Süße mit Süßstoff oder einem Teelöffel Honig ein, wenn nötig.",
   "Serviere es in einer Schüssel mit den Bananenscheiben und einer Prise Zimt obendrauf."],
 "porcoes8": ["30 g Haferflocken · 180 ml Milch · 1 EL Kakao · ½ Banane",
              "40 g Haferflocken · 200 ml Milch · 1 EL Kakao · 1 Banane",
              "45 g Haferflocken · 200 ml Milch · 1 EL Kakao · 1 Banane",
              "50 g Haferflocken · 220 ml Milch · 1 EL Kakao · 1 Banane · Nüsse",
              "50 g Haferflocken · 220 ml Milch · Kakao · 1 Banane · 1 TL Erdnussmus",
              "55 g Haferflocken · 250 ml Milch · Kakao · 1 Banane · 1 EL Erdnussmus",
              "60 g Haferflocken · 250 ml Milch · Kakao · 1 Banane · Erdnussmus",
              "70 g Haferflocken · 300 ml Milch · Kakao · 1 Banane · Erdnussmus"],
 "dica": "100 % Kakao gibt den Schokoladengeschmack ohne den Zucker aus fertigem Kakaopulver — und bringt noch Antioxidantien mit. Die Lust auf Süßes gleich beim Frühstück zu stillen verhindert den Angriff auf die Schokoladentafel später am Tag, und genau da kippen viele Diäten.",
},
{
 "nome": "Omelett mit Champignons und Spinat",
 "hook": "Erdig und würzig, füllt den Teller mit Nährstoffen bei sehr wenigen Kalorien.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 260,
 "ings": ["2 Eier", "1 Handvoll Champignonscheiben", "1 Handvoll Spinat",
          "1 TL Olivenöl", "Salz, Pfeffer und gehackter Knoblauch nach Geschmack"],
 "passos": [
   "Schneide die Champignons in Scheiben und wasche den Spinat.",
   "Erhitze das Olivenöl in einer beschichteten Pfanne bei mittlerer bis hoher Hitze. Brate die Champignons in etwas Öl 3 bis 4 Minuten an, ohne zu viel zu rühren, bis sie goldbraun werden und ihr Wasser abgeben.",
   "Gib den Knoblauch und den Spinat dazu und rühre 1 Minute, nur bis die Blätter zusammenfallen. Würze mit Salz und Pfeffer.",
   "Verquirle die Eier in einer Schüssel und gieße sie über das Gemüse. Stelle die Hitze kleiner.",
   "Lass den Boden 1 bis 2 Minuten fest werden, klappe das Omelett zusammen und serviere es."],
 "porcoes8": ["1 Ei + 1 Eiweiß · Gemüse, so viel du magst",
              "2 Eier · Gemüse, so viel du magst",
              "2 Eier · Gemüse · ½ Scheibe Brot",
              "2 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 2 Scheiben Brot",
              "3 Eier · Gemüse · 2 Scheiben Brot · Käse",
              "4 Eier · Gemüse · 2 Scheiben Brot · Käse"],
 "dica": "Champignons und Spinat bringen Volumen, Geschmack und Nährstoffe bei fast keinen Kalorien — du füllst Teller und Magen. Die Eier ergänzen das mit sättigendem Eiweiß, so entsteht eine reichhaltige Mahlzeit, die trotzdem locker in die Diät passt.",
},
{
 "nome": "Joghurt mit selbst gemachtem Granola und Heidelbeeren",
 "hook": "Das Granola machst du ohne Zucker selbst und nutzt es die ganze Woche — knusprig und genau richtig.",
 "tempo": "5 Min. (+ fertiges Granola)", "rende": "1 Portion", "kcal_base": 330,
 "ings": ["1 Becher griechischer Naturjoghurt (ca. 170 g)", "3 EL selbst gemachtes Granola ohne Zucker",
          "1 Handvoll Heidelbeeren", "Zimt nach Geschmack",
          "(Granola: Haferflocken + gehackte Nüsse + Zimt, bei 160 °C 15 Min. gebacken)"],
 "passos": [
   "Für das selbst gemachte Granola: Vermische Haferflocken mit gehackten Nüssen und Zimt, verteile alles auf einem Backblech und backe es bei 160 °C 12 bis 15 Minuten, dabei nach der Hälfte umrühren. Lass es auskühlen, damit es knusprig wird, und bewahre es in einem Glas auf.",
   "Gib den Joghurt in eine Schale.",
   "Verteile das selbst gemachte Granola darüber.",
   "Streue die Heidelbeeren darauf und gib zum Schluss eine Prise Zimt dazu.",
   "Serviere es sofort, damit das Granola nicht weich wird."],
 "porcoes8": ["120 g Joghurt · 2 EL Granola · Heidelbeeren",
              "170 g Joghurt · 3 EL Granola · Heidelbeeren",
              "170 g Joghurt · 3 EL Granola · Heidelbeeren",
              "200 g Joghurt · 4 EL Granola · Heidelbeeren",
              "200 g Joghurt · 4 EL Granola · Heidelbeeren",
              "250 g Joghurt · 4 EL Granola · Heidelbeeren",
              "250 g Joghurt · 5 EL Granola · Heidelbeeren",
              "300 g Joghurt · 6 EL Granola · Heidelbeeren"],
 "dica": "Fertiges Granola aus der Packung steckt meist voller Zucker und Öl — selbst gemacht fällt das weg und du bestimmst, was hineinkommt. Mit eiweißreichem griechischem Joghurt und Heidelbeeren wird daraus ein knuspriges, sättigendes Frühstück ohne den versteckten Zucker der fertigen Varianten.",
},
{
 "nome": "Vollkorn-Wrap mit Rührei und Gemüse",
 "hook": "Einrollen und mitnehmen — das Frühstück für alle, die aus dem Haus rennen und trotzdem gut essen wollen.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 340,
 "ings": ["1 Vollkorn-Wrap", "2 Eier", "½ Tomate, gewürfelt", "1 Handvoll Spinat",
          "1 EL geriebener Käse", "Salz, Pfeffer und Ölspray"],
 "passos": [
   "Würfle die Tomate und stelle sie beiseite. Wasche den Spinat.",
   "Verquirle die Eier mit Salz und Pfeffer. Erhitze die Pfanne mit etwas Ölspray bei mittlerer Hitze.",
   "Gib den Spinat und die Tomate 1 Minute in die Pfanne, gieße dann die Eier darüber und rühre, bis ein cremiges Rührei entsteht.",
   "Erwärme den Wrap 20 Sekunden je Seite in einer trockenen Pfanne, nur damit er weich wird.",
   "Gib das Rührei in die Mitte des Wraps, streue den Käse darüber und klappe die Seiten nach innen.",
   "Rolle ihn fest zusammen wie einen Burrito und schneide ihn in der Mitte durch. Du kannst ihn unterwegs aus der Hand essen."],
 "porcoes8": ["1 Wrap · 1 Ei + 1 Eiweiß · Gemüse",
              "1 Wrap · 2 Eier · Gemüse · Käse",
              "1 Wrap · 2 Eier · Gemüse · Käse",
              "1 Wrap · 2 Eier · Gemüse · ¼ Avocado",
              "1 Wrap · 3 Eier · Gemüse · Käse",
              "1 großer Wrap · 3 Eier · Gemüse · Käse · ¼ Avocado",
              "1 großer Wrap · 3 Eier · Gemüse · Käse · ½ Avocado",
              "1 großer Wrap · 4 Eier · Gemüse · Käse · ½ Avocado"],
 "dica": "Das Frühstück in der Hand mitnehmen zu können ist das, was verhindert, dass du die Mahlzeit an einem vollen Tag ausfallen lässt. Gefüllt mit Ei und Gemüse liefert dieser Wrap Eiweiß und Ballaststoffe in praktischer Form — viel besser, als den Hunger beim Bäcker mit einem süßen Teilchen zu lösen.",
},
{
 "nome": "Apfel-Zimt-Pfannkuchen",
 "hook": "Riecht nach Apfelkuchen und passt trotzdem in die Diät — der süße Trost am Morgen, ohne den Tag zu ruinieren.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["40 g Haferflocken", "1 Ei", "½ Apfel, gerieben", "Zimt nach Geschmack",
          "1 Prise Backpulver", "Ölspray", "½ Apfel in dünnen Scheiben zum Belegen"],
 "passos": [
   "Reibe den halben Apfel auf der groben Reibe und schneide die andere Hälfte in Scheiben.",
   "Vermische die Haferflocken, das Ei, den geriebenen Apfel, den Zimt und das Backpulver in einer Schüssel, bis alles gut vermischt ist.",
   "Lass den Teig 3 Minuten ruhen, damit die Haferflocken quellen.",
   "Erhitze die beschichtete Pfanne bei mittlerer bis kleiner Hitze und sprühe etwas Öl hinein.",
   "Backe kleine Pfannkuchen, 2 bis 3 Minuten je Seite.",
   "Brate währenddessen die Apfelscheiben in derselben Pfanne mit einer Prise Zimt goldbraun. Serviere sie auf den Pfannkuchen."],
 "porcoes8": ["30 g Haferflocken · 1 Ei · ½ Apfel",
              "40 g Haferflocken · 1 Ei · ½ Apfel",
              "45 g Haferflocken · 1 Ei · ½ Apfel · Nüsse",
              "50 g Haferflocken · 1 Ei · 1 Apfel · Nüsse",
              "50 g Haferflocken · 2 Eier · 1 Apfel",
              "55 g Haferflocken · 2 Eier · 1 Apfel · Nüsse",
              "60 g Haferflocken · 2 Eier · 1 Apfel · Nüsse",
              "70 g Haferflocken · 2 Eier · 1 Apfel · 1 EL Erdnussmus"],
 "dica": "Der Apfel bringt Süße und Ballaststoffe, und der Zimt hebt den Geschmack ganz ohne eine Prise Zucker — Studien deuten sogar darauf hin, dass er beim Steuern des Appetits hilft. Das ist die Variante, die die Lust auf süßen Kuchen stillt, ohne die raffinierten Kohlenhydrate, die dick machen.",
},
{
 "nome": "Vollkornbrot mit Erdnussmus und Banane",
 "hook": "Der 5-Minuten-Klassiker, der Energie, gutes Fett und natürliche Süße vereint.",
 "tempo": "5 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["1 Scheibe Vollkornbrot", "1 EL Erdnussmus", "1 Banane in Scheiben",
          "Zimt nach Geschmack", "1 Prise Chiasamen (nach Wunsch)"],
 "passos": [
   "Toaste die Scheibe Brot, bis sie fest ist.",
   "Streiche das Erdnussmus auf den noch warmen Toast — so wird es etwas weicher und lässt sich leichter verteilen.",
   "Belege alles mit den Bananenscheiben.",
   "Streue Zimt und, wenn du magst, die Chiasamen darüber.",
   "Serviere es sofort. Zum Mitnehmen schneidest du es in der Mitte durch und klappst es wie ein Sandwich zusammen."],
 "porcoes8": ["½ Scheibe Brot · 1 TL Erdnussmus · ½ Banane",
              "1 Scheibe Brot · 1 EL Erdnussmus · 1 Banane",
              "1 Scheibe Brot · 1 EL Erdnussmus · 1 Banane · Chiasamen",
              "1 Scheibe Brot · 1,5 EL Erdnussmus · 1 Banane",
              "1 Scheibe Brot · 1,5 EL Erdnussmus · 1 Banane · 1 gekochtes Ei",
              "2 Scheiben Brot · 2 EL Erdnussmus · 1 Banane",
              "2 Scheiben Brot · 2 EL Erdnussmus · 1 Banane · 1 Ei",
              "2 Scheiben Brot · 2,5 EL Erdnussmus · 1 Banane · 1 Ei"],
 "dica": "Erdnussmus hat gutes Fett und Eiweiß, die lange satt machen — aber es ist kalorienreich, deshalb kommt es auf die Menge an: ein Esslöffel reicht schon. Auf Vollkornbrot mit Banane hast du gleichmäßige Energie für den ganzen Vormittag, ohne den Zuckerhoch und den Absturz danach.",
},
{
 "nome": "Pochierte Eier mit Spargel und Toast",
 "hook": "Elegant wie im Restaurant, einfach genug für einen ganz normalen Tag.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["2 Eier", "1 Handvoll Spargel", "1 Scheibe Vollkornbrot", "1 TL Essig (für das Wasser)",
          "Salz, Pfeffer und Olivenöl nach Geschmack"],
 "passos": [
   "Wasche den Spargel und schneide die harten Enden ab. Koche ihn 3 Minuten in Salzwasser, gieße ihn ab und stelle ihn beiseite.",
   "Erhitze Wasser in einem Topf, bis es fast kocht (mit kleinen Bläschen, ohne stark zu sprudeln), und gib den Essig dazu.",
   "Schlage jedes Ei einzeln in eine Tasse. Rühre mit einem Löffel einen Strudel ins Wasser und lasse das Ei ganz langsam in die Mitte gleiten — die Bewegung legt das Eiweiß um das Eigelb.",
   "Lass es 3 Minuten ziehen, für ein weiches Eigelb. Hole es mit einem Schaumlöffel heraus und lege es auf Küchenpapier ab.",
   "Toaste das Brot. Schichte den Spargel nach unten, die pochierten Eier darauf, dazu etwas Olivenöl, Salz und Pfeffer."],
 "porcoes8": ["1 Ei · Spargel · ½ Scheibe Brot",
              "2 Eier · Spargel · 1 Scheibe Brot",
              "2 Eier · Spargel · 1 Scheibe Brot · Käse",
              "2 Eier · Spargel · 1 Scheibe Brot · ¼ Avocado",
              "3 Eier · Spargel · 1 Scheibe Brot",
              "3 Eier · Spargel · 2 Scheiben Brot",
              "3 Eier · Spargel · 2 Scheiben Brot · ¼ Avocado",
              "4 Eier · Spargel · 2 Scheiben Brot · ¼ Avocado"],
 "dica": "Das pochierte Ei gart nur im Wasser, ganz ohne Öl, deshalb bleiben die Kalorien niedrig. Spargel ist reich an Ballaststoffen und Wasser und hat praktisch keine Kalorien — ein Frühstück, das edel wirkt und trotzdem für die Waage arbeitet.",
},
{
 "nome": "Haferflocken mit Birne und Walnüssen",
 "hook": "Cremig, leicht gesüßt von der Birne und mit dem Biss der Walnüsse.",
 "tempo": "8 Min.", "rende": "1 Portion", "kcal_base": 350,
 "ings": ["40 g Haferflocken", "200 ml Milch (oder Pflanzendrink)", "½ Birne, gewürfelt",
          "3 Walnüsse, gehackt", "Zimt nach Geschmack", "1 TL Honig (nach Wunsch)"],
 "passos": [
   "Gib die Haferflocken und die Milch in einen kleinen Topf und erhitze alles bei mittlerer bis kleiner Hitze unter Rühren.",
   "Gib nach 3 Minuten die Hälfte der Birnenwürfel dazu und koche noch 2 Minuten weiter, bis es dick wird.",
   "Nimm den Topf vom Herd und rühre den Zimt unter.",
   "Serviere alles in einer Schüssel und belege es mit der restlichen frischen Birne und den gehackten Walnüssen.",
   "Wenn nötig, süße mit einem Teelöffel Honig nach."],
 "porcoes8": ["30 g Haferflocken · 180 ml Milch · ½ Birne · 2 Walnüsse",
              "40 g Haferflocken · 200 ml Milch · ½ Birne · 3 Walnüsse",
              "45 g Haferflocken · 200 ml Milch · ½ Birne · 3 Walnüsse",
              "50 g Haferflocken · 220 ml Milch · 1 Birne · 3 Walnüsse",
              "50 g Haferflocken · 220 ml Milch · 1 Birne · 4 Walnüsse",
              "55 g Haferflocken · 250 ml Milch · 1 Birne · 4 Walnüsse",
              "60 g Haferflocken · 250 ml Milch · 1 Birne · 5 Walnüsse",
              "70 g Haferflocken · 300 ml Milch · 1 Birne · 5 Walnüsse"],
 "dica": "Die Birne ist reich an Ballaststoffen und süßt von selbst, Zucker brauchst du dafür nicht. Walnüsse haben gutes Fett, das sättigt, und geben Biss — sie sind aber kalorienreich, ein paar Stück erfüllen den Zweck also schon, ohne die Kalorien des Frühstücks zu sprengen.",
},
{
 "nome": "Griechischer Joghurt mit Pfirsich und Mandeln",
 "hook": "Cremig und leicht süß vom Pfirsich, mit dem Knusprigen der Mandeln — in 3 Minuten fertig.",
 "tempo": "3 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["1 Becher griechischer Naturjoghurt (ca. 170 g)", "1 Pfirsich in Scheiben (oder ½ Dose ohne Zuckerwasser)",
          "1 EL Mandelblättchen", "Zimt nach Geschmack", "1 TL Honig (nach Wunsch)"],
 "passos": [
   "Wenn der Pfirsich frisch ist, wasche ihn und schneide ihn in dünne Scheiben. Nimmst du ihn aus der Dose, wähle eine ohne gezuckertes Wasser und lass ihn gut abtropfen.",
   "Gib den Joghurt in eine Schale.",
   "Verteile die Pfirsichscheiben darüber.",
   "Streue die Mandelblättchen und den Zimt darauf.",
   "Wenn du es süßer magst, gib einen Teelöffel Honig dazu. Serviere es sofort."],
 "porcoes8": ["120 g Joghurt · Pfirsich · ½ EL Mandeln",
              "170 g Joghurt · Pfirsich · 1 EL Mandeln",
              "170 g Joghurt · Pfirsich · 1 EL Mandeln · Honig",
              "200 g Joghurt · Pfirsich · 1 EL Mandeln · 2 EL Haferflocken",
              "200 g Joghurt · Pfirsich · 1,5 EL Mandeln · 2 EL Haferflocken",
              "250 g Joghurt · Pfirsich · 1,5 EL Mandeln · 3 EL Haferflocken",
              "250 g Joghurt · Pfirsich · 2 EL Mandeln · 3 EL Haferflocken",
              "300 g Joghurt · Pfirsich · 2 EL Mandeln · 4 EL Haferflocken"],
 "dica": "Der Pfirsich ist süß und hat wenige Kalorien, das stillt die Lust auf Zucker auf leichte Art. Mit dem eiweißreichen griechischen Joghurt und einer Handvoll Mandeln kombinierst du Eiweiß und gutes Fett für eine Sättigung, die durch den ganzen Vormittag trägt.",
},
{
 "nome": "Vollkorn-Sandwich mit Pute und Käse",
 "hook": "Herzhaft, praktisch und eiweißreich — das schnelle Frühstück für alle, die es morgens nicht süß mögen.",
 "tempo": "6 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["2 Scheiben Vollkornbrot", "2 Scheiben Putenbrust", "1 Scheibe heller Käse",
          "Salatblätter", "Tomatenscheiben", "1 TL Senf oder leichter Frischkäse"],
 "passos": [
   "Wenn du es warm magst, erwärme die Brotscheiben 1 Minute je Seite in einer trockenen Pfanne.",
   "Streiche den Senf oder den leichten Frischkäse auf eine Brotscheibe.",
   "Schichte alles auf: Pute, Käse, Tomate und Salat.",
   "Lege die andere Brotscheibe darauf und drücke leicht an.",
   "Schneide es diagonal durch und serviere. Zum Mitnehmen wickelst du es in Backpapier."],
 "porcoes8": ["1 Scheibe Brot (offen) · 1 Scheibe Pute · Käse",
              "2 Scheiben Brot · 2 Scheiben Pute · Käse",
              "2 Scheiben Brot · 2 Scheiben Pute · Käse",
              "2 Scheiben Brot · 3 Scheiben Pute · Käse · ¼ Avocado",
              "2 Scheiben Brot · 3 Scheiben Pute · Käse · 1 gekochtes Ei",
              "2 Scheiben Brot · 4 Scheiben Pute · Käse · 1 Ei",
              "3 Scheiben Brot · 4 Scheiben Pute · Käse · 1 Ei",
              "3 Scheiben Brot · 5 Scheiben Pute · 2 Scheiben Käse · 1 Ei"],
 "dica": "Putenbrust ist eines der magersten Fleischstücke überhaupt, fast reines Eiweiß, ohne das Fett von Wurstwaren wie Salami oder Mortadella. Auf Vollkornbrot mit Salat ist das ein herzhaftes Frühstück, das mit wenigen Kalorien trägt und ganz ohne Zucker auskommt.",
},
{
 "nome": "Gemüse-Omelett",
 "hook": "Bunt und voller Geschmack, nutzt das, was im Kühlschrank ist, und füllt den Teller.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 260,
 "ings": ["2 Eier", "¼ Paprika, gewürfelt", "¼ Zwiebel, gewürfelt", "½ Tomate, gewürfelt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack"],
 "passos": [
   "Schneide die Paprika, die Zwiebel und die Tomate in kleine Würfel.",
   "Erhitze das Olivenöl in einer beschichteten Pfanne bei mittlerer Hitze. Brate die Zwiebel und die Paprika in etwas Öl unter Rühren 2 bis 3 Minuten an, bis sie weich werden.",
   "Gib die Tomate dazu und brate noch 1 Minute weiter. Würze mit Salz und Pfeffer.",
   "Verquirle die Eier und gieße sie über das Gemüse. Kippe die Pfanne leicht, damit sich alles verteilt.",
   "Wenn der Boden fest wird (nach 2 Minuten), klappe das Omelett zusammen, lass es noch 1 Minute garen und serviere es mit den Kräutern."],
 "porcoes8": ["1 Ei + 1 Eiweiß · Gemüse, so viel du magst",
              "2 Eier · Gemüse, so viel du magst",
              "2 Eier · Gemüse · ½ Scheibe Brot",
              "2 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 2 Scheiben Brot",
              "3 Eier · Gemüse · 2 Scheiben Brot · Käse",
              "4 Eier · Gemüse · 2 Scheiben Brot · Käse"],
 "dica": "Das Omelett mit Gemüse zu füllen erhöht Volumen und Ballaststoffe bei sehr wenigen Kalorien, du isst also einen vollen Teller ohne schlechtes Gewissen. Es ist außerdem ein cleverer Weg, schon morgens mehr Gemüse zu essen, was dir hilft, dein Ballaststoffziel für den Tag zu erreichen.",
},
{
 "nome": "Grüner Smoothie mit Spinat, Banane und Apfel",
 "hook": "Grün, eiskalt und leicht süß — du schmeckst den Spinat gar nicht, aber dein Körper dankt es dir.",
 "tempo": "5 Min.", "rende": "1 Portion", "kcal_base": 250,
 "ings": ["1 große Handvoll Spinat", "½ Banane", "½ Apfel", "200 ml kaltes Wasser (oder Pflanzendrink)",
          "1 EL Haferflocken", "Saft von ½ Zitrone", "Eiswürfel nach Geschmack"],
 "passos": [
   "Wasche den Spinat gründlich.",
   "Gib zuerst die Flüssigkeit in den Mixer, danach den Spinat — die Blätter zuerst mit der Flüssigkeit zu mixen verhindert Stücke.",
   "Mixe 30 Sekunden, bis sich der Spinat auflöst.",
   "Gib die Banane, den Apfel (ohne Kerngehäuse), die Haferflocken, den Zitronensaft und die Eiswürfel dazu.",
   "Mixe auf höchster Stufe, bis alles glatt und gut vermischt ist. Serviere ihn sofort, schön kalt."],
 "porcoes8": ["Spinat · ½ Banane · ½ Apfel · 1 EL Haferflocken",
              "Spinat · ½ Banane · ½ Apfel · 1 EL Haferflocken",
              "Spinat · 1 Banane · ½ Apfel · 2 EL Haferflocken",
              "Spinat · 1 Banane · ½ Apfel · 2 EL Haferflocken · Joghurt",
              "Spinat · 1 Banane · 1 Apfel · 2 EL Haferflocken · Joghurt",
              "Spinat · 1 Banane · 1 Apfel · 3 EL Haferflocken · Joghurt",
              "Spinat · 1 Banane · 1 Apfel · 3 EL Haferflocken · Joghurt · Nüsse",
              "Spinat · 1 Banane · 1 Apfel · 4 EL Haferflocken · Joghurt · Nüsse"],
 "dica": "Spinat mit Obst zu mixen ist ein schmerzloser Weg, morgens Blattgemüse zu essen — die Süße von Banane und Apfel überdeckt das Grüne. Er hat wenige Kalorien und viel Wasser und Ballaststoffe, ideal, um gut versorgt und satt in den Tag zu starten.",
},
{
 "nome": "Rührei mit Champignons und Käse",
 "hook": "Cremig und wohltuend: das herzhafte Frühstück, das mit dem Geschmack von echtem Essen trägt.",
 "tempo": "9 Min.", "rende": "1 Portion", "kcal_base": 300,
 "ings": ["2 Eier", "1 Handvoll Champignonscheiben", "1 EL geriebener Käse",
          "1 TL Olivenöl", "Salz, Pfeffer und Schnittlauch nach Geschmack"],
 "passos": [
   "Schneide die Champignons in Scheiben. Erhitze das Olivenöl in einer Pfanne bei mittlerer bis hoher Hitze und brate die Champignons 3 bis 4 Minuten goldbraun.",
   "Verquirle die Eier mit Salz und Pfeffer.",
   "Stelle die Hitze kleiner, gieße die Eier über die Champignons und lass sie 30 Sekunden stehen.",
   "Schiebe sie mit dem Pfannenwender vorsichtig vom Rand zur Mitte, bis ein cremiges Rührei entsteht.",
   "Rühre kurz vor dem Ende den geriebenen Käse unter. Nimm die Pfanne vom Herd, solange die Eier noch feucht sind, und streue den Schnittlauch darüber."],
 "porcoes8": ["1 Ei + 1 Eiweiß · Champignons · Käse",
              "2 Eier · Champignons · Käse",
              "2 Eier · Champignons · Käse · ½ Scheibe Brot",
              "2 Eier · Champignons · Käse · 1 Scheibe Brot",
              "3 Eier · Champignons · Käse · 1 Scheibe Brot",
              "3 Eier · Champignons · Käse · 2 Scheiben Brot",
              "3 Eier · Champignons · 2 EL Käse · 2 Scheiben Brot",
              "4 Eier · Champignons · 2 EL Käse · 2 Scheiben Brot"],
 "dica": "Champignons bringen einen herzhaften Geschmack, der die Mahlzeit reichhaltiger wirken lässt, ohne zusätzliches Fett. Mit Eiern und etwas Käse ist das ein cremiges, eiweißreiches Frühstück — deutlich sättigender als ein Butterbrot auf die Schnelle.",
},
{
 "nome": "Haferflocken-Pfannkuchen mit Heidelbeeren",
 "hook": "Die Heidelbeeren platzen warm im Teig auf — natürlich süß, ohne zugesetzten Zucker.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 320,
 "ings": ["40 g Haferflocken", "1 Ei", "½ Banane, zerdrückt", "1 Handvoll Heidelbeeren",
          "1 Prise Backpulver", "Zimt nach Geschmack", "Ölspray"],
 "passos": [
   "Vermische die Haferflocken, das Ei, die zerdrückte Banane, das Backpulver und den Zimt in einer Schüssel.",
   "Lass den Teig 3 Minuten ruhen, damit er fester wird.",
   "Hebe die Hälfte der Heidelbeeren vorsichtig unter den Teig, damit sie nicht zerdrückt werden.",
   "Erhitze die beschichtete Pfanne bei mittlerer bis kleiner Hitze, sprühe etwas Öl hinein und backe kleine Pfannkuchen.",
   "Lass sie 2 bis 3 Minuten je Seite und wende sie, wenn kleine Bläschen entstehen.",
   "Serviere sie mit den restlichen frischen Heidelbeeren darüber."],
 "porcoes8": ["30 g Haferflocken · 1 Ei · ½ Banane · Heidelbeeren",
              "40 g Haferflocken · 1 Ei · ½ Banane · Heidelbeeren",
              "45 g Haferflocken · 1 Ei · ½ Banane · Heidelbeeren",
              "50 g Haferflocken · 1 Ei · 1 Banane · Heidelbeeren",
              "50 g Haferflocken · 2 Eier · 1 Banane · Heidelbeeren",
              "55 g Haferflocken · 2 Eier · 1 Banane · Heidelbeeren · Nüsse",
              "60 g Haferflocken · 2 Eier · 1 Banane · Heidelbeeren · Nüsse",
              "70 g Haferflocken · 2 Eier · 1 Banane · Heidelbeeren · 1 EL Erdnussmus"],
 "dica": "Heidelbeeren sind reich an Antioxidantien und haben wenige Kalorien, sie süßen den Pfannkuchen ganz natürlich. Weil die Basis aus Haferflocken, Ei und Banane besteht — ohne weißes Mehl und ohne Zucker —, hast du ein Frühstück, das die Lust auf Süßes stillt, ohne die Zutaten, die dick machen.",
},
{
 "nome": "Joghurt mit Chiasamen, Honig und Kiwi",
 "hook": "Erfrischend und voller Ballaststoffe: das Frühstück, das die Verdauung in Gang bringt und gleichzeitig satt macht.",
 "tempo": "4 Min.", "rende": "1 Portion", "kcal_base": 290,
 "ings": ["1 Becher griechischer Naturjoghurt (ca. 170 g)", "1 EL Chiasamen",
          "1 Kiwi in Scheiben", "1 TL Honig", "Minze (nach Wunsch)"],
 "passos": [
   "Vermische den Joghurt mit den Chiasamen in einer Schale und lass alles 5 Minuten stehen — die Chiasamen quellen leicht auf und machen den Joghurt dicker.",
   "Schäle die Kiwi und schneide sie in Scheiben.",
   "Verteile die Kiwischeiben auf dem Joghurt.",
   "Gib zum Schluss den Honig darüber und, wenn du magst, ein paar Minzblättchen.",
   "Serviere es kalt."],
 "porcoes8": ["120 g Joghurt · 1 EL Chiasamen · Kiwi",
              "170 g Joghurt · 1 EL Chiasamen · Kiwi · Honig",
              "170 g Joghurt · 1 EL Chiasamen · Kiwi · Honig",
              "200 g Joghurt · 1 EL Chiasamen · Kiwi · 2 EL Haferflocken",
              "200 g Joghurt · 1,5 EL Chiasamen · Kiwi · 2 EL Haferflocken",
              "250 g Joghurt · 1,5 EL Chiasamen · Kiwi · 3 EL Haferflocken",
              "250 g Joghurt · 2 EL Chiasamen · Kiwi · 3 EL Haferflocken · Nüsse",
              "300 g Joghurt · 2 EL Chiasamen · Kiwi · 4 EL Haferflocken · Nüsse"],
 "dica": "Chiasamen und Kiwi zusammen sind reich an Ballaststoffen, die die Verdauung unterstützen und länger satt halten. Der griechische Joghurt bringt Eiweiß dazu, und ein Teelöffel Honig süßt, ohne zu übertreiben — ein leichtes Frühstück, das auch noch für die Verdauung sorgt.",
},
{
 "nome": "Vollkornbrot mit Hüttenkäse und Tomate",
 "hook": "Frisch und herzhaft, mit Eiweiß im Käse und fast keinen Kalorien in der Tomate.",
 "tempo": "6 Min.", "rende": "1 Portion", "kcal_base": 250,
 "ings": ["1 Scheibe Vollkornbrot", "3 EL Hüttenkäse", "1 Tomate in Scheiben",
          "Oregano, Salz, Pfeffer und Olivenöl nach Geschmack", "Basilikumblätter (nach Wunsch)"],
 "passos": [
   "Toaste die Scheibe Brot, bis sie fest und knusprig ist.",
   "Streiche den Hüttenkäse auf den Toast und bedecke die ganze Fläche.",
   "Lege die Tomatenscheiben darauf.",
   "Würze mit einer Prise Salz, Pfeffer, Oregano und etwas Olivenöl.",
   "Gib zum Schluss ein paar Basilikumblätter darüber, wenn du welche hast. Serviere es sofort."],
 "porcoes8": ["½ Scheibe Brot · 2 EL Hüttenkäse · Tomate",
              "1 Scheibe Brot · 3 EL Hüttenkäse · Tomate",
              "1 Scheibe Brot · 3 EL Hüttenkäse · Tomate · 1 gekochtes Ei",
              "1 Scheibe Brot · 4 EL Hüttenkäse · Tomate · 1 Ei",
              "1 Scheibe Brot · 4 EL Hüttenkäse · Tomate · 2 Eier",
              "2 Scheiben Brot · 4 EL Hüttenkäse · Tomate · 1 Ei",
              "2 Scheiben Brot · 5 EL Hüttenkäse · Tomate · 2 Eier",
              "2 Scheiben Brot · 6 EL Hüttenkäse · Tomate · 2 Eier"],
 "dica": "Hüttenkäse ist mager und eiweißreich, er stillt den Hunger mit wenigen Kalorien. Auf Vollkornbrot mit Tomate wird daraus eine gesunde Bruschetta — herzhaft, frisch und viel leichter als ein Brot mit fettem Frischkäse.",
},
{
 "nome": "Haferschüssel mit gebackenem Apfel und Zimt",
 "hook": "Der Duft von gebackenem Apfel mit Zimt macht aus normalen Haferflocken einen Trost für kalte Tage.",
 "tempo": "15 Min.", "rende": "1 Portion", "kcal_base": 340,
 "ings": ["40 g Haferflocken", "200 ml Milch (oder Pflanzendrink)", "1 Apfel in Würfeln",
          "Zimtstange oder gemahlener Zimt", "1 TL Honig (nach Wunsch)", "1 EL Walnüsse (nach Wunsch)"],
 "passos": [
   "Schneide den Apfel mit Schale in Würfel. Brate die Würfel in einer beschichteten Pfanne bei mittlerer Hitze mit reichlich Zimt 5 bis 7 Minuten unter Rühren an, bis sie weich und im eigenen Fruchtzucker goldbraun werden.",
   "Koche währenddessen die Haferflocken mit der Milch in einem Topf 4 bis 5 Minuten unter Rühren, bis alles dick wird.",
   "Fülle die Haferflocken in eine Schüssel.",
   "Gib den warmen gebackenen Apfel darüber.",
   "Wenn du magst, kommen zum Schluss der Honig und die gehackten Walnüsse dazu. Serviere es warm."],
 "porcoes8": ["30 g Haferflocken · 180 ml Milch · ½ Apfel",
              "40 g Haferflocken · 200 ml Milch · 1 Apfel",
              "45 g Haferflocken · 200 ml Milch · 1 Apfel · Honig",
              "50 g Haferflocken · 220 ml Milch · 1 Apfel · Walnüsse",
              "50 g Haferflocken · 220 ml Milch · 1 Apfel · Walnüsse",
              "55 g Haferflocken · 250 ml Milch · 1 Apfel · Walnüsse",
              "60 g Haferflocken · 250 ml Milch · 1 Apfel · Walnüsse",
              "70 g Haferflocken · 300 ml Milch · 1 Apfel · Walnüsse · Honig"],
 "dica": "Den Apfel zu backen holt seine natürliche Süße heraus und hebt den Zimt hervor, Zucker brauchst du also nicht. Das ist ein Frühstück, das wie ein warmer Nachtisch tröstet, aber mit den Ballaststoffen aus Frucht und Hafer, die den Hunger stundenlang fernhalten.",
},
]
