# -*- coding: utf-8 -*-
"""BONUS 1 — DIETA VEGETARIANA. ESPANHOL (America Latina).

Traducao literal de `receitas_bonus_veg_en.py`. Convencoes em
GLOSSARIO-TRADUCAO.md: tratamento por "tu", vocabulario LatAm com foco
Mexico (garbanzos, lentejas, jitomate, calabacin, elote, curcuma).
⛔ METRICO: g, ml, °C — como pt/de/fr. Os numeros vem do de/fr.
⛔ Duas listas, como no original: ALMOCOS (4) e JANTARES (4).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
"""

ALMOCOS = [
{
 "nome": "Bowl de garbanzos con arroz y verduras rostizadas",
 "tag": "Almuerzo vegetariano", "num_label": "Bono · Vegetariano",
 "hook": "Un bowl colorido y generoso, sin nada de carne — los garbanzos te sostienen toda la tarde como un plato de proteína.",
 "tempo": "35 min", "rende": "1 porción", "kcal_base": 500,
 "ings": ["80 g de garbanzos cocidos (o de lata, escurridos)",
          "4 cucharadas de arroz integral cocido", "1 calabacín en trozos",
          "½ pimiento en trozos", "½ cebolla morada en trozos",
          "jitomates cherry", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón",
          "sal, pimienta, cúrcuma y orégano al gusto", "hojas verdes"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta el calabacín, el pimiento y la cebolla en trozos parecidos, de un bocado.",
   "En una charola, reparte las verduras y los jitomates cherry, sazona con sal, pimienta, orégano y la mitad del aceite de oliva, y mezcla con las manos.",
   "Hornea de 20 a 25 minutos, hasta que las verduras queden suaves y doradas en las orillas. Voltéalas a la mitad del tiempo.",
   "En un sartén, calienta el resto del aceite de oliva y saltea los garbanzos con la cúrcuma, sal y pimienta 3 minutos, revolviendo, solo para que tomen sabor y se doren ligeramente.",
   "Arma el bowl: una cama de hojas verdes, el arroz de un lado, los garbanzos y las verduras rostizadas encima. Rocía con el jugo de limón y sirve."],
 "porcoes8": ["55 g de garbanzos · 3 cucharadas de arroz · verduras",
              "80 g de garbanzos · 4 cucharadas de arroz · verduras",
              "80 g de garbanzos · 5 cucharadas de arroz · verduras",
              "110 g de garbanzos · 5 cucharadas de arroz · un poco de aceite de oliva",
              "110 g de garbanzos · 5 cucharadas de arroz · verduras",
              "125 g de garbanzos · 6 cucharadas de arroz · 1 cucharada de nueces",
              "165 g de garbanzos · 7 cucharadas de arroz · aguacate",
              "165 g de garbanzos · 8 cucharadas de arroz · aguacate"],
 "dica": "Los garbanzos combinan proteína y fibra que te llenan como un plato de carne, y junto con el arroz integral forman una proteína completa (la pareja leguminosa + cereal que usan los vegetarianos). Rostizar las verduras concentra el sabor sin grasa, manteniendo el plato ligero y sabroso.",
},
{
 "nome": "Pastel de lentejas con puré de papa",
 "tag": "Almuerzo vegetariano", "num_label": "Bono · Vegetariano",
 "hook": "Todo el consuelo de un pastel gratinado, con un relleno sazonado de lentejas en lugar de carne — cremoso y lleno de proteína vegetal.",
 "tempo": "45 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["200 g de lentejas cocidas", "2 papas medianas",
          "1 cebolla, picada", "2 dientes de ajo, picados",
          "1 jitomate, picado", "1 zanahoria, rallada",
          "1 cucharadita de aceite de oliva",
          "2 cucharadas de queso rallado",
          "sal, pimienta, cúrcuma y hierbas frescas al gusto"],
 "passos": [
   "Pela y cuece las papas en agua hirviendo 15 minutos, hasta que queden muy suaves. Escúrrelas y aplástalas con un tenedor, con una pizca de sal, hasta que quede un puré terso.",
   "En un sartén, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos. Agrega la zanahoria rallada y el jitomate y cocina 3 minutos.",
   "Agrega las lentejas cocidas, la cúrcuma, sal y pimienta y cocina otros 5 minutos, aplastando un poco las lentejas con la cuchara, hasta que quede un relleno con cuerpo.",
   "En un refractario, reparte la mitad del puré en el fondo, el relleno de lentejas en medio y el resto del puré encima. Espolvorea el queso rallado.",
   "Hornea a fuego medio-alto (200 °C) por 15 minutos, hasta que la superficie quede dorada. Espolvorea hierbas frescas y sirve."],
 "porcoes8": ["½ porción · ensalada",
              "1 porción · ensalada",
              "1 porción · ensalada",
              "1 porción · 1 cucharada más de queso · ensalada",
              "1 porción · lentejas extra · ensalada",
              "1 porción grande · ensalada",
              "1 porción grande · lentejas extra · ensalada",
              "porción doble · ensalada"],
 "dica": "Las lentejas son ricas en hierro, fibra y proteína vegetal, un trío que llena muchísimo — en el pastel, reemplazan la carne de sobra. Con el puré de papa en la medida correcta y un poco de queso gratinado, es un plato reconfortante que engaña el antojo de comida pesada.",
},
{
 "nome": "Frittata de verduras",
 "tag": "Almuerzo vegetariano", "num_label": "Bono · Vegetariano",
 "hook": "Un omelette alto y esponjoso, horneado con verduras coloridas y queso — proteína del huevo en un platillo que cortas en rebanadas y le gusta a todos.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 420,
 "ings": ["5 huevos", "1 calabacín en cubos pequeños",
          "½ pimiento, picado", "1 jitomate, picado",
          "un puñado de espinaca", "3 cucharadas de queso blanco en cubos",
          "1 cucharadita de aceite de oliva",
          "cebollín, sal y pimienta al gusto",
          "hojas verdes para la ensalada"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). En un sartén que pueda ir al horno, calienta el aceite de oliva y saltea el calabacín y el pimiento 4 minutos, revolviendo, hasta que se suavicen.",
   "Agrega la espinaca y revuelve 1 minuto, solo hasta que se marchite (las hojas se ponen suaves). Reparte las verduras por el sartén.",
   "En un tazón, bate los huevos con sal y pimienta. Agrega el jitomate, el queso y el cebollín y mezcla.",
   "Vierte los huevos sobre las verduras en el sartén y déjalo 2 minutos en el fuego, solo para cuajar la orilla.",
   "Mete el sartén al horno 15 minutos, hasta que la frittata se infle, cuaje en el centro y se dore arriba. Córtala en rebanadas y sirve con una ensalada verde."],
 "porcoes8": ["1 rebanada · ensalada",
              "1 rebanada grande · ensalada",
              "1 rebanada grande · ensalada · 2 cucharadas de arroz",
              "2 rebanadas · ensalada · 2 cucharadas de arroz",
              "2 rebanadas · ensalada · 3 cucharadas de arroz",
              "2 rebanadas grandes · ensalada · 3 cucharadas de arroz",
              "2 rebanadas grandes · ensalada · 4 cucharadas de arroz",
              "3 rebanadas · ensalada · 4 cucharadas de arroz"],
 "dica": "Los huevos son una proteína completa y muy saciante, ideal para un almuerzo vegetariano sin leguminosas. Horneada con verduras y un poco de queso, la frittata rinde mucho, se conserva bien en el refrigerador y mata el hambre de forma ligera y nutritiva.",
},
{
 "nome": "Chili vegetariano de frijoles y garbanzos",
 "tag": "Almuerzo vegetariano", "num_label": "Bono · Vegetariano",
 "hook": "Un guisado picosito y sustancioso sin nada de carne — la prueba de que la comida vegetariana también llena el plato y la panza.",
 "tempo": "30 min", "rende": "3 porciones", "kcal_base": 460,
 "ings": ["175 g de frijoles rojos cocidos", "165 g de garbanzos cocidos",
          "80 g de elote", "1 cebolla, picada",
          "2 dientes de ajo, picados", "1 pimiento, picado",
          "2 jitomates, picados (o salsa de tomate)",
          "1 cucharadita de aceite de oliva", "1 cucharadita de comino",
          "sal, pimienta y paprika al gusto", "arroz para servir"],
 "passos": [
   "Calienta el aceite de oliva en una olla a fuego medio. Fríe la cebolla, el ajo y el pimiento 3 minutos, revolviendo, hasta que se suavicen.",
   "Agrega el comino, la paprika, sal y pimienta y revuelve 30 segundos, para que las especias suelten su aroma.",
   "Agrega los jitomates picados y cocina 5 minutos, hasta que se deshagan en una salsa.",
   "Agrega los frijoles rojos, los garbanzos y el elote. Si se seca, agrega media taza de agua.",
   "Baja el fuego y cocina 15 minutos, revolviendo de vez en cuando, hasta que espese como un guisado cremoso. Sirve con un poco de arroz."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz",
              "1 porción · 4 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz · aguacate",
              "1 porción · 5 cucharadas de arroz",
              "1 porción grande · 6 cucharadas de arroz",
              "porción grande · 7 cucharadas de arroz · aguacate",
              "porción doble · 8 cucharadas de arroz"],
 "dica": "Los frijoles y los garbanzos juntos forman una proteína vegetal muy completa, con una montaña de fibra que te llena por horas. Servido con arroz, cierra la proteína completa. Es un plato barato que dura varios días y demuestra que puedes comer bien sin carne.",
},
]

JANTARES = [
{
 "nome": "Sopa sustanciosa de lentejas con verduras",
 "tag": "Cena vegetariana", "num_label": "Bono · Vegetariano",
 "hook": "Una sopa que es comida de verdad: las lentejas hacen el caldo espeso y lleno de proteína, calentándote y llenándote en una noche fría.",
 "tempo": "40 min", "rende": "3 porciones", "kcal_base": 380,
 "ings": ["190 g de lentejas crudas", "1 papa en cubos",
          "1 zanahoria en cubos", "1 tallo de apio, picado (opcional)",
          "1 jitomate, picado", "1 cebolla, picada",
          "2 dientes de ajo, picados", "1 cucharadita de aceite de oliva",
          "sal, pimienta, cúrcuma y hierbas frescas al gusto",
          "1,2 litros de agua"],
 "passos": [
   "Lava las lentejas. En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos, revolviendo.",
   "Agrega el jitomate, la zanahoria, la papa y el apio y revuelve 2 minutos.",
   "Agrega las lentejas, la cúrcuma, sal, pimienta y el agua. Deja que hierva.",
   "Baja el fuego y cocina de 25 a 30 minutos, revolviendo de vez en cuando, hasta que las lentejas y las verduras queden muy suaves y el caldo tenga cuerpo. Si se seca demasiado, agrega un poco de agua caliente.",
   "Prueba la sal, espolvorea hierbas frescas y sirve bien caliente."],
 "porcoes8": ["1 cucharón · sin pan",
              "2 cucharones · sin pan",
              "2 cucharones · 1 rebanada de pan",
              "2 cucharones · 1 rebanada de pan",
              "2 cucharones · 1 rebanada de pan",
              "3 cucharones · 1 rebanada de pan",
              "3 cucharones · 2 rebanadas de pan",
              "3 cucharones grandes · 2 rebanadas de pan"],
 "dica": "Las lentejas son una de las leguminosas más ricas en proteína y hierro, y en sopa hacen el caldo lo bastante sustancioso para ser una cena completa sin carne. Todo ese líquido y las verduras llenan el estómago con pocas calorías — ligera, caliente y reconfortante.",
},
{
 "nome": "Tofu a la plancha con verduras y arroz",
 "tag": "Cena vegetariana", "num_label": "Bono · Vegetariano",
 "hook": "El tofu dorado toma el sazón y queda delicioso — una opción sin carne que de verdad llena y es ligera para la noche.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 420,
 "ings": ["150 g de tofu firme en rebanadas",
          "4 cucharadas de arroz integral cocido",
          "100 g de brócoli y zanahoria",
          "1 cucharada de salsa de soya clara",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jengibre rallado (opcional)", "sal y pimienta al gusto"],
 "passos": [
   "Seca bien las rebanadas de tofu con papel absorbente, presionando ligeramente — mientras más seco, mejor se dora.",
   "Sazona el tofu con la salsa de soya, el ajo y el jengibre. Déjalo tomar sabor 5 minutos.",
   "Calienta un sartén antiadherente con la mitad del aceite de oliva a fuego medio-alto. Asa las rebanadas de tofu de 3 a 4 minutos de cada lado, sin moverlas, hasta que se forme una costra dorada. Sácalas y resérvalas.",
   "Corta el brócoli en ramitos y la zanahoria en rodajas. En el mismo sartén, con el resto del aceite de oliva, saltea las verduras 4 minutos, hasta que queden tiernas pero todavía firmes.",
   "Arma el plato con el arroz integral, las verduras y el tofu asado encima. Rocía con un poco más de salsa de soya si quieres."],
 "porcoes8": ["120 g de tofu · 3 cucharadas de arroz · verduras",
              "150 g de tofu · 4 cucharadas de arroz · verduras",
              "150 g de tofu · 5 cucharadas de arroz · verduras",
              "170 g de tofu · 5 cucharadas de arroz · un poco de aceite de oliva",
              "170 g de tofu · 5 cucharadas de arroz · verduras",
              "200 g de tofu · 6 cucharadas de arroz · verduras",
              "220 g de tofu · 7 cucharadas de arroz · 1 cucharada de nueces",
              "250 g de tofu · 8 cucharadas de arroz · nueces"],
 "dica": "El tofu se hace de soya y aporta proteína vegetal con poca grasa, siendo una de las mejores opciones para variar de la carne. Bien seco y asado, gana textura y toma el sazón. Con verduras y arroz integral, se vuelve una cena completa, ligera y llena de fibra.",
},
{
 "nome": "Berenjena rellena de garbanzos y queso",
 "tag": "Cena vegetariana", "num_label": "Bono · Vegetariano",
 "hook": "La propia berenjena se convierte en el recipiente, rellena de garbanzos sazonados y gratinada con queso — bonita, generosa y sin carne.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 400,
 "ings": ["1 berenjena grande", "165 g de garbanzos cocidos",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "1 jitomate, picado", "1 cucharadita de aceite de oliva",
          "2 cucharadas de queso rallado bajo en grasa",
          "sal, pimienta, comino y perejil al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta la berenjena a la mitad a lo largo. Con una cuchara, saca parte del centro, formando dos barcas. Pica lo que sacaste.",
   "Pon las barcas en una charola, rocía con un poco de aceite de oliva y hornea 10 minutos, solo para suavizarlas.",
   "En un sartén, calienta el resto del aceite de oliva y fríe la cebolla y el ajo 2 minutos. Agrega el jitomate, el centro picado de la berenjena, los garbanzos, el comino, sal y pimienta y cocina 6 minutos, aplastando un poco los garbanzos, hasta que quede un relleno suave.",
   "Rellena las barcas con la mezcla de garbanzos y espolvorea el queso rallado encima.",
   "Regrésalas al horno 15 minutos, hasta que gratine (el queso se derrite y se dora). Espolvorea perejil y sirve."],
 "porcoes8": ["½ berenjena · ensalada",
              "1 berenjena rellena · ensalada",
              "1 berenjena · 2 cucharadas de arroz",
              "1 berenjena · garbanzos extra · ensalada",
              "1 berenjena · garbanzos extra · 2 cucharadas de arroz",
              "1 berenjena grande · 3 cucharadas de arroz",
              "1 berenjena · doble de garbanzos · 4 cucharadas de arroz",
              "berenjena + porción extra · 4 cucharadas de arroz"],
 "dica": "La berenjena tiene mucha agua y fibra, así que llena el plato con muy pocas calorías. Los garbanzos aportan la proteína vegetal que reemplaza la carne, y un poco de queso gratinado mata el antojo de un plato gratinado. Una cena vegetariana bonita, generosa y ligera.",
},
{
 "nome": "Curry de garbanzos con arroz",
 "tag": "Cena vegetariana", "num_label": "Bono · Vegetariano",
 "hook": "Una salsa dorada y aromática envolviendo los garbanzos — cremosa con leche de coco light, es una cena vegetariana llena de sabor.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 440,
 "ings": ["330 g de garbanzos cocidos", "1 cebolla, picada",
          "2 dientes de ajo, picados", "1 jitomate, picado",
          "1 cucharadita de curry en polvo",
          "120 ml de leche de coco light",
          "un puñado de espinaca (opcional)",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y cilantro al gusto", "arroz para servir"],
 "passos": [
   "Calienta el aceite de oliva en una olla a fuego medio y fríe la cebolla y el ajo 2 minutos, revolviendo.",
   "Agrega el curry y revuelve 30 segundos, para que la especia suelte su aroma. Agrega el jitomate y cocina 3 minutos, hasta que se deshaga.",
   "Agrega los garbanzos y la leche de coco light y mezcla. Sazona con sal y pimienta.",
   "Cocina a fuego bajo 10 minutos, revolviendo de vez en cuando, hasta que la salsa espese. Si quieres, agrega la espinaca en los últimos 2 minutos, solo hasta que se marchite.",
   "Espolvorea cilantro y sirve sobre una porción de arroz."],
 "porcoes8": ["110 g de garbanzos · 3 cucharadas de arroz",
              "165 g de garbanzos · 4 cucharadas de arroz",
              "165 g de garbanzos · 5 cucharadas de arroz",
              "165 g de garbanzos · 5 cucharadas de arroz · espinaca",
              "165 g de garbanzos · 5 cucharadas de arroz",
              "250 g de garbanzos · 6 cucharadas de arroz",
              "250 g de garbanzos · 7 cucharadas de arroz",
              "330 g de garbanzos · 8 cucharadas de arroz"],
 "dica": "Los garbanzos son ricos en proteína y fibra, y en curry quedan cremosos y llenos de sabor. La leche de coco light le da cuerpo a la salsa con mucha menos grasa que la crema. Con arroz, forman una proteína completa — una cena vegetariana reconfortante y nutritiva.",
},
]
