# -*- coding: utf-8 -*-
"""30 receitas de CAFÉ DA MANHÃ (001-030). Português.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+  ·  Homem 70-85/86-100/101-120/120+
Metas (kcal): 300/370/420/470  ·  450/510/560/620
Cada receita tem 'prompt' = foto quadrada, ultrarrealista, SEM texto.
"""

RECEITAS = [
{
 "nome": "Panqueca de Banana e Aveia",
 "hook": "Três ingredientes que você já tem em casa, prontos em 10 minutos — e que seguram a fome até o almoço.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 325,
 "ings": ["1 banana madura", "40 g de aveia em flocos (≈ 4 colheres de sopa)", "1 ovo",
          "1 pitada de canela", "1 pitada de fermento em pó (opcional, deixa mais fofa)",
          "1 fio de óleo ou spray para a frigideira"],
 "passos": [
   "Descasque a banana e coloque num prato fundo. Amasse bem com um garfo até virar um purê liso, sem pedaços grandes.",
   "Adicione o ovo e misture até ficar tudo bem misturado.",
   "Junte a aveia, a canela e o fermento. Misture e deixe descansar 3 minutos — a aveia absorve a umidade e a massa firma, o que facilita virar depois.",
   "Aqueça uma frigideira que não gruda em fogo médio-baixo e passe um fio de óleo (ou spray).",
   "Com uma colher, coloque pequenas porções da massa, do tamanho de meia mão. Panquecas pequenas viram muito mais fácil que as grandes.",
   "Deixe 2 a 3 minutos, até aparecerem bolhinhas na superfície e as bordas firmarem. Vire com cuidado e doure o outro lado por mais 1 a 2 minutos.",
   "Sirva quente. Se quiser, finalize com rodelas de banana, um punhado de frutas vermelhas ou uma colher de chá de mel."],
 "porcoes8": ["¾ banana · 30 g aveia · 1 ovo",
              "1 banana · 40 g aveia · 1 ovo · 1 punhado de frutas vermelhas",
              "1 banana · 45 g aveia · 1 ovo · 1 col. chá de pasta de amendoim",
              "1 banana · 50 g aveia · 1 ovo · 1 col. sopa de pasta de amendoim",
              "1 banana · 50 g aveia · 2 ovos · 1 col. chá de pasta de amendoim",
              "1 banana grande · 55 g aveia · 2 ovos · 1 col. sopa de pasta de amendoim",
              "1 banana grande · 60 g aveia · 2 ovos · 1 col. sopa pasta de amendoim · frutas",
              "1 banana grande · 70 g aveia · 2 ovos · 1,5 col. sopa de pasta de amendoim"],
 "dica": "A aveia é rica em fibra, que retarda a digestão e mantém a saciedade por horas — é o que evita a fome do meio da manhã que faz você beliscar. A banana dá doçura natural sem açúcar adicionado, e o ovo entra com proteína para preservar o músculo enquanto você perde gordura.",
 "prompt": "Square ultra-realistic overhead food photograph of a small stack of golden banana-oat pancakes on a white ceramic plate, topped with fresh banana slices and a few blueberries, a light drizzle of honey, a scatter of rolled oats beside the plate on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ovos Mexidos com Espinafre e Torrada Integral",
 "hook": "O café clássico que enche o prato de proteína e fibra em menos de 10 minutos.",
 "tempo": "8 min", "rende": "1 porção", "kcal_base": 340,
 "ings": ["2 ovos", "1 punhado grande de folhas de espinafre fresco", "1 fatia de pão integral",
          "1 colher de chá de azeite", "sal e pimenta a gosto", "1 tomate pequeno (opcional)"],
 "passos": [
   "Lave o espinafre e escorra bem. Se as folhas forem grandes, corte-as ao meio.",
   "Quebre os ovos numa tigela, tempere com sal e pimenta e bata levemente com um garfo.",
   "Aqueça o azeite numa frigideira que não gruda em fogo médio. Junte o espinafre e mexa por 1 minuto, só até murchar (as folhas ficarem moles).",
   "Abaixe o fogo, despeje os ovos batidos sobre o espinafre e deixe 30 segundos sem mexer.",
   "Com uma espátula, empurre os ovos do fundo para o centro, devagar, até formarem cremosos e ainda úmidos. Desligue o fogo antes de secar demais.",
   "Torre a fatia de pão integral. Sirva os ovos por cima ou ao lado, com rodelas de tomate se quiser."],
 "porcoes8": ["1 ovo + 1 clara · ½ fatia de pão · espinafre à vontade",
              "2 ovos · 1 fatia de pão · espinafre à vontade",
              "2 ovos · 1 fatia de pão · 1 fio a mais de azeite",
              "2 ovos + 1 clara · 1 fatia de pão · 1 col. chá de queijo ralado",
              "3 ovos · 1 fatia de pão · 1 col. chá de azeite",
              "3 ovos · 2 fatias de pão · espinafre à vontade",
              "3 ovos · 2 fatias de pão · 1 col. sopa de queijo ralado",
              "4 ovos · 2 fatias de pão · 1 col. sopa de queijo ralado"],
 "dica": "Ovos são proteína completa e muito saciante — quem come ovos no café sente menos fome ao longo do dia. O espinafre acrescenta volume e fibra com quase nenhuma caloria, então você enche o prato e o estômago sem estourar as calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of soft scrambled eggs with wilted spinach on a white plate, one slice of toasted wholegrain bread and a few cherry tomatoes beside it, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iogurte Grego com Frutas Vermelhas e Aveia",
 "hook": "Montado em camadas, sem cozinhar nada — proteína e fibra numa taça bonita em 3 minutos.",
 "tempo": "3 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["1 pote de iogurte grego natural sem açúcar (≈ 170 g)", "1 punhado de frutas vermelhas (morango, mirtilo ou framboesa)",
          "3 colheres de sopa de aveia em flocos", "1 colher de chá de mel (opcional)", "canela a gosto"],
 "passos": [
   "Se usar morangos, lave e corte em pedaços pequenos. As demais frutas podem ir inteiras.",
   "Numa taça ou copo, coloque metade do iogurte no fundo.",
   "Espalhe metade das frutas e metade da aveia por cima.",
   "Repita: o restante do iogurte, depois as frutas e a aveia que sobraram.",
   "Finalize com uma pitada de canela e, se quiser, o fio de mel. Sirva na hora, enquanto a aveia ainda está crocante."],
 "porcoes8": ["120 g iogurte · frutas · 2 col. aveia",
              "170 g iogurte · frutas · 3 col. aveia",
              "170 g iogurte · frutas · 3 col. aveia · 1 col. chá de mel",
              "200 g iogurte · frutas · 4 col. aveia · 1 col. chá de mel",
              "200 g iogurte · frutas · 4 col. aveia · 1 col. sopa de castanhas",
              "250 g iogurte · frutas · 4 col. aveia · 1 col. sopa de castanhas",
              "250 g iogurte · frutas · 5 col. aveia · 1 col. sopa de castanhas",
              "300 g iogurte · frutas · 6 col. aveia · 1 col. sopa de castanhas"],
 "dica": "O iogurte grego tem quase o dobro de proteína do iogurte comum, o que prolonga a saciedade. Sem açúcar adicionado, a doçura vem das frutas — e a aveia dá fibra e crocância, transformando um lanche rápido numa refeição que sustenta.",
 "prompt": "Square ultra-realistic overhead food photograph of a layered Greek yogurt parfait in a clear glass, with fresh strawberries, blueberries and rolled oats, a light drizzle of honey and a dusting of cinnamon, on a light marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Omelete de Claras com Tomate e Cottage",
 "hook": "Leve, fofa e cheia de proteína — o café de quem quer emagrecer sem passar fome.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 250,
 "ings": ["3 claras + 1 ovo inteiro", "1 tomate pequeno picado", "2 colheres de sopa de queijo cottage",
          "cebolinha ou salsinha picada", "sal e pimenta a gosto", "spray de óleo"],
 "passos": [
   "Pique o tomate em cubinhos e retire o excesso de líquido com um guardanapo, para a omelete não ficar mole.",
   "Numa tigela, junte as claras, o ovo inteiro, sal e pimenta. Bata com um garfo por 30 segundos, até espumar levemente.",
   "Aqueça uma frigideira que não gruda em fogo médio e borrife óleo. Espalhe o tomate picado no fundo por 1 minuto.",
   "Despeje os ovos batidos por cima e incline a frigideira para espalhar de forma uniforme.",
   "Quando as bordas firmarem (1 a 2 minutos), distribua o cottage por metade da omelete.",
   "Com a espátula, dobre a omelete ao meio, cobrindo o cottage. Deixe mais 1 minuto e sirva com as ervas por cima."],
 "porcoes8": ["2 claras + 1 ovo · 1 col. cottage",
              "3 claras + 1 ovo · 2 col. cottage",
              "3 claras + 1 ovo · 2 col. cottage · ½ fatia de pão",
              "3 claras + 1 ovo · 3 col. cottage · 1 fatia de pão",
              "3 claras + 2 ovos · 2 col. cottage · 1 fatia de pão",
              "4 claras + 2 ovos · 3 col. cottage · 1 fatia de pão",
              "4 claras + 2 ovos · 3 col. cottage · 2 fatias de pão",
              "5 claras + 2 ovos · 4 col. cottage · 2 fatias de pão"],
 "dica": "As claras são proteína quase pura, com pouquíssima gordura e caloria — perfeitas para aumentar a proteína do café sem pesar. O cottage entra cremoso e também rico em proteína, e o tomate dá sabor e volume por quase nada de caloria.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded fluffy egg-white omelette with diced tomato and cottage cheese on a white plate, sprinkled with chopped chives, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Aveia Overnight com Maçã e Canela",
 "hook": "Você monta à noite e de manhã já está pronta na geladeira — zero pressa, zero fogão.",
 "tempo": "5 min + geladeira", "rende": "1 porção", "kcal_base": 350,
 "ings": ["40 g de aveia em flocos", "150 ml de leite (ou bebida vegetal)", "½ maçã picada em cubinhos",
          "1 colher de sopa de iogurte natural", "canela a gosto", "1 colher de chá de mel (opcional)"],
 "passos": [
   "Num pote com tampa, misture a aveia, o leite e o iogurte.",
   "Junte metade da maçã picada e uma boa pitada de canela. Mexa bem.",
   "Feche o pote e leve à geladeira por pelo menos 4 horas, ou durante a noite inteira.",
   "De manhã, a aveia estará cremosa e macia. Mexa novamente.",
   "Cubra com o restante da maçã fresca e mais canela. Se quiser, adicione o fio de mel. Coma gelada, direto do pote."],
 "porcoes8": ["30 g aveia · 120 ml leite · ½ maçã",
              "40 g aveia · 150 ml leite · ½ maçã",
              "45 g aveia · 150 ml leite · ½ maçã · 1 col. chá de mel",
              "50 g aveia · 180 ml leite · 1 maçã · 1 col. chá de mel",
              "50 g aveia · 180 ml leite · 1 maçã · 1 col. sopa de castanhas",
              "55 g aveia · 200 ml leite · 1 maçã · 1 col. sopa de castanhas",
              "60 g aveia · 220 ml leite · 1 maçã · 1 col. sopa de castanhas",
              "70 g aveia · 250 ml leite · 1 maçã · 1,5 col. sopa de castanhas"],
 "dica": "Deixar a aveia de molho não muda as calorias, mas deixa a fibra mais fácil de digerir e a refeição mais cremosa e saciante. Como fica pronta na geladeira, você não pula o café da manhã na correria — e pular refeição é o que faz muita gente comer demais no fim do dia.",
 "prompt": "Square ultra-realistic overhead food photograph of overnight oats in a glass jar topped with fresh diced apple and a dusting of cinnamon, a spoon resting beside it on a light wooden table, soft natural morning light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Torrada de Abacate com Ovo",
 "hook": "Cremosa, salgada e do tipo que sacia de verdade — pronta em 8 minutos.",
 "tempo": "8 min", "rende": "1 porção", "kcal_base": 340,
 "ings": ["1 fatia de pão integral", "½ abacate maduro (ou ¼ de abacate grande)", "1 ovo",
          "suco de ½ limão", "sal, pimenta e pimenta calabresa a gosto", "spray de óleo"],
 "passos": [
   "Torre a fatia de pão integral até ficar firme e dourada.",
   "Numa tigela pequena, amasse o abacate com o garfo, junte o suco de limão, sal e pimenta. Misture até virar um creme.",
   "Aqueça uma frigideira que não gruda, borrife óleo e frite o ovo em fogo médio, do jeito que preferir (frito com gema mole ou mexido).",
   "Espalhe o creme de abacate sobre a torrada.",
   "Coloque o ovo por cima e finalize com uma pitada de pimenta calabresa. Sirva imediatamente."],
 "porcoes8": ["½ fatia de pão · ¼ abacate · 1 ovo",
              "1 fatia de pão · ½ abacate · 1 ovo",
              "1 fatia de pão · ½ abacate · 1 ovo · folhas verdes",
              "1 fatia de pão · ½ abacate · 2 ovos",
              "1 fatia de pão · ½ abacate · 2 ovos · folhas verdes",
              "2 fatias de pão · ½ abacate · 2 ovos",
              "2 fatias de pão · 1 abacate pequeno · 2 ovos",
              "2 fatias de pão · 1 abacate pequeno · 3 ovos"],
 "dica": "O abacate tem gordura boa, que dá saciedade prolongada e deixa a refeição cremosa sem manteiga. Junto do ovo e do pão integral, você tem gordura boa, proteína e fibra na mesma torrada — a combinação que segura a fome por horas.",
 "prompt": "Square ultra-realistic overhead food photograph of avocado toast on wholegrain bread topped with a fried egg with runny yolk, sprinkled with chili flakes and cracked pepper, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mingau de Aveia com Banana e Pasta de Amendoim",
 "hook": "Quentinho e reconfortante, o café que parece sobremesa mas trabalha a seu favor.",
 "tempo": "8 min", "rende": "1 porção", "kcal_base": 380,
 "ings": ["40 g de aveia em flocos", "200 ml de leite (ou bebida vegetal)", "½ banana amassada",
          "1 colher de chá de pasta de amendoim", "canela a gosto", "½ banana em rodelas para cobrir"],
 "passos": [
   "Numa panela pequena, junte a aveia, o leite e a banana amassada.",
   "Leve ao fogo médio-baixo, mexendo sempre com uma colher para não grudar no fundo.",
   "Depois de 4 a 5 minutos, a mistura engrossa e fica cremosa. Se quiser mais ralo, junte um pouco mais de leite.",
   "Desligue o fogo, junte a canela e mexa.",
   "Despeje numa tigela, cubra com as rodelas de banana e a pasta de amendoim por cima. Sirva quente."],
 "porcoes8": ["30 g aveia · 180 ml leite · ½ banana · sem pasta",
              "40 g aveia · 200 ml leite · 1 banana · 1 col. chá de pasta",
              "45 g aveia · 200 ml leite · 1 banana · 1 col. chá de pasta",
              "50 g aveia · 220 ml leite · 1 banana · 1 col. sopa de pasta",
              "50 g aveia · 220 ml leite · 1 banana · 1 col. sopa de pasta",
              "55 g aveia · 250 ml leite · 1 banana · 1 col. sopa de pasta",
              "60 g aveia · 250 ml leite · 1 banana · 1,5 col. sopa de pasta",
              "70 g aveia · 300 ml leite · 1 banana · 2 col. sopa de pasta"],
 "dica": "A aveia cozida forma um gel no estômago que retarda a fome. A banana adoça sem açúcar e repõe energia, e a pasta de amendoim entra com gordura boa e proteína — só cuidado com a quantidade, porque ela é calórica: uma colher já faz efeito.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of creamy oatmeal porridge topped with banana slices and a swirl of peanut butter, dusted with cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie Bowl de Banana e Frutas Vermelhas",
 "hook": "Grosso de colher, gelado e colorido — parece açaí, mas trabalha pelo seu emagrecimento.",
 "tempo": "6 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["1 banana congelada em rodelas", "1 punhado de frutas vermelhas congeladas",
          "3 colheres de sopa de iogurte natural", "50 ml de leite (ou bebida vegetal)",
          "2 colheres de sopa de aveia e frutas frescas para cobrir"],
 "passos": [
   "Use a banana já congelada (corte em rodelas na noite anterior e congele) — é o que deixa o smoothie grosso sem gelo.",
   "No liquidificador, junte a banana, as frutas vermelhas congeladas, o iogurte e o leite.",
   "Bata em potência alta (velocidade máxima), parando para mexer com uma colher quando travar. Adicione leite só uma colher por vez, o mínimo para bater. A textura tem de ficar grossa, de sorvete.",
   "Despeje numa tigela.",
   "Cubra com a aveia e as frutas frescas em fileiras bonitas. Coma na hora, de colher, antes de derreter."],
 "porcoes8": ["1 banana · frutas · 2 col. iogurte · 1 col. aveia",
              "1 banana · frutas · 3 col. iogurte · 2 col. aveia",
              "1 banana · frutas · 3 col. iogurte · 2 col. aveia · sementes",
              "1 banana · frutas · 4 col. iogurte · 3 col. aveia",
              "1 banana · frutas · 4 col. iogurte · 3 col. aveia · 1 col. castanhas",
              "1 banana grande · frutas · 5 col. iogurte · 3 col. aveia · castanhas",
              "1 banana grande · frutas · 5 col. iogurte · 4 col. aveia · castanhas",
              "2 bananas · frutas · 6 col. iogurte · 4 col. aveia · castanhas"],
 "dica": "Congelar a fruta dá a textura de sorvete sem precisar de açúcar nem creme. O iogurte acrescenta proteína, e comer de colher, devagar, faz o cérebro registrar a saciedade — bem diferente de tomar um suco batido de canudo em segundos.",
 "prompt": "Square ultra-realistic overhead food photograph of a thick berry-banana smoothie bowl topped with neat rows of fresh strawberries, blueberries and rolled oats, in a light ceramic bowl on a marble surface, soft natural light, vibrant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ovos Cozidos com Abacate e Tomate",
 "hook": "Sem frigideira, sem bagunça — proteína e gordura boa num prato montado em minutos.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["2 ovos", "½ abacate", "1 tomate", "suco de ½ limão", "sal, pimenta e azeite a gosto",
          "folhas verdes a gosto"],
 "passos": [
   "Coloque os ovos numa panela, cubra com água fria e leve ao fogo. A partir da fervura, conte 8 a 9 minutos para gema firme.",
   "Enquanto isso, corte o abacate e o tomate em fatias e disponha no prato sobre algumas folhas verdes.",
   "Escorra os ovos e passe-os por água fria por 1 minuto — isso facilita descascar.",
   "Descasque os ovos, corte ao meio e coloque no prato.",
   "Regue tudo com o suco de limão e um fio de azeite, tempere com sal e pimenta e sirva."],
 "porcoes8": ["1 ovo · ¼ abacate · tomate",
              "2 ovos · ½ abacate · tomate",
              "2 ovos · ½ abacate · tomate · ½ fatia de pão",
              "2 ovos · ½ abacate · tomate · 1 fatia de pão",
              "3 ovos · ½ abacate · tomate · 1 fatia de pão",
              "3 ovos · ½ abacate · tomate · 2 fatias de pão",
              "3 ovos · 1 abacate pequeno · tomate · 2 fatias de pão",
              "4 ovos · 1 abacate pequeno · tomate · 2 fatias de pão"],
 "dica": "Ovo cozido é a proteína mais prática que existe: você pode cozinhar vários de uma vez e guardar na geladeira. Com abacate e tomate, monta um café completo em gordura boa e fibra sem ligar o fogão de manhã.",
 "prompt": "Square ultra-realistic overhead food photograph of halved boiled eggs with sliced avocado and tomato on a bed of green leaves, drizzled with olive oil, on a white plate on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Panqueca Proteica de Aveia e Claras",
 "hook": "A panqueca dos dias de treino: mais proteína, mesma facilidade.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["40 g de aveia em flocos", "3 claras (ou 2 claras + 1 ovo)", "½ banana amassada",
          "1 pitada de fermento em pó", "canela a gosto", "spray de óleo"],
 "passos": [
   "Se preferir a massa mais fina, bata a aveia no liquidificador até virar uma farinha. Se gostar rústica, use em flocos mesmo.",
   "Numa tigela, misture a aveia, as claras, a banana amassada, o fermento e a canela até ficar tudo bem misturado.",
   "Deixe descansar 3 minutos para a aveia hidratar.",
   "Aqueça a frigideira que não gruda em fogo médio-baixo e borrife óleo.",
   "Faça panquecas pequenas. Deixe 2 minutos de cada lado, virando quando aparecerem bolhinhas.",
   "Sirva com frutas frescas por cima. Evite xaropes açucarados — a banana já adoça."],
 "porcoes8": ["2 claras · 30 g aveia · ½ banana",
              "3 claras · 40 g aveia · ½ banana",
              "3 claras · 45 g aveia · ½ banana · frutas",
              "2 claras + 1 ovo · 50 g aveia · 1 banana",
              "3 claras + 1 ovo · 50 g aveia · 1 banana",
              "3 claras + 1 ovo · 55 g aveia · 1 banana · frutas",
              "4 claras + 1 ovo · 60 g aveia · 1 banana · frutas",
              "4 claras + 2 ovos · 70 g aveia · 1 banana · frutas"],
 "dica": "Trocar parte dos ovos por claras aumenta a proteína e reduz a gordura — bom para quem quer definição. A proteína também é o nutriente mais saciante, então essa panqueca segura a fome com menos calorias que a versão doce tradicional.",
 "prompt": "Square ultra-realistic overhead food photograph of a stack of protein oat pancakes topped with fresh strawberries and blueberries on a white plate, on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pudim de Chia com Frutas",
 "hook": "Você mistura em 2 minutos, a geladeira faz o resto, e acorda com uma sobremesa saudável.",
 "tempo": "5 min + geladeira", "rende": "1 porção", "kcal_base": 280,
 "ings": ["3 colheres de sopa de sementes de chia", "200 ml de leite (ou bebida vegetal)",
          "½ colher de chá de essência de baunilha (opcional)", "frutas picadas a gosto para cobrir",
          "1 colher de chá de mel (opcional)"],
 "passos": [
   "Num pote com tampa, junte a chia, o leite e a baunilha. Mexa bem por 30 segundos.",
   "Espere 5 minutos e mexa de novo — esse segundo mexer desfaz os grumos que se formam e é o segredo de um pudim liso.",
   "Feche o pote e leve à geladeira por pelo menos 4 horas, ou de um dia para o outro.",
   "A chia absorve o líquido e forma um pudim de textura gelatinosa.",
   "Antes de servir, mexa, cubra com frutas picadas e, se quiser, o fio de mel."],
 "porcoes8": ["2 col. chia · 150 ml leite · frutas",
              "3 col. chia · 200 ml leite · frutas",
              "3 col. chia · 200 ml leite · frutas · 1 col. chá de mel",
              "3 col. chia · 220 ml leite · frutas · 1 col. sopa de granola",
              "4 col. chia · 220 ml leite · frutas · 1 col. sopa de granola",
              "4 col. chia · 250 ml leite · frutas · 2 col. sopa de granola",
              "4 col. chia · 250 ml leite · frutas · 2 col. granola · castanhas",
              "5 col. chia · 300 ml leite · frutas · 2 col. granola · castanhas"],
 "dica": "A chia absorve muitas vezes o próprio peso em líquido e incha no estômago, dando uma sensação de saciedade duradoura. Ainda é rica em fibra e ômega-3 — um dos ingredientes mais saciantes por caloria que existe.",
 "prompt": "Square ultra-realistic overhead food photograph of chia pudding in a glass jar topped with fresh raspberries, blueberries and kiwi slices, a spoon beside it on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Muffins de Ovo Assados com Legumes",
 "hook": "Você assa uma leva e tem café pronto a semana toda — é só esquentar e comer.",
 "tempo": "25 min", "rende": "6 muffins (2 por porção)", "kcal_base": 220,
 "ings": ["6 ovos", "½ pimentão picado", "1 punhado de espinafre picado", "2 colheres de sopa de queijo ralado",
          "sal e pimenta a gosto", "um pouco de óleo (ou spray) para a comida não grudar"],
 "passos": [
   "Pré-aqueça o forno a 180 °C e passe um pouco de óleo (ou spray) na forma de muffin, para os ovos não grudarem.",
   "Pique bem o pimentão e o espinafre em pedaços pequenos.",
   "Numa tigela, bata os ovos com sal e pimenta. Junte os legumes e o queijo e misture.",
   "Divida a mistura entre as 6 cavidades, enchendo cada uma até cerca de 3/4.",
   "Asse por 18 a 20 minutos, até firmarem e dourarem levemente. Um palito no centro deve sair limpo.",
   "Espere amornar para desenformar. Guarde na geladeira por até 4 dias e esquente na hora de comer."],
 "porcoes8": ["1 muffin + folhas verdes",
              "2 muffins",
              "2 muffins · ½ fatia de pão",
              "2 muffins · 1 fatia de pão",
              "3 muffins · 1 fatia de pão",
              "3 muffins · 2 fatias de pão",
              "3 muffins · 2 fatias de pão · ¼ abacate",
              "4 muffins · 2 fatias de pão · ¼ abacate"],
 "dica": "Ter comida pronta é o que impede a decisão errada na fome da manhã. Esses muffins são proteína e legumes em porção controlada — dá para congelar e sempre ter um café que sustenta à mão, sem improvisar com o que não devia.",
 "prompt": "Square ultra-realistic overhead food photograph of baked egg muffins with bell pepper, spinach and cheese, arranged on a white plate on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Torrada com Ricota, Morango e Mel",
 "hook": "Doce e cremosa como um docinho, mas com proteína e sem açúcar pesado.",
 "tempo": "6 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["1 fatia de pão integral", "3 colheres de sopa de ricota", "4 morangos em fatias",
          "1 colher de chá de mel", "raspas de limão e hortelã (opcional)"],
 "passos": [
   "Torre a fatia de pão até ficar firme.",
   "Numa tigela, amasse a ricota com o garfo até ficar cremosa. Se estiver seca, junte um pouquinho de leite.",
   "Espalhe a ricota sobre a torrada, cobrindo toda a superfície.",
   "Distribua as fatias de morango por cima.",
   "Finalize com o fio de mel e, se quiser, raspas de limão e folhinhas de hortelã. Sirva na hora."],
 "porcoes8": ["½ fatia de pão · 2 col. ricota · morangos",
              "1 fatia de pão · 3 col. ricota · morangos · 1 col. chá de mel",
              "1 fatia de pão · 3 col. ricota · morangos · mel",
              "1 fatia de pão · 4 col. ricota · morangos · mel · castanhas",
              "1 fatia de pão · 4 col. ricota · morangos · 1 ovo cozido",
              "2 fatias de pão · 4 col. ricota · morangos · mel",
              "2 fatias de pão · 5 col. ricota · morangos · castanhas",
              "2 fatias de pão · 6 col. ricota · morangos · castanhas · 1 ovo"],
 "dica": "A ricota é um queijo magro, cremoso e rico em proteína — mata a vontade de doce sem o creme calórico dos recheios industrializados. O morango dá doçura e frescor, e uma colher de chá de mel adoça o suficiente sem transformar o café em bomba de açúcar.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of wholegrain toast spread with ricotta cheese, topped with fresh strawberry slices and a drizzle of honey, garnished with mint, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Aveia Quente com Cacau e Banana",
 "hook": "Gosto de chocolate no café da manhã, sem açúcar e sem culpa.",
 "tempo": "8 min", "rende": "1 porção", "kcal_base": 350,
 "ings": ["40 g de aveia em flocos", "200 ml de leite (ou bebida vegetal)", "1 colher de sopa de cacau em pó 100%",
          "1 banana", "canela a gosto", "adoçante ou 1 colher de chá de mel (opcional)"],
 "passos": [
   "Numa panela pequena, misture a aveia, o leite e o cacau em pó antes de ligar o fogo — assim o cacau dissolve sem empelotar.",
   "Leve ao fogo médio-baixo, mexendo sempre.",
   "Amasse metade da banana e junte à panela; reserve a outra metade em rodelas.",
   "Cozinhe por 4 a 5 minutos, até engrossar e ficar cremoso.",
   "Prove e ajuste a doçura com adoçante ou uma colher de chá de mel, se precisar.",
   "Sirva numa tigela com as rodelas de banana e uma pitada de canela por cima."],
 "porcoes8": ["30 g aveia · 180 ml leite · 1 col. cacau · ½ banana",
              "40 g aveia · 200 ml leite · 1 col. cacau · 1 banana",
              "45 g aveia · 200 ml leite · 1 col. cacau · 1 banana",
              "50 g aveia · 220 ml leite · 1 col. cacau · 1 banana · castanhas",
              "50 g aveia · 220 ml leite · cacau · 1 banana · 1 col. chá de pasta de amendoim",
              "55 g aveia · 250 ml leite · cacau · 1 banana · 1 col. sopa de pasta de amendoim",
              "60 g aveia · 250 ml leite · cacau · 1 banana · pasta de amendoim",
              "70 g aveia · 300 ml leite · cacau · 1 banana · pasta de amendoim"],
 "dica": "O cacau 100% dá o sabor de chocolate sem o açúcar do achocolatado — e ainda tem antioxidantes. Matar a vontade de doce logo no café evita o ataque à barra de chocolate mais tarde, que é onde muita dieta desanda.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of chocolate oatmeal made with cocoa, topped with banana slices and a dusting of cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Omelete de Cogumelos e Espinafre",
 "hook": "Terrosa e saborosa, enche o prato de nutrientes com pouquíssimas calorias.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 260,
 "ings": ["2 ovos", "1 punhado de cogumelos fatiados (champignon)", "1 punhado de espinafre",
          "1 colher de chá de azeite", "sal, pimenta e alho picado a gosto"],
 "passos": [
   "Fatie os cogumelos e lave o espinafre.",
   "Aqueça o azeite numa frigideira que não gruda em fogo médio-alto. Frite os cogumelos em um pouco de óleo por 3 a 4 minutos, sem mexer demais, até dourarem e soltarem a água.",
   "Junte o alho e o espinafre e mexa por 1 minuto, só até murchar (as folhas ficarem moles). Tempere com sal e pimenta.",
   "Bata os ovos numa tigela e despeje sobre os legumes. Abaixe o fogo.",
   "Deixe a base firmar por 1 a 2 minutos, dobre a omelete ao meio e sirva."],
 "porcoes8": ["1 ovo + 1 clara · legumes à vontade",
              "2 ovos · legumes à vontade",
              "2 ovos · legumes · ½ fatia de pão",
              "2 ovos · legumes · 1 fatia de pão",
              "3 ovos · legumes · 1 fatia de pão",
              "3 ovos · legumes · 2 fatias de pão",
              "3 ovos · legumes · 2 fatias de pão · queijo",
              "4 ovos · legumes · 2 fatias de pão · queijo"],
 "dica": "Cogumelos e espinafre dão volume, sabor e nutrientes por quase nenhuma caloria — você enche o prato e o estômago. Os ovos completam com proteína saciante, fazendo uma refeição farta que ainda cabe folgada na dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a folded omelette with sautéed mushrooms and spinach on a white plate, garnished with fresh herbs, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iogurte com Granola Caseira e Mirtilos",
 "hook": "A granola você faz sem açúcar em casa e usa a semana toda — crocante e do jeito certo.",
 "tempo": "5 min (+ granola pronta)", "rende": "1 porção", "kcal_base": 330,
 "ings": ["1 pote de iogurte grego natural (≈ 170 g)", "3 colheres de sopa de granola caseira sem açúcar",
          "1 punhado de mirtilos", "canela a gosto",
          "(granola: aveia + castanhas picadas + canela, assadas a 160 °C por 15 min)"],
 "passos": [
   "Para a granola caseira: misture aveia em flocos com castanhas picadas e canela, espalhe numa assadeira e asse a 160 °C por 12 a 15 minutos, mexendo na metade. Deixe esfriar para ficar crocante e guarde num pote.",
   "Numa taça, coloque o iogurte.",
   "Cubra com a granola caseira.",
   "Espalhe os mirtilos por cima e finalize com uma pitada de canela.",
   "Sirva na hora, para a granola não amolecer."],
 "porcoes8": ["120 g iogurte · 2 col. granola · mirtilos",
              "170 g iogurte · 3 col. granola · mirtilos",
              "170 g iogurte · 3 col. granola · mirtilos",
              "200 g iogurte · 4 col. granola · mirtilos",
              "200 g iogurte · 4 col. granola · mirtilos",
              "250 g iogurte · 4 col. granola · mirtilos",
              "250 g iogurte · 5 col. granola · mirtilos",
              "300 g iogurte · 6 col. granola · mirtilos"],
 "dica": "Granola de pacote costuma ser cheia de açúcar e óleo — fazer em casa corta isso e você controla o que entra. Com iogurte grego rico em proteína e mirtilos, vira um café crocante e saciante sem os açúcares escondidos das versões industrializadas.",
 "prompt": "Square ultra-realistic overhead food photograph of a bowl of Greek yogurt topped with homemade golden granola and fresh blueberries, on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Wrap Integral de Ovo Mexido e Vegetais",
 "hook": "Enrola e leva — o café da manhã de quem sai correndo, mas não abre mão de comer bem.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 340,
 "ings": ["1 tortilha/wrap integral", "2 ovos", "½ tomate picado", "1 punhado de espinafre",
          "1 colher de sopa de queijo ralado", "sal, pimenta e spray de óleo"],
 "passos": [
   "Pique o tomate e reserve. Lave o espinafre.",
   "Bata os ovos com sal e pimenta. Aqueça a frigideira com spray de óleo em fogo médio.",
   "Junte o espinafre e o tomate por 1 minuto, depois despeje os ovos e mexa até formar ovos mexidos cremosos.",
   "Aqueça a tortilha por 20 segundos de cada lado numa frigideira seca, só para amaciar.",
   "Coloque os ovos no centro da tortilha, salpique o queijo e dobre as laterais para dentro.",
   "Enrole firme como um burrito e corte ao meio. Pode comer na mão, na correria."],
 "porcoes8": ["1 wrap · 1 ovo + 1 clara · legumes",
              "1 wrap · 2 ovos · legumes · queijo",
              "1 wrap · 2 ovos · legumes · queijo",
              "1 wrap · 2 ovos · legumes · ¼ abacate",
              "1 wrap · 3 ovos · legumes · queijo",
              "1 wrap grande · 3 ovos · legumes · queijo · ¼ abacate",
              "1 wrap grande · 3 ovos · legumes · queijo · ½ abacate",
              "1 wrap grande · 4 ovos · legumes · queijo · ½ abacate"],
 "dica": "Poder levar o café na mão é o que evita pular a refeição no dia corrido. Recheado de ovo e vegetais, esse wrap dá proteína e fibra num formato prático — muito melhor que resolver a fome numa padaria com pão doce.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain wrap filled with scrambled eggs, spinach and tomato, cut in half to show the filling, on a light wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Panqueca de Maçã e Canela",
 "hook": "Cheira a torta de maçã e cabe na dieta — o conforto do café doce sem sabotar o dia.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["40 g de aveia em flocos", "1 ovo", "½ maçã ralada", "canela a gosto",
          "1 pitada de fermento em pó", "spray de óleo", "½ maçã em fatias finas para cobrir"],
 "passos": [
   "Rale metade da maçã no ralo grosso e reserve a outra metade em fatias.",
   "Numa tigela, misture a aveia, o ovo, a maçã ralada, a canela e o fermento até ficar tudo bem misturado.",
   "Deixe descansar 3 minutos para a aveia hidratar.",
   "Aqueça a frigideira que não gruda em fogo médio-baixo e borrife óleo.",
   "Faça panquecas pequenas, deixando 2 a 3 minutos de cada lado.",
   "Enquanto isso, doure as fatias de maçã na mesma frigideira com uma pitada de canela. Sirva por cima das panquecas."],
 "porcoes8": ["30 g aveia · 1 ovo · ½ maçã",
              "40 g aveia · 1 ovo · ½ maçã",
              "45 g aveia · 1 ovo · ½ maçã · castanhas",
              "50 g aveia · 1 ovo · 1 maçã · castanhas",
              "50 g aveia · 2 ovos · 1 maçã",
              "55 g aveia · 2 ovos · 1 maçã · castanhas",
              "60 g aveia · 2 ovos · 1 maçã · castanhas",
              "70 g aveia · 2 ovos · 1 maçã · 1 col. sopa de pasta de amendoim"],
 "dica": "A maçã traz doçura e fibra, e a canela realça o sabor sem uma pitada de açúcar — estudos sugerem que ela ainda ajuda a controlar o apetite. É a versão que mata a vontade de torta doce sem os carboidratos refinados que engordam.",
 "prompt": "Square ultra-realistic overhead food photograph of apple-cinnamon oat pancakes topped with caramelized apple slices and a dusting of cinnamon, on a white plate on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Torrada Integral com Pasta de Amendoim e Banana",
 "hook": "O clássico de 5 minutos que combina energia, gordura boa e doçura natural.",
 "tempo": "5 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["1 fatia de pão integral", "1 colher de sopa de pasta de amendoim", "1 banana em rodelas",
          "canela a gosto", "1 pitada de sementes de chia (opcional)"],
 "passos": [
   "Torre a fatia de pão até ficar firme.",
   "Espalhe a pasta de amendoim sobre a torrada ainda quente — ela derrete um pouco e fica mais fácil de espalhar.",
   "Cubra com as rodelas de banana.",
   "Salpique canela e, se quiser, as sementes de chia por cima.",
   "Sirva imediatamente. Para levar, corte ao meio e monte como sanduíche."],
 "porcoes8": ["½ fatia de pão · 1 col. chá de pasta · ½ banana",
              "1 fatia de pão · 1 col. sopa de pasta · 1 banana",
              "1 fatia de pão · 1 col. sopa de pasta · 1 banana · chia",
              "1 fatia de pão · 1,5 col. sopa de pasta · 1 banana",
              "1 fatia de pão · 1,5 col. sopa de pasta · 1 banana · 1 ovo cozido",
              "2 fatias de pão · 2 col. sopa de pasta · 1 banana",
              "2 fatias de pão · 2 col. sopa de pasta · 1 banana · 1 ovo",
              "2 fatias de pão · 2,5 col. sopa de pasta · 1 banana · 1 ovo"],
 "dica": "A pasta de amendoim tem gordura boa e proteína, que dão saciedade prolongada — mas é calórica, então a medida importa: uma colher de sopa já é suficiente. Sobre pão integral e banana, você tem energia estável para a manhã inteira, sem o pico e a queda do açúcar.",
 "prompt": "Square ultra-realistic overhead food photograph of wholegrain toast spread with peanut butter, topped with banana slices, chia seeds and a dusting of cinnamon, on a light wooden board, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ovos Poché com Aspargos e Torrada",
 "hook": "Elegante como café de restaurante, simples o bastante para um dia comum.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["2 ovos", "1 punhado de aspargos", "1 fatia de pão integral", "1 colher de chá de vinagre (para a água)",
          "sal, pimenta e azeite a gosto"],
 "passos": [
   "Lave os aspargos e corte a base dura. Cozinhe em água fervente com sal por 3 minutos, escorra e reserve.",
   "Numa panela, aqueça água até quase ferver (com bolhas pequenas, sem borbulhar forte) e junte o vinagre.",
   "Quebre cada ovo numa xícara. Faça um redemoinho na água com uma colher e escorregue o ovo bem devagar no centro — o movimento envolve a clara na gema.",
   "Cozinhe por 3 minutos para gema mole. Retire com uma colher com furos e apoie sobre papel-toalha.",
   "Torre o pão. Monte com os aspargos por baixo, os ovos poché por cima, um fio de azeite, sal e pimenta."],
 "porcoes8": ["1 ovo · aspargos · ½ fatia de pão",
              "2 ovos · aspargos · 1 fatia de pão",
              "2 ovos · aspargos · 1 fatia de pão · queijo",
              "2 ovos · aspargos · 1 fatia de pão · ¼ abacate",
              "3 ovos · aspargos · 1 fatia de pão",
              "3 ovos · aspargos · 2 fatias de pão",
              "3 ovos · aspargos · 2 fatias de pão · ¼ abacate",
              "4 ovos · aspargos · 2 fatias de pão · ¼ abacate"],
 "dica": "O ovo poché é feito só na água, sem óleo, o que mantém as calorias baixas. Os aspargos são ricos em fibra e água e praticamente não têm caloria — um café que parece sofisticado e ainda joga a favor da balança.",
 "prompt": "Square ultra-realistic overhead food photograph of two poached eggs with runny yolks on a slice of wholegrain toast, with green asparagus spears alongside, drizzled with olive oil and cracked pepper, on a white plate, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Aveia com Pêra e Nozes",
 "hook": "Cremosa, levemente adocicada pela pêra e com a crocância das nozes.",
 "tempo": "8 min", "rende": "1 porção", "kcal_base": 350,
 "ings": ["40 g de aveia em flocos", "200 ml de leite (ou bebida vegetal)", "½ pêra picada",
          "3 nozes picadas", "canela a gosto", "1 colher de chá de mel (opcional)"],
 "passos": [
   "Numa panela pequena, junte a aveia e o leite e leve ao fogo médio-baixo, mexendo.",
   "Depois de 3 minutos, junte metade da pêra picada e cozinhe por mais 2 minutos, até engrossar.",
   "Desligue o fogo e junte a canela.",
   "Sirva numa tigela e cubra com o restante da pêra fresca e as nozes picadas.",
   "Se precisar, adoce com uma colher de chá de mel."],
 "porcoes8": ["30 g aveia · 180 ml leite · ½ pêra · 2 nozes",
              "40 g aveia · 200 ml leite · ½ pêra · 3 nozes",
              "45 g aveia · 200 ml leite · ½ pêra · 3 nozes",
              "50 g aveia · 220 ml leite · 1 pêra · 3 nozes",
              "50 g aveia · 220 ml leite · 1 pêra · 4 nozes",
              "55 g aveia · 250 ml leite · 1 pêra · 4 nozes",
              "60 g aveia · 250 ml leite · 1 pêra · 5 nozes",
              "70 g aveia · 300 ml leite · 1 pêra · 5 nozes"],
 "dica": "A pêra é rica em fibra e adoça naturalmente, dispensando o açúcar. As nozes têm gordura boa que dá saciedade e crocância — mas são calóricas, então poucas unidades já cumprem o papel sem estourar as calorias do café.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of creamy oatmeal topped with fresh pear slices and chopped walnuts, dusted with cinnamon, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iogurte Grego com Pêssego e Amêndoas",
 "hook": "Cremoso e docinho pelo pêssego, com o crocante das amêndoas — pronto em 3 minutos.",
 "tempo": "3 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["1 pote de iogurte grego natural (≈ 170 g)", "1 pêssego em fatias (ou ½ lata sem calda)",
          "1 colher de sopa de amêndoas laminadas", "canela a gosto", "1 colher de chá de mel (opcional)"],
 "passos": [
   "Se o pêssego for fresco, lave e corte em fatias finas. Se for em conserva, escolha sem calda açucarada e escorra bem.",
   "Coloque o iogurte numa taça.",
   "Distribua as fatias de pêssego por cima.",
   "Salpique as amêndoas laminadas e a canela.",
   "Se precisar de mais doçura, acrescente uma colher de chá de mel. Sirva na hora."],
 "porcoes8": ["120 g iogurte · pêssego · ½ col. amêndoas",
              "170 g iogurte · pêssego · 1 col. amêndoas",
              "170 g iogurte · pêssego · 1 col. amêndoas · mel",
              "200 g iogurte · pêssego · 1 col. amêndoas · 2 col. aveia",
              "200 g iogurte · pêssego · 1,5 col. amêndoas · 2 col. aveia",
              "250 g iogurte · pêssego · 1,5 col. amêndoas · 3 col. aveia",
              "250 g iogurte · pêssego · 2 col. amêndoas · 3 col. aveia",
              "300 g iogurte · pêssego · 2 col. amêndoas · 4 col. aveia"],
 "dica": "O pêssego é doce e tem poucas calorias, o que satisfaz a vontade de açúcar de forma leve. Com o iogurte grego proteico e um punhado de amêndoas, você combina proteína e gordura boa para uma saciedade que atravessa a manhã.",
 "prompt": "Square ultra-realistic overhead food photograph of Greek yogurt topped with fresh peach slices and toasted flaked almonds, dusted with cinnamon, in a light ceramic bowl on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sanduíche Integral de Peru e Queijo",
 "hook": "Salgado, prático e proteico — o café rápido para quem não curte doce de manhã.",
 "tempo": "6 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["2 fatias de pão integral", "2 fatias de peito de peru", "1 fatia de queijo branco",
          "folhas de alface", "rodelas de tomate", "1 colher de chá de mostarda ou requeijão light"],
 "passos": [
   "Se gostar quente, aqueça as fatias de pão numa frigideira seca por 1 minuto de cada lado.",
   "Passe a mostarda ou o requeijão light numa fatia de pão.",
   "Monte as camadas: peru, queijo, tomate e alface.",
   "Feche com a outra fatia de pão e pressione levemente.",
   "Corte na diagonal e sirva. Para levar, embrulhe em papel-manteiga."],
 "porcoes8": ["1 fatia de pão (aberto) · 1 peru · queijo",
              "2 fatias de pão · 2 peru · queijo",
              "2 fatias de pão · 2 peru · queijo",
              "2 fatias de pão · 3 peru · queijo · ¼ abacate",
              "2 fatias de pão · 3 peru · queijo · 1 ovo cozido",
              "2 fatias de pão · 4 peru · queijo · 1 ovo",
              "3 fatias de pão · 4 peru · queijo · 1 ovo",
              "3 fatias de pão · 5 peru · 2 queijos · 1 ovo"],
 "dica": "O peito de peru é uma das carnes mais magras que existem, quase pura proteína, sem a gordura de embutidos como salame e mortadela. Num pão integral com salada, é um café salgado que sustenta com poucas calorias e nada de açúcar.",
 "prompt": "Square ultra-realistic overhead food photograph of a wholegrain turkey and cheese sandwich with lettuce and tomato, cut diagonally to show the filling, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Omelete de Legumes",
 "hook": "Colorida e cheia de sabor, usa o que você tem na geladeira e enche o prato.",
 "tempo": "10 min", "rende": "1 porção", "kcal_base": 260,
 "ings": ["2 ovos", "¼ de pimentão picado", "¼ de cebola picada", "½ tomate picado",
          "1 colher de chá de azeite", "sal, pimenta e cheiro-verde a gosto"],
 "passos": [
   "Pique o pimentão, a cebola e o tomate em cubinhos pequenos.",
   "Aqueça o azeite numa frigideira que não gruda em fogo médio. Frite a cebola e o pimentão em um pouco de óleo, mexendo, por 2 a 3 minutos, até ficarem macios.",
   "Junte o tomate e frite por mais 1 minuto. Tempere com sal e pimenta.",
   "Bata os ovos e despeje sobre os legumes. Incline a frigideira para espalhar.",
   "Quando a base firmar (2 minutos), dobre a omelete ao meio, cozinhe mais 1 minuto e sirva com cheiro-verde."],
 "porcoes8": ["1 ovo + 1 clara · legumes à vontade",
              "2 ovos · legumes à vontade",
              "2 ovos · legumes · ½ fatia de pão",
              "2 ovos · legumes · 1 fatia de pão",
              "3 ovos · legumes · 1 fatia de pão",
              "3 ovos · legumes · 2 fatias de pão",
              "3 ovos · legumes · 2 fatias de pão · queijo",
              "4 ovos · legumes · 2 fatias de pão · queijo"],
 "dica": "Encher a omelete de legumes aumenta o volume e a fibra com pouquíssima caloria, então você come um prato farto sem culpa. É também uma forma esperta de comer mais vegetais logo de manhã, o que ajuda a bater a meta de fibra do dia.",
 "prompt": "Square ultra-realistic overhead food photograph of a colorful vegetable omelette with bell pepper, onion and tomato, folded on a white plate, garnished with fresh parsley, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie Verde de Espinafre, Banana e Maçã",
 "hook": "Verde, gelado e docinho — você nem sente o espinafre, mas o corpo agradece.",
 "tempo": "5 min", "rende": "1 porção", "kcal_base": 250,
 "ings": ["1 punhado grande de espinafre", "½ banana", "½ maçã", "200 ml de água gelada (ou leite vegetal)",
          "1 colher de sopa de aveia", "suco de ½ limão", "gelo a gosto"],
 "passos": [
   "Lave bem o espinafre.",
   "No liquidificador, coloque primeiro o líquido, depois o espinafre — bater as folhas com o líquido antes evita pedaços.",
   "Bata por 30 segundos, até o espinafre desmanchar.",
   "Junte a banana, a maçã (sem sementes), a aveia, o suco de limão e o gelo.",
   "Bata em potência alta (velocidade máxima) até ficar liso e bem misturado. Sirva na hora, bem gelado."],
 "porcoes8": ["espinafre · ½ banana · ½ maçã · 1 col. aveia",
              "espinafre · ½ banana · ½ maçã · 1 col. aveia",
              "espinafre · 1 banana · ½ maçã · 2 col. aveia",
              "espinafre · 1 banana · ½ maçã · 2 col. aveia · iogurte",
              "espinafre · 1 banana · 1 maçã · 2 col. aveia · iogurte",
              "espinafre · 1 banana · 1 maçã · 3 col. aveia · iogurte",
              "espinafre · 1 banana · 1 maçã · 3 col. aveia · iogurte · castanhas",
              "espinafre · 1 banana · 1 maçã · 4 col. aveia · iogurte · castanhas"],
 "dica": "Bater o espinafre com fruta é uma forma indolor de comer folhas de manhã — o sabor doce da banana e da maçã disfarça o verde. É leve em calorias e rico em água e fibra, ótimo para começar o dia hidratado e saciado.",
 "prompt": "Square ultra-realistic photograph of a tall glass of green spinach-banana-apple smoothie on a light wooden table, with fresh spinach leaves and half an apple beside it, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ovos Mexidos com Cogumelos e Queijo",
 "hook": "Cremoso e reconfortante, o café salgado que sustenta com sabor de comida de verdade.",
 "tempo": "9 min", "rende": "1 porção", "kcal_base": 300,
 "ings": ["2 ovos", "1 punhado de cogumelos fatiados", "1 colher de sopa de queijo ralado",
          "1 colher de chá de azeite", "sal, pimenta e cebolinha a gosto"],
 "passos": [
   "Fatie os cogumelos. Aqueça o azeite numa frigideira em fogo médio-alto e doure os cogumelos por 3 a 4 minutos.",
   "Bata os ovos com sal e pimenta.",
   "Abaixe o fogo, despeje os ovos sobre os cogumelos e deixe 30 segundos parado.",
   "Empurre delicadamente do fundo para o centro com a espátula, formando ovos cremosos.",
   "Antes de terminar de cozinhar, junte o queijo ralado e mexa. Desligue com os ovos ainda úmidos e finalize com cebolinha."],
 "porcoes8": ["1 ovo + 1 clara · cogumelos · queijo",
              "2 ovos · cogumelos · queijo",
              "2 ovos · cogumelos · queijo · ½ fatia de pão",
              "2 ovos · cogumelos · queijo · 1 fatia de pão",
              "3 ovos · cogumelos · queijo · 1 fatia de pão",
              "3 ovos · cogumelos · queijo · 2 fatias de pão",
              "3 ovos · cogumelos · 2 col. queijo · 2 fatias de pão",
              "4 ovos · cogumelos · 2 col. queijo · 2 fatias de pão"],
 "dica": "Os cogumelos dão um sabor umami que faz a refeição parecer mais rica sem gordura extra. Com ovos e um toque de queijo, é um café cremoso e proteico — bem mais saciante que um pão com manteiga na correria.",
 "prompt": "Square ultra-realistic overhead food photograph of creamy scrambled eggs with sautéed mushrooms and melted cheese on a white plate, sprinkled with chives, on a light wooden table, soft natural light, savory and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Panqueca de Aveia com Mirtilos",
 "hook": "Os mirtilos estouram quentinhos na massa — doce natural, sem açúcar adicionado.",
 "tempo": "12 min", "rende": "1 porção", "kcal_base": 320,
 "ings": ["40 g de aveia em flocos", "1 ovo", "½ banana amassada", "1 punhado de mirtilos",
          "1 pitada de fermento em pó", "canela a gosto", "spray de óleo"],
 "passos": [
   "Numa tigela, misture a aveia, o ovo, a banana amassada, o fermento e a canela.",
   "Deixe descansar 3 minutos para a massa firmar.",
   "Junte metade dos mirtilos à massa, delicadamente, para não esmagar.",
   "Aqueça a frigideira que não gruda em fogo médio-baixo, borrife óleo e faça panquecas pequenas.",
   "Deixe 2 a 3 minutos de cada lado, virando quando aparecerem bolhinhas.",
   "Sirva com o restante dos mirtilos frescos por cima."],
 "porcoes8": ["30 g aveia · 1 ovo · ½ banana · mirtilos",
              "40 g aveia · 1 ovo · ½ banana · mirtilos",
              "45 g aveia · 1 ovo · ½ banana · mirtilos",
              "50 g aveia · 1 ovo · 1 banana · mirtilos",
              "50 g aveia · 2 ovos · 1 banana · mirtilos",
              "55 g aveia · 2 ovos · 1 banana · mirtilos · castanhas",
              "60 g aveia · 2 ovos · 1 banana · mirtilos · castanhas",
              "70 g aveia · 2 ovos · 1 banana · mirtilos · 1 col. pasta de amendoim"],
 "dica": "Os mirtilos são ricos em antioxidantes e têm poucas calorias, adoçando a panqueca naturalmente. Como a base é aveia, ovo e banana — sem farinha branca nem açúcar — você tem um café que satisfaz a vontade de doce sem os ingredientes que engordam.",
 "prompt": "Square ultra-realistic overhead food photograph of a stack of oat pancakes studded with blueberries, topped with fresh blueberries and a dusting of cinnamon, on a white plate on a light wooden table, soft natural morning light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iogurte com Chia, Mel e Kiwi",
 "hook": "Refrescante e cheio de fibra, o café que solta o intestino e sacia ao mesmo tempo.",
 "tempo": "4 min", "rende": "1 porção", "kcal_base": 290,
 "ings": ["1 pote de iogurte grego natural (≈ 170 g)", "1 colher de sopa de sementes de chia",
          "1 kiwi em rodelas", "1 colher de chá de mel", "hortelã (opcional)"],
 "passos": [
   "Numa taça, misture o iogurte com a chia e deixe descansar 5 minutos — a chia incha levemente e engrossa o iogurte.",
   "Descasque o kiwi e corte em rodelas.",
   "Distribua as rodelas de kiwi sobre o iogurte.",
   "Finalize com o fio de mel e, se quiser, folhinhas de hortelã.",
   "Sirva gelado."],
 "porcoes8": ["120 g iogurte · 1 col. chia · kiwi",
              "170 g iogurte · 1 col. chia · kiwi · mel",
              "170 g iogurte · 1 col. chia · kiwi · mel",
              "200 g iogurte · 1 col. chia · kiwi · 2 col. aveia",
              "200 g iogurte · 1,5 col. chia · kiwi · 2 col. aveia",
              "250 g iogurte · 1,5 col. chia · kiwi · 3 col. aveia",
              "250 g iogurte · 2 col. chia · kiwi · 3 col. aveia · castanhas",
              "300 g iogurte · 2 col. chia · kiwi · 4 col. aveia · castanhas"],
 "dica": "A chia e o kiwi juntos são ricos em fibra, que ajuda o intestino a funcionar e prolonga a saciedade. O iogurte grego entra com proteína, e uma colher de chá de mel adoça sem exagero — um café leve que ainda cuida da digestão.",
 "prompt": "Square ultra-realistic overhead food photograph of Greek yogurt with chia seeds topped with fresh kiwi slices and a drizzle of honey, garnished with mint, in a glass bowl on a marble surface, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Torrada Integral com Cottage e Tomate",
 "hook": "Fresca e salgada, com proteína no queijo e quase nenhuma caloria no tomate.",
 "tempo": "6 min", "rende": "1 porção", "kcal_base": 250,
 "ings": ["1 fatia de pão integral", "3 colheres de sopa de queijo cottage", "1 tomate em rodelas",
          "orégano, sal, pimenta e azeite a gosto", "folhas de manjericão (opcional)"],
 "passos": [
   "Torre a fatia de pão até ficar firme e crocante.",
   "Espalhe o cottage sobre a torrada, cobrindo toda a superfície.",
   "Coloque as rodelas de tomate por cima.",
   "Tempere com uma pitada de sal, pimenta, orégano e um fio de azeite.",
   "Finalize com folhas de manjericão, se tiver. Sirva na hora."],
 "porcoes8": ["½ fatia de pão · 2 col. cottage · tomate",
              "1 fatia de pão · 3 col. cottage · tomate",
              "1 fatia de pão · 3 col. cottage · tomate · 1 ovo cozido",
              "1 fatia de pão · 4 col. cottage · tomate · 1 ovo",
              "1 fatia de pão · 4 col. cottage · tomate · 2 ovos",
              "2 fatias de pão · 4 col. cottage · tomate · 1 ovo",
              "2 fatias de pão · 5 col. cottage · tomate · 2 ovos",
              "2 fatias de pão · 6 col. cottage · tomate · 2 ovos"],
 "dica": "O queijo cottage é magro e rico em proteína, mata a fome com poucas calorias. Sobre pão integral com tomate, vira uma bruschetta saudável — salgada, fresca e muito mais leve que um pão com requeijão gorduroso.",
 "prompt": "Square ultra-realistic overhead food photograph of wholegrain toast topped with cottage cheese and fresh tomato slices, sprinkled with oregano and basil leaves, drizzled with olive oil, on a light wooden board, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tigela de Aveia com Maçã Assada e Canela",
 "hook": "O cheiro de maçã assada com canela transforma a aveia comum num conforto de dia frio.",
 "tempo": "15 min", "rende": "1 porção", "kcal_base": 340,
 "ings": ["40 g de aveia em flocos", "200 ml de leite (ou bebida vegetal)", "1 maçã em cubos",
          "canela em pau ou em pó", "1 colher de chá de mel (opcional)", "1 colher de sopa de nozes (opcional)"],
 "passos": [
   "Corte a maçã em cubos, com casca. Numa frigideira que não gruda, doure os cubos em fogo médio com bastante canela por 5 a 7 minutos, mexendo, até caramelizarem (ficarem macios e dourados no próprio açúcar da fruta).",
   "Enquanto isso, cozinhe a aveia com o leite numa panela, mexendo, por 4 a 5 minutos, até engrossar.",
   "Despeje a aveia numa tigela.",
   "Cubra com a maçã assada quentinha.",
   "Se quiser, finalize com o fio de mel e as nozes picadas. Sirva quente."],
 "porcoes8": ["30 g aveia · 180 ml leite · ½ maçã",
              "40 g aveia · 200 ml leite · 1 maçã",
              "45 g aveia · 200 ml leite · 1 maçã · mel",
              "50 g aveia · 220 ml leite · 1 maçã · nozes",
              "50 g aveia · 220 ml leite · 1 maçã · nozes",
              "55 g aveia · 250 ml leite · 1 maçã · nozes",
              "60 g aveia · 250 ml leite · 1 maçã · nozes",
              "70 g aveia · 300 ml leite · 1 maçã · nozes · mel"],
 "dica": "Assar a maçã libera a doçura natural dela e realça a canela, então você não precisa de açúcar. É um café que reconforta como uma sobremesa quente, mas com fibra da fruta e da aveia que seguram a fome por horas.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm bowl of oatmeal topped with caramelized baked apple cubes, chopped walnuts and a cinnamon stick, on a light wooden table, soft natural morning light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
