# -*- coding: utf-8 -*-
"""30 receitas de CAFÉ DA MANHÃ (001-030). FRANCÊS.

Tradução literal de `receitas_cafe.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "tu" (o equivalente do "du" alemão), medidas caseiras em
c. à s. / c. à c. / pincée / poignée / tranche, e a xícara convertida em PESO
(a cozinha francesa pesa, não usa "tasse" como medida).
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/001-030,
sem texto na imagem), e prompt duplicado é prompt que diverge.
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 300/370/420/470 · 450/510/560/620
"""

RECEITAS = [
{
 "nome": "Pancakes à la banane et à l'avoine",
 "hook": "Trois ingrédients que tu as déjà chez toi, prêts en 10 minutes — et qui te tiennent jusqu'au déjeuner.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 325,
 "ings": ["1 banane bien mûre", "40 g de flocons d'avoine (environ 4 c. à s.)", "1 œuf",
          "1 pincée de cannelle", "1 pincée de levure chimique (facultatif, ils seront plus moelleux)",
          "un filet d'huile ou de l'huile en spray pour la poêle"],
 "passos": [
   "Épluche la banane et mets-la dans une assiette creuse. Écrase-la bien à la fourchette jusqu'à obtenir une purée lisse, sans gros morceaux.",
   "Ajoute l'œuf et mélange jusqu'à ce que tout soit bien homogène.",
   "Ajoute les flocons d'avoine, la cannelle et la levure. Mélange et laisse reposer la pâte 3 minutes — l'avoine absorbe l'humidité et la pâte se raffermit, ce qui facilite le retournement ensuite.",
   "Fais chauffer une poêle antiadhésive à feu moyen-doux et étale un filet d'huile (ou du spray).",
   "Dépose à la cuillère de petites portions de pâte, de la taille d'une demi-paume. Les petits pancakes se retournent bien plus facilement que les grands.",
   "Laisse cuire 2 à 3 minutes, jusqu'à ce que de petites bulles apparaissent en surface et que les bords se raffermissent. Retourne-les délicatement et fais dorer l'autre face 1 à 2 minutes.",
   "Sers-les chauds. Si tu veux, ajoute des rondelles de banane, une poignée de fruits rouges ou 1 c. à c. de miel."],
 "porcoes8": ["¾ banane · 30 g de flocons d'avoine · 1 œuf",
              "1 banane · 40 g de flocons d'avoine · 1 œuf · 1 poignée de fruits rouges",
              "1 banane · 45 g de flocons d'avoine · 1 œuf · 1 c. à c. de beurre de cacahuète",
              "1 banane · 50 g de flocons d'avoine · 1 œuf · 1 c. à s. de beurre de cacahuète",
              "1 banane · 50 g de flocons d'avoine · 2 œufs · 1 c. à c. de beurre de cacahuète",
              "1 grosse banane · 55 g d'avoine · 2 œufs · 1 c. à s. de beurre de cacahuète",
              "1 grosse banane · 60 g d'avoine · 2 œufs · 1 c. à s. de beurre de cacahuète · fruits",
              "1 grosse banane · 70 g d'avoine · 2 œufs · 1,5 c. à s. de beurre de cacahuète"],
 "dica": "L'avoine est riche en fibres, qui ralentissent la digestion et tiennent au corps pendant des heures — c'est exactement ce qui évite la faim de milieu de matinée qui te pousse à grignoter. La banane apporte une douceur naturelle sans sucre ajouté, et l'œuf apporte des protéines pour préserver le muscle pendant que tu perds de la graisse.",
},
{
 "nome": "Œufs brouillés aux épinards et pain complet",
 "hook": "Le petit-déjeuner classique qui remplit l'assiette de protéines et de fibres en moins de 10 minutes.",
 "tempo": "8 min", "rende": "1 portion", "kcal_base": 340,
 "ings": ["2 œufs", "1 grosse poignée de jeunes pousses d'épinards", "1 tranche de pain complet",
          "1 c. à c. d'huile d'olive", "sel et poivre au goût", "1 petite tomate (facultatif)"],
 "passos": [
   "Lave les épinards et égoutte-les bien. Si les feuilles sont grandes, coupe-les en deux.",
   "Casse les œufs dans un bol, assaisonne avec du sel et du poivre et bats-les légèrement à la fourchette.",
   "Fais chauffer l'huile d'olive dans une poêle antiadhésive à feu moyen. Ajoute les épinards et remue 1 minute, juste le temps que les feuilles retombent.",
   "Baisse le feu, verse les œufs battus sur les épinards et laisse 30 secondes sans remuer.",
   "Avec une spatule, pousse doucement les œufs du bord vers le centre, jusqu'à ce qu'ils soient crémeux et encore un peu humides. Retire du feu avant qu'ils ne sèchent trop.",
   "Fais griller la tranche de pain complet. Sers les œufs dessus ou à côté, avec des rondelles de tomate si tu veux."],
 "porcoes8": ["1 œuf + 1 blanc · ½ tranche de pain · épinards à volonté",
              "2 œufs · 1 tranche de pain · épinards à volonté",
              "2 œufs · 1 tranche de pain · un filet d'huile d'olive en plus",
              "2 œufs + 1 blanc · 1 tranche de pain · 1 c. à c. de fromage râpé",
              "3 œufs · 1 tranche de pain · 1 c. à c. d'huile d'olive",
              "3 œufs · 2 tranches de pain · épinards à volonté",
              "3 œufs · 2 tranches de pain · 1 c. à s. de fromage râpé",
              "4 œufs · 2 tranches de pain · 1 c. à s. de fromage râpé"],
 "dica": "Les œufs sont une protéine complète et très rassasiante — ceux qui mangent des œufs au petit-déjeuner ont moins faim tout au long de la journée. Les épinards ajoutent du volume et des fibres pour presque aucune calorie, tu remplis donc l'assiette et l'estomac sans faire exploser les calories.",
},
{
 "nome": "Yaourt grec aux fruits rouges et à l'avoine",
 "hook": "Monté en couches, sans rien cuire — des protéines et des fibres dans un joli verre, en 3 minutes.",
 "tempo": "3 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["1 pot de yaourt grec nature sans sucre (environ 170 g)", "1 poignée de fruits rouges (fraises, myrtilles ou framboises)",
          "3 c. à s. de flocons d'avoine", "1 c. à c. de miel (facultatif)", "cannelle au goût"],
 "passos": [
   "Si tu prends des fraises, lave-les et coupe-les en petits morceaux. Les autres fruits peuvent rester entiers.",
   "Dans un verre ou une coupe, mets la moitié du yaourt au fond.",
   "Répartis la moitié des fruits et la moitié des flocons d'avoine par-dessus.",
   "Recommence : le reste du yaourt, puis les fruits et l'avoine restants.",
   "Termine par une pincée de cannelle et, si tu veux, le filet de miel. Sers tout de suite, tant que l'avoine est encore croquante."],
 "porcoes8": ["120 g de yaourt · fruits rouges · 2 c. à s. d'avoine",
              "170 g de yaourt · fruits rouges · 3 c. à s. d'avoine",
              "170 g de yaourt · fruits rouges · 3 c. à s. d'avoine · 1 c. à c. de miel",
              "200 g de yaourt · fruits rouges · 4 c. à s. d'avoine · 1 c. à c. de miel",
              "200 g de yaourt · fruits rouges · 4 c. à s. d'avoine · 1 c. à s. de noix",
              "250 g de yaourt · fruits rouges · 4 c. à s. d'avoine · 1 c. à s. de noix",
              "250 g de yaourt · fruits rouges · 5 c. à s. d'avoine · 1 c. à s. de noix",
              "300 g de yaourt · fruits rouges · 6 c. à s. d'avoine · 1 c. à s. de noix"],
 "dica": "Le yaourt grec contient presque deux fois plus de protéines que le yaourt classique, ce qui prolonge la satiété. Sans sucre ajouté, la douceur vient des fruits — et l'avoine apporte des fibres et du croquant, ce qui transforme un en-cas rapide en un vrai repas qui tient au corps.",
},
{
 "nome": "Omelette aux blancs d'œufs, tomate et fromage blanc",
 "hook": "Légère, moelleuse et pleine de protéines — le petit-déjeuner de ceux qui veulent maigrir sans avoir faim.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 250,
 "ings": ["3 blancs d'œufs + 1 œuf entier", "1 petite tomate en dés", "2 c. à s. de fromage blanc",
          "ciboulette ou persil ciselé", "sel et poivre au goût", "huile en spray"],
 "passos": [
   "Coupe la tomate en petits dés et tamponne-la avec du papier absorbant, pour que l'omelette ne soit pas trop humide.",
   "Dans un bol, mets les blancs, l'œuf entier, du sel et du poivre. Bats à la fourchette pendant 30 secondes, jusqu'à ce que ça mousse légèrement.",
   "Fais chauffer une poêle antiadhésive à feu moyen et vaporise un peu d'huile. Répartis les dés de tomate au fond pendant 1 minute.",
   "Verse les œufs battus par-dessus et incline la poêle pour bien les répartir.",
   "Quand les bords sont pris (au bout de 1 à 2 minutes), répartis le fromage blanc sur une moitié de l'omelette.",
   "Avec la spatule, replie l'omelette en deux sur le fromage blanc. Laisse encore 1 minute et sers avec les herbes par-dessus."],
 "porcoes8": ["2 blancs + 1 œuf · 1 c. à s. de fromage blanc",
              "3 blancs + 1 œuf · 2 c. à s. de fromage blanc",
              "3 blancs + 1 œuf · 2 c. à s. de fromage blanc · ½ tranche de pain",
              "3 blancs + 1 œuf · 3 c. à s. de fromage blanc · 1 tranche de pain",
              "3 blancs + 2 œufs · 2 c. à s. de fromage blanc · 1 tranche de pain",
              "4 blancs + 2 œufs · 3 c. à s. de fromage blanc · 1 tranche de pain",
              "4 blancs + 2 œufs · 3 c. à s. de fromage blanc · 2 tranches de pain",
              "5 blancs + 2 œufs · 4 c. à s. de fromage blanc · 2 tranches de pain"],
 "dica": "Les blancs d'œufs sont presque de la protéine pure, avec très peu de graisses et de calories — parfaits pour augmenter les protéines du petit-déjeuner sans l'alourdir. Le fromage blanc apporte du crémeux et lui aussi beaucoup de protéines, et la tomate donne du goût et du volume pour presque aucune calorie.",
},
{
 "nome": "Avoine du lendemain à la pomme et à la cannelle",
 "hook": "Tu la prépares le soir et le matin elle t'attend prête au réfrigérateur — zéro précipitation, zéro casserole.",
 "tempo": "5 min + réfrigérateur", "rende": "1 portion", "kcal_base": 350,
 "ings": ["40 g de flocons d'avoine", "150 ml de lait (ou boisson végétale)", "½ pomme en petits dés",
          "1 c. à s. de yaourt nature", "cannelle au goût", "1 c. à c. de miel (facultatif)"],
 "passos": [
   "Dans un bocal avec couvercle, mélange les flocons d'avoine, le lait et le yaourt.",
   "Ajoute la moitié des dés de pomme et une bonne pincée de cannelle. Mélange bien.",
   "Ferme le bocal et mets-le au réfrigérateur pendant au moins 4 heures, ou toute la nuit.",
   "Le matin, l'avoine sera crémeuse et moelleuse. Mélange à nouveau.",
   "Recouvre avec le reste de pomme fraîche et encore un peu de cannelle. Si tu veux, ajoute le filet de miel. Mange froid, directement dans le bocal."],
 "porcoes8": ["30 g d'avoine · 120 ml de lait · ½ pomme",
              "40 g d'avoine · 150 ml de lait · ½ pomme",
              "45 g d'avoine · 150 ml de lait · ½ pomme · 1 c. à c. de miel",
              "50 g d'avoine · 180 ml de lait · 1 pomme · 1 c. à c. de miel",
              "50 g d'avoine · 180 ml de lait · 1 pomme · 1 c. à s. de noix",
              "55 g d'avoine · 200 ml de lait · 1 pomme · 1 c. à s. de noix",
              "60 g d'avoine · 220 ml de lait · 1 pomme · 1 c. à s. de noix",
              "70 g d'avoine · 250 ml de lait · 1 pomme · 1,5 c. à s. de noix"],
 "dica": "Faire tremper l'avoine ne change rien aux calories, mais rend les fibres plus faciles à digérer et le repas plus crémeux et plus rassasiant. Comme tout est déjà prêt au réfrigérateur, tu ne sautes pas le petit-déjeuner dans la précipitation — et sauter un repas est justement ce qui pousse beaucoup de gens à trop manger en fin de journée.",
},
{
 "nome": "Tartine d'avocat à l'œuf",
 "hook": "Crémeuse, salée et vraiment rassasiante — prête en 8 minutes.",
 "tempo": "8 min", "rende": "1 portion", "kcal_base": 340,
 "ings": ["1 tranche de pain complet", "½ avocat mûr (ou ¼ d'un gros avocat)", "1 œuf",
          "le jus de ½ citron", "sel, poivre et piment en flocons au goût", "huile en spray"],
 "passos": [
   "Fais griller la tranche de pain complet jusqu'à ce qu'elle soit ferme et dorée.",
   "Dans un petit bol, écrase l'avocat à la fourchette, ajoute le jus de citron, du sel et du poivre. Mélange jusqu'à obtenir une crème.",
   "Fais chauffer une poêle antiadhésive, vaporise un peu d'huile et cuis l'œuf à feu moyen comme tu préfères (au plat avec le jaune coulant ou brouillé).",
   "Étale la crème d'avocat sur la tartine.",
   "Pose l'œuf par-dessus et termine par une pincée de piment en flocons. Sers immédiatement."],
 "porcoes8": ["½ tranche de pain · ¼ avocat · 1 œuf",
              "1 tranche de pain · ½ avocat · 1 œuf",
              "1 tranche de pain · ½ avocat · 1 œuf · salade verte",
              "1 tranche de pain · ½ avocat · 2 œufs",
              "1 tranche de pain · ½ avocat · 2 œufs · salade verte",
              "2 tranches de pain · ½ avocat · 2 œufs",
              "2 tranches de pain · 1 petit avocat · 2 œufs",
              "2 tranches de pain · 1 petit avocat · 3 œufs"],
 "dica": "L'avocat contient de bonnes graisses, qui rassasient longtemps et rendent le repas crémeux sans beurre. Avec l'œuf et le pain complet, tu as de bonnes graisses, des protéines et des fibres sur la même tartine — la combinaison qui tient la faim à distance pendant des heures.",
},
{
 "nome": "Porridge à la banane et au beurre de cacahuète",
 "hook": "Chaud et réconfortant, le petit-déjeuner qui a un goût de dessert mais qui travaille pour toi.",
 "tempo": "8 min", "rende": "1 portion", "kcal_base": 380,
 "ings": ["40 g de flocons d'avoine", "200 ml de lait (ou boisson végétale)", "½ banane écrasée",
          "1 c. à c. de beurre de cacahuète", "cannelle au goût", "½ banane en rondelles pour garnir"],
 "passos": [
   "Dans une petite casserole, mets les flocons d'avoine, le lait et la banane écrasée.",
   "Fais chauffer à feu moyen-doux en remuant sans arrêt avec une cuillère pour que rien n'attache au fond.",
   "Au bout de 4 à 5 minutes, le mélange épaissit et devient crémeux. Si tu le veux plus liquide, ajoute un peu de lait.",
   "Retire du feu, ajoute la cannelle et mélange.",
   "Verse dans un bol, garnis avec les rondelles de banane et ajoute le beurre de cacahuète par-dessus. Sers chaud."],
 "porcoes8": ["30 g d'avoine · 180 ml de lait · ½ banane · sans beurre de cacahuète",
              "40 g d'avoine · 200 ml de lait · 1 banane · 1 c. à c. de beurre de cacahuète",
              "45 g d'avoine · 200 ml de lait · 1 banane · 1 c. à c. de beurre de cacahuète",
              "50 g d'avoine · 220 ml de lait · 1 banane · 1 c. à s. de beurre de cacahuète",
              "50 g d'avoine · 220 ml de lait · 1 banane · 1 c. à s. de beurre de cacahuète",
              "55 g d'avoine · 250 ml de lait · 1 banane · 1 c. à s. de beurre de cacahuète",
              "60 g d'avoine · 250 ml de lait · 1 banane · 1,5 c. à s. de beurre de cacahuète",
              "70 g d'avoine · 300 ml de lait · 1 banane · 2 c. à s. de beurre de cacahuète"],
 "dica": "L'avoine cuite forme un gel dans l'estomac qui retarde la faim. La banane sucre sans sucre ajouté et redonne de l'énergie, et le beurre de cacahuète apporte de bonnes graisses et des protéines — attention seulement à la quantité, car il est calorique : une cuillère suffit déjà.",
},
{
 "nome": "Smoothie bowl banane et fruits rouges",
 "hook": "Épais à la cuillère, glacé et coloré — on dirait une glace, mais il travaille pour ta minceur.",
 "tempo": "6 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["1 banane congelée en rondelles", "1 poignée de fruits rouges congelés",
          "3 c. à s. de yaourt nature", "50 ml de lait (ou boisson végétale)",
          "2 c. à s. de flocons d'avoine et des fruits frais pour garnir"],
 "passos": [
   "Utilise la banane déjà congelée (coupe-la en rondelles la veille et mets-la au congélateur) — c'est ce qui rend le smoothie épais sans glaçons.",
   "Dans le mixeur, mets la banane, les fruits rouges congelés, le yaourt et le lait.",
   "Mixe à pleine puissance en t'arrêtant pour remuer à la cuillère quand ça bloque. N'ajoute du lait qu'une cuillère à la fois, le minimum nécessaire. La texture doit être épaisse, comme une glace.",
   "Verse dans un bol.",
   "Garnis avec l'avoine et les fruits frais en belles rangées. Mange tout de suite à la cuillère, avant que ça ne fonde."],
 "porcoes8": ["1 banane · fruits · 2 c. à s. de yaourt · 1 c. à s. d'avoine",
              "1 banane · fruits · 3 c. à s. de yaourt · 2 c. à s. d'avoine",
              "1 banane · fruits · 3 c. à s. de yaourt · 2 c. à s. d'avoine · graines",
              "1 banane · fruits · 4 c. à s. de yaourt · 3 c. à s. d'avoine",
              "1 banane · fruits · 4 c. à s. de yaourt · 3 c. à s. d'avoine · 1 c. à s. de noix",
              "1 grosse banane · fruits · 5 c. à s. de yaourt · 3 c. à s. d'avoine · noix",
              "1 grosse banane · fruits · 5 c. à s. de yaourt · 4 c. à s. d'avoine · noix",
              "2 bananes · fruits · 6 c. à s. de yaourt · 4 c. à s. d'avoine · noix"],
 "dica": "Congeler les fruits donne la texture d'une glace sans sucre ni crème. Le yaourt ajoute des protéines, et manger à la cuillère, lentement, permet au cerveau d'enregistrer la satiété — bien différent d'un smoothie avalé à la paille en quelques secondes.",
},
{
 "nome": "Œufs durs à l'avocat et à la tomate",
 "hook": "Sans poêle, sans désordre — des protéines et de bonnes graisses dans une assiette montée en quelques minutes.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["2 œufs", "½ avocat", "1 tomate", "le jus de ½ citron", "sel, poivre et huile d'olive au goût",
          "salade verte au goût"],
 "passos": [
   "Mets les œufs dans une casserole, couvre-les d'eau froide et porte à ébullition. À partir de l'ébullition, compte 8 à 9 minutes pour un jaune ferme.",
   "Pendant ce temps, coupe l'avocat et la tomate en tranches et dispose-les dans l'assiette sur un lit de salade verte.",
   "Égoutte les œufs et passe-les sous l'eau froide 1 minute — ils s'écalent plus facilement.",
   "Écale les œufs, coupe-les en deux et mets-les dans l'assiette.",
   "Arrose le tout de jus de citron et d'un filet d'huile d'olive, assaisonne avec du sel et du poivre et sers."],
 "porcoes8": ["1 œuf · ¼ avocat · tomate",
              "2 œufs · ½ avocat · tomate",
              "2 œufs · ½ avocat · tomate · ½ tranche de pain",
              "2 œufs · ½ avocat · tomate · 1 tranche de pain",
              "3 œufs · ½ avocat · tomate · 1 tranche de pain",
              "3 œufs · ½ avocat · tomate · 2 tranches de pain",
              "3 œufs · 1 petit avocat · tomate · 2 tranches de pain",
              "4 œufs · 1 petit avocat · tomate · 2 tranches de pain"],
 "dica": "L'œuf dur est la protéine la plus pratique qui soit : tu peux en cuire plusieurs d'un coup et les garder au réfrigérateur. Avec de l'avocat et de la tomate, tu montes un petit-déjeuner complet en bonnes graisses et en fibres sans allumer le feu le matin.",
},
{
 "nome": "Pancakes protéinés à l'avoine et aux blancs d'œufs",
 "hook": "Le pancake des jours d'entraînement : plus de protéines, même simplicité.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["40 g de flocons d'avoine", "3 blancs d'œufs (ou 2 blancs + 1 œuf)", "½ banane écrasée",
          "1 pincée de levure chimique", "cannelle au goût", "huile en spray"],
 "passos": [
   "Si tu préfères une pâte plus fine, mixe les flocons d'avoine jusqu'à obtenir une farine. Si tu l'aimes rustique, garde-les entiers.",
   "Dans un bol, mélange l'avoine, les blancs d'œufs, la banane écrasée, la levure et la cannelle jusqu'à ce que tout soit bien homogène.",
   "Laisse reposer 3 minutes pour que l'avoine s'hydrate.",
   "Fais chauffer la poêle antiadhésive à feu moyen-doux et vaporise un peu d'huile.",
   "Fais de petits pancakes. Laisse 2 minutes de chaque côté, en retournant quand de petites bulles apparaissent.",
   "Sers avec des fruits frais par-dessus. Évite les sirops sucrés — la banane sucre déjà."],
 "porcoes8": ["2 blancs · 30 g d'avoine · ½ banane",
              "3 blancs · 40 g d'avoine · ½ banane",
              "3 blancs · 45 g d'avoine · ½ banane · fruits",
              "2 blancs + 1 œuf · 50 g d'avoine · 1 banane",
              "3 blancs + 1 œuf · 50 g d'avoine · 1 banane",
              "3 blancs + 1 œuf · 55 g d'avoine · 1 banane · fruits",
              "4 blancs + 1 œuf · 60 g d'avoine · 1 banane · fruits",
              "4 blancs + 2 œufs · 70 g d'avoine · 1 banane · fruits"],
 "dica": "Remplacer une partie des œufs par des blancs augmente les protéines et réduit les graisses — bien pour qui cherche à se dessiner. Les protéines sont aussi le nutriment le plus rassasiant, donc ce pancake tient la faim à distance avec moins de calories que la version sucrée classique.",
},
{
 "nome": "Pudding de chia aux fruits",
 "hook": "Tu mélanges en 2 minutes, le réfrigérateur fait le reste, et tu te réveilles avec un dessert sain.",
 "tempo": "5 min + réfrigérateur", "rende": "1 portion", "kcal_base": 280,
 "ings": ["3 c. à s. de graines de chia", "200 ml de lait (ou boisson végétale)",
          "½ c. à c. d'arôme vanille (facultatif)", "fruits en dés au goût pour garnir",
          "1 c. à c. de miel (facultatif)"],
 "passos": [
   "Dans un bocal avec couvercle, mets les graines de chia, le lait et la vanille. Mélange bien pendant 30 secondes.",
   "Attends 5 minutes et mélange à nouveau — ce deuxième mélange défait les grumeaux qui se forment et c'est le secret d'un pudding lisse.",
   "Ferme le bocal et mets-le au réfrigérateur pendant au moins 4 heures, ou d'un jour à l'autre.",
   "Le chia absorbe le liquide et forme un pudding à la texture gélifiée.",
   "Avant de servir, mélange, garnis de fruits en dés et, si tu veux, ajoute le filet de miel."],
 "porcoes8": ["2 c. à s. de chia · 150 ml de lait · fruits",
              "3 c. à s. de chia · 200 ml de lait · fruits",
              "3 c. à s. de chia · 200 ml de lait · fruits · 1 c. à c. de miel",
              "3 c. à s. de chia · 220 ml de lait · fruits · 1 c. à s. de granola",
              "4 c. à s. de chia · 220 ml de lait · fruits · 1 c. à s. de granola",
              "4 c. à s. de chia · 250 ml de lait · fruits · 2 c. à s. de granola",
              "4 c. à s. de chia · 250 ml de lait · fruits · 2 c. à s. de granola · noix",
              "5 c. à s. de chia · 300 ml de lait · fruits · 2 c. à s. de granola · noix"],
 "dica": "Le chia absorbe plusieurs fois son propre poids en liquide et gonfle dans l'estomac, ce qui donne une sensation de satiété durable. Il est en plus riche en fibres et en oméga-3 — l'un des ingrédients les plus rassasiants par calorie qui existent.",
},
{
 "nome": "Muffins aux œufs et aux légumes",
 "hook": "Tu en cuis une fournée et tu as un petit-déjeuner prêt toute la semaine — il suffit de réchauffer et de manger.",
 "tempo": "25 min", "rende": "6 muffins (2 par portion)", "kcal_base": 220,
 "ings": ["6 œufs", "½ poivron en dés", "1 poignée d'épinards ciselés", "2 c. à s. de fromage râpé",
          "sel et poivre au goût", "un peu d'huile (ou du spray) pour que ça n'attache pas"],
 "passos": [
   "Préchauffe le four à 180 °C et étale un peu d'huile (ou du spray) dans le moule à muffins, pour que les œufs n'attachent pas.",
   "Coupe finement le poivron et les épinards en petits morceaux.",
   "Dans un bol, bats les œufs avec du sel et du poivre. Ajoute les légumes et le fromage et mélange.",
   "Répartis le mélange dans les 6 empreintes, en remplissant chacune aux trois quarts environ.",
   "Enfourne 18 à 20 minutes, jusqu'à ce qu'ils soient pris et légèrement dorés. Un cure-dent planté au centre doit ressortir propre.",
   "Laisse tiédir avant de démouler. Ils se gardent 4 jours au réfrigérateur et se réchauffent au moment de manger."],
 "porcoes8": ["1 muffin + salade verte",
              "2 muffins",
              "2 muffins · ½ tranche de pain",
              "2 muffins · 1 tranche de pain",
              "3 muffins · 1 tranche de pain",
              "3 muffins · 2 tranches de pain",
              "3 muffins · 2 tranches de pain · ¼ avocat",
              "4 muffins · 2 tranches de pain · ¼ avocat"],
 "dica": "Avoir de la nourriture prête est ce qui empêche la mauvaise décision quand la faim arrive le matin. Ces muffins sont des protéines et des légumes en portion contrôlée — tu peux les congeler et avoir toujours sous la main un petit-déjeuner qui tient au corps, sans improviser avec ce qu'il ne faudrait pas.",
},
{
 "nome": "Tartine de ricotta, fraises et miel",
 "hook": "Sucrée et crémeuse comme une petite gourmandise, mais avec des protéines et sans sucre lourd.",
 "tempo": "6 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["1 tranche de pain complet", "3 c. à s. de ricotta", "4 fraises en tranches",
          "1 c. à c. de miel", "zeste de citron et menthe (facultatif)"],
 "passos": [
   "Fais griller la tranche de pain jusqu'à ce qu'elle soit ferme.",
   "Dans un bol, écrase la ricotta à la fourchette jusqu'à ce qu'elle soit crémeuse. Si elle est sèche, ajoute un peu de lait.",
   "Étale la ricotta sur la tartine en couvrant toute la surface.",
   "Répartis les tranches de fraise par-dessus.",
   "Termine par le filet de miel et, si tu veux, un peu de zeste de citron et quelques feuilles de menthe. Sers tout de suite."],
 "porcoes8": ["½ tranche de pain · 2 c. à s. de ricotta · fraises",
              "1 tranche de pain · 3 c. à s. de ricotta · fraises · 1 c. à c. de miel",
              "1 tranche de pain · 3 c. à s. de ricotta · fraises · miel",
              "1 tranche de pain · 4 c. à s. de ricotta · fraises · miel · noix",
              "1 tranche de pain · 4 c. à s. de ricotta · fraises · 1 œuf dur",
              "2 tranches de pain · 4 c. à s. de ricotta · fraises · miel",
              "2 tranches de pain · 5 c. à s. de ricotta · fraises · noix",
              "2 tranches de pain · 6 c. à s. de ricotta · fraises · noix · 1 œuf"],
 "dica": "La ricotta est un fromage maigre, crémeux et riche en protéines — elle calme l'envie de sucré sans la crème calorique des pâtes à tartiner industrielles. La fraise apporte de la douceur et de la fraîcheur, et une cuillère à café de miel sucre assez sans transformer le petit-déjeuner en bombe de sucre.",
},
{
 "nome": "Avoine chaude au cacao et à la banane",
 "hook": "Le goût du chocolat au petit-déjeuner, sans sucre et sans culpabilité.",
 "tempo": "8 min", "rende": "1 portion", "kcal_base": 350,
 "ings": ["40 g de flocons d'avoine", "200 ml de lait (ou boisson végétale)", "1 c. à s. de cacao en poudre 100 %",
          "1 banane", "cannelle au goût", "édulcorant ou 1 c. à c. de miel (facultatif)"],
 "passos": [
   "Dans une petite casserole, mélange les flocons d'avoine, le lait et le cacao en poudre avant d'allumer le feu — ainsi le cacao se dissout sans grumeaux.",
   "Fais chauffer à feu moyen-doux en remuant sans arrêt.",
   "Écrase la moitié de la banane et ajoute-la dans la casserole ; garde l'autre moitié en rondelles.",
   "Fais cuire 4 à 5 minutes, jusqu'à ce que ce soit épais et crémeux.",
   "Goûte et ajuste la douceur avec de l'édulcorant ou une cuillère à café de miel, si besoin.",
   "Sers dans un bol avec les rondelles de banane et une pincée de cannelle par-dessus."],
 "porcoes8": ["30 g d'avoine · 180 ml de lait · 1 c. à s. de cacao · ½ banane",
              "40 g d'avoine · 200 ml de lait · 1 c. à s. de cacao · 1 banane",
              "45 g d'avoine · 200 ml de lait · 1 c. à s. de cacao · 1 banane",
              "50 g d'avoine · 220 ml de lait · 1 c. à s. de cacao · 1 banane · noix",
              "50 g d'avoine · 220 ml de lait · cacao · 1 banane · 1 c. à c. de beurre de cacahuète",
              "55 g d'avoine · 250 ml de lait · cacao · 1 banane · 1 c. à s. de beurre de cacahuète",
              "60 g d'avoine · 250 ml de lait · cacao · 1 banane · beurre de cacahuète",
              "70 g d'avoine · 300 ml de lait · cacao · 1 banane · beurre de cacahuète"],
 "dica": "Le cacao 100 % donne le goût du chocolat sans le sucre du chocolat en poudre du commerce — et il apporte en plus des antioxydants. Calmer l'envie de sucré dès le petit-déjeuner évite l'assaut sur la tablette de chocolat plus tard, et c'est là que beaucoup de régimes déraillent.",
},
{
 "nome": "Omelette aux champignons et aux épinards",
 "hook": "Terreuse et savoureuse, elle remplit l'assiette de nutriments pour très peu de calories.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 260,
 "ings": ["2 œufs", "1 poignée de champignons émincés", "1 poignée d'épinards",
          "1 c. à c. d'huile d'olive", "sel, poivre et ail haché au goût"],
 "passos": [
   "Émince les champignons et lave les épinards.",
   "Fais chauffer l'huile d'olive dans une poêle antiadhésive à feu moyen-vif. Fais revenir les champignons dans un peu d'huile 3 à 4 minutes, sans trop remuer, jusqu'à ce qu'ils dorent et rendent leur eau.",
   "Ajoute l'ail et les épinards et remue 1 minute, juste le temps que les feuilles retombent. Assaisonne avec du sel et du poivre.",
   "Bats les œufs dans un bol et verse-les sur les légumes. Baisse le feu.",
   "Laisse la base prendre 1 à 2 minutes, replie l'omelette en deux et sers."],
 "porcoes8": ["1 œuf + 1 blanc · légumes à volonté",
              "2 œufs · légumes à volonté",
              "2 œufs · légumes · ½ tranche de pain",
              "2 œufs · légumes · 1 tranche de pain",
              "3 œufs · légumes · 1 tranche de pain",
              "3 œufs · légumes · 2 tranches de pain",
              "3 œufs · légumes · 2 tranches de pain · fromage",
              "4 œufs · légumes · 2 tranches de pain · fromage"],
 "dica": "Les champignons et les épinards apportent du volume, du goût et des nutriments pour presque aucune calorie — tu remplis l'assiette et l'estomac. Les œufs complètent avec des protéines rassasiantes, ce qui donne un repas copieux qui rentre pourtant largement dans le régime.",
},
{
 "nome": "Yaourt au granola maison et aux myrtilles",
 "hook": "Le granola, tu le fais sans sucre à la maison et tu l'utilises toute la semaine — croustillant et comme il faut.",
 "tempo": "5 min (+ granola prêt)", "rende": "1 portion", "kcal_base": 330,
 "ings": ["1 pot de yaourt grec nature (environ 170 g)", "3 c. à s. de granola maison sans sucre",
          "1 poignée de myrtilles", "cannelle au goût",
          "(granola : avoine + noix concassées + cannelle, cuits à 160 °C pendant 15 min)"],
 "passos": [
   "Pour le granola maison : mélange des flocons d'avoine avec des noix concassées et de la cannelle, étale sur une plaque et enfourne à 160 °C pendant 12 à 15 minutes, en remuant à mi-cuisson. Laisse refroidir pour que ce soit croustillant et garde dans un bocal.",
   "Dans une coupe, mets le yaourt.",
   "Recouvre avec le granola maison.",
   "Répartis les myrtilles par-dessus et termine par une pincée de cannelle.",
   "Sers tout de suite, pour que le granola ne ramollisse pas."],
 "porcoes8": ["120 g de yaourt · 2 c. à s. de granola · myrtilles",
              "170 g de yaourt · 3 c. à s. de granola · myrtilles",
              "170 g de yaourt · 3 c. à s. de granola · myrtilles",
              "200 g de yaourt · 4 c. à s. de granola · myrtilles",
              "200 g de yaourt · 4 c. à s. de granola · myrtilles",
              "250 g de yaourt · 4 c. à s. de granola · myrtilles",
              "250 g de yaourt · 5 c. à s. de granola · myrtilles",
              "300 g de yaourt · 6 c. à s. de granola · myrtilles"],
 "dica": "Le granola du commerce est souvent plein de sucre et d'huile — le faire maison supprime ça et tu contrôles ce qui rentre dedans. Avec un yaourt grec riche en protéines et des myrtilles, ça devient un petit-déjeuner croustillant et rassasiant sans les sucres cachés des versions industrielles.",
},
{
 "nome": "Wrap complet aux œufs brouillés et aux légumes",
 "hook": "Tu roules et tu emportes — le petit-déjeuner de ceux qui partent en courant mais ne renoncent pas à bien manger.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 340,
 "ings": ["1 tortilla complète", "2 œufs", "½ tomate en dés", "1 poignée d'épinards",
          "1 c. à s. de fromage râpé", "sel, poivre et huile en spray"],
 "passos": [
   "Coupe la tomate en dés et réserve. Lave les épinards.",
   "Bats les œufs avec du sel et du poivre. Fais chauffer la poêle avec un peu d'huile en spray à feu moyen.",
   "Ajoute les épinards et la tomate pendant 1 minute, puis verse les œufs et remue jusqu'à obtenir des œufs brouillés crémeux.",
   "Réchauffe la tortilla 20 secondes de chaque côté dans une poêle sèche, juste pour l'assouplir.",
   "Mets les œufs au centre de la tortilla, parsème de fromage et replie les côtés vers l'intérieur.",
   "Roule bien serré comme un burrito et coupe en deux. Tu peux le manger à la main, en route."],
 "porcoes8": ["1 wrap · 1 œuf + 1 blanc · légumes",
              "1 wrap · 2 œufs · légumes · fromage",
              "1 wrap · 2 œufs · légumes · fromage",
              "1 wrap · 2 œufs · légumes · ¼ avocat",
              "1 wrap · 3 œufs · légumes · fromage",
              "1 grand wrap · 3 œufs · légumes · fromage · ¼ avocat",
              "1 grand wrap · 3 œufs · légumes · fromage · ½ avocat",
              "1 grand wrap · 4 œufs · légumes · fromage · ½ avocat"],
 "dica": "Pouvoir emporter le petit-déjeuner à la main est ce qui évite de sauter le repas dans une journée chargée. Garni d'œufs et de légumes, ce wrap apporte des protéines et des fibres dans un format pratique — bien mieux que de régler la faim à la boulangerie avec une viennoiserie.",
},
{
 "nome": "Pancakes à la pomme et à la cannelle",
 "hook": "Ça sent la tarte aux pommes et ça rentre dans le régime — le réconfort du sucré du matin sans saboter la journée.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["40 g de flocons d'avoine", "1 œuf", "½ pomme râpée", "cannelle au goût",
          "1 pincée de levure chimique", "huile en spray", "½ pomme en fines tranches pour garnir"],
 "passos": [
   "Râpe la moitié de la pomme avec une grosse râpe et garde l'autre moitié en tranches.",
   "Dans un bol, mélange l'avoine, l'œuf, la pomme râpée, la cannelle et la levure jusqu'à ce que tout soit bien homogène.",
   "Laisse reposer 3 minutes pour que l'avoine s'hydrate.",
   "Fais chauffer la poêle antiadhésive à feu moyen-doux et vaporise un peu d'huile.",
   "Fais de petits pancakes, 2 à 3 minutes de chaque côté.",
   "Pendant ce temps, fais dorer les tranches de pomme dans la même poêle avec une pincée de cannelle. Sers-les sur les pancakes."],
 "porcoes8": ["30 g d'avoine · 1 œuf · ½ pomme",
              "40 g d'avoine · 1 œuf · ½ pomme",
              "45 g d'avoine · 1 œuf · ½ pomme · noix",
              "50 g d'avoine · 1 œuf · 1 pomme · noix",
              "50 g d'avoine · 2 œufs · 1 pomme",
              "55 g d'avoine · 2 œufs · 1 pomme · noix",
              "60 g d'avoine · 2 œufs · 1 pomme · noix",
              "70 g d'avoine · 2 œufs · 1 pomme · 1 c. à s. de beurre de cacahuète"],
 "dica": "La pomme apporte de la douceur et des fibres, et la cannelle relève le goût sans une pincée de sucre — des études suggèrent même qu'elle aide à contrôler l'appétit. C'est la version qui calme l'envie de tarte sucrée sans les glucides raffinés qui font grossir.",
},
{
 "nome": "Pain complet au beurre de cacahuète et à la banane",
 "hook": "Le classique de 5 minutes qui réunit énergie, bonnes graisses et douceur naturelle.",
 "tempo": "5 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["1 tranche de pain complet", "1 c. à s. de beurre de cacahuète", "1 banane en rondelles",
          "cannelle au goût", "1 pincée de graines de chia (facultatif)"],
 "passos": [
   "Fais griller la tranche de pain jusqu'à ce qu'elle soit ferme.",
   "Étale le beurre de cacahuète sur la tartine encore chaude — il fond un peu et s'étale plus facilement.",
   "Recouvre avec les rondelles de banane.",
   "Saupoudre de cannelle et, si tu veux, de graines de chia par-dessus.",
   "Sers immédiatement. Pour emporter, coupe en deux et referme comme un sandwich."],
 "porcoes8": ["½ tranche de pain · 1 c. à c. de beurre de cacahuète · ½ banane",
              "1 tranche de pain · 1 c. à s. de beurre de cacahuète · 1 banane",
              "1 tranche de pain · 1 c. à s. de beurre de cacahuète · 1 banane · chia",
              "1 tranche de pain · 1,5 c. à s. de beurre de cacahuète · 1 banane",
              "1 tranche de pain · 1,5 c. à s. de beurre de cacahuète · 1 banane · 1 œuf dur",
              "2 tranches de pain · 2 c. à s. de beurre de cacahuète · 1 banane",
              "2 tranches de pain · 2 c. à s. de beurre de cacahuète · 1 banane · 1 œuf",
              "2 tranches de pain · 2,5 c. à s. de beurre de cacahuète · 1 banane · 1 œuf"],
 "dica": "Le beurre de cacahuète contient de bonnes graisses et des protéines, qui rassasient longtemps — mais il est calorique, donc la mesure compte : une cuillère à soupe suffit. Sur du pain complet avec de la banane, tu as une énergie stable pour toute la matinée, sans le pic et la chute du sucre.",
},
{
 "nome": "Œufs pochés aux asperges et pain grillé",
 "hook": "Élégant comme au restaurant, assez simple pour un jour ordinaire.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["2 œufs", "1 poignée d'asperges", "1 tranche de pain complet", "1 c. à c. de vinaigre (pour l'eau)",
          "sel, poivre et huile d'olive au goût"],
 "passos": [
   "Lave les asperges et coupe la base dure. Fais-les cuire 3 minutes dans de l'eau bouillante salée, égoutte et réserve.",
   "Dans une casserole, fais chauffer de l'eau jusqu'à frémissement (petites bulles, sans gros bouillons) et ajoute le vinaigre.",
   "Casse chaque œuf dans une tasse. Fais un tourbillon dans l'eau avec une cuillère et fais glisser l'œuf tout doucement au centre — le mouvement enveloppe le jaune dans le blanc.",
   "Laisse cuire 3 minutes pour un jaune coulant. Retire avec une écumoire et pose sur du papier absorbant.",
   "Fais griller le pain. Monte avec les asperges dessous, les œufs pochés par-dessus, un filet d'huile d'olive, du sel et du poivre."],
 "porcoes8": ["1 œuf · asperges · ½ tranche de pain",
              "2 œufs · asperges · 1 tranche de pain",
              "2 œufs · asperges · 1 tranche de pain · fromage",
              "2 œufs · asperges · 1 tranche de pain · ¼ avocat",
              "3 œufs · asperges · 1 tranche de pain",
              "3 œufs · asperges · 2 tranches de pain",
              "3 œufs · asperges · 2 tranches de pain · ¼ avocat",
              "4 œufs · asperges · 2 tranches de pain · ¼ avocat"],
 "dica": "L'œuf poché cuit uniquement dans l'eau, sans huile, ce qui garde les calories basses. Les asperges sont riches en fibres et en eau et n'ont pratiquement pas de calories — un petit-déjeuner qui a l'air raffiné et qui joue quand même en faveur de la balance.",
},
{
 "nome": "Avoine à la poire et aux noix",
 "hook": "Crémeuse, légèrement sucrée par la poire et avec le croquant des noix.",
 "tempo": "8 min", "rende": "1 portion", "kcal_base": 350,
 "ings": ["40 g de flocons d'avoine", "200 ml de lait (ou boisson végétale)", "½ poire en dés",
          "3 noix concassées", "cannelle au goût", "1 c. à c. de miel (facultatif)"],
 "passos": [
   "Dans une petite casserole, mets l'avoine et le lait et fais chauffer à feu moyen-doux en remuant.",
   "Au bout de 3 minutes, ajoute la moitié des dés de poire et poursuis la cuisson 2 minutes, jusqu'à épaississement.",
   "Retire du feu et ajoute la cannelle.",
   "Sers dans un bol et garnis avec le reste de poire fraîche et les noix concassées.",
   "Si besoin, sucre avec une cuillère à café de miel."],
 "porcoes8": ["30 g d'avoine · 180 ml de lait · ½ poire · 2 noix",
              "40 g d'avoine · 200 ml de lait · ½ poire · 3 noix",
              "45 g d'avoine · 200 ml de lait · ½ poire · 3 noix",
              "50 g d'avoine · 220 ml de lait · 1 poire · 3 noix",
              "50 g d'avoine · 220 ml de lait · 1 poire · 4 noix",
              "55 g d'avoine · 250 ml de lait · 1 poire · 4 noix",
              "60 g d'avoine · 250 ml de lait · 1 poire · 5 noix",
              "70 g d'avoine · 300 ml de lait · 1 poire · 5 noix"],
 "dica": "La poire est riche en fibres et sucre naturellement, ce qui dispense de sucre ajouté. Les noix apportent de bonnes graisses qui rassasient et du croquant — mais elles sont caloriques, donc quelques unités suffisent à jouer leur rôle sans faire exploser les calories du petit-déjeuner.",
},
{
 "nome": "Yaourt grec à la pêche et aux amandes",
 "hook": "Crémeux et légèrement sucré par la pêche, avec le croquant des amandes — prêt en 3 minutes.",
 "tempo": "3 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["1 pot de yaourt grec nature (environ 170 g)", "1 pêche en tranches (ou ½ boîte sans sirop)",
          "1 c. à s. d'amandes effilées", "cannelle au goût", "1 c. à c. de miel (facultatif)"],
 "passos": [
   "Si la pêche est fraîche, lave-la et coupe-la en fines tranches. Si elle est en conserve, choisis-la sans sirop sucré et égoutte-la bien.",
   "Mets le yaourt dans une coupe.",
   "Répartis les tranches de pêche par-dessus.",
   "Parsème d'amandes effilées et de cannelle.",
   "Si tu veux plus de douceur, ajoute une cuillère à café de miel. Sers tout de suite."],
 "porcoes8": ["120 g de yaourt · pêche · ½ c. à s. d'amandes",
              "170 g de yaourt · pêche · 1 c. à s. d'amandes",
              "170 g de yaourt · pêche · 1 c. à s. d'amandes · miel",
              "200 g de yaourt · pêche · 1 c. à s. d'amandes · 2 c. à s. d'avoine",
              "200 g de yaourt · pêche · 1,5 c. à s. d'amandes · 2 c. à s. d'avoine",
              "250 g de yaourt · pêche · 1,5 c. à s. d'amandes · 3 c. à s. d'avoine",
              "250 g de yaourt · pêche · 2 c. à s. d'amandes · 3 c. à s. d'avoine",
              "300 g de yaourt · pêche · 2 c. à s. d'amandes · 4 c. à s. d'avoine"],
 "dica": "La pêche est sucrée et peu calorique, ce qui satisfait l'envie de sucre en douceur. Avec le yaourt grec protéiné et une poignée d'amandes, tu combines protéines et bonnes graisses pour une satiété qui traverse toute la matinée.",
},
{
 "nome": "Sandwich complet à la dinde et au fromage",
 "hook": "Salé, pratique et protéiné — le petit-déjeuner rapide pour ceux qui n'aiment pas le sucré le matin.",
 "tempo": "6 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["2 tranches de pain complet", "2 tranches de blanc de dinde", "1 tranche de fromage",
          "feuilles de salade", "rondelles de tomate", "1 c. à c. de moutarde ou de fromage à tartiner allégé"],
 "passos": [
   "Si tu l'aimes chaud, réchauffe les tranches de pain 1 minute de chaque côté dans une poêle sèche.",
   "Étale la moutarde ou le fromage à tartiner allégé sur une tranche de pain.",
   "Monte les couches : dinde, fromage, tomate et salade.",
   "Referme avec l'autre tranche de pain et presse légèrement.",
   "Coupe en diagonale et sers. Pour emporter, enveloppe dans du papier cuisson."],
 "porcoes8": ["1 tranche de pain (ouvert) · 1 tranche de dinde · fromage",
              "2 tranches de pain · 2 tranches de dinde · fromage",
              "2 tranches de pain · 2 tranches de dinde · fromage",
              "2 tranches de pain · 3 tranches de dinde · fromage · ¼ avocat",
              "2 tranches de pain · 3 tranches de dinde · fromage · 1 œuf dur",
              "2 tranches de pain · 4 tranches de dinde · fromage · 1 œuf",
              "3 tranches de pain · 4 tranches de dinde · fromage · 1 œuf",
              "3 tranches de pain · 5 tranches de dinde · 2 fromages · 1 œuf"],
 "dica": "Le blanc de dinde est l'une des viandes les plus maigres qui soient, presque de la protéine pure, sans la graisse de la charcuterie comme le salami ou la mortadelle. Sur du pain complet avec de la salade, c'est un petit-déjeuner salé qui tient au corps avec peu de calories et sans sucre.",
},
{
 "nome": "Omelette aux légumes",
 "hook": "Colorée et pleine de goût, elle utilise ce que tu as dans le réfrigérateur et remplit l'assiette.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 260,
 "ings": ["2 œufs", "¼ de poivron en dés", "¼ d'oignon en dés", "½ tomate en dés",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût"],
 "passos": [
   "Coupe le poivron, l'oignon et la tomate en petits dés.",
   "Fais chauffer l'huile d'olive dans une poêle antiadhésive à feu moyen. Fais revenir l'oignon et le poivron dans un peu d'huile, en remuant, 2 à 3 minutes, jusqu'à ce qu'ils soient tendres.",
   "Ajoute la tomate et poursuis 1 minute. Assaisonne avec du sel et du poivre.",
   "Bats les œufs et verse-les sur les légumes. Incline la poêle pour bien répartir.",
   "Quand la base est prise (au bout de 2 minutes), replie l'omelette en deux, laisse cuire encore 1 minute et sers avec les herbes."],
 "porcoes8": ["1 œuf + 1 blanc · légumes à volonté",
              "2 œufs · légumes à volonté",
              "2 œufs · légumes · ½ tranche de pain",
              "2 œufs · légumes · 1 tranche de pain",
              "3 œufs · légumes · 1 tranche de pain",
              "3 œufs · légumes · 2 tranches de pain",
              "3 œufs · légumes · 2 tranches de pain · fromage",
              "4 œufs · légumes · 2 tranches de pain · fromage"],
 "dica": "Garnir l'omelette de légumes augmente le volume et les fibres pour très peu de calories, tu manges donc une assiette copieuse sans culpabilité. C'est aussi une façon maligne de manger plus de légumes dès le matin, ce qui aide à atteindre ton objectif de fibres de la journée.",
},
{
 "nome": "Smoothie vert aux épinards, banane et pomme",
 "hook": "Vert, glacé et légèrement sucré — tu ne sens même pas les épinards, mais ton corps te remercie.",
 "tempo": "5 min", "rende": "1 portion", "kcal_base": 250,
 "ings": ["1 grosse poignée d'épinards", "½ banane", "½ pomme", "200 ml d'eau glacée (ou boisson végétale)",
          "1 c. à s. de flocons d'avoine", "le jus de ½ citron", "glaçons au goût"],
 "passos": [
   "Lave bien les épinards.",
   "Dans le mixeur, mets d'abord le liquide, puis les épinards — mixer les feuilles avec le liquide d'abord évite les morceaux.",
   "Mixe 30 secondes, jusqu'à ce que les épinards se défassent.",
   "Ajoute la banane, la pomme (sans les pépins), l'avoine, le jus de citron et les glaçons.",
   "Mixe à pleine puissance jusqu'à ce que ce soit lisse et bien homogène. Sers tout de suite, bien frais."],
 "porcoes8": ["épinards · ½ banane · ½ pomme · 1 c. à s. d'avoine",
              "épinards · ½ banane · ½ pomme · 1 c. à s. d'avoine",
              "épinards · 1 banane · ½ pomme · 2 c. à s. d'avoine",
              "épinards · 1 banane · ½ pomme · 2 c. à s. d'avoine · yaourt",
              "épinards · 1 banane · 1 pomme · 2 c. à s. d'avoine · yaourt",
              "épinards · 1 banane · 1 pomme · 3 c. à s. d'avoine · yaourt",
              "épinards · 1 banane · 1 pomme · 3 c. à s. d'avoine · yaourt · noix",
              "épinards · 1 banane · 1 pomme · 4 c. à s. d'avoine · yaourt · noix"],
 "dica": "Mixer les épinards avec des fruits est une façon indolore de manger des feuilles vertes le matin — le goût sucré de la banane et de la pomme masque le vert. C'est léger en calories et riche en eau et en fibres, idéal pour commencer la journée bien hydraté et rassasié.",
},
{
 "nome": "Œufs brouillés aux champignons et au fromage",
 "hook": "Crémeux et réconfortant, le petit-déjeuner salé qui tient au corps avec un goût de vraie cuisine.",
 "tempo": "9 min", "rende": "1 portion", "kcal_base": 300,
 "ings": ["2 œufs", "1 poignée de champignons émincés", "1 c. à s. de fromage râpé",
          "1 c. à c. d'huile d'olive", "sel, poivre et ciboulette au goût"],
 "passos": [
   "Émince les champignons. Fais chauffer l'huile d'olive dans une poêle à feu moyen-vif et fais dorer les champignons 3 à 4 minutes.",
   "Bats les œufs avec du sel et du poivre.",
   "Baisse le feu, verse les œufs sur les champignons et laisse 30 secondes sans y toucher.",
   "Pousse délicatement du bord vers le centre avec la spatule, pour former des œufs crémeux.",
   "Juste avant la fin de cuisson, ajoute le fromage râpé et mélange. Retire du feu tant que les œufs sont encore humides et termine par la ciboulette."],
 "porcoes8": ["1 œuf + 1 blanc · champignons · fromage",
              "2 œufs · champignons · fromage",
              "2 œufs · champignons · fromage · ½ tranche de pain",
              "2 œufs · champignons · fromage · 1 tranche de pain",
              "3 œufs · champignons · fromage · 1 tranche de pain",
              "3 œufs · champignons · fromage · 2 tranches de pain",
              "3 œufs · champignons · 2 c. à s. de fromage · 2 tranches de pain",
              "4 œufs · champignons · 2 c. à s. de fromage · 2 tranches de pain"],
 "dica": "Les champignons donnent un goût savoureux qui fait paraître le repas plus riche sans graisse supplémentaire. Avec des œufs et une touche de fromage, c'est un petit-déjeuner crémeux et protéiné — bien plus rassasiant qu'une tartine beurrée avalée à la va-vite.",
},
{
 "nome": "Pancakes à l'avoine et aux myrtilles",
 "hook": "Les myrtilles éclatent toutes chaudes dans la pâte — un sucré naturel, sans sucre ajouté.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 320,
 "ings": ["40 g de flocons d'avoine", "1 œuf", "½ banane écrasée", "1 poignée de myrtilles",
          "1 pincée de levure chimique", "cannelle au goût", "huile en spray"],
 "passos": [
   "Dans un bol, mélange l'avoine, l'œuf, la banane écrasée, la levure et la cannelle.",
   "Laisse reposer 3 minutes pour que la pâte se raffermisse.",
   "Incorpore délicatement la moitié des myrtilles à la pâte, pour ne pas les écraser.",
   "Fais chauffer la poêle antiadhésive à feu moyen-doux, vaporise un peu d'huile et fais de petits pancakes.",
   "Laisse 2 à 3 minutes de chaque côté, en retournant quand de petites bulles apparaissent.",
   "Sers avec le reste des myrtilles fraîches par-dessus."],
 "porcoes8": ["30 g d'avoine · 1 œuf · ½ banane · myrtilles",
              "40 g d'avoine · 1 œuf · ½ banane · myrtilles",
              "45 g d'avoine · 1 œuf · ½ banane · myrtilles",
              "50 g d'avoine · 1 œuf · 1 banane · myrtilles",
              "50 g d'avoine · 2 œufs · 1 banane · myrtilles",
              "55 g d'avoine · 2 œufs · 1 banane · myrtilles · noix",
              "60 g d'avoine · 2 œufs · 1 banane · myrtilles · noix",
              "70 g d'avoine · 2 œufs · 1 banane · myrtilles · 1 c. à s. de beurre de cacahuète"],
 "dica": "Les myrtilles sont riches en antioxydants et peu caloriques, elles sucrent le pancake naturellement. Comme la base est de l'avoine, un œuf et une banane — sans farine blanche ni sucre — tu as un petit-déjeuner qui satisfait l'envie de sucré sans les ingrédients qui font grossir.",
},
{
 "nome": "Yaourt au chia, miel et kiwi",
 "hook": "Rafraîchissant et plein de fibres, le petit-déjeuner qui réveille le transit et rassasie en même temps.",
 "tempo": "4 min", "rende": "1 portion", "kcal_base": 290,
 "ings": ["1 pot de yaourt grec nature (environ 170 g)", "1 c. à s. de graines de chia",
          "1 kiwi en rondelles", "1 c. à c. de miel", "menthe (facultatif)"],
 "passos": [
   "Dans une coupe, mélange le yaourt avec le chia et laisse reposer 5 minutes — le chia gonfle légèrement et épaissit le yaourt.",
   "Épluche le kiwi et coupe-le en rondelles.",
   "Répartis les rondelles de kiwi sur le yaourt.",
   "Termine par le filet de miel et, si tu veux, quelques feuilles de menthe.",
   "Sers frais."],
 "porcoes8": ["120 g de yaourt · 1 c. à s. de chia · kiwi",
              "170 g de yaourt · 1 c. à s. de chia · kiwi · miel",
              "170 g de yaourt · 1 c. à s. de chia · kiwi · miel",
              "200 g de yaourt · 1 c. à s. de chia · kiwi · 2 c. à s. d'avoine",
              "200 g de yaourt · 1,5 c. à s. de chia · kiwi · 2 c. à s. d'avoine",
              "250 g de yaourt · 1,5 c. à s. de chia · kiwi · 3 c. à s. d'avoine",
              "250 g de yaourt · 2 c. à s. de chia · kiwi · 3 c. à s. d'avoine · noix",
              "300 g de yaourt · 2 c. à s. de chia · kiwi · 4 c. à s. d'avoine · noix"],
 "dica": "Le chia et le kiwi ensemble sont riches en fibres, ce qui aide le transit à bien fonctionner et prolonge la satiété. Le yaourt grec apporte les protéines, et une cuillère à café de miel sucre sans excès — un petit-déjeuner léger qui prend aussi soin de la digestion.",
},
{
 "nome": "Tartine complète au fromage blanc et à la tomate",
 "hook": "Fraîche et salée, avec les protéines du fromage et presque aucune calorie dans la tomate.",
 "tempo": "6 min", "rende": "1 portion", "kcal_base": 250,
 "ings": ["1 tranche de pain complet", "3 c. à s. de fromage blanc", "1 tomate en rondelles",
          "origan, sel, poivre et huile d'olive au goût", "feuilles de basilic (facultatif)"],
 "passos": [
   "Fais griller la tranche de pain jusqu'à ce qu'elle soit ferme et croustillante.",
   "Étale le fromage blanc sur la tartine en couvrant toute la surface.",
   "Pose les rondelles de tomate par-dessus.",
   "Assaisonne avec une pincée de sel, du poivre, de l'origan et un filet d'huile d'olive.",
   "Termine par des feuilles de basilic, si tu en as. Sers tout de suite."],
 "porcoes8": ["½ tranche de pain · 2 c. à s. de fromage blanc · tomate",
              "1 tranche de pain · 3 c. à s. de fromage blanc · tomate",
              "1 tranche de pain · 3 c. à s. de fromage blanc · tomate · 1 œuf dur",
              "1 tranche de pain · 4 c. à s. de fromage blanc · tomate · 1 œuf",
              "1 tranche de pain · 4 c. à s. de fromage blanc · tomate · 2 œufs",
              "2 tranches de pain · 4 c. à s. de fromage blanc · tomate · 1 œuf",
              "2 tranches de pain · 5 c. à s. de fromage blanc · tomate · 2 œufs",
              "2 tranches de pain · 6 c. à s. de fromage blanc · tomate · 2 œufs"],
 "dica": "Le fromage blanc est maigre et riche en protéines, il calme la faim avec peu de calories. Sur du pain complet avec de la tomate, ça devient une bruschetta saine — salée, fraîche et bien plus légère qu'une tartine au fromage à tartiner gras.",
},
{
 "nome": "Bol d'avoine à la pomme rôtie et à la cannelle",
 "hook": "L'odeur de pomme rôtie à la cannelle transforme une simple avoine en réconfort de jour froid.",
 "tempo": "15 min", "rende": "1 portion", "kcal_base": 340,
 "ings": ["40 g de flocons d'avoine", "200 ml de lait (ou boisson végétale)", "1 pomme en dés",
          "cannelle en bâton ou en poudre", "1 c. à c. de miel (facultatif)", "1 c. à s. de noix (facultatif)"],
 "passos": [
   "Coupe la pomme en dés, avec la peau. Dans une poêle antiadhésive, fais dorer les dés à feu moyen avec beaucoup de cannelle 5 à 7 minutes, en remuant, jusqu'à ce qu'ils soient tendres et dorés dans leur propre sucre.",
   "Pendant ce temps, fais cuire l'avoine avec le lait dans une casserole, en remuant, 4 à 5 minutes, jusqu'à épaississement.",
   "Verse l'avoine dans un bol.",
   "Recouvre avec la pomme rôtie encore chaude.",
   "Si tu veux, termine par le filet de miel et les noix concassées. Sers chaud."],
 "porcoes8": ["30 g d'avoine · 180 ml de lait · ½ pomme",
              "40 g d'avoine · 200 ml de lait · 1 pomme",
              "45 g d'avoine · 200 ml de lait · 1 pomme · miel",
              "50 g d'avoine · 220 ml de lait · 1 pomme · noix",
              "50 g d'avoine · 220 ml de lait · 1 pomme · noix",
              "55 g d'avoine · 250 ml de lait · 1 pomme · noix",
              "60 g d'avoine · 250 ml de lait · 1 pomme · noix",
              "70 g d'avoine · 300 ml de lait · 1 pomme · noix · miel"],
 "dica": "Rôtir la pomme libère sa douceur naturelle et met la cannelle en valeur, tu n'as donc pas besoin de sucre. C'est un petit-déjeuner qui réconforte comme un dessert chaud, mais avec les fibres du fruit et de l'avoine qui tiennent la faim à distance pendant des heures.",
},
]
