# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). FRANCÊS. Todas FIT e SEM AÇÚCAR.

Tradução literal de `receitas_sobremesa.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/101-120).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 120/150/170/190 · 180/200/230/260 (porções pequenas de sobremesa)
"""

RECEITAS = [
{
 "nome": "Gâteau au chocolat sans sucre",
 "hook": "Moelleux, fondant et bien chocolaté — le gâteau qui calme l'envie de sucré sans une pincée de sucre, fait avec du vrai cacao.",
 "tempo": "40 min", "rende": "8 parts", "kcal_base": 150,
 "ings": ["3 œufs", "1 banane bien mûre écrasée", "4 c. à s. de cacao en poudre 100 % (sans sucre)",
          "5 c. à s. de flocons d'avoine mixés en farine (ou de la farine complète)",
          "édulcorant spécial cuisson au goût — ou 2 c. à s. de miel",
          "120 ml de lait (ou boisson végétale)", "1 c. à s. d'huile", "1 c. à c. de levure chimique"],
 "passos": [
   "Préchauffe le four à 180 °C. Étale un filet d'huile dans un petit moule et saupoudre un peu de cacao, pour que le gâteau n'attache pas.",
   "Dans un bol, bats les œufs avec l'édulcorant (ou le miel) à la fourchette ou au fouet pendant 1 minute, jusqu'à ce que ce soit mousseux.",
   "Ajoute la banane écrasée, le lait et l'huile et mélange bien.",
   "Ajoute le cacao en poudre et l'avoine mixée (ou la farine) et remue jusqu'à obtenir une pâte lisse, sans zones sèches.",
   "En dernier, ajoute la levure et mélange délicatement, juste pour l'incorporer (trop remuer après la levure rend le gâteau lourd).",
   "Verse dans le moule et enfourne 30 minutes. Pour savoir s'il est cuit, plante un cure-dent au centre : s'il ressort propre, le gâteau est prêt.",
   "Laisse tiédir avant de démouler et de couper. Il est excellent avec des fruits rouges par-dessus."],
 "porcoes8": ["1 part fine",
              "1 part",
              "1 part · fruits rouges",
              "1 part · 1 c. à s. de yaourt",
              "1 part",
              "1 part moyenne",
              "1 part · fruits rouges",
              "1 grande part · fruits"],
 "dica": "Le cacao pur donne tout le goût du chocolat sans le sucre et la graisse du chocolat en poudre du commerce. La banane sucre naturellement et garde le gâteau moelleux, l'avoine apporte des fibres et les œufs des protéines. C'est la preuve qu'on peut manger du gâteau au chocolat et continuer à maigrir, à condition de respecter la taille de la part.",
},
{
 "nome": "Mousse au chocolat à l'avocat",
 "hook": "Crémeuse comme une mousse classique, mais le secret c'est l'avocat — personne ne devine, et il n'y a ni crème ni sucre.",
 "tempo": "10 min + réfrigérateur", "rende": "2 verres", "kcal_base": 170,
 "ings": ["1 avocat mûr (ou ½ gros avocat)", "3 c. à s. de cacao en poudre 100 %",
          "édulcorant au goût — ou 2 c. à s. de miel", "3 c. à s. de lait (ou boisson végétale)",
          "1 pincée de cannelle", "1 pincée de sel", "copeaux de chocolat noir (70 %) pour décorer (facultatif)"],
 "passos": [
   "Coupe l'avocat en deux, retire le noyau et prélève la chair à la cuillère. N'utilise que la partie bien tendre et verte.",
   "Mets la chair d'avocat dans le mixeur ou le bol du mixeur plongeant, avec le cacao, l'édulcorant (ou le miel), le lait, la cannelle et le sel.",
   "Mixe à pleine puissance jusqu'à obtenir une crème lisse et brillante, sans morceaux. Si c'est trop épais, ajoute un peu de lait.",
   "Goûte et ajuste la douceur à ton goût.",
   "Répartis dans deux verres et mets au réfrigérateur au moins 30 minutes, pour que la mousse prenne et refroidisse. Sers avec des copeaux de chocolat par-dessus."],
 "porcoes8": ["½ petit verre",
              "1 petit verre",
              "1 verre",
              "1 verre · copeaux de chocolat",
              "1 verre",
              "1 verre moyen",
              "1 verre · copeaux de chocolat",
              "1 grand verre · copeaux"],
 "dica": "L'avocat donne le crémeux de la mousse avec de la bonne graisse à la place de la crème, et il rassasie bien. Le cacao pur apporte le goût du chocolat sans sucre. C'est un dessert riche et satisfaisant qui, en petite portion, rentre tranquillement dans le régime.",
},
{
 "nome": "Boules au chocolat sans sucre",
 "hook": "La petite gourmandise de fête en version sans sucre et sans lait concentré — roulée, chocolatée et juste de la bonne taille pour calmer l'envie.",
 "tempo": "20 min + réfrigérateur", "rende": "10 boules", "kcal_base": 130,
 "ings": ["6 dattes dénoyautées (ce fruit sec très sucré)", "3 c. à s. de cacao en poudre 100 %",
          "2 c. à s. de lait (ou boisson végétale)", "1 c. à s. de beurre de cacahuète",
          "du cacao en poudre en plus pour rouler", "1 pincée de sel"],
 "passos": [
   "Laisse tremper les dattes dans de l'eau tiède 10 minutes, pour qu'elles s'attendrissent. Égoutte.",
   "Dans le bol du mixeur plongeant ou au mixeur, mixe les dattes avec le cacao, le lait, le beurre de cacahuète et le sel, jusqu'à obtenir une pâte épaisse et bien homogène. Si besoin, arrête-toi et ramène la pâte au centre avec une cuillère.",
   "La pâte doit être assez ferme pour être roulée. Si elle est molle, mets-la au réfrigérateur 20 minutes.",
   "Avec les mains légèrement humides, prends de petites portions et roule des boules de la taille d'une noix.",
   "Roule chaque boule dans le cacao en poudre pour l'enrober. Garde-les au réfrigérateur et sers-les bien fraîches."],
 "porcoes8": ["1 boule",
              "1 à 2 boules",
              "2 boules",
              "2 boules",
              "2 boules",
              "2 à 3 boules",
              "3 boules",
              "3 boules"],
 "dica": "Les dattes remplacent le sucre et le lait concentré par une douceur naturelle et beaucoup de fibres, qui freinent l'envie de sucré. Le cacao pur donne le goût du chocolat et le beurre de cacahuète le crémeux. Une ou deux boules calment l'envie sans faire exploser les calories.",
},
{
 "nome": "Mug cake au chocolat",
 "hook": "Une envie de sucré le soir ? En trois minutes, au micro-ondes, tu as un petit gâteau chaud au chocolat rien que pour toi.",
 "tempo": "5 min", "rende": "1 tasse", "kcal_base": 190,
 "ings": ["1 œuf", "2 c. à s. de flocons d'avoine mixés en farine", "1 c. à s. de cacao en poudre 100 %",
          "édulcorant au goût — ou 1 c. à s. de miel", "2 c. à s. de lait",
          "½ c. à c. de levure chimique", "1 pincée de sel"],
 "passos": [
   "Dans une grande tasse allant au micro-ondes, casse l'œuf et bats-le à la fourchette.",
   "Ajoute l'avoine mixée, le cacao, l'édulcorant (ou le miel), le lait et le sel. Mélange bien, jusqu'à obtenir une pâte lisse, sans zones sèches sur les bords.",
   "En dernier, ajoute la levure et mélange délicatement.",
   "Mets la tasse au micro-ondes à pleine puissance pendant 1 minute 30 à 2 minutes. Le gâteau gonfle et prend ; s'il est encore humide au centre, remets 20 secondes.",
   "Attention, la tasse sort brûlante. Laisse tiédir 1 minute et mange directement dans la tasse. C'est excellent avec des fruits par-dessus."],
 "porcoes8": ["½ tasse",
              "1 petite tasse",
              "1 tasse",
              "1 tasse · fruits",
              "1 tasse",
              "1 tasse",
              "1 tasse · fruits",
              "1 tasse · fruits · 1 c. à s. de beurre de cacahuète"],
 "dica": "Fait sur le moment et dans la portion d'une tasse, ce petit gâteau contrôle naturellement la quantité que tu manges — il ne reste pas un gâteau entier à te tenter sur la table. Avec de l'avoine, un œuf et du cacao pur, il est sucré, chaud et réconfortant sans sucre, idéal pour l'envie du soir.",
},
{
 "nome": "Mousse de fraise au yaourt",
 "hook": "Rosée, veloutée et rafraîchissante — une mousse de fraise qui ne demande que trois ingrédients et aucun sucre.",
 "tempo": "10 min + réfrigérateur", "rende": "3 verres", "kcal_base": 120,
 "ings": ["300 g de fraises (fraîches ou surgelées)", "1 pot de yaourt nature sans sucre (environ 170 g)",
          "1 c. à s. de gélatine en poudre neutre", "édulcorant au goût — ou 1 c. à s. de miel",
          "3 c. à s. d'eau chaude", "fraises coupées pour décorer"],
 "passos": [
   "Lave les fraises et retire les petites feuilles vertes. Garde-en quelques-unes pour décorer.",
   "Dans une tasse, dissous la gélatine dans l'eau chaude, en remuant bien jusqu'à ce que ce soit transparent, sans petits grains. Laisse tiédir.",
   "Au mixeur, mixe les fraises avec le yaourt et l'édulcorant (ou le miel) jusqu'à obtenir une crème lisse et rosée.",
   "Le mixeur en marche à petite vitesse, ajoute la gélatine dissoute et mixe encore 30 secondes, juste pour mélanger.",
   "Répartis dans des verres et mets au réfrigérateur au moins 2 heures, jusqu'à ce que ça prenne. Sers avec des fraises coupées par-dessus."],
 "porcoes8": ["½ verre",
              "1 petit verre",
              "1 verre",
              "1 verre · fraises",
              "1 verre",
              "1 verre moyen",
              "1 verre · fraises",
              "1 grand verre · fraises"],
 "dica": "La fraise est sucrée et pleine de vitamine C pour très peu de calories, et le yaourt nature ajoute des protéines et du crémeux sans sucre. La gélatine donne la texture d'une mousse sans crème. Un dessert léger, joli et rafraîchissant qui satisfait l'envie de sucré.",
},
{
 "nome": "Glace crémeuse à la banane",
 "hook": "Une vraie glace, crémeuse et glacée, faite uniquement avec de la banane — sans sucre, sans lait, sans sorbetière.",
 "tempo": "5 min + congélateur", "rende": "2 portions", "kcal_base": 120,
 "ings": ["3 bananes mûres", "1 c. à s. de cacao en poudre 100 % OU 1 poignée de fruits rouges (facultatif, pour le goût)",
          "1 pincée de cannelle", "1 c. à c. de beurre de cacahuète (facultatif)"],
 "passos": [
   "Épluche les bananes, coupe-les en rondelles et mets-les dans un sac ou une boîte. Place au congélateur au moins 3 heures, jusqu'à ce qu'elles soient bien dures.",
   "Sors les rondelles congelées et mets-les dans un mixeur puissant ou dans le bol du mixeur plongeant.",
   "Mixe à pleine puissance. Au début, ça fait des petits morceaux ; continue de mixer (en t'arrêtant pour ramener la banane au centre) jusqu'à obtenir une crème lisse, comme une glace de sorbetière.",
   "Si tu veux du goût, ajoute le cacao ou les fruits rouges et mixe encore un peu.",
   "Sers tout de suite, bien crémeuse, avec une pincée de cannelle — ou remets au congélateur 1 heure pour qu'elle soit plus ferme, comme une glace en bac."],
 "porcoes8": ["½ portion",
              "1 petite portion",
              "1 portion",
              "1 portion · 1 c. à s. de beurre de cacahuète",
              "1 portion",
              "1 portion moyenne",
              "1 portion · fruits",
              "1 grande portion · fruits · beurre de cacahuète"],
 "dica": "Congelée et mixée, la banane libère son propre sucre naturel et devient une crème identique à une glace, sans sucre, lait ni crème. C'est sucré, glacé et satisfaisant, avec les fibres et le potassium du fruit — le dessert parfait pour les jours chauds, sans culpabilité.",
},
{
 "nome": "Flan léger au lait",
 "hook": "Le flan crémeux de toujours, avec son caramel doré — mais sans sucre et bien plus léger, fait avec du lait et des œufs.",
 "tempo": "50 min", "rende": "6 parts", "kcal_base": 130,
 "ings": ["3 œufs", "480 ml de lait écrémé (ou boisson végétale)", "édulcorant spécial cuisson au goût",
          "1 c. à c. d'arôme vanille", "édulcorant qui caramélise (facultatif, pour le caramel)",
          "eau chaude pour le bain-marie"],
 "passos": [
   "Préchauffe le four à 180 °C. Si tu veux un caramel, fais fondre un peu d'édulcorant adapté au caramel dans un petit moule et étale-le au fond (ou saute cette étape).",
   "Au mixeur, mixe les œufs, le lait, l'édulcorant et la vanille pendant 1 minute, jusqu'à ce que tout soit bien mélangé.",
   "Verse le mélange dans le moule.",
   "Place le moule dans un plat plus grand et remplis ce plat d'eau chaude jusqu'à mi-hauteur du moule (c'est le bain-marie : l'eau fait cuire le flan uniformément et le rend crémeux).",
   "Enfourne 40 minutes, jusqu'à ce qu'il soit pris mais tremble encore légèrement au centre. Laisse refroidir puis mets au réfrigérateur 3 heures avant de démouler."],
 "porcoes8": ["1 part fine",
              "1 part",
              "1 part",
              "1 part · fruits",
              "1 part",
              "1 part moyenne",
              "1 part · fruits",
              "1 grande part · fruits"],
 "dica": "En remplaçant le lait concentré et le sucre par du lait écrémé et de l'édulcorant, le flan garde son crémeux et son goût avec une fraction des calories. Les œufs et le lait apportent en plus des protéines. En petite part, c'est un dessert classique qui rentre dans le régime.",
},
{
 "nome": "Biscuits à l'avoine et à la banane",
 "hook": "Deux ingrédients, un bol et vingt minutes : de petits biscuits moelleux et sucrés, sans sucre et sans farine blanche.",
 "tempo": "20 min", "rende": "12 biscuits", "kcal_base": 110,
 "ings": ["2 bananes bien mûres", "135 g de flocons d'avoine", "1 pincée de cannelle",
          "1 c. à s. de raisins secs ou de morceaux de chocolat noir (70 %) (facultatif)", "1 pincée de sel"],
 "passos": [
   "Préchauffe le four à 180 °C. Recouvre une plaque de papier cuisson.",
   "Dans un bol, écrase bien les bananes à la fourchette, jusqu'à obtenir une purée sans gros morceaux.",
   "Ajoute l'avoine, la cannelle, le sel et, si tu veux, les raisins secs ou le chocolat concassé. Mélange jusqu'à obtenir une pâte collante.",
   "À la cuillère, dépose de petites portions sur la plaque et aplatis-les avec le dos de la cuillère, pour leur donner une forme de biscuit.",
   "Enfourne 12 à 15 minutes, jusqu'à ce que les bords soient dorés et fermes. Laisse refroidir sur la plaque (ils se raffermissent en refroidissant) et sers."],
 "porcoes8": ["1 biscuit",
              "2 biscuits",
              "2 biscuits",
              "2 biscuits · fruits",
              "2 biscuits",
              "3 biscuits",
              "3 biscuits",
              "3 à 4 biscuits"],
 "dica": "La banane mûre sucre et lie sans avoir besoin de sucre ni de farine blanche, et l'avoine apporte les fibres qui rassasient. Ce sont des biscuits naturels, excellents pour le goûter ou en dessert, qui calment l'envie de sucré en douceur — mais compte combien tu en manges, car il est facile d'exagérer.",
},
{
 "nome": "Pomme au four à la cannelle et aux noix",
 "hook": "La pomme devient tendre et parfumée à la cannelle, avec une garniture croquante aux noix — un dessert chaud qui réconforte comme une tarte, sans la pâte.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 130,
 "ings": ["2 pommes", "cannelle en poudre au goût", "1 c. à s. de noix concassées (ou d'autres fruits à coque)",
          "1 c. à s. de flocons d'avoine", "1 c. à c. de miel (facultatif)", "1 pincée de clou de girofle en poudre (facultatif)"],
 "passos": [
   "Préchauffe le four à 180 °C. Lave les pommes et, avec un couteau, retire le cœur au centre (la partie avec les pépins), en formant un trou, sans percer jusqu'au fond.",
   "Dans un petit bol, mélange les noix concassées, l'avoine, la cannelle et, si tu veux, le miel et le girofle.",
   "Garnis le trou de chaque pomme avec ce mélange, en tassant légèrement.",
   "Pose les pommes sur une plaque avec un doigt d'eau au fond (pour qu'elles ne se dessèchent pas) et saupoudre encore de cannelle par-dessus.",
   "Enfourne 25 à 30 minutes, jusqu'à ce que la pomme soit bien tendre (une fourchette entre facilement) et la garniture dorée. Sers chaud, nature ou avec une cuillère de yaourt nature."],
 "porcoes8": ["½ pomme",
              "1 pomme",
              "1 pomme",
              "1 pomme · 1 c. à s. de yaourt",
              "1 pomme",
              "1 pomme · noix en plus",
              "1 pomme · yaourt",
              "2 pommes · yaourt"],
 "dica": "Cuire la pomme au four concentre sa douceur naturelle, elle devient donc sucrée sans sucre. La cannelle relève le goût et aide à contrôler l'envie de sucré, et les noix apportent de bonnes graisses et du croquant. C'est le réconfort d'une tarte aux pommes avec une fraction des calories.",
},
{
 "nome": "Gelée de fruits maison",
 "hook": "Colorée, brillante et rafraîchissante, avec de vrais morceaux de fruits à l'intérieur — le dessert le plus léger qui soit.",
 "tempo": "10 min + réfrigérateur", "rende": "4 verres", "kcal_base": 70,
 "ings": ["1 c. à s. de gélatine en poudre neutre", "480 ml de jus de fruits sans sucre (orange, raisin ou fraise)",
          "120 ml d'eau", "150 g de fruits en dés (fraise, kiwi, mangue ou raisin)", "édulcorant au goût (facultatif)"],
 "passos": [
   "Dans une petite casserole, mets l'eau et saupoudre la gélatine par-dessus. Laisse reposer 2 minutes (la gélatine gonfle, c'est ce qu'on appelle la réhydratation).",
   "Chauffe à feu doux et remue 1 minute, juste le temps que la gélatine se dissolve complètement, sans bouillir. Retire du feu.",
   "Ajoute le jus de fruits (et l'édulcorant, si tu veux) et mélange bien.",
   "Mets les fruits en dés au fond de verres ou d'un plat et verse le liquide par-dessus.",
   "Mets au réfrigérateur au moins 4 heures, jusqu'à ce que ce soit ferme. Sers bien frais."],
 "porcoes8": ["½ verre",
              "1 petit verre",
              "1 verre",
              "1 verre · fruits en plus",
              "1 verre",
              "1 verre moyen",
              "1 verre · fruits",
              "1 grand verre · fruits"],
 "dica": "Faite avec du jus de fruits à la place de la poudre pleine de sucre et de colorants, la gelée maison n'a pratiquement aucune calorie et contient en plus de vrais morceaux de fruits. C'est le dessert idéal quand l'envie de quelque chose de sucré et de froid arrive, sans peser en rien sur le régime.",
},
{
 "nome": "Barres d'avoine aux fruits séchés",
 "hook": "La barre de céréales maison, moelleuse et sucrée, sans les sucres et les sirops des versions industrielles — parfaite pour le sac.",
 "tempo": "30 min", "rende": "8 barres", "kcal_base": 150,
 "ings": ["180 g de flocons d'avoine", "2 bananes mûres écrasées", "3 c. à s. de fruits séchés hachés (raisins secs, abricots secs ou dattes)",
          "2 c. à s. de noix ou d'amandes concassées", "1 c. à s. de miel (facultatif)", "1 pincée de cannelle et de sel"],
 "passos": [
   "Préchauffe le four à 180 °C. Recouvre un petit moule rectangulaire de papier cuisson.",
   "Dans un bol, écrase bien les bananes jusqu'à obtenir une purée.",
   "Ajoute l'avoine, les fruits séchés hachés, les noix, la cannelle, le sel et, si tu veux, le miel. Mélange jusqu'à obtenir une pâte collante et homogène.",
   "Verse la pâte dans le moule et tasse bien avec le dos d'une cuillère, en formant une couche ferme et régulière (plus c'est tassé, moins la barre s'effrite).",
   "Enfourne 20 minutes, jusqu'à ce que les bords dorent. Laisse refroidir complètement dans le moule avant de couper en barres (coupées chaudes, elles s'effritent)."],
 "porcoes8": ["1 barre",
              "1 barre",
              "1 barre",
              "1 barre · fruits",
              "1 barre",
              "1 à 2 barres",
              "2 barres",
              "2 barres"],
 "dica": "Les barres du supermarché contiennent souvent plus de sucre et de sirop qu'une confiserie. Faite maison avec de l'avoine, de la banane et des fruits séchés, la barre sucre naturellement et apporte des fibres et de l'énergie qui tiennent la faim. Excellente pour le goûter ou comme dessert pratique, mais mange-en une à la fois.",
},
{
 "nome": "Plaque de yaourt glacé aux fruits rouges",
 "hook": "Une plaque croquante de yaourt glacé parsemée de fruits, que tu casses en morceaux — jolie, amusante et sans sucre.",
 "tempo": "5 min + congélateur", "rende": "4 portions", "kcal_base": 100,
 "ings": ["1 grand pot de yaourt grec nature sans sucre (environ 350 g)", "140 g de fruits rouges (fraises, myrtilles, framboises)",
          "1 c. à s. de miel (facultatif)", "1 c. à s. de noix concassées (facultatif)", "copeaux de chocolat noir 70 % (facultatif)"],
 "passos": [
   "Recouvre une plaque ou un plat peu profond de papier cuisson.",
   "Dans un bol, mélange le yaourt grec avec le miel (si tu en mets), jusqu'à ce que ce soit bien lisse.",
   "Étale le yaourt sur le papier cuisson, en formant une couche d'environ un demi-doigt d'épaisseur.",
   "Parsème par-dessus les fruits rouges (coupe les fraises), les noix et les copeaux de chocolat, en répartissant sur toute la surface.",
   "Mets au congélateur 3 à 4 heures, jusqu'à ce que ce soit bien dur. Casse ou coupe en morceaux irréguliers et sers tout de suite (ça fond vite). Garde le reste au congélateur."],
 "porcoes8": ["1 petit morceau",
              "1 morceau",
              "1 à 2 morceaux",
              "2 morceaux",
              "2 morceaux",
              "2 morceaux",
              "2 à 3 morceaux",
              "3 morceaux"],
 "dica": "Le yaourt grec apporte des protéines et du crémeux sans sucre, et congelé il devient une petite gourmandise glacée et croquante. Les fruits rouges sucrent naturellement et remplissent le tout d'antioxydants. Un dessert rafraîchissant et léger, excellent pour l'été et pour l'envie de grignoter quelque chose de sucré.",
},
{
 "nome": "Truffes au chocolat allégées",
 "hook": "Petites, intenses et chocolatées — la truffe qui fond en bouche sans aucun sucre, pour les moments de grande envie.",
 "tempo": "20 min + réfrigérateur", "rende": "10 truffes", "kcal_base": 120,
 "ings": ["100 g de chocolat noir 70 % (ou plus fort)", "4 c. à s. de lait chaud (ou boisson végétale)",
          "2 c. à s. de noix de coco râpée sans sucre", "du cacao en poudre 100 % pour rouler", "1 pincée de sel"],
 "passos": [
   "Hache le chocolat noir en petits morceaux et mets-le dans un bol.",
   "Chauffe le lait jusqu'à frémissement et verse-le sur le chocolat. Attends 1 minute et remue jusqu'à ce que le chocolat soit complètement fondu et devienne une crème lisse et brillante (c'est la ganache).",
   "Ajoute la noix de coco râpée et le sel et mélange. Mets au réfrigérateur 1 heure, jusqu'à ce que le mélange soit assez ferme pour être roulé.",
   "Avec les mains, prends de petites portions et roule des boules de la taille d'une grosse olive.",
   "Roule chaque truffe dans le cacao en poudre pour l'enrober. Garde-les au réfrigérateur et sers-les fraîches."],
 "porcoes8": ["1 truffe",
              "1 truffe",
              "1 à 2 truffes",
              "2 truffes",
              "2 truffes",
              "2 truffes",
              "2 à 3 truffes",
              "3 truffes"],
 "dica": "Le chocolat à 70 % ou plus contient peu de sucre et beaucoup de cacao, riche en antioxydants. En petite truffe, il satisfait l'envie intense de chocolat avec bien moins de sucre qu'un bonbon classique. Une ou deux règlent le désir sans saboter le régime.",
},
{
 "nome": "Gâteau à la carotte avec glaçage au cacao",
 "hook": "Le gâteau à la carotte moelleux de l'enfance, avec un glaçage au chocolat — sans sucre, mais avec toute la tendresse et tout le goût.",
 "tempo": "45 min", "rende": "8 parts", "kcal_base": 160,
 "ings": ["2 carottes moyennes coupées", "3 œufs", "3 c. à s. d'huile", "édulcorant spécial cuisson au goût",
          "135 g de flocons d'avoine mixés en farine (ou de la farine complète)", "1 c. à c. de levure chimique",
          "Glaçage : 2 c. à s. de cacao en poudre 100 % + 2 c. à s. de lait + édulcorant au goût"],
 "passos": [
   "Préchauffe le four à 180 °C. Étale un filet d'huile dans un moule et saupoudre un peu de farine.",
   "Au mixeur, mixe les carottes coupées, les œufs, l'huile et l'édulcorant jusqu'à obtenir une crème lisse et orangée.",
   "Transvase dans un bol, ajoute l'avoine mixée (ou la farine) et mélange. En dernier, ajoute la levure et remue délicatement.",
   "Verse dans le moule et enfourne 30 minutes, jusqu'à ce qu'un cure-dent planté au centre ressorte propre.",
   "Prépare le glaçage : dans une petite casserole, mélange le cacao, le lait et l'édulcorant et chauffe à feu doux 2 minutes, en remuant, jusqu'à obtenir une crème brillante. Étale sur le gâteau encore tiède."],
 "porcoes8": ["1 part fine",
              "1 part",
              "1 part",
              "1 part · fruits",
              "1 part",
              "1 part moyenne",
              "1 part · fruits",
              "1 grande part"],
 "dica": "La carotte garde le gâteau moelleux et naturellement sucré, et apporte en plus de la vitamine A. En remplaçant le sucre par de l'édulcorant et la farine blanche par de l'avoine, le gâteau devient léger et plein de fibres. Le glaçage au cacao pur donne la touche chocolatée sans le sucre du glaçage traditionnel.",
},
{
 "nome": "Mousse au citron",
 "hook": "Juste ce qu'il faut d'acidité, crémeuse et bien fraîche — une mousse au citron rafraîchissante qui nettoie le palais et ne contient pas de sucre.",
 "tempo": "10 min + réfrigérateur", "rende": "3 verres", "kcal_base": 120,
 "ings": ["1 pot de yaourt nature sans sucre (environ 170 g)", "le jus de 2 citrons", "le zeste de 1 citron",
          "1 c. à s. de gélatine en poudre neutre", "3 c. à s. d'eau chaude",
          "édulcorant au goût — ou 2 c. à s. de miel"],
 "passos": [
   "Lave bien 1 citron et prélève le zeste, uniquement la partie jaune de la peau (la partie blanche est amère). Presse les 2 citrons pour en extraire le jus.",
   "Dans une tasse, dissous la gélatine dans l'eau chaude, en remuant jusqu'à ce que ce soit transparent. Laisse tiédir.",
   "Dans un bol, mélange le yaourt, le jus de citron, le zeste et l'édulcorant (ou le miel), jusqu'à obtenir une crème.",
   "Ajoute la gélatine dissoute et mélange bien et rapidement, pour éviter les petits grumeaux.",
   "Répartis dans des verres et mets au réfrigérateur au moins 2 heures, jusqu'à ce que ça prenne. Sers frais, avec encore un peu de zeste de citron par-dessus."],
 "porcoes8": ["½ verre",
              "1 petit verre",
              "1 verre",
              "1 verre · fruits",
              "1 verre",
              "1 verre moyen",
              "1 verre · fruits",
              "1 grand verre · fruits"],
 "dica": "Le citron apporte de la fraîcheur et un goût marqué qui trompe l'envie de sucré sans avoir besoin de beaucoup d'édulcorant. Le yaourt nature apporte des protéines et du crémeux, et la gélatine fait prendre la mousse sans crème. Un dessert léger, rafraîchissant et presque sans matière grasse.",
},
{
 "nome": "Cheesecake léger aux fruits rouges (sans cuisson)",
 "hook": "Crémeux, avec une base croquante et un coulis de fruits, monté sans four — le cheesecake de tes rêves en version légère et sans sucre.",
 "tempo": "20 min + réfrigérateur", "rende": "6 parts", "kcal_base": 170,
 "ings": ["Base : 90 g de flocons d'avoine + 1 banane écrasée + 1 c. à c. de cannelle",
          "Crème : 250 g de ricotta (ou de fromage blanc) + ½ pot de yaourt nature + édulcorant au goût + le jus de ½ citron",
          "1 c. à s. de gélatine en poudre neutre + 3 c. à s. d'eau chaude",
          "Coulis : 140 g de fruits rouges + édulcorant au goût"],
 "passos": [
   "Base : mélange l'avoine, la banane écrasée et la cannelle jusqu'à former une pâte. Tasse-la au fond d'un petit moule (de préférence un moule à charnière), en formant une couche ferme. Mets au congélateur 10 minutes.",
   "Dissous la gélatine dans l'eau chaude, en remuant jusqu'à ce que ce soit transparent. Laisse tiédir.",
   "Crème : au mixeur, mixe la ricotta, le yaourt, l'édulcorant et le jus de citron jusqu'à obtenir une crème bien lisse. Ajoute la gélatine et mixe encore 20 secondes.",
   "Verse la crème sur la base et lisse la surface. Mets au réfrigérateur au moins 3 heures, jusqu'à ce que ça prenne.",
   "Coulis : dans une petite casserole, fais cuire les fruits rouges avec l'édulcorant à feu doux 5 minutes, en les écrasant un peu, jusqu'à obtenir une sorte de confiture. Laisse refroidir et étale sur le cheesecake avant de servir."],
 "porcoes8": ["1 part fine",
              "1 part",
              "1 part",
              "1 part · coulis en plus",
              "1 part",
              "1 part moyenne",
              "1 part · coulis",
              "1 grande part · coulis"],
 "dica": "La ricotta et le fromage blanc donnent le crémeux du fromage à tartiner avec bien moins de graisse et plus de protéines. La base d'avoine et de banane remplace le biscuit au beurre, et le coulis de fruits cuits rend le sucre inutile. Un vrai cheesecake qui rentre dans le régime, avec une part maîtrisée.",
},
{
 "nome": "Bâtonnets glacés aux fruits maison",
 "hook": "Rafraîchissants et pleins de vrais fruits, ces bâtonnets glacés maison sont le dessert parfait pour la chaleur — et il n'y a pas une goutte de sucre.",
 "tempo": "10 min + congélateur", "rende": "6 bâtonnets", "kcal_base": 60,
 "ings": ["300 g de fruits en dés (fraise, mangue, kiwi ou pastèque)", "240 ml de jus de fruits sans sucre (ou eau de coco)",
          "1 pot de yaourt nature sans sucre (facultatif, pour des bâtonnets crémeux)", "édulcorant au goût (facultatif)",
          "moules à bâtonnets glacés et bâtons"],
 "passos": [
   "Coupe les fruits en petits morceaux, pour qu'ils entrent dans les moules.",
   "Choisis le style : pour des bâtonnets aux fruits, n'utilise que les fruits et le jus ; pour des bâtonnets crémeux, mixe les fruits avec le yaourt.",
   "Mets quelques morceaux de fruits au fond de chaque moule (c'est joli) et complète avec le jus ou la crème mixée, en laissant un doigt d'espace en haut (le liquide gonfle en gelant).",
   "Plante un bâton au centre de chaque bâtonnet.",
   "Mets au congélateur au moins 5 heures, jusqu'à ce qu'ils soient bien fermes. Pour démouler, passe rapidement le moule sous l'eau tiède."],
 "porcoes8": ["1 bâtonnet",
              "1 bâtonnet",
              "1 bâtonnet",
              "1 à 2 bâtonnets",
              "1 bâtonnet",
              "1 à 2 bâtonnets",
              "2 bâtonnets",
              "2 bâtonnets"],
 "dica": "Les glaces à l'eau du commerce ne sont presque que de l'eau, du sucre et du colorant. Faits maison avec de vrais fruits et du jus naturel, les bâtonnets deviennent un dessert rafraîchissant plein de vitamines et pratiquement sans calories — la meilleure façon de calmer l'envie de glacé quand il fait chaud, sans culpabilité.",
},
{
 "nome": "Muffins à la pomme et à la cannelle",
 "hook": "Moelleux, parfumés et avec des morceaux de pomme — des muffins de goûter qui ont l'air d'un péché, mais qui sont légers et sans sucre.",
 "tempo": "35 min", "rende": "6 muffins", "kcal_base": 140,
 "ings": ["2 œufs", "1 pomme râpée + ½ pomme en petits dés", "135 g de flocons d'avoine mixés en farine",
          "3 c. à s. d'huile", "édulcorant spécial cuisson au goût", "120 ml de lait",
          "1 c. à c. de cannelle", "1 c. à c. de levure chimique", "1 pincée de sel"],
 "passos": [
   "Préchauffe le four à 180 °C. Garnis un moule à muffins de caissettes en papier (ou étale un filet d'huile dans les empreintes).",
   "Dans un bol, bats les œufs avec l'édulcorant et l'huile pendant 1 minute. Ajoute le lait et la pomme râpée et mélange.",
   "Ajoute l'avoine mixée, la cannelle et le sel et remue jusqu'à obtenir une pâte homogène. Ajoute les dés de pomme et la levure et mélange délicatement.",
   "Répartis la pâte dans les caissettes, en remplissant aux deux tiers (ils gonflent).",
   "Enfourne 20 à 25 minutes, jusqu'à ce qu'ils soient dorés et qu'un cure-dent planté ressorte propre. Laisse tiédir et sers."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 c. à s. de yaourt",
              "1 muffin",
              "1 à 2 muffins",
              "2 muffins",
              "2 muffins"],
 "dica": "La pomme râpée garde les muffins moelleux et naturellement sucrés, ce qui rend le sucre inutile. L'avoine apporte les fibres qui rassasient et la cannelle met en valeur la douceur du fruit. Ils sont excellents pour le goûter ou en dessert, dans la portion d'une pièce, et calment l'envie de viennoiserie en douceur.",
},
{
 "nome": "Crumble aux pommes et à l'avoine",
 "hook": "Une pomme fondante en dessous, une garniture croustillante d'avoine au-dessus — le réconfort d'une tarte chaude, monté en quelques minutes et sans sucre.",
 "tempo": "40 min", "rende": "4 portions", "kcal_base": 160,
 "ings": ["3 pommes en dés", "le jus de ½ citron", "1 c. à c. de cannelle",
          "Garniture : 90 g de flocons d'avoine + 2 c. à s. de noix concassées + 2 c. à s. d'huile de coco (ou d'huile ordinaire) + édulcorant au goût",
          "1 pincée de sel"],
 "passos": [
   "Préchauffe le four à 180 °C. Dans un bol, mélange les dés de pomme avec le jus de citron et la cannelle et étale-les au fond d'un plat à gratin.",
   "Prépare la garniture : dans un autre bol, mélange l'avoine, les noix, l'huile, l'édulcorant et le sel, en frottant du bout des doigts jusqu'à obtenir une garniture humide et grumeleuse.",
   "Répartis la garniture sur les pommes, en couvrant toute la surface.",
   "Enfourne 25 à 30 minutes, jusqu'à ce que la pomme bouillonne sur les côtés et que la garniture soit dorée et croustillante.",
   "Laisse tiédir 5 minutes et sers. C'est délicieux avec une cuillère de yaourt nature ou de glace à la banane par-dessus."],
 "porcoes8": ["½ portion",
              "1 petite portion",
              "1 portion",
              "1 portion · yaourt",
              "1 portion",
              "1 portion moyenne",
              "1 portion · yaourt",
              "1 grande portion · yaourt"],
 "dica": "La pomme cuite libère sa propre douceur, et la cannelle renforce le goût sans sucre. La garniture d'avoine et de noix donne le croustillant d'une tarte avec des fibres et de bonnes graisses à la place du beurre et de la farine blanche. C'est le réconfort d'un dessert chaud du four, dans la bonne portion.",
},
{
 "nome": "Poire rôtie aux épices",
 "hook": "La poire devient tendre et juteuse, parfumée à la cannelle et au girofle — un dessert élégant et chaud, sucré uniquement par le fruit.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 110,
 "ings": ["2 poires fermes", "cannelle en bâton (ou en poudre)", "2 clous de girofle", "zeste d'orange (facultatif)",
          "1 c. à c. de miel (facultatif)", "1 c. à s. de noix ou d'amandes concassées"],
 "passos": [
   "Préchauffe le four à 180 °C. Lave les poires, coupe-les en deux dans la longueur et retire le cœur au centre avec une petite cuillère, en formant une cavité.",
   "Pose les moitiés de poire sur une plaque, face coupée vers le haut. Saupoudre de cannelle et mets un clou de girofle et un peu de zeste d'orange dans chaque cavité.",
   "Si tu veux, dépose quelques gouttes de miel sur chaque poire.",
   "Verse un doigt d'eau au fond de la plaque (pour que ça ne se dessèche pas) et enfourne 25 minutes, jusqu'à ce que la poire soit bien tendre (une fourchette entre facilement).",
   "Retire les clous de girofle, parsème de noix concassées par-dessus et sers chaud, nature ou avec une cuillère de yaourt nature."],
 "porcoes8": ["1 moitié",
              "1 poire (2 moitiés)",
              "1 poire",
              "1 poire · yaourt",
              "1 poire",
              "1 poire · noix en plus",
              "1 poire · yaourt",
              "2 poires · yaourt"],
 "dica": "Rôtir la poire concentre le sucre naturel du fruit et la rend sucrée sans sucre ajouté. Les épices apportent un parfum réconfortant qui satisfait le palais, et les noix ajoutent de bonnes graisses et du croquant. Un dessert chaud, léger et raffiné.",
},
]
