# -*- coding: utf-8 -*-
"""30 receitas de VITAMINAS, SUCOS E CHÁS DETOX (121-150). Português. Sem açúcar.
Layout: 2 por página (motor_sucos.py), cartão compacto e legível.
- Sucos e vitaminas (têm caloria): tabela de ajuste compacta -> porcoes8 (8 entradas).
  Metas (kcal): 90/110/130/150 · 130/150/170/190.
- Chás e águas detox (≈ zero caloria, sem açúcar): campo 'livre': True ->
  mostra faixa 'bebida livre, à vontade' no lugar da tabela (não precisa de porcoes8).
Cada receita tem 'prompt' = foto quadrada, ultrarrealista, SEM texto.
"""

# porção padrão para sucos (metas 90/110/130/150 · 130/150/170/190)
P = ["1 copo (200 ml)", "1 copo (250 ml)", "1 copo grande (300 ml)", "1 copo grande · ½ fruta",
     "1 copo grande (300 ml)", "1 copo grande (350 ml)", "1 copo grande · ½ fruta", "2 copos ou 1 fruta a mais"]
# porção padrão para vitaminas (mais encorpadas, dá para somar aveia)
V = ["1 copo (200 ml)", "1 copo (250 ml)", "1 copo grande (300 ml)", "1 copo · 1 col. aveia",
     "1 copo grande (300 ml)", "1 copo grande (350 ml)", "1 copo grande · 1 col. aveia", "1 copo grande · 2 col. aveia"]

RECEITAS = [
# ---------------- SUCOS DETOX (121-130) ----------------
{
 "nome": "Suco Verde Detox",
 "hook": "O clássico detox da manhã: leve, refrescante e cheio de clorofila para dar aquele empurrão no organismo.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 90,
 "ings": ["1 folha de couve (ou 1 punhado de espinafre)", "1 maçã verde em pedaços", "suco de ½ limão",
          "1 pedacinho de gengibre", "200 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Lave bem a couve e a maçã. Tire o talo grosso da couve.",
   "Coloque tudo no liquidificador com a água gelada e bata em velocidade máxima por 1 minuto, até ficar bem líquido.",
   "Se preferir sem pedacinhos, coe com uma peneira. Sirva na hora, com gelo."],
 "porcoes8": P,
 "dica": "As folhas verdes têm muita fibra e água com pouquíssima caloria, ajudando a desinchar e a dar saciedade. Beber antes do café da manhã hidrata e prepara o corpo para o dia. Sem açúcar, é uma das bebidas mais leves que existem.",
 "prompt": "Square ultra-realistic overhead food photograph of a tall glass of fresh green detox juice with kale and green apple, a lemon slice and ice, a few kale leaves and an apple beside it, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Pepino, Limão e Hortelã",
 "hook": "Puro frescor num copo — o pepino refresca, o limão desperta e a hortelã perfuma. Hidratação que ajuda a desinchar.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 70,
 "ings": ["½ pepino em pedaços", "suco de 1 limão", "5 folhas de hortelã", "250 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Lave o pepino e corte em pedaços (pode deixar a casca, se for fina).",
   "Bata o pepino, o suco de limão, a hortelã e a água no liquidificador por 1 minuto.",
   "Coe se quiser mais limpo e sirva bem gelado, com gelo."],
 "porcoes8": P,
 "dica": "O pepino é quase todo água e ajuda a hidratar e a reduzir a retenção de líquido (aquele inchaço). Com limão e hortelã, vira uma bebida super refrescante e praticamente sem calorias — ótima para tomar ao longo do dia no lugar de refrigerante.",
 "prompt": "Square ultra-realistic overhead food photograph of a tall glass of cucumber lemon mint water with cucumber slices, lemon and fresh mint leaves, ice cubes, on a light wooden table, soft natural light, fresh and refreshing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Abacaxi com Hortelã e Gengibre",
 "hook": "Docinho, tropical e digestivo — o abacaxi com gengibre é aquele suco que refresca e ainda ajuda a desinflamar.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 110,
 "ings": ["2 fatias de abacaxi em pedaços", "5 folhas de hortelã", "1 pedacinho de gengibre",
          "200 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Corte o abacaxi em pedaços, tirando a casca e o miolo duro do centro.",
   "Bata o abacaxi, a hortelã, o gengibre e a água no liquidificador por 1 minuto, até ficar homogêneo.",
   "Coe se quiser e sirva bem gelado, com gelo e uma folhinha de hortelã."],
 "porcoes8": P,
 "dica": "O abacaxi tem enzimas que ajudam na digestão e é rico em água e vitamina C. O gengibre acelera levemente o metabolismo e desinflama. É um suco naturalmente doce, então não precisa de açúcar — a fruta já faz esse trabalho.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh pineapple juice with mint and ginger, pineapple wedges and mint beside it, ice cubes, on a light wooden table, soft natural light, tropical and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Beterraba, Cenoura e Laranja",
 "hook": "Vermelho vibrante e cheio de energia — a beterraba com laranja é um suco que dá disposição e colore o dia.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 120,
 "ings": ["½ beterraba pequena crua em pedaços", "1 cenoura em pedaços", "suco de 2 laranjas",
          "100 ml de água", "gelo a gosto"],
 "passos": [
   "Descasque a beterraba e a cenoura e corte em pedaços pequenos.",
   "Esprema as laranjas. Bata a beterraba, a cenoura, o suco de laranja e a água no liquidificador por 2 minutos, até ficar bem líquido.",
   "Coe com uma peneira (a beterraba e a cenoura deixam fibras) e sirva gelado."],
 "porcoes8": P,
 "dica": "A beterraba melhora a circulação e dá energia, a cenoura traz vitamina A e a laranja, vitamina C. Juntas, formam um suco naturalmente doce e nutritivo. Como tem açúcar natural das frutas e da beterraba, vale respeitar a porção do copo.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of vibrant red beetroot carrot orange juice, with beetroot, carrot and orange slices beside it, ice cubes, on a light wooden table, soft natural light, vibrant and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Melancia com Limão",
 "hook": "A hidratação em forma de suco: a melancia é quase toda água, doce na medida e refrescante como poucos.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 80,
 "ings": ["2 fatias grandes de melancia sem casca", "suco de ½ limão", "5 folhas de hortelã (opcional)", "gelo a gosto"],
 "passos": [
   "Corte a melancia em cubos e retire as sementes maiores.",
   "Bata a melancia com o suco de limão (e a hortelã, se quiser) no liquidificador por 30 segundos — a melancia solta muita água, quase não precisa acrescentar líquido.",
   "Sirva imediatamente, bem gelado, com gelo."],
 "porcoes8": P,
 "dica": "A melancia tem mais de 90% de água, então hidrata muito e enche o estômago com poucas calorias. É naturalmente doce e refrescante, perfeita para matar a vontade de algo doce e gelado no calor sem sair da dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh watermelon juice with a lemon slice and mint, watermelon wedges beside it, ice cubes, on a light wooden table, soft natural light, fresh and summery, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Cenoura, Maçã e Gengibre",
 "hook": "Doce, alaranjado e com um toque picante de gengibre — um suco que fortalece a imunidade e desperta o corpo.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 110,
 "ings": ["1 cenoura em pedaços", "1 maçã em pedaços", "1 pedacinho de gengibre", "200 ml de água", "gelo a gosto"],
 "passos": [
   "Descasque a cenoura e corte a maçã em pedaços, tirando as sementes.",
   "Bata a cenoura, a maçã, o gengibre e a água no liquidificador por 2 minutos, até ficar bem líquido.",
   "Coe com uma peneira e sirva gelado."],
 "porcoes8": P,
 "dica": "A cenoura e a maçã dão doçura natural e muita fibra, enquanto o gengibre dá aquele toque termogênico que ajuda o metabolismo. É um suco reforçado em vitaminas, ideal para começar o dia com energia sem precisar de açúcar.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of carrot apple ginger juice, with carrot, apple and ginger beside it, ice cubes, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco Verde de Espinafre, Abacaxi e Pepino",
 "hook": "Verdinho e docinho ao mesmo tempo — o abacaxi disfarça o espinafre e você nem percebe que está tomando algo tão saudável.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 100,
 "ings": ["1 punhado de espinafre", "1 fatia de abacaxi em pedaços", "½ pepino em pedaços",
          "suco de ½ limão", "200 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Lave bem o espinafre e o pepino.",
   "Bata o espinafre, o abacaxi, o pepino, o limão e a água no liquidificador por 1 minuto, até ficar bem verde e líquido.",
   "Coe se quiser e sirva gelado."],
 "porcoes8": P,
 "dica": "O espinafre é riquíssimo em ferro e nutrientes com quase nenhuma caloria, e o abacaxi deixa o suco docinho e gostoso sem açúcar. O pepino hidrata e ajuda a desinchar. É um jeito fácil e saboroso de comer mais verde.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of green smoothie with spinach, pineapple and cucumber, spinach leaves and pineapple beside it, ice cubes, on a light wooden table, soft natural light, fresh and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Laranja com Cenoura e Gengibre",
 "hook": "A dose diária de vitamina C num copo alaranjado e brilhante — reforça a imunidade e dá energia para o dia.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 110,
 "ings": ["suco de 3 laranjas", "1 cenoura em pedaços", "1 pedacinho de gengibre", "gelo a gosto"],
 "passos": [
   "Esprema as laranjas para tirar o suco.",
   "Descasque a cenoura e corte em pedaços pequenos. Bata a cenoura, o suco de laranja e o gengibre no liquidificador por 2 minutos.",
   "Coe com uma peneira e sirva bem gelado, com gelo."],
 "porcoes8": P,
 "dica": "A laranja e a cenoura são cheias de vitamina C e A, e o gengibre dá um toque que ajuda a circulação e o metabolismo. É um suco energético e naturalmente doce — só lembre de respeitar a porção, já que o açúcar das frutas soma calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh orange carrot ginger juice, with orange halves, carrot and ginger beside it, ice cubes, on a light wooden table, soft natural light, bright and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco de Uva Natural com Limão",
 "hook": "Roxo intenso e cheio de antioxidantes — a uva vira um suco naturalmente doce que faz bem ao coração.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 120,
 "ings": ["1 cacho pequeno de uvas roxas sem semente (≈ 1 xícara e meia)", "suco de ½ limão",
          "150 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Lave bem as uvas e tire dos cabinhos.",
   "Bata as uvas com o limão e a água no liquidificador por 1 minuto, até desmancharem.",
   "Coe com uma peneira, apertando bem para tirar todo o suco, e sirva gelado."],
 "porcoes8": P,
 "dica": "A uva roxa é rica em antioxidantes que protegem o coração e a pele. Feito na hora, sem açúcar, o suco de uva natural é bem diferente do de caixinha — só lembre que a uva é uma fruta bem doce, então a porção do copo importa.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of natural purple grape juice with a lemon slice, fresh grapes beside it, ice cubes, on a light wooden table, soft natural light, rich and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Suco Detox de Maçã, Couve e Salsão",
 "hook": "Levíssimo e desinchante — a combinação verde que limpa o organismo e cai muito bem antes das refeições.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 90,
 "ings": ["1 maçã verde em pedaços", "1 folha de couve", "1 talo de salsão (aipo)", "suco de ½ limão",
          "200 ml de água gelada", "gelo a gosto"],
 "passos": [
   "Lave a couve, a maçã e o salsão. Tire o talo grosso da couve.",
   "Bata a maçã, a couve, o salsão, o limão e a água no liquidificador por 1 minuto.",
   "Coe e sirva bem gelado."],
 "porcoes8": P,
 "dica": "O salsão (aipo) é diurético e ajuda a eliminar o excesso de líquido, a couve dá fibra e nutrientes e a maçã adoça naturalmente. É um suco verde leve e desinchante, ótimo para acompanhar uma rotina de emagrecimento.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of green detox juice with apple, kale and celery, celery stalks and green apple beside it, ice cubes, on a light wooden table, soft natural light, fresh and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- VITAMINAS / SMOOTHIES (131-140) ----------------
{
 "nome": "Vitamina de Banana com Aveia e Canela",
 "hook": "Cremosa e reconfortante, essa vitamina sustenta a manhã inteira — o café da manhã líquido para dias corridos.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 190,
 "ings": ["1 banana", "2 colheres de sopa de aveia", "200 ml de leite (ou bebida vegetal)",
          "1 pitada de canela", "gelo a gosto"],
 "passos": [
   "Descasque a banana (se estiver bem madura, adoça mais).",
   "Bata a banana, a aveia, o leite e a canela no liquidificador por 1 minuto, até ficar cremoso.",
   "Sirva na hora, com uma pitada de canela por cima. Se quiser mais gelado, junte gelo e bata de novo."],
 "porcoes8": V,
 "dica": "A banana com aveia é uma dupla que sacia por horas graças à fibra, e o leite entra com proteína. É uma vitamina que funciona como refeição líquida completa — perfeita para o café da manhã ou o lanche de quem tem pressa, sem precisar de açúcar.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy banana oat smoothie dusted with cinnamon, oats and a banana beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vitamina de Morango com Iogurte",
 "hook": "Rosada e cremosa, com o docinho natural do morango — uma vitamina que parece um milk-shake, mas é leve e proteica.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 150,
 "ings": ["1 xícara de morangos (frescos ou congelados)", "1 pote de iogurte natural sem açúcar (≈ 170 g)",
          "100 ml de leite (ou água)", "adoçante a gosto (opcional)", "gelo a gosto"],
 "passos": [
   "Lave os morangos e tire as folhinhas verdes.",
   "Bata os morangos, o iogurte e o leite no liquidificador por 1 minuto, até virar um creme rosado e liso.",
   "Prove e, se quiser, adoce um pouco. Sirva gelado."],
 "porcoes8": V,
 "dica": "O iogurte natural traz proteína e cremosidade sem açúcar, e o morango adoça de forma natural com pouquíssima caloria. É uma vitamina saciante e refrescante que mata a vontade de milk-shake de forma leve e nutritiva.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy pink strawberry yogurt smoothie, fresh strawberries beside it, on a light wooden table, soft natural light, creamy and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vitamina de Frutas Vermelhas",
 "hook": "Roxa, antioxidante e cheia de sabor — um mix de frutinhas vermelhas batido cremoso, ótimo para a pele e a saciedade.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 140,
 "ings": ["1 xícara de frutas vermelhas mistas (morango, mirtilo, framboesa)", "1 pote de iogurte natural sem açúcar",
          "100 ml de leite (ou água)", "adoçante a gosto (opcional)", "gelo a gosto"],
 "passos": [
   "Se as frutas forem congeladas, use direto (deixam a vitamina mais gelada e cremosa).",
   "Bata as frutas vermelhas, o iogurte e o leite no liquidificador por 1 minuto, até virar um creme liso.",
   "Prove, adoce se quiser e sirva na hora."],
 "porcoes8": V,
 "dica": "As frutas vermelhas são campeãs em antioxidantes, que combatem o envelhecimento, e têm baixo índice de açúcar. Com iogurte, viram uma vitamina proteica e cremosa que sacia e é uma das mais saudáveis para o lanche.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy mixed berry smoothie in purple color, fresh berries beside it, on a light wooden table, soft natural light, creamy and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie Verde com Banana e Espinafre",
 "hook": "Verde por fora, docinho por dentro — a banana esconde o espinafre e entrega uma bebida cremosa cheia de nutrientes.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 160,
 "ings": ["1 banana", "1 punhado de espinafre", "½ maçã em pedaços", "200 ml de leite (ou água de coco)",
          "gelo a gosto"],
 "passos": [
   "Lave bem o espinafre.",
   "Bata a banana, o espinafre, a maçã e o leite no liquidificador por 1 minuto, até ficar verde e cremoso.",
   "Sirva na hora, bem gelado."],
 "porcoes8": V,
 "dica": "É um jeito delicioso de comer mais folhas verdes: a banana e a maçã adoçam naturalmente e disfarçam o espinafre, que entra cheio de ferro e fibra. Cremoso e saciante, funciona como um café da manhã líquido e nutritivo.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy green smoothie with banana and spinach, spinach leaves and a banana beside it, on a light wooden table, soft natural light, creamy and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vitamina de Abacate",
 "hook": "Cremosíssima e reconfortante, com a gordura boa do abacate — uma vitamina que sacia de verdade e nutre a pele.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 190,
 "ings": ["½ abacate maduro", "200 ml de leite (ou bebida vegetal)", "adoçante a gosto — ou 1 colher de chá de mel",
          "1 pitada de canela ou algumas gotas de limão", "gelo a gosto"],
 "passos": [
   "Retire a polpa do abacate com uma colher, usando só a parte bem macia.",
   "Bata o abacate, o leite e o adoçante (ou mel) no liquidificador por 1 minuto, até virar um creme liso e sedoso.",
   "Sirva gelado, com uma pitada de canela ou umas gotas de limão."],
 "porcoes8": V,
 "dica": "O abacate tem gordura boa que sacia bastante e faz bem ao coração e à pele. Batido com leite, vira uma vitamina cremosa e nutritiva que segura a fome por horas. Por ser mais calórico, é uma ótima opção de lanche na porção de um copo.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy avocado smoothie dusted with cinnamon, half an avocado beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie de Manga com Iogurte",
 "hook": "Tropical, dourado e cremoso — a manga vira um smoothie docinho que parece sobremesa e refresca na hora.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 150,
 "ings": ["1 manga madura em cubos (ou 1 xícara congelada)", "1 pote de iogurte natural sem açúcar",
          "100 ml de leite (ou água)", "gelo a gosto"],
 "passos": [
   "Descasque a manga e corte a polpa em cubos.",
   "Bata a manga, o iogurte e o leite no liquidificador por 1 minuto, até virar um creme dourado e liso.",
   "Sirva bem gelado."],
 "porcoes8": V,
 "dica": "A manga é naturalmente doce e cheia de vitamina A e C, dispensando açúcar. Com iogurte, o smoothie ganha proteína e cremosidade, virando um lanche refrescante e saciante — só respeite a porção, já que a manga é uma fruta doce.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy golden mango smoothie, fresh mango cubes beside it, on a light wooden table, soft natural light, tropical and creamy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vitamina de Pera com Aveia",
 "hook": "Suave e delicada, a pera dá uma doçura leve à aveia cremosa — uma vitamina calminha e reconfortante.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 170,
 "ings": ["1 pera madura em pedaços", "2 colheres de sopa de aveia", "200 ml de leite (ou bebida vegetal)",
          "1 pitada de canela", "gelo a gosto"],
 "passos": [
   "Lave a pera e corte em pedaços, tirando o miolo com as sementes.",
   "Bata a pera, a aveia, o leite e a canela no liquidificador por 1 minuto, até ficar cremoso.",
   "Sirva na hora, com uma pitada de canela por cima."],
 "porcoes8": V,
 "dica": "A pera é uma fruta suave e cheia de fibra, e com a aveia forma uma vitamina que sacia por bastante tempo. O leite acrescenta proteína. É uma bebida leve e reconfortante, ótima para o café da manhã ou um lanche que segura a fome.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy pear oat smoothie dusted with cinnamon, a pear and oats beside it, on a light wooden table, soft natural light, creamy and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie de Banana e Cacau",
 "hook": "Gosto de chocolate numa vitamina cremosa e sem açúcar — a solução perfeita para a vontade de doce da tarde.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 180,
 "ings": ["1 banana", "1 colher de sopa de cacau em pó 100%", "200 ml de leite (ou bebida vegetal)",
          "1 colher de chá de pasta de amendoim (opcional)", "gelo a gosto"],
 "passos": [
   "Descasque a banana (se estiver bem madura, adoça mais).",
   "Bata a banana, o cacau, o leite e a pasta de amendoim no liquidificador por 1 minuto, até virar um creme achocolatado e liso.",
   "Sirva bem gelado, com gelo."],
 "porcoes8": V,
 "dica": "O cacau puro dá o sabor de chocolate sem açúcar, e a banana adoça e deixa a vitamina cremosa. É a maneira mais gostosa de matar a vontade de chocolate à tarde de forma nutritiva, com a fibra da fruta e a proteína do leite.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy chocolate banana smoothie, a banana and cocoa powder beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vitamina de Maçã com Canela e Aveia",
 "hook": "O sabor de uma torta de maçã num copo cremoso — aveia, maçã e canela batidas num lanche que reconforta.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 170,
 "ings": ["1 maçã em pedaços", "2 colheres de sopa de aveia", "200 ml de leite (ou bebida vegetal)",
          "1 colher de chá de canela", "gelo a gosto"],
 "passos": [
   "Corte a maçã em pedaços, tirando as sementes (pode deixar a casca).",
   "Bata a maçã, a aveia, o leite e a canela no liquidificador por 1 minuto e meio, até ficar cremoso e a maçã bem desmanchada.",
   "Sirva na hora, com um pouco mais de canela por cima."],
 "porcoes8": V,
 "dica": "Maçã com canela e aveia lembram uma sobremesa, mas juntas viram uma vitamina cheia de fibra que sacia por horas. A canela ajuda a controlar a vontade de doce. É um lanche cremoso, gostoso e leve, sem nenhum açúcar adicionado.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy apple cinnamon oat smoothie, an apple and cinnamon stick beside it, on a light wooden table, soft natural light, creamy and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Smoothie de Melão com Hortelã",
 "hook": "Verde-claro, docinho e ultra-refrescante — o melão com hortelã é hidratação pura numa vitamina leve.",
 "tempo": "5 min", "rende": "1 copo grande", "kcal_base": 110,
 "ings": ["3 fatias de melão sem casca em cubos", "5 folhas de hortelã", "½ pote de iogurte natural (ou 100 ml de água)",
          "gelo a gosto"],
 "passos": [
   "Corte o melão em cubos, tirando as sementes.",
   "Bata o melão, a hortelã e o iogurte (ou a água) no liquidificador por 1 minuto, até ficar liso.",
   "Sirva bem gelado, com uma folhinha de hortelã."],
 "porcoes8": V,
 "dica": "O melão é rico em água e ajuda a hidratar e desinchar, com pouquíssima caloria. Batido com hortelã, fica refrescante e leve; com um pouco de iogurte, ganha cremosidade e proteína. Uma vitamina perfeita para os dias quentes.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of light green melon mint smoothie, melon cubes and mint beside it, on a light wooden table, soft natural light, fresh and refreshing, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- ÁGUAS DETOX (141-144) — LIVRES ----------------
{
 "nome": "Água Detox de Pepino, Limão e Hortelã",
 "hook": "A água que dá vontade de beber: leve, perfumada e refrescante, para hidratar o dia inteiro sem enjoar.",
 "tempo": "5 min + geladeira", "rende": "1 jarra", "kcal_base": 10, "livre": True,
 "ings": ["1 litro de água", "½ pepino em rodelas finas", "½ limão em rodelas", "6 folhas de hortelã", "gelo a gosto"],
 "passos": [
   "Lave o pepino, o limão e a hortelã.",
   "Numa jarra, coloque a água, as rodelas de pepino e de limão e as folhas de hortelã.",
   "Leve à geladeira por pelo menos 1 hora, para a água pegar o sabor. Sirva gelada ao longo do dia; pode completar com mais água conforme for bebendo."],
 "dica": "Trocar refrigerante e sucos açucarados por água saborizada é um dos hábitos que mais ajudam a emagrecer. O pepino, o limão e a hortelã dão sabor sem calorias, tornando a água mais gostosa e ajudando você a se manter hidratado o dia todo.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass jug of infused detox water with cucumber slices, lemon and mint leaves, ice, a filled glass beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Água Detox de Gengibre e Limão",
 "hook": "Uma água morna ou gelada com um toque picante que desperta o metabolismo logo cedo.",
 "tempo": "5 min", "rende": "1 copo", "kcal_base": 8, "livre": True,
 "ings": ["1 copo de água (morna ou gelada)", "suco de ½ limão", "algumas lâminas finas de gengibre", "gelo a gosto (se gelada)"],
 "passos": [
   "Corte o gengibre em lâminas bem finas.",
   "Misture a água, o suco de limão e o gengibre num copo.",
   "Deixe descansar 5 minutos para o gengibre soltar o sabor. Beba pela manhã, em jejum, morna ou gelada."],
 "dica": "Beber água com limão e gengibre em jejum ajuda a despertar o organismo e a digestão. O gengibre tem um leve efeito termogênico (que acelera um pouco o metabolismo). Sem açúcar, é um ritual matinal simples que apoia o emagrecimento.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of ginger lemon water with thin ginger slices and lemon, ginger root and lemon beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Água Detox de Frutas Vermelhas",
 "hook": "Rosada e bonita na jarra, com frutinhas boiando — uma água saborizada que parece bebida de spa.",
 "tempo": "5 min + geladeira", "rende": "1 jarra", "kcal_base": 15, "livre": True,
 "ings": ["1 litro de água", "1 punhado de frutas vermelhas (morango, mirtilo, framboesa)", "½ limão em rodelas",
          "folhas de hortelã", "gelo a gosto"],
 "passos": [
   "Lave as frutas vermelhas e corte os morangos ao meio.",
   "Numa jarra, coloque a água, as frutas, as rodelas de limão e a hortelã. Amasse levemente as frutas com uma colher para soltarem a cor e o sabor.",
   "Leve à geladeira por 1 a 2 horas e sirva gelada."],
 "dica": "As frutas vermelhas dão cor, sabor e antioxidantes à água com quase nenhuma caloria. É uma forma linda e gostosa de beber mais água ao longo do dia, substituindo bebidas açucaradas e ajudando na hidratação e no emagrecimento.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass jug of infused water with strawberries, blueberries, lemon slices and mint, ice, a filled glass beside it, on a light wooden table, soft natural light, fresh and pretty, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Água de Coco com Limão e Hortelã",
 "hook": "A hidratação natural da água de coco, turbinada com limão e hortelã — refrescante e cheia de minerais.",
 "tempo": "3 min", "rende": "1 copo grande", "kcal_base": 45, "livre": True,
 "ings": ["1 copo grande de água de coco", "suco de ½ limão", "5 folhas de hortelã", "gelo a gosto"],
 "passos": [
   "Misture a água de coco com o suco de limão num copo.",
   "Junte as folhas de hortelã e o gelo e mexa.",
   "Sirva bem gelada, de preferência natural (a água de coco de caixinha costuma ter açúcar adicionado — prefira a natural)."],
 "dica": "A água de coco repõe minerais e hidrata muito bem, com poucas calorias quando é natural. Com limão e hortelã, fica ainda mais refrescante. É ótima depois de atividade física ou nos dias quentes, no lugar de bebidas esportivas açucaradas.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of coconut water with lemon and mint leaves, ice, half a lime beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- CHÁS / INFUSÕES (145-150) — LIVRES ----------------
{
 "nome": "Chá Verde com Limão e Gengibre",
 "hook": "O aliado nº 1 de quem quer emagrecer: o chá verde acelera o metabolismo, e o limão e o gengibre dão um empurrão a mais.",
 "tempo": "8 min", "rende": "1 xícara", "kcal_base": 5, "livre": True,
 "ings": ["1 xícara de água", "1 colher de chá de chá verde (ou 1 sachê)", "algumas lâminas de gengibre", "suco de ½ limão"],
 "passos": [
   "Ferva a água e desligue o fogo. Espere 1 minuto (água muito quente deixa o chá verde amargo).",
   "Junte o chá verde e as lâminas de gengibre, tampe e deixe descansar (abafado) por 3 minutos.",
   "Coe, junte o suco de limão e beba morno. Pode tomar gelado também, ao longo do dia."],
 "dica": "O chá verde é um dos alimentos mais estudados para o emagrecimento: ele tem substâncias que ajudam a acelerar o metabolismo e a queimar gordura. Com gengibre e limão, o efeito é reforçado. Sem açúcar, é uma bebida livre que você pode tomar todo dia.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass cup of green tea with lemon and ginger slices, ginger root and lemon beside it, on a light wooden table, soft natural light, warm and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chá de Hibisco Gelado",
 "hook": "Vermelho-rubi e levemente azedinho, o hibisco é famoso por ajudar a desinchar — delicioso gelado no calor.",
 "tempo": "10 min + geladeira", "rende": "1 jarra", "kcal_base": 5, "livre": True,
 "ings": ["1 litro de água", "2 colheres de sopa de flores de hibisco secas (ou 2 sachês)",
          "rodelas de limão", "folhas de hortelã", "gelo a gosto"],
 "passos": [
   "Ferva a água e desligue. Junte o hibisco, tampe e deixe descansar (abafado) por 5 a 7 minutos.",
   "Coe e deixe esfriar. Leve à geladeira.",
   "Sirva bem gelado, com rodelas de limão, hortelã e gelo."],
 "dica": "O chá de hibisco é conhecido por ajudar a reduzir a retenção de líquido (o inchaço) e é rico em antioxidantes. Gelado e sem açúcar, é uma bebida refrescante e livre, ótima para substituir refrigerantes e sucos industrializados ao longo do dia.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of iced hibiscus tea in deep red color with lemon slices and mint, ice, on a light wooden table, soft natural light, refreshing and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chá de Camomila com Canela",
 "hook": "Quentinho e reconfortante, o chá que acalma antes de dormir — e uma boa noite de sono também ajuda a emagrecer.",
 "tempo": "8 min", "rende": "1 xícara", "kcal_base": 5, "livre": True,
 "ings": ["1 xícara de água", "1 colher de sopa de flores de camomila (ou 1 sachê)", "1 pau de canela (ou 1 pitada em pó)"],
 "passos": [
   "Ferva a água e desligue o fogo.",
   "Junte a camomila e a canela, tampe e deixe descansar (abafado) por 5 minutos.",
   "Coe e beba morno, de preferência à noite, antes de dormir."],
 "dica": "A camomila acalma e ajuda a relaxar, melhorando o sono. Dormir bem é um fator que muita gente esquece no emagrecimento: noites mal dormidas aumentam a fome e a vontade de doce no dia seguinte. Este chá é um ritual noturno que apoia a dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm cup of chamomile tea with a cinnamon stick, dried chamomile flowers beside it, on a light wooden table, soft natural light, warm and calming, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Infusão de Gengibre, Limão e Canela",
 "hook": "Uma infusão termogênica e cheirosa que aquece o corpo e dá aquele estímulo ao metabolismo.",
 "tempo": "10 min", "rende": "1 xícara grande", "kcal_base": 8, "livre": True,
 "ings": ["1 xícara grande de água", "várias lâminas de gengibre", "1 pau de canela", "suco de ½ limão"],
 "passos": [
   "Numa panelinha, ferva a água com as lâminas de gengibre e o pau de canela por 5 minutos, em fogo baixo.",
   "Desligue, tampe e deixe descansar por mais 3 minutos.",
   "Coe, junte o suco de limão e beba morno."],
 "dica": "O gengibre e a canela têm um leve efeito termogênico, ou seja, ajudam o corpo a gastar um pouco mais de energia. É uma infusão quentinha e reconfortante, sem açúcar, que cai bem em dias frios e dá aquele apoio extra ao metabolismo.",
 "prompt": "Square ultra-realistic overhead food photograph of a cup of ginger cinnamon lemon infusion with ginger slices and a cinnamon stick, lemon beside it, on a light wooden table, soft natural light, warm and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chá de Hortelã com Limão",
 "hook": "Fresco e digestivo, o chá de hortelã acalma o estômago depois das refeições — leve e cheiroso.",
 "tempo": "8 min", "rende": "1 xícara", "kcal_base": 4, "livre": True,
 "ings": ["1 xícara de água", "1 punhado de folhas de hortelã fresca (ou 1 sachê)", "suco de ½ limão"],
 "passos": [
   "Ferva a água e desligue o fogo.",
   "Junte as folhas de hortelã, tampe e deixe descansar (abafado) por 5 minutos.",
   "Coe, junte o suco de limão e beba morno ou gelado, de preferência depois das refeições."],
 "dica": "A hortelã ajuda na digestão e reduz aquela sensação de estômago pesado depois de comer. Um chá digestivo e sem açúcar depois das refeições é um hábito simples que ajuda a evitar beliscar doces logo em seguida.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass cup of fresh mint tea with a lemon slice and mint leaves, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chá de Erva-doce",
 "hook": "Suave e adocicado por natureza, a erva-doce acalma o estômago e reduz os gases — um chá reconfortante depois de comer.",
 "tempo": "8 min", "rende": "1 xícara", "kcal_base": 4, "livre": True,
 "ings": ["1 xícara de água", "1 colher de chá de sementes de erva-doce (funcho) — ou 1 sachê"],
 "passos": [
   "Amasse levemente as sementes de erva-doce (isso solta mais aroma).",
   "Ferva a água e desligue. Junte a erva-doce, tampe e deixe descansar (abafado) por 5 minutos.",
   "Coe e beba morno, de preferência depois das refeições ou à noite."],
 "dica": "A erva-doce (funcho) é conhecida por acalmar o estômago e reduzir os gases e o inchaço da barriga. Naturalmente adocicada, dispensa açúcar. É um chá digestivo e reconfortante, ótimo para fechar uma refeição de forma leve.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm cup of fennel seed tea, fennel seeds scattered beside it, on a light wooden table, soft natural light, warm and calming, shallow depth of field, no text, no writing, 1:1 square.",
},
]
