# -*- coding: utf-8 -*-
"""BÔNUS 1 — DIETA VEGETARIANA: 8 receitas NOVAS (fotos 151-158). ALEMÃO.

Tradução literal de `receitas_bonus_veg.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/151-158).
ALMOCOS -> tipo 'almoco' (metas 360/440/500/560 · 540/610/680/750), fotos 151-154
JANTARES -> tipo 'jantar' (metas 340/420/480/540 · 520/590/650/720), fotos 155-158
"""

ALMOCOS = [
{
 "nome": "Kichererbsen-Bowl mit Reis und Ofengemüse",
 "tag": "Vegetarisches Mittagessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Eine bunte, üppige Schüssel ganz ohne Fleisch — die Kichererbse trägt durch den ganzen Nachmittag wie ein Eiweißgericht.",
 "tempo": "35 Min.", "rende": "1 Portion", "kcal_base": 500,
 "ings": ["80 g gekochte Kichererbsen (oder aus der Dose, abgetropft)", "4 EL gekochter Vollkornreis",
          "1 Zucchini in Stücken", "½ Paprika in Stücken", "½ rote Zwiebel in Stücken", "Kirschtomaten",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer, Kurkuma und Oregano nach Geschmack", "Blattsalat"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Schneide die Zucchini, die Paprika und die Zwiebel in ähnlich große, mundgerechte Stücke.",
   "Verteile das Gemüse und die Kirschtomaten auf einem Backblech, würze alles mit Salz, Pfeffer, Oregano und der Hälfte des Olivenöls und vermische es mit den Händen.",
   "Backe alles 20 bis 25 Minuten, bis das Gemüse weich und an den Spitzen goldbraun ist. Wende es nach der Hälfte der Zeit.",
   "Erhitze das restliche Olivenöl in einer Pfanne und brate die Kichererbsen mit dem Kurkuma, Salz und Pfeffer 3 Minuten unter Rühren an, nur damit sie Geschmack annehmen und leicht bräunen.",
   "Baue die Schüssel auf: ein Bett aus Blattsalat, der Reis an einer Seite, die Kichererbsen und das Ofengemüse darüber. Beträufle alles mit dem Zitronensaft und serviere."],
 "porcoes8": ["55 g Kichererbsen · 3 EL Reis · Gemüse",
              "80 g Kichererbsen · 4 EL Reis · Gemüse",
              "80 g Kichererbsen · 5 EL Reis · Gemüse",
              "110 g Kichererbsen · 5 EL Reis · etwas Olivenöl",
              "110 g Kichererbsen · 5 EL Reis · Gemüse",
              "125 g Kichererbsen · 6 EL Reis · 1 EL Nüsse",
              "165 g Kichererbsen · 7 EL Reis · Avocado",
              "165 g Kichererbsen · 8 EL Reis · Avocado"],
 "dica": "Die Kichererbse verbindet Eiweiß und Ballaststoffe, die wie ein Fleischgericht sättigen, und zusammen mit dem Vollkornreis ergibt sie ein vollständiges Eiweiß (das Duo aus Hülsenfrucht und Getreide, das Vegetarier nutzen). Das Gemüse im Ofen zu garen konzentriert den Geschmack ohne Fett und lässt das Gericht leicht und würzig werden.",
},
{
 "nome": "Linsen-Auflauf mit Kartoffelpüree",
 "tag": "Vegetarisches Mittagessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Der ganze Trost eines überbackenen Auflaufs, mit einer Füllung aus gewürzten Linsen anstelle von Fleisch — cremig und voller pflanzlichem Eiweiß.",
 "tempo": "45 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["200 g gekochte Linsen", "2 mittelgroße Kartoffeln", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt",
          "1 Tomate, gehackt", "1 Möhre, gerieben", "1 TL Olivenöl",
          "2 EL geriebener Käse", "Salz, Pfeffer, Kurkuma, Petersilie und Schnittlauch nach Geschmack"],
 "passos": [
   "Schäle die Kartoffeln und koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich sind. Gieße sie ab und zerdrücke sie mit einer Gabel und einer Prise Salz zu einem glatten Püree.",
   "Erhitze das Olivenöl in einer Pfanne und brate die Zwiebel und den Knoblauch 2 Minuten an. Gib die geriebene Möhre und die Tomate dazu und koche alles 3 Minuten.",
   "Füge die gekochten Linsen, das Kurkuma, Salz und Pfeffer hinzu und koche alles noch 5 Minuten, dabei die Linsen mit dem Löffel etwas zerdrücken, bis eine kräftige Füllung entsteht.",
   "Verteile die Hälfte des Pürees in einer Auflaufform, darauf die Linsenfüllung und darüber das restliche Püree. Streue den geriebenen Käse darauf.",
   "Backe alles bei 200 °C 15 Minuten, bis die Oberfläche goldbraun ist. Streue die Kräuter darüber und serviere."],
 "porcoes8": ["½ Portion · Salat",
              "1 Portion · Salat",
              "1 Portion · Salat",
              "1 Portion · 1 EL Käse mehr · Salat",
              "1 Portion · extra Linsen · Salat",
              "1 große Portion · Salat",
              "1 große Portion · extra Linsen · Salat",
              "doppelte Portion · Salat"],
 "dica": "Die Linse ist reich an Eisen, Ballaststoffen und pflanzlichem Eiweiß, ein Trio, das stark sättigt — im Auflauf ersetzt sie das Fleisch mit Leichtigkeit. Mit dem Kartoffelpüree im richtigen Maß und etwas überbackenem Käse ist das ein wohltuendes Gericht, das die Lust auf schweres Essen austrickst.",
},
{
 "nome": "Gemüse-Frittata",
 "tag": "Vegetarisches Mittagessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Ein hohes, lockeres Omelett, gebacken mit buntem Gemüse und Käse — das Eiweiß der Eier in einem Gericht, das man in Stücke schneidet und das allen schmeckt.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 420,
 "ings": ["5 Eier", "1 Zucchini in kleinen Würfeln", "½ Paprika, gehackt", "1 Tomate, gehackt", "1 Handvoll Spinat",
          "3 EL heller Käse in Würfeln", "1 TL Olivenöl",
          "Schnittlauch, Salz und Pfeffer nach Geschmack", "Blattsalat für den Salat"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Erhitze das Olivenöl in einer ofenfesten Pfanne und brate die Zucchini und die Paprika 4 Minuten unter Rühren an, bis sie weich werden.",
   "Gib den Spinat dazu und rühre 1 Minute, nur bis die Blätter zusammenfallen. Verteile das Gemüse in der Pfanne.",
   "Verquirle die Eier in einer Schüssel mit Salz und Pfeffer. Gib die Tomate, den Käse und den Schnittlauch dazu und vermische alles.",
   "Gieße die Eier über das Gemüse in der Pfanne und lass alles 2 Minuten auf dem Herd, nur damit der Rand fest wird.",
   "Schiebe die Pfanne 15 Minuten in den Ofen, bis die Frittata aufgeht, in der Mitte fest wird und oben goldbraun ist. Schneide sie in Stücke und serviere sie mit einem grünen Salat."],
 "porcoes8": ["1 Stück · Salat",
              "1 großes Stück · Salat",
              "1 großes Stück · Salat · 2 EL Reis",
              "2 Stücke · Salat · 2 EL Reis",
              "2 Stücke · Salat · 3 EL Reis",
              "2 große Stücke · Salat · 3 EL Reis",
              "2 große Stücke · Salat · 4 EL Reis",
              "3 Stücke · Salat · 4 EL Reis"],
 "dica": "Eier sind vollwertiges Eiweiß und machen sehr satt, ideal für ein vegetarisches Mittagessen ohne Hülsenfrüchte. Mit Gemüse und etwas Käse gebacken reicht die Frittata weit, hält sich gut im Kühlschrank und stillt den Hunger auf leichte und nahrhafte Weise.",
},
{
 "nome": "Vegetarisches Chili mit Bohnen und Kichererbsen",
 "tag": "Vegetarisches Mittagessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Ein würziger, kräftiger Eintopf ganz ohne Fleisch — der Beweis, dass vegetarisches Essen Teller und Bauch genauso füllt.",
 "tempo": "30 Min.", "rende": "3 Portionen", "kcal_base": 460,
 "ings": ["175 g gekochte Kidneybohnen", "165 g gekochte Kichererbsen", "80 g Mais",
          "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 Paprika, gehackt", "2 Tomaten, gehackt (oder Tomatensoße)",
          "1 TL Olivenöl", "1 TL Kreuzkümmel", "Salz, Pfeffer und Paprikapulver nach Geschmack",
          "Reis zum Servieren"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf bei mittlerer Hitze. Brate die Zwiebel, den Knoblauch und die Paprika 3 Minuten unter Rühren an, bis sie weich werden.",
   "Gib den Kreuzkümmel, das Paprikapulver, Salz und Pfeffer dazu und rühre 30 Sekunden, damit die Gewürze ihr Aroma abgeben.",
   "Füge die gehackten Tomaten hinzu und koche alles 5 Minuten, bis sie zu einer Soße zerfallen.",
   "Gib die Kidneybohnen, die Kichererbsen und den Mais dazu. Wenn es zu trocken wird, gieße 120 ml Wasser an.",
   "Stelle die Hitze klein und koche alles 15 Minuten unter gelegentlichem Rühren, bis ein sämiger Eintopf entsteht. Serviere ihn mit etwas Reis."],
 "porcoes8": ["½ Portion · 3 EL Reis",
              "1 Portion · 4 EL Reis",
              "1 Portion · 5 EL Reis",
              "1 Portion · 5 EL Reis · Avocado",
              "1 Portion · 5 EL Reis",
              "1 große Portion · 6 EL Reis",
              "große Portion · 7 EL Reis · Avocado",
              "doppelte Portion · 8 EL Reis"],
 "dica": "Bohnen und Kichererbsen zusammen ergeben ein sehr vollständiges pflanzliches Eiweiß, mit einem Berg an Ballaststoffen, der stundenlang satt hält. Mit Reis serviert wird das Eiweiß vollständig. Ein günstiges Gericht, das für mehrere Tage reicht und beweist, dass man ohne Fleisch gut essen kann.",
},
]

JANTARES = [
{
 "nome": "Kräftige Linsensuppe mit Gemüse",
 "tag": "Vegetarisches Abendessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Eine Suppe, die eine echte Mahlzeit ist: Die Linse macht die Brühe kräftig und eiweißreich, wärmt und sättigt an einem kalten Abend.",
 "tempo": "40 Min.", "rende": "3 Portionen", "kcal_base": 380,
 "ings": ["190 g rohe Linsen", "1 Kartoffel in Würfeln", "1 Möhre in Würfeln", "1 Stange Staudensellerie, gehackt (nach Wunsch)",
          "1 Tomate, gehackt", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer, Kurkuma und Kräuter nach Geschmack", "1,2 Liter Wasser"],
 "passos": [
   "Wasche die Linsen. Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an.",
   "Gib die Tomate, die Möhre, die Kartoffel und den Sellerie dazu und rühre 2 Minuten.",
   "Füge die Linsen, das Kurkuma, Salz, Pfeffer und das Wasser hinzu. Lass alles aufkochen.",
   "Stelle die Hitze klein und koche alles 25 bis 30 Minuten unter gelegentlichem Rühren, bis die Linsen und das Gemüse ganz weich sind und die Brühe sämig wird. Wenn zu viel verkocht, gieße etwas heißes Wasser nach.",
   "Schmecke mit Salz ab, streue die Kräuter darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["1 Kelle · ohne Brot",
              "2 Kellen · ohne Brot",
              "2 Kellen · 1 Scheibe Brot",
              "2 Kellen · 1 Scheibe Brot",
              "2 Kellen · 1 Scheibe Brot",
              "3 Kellen · 1 Scheibe Brot",
              "3 Kellen · 2 Scheiben Brot",
              "3 große Kellen · 2 Scheiben Brot"],
 "dica": "Die Linse ist eine der eiweiß- und eisenreichsten Hülsenfrüchte, und in der Suppe macht sie die Brühe kräftig genug für ein vollständiges Abendessen ohne Fleisch. Die vielen Flüssigkeiten und das Gemüse füllen den Magen mit wenigen Kalorien — leicht, warm und wohltuend.",
},
{
 "nome": "Gegrillter Tofu mit Gemüse und Reis",
 "tag": "Vegetarisches Abendessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Der goldbraune Tofu nimmt die Würze auf und schmeckt köstlich — eine Variante ohne Fleisch, die wirklich sättigt und abends leicht ist.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 420,
 "ings": ["150 g fester Tofu in Scheiben", "4 EL gekochter Vollkornreis", "100 g Brokkoli und Möhren",
          "1 EL helle Sojasoße", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "geriebener Ingwer (nach Wunsch)", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Tupfe die Tofuscheiben mit Küchenpapier gut trocken und drücke sie leicht aus — je trockener er ist, desto besser bräunt er.",
   "Würze den Tofu mit der Sojasoße, dem Knoblauch und dem Ingwer. Lass ihn 5 Minuten Geschmack annehmen.",
   "Erhitze eine beschichtete Pfanne mit der Hälfte des Olivenöls bei mittlerer bis hoher Hitze. Brate die Tofuscheiben 3 bis 4 Minuten je Seite, ohne daran zu rühren, bis sich eine goldbraune Kruste bildet. Nimm sie heraus und stelle sie beiseite.",
   "Schneide den Brokkoli in Röschen und die Möhre in Scheiben. Brate das Gemüse in derselben Pfanne mit dem restlichen Olivenöl 4 Minuten an, bis es weich, aber noch fest ist.",
   "Richte den Teller mit dem Vollkornreis, dem Gemüse und dem gegrillten Tofu darauf an. Beträufle alles mit noch etwas Sojasoße, wenn du magst."],
 "porcoes8": ["120 g Tofu · 3 EL Reis · Gemüse",
              "150 g Tofu · 4 EL Reis · Gemüse",
              "150 g Tofu · 5 EL Reis · Gemüse",
              "170 g Tofu · 5 EL Reis · etwas Olivenöl",
              "170 g Tofu · 5 EL Reis · Gemüse",
              "200 g Tofu · 6 EL Reis · Gemüse",
              "220 g Tofu · 7 EL Reis · 1 EL Nüsse",
              "250 g Tofu · 8 EL Reis · Nüsse"],
 "dica": "Tofu wird aus Sojabohnen gemacht und liefert pflanzliches Eiweiß mit wenig Fett, er ist eine der besten Möglichkeiten, vom Fleisch abzuwechseln. Gut abgetrocknet und gebraten bekommt er Struktur und nimmt die Würze auf. Mit Gemüse und Vollkornreis wird daraus ein vollständiges, leichtes und ballaststoffreiches Abendessen.",
},
{
 "nome": "Gefüllte Aubergine mit Kichererbsen und Käse",
 "tag": "Vegetarisches Abendessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Die Aubergine wird selbst zur Schüssel, gefüllt mit gewürzten Kichererbsen und mit Käse überbacken — schön, üppig und ohne Fleisch.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 400,
 "ings": ["1 große Aubergine", "165 g gekochte Kichererbsen", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 Tomate, gehackt", "1 TL Olivenöl", "2 EL magerer geriebener Käse",
          "Salz, Pfeffer, Kreuzkümmel und Petersilie nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Halbiere die Aubergine der Länge nach. Hole mit einem Löffel einen Teil des Inneren heraus, sodass zwei 'Boote' entstehen. Hacke das herausgeholte Innere klein.",
   "Lege die Boote auf ein Backblech, beträufle sie mit etwas Olivenöl und backe sie 10 Minuten, nur damit sie weicher werden.",
   "Erhitze das restliche Olivenöl in einer Pfanne und brate die Zwiebel und den Knoblauch 2 Minuten an. Gib die Tomate, das gehackte Innere der Aubergine, die Kichererbsen, den Kreuzkümmel, Salz und Pfeffer dazu und koche alles 6 Minuten, dabei die Kichererbsen etwas zerdrücken, bis eine weiche Füllung entsteht.",
   "Fülle die Boote mit der Kichererbsenmischung und streue den geriebenen Käse darüber.",
   "Backe alles noch 15 Minuten, bis der Käse geschmolzen und goldbraun ist. Streue Petersilie darüber und serviere."],
 "porcoes8": ["½ Aubergine · Salat",
              "1 gefüllte Aubergine · Salat",
              "1 Aubergine · 2 EL Reis",
              "1 Aubergine · extra Kichererbsen · Salat",
              "1 Aubergine · extra Kichererbsen · 2 EL Reis",
              "1 große Aubergine · 3 EL Reis",
              "1 Aubergine · doppelt Kichererbsen · 4 EL Reis",
              "Aubergine + extra Portion · 4 EL Reis"],
 "dica": "Die Aubergine enthält viel Wasser und Ballaststoffe, sie füllt den Teller also mit sehr wenigen Kalorien. Die Kichererbse bringt das pflanzliche Eiweiß, das das Fleisch ersetzt, und etwas überbackener Käse stillt die Lust auf Gratiniertes. Ein schönes, üppiges und leichtes vegetarisches Abendessen.",
},
{
 "nome": "Kichererbsen-Curry mit Reis",
 "tag": "Vegetarisches Abendessen", "num_label": "Bonus · Vegetarisch",
 "hook": "Eine goldene, duftende Soße, die die Kichererbsen umhüllt — cremig mit leichter Kokosmilch ist das ein vegetarisches Abendessen voller Geschmack.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 440,
 "ings": ["330 g gekochte Kichererbsen", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 Tomate, gehackt",
          "1 TL Currypulver", "120 ml leichte Kokosmilch", "1 Handvoll Spinat (nach Wunsch)",
          "1 TL Olivenöl", "Salz, Pfeffer und Koriander nach Geschmack", "Reis zum Servieren"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf bei mittlerer Hitze und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an.",
   "Gib das Currypulver dazu und rühre 30 Sekunden, damit das Gewürz sein Aroma abgibt. Füge die Tomate hinzu und koche sie 3 Minuten, bis sie zerfällt.",
   "Gib die Kichererbsen und die leichte Kokosmilch dazu und vermische alles. Würze mit Salz und Pfeffer.",
   "Koche alles 10 Minuten bei kleiner Hitze unter gelegentlichem Rühren, bis die Soße andickt. Wenn du magst, gib in den letzten 2 Minuten den Spinat dazu, nur bis er zusammenfällt.",
   "Streue Koriander darüber und serviere alles über einer Portion Reis."],
 "porcoes8": ["110 g Kichererbsen · 3 EL Reis",
              "165 g Kichererbsen · 4 EL Reis",
              "165 g Kichererbsen · 5 EL Reis",
              "165 g Kichererbsen · 5 EL Reis · Spinat",
              "165 g Kichererbsen · 5 EL Reis",
              "250 g Kichererbsen · 6 EL Reis",
              "250 g Kichererbsen · 7 EL Reis",
              "330 g Kichererbsen · 8 EL Reis"],
 "dica": "Die Kichererbse ist reich an Eiweiß und Ballaststoffen, und im Curry wird sie cremig und voller Geschmack. Leichte Kokosmilch gibt der Soße ihre Sämigkeit mit deutlich weniger Fett als Sahne. Mit Reis ergibt sie ein vollständiges Eiweiß — ein wohltuendes und nahrhaftes vegetarisches Abendessen.",
},
]
