# -*- coding: utf-8 -*-
"""DINNER recipes (066-100). English (US market).
porcoes8 order: Woman 120-155/155-185/185-220/220+ lb · Man 155-185/185-220/220-265/265+ lb
Targets (cal): 340/420/480/540 · 520/590/650/720
US units: oz for meat/fish · cups / tbsp / tsp · °F. Photos shared with the PT edition.
"""

RECEITAS = [
{
 "nome": "Pumpkin Soup with Shredded Chicken",
 "hook": "Creamy, orange and comforting — a soup that warms the night and brings chicken protein to truly fill you.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 340,
 "ings": ["1 large piece of squash, cubed (about 1 lb)", "1 chicken breast fillet (about 5 oz)",
          "1 onion, chopped", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "salt, pepper and grated ginger to taste", "fresh herbs to finish", "4 cups (1 quart) water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and garlic for 2 minutes, stirring, until translucent.",
   "Add the cubed squash, the whole chicken fillet and the water. Bring to a boil and cook for 20 minutes, until the squash is very soft.",
   "Remove the chicken, let it cool a little and shred with two forks. Set aside.",
   "With an immersion blender (that stick blender) or a regular blender, blend the squash with the broth into a smooth cream. Be careful with the hot liquid.",
   "Return the cream to the pot, add the shredded chicken, the ginger, salt and pepper and warm for 3 minutes. Serve with fresh herbs on top."],
 "porcoes8": ["1 ladle · little chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Squash has lots of water and fiber, which fills your stomach for very few calories. The heat of the soup makes you eat more slowly, and the shredded chicken turns the light cream into a complete meal that holds hunger until bedtime, without weight.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy orange pumpkin soup topped with shredded chicken and chopped parsley, in a rustic bowl, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Fillet in Mustard Sauce with Steamed Vegetables",
 "hook": "A creamy mustard and yogurt sauce dresses the chicken up — light, elegant and ready fast for dinner.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 chicken breast fillet (about 5 oz)", "1 tablespoon plain unsweetened yogurt",
          "1 teaspoon mustard", "1 cup broccoli, carrot and green beans", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Cut the vegetables into similar pieces. Steam (or cook in a covered pan with a finger of water) for 6 minutes, until soft but still firm and colorful.",
   "Season the chicken with salt, pepper and the garlic. Heat a nonstick pan with the olive oil over medium heat and grill the fillet for 4 to 5 minutes per side, until golden and white inside.",
   "In a small bowl, mix the yogurt, the mustard, the lemon juice, salt and pepper, into a creamy sauce.",
   "Put the chicken on the plate, drizzle with the mustard sauce and serve the vegetables on the side.",
   "Sprinkle fresh herbs and serve hot."],
 "porcoes8": ["4 oz chicken · vegetables",
              "5 oz chicken · vegetables",
              "5 oz chicken · vegetables · 2 tbsp rice",
              "6 oz chicken · vegetables · 2 tbsp rice",
              "6 oz chicken · vegetables · 3 tbsp rice",
              "7 oz chicken · vegetables · 3 tbsp rice",
              "8 oz chicken · vegetables · 4 tbsp rice",
              "9 oz chicken · vegetables · 4 tbsp rice"],
 "dica": "The creamy sauce comes from yogurt, not heavy cream or butter, cutting a lot of fat. Mustard gives bold flavor for almost no calories. Steaming the vegetables keeps the nutrients and uses no oil — a light dinner that feels like a restaurant.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast with a creamy mustard yogurt sauce, served with steamed broccoli, carrot and green beans, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fish Baked in Parchment with Vegetables",
 "hook": "The fish cooks in its own steam inside the paper, coming out incredibly tender — and you open the packet at the table, hot and fragrant.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "½ zucchini, thinly sliced",
          "½ carrot, in thin strips", "cherry tomatoes, cut", "1 clove of garlic, sliced", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and herbs (thyme or oregano) to taste", "1 large sheet of parchment paper"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). Cut the zucchini and carrot into thin slices, so they cook in the same time as the fish.",
   "In the center of a large sheet of parchment, make a bed with the vegetables. Season with a little salt, pepper and half the olive oil.",
   "Place the fish fillet on top. Season with salt, pepper, the garlic, the herbs, the lemon juice and the rest of the olive oil.",
   "Close the paper like a parcel: bring the ends together and fold the edges well, leaving an air space inside, to form a sealed packet.",
   "Bake for 18 to 20 minutes. Open carefully (hot steam escapes) and serve in the paper or move to a plate."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 1 small potato",
              "6 oz fish · vegetables · 1 potato",
              "6 oz fish · vegetables · 1 potato",
              "7 oz fish · vegetables · 1 potato",
              "8 oz fish · vegetables · 1 large potato",
              "9 oz fish · vegetables · 2 small potatoes"],
 "dica": "Cooking in parchment uses almost no fat: the fish and vegetables cook in their own steam, keeping the flavor and turning very tender. It is one of the lightest, healthiest ways to make fish, perfect for a dinner with no weight and no dirty pans.",
 "prompt": "Square ultra-realistic overhead food photograph of a white fish fillet baked in open parchment paper with zucchini, carrot, cherry tomato and herbs, steam rising, a lemon wedge, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Shepherd's Pie with Cauliflower Mash",
 "hook": "All the comfort of a gratinated shepherd's pie, but the topping is cauliflower mash — creamy, light and with far fewer calories.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["1 medium cauliflower", "2 cooked and shredded chicken breast fillets (about 10 oz)", "1 onion, chopped",
          "1 clove of garlic, chopped", "1 tomato, chopped", "1 teaspoon olive oil",
          "2 tablespoons low-fat grated cheese", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Cut the cauliflower into pieces and cook in boiling water for 12 minutes, until very soft. Drain very well (cauliflower holds water) and mash with a fork, with a pinch of salt, into a creamy mash.",
   "In a pan, heat the olive oil and fry the onion and garlic for 2 minutes. Add the shredded chicken and the tomato, season with salt and pepper and cook for 5 minutes, until it forms a soft filling.",
   "In a baking dish, spread the chicken on the bottom and cover with the cauliflower mash.",
   "Sprinkle the grated cheese on top.",
   "Bake at medium-high heat (400°F) for 15 minutes, until the top is lightly golden. Sprinkle fresh herbs and serve."],
 "porcoes8": ["½ serving · salad",
              "1 serving · salad",
              "1 serving · salad",
              "1 serving · extra chicken · salad",
              "1 serving · extra chicken · salad",
              "1 large serving · salad",
              "1 large serving · extra chicken · salad",
              "double serving · salad"],
 "dica": "Cauliflower instead of potato cuts a good part of the calories and carbs, keeping the mash creamy. Shredded chicken gives protein and fullness. It is the ideal comforting dish for the dinner of anyone who wants to eat warm and light before bed.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken shepherd's pie topped with creamy cauliflower mash, golden gratin top, a spoon lifting a portion, in a white dish, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Vegetable Soup with Lean Beef",
 "hook": "The soup that tastes like grandma made it: pieces of tender beef and vegetables in a seasoned broth, filling your belly and warming your soul.",
 "tempo": "50 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["9 oz lean beef, cubed (shank or round)", "1 potato, cubed", "1 carrot, cubed",
          "1 zucchini, cubed", "1 tomato, chopped", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste", "6 cups (1.5 quarts) water"],
 "passos": [
   "In a pot, heat the olive oil and brown the beef cubes on all sides, stirring, for 5 minutes.",
   "Add the onion and garlic and fry for 2 minutes. Add the tomato and stir for 2 more minutes.",
   "Add the water, season with salt and pepper, cover and cook over medium-low heat for 30 minutes, until the beef starts to soften.",
   "Add the potato, the carrot and the zucchini and cook for 15 more minutes, until the beef is very tender and the vegetables cooked.",
   "Taste for salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · little beef",
              "2 ladles · beef",
              "2 ladles · beef",
              "2 ladles · beef · 1 slice bread",
              "2 ladles · extra beef · 1 slice bread",
              "3 ladles · beef · 1 slice bread",
              "3 ladles · extra beef · 2 slices bread",
              "3 large ladles · double beef · 2 slices bread"],
 "dica": "Soups with lots of liquid and vegetables fill your stomach for few calories, and eating them hot makes you eat slowly and feel full sooner. Lean beef brings the protein, making the soup hearty enough to be a complete dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty beef and vegetable soup with tender beef cubes, potato, carrot and zucchini in a broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Salmon with Yogurt-Dill Sauce and Vegetables",
 "hook": "Pink salmon gets a fresh yogurt-dill sauce — sophisticated, light and made in twenty minutes.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["1 salmon steak (about 5 oz)", "2 tablespoons plain unsweetened yogurt", "chopped dill",
          "1 cup broccoli and carrot", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and chopped garlic to taste"],
 "passos": [
   "Cut the broccoli into florets and the carrot into rounds. Steam for 6 minutes, until soft but still firm.",
   "Season the salmon with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat. Put the salmon skin-side down and leave 4 minutes, then flip and leave 3 more minutes, until lighter in color and it flakes with a fork.",
   "Prepare the sauce: mix the yogurt, the chopped dill, a little salt and a few drops of lemon.",
   "Build the plate with the salmon, the vegetables on the side and the yogurt sauce on top or apart."],
 "porcoes8": ["4 oz salmon · vegetables",
              "5 oz salmon · vegetables",
              "5 oz salmon · vegetables · 1 small potato",
              "6 oz salmon · vegetables · 1 potato",
              "6 oz salmon · vegetables · 1 potato",
              "7 oz salmon · vegetables · 1 potato",
              "8 oz salmon · vegetables · 1 large potato",
              "9 oz salmon · vegetables · 2 small potatoes"],
 "dica": "Salmon brings the good fat (omega-3) that fills you and helps the heart. The yogurt-dill sauce replaces greasy creamy sauces with a fresh, high-protein version. With steamed vegetables, it is a light, pretty and complete dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-seared salmon fillet with a creamy yogurt dill sauce, served with steamed broccoli and carrot, a lemon wedge, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Lemon Chicken with Roasted Vegetables",
 "hook": "The chicken stays juicy and lightly citrusy, roasted with vegetables that caramelize at the edges — one tray, zero work.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["2 skinless chicken thighs (or 2 fillets, about 10 oz)", "1 zucchini, in pieces", "1 bell pepper, in pieces",
          "1 onion, in wedges", "cherry tomatoes", "2 cloves of garlic", "1 teaspoon olive oil",
          "juice of 1 lemon", "salt, pepper and oregano to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). On a roasting tray, spread the zucchini, the pepper, the onion, the cherry tomatoes and the garlic cloves.",
   "Season the vegetables with salt, pepper, oregano and half the olive oil, and mix.",
   "Season the chicken with salt, pepper, the lemon juice and the rest of the olive oil. Place the pieces among the vegetables.",
   "Bake for 35 minutes, turning halfway, until the chicken is golden and cooked through (the juice that runs out when pierced comes out clear) and the vegetables soft with golden edges.",
   "Serve straight from the tray, drizzling with the lemon juices that formed."],
 "porcoes8": ["1 thigh · vegetables",
              "1 thigh · vegetables",
              "1 large thigh · vegetables",
              "2 thighs · vegetables",
              "2 thighs · vegetables",
              "2 thighs · vegetables · 1 potato",
              "2 thighs · vegetables · 1 large potato",
              "3 thighs · vegetables · 1 large potato"],
 "dica": "Roasting without skin and with little oil keeps the chicken light, and lemon adds freshness with no calories. Roasted vegetables turn sweet and tasty on their own, skipping heavy sauces. A practical, colorful, light dinner made on one tray.",
 "prompt": "Square ultra-realistic overhead food photograph of oven-roasted lemon chicken thighs with zucchini, pepper, onion and cherry tomatoes on a roasting tray, golden and juicy, lemon wedges, soft natural light, rustic and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Turkey Meatballs with Zucchini in Sauce",
 "hook": "Light turkey meatballs swimming in a fresh tomato sauce, over zucchini ribbons — the pasta that does not weigh on the scale.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["9 oz ground turkey breast (or ground chicken)", "1 egg", "2 tablespoons oats",
          "2 large zucchini", "3 ripe tomatoes, chopped (or tomato sauce)", "1 onion, chopped",
          "2 cloves of garlic, chopped", "1 teaspoon olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "In a bowl, mix the ground turkey, the egg, the oats, half the garlic, salt and pepper. Knead with your hands and roll walnut-sized balls.",
   "Heat the olive oil in a wide pot and brown the meatballs on all sides, turning carefully, for 5 minutes. Remove and set aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the chopped tomatoes, salt and pepper and cook for 10 minutes, until it becomes a sauce.",
   "Return the meatballs to the sauce and cook for 8 more minutes, until cooked through.",
   "With a vegetable peeler, make thin ribbons of the zucchini (like noodles). Put the raw ribbons on the plate and pour the hot meatballs with sauce on top — the heat softens the zucchini. Sprinkle basil."],
 "porcoes8": ["3 meatballs · zucchini",
              "4 meatballs · zucchini",
              "4 meatballs · zucchini · 2 tbsp rice",
              "5 meatballs · zucchini · 2 tbsp rice",
              "5 meatballs · zucchini · 3 tbsp rice",
              "6 meatballs · zucchini · 3 tbsp rice",
              "7 meatballs · zucchini · 4 tbsp rice",
              "8 meatballs · zucchini · 4 tbsp rice"],
 "dica": "Swapping pasta for zucchini ribbons cuts almost all the carbs and fills the plate with fiber and water. Turkey meatballs are lean and high in protein, and a fresh tomato sauce, with no sugar, keeps the dinner tasty and very light.",
 "prompt": "Square ultra-realistic overhead food photograph of turkey meatballs in fresh tomato sauce served over zucchini noodles, sprinkled with basil, in a white bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Herb-Crusted Fish Fillet with Mashed Potato",
 "hook": "A crispy herb crust outside, tender fish inside — it looks like a chef's plate, but it is simple and light.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 410,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "2 tablespoons whole-grain breadcrumbs",
          "finely chopped parsley and chives", "1 medium potato", "1 teaspoon olive oil",
          "juice of ½ lemon", "1 clove of garlic, chopped", "salt and pepper to taste"],
 "passos": [
   "Peel and cook the potato in boiling water for 15 minutes, until very soft. Drain and mash with a fork, with a pinch of salt, into a smooth mash.",
   "Turn the oven to medium-high heat (400°F). Season the fish with salt, pepper, the garlic and the lemon juice.",
   "In a small bowl, mix the breadcrumbs with the parsley, the chives and a drizzle of olive oil, forming a moist crumb topping.",
   "Put the fish on a tray and cover the top with the herb crumb, pressing lightly to stick.",
   "Bake for 15 to 18 minutes, until the crust is golden and crispy and the fish flakes. Serve with the mashed potato."],
 "porcoes8": ["4 oz fish · ½ serving mash",
              "5 oz fish · 1 serving mash",
              "5 oz fish · 1 serving mash",
              "6 oz fish · 1 serving mash",
              "6 oz fish · 1 serving mash",
              "7 oz fish · 1 large serving mash",
              "8 oz fish · large serving mash",
              "9 oz fish · double serving mash"],
 "dica": "The herb crust with a bit of breadcrumbs gives crunch with no frying, keeping the fish light and full of flavor. White fish is very lean and high in protein, and the mash in the right amount comforts without overdoing it — a pretty, light dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a herb-crusted white fish fillet with a golden crispy top, served with creamy mashed potato and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Steak with Chickpea Salad",
 "hook": "A steak cooked to your liking beside a warm chickpea salad — double protein that fills you without weighing on dinner.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 440,
 "ings": ["1 lean beef steak (about 4 oz)", "½ cup cooked chickpeas",
          "½ tomato, diced", "red onion, chopped", "green leaves", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Grill the steak for 2 to 3 minutes per side, without moving it, until golden outside and cooked to your liking. Let it rest 2 minutes before cutting.",
   "In a bowl, mix the chickpeas, the tomato, the red onion and the parsley.",
   "Dress the salad with the olive oil, the lemon juice, salt and pepper.",
   "Serve the sliced steak over a bed of green leaves, with the chickpea salad on the side."],
 "porcoes8": ["3.5 oz beef · ⅓ cup chickpeas · salad",
              "4 oz beef · ½ cup chickpeas · salad",
              "4.5 oz beef · ½ cup chickpeas · salad",
              "5 oz beef · ⅔ cup chickpeas · salad",
              "5 oz beef · ⅔ cup chickpeas · salad",
              "6 oz beef · ¾ cup chickpeas · salad",
              "7 oz beef · 1 cup chickpeas · salad",
              "8 oz beef · 1 cup chickpeas · salad"],
 "dica": "Chickpeas add fiber and plant protein to the beef's protein, making the plate very filling with few calories. Grilling the lean steak with no oil and serving it with a fresh salad is a light dinner, full of flavor, that holds hunger for hours.",
 "prompt": "Square ultra-realistic overhead food photograph of a sliced grilled lean beef steak on green leaves, with a warm chickpea salad with tomato and red onion beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Creamy Broccoli Soup with Chicken",
 "hook": "Green, velvety and full of flavor — a creamy broccoli soup that gets body from the chicken and becomes a complete dinner.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 330,
 "ings": ["1 bunch of broccoli", "1 chicken breast fillet (about 5 oz)", "1 small potato (adds creaminess)",
          "1 onion, chopped", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "salt, pepper and nutmeg to taste", "4 cups (1 quart) water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and garlic for 2 minutes, stirring.",
   "Add the cubed potato, the whole chicken fillet and the water. Cook for 15 minutes.",
   "Remove the chicken, let it cool a little and shred. Set aside. Add the broccoli (just the florets) to the pot and cook 5 more minutes, until soft but still green.",
   "Blend the soup with an immersion blender (stick blender) or a regular blender into a smooth cream. Be careful with the hot liquid.",
   "Return the cream to the pot, add the shredded chicken, season with salt, pepper and a touch of nutmeg and warm for 3 minutes. Serve."],
 "porcoes8": ["1 ladle · little chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Broccoli is one of the most nutritious, lowest-calorie vegetables, and blended it becomes a velvety cream with no need for heavy cream. A small piece of potato gives the creaminess, and shredded chicken completes the soup with protein, keeping the dinner light and filling.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy green broccoli soup topped with shredded chicken, in a rustic bowl, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Turkey Wrap with Salad",
 "hook": "Slices of turkey breast, fresh leaves and a creamy touch, rolled in a soft flatbread — a light dinner to eat with your hands.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 360,
 "ings": ["1 whole-grain tortilla", "4 slices of turkey breast (lean deli meat)", "1 tablespoon cottage cheese (or light cream cheese)",
          "lettuce leaves", "½ tomato, sliced", "grated carrot", "cucumber, in strips",
          "salt, pepper and mustard to taste"],
 "passos": [
   "Warm the tortilla for 20 seconds in a pan, just to make it soft and easy to roll.",
   "Spread the cottage cheese (or light cream cheese) over the whole tortilla, like butter.",
   "Put the lettuce leaves, the turkey slices, the tomato, the grated carrot and the cucumber in the center.",
   "Season with a little salt, pepper and mustard.",
   "Fold the sides in and roll it up tight, from the bottom. Cut in half on the diagonal and serve."],
 "porcoes8": ["3 turkey slices · ½ tortilla · salad",
              "4 turkey slices · 1 tortilla · salad",
              "4 turkey slices · 1 tortilla · salad",
              "5 turkey slices · 1 tortilla · salad",
              "5 turkey slices · 1 tortilla · salad",
              "6 turkey slices · 1 large tortilla · salad",
              "6 turkey slices · 2 tortillas · salad",
              "8 turkey slices · 2 tortillas · salad"],
 "dica": "Turkey breast is a lean, practical meat, full of protein. Swapping regular cream cheese for cottage or a light version and filling the wrap with leaves and vegetables, you get a light, quick, filling dinner, perfect for days you do not want to cook.",
 "prompt": "Square ultra-realistic overhead food photograph of a turkey wrap cut in half, filled with turkey slices, lettuce, tomato, grated carrot and cucumber, on a wooden board, fresh vegetables beside it, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Stew with Vegetables",
 "hook": "Pieces of tender chicken in a thick, seasoned broth, with vegetables that melt in your mouth — cozy home cooking from the pot.",
 "tempo": "40 min", "rende": "3 servings", "kcal_base": 390,
 "ings": ["2 chicken breast fillets, cubed (about 10 oz)", "1 potato, cubed", "1 carrot, in rounds",
          "1 zucchini, cubed", "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 teaspoon olive oil", "salt, pepper, turmeric and fresh herbs to taste"],
 "passos": [
   "Season the chicken cubes with salt, pepper and a little turmeric.",
   "In a pot, heat the olive oil and brown the chicken cubes for 5 minutes, stirring. Add the onion and garlic and fry for 2 minutes.",
   "Add the tomato and stir for 2 minutes, until it starts to break down.",
   "Add the potato and carrot and cover with water (enough to cover everything). Season with salt and cook for 15 minutes.",
   "Add the zucchini and cook 8 more minutes, until everything is soft and the broth thickens. Sprinkle fresh herbs and serve on its own or with a little rice."],
 "porcoes8": ["½ serving · no rice",
              "1 serving · no rice",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "The stew cooks everything in one pot with little fat, and the chicken's own broth seasons the vegetables. It is a hearty dish that fills you for few calories, great for dinner because it is warm, comforting and light at the same time.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken stew with potato, carrot and zucchini in a golden broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tuna Burger with Salad",
 "hook": "Made from canned tuna, this burger is cheap, full of protein and ready in a flash — a light, practical dinner.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["2 cans of tuna in water, drained", "1 egg", "3 tablespoons oats", "½ onion, finely chopped",
          "chopped parsley", "1 teaspoon olive oil", "salt, pepper and juice of ½ lemon to taste",
          "green leaves, tomato and cucumber for the salad"],
 "passos": [
   "Drain the tuna well, pressing to remove the liquid. In a bowl, mix the tuna, the egg, the oats, the onion, the parsley, salt, pepper and the lemon juice.",
   "Mash everything with a fork until it holds together. If it is soft, add a bit more oats.",
   "Shape two patties with your hands, pressing flat.",
   "Heat a nonstick pan with the olive oil over medium heat. Add the burgers and leave 4 minutes per side, without moving them, until golden and firm. Flip carefully.",
   "Serve with a generous salad of leaves, tomato and cucumber on the side."],
 "porcoes8": ["1 burger · salad",
              "1 burger · salad",
              "1 burger · salad · ½ bun",
              "2 burgers · salad",
              "2 burgers · salad",
              "2 burgers · salad · 1 bun",
              "2 burgers · salad · 1 bun",
              "3 burgers · salad · 1 bun"],
 "dica": "Canned tuna is a cheap, practical protein source, and bound with egg and oats (instead of a lot of bread) it becomes a lean, filling burger. Grilled with no frying and served with plenty of salad, it is a light, economical dinner that fills your belly.",
 "prompt": "Square ultra-realistic overhead food photograph of two homemade tuna patties, golden seared, served with a fresh salad of green leaves, tomato and cucumber, a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pot Roast Beef with Vegetables",
 "hook": "A piece of beef that cooks slowly until it falls apart, with vegetables soaked in the broth — the Sunday dinner, in the right amount.",
 "tempo": "1 h 20 min", "rende": "3 servings", "kcal_base": 440,
 "ings": ["14 oz lean beef roast (shank, eye of round or bottom round)", "2 carrots, in large pieces",
          "2 potatoes, in large pieces", "1 onion, in wedges", "2 cloves of garlic", "1 tomato, chopped",
          "1 bay leaf", "1 teaspoon olive oil", "salt, pepper and rosemary to taste"],
 "passos": [
   "Season the beef with salt and pepper. In a deep pot, heat the olive oil and brown the beef on all sides, turning, for about 6 minutes (this browning gives lots of flavor to the broth).",
   "Add the onion, garlic and tomato and fry for 2 minutes. Add the bay leaf and hot water until it covers half the beef.",
   "Cover and cook over low heat for 50 minutes, turning the beef halfway. If the water dries too much, add a bit more hot water.",
   "Add the carrots and potatoes and cook for 25 more minutes, until the beef is so tender it falls apart and the vegetables are cooked.",
   "Remove the bay leaf. Slice or shred the beef and serve with the vegetables and the broth on top."],
 "porcoes8": ["½ serving beef · vegetables",
              "1 serving beef · vegetables",
              "1 serving beef · vegetables",
              "1 serving · vegetables · 1 extra potato",
              "1 serving · vegetables · 1 extra potato",
              "1 large serving · vegetables",
              "large serving · vegetables · extra potato",
              "double serving · vegetables"],
 "dica": "Slow cooking softens lean, cheap cuts with no need for fat, and the broth that forms seasons the vegetables naturally. Served with the beef measured and lots of vegetables, it is a comforting weekend dish that fits your diet just right.",
 "prompt": "Square ultra-realistic overhead food photograph of a slow-cooked pot roast beef, tender and sliced, with carrots, potatoes and onion in a rich broth, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Stuffed with Ricotta and Spinach",
 "hook": "The chicken fillet opens like a pocket and holds a creamy ricotta and spinach filling — surprising, juicy and light.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 thick chicken breast fillets (about 10 oz)", "4 tablespoons ricotta", "1 large handful of spinach",
          "1 clove of garlic, chopped", "1 teaspoon olive oil", "juice of ½ lemon",
          "salt, pepper and nutmeg to taste", "toothpicks"],
 "passos": [
   "In a pan, heat a few drops of olive oil and sauté the spinach with the garlic for 1 minute, just until it wilts. Let it cool and chop.",
   "In a bowl, mix the ricotta, the chopped spinach, salt, pepper and a touch of nutmeg, forming a creamy filling.",
   "With a knife, make a cut in the side of each fillet, opening a pocket (without cutting all the way through). Season the chicken with salt, pepper and the lemon juice.",
   "Fill the pockets with the ricotta mixture and close the opening with one or two toothpicks.",
   "Heat the rest of the olive oil in a pan over medium heat and brown the fillets for 5 to 6 minutes per side, until golden and cooked through. Remove the toothpicks before serving, with a salad on the side."],
 "porcoes8": ["1 small fillet · salad",
              "1 fillet · salad",
              "1 fillet · salad · 2 tbsp rice",
              "1 large fillet · salad · 2 tbsp rice",
              "1 large fillet · salad · 3 tbsp rice",
              "1 large fillet · salad · 4 tbsp rice",
              "2 fillets · salad · 4 tbsp rice",
              "2 fillets · salad · 5 tbsp rice"],
 "dica": "Ricotta is a lean, creamy cheese, full of protein and low in fat, ideal for stuffing without weighing you down. Spinach brings fiber and nutrients for almost no calories. The result is a juicy, sophisticated chicken, light enough for dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken breast stuffed with ricotta and spinach, sliced to show the creamy filling, with a fresh green salad, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fish Soup with Vegetables",
 "hook": "A fragrant broth with pieces of white fish and vegetables — light, full of sea flavor and comforting on a cold night.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 340,
 "ings": ["14 oz white fish fillet, in pieces (whiting or hake)", "1 potato, cubed", "1 carrot, cubed",
          "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper, coriander or parsley to taste", "5 cups water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and garlic for 2 minutes. Add the tomato and stir 2 more minutes, until it breaks down.",
   "Add the water, the potato and the carrot. Season with salt and pepper and cook for 15 minutes, until the vegetables are soft.",
   "Add the fish pieces (fish cooks fast, which is why it goes in at the end) and cook for 6 to 8 minutes, just until the fish is white and tender, without falling apart too much.",
   "Add the lemon juice and taste for salt.",
   "Sprinkle coriander or parsley and serve very hot."],
 "porcoes8": ["1 ladle · fish",
              "2 ladles · fish",
              "2 ladles · fish",
              "2 ladles · fish · 1 slice bread",
              "2 ladles · extra fish · 1 slice bread",
              "3 ladles · fish · 1 slice bread",
              "3 ladles · extra fish · 2 slices bread",
              "3 large ladles · double fish · 2 slices bread"],
 "dica": "White fish is very lean and cooks in minutes, keeping the soup light and full of protein. The broth with vegetables fills your stomach for very few calories, and the touch of lemon lifts the flavor without excess salt — a warm, light dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a light fish soup with chunks of white fish, potato, carrot and tomato in a fragrant broth, in a rustic bowl, coriander on top, a lemon wedge, on a light wooden table, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Turkey Escalope in Mushroom Sauce",
 "hook": "Thin turkey slices in a creamy mushroom sauce — a dinner that looks expensive, made with little fat in twenty minutes.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 thin turkey breast fillets (about 10 oz)", "1 cup sliced mushrooms (button)", "1 onion, chopped",
          "1 clove of garlic, chopped", "3 tablespoons plain unsweetened yogurt", "1 teaspoon olive oil",
          "salt, pepper and parsley to taste", "rice or mash to serve"],
 "passos": [
   "Season the thin turkey fillets with salt and pepper.",
   "Heat a nonstick pan with half the olive oil over medium-high heat and brown the fillets for 2 to 3 minutes per side, until golden and cooked. Remove and set aside.",
   "In the same pan, with the rest of the olive oil, fry the onion and garlic for 2 minutes. Add the mushrooms and cook for 4 minutes, until they soften and release their water.",
   "Lower the heat, turn off and add the yogurt, stirring — off the heat it does not curdle. Adjust the salt and pepper.",
   "Return the fillets to the pan to coat in the sauce. Sprinkle parsley and serve with a little rice or mash."],
 "porcoes8": ["1 fillet · 2 tbsp rice",
              "1 fillet · 3 tbsp rice",
              "1 large fillet · 3 tbsp rice",
              "1 large fillet · 4 tbsp rice",
              "1 large fillet · 4 tbsp rice",
              "2 fillets · 4 tbsp rice",
              "2 fillets · 5 tbsp rice",
              "2 fillets · 6 tbsp rice"],
 "dica": "Turkey is a lean, high-protein white meat. The creamy sauce comes from yogurt, not heavy cream, cutting a lot of fat. Mushrooms give intense flavor and body to the sauce for very few calories — a sophisticated, light dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of thin turkey escalopes in a creamy mushroom sauce, garnished with parsley, served with a little rice, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Eggs in Tomato Sauce with Chicken",
 "hook": "Eggs cooked inside a seasoned tomato sauce, with pieces of chicken — a warm, different dinner, straight from the pan to the table.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 370,
 "ings": ["4 eggs", "1 cooked and shredded chicken breast fillet (about 4 oz)", "3 ripe tomatoes, chopped (or tomato sauce)",
          "1 onion, chopped", "1 clove of garlic, chopped", "½ bell pepper, chopped", "1 teaspoon olive oil",
          "salt, pepper, paprika and fresh herbs to taste", "whole-grain bread to serve"],
 "passos": [
   "In an oven-safe (or deep) pan, heat the olive oil and fry the onion, garlic and pepper for 3 minutes, stirring.",
   "Add the chopped tomatoes, the paprika, salt and pepper and cook for 8 minutes, until it becomes a hearty sauce. Add the shredded chicken and mix.",
   "With a spoon, make small wells in the sauce. Crack an egg into each well, without mixing, so the yolks stay whole.",
   "Cover the pan and cook over low heat for 6 to 8 minutes, until the whites set and the yolks are how you like them. (Or bake at medium heat for 10 minutes.)",
   "Sprinkle fresh herbs and serve in the pan, with slices of whole-grain bread on the side."],
 "porcoes8": ["1 egg · chicken · sauce",
              "2 eggs · chicken · sauce",
              "2 eggs · chicken · 1 slice bread",
              "2 eggs · extra chicken · 1 slice bread",
              "2 eggs · extra chicken · 1 slice bread",
              "2 eggs · chicken · 2 slices bread",
              "3 eggs · extra chicken · 2 slices bread",
              "3 eggs · double chicken · 2 slices bread"],
 "dica": "Eggs are a complete, very filling protein, and cooked in the tomato sauce they stay light, with no frying. The chicken adds even more protein and the sauce fills the plate with the volume of tomatoes. It is a warm, cheap, comforting dinner that fills you well.",
 "prompt": "Square ultra-realistic overhead food photograph of baked eggs in a spiced tomato sauce with shredded chicken and pepper in a skillet, sprinkled with parsley, a slice of wholegrain bread beside it, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Shrimp and Vegetable Skewers",
 "hook": "Pink shrimp and colorful vegetables skewered together, grilled until golden — light, pretty and with a party feel.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 360,
 "ings": ["9 oz peeled large shrimp", "1 bell pepper, in squares", "1 onion, in pieces",
          "1 zucchini, in thick rounds", "cherry tomatoes", "2 cloves of garlic, chopped", "1 teaspoon olive oil",
          "juice of 1 lemon", "salt, pepper and paprika to taste", "skewer sticks"],
 "passos": [
   "Season the shrimp with salt, pepper, paprika, the garlic and the lemon juice. Let it take on flavor for 10 minutes.",
   "Build the skewers alternating a shrimp, a square of pepper, a piece of onion, a zucchini round and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or grill over medium-high heat. Add the skewers and turn every 2 minutes, for about 8 minutes total, just until the shrimp turn pink and curl. Do not overcook, or they get rubbery.",
   "Serve the skewers with a salad or a little rice."],
 "porcoes8": ["1 skewer · salad",
              "2 skewers · salad",
              "2 skewers · salad · 2 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 4 tbsp rice",
              "3 large skewers · salad · 4 tbsp rice"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories. Skewered with colorful vegetables and grilled with no oil, it becomes a light, striking, tasty dinner that controls the portion naturally and even suits special occasions.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled shrimp and vegetable skewers with pepper, onion, zucchini and cherry tomato, on a white plate with a lemon wedge, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Salmon with Asparagus",
 "hook": "Two stars on one plate: juicy salmon and crunchy asparagus — a fancy, light dinner ready in fifteen minutes.",
 "tempo": "18 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 salmon steak (about 5 oz)", "1 bunch of asparagus", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and lemon zest to taste"],
 "passos": [
   "Wash the asparagus and snap off the tough bottom end of each (it breaks naturally at the right spot when you bend it).",
   "Season the salmon with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with half the olive oil over medium heat. Put the salmon skin-side down and leave 4 minutes, flip and leave 3 more minutes, until lighter in color and it flakes.",
   "At the same time, in another pan (or the same, after removing the salmon), sauté the asparagus with the rest of the olive oil over high heat for 4 minutes, stirring, until green and soft but still crunchy.",
   "Build the plate with the salmon and the asparagus. Finish with lemon zest on top."],
 "porcoes8": ["4 oz salmon · asparagus",
              "5 oz salmon · asparagus",
              "5 oz salmon · asparagus · 1 small potato",
              "6 oz salmon · asparagus · 1 potato",
              "6 oz salmon · asparagus · 1 potato",
              "7 oz salmon · asparagus · 1 potato",
              "8 oz salmon · asparagus · 1 large potato",
              "9 oz salmon · asparagus · 2 small potatoes"],
 "dica": "Salmon brings protein and omega-3, the good fat that fills you and protects the heart. Asparagus is light, full of fiber and helps reduce bloating, with very few calories. Grilled together with little oil, they make an elegant, light and nourishing dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled salmon fillet with sautéed green asparagus spears, lemon zest on top, a lemon wedge, on a white plate, light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ground Beef Sautéed with Zucchini (Hash)",
 "hook": "A quick beef and zucchini hash with an egg on top — made in the pan in minutes, it fills you with no need for rice.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["9 oz lean ground beef", "2 zucchini, diced", "1 tomato, chopped", "1 onion, chopped",
          "1 clove of garlic, chopped", "2 eggs", "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Heat the olive oil in a pan over medium heat and fry the onion and garlic for 2 minutes, stirring.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the tomato and the diced zucchini, season with salt and pepper and cook for 8 minutes, stirring now and then, until the zucchini is soft and releases its own juice.",
   "Meanwhile, fry or cook the eggs separately (fry with very little oil or cook for 6 minutes for a soft yolk).",
   "Serve the hash hot with an egg on top of each portion and fresh herbs sprinkled over."],
 "porcoes8": ["½ serving · 1 egg",
              "1 serving · 1 egg",
              "1 serving · 1 egg · 2 tbsp rice",
              "1 serving · 1 egg · 3 tbsp rice",
              "1 serving · 2 eggs · 3 tbsp rice",
              "1 large serving · 2 eggs · 3 tbsp rice",
              "large serving · 2 eggs · 4 tbsp rice",
              "double serving · 2 eggs · 4 tbsp rice"],
 "dica": "Diced zucchini blends into the beef and adds volume for very few calories, helping you eat less meat without missing it. The egg on top adds protein and creaminess. With no rice or just a little, it is a light, quick and very filling dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a ground beef and zucchini sauté topped with a fried egg, sprinkled with parsley, on a white plate, light wooden table, soft natural light, homestyle and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pizza-Style Chicken with Salad",
 "hook": "The taste of pizza with no crust: grilled chicken gets tomato sauce, melted cheese and oregano — beats the craving and does not weigh you down.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 chicken breast fillets (about 10 oz)", "½ cup homemade tomato sauce", "3 tablespoons low-fat grated mozzarella",
          "tomato slices", "1 teaspoon olive oil", "oregano, salt and pepper to taste",
          "green leaves for the salad"],
 "passos": [
   "Season the chicken fillets with salt and pepper.",
   "Heat a nonstick pan with the olive oil over medium heat and grill the fillets for 4 to 5 minutes per side, until golden and white inside.",
   "Lower the heat. Cover each fillet with the tomato sauce, one or two tomato slices and the grated mozzarella. Sprinkle oregano.",
   "Cover the pan and leave 3 to 4 minutes, just until the cheese melts (this is the trick to gratinate with no oven).",
   "Serve with a fresh green salad on the side."],
 "porcoes8": ["3.5 oz chicken · little cheese · salad",
              "4.5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · 2 tbsp rice",
              "5 oz chicken · cheese · 3 tbsp rice",
              "6 oz chicken · cheese · 3 tbsp rice",
              "7 oz chicken · cheese · 4 tbsp rice",
              "8 oz chicken · extra cheese · 4 tbsp rice"],
 "dica": "You beat the pizza craving with the flavor of tomato sauce, cheese and oregano, but with no crust and no fat. The grilled chicken gives lean protein and fullness, and a bit of melted cheese is enough for the pleasure of something gratinated. Light and satisfying.",
 "prompt": "Square ultra-realistic overhead food photograph of a grilled chicken breast topped with tomato sauce, melted mozzarella and oregano, with tomato slices, a fresh green salad beside it, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pan-Grilled Fish with Vegetables",
 "hook": "All in one pan: the fish browns on one side while the vegetables sauté on the other — a light, fast, no-mess dinner.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "1 zucchini, in half-moons",
          "½ bell pepper, in strips", "cherry tomatoes", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the fish with salt, pepper, the garlic and the lemon juice.",
   "Heat a large pan with half the olive oil over medium-high heat. On one side, put the fillet and leave 3 to 4 minutes per side, flipping carefully, until golden and it flakes.",
   "On the other side of the pan (or after removing the fish), add the rest of the olive oil and sauté the zucchini, the pepper and the cherry tomatoes for 4 to 5 minutes, stirring, until soft but still firm.",
   "Season the vegetables with salt and pepper.",
   "Build the plate with the fish and the sautéed vegetables. Sprinkle parsley and finish with a bit more lemon."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 1 small potato",
              "6 oz fish · vegetables · 1 potato",
              "6 oz fish · vegetables · 1 potato",
              "7 oz fish · vegetables · 1 potato",
              "8 oz fish · vegetables · 1 large potato",
              "9 oz fish · vegetables · 2 small potatoes"],
 "dica": "White fish is light and cooks in minutes, and made in the same pan as the vegetables it uses very little oil. Sautéed vegetables add color, fiber and volume for almost no calories. It is one of the fastest, lightest, most practical dinners there is.",
 "prompt": "Square ultra-realistic overhead food photograph of a pan-grilled white fish fillet with sautéed zucchini, pepper and cherry tomatoes, parsley and a lemon wedge, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Turkey Breast with Pumpkin Mash",
 "hook": "Lean turkey over a naturally sweet, orange pumpkin mash — a light dinner with a cozy feel.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 390,
 "ings": ["1 turkey breast fillet (about 5 oz)", "1 piece of squash, cubed (about 10 oz)", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper, sage or rosemary to taste",
          "green leaves for the salad"],
 "passos": [
   "Cook the squash in boiling water for 15 minutes, until very soft. Drain very well and mash with a fork, with a pinch of salt, into a smooth, creamy mash.",
   "Season the turkey with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat and grill the fillet for 3 to 4 minutes per side, until golden and white inside.",
   "If you like, finish the turkey with a little sage or rosemary in the pan in the last seconds, to add aroma.",
   "Build the plate with the pumpkin mash, the sliced turkey on top and a green salad on the side."],
 "porcoes8": ["4 oz turkey · ½ serving mash · salad",
              "5 oz turkey · 1 serving mash · salad",
              "5 oz turkey · 1 serving mash · salad",
              "6 oz turkey · 1 serving mash · salad",
              "6 oz turkey · 1 serving mash · salad",
              "7 oz turkey · 1 large serving mash · salad",
              "8 oz turkey · large serving mash · salad",
              "9 oz turkey · double serving mash · salad"],
 "dica": "Turkey breast is even leaner than chicken, full of protein. Squash makes a creamy, sweet mash for very few calories, beating the sweet craving and filling the plate with fiber. A light, comforting, colorful dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of sliced grilled turkey breast over a smooth orange pumpkin mash, with a small green salad, sage on top, on a white plate, light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Noodle Soup (Loaded)",
 "hook": "The classic chicken soup, loaded with plenty of chicken and vegetables — the dinner that hugs, heals and still fits your diet.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["1 chicken breast fillet (about 5 oz)", "½ cup small pasta (thin noodles or small rings)",
          "1 carrot, diced", "1 celery stalk, chopped (optional)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste", "5 cups water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and garlic for 2 minutes, stirring.",
   "Add the whole chicken fillet, the carrot, the celery and the water. Season with salt and cook for 15 minutes, until the chicken is cooked.",
   "Remove the chicken, let it cool a little and shred. Return the shredded chicken to the pot.",
   "Add the small pasta and cook 8 to 10 more minutes, until the pasta is soft (stir now and then so it does not stick to the bottom).",
   "Taste for salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · extra chicken",
              "2 ladles · extra chicken · extra pasta",
              "3 ladles · chicken",
              "3 ladles · extra chicken · extra pasta",
              "3 large ladles · double chicken"],
 "dica": "Chicken soup is light and comforting: the broth with vegetables fills your stomach for few calories and the chicken gives the protein that fills you. With little pasta and lots of chicken and vegetables, it becomes a complete, warm dinner, ideal for cold nights or days with no appetite.",
 "prompt": "Square ultra-realistic overhead food photograph of a chicken noodle soup with shredded chicken, small pasta, carrot and celery in a golden broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Light Shrimp Curry with Vegetables",
 "hook": "Shrimp bathed in a golden curry and light coconut milk sauce — fragrant, creamy and surprisingly light.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["10 oz peeled shrimp", "1 onion, chopped", "1 clove of garlic, chopped", "1 bell pepper, in strips",
          "1 teaspoon curry powder", "½ cup light coconut milk", "1 tomato, chopped",
          "1 teaspoon olive oil", "juice of ½ lemon", "salt, pepper and coriander to taste", "rice to serve"],
 "passos": [
   "Season the shrimp with salt, pepper and the lemon juice. Let it take on flavor for 5 minutes.",
   "Heat the olive oil in a pan over medium heat and fry the onion, garlic and pepper for 3 minutes, stirring.",
   "Add the curry and stir for 30 seconds, for the seasoning to release its aroma. Add the tomato and cook for 3 minutes, until it breaks down.",
   "Add the light coconut milk and bring to a gentle boil. Add the shrimp and cook for 3 to 4 minutes, just until pink. Do not overcook, or they get rubbery.",
   "Sprinkle coriander and serve over a small portion of rice."],
 "porcoes8": ["4 oz shrimp · 2 tbsp rice",
              "5 oz shrimp · 3 tbsp rice",
              "5 oz shrimp · 3 tbsp rice",
              "6 oz shrimp · 4 tbsp rice",
              "6 oz shrimp · 4 tbsp rice",
              "7 oz shrimp · 4 tbsp rice",
              "8 oz shrimp · 5 tbsp rice",
              "9 oz shrimp · 5 tbsp rice"],
 "dica": "Shrimp is almost pure protein and cooks fast. Light coconut milk gives the sauce creaminess with far less fat than heavy cream, and the curry perfumes it and gives the feeling of a special dish. With little rice, it is a light, flavorful dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of shrimp in a light golden coconut curry sauce with pepper, served with a little white rice, coriander on top, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef Stew with Potato",
 "hook": "Beef cubes that fall apart in a thick broth with potato — the stew that comforts on a cold night, in the right portion.",
 "tempo": "1 h", "rende": "3 servings", "kcal_base": 430,
 "ings": ["10 oz lean beef, cubed (shank or lean chuck)", "2 potatoes, in large cubes", "1 carrot, in rounds",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 tomato, chopped", "1 bay leaf",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Season the beef cubes with salt and pepper. In a pot, heat the olive oil and brown the beef on all sides, stirring, for 6 minutes.",
   "Add the onion and garlic and fry for 2 minutes. Add the tomato and the bay leaf and stir for 2 minutes.",
   "Cover with hot water, cover and cook over low heat for 35 minutes, until the beef starts to soften. If it dries out, add more hot water.",
   "Add the potato and carrot and cook 20 more minutes, until the beef falls apart and the potato is soft (the potato helps thicken the broth).",
   "Remove the bay leaf, sprinkle fresh herbs and serve hot, on its own or with a little rice."],
 "porcoes8": ["½ serving · no rice",
              "1 serving · no rice",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "Slow cooking softens lean, cheap cuts, and the potato thickens the broth naturally, with no flour or cream. It is a hearty dish that fills you well with controlled calories — the comfort of a stew without leaving your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a beef stew with tender beef chunks, potato and carrot in a thick broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Oven Omelette with Lean Ham and Vegetables",
 "hook": "A tall, fluffy omelette baked in the oven, filled with vegetables and lean ham — cut it into slices and it feeds the family.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["6 eggs", "4 slices of lean ham (turkey), chopped", "½ bell pepper, chopped", "1 tomato, chopped",
          "handful of spinach", "2 tablespoons low-fat grated cheese", "1 teaspoon olive oil",
          "chives, salt and pepper to taste"],
 "passos": [
   "Turn the oven to medium heat (350°F). Brush a small baking dish with the olive oil.",
   "In a bowl, beat the eggs with salt and pepper for 30 seconds.",
   "Add to the eggs the chopped ham, the pepper, the tomato, the spinach and the chives, and mix.",
   "Pour the mixture into the dish and sprinkle the grated cheese on top.",
   "Bake for 20 to 25 minutes, until the omelette puffs up, sets in the center and lightly browns on top. Cut into slices and serve hot or warm, with a salad."],
 "porcoes8": ["1 slice · salad",
              "1 large slice · salad",
              "1 large slice · salad · 1 slice bread",
              "2 slices · salad · 1 slice bread",
              "2 slices · salad · 1 slice bread",
              "2 large slices · salad · 1 slice bread",
              "2 large slices · salad · 2 slices bread",
              "3 slices · salad · 2 slices bread"],
 "dica": "Eggs are a complete, very filling protein, and baked in the oven they skip the frying. Lean turkey ham adds flavor and protein with little fat, and the vegetables give volume and fiber. It makes a good amount, keeps well and is a light, practical dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked oven omelette (frittata) with lean ham, pepper, tomato and spinach, cut into slices, in a baking dish, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oven-Baked Tilapia with Tomato and Onion",
 "hook": "White fish fillets baked under a bed of tomato and onion that turn into a natural sauce — light, juicy and effortless.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 370,
 "ings": ["2 tilapia fillets (or other white fish, about 10 oz)", "2 tomatoes, in rounds", "1 onion, in rounds",
          "1 clove of garlic, sliced", "1 teaspoon olive oil", "juice of 1 lemon",
          "salt, pepper, oregano and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400°F). In a baking dish, spread half the tomato and onion rounds on the bottom, forming a bed.",
   "Season the fish fillets with salt, pepper, the garlic, the oregano and the lemon juice. Place them over the bed of tomato and onion.",
   "Cover the fillets with the rest of the tomato and onion and drizzle with the olive oil.",
   "Bake for 20 to 25 minutes, until the fish flakes and the tomato and onion are soft, releasing a natural sauce.",
   "Sprinkle parsley and serve with the sauce on top, alongside a salad or a little rice."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 2 tbsp rice",
              "6 oz fish · vegetables · 3 tbsp rice",
              "6 oz fish · vegetables · 3 tbsp rice",
              "7 oz fish · vegetables · 3 tbsp rice",
              "8 oz fish · vegetables · 4 tbsp rice",
              "9 oz fish · vegetables · 4 tbsp rice"],
 "dica": "White fish is very lean and high in protein, and baking it under tomato and onion creates a natural sauce with no fat, keeping the fillet juicy. It is a light, cheap, flavorful dinner that practically makes itself in the oven.",
 "prompt": "Square ultra-realistic overhead food photograph of baked white fish fillets topped with tomato and onion slices forming a natural sauce, sprinkled with parsley and oregano, in a white dish, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chicken Meatballs in Soup",
 "hook": "Tender chicken balls cooked in a light broth with vegetables — a fun, complete soup that fills you and warms you.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 350,
 "ings": ["10 oz ground chicken breast", "1 egg", "2 tablespoons oats", "1 carrot, diced",
          "1 potato, diced", "1 zucchini, diced", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 teaspoon olive oil", "salt, pepper and fresh herbs to taste", "5 cups water"],
 "passos": [
   "In a bowl, mix the ground chicken, the egg, the oats, salt and pepper. Knead with your hands and roll small walnut-sized balls.",
   "In a pot, heat the olive oil and fry the onion and garlic for 2 minutes. Add the water, the carrot and the potato, season with salt and cook for 10 minutes.",
   "Carefully drop the raw meatballs into the boiling broth, one by one. Do not stir for 3 minutes, so they firm up.",
   "Add the zucchini and cook 10 more minutes, until the meatballs are cooked through and the vegetables soft.",
   "Taste for salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["3 meatballs · 1 ladle broth",
              "4 meatballs · 2 ladles",
              "4 meatballs · 2 ladles",
              "5 meatballs · 2 ladles · 1 slice bread",
              "5 meatballs · 2 ladles · 1 slice bread",
              "6 meatballs · 3 ladles · 1 slice bread",
              "7 meatballs · 3 ladles · 2 slices bread",
              "8 meatballs · 3 ladles · 2 slices bread"],
 "dica": "Chicken meatballs give the protein that fills you, and cooked inside the soup they make the broth tastier. The lots of liquid and vegetables fill your stomach for few calories. It is a complete, light and comforting dinner that pleases even those who do not like thin soup.",
 "prompt": "Square ultra-realistic overhead food photograph of a light soup with small chicken meatballs, carrot, potato and zucchini in a clear broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Grilled Shrimp with Leafy Salad",
 "hook": "Golden garlic shrimp over a fresh, crunchy salad — a light, elegant dinner ready in fifteen minutes.",
 "tempo": "15 min", "rende": "1 serving", "kcal_base": 330,
 "ings": ["5 oz peeled large shrimp", "mixed green leaves", "½ tomato, diced", "½ cucumber, sliced",
          "red onion, thinly sliced", "2 cloves of garlic, chopped", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Dry the shrimp well with paper towel and season with salt, pepper and half the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium-high heat. Add the garlic and stir for 30 seconds, just until fragrant.",
   "Add the shrimp and grill for 2 to 3 minutes per side, just until pink and golden. Do not overcook.",
   "In a large bowl or plate, build the salad with the green leaves, the tomato, the cucumber and the red onion. Season with the rest of the lemon, salt and pepper.",
   "Put the hot shrimp on top of the salad, sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · salad",
              "5 oz shrimp · salad",
              "5 oz shrimp · salad · 1 slice bread",
              "6 oz shrimp · salad · 1 slice bread",
              "6 oz shrimp · salad · 2 tbsp rice",
              "7 oz shrimp · salad · 3 tbsp rice",
              "8 oz shrimp · salad · 3 tbsp rice",
              "9 oz shrimp · salad · 4 tbsp rice"],
 "dica": "Shrimp is almost pure protein, with very few calories, so it fills the plate without weighing you down. Browned in garlic and served over a fresh, crunchy salad, it is one of the lightest dinners possible — ideal for the evening, when the body uses less energy.",
 "prompt": "Square ultra-realistic overhead food photograph of golden garlic grilled shrimp served over a fresh salad of green leaves, tomato, cucumber and red onion, a lemon wedge, in a bowl, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fish Stew with Coconut Milk and Vegetables",
 "hook": "A creamy, fragrant fish stew with a touch of coconut milk — light as the sea, comforting as a hug.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 390,
 "ings": ["10 oz white fish fillet, in large pieces", "1 bell pepper, in strips", "1 tomato, chopped", "1 onion, in strips",
          "2 cloves of garlic, chopped", "½ cup light coconut milk", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and coriander to taste"],
 "passos": [
   "Season the fish pieces with salt, pepper, the garlic and the lemon juice. Let it take on flavor for 5 minutes.",
   "In a wide pot, heat the olive oil and make a bed with the onion, the pepper and the tomato. Sauté for 3 minutes, stirring.",
   "Place the fish pieces over the vegetables (do not stir much, so the fish does not fall apart).",
   "Drizzle with the light coconut milk, cover and cook over medium-low heat for 10 to 12 minutes, until the fish is white and tender and the broth thickens.",
   "Sprinkle coriander and serve with a small portion of rice, to enjoy the broth."],
 "porcoes8": ["4 oz fish · 2 tbsp rice",
              "5 oz fish · 3 tbsp rice",
              "5 oz fish · 3 tbsp rice",
              "6 oz fish · 4 tbsp rice",
              "6 oz fish · 4 tbsp rice",
              "7 oz fish · 4 tbsp rice",
              "8 oz fish · 5 tbsp rice",
              "9 oz fish · 5 tbsp rice"],
 "dica": "White fish is lean and high in protein, and light coconut milk gives the broth creaminess with far less fat than heavy cream. The vegetables release water and form a light, fragrant sauce. It is a comforting, light stew, perfect for dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a fish stew with chunks of white fish, pepper, onion and tomato in a light coconut broth, in a rustic bowl, coriander on top, a little rice beside it, on a light wooden table, soft natural light, warm and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beef and Vegetable Skewers",
 "hook": "Juicy beef cubes alternated with colorful vegetables, grilled until golden — barbecue flavor in the right amount.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["9 oz lean beef, cubed (sirloin or round)", "1 bell pepper, in squares", "1 onion, in pieces",
          "1 zucchini, in thick rounds", "cherry tomatoes", "1 clove of garlic, chopped", "1 teaspoon olive oil",
          "salt, pepper and paprika to taste", "skewer sticks"],
 "passos": [
   "Season the beef cubes with salt, pepper, paprika and the garlic. Let it take on flavor for 10 minutes.",
   "Build the skewers alternating a beef cube, a square of pepper, a piece of onion, a zucchini round and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or grill over medium-high heat. Add the skewers and turn every 3 minutes, for about 12 minutes total, until the beef is golden outside and cooked to your liking.",
   "Serve the skewers with a salad or a little rice."],
 "porcoes8": ["1 skewer · salad",
              "2 skewers · salad",
              "2 skewers · salad · 2 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 4 tbsp rice",
              "3 large skewers · salad · 4 tbsp rice"],
 "dica": "Skewers beat the barbecue craving in a light way: the lean beef gives protein and the colorful vegetables fill the stick with fiber and few calories. Skewering helps control the portion naturally, and grilling with no oil keeps everything tasty and light.",
 "prompt": "Square ultra-realistic overhead food photograph of grilled beef and vegetable skewers with pepper, onion, zucchini and cherry tomato, on a white plate with a fresh salad, on a light wooden table, soft natural light, colorful and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Warm Chicken, Egg and Potato Salad",
 "hook": "Golden potatoes, grilled chicken and egg, all warm over fresh leaves — a salad that is a complete, cozy dinner.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 chicken breast fillet (about 4.5 oz)", "1 small potato, cubed", "2 boiled eggs",
          "green leaves", "cherry tomatoes", "red onion, sliced", "1 teaspoon olive oil",
          "juice of ½ lemon", "salt, pepper and mustard to taste"],
 "passos": [
   "Cook the potato cubes in boiling salted water for 12 minutes, until soft. Drain. If you want them golden, sauté for 3 minutes in a pan with a few drops of olive oil.",
   "Cook the eggs for 9 minutes, run under cold water, peel and cut in half.",
   "Season the chicken with salt and pepper and grill in a nonstick pan for 4 to 5 minutes per side, until golden. Cut into strips.",
   "In a bowl or plate, make a bed of green leaves and add the cherry tomatoes and the onion.",
   "Arrange on top the warm potato, the chicken strips and the eggs. Make a dressing by mixing the olive oil, the lemon juice, the mustard, salt and pepper, drizzle and serve right away."],
 "porcoes8": ["3.5 oz chicken · ½ potato · 1 egg",
              "4.5 oz chicken · 1 small potato · 2 eggs",
              "4.5 oz chicken · 1 potato · 2 eggs",
              "5 oz chicken · 1 potato · 2 eggs",
              "5 oz chicken · 1 potato · 2 eggs",
              "6 oz chicken · 1 large potato · 2 eggs",
              "7 oz chicken · 1 large potato · 3 eggs",
              "8 oz chicken · 2 small potatoes · 3 eggs"],
 "dica": "It is a salad that fills you like a warm meal: the chicken and egg give double protein, the potato in the right amount brings energy and the leaves fill the plate with fiber. Served warm, it is comforting and light at the same time — ideal for dinner.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm salad with grilled chicken strips, golden potato cubes, halved boiled eggs, green leaves, cherry tomatoes and red onion, mustard dressing, in a bowl, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
