# -*- coding: utf-8 -*-
"""35 receitas de ALMOÇO (031-065). ALEMÃO.

Tradução literal de `receitas_almoco.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ A xícara virou PESO em 13 receitas desta categoria — cozinha alemã pesa.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/031-065).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 360/440/500/560 · 540/610/680/750
"""

RECEITAS = [
{
 "nome": "Gegrillte Hähnchenbrust mit Vollkornreis und Brokkoli",
 "hook": "Das einfachste Gericht der Welt und eines der besten zum Abnehmen: mageres Eiweiß, ein gutes Kohlenhydrat und Gemüse, so viel du magst.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 470,
 "ings": ["1 Hähnchenbrustfilet (ca. 150 g)", "4 EL gekochter Vollkornreis",
          "1 Teller Brokkoli", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Würze das Hähnchen von beiden Seiten mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft. Lass es 5 Minuten Geschmack annehmen.",
   "Schneide den Brokkoli in kleine Röschen. Bringe Wasser in einem Topf zum Kochen, gib den Brokkoli hinein und lass ihn nur 3 Minuten darin, bis er kräftig grün und weich, aber noch fest ist. Gieße ihn ab.",
   "Erhitze eine beschichtete Pfanne bei mittlerer bis hoher Hitze mit dem Olivenöl. Lege das Hähnchen hinein und lass es 4 bis 5 Minuten je Seite braten, ohne daran zu rühren, bis es außen goldbraun und innen weiß ist.",
   "Um zu prüfen, ob es gar ist, schneide das Filet in der Mitte ein: Das Fleisch muss ganz weiß sein, ohne rosa Stellen.",
   "Wärme den bereits gekochten Vollkornreis auf. Richte den Teller mit dem Reis, dem aufgeschnittenen Hähnchen und dem Brokkoli daneben an.",
   "Wenn du magst, beträufle den Brokkoli mit etwas Olivenöl und noch etwas Zitrone."],
 "porcoes8": ["100 g Hähnchen · 3 EL Reis · Brokkoli, so viel du magst",
              "120 g Hähnchen · 4 EL Reis · Brokkoli, so viel du magst",
              "130 g Hähnchen · 5 EL Reis · Brokkoli, so viel du magst",
              "150 g Hähnchen · 5 EL Reis · etwas Olivenöl",
              "150 g Hähnchen · 5 EL Reis · Brokkoli, so viel du magst",
              "170 g Hähnchen · 6 EL Reis · Brokkoli, so viel du magst",
              "200 g Hähnchen · 7 EL Reis · etwas Olivenöl",
              "220 g Hähnchen · 8 EL Reis · etwas Olivenöl"],
 "dica": "Hähnchenbrust ist fast reines Eiweiß, das stark sättigt und hilft, den Muskel zu erhalten, während du Fett verlierst. Vollkornreis hat Ballaststoffe und gibt die Energie langsam ab, du bekommst also nicht diesen Hunger, der eine Stunde später zuschlägt. Der Brokkoli füllt den Teller mit fast keinen Kalorien.",
},
{
 "nome": "Tilapiafilet mit Süßkartoffelpüree",
 "hook": "Leichter Fisch und ein von Natur aus süßliches Püree — ein Mittagessen wie im Restaurant, das trotzdem in die Diät passt.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 440,
 "ings": ["1 Tilapiafilet (ca. 150 g)", "1 mittelgroße Süßkartoffel", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "gehackte Petersilie und Schnittlauch", "Salz, Pfeffer und Paprikapulver nach Geschmack",
          "Blattsalat für den Salat"],
 "passos": [
   "Schäle die Süßkartoffel und schneide sie in Stücke. Koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich ist (eine Gabel geht ohne Mühe hinein). Gieße sie ab.",
   "Zerdrücke die Süßkartoffel noch warm mit einer Gabel, gib eine Prise Salz und die Hälfte des Olivenöls dazu und rühre, bis ein glattes Püree entsteht.",
   "Würze den Tilapia mit Salz, Pfeffer, Paprikapulver und dem Zitronensaft.",
   "Erhitze eine beschichtete Pfanne mit dem restlichen Olivenöl bei mittlerer Hitze. Lege das Filet hinein und lass es 3 bis 4 Minuten je Seite braten, dabei nur einmal vorsichtig wenden, bis es goldbraun ist und sich leicht von der Pfanne löst.",
   "Richte den Teller mit dem Püree an, lege das Filet darauf und gib eine Portion Blattsalat daneben. Streue zum Schluss die Kräuter darüber."],
 "porcoes8": ["120 g Fisch · ½ Süßkartoffel · Salat",
              "150 g Fisch · 1 kleine Süßkartoffel · Salat",
              "150 g Fisch · 1 mittlere Süßkartoffel · Salat",
              "170 g Fisch · 1 mittlere Süßkartoffel · etwas Olivenöl",
              "170 g Fisch · 1 mittlere Süßkartoffel · Salat",
              "200 g Fisch · 1 große Süßkartoffel · Salat",
              "220 g Fisch · 1 große Süßkartoffel · etwas Olivenöl",
              "250 g Fisch · 1 große Süßkartoffel · etwas Olivenöl"],
 "dica": "Tilapia ist ein magerer Fisch, voller Eiweiß und mit sehr wenig Fett. Die Süßkartoffel sättigt stundenlang und gibt ihre Energie sehr langsam ab, obwohl sie ein Kohlenhydrat ist — deshalb ist sie der Liebling von allen, die abnehmen wollen, ohne schlapp zu werden.",
},
{
 "nome": "Gegrilltes Thunfischsteak mit Gemüse und Kartoffeln",
 "hook": "Frischer Thunfisch wird zum Steak aus dem Meer: außen fest, innen saftig, und in wenigen Minuten fertig.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 450,
 "ings": ["1 frisches Thunfischsteak (ca. 150 g)", "1 kleine Kartoffel in Scheiben", "110 g grüne Bohnen und Möhren",
          "1 Knoblauchzehe, gehackt", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und Oregano nach Geschmack"],
 "passos": [
   "Koche die Kartoffelscheiben 10 Minuten in kochendem Salzwasser, bis sie weich sind, aber nicht zerfallen. Gieße sie ab.",
   "Schneide die grünen Bohnen in Stücke und die Möhren in Scheiben. Gare sie im Dampf oder in wenig kochendem Wasser 5 Minuten, bis sie weich, aber noch fest sind.",
   "Würze das Thunfischsteak mit Salz, Pfeffer, dem Knoblauch, dem Oregano und dem Zitronensaft. Lass es 5 Minuten Geschmack annehmen.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei hoher Hitze. Lege das Steak hinein und lass es 2 bis 3 Minuten je Seite braten — Thunfisch schmeckt hervorragend, wenn er in der Mitte noch leicht rosa ist; magst du ihn durch, lass ihn 1 Minute länger je Seite.",
   "Richte den Teller mit den Kartoffeln, dem Gemüse und dem Thunfischsteak darauf an. Beträufle alles mit noch etwas Zitrone und serviere."],
 "porcoes8": ["120 g Thunfisch · ½ Kartoffel · Gemüse",
              "150 g Thunfisch · 1 kleine Kartoffel · Gemüse",
              "150 g Thunfisch · 1 Kartoffel · Gemüse",
              "170 g Thunfisch · 1 Kartoffel · etwas Olivenöl",
              "170 g Thunfisch · 1 Kartoffel · Gemüse",
              "200 g Thunfisch · 1 große Kartoffel · Gemüse",
              "220 g Thunfisch · 1 große Kartoffel · etwas Olivenöl",
              "250 g Thunfisch · 2 kleine Kartoffeln · etwas Olivenöl"],
 "dica": "Frischer Thunfisch ist eines der magersten Stücke aus dem Meer: viel Eiweiß, Omega-3 (das gute Fett) und sehr wenig schlechtes Fett. Kurz bei hoher Hitze gebraten bleibt er saftig, ganz ohne Öl, und mit Gemüse und etwas Kartoffel wird daraus ein edles, leichtes Mittagessen.",
},
{
 "nome": "Vollkorn-Wrap mit gezupftem Hähnchen",
 "hook": "Ein praktischer Wrap für die Arbeit, gefüllt mit Hähnchen und Salat — stillt den Hunger, ohne schwer zu liegen.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 420,
 "ings": ["1 Vollkorn-Tortilla (oder Vollkorn-Fladenbrot)", "1 gekochtes, gezupftes Hähnchenfilet (ca. 120 g)",
          "1 EL Naturjoghurt ohne Zucker", "Salatblätter", "½ Tomate in Scheiben",
          "geriebene Möhre", "Salz, Pfeffer und etwas Senf nach Geschmack"],
 "passos": [
   "Koche die Hähnchenbrust etwa 15 Minuten in Salzwasser, bis sie innen weiß ist. Lass sie lauwarm werden und zupfe sie mit zwei Gabeln in Fasern auseinander.",
   "Vermische das gezupfte Hähnchen in einer Schüssel mit dem Joghurt, dem Senf, Salz und Pfeffer zu einer cremigen Füllung.",
   "Erwärme die Tortilla 20 Sekunden in einer Pfanne, nur damit sie weich und leicht zu rollen wird.",
   "Verteile die Salatblätter in der Mitte der Tortilla. Gib das cremige Hähnchen, die Tomate und die geriebene Möhre darauf.",
   "Klappe beide Seiten nach innen und rolle den Wrap von unten nach oben fest zusammen. Schneide ihn diagonal durch und serviere."],
 "porcoes8": ["100 g Hähnchen · ½ Tortilla · Salat",
              "120 g Hähnchen · 1 Tortilla · Salat",
              "130 g Hähnchen · 1 Tortilla · Salat",
              "150 g Hähnchen · 1 Tortilla · 1 gehäufter EL Joghurt",
              "150 g Hähnchen · 1 Tortilla · Salat",
              "170 g Hähnchen · 1 große Tortilla · Salat",
              "200 g Hähnchen · 2 Tortillas · Salat",
              "220 g Hähnchen · 2 Tortillas · Salat"],
 "dica": "Die Mayonnaise durch Naturjoghurt zu ersetzen spart einen großen Teil der Kalorien und bringt noch Eiweiß dazu. Gezupftes Hähnchen verteilt sich gut und gibt das Gefühl einer üppigen Füllung bei wenig Fett, und die Vollkorn-Tortilla hat mehr Ballaststoffe als Weißbrot und hält den Hunger länger fern.",
},
{
 "nome": "Gebackener Lachs mit Ofengemüse",
 "hook": "Alles auf einem Blech: der edelste Fisch fürs Herz, goldbraun gebacken zusammen mit buntem Gemüse.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 490,
 "ings": ["1 Lachsfilet (ca. 150 g)", "1 kleine Kartoffel in Scheiben", "1 Zucchini in Scheiben",
          "½ Paprika in Streifen", "Kirschtomaten", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und Rosmarin nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Schneide die Kartoffel in dünne Scheiben — so gart sie in derselben Zeit wie der Fisch.",
   "Verteile die Kartoffel, die Zucchini, die Paprika und die Kirschtomaten auf einem Backblech. Würze alles mit Salz, Pfeffer, Rosmarin und der Hälfte des Olivenöls und vermische es.",
   "Schiebe das Blech 10 Minuten in den Ofen, nur damit die Kartoffel weicher wird.",
   "Hole das Blech heraus, mache in der Mitte Platz und lege den Lachs hinein. Würze den Fisch mit Salz, Pfeffer, dem Zitronensaft und dem restlichen Olivenöl.",
   "Schiebe alles noch einmal 15 Minuten in den Ofen, bis der Lachs heller wird und sich beim Anstupsen mit der Gabel in Stücke teilen lässt. Serviere direkt vom Blech oder angerichtet auf dem Teller."],
 "porcoes8": ["120 g Lachs · ½ Kartoffel · Gemüse",
              "150 g Lachs · 1 kleine Kartoffel · Gemüse",
              "150 g Lachs · 1 Kartoffel · Gemüse",
              "170 g Lachs · 1 Kartoffel · etwas Olivenöl",
              "170 g Lachs · 1 Kartoffel · Gemüse",
              "200 g Lachs · 1 große Kartoffel · Gemüse",
              "220 g Lachs · 1 große Kartoffel · etwas Olivenöl",
              "250 g Lachs · 2 kleine Kartoffeln · etwas Olivenöl"],
 "dica": "Lachs ist reich an gutem Fett (Omega-3), das dem Herzen hilft und stark sättigt. Alles zusammen auf einem Blech zu backen braucht fast kein Öl und gibt dem Gemüse einen kräftigen Geschmack — ein vollständiges, schönes und leichtes Gericht mit dem kleinsten Aufwand.",
},
{
 "nome": "Süßkartoffel-Auflauf mit magerem Hackfleisch",
 "hook": "Der Trost eines cremigen Auflaufs, aber mit Süßkartoffelpüree und magerem Fleisch — pure Zufriedenheit, ohne schlechtes Gewissen.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 460,
 "ings": ["2 mittelgroße Süßkartoffeln", "250 g mageres Rinderhackfleisch", "1 Zwiebel, gehackt",
          "1 Knoblauchzehe, gehackt", "1 Tomate, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack", "1 EL magerer geriebener Käse"],
 "passos": [
   "Schäle die Süßkartoffeln, schneide sie in Stücke und koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich sind. Gieße sie ab und zerdrücke sie mit einer Gabel und einer Prise Salz zu einem glatten Püree.",
   "Erhitze das Olivenöl in einer Pfanne und brate die Zwiebel und den Knoblauch bei mittlerer Hitze 2 Minuten unter Rühren an, bis sie glasig sind.",
   "Gib das Hackfleisch dazu und rühre, dabei die Klumpen mit dem Löffel zerteilen, bis nichts mehr rosa ist.",
   "Gib die Tomate, Salz und Pfeffer dazu und koche alles noch 5 Minuten ein. Nimm die Pfanne vom Herd und rühre die Kräuter unter.",
   "Verteile die Hälfte des Pürees in einer Auflaufform, darauf das Fleisch und darüber das restliche Püree. Streue den geriebenen Käse darauf.",
   "Backe alles bei 200 °C 15 Minuten, bis die Oberfläche leicht goldbraun ist. Serviere es warm."],
 "porcoes8": ["½ Portion · grüner Salat",
              "1 Portion · grüner Salat",
              "1 Portion · grüner Salat",
              "1 Portion · 1 EL Käse mehr",
              "1 Portion + extra Fleisch · Salat",
              "1 große Portion · Salat",
              "1 große Portion + Fleisch · Salat",
              "doppelte Fleischportion · Salat"],
 "dica": "Die Süßkartoffel ersetzt die normale Kartoffel im Auflauf durch eine Variante mit mehr Ballaststoffen, die stärker sättigt. Das magere Fleisch liefert reichlich Eiweiß ohne das Übermaß an Fett von fettem Fleisch. Es ist genau die Art wohltuendes Gericht, das die Lust auf Ungesundes austrickst.",
},
{
 "nome": "Kompletter Salat mit Thunfisch, Kichererbsen und Ei",
 "hook": "Ohne Herd: ein richtiger Salat, der Teller und Bauch füllt und in fünf Minuten angerichtet ist.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 400,
 "ings": ["1 Dose Thunfisch in Wasser, abgetropft", "80 g gekochte Kichererbsen", "2 gekochte Eier",
          "gemischter Blattsalat", "½ Tomate in Würfeln", "½ Gurke in Scheiben", "rote Zwiebel in dünnen Ringen",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Koche die Eier: Gib sie mit Wasser in einen Topf, lass es aufkochen und zähle 9 Minuten. Halte sie unter kaltes Wasser, pelle sie und halbiere sie.",
   "Lass den Thunfisch und die Kichererbsen gut abtropfen.",
   "Verteile den Blattsalat auf einem Teller oder in einer großen Schüssel. Gib die Tomate, die Gurke und die Zwiebel darauf.",
   "Setze den Thunfisch in die Mitte, die Kichererbsen darum herum und die Eier an die Seiten.",
   "Beträufle alles mit dem Olivenöl und dem Zitronensaft, würze mit Salz und Pfeffer und serviere."],
 "porcoes8": ["½ Dose Thunfisch · 55 g Kichererbsen · 1 Ei",
              "1 Dose Thunfisch · 80 g Kichererbsen · 2 Eier",
              "1 Dose Thunfisch · 80 g Kichererbsen · 2 Eier",
              "1 Dose Thunfisch · 110 g Kichererbsen · 2 Eier · Avocado",
              "1 Dose Thunfisch · 110 g Kichererbsen · 2 Eier",
              "1½ Dosen Thunfisch · 125 g Kichererbsen · 2 Eier",
              "1½ Dosen Thunfisch · 165 g Kichererbsen · 3 Eier · Avocado",
              "2 Dosen Thunfisch · 165 g Kichererbsen · 3 Eier · Avocado"],
 "dica": "Das ist eine Eiweißbombe (Thunfisch, Ei und Kichererbsen zusammen), die kaum Arbeit macht. Das Eiweiß und die Ballaststoffe im Salat halten den Hunger stundenlang fern, und weil alles frisch ist und nichts in Öl gebraten wird, bleibt der Teller leicht, auch wenn er gut gefüllt ist.",
},
{
 "nome": "Leichtes Hähnchen-Stroganoff mit Reis",
 "hook": "Das cremige Stroganoff wie immer, nur mit Joghurt statt Sahne — gleicher Genuss, halb so viele Kalorien.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["2 Hähnchenbrustfilets in Würfeln (ca. 300 g)", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "70 g Champignonscheiben", "1 EL Tomatenmark",
          "4 EL Naturjoghurt ohne Zucker", "1 TL Olivenöl",
          "Salz, Pfeffer und Senf nach Geschmack", "weißer Reis oder Vollkornreis zum Servieren"],
 "passos": [
   "Würze die Hähnchenwürfel mit Salz und Pfeffer.",
   "Erhitze das Olivenöl in einem Topf bei mittlerer bis hoher Hitze und brate die Hähnchenwürfel 5 Minuten unter gelegentlichem Rühren rundherum an. Nimm sie heraus und stelle sie beiseite.",
   "Brate im selben Topf die Zwiebel und den Knoblauch 2 Minuten unter Rühren an, bis sie glasig sind. Gib die Champignons dazu und koche alles 3 Minuten weiter, bis sie zusammenfallen.",
   "Gib das Hähnchen zurück in den Topf, rühre das Tomatenmark und den Senf unter und lass alles 3 Minuten ziehen.",
   "Nimm den Topf vom Herd. Erst jetzt rührst du den Joghurt unter — vom Herd genommen gerinnt er nicht (bildet keine Klümpchen). Schmecke mit Salz ab und serviere alles über dem Reis."],
 "porcoes8": ["½ Portion · 3 EL Reis",
              "1 Portion · 4 EL Reis",
              "1 Portion · 5 EL Reis",
              "1 Portion · 5 EL Reis · extra Hähnchen",
              "1 Portion · 5 EL Reis",
              "1 große Portion · 6 EL Reis",
              "1 Portion + Hähnchen · 7 EL Reis",
              "doppelte Portion · 8 EL Reis"],
 "dica": "Das Geheimnis ist der Naturjoghurt anstelle der Sahne: Du behältst die Cremigkeit und den Geschmack, sparst aber Fett und gewinnst noch Eiweiß dazu. Das Hähnchen sättigt, und die Champignons bringen Volumen und Geschmack bei sehr wenigen Kalorien.",
},
{
 "nome": "Putenbrust mit Gemüse-Couscous",
 "hook": "Der Couscous ist nur mit heißem Wasser fertig — das schnellste und lockerste Mittagessen für volle Tage.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 430,
 "ings": ["1 Putenbrustfilet (ca. 150 g)", "90 g Couscous (die kleinen Kügelchen)",
          "120 ml heißes Wasser", "½ Zucchini in kleinen Würfeln", "½ Paprika in kleinen Würfeln", "Kirschtomaten, geschnitten",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer und Minze nach Geschmack"],
 "passos": [
   "Gib den Couscous in eine Schüssel, füge eine Prise Salz und das heiße Wasser dazu (das Wasser soll den Couscous einen Finger breit bedecken). Decke die Schüssel mit einem Teller ab und lass alles 5 Minuten stehen.",
   "Lockere den Couscous mit einer Gabel auf, gehe dabei durch die ganze Schüssel, bis er locker ist und nicht mehr klebt.",
   "Würze die Putenbrust mit Salz und Pfeffer. Erhitze eine beschichtete Pfanne mit der Hälfte des Olivenöls und brate die Pute 3 bis 4 Minuten je Seite, bis sie goldbraun und innen weiß ist.",
   "Gib die rohen Zucchini-, Paprika- und Tomatenwürfel, das restliche Olivenöl, den Zitronensaft und die Minze zum Couscous. Vermische alles.",
   "Serviere den Couscous mit der aufgeschnittenen Putenbrust darauf."],
 "porcoes8": ["120 g Pute · 60 g Couscous · Gemüse",
              "150 g Pute · 90 g Couscous · Gemüse",
              "150 g Pute · 90 g Couscous · Gemüse",
              "170 g Pute · 115 g Couscous · etwas Olivenöl",
              "170 g Pute · 115 g Couscous · Gemüse",
              "200 g Pute · 130 g Couscous · Gemüse",
              "220 g Pute · 175 g Couscous · etwas Olivenöl",
              "250 g Pute · 175 g Couscous · etwas Olivenöl"],
 "dica": "Putenbrust ist noch magerer als Hähnchen und steckt voller Eiweiß. Couscous gart nur mit heißem Wasser, ganz ohne Fett, und mit rohem Gemüse vermischt wird daraus ein leichtes, buntes und erfrischendes Gericht — perfekt für mittags.",
},
{
 "nome": "Chili mit Rindfleisch und schwarzen Bohnen",
 "hook": "Ein würziger, kräftiger Eintopf, der von innen wärmt — Bohnen, mageres Fleisch und viel Geschmack in einem Topf.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 450,
 "ings": ["300 g mageres Rinderhackfleisch", "170 g gekochte schwarze Bohnen (oder aus der Dose, abgetropft)",
          "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 Paprika, gehackt", "2 Tomaten, gehackt (oder Tomatensoße)",
          "1 TL Olivenöl", "1 TL gemahlener Kreuzkümmel", "Salz, Pfeffer und Paprikapulver nach Geschmack"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf bei mittlerer Hitze. Brate die Zwiebel, den Knoblauch und die Paprika 3 Minuten unter Rühren an, bis sie weich werden.",
   "Gib das Hackfleisch dazu und rühre, dabei die Klumpen mit dem Löffel zerteilen, bis nichts mehr rosa ist.",
   "Gib den Kreuzkümmel, das Paprikapulver, Salz und Pfeffer dazu und vermische alles gut, damit die Gewürze ihr Aroma abgeben.",
   "Gib die gehackten Tomaten und die schwarzen Bohnen dazu. Wenn es zu trocken wird, gieße 120 ml Wasser an.",
   "Stelle die Hitze klein und lass alles 15 bis 20 Minuten bei kleiner Hitze köcheln, dabei ab und zu umrühren, bis ein sämiger Eintopf entsteht. Serviere ihn pur oder mit etwas Reis."],
 "porcoes8": ["½ Portion · Salat",
              "1 Portion · Salat",
              "1 Portion · 2 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 große Portion · 4 EL Reis",
              "1 große Portion · 5 EL Reis",
              "doppelte Portion · 5 EL Reis"],
 "dica": "Schwarze Bohnen sind Spitzenreiter bei Ballaststoffen und pflanzlichem Eiweiß, und zusammen mit dem mageren Fleisch machen sie das Gericht bei wenigen Kalorien sehr sättigend. Der Eintopf reicht weit, hält sich gut im Kühlschrank und stillt die Lust auf warmes, würziges Essen, ohne aus der Spur zu bringen.",
},
{
 "nome": "Vollkornnudeln mit Tomatensoße und Putenbällchen",
 "hook": "Ja, du kannst beim Abnehmen Nudeln essen — als Vollkornvariante, mit frischer Soße und mageren Fleischbällchen.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 480,
 "ings": ["150 g Vollkornnudeln (Trockengewicht)", "250 g Putenhackfleisch (oder Hähnchenhack)",
          "3 reife Tomaten, gehackt (oder Tomatensoße)", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt",
          "1 Ei", "2 EL Haferflocken", "1 TL Olivenöl", "Salz, Pfeffer und Basilikum nach Geschmack"],
 "passos": [
   "Vermische das Putenhack, das Ei, die Haferflocken, die Hälfte des Knoblauchs, Salz und Pfeffer in einer Schüssel. Knete alles mit den Händen, bis es bindet, und forme Bällchen von der Größe einer Walnuss.",
   "Erhitze das Olivenöl in einem weiten Topf und brate die Bällchen rundherum an, dabei vorsichtig drehen, etwa 5 Minuten. Nimm sie heraus und stelle sie beiseite.",
   "Brate im selben Topf die Zwiebel und den restlichen Knoblauch 2 Minuten an. Gib die gehackten Tomaten, Salz und Pfeffer dazu und koche alles 10 Minuten unter Rühren, bis eine Soße entsteht.",
   "Gib die Bällchen zurück in die Soße und lass sie noch 8 Minuten garen, bis sie innen durch sind.",
   "Koche währenddessen die Nudeln in kochendem Salzwasser nach Packungsangabe, bis sie gar, aber noch bissfest sind. Gieße sie ab.",
   "Vermische die Nudeln mit der Soße und den Bällchen, streue das Basilikum darüber und serviere."],
 "porcoes8": ["⅔ Portion Nudeln · 3 Bällchen",
              "1 Portion · 4 Bällchen",
              "1 Portion · 4 Bällchen",
              "1 Portion · 5 Bällchen",
              "1 Portion · 5 Bällchen",
              "1 große Portion · 6 Bällchen",
              "große Portion · 7 Bällchen",
              "doppelte Portion · 8 Bällchen"],
 "dica": "Vollkornnudeln haben mehr Ballaststoffe und sättigen stärker als normale, und die Putenbällchen liefern mageres Eiweiß anstelle von fettem Fleisch. Eine frisch gekochte Tomatensoße ohne Zucker und ohne Fertigprodukte macht das Gericht schmackhaft und viel leichter.",
},
{
 "nome": "Gefülltes Omelett mit Gemüse",
 "hook": "Ein leichtes Mittagessen für Tage ohne Zeit: locker, warm und voller Eiweiß, in zehn Minuten aus der Pfanne.",
 "tempo": "12 Min.", "rende": "1 Portion", "kcal_base": 360,
 "ings": ["3 Eier", "½ Tomate in kleinen Würfeln", "½ Paprika in kleinen Würfeln", "1 Handvoll Spinat",
          "1 EL heller Käse in Würfeln", "1 TL Olivenöl",
          "Schnittlauch, Salz und Pfeffer nach Geschmack", "1 Scheibe Vollkornbrot (nach Wunsch)"],
 "passos": [
   "Schlage die Eier in eine Schüssel, würze sie mit Salz und Pfeffer und verquirle sie 30 Sekunden mit einer Gabel, bis alles gut vermischt ist.",
   "Erhitze das Olivenöl in einer beschichteten Pfanne bei mittlerer bis kleiner Hitze. Gib die Paprika und den Spinat dazu und rühre 1 Minute, nur bis der Spinat zusammenfällt.",
   "Verteile das Gemüse in der Pfanne und gieße die Eier darüber. Lass alles 1 Minute stehen, ohne zu rühren, bis der Rand fest wird.",
   "Gib die Tomate und den Käse auf eine Hälfte des Omeletts. Klappe die andere Hälfte mit einem Pfannenwender darüber, sodass ein Halbmond entsteht.",
   "Lass es noch 1 Minute, nur bis der Käse weich wird. Streue Schnittlauch darüber und serviere, wenn du magst mit der Scheibe Brot."],
 "porcoes8": ["2 Eier · Gemüse · ½ Scheibe Brot",
              "3 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 1 Scheibe Brot",
              "3 Eier · 2 EL Käse · 1 Scheibe Brot",
              "3 Eier · Gemüse · 1 Scheibe Brot",
              "4 Eier · Gemüse · 1 Scheibe Brot",
              "4 Eier · 2 EL Käse · 2 Scheiben Brot",
              "5 Eier · Gemüse · 2 Scheiben Brot"],
 "dica": "Eier sind Eiweiß von höchster Qualität und machen sehr satt — wer mittags Eier isst, nascht nachmittags meist weniger. Mit Gemüse gefüllt gewinnt das Omelett Volumen, Farbe und Ballaststoffe, fast ohne Kalorien dazuzurechnen, und wird zu einer vollständigen, schnellen Mahlzeit.",
},
{
 "nome": "Mageres Rindersteak mit Reis, Bohnen und Grünkohl",
 "hook": "Das Alltagsgericht, so wie wir es lieben — nur im richtigen Maß, mit magerem Fleisch und leicht gebratenem Grünkohl.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 500,
 "ings": ["1 mageres Rindersteak (aus der Oberschale, ca. 130 g)", "4 EL gekochter Reis",
          "4 EL gekochte Bohnen", "2 Blätter Grünkohl in feinen Streifen",
          "1 Knoblauchzehe, gehackt", "1 TL Olivenöl", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Würze das Steak von beiden Seiten mit Salz und Pfeffer.",
   "Erhitze eine beschichtete Pfanne bei hoher Hitze mit ein paar Tropfen Olivenöl. Lege das Steak hinein und lass es 2 bis 3 Minuten je Seite braten, ohne daran zu rühren, bis es außen goldbraun und innen so ist, wie du es magst.",
   "Schneide den Grünkohl in sehr feine Streifen. Erhitze das restliche Olivenöl in einer Pfanne und brate den Knoblauch 30 Sekunden an, nur bis er duftet.",
   "Gib den Grünkohl dazu und rühre ihn bei hoher Hitze 1 bis 2 Minuten, nur bis er etwas zusammenfällt und noch grün ist. Würze mit Salz.",
   "Wärme den Reis und die Bohnen auf. Richte den Teller mit dem Reis, den Bohnen, dem Steak und dem Grünkohl daneben an."],
 "porcoes8": ["100 g Fleisch · 3 EL Reis · 3 EL Bohnen",
              "130 g Fleisch · 4 EL Reis · 4 EL Bohnen",
              "130 g Fleisch · 5 EL Reis · 4 EL Bohnen",
              "150 g Fleisch · 5 EL Reis · 5 EL Bohnen",
              "150 g Fleisch · 5 EL Reis · 5 EL Bohnen",
              "170 g Fleisch · 6 EL Reis · 5 EL Bohnen",
              "200 g Fleisch · 7 EL Reis · 6 EL Bohnen",
              "220 g Fleisch · 8 EL Reis · 6 EL Bohnen"],
 "dica": "Du kannst das klassische Gericht aus Reis, Bohnen und Fleisch essen, ohne die Diät zu verlassen: Der Schlüssel ist ein mageres Stück Fleisch, abgemessener Reis und abgemessene Bohnen und reichlich Grünkohl, der den Teller mit Ballaststoffen und fast keinen Kalorien füllt. Die Bohnen bringen zusätzlich Ballaststoffe und Eiweiß, die den Hunger fernhalten.",
},
{
 "nome": "Steak mit gerösteten Zwiebeln, Kartoffelpüree und Salat",
 "hook": "Steak mit goldbraunen Zwiebeln ist purer Trost — auf einem leichten Püree und neben frischem Salat passt es genau in die Diät.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 500,
 "ings": ["1 mageres Rindersteak (Oberschale oder Hüfte, ca. 130 g)", "2 mittelgroße Kartoffeln", "1 Zwiebel in Ringen",
          "1 TL Olivenöl", "Salz und Pfeffer nach Geschmack", "Blattsalat und Tomate für den Salat",
          "Saft von ½ Zitrone"],
 "passos": [
   "Schäle die Kartoffeln und koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich sind. Gieße sie ab und zerdrücke sie mit einer Gabel und einer Prise Salz zu einem glatten Püree. Für mehr Cremigkeit gib etwas Kochwasser dazu.",
   "Würze das Steak von beiden Seiten mit Salz und Pfeffer.",
   "Erhitze eine beschichtete Pfanne bei hoher Hitze mit ein paar Tropfen Olivenöl. Lege das Steak hinein und lass es 2 bis 3 Minuten je Seite braten, ohne daran zu rühren, bis es außen goldbraun und innen nach deinem Geschmack ist. Nimm es heraus und stelle es beiseite.",
   "Gib die Zwiebelringe und das restliche Olivenöl in dieselbe Pfanne. Rühre sie bei mittlerer Hitze 5 Minuten, bis die Zwiebel weich und goldbraun (schön süß) ist.",
   "Bedecke das Steak mit den goldbraunen Zwiebeln. Richte den Teller mit dem Püree, dem Steak und einem grünen Salat mit Zitrone an."],
 "porcoes8": ["100 g Fleisch · ½ Portion Püree · Salat",
              "130 g Fleisch · 1 Portion Püree · Salat",
              "130 g Fleisch · 1 Portion Püree · Salat",
              "150 g Fleisch · 1 Portion Püree · Salat",
              "150 g Fleisch · 1 Portion Püree · Salat",
              "170 g Fleisch · 1 große Portion Püree · Salat",
              "200 g Fleisch · große Portion Püree · Salat",
              "220 g Fleisch · doppelte Portion Püree · Salat"],
 "dica": "Mit einem mageren Stück Fleisch und ohne Öl gebraten wird das Steak zu fast reinem Eiweiß. Die goldbraune Zwiebel bringt sehr viel Geschmack bei kaum Kalorien und macht fettige Soßen überflüssig. Mit abgemessenem Püree und reichlich Salat sättigt der Teller, ohne schwer zu liegen.",
},
{
 "nome": "Garnelen aus der Pfanne mit Gemüse und Reis",
 "hook": "Garnelen sind im Handumdrehen fertig und leicht wie kaum etwas anderes — ein schnelles Mittagessen mit edler Wirkung.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 430,
 "ings": ["150 g geputzte Garnelen", "4 EL gekochter Vollkornreis", "½ Zucchini in Halbmonden",
          "½ Paprika in Streifen", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Würze die Garnelen mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft. Lass sie 5 Minuten Geschmack annehmen.",
   "Erhitze eine große Pfanne mit der Hälfte des Olivenöls bei hoher Hitze. Gib die Zucchini und die Paprika dazu und rühre 3 Minuten, bis sie weich, aber noch fest sind. Nimm sie heraus und stelle sie beiseite.",
   "Gib das restliche Olivenöl und die Garnelen in dieselbe Pfanne. Brate sie bei hoher Hitze unter Rühren 2 bis 3 Minuten an, nur bis sie rosa werden und sich einrollen. Pass auf, dass sie nicht zu lange braten, sonst werden sie gummiartig.",
   "Gib das Gemüse zurück in die Pfanne, füge den bereits gekochten Vollkornreis dazu und vermische alles 1 Minute, nur um es zu erwärmen.",
   "Streue Petersilie darüber und serviere sofort."],
 "porcoes8": ["120 g Garnelen · 3 EL Reis · Gemüse",
              "150 g Garnelen · 4 EL Reis · Gemüse",
              "150 g Garnelen · 5 EL Reis · Gemüse",
              "170 g Garnelen · 5 EL Reis · etwas Olivenöl",
              "170 g Garnelen · 5 EL Reis · Gemüse",
              "200 g Garnelen · 6 EL Reis · Gemüse",
              "220 g Garnelen · 7 EL Reis · etwas Olivenöl",
              "250 g Garnelen · 8 EL Reis · etwas Olivenöl"],
 "dica": "Garnelen bestehen fast nur aus Eiweiß, mit sehr wenig Fett und wenigen Kalorien, du kannst dir also gut auffüllen, ohne dass es schwer wird. Kurz bei hoher Hitze mit Gemüse gebraten behalten sie ihren Biss und ihren Geschmack — ein leichtes Gericht, das in Minuten fertig ist.",
},
{
 "nome": "Leichtes Hähnchen-Pfannengericht mit Vollkornreis",
 "hook": "Der chinesische Klassiker zu Hause, in der mageren Variante: Hähnchenwürfel und knackiges Gemüse in einer leichten, glänzenden Soße.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 460,
 "ings": ["2 Hähnchenbrustfilets in Würfeln (ca. 300 g)", "1 Paprika in Würfeln", "1 Zwiebel in Würfeln",
          "1 Stange Staudensellerie in Stücken (nach Wunsch)", "1 Knoblauchzehe, gehackt", "1 EL helle Sojasoße",
          "1 TL Speisestärke", "1 TL Olivenöl", "Vollkornreis zum Servieren"],
 "passos": [
   "Würze die Hähnchenwürfel mit etwas Sojasoße und dem Knoblauch. Lass sie 5 Minuten Geschmack annehmen.",
   "Löse die Speisestärke in 120 ml Wasser mit der restlichen Sojasoße auf. Rühre alles gut um und stelle es beiseite — das bindet später die Soße.",
   "Erhitze eine große Pfanne mit der Hälfte des Olivenöls bei hoher Hitze. Brate die Hähnchenwürfel 5 Minuten unter Rühren an, bis sie innen weiß sind. Nimm sie heraus und stelle sie beiseite.",
   "Gib das restliche Olivenöl in dieselbe Pfanne und dazu die Paprika, die Zwiebel und den Sellerie. Rühre alles bei hoher Hitze 3 Minuten, bis es weich, aber noch knackig ist.",
   "Gib das Hähnchen zurück, rühre die Stärkemischung um und gieße sie in die Pfanne. Rühre 1 bis 2 Minuten, bis die Soße andickt und glänzend alles überzieht. Serviere über dem Vollkornreis."],
 "porcoes8": ["½ Portion · 3 EL Reis",
              "1 Portion · 4 EL Reis",
              "1 Portion · 5 EL Reis",
              "1 Portion · 5 EL Reis · extra Hähnchen",
              "1 Portion · 5 EL Reis",
              "1 große Portion · 6 EL Reis",
              "1 Portion + Hähnchen · 7 EL Reis",
              "doppelte Portion · 8 EL Reis"],
 "dica": "Zu Hause bestimmst du selbst über das Öl und den Zucker, mit denen Restaurants übertreiben. Das Hähnchen liefert mageres Eiweiß, das Gemüse bleibt knackig bei wenigen Kalorien, und nur ein Hauch Stärke gibt die schöne Soße, ohne das Gericht schwer zu machen.",
},
{
 "nome": "Mexikanische Bowl mit Rindfleisch, schwarzen Bohnen und Mais",
 "hook": "Alle Farben und Aromen Mexikos in einer Schüssel — üppig, würzig und überraschend leicht.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 490,
 "ings": ["250 g mageres Rinderhackfleisch", "170 g gekochte schwarze Bohnen", "80 g Mais",
          "4 EL gekochter Reis", "1 Tomate in Würfeln", "½ Avocado in Scheiben",
          "Blattsalat", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Kreuzkümmel, Salz, Pfeffer und Koriander nach Geschmack", "Saft von ½ Zitrone"],
 "passos": [
   "Erhitze das Olivenöl in einer Pfanne und brate den Knoblauch 30 Sekunden an. Gib das Hackfleisch dazu und rühre, dabei die Klumpen zerteilen, bis nichts mehr rosa ist.",
   "Würze das Fleisch mit Kreuzkümmel, Salz und Pfeffer und koche es 3 Minuten weiter. Gib die schwarzen Bohnen und den Mais dazu und erwärme alles 2 Minuten.",
   "Lege in einer Schüssel ein Bett aus Blattsalat an und gib den Reis an eine Seite.",
   "Verteile darüber das Fleisch mit den Bohnen und dem Mais, die Tomate und die Avocadoscheiben.",
   "Beträufle alles mit dem Zitronensaft, streue Koriander darüber und serviere."],
 "porcoes8": ["½ Portion · 3 EL Reis · ¼ Avocado",
              "1 Portion · 4 EL Reis · ¼ Avocado",
              "1 Portion · 4 EL Reis · ½ Avocado",
              "1 Portion · 5 EL Reis · ½ Avocado",
              "1 Portion · 5 EL Reis · ½ Avocado",
              "1 große Portion · 6 EL Reis · ½ Avocado",
              "große Portion · 7 EL Reis · ½ Avocado",
              "doppelte Portion · 8 EL Reis · Avocado"],
 "dica": "Das ist eine vollständige Mahlzeit in einer einzigen Schüssel: Eiweiß aus dem Fleisch, Ballaststoffe aus Bohnen und Mais und das gute Fett der Avocado, das Cremigkeit und Sättigung bringt. Gut gewürzt stillt es die Lust auf deftiges Essen ohne das Übermaß an Fett.",
},
{
 "nome": "Salat mit gegrilltem Hähnchen und Mango",
 "hook": "Süß, herzhaft und erfrischend: warmes gegrilltes Hähnchen trifft süße Mango in einem Salat, der nicht nach Diät schmeckt.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 400,
 "ings": ["1 Hähnchenbrustfilet (ca. 130 g)", "gemischter Blattsalat", "½ Mango in Würfeln",
          "½ Gurke in Scheiben", "rote Zwiebel in dünnen Ringen", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Minze nach Geschmack"],
 "passos": [
   "Würze das Hähnchen mit Salz und Pfeffer. Erhitze eine beschichtete Pfanne bei mittlerer bis hoher Hitze und brate das Filet 4 bis 5 Minuten je Seite, bis es goldbraun und innen weiß ist. Lass es lauwarm werden und schneide es in Streifen.",
   "Schäle die Mango und schneide das Fruchtfleisch in Würfel. Schneide die Gurke in Scheiben und die Zwiebel in sehr dünne Ringe.",
   "Verteile den Blattsalat in einer großen Schüssel oder auf einem tiefen Teller.",
   "Gib darauf die Mangowürfel, die Gurke, die Zwiebel und die Hähnchenstreifen.",
   "Rühre für das Dressing das Olivenöl, den Zitronensaft, Salz und Pfeffer zusammen. Beträufle den Salat damit, streue Minze darüber und serviere."],
 "porcoes8": ["100 g Hähnchen · ¼ Mango · Salat",
              "130 g Hähnchen · ½ Mango · Salat",
              "130 g Hähnchen · ½ Mango · Salat",
              "150 g Hähnchen · ½ Mango · etwas Olivenöl",
              "150 g Hähnchen · ½ Mango · Salat",
              "170 g Hähnchen · ½ Mango · 1 EL Nüsse",
              "200 g Hähnchen · 1 Mango · Nüsse",
              "220 g Hähnchen · 1 Mango · Nüsse"],
 "dica": "Die Mango kommt als natürliche Süße ohne zugesetzten Zucker dazu und stillt die Lust auf Süßes mitten in einer herzhaften Mahlzeit. Das gegrillte Hähnchen liefert das sättigende Eiweiß, und die Menge an Blättern und Gemüse füllt den Teller mit sehr wenigen Kalorien. Ein Salat, der eine vollständige Mahlzeit ist.",
},
{
 "nome": "Hähnchenfilet in leichtem Curry mit Reis",
 "hook": "Eine goldene, duftende Soße, die das gewohnte Hähnchen verwandelt — cremig ohne Sahne, mit leichter Kokosmilch.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["2 Hähnchenbrustfilets in Würfeln (ca. 300 g)", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Currypulver", "120 ml leichte Kokosmilch (oder normale Milch)",
          "1 Tomate, gehackt", "1 TL Olivenöl", "Salz und Pfeffer nach Geschmack", "Reis zum Servieren"],
 "passos": [
   "Würze die Hähnchenwürfel mit Salz, Pfeffer und der Hälfte des Currypulvers.",
   "Erhitze das Olivenöl in einem Topf bei mittlerer Hitze und brate die Hähnchenwürfel 5 Minuten unter Rühren rundherum an. Nimm sie heraus und stelle sie beiseite.",
   "Brate im selben Topf die Zwiebel und den Knoblauch 2 Minuten an. Gib das restliche Currypulver dazu und rühre 30 Sekunden, nur damit das Gewürz seinen Duft abgibt.",
   "Gib die Tomate dazu und koche sie 3 Minuten, bis sie zerfällt. Gib das Hähnchen zurück und gieße die Kokosmilch an.",
   "Lass alles 8 bis 10 Minuten bei kleiner Hitze köcheln, dabei ab und zu umrühren, bis die Soße andickt und das Hähnchen zart ist. Serviere über dem Reis."],
 "porcoes8": ["½ Portion · 3 EL Reis",
              "1 Portion · 4 EL Reis",
              "1 Portion · 5 EL Reis",
              "1 Portion · 5 EL Reis · extra Hähnchen",
              "1 Portion · 5 EL Reis",
              "1 große Portion · 6 EL Reis",
              "1 Portion + Hähnchen · 7 EL Reis",
              "doppelte Portion · 8 EL Reis"],
 "dica": "Leichte Kokosmilch macht die Soße cremig mit viel weniger Fett als Sahne. Das Curry duftet und lässt das Gericht besonders wirken, was hilft, langsam zu essen und mit einer abgemessenen Portion Hähnchen und Reis zufrieden zu sein.",
},
{
 "nome": "Gebackene Sardinen mit Kartoffeln und Salat",
 "hook": "Günstig, voller Omega-3 und in Minuten fertig — die Sardine ist eine der besten Freundinnen von allen, die mit wenig Geld abnehmen wollen.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 450,
 "ings": ["3 bis 4 frische, geputzte Sardinen (oder 1 Dose Sardinen in Wasser)", "1 kleine Kartoffel in Scheiben",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "1 Knoblauchzehe, gehackt",
          "Salz, Pfeffer und Oregano nach Geschmack", "Blattsalat und Tomate für den Salat"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Schneide die Kartoffel in dünne Scheiben, würze sie mit Salz und der Hälfte des Olivenöls und verteile sie auf einem Backblech.",
   "Schiebe die Kartoffel 10 Minuten in den Ofen, damit sie weicher wird.",
   "Würze die Sardinen mit Salz, Pfeffer, Knoblauch, Oregano und dem Zitronensaft.",
   "Hole das Blech heraus, lege die Sardinen zwischen die Kartoffeln und beträufle alles mit dem restlichen Olivenöl.",
   "Schiebe alles noch einmal 15 Minuten in den Ofen, bis die Sardinen goldbraun und die Kartoffeln weich sind. Serviere mit einem frischen grünen Salat daneben.",
   "Wenn du Sardinen aus der Dose nimmst, lass den Ofen für den Fisch aus: Backe nur die Kartoffel und richte den Teller mit den abgetropften Sardinen und dem Salat an."],
 "porcoes8": ["2 Sardinen · ½ Kartoffel · Salat",
              "3 Sardinen · 1 kleine Kartoffel · Salat",
              "3 Sardinen · 1 Kartoffel · Salat",
              "4 Sardinen · 1 Kartoffel · etwas Olivenöl",
              "4 Sardinen · 1 Kartoffel · Salat",
              "4 Sardinen · 1 große Kartoffel · Salat",
              "5 Sardinen · 1 große Kartoffel · etwas Olivenöl",
              "6 Sardinen · 2 kleine Kartoffeln · Salat"],
 "dica": "Die Sardine ist ein kleiner, kräftiger Fisch: viel Omega-3 (das gute Fett, das dem Herzen hilft), Eiweiß und Kalzium, zu einem sehr niedrigen Preis. Mit etwas Kartoffel gebacken und einem frischen Salat wird daraus ein vollständiges, nahrhaftes und günstiges Mittagessen.",
},
{
 "nome": "Gefüllte Aubergine mit Hackfleisch",
 "hook": "Die Aubergine wird selbst zur Schüssel — gefüllt mit gewürztem Fleisch und überbacken ist sie schön und trickst jede Lust auf Völlerei aus.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 420,
 "ings": ["1 große Aubergine", "200 g mageres Rinderhackfleisch", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 Tomate, gehackt", "1 TL Olivenöl", "2 EL magerer geriebener Käse",
          "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Halbiere die Aubergine der Länge nach. Hole mit einem Löffel einen Teil des Inneren heraus, sodass zwei 'Boote' entstehen. Hacke das herausgeholte Innere klein.",
   "Lege die Boote auf ein Backblech, beträufle sie mit etwas Olivenöl und backe sie 10 Minuten, nur damit sie weicher werden.",
   "Brate währenddessen in einer Pfanne die Zwiebel und den Knoblauch im restlichen Olivenöl 2 Minuten an. Gib das Hackfleisch dazu und rühre, bis nichts mehr rosa ist.",
   "Gib die Tomate, das gehackte Innere der Aubergine, Salz und Pfeffer dazu und koche alles 5 Minuten, bis eine weiche Füllung entsteht.",
   "Fülle die Auberginenboote mit dem Fleisch, streue den geriebenen Käse darüber und backe alles noch 15 Minuten, bis der Käse geschmolzen und goldbraun ist. Streue Petersilie darüber und serviere."],
 "porcoes8": ["½ Aubergine · Salat",
              "1 gefüllte Aubergine · Salat",
              "1 Aubergine · 2 EL Reis",
              "1 Aubergine · extra Fleisch · Salat",
              "1 Aubergine · extra Fleisch · 2 EL Reis",
              "1 große Aubergine · 3 EL Reis",
              "1 Aubergine · doppelt Fleisch · 4 EL Reis",
              "Aubergine + extra Fleischportion · 4 EL Reis"],
 "dica": "Die Aubergine enthält viel Wasser und Ballaststoffe, sie füllt den Magen also mit sehr wenigen Kalorien — gefüllt gibt sie dem Teller Volumen und sättigt. Das magere Fleisch bringt das Eiweiß, und etwas Käse obendrauf stillt die Lust auf Überbackenes, ohne zu übertreiben.",
},
{
 "nome": "Leichter Caesar-Salat mit gegrilltem Hähnchen",
 "hook": "Der cremige Caesar-Salat, den du liebst, mit einem cleveren Joghurt-Dressing — die ganze Cremigkeit, kein schlechtes Gewissen.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 400,
 "ings": ["1 gegrilltes Hähnchenfilet in Streifen (ca. 130 g)", "Römersalat", "1 Scheibe Vollkornbrot in Würfeln",
          "2 EL Naturjoghurt ohne Zucker", "1 TL Senf",
          "1 TL geriebener Käse", "Saft von ½ Zitrone", "1 Knoblauchzehe, zerdrückt", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Würze das Hähnchen mit Salz und Pfeffer und brate es in einer beschichteten Pfanne 4 Minuten je Seite, bis es goldbraun und innen weiß ist. Schneide es in Streifen.",
   "Mache die Croûtons: Verteile die Vollkornbrotwürfel auf einem Backblech und backe sie 8 Minuten bei mittlerer Hitze, bis sie knusprig sind (oder röste sie in einer Pfanne ohne Öl).",
   "Rühre das Dressing an: Vermische in einer kleinen Schüssel den Joghurt, den Senf, den geriebenen Käse, den Zitronensaft, den zerdrückten Knoblauch, Salz und Pfeffer zu einer Creme.",
   "Zupfe den Salat mit den Händen in eine große Schüssel. Gieße das Dressing darüber und vermische alles, damit die Blätter bedeckt sind.",
   "Gib die Hähnchenstreifen und die Croûtons darauf und serviere sofort, damit das Brot knusprig bleibt."],
 "porcoes8": ["100 g Hähnchen · Salat · wenige Croûtons",
              "130 g Hähnchen · Salat · Croûtons",
              "130 g Hähnchen · Salat · Croûtons",
              "150 g Hähnchen · Salat · 1 EL Käse mehr",
              "150 g Hähnchen · Salat · Croûtons",
              "170 g Hähnchen · Salat · Croûtons",
              "200 g Hähnchen · Salat · extra Croûtons",
              "220 g Hähnchen · Salat · extra Croûtons"],
 "dica": "Das klassische Caesar-Dressing ist eine Bombe aus Mayonnaise und Öl. Ersetzt durch Joghurt mit Senf und Zitrone behältst du die Cremigkeit und den kräftigen Geschmack bei viel weniger Fett. Das gegrillte Hähnchen macht aus dem Salat eine richtige Mahlzeit, voller Eiweiß.",
},
{
 "nome": "Rindfleischstreifen mit Paprika und Reis",
 "hook": "Fein geschnittene Fleischstreifen mit bunter Paprika aus der Pfanne — duftend, würzig und in Minuten fertig.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["250 g mageres Rindfleisch in feinen Streifen (Hüfte oder Oberschale)", "1 rote Paprika in Streifen",
          "1 gelbe Paprika in Streifen", "1 Zwiebel in Streifen", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Kreuzkümmel, Salz, Pfeffer und Koriander nach Geschmack",
          "Reis zum Servieren"],
 "passos": [
   "Würze die Fleischstreifen mit Salz, Pfeffer, Kreuzkümmel, dem Knoblauch und dem Zitronensaft. Lass sie 10 Minuten Geschmack annehmen.",
   "Erhitze eine große Pfanne mit der Hälfte des Olivenöls bei hoher Hitze. Gib das Fleisch nach und nach hinein (nicht alles auf einmal, sonst zieht es Wasser) und brate es unter Rühren 3 Minuten scharf an. Nimm es heraus und stelle es beiseite.",
   "Gib in dieselbe Pfanne mit dem restlichen Olivenöl die Zwiebel und die Paprika. Rühre alles bei hoher Hitze 4 Minuten, bis es weich, aber noch fest und farbig ist.",
   "Gib das Fleisch zurück in die Pfanne und vermische alles 1 Minute, nur damit sich die Aromen verbinden.",
   "Streue Koriander darüber und serviere über einer Portion Reis. Es schmeckt auch hervorragend in einer Vollkorn-Tortilla gerollt."],
 "porcoes8": ["½ Portion · 3 EL Reis",
              "1 Portion · 4 EL Reis",
              "1 Portion · 5 EL Reis",
              "1 Portion · 5 EL Reis · extra Fleisch",
              "1 Portion · 5 EL Reis",
              "1 große Portion · 6 EL Reis",
              "1 Portion + Fleisch · 7 EL Reis",
              "doppelte Portion · 8 EL Reis"],
 "dica": "Das Fleisch in feine Streifen zu schneiden reicht weiter: Eine kleine Portion sieht auf dem Teller nach viel mehr aus. Kurz bei hoher Hitze mit Paprika gebraten bleibt es saftig und voller Geschmack, ganz ohne fettige Soße. Die Paprika bringt Farbe, Vitamine und Ballaststoffe für fast keine Kalorien.",
},
{
 "nome": "Selbst gemachter Burger aus magerem Rindfleisch mit Salat",
 "hook": "Der Burger, der die Lust stillt und beim Abnehmen hilft — zu Hause aus magerem Fleisch gemacht, ohne fettiges Brötchen.",
 "tempo": "20 Min.", "rende": "2 Portionen", "kcal_base": 440,
 "ings": ["250 g mageres Rinderhackfleisch", "½ Zwiebel, fein gehackt", "1 Knoblauchzehe, gehackt",
          "Salz, Pfeffer und Petersilie nach Geschmack", "1 TL Olivenöl", "2 Vollkornbrötchen",
          "Salatblätter, Tomate und Zwiebel in Ringen zum Belegen"],
 "passos": [
   "Vermische das Hackfleisch in einer Schüssel mit der gehackten Zwiebel, dem Knoblauch, Salz, Pfeffer und Petersilie. Knete es mit den Händen nur so lange, bis es bindet, nicht länger (sonst wird der Burger zäh).",
   "Teile das Fleisch in zwei Teile und forme zwei Scheiben, die du mit den Händen gut flach drückst. Drücke mit dem Daumen eine leichte Mulde in die Mitte jeder Scheibe — so wölben sie sich beim Braten nicht auf.",
   "Erhitze eine beschichtete Pfanne mit ein paar Tropfen Olivenöl bei mittlerer bis hoher Hitze. Lege die Burger hinein und brate sie 3 bis 4 Minuten je Seite, ohne sie mit dem Pfannenwender anzudrücken, bis sie außen goldbraun und innen wie gewünscht sind.",
   "Wenn du magst, röste die aufgeschnittenen Vollkornbrötchen kurz in der Pfanne.",
   "Baue alles auf: Brötchen, Salat, der Burger, die Tomate und die Zwiebel. Klappe es zu und serviere. Für eine noch leichtere Variante isst du den Burger ohne Brötchen, mit einer gut gefüllten Portion Salat daneben."],
 "porcoes8": ["1 Burger · ohne Brötchen · Salat",
              "1 Burger · ½ Brötchen · Salat",
              "1 Burger · 1 Brötchen · Salat",
              "1 Burger · 1 Brötchen · Salat",
              "1 großer Burger · 1 Brötchen · Salat",
              "1 großer Burger · 1 Brötchen · Salat",
              "2 Burger · 1 Brötchen · Salat",
              "2 Burger · 1 Brötchen · Salat"],
 "dica": "Das Problem am Imbiss-Burger sind das fette Fleisch, die Soße und das Frittierte. Zu Hause aus magerem Fleisch und ohne Öl gebraten wird er zu reinem Eiweiß. Mit reichlich Salat und wenig (oder gar keinem) Brötchen stillst du die Lust, ohne die Kalorien zu sprengen.",
},
{
 "nome": "Weißer Fisch mit Gemüse und Couscous",
 "hook": "Ein zartes weißes Filet auf lockerem Couscous — leicht, elegant und fertig, bevor du es merkst.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 420,
 "ings": ["1 Filet vom weißen Fisch (Seehecht, Kabeljau oder Tilapia, ca. 150 g)", "90 g Couscous",
          "120 ml heißes Wasser", "130 g gewürfeltes Gemüse (grüne Bohnen, Möhre, Erbsen)",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Gib den Couscous mit einer Prise Salz in eine Schüssel, gieße das heiße Wasser darüber, decke sie mit einem Teller ab und lass alles 5 Minuten stehen. Lockere ihn danach mit einer Gabel auf, bis er locker ist.",
   "Gare das gewürfelte Gemüse im Dampf oder in wenig kochendem Wasser 5 Minuten, bis es weich, aber noch fest ist. Gieße es ab.",
   "Würze den Fisch mit Salz, Pfeffer und dem Zitronensaft.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze. Lege das Filet hinein und lass es 3 bis 4 Minuten je Seite braten, dabei einmal vorsichtig wenden, bis es goldbraun ist und sich mit der Gabel in Stücke teilen lässt.",
   "Vermische das Gemüse mit dem Couscous. Richte den Teller mit dem Gemüse-Couscous an und lege das Filet darauf. Streue Petersilie darüber und serviere."],
 "porcoes8": ["120 g Fisch · 60 g Couscous · Gemüse",
              "150 g Fisch · 90 g Couscous · Gemüse",
              "150 g Fisch · 90 g Couscous · Gemüse",
              "170 g Fisch · 115 g Couscous · etwas Olivenöl",
              "170 g Fisch · 115 g Couscous · Gemüse",
              "200 g Fisch · 130 g Couscous · Gemüse",
              "220 g Fisch · 175 g Couscous · etwas Olivenöl",
              "250 g Fisch · 175 g Couscous · etwas Olivenöl"],
 "dica": "Weiße Fische wie Seehecht und Kabeljau sind sehr mager und leicht, ideal für alle, die abnehmen wollen. Couscous gart nur mit heißem Wasser, ganz ohne Fett, und mit dem Gemüse wird daraus eine bunte, lockere Beilage voller Ballaststoffe.",
},
{
 "nome": "Hähnchen-Gemüse-Spieße mit Reis",
 "hook": "Bunt und schön zu stecken, garen die Spieße gleichmäßig und geben jedem Mittagessen ein bisschen Festtagsstimmung.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 450,
 "ings": ["2 Hähnchenbrustfilets in Würfeln (ca. 300 g)", "1 Paprika in Quadraten", "1 Zwiebel in Stücken",
          "1 Zucchini in dicken Scheiben", "Kirschtomaten", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und Paprikapulver nach Geschmack", "Reis zum Servieren", "Schaschlikspieße"],
 "passos": [
   "Würze die Hähnchenwürfel mit Salz, Pfeffer, Paprikapulver und dem Zitronensaft. Lass sie 10 Minuten Geschmack annehmen.",
   "Stecke die Spieße und wechsle dabei ab: ein Würfel Hähnchen, ein Stück Paprika, eines Zwiebel, eine Scheibe Zucchini und eine Kirschtomate, bis der Spieß voll ist.",
   "Bestreiche die Spieße mit dem Olivenöl.",
   "Erhitze eine große Pfanne oder eine Grillpfanne bei mittlerer bis hoher Hitze. Lege die Spieße hinein und drehe sie alle 3 Minuten, bis das Hähnchen rundherum goldbraun und innen weiß ist (insgesamt etwa 12 Minuten).",
   "Serviere die Spieße über einer Portion Reis."],
 "porcoes8": ["1 Spieß · 3 EL Reis",
              "2 Spieße · 4 EL Reis",
              "2 Spieße · 5 EL Reis",
              "2 Spieße · 5 EL Reis · extra Hähnchen",
              "2 Spieße · 5 EL Reis",
              "3 Spieße · 6 EL Reis",
              "3 Spieße · 7 EL Reis",
              "3 große Spieße · 8 EL Reis"],
 "dica": "Die Spieße helfen ganz von selbst dabei, die Portion im Blick zu behalten, und mischen viel Gemüse unter das Eiweiß. Mageres gegrilltes Hähnchen sättigt ohne Fett, und das bunte Gemüse füllt den Teller mit Ballaststoffen und Vitaminen für fast keine Kalorien.",
},
{
 "nome": "Leichter Kartoffelsalat mit Ei und Thunfisch",
 "hook": "Der cremige Kartoffelsalat von Festen, ohne die schwere Mayonnaise — er wird zur vollständigen, leichten Mahlzeit.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 410,
 "ings": ["2 mittelgroße Kartoffeln in Würfeln", "2 gekochte Eier", "1 Dose Thunfisch in Wasser, abgetropft",
          "3 EL Naturjoghurt ohne Zucker", "1 TL Senf",
          "rote Zwiebel, Petersilie und Schnittlauch, gehackt", "Salz, Pfeffer und Saft von ½ Zitrone nach Geschmack"],
 "passos": [
   "Koche die Kartoffelwürfel 12 bis 15 Minuten in kochendem Salzwasser, bis sie weich sind, aber nicht zerfallen (eine Gabel geht leicht hinein). Gieße sie ab und lass sie etwas abkühlen.",
   "Koche die Eier 9 Minuten, halte sie unter kaltes Wasser, pelle sie und schneide sie in Stücke.",
   "Rühre das Dressing an: Vermische den Joghurt, den Senf, den Zitronensaft, Salz und Pfeffer in einer großen Schüssel.",
   "Gib die lauwarmen Kartoffeln, den abgetropften Thunfisch, die Eier, die rote Zwiebel und die Kräuter in die Schüssel.",
   "Vermische alles vorsichtig, damit die Kartoffeln nicht zerfallen. Schmecke mit Salz ab und serviere sofort oder gekühlt."],
 "porcoes8": ["½ Portion · ½ Dose Thunfisch · 1 Ei",
              "1 Portion · 1 Dose Thunfisch · 2 Eier",
              "1 Portion · 1 Dose Thunfisch · 2 Eier",
              "1 Portion · 1 Dose Thunfisch · 2 Eier · grüner Salat",
              "1 Portion · 1 Dose Thunfisch · 2 Eier",
              "1 große Portion · 1½ Dosen Thunfisch · 2 Eier",
              "große Portion · 1½ Dosen Thunfisch · 3 Eier",
              "doppelte Portion · 2 Dosen Thunfisch · 3 Eier"],
 "dica": "Die Mayonnaise durch Joghurt mit Senf zu ersetzen spart sehr viel Fett und bringt noch Eiweiß dazu. Thunfisch und Ei machen aus einem Kartoffelsalat eine vollständige, sättigende Mahlzeit. Die kalte Kartoffel bildet sogar einen besonderen Ballaststoff, der die guten Darmbakterien füttert.",
},
{
 "nome": "Hähnchen aus dem Ofen mit Wurzelgemüse",
 "hook": "Alles auf ein Blech und den Ofen arbeiten lassen — das Hähnchen wird goldbraun und das Gemüse weich und süßlich.",
 "tempo": "45 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["2 Hähnchenoberkeulen ohne Haut (oder 2 dicke Filets, ca. 300 g)", "1 Kartoffel in Stücken",
          "1 Möhre in großen Stücken", "1 Stück Kürbis in Würfeln", "1 Zwiebel in Spalten",
          "2 Knoblauchzehen", "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer und Rosmarin nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Schneide die Kartoffel, die Möhre, den Kürbis und die Zwiebel in große, ähnlich große Stücke, damit alles gleichmäßig gart.",
   "Verteile das Gemüse und die Knoblauchzehen auf einem großen Backblech. Würze alles mit Salz, Pfeffer, Rosmarin und der Hälfte des Olivenöls und vermische es mit den Händen.",
   "Würze das Hähnchen mit Salz, Pfeffer, dem Zitronensaft und dem restlichen Olivenöl. Lege die Stücke zwischen das Gemüse.",
   "Schiebe alles 35 bis 40 Minuten in den Ofen und wende das Gemüse nach der Hälfte der Zeit, bis das Hähnchen goldbraun und innen gar ist (die Flüssigkeit, die beim Einstechen austritt, muss klar sein) und das Gemüse weich ist.",
   "Serviere direkt vom Blech, mit dem ganzen Bratensaft, der sich unten gesammelt hat."],
 "porcoes8": ["1 Oberkeule · ½ Portion Gemüse",
              "1 Oberkeule · 1 Portion Gemüse",
              "1 große Oberkeule · 1 Portion Gemüse",
              "2 Oberkeulen · 1 Portion Gemüse",
              "2 Oberkeulen · 1 Portion Gemüse",
              "2 Oberkeulen · 1 große Portion Gemüse",
              "2 Oberkeulen · große Portion Gemüse",
              "3 Oberkeulen · doppelte Portion Gemüse"],
 "dica": "Ohne Haut und ohne viel Öl gebacken bleibt das Hähnchen leicht, und der eigene Bratensaft würzt das Gemüse, ohne dass Fett nötig wäre. Kürbis und Möhre werden beim Backen süßlich, das stillt die Lust auf Süßes, und sie füllen den Teller mit Ballaststoffen und Vitaminen für wenige Kalorien.",
},
{
 "nome": "Hähnchen Parmigiana aus dem Ofen mit Salat",
 "hook": "Die knusprige, überbackene Parmigiana deiner Träume, im Ofen gebacken statt frittiert — der ganze Genuss, ohne das Frittierte.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 470,
 "ings": ["2 dünne Hähnchenbrustfilets (ca. 300 g)", "1 Ei", "4 EL Vollkorn-Paniermehl",
          "240 ml selbst gemachte Tomatensoße", "3 EL geriebener magerer Mozzarella",
          "Salz, Pfeffer und Oregano nach Geschmack", "Blattsalat für den Salat"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Würze die dünnen Filets mit Salz und Pfeffer.",
   "Verquirle das Ei auf einem tiefen Teller. Gib das Paniermehl mit dem Oregano vermischt auf einen anderen Teller.",
   "Ziehe jedes Filet zuerst durch das Ei, dann durch das Paniermehl und drücke es an, damit beide Seiten gut bedeckt sind.",
   "Lege die Filets auf ein beschichtetes Backblech (oder eines mit Backpapier) und backe sie 15 Minuten, dabei nach der Hälfte wenden, bis die Kruste goldbraun und knusprig ist.",
   "Bedecke jedes Filet mit der Tomatensoße und dem geriebenen Käse. Backe alles noch 8 Minuten, bis der Käse geschmolzen ist und Blasen wirft.",
   "Serviere mit einem frischen grünen Salat daneben."],
 "porcoes8": ["100 g Hähnchen · wenig Käse · Salat",
              "130 g Hähnchen · Käse · Salat",
              "150 g Hähnchen · Käse · Salat",
              "150 g Hähnchen · Käse · 3 EL Reis",
              "150 g Hähnchen · Käse · 3 EL Reis",
              "170 g Hähnchen · Käse · 4 EL Reis",
              "200 g Hähnchen · Käse · 5 EL Reis",
              "220 g Hähnchen · extra Käse · 5 EL Reis"],
 "dica": "Die Parmigiana macht dick wegen des Frittierens und des vielen Käses. Mit Vollkorn-Paniermehl paniert und im Ofen gebacken wird sie knusprig mit einem Bruchteil des Fetts. Etwas magerer Käse obendrauf stillt die Lust auf Überbackenes, und der Salat bringt den Teller ins Gleichgewicht.",
},
{
 "nome": "Bowl mit Reis, Edamame und Lachs",
 "hook": "Inspiriert von der hawaiianischen Poke Bowl: frisch, bunt und nahrhaft, in einer Schüssel angerichtet und sättigend, ohne schwer zu liegen.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 480,
 "ings": ["1 Lachsfilet in Würfeln (ca. 130 g)", "4 EL gekochter Reis", "80 g gekochte Edamame (grüne Sojabohnen)",
          "½ Gurke in kleinen Würfeln", "½ Möhre, gerieben", "½ Avocado in Scheiben", "1 EL helle Sojasoße",
          "Sesam, Saft von ½ Zitrone und Schnittlauch nach Geschmack"],
 "passos": [
   "Koche die Edamame 4 Minuten in kochendem Wasser, gieße sie ab und hole die Kerne aus den Schoten, falls sie noch darin sind.",
   "Würze die Lachswürfel mit der Sojasoße und dem Zitronensaft. Lass sie 5 Minuten Geschmack annehmen. (Magst du ihn lieber gegart, brate die Würfel kurz 3 Minuten in einer Pfanne an.)",
   "Gib den Reis als Basis an eine Seite einer Schüssel.",
   "Ordne darauf in getrennten Gruppen den Lachs, die Edamame, die Gurke, die geriebene Möhre und die Avocado an.",
   "Beträufle alles mit noch etwas Sojasoße, streue Sesam und Schnittlauch darüber und serviere."],
 "porcoes8": ["100 g Lachs · 3 EL Reis · ¼ Avocado",
              "130 g Lachs · 4 EL Reis · ½ Avocado",
              "130 g Lachs · 5 EL Reis · ½ Avocado",
              "150 g Lachs · 5 EL Reis · ½ Avocado",
              "150 g Lachs · 5 EL Reis · ½ Avocado",
              "170 g Lachs · 6 EL Reis · ½ Avocado",
              "200 g Lachs · 7 EL Reis · Avocado",
              "220 g Lachs · 8 EL Reis · Avocado"],
 "dica": "Das ist ein vollständiges, ausgewogenes Gericht: Eiweiß und Omega-3 aus dem Lachs, pflanzliches Eiweiß aus den Edamame, das gute Fett der Avocado und die Ballaststoffe aus dem rohen Gemüse. In einer Schüssel angerichtet sieht es schön aus und sättigt — der Beweis, dass gesundes Essen ein Fest für die Augen sein kann.",
},
{
 "nome": "Kräftige Gemüsesuppe mit gezupftem Hähnchen",
 "hook": "Eine Suppe, die eine echte Mahlzeit ist: kräftig mit Hähnchen und Gemüse, wärmt den Körper und sättigt, ohne schwer zu liegen.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 380,
 "ings": ["1 Hähnchenbrustfilet (ca. 150 g)", "1 Kartoffel in Würfeln", "1 Möhre in Würfeln",
          "1 Zucchini in Würfeln", "80 g Mais oder Erbsen", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack", "1 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem großen Topf und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an, bis sie glasig sind.",
   "Gib das ganze Hähnchenfilet und das Wasser dazu. Lass alles aufkochen und 15 Minuten garen, bis das Hähnchen durch ist.",
   "Nimm das Hähnchen heraus, lass es lauwarm werden und zupfe es mit zwei Gabeln auseinander. Stelle es beiseite.",
   "Gib in dasselbe Wasser die Kartoffel, die Möhre, die Zucchini und den Mais. Würze mit Salz und Pfeffer und koche alles 12 bis 15 Minuten, bis das Gemüse weich ist.",
   "Gib das gezupfte Hähnchen zurück in den Topf, schmecke mit Salz ab und koche alles noch 3 Minuten. Streue die Kräuter darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["1 Kelle · Hähnchen · ohne extra Kartoffel",
              "2 Kellen · Hähnchen · Gemüse",
              "2 Kellen · Hähnchen · Gemüse",
              "2 Kellen · extra Hähnchen · 1 Scheibe Brot",
              "2 Kellen · extra Hähnchen · 1 Scheibe Brot",
              "3 Kellen · Hähnchen · 1 Scheibe Brot",
              "3 Kellen · extra Hähnchen · 2 Scheiben Brot",
              "3 große Kellen · doppelt Hähnchen · 2 Scheiben Brot"],
 "dica": "Suppen sind hervorragend zum Abnehmen: Die Menge an Flüssigkeit und Gemüse füllt den Magen mit sehr wenigen Kalorien, und die Wärme sorgt dafür, dass man langsamer isst. Mit dem gezupften Hähnchen ist sie keine Vorspeise mehr, sondern eine vollständige, leichte und wohltuende Mahlzeit.",
},
{
 "nome": "Herzhafter Haferpfannkuchen mit Hähnchenfüllung",
 "hook": "Der Teig braucht nur Ei und Haferflocken, ist in Sekunden gerührt und wird zu einem goldbraunen Pfannkuchen mit cremiger Hähnchenfüllung.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 400,
 "ings": ["1 Ei", "3 EL Haferflocken", "3 EL Wasser", "1 Prise Salz",
          "1 gekochtes, gezupftes Hähnchenfilet (ca. 100 g)", "2 EL Tomatensoße",
          "1 EL Naturjoghurt", "1 TL Olivenöl", "Oregano nach Geschmack"],
 "passos": [
   "Verquirle in einer Schüssel mit einer Gabel das Ei, die Haferflocken, das Wasser und das Salz zu einem glatten Teig. Lass ihn 3 Minuten ruhen, damit die Haferflocken die Flüssigkeit aufnehmen.",
   "Erhitze eine beschichtete Pfanne mit der Hälfte des Olivenöls bei mittlerer Hitze. Gieße den Teig hinein und verteile ihn durch Schwenken der Pfanne zu einer dünnen Scheibe.",
   "Lass ihn 2 Minuten backen, bis sich der Rand löst, wende ihn vorsichtig und backe die andere Seite 1 Minute goldbraun. Nimm den Pfannkuchen heraus.",
   "Vermische das gezupfte Hähnchen mit der Tomatensoße, dem Joghurt und dem Oregano und erwärme alles kurz in der Pfanne.",
   "Fülle den Pfannkuchen mit dem Hähnchen, klappe ihn zusammen oder rolle ihn und serviere ihn warm, wenn du magst mit einem Salat daneben."],
 "porcoes8": ["1 Pfannkuchen · 80 g Hähnchen",
              "1 Pfannkuchen · 100 g Hähnchen",
              "1 Pfannkuchen · 120 g Hähnchen",
              "1 Pfannkuchen · 120 g Hähnchen · Salat",
              "1 Pfannkuchen · 130 g Hähnchen · Salat",
              "2 Pfannkuchen · 150 g Hähnchen",
              "2 Pfannkuchen · 170 g Hähnchen · Salat",
              "2 Pfannkuchen · 200 g Hähnchen · Salat"],
 "dica": "Der Teig aus Ei und Haferflocken ersetzt weißes Mehl durch Ballaststoffe und Eiweiß und sättigt damit viel stärker als ein normaler Pfannkuchen. Gefüllt mit gezupftem Hähnchen und einer leichten Joghurtsoße wird daraus eine praktische, schmackhafte und vollständige Mahlzeit, die auch abends gut passt.",
},
{
 "nome": "Knoblauchgarnelen mit Gemüse und Reis",
 "hook": "Rosige Garnelen, goldbraun im Knoblauch gebraten, die die ganze Küche durchduften — ein leichtes und besonderes Wochenendessen.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 430,
 "ings": ["150 g geputzte Garnelen", "4 EL gekochter Reis", "100 g Brokkoli und grüne Bohnen",
          "2 Knoblauchzehen, gehackt", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Tupfe die Garnelen mit Küchenpapier gut trocken und würze sie mit Salz, Pfeffer und dem Zitronensaft. Lass sie 5 Minuten Geschmack annehmen.",
   "Schneide den Brokkoli in Röschen und die grünen Bohnen in Stücke. Gare sie im Dampf oder in wenig kochendem Wasser 4 Minuten, bis sie grün und weich, aber noch fest sind. Gieße sie ab.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze. Gib den gehackten Knoblauch dazu und rühre 30 Sekunden, nur bis er duftet und leicht Farbe annimmt — pass auf, dass er nicht verbrennt, sonst wird er bitter.",
   "Lege die Garnelen hinein und brate sie bei mittlerer bis hoher Hitze unter Rühren 2 bis 3 Minuten, nur bis sie rosa werden und sich einrollen. Brate sie nicht zu lange, sonst werden sie gummiartig.",
   "Gib das Gemüse und den bereits gekochten Reis in die Pfanne und vermische alles 1 Minute, damit es den Knoblauchgeschmack annimmt. Streue Petersilie darüber und serviere sofort."],
 "porcoes8": ["120 g Garnelen · 3 EL Reis · Gemüse",
              "150 g Garnelen · 4 EL Reis · Gemüse",
              "150 g Garnelen · 5 EL Reis · Gemüse",
              "170 g Garnelen · 5 EL Reis · etwas Olivenöl",
              "170 g Garnelen · 5 EL Reis · Gemüse",
              "200 g Garnelen · 6 EL Reis · Gemüse",
              "220 g Garnelen · 7 EL Reis · etwas Olivenöl",
              "250 g Garnelen · 8 EL Reis · etwas Olivenöl"],
 "dica": "Garnelen bestehen fast nur aus Eiweiß, mit sehr wenig Fett und wenigen Kalorien, du kannst dir also ohne schlechtes Gewissen auffüllen. Im Knoblauch goldbraun gebraten gewinnen sie sehr viel Geschmack mit nur etwas Olivenöl, und mit dem Gemüse und einer abgemessenen Portion Reis wird daraus ein leichtes Gericht mit Restaurant-Wirkung.",
},
{
 "nome": "Fleischbällchen in Soße mit Kartoffelpüree",
 "hook": "Zarte Fleischbällchen in kräftiger Tomatensoße, auf einem leichten Püree — die warme Umarmung, die die Diät erlaubt.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 490,
 "ings": ["250 g mageres Rinderhackfleisch", "1 Ei", "2 EL Haferflocken", "1 Knoblauchzehe, gehackt",
          "3 Tomaten, gehackt (oder Tomatensoße)", "1 Zwiebel, gehackt", "2 mittelgroße Kartoffeln",
          "1 TL Olivenöl", "Salz, Pfeffer und Basilikum nach Geschmack"],
 "passos": [
   "Schäle die Kartoffeln und koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich sind. Gieße sie ab und zerdrücke sie mit einer Gabel und einer Prise Salz zu einem glatten Püree. Für mehr Cremigkeit gib etwas Kochwasser dazu.",
   "Vermische in einer Schüssel das Hackfleisch, das Ei, die Haferflocken, die Hälfte des Knoblauchs, Salz und Pfeffer. Knete alles mit den Händen und forme Bällchen von der Größe einer Walnuss.",
   "Erhitze das Olivenöl in einem Topf und brate die Bällchen rundherum an, dabei vorsichtig drehen, 5 Minuten lang. Nimm sie heraus und stelle sie beiseite.",
   "Brate im selben Topf die Zwiebel und den restlichen Knoblauch 2 Minuten an. Gib die Tomaten, Salz und Pfeffer dazu und koche alles 8 Minuten, bis eine Soße entsteht.",
   "Gib die Bällchen zurück in die Soße und lass sie noch 8 Minuten garen, bis sie innen durch sind. Streue Basilikum darüber.",
   "Serviere die Bällchen mit der Soße über dem Kartoffelpüree."],
 "porcoes8": ["3 Bällchen · ½ Portion Püree",
              "4 Bällchen · 1 Portion Püree",
              "4 Bällchen · 1 Portion Püree",
              "5 Bällchen · 1 Portion Püree",
              "5 Bällchen · 1 Portion Püree",
              "6 Bällchen · 1 große Portion Püree",
              "7 Bällchen · große Portion Püree",
              "8 Bällchen · doppelte Portion Püree"],
 "dica": "Die Bällchen enthalten Haferflocken statt mehr Brot, das bindet mit Ballaststoffen statt mit weißer Stärke. Aus magerem Fleisch gemacht und in der Soße gegart (nicht frittiert) bleiben sie saftig und leicht. Normales Kartoffelpüree ist im richtigen Maß wohltuend und sättigt gut.",
},
{
 "nome": "Leichtes Risotto mit Hähnchen und Gemüse",
 "hook": "Die Cremigkeit eines Risottos ohne Butter und ohne zu viel Käse — der Reis gibt seine eigene Cremigkeit ab und umhüllt Hähnchen und Gemüse.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 480,
 "ings": ["185 g Reis (Risottoreis oder normaler Reis)", "2 Hähnchenbrustfilets in Würfeln (ca. 300 g)",
          "1 Möhre in kleinen Würfeln", "75 g Erbsen", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "1 EL geriebener Käse", "Salz, Pfeffer und Petersilie nach Geschmack",
          "selbst gemachte Gemüsebrühe oder heißes Wasser (etwa 700 ml)"],
 "passos": [
   "Würze die Hähnchenwürfel mit Salz und Pfeffer. Erhitze das Olivenöl in einem Topf und brate das Hähnchen 5 Minuten unter Rühren an. Nimm es heraus und stelle es beiseite.",
   "Brate im selben Topf die Zwiebel und den Knoblauch 2 Minuten an. Gib den Reis dazu und rühre 1 Minute, nur damit sich die Körner mit den Aromen verbinden.",
   "Gieße die heiße Brühe nach und nach an, immer eine Kelle auf einmal, und rühre dabei ständig. Gib erst mehr Brühe dazu, wenn die vorherige fast eingekocht ist.",
   "Nach der Hälfte der Garzeit (etwa 10 Minuten) gibst du die Möhre und die Erbsen dazu. Rühre weiter und gieße weiter Brühe an.",
   "Wenn der Reis weich und cremig ist (insgesamt etwa 18 bis 20 Minuten), gib das Hähnchen zurück, rühre den geriebenen Käse unter und nimm den Topf vom Herd. Streue Petersilie darüber und serviere sofort."],
 "porcoes8": ["½ Portion · Hähnchen",
              "1 Portion · Hähnchen",
              "1 Portion · Hähnchen",
              "1 Portion · extra Hähnchen",
              "1 Portion · extra Hähnchen",
              "1 große Portion · Hähnchen",
              "große Portion · extra Hähnchen",
              "doppelte Portion · extra Hähnchen"],
 "dica": "Ein klassisches Risotto enthält sehr viel Butter und Käse. Hier kommt die Cremigkeit aus der Stärke des Reises selbst, die beim Rühren frei wird, mit nur einem Hauch Käse. Mit reichlich Hähnchen und Gemüse wird das Gericht kräftig und befriedigend — der Beweis, dass man Risotto ohne schlechtes Gewissen essen kann.",
},
]
