# -*- coding: utf-8 -*-
"""35 receitas de ALMOCO (031-065). ITALIANO.

Traducao literal de `receitas_almoco_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md.
⛔ METRICO: g, ml, °C — como pt/de/fr/es. `5 oz` -> `150 g` · `400 °F` -> `200 °C`
   · `4 cups of water` -> `1 litro d'acqua` · `1 cup of rice` -> `185 g di riso`.
⛔ O campo `prompt` NAO e' replicado: a foto e' a mesma (fotos/NNN, sem texto).
"""

RECEITAS = [
{
 "nome": "Pollo alla griglia con riso integrale e broccoli",
 "hook": "Il piatto più semplice del mondo e uno dei migliori per dimagrire: proteine magre, un buon carboidrato e verdure quante ne vuoi.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 470,
 "ings": ["1 filetto di petto di pollo (circa 150 g)",
          "4 cucchiai di riso integrale cotto", "1 piatto di broccoli",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale e pepe q.b."],
 "passos": [
   "Condisci il pollo su entrambi i lati con sale, pepe, l'aglio e il succo di limone. Lascialo insaporire per 5 minuti.",
   "Taglia i broccoli a cimette piccole. Porta a bollore l'acqua in una pentola, aggiungi i broccoli e lasciali solo 3 minuti, finché non sono di un verde brillante e teneri ma ancora sodi. Scolali.",
   "Scalda una padella antiaderente a fuoco medio-alto con l'olio d'oliva. Metti il pollo e lascialo 4-5 minuti per lato, senza spostarlo, finché non è dorato fuori e bianco dentro.",
   "Per capire se è cotto, taglia il filetto al centro: la carne deve essere bianca fino in fondo, senza parti rosate.",
   "Scalda il riso integrale già cotto. Componi il piatto con il riso, il pollo a fette e i broccoli di lato.",
   "Se ti va, condisci i broccoli con un po' di olio d'oliva e ancora un po' di limone."],
 "porcoes8": ["100 g di pollo · 3 cucchiai di riso · broccoli, quanti ne vuoi",
              "120 g di pollo · 4 cucchiai di riso · broccoli, quanti ne vuoi",
              "130 g di pollo · 5 cucchiai di riso · broccoli, quanti ne vuoi",
              "150 g di pollo · 5 cucchiai di riso · un po' di olio d'oliva",
              "150 g di pollo · 5 cucchiai di riso · broccoli, quanti ne vuoi",
              "170 g di pollo · 6 cucchiai di riso · broccoli, quanti ne vuoi",
              "200 g di pollo · 7 cucchiai di riso · un po' di olio d'oliva",
              "220 g di pollo · 8 cucchiai di riso · un po' di olio d'oliva"],
 "dica": "Il petto di pollo è quasi proteina pura, molto saziante, e aiuta a proteggere il muscolo mentre perdi grasso. Il riso integrale ha fibre e rilascia energia lentamente, così non ti prende quella fame che arriva un'ora dopo. I broccoli riempiono il piatto con quasi zero calorie.",
},
{
 "nome": "Filetto di tilapia con purè di patate dolci",
 "hook": "Pesce leggero e un purè naturalmente dolce — un pranzo che sembra un piatto da ristorante e rientra nella tua dieta.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 440,
 "ings": ["1 filetto di tilapia (circa 150 g)", "1 patata dolce media",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "erbe fresche tritate", "sale, pepe e paprika q.b.",
          "foglie verdi per l'insalata"],
 "passos": [
   "Sbuccia la patata dolce e tagliala a pezzi. Cuocila in acqua bollente per 15 minuti, finché non è molto morbida (la forchetta entra senza sforzo). Scolala.",
   "Schiaccia la patata ancora calda con la forchetta, aggiungi un pizzico di sale e metà dell'olio d'oliva, e mescola finché non diventa un purè liscio.",
   "Condisci la tilapia con sale, pepe, paprika e il succo di limone.",
   "Scalda una padella antiaderente con il resto dell'olio d'oliva a fuoco medio. Metti il filetto e lascialo 3-4 minuti per lato, girandolo con delicatezza una sola volta, finché non è dorato e si stacca facilmente dalla padella.",
   "Componi il piatto con il purè, il filetto sopra e una porzione di foglie verdi di lato. Completa con le erbe fresche."],
 "porcoes8": ["120 g di pesce · ½ patata dolce · insalata",
              "150 g di pesce · 1 patata dolce piccola · insalata",
              "150 g di pesce · 1 patata dolce media · insalata",
              "170 g di pesce · 1 patata dolce media · un po' di olio d'oliva",
              "170 g di pesce · 1 patata dolce media · insalata",
              "200 g di pesce · 1 patata dolce grande · insalata",
              "220 g di pesce · 1 patata dolce grande · un po' di olio d'oliva",
              "250 g di pesce · 1 patata dolce grande · un po' di olio d'oliva"],
 "dica": "La tilapia è un pesce magro, pieno di proteine e con pochissimi grassi. La patata dolce ti tiene sazia per ore e, pur essendo un carboidrato, rilascia energia molto lentamente — per questo è la preferita di chi vuole dimagrire senza perdere energia.",
},
{
 "nome": "Trancio di tonno alla griglia con verdure e patate",
 "hook": "Il tonno fresco diventa una bistecca di mare: sodo fuori, succoso dentro, e pronto in pochi minuti.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 450,
 "ings": ["1 trancio di tonno fresco (circa 150 g)",
          "1 patata piccola a fettine", "110 g di fagiolini e carota",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e origano q.b."],
 "passos": [
   "Cuoci le fettine di patata in acqua bollente salata per 10 minuti, finché non sono morbide ma non si sfaldano. Scolale.",
   "Taglia i fagiolini a pezzetti e la carota a rondelle. Cuocili a vapore o in poca acqua bollente per 5 minuti, finché non sono teneri ma ancora sodi.",
   "Condisci il trancio di tonno con sale, pepe, l'aglio, l'origano e il succo di limone. Lascialo insaporire per 5 minuti.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco alto. Metti il trancio e lascialo 2-3 minuti per lato — il tonno è ottimo leggermente rosato al centro; se lo preferisci ben cotto, lascialo 1 minuto in più per lato.",
   "Componi il piatto con la patata, le verdure e il trancio di tonno sopra. Condisci con ancora un po' di limone e servi."],
 "porcoes8": ["120 g di tonno · ½ patata · verdure",
              "150 g di tonno · 1 patata piccola · verdure",
              "150 g di tonno · 1 patata · verdure",
              "170 g di tonno · 1 patata · un po' di olio d'oliva",
              "170 g di tonno · 1 patata · verdure",
              "200 g di tonno · 1 patata grande · verdure",
              "220 g di tonno · 1 patata grande · un po' di olio d'oliva",
              "250 g di tonno · 2 patate piccole · un po' di olio d'oliva"],
 "dica": "Il tonno fresco è una delle carni più magre che vengano dal mare: tante proteine, omega-3 (il grasso buono) e pochissimo grasso cattivo. Cotto veloce a fuoco alto, resta succoso senza olio, e con le verdure e un po' di patata diventa un pranzo raffinato e leggero.",
},
{
 "nome": "Wrap integrale con pollo sfilacciato",
 "hook": "Un involtino pratico da portare al lavoro, farcito di pollo e insalata — toglie la fame senza appesantirti.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 420,
 "ings": ["1 piadina integrale (o pane piatto integrale)",
          "1 filetto di pollo cotto e sfilacciato (circa 120 g)",
          "1 cucchiaio di yogurt naturale senza zucchero", "foglie di lattuga",
          "½ pomodoro a fettine", "carota grattugiata",
          "sale, pepe e un po' di senape q.b."],
 "passos": [
   "Cuoci il petto di pollo in acqua salata per circa 15 minuti, finché non è bianco dentro. Fallo intiepidire e sfilaccialo con due forchette, tirando la carne a filamenti.",
   "In una ciotola, mescola il pollo sfilacciato con lo yogurt, la senape, sale e pepe, finché non diventa una farcia cremosa.",
   "Scalda la piadina 20 secondi in padella, giusto perché diventi morbida e facile da arrotolare.",
   "Distribuisci le foglie di lattuga al centro della piadina. Metti sopra il pollo cremoso, il pomodoro e la carota grattugiata.",
   "Ripiega i due lati verso l'interno e arrotola stretto, dal basso verso l'alto. Taglia a metà in diagonale e servi."],
 "porcoes8": ["100 g di pollo · ½ piadina · insalata",
              "120 g di pollo · 1 piadina · insalata",
              "130 g di pollo · 1 piadina · insalata",
              "150 g di pollo · 1 piadina · 1 cucchiaio colmo di yogurt",
              "150 g di pollo · 1 piadina · insalata",
              "170 g di pollo · 1 piadina grande · insalata",
              "200 g di pollo · 2 piadine · insalata",
              "220 g di pollo · 2 piadine · insalata"],
 "dica": "Sostituire la maionese con lo yogurt naturale taglia buona parte delle calorie e aggiunge comunque proteine. Il pollo sfilacciato si distribuisce bene e dà la sensazione di una farcia abbondante con pochi grassi, e la piadina integrale ha più fibre del pane bianco, tenendo a bada la fame più a lungo.",
},
{
 "nome": "Salmone al forno con verdure",
 "hook": "Tutto in una teglia: il pesce più prezioso per il tuo cuore, dorato insieme a verdure colorate.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 490,
 "ings": ["1 filetto di salmone (circa 150 g)", "1 patata piccola a fettine",
          "1 zucchina a rondelle", "½ peperone a striscioline",
          "pomodorini", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e rosmarino q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la patata a fettine sottili — così cuoce nello stesso tempo del pesce.",
   "Su una teglia, distribuisci la patata, la zucchina, il peperone e i pomodorini. Condisci con sale, pepe, rosmarino e metà dell'olio d'oliva, e mescola.",
   "Inforna per 10 minuti, giusto perché la patata inizi ad ammorbidirsi.",
   "Tira fuori la teglia, apri uno spazio al centro e metti il salmone. Condisci il pesce con sale, pepe, il succo di limone e il resto dell'olio d'oliva.",
   "Rimetti in forno per altri 15 minuti, finché il salmone non schiarisce e non si sfalda quando lo tocchi con la forchetta. Servi direttamente dalla teglia o nel piatto."],
 "porcoes8": ["120 g di salmone · ½ patata · verdure",
              "150 g di salmone · 1 patata piccola · verdure",
              "150 g di salmone · 1 patata · verdure",
              "170 g di salmone · 1 patata · un po' di olio d'oliva",
              "170 g di salmone · 1 patata · verdure",
              "200 g di salmone · 1 patata grande · verdure",
              "220 g di salmone · 1 patata grande · un po' di olio d'oliva",
              "250 g di salmone · 2 patate piccole · un po' di olio d'oliva"],
 "dica": "Il salmone è ricco di grassi buoni (omega-3), che aiutano il cuore e saziano molto. Cuocere tutto insieme nella stessa teglia usa quasi zero olio e lascia alle verdure un sapore concentrato — un piatto completo, bello e leggero con il minimo sforzo.",
},
{
 "nome": "Pasticcio di patate dolci con carne macinata magra",
 "hook": "La coccola di un pasticcio cremoso, ma con purè di patate dolci e carne magra — pura soddisfazione, senza sensi di colpa.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 460,
 "ings": ["2 patate dolci medie", "250 g di carne macinata magra di manzo",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 pomodoro, a pezzetti", "1 cucchiaino di olio d'oliva",
          "sale, pepe ed erbe fresche q.b.",
          "1 cucchiaio di formaggio grattugiato magro"],
 "passos": [
   "Sbuccia le patate dolci, tagliale a pezzi e cuocile in acqua bollente per 15 minuti, finché non sono molto morbide. Scolale e schiacciale con la forchetta, con un pizzico di sale, finché non diventa un purè liscio.",
   "In una padella, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio a fuoco medio, mescolando, per 2 minuti, finché non diventano trasparenti.",
   "Aggiungi la carne macinata e mescola, sgranandola con il cucchiaio, finché non perde tutto il colore rosato.",
   "Aggiungi il pomodoro, sale e pepe e cuoci per altri 5 minuti, finché non si restringe. Spegni e aggiungi le erbe fresche.",
   "In una pirofila, stendi metà del purè sul fondo, la carne al centro e il resto del purè sopra. Spolvera il formaggio grattugiato.",
   "Inforna a fuoco medio-alto (200 °C) per 15 minuti, finché la superficie non è leggermente dorata. Servi caldo."],
 "porcoes8": ["½ porzione · insalata verde",
              "1 porzione · insalata verde",
              "1 porzione · insalata verde",
              "1 porzione · 1 cucchiaio in più di formaggio",
              "1 porzione + carne extra · insalata",
              "1 porzione grande · insalata",
              "1 porzione grande + carne · insalata",
              "porzione doppia di carne · insalata"],
 "dica": "La patata dolce sostituisce la patata normale del pasticcio con una versione più ricca di fibre, che sazia di più. La carne magra dà tante proteine senza il grasso in eccesso dei tagli grassi. È il tipo di piatto avvolgente che inganna la voglia di cibo spazzatura.",
},
{
 "nome": "Insalatona con tonno, ceci e uovo",
 "hook": "Senza fornelli: un'insalata vera che riempie il piatto e la pancia, messa insieme in cinque minuti.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 400,
 "ings": ["1 scatoletta di tonno al naturale, scolata",
          "80 g di ceci cotti", "2 uova sode", "foglie verdi miste",
          "½ pomodoro a cubetti", "½ cetriolo a rondelle",
          "cipolla rossa a fettine sottili", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale e pepe q.b."],
 "passos": [
   "Cuoci le uova: mettile in una pentola con l'acqua, porta a bollore e conta 9 minuti. Passale sotto l'acqua fredda, sbucciale e tagliale a metà.",
   "Scola bene il tonno e i ceci.",
   "In un piatto o in una ciotola grande, distribuisci le foglie verdi. Sopra, disponi il pomodoro, il cetriolo e la cipolla.",
   "Metti il tonno al centro, i ceci intorno e le uova ai lati.",
   "Condisci con l'olio d'oliva e il succo di limone, aggiusta di sale e pepe e servi."],
 "porcoes8": ["½ scatoletta di tonno · 55 g di ceci · 1 uovo",
              "1 scatoletta di tonno · 80 g di ceci · 2 uova",
              "1 scatoletta di tonno · 80 g di ceci · 2 uova",
              "1 scatoletta di tonno · 110 g di ceci · 2 uova · avocado",
              "1 scatoletta di tonno · 110 g di ceci · 2 uova",
              "1½ scatolette di tonno · 125 g di ceci · 2 uova",
              "1½ scatolette di tonno · 165 g di ceci · 3 uova · avocado",
              "2 scatolette di tonno · 165 g di ceci · 3 uova · avocado"],
 "dica": "È una bomba di proteine (tonno, uovo e ceci insieme) che richiede quasi nessun lavoro. Le proteine e le fibre dell'insalata tengono a bada la fame per ore, e visto che è tutto fresco e non cotto nell'olio, il piatto resta leggero anche quando è abbondante.",
},
{
 "nome": "Stroganoff di pollo leggero con riso",
 "hook": "Lo stesso stroganoff cremoso, ma sostituendo la panna con lo yogurt — stessa bontà, metà delle calorie.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "70 g di funghi champignon a fettine",
          "1 cucchiaio di concentrato di pomodoro",
          "4 cucchiai di yogurt naturale senza zucchero",
          "1 cucchiaino di olio d'oliva", "sale, pepe e senape q.b.",
          "riso bianco o integrale per servire"],
 "passos": [
   "Condisci i cubetti di pollo con sale e pepe.",
   "Scalda l'olio d'oliva in una pentola a fuoco medio-alto e fai rosolare i cubetti di pollo all'esterno, mescolando ogni tanto, per 5 minuti. Toglili e mettili da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando, finché non diventano trasparenti. Aggiungi i funghi e cuoci per altri 3 minuti, finché non appassiscono (si ammorbidiscono).",
   "Rimetti il pollo nella pentola, aggiungi il concentrato di pomodoro e la senape, mescola e lascia andare per 3 minuti.",
   "Spegni il fuoco. Solo a questo punto aggiungi lo yogurt e mescola — a fuoco spento non impazzisce (non fa grumi). Aggiusta di sale e servi sul riso."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso",
              "1 porzione · 4 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso · pollo extra",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione grande · 6 cucchiai di riso",
              "1 porzione + pollo · 7 cucchiai di riso",
              "porzione doppia · 8 cucchiai di riso"],
 "dica": "Il segreto è lo yogurt naturale al posto della panna: mantieni la cremosità e il sapore, ma togli grassi e guadagni pure proteine. Il pollo porta sazietà e i funghi aggiungono volume e sapore con pochissime calorie.",
},
{
 "nome": "Petto di tacchino con cous cous di verdure",
 "hook": "Il cous cous è pronto con la sola acqua calda — il pranzo più veloce e sgranato per i giorni di corsa.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 430,
 "ings": ["1 filetto di petto di tacchino (circa 150 g)",
          "90 g di cous cous (quello a grana piccola)", "120 ml di acqua calda",
          "½ zucchina a cubetti piccoli", "½ peperone a cubetti piccoli",
          "pomodorini, tagliati", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e menta q.b."],
 "passos": [
   "Metti il cous cous in una ciotola, aggiungi un pizzico di sale e l'acqua calda (l'acqua deve coprire il cous cous di circa un dito). Coprilo con un piatto e lascialo 5 minuti.",
   "Sgrana il cous cous con la forchetta, passando per tutta la ciotola, finché non è sgranato e non si attacca.",
   "Condisci il petto di tacchino con sale e pepe. Scalda una padella antiaderente con metà dell'olio d'oliva e cuoci il tacchino 3-4 minuti per lato, finché non è dorato e bianco dentro.",
   "Aggiungi al cous cous i cubetti crudi di zucchina, peperone e pomodoro, il resto dell'olio d'oliva, il succo di limone e la menta. Mescola.",
   "Servi il cous cous con il petto di tacchino a fette sopra."],
 "porcoes8": ["120 g di tacchino · 60 g di cous cous · verdure",
              "150 g di tacchino · 90 g di cous cous · verdure",
              "150 g di tacchino · 90 g di cous cous · verdure",
              "170 g di tacchino · 115 g di cous cous · un po' di olio d'oliva",
              "170 g di tacchino · 115 g di cous cous · verdure",
              "200 g di tacchino · 130 g di cous cous · verdure",
              "220 g di tacchino · 175 g di cous cous · un po' di olio d'oliva",
              "250 g di tacchino · 175 g di cous cous · un po' di olio d'oliva"],
 "dica": "Il petto di tacchino è ancora più magro del pollo e pieno di proteine. Il cous cous cuoce con la sola acqua calda, senza grassi, e mescolato con le verdure crude diventa un piatto leggero, colorato e rinfrescante — perfetto per pranzo.",
},
{
 "nome": "Chili di manzo con fagioli neri",
 "hook": "Uno stufato piccante e sostanzioso che scalda l'anima — fagioli, carne magra e tanto sapore in una pentola sola.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 450,
 "ings": ["300 g di carne macinata magra di manzo",
          "170 g di fagioli neri cotti (o in scatola, scolati)",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati",
          "1 peperone, a pezzetti",
          "2 pomodori, a pezzetti (o passata di pomodoro)",
          "1 cucchiaino di olio d'oliva", "1 cucchiaino di cumino in polvere",
          "sale, pepe e paprika q.b."],
 "passos": [
   "Scalda l'olio d'oliva in una pentola a fuoco medio. Fai soffriggere la cipolla, l'aglio e il peperone per 3 minuti, mescolando, finché non si ammorbidiscono.",
   "Aggiungi la carne macinata e mescola, sgranandola con il cucchiaio, finché non perde tutto il colore rosato.",
   "Aggiungi il cumino, la paprika, sale e pepe e mescola bene, così le spezie liberano il loro aroma.",
   "Aggiungi i pomodori a pezzetti e i fagioli neri. Se si asciuga troppo, aggiungi mezzo bicchiere d'acqua.",
   "Abbassa la fiamma e lascia cuocere a fuoco basso per 15-20 minuti, mescolando ogni tanto, finché non si addensa in uno stufato cremoso. Servilo da solo o con un po' di riso."],
 "porcoes8": ["½ porzione · insalata",
              "1 porzione · insalata",
              "1 porzione · 2 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione · 3 cucchiai di riso",
              "1 porzione grande · 4 cucchiai di riso",
              "1 porzione grande · 5 cucchiai di riso",
              "porzione doppia · 5 cucchiai di riso"],
 "dica": "I fagioli neri sono campioni di fibre e proteine vegetali, e insieme alla carne magra rendono il piatto molto saziante con poche calorie. È uno stufato che rende parecchio, si conserva bene in frigo e toglie la voglia di cibo caldo e ben condito senza farti uscire dal percorso.",
},
{
 "nome": "Pasta integrale al pomodoro con polpette di tacchino",
 "hook": "Sì, puoi mangiare la pasta e dimagrire lo stesso — nella versione integrale, con sugo fresco e polpette magre.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 480,
 "ings": ["150 g di pasta integrale (peso a crudo)",
          "250 g di macinato di petto di tacchino (o di pollo)",
          "3 pomodori maturi, a pezzetti (o passata di pomodoro)",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati", "1 uovo",
          "2 cucchiai di avena", "1 cucchiaino di olio d'oliva",
          "sale, pepe e basilico q.b."],
 "passos": [
   "In una ciotola, mescola il macinato di tacchino, l'uovo, l'avena, metà dell'aglio, sale e pepe. Impasta con le mani finché non sta insieme e forma delle palline grandi come una noce.",
   "Scalda l'olio d'oliva in una pentola larga e fai rosolare le polpette su tutti i lati, girandole con delicatezza, per circa 5 minuti. Toglile e mettile da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e il resto dell'aglio per 2 minuti. Aggiungi i pomodori a pezzetti, sale e pepe e cuoci per 10 minuti, mescolando, finché non diventa un sugo.",
   "Rimetti le polpette nel sugo e lasciale cuocere per altri 8 minuti, finché non sono cotte dentro.",
   "Nel frattempo, cuoci la pasta in acqua bollente salata per il tempo indicato sulla confezione, finché non è cotta ma ancora al dente. Scolala.",
   "Manteca la pasta nel sugo con le polpette, spolvera il basilico e servi."],
 "porcoes8": ["⅔ porzione di pasta · 3 polpette",
              "1 porzione · 4 polpette",
              "1 porzione · 4 polpette",
              "1 porzione · 5 polpette",
              "1 porzione · 5 polpette",
              "1 porzione grande · 6 polpette",
              "porzione grande · 7 polpette",
              "porzione doppia · 8 polpette"],
 "dica": "La pasta integrale ha più fibre e sazia di più di quella normale, e le polpette di tacchino danno proteine magre al posto della carne grassa. Un sugo di pomodoro fatto al momento, senza zucchero e senza niente di industriale, mantiene il piatto saporito e molto più leggero.",
},
{
 "nome": "Omelette ripiena di verdure",
 "hook": "Un pranzo leggero per i giorni senza tempo: soffice, caldo e pieno di proteine, pronto in padella in dieci minuti.",
 "tempo": "12 min", "rende": "1 porzione", "kcal_base": 360,
 "ings": ["3 uova", "½ pomodoro a cubetti piccoli",
          "½ peperone a cubetti piccoli", "una manciata di spinaci",
          "1 cucchiaio di formaggio bianco a cubetti",
          "1 cucchiaino di olio d'oliva", "erba cipollina, sale e pepe q.b.",
          "1 fetta di pane integrale (facoltativo)"],
 "passos": [
   "Rompi le uova in una ciotola, condisci con sale e pepe e sbattile con la forchetta per 30 secondi, finché non sono omogenee (ben amalgamate).",
   "Scalda l'olio d'oliva in una padella antiaderente a fuoco medio-basso. Aggiungi il peperone e gli spinaci e mescola per 1 minuto, giusto finché gli spinaci non appassiscono (si ammorbidiscono).",
   "Distribuisci le verdure per la padella e versa sopra le uova. Lascia 1 minuto senza mescolare, finché il bordo non si rassoda.",
   "Metti il pomodoro e il formaggio su metà dell'omelette. Con una spatola, ripiega l'altra metà sopra, formando una mezzaluna.",
   "Lasciala ancora un minuto, giusto finché il formaggio non si ammorbidisce. Spolvera l'erba cipollina e servi, con la fetta di pane se ti va."],
 "porcoes8": ["2 uova · verdure · ½ pane",
              "3 uova · verdure · 1 fetta di pane",
              "3 uova · verdure · 1 fetta di pane",
              "3 uova · 2 cucchiai di formaggio · 1 fetta di pane",
              "3 uova · verdure · 1 fetta di pane",
              "4 uova · verdure · 1 fetta di pane",
              "4 uova · 2 cucchiai di formaggio · 2 fette di pane",
              "5 uova · verdure · 2 fette di pane"],
 "dica": "Le uova sono una proteina di altissima qualità e molto saziante — chi mangia uova a pranzo di solito spizzica meno nel pomeriggio. Ripiena di verdure, l'omelette guadagna volume, colore e fibre con quasi zero calorie in più, diventando un pasto completo e veloce.",
},
{
 "nome": "Bistecca di manzo magra con riso, fagioli e cavolo nero",
 "hook": "Il piatto di tutti i giorni, come piace a noi — solo nella misura giusta, con carne magra e cavolo nero saltato appena.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 500,
 "ings": ["1 bistecca di manzo magra (circa 130 g)",
          "4 cucchiai di riso cotto", "4 cucchiai di fagioli cotti",
          "2 foglie di cavolo nero tagliate a striscioline sottili",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale e pepe q.b."],
 "passos": [
   "Condisci la bistecca con sale e pepe su entrambi i lati.",
   "Scalda una padella antiaderente a fuoco alto con qualche goccia di olio d'oliva. Metti la bistecca e lasciala 2-3 minuti per lato, senza spostarla, finché non è dorata fuori e cotta come piace a te dentro.",
   "Taglia il cavolo nero a striscioline molto sottili. In una padella, scalda il resto dell'olio d'oliva e fai soffriggere l'aglio per 30 secondi, giusto finché non profuma.",
   "Aggiungi il cavolo nero e mescola a fuoco alto per 1-2 minuti, giusto finché non appassisce un po' (si ammorbidisce) e resta verde. Aggiusta di sale.",
   "Scalda il riso e i fagioli. Componi il piatto con il riso, i fagioli, la bistecca e il cavolo nero di lato."],
 "porcoes8": ["100 g di carne · 3 cucchiai di riso · 3 cucchiai di fagioli",
              "130 g di carne · 4 cucchiai di riso · 4 cucchiai di fagioli",
              "130 g di carne · 5 cucchiai di riso · 4 cucchiai di fagioli",
              "150 g di carne · 5 cucchiai di riso · 5 cucchiai di fagioli",
              "150 g di carne · 5 cucchiai di riso · 5 cucchiai di fagioli",
              "170 g di carne · 6 cucchiai di riso · 5 cucchiai di fagioli",
              "200 g di carne · 7 cucchiai di riso · 6 cucchiai di fagioli",
              "220 g di carne · 8 cucchiai di riso · 6 cucchiai di fagioli"],
 "dica": "Puoi mangiare il piatto tradizionale di riso, fagioli e carne senza uscire dalla tua dieta: la chiave è scegliere un taglio magro, misurare il riso e i fagioli ed essere generosa con il cavolo nero, che riempie il piatto di fibre e quasi zero calorie. Anche i fagioli portano fibre e proteine che tengono a bada la fame.",
},
{
 "nome": "Bistecca con cipolle, purè di patate e insalata",
 "hook": "La bistecca con le cipolle dorate è pura consolazione — su un purè leggero e accanto a un'insalata fresca, rientra perfettamente nella tua dieta.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 500,
 "ings": ["1 bistecca di manzo magra (circa 130 g)", "2 patate medie",
          "1 cipolla a fettine", "1 cucchiaino di olio d'oliva",
          "sale e pepe q.b.", "foglie verdi e pomodoro per l'insalata",
          "succo di ½ limone"],
 "passos": [
   "Sbuccia e cuoci le patate in acqua bollente per 15 minuti, finché non sono molto morbide. Scolale e schiacciale con la forchetta, con un pizzico di sale, finché non diventa un purè liscio. Se lo vuoi più cremoso, aggiungi un po' dell'acqua di cottura.",
   "Condisci la bistecca con sale e pepe su entrambi i lati.",
   "Scalda una padella antiaderente a fuoco alto con qualche goccia di olio d'oliva. Metti la bistecca e lasciala 2-3 minuti per lato, senza spostarla, finché non è dorata fuori e cotta come piace a te. Toglila e mettila da parte.",
   "Nella stessa padella, metti le fettine di cipolla e il resto dell'olio d'oliva. Mescola a fuoco medio per 5 minuti, finché la cipolla non è morbida e dorata (bella dolce).",
   "Copri la bistecca con le cipolle dorate. Componi il piatto con il purè, la bistecca con le cipolle e un'insalata verde condita con il limone."],
 "porcoes8": ["100 g di carne · ½ porzione di purè · insalata",
              "130 g di carne · 1 porzione di purè · insalata",
              "130 g di carne · 1 porzione di purè · insalata",
              "150 g di carne · 1 porzione di purè · insalata",
              "150 g di carne · 1 porzione di purè · insalata",
              "170 g di carne · 1 porzione grande di purè · insalata",
              "200 g di carne · porzione grande di purè · insalata",
              "220 g di carne · porzione doppia di purè · insalata"],
 "dica": "Scegliere un taglio magro e cuocerlo senza olio trasforma la bistecca in quasi proteina pura. Le cipolle dorate portano tantissimo sapore con pochissime calorie e fanno sì che tu non abbia bisogno di salse grasse. Con il purè nella misura giusta e tanta insalata, il piatto soddisfa senza appesantirti.",
},
{
 "nome": "Gamberi saltati con verdure e riso",
 "hook": "I gamberi sono pronti in un batter d'occhio e sono leggerissimi — un pranzo veloce che sembra sofisticato.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 430,
 "ings": ["150 g di gamberi puliti", "4 cucchiai di riso integrale cotto",
          "½ zucchina a mezzelune", "½ peperone a striscioline",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Condisci i gamberi con sale, pepe, l'aglio e il succo di limone. Lasciali insaporire per 5 minuti.",
   "Scalda una padella grande con metà dell'olio d'oliva a fuoco alto. Aggiungi la zucchina e il peperone e mescola per 3 minuti, finché non sono teneri ma ancora sodi. Toglili e mettili da parte.",
   "Nella stessa padella, metti il resto dell'olio d'oliva e i gamberi. Saltali (mescola a fuoco alto) per 2-3 minuti, giusto finché non diventano rosa e non si arricciano. Attenta a non cuocerli troppo, o diventano gommosi.",
   "Rimetti le verdure in padella, aggiungi il riso integrale già cotto e mescola per 1 minuto, giusto per scaldare tutto.",
   "Spolvera il prezzemolo e servi subito."],
 "porcoes8": ["120 g di gamberi · 3 cucchiai di riso · verdure",
              "150 g di gamberi · 4 cucchiai di riso · verdure",
              "150 g di gamberi · 5 cucchiai di riso · verdure",
              "170 g di gamberi · 5 cucchiai di riso · un po' di olio d'oliva",
              "170 g di gamberi · 5 cucchiai di riso · verdure",
              "200 g di gamberi · 6 cucchiai di riso · verdure",
              "220 g di gamberi · 7 cucchiai di riso · un po' di olio d'oliva",
              "250 g di gamberi · 8 cucchiai di riso · un po' di olio d'oliva"],
 "dica": "Il gambero è quasi tutto proteine, con pochissimi grassi e poche calorie, quindi puoi mangiarne una porzione abbondante senza appesantirti. Saltato veloce a fuoco alto con le verdure, mantiene una consistenza soda e il suo sapore, in un piatto leggero pronto in pochi minuti.",
},
{
 "nome": "Pollo saltato leggero con riso integrale",
 "hook": "Il classico cinese a casa, nella versione magra: pollo a cubetti e verdure croccanti in una salsa leggera e lucida.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 460,
 "ings": ["2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 peperone a cubetti", "1 cipolla a cubetti",
          "1 gambo di sedano a pezzetti (facoltativo)",
          "1 spicchio d'aglio, tritato", "1 cucchiaio di salsa di soia chiara",
          "1 cucchiaino di amido di mais", "1 cucchiaino di olio d'oliva",
          "riso integrale per servire"],
 "passos": [
   "Condisci i cubetti di pollo con un po' della salsa di soia e l'aglio. Lasciali insaporire per 5 minuti.",
   "Sciogli l'amido di mais in mezzo bicchiere d'acqua con il resto della salsa di soia. Mescola bene e mettilo da parte — è questo che addenserà la salsa.",
   "Scalda una padella grande con metà dell'olio d'oliva a fuoco alto. Fai rosolare i cubetti di pollo per 5 minuti, mescolando, finché non sono bianchi dentro. Toglili e mettili da parte.",
   "Nella stessa padella, metti il resto dell'olio d'oliva e aggiungi il peperone, la cipolla e il sedano. Mescola a fuoco alto per 3 minuti, finché non sono teneri ma ancora croccanti.",
   "Rimetti il pollo, mescola il composto di amido e versalo in padella. Mescola per 1-2 minuti, finché la salsa non si addensa e diventa lucida, avvolgendo tutto. Servi sul riso integrale."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso",
              "1 porzione · 4 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso · pollo extra",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione grande · 6 cucchiai di riso",
              "1 porzione + pollo · 7 cucchiai di riso",
              "porzione doppia · 8 cucchiai di riso"],
 "dica": "Farlo in casa ti permette di controllare l'olio e lo zucchero di cui i ristoranti abusano. Il pollo dà proteine magre, le verdure arrivano croccanti con poche calorie e un solo tocco di amido dà quella bella salsa senza appesantire il piatto.",
},
{
 "nome": "Bowl messicana con manzo, fagioli neri e mais",
 "hook": "Tutti i colori e i sapori del Messico in una ciotola — abbondante, ben condita e sorprendentemente leggera.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 490,
 "ings": ["250 g di carne macinata magra di manzo",
          "170 g di fagioli neri cotti", "80 g di mais",
          "4 cucchiai di riso cotto", "1 pomodoro a cubetti",
          "½ avocado a fettine", "foglie verdi",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "cumino, sale, pepe e coriandolo q.b.", "succo di ½ limone"],
 "passos": [
   "Scalda l'olio d'oliva in una padella e fai soffriggere l'aglio per 30 secondi. Aggiungi la carne macinata e mescola, sgranandola, finché non perde il colore rosato.",
   "Condisci la carne con cumino, sale e pepe e cuoci per altri 3 minuti. Aggiungi i fagioli neri e il mais e scalda per 2 minuti.",
   "In una ciotola, fai un letto di foglie verdi e metti il riso da un lato.",
   "Disponi sopra la carne con i fagioli e il mais, il pomodoro e le fettine di avocado.",
   "Condisci con il succo di limone, spolvera il coriandolo e servi."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso · ¼ avocado",
              "1 porzione · 4 cucchiai di riso · ¼ avocado",
              "1 porzione · 4 cucchiai di riso · ½ avocado",
              "1 porzione · 5 cucchiai di riso · ½ avocado",
              "1 porzione · 5 cucchiai di riso · ½ avocado",
              "1 porzione grande · 6 cucchiai di riso · ½ avocado",
              "porzione grande · 7 cucchiai di riso · ½ avocado",
              "porzione doppia · 8 cucchiai di riso · avocado"],
 "dica": "È un piatto completo in una sola ciotola: proteine dalla carne, fibre dai fagioli e dal mais, e il grasso buono dell'avocado, che porta cremosità e sazietà. Ben condita, soddisfa la voglia di cibo da locale senza il grasso in eccesso.",
},
{
 "nome": "Insalata di pollo alla griglia con mango",
 "hook": "Dolce, salata e rinfrescante: il pollo caldo alla griglia incontra il mango dolce in un'insalata che non sa di dieta.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 400,
 "ings": ["1 filetto di petto di pollo (circa 130 g)", "foglie verdi miste",
          "½ mango a cubetti", "½ cetriolo a rondelle",
          "cipolla rossa a fettine sottili", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e menta q.b."],
 "passos": [
   "Condisci il pollo con sale e pepe. Scalda una padella antiaderente a fuoco medio-alto e cuoci il filetto 4-5 minuti per lato, finché non è dorato e bianco dentro. Fallo intiepidire e taglialo a striscioline.",
   "Sbuccia il mango e taglia la polpa a cubetti. Taglia il cetriolo a rondelle e la cipolla a fettine molto sottili.",
   "In una ciotola grande o in un piatto fondo, distribuisci le foglie verdi.",
   "Disponi sopra i cubetti di mango, il cetriolo, la cipolla e le striscioline di pollo.",
   "Prepara il condimento mescolando l'olio d'oliva, il succo di limone, sale e pepe. Versalo sull'insalata, spolvera la menta e servi."],
 "porcoes8": ["100 g di pollo · ¼ mango · insalata",
              "130 g di pollo · ½ mango · insalata",
              "130 g di pollo · ½ mango · insalata",
              "150 g di pollo · ½ mango · un po' di olio d'oliva",
              "150 g di pollo · ½ mango · insalata",
              "170 g di pollo · ½ mango · 1 cucchiaio di noci",
              "200 g di pollo · 1 mango · noci",
              "220 g di pollo · 1 mango · noci"],
 "dica": "Il mango entra come dolce naturale, senza zuccheri aggiunti, e soddisfa la voglia di qualcosa di dolce dentro un pasto salato. Il pollo alla griglia dà le proteine che saziano, e il volume di foglie e verdure riempie il piatto con pochissime calorie. Un'insalata che è un pasto completo.",
},
{
 "nome": "Filetto di pollo al curry leggero con riso",
 "hook": "Una salsa dorata e profumata che trasforma il solito pollo — cremosa senza panna, con il latte di cocco light.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di curry in polvere",
          "120 ml di latte di cocco light (o latte normale)",
          "1 pomodoro, a pezzetti", "1 cucchiaino di olio d'oliva",
          "sale e pepe q.b.", "riso per servire"],
 "passos": [
   "Condisci i cubetti di pollo con sale, pepe e metà del curry.",
   "Scalda l'olio d'oliva in una pentola a fuoco medio e fai rosolare i cubetti di pollo all'esterno, mescolando, per 5 minuti. Toglili e mettili da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi il resto del curry e mescola per 30 secondi, giusto perché la spezia liberi il suo profumo.",
   "Aggiungi il pomodoro e cuoci per 3 minuti, finché non si disfa. Rimetti il pollo e aggiungi il latte di cocco.",
   "Cuoci a fuoco basso per 8-10 minuti, mescolando ogni tanto, finché la salsa non si addensa e il pollo non è tenero. Servi sul riso."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso",
              "1 porzione · 4 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso · pollo extra",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione grande · 6 cucchiai di riso",
              "1 porzione + pollo · 7 cucchiai di riso",
              "porzione doppia · 8 cucchiai di riso"],
 "dica": "Il latte di cocco light dà cremosità alla salsa con molti meno grassi della panna. Il curry la profuma e dà la sensazione di un piatto speciale, il che ti aiuta a mangiare lentamente e a sentirti soddisfatta con una porzione controllata di pollo e riso.",
},
{
 "nome": "Sarde al forno con patate e insalata",
 "hook": "Economiche, piene di omega-3 e pronte in pochi minuti — le sarde sono una delle migliori amiche di chi dimagrisce senza spendere.",
 "tempo": "30 min", "rende": "1 porzione", "kcal_base": 450,
 "ings": ["3 o 4 sarde fresche pulite (o 1 scatoletta di sarde al naturale)",
          "1 patata piccola a fettine", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "1 spicchio d'aglio, tritato",
          "sale, pepe e origano q.b.",
          "foglie verdi e pomodoro per l'insalata"],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la patata a fettine sottili, condiscila con sale e metà dell'olio d'oliva e distribuiscila su una teglia.",
   "Inforna la patata per 10 minuti, per iniziare ad ammorbidirla.",
   "Condisci le sarde con sale, pepe, aglio, origano e il succo di limone.",
   "Tira fuori la teglia, metti le sarde tra le patate e condisci con il resto dell'olio d'oliva.",
   "Rimetti in forno per altri 15 minuti, finché le sarde non sono dorate e la patata morbida. Servi con un'insalata verde fresca di lato.",
   "Se usi le sarde in scatola, salta il forno per il pesce: inforna solo la patata e componi il piatto con le sarde scolate e l'insalata."],
 "porcoes8": ["2 sarde · ½ patata · insalata",
              "3 sarde · 1 patata piccola · insalata",
              "3 sarde · 1 patata · insalata",
              "4 sarde · 1 patata · un po' di olio d'oliva",
              "4 sarde · 1 patata · insalata",
              "4 sarde · 1 patata grande · insalata",
              "5 sarde · 1 patata grande · un po' di olio d'oliva",
              "6 sarde · 2 patate piccole · insalata"],
 "dica": "La sarda è un pesciolino potente: tanti omega-3 (il grasso buono che fa benissimo al cuore), proteine e calcio, a un prezzo bassissimo. Al forno con un po' di patata e un'insalata fresca, diventa un pranzo completo, nutriente ed economico.",
},
{
 "nome": "Melanzane ripiene di carne macinata",
 "hook": "La melanzana stessa diventa la ciotola — ripiena di carne condita e gratinata sopra, è bella e inganna qualsiasi voglia di abbuffata.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 420,
 "ings": ["1 melanzana grande", "200 g di carne macinata magra di manzo",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 pomodoro, a pezzetti", "1 cucchiaino di olio d'oliva",
          "2 cucchiai di formaggio grattugiato magro",
          "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la melanzana a metà per il lungo. Con un cucchiaio, togli parte della polpa centrale, formando due 'barchette'. Trita la polpa che hai tolto.",
   "Metti le barchette su una teglia, condisci con un po' di olio d'oliva e inforna per 10 minuti, giusto per ammorbidirle.",
   "Nel frattempo, in una padella, fai soffriggere la cipolla e l'aglio nel resto dell'olio d'oliva per 2 minuti. Aggiungi la carne macinata e mescola finché non perde il colore rosato.",
   "Aggiungi il pomodoro, la polpa di melanzana tritata, sale e pepe e cuoci per 5 minuti, finché non diventa un ripieno morbido.",
   "Riempi le barchette di melanzana con la carne, spolvera sopra il formaggio grattugiato e rimettile in forno per 15 minuti, finché la superficie non si gratina (il formaggio si scioglie e si dora). Spolvera il prezzemolo e servi."],
 "porcoes8": ["½ melanzana · insalata",
              "1 melanzana ripiena · insalata",
              "1 melanzana · 2 cucchiai di riso",
              "1 melanzana · carne extra · insalata",
              "1 melanzana · carne extra · 2 cucchiai di riso",
              "1 melanzana grande · 3 cucchiai di riso",
              "1 melanzana · carne doppia · 4 cucchiai di riso",
              "melanzana + porzione extra di carne · 4 cucchiai di riso"],
 "dica": "La melanzana ha tanta acqua e fibre, quindi riempie lo stomaco con pochissime calorie — ripiena, dà volume al piatto e sazia. La carne magra porta le proteine, e un po' di formaggio sopra toglie la voglia di un piatto gratinato e filante senza esagerare.",
},
{
 "nome": "Caesar salad fit con pollo alla griglia",
 "hook": "La cremosa Caesar salad che ami, con un condimento intelligente allo yogurt — tutta la cremosità, nessun senso di colpa.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 400,
 "ings": ["1 filetto di pollo alla griglia a striscioline (circa 130 g)",
          "foglie di lattuga romana", "1 fetta di pane integrale a cubetti",
          "2 cucchiai di yogurt naturale senza zucchero",
          "1 cucchiaino di senape", "1 cucchiaino di formaggio grattugiato",
          "succo di ½ limone", "1 spicchio d'aglio, schiacciato",
          "sale e pepe q.b."],
 "passos": [
   "Condisci il pollo con sale e pepe e cuocilo in una padella antiaderente per 4 minuti per lato, finché non è dorato e bianco dentro. Taglialo a striscioline.",
   "Prepara i crostini: distribuisci i cubetti di pane integrale su una teglia e inforna a fuoco medio per 8 minuti, finché non sono croccanti (oppure tostali in padella senza olio).",
   "Prepara il condimento: in una ciotolina, mescola lo yogurt, la senape, il formaggio grattugiato, il succo di limone, l'aglio schiacciato, sale e pepe, finché non diventa una crema.",
   "Spezza la lattuga con le mani e mettila in una ciotola grande. Condiscila e mescola per rivestire le foglie.",
   "Metti sopra le striscioline di pollo e i crostini e servi subito, così il pane resta croccante."],
 "porcoes8": ["100 g di pollo · insalata · pochi crostini",
              "130 g di pollo · insalata · crostini",
              "130 g di pollo · insalata · crostini",
              "150 g di pollo · insalata · 1 cucchiaio in più di formaggio",
              "150 g di pollo · insalata · crostini",
              "170 g di pollo · insalata · crostini",
              "200 g di pollo · insalata · crostini extra",
              "220 g di pollo · insalata · crostini extra"],
 "dica": "Il condimento Caesar tradizionale è una bomba di maionese e olio. Sostituirlo con lo yogurt con senape e limone mantiene la cremosità e il gusto deciso con molti meno grassi. Il pollo alla griglia trasforma l'insalata in un pasto vero, pieno di proteine.",
},
{
 "nome": "Straccetti di manzo con peperoni e riso",
 "hook": "Striscioline sottili di manzo saltate con peperoni colorati — profumate, ben condite e pronte in padella in pochi minuti.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["250 g di manzo magro a striscioline sottili",
          "1 peperone rosso a striscioline", "1 peperone giallo a striscioline",
          "1 cipolla a striscioline", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "cumino, sale, pepe e coriandolo q.b.", "riso per servire"],
 "passos": [
   "Condisci gli straccetti di manzo con sale, pepe, cumino, l'aglio e il succo di limone. Lasciali insaporire per 10 minuti.",
   "Scalda una padella grande con metà dell'olio d'oliva a fuoco alto. Metti la carne poca alla volta (non tutta insieme, o rilascia acqua) e falla rosolare veloce, mescolando, per 3 minuti. Toglila e mettila da parte.",
   "Nella stessa padella, con il resto dell'olio d'oliva, aggiungi la cipolla e i peperoni. Mescola a fuoco alto per 4 minuti, finché non sono teneri ma ancora sodi e colorati.",
   "Rimetti la carne in padella e mescola per 1 minuto, giusto per unire i sapori.",
   "Spolvera il coriandolo e servi su una porzione di riso. È ottimo anche arrotolato in una piadina integrale."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso",
              "1 porzione · 4 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso · carne extra",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione grande · 6 cucchiai di riso",
              "1 porzione + carne · 7 cucchiai di riso",
              "porzione doppia · 8 cucchiai di riso"],
 "dica": "Tagliare la carne a striscioline sottili rende di più: una porzione piccola sembra molto di più nel piatto. Saltata veloce a fuoco alto con i peperoni, resta succosa e piena di sapore senza bisogno di una salsa grassa. I peperoni portano colore, vitamine e fibre per quasi zero calorie.",
},
{
 "nome": "Hamburger di manzo magro fatto in casa con insalata",
 "hook": "L'hamburger che toglie la voglia e ti aiuta comunque a dimagrire — fatto in casa con carne magra, senza il panino unto.",
 "tempo": "20 min", "rende": "2 porzioni", "kcal_base": 440,
 "ings": ["250 g di carne macinata magra di manzo",
          "½ cipolla, tritata finemente", "1 spicchio d'aglio, tritato",
          "sale, pepe e prezzemolo q.b.", "1 cucchiaino di olio d'oliva",
          "2 panini integrali da hamburger",
          "foglie di lattuga, pomodoro e cipolla a rondelle per comporlo"],
 "passos": [
   "In una ciotola, mescola la carne macinata con la cipolla tritata, l'aglio, sale, pepe e prezzemolo. Impasta con le mani solo finché non sta insieme, senza lavorarla troppo (o l'hamburger diventa duro).",
   "Dividi la carne in due e forma due dischi, appiattendoli bene con le mani. Fai una leggera fossetta al centro di ciascuno con il pollice — questo impedisce che si gonfino in mezzo.",
   "Scalda una padella antiaderente con qualche goccia di olio d'oliva a fuoco medio-alto. Metti gli hamburger e lasciali 3-4 minuti per lato, senza schiacciarli con la spatola, finché non sono dorati fuori e cotti come piace a te dentro.",
   "Se ti va, tosta leggermente il panino integrale, aperto, in padella.",
   "Componi: panino, lattuga, l'hamburger, il pomodoro e la cipolla. Chiudi e servi. Per una versione ancora più leggera, mangia l'hamburger senza pane, con un'insalata abbondante di lato."],
 "porcoes8": ["1 hamburger · senza pane · insalata",
              "1 hamburger · ½ panino · insalata",
              "1 hamburger · 1 panino · insalata",
              "1 hamburger · 1 panino · insalata",
              "1 hamburger grande · 1 panino · insalata",
              "1 hamburger grande · 1 panino · insalata",
              "2 hamburger · 1 panino · insalata",
              "2 hamburger · 1 panino · insalata"],
 "dica": "Il problema dell'hamburger da fast food è la carne grassa, la salsa e la frittura. Fatto in casa con carne magra e cotto senza olio, diventa proteina pura. Mangiandolo con tanta insalata e poco (o niente) pane, togli la voglia senza far saltare le tue calorie.",
},
{
 "nome": "Pesce bianco con verdure e cous cous",
 "hook": "Un filetto bianco delicato su un cous cous sgranato — leggero, elegante e pronto prima che te ne accorga.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 420,
 "ings": ["1 filetto di pesce bianco (merluzzo, nasello o tilapia, circa 150 g)",
          "90 g di cous cous", "120 ml di acqua calda",
          "130 g di verdure a pezzetti (fagiolini, carota, piselli)",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Metti il cous cous in una ciotola con un pizzico di sale, coprilo con l'acqua calda, coprilo con un piatto e lascialo 5 minuti. Poi sgranalo con la forchetta finché non è ben sgranato.",
   "Cuoci le verdure a pezzetti a vapore o in poca acqua bollente per 5 minuti, finché non sono tenere ma ancora sode. Scolale.",
   "Condisci il pesce con sale, pepe e il succo di limone.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio. Metti il filetto e lascialo 3-4 minuti per lato, girandolo con delicatezza una volta, finché non è dorato e si sfalda con la forchetta.",
   "Mescola le verdure nel cous cous. Componi il piatto con il cous cous alle verdure e il filetto sopra. Spolvera il prezzemolo e servi."],
 "porcoes8": ["120 g di pesce · 60 g di cous cous · verdure",
              "150 g di pesce · 90 g di cous cous · verdure",
              "150 g di pesce · 90 g di cous cous · verdure",
              "170 g di pesce · 115 g di cous cous · un po' di olio d'oliva",
              "170 g di pesce · 115 g di cous cous · verdure",
              "200 g di pesce · 130 g di cous cous · verdure",
              "220 g di pesce · 175 g di cous cous · un po' di olio d'oliva",
              "250 g di pesce · 175 g di cous cous · un po' di olio d'oliva"],
 "dica": "I pesci bianchi come il merluzzo e il nasello sono magrissimi e leggeri, ideali per il pranzo di chi vuole dimagrire. Il cous cous cuoce con la sola acqua calda, senza grassi, e con le verdure diventa un contorno colorato, sgranato e pieno di fibre.",
},
{
 "nome": "Spiedini di pollo e verdure con riso",
 "hook": "Colorati e divertenti da comporre, gli spiedini cuociono in modo uniforme e danno a qualsiasi pranzo un'aria di festa.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 450,
 "ings": ["2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 peperone a quadrotti", "1 cipolla a pezzi",
          "1 zucchina a rondelle spesse", "pomodorini",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e paprika q.b.", "riso per servire",
          "stecchini per spiedini"],
 "passos": [
   "Condisci i cubetti di pollo con sale, pepe, paprika e il succo di limone. Lasciali insaporire per 10 minuti.",
   "Componi gli spiedini alternando un cubetto di pollo, un pezzo di peperone, uno di cipolla, una rondella di zucchina e un pomodorino, finché lo stecchino non è pieno.",
   "Spennella gli spiedini con l'olio d'oliva.",
   "Scalda una padella grande o una piastra a fuoco medio-alto. Metti gli spiedini e girali ogni 3 minuti, finché il pollo non è dorato su tutti i lati e bianco dentro (circa 12 minuti in tutto).",
   "Servi gli spiedini su una porzione di riso."],
 "porcoes8": ["1 spiedino · 3 cucchiai di riso",
              "2 spiedini · 4 cucchiai di riso",
              "2 spiedini · 5 cucchiai di riso",
              "2 spiedini · 5 cucchiai di riso · pollo extra",
              "2 spiedini · 5 cucchiai di riso",
              "3 spiedini · 6 cucchiai di riso",
              "3 spiedini · 7 cucchiai di riso",
              "3 spiedini grandi · 8 cucchiai di riso"],
 "dica": "Gli spiedini ti aiutano a controllare la porzione in modo naturale e a mescolare tante verdure alle proteine. Il pollo magro alla griglia porta sazietà senza grassi, e le verdure colorate riempiono il piatto di fibre e vitamine per quasi zero calorie.",
},
{
 "nome": "Insalata di patate fit con uovo e tonno",
 "hook": "La cremosa insalata di patate delle feste, senza la maionese pesante — diventa un pranzo completo e leggero.",
 "tempo": "25 min", "rende": "2 porzioni", "kcal_base": 410,
 "ings": ["2 patate medie a cubetti", "2 uova sode",
          "1 scatoletta di tonno al naturale, scolata",
          "3 cucchiai di yogurt naturale senza zucchero",
          "1 cucchiaino di senape",
          "cipolla rossa ed erbe fresche tritate",
          "sale, pepe e succo di ½ limone q.b."],
 "passos": [
   "Cuoci i cubetti di patata in acqua bollente salata per 12-15 minuti, finché non sono morbidi ma non si sfaldano (la forchetta entra facilmente). Scolali e falli intiepidire.",
   "Cuoci le uova per 9 minuti, passale sotto l'acqua fredda, sbucciale e tagliale a pezzi.",
   "Prepara il condimento: mescola lo yogurt, la senape, il succo di limone, sale e pepe in una ciotola grande.",
   "Aggiungi nella ciotola la patata tiepida, il tonno scolato, le uova, la cipolla rossa e le erbe fresche.",
   "Mescola con delicatezza, per non rompere la patata. Aggiusta di sale e servi subito o fredda."],
 "porcoes8": ["½ porzione · ½ scatoletta di tonno · 1 uovo",
              "1 porzione · 1 scatoletta di tonno · 2 uova",
              "1 porzione · 1 scatoletta di tonno · 2 uova",
              "1 porzione · 1 scatoletta di tonno · 2 uova · insalata verde",
              "1 porzione · 1 scatoletta di tonno · 2 uova",
              "1 porzione grande · 1½ scatolette di tonno · 2 uova",
              "porzione grande · 1½ scatolette di tonno · 3 uova",
              "porzione doppia · 2 scatolette di tonno · 3 uova"],
 "dica": "Sostituire la maionese con lo yogurt e la senape taglia moltissimi grassi e aggiunge comunque proteine. Il tonno e l'uovo trasformano un'insalata di patate in un pasto completo e saziante. La patata raffreddata forma perfino una fibra speciale che nutre i batteri buoni del tuo intestino.",
},
{
 "nome": "Pollo arrosto al forno con ortaggi a radice",
 "hook": "Metti tutto in una teglia e lascia lavorare il forno — il pollo esce dorato e le verdure diventano morbide e dolci.",
 "tempo": "45 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["2 cosce di pollo senza pelle (o 2 filetti spessi, circa 300 g)",
          "1 patata a pezzi", "1 carota a pezzi grandi",
          "1 pezzo di zucca a cubetti", "1 cipolla a spicchi",
          "2 spicchi d'aglio", "1 cucchiaino di olio d'oliva",
          "succo di ½ limone", "sale, pepe e rosmarino q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la patata, la carota, la zucca e la cipolla a pezzi grandi e simili tra loro, così arrostiscono in modo uniforme.",
   "Su una teglia grande, distribuisci le verdure e gli spicchi d'aglio. Condisci con sale, pepe, rosmarino e metà dell'olio d'oliva, e mescola con le mani.",
   "Condisci il pollo con sale, pepe, il succo di limone e il resto dell'olio d'oliva. Metti i pezzi tra le verdure.",
   "Inforna per 35-40 minuti, girando le verdure a metà cottura, finché il pollo non è dorato e cotto dentro (il liquido che esce quando lo punzecchi deve uscire trasparente) e le verdure morbide.",
   "Servi direttamente dalla teglia, con tutti i succhi che si sono formati sul fondo."],
 "porcoes8": ["1 coscia · ½ porzione di verdure",
              "1 coscia · 1 porzione di verdure",
              "1 coscia grande · 1 porzione di verdure",
              "2 cosce · 1 porzione di verdure",
              "2 cosce · 1 porzione di verdure",
              "2 cosce · 1 porzione grande di verdure",
              "2 cosce · porzione grande di verdure",
              "3 cosce · porzione doppia di verdure"],
 "dica": "Arrostire senza pelle e senza troppo olio mantiene il pollo leggero, e i succhi che rilascia condiscono le verdure senza bisogno di grassi. La zucca e la carota diventano dolci arrostendo, togliendo la voglia di qualcosa di dolce, e riempiono il piatto di fibre e vitamine per poche calorie.",
},
{
 "nome": "Cotoletta di pollo fit al forno con insalata",
 "hook": "La cotoletta croccante e filante dei tuoi sogni, al forno invece che fritta — tutto il piacere, niente frittura.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["2 filetti sottili di petto di pollo (circa 300 g)", "1 uovo",
          "4 cucchiai di pangrattato integrale",
          "240 ml di passata di pomodoro fatta in casa",
          "3 cucchiai di mozzarella magra grattugiata",
          "sale, pepe e origano q.b.", "foglie verdi per l'insalata"],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Condisci i filetti sottili con sale e pepe.",
   "Sbatti l'uovo in un piatto fondo. Metti il pangrattato in un altro piatto, mescolato con l'origano.",
   "Passa ogni filetto prima nell'uovo, poi nel pangrattato, premendo per impanare bene entrambi i lati.",
   "Metti i filetti su una teglia antiaderente (o rivestita di carta da forno) e inforna per 15 minuti, girandoli a metà, finché la panatura non è dorata e croccante.",
   "Copri ogni filetto con la passata di pomodoro e il formaggio grattugiato. Rimetti in forno per altri 8 minuti, finché il formaggio non si scioglie e sfrigola.",
   "Servi con un'insalata verde fresca di lato."],
 "porcoes8": ["100 g di pollo · poco formaggio · insalata",
              "130 g di pollo · formaggio · insalata",
              "150 g di pollo · formaggio · insalata",
              "150 g di pollo · formaggio · 3 cucchiai di riso",
              "150 g di pollo · formaggio · 3 cucchiai di riso",
              "170 g di pollo · formaggio · 4 cucchiai di riso",
              "200 g di pollo · formaggio · 5 cucchiai di riso",
              "220 g di pollo · formaggio extra · 5 cucchiai di riso"],
 "dica": "La cotoletta fa ingrassare per la frittura e per il formaggio in eccesso. Impanata con pangrattato integrale e cotta al forno, viene croccante con una frazione dei grassi. Un po' di formaggio magro sopra toglie la voglia di un piatto filante, e l'insalata bilancia il piatto.",
},
{
 "nome": "Bowl di riso, edamame e salmone",
 "hook": "Ispirata al poke hawaiano: fresca, colorata e nutriente, costruita in una ciotola e saziante senza appesantirti.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 480,
 "ings": ["1 filetto di salmone a cubetti (circa 130 g)",
          "4 cucchiai di riso cotto",
          "80 g di edamame cotto (fagioli di soia verdi)",
          "½ cetriolo a cubetti piccoli", "½ carota, grattugiata",
          "½ avocado a fettine", "1 cucchiaio di salsa di soia chiara",
          "semi di sesamo, succo di ½ limone ed erba cipollina q.b."],
 "passos": [
   "Cuoci l'edamame in acqua bollente per 4 minuti, scolalo e, se è nel baccello, tirane fuori i fagiolini.",
   "Condisci i cubetti di salmone con la salsa di soia e il succo di limone. Lasciali insaporire per 5 minuti. (Se lo preferisci cotto, scotta velocemente i cubetti in padella per 3 minuti.)",
   "In una ciotola, metti il riso da un lato come base.",
   "Disponi sopra, in gruppi separati, il salmone, l'edamame, il cetriolo, la carota grattugiata e l'avocado.",
   "Condisci con ancora un po' di salsa di soia, spolvera i semi di sesamo e l'erba cipollina e servi."],
 "porcoes8": ["100 g di salmone · 3 cucchiai di riso · ¼ avocado",
              "130 g di salmone · 4 cucchiai di riso · ½ avocado",
              "130 g di salmone · 5 cucchiai di riso · ½ avocado",
              "150 g di salmone · 5 cucchiai di riso · ½ avocado",
              "150 g di salmone · 5 cucchiai di riso · ½ avocado",
              "170 g di salmone · 6 cucchiai di riso · ½ avocado",
              "200 g di salmone · 7 cucchiai di riso · avocado",
              "220 g di salmone · 8 cucchiai di riso · avocado"],
 "dica": "È un piatto completo ed equilibrato: proteine e omega-3 dal salmone, proteine vegetali dall'edamame, grassi buoni dall'avocado e le fibre delle verdure crude. Costruito in una ciotola, è bellissimo e saziante, e dimostra che il cibo sano può essere una festa per gli occhi.",
},
{
 "nome": "Zuppa sostanziosa di verdure con pollo sfilacciato",
 "hook": "Una zuppa che è un pasto vero: piena di pollo e verdure, scalda il corpo e sazia senza appesantirti.",
 "tempo": "35 min", "rende": "3 porzioni", "kcal_base": 380,
 "ings": ["1 filetto di petto di pollo (circa 150 g)", "1 patata a cubetti",
          "1 carota a cubetti", "1 zucchina a cubetti",
          "80 g di mais o piselli", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 cucchiaino di olio d'oliva",
          "sale, pepe ed erbe fresche q.b.", "1 litro di acqua"],
 "passos": [
   "In una pentola grande, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando, finché non diventano trasparenti.",
   "Aggiungi il filetto di pollo intero e l'acqua. Porta a bollore e cuoci per 15 minuti, finché il pollo non è cotto.",
   "Tira fuori il pollo, fallo intiepidire e sfilaccialo con due forchette. Mettilo da parte.",
   "Nella stessa acqua, aggiungi la patata, la carota, la zucchina e il mais. Aggiusta di sale e pepe e cuoci per 12-15 minuti, finché le verdure non sono morbide.",
   "Rimetti il pollo sfilacciato nella pentola, aggiusta di sale e cuoci per altri 3 minuti. Spolvera le erbe fresche e servi ben caldo."],
 "porcoes8": ["1 mestolo · pollo · senza patata extra",
              "2 mestoli · pollo · verdure",
              "2 mestoli · pollo · verdure",
              "2 mestoli · pollo extra · 1 fetta di pane",
              "2 mestoli · pollo extra · 1 fetta di pane",
              "3 mestoli · pollo · 1 fetta di pane",
              "3 mestoli · pollo extra · 2 fette di pane",
              "3 mestoli grandi · doppio pollo · 2 fette di pane"],
 "dica": "Le zuppe sono ottime per dimagrire: il volume di liquido e verdure riempie lo stomaco con pochissime calorie, e il calore ti fa mangiare più lentamente. Con il pollo sfilacciato, smette di essere solo un antipasto e diventa un pasto completo, leggero e avvolgente.",
},
{
 "nome": "Pancake salato di avena ripieno di pollo",
 "hook": "L'impasto vuole solo uovo e avena, si frulla in pochi secondi e diventa un pancake dorato ripieno di pollo cremoso.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 400,
 "ings": ["1 uovo", "3 cucchiai di avena", "3 cucchiai di acqua",
          "1 pizzico di sale",
          "1 filetto di pollo cotto e sfilacciato (circa 100 g)",
          "2 cucchiai di passata di pomodoro",
          "1 cucchiaio di yogurt naturale", "1 cucchiaino di olio d'oliva",
          "origano q.b."],
 "passos": [
   "In una ciotola, sbatti con la forchetta l'uovo, l'avena, l'acqua e il sale finché non diventa un impasto liscio. Lascia riposare 3 minuti perché l'avena assorba il liquido.",
   "Scalda una padella antiaderente con metà dell'olio d'oliva a fuoco medio. Versa l'impasto e distribuiscilo ruotando la padella, formando un disco sottile.",
   "Lascialo 2 minuti, finché il bordo non si stacca, giralo con delicatezza e fai dorare l'altro lato per un altro minuto. Togli il pancake.",
   "Mescola il pollo sfilacciato con la passata di pomodoro, lo yogurt e l'origano, e scaldalo velocemente in padella.",
   "Farcisci il pancake con il pollo, piegalo a metà o arrotolalo e servi caldo, con un'insalata di lato se ti va."],
 "porcoes8": ["1 pancake · 80 g di pollo",
              "1 pancake · 100 g di pollo",
              "1 pancake · 120 g di pollo",
              "1 pancake · 120 g di pollo · insalata",
              "1 pancake · 130 g di pollo · insalata",
              "2 pancake · 150 g di pollo",
              "2 pancake · 170 g di pollo · insalata",
              "2 pancake · 200 g di pollo · insalata"],
 "dica": "Un impasto di uovo e avena sostituisce la farina bianca con fibre e proteine, saziando molto più di un pancake normale. Farcito con pollo sfilacciato e una salsa leggera allo yogurt, diventa un pasto pratico, saporito e completo, ottimo anche per cena.",
},
{
 "nome": "Gamberi all'aglio con verdure e riso",
 "hook": "Gamberi rosa rosolati nell'aglio, che riempiono di profumo tutta la cucina — un pranzo del fine settimana leggero e speciale.",
 "tempo": "20 min", "rende": "1 porzione", "kcal_base": 430,
 "ings": ["150 g di gamberi puliti", "4 cucchiai di riso cotto",
          "100 g di broccoli e fagiolini", "2 spicchi d'aglio, tritati",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe e prezzemolo q.b."],
 "passos": [
   "Asciuga bene i gamberi con la carta da cucina e condiscili con sale, pepe e il succo di limone. Lasciali insaporire per 5 minuti.",
   "Taglia i broccoli a cimette e i fagiolini a pezzetti. Cuocili a vapore o in poca acqua bollente per 4 minuti, finché non sono verdi e teneri ma ancora sodi. Scolali.",
   "Scalda una padella antiaderente con l'olio d'oliva a fuoco medio. Aggiungi l'aglio tritato e mescola per 30 secondi, giusto finché non profuma e inizia a dorarsi — attenta a non bruciarlo, o diventa amaro.",
   "Metti i gamberi e saltali (mescola a fuoco medio-alto) per 2-3 minuti, giusto finché non diventano rosa e non si arricciano. Non cuocerli troppo, o diventano gommosi.",
   "Aggiungi in padella le verdure e il riso già cotto e mescola per 1 minuto, per prendere il sapore dell'aglio. Spolvera il prezzemolo e servi subito."],
 "porcoes8": ["120 g di gamberi · 3 cucchiai di riso · verdure",
              "150 g di gamberi · 4 cucchiai di riso · verdure",
              "150 g di gamberi · 5 cucchiai di riso · verdure",
              "170 g di gamberi · 5 cucchiai di riso · un po' di olio d'oliva",
              "170 g di gamberi · 5 cucchiai di riso · verdure",
              "200 g di gamberi · 6 cucchiai di riso · verdure",
              "220 g di gamberi · 7 cucchiai di riso · un po' di olio d'oliva",
              "250 g di gamberi · 8 cucchiai di riso · un po' di olio d'oliva"],
 "dica": "Il gambero è quasi tutto proteine, con pochissimi grassi e poche calorie, quindi puoi servirtene in abbondanza senza sensi di colpa. Rosolato nell'aglio, guadagna tantissimo sapore con appena un po' di olio d'oliva, e con le verdure e una porzione misurata di riso diventa un piatto leggero che sembra da ristorante.",
},
{
 "nome": "Polpette di manzo al sugo con purè di patate",
 "hook": "Polpette morbide in un sugo di pomodoro ricco, su un purè leggero — l'abbraccio caldo che la tua dieta ti concede.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 490,
 "ings": ["250 g di carne macinata magra di manzo", "1 uovo",
          "2 cucchiai di avena", "1 spicchio d'aglio, tritato",
          "3 pomodori, a pezzetti (o passata di pomodoro)",
          "1 cipolla, tritata", "2 patate medie",
          "1 cucchiaino di olio d'oliva", "sale, pepe e basilico q.b."],
 "passos": [
   "Sbuccia e cuoci le patate in acqua bollente per 15 minuti, finché non sono molto morbide. Scolale e schiacciale con la forchetta, con un pizzico di sale, finché non diventa un purè liscio. Se lo vuoi più cremoso, aggiungi un po' dell'acqua di cottura.",
   "In una ciotola, mescola la carne macinata, l'uovo, l'avena, metà dell'aglio, sale e pepe. Impasta con le mani e forma delle palline grandi come una noce.",
   "Scalda l'olio d'oliva in una pentola e fai rosolare le polpette su tutti i lati, girandole con delicatezza, per 5 minuti. Toglile e mettile da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e il resto dell'aglio per 2 minuti. Aggiungi i pomodori, sale e pepe e cuoci per 8 minuti, finché non diventa un sugo.",
   "Rimetti le polpette nel sugo e cuoci per altri 8 minuti, finché non sono cotte dentro. Spolvera il basilico.",
   "Servi le polpette con il sugo sul purè di patate."],
 "porcoes8": ["3 polpette · ½ porzione di purè",
              "4 polpette · 1 porzione di purè",
              "4 polpette · 1 porzione di purè",
              "5 polpette · 1 porzione di purè",
              "5 polpette · 1 porzione di purè",
              "6 polpette · 1 porzione grande di purè",
              "7 polpette · porzione grande di purè",
              "8 polpette · porzione doppia di purè"],
 "dica": "Le polpette usano l'avena al posto di altro pane, il che le lega con fibre invece che con amido bianco. Fatte con carne magra e cotte nel sugo (non fritte), restano succose e leggere. Il purè di patate normale, nella misura giusta, è avvolgente e saziante.",
},
{
 "nome": "Risotto leggero con pollo e verdure",
 "hook": "La cremosità del risotto senza burro e senza formaggio in eccesso — il riso rilascia la sua crema e avvolge il pollo e le verdure.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 480,
 "ings": ["185 g di riso (arborio o normale)",
          "2 filetti di petto di pollo a cubetti (circa 300 g)",
          "1 carota a cubetti piccoli", "75 g di piselli",
          "1 cipolla, tritata", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di olio d'oliva", "1 cucchiaio di formaggio grattugiato",
          "sale, pepe e prezzemolo q.b.",
          "brodo vegetale fatto in casa o acqua calda (circa 700 ml)"],
 "passos": [
   "Condisci i cubetti di pollo con sale e pepe. Scalda l'olio d'oliva in una pentola e fai rosolare il pollo per 5 minuti, mescolando. Toglilo e mettilo da parte.",
   "Nella stessa pentola, fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi il riso e mescola per 1 minuto, giusto per rivestire i chicchi di condimento.",
   "Inizia ad aggiungere il brodo caldo poco alla volta, un mestolo per volta, mescolando sempre. Aggiungi altro brodo solo quando il precedente si è quasi asciugato.",
   "A metà cottura (circa 10 minuti), aggiungi la carota e i piselli. Continua a mescolare e ad aggiungere brodo.",
   "Quando il riso è morbido e cremoso (circa 18-20 minuti in tutto), rimetti il pollo, aggiungi il formaggio grattugiato e mescola. Spegni, spolvera il prezzemolo e servi subito."],
 "porcoes8": ["½ porzione · pollo",
              "1 porzione · pollo",
              "1 porzione · pollo",
              "1 porzione · pollo extra",
              "1 porzione · pollo extra",
              "1 porzione grande · pollo",
              "porzione grande · pollo extra",
              "porzione doppia · pollo extra"],
 "dica": "Il risotto tradizionale richiede tanto burro e formaggio. Qui la cremosità arriva dall'amido del riso stesso rilasciato dal mescolare, con appena un tocco di formaggio. Con tanto pollo e verdure, il piatto è sostanzioso e soddisfacente, e dimostra che si può mangiare il risotto senza sensi di colpa.",
},
]
