# -*- coding: utf-8 -*-
"""BÔNUS 1 — DIETA VEGETARIANA: 8 receitas NOVAS (fotos 151-158).
São os únicos pratos que o livro principal não tem em versão vegetariana
(almoços e jantares principais sempre levam carne/peixe). Café, sobremesa e
sucos da dieta vegetariana são referências a receitas que já existem no livro.
Ovo-lacto vegetariano; proteína de leguminosas, tofu, ovos e queijos.
ALMOCOS -> tipo 'almoco' (metas 360/440/500/560 · 540/610/680/750), fotos 151-154
JANTARES -> tipo 'jantar' (metas 340/420/480/540 · 520/590/650/720), fotos 155-158
"""

ALMOCOS = [
{
 "nome": "Bowl de Grão-de-Bico com Arroz e Legumes Assados",
 "tag": "Almoço vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Uma tigela colorida e farta, sem carne nenhuma — o grão-de-bico sustenta a tarde inteira como um prato de proteína.",
 "tempo": "35 min", "rende": "1 porção", "kcal_base": 500,
 "ings": ["½ xícara de grão-de-bico cozido (ou de lata, escorrido)", "4 colheres de sopa de arroz integral cozido",
          "1 abobrinha em pedaços", "½ pimentão em pedaços", "½ cebola roxa em pedaços", "tomatinhos",
          "1 colher de chá de azeite", "suco de ½ limão", "sal, pimenta, cúrcuma e orégano a gosto", "folhas verdes"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a abobrinha, o pimentão e a cebola em pedaços parecidos, do tamanho de um bocado.",
   "Numa assadeira, espalhe os legumes e os tomatinhos, tempere com sal, pimenta, orégano e metade do azeite, e misture com as mãos.",
   "Leve ao forno por 20 a 25 minutos, até os legumes ficarem macios e dourados nas pontas. Vire na metade do tempo.",
   "Numa frigideira, aqueça o restante do azeite e refogue o grão-de-bico com a cúrcuma, sal e pimenta por 3 minutos, mexendo, só para pegar sabor e dourar de leve.",
   "Monte a tigela: uma cama de folhas verdes, o arroz de um lado, o grão-de-bico e os legumes assados por cima. Regue com o suco de limão e sirva."],
 "porcoes8": ["⅓ xíc. grão · 3 col. arroz · legumes",
              "½ xíc. grão · 4 col. arroz · legumes",
              "½ xíc. grão · 5 col. arroz · legumes",
              "⅔ xíc. grão · 5 col. arroz · 1 fio de azeite",
              "⅔ xíc. grão · 5 col. arroz · legumes",
              "¾ xíc. grão · 6 col. arroz · 1 col. castanhas",
              "1 xíc. grão · 7 col. arroz · abacate",
              "1 xíc. grão · 8 col. arroz · abacate"],
 "dica": "O grão-de-bico combina proteína e fibra que saciam como um prato de carne, e junto com o arroz integral forma uma proteína completa (a dupla leguminosa + cereal que os vegetarianos usam). Assar os legumes concentra o sabor sem gordura, deixando o prato leve e cheio de gosto.",
 "prompt": "Square ultra-realistic overhead food photograph of a colorful vegetarian bowl with chickpeas, brown rice, roasted zucchini, pepper, red onion and cherry tomatoes on green leaves, in a white bowl, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Escondidinho de Lentilha com Purê de Batata",
 "tag": "Almoço vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Todo o conforto de um escondidinho gratinado, com um recheio de lentilha temperada no lugar da carne — cremoso e cheio de proteína vegetal.",
 "tempo": "45 min", "rende": "2 porções", "kcal_base": 470,
 "ings": ["1 xícara de lentilha cozida", "2 batatas médias", "1 cebola picada", "2 dentes de alho picados",
          "1 tomate picado", "1 cenoura ralada", "1 colher de chá de azeite",
          "2 colheres de sopa de queijo ralado", "sal, pimenta, cúrcuma e cheiro-verde a gosto"],
 "passos": [
   "Descasque e cozinhe as batatas em água fervente por 15 minutos, até ficarem bem macias. Escorra e amasse com um garfo, com uma pitada de sal, até virar um purê liso.",
   "Numa frigideira, aqueça o azeite e frite a cebola e o alho por 2 minutos. Junte a cenoura ralada e o tomate e cozinhe por 3 minutos.",
   "Acrescente a lentilha cozida, a cúrcuma, sal e pimenta e cozinhe por mais 5 minutos, amassando um pouco a lentilha com a colher, até formar um recheio encorpado.",
   "Num refratário, espalhe metade do purê no fundo, o recheio de lentilha no meio e o restante do purê por cima. Polvilhe o queijo ralado.",
   "Leve ao forno médio-alto (200 °C) por 15 minutos, até a superfície dourar. Salpique cheiro-verde e sirva."],
 "porcoes8": ["½ porção · salada",
              "1 porção · salada",
              "1 porção · salada",
              "1 porção · 1 col. queijo a mais · salada",
              "1 porção · lentilha extra · salada",
              "1 porção grande · salada",
              "1 porção grande · lentilha extra · salada",
              "porção dupla · salada"],
 "dica": "A lentilha é rica em ferro, fibra e proteína vegetal, um trio que sacia bastante — no escondidinho, substitui a carne com folga. Com o purê de batata na medida certa e um pouco de queijo gratinado, é um prato reconfortante que engana a vontade de comida pesada.",
 "prompt": "Square ultra-realistic overhead food photograph of a lentil shepherd's pie topped with golden mashed potato gratin in a white baking dish, a spoon lifting a portion, a small salad beside it, on a light wooden table, soft natural light, comforting and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frittata de Legumes",
 "tag": "Almoço vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Uma omelete alta e fofa, assada com legumes coloridos e queijo — proteína dos ovos num prato que corta em fatias e agrada todo mundo.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 420,
 "ings": ["5 ovos", "1 abobrinha em cubinhos", "½ pimentão picado", "1 tomate picado", "punhado de espinafre",
          "3 colheres de sopa de queijo branco em cubos", "1 colher de chá de azeite",
          "cebolinha, sal e pimenta a gosto", "folhas verdes para a salada"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Numa frigideira que possa ir ao forno, aqueça o azeite e refogue a abobrinha e o pimentão por 4 minutos, mexendo, até amaciarem.",
   "Junte o espinafre e mexa por 1 minuto, só até murchar (as folhas ficarem moles). Espalhe os legumes pela frigideira.",
   "Numa tigela, bata os ovos com sal e pimenta. Junte o tomate, o queijo e a cebolinha e misture.",
   "Despeje os ovos sobre os legumes na frigideira e deixe 2 minutos no fogo, só para firmar a borda.",
   "Leve a frigideira ao forno por 15 minutos, até a frittata inflar, firmar no centro e dourar por cima. Corte em fatias e sirva com uma salada verde."],
 "porcoes8": ["1 fatia · salada",
              "1 fatia grande · salada",
              "1 fatia grande · salada · 2 col. arroz",
              "2 fatias · salada · 2 col. arroz",
              "2 fatias · salada · 3 col. arroz",
              "2 fatias grandes · salada · 3 col. arroz",
              "2 fatias grandes · salada · 4 col. arroz",
              "3 fatias · salada · 4 col. arroz"],
 "dica": "Os ovos são proteína completa e muito saciante, ideais para um almoço vegetariano sem leguminosas. Assada com legumes e um pouco de queijo, a frittata rende, guarda bem na geladeira e mata a fome de forma leve e nutritiva.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked vegetable frittata with zucchini, pepper, tomato and spinach, cut into slices in a skillet, a fresh green salad beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chili Vegetariano de Feijão e Grão-de-Bico",
 "tag": "Almoço vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Um ensopado picante e encorpado, sem carne nenhuma — a prova de que comida vegetariana também enche o prato e a barriga.",
 "tempo": "30 min", "rende": "3 porções", "kcal_base": 460,
 "ings": ["1 xícara de feijão vermelho cozido", "1 xícara de grão-de-bico cozido", "½ xícara de milho",
          "1 cebola picada", "2 dentes de alho picados", "1 pimentão picado", "2 tomates picados (ou molho de tomate)",
          "1 colher de chá de azeite", "1 colher de chá de cominho", "sal, pimenta e páprica a gosto",
          "arroz para servir"],
 "passos": [
   "Aqueça o azeite numa panela em fogo médio. Frite a cebola, o alho e o pimentão por 3 minutos, mexendo, até amaciarem.",
   "Junte o cominho, a páprica, sal e pimenta e mexa por 30 segundos, para os temperos soltarem o aroma.",
   "Acrescente os tomates picados e cozinhe por 5 minutos, até desmancharem num molho.",
   "Junte o feijão vermelho, o grão-de-bico e o milho. Se ficar seco, coloque meia xícara de água.",
   "Abaixe o fogo e cozinhe por 15 minutos, mexendo de vez em quando, até engrossar num ensopado cremoso. Sirva com um pouco de arroz."],
 "porcoes8": ["½ porção · 3 col. arroz",
              "1 porção · 4 col. arroz",
              "1 porção · 5 col. arroz",
              "1 porção · 5 col. arroz · abacate",
              "1 porção · 5 col. arroz",
              "1 porção grande · 6 col. arroz",
              "porção grande · 7 col. arroz · abacate",
              "porção dupla · 8 col. arroz"],
 "dica": "Feijão e grão-de-bico juntos formam uma proteína vegetal muito completa, com uma montanha de fibra que sacia por horas. Servido com arroz, fecha a proteína completa. É um prato barato, que rende para vários dias e prova que dá para comer bem sem carne.",
 "prompt": "Square ultra-realistic overhead food photograph of a vegetarian red bean and chickpea chili with corn and pepper in a rustic bowl, a little rice beside it, coriander on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
]

JANTARES = [
{
 "nome": "Sopa Substanciosa de Lentilha com Legumes",
 "tag": "Jantar vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Uma sopa que é refeição de verdade: a lentilha deixa o caldo encorpado e cheio de proteína, aquecendo e saciando numa noite fria.",
 "tempo": "40 min", "rende": "3 porções", "kcal_base": 380,
 "ings": ["1 xícara de lentilha crua", "1 batata em cubos", "1 cenoura em cubos", "1 talo de salsão picado (opcional)",
          "1 tomate picado", "1 cebola picada", "2 dentes de alho picados", "1 colher de chá de azeite",
          "sal, pimenta, cúrcuma e cheiro-verde a gosto", "1,2 litro de água"],
 "passos": [
   "Lave a lentilha. Numa panela, aqueça o azeite e frite a cebola e o alho por 2 minutos, mexendo.",
   "Junte o tomate, a cenoura, a batata e o salsão e mexa por 2 minutos.",
   "Acrescente a lentilha, a cúrcuma, sal, pimenta e a água. Deixe ferver.",
   "Abaixe o fogo e cozinhe por 25 a 30 minutos, mexendo de vez em quando, até a lentilha e os legumes ficarem bem macios e o caldo encorpar. Se secar demais, junte um pouco de água quente.",
   "Prove o sal, salpique cheiro-verde e sirva bem quente."],
 "porcoes8": ["1 concha · sem pão",
              "2 conchas · sem pão",
              "2 conchas · 1 fatia pão",
              "2 conchas · 1 fatia pão",
              "2 conchas · 1 fatia pão",
              "3 conchas · 1 fatia pão",
              "3 conchas · 2 fatias pão",
              "3 conchas grandes · 2 fatias pão"],
 "dica": "A lentilha é uma das leguminosas mais ricas em proteína e ferro, e na sopa deixa o caldo substancioso o suficiente para ser um jantar completo sem carne. O muito líquido e os legumes enchem o estômago com poucas calorias — leve, quentinho e reconfortante.",
 "prompt": "Square ultra-realistic overhead food photograph of a hearty lentil soup with potato, carrot and tomato in a thick broth, in a rustic bowl, parsley on top, on a light wooden table, soft natural light, warm and comforting, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Tofu Grelhado com Legumes e Arroz",
 "tag": "Jantar vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "O tofu dourado absorve o tempero e fica delicioso — uma opção sem carne que sacia de verdade e é leve para a noite.",
 "tempo": "25 min", "rende": "1 porção", "kcal_base": 420,
 "ings": ["150 g de tofu firme em fatias", "4 colheres de sopa de arroz integral cozido", "1 xícara de brócolis e cenoura",
          "1 colher de sopa de molho de soja light", "1 dente de alho picado", "1 colher de chá de azeite",
          "gengibre ralado (opcional)", "sal e pimenta a gosto"],
 "passos": [
   "Seque bem as fatias de tofu com papel-toalha, apertando de leve — quanto mais seco, melhor ele doura.",
   "Tempere o tofu com o molho de soja, o alho e o gengibre. Deixe pegar gosto por 5 minutos.",
   "Aqueça uma frigideira que não gruda com metade do azeite em fogo médio-alto. Grelhe as fatias de tofu por 3 a 4 minutos de cada lado, sem mexer, até formar uma casquinha dourada. Tire e deixe de lado.",
   "Corte o brócolis em buquês e a cenoura em rodelas. Na mesma frigideira, com o restante do azeite, salteie os legumes por 4 minutos, até ficarem macios mas ainda firmes.",
   "Monte o prato com o arroz integral, os legumes e o tofu grelhado por cima. Regue com um pouco mais de molho de soja se quiser."],
 "porcoes8": ["120 g tofu · 3 col. arroz · legumes",
              "150 g tofu · 4 col. arroz · legumes",
              "150 g tofu · 5 col. arroz · legumes",
              "170 g tofu · 5 col. arroz · 1 fio de azeite",
              "170 g tofu · 5 col. arroz · legumes",
              "200 g tofu · 6 col. arroz · legumes",
              "220 g tofu · 7 col. arroz · 1 col. castanhas",
              "250 g tofu · 8 col. arroz · castanhas"],
 "dica": "O tofu é feito de soja e traz proteína vegetal com pouca gordura, sendo uma das melhores opções para variar da carne. Bem seco e grelhado, ganha textura e absorve os temperos. Com legumes e arroz integral, vira um jantar completo, leve e cheio de fibra.",
 "prompt": "Square ultra-realistic overhead food photograph of golden pan-grilled tofu slices with sautéed broccoli and carrot over brown rice, in a bowl, sesame and soy glaze, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Berinjela Recheada com Grão-de-Bico e Queijo",
 "tag": "Jantar vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "A própria berinjela vira a tigela, recheada de grão-de-bico temperado e gratinada com queijo — bonita, farta e sem carne.",
 "tempo": "40 min", "rende": "2 porções", "kcal_base": 400,
 "ings": ["1 berinjela grande", "1 xícara de grão-de-bico cozido", "1 cebola picada", "1 dente de alho picado",
          "1 tomate picado", "1 colher de chá de azeite", "2 colheres de sopa de queijo ralado magro",
          "sal, pimenta, cominho e salsinha a gosto"],
 "passos": [
   "Ligue o forno em temperatura média-alta (200 °C). Corte a berinjela ao meio no comprimento. Com uma colher, retire parte do miolo, formando duas 'barquinhas'. Pique o miolo retirado.",
   "Coloque as barquinhas numa assadeira, regue com um pouco de azeite e asse por 10 minutos, só para amaciar.",
   "Numa frigideira, aqueça o restante do azeite e frite a cebola e o alho por 2 minutos. Junte o tomate, o miolo picado da berinjela, o grão-de-bico, o cominho, sal e pimenta e cozinhe por 6 minutos, amassando um pouco o grão-de-bico, até formar um recheio macio.",
   "Recheie as barquinhas com a mistura de grão-de-bico e polvilhe o queijo ralado por cima.",
   "Volte ao forno por 15 minutos, até gratinar (o queijo derreter e dourar). Salpique salsinha e sirva."],
 "porcoes8": ["½ berinjela · salada",
              "1 berinjela recheada · salada",
              "1 berinjela · 2 col. arroz",
              "1 berinjela · grão extra · salada",
              "1 berinjela · grão extra · 2 col. arroz",
              "1 berinjela grande · 3 col. arroz",
              "1 berinjela · grão duplo · 4 col. arroz",
              "berinjela + porção extra · 4 col. arroz"],
 "dica": "A berinjela tem muita água e fibra, então enche o prato com pouquíssima caloria. O grão-de-bico entra com a proteína vegetal que substitui a carne, e um pouco de queijo gratinado mata a vontade de gratinado. Um jantar vegetariano bonito, farto e leve.",
 "prompt": "Square ultra-realistic overhead food photograph of two baked stuffed eggplant halves filled with seasoned chickpeas and melted cheese, sprinkled with parsley, on a white plate, light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Curry de Grão-de-Bico com Arroz",
 "tag": "Jantar vegetariano", "num_label": "Bônus · Vegetariano",
 "hook": "Um molho dourado e perfumado envolvendo o grão-de-bico — cremoso com leite de coco light, é um jantar vegetariano cheio de sabor.",
 "tempo": "30 min", "rende": "2 porções", "kcal_base": 440,
 "ings": ["2 xícaras de grão-de-bico cozido", "1 cebola picada", "2 dentes de alho picados", "1 tomate picado",
          "1 colher de chá de curry em pó", "½ xícara de leite de coco light", "punhado de espinafre (opcional)",
          "1 colher de chá de azeite", "sal, pimenta e coentro a gosto", "arroz para servir"],
 "passos": [
   "Aqueça o azeite numa panela em fogo médio e frite a cebola e o alho por 2 minutos, mexendo.",
   "Junte o curry e mexa por 30 segundos, para o tempero soltar o aroma. Acrescente o tomate e cozinhe por 3 minutos, até desmanchar.",
   "Junte o grão-de-bico e o leite de coco light e misture. Tempere com sal e pimenta.",
   "Cozinhe em fogo baixo por 10 minutos, mexendo de vez em quando, até o molho engrossar. Se quiser, junte o espinafre nos últimos 2 minutos, só até murchar.",
   "Salpique coentro e sirva sobre uma porção de arroz."],
 "porcoes8": ["⅔ xíc. grão · 3 col. arroz",
              "1 xíc. grão · 4 col. arroz",
              "1 xíc. grão · 5 col. arroz",
              "1 xíc. grão · 5 col. arroz · espinafre",
              "1 xíc. grão · 5 col. arroz",
              "1½ xíc. grão · 6 col. arroz",
              "1½ xíc. grão · 7 col. arroz",
              "2 xíc. grão · 8 col. arroz"],
 "dica": "O grão-de-bico é rico em proteína e fibra, e no curry fica cremoso e cheio de sabor. O leite de coco light dá a untuosidade do molho com bem menos gordura que o creme de leite. Com arroz, forma uma proteína completa — um jantar vegetariano reconfortante e nutritivo.",
 "prompt": "Square ultra-realistic overhead food photograph of a chickpea curry in a golden coconut sauce with spinach, served with white rice in a bowl, coriander on top, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
]
