# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). FRANCÊS.

Tradução literal de `receitas_jantar.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/066-100).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 340/420/480/540 · 520/590/650/720
"""

RECEITAS = [
{
 "nome": "Soupe de potiron au poulet effiloché",
 "hook": "Crémeuse, orangée et réconfortante — une soupe qui réchauffe le soir et qui apporte en plus les protéines du poulet pour vraiment rassasier.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 340,
 "ings": ["1 gros morceau de potiron en dés (environ 500 g)", "1 filet de blanc de poulet (environ 150 g)",
          "1 oignon haché", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "sel, poivre et gingembre râpé au goût", "persil et ciboulette pour finir", "1 litre d'eau"],
 "passos": [
   "Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes, en remuant, jusqu'à ce qu'ils deviennent translucides.",
   "Ajoute le potiron en dés, le filet de poulet entier et l'eau. Porte à ébullition et fais cuire 20 minutes, jusqu'à ce que le potiron soit bien tendre.",
   "Retire le poulet, laisse tiédir et effiloche-le avec deux fourchettes. Réserve.",
   "Avec un mixeur plongeant (ce bâton qui mixe) ou au mixeur, réduis le potiron et le bouillon en une crème lisse. Attention au liquide chaud.",
   "Remets la crème dans la casserole, ajoute le poulet effiloché, le gingembre, du sel et du poivre et réchauffe 3 minutes. Sers avec les herbes par-dessus."],
 "porcoes8": ["1 louche · peu de poulet",
              "2 louches · poulet",
              "2 louches · poulet",
              "2 louches · poulet · 1 tranche de pain",
              "2 louches · poulet en plus · 1 tranche de pain",
              "3 louches · poulet · 1 tranche de pain",
              "3 louches · poulet en plus · 2 tranches de pain",
              "3 grandes louches · double poulet · 2 tranches de pain"],
 "dica": "Le potiron contient beaucoup d'eau et de fibres, ce qui remplit l'estomac pour très peu de calories. La chaleur de la soupe fait manger plus lentement, et le poulet effiloché transforme cette crème légère en un repas complet qui tient jusqu'au coucher, sans lourdeur.",
},
{
 "nome": "Filet de poulet sauce moutarde et légumes vapeur",
 "hook": "Une sauce crémeuse à la moutarde et au yaourt habille le poulet pour les grands soirs — léger, élégant et prêt vite pour le dîner.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 400,
 "ings": ["1 filet de blanc de poulet (environ 150 g)", "1 c. à s. de yaourt nature sans sucre",
          "1 c. à c. de moutarde", "100 g de brocoli, carotte et haricots verts", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre, persil et ciboulette au goût"],
 "passos": [
   "Coupe les légumes en morceaux de taille similaire. Fais-les cuire à la vapeur (ou dans une casserole avec un doigt d'eau et un couvercle) 6 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes et colorés.",
   "Assaisonne le poulet avec du sel, du poivre et l'ail. Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen et grille le filet 4 à 5 minutes de chaque côté, jusqu'à ce qu'il soit doré et blanc à l'intérieur.",
   "Dans un petit bol, mélange le yaourt, la moutarde, le jus de citron, du sel et du poivre, jusqu'à obtenir une sauce crémeuse.",
   "Pose le poulet dans l'assiette, nappe-le de sauce moutarde et sers avec les légumes à côté.",
   "Parsème d'herbes et sers chaud."],
 "porcoes8": ["120 g de poulet · légumes",
              "150 g de poulet · légumes",
              "150 g de poulet · légumes · 2 c. à s. de riz",
              "170 g de poulet · légumes · 2 c. à s. de riz",
              "170 g de poulet · légumes · 3 c. à s. de riz",
              "200 g de poulet · légumes · 3 c. à s. de riz",
              "220 g de poulet · légumes · 4 c. à s. de riz",
              "250 g de poulet · légumes · 4 c. à s. de riz"],
 "dica": "La sauce crémeuse vient du yaourt, pas de la crème ni du beurre, ce qui supprime beaucoup de graisse. La moutarde donne un goût fort pour presque aucune calorie. Cuire les légumes à la vapeur préserve les nutriments et n'utilise pas d'huile — un dîner léger qui a l'air d'un plat de restaurant.",
},
{
 "nome": "Poisson en papillote aux légumes",
 "hook": "Le poisson cuit dans sa propre vapeur à l'intérieur du papier et devient incroyablement tendre — et tu ouvres la papillote à table, chaude et parfumée.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 380,
 "ings": ["1 filet de poisson blanc (merlu, colin ou tilapia, environ 150 g)", "½ courgette en fines rondelles",
          "½ carotte en fines lanières", "tomates cerises coupées", "1 gousse d'ail en lamelles", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et herbes (thym ou origan) au goût", "1 grande feuille de papier cuisson"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe la courgette et la carotte en fines lamelles, pour qu'elles cuisent dans le même temps que le poisson.",
   "Au centre d'une grande feuille de papier cuisson, fais un lit avec les légumes. Assaisonne avec un peu de sel, du poivre et la moitié de l'huile d'olive.",
   "Pose le filet de poisson par-dessus. Assaisonne avec du sel, du poivre, l'ail, les herbes, le jus de citron et le reste d'huile d'olive.",
   "Referme le papier comme un paquet : rassemble les bords et plie-les bien, en laissant un espace d'air à l'intérieur, pour former une papillote fermée.",
   "Enfourne 18 à 20 minutes. Ouvre avec précaution (il en sort de la vapeur brûlante) et sers dans le papier ou transfère dans l'assiette."],
 "porcoes8": ["120 g de poisson · légumes",
              "150 g de poisson · légumes",
              "150 g de poisson · légumes · 1 petite pomme de terre",
              "170 g de poisson · légumes · 1 pomme de terre",
              "170 g de poisson · légumes · 1 pomme de terre",
              "200 g de poisson · légumes · 1 pomme de terre",
              "220 g de poisson · légumes · 1 grosse pomme de terre",
              "250 g de poisson · légumes · 2 petites pommes de terre"],
 "dica": "Cuire en papillote n'utilise presque pas de matière grasse : le poisson et les légumes cuisent dans leur propre vapeur, gardent leur goût et deviennent très tendres. C'est l'une des façons les plus légères et les plus saines de préparer le poisson, parfaite pour un dîner sans lourdeur et sans casserole à laver.",
},
{
 "nome": "Gratin de poulet à la purée de chou-fleur",
 "hook": "Tout le réconfort d'un gratin, mais le dessus est une purée de chou-fleur — crémeuse, légère et avec bien moins de calories.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 380,
 "ings": ["1 chou-fleur moyen", "2 filets de blanc de poulet cuits et effilochés (environ 300 g)", "1 oignon haché",
          "1 gousse d'ail hachée", "1 tomate hachée", "1 c. à c. d'huile d'olive",
          "2 c. à s. de fromage râpé allégé", "sel, poivre, persil et ciboulette au goût"],
 "passos": [
   "Coupe le chou-fleur en morceaux et fais-le cuire 12 minutes dans de l'eau bouillante, jusqu'à ce qu'il soit bien tendre. Égoutte très bien (le chou-fleur retient l'eau) et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée crémeuse.",
   "Dans une poêle, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes. Ajoute le poulet effiloché et la tomate, assaisonne avec du sel et du poivre et fais cuire 5 minutes, jusqu'à obtenir une garniture moelleuse.",
   "Dans un plat à gratin, étale le poulet au fond et recouvre de purée de chou-fleur.",
   "Parsème de fromage râpé.",
   "Enfourne à 200 °C pendant 15 minutes, jusqu'à ce que la surface soit légèrement dorée. Parsème d'herbes et sers."],
 "porcoes8": ["½ portion · salade",
              "1 portion · salade",
              "1 portion · salade",
              "1 portion · poulet en plus · salade",
              "1 portion · poulet en plus · salade",
              "1 grande portion · salade",
              "1 grande portion · poulet en plus · salade",
              "double portion · salade"],
 "dica": "Le chou-fleur à la place de la pomme de terre supprime une bonne partie des calories et des glucides, tout en gardant le crémeux de la purée. Le poulet effiloché apporte les protéines et la satiété. C'est le plat réconfortant idéal pour qui veut manger chaud et léger avant d'aller dormir.",
},
{
 "nome": "Soupe de légumes au bœuf maigre",
 "hook": "La soupe qui semble faite par une grand-mère : des morceaux de viande tendre et des légumes dans un bouillon relevé, qui remplit le ventre et réchauffe l'âme.",
 "tempo": "50 min", "rende": "3 portions", "kcal_base": 360,
 "ings": ["250 g de bœuf maigre en dés (gîte ou macreuse)", "1 pomme de terre en dés", "1 carotte en dés",
          "1 courgette en dés", "1 tomate hachée", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût", "1,5 litre d'eau"],
 "passos": [
   "Dans une casserole, fais chauffer l'huile d'olive et fais dorer les dés de viande de tous les côtés, en remuant, 5 minutes.",
   "Ajoute l'oignon et l'ail et fais revenir 2 minutes. Ajoute la tomate et remue 2 minutes de plus.",
   "Verse l'eau, assaisonne avec du sel et du poivre, couvre et fais cuire à feu moyen-doux 30 minutes, jusqu'à ce que la viande commence à s'attendrir.",
   "Ajoute la pomme de terre, la carotte et la courgette et fais cuire encore 15 minutes, jusqu'à ce que la viande soit bien tendre et les légumes cuits.",
   "Goûte le sel, parsème d'herbes et sers bien chaud."],
 "porcoes8": ["1 louche · peu de viande",
              "2 louches · viande",
              "2 louches · viande",
              "2 louches · viande · 1 tranche de pain",
              "2 louches · viande en plus · 1 tranche de pain",
              "3 louches · viande · 1 tranche de pain",
              "3 louches · viande en plus · 2 tranches de pain",
              "3 grandes louches · double viande · 2 tranches de pain"],
 "dica": "Les soupes avec beaucoup de liquide et de légumes remplissent l'estomac pour peu de calories, et les manger chaudes oblige à manger lentement et à se sentir rassasié plus tôt. La viande maigre apporte les protéines, ce qui rend la soupe assez consistante pour être un dîner complet.",
},
{
 "nome": "Saumon sauce yaourt-aneth et légumes",
 "hook": "Le saumon rosé reçoit une sauce toute fraîche au yaourt et à l'aneth — raffiné, léger et fait en vingt minutes.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 430,
 "ings": ["1 pavé de saumon (environ 150 g)", "2 c. à s. de yaourt nature sans sucre", "aneth ciselé",
          "100 g de brocoli et carotte", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et ail haché au goût"],
 "passos": [
   "Coupe le brocoli en bouquets et la carotte en rondelles. Fais-les cuire à la vapeur 6 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes.",
   "Assaisonne le saumon avec du sel, du poivre, l'ail et le jus de citron.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen. Pose le saumon côté peau vers le bas et laisse 4 minutes, puis retourne et laisse encore 3 minutes, jusqu'à ce qu'il devienne plus clair et se détache en lamelles à la fourchette.",
   "Prépare la sauce : mélange le yaourt, l'aneth ciselé, un peu de sel et quelques gouttes de citron.",
   "Monte l'assiette avec le saumon, les légumes à côté et la sauce au yaourt par-dessus ou à part."],
 "porcoes8": ["120 g de saumon · légumes",
              "150 g de saumon · légumes",
              "150 g de saumon · légumes · 1 petite pomme de terre",
              "170 g de saumon · légumes · 1 pomme de terre",
              "170 g de saumon · légumes · 1 pomme de terre",
              "200 g de saumon · légumes · 1 pomme de terre",
              "220 g de saumon · légumes · 1 grosse pomme de terre",
              "250 g de saumon · légumes · 2 petites pommes de terre"],
 "dica": "Le saumon apporte la bonne graisse (oméga-3) qui rassasie et fait du bien au cœur. La sauce au yaourt et à l'aneth remplace les sauces crémeuses grasses par une version fraîche et protéinée. Avec des légumes vapeur, c'est un dîner léger, beau et complet.",
},
{
 "nome": "Poulet au citron et légumes rôtis",
 "hook": "Le poulet reste juteux et légèrement citronné, rôti avec des légumes qui caramélisent aux pointes — une plaque, zéro travail.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 420,
 "ings": ["2 hauts de cuisse de poulet sans peau (ou 2 filets, environ 300 g)", "1 courgette en morceaux", "1 poivron en morceaux",
          "1 oignon en quartiers", "tomates cerises", "2 gousses d'ail", "1 c. à c. d'huile d'olive",
          "le jus de 1 citron", "sel, poivre et origan au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Sur une plaque, étale la courgette, le poivron, l'oignon, les tomates cerises et les gousses d'ail.",
   "Assaisonne les légumes avec du sel, du poivre, de l'origan et la moitié de l'huile d'olive, et mélange.",
   "Assaisonne le poulet avec du sel, du poivre, le jus de citron et le reste d'huile d'olive. Place les morceaux entre les légumes.",
   "Enfourne 35 minutes, en retournant à mi-cuisson, jusqu'à ce que le poulet soit doré et cuit à cœur (le jus qui s'écoule quand on le pique est clair) et les légumes tendres avec les pointes dorées.",
   "Sers directement de la plaque, en arrosant du jus citronné qui s'est formé."],
 "porcoes8": ["1 haut de cuisse · légumes",
              "1 haut de cuisse · légumes",
              "1 gros haut de cuisse · légumes",
              "2 hauts de cuisse · légumes",
              "2 hauts de cuisse · légumes",
              "2 hauts de cuisse · légumes · 1 pomme de terre",
              "2 hauts de cuisse · légumes · 1 grosse pomme de terre",
              "3 hauts de cuisse · légumes · 1 grosse pomme de terre"],
 "dica": "Rôtir sans peau et avec peu d'huile garde le poulet léger, et le citron apporte de la fraîcheur sans ajouter de calories. Les légumes rôtis deviennent sucrés et savoureux tout seuls, ce qui rend les sauces lourdes inutiles. Un dîner pratique, coloré et léger fait sur une seule plaque.",
},
{
 "nome": "Boulettes de dinde aux courgettes en sauce",
 "hook": "Des boulettes légères de dinde qui nagent dans une sauce tomate fraîche, sur des rubans de courgette — les pâtes qui ne pèsent pas sur la balance.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 380,
 "ings": ["250 g de dinde hachée (ou poulet haché)", "1 œuf", "2 c. à s. de flocons d'avoine",
          "2 grosses courgettes", "3 tomates mûres hachées (ou sauce tomate)", "1 oignon haché",
          "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive", "sel, poivre et basilic au goût"],
 "passos": [
   "Dans un bol, mélange la dinde hachée, l'œuf, l'avoine, la moitié de l'ail, du sel et du poivre. Malaxe à la main et forme des boulettes de la taille d'une noix.",
   "Fais chauffer l'huile d'olive dans une grande casserole et fais dorer les boulettes de tous les côtés, en les tournant délicatement, 5 minutes. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et le reste de l'ail 2 minutes. Ajoute les tomates hachées, du sel et du poivre et fais cuire 10 minutes, jusqu'à obtenir une sauce.",
   "Remets les boulettes dans la sauce et fais cuire encore 8 minutes, jusqu'à ce qu'elles soient cuites à cœur.",
   "Avec un économe, fais de fins rubans de courgette (comme des pâtes). Mets les rubans crus dans l'assiette et verse les boulettes chaudes avec la sauce par-dessus — la chaleur attendrit la courgette. Parsème de basilic."],
 "porcoes8": ["3 boulettes · courgette",
              "4 boulettes · courgette",
              "4 boulettes · courgette · 2 c. à s. de riz",
              "5 boulettes · courgette · 2 c. à s. de riz",
              "5 boulettes · courgette · 3 c. à s. de riz",
              "6 boulettes · courgette · 3 c. à s. de riz",
              "7 boulettes · courgette · 4 c. à s. de riz",
              "8 boulettes · courgette · 4 c. à s. de riz"],
 "dica": "Remplacer les pâtes par des rubans de courgette supprime presque tous les glucides et remplit l'assiette de fibres et d'eau. Les boulettes de dinde sont maigres et protéinées, et la sauce tomate faite sur le moment, sans sucre, rend le dîner savoureux et très léger.",
},
{
 "nome": "Filet de poisson en croûte d'herbes et purée",
 "hook": "Une petite croûte croustillante aux herbes dehors, le poisson tendre dedans — on dirait un plat de chef, mais c'est simple et léger.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 410,
 "ings": ["1 filet de poisson blanc (merlu, colin ou tilapia, environ 150 g)", "2 c. à s. de chapelure complète",
          "persil et ciboulette finement ciselés", "1 pomme de terre moyenne", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "1 gousse d'ail hachée", "sel et poivre au goût"],
 "passos": [
   "Épluche et fais cuire la pomme de terre 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elle soit bien tendre. Égoutte et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse.",
   "Préchauffe le four à 200 °C. Assaisonne le poisson avec du sel, du poivre, l'ail et le jus de citron.",
   "Dans un petit bol, mélange la chapelure avec le persil, la ciboulette et un filet d'huile d'olive, pour former une chapelure humide.",
   "Pose le poisson sur une plaque et recouvre le dessus de la chapelure aux herbes, en appuyant légèrement pour qu'elle adhère.",
   "Enfourne 15 à 18 minutes, jusqu'à ce que la croûte soit dorée et croustillante et que le poisson se détache en lamelles. Sers avec la purée de pommes de terre."],
 "porcoes8": ["120 g de poisson · ½ portion de purée",
              "150 g de poisson · 1 portion de purée",
              "150 g de poisson · 1 portion de purée",
              "170 g de poisson · 1 portion de purée",
              "170 g de poisson · 1 portion de purée",
              "200 g de poisson · 1 grande portion de purée",
              "220 g de poisson · grande portion de purée",
              "250 g de poisson · double portion de purée"],
 "dica": "La croûte d'herbes avec un peu de chapelure donne du croustillant sans friture, ce qui laisse le poisson léger et plein de goût. Le poisson blanc est très maigre et protéiné, et la purée dans la bonne mesure réconforte sans excès — un dîner beau et léger.",
},
{
 "nome": "Steak grillé et salade de pois chiches",
 "hook": "Un steak à point à côté d'une salade tiède de pois chiches — une double protéine qui rassasie sans alourdir le dîner.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 440,
 "ings": ["1 steak de bœuf maigre (environ 120 g)", "80 g de pois chiches cuits",
          "½ tomate en dés", "oignon rouge haché", "salade verte", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et persil au goût"],
 "passos": [
   "Assaisonne le steak avec du sel et du poivre des deux côtés.",
   "Fais chauffer une poêle antiadhésive à feu vif avec quelques gouttes d'huile d'olive. Grille le steak 2 à 3 minutes de chaque côté, sans y toucher, jusqu'à ce qu'il soit doré dehors et à ton goût dedans. Laisse reposer 2 minutes avant de le couper.",
   "Dans un bol, mélange les pois chiches, la tomate, l'oignon rouge et le persil.",
   "Assaisonne la salade avec l'huile d'olive, le jus de citron, du sel et du poivre.",
   "Sers le steak tranché sur un lit de salade verte, avec la salade de pois chiches à côté."],
 "porcoes8": ["100 g de viande · 55 g de pois chiches · salade",
              "120 g de viande · 80 g de pois chiches · salade",
              "130 g de viande · 80 g de pois chiches · salade",
              "150 g de viande · 110 g de pois chiches · salade",
              "150 g de viande · 110 g de pois chiches · salade",
              "170 g de viande · 125 g de pois chiches · salade",
              "200 g de viande · 165 g de pois chiches · salade",
              "220 g de viande · 165 g de pois chiches · salade"],
 "dica": "Le pois chiche ajoute des fibres et des protéines végétales aux protéines de la viande, ce qui rend le plat très rassasiant pour peu de calories. Griller le steak maigre sans huile et le servir avec une salade fraîche donne un dîner léger, plein de goût, qui tient la faim à distance pendant des heures.",
},
{
 "nome": "Velouté de brocoli au poulet",
 "hook": "Bien vert, velouté et plein de goût — un velouté de brocoli qui prend du corps grâce au poulet et devient un dîner complet.",
 "tempo": "30 min", "rende": "3 portions", "kcal_base": 330,
 "ings": ["1 tête de brocoli", "1 filet de blanc de poulet (environ 150 g)", "1 petite pomme de terre (elle donne du crémeux)",
          "1 oignon haché", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "sel, poivre et noix de muscade au goût", "1 litre d'eau"],
 "passos": [
   "Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes, en remuant.",
   "Ajoute la pomme de terre en dés, le filet de poulet entier et l'eau. Fais cuire 15 minutes.",
   "Retire le poulet, laisse tiédir et effiloche-le. Réserve. Ajoute le brocoli (seulement les bouquets) dans la casserole et fais cuire encore 5 minutes, jusqu'à ce qu'il soit tendre mais encore vert.",
   "Mixe la soupe au mixeur plongeant (le bâton qui mixe) ou au mixeur jusqu'à obtenir une crème lisse. Attention au liquide chaud.",
   "Remets la crème dans la casserole, ajoute le poulet effiloché, assaisonne avec du sel, du poivre et une pointe de noix de muscade et réchauffe 3 minutes. Sers."],
 "porcoes8": ["1 louche · peu de poulet",
              "2 louches · poulet",
              "2 louches · poulet",
              "2 louches · poulet · 1 tranche de pain",
              "2 louches · poulet en plus · 1 tranche de pain",
              "3 louches · poulet · 1 tranche de pain",
              "3 louches · poulet en plus · 2 tranches de pain",
              "3 grandes louches · double poulet · 2 tranches de pain"],
 "dica": "Le brocoli est l'un des légumes les plus nourrissants et les moins caloriques, et mixé il devient un velouté onctueux sans avoir besoin de crème. Un petit morceau de pomme de terre donne le crémeux, et le poulet effiloché complète la soupe avec des protéines, ce qui rend le dîner léger et rassasiant.",
},
{
 "nome": "Wrap à la dinde et à la salade",
 "hook": "Des tranches de blanc de dinde, des feuilles bien fraîches et une touche crémeuse, roulées dans un pain moelleux — un dîner léger à manger avec les mains.",
 "tempo": "10 min", "rende": "1 portion", "kcal_base": 360,
 "ings": ["1 tortilla complète", "4 tranches de blanc de dinde", "1 c. à s. de fromage blanc (ou de fromage à tartiner allégé)",
          "feuilles de salade", "½ tomate en rondelles", "carotte râpée", "concombre en bâtonnets",
          "sel, poivre et moutarde au goût"],
 "passos": [
   "Réchauffe la tortilla 20 secondes dans une poêle, juste pour l'assouplir et pouvoir la rouler.",
   "Étale le fromage blanc (ou le fromage à tartiner allégé) sur toute la tortilla, comme du beurre.",
   "Mets au centre les feuilles de salade, les tranches de dinde, la tomate, la carotte râpée et le concombre.",
   "Assaisonne avec un peu de sel, du poivre et de la moutarde.",
   "Replie les côtés vers l'intérieur et roule bien serré, de bas en haut. Coupe en deux en diagonale et sers."],
 "porcoes8": ["3 tranches de dinde · ½ tortilla · salade",
              "4 tranches de dinde · 1 tortilla · salade",
              "4 tranches de dinde · 1 tortilla · salade",
              "5 tranches de dinde · 1 tortilla · salade",
              "5 tranches de dinde · 1 tortilla · salade",
              "6 tranches de dinde · 1 grande tortilla · salade",
              "6 tranches de dinde · 2 tortillas · salade",
              "8 tranches de dinde · 2 tortillas · salade"],
 "dica": "Le blanc de dinde est une viande maigre et pratique, pleine de protéines. En remplaçant le fromage à tartiner classique par du fromage blanc ou une version allégée et en garnissant le wrap de feuilles et de légumes, tu as un dîner léger, rapide et rassasiant, parfait pour les jours où tu n'as pas envie de cuisiner.",
},
{
 "nome": "Ragoût de poulet aux légumes",
 "hook": "Des morceaux de poulet tendre dans un bouillon épais et relevé, avec des légumes qui fondent en bouche — une cuisine de cocotte qui fait du bien.",
 "tempo": "40 min", "rende": "3 portions", "kcal_base": 390,
 "ings": ["2 filets de blanc de poulet en dés (environ 300 g)", "1 pomme de terre en dés", "1 carotte en rondelles",
          "1 courgette en dés", "1 tomate hachée", "1 oignon haché", "2 gousses d'ail hachées",
          "1 c. à c. d'huile d'olive", "sel, poivre, curcuma et herbes au goût"],
 "passos": [
   "Assaisonne les dés de poulet avec du sel, du poivre et un peu de curcuma.",
   "Dans une casserole, fais chauffer l'huile d'olive et fais dorer les dés de poulet 5 minutes, en remuant. Ajoute l'oignon et l'ail et fais revenir 2 minutes.",
   "Ajoute la tomate et remue 2 minutes, jusqu'à ce qu'elle commence à se défaire.",
   "Ajoute la pomme de terre et la carotte et couvre d'eau (assez pour tout recouvrir). Assaisonne avec du sel et fais cuire 15 minutes.",
   "Ajoute la courgette et fais cuire encore 8 minutes, jusqu'à ce que tout soit tendre et que le bouillon prenne du corps. Parsème d'herbes et sers nature ou avec un peu de riz."],
 "porcoes8": ["½ portion · sans riz",
              "1 portion · sans riz",
              "1 portion · 2 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 grande portion · 4 c. à s. de riz",
              "grande portion · 5 c. à s. de riz",
              "double portion · 5 c. à s. de riz"],
 "dica": "Le ragoût cuit tout dans la même casserole avec peu de matière grasse, et le bouillon du poulet assaisonne les légumes tout seul. C'est un plat consistant qui rassasie pour peu de calories, excellent pour le dîner parce qu'il est chaud, réconfortant et léger à la fois.",
},
{
 "nome": "Galettes de thon et salade",
 "hook": "Faites avec du thon en boîte, ces galettes sont économiques, pleines de protéines et prêtes en un instant — un dîner léger et pratique.",
 "tempo": "20 min", "rende": "2 portions", "kcal_base": 380,
 "ings": ["2 boîtes de thon au naturel, égoutté", "1 œuf", "3 c. à s. de flocons d'avoine", "½ oignon finement haché",
          "persil ciselé", "1 c. à c. d'huile d'olive", "sel, poivre et le jus de ½ citron au goût",
          "salade verte, tomate et concombre pour la salade"],
 "passos": [
   "Égoutte bien le thon en pressant pour retirer le liquide. Dans un bol, mélange le thon, l'œuf, l'avoine, l'oignon, le persil, du sel, du poivre et le jus de citron.",
   "Écrase le tout à la fourchette jusqu'à ce que ça se tienne. Si c'est trop mou, ajoute un peu plus d'avoine.",
   "Forme deux disques à la main, bien aplatis.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen. Pose les galettes et laisse 4 minutes de chaque côté, sans y toucher, jusqu'à ce qu'elles soient dorées et fermes. Retourne délicatement.",
   "Sers avec une salade bien garnie de feuilles, de tomate et de concombre à côté."],
 "porcoes8": ["1 galette · salade",
              "1 galette · salade",
              "1 galette · salade · ½ pain",
              "2 galettes · salade",
              "2 galettes · salade",
              "2 galettes · salade · 1 pain",
              "2 galettes · salade · 1 pain",
              "3 galettes · salade · 1 pain"],
 "dica": "Le thon en boîte est une source de protéines bon marché et pratique, et lié avec un œuf et de l'avoine (à la place de beaucoup de pain), il devient une galette maigre et rassasiante. Grillée sans friture et servie avec beaucoup de salade, c'est un dîner léger et économique qui remplit le ventre.",
},
{
 "nome": "Bœuf braisé à la cocotte avec légumes",
 "hook": "Un morceau de viande qui cuit lentement jusqu'à se défaire, avec des légumes imbibés de bouillon — le dîner du dimanche, dans la bonne mesure.",
 "tempo": "1 h 20 min", "rende": "3 portions", "kcal_base": 440,
 "ings": ["400 g de bœuf maigre en un morceau (gîte, rond de gîte ou macreuse)", "2 carottes en gros morceaux",
          "2 pommes de terre en gros morceaux", "1 oignon en quartiers", "2 gousses d'ail", "1 tomate hachée",
          "1 feuille de laurier", "1 c. à c. d'huile d'olive", "sel, poivre et romarin au goût"],
 "passos": [
   "Assaisonne le morceau de viande avec du sel et du poivre. Dans une cocotte, fais chauffer l'huile d'olive et fais dorer la viande de tous les côtés, en la tournant, environ 6 minutes (ce brunissage donne beaucoup de goût au bouillon).",
   "Ajoute l'oignon, l'ail et la tomate et fais revenir 2 minutes. Ajoute la feuille de laurier et de l'eau chaude jusqu'à mi-hauteur de la viande.",
   "Couvre et fais cuire à feu doux 50 minutes, en retournant la viande à mi-cuisson. Si l'eau réduit trop, ajoute un peu d'eau chaude.",
   "Ajoute les carottes et les pommes de terre et fais cuire encore 25 minutes, jusqu'à ce que la viande soit si tendre qu'elle se défasse et les légumes cuits.",
   "Retire la feuille de laurier. Tranche ou effiloche la viande et sers avec les légumes et le bouillon par-dessus."],
 "porcoes8": ["½ portion de viande · légumes",
              "1 portion de viande · légumes",
              "1 portion de viande · légumes",
              "1 portion · légumes · 1 pomme de terre en plus",
              "1 portion · légumes · 1 pomme de terre en plus",
              "1 grande portion · légumes",
              "grande portion · légumes · pomme de terre en plus",
              "double portion · légumes"],
 "dica": "La cuisson lente attendrit les morceaux maigres et bon marché sans avoir besoin de matière grasse, et le bouillon qui se forme assaisonne les légumes naturellement. Servi avec la viande dans la bonne mesure et beaucoup de légumes, c'est un plat réconfortant de week-end qui rentre parfaitement dans le régime.",
},
{
 "nome": "Poulet farci à la ricotta et aux épinards",
 "hook": "Le filet de poulet s'ouvre comme une poche et garde une farce crémeuse de ricotta et d'épinards — surprenant, juteux et léger.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 400,
 "ings": ["2 filets épais de blanc de poulet (environ 300 g)", "4 c. à s. de ricotta", "1 grosse poignée d'épinards",
          "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et noix de muscade au goût", "cure-dents"],
 "passos": [
   "Dans une poêle, fais chauffer quelques gouttes d'huile d'olive et fais revenir les épinards avec l'ail 1 minute, juste le temps qu'ils retombent. Laisse refroidir et hache-les.",
   "Dans un bol, mélange la ricotta, les épinards hachés, du sel, du poivre et une pointe de noix de muscade, pour former une farce crémeuse.",
   "Avec un couteau, fais une entaille sur le côté de chaque filet, en ouvrant une poche (sans couper jusqu'au bout). Assaisonne le poulet avec du sel, du poivre et le jus de citron.",
   "Garnis les poches avec le mélange de ricotta et referme l'ouverture avec un ou deux cure-dents.",
   "Fais chauffer le reste d'huile d'olive dans une poêle à feu moyen et fais dorer les filets 5 à 6 minutes de chaque côté, jusqu'à ce qu'ils soient dorés et cuits à cœur. Retire les cure-dents avant de servir, avec une salade à côté."],
 "porcoes8": ["1 petit filet · salade",
              "1 filet · salade",
              "1 filet · salade · 2 c. à s. de riz",
              "1 gros filet · salade · 2 c. à s. de riz",
              "1 gros filet · salade · 3 c. à s. de riz",
              "1 gros filet · salade · 4 c. à s. de riz",
              "2 filets · salade · 4 c. à s. de riz",
              "2 filets · salade · 5 c. à s. de riz"],
 "dica": "La ricotta est un fromage maigre et crémeux, plein de protéines et avec peu de graisses, idéal pour farcir sans alourdir. Les épinards apportent des fibres et des nutriments pour presque aucune calorie. Le résultat est un poulet juteux et raffiné, assez léger pour le dîner.",
},
{
 "nome": "Soupe de poisson aux légumes",
 "hook": "Un bouillon parfumé avec des morceaux de poisson blanc et des légumes — léger, plein de goût de mer et réconfortant par une soirée fraîche.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 340,
 "ings": ["400 g de filet de poisson blanc en morceaux (merlu ou colin)", "1 pomme de terre en dés", "1 carotte en dés",
          "1 tomate hachée", "1 oignon haché", "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre, coriandre ou persil au goût", "1,2 litre d'eau"],
 "passos": [
   "Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes. Ajoute la tomate et remue 2 minutes de plus, jusqu'à ce qu'elle se défasse.",
   "Ajoute l'eau, la pomme de terre et la carotte. Assaisonne avec du sel et du poivre et fais cuire 15 minutes, jusqu'à ce que les légumes soient tendres.",
   "Ajoute les morceaux de poisson (le poisson cuit vite, c'est pour ça qu'il arrive à la fin) et fais cuire 6 à 8 minutes, juste le temps qu'il devienne blanc et tendre, sans trop se défaire.",
   "Ajoute le jus de citron et goûte le sel.",
   "Parsème de coriandre ou de persil et sers bien chaud."],
 "porcoes8": ["1 louche · poisson",
              "2 louches · poisson",
              "2 louches · poisson",
              "2 louches · poisson · 1 tranche de pain",
              "2 louches · poisson en plus · 1 tranche de pain",
              "3 louches · poisson · 1 tranche de pain",
              "3 louches · poisson en plus · 2 tranches de pain",
              "3 grandes louches · double poisson · 2 tranches de pain"],
 "dica": "Le poisson blanc est très maigre et cuit en quelques minutes, ce qui laisse la soupe légère et pleine de protéines. Le bouillon avec les légumes remplit l'estomac pour très peu de calories, et la touche de citron relève le goût sans excès de sel — un dîner chaud et léger.",
},
{
 "nome": "Escalopes de dinde à la sauce aux champignons",
 "hook": "De fines tranches de dinde dans une sauce crémeuse aux champignons — un dîner qui a l'air coûteux, fait avec peu de matière grasse en vingt minutes.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 400,
 "ings": ["2 fines escalopes de blanc de dinde (environ 300 g)", "70 g de champignons émincés", "1 oignon haché",
          "1 gousse d'ail hachée", "3 c. à s. de yaourt nature sans sucre", "1 c. à c. d'huile d'olive",
          "sel, poivre et persil au goût", "riz ou purée pour servir"],
 "passos": [
   "Assaisonne les fines escalopes de dinde avec du sel et du poivre.",
   "Fais chauffer une poêle antiadhésive avec la moitié de l'huile d'olive à feu moyen-vif et fais dorer les escalopes 2 à 3 minutes de chaque côté, jusqu'à ce qu'elles soient dorées et cuites. Retire et réserve.",
   "Dans la même poêle, avec le reste d'huile d'olive, fais revenir l'oignon et l'ail 2 minutes. Ajoute les champignons et fais cuire 4 minutes, jusqu'à ce qu'ils retombent et rendent leur eau.",
   "Baisse le feu, retire du feu et ajoute le yaourt en remuant — hors du feu, il ne tranche pas (il ne fait pas de grumeaux). Rectifie le sel et le poivre.",
   "Remets les escalopes dans la poêle pour qu'elles s'enrobent de sauce. Parsème de persil et sers avec un peu de riz ou de purée."],
 "porcoes8": ["1 escalope · 2 c. à s. de riz",
              "1 escalope · 3 c. à s. de riz",
              "1 grande escalope · 3 c. à s. de riz",
              "1 grande escalope · 4 c. à s. de riz",
              "1 grande escalope · 4 c. à s. de riz",
              "2 escalopes · 4 c. à s. de riz",
              "2 escalopes · 5 c. à s. de riz",
              "2 escalopes · 6 c. à s. de riz"],
 "dica": "La dinde est une viande blanche maigre et protéinée. La sauce crémeuse vient du yaourt, pas de la crème, ce qui supprime beaucoup de graisse. Les champignons donnent un goût intense et du corps à la sauce pour très peu de calories — un dîner raffiné et léger.",
},
{
 "nome": "Œufs au four dans une sauce tomate au poulet",
 "hook": "Des œufs cuits dans une sauce tomate relevée, avec des morceaux de poulet — un dîner chaud et différent, de la poêle directement à table.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 370,
 "ings": ["4 œufs", "1 filet de blanc de poulet cuit et effiloché (environ 120 g)", "3 tomates mûres hachées (ou sauce tomate)",
          "1 oignon haché", "1 gousse d'ail hachée", "½ poivron haché", "1 c. à c. d'huile d'olive",
          "sel, poivre, paprika et herbes au goût", "pain complet pour servir"],
 "passos": [
   "Dans une poêle qui peut aller au four (ou une poêle creuse), fais chauffer l'huile d'olive et fais revenir l'oignon, l'ail et le poivron 3 minutes, en remuant.",
   "Ajoute les tomates hachées, le paprika, du sel et du poivre et fais cuire 8 minutes, jusqu'à obtenir une sauce consistante. Ajoute le poulet effiloché et mélange.",
   "Avec une cuillère, fais de petits creux dans la sauce. Casse un œuf dans chaque creux, sans mélanger, pour que les jaunes restent entiers.",
   "Couvre la poêle et fais cuire à feu doux 6 à 8 minutes, jusqu'à ce que les blancs soient pris et les jaunes à ton goût. (Ou enfourne à four moyen 10 minutes.)",
   "Parsème d'herbes et sers dans la poêle, avec des tranches de pain complet pour accompagner."],
 "porcoes8": ["1 œuf · poulet · sauce",
              "2 œufs · poulet · sauce",
              "2 œufs · poulet · 1 tranche de pain",
              "2 œufs · poulet en plus · 1 tranche de pain",
              "2 œufs · poulet en plus · 1 tranche de pain",
              "2 œufs · poulet · 2 tranches de pain",
              "3 œufs · poulet en plus · 2 tranches de pain",
              "3 œufs · double poulet · 2 tranches de pain"],
 "dica": "Les œufs sont une protéine complète et très rassasiante, et cuits dans la sauce tomate ils restent légers, sans friture. Le poulet ajoute encore plus de protéines et la sauce remplit l'assiette avec le volume des tomates. C'est un dîner chaud, économique et réconfortant qui rassasie bien.",
},
{
 "nome": "Brochettes de crevettes aux légumes",
 "hook": "Des crevettes rosées et des légumes colorés enfilés ensemble, grillés jusqu'à dorer — léger, joli et avec un air de fête.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 360,
 "ings": ["250 g de grosses crevettes décortiquées", "1 poivron en carrés", "1 oignon en morceaux",
          "1 courgette en grosses rondelles", "tomates cerises", "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive",
          "le jus de 1 citron", "sel, poivre et paprika au goût", "piques à brochette"],
 "passos": [
   "Assaisonne les crevettes avec du sel, du poivre, du paprika, l'ail et le jus de citron. Laisse prendre le goût 10 minutes.",
   "Monte les brochettes en alternant une crevette, un carré de poivron, un morceau d'oignon, une rondelle de courgette et une tomate cerise, jusqu'à remplir la pique.",
   "Badigeonne les brochettes d'huile d'olive.",
   "Fais chauffer une grande poêle ou un gril à feu moyen-vif. Pose les brochettes et tourne-les toutes les 2 minutes, environ 8 minutes au total, juste le temps que les crevettes rosissent et s'enroulent. Ne les laisse pas trop cuire, sinon elles deviennent caoutchouteuses.",
   "Sers les brochettes avec une salade ou un peu de riz."],
 "porcoes8": ["1 brochette · salade",
              "2 brochettes · salade",
              "2 brochettes · salade · 2 c. à s. de riz",
              "2 brochettes · salade · 3 c. à s. de riz",
              "2 brochettes · salade · 3 c. à s. de riz",
              "3 brochettes · salade · 3 c. à s. de riz",
              "3 brochettes · salade · 4 c. à s. de riz",
              "3 grandes brochettes · salade · 4 c. à s. de riz"],
 "dica": "La crevette est presque entièrement de la protéine, avec très peu de graisses et de calories. Enfilée avec des légumes colorés et grillée sans huile, elle devient un dîner léger, joli et savoureux, qui contrôle la portion naturellement et plaît même pour les occasions spéciales.",
},
{
 "nome": "Saumon grillé aux asperges",
 "hook": "Deux stars dans une seule assiette : le saumon juteux et les asperges croquantes — un dîner chic, léger et prêt en quinze minutes.",
 "tempo": "18 min", "rende": "1 portion", "kcal_base": 420,
 "ings": ["1 pavé de saumon (environ 150 g)", "1 botte d'asperges", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et zeste de citron au goût"],
 "passos": [
   "Lave les asperges et casse la pointe dure du bas de chacune (elle se rompt naturellement au bon endroit quand tu la plies).",
   "Assaisonne le saumon avec du sel, du poivre, l'ail et le jus de citron.",
   "Fais chauffer une poêle antiadhésive avec la moitié de l'huile d'olive à feu moyen. Pose le saumon côté peau vers le bas et laisse 4 minutes, retourne et laisse encore 3 minutes, jusqu'à ce qu'il devienne plus clair et se détache en lamelles.",
   "En même temps, dans une autre poêle (ou dans la même, après avoir retiré le saumon), fais sauter les asperges avec le reste d'huile d'olive à feu vif 4 minutes, en remuant, jusqu'à ce qu'elles soient vertes et tendres mais encore croquantes.",
   "Monte l'assiette avec le saumon et les asperges. Termine par un peu de zeste de citron par-dessus."],
 "porcoes8": ["120 g de saumon · asperges",
              "150 g de saumon · asperges",
              "150 g de saumon · asperges · 1 petite pomme de terre",
              "170 g de saumon · asperges · 1 pomme de terre",
              "170 g de saumon · asperges · 1 pomme de terre",
              "200 g de saumon · asperges · 1 pomme de terre",
              "220 g de saumon · asperges · 1 grosse pomme de terre",
              "250 g de saumon · asperges · 2 petites pommes de terre"],
 "dica": "Le saumon apporte des protéines et des oméga-3, la bonne graisse qui rassasie et protège le cœur. Les asperges sont légères, pleines de fibres et aident à dégonfler, pour très peu de calories. Grillés ensemble avec peu d'huile, ils forment un dîner élégant, léger et nourrissant.",
},
{
 "nome": "Poêlée de bœuf haché aux courgettes",
 "hook": "Une poêlée rapide de bœuf haché avec des courgettes et un œuf par-dessus — faite à la poêle en quelques minutes, elle rassasie même sans riz.",
 "tempo": "20 min", "rende": "2 portions", "kcal_base": 380,
 "ings": ["250 g de viande de bœuf hachée maigre", "2 courgettes en petits dés", "1 tomate hachée", "1 oignon haché",
          "1 gousse d'ail hachée", "2 œufs", "1 c. à c. d'huile d'olive", "sel, poivre et herbes au goût"],
 "passos": [
   "Fais chauffer l'huile d'olive dans une poêle à feu moyen et fais revenir l'oignon et l'ail 2 minutes, en remuant.",
   "Ajoute la viande hachée et remue en défaisant les morceaux à la cuillère, jusqu'à ce qu'il n'y ait plus de rose.",
   "Ajoute la tomate et les dés de courgette, assaisonne avec du sel et du poivre et fais cuire 8 minutes, en remuant de temps en temps, jusqu'à ce que la courgette soit tendre et rende son jus.",
   "Pendant ce temps, fais cuire les œufs à part (au plat avec très peu d'huile ou durs pendant 6 minutes pour un jaune coulant).",
   "Sers la poêlée chaude avec un œuf sur chaque portion et les herbes par-dessus."],
 "porcoes8": ["½ portion · 1 œuf",
              "1 portion · 1 œuf",
              "1 portion · 1 œuf · 2 c. à s. de riz",
              "1 portion · 1 œuf · 3 c. à s. de riz",
              "1 portion · 2 œufs · 3 c. à s. de riz",
              "1 grande portion · 2 œufs · 3 c. à s. de riz",
              "grande portion · 2 œufs · 4 c. à s. de riz",
              "double portion · 2 œufs · 4 c. à s. de riz"],
 "dica": "La courgette en dés se mélange à la viande et donne du volume au plat pour très peu de calories, ce qui aide à manger moins de viande sans en ressentir le manque. L'œuf par-dessus ajoute des protéines et du crémeux. Sans riz ou avec peu, c'est un dîner léger, rapide et très rassasiant.",
},
{
 "nome": "Poulet façon pizza avec salade",
 "hook": "Le goût de la pizza sans la pâte : le poulet grillé reçoit de la sauce tomate, du fromage fondu et de l'origan — ça calme l'envie et ça ne pèse pas.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 400,
 "ings": ["2 filets de blanc de poulet (environ 300 g)", "120 ml de sauce tomate maison", "3 c. à s. de mozzarella allégée râpée",
          "rondelles de tomate", "1 c. à c. d'huile d'olive", "origan, sel et poivre au goût",
          "salade verte"],
 "passos": [
   "Assaisonne les filets de poulet avec du sel et du poivre.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen et grille les filets 4 à 5 minutes de chaque côté, jusqu'à ce qu'ils soient dorés et blancs à l'intérieur.",
   "Baisse le feu. Recouvre chaque filet de sauce tomate, d'une ou deux rondelles de tomate et de mozzarella râpée. Saupoudre d'origan.",
   "Couvre la poêle et laisse 3 à 4 minutes, juste le temps que le fromage fonde (c'est l'astuce pour gratiner sans four).",
   "Sers avec une salade verte fraîche à côté."],
 "porcoes8": ["100 g de poulet · peu de fromage · salade",
              "130 g de poulet · fromage · salade",
              "150 g de poulet · fromage · salade",
              "150 g de poulet · fromage · 2 c. à s. de riz",
              "150 g de poulet · fromage · 3 c. à s. de riz",
              "170 g de poulet · fromage · 3 c. à s. de riz",
              "200 g de poulet · fromage · 4 c. à s. de riz",
              "220 g de poulet · fromage en plus · 4 c. à s. de riz"],
 "dica": "Tu calmes l'envie de pizza avec le goût de la sauce tomate, du fromage et de l'origan, mais sans la pâte ni la graisse. Le poulet grillé apporte des protéines maigres et de la satiété, et un peu de fromage fondu suffit au plaisir du gratiné. Léger et satisfaisant.",
},
{
 "nome": "Poisson grillé aux légumes à la poêle",
 "hook": "Tout dans une seule poêle : le poisson dore d'un côté pendant que les légumes sautent de l'autre — dîner léger, rapide et sans désordre.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 380,
 "ings": ["1 filet de poisson blanc (merlu, colin ou tilapia, environ 150 g)", "1 courgette en demi-lunes",
          "½ poivron en lanières", "tomates cerises", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et persil au goût"],
 "passos": [
   "Assaisonne le poisson avec du sel, du poivre, l'ail et le jus de citron.",
   "Fais chauffer une grande poêle avec la moitié de l'huile d'olive à feu moyen-vif. D'un côté, pose le filet et laisse 3 à 4 minutes de chaque côté, en le retournant délicatement, jusqu'à ce qu'il soit doré et se détache en lamelles.",
   "De l'autre côté de la poêle (ou après avoir retiré le poisson), mets le reste d'huile d'olive et fais sauter la courgette, le poivron et les tomates cerises 4 à 5 minutes, en remuant, jusqu'à ce qu'ils soient tendres mais encore fermes.",
   "Assaisonne les légumes avec du sel et du poivre.",
   "Monte l'assiette avec le poisson et les légumes sautés. Parsème de persil et termine par encore un peu de citron."],
 "porcoes8": ["120 g de poisson · légumes",
              "150 g de poisson · légumes",
              "150 g de poisson · légumes · 1 petite pomme de terre",
              "170 g de poisson · légumes · 1 pomme de terre",
              "170 g de poisson · légumes · 1 pomme de terre",
              "200 g de poisson · légumes · 1 pomme de terre",
              "220 g de poisson · légumes · 1 grosse pomme de terre",
              "250 g de poisson · légumes · 2 petites pommes de terre"],
 "dica": "Le poisson blanc est léger et cuit en quelques minutes, et préparé dans la même poêle que les légumes, il n'utilise presque pas d'huile. Les légumes sautés apportent de la couleur, des fibres et du volume pour presque aucune calorie. C'est l'un des dîners les plus rapides, légers et pratiques qui soient.",
},
{
 "nome": "Blanc de dinde grillé et purée de potiron",
 "hook": "La dinde maigre sur une purée de potiron naturellement sucrée et orangée — un dîner léger avec un air de douceur.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 390,
 "ings": ["1 filet de blanc de dinde (environ 150 g)", "1 morceau de potiron en dés (environ 300 g)", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre, sauge ou romarin au goût",
          "salade verte"],
 "passos": [
   "Fais cuire le potiron 15 minutes dans de l'eau bouillante, jusqu'à ce qu'il soit bien tendre. Égoutte très bien et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse et crémeuse.",
   "Assaisonne la dinde avec du sel, du poivre, l'ail et le jus de citron.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen et grille le filet 3 à 4 minutes de chaque côté, jusqu'à ce qu'il soit doré et blanc à l'intérieur.",
   "Si tu veux, termine la dinde avec un peu de sauge ou de romarin dans la poêle dans les dernières secondes, pour parfumer.",
   "Monte l'assiette avec la purée de potiron, la dinde tranchée par-dessus et une salade verte à côté."],
 "porcoes8": ["120 g de dinde · ½ portion de purée · salade",
              "150 g de dinde · 1 portion de purée · salade",
              "150 g de dinde · 1 portion de purée · salade",
              "170 g de dinde · 1 portion de purée · salade",
              "170 g de dinde · 1 portion de purée · salade",
              "200 g de dinde · 1 grande portion de purée · salade",
              "220 g de dinde · grande portion de purée · salade",
              "250 g de dinde · double portion de purée · salade"],
 "dica": "Le blanc de dinde est encore plus maigre que le poulet et plein de protéines. Le potiron fait une purée crémeuse et sucrée pour très peu de calories, ce qui calme l'envie de sucré et remplit l'assiette de fibres. Un dîner léger, réconfortant et coloré.",
},
{
 "nome": "Soupe de poulet aux petites pâtes",
 "hook": "La soupe de poulet de toujours, renforcée avec beaucoup de poulet et de légumes — le dîner qui réconforte, qui soigne et qui rentre dans le régime.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 360,
 "ings": ["1 filet de blanc de poulet (environ 150 g)", "50 g de petites pâtes (vermicelles ou petits anneaux)",
          "1 carotte en petits dés", "1 branche de céleri hachée (facultatif)", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût", "1,2 litre d'eau"],
 "passos": [
   "Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes, en remuant.",
   "Ajoute le filet de poulet entier, la carotte, le céleri et l'eau. Assaisonne avec du sel et fais cuire 15 minutes, jusqu'à ce que le poulet soit cuit.",
   "Retire le poulet, laisse tiédir et effiloche-le. Remets le poulet effiloché dans la casserole.",
   "Ajoute les petites pâtes et fais cuire encore 8 à 10 minutes, jusqu'à ce que les pâtes soient tendres (remue de temps en temps pour qu'elles n'attachent pas au fond).",
   "Goûte le sel, parsème d'herbes et sers bien chaud."],
 "porcoes8": ["1 louche · poulet",
              "2 louches · poulet",
              "2 louches · poulet",
              "2 louches · poulet en plus",
              "2 louches · poulet en plus · pâtes en plus",
              "3 louches · poulet",
              "3 louches · poulet en plus · pâtes en plus",
              "3 grandes louches · double poulet"],
 "dica": "La soupe de poulet est légère et réconfortante : le bouillon avec les légumes remplit l'estomac pour peu de calories et le poulet apporte les protéines qui rassasient. Avec peu de pâtes et beaucoup de poulet et de légumes, elle devient un dîner complet et chaud, idéal pour les soirées fraîches ou les jours sans appétit.",
},
{
 "nome": "Crevettes au curry léger et légumes",
 "hook": "Des crevettes nappées d'une sauce dorée au curry et au lait de coco allégé — parfumée, crémeuse et étonnamment légère.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 380,
 "ings": ["300 g de crevettes décortiquées", "1 oignon haché", "1 gousse d'ail hachée", "1 poivron en lanières",
          "1 c. à c. de curry en poudre", "120 ml de lait de coco allégé", "1 tomate hachée",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre et coriandre au goût", "riz pour servir"],
 "passos": [
   "Assaisonne les crevettes avec du sel, du poivre et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Fais chauffer l'huile d'olive dans une poêle à feu moyen et fais revenir l'oignon, l'ail et le poivron 3 minutes, en remuant.",
   "Ajoute le curry et remue 30 secondes, pour que l'épice libère son arôme. Ajoute la tomate et fais cuire 3 minutes, jusqu'à ce qu'elle se défasse.",
   "Verse le lait de coco allégé et porte à léger frémissement. Mets les crevettes et fais cuire 3 à 4 minutes, juste le temps qu'elles rosissent. Ne les cuis pas trop, sinon elles deviennent caoutchouteuses.",
   "Parsème de coriandre et sers sur une petite portion de riz."],
 "porcoes8": ["120 g de crevettes · 2 c. à s. de riz",
              "150 g de crevettes · 3 c. à s. de riz",
              "150 g de crevettes · 3 c. à s. de riz",
              "170 g de crevettes · 4 c. à s. de riz",
              "170 g de crevettes · 4 c. à s. de riz",
              "200 g de crevettes · 4 c. à s. de riz",
              "220 g de crevettes · 5 c. à s. de riz",
              "250 g de crevettes · 5 c. à s. de riz"],
 "dica": "La crevette est presque de la protéine pure et cuit vite. Le lait de coco allégé donne du crémeux à la sauce avec bien moins de graisse que la crème, et le curry parfume et donne l'impression d'un plat spécial. Avec peu de riz, c'est un dîner léger et plein de goût.",
},
{
 "nome": "Ragoût de bœuf aux pommes de terre",
 "hook": "Des dés de viande qui se défont dans un bouillon épais avec des pommes de terre — le ragoût qui réconforte par une soirée froide, dans la bonne portion.",
 "tempo": "1 h", "rende": "3 portions", "kcal_base": 430,
 "ings": ["300 g de bœuf maigre en dés (gîte ou paleron maigre)", "2 pommes de terre en gros dés", "1 carotte en rondelles",
          "1 oignon haché", "2 gousses d'ail hachées", "1 tomate hachée", "1 feuille de laurier",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût"],
 "passos": [
   "Assaisonne les dés de viande avec du sel et du poivre. Dans une casserole, fais chauffer l'huile d'olive et fais dorer la viande de tous les côtés, en remuant, 6 minutes.",
   "Ajoute l'oignon et l'ail et fais revenir 2 minutes. Ajoute la tomate et la feuille de laurier et remue 2 minutes.",
   "Couvre d'eau chaude, couvre la casserole et fais cuire à feu doux 35 minutes, jusqu'à ce que la viande commence à s'attendrir. Si ça réduit, ajoute de l'eau chaude.",
   "Ajoute la pomme de terre et la carotte et fais cuire encore 20 minutes, jusqu'à ce que la viande se défasse et que la pomme de terre soit tendre (la pomme de terre aide à épaissir le bouillon).",
   "Retire la feuille de laurier, parsème d'herbes et sers chaud, nature ou avec un peu de riz."],
 "porcoes8": ["½ portion · sans riz",
              "1 portion · sans riz",
              "1 portion · 2 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 grande portion · 4 c. à s. de riz",
              "grande portion · 5 c. à s. de riz",
              "double portion · 5 c. à s. de riz"],
 "dica": "La cuisson lente attendrit les morceaux maigres et bon marché, et la pomme de terre épaissit le bouillon naturellement, sans farine ni crème. C'est un plat consistant qui rassasie beaucoup avec des calories maîtrisées — le réconfort d'un ragoût sans sortir du droit chemin.",
},
{
 "nome": "Omelette au four au jambon de dinde et aux légumes",
 "hook": "Une omelette haute et moelleuse cuite au four, garnie de légumes et de jambon de dinde maigre — tu la coupes en parts et elle nourrit toute la famille.",
 "tempo": "30 min", "rende": "3 portions", "kcal_base": 360,
 "ings": ["6 œufs", "4 tranches de jambon de dinde maigre hachées", "½ poivron haché", "1 tomate hachée",
          "1 poignée d'épinards", "2 c. à s. de fromage râpé allégé", "1 c. à c. d'huile d'olive",
          "ciboulette, sel et poivre au goût"],
 "passos": [
   "Préchauffe le four à 180 °C. Badigeonne un petit plat à gratin d'huile d'olive.",
   "Dans un bol, bats les œufs avec du sel et du poivre pendant 30 secondes.",
   "Ajoute aux œufs le jambon haché, le poivron, la tomate, les épinards et la ciboulette, et mélange.",
   "Verse le mélange dans le plat et parsème de fromage râpé par-dessus.",
   "Enfourne 20 à 25 minutes, jusqu'à ce que l'omelette gonfle, soit prise au centre et légèrement dorée dessus. Coupe en parts et sers chaud ou tiède, avec une salade."],
 "porcoes8": ["1 part · salade",
              "1 grande part · salade",
              "1 grande part · salade · 1 tranche de pain",
              "2 parts · salade · 1 tranche de pain",
              "2 parts · salade · 1 tranche de pain",
              "2 grandes parts · salade · 1 tranche de pain",
              "2 grandes parts · salade · 2 tranches de pain",
              "3 parts · salade · 2 tranches de pain"],
 "dica": "Les œufs sont une protéine complète et très rassasiante, et cuits au four ils se passent de friture. Le jambon de dinde maigre ajoute du goût et des protéines avec peu de graisse, et les légumes donnent du volume et des fibres. Ça fait plusieurs portions, ça se garde bien et c'est un dîner léger et pratique.",
},
{
 "nome": "Tilapia au four à la tomate et à l'oignon",
 "hook": "Des filets de poisson blanc cuits sous un lit de tomate et d'oignon qui deviennent une sauce naturelle — léger, juteux et sans effort.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 370,
 "ings": ["2 filets de tilapia (ou un autre poisson blanc, environ 300 g)", "2 tomates en rondelles", "1 oignon en rondelles",
          "1 gousse d'ail en lamelles", "1 c. à c. d'huile d'olive", "le jus de 1 citron",
          "sel, poivre, origan et persil au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Dans un plat à gratin, étale la moitié des rondelles de tomate et d'oignon au fond, pour former un lit.",
   "Assaisonne les filets de poisson avec du sel, du poivre, l'ail, l'origan et le jus de citron. Pose-les sur le lit de tomate et d'oignon.",
   "Recouvre les filets du reste de tomate et d'oignon et arrose d'huile d'olive.",
   "Enfourne 20 à 25 minutes, jusqu'à ce que le poisson se détache en lamelles et que la tomate et l'oignon soient tendres, en libérant une sauce naturelle.",
   "Parsème de persil et sers avec la sauce par-dessus, accompagné d'une salade ou d'un peu de riz."],
 "porcoes8": ["120 g de poisson · légumes",
              "150 g de poisson · légumes",
              "150 g de poisson · légumes · 2 c. à s. de riz",
              "170 g de poisson · légumes · 3 c. à s. de riz",
              "170 g de poisson · légumes · 3 c. à s. de riz",
              "200 g de poisson · légumes · 3 c. à s. de riz",
              "220 g de poisson · légumes · 4 c. à s. de riz",
              "250 g de poisson · légumes · 4 c. à s. de riz"],
 "dica": "Le poisson blanc est très maigre et protéiné, et le cuire sous la tomate et l'oignon crée une sauce naturelle sans matière grasse, qui garde le filet juteux. C'est un dîner léger, économique et plein de goût, qui se fait pratiquement tout seul au four.",
},
{
 "nome": "Boulettes de poulet dans la soupe",
 "hook": "De petites boulettes moelleuses de poulet cuites dans un bouillon léger avec des légumes — une soupe amusante et complète, qui rassasie et réchauffe.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 350,
 "ings": ["300 g de blanc de poulet haché", "1 œuf", "2 c. à s. de flocons d'avoine", "1 carotte en petits dés",
          "1 pomme de terre en petits dés", "1 courgette en petits dés", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût", "1,2 litre d'eau"],
 "passos": [
   "Dans un bol, mélange le poulet haché, l'œuf, l'avoine, du sel et du poivre. Malaxe à la main et forme de petites boulettes de la taille d'une noix.",
   "Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes. Ajoute l'eau, la carotte et la pomme de terre, assaisonne avec du sel et fais cuire 10 minutes.",
   "Avec précaution, dépose les boulettes crues une à une dans le bouillon frémissant. Ne remue pas pendant 3 minutes, pour qu'elles se raffermissent.",
   "Ajoute la courgette et fais cuire encore 10 minutes, jusqu'à ce que les boulettes soient cuites à cœur et les légumes tendres.",
   "Goûte le sel, parsème d'herbes et sers bien chaud."],
 "porcoes8": ["3 boulettes · 1 louche de bouillon",
              "4 boulettes · 2 louches",
              "4 boulettes · 2 louches",
              "5 boulettes · 2 louches · 1 tranche de pain",
              "5 boulettes · 2 louches · 1 tranche de pain",
              "6 boulettes · 3 louches · 1 tranche de pain",
              "7 boulettes · 3 louches · 2 tranches de pain",
              "8 boulettes · 3 louches · 2 tranches de pain"],
 "dica": "Les boulettes de poulet apportent les protéines qui rassasient, et cuites dans la soupe elles rendent le bouillon plus savoureux. Le liquide et les légumes en abondance remplissent l'estomac pour peu de calories. C'est un dîner complet, léger et réconfortant, qui plaît même à ceux qui n'aiment pas les soupes claires.",
},
{
 "nome": "Crevettes grillées sur salade verte",
 "hook": "Des crevettes dorées à l'ail sur une salade fraîche et croquante — un dîner léger, élégant et prêt en quinze minutes.",
 "tempo": "15 min", "rende": "1 portion", "kcal_base": 330,
 "ings": ["150 g de grosses crevettes décortiquées", "salade verte variée", "½ tomate en dés", "½ concombre en rondelles",
          "oignon rouge en fines lamelles", "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et persil au goût"],
 "passos": [
   "Sèche bien les crevettes avec du papier absorbant et assaisonne-les avec du sel, du poivre et la moitié du jus de citron.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen-vif. Ajoute l'ail et remue 30 secondes, juste le temps qu'il embaume.",
   "Mets les crevettes et grille-les 2 à 3 minutes de chaque côté, juste le temps qu'elles rosissent et dorent. Ne les cuis pas trop.",
   "Dans un grand saladier ou une assiette, monte la salade avec les feuilles vertes, la tomate, le concombre et l'oignon rouge. Assaisonne avec le reste du citron, du sel et du poivre.",
   "Pose les crevettes chaudes sur la salade, parsème de persil et sers tout de suite."],
 "porcoes8": ["120 g de crevettes · salade",
              "150 g de crevettes · salade",
              "150 g de crevettes · salade · 1 tranche de pain",
              "170 g de crevettes · salade · 1 tranche de pain",
              "170 g de crevettes · salade · 2 c. à s. de riz",
              "200 g de crevettes · salade · 3 c. à s. de riz",
              "220 g de crevettes · salade · 3 c. à s. de riz",
              "250 g de crevettes · salade · 4 c. à s. de riz"],
 "dica": "La crevette est presque de la protéine pure, avec très peu de calories, elle remplit donc l'assiette sans peser. Dorée à l'ail et servie sur une salade fraîche et croquante, c'est l'un des dîners les plus légers possibles — idéal le soir, quand le corps dépense moins d'énergie.",
},
{
 "nome": "Poisson mijoté au lait de coco et légumes",
 "hook": "Un mijoté crémeux et parfumé de poisson avec une touche de lait de coco — léger comme la mer, réconfortant comme une étreinte.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 390,
 "ings": ["300 g de filet de poisson blanc en gros morceaux", "1 poivron en lanières", "1 tomate hachée", "1 oignon en lanières",
          "2 gousses d'ail hachées", "120 ml de lait de coco allégé", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et coriandre au goût"],
 "passos": [
   "Assaisonne les morceaux de poisson avec du sel, du poivre, l'ail et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Dans une large casserole, fais chauffer l'huile d'olive et fais un lit avec l'oignon, le poivron et la tomate. Fais revenir 3 minutes, en remuant.",
   "Pose les morceaux de poisson sur les légumes (ne remue pas trop, pour que le poisson ne se défasse pas).",
   "Arrose de lait de coco allégé, couvre et fais cuire à feu moyen-doux 10 à 12 minutes, jusqu'à ce que le poisson soit blanc et tendre et que le bouillon prenne du corps.",
   "Parsème de coriandre et sers avec une petite portion de riz, pour profiter du bouillon."],
 "porcoes8": ["120 g de poisson · 2 c. à s. de riz",
              "150 g de poisson · 3 c. à s. de riz",
              "150 g de poisson · 3 c. à s. de riz",
              "170 g de poisson · 4 c. à s. de riz",
              "170 g de poisson · 4 c. à s. de riz",
              "200 g de poisson · 4 c. à s. de riz",
              "220 g de poisson · 5 c. à s. de riz",
              "250 g de poisson · 5 c. à s. de riz"],
 "dica": "Le poisson blanc est maigre et protéiné, et le lait de coco allégé donne du crémeux au bouillon avec bien moins de graisse que la crème. Les légumes rendent leur eau et forment une sauce légère et parfumée. C'est un mijoté réconfortant et léger, parfait pour le dîner.",
},
{
 "nome": "Brochettes de bœuf aux légumes",
 "hook": "Des dés de viande juteux alternés avec des légumes colorés, grillés jusqu'à dorer — un goût de barbecue dans la bonne mesure.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 420,
 "ings": ["250 g de bœuf maigre en dés", "1 poivron en carrés", "1 oignon en morceaux",
          "1 courgette en grosses rondelles", "tomates cerises", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "sel, poivre et paprika au goût", "piques à brochette"],
 "passos": [
   "Assaisonne les dés de viande avec du sel, du poivre, du paprika et l'ail. Laisse prendre le goût 10 minutes.",
   "Monte les brochettes en alternant un dé de viande, un carré de poivron, un morceau d'oignon, une rondelle de courgette et une tomate cerise, jusqu'à remplir la pique.",
   "Badigeonne les brochettes d'huile d'olive.",
   "Fais chauffer une grande poêle ou un gril à feu moyen-vif. Pose les brochettes et tourne-les toutes les 3 minutes, environ 12 minutes au total, jusqu'à ce que la viande soit dorée dehors et à ton goût dedans.",
   "Sers les brochettes avec une salade ou un peu de riz."],
 "porcoes8": ["1 brochette · salade",
              "2 brochettes · salade",
              "2 brochettes · salade · 2 c. à s. de riz",
              "2 brochettes · salade · 3 c. à s. de riz",
              "2 brochettes · salade · 3 c. à s. de riz",
              "3 brochettes · salade · 3 c. à s. de riz",
              "3 brochettes · salade · 4 c. à s. de riz",
              "3 grandes brochettes · salade · 4 c. à s. de riz"],
 "dica": "Les brochettes calment l'envie de grillades de façon légère : la viande maigre apporte les protéines et les légumes colorés remplissent la pique de fibres pour peu de calories. Enfiler aide naturellement à contrôler la portion, et griller sans huile garde tout savoureux et léger.",
},
{
 "nome": "Salade tiède au poulet, œuf et pommes de terre",
 "hook": "Des pommes de terre dorées, du poulet grillé et de l'œuf, le tout tiède sur des feuilles bien fraîches — une salade qui est un dîner complet et douillet.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 420,
 "ings": ["1 filet de blanc de poulet (environ 130 g)", "1 petite pomme de terre en dés", "2 œufs durs",
          "salade verte", "tomates cerises", "oignon rouge en lamelles", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et moutarde au goût"],
 "passos": [
   "Fais cuire les dés de pomme de terre 12 minutes dans de l'eau bouillante salée, jusqu'à ce qu'ils soient tendres. Égoutte. Si tu les veux dorés, fais-les sauter 3 minutes à la poêle avec quelques gouttes d'huile d'olive.",
   "Fais cuire les œufs 9 minutes, passe-les sous l'eau froide, écale-les et coupe-les en deux.",
   "Assaisonne le poulet avec du sel et du poivre et grille-le dans une poêle antiadhésive 4 à 5 minutes de chaque côté, jusqu'à ce qu'il soit doré. Coupe en lanières.",
   "Dans un saladier ou une assiette, fais un lit de salade verte et ajoute les tomates cerises et l'oignon.",
   "Répartis par-dessus la pomme de terre tiède, le poulet en lanières et les œufs. Prépare une sauce en mélangeant l'huile d'olive, le jus de citron, la moutarde, du sel et du poivre, arrose et sers tout de suite."],
 "porcoes8": ["100 g de poulet · ½ pomme de terre · 1 œuf",
              "130 g de poulet · 1 petite pomme de terre · 2 œufs",
              "130 g de poulet · 1 pomme de terre · 2 œufs",
              "150 g de poulet · 1 pomme de terre · 2 œufs",
              "150 g de poulet · 1 pomme de terre · 2 œufs",
              "170 g de poulet · 1 grosse pomme de terre · 2 œufs",
              "200 g de poulet · 1 grosse pomme de terre · 3 œufs",
              "220 g de poulet · 2 petites pommes de terre · 3 œufs"],
 "dica": "C'est une salade qui rassasie comme un repas chaud : le poulet et l'œuf apportent une double dose de protéines, la pomme de terre dans la bonne mesure donne de l'énergie et les feuilles remplissent l'assiette de fibres. Servie tiède, elle est réconfortante et légère à la fois — idéale pour le dîner.",
},
]
