# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). ESPANHOL (America Latina).

Traducao literal de `receitas_sobremesa_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario LatAm com foco Mexico (platano, fresa,
grenetina, endulzante, crema de cacahuate).
⛔ METRICO: g, ml, °C — como pt/de/fr. Os numeros vem do de/fr, NUNCA de
oz/cup de volta.
⛔ O campo `prompt` NAO e replicado: a foto e a mesma do PT (fotos/101-120).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
Metas (kcal): 120/150/170/190 · 180/200/230/260
"""

RECEITAS = [
{
 "nome": "Pastel de chocolate fit sin azúcar",
 "hook": "Esponjoso, húmedo y bien chocolatoso — el pastel que mata el antojo de dulce sin una pizca de azúcar, hecho con cacao de verdad.",
 "tempo": "40 min", "rende": "8 rebanadas", "kcal_base": 150,
 "ings": ["3 huevos", "1 plátano muy maduro, aplastado",
          "4 cucharadas de cacao en polvo 100 % (sin azúcar)",
          "5 cucharadas de avena molida en licuadora hasta hacerse harina (o harina integral)",
          "endulzante para hornear al gusto (el que sirve para el horno) — o 2 cucharadas de miel",
          "120 ml de leche (o bebida vegetal)", "1 cucharada de aceite",
          "1 cucharadita de polvo para hornear"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Unta un poco de aceite en un molde pequeño y espolvoréalo con cacao, para que el pastel no se pegue.",
   "En un tazón, bate los huevos con el endulzante (o la miel) con un tenedor o un batidor, 1 minuto, hasta que espume.",
   "Agrega el plátano aplastado, la leche y el aceite y mezcla bien.",
   "Agrega el cacao en polvo y la avena molida (o la harina) y revuelve hasta que quede una mezcla pareja, sin grumos secos.",
   "Al final, agrega el polvo para hornear y mezcla ligeramente, solo para integrarlo (revolver mucho después del polvo para hornear hace el pastel pesado).",
   "Vierte la mezcla en el molde y hornea 30 minutos. Para saber si ya está, mete un palillo en el centro: si sale limpio, el pastel está listo.",
   "Déjalo enfriar un poco antes de desmoldarlo y cortarlo. Queda excelente con frutos rojos encima."],
 "porcoes8": ["1 rebanada delgada",
              "1 rebanada",
              "1 rebanada · frutos rojos",
              "1 rebanada · 1 cucharada de yogur",
              "1 rebanada",
              "1 rebanada mediana",
              "1 rebanada · frutos rojos",
              "1 rebanada grande · frutos rojos"],
 "dica": "El cacao puro te da todo el sabor a chocolate sin el azúcar y la grasa del chocolate en polvo. El plátano endulza de forma natural y mantiene el pastel húmedo, la avena aporta fibra y los huevos proteína. Es la prueba de que puedes comer pastel de chocolate y seguir bajando de peso, siempre que la rebanada sea del tamaño correcto.",
},
{
 "nome": "Mousse de chocolate y aguacate",
 "hook": "Tan cremoso como el mousse tradicional, pero el secreto es el aguacate — nadie lo adivina, y no lleva crema ni azúcar.",
 "tempo": "10 min + refrigerador", "rende": "2 vasos", "kcal_base": 170,
 "ings": ["1 aguacate maduro (o ½ aguacate grande)",
          "3 cucharadas de cacao en polvo 100 %",
          "endulzante para hornear al gusto — o 2 cucharadas de miel",
          "3 cucharadas de leche (o bebida vegetal)", "1 pizca de canela",
          "1 pizca de sal",
          "chocolate 70 % rallado para decorar (opcional)"],
 "passos": [
   "Corta el aguacate a la mitad, saca el hueso y saca la pulpa con una cuchara. Usa solo la parte bien suave y verde.",
   "Pon la pulpa de aguacate en la licuadora o en el vaso de la licuadora de inmersión, junto con el cacao, el endulzante (o la miel), la leche, la canela y la sal.",
   "Licúa a velocidad máxima hasta que quede una crema tersa y brillante, sin grumos. Si queda muy espesa, agrega un poco más de leche.",
   "Pruébala y ajusta el dulzor a tu gusto.",
   "Repártela en dos vasos y mételos al refrigerador por lo menos 30 minutos, para que cuaje y se enfríe. Sirve con chocolate rallado encima."],
 "porcoes8": ["½ vaso pequeño",
              "1 vaso pequeño",
              "1 vaso",
              "1 vaso · chocolate rallado",
              "1 vaso",
              "1 vaso mediano",
              "1 vaso · chocolate rallado",
              "1 vaso grande · chocolate rallado"],
 "dica": "El aguacate da la cremosidad del mousse con grasa buena en lugar de crema, y llena mucho. El cacao puro aporta el sabor a chocolate sin azúcar. Es un postre rico y satisfactorio que, en porción pequeña, entra fácilmente en tu dieta.",
},
{
 "nome": "Trufas fit de cacao",
 "hook": "El dulce de fiesta en una versión sin azúcar y sin leche condensada — enrollado, chocolatoso y del tamaño justo para el antojo.",
 "tempo": "20 min + refrigerador", "rende": "10 trufas", "kcal_base": 130,
 "ings": ["6 dátiles sin hueso (esa fruta seca muy dulce)",
          "3 cucharadas de cacao en polvo 100 %",
          "2 cucharadas de leche (o bebida vegetal)",
          "1 cucharada de crema de cacahuate",
          "cacao en polvo extra para revolcar", "1 pizca de sal"],
 "passos": [
   "Remoja los dátiles en agua tibia 10 minutos, para que se suavicen. Escúrrelos.",
   "En el vaso de la licuadora de inmersión o en la licuadora, licúa los dátiles con el cacao, la leche, la crema de cacahuate y la sal, hasta que quede una masa espesa y pareja (bien mezclada). Si lo necesitas, detente y empuja la masa al centro con una cuchara.",
   "La masa debe quedar lo bastante firme para enrollarse. Si queda suave, métela al refrigerador 20 minutos.",
   "Con las manos ligeramente húmedas, toma porciones pequeñas y forma bolitas del tamaño de una nuez.",
   "Revuelca cada bolita en el cacao en polvo para cubrirla. Guárdalas en el refrigerador y sírvelas frías."],
 "porcoes8": ["1 trufa",
              "1 o 2 trufas",
              "2 trufas",
              "2 trufas",
              "2 trufas",
              "2 o 3 trufas",
              "3 trufas",
              "3 trufas"],
 "dica": "Los dátiles reemplazan el azúcar y la leche condensada con dulzor natural y bastante fibra, que detiene el antojo de dulce. El cacao puro da el sabor a chocolate y la crema de cacahuate la cremosidad. Una o dos bolitas matan el antojo sin disparar tus calorías.",
},
{
 "nome": "Pastel de chocolate en taza",
 "hook": "¿Antojo de algo dulce en la noche? En tres minutos, en el microondas, tienes un pastelito de chocolate caliente solo para ti.",
 "tempo": "5 min", "rende": "1 taza", "kcal_base": 190,
 "ings": ["1 huevo",
          "2 cucharadas de avena molida en licuadora hasta hacerse harina",
          "1 cucharada de cacao en polvo 100 %",
          "endulzante para hornear al gusto — o 1 cucharada de miel",
          "2 cucharadas de leche", "½ cucharadita de polvo para hornear",
          "1 pizca de sal"],
 "passos": [
   "En una taza grande (que pueda ir al microondas), rompe el huevo y bátelo con un tenedor.",
   "Agrega la avena molida, el cacao, el endulzante (o la miel), la leche y la sal. Mezcla bien, hasta que quede una masa pareja, sin partes secas en las orillas.",
   "Al final, agrega el polvo para hornear y revuelve ligeramente.",
   "Mete la taza al microondas a potencia alta (máxima) de 1 minuto 30 segundos a 2 minutos. El pastel se infla y cuaja; si sigue húmedo en el centro, dale otros 20 segundos.",
   "Cuidado, la taza sale caliente. Déjala enfriar 1 minuto y cómelo directo de la taza. Queda excelente con fruta encima."],
 "porcoes8": ["½ taza",
              "1 taza pequeña",
              "1 taza",
              "1 taza · fruta",
              "1 taza",
              "1 taza",
              "1 taza · fruta",
              "1 taza · fruta · 1 cucharada de crema de cacahuate"],
 "dica": "Hecho al momento y en una porción de una sola taza, este pastelito controla de forma natural cuánto comes — no queda un pastel entero tentándote en la mesa. Con avena, huevo y cacao puro, es dulce, caliente y reconfortante sin azúcar, ideal para un antojo nocturno.",
},
{
 "nome": "Mousse de yogur y fresa",
 "hook": "Rosado, aterciopelado y refrescante — un mousse de fresa que lleva solo tres ingredientes y nada de azúcar.",
 "tempo": "10 min + refrigerador", "rende": "3 vasos", "kcal_base": 120,
 "ings": ["300 g de fresas (frescas o congeladas)",
          "1 vaso de yogur natural sin azúcar (unos 170 g)",
          "1 cucharada de grenetina sin sabor",
          "endulzante al gusto — o 1 cucharada de miel",
          "3 cucharadas de agua caliente",
          "fresas picadas para decorar"],
 "passos": [
   "Lava las fresas y quítales las hojitas verdes. Guarda algunas para decorar.",
   "En una taza, disuelve la grenetina sin sabor en el agua caliente, revolviendo bien hasta que quede transparente, sin grumitos. Déjala enfriar un poco.",
   "En la licuadora, licúa las fresas con el yogur y el endulzante (o la miel) hasta que quede una crema tersa y rosada.",
   "Con la licuadora funcionando a velocidad baja, agrega la grenetina disuelta y licúa otros 30 segundos, solo para integrarla.",
   "Reparte en vasos y mételos al refrigerador por lo menos 2 horas, hasta que cuaje. Sirve con fresas picadas encima."],
 "porcoes8": ["½ vaso",
              "1 vaso pequeño",
              "1 vaso",
              "1 vaso · fresas",
              "1 vaso",
              "1 vaso mediano",
              "1 vaso · fresas",
              "1 vaso grande · fresas"],
 "dica": "Las fresas son dulces y llenas de vitamina C con muy pocas calorías, y el yogur natural suma proteína y cremosidad sin azúcar. La grenetina da la textura del mousse sin crema. Un postre ligero, bonito y refrescante que satisface el antojo de algo dulce.",
},
{
 "nome": "Nice cream cremoso de plátano",
 "hook": "Un helado de verdad, cremoso y frío, hecho solo con plátanos — sin azúcar, sin leche y sin máquina de helados.",
 "tempo": "5 min + congelador", "rende": "2 porciones", "kcal_base": 120,
 "ings": ["3 plátanos maduros",
          "1 cucharada de cacao en polvo 100 % O 1 puñado de frutos rojos (opcional, para dar sabor)",
          "1 pizca de canela",
          "1 cucharadita de crema de cacahuate (opcional)"],
 "passos": [
   "Pela los plátanos, córtalos en rodajas y ponlos en una bolsa o un recipiente. Congélalos por lo menos 3 horas, hasta que estén bien duros.",
   "Saca las rodajas congeladas y ponlas en una licuadora potente o en el vaso de la licuadora de inmersión.",
   "Licúa a velocidad máxima. Al principio se hace trocitos; sigue licuando (deteniéndote para empujar el plátano al centro) hasta que quede una crema tersa, igualita a un helado de máquina.",
   "Si quieres darle sabor, agrega el cacao o los frutos rojos y licúa un poco más.",
   "Sirve de inmediato, bien cremoso, con una pizca de canela — o mételo al congelador 1 hora para que quede más firme, como helado de bote."],
 "porcoes8": ["½ porción",
              "1 porción pequeña",
              "1 porción",
              "1 porción · 1 cucharada de crema de cacahuate",
              "1 porción",
              "1 porción mediana",
              "1 porción · fruta",
              "1 porción grande · fruta · crema de cacahuate"],
 "dica": "Congelado y licuado, el plátano suelta su propio azúcar natural y se convierte en una crema igualita a un helado, sin necesidad de azúcar, leche ni crema. Es dulce, frío y satisfactorio, con la fibra y el potasio de la fruta — el postre perfecto para los días calurosos, sin culpa.",
},
{
 "nome": "Flan de leche fit",
 "hook": "El mismo flan cremoso, con ese caramelo dorado — solo que sin azúcar y mucho más ligero, hecho con leche y huevos.",
 "tempo": "50 min", "rende": "6 rebanadas", "kcal_base": 130,
 "ings": ["3 huevos", "480 ml de leche descremada (o bebida vegetal)",
          "endulzante para hornear al gusto (el que sirve para el horno)",
          "1 cucharadita de extracto de vainilla",
          "endulzante que se hace caramelo (opcional, para la salsa)",
          "agua caliente para el baño maría"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Si quieres el caramelo, derrite un poco de endulzante tipo caramelo en un sartén pequeño y repártelo en el fondo (o sáltate el caramelo).",
   "En la licuadora, licúa los huevos, la leche, el endulzante y la vainilla 1 minuto, hasta que quede bien mezclado.",
   "Vierte la mezcla en el molde.",
   "Pon el molde dentro de una charola más grande y llena la charola con agua caliente hasta la mitad de la altura del molde (esto es el baño maría: el agua hace que el flan se hornee parejo y quede cremoso).",
   "Hornea 40 minutos, hasta que cuaje pero todavía se mueva ligeramente en el centro. Déjalo enfriar y después mételo al refrigerador 3 horas antes de desmoldarlo."],
 "porcoes8": ["1 rebanada delgada",
              "1 rebanada",
              "1 rebanada",
              "1 rebanada · fruta",
              "1 rebanada",
              "1 rebanada mediana",
              "1 rebanada · fruta",
              "1 rebanada grande · fruta"],
 "dica": "Al cambiar la leche condensada y el azúcar por leche descremada y endulzante, el flan conserva su cremosidad y sabor con una fracción de las calorías. Los huevos y la leche además aportan proteína. En una rebanada pequeña, es un postre clásico que entra en tu dieta.",
},
{
 "nome": "Galletas de avena y plátano",
 "hook": "Dos ingredientes, un tazón y veinte minutos: galletitas suaves y apenas dulces, sin azúcar y sin harina blanca.",
 "tempo": "20 min", "rende": "12 galletas", "kcal_base": 110,
 "ings": ["2 plátanos muy maduros", "135 g de avena en hojuelas",
          "1 pizca de canela",
          "1 cucharada de pasas o chispas de chocolate 70 % (opcional)",
          "1 pizca de sal"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Cubre una charola con papel para hornear.",
   "En un tazón, aplasta bien los plátanos con un tenedor, hasta que queden un puré sin grumos grandes.",
   "Agrega la avena, la canela, la sal y, si quieres, las pasas o el chocolate picado. Mezcla hasta que se forme una masa pegajosa.",
   "Con una cuchara, pon porciones pequeñas en la charola y aplana cada una con el revés de la cuchara, dándoles forma de galleta.",
   "Hornea de 12 a 15 minutos, hasta que las orillas queden doradas y firmes. Déjalas enfriar en la charola (se firman al enfriarse) y sirve."],
 "porcoes8": ["1 galleta",
              "2 galletas",
              "2 galletas",
              "2 galletas · fruta",
              "2 galletas",
              "3 galletas",
              "3 galletas",
              "3 o 4 galletas"],
 "dica": "El plátano maduro endulza y liga sin necesidad de azúcar ni harina blanca, y la avena aporta la fibra que te llena. Son galletas naturales, buenísimas para una colación o un postre, que matan el antojo de dulce de forma ligera — pero cuenta cuántas comes, porque es fácil excederse.",
},
{
 "nome": "Manzana al horno con canela y nueces",
 "hook": "La manzana queda suave y aromática con canela, con un relleno crujiente de nueces — un postre caliente que reconforta como un pay, sin la masa.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 130,
 "ings": ["2 manzanas", "canela molida al gusto",
          "1 cucharada de nueces picadas (u otras nueces)",
          "1 cucharada de avena en hojuelas",
          "1 cucharadita de miel (opcional)",
          "1 pizca de clavo molido (opcional)"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Lava las manzanas y, con un cuchillo, saca el corazón del centro (la parte de las semillas), formando un hueco, sin atravesar el fondo.",
   "En un tazón pequeño, mezcla las nueces picadas, la avena, la canela y, si quieres, la miel y el clavo.",
   "Rellena el hueco de cada manzana con esta mezcla, presionando ligeramente.",
   "Pon las manzanas en una charola con un dedo de agua en el fondo (para que no se resequen) y espolvorea más canela encima.",
   "Hornea de 25 a 30 minutos, hasta que la manzana quede muy suave (el tenedor entra fácil) y el relleno dorado. Sirve caliente, sola o con una cucharada de yogur natural."],
 "porcoes8": ["½ manzana",
              "1 manzana",
              "1 manzana",
              "1 manzana · 1 cucharada de yogur",
              "1 manzana",
              "1 manzana · nueces extra",
              "1 manzana · yogur",
              "2 manzanas · yogur"],
 "dica": "Hornear la manzana concentra el dulzor natural de la fruta, así que queda dulce sin azúcar. La canela levanta el sabor y ayuda a controlar el antojo de dulce, y las nueces aportan grasa buena y textura crujiente. Es el consuelo de un pay de manzana con una fracción de las calorías.",
},
{
 "nome": "Gelatina casera de fruta",
 "hook": "Colorida, temblorosa y refrescante, con trozos de fruta de verdad adentro — el postre más ligero que existe.",
 "tempo": "10 min + refrigerador", "rende": "4 vasos", "kcal_base": 70,
 "ings": ["1 cucharada de grenetina sin sabor",
          "480 ml de jugo natural de fruta sin azúcar (naranja, uva o fresa)",
          "120 ml de agua",
          "150 g de fruta picada (fresa, kiwi, mango o uvas)",
          "endulzante al gusto (opcional)"],
 "passos": [
   "En una olla pequeña, pon el agua y espolvorea la grenetina sin sabor encima. Déjala reposar 2 minutos (la grenetina se hincha, eso se llama hidratar).",
   "Ponla a fuego bajo y revuelve 1 minuto, solo hasta que la grenetina se disuelva por completo, sin que hierva. Apaga.",
   "Agrega el jugo natural de fruta (y el endulzante, si quieres) y mezcla bien.",
   "Pon la fruta picada en el fondo de los vasos o de un refractario y vierte el líquido encima.",
   "Mete al refrigerador por lo menos 4 horas, hasta que cuaje. Sirve bien fría."],
 "porcoes8": ["½ vaso",
              "1 vaso pequeño",
              "1 vaso",
              "1 vaso · fruta extra",
              "1 vaso",
              "1 vaso mediano",
              "1 vaso · fruta",
              "1 vaso grande · fruta"],
 "dica": "Hecha con jugo natural en lugar del polvo lleno de azúcar y colorantes, la gelatina casera prácticamente no tiene calorías y aun así lleva trozos de fruta de verdad. Es el postre ideal para cuando quieres algo dulce y frío sin que pese nada en tu dieta.",
},
{
 "nome": "Barra de avena con fruta seca",
 "hook": "La barra de cereal casera, masticable y apenas dulce, sin los azúcares y jarabes de las de tienda — perfecta para tu bolsa.",
 "tempo": "30 min", "rende": "8 barras", "kcal_base": 150,
 "ings": ["180 g de avena en hojuelas", "2 plátanos maduros, aplastados",
          "3 cucharadas de fruta seca picada (pasas, chabacano o dátiles)",
          "2 cucharadas de nueces picadas",
          "1 cucharada de miel (opcional)", "1 pizca de canela y sal"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Cubre un molde rectangular pequeño con papel para hornear.",
   "En un tazón, aplasta bien los plátanos hasta que queden un puré.",
   "Agrega la avena, la fruta seca picada, las nueces, la canela, la sal y, si quieres, la miel. Mezcla hasta que se forme una masa pegajosa y pareja.",
   "Vierte la masa en el molde y presiónala bien con el revés de una cuchara, dejando una capa firme y pareja (mientras más apretada, menos se desmorona la barra).",
   "Hornea 20 minutos, hasta que las orillas queden doradas. Déjala enfriar por completo en el molde antes de cortarla en barras (si la cortas caliente, se desmorona)."],
 "porcoes8": ["1 barra",
              "1 barra",
              "1 barra",
              "1 barra · fruta",
              "1 barra",
              "1 o 2 barras",
              "2 barras",
              "2 barras"],
 "dica": "Las barras de supermercado suelen tener más azúcar y jarabe que un dulce. Hecha en casa con avena, plátano y fruta seca, la barra endulza de forma natural y aporta fibra y energía que detienen el hambre. Buenísima para una colación o un postre práctico, pero come una a la vez.",
},
{
 "nome": "Yogur congelado en trozos con frutos rojos",
 "hook": "Una lámina crujiente de yogur congelado salpicada de fruta, que rompes en pedazos — bonita, divertida y sin azúcar.",
 "tempo": "5 min + congelador", "rende": "4 porciones", "kcal_base": 100,
 "ings": ["1 envase grande de yogur griego natural sin azúcar (unos 350 g)",
          "140 g de frutos rojos (fresa, arándano, frambuesa)",
          "1 cucharada de miel (opcional)",
          "1 cucharada de nueces picadas (opcional)",
          "chocolate 70 % rallado (opcional)"],
 "passos": [
   "Cubre una charola o un refractario poco hondo con papel para hornear.",
   "En un tazón, mezcla el yogur griego con la miel (si la usas), hasta que quede muy terso.",
   "Extiende el yogur sobre el papel, formando una capa como de medio dedo de grosor.",
   "Reparte los frutos rojos encima (corta las fresas), las nueces y el chocolate rallado, distribuyéndolos por toda la superficie.",
   "Congela de 3 a 4 horas, hasta que esté bien duro. Rómpelo o córtalo en trozos irregulares y sirve de inmediato (se derrite rápido). Guarda el resto en el congelador."],
 "porcoes8": ["1 trozo pequeño",
              "1 trozo",
              "1 o 2 trozos",
              "2 trozos",
              "2 trozos",
              "2 trozos",
              "2 o 3 trozos",
              "3 trozos"],
 "dica": "El yogur griego aporta proteína y cremosidad sin azúcar, y congelado se convierte en un antojo frío y crujiente. Los frutos rojos endulzan de forma natural y lo llenan de antioxidantes. Es un postre refrescante y ligero, buenísimo para el verano y para las ganas de picar algo dulce.",
},
{
 "nome": "Trufas de chocolate fit",
 "hook": "Pequeñas, intensas y chocolatosas — la trufa que se derrite en la boca sin nada de azúcar, para los momentos de antojo fuerte.",
 "tempo": "20 min + refrigerador", "rende": "10 trufas", "kcal_base": 120,
 "ings": ["100 g de chocolate 70 % (o más oscuro)",
          "4 cucharadas de leche caliente (o bebida vegetal)",
          "2 cucharadas de coco rallado sin azúcar",
          "cacao en polvo 100 % para revolcar", "1 pizca de sal"],
 "passos": [
   "Pica el chocolate 70 % en trozos pequeños y ponlo en un tazón.",
   "Calienta la leche hasta que casi hierva y viértela sobre el chocolate. Espera 1 minuto y revuelve hasta que el chocolate se derrita por completo, formando una crema tersa y brillante (esto es la ganache).",
   "Agrega el coco rallado y la sal y mezcla. Mete al refrigerador 1 hora, hasta que la mezcla quede lo bastante firme para enrollarse.",
   "Con las manos, toma porciones pequeñas y forma bolitas del tamaño de una aceituna grande.",
   "Revuelca cada trufa en el cacao en polvo para cubrirla. Guárdalas en el refrigerador y sírvelas frías."],
 "porcoes8": ["1 trufa",
              "1 trufa",
              "1 o 2 trufas",
              "2 trufas",
              "2 trufas",
              "2 trufas",
              "2 o 3 trufas",
              "3 trufas"],
 "dica": "El chocolate de 70 % o más oscuro tiene poco azúcar y mucho cacao, que es rico en antioxidantes. En una trufa pequeña, satisface el antojo intenso de chocolate con mucho menos azúcar que un dulce normal. Una o dos resuelven el antojo sin sabotear tu dieta.",
},
{
 "nome": "Pastel de zanahoria fit con glaseado de cacao",
 "hook": "El pastel de zanahoria esponjoso de tu infancia, con un glaseado de chocolate — sin azúcar, pero con toda la calidez y el sabor.",
 "tempo": "45 min", "rende": "8 rebanadas", "kcal_base": 160,
 "ings": ["2 zanahorias medianas, picadas", "3 huevos",
          "3 cucharadas de aceite",
          "endulzante para hornear al gusto (el que sirve para el horno)",
          "135 g de avena molida en licuadora hasta hacerse harina (o harina integral)",
          "1 cucharadita de polvo para hornear",
          "Glaseado: 2 cucharadas de cacao en polvo 100 % + 2 cucharadas de leche + endulzante al gusto"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Unta un poco de aceite en un molde y espolvoréalo con un poco de harina.",
   "En la licuadora, licúa las zanahorias picadas, los huevos, el aceite y el endulzante hasta que quede una crema tersa y anaranjada.",
   "Pásala a un tazón, agrega la avena molida (o la harina) y mezcla. Al final, agrega el polvo para hornear y revuelve ligeramente.",
   "Vierte la mezcla en el molde y hornea 30 minutos, hasta que un palillo metido en el centro salga limpio.",
   "Haz el glaseado: en una olla pequeña, mezcla el cacao, la leche y el endulzante y calienta a fuego bajo 2 minutos, revolviendo, hasta que quede una crema brillante. Extiéndelo sobre el pastel todavía tibio."],
 "porcoes8": ["1 rebanada delgada",
              "1 rebanada",
              "1 rebanada",
              "1 rebanada · fruta",
              "1 rebanada",
              "1 rebanada mediana",
              "1 rebanada · fruta",
              "1 rebanada grande"],
 "dica": "La zanahoria mantiene el pastel húmedo y naturalmente dulce, y además aporta vitamina A. Al cambiar el azúcar por endulzante y la harina blanca por avena, el pastel queda ligero y lleno de fibra. El glaseado de cacao puro da el toque de chocolate sin el azúcar de un betún tradicional.",
},
{
 "nome": "Mousse de limón",
 "hook": "Ácido en la medida justa, cremoso y frío — un mousse de limón refrescante que limpia el paladar y no tiene azúcar.",
 "tempo": "10 min + refrigerador", "rende": "3 vasos", "kcal_base": 120,
 "ings": ["1 vaso de yogur natural sin azúcar (unos 170 g)",
          "jugo de 2 limones", "ralladura de 1 limón",
          "1 cucharada de grenetina sin sabor",
          "3 cucharadas de agua caliente",
          "endulzante al gusto — o 2 cucharadas de miel"],
 "passos": [
   "Lava bien 1 limón y saca la ralladura solo de la parte verde de la cáscara (la parte blanca amarga). Exprime los 2 limones para el jugo.",
   "En una taza, disuelve la grenetina sin sabor en el agua caliente, revolviendo hasta que quede transparente. Déjala enfriar un poco.",
   "En un tazón, mezcla el yogur, el jugo de limón, la ralladura y el endulzante (o la miel), hasta que quede cremoso.",
   "Agrega la grenetina disuelta y mezcla bien y rápido, para que no se formen grumitos.",
   "Reparte en vasos y mete al refrigerador por lo menos 2 horas, hasta que cuaje. Sirve frío, con más ralladura de limón encima."],
 "porcoes8": ["½ vaso",
              "1 vaso pequeño",
              "1 vaso",
              "1 vaso · fruta",
              "1 vaso",
              "1 vaso mediano",
              "1 vaso · fruta",
              "1 vaso grande · fruta"],
 "dica": "El limón aporta frescura y un sabor fuerte que engaña el antojo de dulce sin necesidad de mucho endulzante. El yogur natural aporta proteína y cremosidad, y la grenetina cuaja el mousse sin crema. Un postre ligero, refrescante y con casi cero grasa.",
},
{
 "nome": "Cheesecake fit de frutos rojos (sin horno)",
 "hook": "Cremoso, con una base crujiente y una cobertura de fruta, armado sin horno — el cheesecake de tus sueños en versión ligera y sin azúcar.",
 "tempo": "20 min + refrigerador", "rende": "6 rebanadas", "kcal_base": 170,
 "ings": ["Base: 90 g de avena + 1 plátano aplastado + 1 cucharadita de canela",
          "Crema: 250 g de ricotta (o queso cottage) + ½ envase de yogur natural + endulzante al gusto + jugo de ½ limón",
          "1 cucharada de grenetina sin sabor + 3 cucharadas de agua caliente",
          "Cobertura: 140 g de frutos rojos + endulzante al gusto"],
 "passos": [
   "Base: mezcla la avena, el plátano aplastado y la canela hasta que se forme una masa. Presiónala en el fondo de un molde pequeño (de preferencia desmontable), formando una capa firme. Mete al congelador 10 minutos.",
   "Disuelve la grenetina en el agua caliente, revolviendo hasta que quede transparente. Déjala enfriar un poco.",
   "Crema: en la licuadora, licúa la ricotta, el yogur, el endulzante y el jugo de limón hasta que quede una crema muy tersa. Agrega la grenetina y licúa otros 20 segundos.",
   "Vierte la crema sobre la base y empareja la superficie. Mete al refrigerador por lo menos 3 horas, hasta que cuaje.",
   "Cobertura: en una olla pequeña, cocina los frutos rojos con el endulzante a fuego bajo 5 minutos, aplastándolos un poco, hasta que quede una mermelada. Déjala enfriar y extiéndela sobre el cheesecake antes de servir."],
 "porcoes8": ["1 rebanada delgada",
              "1 rebanada",
              "1 rebanada",
              "1 rebanada · cobertura extra",
              "1 rebanada",
              "1 rebanada mediana",
              "1 rebanada · cobertura",
              "1 rebanada grande · cobertura"],
 "dica": "La ricotta y el queso cottage dan la cremosidad del queso crema con mucha menos grasa y más proteína. La base de avena y plátano reemplaza la galleta con mantequilla, y la cobertura de fruta cocida no necesita azúcar. Un cheesecake de verdad que entra en tu dieta, en una rebanada controlada.",
},
{
 "nome": "Paletas caseras de fruta",
 "hook": "Refrescantes y llenas de fruta de verdad, estas paletas caseras son el postre perfecto para el calor — y no tienen ni una gota de azúcar.",
 "tempo": "10 min + congelador", "rende": "6 paletas", "kcal_base": 60,
 "ings": ["300 g de fruta picada (fresa, mango, kiwi o sandía)",
          "240 ml de jugo natural sin azúcar (o agua de coco)",
          "1 envase de yogur natural sin azúcar (opcional, para paletas cremosas)",
          "endulzante al gusto (opcional)",
          "moldes para paleta y palitos"],
 "passos": [
   "Pica la fruta en trozos pequeños, para que quepan en los moldes.",
   "Elige el estilo: para paletas de fruta, usa solo la fruta y el jugo natural; para paletas cremosas, licúa la fruta con el yogur en la licuadora.",
   "Pon algunos trozos de fruta en el fondo de cada molde (se ve bonito) y llénalo con el jugo o la crema licuada, dejando un dedo de espacio arriba (el líquido se expande al congelarse).",
   "Clava un palito en el centro de cada paleta.",
   "Congela por lo menos 5 horas, hasta que estén bien firmes. Para desmoldarlas, pasa el molde rápido bajo agua tibia."],
 "porcoes8": ["1 paleta",
              "1 paleta",
              "1 paleta",
              "1 o 2 paletas",
              "1 paleta",
              "1 o 2 paletas",
              "2 paletas",
              "2 paletas"],
 "dica": "Las paletas de tienda son casi solo agua, azúcar y colorante. Hecha en casa con fruta de verdad y jugo natural, la paleta se vuelve un postre refrescante lleno de vitaminas y prácticamente sin calorías — la mejor forma de matar el antojo de algo frío en el calor sin culpa.",
},
{
 "nome": "Muffins de manzana y canela",
 "hook": "Esponjosos, aromáticos y con trozos de manzana — muffins de la tarde que parecen un pecado, pero son ligeros y sin azúcar.",
 "tempo": "35 min", "rende": "6 muffins", "kcal_base": 140,
 "ings": ["2 huevos",
          "1 manzana rallada + ½ manzana en cubos pequeños",
          "135 g de avena molida en licuadora hasta hacerse harina",
          "3 cucharadas de aceite",
          "endulzante para hornear al gusto (el que sirve para el horno)",
          "120 ml de leche", "1 cucharadita de canela",
          "1 cucharadita de polvo para hornear", "1 pizca de sal"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Cubre un molde para muffins con capacillos (o unta un poco de aceite en los huecos).",
   "En un tazón, bate los huevos con el endulzante y el aceite 1 minuto. Agrega la leche y la manzana rallada y mezcla.",
   "Agrega la avena molida, la canela y la sal y revuelve hasta que quede una masa pareja. Agrega los cubos de manzana y el polvo para hornear y mezcla ligeramente.",
   "Reparte la masa en los capacillos, llenándolos hasta dos terceras partes (se inflan).",
   "Hornea de 20 a 25 minutos, hasta que queden dorados y un palillo salga limpio. Déjalos enfriar un poco y sirve."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 cucharada de yogur",
              "1 muffin",
              "1 o 2 muffins",
              "2 muffins",
              "2 muffins"],
 "dica": "La manzana rallada mantiene los muffins húmedos y naturalmente dulces, así que no necesitas azúcar. La avena aporta la fibra que te llena y la canela levanta el dulzor de la fruta. Son buenísimos para una colación o postre, en porción de una pieza, matando el antojo de pan dulce de forma ligera.",
},
{
 "nome": "Crumble de manzana y avena",
 "hook": "Manzana suave abajo, una migaja crujiente de avena arriba — el consuelo de un pay caliente, armado en minutos y sin azúcar.",
 "tempo": "40 min", "rende": "4 porciones", "kcal_base": 160,
 "ings": ["3 manzanas en cubos", "jugo de ½ limón",
          "1 cucharadita de canela",
          "Migaja: 90 g de avena en hojuelas + 2 cucharadas de nueces picadas + 2 cucharadas de aceite de coco (o aceite normal) + endulzante al gusto",
          "1 pizca de sal"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). En un tazón, mezcla los cubos de manzana con el jugo de limón y la canela y repártelos en el fondo de un refractario.",
   "Haz la migaja: en otro tazón, mezcla la avena, las nueces, el aceite, el endulzante y la sal, frotando con las yemas de los dedos hasta que se forme una migaja húmeda y con grumos.",
   "Reparte la migaja sobre las manzanas, cubriendo toda la superficie.",
   "Hornea de 25 a 30 minutos, hasta que la manzana burbujee por los lados y la migaja quede dorada y crujiente.",
   "Déjalo enfriar 5 minutos y sirve. Queda delicioso con una cucharada de yogur natural o nice cream de plátano encima."],
 "porcoes8": ["½ porción",
              "1 porción pequeña",
              "1 porción",
              "1 porción · yogur",
              "1 porción",
              "1 porción mediana",
              "1 porción · yogur",
              "1 porción grande · yogur"],
 "dica": "La manzana horneada suelta su propio dulzor, y la canela refuerza el sabor sin azúcar. La migaja de avena y nueces da el crujido de un pay con fibra y grasa buena en lugar de mantequilla y harina blanca. Es el consuelo de un postre caliente al horno, en la porción correcta.",
},
{
 "nome": "Pera al horno con especias",
 "hook": "La pera queda suave y jugosa, perfumada con canela y clavo — un postre elegante y caliente, endulzado solo por la fruta.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 110,
 "ings": ["2 peras firmes", "raja de canela (o molida)",
          "2 clavos de olor", "ralladura de naranja (opcional)",
          "1 cucharadita de miel (opcional)",
          "1 cucharada de nueces o almendras picadas"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Lava las peras, córtalas a la mitad a lo largo y saca el corazón del centro con una cuchara pequeña, formando un hueco.",
   "Pon las mitades de pera en una charola, con el corte hacia arriba. Espolvoréales canela y pon un clavo y un poco de ralladura de naranja en cada hueco.",
   "Si quieres, deja caer unas gotas de miel en cada pera.",
   "Pon un dedo de agua en el fondo de la charola (para que no se resequen) y hornea 25 minutos, hasta que la pera quede muy suave (el tenedor entra fácil).",
   "Saca los clavos, espolvorea las nueces picadas encima y sirve caliente, sola o con una cucharada de yogur natural."],
 "porcoes8": ["1 mitad",
              "1 pera (2 mitades)",
              "1 pera",
              "1 pera · yogur",
              "1 pera",
              "1 pera · nueces extra",
              "1 pera · yogur",
              "2 peras · yogur"],
 "dica": "Hornear la pera concentra el azúcar natural de la fruta, dejándola dulce sin necesidad de azúcar añadida. Las especias aportan un aroma reconfortante que satisface el paladar, y las nueces suman grasa buena y textura crujiente. Un postre caliente, ligero y sofisticado.",
},
]
