# -*- coding: utf-8 -*-
"""30 receitas de SUCO/BEBIDA (121-150). ITALIANO.

Traducao literal de `receitas_suco_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md.
⛔ METRICO: `3/4 cup`->`200 ml` · `1 cup`->`240/250 ml` · `4 cups`->`1 litro`
   · `1 1/2 cups grapes`->`225 g` · `1 cup berries`->`140 g`.
⛔⛔ As 10 ultimas sao `livre: True` e NAO tem `porcoes8` — o motor troca a
   tabela de porcao por uma faixa "a volontà". Inventar a tabela delas seria
   inventar produto; a paridade com o PT e' cobrada pelo lint.
⚠️ Os NOMES nao sao livres: o `TAG_BEBIDA["it"]` le' o nome para decidir o
   rotulo. Por isso a 147 e' "Tisana di camomilla" e nao "Camomilla" — sozinha
   ela cairia no rotulo padrao `Succo detox`. Medido no controle negativo.
⛔ O campo `prompt` NAO e' replicado: a foto e' a mesma (fotos/NNN, sem texto).
"""

# porção padrão para sucos (metas 90/110/130/150 · 130/150/170/190)
P = ["1 bicchiere (200 ml)", "1 bicchiere (250 ml)", "1 bicchiere grande (300 ml)", "1 bicchiere grande · ½ frutto",
     "1 bicchiere grande (300 ml)", "1 bicchiere grande (350 ml)", "1 bicchiere grande · ½ frutto", "2 bicchieri o 1 frutto in più"]
# porção padrão para vitaminas (mais encorpadas, dá para somar aveia)
V = ["1 bicchiere (200 ml)", "1 bicchiere (250 ml)", "1 bicchiere grande (300 ml)", "1 bicchiere · 1 cucchiaio di avena",
     "1 bicchiere grande (300 ml)", "1 bicchiere grande (350 ml)", "1 bicchiere grande · 1 cucchiaio di avena", "1 bicchiere grande · 2 cucchiai di avena"]


RECEITAS = [
{
 "nome": "Succo verde detox",
 "hook": "Il classico detox del mattino: leggero, rinfrescante e pieno di clorofilla per dare al tuo corpo quella spinta.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 90,
 "ings": ["1 foglia di cavolo nero (o 1 manciata di spinaci)",
          "1 mela verde a pezzi", "succo di ½ limone",
          "1 pezzetto di zenzero", "200 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Lava bene il cavolo nero e la mela. Togli il gambo grosso al cavolo nero.",
   "Metti tutto nel frullatore con l'acqua fredda e frulla alla massima velocità per 1 minuto, finché non è completamente liquido.",
   "Se lo preferisci senza pezzetti, filtralo con un colino. Servi subito, con il ghiaccio."],
 "porcoes8": P,
 "dica": "Le foglie verdi hanno tante fibre e acqua con pochissime calorie, e aiutano a sgonfiare e a dare sazietà. Berlo prima di colazione ti idrata e prepara il corpo per la giornata. Senza zucchero, è una delle bevande più leggere che ci siano.",
},
{
 "nome": "Succo di cetriolo, limone e menta",
 "hook": "Pura freschezza in un bicchiere — il cetriolo rinfresca, il limone ti sveglia e la menta profuma. Idratazione che aiuta a sgonfiare.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 70,
 "ings": ["½ cetriolo a pezzi", "succo di 1 limone", "5 foglie di menta",
          "250 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Lava il cetriolo e taglialo a pezzi (puoi lasciare la buccia se è sottile).",
   "Frulla il cetriolo, il succo di limone, la menta e l'acqua nel frullatore per 1 minuto.",
   "Filtralo se lo vuoi più pulito e servi ben freddo, con il ghiaccio."],
 "porcoes8": P,
 "dica": "Il cetriolo è quasi tutto acqua e aiuta a idratarti e a ridurre la ritenzione idrica (quella sensazione di gonfiore). Con limone e menta, diventa una bevanda super rinfrescante con praticamente zero calorie — ottima da bere durante la giornata al posto delle bibite gassate.",
},
{
 "nome": "Succo di ananas con menta e zenzero",
 "hook": "Dolce, tropicale e utile alla digestione — l'ananas con lo zenzero è il succo che rinfresca e aiuta anche a calmare l'infiammazione.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 110,
 "ings": ["2 fette di ananas a pezzi", "5 foglie di menta",
          "1 pezzetto di zenzero", "200 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Taglia l'ananas a pezzi, togliendo la buccia e il torsolo duro al centro.",
   "Frulla l'ananas, la menta, lo zenzero e l'acqua nel frullatore per 1 minuto, finché non è omogeneo.",
   "Filtralo se ti va e servi ben freddo, con il ghiaccio e una foglia di menta."],
 "porcoes8": P,
 "dica": "L'ananas ha enzimi che aiutano la digestione ed è ricco di acqua e vitamina C. Lo zenzero accelera leggermente il metabolismo e calma l'infiammazione. È un succo naturalmente dolce, quindi non ha bisogno di zucchero — la frutta fa già quel lavoro.",
},
{
 "nome": "Succo di barbabietola, carota e arancia",
 "hook": "Rosso acceso e pieno di energia — la barbabietola con l'arancia è un succo che ti tira su e colora la tua giornata.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 120,
 "ings": ["½ barbabietola cruda piccola a pezzi", "1 carota a pezzi",
          "succo di 2 arance", "100 ml di acqua", "ghiaccio q.b."],
 "passos": [
   "Sbuccia la barbabietola e la carota e tagliale a pezzetti.",
   "Spremi le arance. Frulla la barbabietola, la carota, il succo d'arancia e l'acqua nel frullatore per 2 minuti, finché non è completamente liquido.",
   "Filtralo con un colino (barbabietola e carota lasciano fibre) e servi freddo."],
 "porcoes8": P,
 "dica": "La barbabietola migliora la circolazione e dà energia, la carota porta vitamina A e l'arancia vitamina C. Insieme, fanno un succo naturalmente dolce e nutriente. Visto che ha lo zucchero naturale della frutta e della barbabietola, vale la pena rispettare la porzione da un bicchiere.",
},
{
 "nome": "Succo di anguria con limone",
 "hook": "Idratazione sotto forma di succo: l'anguria è quasi tutta acqua, dolce al punto giusto e rinfrescante come poche.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 80,
 "ings": ["2 fette grandi di anguria senza buccia", "succo di ½ limone",
          "5 foglie di menta (facoltativo)", "ghiaccio q.b."],
 "passos": [
   "Taglia l'anguria a cubetti e togli i semi più grossi.",
   "Frulla l'anguria con il succo di limone (e la menta, se ti va) nel frullatore per 30 secondi — l'anguria rilascia tantissima acqua, quindi non serve quasi aggiungere liquido.",
   "Servi immediatamente, ben fredda, con il ghiaccio."],
 "porcoes8": P,
 "dica": "L'anguria è composta per oltre il 90 % di acqua, quindi idrata tantissimo e riempie lo stomaco con poche calorie. È naturalmente dolce e rinfrescante, perfetta per togliere la voglia di qualcosa di dolce e freddo con il caldo senza uscire dalla tua dieta.",
},
{
 "nome": "Succo di carota, mela e zenzero",
 "hook": "Dolce, arancione e con un tocco piccante di zenzero — un succo che rinforza le difese e sveglia il corpo.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 110,
 "ings": ["1 carota a pezzi", "1 mela a pezzi", "1 pezzetto di zenzero",
          "200 ml di acqua", "ghiaccio q.b."],
 "passos": [
   "Sbuccia la carota e taglia la mela a pezzi, togliendo i semi.",
   "Frulla la carota, la mela, lo zenzero e l'acqua nel frullatore per 2 minuti, finché non è completamente liquido.",
   "Filtralo con un colino e servi freddo."],
 "porcoes8": P,
 "dica": "La carota e la mela portano dolcezza naturale e tante fibre, mentre lo zenzero dà quel tocco termogenico che aiuta il metabolismo. È un succo carico di vitamine, ideale per iniziare la giornata con energia e senza bisogno di zucchero.",
},
{
 "nome": "Succo verde con spinaci, ananas e cetriolo",
 "hook": "Verde e dolce allo stesso tempo — l'ananas nasconde gli spinaci e non ti accorgi nemmeno di stare bevendo qualcosa di così sano.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 100,
 "ings": ["1 manciata di spinaci", "1 fetta di ananas a pezzi",
          "½ cetriolo a pezzi", "succo di ½ limone",
          "200 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Lava bene gli spinaci e il cetriolo.",
   "Frulla gli spinaci, l'ananas, il cetriolo, il limone e l'acqua nel frullatore per 1 minuto, finché non è ben verde e liquido.",
   "Filtralo se ti va e servi freddo."],
 "porcoes8": P,
 "dica": "Gli spinaci sono estremamente ricchi di ferro e nutrienti con quasi zero calorie, e l'ananas rende il succo dolce e gustoso senza zucchero. Il cetriolo idrata e aiuta a sgonfiare. È un modo facile e buono di mangiare più verde.",
},
{
 "nome": "Succo d'arancia con carota e zenzero",
 "hook": "La tua dose quotidiana di vitamina C in un bicchiere arancione acceso — rinforza le difese e ti dà energia per la giornata.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 110,
 "ings": ["succo di 3 arance", "1 carota a pezzi", "1 pezzetto di zenzero",
          "ghiaccio q.b."],
 "passos": [
   "Spremi le arance per il succo.",
   "Sbuccia la carota e tagliala a pezzetti. Frulla la carota, il succo d'arancia e lo zenzero nel frullatore per 2 minuti.",
   "Filtralo con un colino e servi ben freddo, con il ghiaccio."],
 "porcoes8": P,
 "dica": "L'arancia e la carota sono piene di vitamina C e A, e lo zenzero aggiunge un tocco che aiuta la circolazione e il metabolismo. È un succo energizzante e naturalmente dolce — ricorda solo di rispettare la porzione, visto che lo zucchero della frutta aggiunge calorie.",
},
{
 "nome": "Succo d'uva naturale con limone",
 "hook": "Viola intenso e pieno di antiossidanti — l'uva diventa un succo naturalmente dolce che fa bene al cuore.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 120,
 "ings": ["1 grappolo piccolo di uva nera senza semi (circa 225 g)",
          "succo di ½ limone", "150 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Lava bene l'uva e staccala dal raspo.",
   "Frulla l'uva con il limone e l'acqua nel frullatore per 1 minuto, finché non si disfa.",
   "Filtralo con un colino, premendo bene per estrarre tutto il succo, e servi freddo."],
 "porcoes8": P,
 "dica": "L'uva nera è ricca di antiossidanti che proteggono il cuore e la pelle. Fatto al momento, senza zucchero, il succo d'uva naturale è molto diverso da quello confezionato — ricorda solo che l'uva è un frutto molto dolce, quindi la porzione da un bicchiere conta.",
},
{
 "nome": "Succo detox con mela, cavolo nero e sedano",
 "hook": "Leggerissimo e sgonfiante — la combinazione verde che ripulisce l'organismo e funziona molto bene prima dei pasti.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 90,
 "ings": ["1 mela verde a pezzi", "1 foglia di cavolo nero",
          "1 gambo di sedano", "succo di ½ limone",
          "200 ml di acqua fredda", "ghiaccio q.b."],
 "passos": [
   "Lava il cavolo nero, la mela e il sedano. Togli il gambo grosso al cavolo nero.",
   "Frulla la mela, il cavolo nero, il sedano, il limone e l'acqua nel frullatore per 1 minuto.",
   "Filtralo e servi ben freddo."],
 "porcoes8": P,
 "dica": "Il sedano è diuretico e aiuta a eliminare i liquidi in eccesso, il cavolo nero porta fibre e nutrienti e la mela dolcifica in modo naturale. È un succo verde leggero e sgonfiante, ottimo per accompagnare un percorso di dimagrimento.",
},
{
 "nome": "Frullato di banana con avena e cannella",
 "hook": "Cremoso e avvolgente, questo frullato ti porta avanti per tutta la mattina — la colazione liquida per i giorni di corsa.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 190,
 "ings": ["1 banana", "2 cucchiai di avena",
          "200 ml di latte (o bevanda vegetale)", "1 pizzico di cannella",
          "ghiaccio q.b."],
 "passos": [
   "Sbuccia la banana (se è molto matura, dolcifica di più).",
   "Frulla la banana, l'avena, il latte e la cannella nel frullatore per 1 minuto, finché non è cremoso.",
   "Servi subito, con un pizzico di cannella sopra. Se lo vuoi più freddo, aggiungi il ghiaccio e frulla di nuovo."],
 "porcoes8": V,
 "dica": "La banana con l'avena è una coppia che ti tiene sazia per ore grazie alle fibre, e il latte porta proteine. È un frullato che funziona come un pasto liquido completo — perfetto per la colazione o per uno spuntino quando hai fretta, senza bisogno di zucchero.",
},
{
 "nome": "Frullato di fragole con yogurt",
 "hook": "Rosa e cremoso, con la dolcezza naturale delle fragole — un frullato che sembra un milkshake, ma è leggero e pieno di proteine.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 150,
 "ings": ["150 g di fragole (fresche o congelate)",
          "1 vasetto di yogurt naturale senza zucchero (circa 170 g)",
          "100 ml di latte (o acqua)", "dolcificante q.b. (facoltativo)",
          "ghiaccio q.b."],
 "passos": [
   "Lava le fragole e togli le foglioline verdi.",
   "Frulla le fragole, lo yogurt e il latte nel frullatore per 1 minuto, finché non diventa una crema rosa e liscia.",
   "Assaggia e, se ti va, dolcifica un po'. Servi freddo."],
 "porcoes8": V,
 "dica": "Lo yogurt naturale porta proteine e cremosità senza zucchero, e le fragole dolcificano in modo naturale con pochissime calorie. È un frullato saziante e rinfrescante che toglie la voglia di milkshake in modo leggero e nutriente.",
},
{
 "nome": "Frullato di frutti di bosco misti",
 "hook": "Viola, pieno di antiossidanti e carico di sapore — un mix di frutti di bosco frullato cremoso, ottimo per la pelle e per la sazietà.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 140,
 "ings": ["140 g di frutti di bosco misti (fragola, mirtillo, lampone)",
          "1 vasetto di yogurt naturale senza zucchero",
          "100 ml di latte (o acqua)", "dolcificante q.b. (facoltativo)",
          "ghiaccio q.b."],
 "passos": [
   "Se i frutti di bosco sono congelati, usali direttamente dal freezer (rendono il frullato più freddo e più cremoso).",
   "Frulla i frutti di bosco, lo yogurt e il latte nel frullatore per 1 minuto, finché non diventa una crema liscia.",
   "Assaggia, dolcifica se ti va e servi subito."],
 "porcoes8": V,
 "dica": "I frutti di bosco sono campioni di antiossidanti, che combattono l'invecchiamento, e sono poveri di zucchero. Con lo yogurt, diventano un frullato cremoso e ricco di proteine che sazia ed è uno degli spuntini più sani che ci siano.",
},
{
 "nome": "Frullato verde con banana e spinaci",
 "hook": "Verde fuori, dolce dentro — la banana nasconde gli spinaci e consegna una bevanda cremosa e piena di nutrienti.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 160,
 "ings": ["1 banana", "1 manciata di spinaci", "½ mela a pezzi",
          "200 ml di latte (o acqua di cocco)", "ghiaccio q.b."],
 "passos": [
   "Lava bene gli spinaci.",
   "Frulla la banana, gli spinaci, la mela e il latte nel frullatore per 1 minuto, finché non è verde e cremoso.",
   "Servi subito, ben freddo."],
 "porcoes8": V,
 "dica": "È un modo delizioso di mangiare più foglie verdi: la banana e la mela dolcificano in modo naturale e nascondono gli spinaci, che arrivano pieni di ferro e fibre. Cremoso e saziante, funziona come una colazione liquida e nutriente.",
},
{
 "nome": "Frullato di avocado",
 "hook": "Estremamente cremoso e avvolgente, con il grasso buono dell'avocado — un frullato che sazia davvero e nutre la pelle.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 190,
 "ings": ["½ avocado maturo", "200 ml di latte (o bevanda vegetale)",
          "dolcificante q.b. — o 1 cucchiaino di miele",
          "1 pizzico di cannella o qualche goccia di limone", "ghiaccio q.b."],
 "passos": [
   "Preleva la polpa dell'avocado con un cucchiaio, usando solo la parte ben morbida.",
   "Frulla l'avocado, il latte e il dolcificante (o miele) nel frullatore per 1 minuto, finché non diventa una crema liscia e vellutata.",
   "Servi freddo, con un pizzico di cannella o qualche goccia di limone."],
 "porcoes8": V,
 "dica": "L'avocado ha grassi buoni che saziano molto e fanno bene al cuore e alla pelle. Frullato con il latte, diventa un frullato cremoso e nutriente che tiene a bada la fame per ore. Visto che è più calorico, è un'ottima opzione per uno spuntino in una porzione da un bicchiere.",
},
{
 "nome": "Frullato di mango con yogurt",
 "hook": "Tropicale, dorato e cremoso — il mango diventa un frullato dolce che sa di dessert e rinfresca subito.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 150,
 "ings": ["1 mango maturo a cubetti (o 165 g congelato)",
          "1 vasetto di yogurt naturale senza zucchero",
          "100 ml di latte (o acqua)", "ghiaccio q.b."],
 "passos": [
   "Sbuccia il mango e taglia la polpa a cubetti.",
   "Frulla il mango, lo yogurt e il latte nel frullatore per 1 minuto, finché non diventa una crema dorata e liscia.",
   "Servi ben freddo."],
 "porcoes8": V,
 "dica": "Il mango è naturalmente dolce e pieno di vitamina A e C, quindi non ha bisogno di zucchero. Con lo yogurt, il frullato guadagna proteine e cremosità, diventando uno spuntino rinfrescante e saziante — rispetta solo la porzione, visto che il mango è un frutto dolce.",
},
{
 "nome": "Frullato di pera con avena",
 "hook": "Delicato e gentile, la pera porta una dolcezza leggera all'avena cremosa — un frullato calmo e avvolgente.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 170,
 "ings": ["1 pera matura a pezzi", "2 cucchiai di avena",
          "200 ml di latte (o bevanda vegetale)", "1 pizzico di cannella",
          "ghiaccio q.b."],
 "passos": [
   "Lava la pera e tagliala a pezzi, togliendo il torsolo con i semi.",
   "Frulla la pera, l'avena, il latte e la cannella nel frullatore per 1 minuto, finché non è cremoso.",
   "Servi subito, con un pizzico di cannella sopra."],
 "porcoes8": V,
 "dica": "La pera è un frutto delicato pieno di fibre, e con l'avena fa un frullato che ti tiene sazia per un bel po'. Il latte aggiunge proteine. È una bevanda leggera e avvolgente, ottima per la colazione o per uno spuntino che tiene a bada la fame.",
},
{
 "nome": "Frullato di banana e cacao",
 "hook": "Il gusto del cioccolato in un frullato cremoso e senza zucchero — la risposta perfetta alla voglia di dolce del pomeriggio.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 180,
 "ings": ["1 banana", "1 cucchiaio di cacao amaro in polvere 100 %",
          "200 ml di latte (o bevanda vegetale)",
          "1 cucchiaino di burro di arachidi (facoltativo)", "ghiaccio q.b."],
 "passos": [
   "Sbuccia la banana (se è molto matura, dolcifica di più).",
   "Frulla la banana, il cacao, il latte e il burro di arachidi nel frullatore per 1 minuto, finché non diventa una crema liscia e cioccolatosa.",
   "Servi ben freddo, con il ghiaccio."],
 "porcoes8": V,
 "dica": "Il cacao puro dà il sapore del cioccolato senza zucchero, e la banana lo dolcifica e rende il frullato cremoso. È il modo più buono di togliere la voglia di cioccolato del pomeriggio in modo nutriente, con le fibre della frutta e le proteine del latte.",
},
{
 "nome": "Frullato di mela con cannella e avena",
 "hook": "Il sapore di una torta di mele in un bicchiere cremoso — avena, mela e cannella frullate in uno spuntino che consola.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 170,
 "ings": ["1 mela a pezzi", "2 cucchiai di avena",
          "200 ml di latte (o bevanda vegetale)", "1 cucchiaino di cannella",
          "ghiaccio q.b."],
 "passos": [
   "Taglia la mela a pezzi, togliendo i semi (puoi lasciare la buccia).",
   "Frulla la mela, l'avena, il latte e la cannella nel frullatore per 1 minuto e mezzo, finché non è cremoso e la mela non si è disfatta del tutto.",
   "Servi subito, con ancora un po' di cannella sopra."],
 "porcoes8": V,
 "dica": "La mela con la cannella e l'avena sa di dessert, ma insieme fanno un frullato pieno di fibre che ti tiene sazia per ore. La cannella aiuta a controllare la voglia di dolce. È uno spuntino cremoso, buono e leggero, senza nessuno zucchero aggiunto.",
},
{
 "nome": "Frullato di melone con menta",
 "hook": "Verde chiaro, dolce e ultra rinfrescante — il melone con la menta è pura idratazione in un frullato leggero.",
 "tempo": "5 min", "rende": "1 bicchiere grande", "kcal_base": 110,
 "ings": ["3 fette di melone senza buccia, a cubetti", "5 foglie di menta",
          "½ vasetto di yogurt naturale (o 100 ml di acqua)", "ghiaccio q.b."],
 "passos": [
   "Taglia il melone a cubetti, togliendo i semi.",
   "Frulla il melone, la menta e lo yogurt (o l'acqua) nel frullatore per 1 minuto, finché non è liscio.",
   "Servi ben freddo, con una foglia di menta."],
 "porcoes8": V,
 "dica": "Il melone è ricco di acqua e aiuta a idratarti e a sgonfiare, con pochissime calorie. Frullato con la menta è rinfrescante e leggero; con un po' di yogurt, guadagna cremosità e proteine. Un frullato perfetto per le giornate calde.",
},
{
 "nome": "Acqua detox con cetriolo, limone e menta",
 "hook": "L'acqua che ti fa venire voglia di bere: leggera, profumata e rinfrescante, per tenerti idratata tutto il giorno senza annoiarti.",
 "tempo": "5 min + frigo", "rende": "1 caraffa", "kcal_base": 10, "livre": True,
 "ings": ["1 litro di acqua", "½ cetriolo a rondelle sottili",
          "½ limone a rondelle", "6 foglie di menta", "ghiaccio q.b."],
 "passos": [
   "Lava il cetriolo, il limone e la menta.",
   "In una caraffa, metti l'acqua, le rondelle di cetriolo e limone e le foglie di menta.",
   "Metti in frigo per almeno 1 ora, così l'acqua prende il sapore. Servi fredda durante la giornata; puoi rabboccarla con altra acqua man mano che la bevi."],
 "dica": "Sostituire le bibite gassate e i succhi zuccherati con acqua aromatizzata è una delle abitudini che più aiutano a dimagrire. Cetriolo, limone e menta portano sapore senza calorie, rendendo l'acqua più buona e aiutandoti a restare idratata tutto il giorno.",
},
{
 "nome": "Acqua detox con zenzero e limone",
 "hook": "Un'acqua tiepida o fredda con un tocco piccante che sveglia il metabolismo appena alzata.",
 "tempo": "5 min", "rende": "1 bicchiere", "kcal_base": 8, "livre": True,
 "ings": ["1 bicchiere di acqua (tiepida o fredda)", "succo di ½ limone",
          "qualche fettina sottile di zenzero", "ghiaccio q.b. (se fredda)"],
 "passos": [
   "Taglia lo zenzero a fettine molto sottili.",
   "Mescola l'acqua, il succo di limone e lo zenzero in un bicchiere.",
   "Lascia riposare 5 minuti perché lo zenzero rilasci il suo sapore. Bevila la mattina, a digiuno, tiepida o fredda."],
 "dica": "Bere acqua con limone e zenzero a digiuno aiuta a svegliare il corpo e la digestione. Lo zenzero ha un leggero effetto termogenico (accelera un po' il metabolismo). Senza zucchero, è un semplice rituale mattutino che sostiene il dimagrimento.",
},
{
 "nome": "Acqua detox ai frutti di bosco",
 "hook": "Rosa e bellissima nella caraffa, con i frutti che galleggiano — un'acqua aromatizzata che sembra una bevanda da spa.",
 "tempo": "5 min + frigo", "rende": "1 caraffa", "kcal_base": 15, "livre": True,
 "ings": ["1 litro di acqua",
          "1 manciata di frutti di bosco (fragola, mirtillo, lampone)",
          "½ limone a rondelle", "foglie di menta", "ghiaccio q.b."],
 "passos": [
   "Lava i frutti di bosco e taglia le fragole a metà.",
   "In una caraffa, metti l'acqua, la frutta, le rondelle di limone e la menta. Schiaccia leggermente la frutta con un cucchiaio perché rilasci il colore e il sapore.",
   "Metti in frigo per 1-2 ore e servi fredda."],
 "dica": "I frutti di bosco portano colore, sapore e antiossidanti all'acqua con quasi zero calorie. È un modo bello e gustoso di bere più acqua durante la giornata, sostituendo le bevande zuccherate e aiutando l'idratazione e il dimagrimento.",
},
{
 "nome": "Acqua di cocco con limone e menta",
 "hook": "L'idratazione naturale dell'acqua di cocco, rinforzata con limone e menta — rinfrescante e piena di minerali.",
 "tempo": "3 min", "rende": "1 bicchiere grande", "kcal_base": 45, "livre": True,
 "ings": ["1 bicchiere grande di acqua di cocco", "succo di ½ limone",
          "5 foglie di menta", "ghiaccio q.b."],
 "passos": [
   "Mescola l'acqua di cocco con il succo di limone in un bicchiere.",
   "Aggiungi le foglie di menta e il ghiaccio e mescola.",
   "Servi ben fredda, meglio se quella naturale (l'acqua di cocco confezionata ha di solito zuccheri aggiunti — scegli quella naturale)."],
 "dica": "L'acqua di cocco reintegra i minerali e idrata benissimo, con poche calorie quando è naturale. Con limone e menta, è ancora più rinfrescante. È ottima dopo l'attività fisica o nelle giornate calde, al posto delle bevande sportive zuccherate.",
},
{
 "nome": "Tè verde con limone e zenzero",
 "hook": "L'alleato numero 1 di chi dimagrisce: il tè verde accelera il metabolismo, e limone e zenzero gli danno una spinta in più.",
 "tempo": "8 min", "rende": "1 tazza", "kcal_base": 5, "livre": True,
 "ings": ["240 ml di acqua", "1 cucchiaino di tè verde (o 1 bustina)",
          "qualche fettina di zenzero", "succo di ½ limone"],
 "passos": [
   "Porta a bollore l'acqua e spegni il fuoco. Aspetta 1 minuto (l'acqua troppo calda rende amaro il tè verde).",
   "Aggiungi il tè verde e le fettine di zenzero, copri e lascia in infusione per 3 minuti.",
   "Filtralo, aggiungi il succo di limone e bevilo caldo. Puoi berlo anche freddo, durante la giornata."],
 "dica": "Il tè verde è uno degli alimenti più studiati per il dimagrimento: contiene sostanze che aiutano ad accelerare il metabolismo e a bruciare grassi. Con zenzero e limone, l'effetto si rinforza. Senza zucchero, è una bevanda libera che puoi bere ogni giorno.",
},
{
 "nome": "Tè freddo all'ibisco",
 "hook": "Rosso rubino e leggermente acidulo, l'ibisco è famoso per aiutare a sgonfiare — delizioso freddo quando fa caldo.",
 "tempo": "10 min + frigo", "rende": "1 caraffa", "kcal_base": 5, "livre": True,
 "ings": ["1 litro di acqua",
          "2 cucchiai di fiori di ibisco secchi (o 2 bustine)",
          "rondelle di limone", "foglie di menta", "ghiaccio q.b."],
 "passos": [
   "Porta a bollore l'acqua e spegni. Aggiungi l'ibisco, copri e lascia in infusione per 5-7 minuti.",
   "Filtralo e fallo raffreddare. Mettilo in frigo.",
   "Servi ben freddo, con rondelle di limone, menta e ghiaccio."],
 "dica": "Il tè all'ibisco è noto per aiutare a ridurre la ritenzione idrica (il gonfiore) ed è ricco di antiossidanti. Freddo e senza zucchero, è una bevanda rinfrescante e libera, ottima per sostituire le bibite gassate e i succhi industriali durante la giornata.",
},
{
 "nome": "Tisana di camomilla con cannella",
 "hook": "Calda e avvolgente, la tisana che ti calma prima di dormire — e dormire bene aiuta anche a dimagrire.",
 "tempo": "8 min", "rende": "1 tazza", "kcal_base": 5, "livre": True,
 "ings": ["240 ml di acqua",
          "1 cucchiaio di fiori di camomilla (o 1 bustina)",
          "1 stecca di cannella (o 1 pizzico in polvere)"],
 "passos": [
   "Porta a bollore l'acqua e spegni il fuoco.",
   "Aggiungi la camomilla e la cannella, copri e lascia in infusione per 5 minuti.",
   "Filtrala e bevila calda, meglio la sera, prima di dormire."],
 "dica": "La camomilla calma e aiuta a rilassarsi, migliorando il sonno. Dormire bene è un fattore che molte persone dimenticano nel dimagrimento: le notti storte aumentano la fame e la voglia di dolce del giorno dopo. Questa tisana è un rituale serale che sostiene la tua dieta.",
},
{
 "nome": "Infuso di zenzero, limone e cannella",
 "hook": "Un infuso termogenico e profumato che scalda il corpo e dà al metabolismo quella spinta.",
 "tempo": "10 min", "rende": "1 tazza grande", "kcal_base": 8, "livre": True,
 "ings": ["300 ml di acqua", "diverse fettine di zenzero",
          "1 stecca di cannella", "succo di ½ limone"],
 "passos": [
   "In un pentolino, fai bollire l'acqua con le fettine di zenzero e la stecca di cannella per 5 minuti, a fuoco basso.",
   "Spegni, copri e lascia riposare per altri 3 minuti.",
   "Filtralo, aggiungi il succo di limone e bevilo caldo."],
 "dica": "Lo zenzero e la cannella hanno un leggero effetto termogenico, cioè aiutano il corpo a consumare un po' più di energia. È un infuso caldo e avvolgente, senza zucchero, che funziona bene nelle giornate fredde e dà al metabolismo quel sostegno in più.",
},
{
 "nome": "Tè alla menta con limone",
 "hook": "Fresco e utile alla digestione, il tè alla menta calma lo stomaco dopo i pasti — leggero e profumato.",
 "tempo": "8 min", "rende": "1 tazza", "kcal_base": 4, "livre": True,
 "ings": ["240 ml di acqua",
          "1 manciata di foglie fresche di menta (o 1 bustina)",
          "succo di ½ limone"],
 "passos": [
   "Porta a bollore l'acqua e spegni il fuoco.",
   "Aggiungi le foglie di menta, copri e lascia in infusione per 5 minuti.",
   "Filtralo, aggiungi il succo di limone e bevilo caldo o freddo, meglio dopo i pasti."],
 "dica": "La menta aiuta la digestione e riduce quella sensazione di stomaco pesante dopo aver mangiato. Una tisana digestiva senza zucchero dopo i pasti è un'abitudine semplice che ti aiuta a evitare di sgranocchiare dolci subito dopo.",
},
{
 "nome": "Tisana al finocchio",
 "hook": "Delicata e naturalmente dolce, il finocchio calma lo stomaco e riduce il gonfiore — una tisana avvolgente dopo mangiato.",
 "tempo": "8 min", "rende": "1 tazza", "kcal_base": 4, "livre": True,
 "ings": ["240 ml di acqua",
          "1 cucchiaino di semi di finocchio — o 1 bustina"],
 "passos": [
   "Schiaccia leggermente i semi di finocchio (così rilasciano più aroma).",
   "Porta a bollore l'acqua e spegni. Aggiungi il finocchio, copri e lascia in infusione per 5 minuti.",
   "Filtrala e bevila calda, meglio dopo i pasti o la sera."],
 "dica": "Il finocchio è noto per calmare lo stomaco e ridurre i gas e il gonfiore addominale. Naturalmente dolce, non ha bisogno di zucchero. È una tisana digestiva e avvolgente, ottima per chiudere un pasto in modo leggero.",
},
]
