# -*- coding: utf-8 -*-
"""DESSERT recipes (101-120). English (US market). All FIT and SUGAR-FREE.
Sweetened with fruit, a touch of honey (optional) or baking sweetener (heat-stable).
porcoes8 order: Woman 120-155/155-185/185-220/220+ lb · Man 155-185/185-220/220-265/265+ lb
Targets (cal): 120/150/170/190 · 180/200/230/260 (small dessert portions)
Includes the CHOCOLATE CAKE (101), requested on the landing. US units: cups/tbsp/tsp/oz/°F.
"""

RECEITAS = [
{
 "nome": "Sugar-Free Fit Chocolate Cake",
 "hook": "Fluffy, moist and deeply chocolatey — the cake that beats the sweet craving with no pinch of sugar, made with real cocoa.",
 "tempo": "40 min", "rende": "8 slices", "kcal_base": 150,
 "ings": ["3 eggs", "1 very ripe banana, mashed", "4 tablespoons 100% cocoa powder (unsweetened)",
          "5 tablespoons oats blended into flour (or whole-wheat flour)",
          "baking sweetener to taste (heat-stable) — or 2 tablespoons honey",
          "½ cup milk (or plant milk)", "1 tablespoon oil", "1 teaspoon baking powder"],
 "passos": [
   "Turn the oven to medium heat (350°F). Grease a small pan with a little oil and dust with a bit of cocoa, so the cake does not stick.",
   "In a bowl, beat the eggs with the sweetener (or honey) using a fork or whisk, for 1 minute, until foamy.",
   "Add the mashed banana, the milk and the oil and mix well.",
   "Add the cocoa powder and the blended oats (or flour) and stir into a smooth batter, with no dry spots.",
   "Last, add the baking powder and stir gently, just to combine (over-mixing after the baking powder makes the cake heavy).",
   "Pour into the pan and bake for 30 minutes. To check it is done, poke a toothpick in the center: if it comes out clean, the cake is baked.",
   "Let it cool a little before unmolding and slicing. It is great with berries on top."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice · berries",
              "1 slice · 1 tbsp yogurt",
              "1 slice",
              "1 medium slice",
              "1 slice · berries",
              "1 large slice · fruit"],
 "dica": "Pure cocoa gives all the chocolate flavor without the sugar and fat of chocolate mixes. Banana sweetens naturally and keeps the cake moist, the oats bring fiber and the eggs protein. It is proof you can eat chocolate cake and keep losing weight, as long as it is the right slice.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of moist dark chocolate cake on a white plate, topped with a few fresh raspberries, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chocolate Avocado Mousse",
 "hook": "Creamy like the traditional mousse, but the secret is avocado — no one guesses, and it has no heavy cream and no sugar.",
 "tempo": "10 min + fridge", "rende": "2 glasses", "kcal_base": 170,
 "ings": ["1 ripe avocado (or ½ large avocado)", "3 tablespoons 100% cocoa powder",
          "baking sweetener to taste — or 2 tablespoons honey", "3 tablespoons milk (or plant milk)",
          "1 pinch of cinnamon", "1 pinch of salt", "70% chocolate shavings to garnish (optional)"],
 "passos": [
   "Cut the avocado in half, remove the pit and scoop out the flesh with a spoon. Use only the very soft, green part.",
   "Put the avocado flesh in a blender or the mixer cup, along with the cocoa, the sweetener (or honey), the milk, the cinnamon and the salt.",
   "Blend on high until it becomes a smooth, glossy cream, with no lumps. If it is too thick, add a bit more milk.",
   "Taste and adjust the sweetness to your liking.",
   "Divide into two glasses and refrigerate for at least 30 minutes, to set and chill. Serve with chocolate shavings on top."],
 "porcoes8": ["½ small glass",
              "1 small glass",
              "1 glass",
              "1 glass · chocolate shavings",
              "1 glass",
              "1 medium glass",
              "1 glass · chocolate shavings",
              "1 large glass · shavings"],
 "dica": "Avocado gives the mousse its creaminess with good fat instead of heavy cream, and it is very filling. Pure cocoa brings the chocolate flavor with no sugar. It is a rich, satisfying dessert that, in a small portion, fits easily in your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy dark chocolate avocado mousse in a small glass, topped with chocolate shavings and a mint leaf, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Cocoa Fudge Balls",
 "hook": "The party fudge ball in a version with no sugar and no condensed milk — rolled up, chocolatey and just the right size for the craving.",
 "tempo": "20 min + fridge", "rende": "10 balls", "kcal_base": 130,
 "ings": ["6 pitted dates (that sweet dried fruit)", "3 tablespoons 100% cocoa powder",
          "2 tablespoons milk (or plant milk)", "1 tablespoon peanut butter",
          "extra cocoa powder for rolling", "1 pinch of salt"],
 "passos": [
   "Soak the dates in warm water for 10 minutes, to soften them. Drain.",
   "In the mixer cup or blender, blend the dates with the cocoa, the milk, the peanut butter and the salt, into a thick, smooth dough. If needed, stop and push the mixture to the center with a spoon.",
   "The dough should be firm enough to roll. If it is soft, refrigerate for 20 minutes.",
   "With lightly moistened hands, take small portions and roll walnut-sized balls.",
   "Roll each ball in cocoa powder to coat. Keep in the fridge and serve chilled."],
 "porcoes8": ["1 ball",
              "1 to 2 balls",
              "2 balls",
              "2 balls",
              "2 balls",
              "2 to 3 balls",
              "3 balls",
              "3 balls"],
 "dica": "Dates replace sugar and condensed milk with a natural sweetness and lots of fiber, which holds the sweet craving. Pure cocoa gives the chocolate flavor and the peanut butter the creaminess. One or two balls beat the craving without blowing your calories.",
 "prompt": "Square ultra-realistic overhead food photograph of several dark chocolate energy balls rolled in cocoa powder on a small white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chocolate Mug Cake",
 "hook": "Did the sweet craving hit at night? In three minutes, in the microwave, you have a warm little chocolate cake just for you.",
 "tempo": "5 min", "rende": "1 mug", "kcal_base": 190,
 "ings": ["1 egg", "2 tablespoons oats blended into flour", "1 tablespoon 100% cocoa powder",
          "baking sweetener to taste — or 1 tablespoon honey", "2 tablespoons milk",
          "½ teaspoon baking powder", "1 pinch of salt"],
 "passos": [
   "In a large (microwave-safe) mug, crack the egg and beat with a fork.",
   "Add the blended oats, the cocoa, the sweetener (or honey), the milk and the salt. Mix well, into a smooth batter, with no dry spots at the edges.",
   "Last, add the baking powder and stir gently.",
   "Microwave the mug on high (full power) for 1 minute 30 seconds to 2 minutes. The cake rises and sets; if it is still wet in the center, add 20 more seconds.",
   "Careful, the mug comes out hot. Let it cool 1 minute and eat it in the mug. It is great with fruit on top."],
 "porcoes8": ["½ mug",
              "1 small mug",
              "1 mug",
              "1 mug · fruit",
              "1 mug",
              "1 mug",
              "1 mug · fruit",
              "1 mug · fruit · 1 tbsp peanut butter"],
 "dica": "Made fresh and in a single-mug portion, this cake naturally controls how much you eat — there is no whole cake tempting you on the table. With oats, egg and pure cocoa, it is sweet, warm and comforting with no sugar, ideal for the night-time craving.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm chocolate mug cake in a ceramic mug, topped with a few raspberries, a spoon beside it, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Strawberry Yogurt Mousse",
 "hook": "Pink, velvety and refreshing — a strawberry mousse with just three ingredients and no sugar.",
 "tempo": "10 min + fridge", "rende": "3 glasses", "kcal_base": 120,
 "ings": ["2 cups strawberries (fresh or frozen)", "1 cup (8 oz) plain unsweetened yogurt",
          "1 tablespoon unflavored gelatin", "sweetener to taste — or 1 tablespoon honey",
          "3 tablespoons hot water", "chopped strawberries to garnish"],
 "passos": [
   "Wash the strawberries and remove the green tops. Keep a few for garnish.",
   "In a cup, dissolve the unflavored gelatin in the hot water, stirring well until clear, with no grains. Let it cool a little.",
   "In the blender, blend the strawberries with the yogurt and the sweetener (or honey) into a smooth, pink cream.",
   "With the blender running on low speed, add the dissolved gelatin and blend 30 more seconds, just to mix.",
   "Divide into glasses and refrigerate for at least 2 hours, until set. Serve with chopped strawberries on top."],
 "porcoes8": ["½ glass",
              "1 small glass",
              "1 glass",
              "1 glass · strawberries",
              "1 glass",
              "1 medium glass",
              "1 glass · strawberries",
              "1 large glass · strawberries"],
 "dica": "Strawberry is sweet and full of vitamin C for very few calories, and plain yogurt adds protein and creaminess with no sugar. The gelatin gives the mousse texture with no heavy cream. A light, pretty, refreshing dessert that satisfies the sweet craving.",
 "prompt": "Square ultra-realistic overhead food photograph of a pink strawberry yogurt mousse in a glass, topped with fresh chopped strawberries and a mint leaf, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Creamy Banana Nice Cream",
 "hook": "A real ice cream, creamy and cold, made with just banana — no sugar, no milk, no ice cream machine.",
 "tempo": "5 min + freezer", "rende": "2 servings", "kcal_base": 120,
 "ings": ["3 ripe bananas", "1 tablespoon 100% cocoa powder OR 1 handful of berries (optional, for flavor)",
          "1 pinch of cinnamon", "1 teaspoon peanut butter (optional)"],
 "passos": [
   "Peel the bananas, cut into rounds and put in a bag or container. Freeze for at least 3 hours, until very hard.",
   "Take out the frozen rounds and put them in a powerful blender or the mixer cup.",
   "Blend on high. At first it turns to little pieces; keep blending (stopping to push the banana to the center) until it becomes a smooth cream, like machine ice cream.",
   "If you want flavor, add the cocoa or the berries and blend a bit more.",
   "Serve right away, nice and creamy, with a pinch of cinnamon — or freeze for 1 hour to make it firmer, like tub ice cream."],
 "porcoes8": ["½ serving",
              "1 small serving",
              "1 serving",
              "1 serving · 1 tsp peanut butter",
              "1 serving",
              "1 medium serving",
              "1 serving · fruit",
              "1 large serving · fruit · peanut butter"],
 "dica": "Frozen and blended, the banana releases its own natural sugar and turns into a cream just like ice cream, with no need for sugar, milk or cream. It is sweet, cold and satisfying, with the fiber and potassium of the fruit — the perfect dessert for hot days, with no guilt.",
 "prompt": "Square ultra-realistic overhead food photograph of a scoop of creamy banana nice cream in a bowl, dusted with cinnamon, a few banana slices beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Milk Flan",
 "hook": "The creamy flan you know, with that golden caramel — only with no sugar and much lighter, made with milk and eggs.",
 "tempo": "50 min", "rende": "6 slices", "kcal_base": 130,
 "ings": ["3 eggs", "2 cups skim milk (or plant milk)", "baking sweetener to taste (heat-stable)",
          "1 teaspoon vanilla extract", "caramel-type baking sweetener (optional, for the topping)",
          "hot water for the water bath"],
 "passos": [
   "Turn the oven to medium heat (350°F). If you want caramel, melt a little caramel-type sweetener in a mold and spread it on the bottom (or skip the caramel).",
   "In the blender, blend the eggs, the milk, the sweetener and the vanilla for 1 minute, until well combined.",
   "Pour the mixture into the mold.",
   "Put the mold inside a larger baking dish and fill the dish with hot water halfway up the height of the mold (this is the water bath: the water makes the flan bake evenly and stay creamy).",
   "Bake for 40 minutes, until set but still slightly wobbly in the center. Let it cool and then refrigerate for 3 hours before unmolding."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · fruit",
              "1 slice",
              "1 medium slice",
              "1 slice · fruit",
              "1 large slice · fruit"],
 "dica": "Swapping condensed milk and sugar for skim milk and sweetener, the flan keeps its creaminess and flavor with a fraction of the calories. The eggs and milk still give protein. In a small slice, it is a classic dessert that fits your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of creamy milk flan with a light golden caramel on top, on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oatmeal Banana Cookies",
 "hook": "Two ingredients, one bowl and twenty minutes: soft, sweet little cookies, with no sugar and no white flour.",
 "tempo": "20 min", "rende": "12 cookies", "kcal_base": 110,
 "ings": ["2 very ripe bananas", "1½ cups rolled oats", "1 pinch of cinnamon",
          "1 tablespoon raisins or 70% chocolate chips (optional)", "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350°F). Line a tray with parchment paper.",
   "In a bowl, mash the bananas well with a fork, into a purée with no big lumps.",
   "Add the oats, the cinnamon, the salt and, if you like, the raisins or chopped chocolate. Mix into a sticky dough.",
   "With a spoon, place small portions on the tray and flatten each with the back of the spoon, giving it a cookie shape.",
   "Bake for 12 to 15 minutes, until the edges are golden and firm. Let cool on the tray (they firm up as they cool) and serve."],
 "porcoes8": ["1 cookie",
              "2 cookies",
              "2 cookies",
              "2 cookies · fruit",
              "2 cookies",
              "3 cookies",
              "3 cookies",
              "3 to 4 cookies"],
 "dica": "Ripe banana sweetens and binds with no need for sugar or white flour, and the oats bring filling fiber. They are natural cookies, great for a snack or dessert, that beat the sweet craving in a light way — but count how many you eat, because they are easy to overdo.",
 "prompt": "Square ultra-realistic overhead food photograph of several soft oatmeal banana cookies on a wooden board, with a few oats and raisins scattered around, soft natural light, homemade and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Baked Apple with Cinnamon and Walnuts",
 "hook": "The apple turns soft and fragrant with cinnamon, with a crunchy walnut filling — a warm dessert that comforts like a pie, without the crust.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 130,
 "ings": ["2 apples", "ground cinnamon to taste", "1 tablespoon chopped walnuts (or other nuts)",
          "1 tablespoon rolled oats", "1 teaspoon honey (optional)", "1 pinch of ground cloves (optional)"],
 "passos": [
   "Turn the oven to medium heat (350°F). Wash the apples and, with a knife, remove the core from the center (the seed part), forming a hole, without piercing all the way through.",
   "In a small bowl, mix the chopped walnuts, the oats, the cinnamon and, if you like, the honey and the cloves.",
   "Fill the hole of each apple with this mixture, pressing lightly.",
   "Put the apples in a baking dish with a finger of water on the bottom (so they do not dry out) and dust more cinnamon on top.",
   "Bake for 25 to 30 minutes, until the apple is very soft (a fork goes in easily) and the filling golden. Serve warm, on its own or with a spoon of plain yogurt."],
 "porcoes8": ["½ apple",
              "1 apple",
              "1 apple",
              "1 apple · 1 tbsp yogurt",
              "1 apple",
              "1 apple · extra walnuts",
              "1 apple · yogurt",
              "2 apples · yogurt"],
 "dica": "Baking the apple concentrates the fruit's natural sweetness, so it turns sweet with no sugar. Cinnamon lifts the flavor and helps control the sweet craving, and the walnuts add good fat and crunch. It is the comfort of an apple pie with a fraction of the calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked apple filled with oats and chopped walnuts, dusted with cinnamon, on a small plate with a spoon, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Homemade Fruit Jelly",
 "hook": "Colorful, wobbly and refreshing, with real pieces of fruit inside — the lightest dessert there is.",
 "tempo": "10 min + fridge", "rende": "4 glasses", "kcal_base": 70,
 "ings": ["1 tablespoon unflavored gelatin", "2 cups natural fruit juice, unsweetened (orange, grape or strawberry)",
          "½ cup water", "1 cup chopped fruit (strawberry, kiwi, mango or grapes)", "sweetener to taste (optional)"],
 "passos": [
   "In a small pot, put the water and sprinkle the unflavored gelatin on top. Let it rest 2 minutes (the gelatin swells, which is called blooming).",
   "Set over low heat and stir for 1 minute, just until the gelatin dissolves completely, without boiling. Turn off.",
   "Add the natural fruit juice (and the sweetener, if you like) and mix well.",
   "Put the chopped fruit in the bottom of glasses or a dish and pour the liquid on top.",
   "Refrigerate for at least 4 hours, until firm. Serve well chilled."],
 "porcoes8": ["½ glass",
              "1 small glass",
              "1 glass",
              "1 glass · extra fruit",
              "1 glass",
              "1 medium glass",
              "1 glass · fruit",
              "1 large glass · fruit"],
 "dica": "Made with natural juice instead of the powder full of sugar and dye, homemade jelly is practically calorie-free and even has real pieces of fruit. It is the ideal dessert for when the craving for something sweet and cold hits, without weighing on your diet at all.",
 "prompt": "Square ultra-realistic overhead food photograph of colorful homemade fruit jelly in a glass with pieces of strawberry, kiwi and grapes suspended inside, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Oat and Dried Fruit Bars",
 "hook": "The homemade cereal bar, chewy and sweet, without the sugars and syrups of the store-bought ones — perfect for your bag.",
 "tempo": "30 min", "rende": "8 bars", "kcal_base": 150,
 "ings": ["2 cups rolled oats", "2 ripe bananas, mashed", "3 tablespoons chopped dried fruit (raisins, apricot or dates)",
          "2 tablespoons chopped nuts", "1 tablespoon honey (optional)", "1 pinch of cinnamon and salt"],
 "passos": [
   "Turn the oven to medium heat (350°F). Line a small rectangular pan with parchment paper.",
   "In a bowl, mash the bananas well into a purée.",
   "Add the oats, the chopped dried fruit, the nuts, the cinnamon, the salt and, if you like, the honey. Mix into a sticky, even dough.",
   "Pour the dough into the pan and press well with the back of a spoon, leaving a firm, even layer (the tighter it is, the less the bar crumbles).",
   "Bake for 20 minutes, until the edges are golden. Let it cool completely in the pan before cutting into bars (if you cut it warm, it crumbles)."],
 "porcoes8": ["1 bar",
              "1 bar",
              "1 bar",
              "1 bar · fruit",
              "1 bar",
              "1 to 2 bars",
              "2 bars",
              "2 bars"],
 "dica": "Supermarket bars often have more sugar and syrup than a candy. Made at home with oats, banana and dried fruit, the bar sweetens naturally and brings fiber and energy that hold hunger. Great for a snack or a practical dessert, but eat one at a time.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade oat and dried fruit granola bars stacked on a wooden board, with oats, raisins and nuts scattered around, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Frozen Yogurt Bark with Berries",
 "hook": "A crunchy sheet of frozen yogurt scattered with fruit, that you break into pieces — pretty, fun and sugar-free.",
 "tempo": "5 min + freezer", "rende": "4 servings", "kcal_base": 100,
 "ings": ["1 large tub of plain unsweetened Greek yogurt (about 1½ cups / 12 oz)", "1 cup berries (strawberry, blueberry, raspberry)",
          "1 tablespoon honey (optional)", "1 tablespoon chopped nuts (optional)", "70% chocolate shavings (optional)"],
 "passos": [
   "Line a tray or shallow dish with parchment paper.",
   "In a bowl, mix the Greek yogurt with the honey (if using), until smooth.",
   "Spread the yogurt over the parchment, forming a layer about half a finger thick.",
   "Scatter the berries (cut the strawberries), the nuts and the chocolate shavings on top, spreading over the whole surface.",
   "Freeze for 3 to 4 hours, until very hard. Break or cut into irregular pieces and serve right away (it melts fast). Keep the rest in the freezer."],
 "porcoes8": ["1 small piece",
              "1 piece",
              "1 to 2 pieces",
              "2 pieces",
              "2 pieces",
              "2 pieces",
              "2 to 3 pieces",
              "3 pieces"],
 "dica": "Greek yogurt brings protein and creaminess with no sugar, and frozen it becomes a cold, crunchy treat. The berries sweeten naturally and load it with antioxidants. It is a refreshing, light dessert, great for summer and for the urge to nibble something sweet.",
 "prompt": "Square ultra-realistic overhead food photograph of frozen yogurt bark broken into pieces, topped with berries, chopped nuts and dark chocolate shavings, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Chocolate Truffles",
 "hook": "Small, intense and chocolatey — the truffle that melts in your mouth with no sugar at all, for moments of strong craving.",
 "tempo": "20 min + fridge", "rende": "10 truffles", "kcal_base": 120,
 "ings": ["3.5 oz 70% chocolate (or darker)", "4 tablespoons hot milk (or plant milk)",
          "2 tablespoons unsweetened shredded coconut", "100% cocoa powder for rolling", "1 pinch of salt"],
 "passos": [
   "Chop the 70% chocolate into small pieces and put it in a bowl.",
   "Heat the milk until almost boiling and pour it over the chocolate. Wait 1 minute and stir until the chocolate melts completely, into a smooth, glossy cream (this is ganache).",
   "Add the shredded coconut and the salt and mix. Refrigerate for 1 hour, until the mixture is firm enough to roll.",
   "With your hands, take small portions and roll balls the size of a large olive.",
   "Roll each truffle in cocoa powder to coat. Keep in the fridge and serve chilled."],
 "porcoes8": ["1 truffle",
              "1 truffle",
              "1 to 2 truffles",
              "2 truffles",
              "2 truffles",
              "2 truffles",
              "2 to 3 truffles",
              "3 truffles"],
 "dica": "70% or darker chocolate has little sugar and lots of cocoa, which is rich in antioxidants. In a small truffle, it satisfies the intense chocolate craving with far less sugar than a regular candy. One or two settle the craving without sabotaging your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of dark chocolate truffles rolled in cocoa powder on a small dark plate, one cut in half showing the smooth center, on a light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fit Carrot Cake with Cocoa Glaze",
 "hook": "The fluffy carrot cake of childhood, with a chocolate glaze — no sugar, but all the love and flavor.",
 "tempo": "45 min", "rende": "8 slices", "kcal_base": 160,
 "ings": ["2 medium carrots, chopped", "3 eggs", "3 tablespoons oil", "baking sweetener to taste (heat-stable)",
          "1½ cups oats blended into flour (or whole-wheat flour)", "1 teaspoon baking powder",
          "Glaze: 2 tablespoons 100% cocoa powder + 2 tablespoons milk + sweetener to taste"],
 "passos": [
   "Turn the oven to medium heat (350°F). Grease a pan with a little oil and dust with a bit of flour.",
   "In the blender, blend the chopped carrots, the eggs, the oil and the sweetener into a smooth, orange cream.",
   "Move to a bowl, add the blended oats (or flour) and mix. Last, add the baking powder and stir gently.",
   "Pour into the pan and bake for 30 minutes, until a toothpick poked in the center comes out clean.",
   "Make the glaze: in a small pot, mix the cocoa, the milk and the sweetener and heat over low heat for 2 minutes, stirring, into a glossy cream. Spread over the still-warm cake."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · fruit",
              "1 slice",
              "1 medium slice",
              "1 slice · fruit",
              "1 large slice"],
 "dica": "Carrot keeps the cake moist and naturally sweet, and adds vitamin A. Swapping sugar for sweetener and white flour for oats, the cake stays light and full of fiber. The pure cocoa glaze gives the chocolate touch without the sugar of a traditional frosting.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of carrot cake with a dark chocolate glaze on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Lemon Mousse",
 "hook": "Just the right amount of tart, creamy and cold — a refreshing lemon mousse that cleans the palate and has no sugar.",
 "tempo": "10 min + fridge", "rende": "3 glasses", "kcal_base": 120,
 "ings": ["1 cup (8 oz) plain unsweetened yogurt", "juice of 2 lemons", "zest of 1 lemon",
          "1 tablespoon unflavored gelatin", "3 tablespoons hot water",
          "sweetener to taste — or 2 tablespoons honey"],
 "passos": [
   "Wash 1 lemon well and grate the zest from only the yellow part of the peel (the white part is bitter). Squeeze the 2 lemons for the juice.",
   "In a cup, dissolve the unflavored gelatin in the hot water, stirring until clear. Let it cool a little.",
   "In a bowl, mix the yogurt, the lemon juice, the zest and the sweetener (or honey), until creamy.",
   "Add the dissolved gelatin and mix well and fast, so it does not form little lumps.",
   "Divide into glasses and refrigerate for at least 2 hours, until set. Serve chilled, with more lemon zest on top."],
 "porcoes8": ["½ glass",
              "1 small glass",
              "1 glass",
              "1 glass · fruit",
              "1 glass",
              "1 medium glass",
              "1 glass · fruit",
              "1 large glass · fruit"],
 "dica": "Lemon gives freshness and a bold flavor that tricks the sweet craving with little need for sweetener. Plain yogurt brings protein and creaminess, and the gelatin sets the mousse with no heavy cream. A light, refreshing dessert, close to zero fat.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy lemon mousse in a glass, topped with lemon zest and a thin lemon slice, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "No-Bake Fit Berry Cheesecake",
 "hook": "Creamy, with a crunchy base and a fruit topping, put together with no oven — the cheesecake of dreams in a light, sugar-free version.",
 "tempo": "20 min + fridge", "rende": "6 slices", "kcal_base": 170,
 "ings": ["Base: 1 cup oats + 1 mashed banana + 1 teaspoon cinnamon",
          "Cream: 1 cup ricotta (or cottage) + ½ cup plain yogurt + sweetener to taste + juice of ½ lemon",
          "1 tablespoon unflavored gelatin + 3 tablespoons hot water",
          "Topping: 1 cup berries + sweetener to taste"],
 "passos": [
   "Base: mix the oats, the mashed banana and the cinnamon into a dough. Press it into the bottom of a small pan (preferably a springform), forming a firm layer. Freeze for 10 minutes.",
   "Dissolve the gelatin in the hot water, stirring until clear. Let it cool a little.",
   "Cream: in the blender, blend the ricotta, the yogurt, the sweetener and the lemon juice into a very smooth cream. Add the gelatin and blend 20 more seconds.",
   "Pour the cream over the base and smooth the surface. Refrigerate for at least 3 hours, until set.",
   "Topping: in a small pot, cook the berries with the sweetener over low heat for 5 minutes, mashing a little, into a jam. Let it cool and spread over the cheesecake before serving."],
 "porcoes8": ["1 thin slice",
              "1 slice",
              "1 slice",
              "1 slice · extra topping",
              "1 slice",
              "1 medium slice",
              "1 slice · topping",
              "1 large slice · topping"],
 "dica": "Ricotta and cottage give the creaminess of cream cheese with much less fat and more protein. The oat and banana base replaces the buttery cookie crust, and the cooked fruit topping skips the sugar. A real cheesecake that fits your diet, in a controlled slice.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of no-bake cheesecake with an oat base and a glossy red berry topping, on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Homemade Fruit Popsicles",
 "hook": "Refreshing and full of real fruit, these homemade popsicles are the perfect dessert for the heat — and not a drop of sugar.",
 "tempo": "10 min + freezer", "rende": "6 popsicles", "kcal_base": 60,
 "ings": ["2 cups chopped fruit (strawberry, mango, kiwi or watermelon)", "1 cup natural unsweetened juice (or coconut water)",
          "1 tub of plain unsweetened yogurt (optional, for creamy popsicles)", "sweetener to taste (optional)",
          "popsicle molds and sticks"],
 "passos": [
   "Chop the fruit into small pieces, so it fits in the molds.",
   "Choose the style: for fruit popsicles, use just the fruit and the natural juice; for creamy popsicles, blend the fruit with the yogurt.",
   "Put a few pieces of fruit in the bottom of each mold (it looks pretty) and top with the juice or the blended cream, leaving a finger of space at the top (the liquid expands as it freezes).",
   "Push a stick into the center of each popsicle.",
   "Freeze for at least 5 hours, until very firm. To unmold, run the mold quickly under warm water."],
 "porcoes8": ["1 popsicle",
              "1 popsicle",
              "1 popsicle",
              "1 to 2 popsicles",
              "1 popsicle",
              "1 to 2 popsicles",
              "2 popsicles",
              "2 popsicles"],
 "dica": "Store-bought popsicles are almost just water, sugar and dye. Made at home with real fruit and natural juice, the popsicle becomes a refreshing dessert full of vitamins and practically no calories — the best way to beat the craving for something cold in the heat, with no guilt.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade fruit popsicles with visible pieces of strawberry, mango and kiwi, on a plate with ice, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Apple Cinnamon Muffins",
 "hook": "Fluffy, fragrant and with pieces of apple — afternoon muffins that feel like a sin, but are light and sugar-free.",
 "tempo": "35 min", "rende": "6 muffins", "kcal_base": 140,
 "ings": ["2 eggs", "1 grated apple + ½ apple, diced", "1½ cups oats blended into flour",
          "3 tablespoons oil", "baking sweetener to taste (heat-stable)", "½ cup milk",
          "1 teaspoon cinnamon", "1 teaspoon baking powder", "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350°F). Line a muffin tin with paper liners (or grease the cups with a little oil).",
   "In a bowl, beat the eggs with the sweetener and the oil for 1 minute. Add the milk and the grated apple and mix.",
   "Add the blended oats, the cinnamon and the salt and stir into an even batter. Add the diced apple and the baking powder and mix gently.",
   "Divide the batter into the liners, filling two-thirds full (they rise).",
   "Bake for 20 to 25 minutes, until golden and a poked toothpick comes out clean. Let cool a little and serve."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 tbsp yogurt",
              "1 muffin",
              "1 to 2 muffins",
              "2 muffins",
              "2 muffins"],
 "dica": "Grated apple keeps the muffins moist and naturally sweet, with no need for sugar. The oats bring filling fiber and the cinnamon lifts the fruit's sweetness. They are great for a snack or dessert, in a single-muffin portion, beating the bakery craving in a light way.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade apple cinnamon muffins in paper liners on a wooden board, one broken open showing apple pieces, dusted with cinnamon, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Apple Oat Crumble",
 "hook": "Soft apple underneath, a crunchy oat crumble on top — the coziness of a warm pie, put together in minutes and with no sugar.",
 "tempo": "40 min", "rende": "4 servings", "kcal_base": 160,
 "ings": ["3 apples, cubed", "juice of ½ lemon", "1 teaspoon cinnamon",
          "Crumble: 1 cup rolled oats + 2 tablespoons chopped nuts + 2 tablespoons coconut oil (or regular oil) + sweetener to taste",
          "1 pinch of salt"],
 "passos": [
   "Turn the oven to medium heat (350°F). In a bowl, mix the apple cubes with the lemon juice and the cinnamon and spread on the bottom of a baking dish.",
   "Make the crumble: in another bowl, mix the oats, the nuts, the oil, the sweetener and the salt, rubbing with your fingertips until it forms a moist, clumpy crumble.",
   "Spread the crumble over the apples, covering the whole surface.",
   "Bake for 25 to 30 minutes, until the apple bubbles at the edges and the crumble is golden and crunchy.",
   "Let it cool 5 minutes and serve. It is delicious with a spoon of plain yogurt or banana nice cream on top."],
 "porcoes8": ["½ serving",
              "1 small serving",
              "1 serving",
              "1 serving · yogurt",
              "1 serving",
              "1 medium serving",
              "1 serving · yogurt",
              "1 large serving · yogurt"],
 "dica": "The baked apple releases its own sweetness, and cinnamon reinforces the flavor with no sugar. The oat and nut crumble gives the crunch of a pie with fiber and good fat instead of butter and white flour. It is the comfort of a warm oven dessert, in the right portion.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm apple oat crumble in a small dish, golden crunchy topping over soft baked apples, a spoon lifting a portion, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Spiced Baked Pears",
 "hook": "The pear turns soft and juicy, fragrant with cinnamon and cloves — an elegant, warm dessert, sweet from the fruit alone.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 110,
 "ings": ["2 firm pears", "cinnamon stick (or ground)", "2 cloves", "orange zest (optional)",
          "1 teaspoon honey (optional)", "1 tablespoon chopped walnuts or almonds"],
 "passos": [
   "Turn the oven to medium heat (350°F). Wash the pears, cut them in half lengthwise and remove the core from the center with a small spoon, making a hollow.",
   "Put the pear halves in a baking dish, cut-side up. Dust cinnamon on top and put a clove and a bit of orange zest in each hollow.",
   "If you like, drip a few drops of honey on each pear.",
   "Put a finger of water on the bottom of the dish (so they do not dry out) and bake for 25 minutes, until the pear is very soft (a fork goes in easily).",
   "Remove the cloves, sprinkle the chopped nuts on top and serve warm, on its own or with a spoon of plain yogurt."],
 "porcoes8": ["1 half",
              "1 pear (2 halves)",
              "1 pear",
              "1 pear · yogurt",
              "1 pear",
              "1 pear · extra nuts",
              "1 pear · yogurt",
              "2 pears · yogurt"],
 "dica": "Baking the pear concentrates the fruit's natural sugar, making it sweet with no added sugar. The spices give a comforting aroma that satisfies the palate, and the nuts add good fat and crunch. A warm, light and sophisticated dessert.",
 "prompt": "Square ultra-realistic overhead food photograph of baked pear halves with cinnamon, cloves and chopped nuts, on a small plate, on a light wooden table, soft natural light, elegant and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
]
