# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). Português. Todas FIT e SEM AÇÚCAR.
Adoça com fruta, um toque de mel (opcional) ou adoçante culinário (o próprio para forno).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+  ·  Homem 70-85/86-100/101-120/120+
Metas (kcal): 120/150/170/190  ·  180/200/230/260  (porções pequenas de sobremesa)
Inclui o BOLO DE CHOCOLATE (101), pedido na landing. Cada receita tem 'prompt' = foto quadrada.
"""

RECEITAS = [
{
 "nome": "Bolo de Chocolate Fit sem Açúcar",
 "hook": "Fofo, úmido e bem chocolatudo — o bolo que mata a vontade de doce sem uma pitada de açúcar, feito com cacau de verdade.",
 "tempo": "40 min", "rende": "8 fatias", "kcal_base": 150,
 "ings": ["3 ovos", "1 banana bem madura amassada", "4 colheres de sopa de cacau em pó 100% (sem açúcar)",
          "5 colheres de sopa de aveia batida virada farinha (ou farinha de trigo integral)",
          "adoçante culinário a gosto (o próprio para forno) — ou 2 colheres de sopa de mel",
          "½ xícara de leite (ou bebida vegetal)", "1 colher de sopa de óleo", "1 colher de chá de fermento em pó"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Espalhe um fio de óleo numa forma pequena e polvilhe um pouco de cacau, para o bolo não grudar.",
   "Numa tigela, bata os ovos com o adoçante (ou o mel) usando um garfo ou batedor, por 1 minuto, até ficar espumoso.",
   "Junte a banana amassada, o leite e o óleo e misture bem.",
   "Acrescente o cacau em pó e a aveia batida (ou a farinha) e mexa até ficar uma massa lisa, sem pontos secos.",
   "Por último, junte o fermento e misture de leve, só para incorporar (mexer demais depois do fermento deixa o bolo pesado).",
   "Despeje na forma e leve ao forno por 30 minutos. Para saber se está pronto, espete um palito no centro: se sair limpo, o bolo está assado.",
   "Deixe amornar antes de desenformar e cortar. Fica ótimo com frutas vermelhas por cima."],
 "porcoes8": ["1 fatia fina",
              "1 fatia",
              "1 fatia · frutas vermelhas",
              "1 fatia · 1 col. iogurte",
              "1 fatia",
              "1 fatia média",
              "1 fatia · frutas vermelhas",
              "1 fatia grande · frutas"],
 "dica": "O cacau puro dá todo o sabor de chocolate sem o açúcar e a gordura do achocolatado. A banana adoça naturalmente e deixa o bolo úmido, a aveia entra com fibra e os ovos com proteína. É a prova de que dá para comer bolo de chocolate e continuar emagrecendo, desde que na fatia certa.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of moist dark chocolate cake on a white plate, topped with a few fresh raspberries, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mousse de Chocolate com Abacate",
 "hook": "Cremosa como a mousse tradicional, mas o segredo é o abacate — ninguém adivinha, e não leva creme de leite nem açúcar.",
 "tempo": "10 min + geladeira", "rende": "2 taças", "kcal_base": 170,
 "ings": ["1 abacate maduro (ou ½ avocado grande)", "3 colheres de sopa de cacau em pó 100%",
          "adoçante culinário a gosto — ou 2 colheres de sopa de mel", "3 colheres de sopa de leite (ou bebida vegetal)",
          "1 pitada de canela", "1 pitada de sal", "raspas de chocolate 70% para enfeitar (opcional)"],
 "passos": [
   "Corte o abacate ao meio, retire o caroço e tire a polpa com uma colher. Use só a parte bem macia e verde.",
   "Coloque a polpa do abacate no liquidificador ou copo do mixer, junto com o cacau, o adoçante (ou mel), o leite, a canela e o sal.",
   "Bata em velocidade máxima até virar um creme liso e brilhante, sem pedaços. Se ficar muito grosso, junte mais um pouco de leite.",
   "Prove e ajuste o doce a seu gosto.",
   "Divida em duas taças e leve à geladeira por pelo menos 30 minutos, para firmar e gelar. Sirva com raspas de chocolate por cima."],
 "porcoes8": ["½ taça pequena",
              "1 taça pequena",
              "1 taça",
              "1 taça · raspas de chocolate",
              "1 taça",
              "1 taça média",
              "1 taça · raspas de chocolate",
              "1 taça grande · raspas"],
 "dica": "O abacate dá a cremosidade da mousse com gordura boa no lugar do creme de leite, e sacia bastante. O cacau puro entra com o sabor de chocolate sem açúcar. É uma sobremesa rica e satisfatória que, em porção pequena, cabe tranquilamente na dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy dark chocolate avocado mousse in a small glass, topped with chocolate shavings and a mint leaf, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Brigadeiro Fit de Cacau",
 "hook": "O docinho de festa numa versão sem açúcar e sem leite condensado — enroladinho, chocolatudo e do tamanho certo para a vontade.",
 "tempo": "20 min + geladeira", "rende": "10 bolinhas", "kcal_base": 130,
 "ings": ["6 tâmaras sem caroço (aquela fruta seca bem docinha)", "3 colheres de sopa de cacau em pó 100%",
          "2 colheres de sopa de leite (ou bebida vegetal)", "1 colher de sopa de pasta de amendoim",
          "cacau em pó extra para enrolar", "1 pitada de sal"],
 "passos": [
   "Deixe as tâmaras de molho em água morna por 10 minutos, para amaciarem. Escorra.",
   "No copo do mixer ou liquidificador, bata as tâmaras com o cacau, o leite, a pasta de amendoim e o sal, até virar uma massa grossa e homogênea (bem misturada). Se precisar, pare e empurre a massa para o meio com uma colher.",
   "A massa deve ficar firme o suficiente para enrolar. Se estiver mole, leve à geladeira por 20 minutos.",
   "Com as mãos levemente umedecidas, pegue pequenas porções e enrole bolinhas do tamanho de uma noz.",
   "Passe cada bolinha no cacau em pó para cobrir. Guarde na geladeira e sirva geladinho."],
 "porcoes8": ["1 bolinha",
              "1 a 2 bolinhas",
              "2 bolinhas",
              "2 bolinhas",
              "2 bolinhas",
              "2 a 3 bolinhas",
              "3 bolinhas",
              "3 bolinhas"],
 "dica": "As tâmaras substituem o açúcar e o leite condensado com uma doçura natural e muita fibra, que segura a vontade de doce. O cacau puro dá o sabor de chocolate e a pasta de amendoim, a cremosidade. Um ou dois docinhos matam a vontade sem estourar as calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of several dark chocolate energy balls rolled in cocoa powder on a small white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bolo de Caneca de Chocolate",
 "hook": "A vontade de doce bateu à noite? Em três minutos, no micro-ondas, você tem um bolinho quente de chocolate só para você.",
 "tempo": "5 min", "rende": "1 caneca", "kcal_base": 190,
 "ings": ["1 ovo", "2 colheres de sopa de aveia batida virada farinha", "1 colher de sopa de cacau em pó 100%",
          "adoçante culinário a gosto — ou 1 colher de sopa de mel", "2 colheres de sopa de leite",
          "½ colher de chá de fermento em pó", "1 pitada de sal"],
 "passos": [
   "Numa caneca grande (de micro-ondas), quebre o ovo e bata com um garfo.",
   "Junte a aveia batida, o cacau, o adoçante (ou mel), o leite e o sal. Misture bem, até virar uma massa lisa, sem pontos secos nas bordas.",
   "Por último, junte o fermento e mexa de leve.",
   "Leve a caneca ao micro-ondas na potência alta (força máxima) por 1 minuto e 30 segundos a 2 minutos. O bolo cresce e firma; se ainda estiver molhado no centro, coloque mais 20 segundos.",
   "Cuidado que a caneca sai quente. Deixe amornar 1 minuto e coma na própria caneca. Fica ótimo com frutas por cima."],
 "porcoes8": ["½ caneca",
              "1 caneca pequena",
              "1 caneca",
              "1 caneca · frutas",
              "1 caneca",
              "1 caneca",
              "1 caneca · frutas",
              "1 caneca · frutas · 1 col. pasta de amendoim"],
 "dica": "Feito na hora e na porção de uma caneca, esse bolinho controla naturalmente o quanto você come — não sobra bolo inteiro tentando na mesa. Com aveia, ovo e cacau puro, é doce, quente e reconfortante sem açúcar, ideal para a vontade da noite.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm chocolate mug cake in a ceramic mug, topped with a few raspberries, a spoon beside it, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mousse de Morango com Iogurte",
 "hook": "Rosada, aveludada e refrescante — uma mousse de morango que leva só três ingredientes e nenhum açúcar.",
 "tempo": "10 min + geladeira", "rende": "3 taças", "kcal_base": 120,
 "ings": ["2 xícaras de morangos (frescos ou congelados)", "1 pote de iogurte natural sem açúcar (≈ 170 g)",
          "1 colher de sopa de gelatina sem sabor", "adoçante a gosto — ou 1 colher de sopa de mel",
          "3 colheres de sopa de água quente", "morangos picados para enfeitar"],
 "passos": [
   "Lave os morangos e tire as folhinhas verdes. Guarde alguns para enfeitar.",
   "Numa xícara, dissolva a gelatina sem sabor na água quente, mexendo bem até ficar transparente, sem grãozinhos. Deixe amornar.",
   "No liquidificador, bata os morangos com o iogurte e o adoçante (ou mel) até virar um creme liso e rosado.",
   "Com o liquidificador ligado em velocidade baixa, junte a gelatina dissolvida e bata por mais 30 segundos, só para misturar.",
   "Divida em taças e leve à geladeira por pelo menos 2 horas, até firmar. Sirva com morangos picados por cima."],
 "porcoes8": ["½ taça",
              "1 taça pequena",
              "1 taça",
              "1 taça · morangos",
              "1 taça",
              "1 taça média",
              "1 taça · morangos",
              "1 taça grande · morangos"],
 "dica": "O morango é doce e cheio de vitamina C com pouquíssima caloria, e o iogurte natural soma proteína e cremosidade sem açúcar. A gelatina dá a textura de mousse sem creme de leite. Uma sobremesa leve, bonita e refrescante que sacia a vontade de doce.",
 "prompt": "Square ultra-realistic overhead food photograph of a pink strawberry yogurt mousse in a glass, topped with fresh chopped strawberries and a mint leaf, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Sorvete Cremoso de Banana",
 "hook": "Um sorvete de verdade, cremoso e gelado, feito só com banana — sem açúcar, sem leite, sem máquina de sorvete.",
 "tempo": "5 min + congelador", "rende": "2 porções", "kcal_base": 120,
 "ings": ["3 bananas maduras", "1 colher de sopa de cacau em pó 100% OU 1 punhado de frutas vermelhas (opcional, para dar sabor)",
          "1 pitada de canela", "1 colher de chá de pasta de amendoim (opcional)"],
 "passos": [
   "Descasque as bananas, corte em rodelas e coloque num saco ou pote. Leve ao congelador por pelo menos 3 horas, até ficarem bem duras.",
   "Tire as rodelas congeladas e coloque no liquidificador potente ou no copo do mixer.",
   "Bata em velocidade máxima. No começo vira pedacinhos; continue batendo (parando para empurrar a banana para o meio) até virar um creme liso, igual sorvete de máquina.",
   "Se quiser sabor, junte o cacau ou as frutas vermelhas e bata mais um pouco.",
   "Sirva na hora, bem cremoso, com uma pitada de canela — ou leve ao congelador por 1 hora para ficar mais firme, como sorvete de pote."],
 "porcoes8": ["½ porção",
              "1 porção pequena",
              "1 porção",
              "1 porção · 1 col. pasta de amendoim",
              "1 porção",
              "1 porção média",
              "1 porção · frutas",
              "1 porção grande · frutas · pasta de amendoim"],
 "dica": "Congelada e batida, a banana solta o próprio açúcar natural e vira um creme igual a sorvete, sem precisar de açúcar, leite ou nata. É doce, gelado e satisfatório, com a fibra e o potássio da fruta — a sobremesa perfeita para os dias quentes sem culpa.",
 "prompt": "Square ultra-realistic overhead food photograph of a scoop of creamy banana nice cream in a bowl, dusted with cinnamon, a few banana slices beside it, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pudim de Leite Fit",
 "hook": "O pudim cremoso de sempre, com aquela calda dourada — só que sem açúcar e muito mais leve, feito com leite e ovos.",
 "tempo": "50 min", "rende": "6 fatias", "kcal_base": 130,
 "ings": ["3 ovos", "2 xícaras de leite desnatado (ou bebida vegetal)", "adoçante culinário a gosto (o próprio para forno)",
          "1 colher de chá de essência de baunilha", "adoçante culinário que vira caramelo (opcional, para a calda)",
          "água quente para o banho-maria"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Se quiser calda, derreta um pouco de adoçante próprio para caramelo numa forminha e espalhe no fundo (ou pule a calda).",
   "No liquidificador, bata os ovos, o leite, o adoçante e a baunilha por 1 minuto, até ficar bem misturado.",
   "Despeje a mistura na forma.",
   "Coloque a forma dentro de uma assadeira maior e encha a assadeira com água quente até a metade da altura da forma (isso é o banho-maria: a água faz o pudim assar por igual e ficar cremoso).",
   "Leve ao forno por 40 minutos, até firmar mas ainda tremer levemente no centro. Deixe esfriar e depois leve à geladeira por 3 horas antes de desenformar."],
 "porcoes8": ["1 fatia fina",
              "1 fatia",
              "1 fatia",
              "1 fatia · frutas",
              "1 fatia",
              "1 fatia média",
              "1 fatia · frutas",
              "1 fatia grande · frutas"],
 "dica": "Trocando o leite condensado e o açúcar por leite desnatado e adoçante, o pudim mantém a cremosidade e o sabor com uma fração das calorias. Os ovos e o leite ainda dão proteína. Em fatia pequena, é uma sobremesa clássica que cabe na dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of creamy milk flan (pudim) with a light golden caramel on top, on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Cookies de Aveia e Banana",
 "hook": "Dois ingredientes, uma tigela e vinte minutos: biscoitinhos macios e docinhos, sem açúcar e sem farinha branca.",
 "tempo": "20 min", "rende": "12 cookies", "kcal_base": 110,
 "ings": ["2 bananas bem maduras", "1 xícara e meia de aveia em flocos", "1 pitada de canela",
          "1 colher de sopa de uvas-passas ou pedacinhos de chocolate 70% (opcional)", "1 pitada de sal"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Forre uma assadeira com papel-manteiga.",
   "Numa tigela, amasse bem as bananas com um garfo, até virar um purê sem pedaços grandes.",
   "Junte a aveia, a canela, o sal e, se quiser, as passas ou o chocolate picado. Misture até formar uma massa grudenta.",
   "Com uma colher, coloque pequenas porções na assadeira e achate cada uma com as costas da colher, dando o formato de biscoito.",
   "Leve ao forno por 12 a 15 minutos, até as bordas ficarem douradas e firmes. Deixe esfriar na assadeira (eles firmam ao esfriar) e sirva."],
 "porcoes8": ["1 cookie",
              "2 cookies",
              "2 cookies",
              "2 cookies · frutas",
              "2 cookies",
              "3 cookies",
              "3 cookies",
              "3 a 4 cookies"],
 "dica": "A banana madura adoça e dá liga sem precisar de açúcar nem farinha branca, e a aveia entra com fibra que sacia. São biscoitos naturais, ótimos para o lanche ou a sobremesa, que matam a vontade de doce de forma leve — mas conte quantos come, porque são fáceis de exagerar.",
 "prompt": "Square ultra-realistic overhead food photograph of several soft oatmeal banana cookies on a wooden board, with a few oats and raisins scattered around, soft natural light, homemade and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Maçã Assada com Canela e Nozes",
 "hook": "A maçã fica macia e perfumada de canela, com um recheio crocante de nozes — uma sobremesa quente que conforta como uma torta, sem a massa.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 130,
 "ings": ["2 maçãs", "canela em pó a gosto", "1 colher de sopa de nozes picadas (ou outra castanha)",
          "1 colher de sopa de aveia em flocos", "1 colher de chá de mel (opcional)", "1 pitada de cravo em pó (opcional)"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Lave as maçãs e, com uma faca, retire o miolo do centro (a parte das sementes), formando um buraco, sem furar até o fundo.",
   "Numa tigelinha, misture as nozes picadas, a aveia, a canela e, se quiser, o mel e o cravo.",
   "Recheie o buraco de cada maçã com essa mistura, apertando de leve.",
   "Coloque as maçãs numa assadeira com um dedo de água no fundo (para não ressecar) e polvilhe mais canela por cima.",
   "Asse por 25 a 30 minutos, até a maçã ficar bem macia (um garfo entra fácil) e o recheio dourado. Sirva quente, sozinha ou com uma colher de iogurte natural."],
 "porcoes8": ["½ maçã",
              "1 maçã",
              "1 maçã",
              "1 maçã · 1 col. iogurte",
              "1 maçã",
              "1 maçã · nozes extras",
              "1 maçã · iogurte",
              "2 maçãs · iogurte"],
 "dica": "Assar a maçã concentra a doçura natural da fruta, então ela fica adocicada sem açúcar. A canela realça o sabor e ajuda a controlar a vontade de doce, e as nozes dão gordura boa e crocância. É o conforto de uma torta de maçã com uma fração das calorias.",
 "prompt": "Square ultra-realistic overhead food photograph of a baked apple filled with oats and chopped walnuts, dusted with cinnamon, on a small plate with a spoon, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Gelatina de Frutas Caseira",
 "hook": "Colorida, tremeluzente e refrescante, com pedaços de fruta de verdade por dentro — a sobremesa mais leve que existe.",
 "tempo": "10 min + geladeira", "rende": "4 taças", "kcal_base": 70,
 "ings": ["1 colher de sopa de gelatina sem sabor", "2 xícaras de suco natural de fruta sem açúcar (laranja, uva ou morango)",
          "½ xícara de água", "1 xícara de frutas picadas (morango, kiwi, manga ou uva)", "adoçante a gosto (opcional)"],
 "passos": [
   "Numa panela pequena, coloque a água e polvilhe a gelatina sem sabor por cima. Deixe descansar 2 minutos (a gelatina incha, o que se chama hidratar).",
   "Leve ao fogo baixo e mexa por 1 minuto, só até a gelatina dissolver por completo, sem ferver. Desligue.",
   "Junte o suco natural de fruta (e o adoçante, se quiser) e misture bem.",
   "Coloque as frutas picadas no fundo de taças ou de uma travessa e despeje o líquido por cima.",
   "Leve à geladeira por pelo menos 4 horas, até ficar firme. Sirva bem gelada."],
 "porcoes8": ["½ taça",
              "1 taça pequena",
              "1 taça",
              "1 taça · frutas extras",
              "1 taça",
              "1 taça média",
              "1 taça · frutas",
              "1 taça grande · frutas"],
 "dica": "Feita com suco natural no lugar do pó cheio de açúcar e corante, a gelatina caseira é praticamente sem calorias e ainda leva pedaços de fruta de verdade. É a sobremesa ideal para quando bate a vontade de algo doce e gelado sem pesar em nada na dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of colorful homemade fruit jelly in a glass with pieces of strawberry, kiwi and grapes suspended inside, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Barrinha de Aveia com Frutas Secas",
 "hook": "A barrinha de cereal caseira, mastigável e docinha, sem os açúcares e xaropes das industrializadas — perfeita para a bolsa.",
 "tempo": "30 min", "rende": "8 barrinhas", "kcal_base": 150,
 "ings": ["2 xícaras de aveia em flocos", "2 bananas maduras amassadas", "3 colheres de sopa de frutas secas picadas (uva-passa, damasco ou tâmara)",
          "2 colheres de sopa de castanhas ou nozes picadas", "1 colher de sopa de mel (opcional)", "1 pitada de canela e sal"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Forre uma forma retangular pequena com papel-manteiga.",
   "Numa tigela, amasse bem as bananas até virar um purê.",
   "Junte a aveia, as frutas secas picadas, as castanhas, a canela, o sal e, se quiser, o mel. Misture até formar uma massa grudenta e uniforme.",
   "Despeje a massa na forma e aperte bem com as costas de uma colher, deixando uma camada firme e igual (quanto mais apertada, menos a barrinha esfarela).",
   "Asse por 20 minutos, até dourar as bordas. Deixe esfriar completamente na forma antes de cortar em barrinhas (se cortar quente, esfarela)."],
 "porcoes8": ["1 barrinha",
              "1 barrinha",
              "1 barrinha",
              "1 barrinha · frutas",
              "1 barrinha",
              "1 a 2 barrinhas",
              "2 barrinhas",
              "2 barrinhas"],
 "dica": "As barrinhas de supermercado costumam ter mais açúcar e xarope que um doce. Feita em casa com aveia, banana e frutas secas, a barrinha adoça de forma natural e traz fibra e energia que seguram a fome. Ótima para o lanche ou uma sobremesa prática, mas coma uma de cada vez.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade oat and dried fruit granola bars stacked on a wooden board, with oats, raisins and nuts scattered around, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iogurte Gelado com Frutas Vermelhas",
 "hook": "Uma placa crocante de iogurte gelado salpicado de frutas, que você quebra em pedaços — bonita, divertida e sem açúcar.",
 "tempo": "5 min + congelador", "rende": "4 porções", "kcal_base": 100,
 "ings": ["1 pote grande de iogurte grego natural sem açúcar (≈ 350 g)", "1 xícara de frutas vermelhas (morango, mirtilo, framboesa)",
          "1 colher de sopa de mel (opcional)", "1 colher de sopa de castanhas picadas (opcional)", "raspas de chocolate 70% (opcional)"],
 "passos": [
   "Forre uma assadeira ou travessa rasa com papel-manteiga.",
   "Numa tigela, misture o iogurte grego com o mel (se usar), até ficar bem liso.",
   "Espalhe o iogurte sobre o papel-manteiga, formando uma camada de mais ou menos meio dedo de altura.",
   "Salpique por cima as frutas vermelhas (corte os morangos), as castanhas e as raspas de chocolate, espalhando por toda a superfície.",
   "Leve ao congelador por 3 a 4 horas, até ficar bem duro. Quebre ou corte em pedaços irregulares e sirva na hora (derrete rápido). Guarde o restante no congelador."],
 "porcoes8": ["1 pedaço pequeno",
              "1 pedaço",
              "1 a 2 pedaços",
              "2 pedaços",
              "2 pedaços",
              "2 pedaços",
              "2 a 3 pedaços",
              "3 pedaços"],
 "dica": "O iogurte grego traz proteína e cremosidade sem açúcar, e congelado vira um docinho gelado e crocante. As frutas vermelhas adoçam naturalmente e enchem de antioxidantes. É uma sobremesa refrescante e leve, ótima para o verão e para a vontade de beliscar algo doce.",
 "prompt": "Square ultra-realistic overhead food photograph of frozen yogurt bark broken into pieces, topped with berries, chopped nuts and dark chocolate shavings, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Trufa de Chocolate Fit",
 "hook": "Pequena, intensa e chocolatuda — a trufa que derrete na boca sem açúcar nenhum, para os momentos de vontade forte.",
 "tempo": "20 min + geladeira", "rende": "10 trufas", "kcal_base": 120,
 "ings": ["100 g de chocolate 70% (ou mais escuro)", "4 colheres de sopa de leite quente (ou bebida vegetal)",
          "2 colheres de sopa de coco ralado sem açúcar", "cacau em pó 100% para enrolar", "1 pitada de sal"],
 "passos": [
   "Pique o chocolate 70% em pedaços pequenos e coloque numa tigela.",
   "Aqueça o leite até quase ferver e despeje sobre o chocolate. Espere 1 minuto e mexa até o chocolate derreter por completo, virando um creme liso e brilhante (isso é o ganache).",
   "Junte o coco ralado e o sal e misture. Leve à geladeira por 1 hora, até a mistura firmar o suficiente para enrolar.",
   "Com as mãos, pegue pequenas porções e enrole bolinhas do tamanho de uma azeitona grande.",
   "Passe cada trufa no cacau em pó para cobrir. Guarde na geladeira e sirva geladas."],
 "porcoes8": ["1 trufa",
              "1 trufa",
              "1 a 2 trufas",
              "2 trufas",
              "2 trufas",
              "2 trufas",
              "2 a 3 trufas",
              "3 trufas"],
 "dica": "O chocolate 70% ou mais amargo tem pouco açúcar e muito cacau, que é rico em antioxidantes. Em trufa pequena, ele satisfaz a vontade intensa de chocolate com bem menos açúcar que um bombom comum. Uma ou duas resolvem o desejo sem sabotar a dieta.",
 "prompt": "Square ultra-realistic overhead food photograph of dark chocolate truffles rolled in cocoa powder on a small dark plate, one cut in half showing the smooth center, on a light wooden table, soft natural light, elegant and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Bolo de Cenoura Fit com Cobertura de Cacau",
 "hook": "O bolo de cenoura fofinho da infância, com cobertura de chocolate — sem açúcar, mas com todo o carinho e o sabor.",
 "tempo": "45 min", "rende": "8 fatias", "kcal_base": 160,
 "ings": ["2 cenouras médias picadas", "3 ovos", "3 colheres de sopa de óleo", "adoçante culinário a gosto (o próprio para forno)",
          "1 xícara e meia de aveia batida virada farinha (ou farinha de trigo integral)", "1 colher de chá de fermento em pó",
          "Cobertura: 2 colheres de sopa de cacau em pó 100% + 2 colheres de sopa de leite + adoçante a gosto"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Espalhe um fio de óleo numa forma e polvilhe um pouco de farinha.",
   "No liquidificador, bata as cenouras picadas, os ovos, o óleo e o adoçante até virar um creme liso e alaranjado.",
   "Passe para uma tigela, junte a aveia batida (ou farinha) e misture. Por último, junte o fermento e mexa de leve.",
   "Despeje na forma e asse por 30 minutos, até que um palito espetado no centro saia limpo.",
   "Faça a cobertura: numa panelinha, misture o cacau, o leite e o adoçante e aqueça em fogo baixo por 2 minutos, mexendo, até virar um creme brilhante. Espalhe sobre o bolo já morno."],
 "porcoes8": ["1 fatia fina",
              "1 fatia",
              "1 fatia",
              "1 fatia · frutas",
              "1 fatia",
              "1 fatia média",
              "1 fatia · frutas",
              "1 fatia grande"],
 "dica": "A cenoura deixa o bolo úmido e naturalmente adocicado, além de somar vitamina A. Trocando o açúcar por adoçante e a farinha branca por aveia, o bolo fica leve e cheio de fibra. A cobertura de cacau puro dá o toque de chocolate sem o açúcar do brigadeiro tradicional.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of carrot cake with a dark chocolate glaze on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mousse de Limão",
 "hook": "Azedinha na medida certa, cremosa e geladinha — uma mousse de limão refrescante que limpa o paladar e não leva açúcar.",
 "tempo": "10 min + geladeira", "rende": "3 taças", "kcal_base": 120,
 "ings": ["1 pote de iogurte natural sem açúcar (≈ 170 g)", "suco de 2 limões", "raspas da casca de 1 limão",
          "1 colher de sopa de gelatina sem sabor", "3 colheres de sopa de água quente",
          "adoçante a gosto — ou 2 colheres de sopa de mel"],
 "passos": [
   "Lave bem 1 limão e tire as raspas só da parte verde da casca (a parte branca é amarga). Esprema os 2 limões para tirar o suco.",
   "Numa xícara, dissolva a gelatina sem sabor na água quente, mexendo até ficar transparente. Deixe amornar.",
   "Numa tigela, misture o iogurte, o suco de limão, as raspas e o adoçante (ou mel), até ficar cremoso.",
   "Junte a gelatina dissolvida e misture bem e rápido, para não formar pelotinhas.",
   "Divida em taças e leve à geladeira por pelo menos 2 horas, até firmar. Sirva gelada, com mais raspas de limão por cima."],
 "porcoes8": ["½ taça",
              "1 taça pequena",
              "1 taça",
              "1 taça · frutas",
              "1 taça",
              "1 taça média",
              "1 taça · frutas",
              "1 taça grande · frutas"],
 "dica": "O limão dá frescor e um sabor marcante que engana a vontade de doce sem precisar de muito adoçante. O iogurte natural entra com proteína e cremosidade, e a gelatina firma a mousse sem creme de leite. Uma sobremesa leve, refrescante e pertinho de zero de gordura.",
 "prompt": "Square ultra-realistic overhead food photograph of a creamy lemon mousse in a glass, topped with lemon zest and a thin lemon slice, on a light wooden table, soft natural light, fresh and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Cheesecake Fit de Frutas Vermelhas (sem forno)",
 "hook": "Cremoso, com base crocante e calda de frutas, montado sem forno — o cheesecake dos sonhos numa versão leve e sem açúcar.",
 "tempo": "20 min + geladeira", "rende": "6 fatias", "kcal_base": 170,
 "ings": ["Base: 1 xícara de aveia + 1 banana amassada + 1 colher de chá de canela",
          "Creme: 1 xícara de ricota (ou cottage) + ½ pote de iogurte natural + adoçante a gosto + suco de ½ limão",
          "1 colher de sopa de gelatina sem sabor + 3 colheres de sopa de água quente",
          "Calda: 1 xícara de frutas vermelhas + adoçante a gosto"],
 "passos": [
   "Base: misture a aveia, a banana amassada e a canela até formar uma massa. Aperte no fundo de uma forma pequena (de preferência com fundo que solta), formando uma camada firme. Leve ao congelador por 10 minutos.",
   "Dissolva a gelatina na água quente, mexendo até ficar transparente. Deixe amornar.",
   "Creme: no liquidificador, bata a ricota, o iogurte, o adoçante e o suco de limão até virar um creme bem liso. Junte a gelatina e bata mais 20 segundos.",
   "Despeje o creme sobre a base e alise a superfície. Leve à geladeira por pelo menos 3 horas, até firmar.",
   "Calda: numa panelinha, cozinhe as frutas vermelhas com o adoçante em fogo baixo por 5 minutos, amassando um pouco, até virar uma geleia. Deixe esfriar e espalhe sobre o cheesecake antes de servir."],
 "porcoes8": ["1 fatia fina",
              "1 fatia",
              "1 fatia",
              "1 fatia · calda extra",
              "1 fatia",
              "1 fatia média",
              "1 fatia · calda",
              "1 fatia grande · calda"],
 "dica": "A ricota e o cottage dão a cremosidade do cream cheese com muito menos gordura e mais proteína. A base de aveia e banana substitui o biscoito amanteigado, e a calda de fruta cozida dispensa o açúcar. Um cheesecake de verdade que cabe na dieta, em fatia controlada.",
 "prompt": "Square ultra-realistic overhead food photograph of a slice of no-bake cheesecake with an oat base and a glossy red berry topping, on a white plate, on a light wooden table, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Picolé de Frutas Caseiro",
 "hook": "Refrescante e cheio de fruta de verdade, esse picolé caseiro é a sobremesa perfeita para o calor — e não tem uma gota de açúcar.",
 "tempo": "10 min + congelador", "rende": "6 picolés", "kcal_base": 60,
 "ings": ["2 xícaras de frutas picadas (morango, manga, kiwi ou melancia)", "1 xícara de suco natural sem açúcar (ou água de coco)",
          "1 pote de iogurte natural sem açúcar (opcional, para picolé cremoso)", "adoçante a gosto (opcional)",
          "forminhas de picolé e palitos"],
 "passos": [
   "Pique as frutas em pedaços pequenos, para caberem nas forminhas.",
   "Escolha o estilo: para picolé de fruta, use só as frutas e o suco natural; para picolé cremoso, bata as frutas com o iogurte no liquidificador.",
   "Coloque alguns pedaços de fruta no fundo de cada forminha (fica bonito) e complete com o suco ou o creme batido, deixando um dedo de espaço no topo (o líquido incha ao congelar).",
   "Espete um palito no centro de cada picolé.",
   "Leve ao congelador por pelo menos 5 horas, até ficarem bem firmes. Para desenformar, passe a forminha rapidamente sob água morna."],
 "porcoes8": ["1 picolé",
              "1 picolé",
              "1 picolé",
              "1 a 2 picolés",
              "1 picolé",
              "1 a 2 picolés",
              "2 picolés",
              "2 picolés"],
 "dica": "Os picolés de caixinha são quase só água, açúcar e corante. Feito em casa com fruta de verdade e suco natural, o picolé vira uma sobremesa refrescante cheia de vitaminas e praticamente sem calorias — a melhor forma de matar a vontade de gelado no calor sem culpa.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade fruit popsicles with visible pieces of strawberry, mango and kiwi, on a plate with ice, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Muffin de Maçã e Canela",
 "hook": "Fofinhos, cheirosos e com pedaços de maçã — muffins de café da tarde que parecem pecado, mas são leves e sem açúcar.",
 "tempo": "35 min", "rende": "6 muffins", "kcal_base": 140,
 "ings": ["2 ovos", "1 maçã ralada + ½ maçã em cubinhos", "1 xícara e meia de aveia batida virada farinha",
          "3 colheres de sopa de óleo", "adoçante culinário a gosto (o próprio para forno)", "½ xícara de leite",
          "1 colher de chá de canela", "1 colher de chá de fermento em pó", "1 pitada de sal"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Forre uma forma de muffin com forminhas de papel (ou espalhe um fio de óleo nos buracos).",
   "Numa tigela, bata os ovos com o adoçante e o óleo por 1 minuto. Junte o leite e a maçã ralada e misture.",
   "Acrescente a aveia batida, a canela e o sal e mexa até ficar uma massa homogênea. Junte os cubinhos de maçã e o fermento e misture de leve.",
   "Distribua a massa nas forminhas, enchendo até dois terços (eles crescem).",
   "Asse por 20 a 25 minutos, até dourarem e um palito espetado sair limpo. Deixe amornar e sirva."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 col. iogurte",
              "1 muffin",
              "1 a 2 muffins",
              "2 muffins",
              "2 muffins"],
 "dica": "A maçã ralada deixa os muffins úmidos e naturalmente doces, dispensando o açúcar. A aveia dá fibra que sacia e a canela realça a doçura da fruta. São ótimos para o lanche ou a sobremesa, na porção de uma unidade, matando a vontade de padaria de forma leve.",
 "prompt": "Square ultra-realistic overhead food photograph of homemade apple cinnamon muffins in paper liners on a wooden board, one broken open showing apple pieces, dusted with cinnamon, soft natural light, appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Crumble de Maçã e Aveia",
 "hook": "Maçã macia por baixo, farofinha crocante de aveia por cima — o aconchego de uma torta quente, montado em minutos e sem açúcar.",
 "tempo": "40 min", "rende": "4 porções", "kcal_base": 160,
 "ings": ["3 maçãs em cubos", "suco de ½ limão", "1 colher de chá de canela",
          "Farofa: 1 xícara de aveia em flocos + 2 colheres de sopa de castanhas picadas + 2 colheres de sopa de óleo de coco (ou óleo comum) + adoçante a gosto",
          "1 pitada de sal"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Numa tigela, misture os cubos de maçã com o suco de limão e a canela e espalhe no fundo de um refratário.",
   "Faça a farofa: numa outra tigela, misture a aveia, as castanhas, o óleo, o adoçante e o sal, esfregando com as pontas dos dedos até formar uma farofa úmida e grudadinha.",
   "Espalhe a farofa por cima das maçãs, cobrindo toda a superfície.",
   "Asse por 25 a 30 minutos, até a maçã borbulhar nas laterais e a farofa ficar dourada e crocante.",
   "Deixe amornar 5 minutos e sirva. Fica delicioso com uma colher de iogurte natural ou sorvete de banana por cima."],
 "porcoes8": ["½ porção",
              "1 porção pequena",
              "1 porção",
              "1 porção · iogurte",
              "1 porção",
              "1 porção média",
              "1 porção · iogurte",
              "1 porção grande · iogurte"],
 "dica": "A maçã assada solta a própria doçura, e a canela reforça o sabor sem açúcar. A farofa de aveia e castanhas dá a crocância de uma torta com fibra e gordura boa no lugar da manteiga e da farinha branca. É o conforto de uma sobremesa quente de forno, na porção certa.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm apple oat crumble in a small dish, golden crunchy topping over soft baked apples, a spoon lifting a portion, on a light wooden table, soft natural light, cozy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pera Assada com Especiarias",
 "hook": "A pera fica macia e suculenta, perfumada de canela e cravo — uma sobremesa elegante e quente, doce só pela fruta.",
 "tempo": "35 min", "rende": "2 porções", "kcal_base": 110,
 "ings": ["2 peras firmes", "canela em pau (ou em pó)", "2 cravos-da-índia", "raspas de casca de laranja (opcional)",
          "1 colher de chá de mel (opcional)", "1 colher de sopa de nozes ou amêndoas picadas"],
 "passos": [
   "Ligue o forno em temperatura média (180 °C). Lave as peras, corte ao meio no comprimento e retire o miolo do centro com uma colher pequena, fazendo uma cavidade.",
   "Coloque as metades de pera numa assadeira, com a parte cortada para cima. Polvilhe canela por cima e coloque um cravo e um pouco de raspas de laranja em cada cavidade.",
   "Se quiser, pingue algumas gotas de mel em cada pera.",
   "Coloque um dedo de água no fundo da assadeira (para não ressecar) e asse por 25 minutos, até a pera ficar bem macia (um garfo entra fácil).",
   "Retire os cravos, salpique as nozes picadas por cima e sirva quente, sozinha ou com uma colher de iogurte natural."],
 "porcoes8": ["1 metade",
              "1 pera (2 metades)",
              "1 pera",
              "1 pera · iogurte",
              "1 pera",
              "1 pera · nozes extras",
              "1 pera · iogurte",
              "2 peras · iogurte"],
 "dica": "Assar a pera concentra o açúcar natural da fruta, deixando-a docinha sem precisar de açúcar adicionado. As especiarias dão um aroma reconfortante que satisfaz o paladar, e as nozes acrescentam gordura boa e crocância. Uma sobremesa quente, leve e sofisticada.",
 "prompt": "Square ultra-realistic overhead food photograph of baked pear halves with cinnamon, cloves and chopped nuts, on a small plate, on a light wooden table, soft natural light, elegant and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
]
