# -*- coding: utf-8 -*-
"""35 receitas de ALMOCO (031-065). ESPANHOL (America Latina).

Traducao literal de `receitas_almoco_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario LatAm com foco Mexico (camote, jitomate,
ejotes, elote, calabacin, carne molida, pollo deshebrado).
⛔ METRICO: g, ml, °C — como pt/de/fr. Os numeros vem do de/fr, NUNCA de
oz/cup de volta: e o que preserva a escada das 8 faixas.
⛔ O campo `prompt` NAO e replicado: a foto e a mesma do PT (fotos/031-065).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
Metas (kcal): 360/440/500/560 · 540/610/680/750
"""

RECEITAS = [
{
 "nome": "Pollo a la plancha con arroz integral y brócoli",
 "hook": "El plato más simple del mundo y uno de los mejores para bajar de peso: proteína magra, un buen carbohidrato y verduras todo lo que quieras.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 470,
 "ings": ["1 filete de pechuga de pollo (unos 150 g)", "4 cucharadas de arroz integral cocido",
          "1 plato de brócoli", "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal y pimienta al gusto"],
 "passos": [
   "Sazona el pollo por los dos lados con sal, pimienta, el ajo y el jugo de limón. Déjalo tomar sabor 5 minutos.",
   "Corta el brócoli en ramitos pequeños. Hierve agua en una olla, agrega el brócoli y déjalo solo 3 minutos, hasta que quede verde brillante y tierno pero todavía firme. Escúrrelo.",
   "Calienta un sartén antiadherente a fuego medio-alto con el aceite de oliva. Pon el pollo y déjalo de 4 a 5 minutos de cada lado, sin moverlo, hasta que quede dorado por fuera y blanco por dentro.",
   "Para saber si ya está, corta el filete por la mitad: la carne tiene que estar blanca hasta el centro, sin ninguna parte rosada.",
   "Calienta el arroz integral ya cocido. Arma el plato con el arroz, el pollo rebanado y el brócoli a un lado.",
   "Si quieres, rocía el brócoli con un poco de aceite de oliva y más limón."],
 "porcoes8": ["100 g de pollo · 3 cucharadas de arroz · brócoli, todo lo que quieras",
              "120 g de pollo · 4 cucharadas de arroz · brócoli, todo lo que quieras",
              "130 g de pollo · 5 cucharadas de arroz · brócoli, todo lo que quieras",
              "150 g de pollo · 5 cucharadas de arroz · un poco de aceite de oliva",
              "150 g de pollo · 5 cucharadas de arroz · brócoli, todo lo que quieras",
              "170 g de pollo · 6 cucharadas de arroz · brócoli, todo lo que quieras",
              "200 g de pollo · 7 cucharadas de arroz · un poco de aceite de oliva",
              "220 g de pollo · 8 cucharadas de arroz · un poco de aceite de oliva"],
 "dica": "La pechuga de pollo es casi proteína pura, muy saciante, y ayuda a proteger tu músculo mientras pierdes grasa. El arroz integral tiene fibra y libera energía despacio, así que no te da esa hambre que llega una hora después. El brócoli llena el plato con casi nada de calorías.",
},
{
 "nome": "Filete de tilapia con puré de camote",
 "hook": "Pescado ligero y un puré naturalmente dulce — una comida que parece de restaurante y entra en tu dieta.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 440,
 "ings": ["1 filete de tilapia (unos 150 g)", "1 camote mediano",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "hierbas frescas picadas", "sal, pimienta y paprika al gusto",
          "hojas verdes para la ensalada"],
 "passos": [
   "Pela el camote y córtalo en trozos. Cuécelo en agua hirviendo 15 minutos, hasta que quede muy suave (el tenedor entra sin esfuerzo). Escúrrelo.",
   "Aplasta el camote todavía caliente con un tenedor, agrega una pizca de sal y la mitad del aceite de oliva, y mezcla hasta que quede un puré terso.",
   "Sazona la tilapia con sal, pimienta, paprika y el jugo de limón.",
   "Calienta un sartén antiadherente con el resto del aceite de oliva a fuego medio. Pon el filete y déjalo de 3 a 4 minutos de cada lado, volteándolo con cuidado una sola vez, hasta que quede dorado y se despegue fácil del sartén.",
   "Arma el plato con el puré, el filete encima y una porción de hojas verdes a un lado. Termina con las hierbas frescas."],
 "porcoes8": ["120 g de pescado · ½ camote · ensalada",
              "150 g de pescado · 1 camote pequeño · ensalada",
              "150 g de pescado · 1 camote mediano · ensalada",
              "170 g de pescado · 1 camote mediano · un poco de aceite de oliva",
              "170 g de pescado · 1 camote mediano · ensalada",
              "200 g de pescado · 1 camote grande · ensalada",
              "220 g de pescado · 1 camote grande · un poco de aceite de oliva",
              "250 g de pescado · 1 camote grande · un poco de aceite de oliva"],
 "dica": "La tilapia es un pescado magro, lleno de proteína y con muy poca grasa. El camote te mantiene satisfecha por horas y, aunque es un carbohidrato, libera energía muy despacio — por eso es el favorito de quien quiere bajar de peso sin perder energía.",
},
{
 "nome": "Filete de atún a la plancha con verduras y papa",
 "hook": "El atún fresco se convierte en un bistec del mar: firme por fuera, jugoso por dentro, y listo en pocos minutos.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 450,
 "ings": ["1 filete de atún fresco (unos 150 g)", "1 papa pequeña en rebanadas",
          "110 g de ejotes y zanahoria", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y orégano al gusto"],
 "passos": [
   "Cuece las rebanadas de papa en agua hirviendo con sal 10 minutos, hasta que queden suaves pero sin deshacerse. Escúrrelas.",
   "Corta los ejotes en trozos y la zanahoria en rodajas. Cuécelos en una vaporera o en un poco de agua hirviendo 5 minutos, hasta que queden tiernos pero todavía firmes.",
   "Sazona el filete de atún con sal, pimienta, el ajo, el orégano y el jugo de limón. Déjalo tomar sabor 5 minutos.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego alto. Pon el filete y déjalo de 2 a 3 minutos de cada lado — el atún queda excelente ligeramente rosado en el centro; si lo prefieres bien cocido, déjalo 1 minuto más de cada lado.",
   "Arma el plato con la papa, las verduras y el filete de atún encima. Rocía con un poco más de limón y sirve."],
 "porcoes8": ["120 g de atún · ½ papa · verduras",
              "150 g de atún · 1 papa pequeña · verduras",
              "150 g de atún · 1 papa · verduras",
              "170 g de atún · 1 papa · un poco de aceite de oliva",
              "170 g de atún · 1 papa · verduras",
              "200 g de atún · 1 papa grande · verduras",
              "220 g de atún · 1 papa grande · un poco de aceite de oliva",
              "250 g de atún · 2 papas pequeñas · un poco de aceite de oliva"],
 "dica": "El atún fresco es una de las carnes más magras del mar: mucha proteína, omega-3 (la grasa buena) y muy poca grasa mala. Sellado rápido a fuego alto queda jugoso sin aceite, y con verduras y un poco de papa se vuelve una comida fina y ligera.",
},
{
 "nome": "Wrap integral con pollo deshebrado",
 "hook": "Un rollo práctico para llevar al trabajo, relleno de pollo y ensalada — mata el hambre sin pesarte.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 420,
 "ings": ["1 tortilla integral (o pan plano integral)",
          "1 filete de pollo cocido y deshebrado (unos 120 g)",
          "1 cucharada de yogur natural sin azúcar", "hojas de lechuga",
          "½ jitomate en rebanadas", "zanahoria rallada",
          "sal, pimienta y un poco de mostaza al gusto"],
 "passos": [
   "Cuece la pechuga de pollo en agua con sal unos 15 minutos, hasta que quede blanca por dentro. Déjala enfriar un poco y deshébrala con dos tenedores, jalando la carne en hebras.",
   "En un tazón, mezcla el pollo deshebrado con el yogur, la mostaza, sal y pimienta, hasta que quede un relleno cremoso.",
   "Calienta la tortilla 20 segundos en un sartén, solo para que se suavice y sea fácil de enrollar.",
   "Reparte las hojas de lechuga en el centro de la tortilla. Pon encima el pollo cremoso, el jitomate y la zanahoria rallada.",
   "Dobla los dos lados hacia adentro y enróllala apretada, de abajo hacia arriba. Córtala a la mitad en diagonal y sirve."],
 "porcoes8": ["100 g de pollo · ½ tortilla · ensalada",
              "120 g de pollo · 1 tortilla · ensalada",
              "130 g de pollo · 1 tortilla · ensalada",
              "150 g de pollo · 1 tortilla · 1 cucharada copeteada de yogur",
              "150 g de pollo · 1 tortilla · ensalada",
              "170 g de pollo · 1 tortilla grande · ensalada",
              "200 g de pollo · 2 tortillas · ensalada",
              "220 g de pollo · 2 tortillas · ensalada"],
 "dica": "Cambiar la mayonesa por yogur natural corta buena parte de las calorías y además suma proteína. El pollo deshebrado se reparte bien y da la sensación de un relleno generoso con poca grasa, y la tortilla integral tiene más fibra que el pan blanco, deteniendo el hambre por más tiempo.",
},
{
 "nome": "Salmón al horno con verduras",
 "hook": "Todo en una sola charola: el pescado más fino para tu corazón, dorado junto con verduras coloridas.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 490,
 "ings": ["1 filete de salmón (unos 150 g)", "1 papa pequeña en rebanadas",
          "1 calabacín en rodajas", "½ pimiento en tiras", "jitomates cherry",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y romero al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta la papa en rebanadas delgadas — así se hornea en el mismo tiempo que el pescado.",
   "En una charola, reparte la papa, el calabacín, el pimiento y los jitomates cherry. Sazona con sal, pimienta, romero y la mitad del aceite de oliva, y mezcla.",
   "Hornea 10 minutos, solo para que la papa empiece a suavizarse.",
   "Saca la charola, abre un espacio en medio y pon el salmón. Sazona el pescado con sal, pimienta, el jugo de limón y el resto del aceite de oliva.",
   "Regrésalo al horno otros 15 minutos, hasta que el salmón se ponga más claro y se separe en láminas al picarlo con un tenedor. Sírvelo directo de la charola o en el plato."],
 "porcoes8": ["120 g de salmón · ½ papa · verduras",
              "150 g de salmón · 1 papa pequeña · verduras",
              "150 g de salmón · 1 papa · verduras",
              "170 g de salmón · 1 papa · un poco de aceite de oliva",
              "170 g de salmón · 1 papa · verduras",
              "200 g de salmón · 1 papa grande · verduras",
              "220 g de salmón · 1 papa grande · un poco de aceite de oliva",
              "250 g de salmón · 2 papas pequeñas · un poco de aceite de oliva"],
 "dica": "El salmón es rico en grasa buena (omega-3), que ayuda a tu corazón y además te deja muy satisfecha. Hornear todo junto en la misma charola usa casi nada de aceite y deja las verduras con un sabor concentrado — un plato completo, bonito y ligero con el mínimo esfuerzo.",
},
{
 "nome": "Pastel de camote con carne molida magra",
 "hook": "El consuelo de un pastel de carne cremoso, pero con puré de camote y carne magra — pura satisfacción, sin culpa.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 460,
 "ings": ["2 camotes medianos", "250 g de carne molida magra de res",
          "1 cebolla, picada", "1 diente de ajo, picado", "1 jitomate, picado",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto",
          "1 cucharada de queso rallado bajo en grasa"],
 "passos": [
   "Pela los camotes, córtalos en trozos y cuécelos en agua hirviendo 15 minutos, hasta que queden muy suaves. Escúrrelos y aplástalos con un tenedor, con una pizca de sal, hasta que quede un puré terso.",
   "En un sartén, calienta el aceite de oliva y fríe la cebolla y el ajo a fuego medio, revolviendo, 2 minutos, hasta que se pongan transparentes.",
   "Agrega la carne molida y revuelve, deshaciendo los trozos con la cuchara, hasta que pierda todo el color rosado.",
   "Agrega el jitomate, sal y pimienta y cocina otros 5 minutos, hasta que reduzca. Apaga y agrega las hierbas frescas.",
   "En un refractario, reparte la mitad del puré en el fondo, la carne en medio y el resto del puré encima. Espolvorea el queso rallado.",
   "Hornea a fuego medio-alto (200 °C) por 15 minutos, hasta que la superficie quede ligeramente dorada. Sirve caliente."],
 "porcoes8": ["½ porción · ensalada verde",
              "1 porción · ensalada verde",
              "1 porción · ensalada verde",
              "1 porción · 1 cucharada más de queso",
              "1 porción + carne extra · ensalada",
              "1 porción grande · ensalada",
              "1 porción grande + carne · ensalada",
              "porción doble de carne · ensalada"],
 "dica": "El camote cambia la papa normal del pastel por una versión con más fibra, que te llena más. La carne magra da bastante proteína sin el exceso de grasa de los cortes grasosos. Es el tipo de plato reconfortante que engaña el antojo de comida chatarra.",
},
{
 "nome": "Ensalada completa con atún, garbanzos y huevo",
 "hook": "Sin estufa: una ensalada de verdad que llena el plato y la panza, armada en cinco minutos.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 400,
 "ings": ["1 lata de atún en agua, escurrida", "80 g de garbanzos cocidos",
          "2 huevos cocidos", "hojas verdes mixtas", "½ jitomate en cubos",
          "½ pepino en rodajas", "cebolla morada en rebanadas delgadas",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal y pimienta al gusto"],
 "passos": [
   "Cuece los huevos: ponlos en una olla con agua, deja que hierva y cuenta 9 minutos. Ponlos bajo el chorro de agua fría, pélalos y córtalos a la mitad.",
   "Escurre bien el atún y los garbanzos.",
   "En un plato o en un tazón grande, reparte las hojas verdes. Encima, acomoda el jitomate, el pepino y la cebolla.",
   "Pon el atún en el centro, los garbanzos alrededor y los huevos a los lados.",
   "Rocía con el aceite de oliva y el jugo de limón, sazona con sal y pimienta y sirve."],
 "porcoes8": ["½ lata de atún · 55 g de garbanzos · 1 huevo",
              "1 lata de atún · 80 g de garbanzos · 2 huevos",
              "1 lata de atún · 80 g de garbanzos · 2 huevos",
              "1 lata de atún · 110 g de garbanzos · 2 huevos · aguacate",
              "1 lata de atún · 110 g de garbanzos · 2 huevos",
              "1½ latas de atún · 125 g de garbanzos · 2 huevos",
              "1½ latas de atún · 165 g de garbanzos · 3 huevos · aguacate",
              "2 latas de atún · 165 g de garbanzos · 3 huevos · aguacate"],
 "dica": "Es una bomba de proteína (atún, huevo y garbanzos juntos) que casi no da trabajo. La proteína y la fibra de la ensalada detienen el hambre por horas, y como todo es fresco y no está cocinado en aceite, el plato se mantiene ligero aunque sea generoso.",
},
{
 "nome": "Strogonoff de pollo ligero con arroz",
 "hook": "El mismo strogonoff cremoso, pero cambiando la crema por yogur — el mismo gusto, la mitad de las calorías.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "70 g de champiñones en rebanadas", "1 cucharada de puré de tomate",
          "4 cucharadas de yogur natural sin azúcar",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y mostaza al gusto",
          "arroz blanco o integral para servir"],
 "passos": [
   "Sazona los cubos de pollo con sal y pimienta.",
   "Calienta el aceite de oliva en una olla a fuego medio-alto y dora los cubos de pollo por fuera, revolviendo de vez en cuando, 5 minutos. Sácalos y resérvalos.",
   "En la misma olla, fríe la cebolla y el ajo 2 minutos, revolviendo, hasta que se pongan transparentes. Agrega los champiñones y cocina otros 3 minutos, hasta que se ablanden.",
   "Regresa el pollo a la olla, agrega el puré de tomate y la mostaza, mezcla y déjalo 3 minutos.",
   "Apaga el fuego. Solo entonces agrega el yogur y revuelve — fuera del fuego no se corta (no se hace grumos). Prueba la sal y sirve sobre el arroz."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz",
              "1 porción · 4 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz · pollo extra",
              "1 porción · 5 cucharadas de arroz",
              "1 porción grande · 6 cucharadas de arroz",
              "1 porción + pollo · 7 cucharadas de arroz",
              "porción doble · 8 cucharadas de arroz"],
 "dica": "El secreto es el yogur natural en lugar de la crema: conservas la cremosidad y el sabor, pero cortas grasa y encima ganas proteína. El pollo aporta saciedad y los champiñones agregan volumen y sabor con muy pocas calorías.",
},
{
 "nome": "Pechuga de pavo con cuscús de verduras",
 "hook": "El cuscús queda listo solo con agua caliente — la comida más rápida y esponjosa para los días ocupados.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 430,
 "ings": ["1 filete de pechuga de pavo (unos 150 g)",
          "90 g de cuscús (el de bolitas pequeñas)", "120 ml de agua caliente",
          "½ calabacín en cubos pequeños", "½ pimiento en cubos pequeños",
          "jitomates cherry, cortados", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y menta al gusto"],
 "passos": [
   "Pon el cuscús en un tazón, agrega una pizca de sal y el agua caliente (el agua debe cubrir el cuscús como un dedo). Tápalo con un plato y déjalo 5 minutos.",
   "Suelta el cuscús con un tenedor, recorriendo todo el tazón, hasta que quede esponjoso y sin pegarse.",
   "Sazona la pechuga de pavo con sal y pimienta. Calienta un sartén antiadherente con la mitad del aceite de oliva y asa el pavo de 3 a 4 minutos de cada lado, hasta que quede dorado y blanco por dentro.",
   "Agrega al cuscús los cubos crudos de calabacín, pimiento y jitomate, el resto del aceite de oliva, el jugo de limón y la menta. Mezcla.",
   "Sirve el cuscús con la pechuga de pavo rebanada encima."],
 "porcoes8": ["120 g de pavo · 60 g de cuscús · verduras",
              "150 g de pavo · 90 g de cuscús · verduras",
              "150 g de pavo · 90 g de cuscús · verduras",
              "170 g de pavo · 115 g de cuscús · un poco de aceite de oliva",
              "170 g de pavo · 115 g de cuscús · verduras",
              "200 g de pavo · 130 g de cuscús · verduras",
              "220 g de pavo · 175 g de cuscús · un poco de aceite de oliva",
              "250 g de pavo · 175 g de cuscús · un poco de aceite de oliva"],
 "dica": "La pechuga de pavo es todavía más magra que el pollo y está llena de proteína. El cuscús se cocina solo con agua caliente, sin grasa, y mezclado con verduras crudas se vuelve un plato ligero, colorido y refrescante — perfecto para la comida.",
},
{
 "nome": "Chili de carne con frijoles negros",
 "hook": "Un guisado picosito y sustancioso que reconforta el alma — frijoles, carne magra y mucho sabor en una sola olla.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 450,
 "ings": ["300 g de carne molida magra de res",
          "170 g de frijoles negros cocidos (o de lata, escurridos)",
          "1 cebolla, picada", "2 dientes de ajo, picados",
          "1 pimiento, picado", "2 jitomates, picados (o salsa de tomate)",
          "1 cucharadita de aceite de oliva", "1 cucharadita de comino molido",
          "sal, pimienta y paprika al gusto"],
 "passos": [
   "Calienta el aceite de oliva en una olla a fuego medio. Fríe la cebolla, el ajo y el pimiento 3 minutos, revolviendo, hasta que se suavicen.",
   "Agrega la carne molida y revuelve, deshaciendo los trozos con la cuchara, hasta que pierda todo el color rosado.",
   "Agrega el comino, la paprika, sal y pimienta y mezcla bien, para que las especias suelten su aroma.",
   "Agrega los jitomates picados y los frijoles negros. Si se seca demasiado, agrega media taza de agua.",
   "Baja el fuego y déjalo cocinar a fuego bajo de 15 a 20 minutos, revolviendo de vez en cuando, hasta que espese como un guisado cremoso. Sírvelo solo o con un poco de arroz."],
 "porcoes8": ["½ porción · ensalada",
              "1 porción · ensalada",
              "1 porción · 2 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción grande · 4 cucharadas de arroz",
              "porción grande · 5 cucharadas de arroz",
              "porción doble · 6 cucharadas de arroz"],
 "dica": "Los frijoles negros son ricos en fibra y proteína vegetal, y hacen que el guisado rinda mucho más con pocas calorías. La carne magra aporta la proteína que sacia, y las especias dan un sabor intenso sin necesidad de grasa.",
},
{
 "nome": "Pasta integral en salsa de jitomate con albóndigas de pavo",
 "hook": "Sí, puedes comer pasta y aun así bajar de peso — en la versión integral, con salsa fresca y albóndigas magras.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 480,
 "ings": ["150 g de pasta integral (peso en seco)",
          "250 g de carne molida de pechuga de pavo (o de pollo)",
          "3 jitomates maduros, picados (o salsa de tomate)",
          "1 cebolla, picada", "2 dientes de ajo, picados", "1 huevo",
          "2 cucharadas de avena", "1 cucharadita de aceite de oliva",
          "sal, pimienta y albahaca al gusto"],
 "passos": [
   "En un tazón, mezcla la carne molida de pavo, el huevo, la avena, la mitad del ajo, sal y pimienta. Amasa con las manos hasta que se integre y forma bolitas del tamaño de una nuez.",
   "Calienta el aceite de oliva en una olla amplia y dora las albóndigas por todos lados, volteándolas con cuidado, unos 5 minutos. Sácalas y resérvalas.",
   "En la misma olla, fríe la cebolla y el resto del ajo 2 minutos. Agrega los jitomates picados, sal y pimienta y cocina 10 minutos, revolviendo, hasta que se haga una salsa.",
   "Regresa las albóndigas a la salsa y déjalas cocinar otros 8 minutos, hasta que estén cocidas por dentro.",
   "Mientras tanto, cuece la pasta en agua hirviendo con sal el tiempo del paquete, hasta que quede cocida pero todavía firme. Escúrrela.",
   "Mezcla la pasta con la salsa y las albóndigas, espolvorea la albahaca y sirve."],
 "porcoes8": ["⅔ porción de pasta · 3 albóndigas",
              "1 porción · 4 albóndigas",
              "1 porción · 4 albóndigas",
              "1 porción · 5 albóndigas",
              "1 porción · 5 albóndigas",
              "1 porción grande · 6 albóndigas",
              "porción grande · 7 albóndigas",
              "porción doble · 8 albóndigas"],
 "dica": "La pasta integral tiene más fibra y te llena más que la normal, y las albóndigas de pavo dan proteína magra en lugar de carne grasosa. Una salsa de jitomate hecha al momento, sin azúcar y sin nada procesado, mantiene el plato sabroso y mucho más ligero.",
},
{
 "nome": "Omelette relleno de verduras",
 "hook": "Una comida ligera para los días sin tiempo: esponjoso, caliente y lleno de proteína, listo en el sartén en diez minutos.",
 "tempo": "12 min", "rende": "1 porción", "kcal_base": 360,
 "ings": ["3 huevos", "½ jitomate en cubos pequeños",
          "½ pimiento en cubos pequeños", "un puñado de espinaca",
          "1 cucharada de queso blanco en cubos",
          "1 cucharadita de aceite de oliva",
          "cebollín, sal y pimienta al gusto",
          "1 rebanada de pan integral (opcional)"],
 "passos": [
   "Rompe los huevos en un tazón, sazona con sal y pimienta y bátelos con un tenedor 30 segundos, hasta que queden parejos (bien mezclados).",
   "Calienta el aceite de oliva en un sartén antiadherente a fuego medio-bajo. Agrega el pimiento y la espinaca y revuelve 1 minuto, solo hasta que la espinaca se marchite (se ponga suave).",
   "Reparte las verduras por el sartén y vierte los huevos encima. Déjalo 1 minuto sin revolver, hasta que la orilla cuaje.",
   "Pon el jitomate y el queso sobre la mitad del omelette. Con una espátula, dobla la otra mitad encima, formando una media luna.",
   "Déjalo un minuto más, solo hasta que el queso se suavice. Espolvorea cebollín y sirve, con la rebanada de pan si quieres."],
 "porcoes8": ["2 huevos · verduras · ½ pan",
              "3 huevos · verduras · 1 rebanada de pan",
              "3 huevos · verduras · 1 rebanada de pan",
              "3 huevos · 2 cucharadas de queso · 1 rebanada de pan",
              "3 huevos · verduras · 1 rebanada de pan",
              "4 huevos · verduras · 1 rebanada de pan",
              "4 huevos · 2 cucharadas de queso · 2 rebanadas de pan",
              "5 huevos · verduras · 2 rebanadas de pan"],
 "dica": "Los huevos son una proteína de muy alta calidad y muy saciante — quien come huevo en la comida suele picar menos por la tarde. Relleno de verduras, el omelette gana volumen, color y fibra casi sin calorías extra, volviéndose una comida completa y rápida.",
},
{
 "nome": "Bistec de res magro con arroz, frijoles y col",
 "hook": "El plato de todos los días, como nos gusta — solo que en la medida correcta, con carne magra y col apenas salteada.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 500,
 "ings": ["1 bistec de res magro (unos 130 g)", "4 cucharadas de arroz cocido",
          "4 cucharadas de frijoles cocidos",
          "2 hojas de col cortadas en tiras delgadas",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal y pimienta al gusto"],
 "passos": [
   "Sazona el bistec con sal y pimienta por los dos lados.",
   "Calienta un sartén antiadherente a fuego alto con unas gotas de aceite de oliva. Pon el bistec y déjalo de 2 a 3 minutos de cada lado, sin moverlo, hasta que quede dorado por fuera y al término que te guste por dentro.",
   "Corta la col en tiras muy delgadas. En un sartén, calienta el resto del aceite de oliva y fríe el ajo 30 segundos, solo hasta que huela rico.",
   "Agrega la col y revuelve a fuego alto de 1 a 2 minutos, solo hasta que se marchite un poco (se ponga más suave) y siga verde. Sazona con sal.",
   "Calienta el arroz y los frijoles. Arma el plato con el arroz, los frijoles, el bistec y la col a un lado."],
 "porcoes8": ["100 g de carne · 3 cucharadas de arroz · 3 cucharadas de frijoles",
              "130 g de carne · 4 cucharadas de arroz · 4 cucharadas de frijoles",
              "130 g de carne · 5 cucharadas de arroz · 4 cucharadas de frijoles",
              "150 g de carne · 5 cucharadas de arroz · 5 cucharadas de frijoles",
              "150 g de carne · 5 cucharadas de arroz · 5 cucharadas de frijoles",
              "170 g de carne · 6 cucharadas de arroz · 5 cucharadas de frijoles",
              "200 g de carne · 7 cucharadas de arroz · 6 cucharadas de frijoles",
              "220 g de carne · 8 cucharadas de arroz · 6 cucharadas de frijoles"],
 "dica": "Puedes comer el plato tradicional de arroz, frijoles y carne sin salirte de tu dieta: la clave es elegir un corte magro, medir el arroz y los frijoles y ser generosa con la col, que llena el plato de fibra y casi nada de calorías. Los frijoles además aportan fibra y proteína que detienen el hambre.",
},
{
 "nome": "Bistec encebollado con puré de papa y ensalada",
 "hook": "El bistec con cebolla dorada es puro consuelo — sobre un puré ligero y junto a una ensalada fresca, entra justo en tu dieta.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 500,
 "ings": ["1 bistec de res magro (unos 130 g)", "2 papas medianas",
          "1 cebolla en rebanadas", "1 cucharadita de aceite de oliva",
          "sal y pimienta al gusto",
          "hojas verdes y jitomate para la ensalada", "jugo de ½ limón"],
 "passos": [
   "Pela y cuece las papas en agua hirviendo 15 minutos, hasta que queden muy suaves. Escúrrelas y aplástalas con un tenedor, con una pizca de sal, hasta que quede un puré terso. Si lo quieres más cremoso, agrega un poco del agua de la cocción.",
   "Sazona el bistec con sal y pimienta por los dos lados.",
   "Calienta un sartén antiadherente a fuego alto con unas gotas de aceite de oliva. Pon el bistec y déjalo de 2 a 3 minutos de cada lado, sin moverlo, hasta que quede dorado por fuera y al término que te guste. Sácalo y resérvalo.",
   "En el mismo sartén, pon las rebanadas de cebolla y el resto del aceite de oliva. Revuelve a fuego medio 5 minutos, hasta que la cebolla quede suave y dorada (bien dulcecita).",
   "Cubre el bistec con la cebolla dorada. Arma el plato con el puré, el bistec encebollado y una ensalada verde aliñada con limón."],
 "porcoes8": ["100 g de carne · ½ porción de puré · ensalada",
              "130 g de carne · 1 porción de puré · ensalada",
              "130 g de carne · 1 porción de puré · ensalada",
              "150 g de carne · 1 porción de puré · ensalada",
              "150 g de carne · 1 porción de puré · ensalada",
              "170 g de carne · 1 porción grande de puré · ensalada",
              "200 g de carne · porción grande de puré · ensalada",
              "220 g de carne · porción doble de puré · ensalada"],
 "dica": "Elegir un corte magro y asarlo sin aceite convierte al bistec en casi proteína pura. La cebolla dorada aporta mucho sabor con muy pocas calorías y hace que no necesites salsas grasosas. Con el puré en la medida correcta y bastante ensalada, el plato satisface sin pesarte.",
},
{
 "nome": "Camarones salteados con verduras y arroz",
 "hook": "El camarón está listo en un abrir y cerrar de ojos y es de lo más ligero que hay — una comida rápida que se ve sofisticada.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 430,
 "ings": ["150 g de camarones limpios", "4 cucharadas de arroz integral cocido",
          "½ calabacín en medias lunas", "½ pimiento en tiras",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y perejil al gusto"],
 "passos": [
   "Sazona los camarones con sal, pimienta, el ajo y el jugo de limón. Déjalos tomar sabor 5 minutos.",
   "Calienta un sartén grande con la mitad del aceite de oliva a fuego alto. Agrega el calabacín y el pimiento y revuelve 3 minutos, hasta que queden tiernos pero todavía firmes. Sácalos y resérvalos.",
   "En el mismo sartén, pon el resto del aceite de oliva y los camarones. Saltéalos (revuelve a fuego alto) de 2 a 3 minutos, solo hasta que el camarón se ponga rosado y se enrosque. Cuidado con cocerlos de más, o quedan chiclosos.",
   "Regresa las verduras al sartén, agrega el arroz integral ya cocido y mezcla 1 minuto, solo para calentar todo.",
   "Espolvorea perejil y sirve de inmediato."],
 "porcoes8": ["120 g de camarones · 3 cucharadas de arroz · verduras",
              "150 g de camarones · 4 cucharadas de arroz · verduras",
              "150 g de camarones · 5 cucharadas de arroz · verduras",
              "170 g de camarones · 5 cucharadas de arroz · un poco de aceite de oliva",
              "170 g de camarones · 5 cucharadas de arroz · verduras",
              "200 g de camarones · 6 cucharadas de arroz · verduras",
              "220 g de camarones · 7 cucharadas de arroz · un poco de aceite de oliva",
              "250 g de camarones · 8 cucharadas de arroz · un poco de aceite de oliva"],
 "dica": "El camarón es casi todo proteína, con muy poca grasa y pocas calorías, así que puedes comer una porción generosa sin pesarte. Salteado rápido a fuego alto con verduras, conserva una textura firme y su sabor, en un plato ligero que está listo en minutos.",
},
{
 "nome": "Salteado ligero de pollo con arroz integral",
 "hook": "El clásico chino en casa, en versión magra: pollo en cubos y verduras crujientes en una salsa ligera y brillante.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 460,
 "ings": ["2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 pimiento en cubos", "1 cebolla en cubos",
          "1 tallo de apio en trozos (opcional)", "1 diente de ajo, picado",
          "1 cucharada de salsa de soya clara", "1 cucharadita de fécula de maíz",
          "1 cucharadita de aceite de oliva", "arroz integral para servir"],
 "passos": [
   "Sazona los cubos de pollo con un poco de la salsa de soya y el ajo. Déjalos tomar sabor 5 minutos.",
   "Disuelve la fécula de maíz en media taza de agua con el resto de la salsa de soya. Mezcla bien y resérvalo — eso es lo que va a espesar la salsa.",
   "Calienta un sartén grande con la mitad del aceite de oliva a fuego alto. Dora los cubos de pollo 5 minutos, revolviendo, hasta que queden blancos por dentro. Sácalos y resérvalos.",
   "En el mismo sartén, pon el resto del aceite de oliva y agrega el pimiento, la cebolla y el apio. Revuelve a fuego alto 3 minutos, hasta que queden tiernos pero todavía crujientes.",
   "Regresa el pollo, revuelve la mezcla de fécula y viértela en el sartén. Revuelve de 1 a 2 minutos, hasta que la salsa espese y quede brillante, cubriendo todo. Sirve sobre el arroz integral."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz",
              "1 porción · 4 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz · pollo extra",
              "1 porción · 5 cucharadas de arroz",
              "1 porción grande · 6 cucharadas de arroz",
              "1 porción + pollo · 7 cucharadas de arroz",
              "porción doble · 8 cucharadas de arroz"],
 "dica": "Hacerlo en casa te deja controlar el aceite y el azúcar que en los restaurantes se exceden. El pollo da proteína magra, las verduras entran crujientes con pocas calorías y apenas un toque de fécula da esa salsa bonita sin engordar el plato.",
},
{
 "nome": "Bowl mexicano con carne, frijoles negros y elote",
 "hook": "Todos los colores y sabores de México en un solo bowl — generoso, bien sazonado y sorprendentemente ligero.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 490,
 "ings": ["250 g de carne molida magra de res",
          "170 g de frijoles negros cocidos", "80 g de elote",
          "4 cucharadas de arroz cocido", "1 jitomate en cubos",
          "½ aguacate en rebanadas", "hojas verdes",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "comino, sal, pimienta y cilantro al gusto", "jugo de ½ limón"],
 "passos": [
   "Calienta el aceite de oliva en un sartén y fríe el ajo 30 segundos. Agrega la carne molida y revuelve, deshaciendo los trozos, hasta que pierda el color rosado.",
   "Sazona la carne con comino, sal y pimienta y cocina otros 3 minutos. Agrega los frijoles negros y el elote y calienta 2 minutos.",
   "En un bowl, haz una cama de hojas verdes y pon el arroz a un lado.",
   "Acomoda encima la carne con frijoles y elote, el jitomate y las rebanadas de aguacate.",
   "Rocía con el jugo de limón, espolvorea cilantro y sirve."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz · ¼ aguacate",
              "1 porción · 4 cucharadas de arroz · ¼ aguacate",
              "1 porción · 4 cucharadas de arroz · ½ aguacate",
              "1 porción · 5 cucharadas de arroz · ½ aguacate",
              "1 porción · 5 cucharadas de arroz · ½ aguacate",
              "1 porción grande · 6 cucharadas de arroz · ½ aguacate",
              "porción grande · 7 cucharadas de arroz · ½ aguacate",
              "porción doble · 8 cucharadas de arroz · aguacate"],
 "dica": "Es un plato completo en un solo bowl: proteína de la carne, fibra de los frijoles y el elote, y la grasa buena del aguacate, que aporta cremosidad y saciedad. Bien sazonado, satisface el antojo de comida de antojito sin el exceso de grasa.",
},
{
 "nome": "Ensalada de pollo a la plancha con mango",
 "hook": "Dulce, salada y refrescante: el pollo caliente de la plancha se encuentra con el mango dulce en una ensalada que no se siente dieta.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 400,
 "ings": ["1 filete de pechuga de pollo (unos 130 g)", "hojas verdes mixtas",
          "½ mango en cubos", "½ pepino en rodajas",
          "cebolla morada en rebanadas delgadas",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y menta al gusto"],
 "passos": [
   "Sazona el pollo con sal y pimienta. Calienta un sartén antiadherente a fuego medio-alto y asa el filete de 4 a 5 minutos de cada lado, hasta que quede dorado y blanco por dentro. Déjalo enfriar un poco y córtalo en tiras.",
   "Pela el mango y corta la pulpa en cubos. Corta el pepino en rodajas y la cebolla en rebanadas muy delgadas.",
   "En un tazón grande o plato hondo, reparte las hojas verdes.",
   "Acomoda encima los cubos de mango, el pepino, la cebolla y las tiras de pollo.",
   "Haz el aderezo mezclando el aceite de oliva, el jugo de limón, sal y pimienta. Rocíalo sobre la ensalada, espolvorea menta y sirve."],
 "porcoes8": ["100 g de pollo · ¼ mango · ensalada",
              "130 g de pollo · ½ mango · ensalada",
              "130 g de pollo · ½ mango · ensalada",
              "150 g de pollo · ½ mango · un poco de aceite de oliva",
              "150 g de pollo · ½ mango · ensalada",
              "170 g de pollo · ½ mango · 1 cucharada de nueces",
              "200 g de pollo · 1 mango · nueces",
              "220 g de pollo · 1 mango · nueces"],
 "dica": "El mango entra como dulce natural, sin azúcar añadida, y satisface el antojo de algo dulce dentro de una comida salada. El pollo a la plancha da la proteína que llena, y el volumen de hojas y verduras llena el plato con muy pocas calorías. Una ensalada que es comida completa.",
},
{
 "nome": "Filete de pollo en curry ligero con arroz",
 "hook": "Una salsa dorada y aromática que transforma el pollo de siempre — cremosa sin crema, usando leche de coco light.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "1 cucharadita de curry en polvo",
          "120 ml de leche de coco light (o leche normal)",
          "1 jitomate, picado", "1 cucharadita de aceite de oliva",
          "sal y pimienta al gusto", "arroz para servir"],
 "passos": [
   "Sazona los cubos de pollo con sal, pimienta y la mitad del curry.",
   "Calienta el aceite de oliva en una olla a fuego medio y dora los cubos de pollo por fuera, revolviendo, 5 minutos. Sácalos y resérvalos.",
   "En la misma olla, fríe la cebolla y el ajo 2 minutos. Agrega el resto del curry y revuelve 30 segundos, solo para que la especia suelte su olor.",
   "Agrega el jitomate y cocina 3 minutos, hasta que se deshaga. Regresa el pollo y agrega la leche de coco.",
   "Cocina a fuego bajo de 8 a 10 minutos, revolviendo de vez en cuando, hasta que la salsa espese y el pollo quede suave. Sirve sobre el arroz."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz",
              "1 porción · 4 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz · pollo extra",
              "1 porción · 5 cucharadas de arroz",
              "1 porción grande · 6 cucharadas de arroz",
              "1 porción + pollo · 7 cucharadas de arroz",
              "porción doble · 8 cucharadas de arroz"],
 "dica": "La leche de coco light da cremosidad a la salsa con mucha menos grasa que la crema. El curry la perfuma y da la sensación de un plato especial, lo que te ayuda a comer despacio y quedar satisfecha con una porción controlada de pollo y arroz.",
},
{
 "nome": "Sardinas al horno con papa y ensalada",
 "hook": "Baratas, llenas de omega-3 y listas en minutos — las sardinas son de las mejores amigas de quien baja de peso sin gastar mucho.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 450,
 "ings": ["3 o 4 sardinas frescas limpias (o 1 lata de sardinas en agua)",
          "1 papa pequeña en rebanadas", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "1 diente de ajo, picado",
          "sal, pimienta y orégano al gusto",
          "hojas verdes y jitomate para la ensalada"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta la papa en rebanadas delgadas, sazona con sal y la mitad del aceite de oliva y repártela en una charola.",
   "Hornea la papa 10 minutos, para empezar a suavizarla.",
   "Sazona las sardinas con sal, pimienta, ajo, orégano y el jugo de limón.",
   "Saca la charola, pon las sardinas entre las papas y rocía con el resto del aceite de oliva.",
   "Regrésala al horno otros 15 minutos, hasta que las sardinas queden doradas y la papa suave. Sirve con una ensalada verde fresca a un lado.",
   "Si usas sardinas de lata, sáltate el horno para el pescado: solo hornea la papa y arma el plato con las sardinas escurridas y la ensalada."],
 "porcoes8": ["2 sardinas · ½ papa · ensalada",
              "3 sardinas · 1 papa pequeña · ensalada",
              "3 sardinas · 1 papa · ensalada",
              "4 sardinas · 1 papa · un poco de aceite de oliva",
              "4 sardinas · 1 papa · ensalada",
              "4 sardinas · 1 papa grande · ensalada",
              "5 sardinas · 1 papa grande · un poco de aceite de oliva",
              "6 sardinas · 2 papas pequeñas · ensalada"],
 "dica": "La sardina es un pescadito poderoso: mucho omega-3 (la grasa buena que le hace bien a tu corazón), proteína y calcio, por un precio muy bajo. Horneada con un poco de papa y una ensalada fresca, se vuelve una comida completa, nutritiva y barata.",
},
{
 "nome": "Berenjena rellena de carne molida",
 "hook": "La propia berenjena se convierte en el recipiente — rellena de carne sazonada y gratinada arriba, es bonita y engaña cualquier antojo de comilona.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 420,
 "ings": ["1 berenjena grande", "200 g de carne molida magra de res",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "1 jitomate, picado", "1 cucharadita de aceite de oliva",
          "2 cucharadas de queso rallado bajo en grasa",
          "sal, pimienta y perejil al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta la berenjena a la mitad a lo largo. Con una cuchara, saca parte del centro, formando dos barcas. Pica lo que sacaste.",
   "Pon las barcas en una charola, rocía con un poco de aceite de oliva y hornea 10 minutos, solo para suavizarlas.",
   "Mientras tanto, en un sartén, fríe la cebolla y el ajo en el resto del aceite de oliva 2 minutos. Agrega la carne molida y revuelve hasta que pierda el color rosado.",
   "Agrega el jitomate, el centro picado de la berenjena, sal y pimienta y cocina 5 minutos, hasta que quede un relleno suave.",
   "Rellena las barcas de berenjena con la carne, espolvorea el queso rallado encima y regrésalas al horno 15 minutos, hasta que gratine (el queso se derrite y se dora). Espolvorea perejil y sirve."],
 "porcoes8": ["½ berenjena · ensalada",
              "1 berenjena rellena · ensalada",
              "1 berenjena · 2 cucharadas de arroz",
              "1 berenjena · carne extra · ensalada",
              "1 berenjena · carne extra · 2 cucharadas de arroz",
              "1 berenjena grande · 3 cucharadas de arroz",
              "1 berenjena grande · carne extra · 3 cucharadas de arroz",
              "2 mitades · carne extra · 4 cucharadas de arroz"],
 "dica": "La berenjena tiene mucha agua y fibra, así que llena el plato y el estómago con muy pocas calorías. Usarla como recipiente hace que la porción de carne rinda más, y el gratinado ligero da la sensación de un plato especial sin necesidad de mucho queso.",
},
{
 "nome": "Ensalada César fit con pollo a la plancha",
 "hook": "La ensalada César cremosa que te encanta, con un aderezo inteligente de yogur — toda la cremosidad, nada de culpa.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 400,
 "ings": ["1 filete de pollo asado en tiras (unos 130 g)",
          "hojas de lechuga romana", "1 rebanada de pan integral en cubos",
          "2 cucharadas de yogur natural sin azúcar", "1 cucharadita de mostaza",
          "1 cucharadita de queso rallado", "jugo de ½ limón",
          "1 diente de ajo, machacado", "sal y pimienta al gusto"],
 "passos": [
   "Sazona el pollo con sal y pimienta y ásalo en un sartén antiadherente 4 minutos de cada lado, hasta que quede dorado y blanco por dentro. Córtalo en tiras.",
   "Haz los crotones: reparte los cubos de pan integral en una charola y hornéalos a fuego medio 8 minutos, hasta que queden crujientes (o tuéstalos en un sartén sin aceite).",
   "Prepara el aderezo: en un tazón pequeño, mezcla el yogur, la mostaza, el queso rallado, el jugo de limón, el ajo machacado, sal y pimienta, hasta que quede una crema.",
   "Rompe la lechuga con las manos y ponla en un tazón grande. Rocía con el aderezo y revuelve para cubrir las hojas.",
   "Pon encima las tiras de pollo y los crotones y sirve de inmediato, para que el pan siga crujiente."],
 "porcoes8": ["100 g de pollo · ensalada · pocos crotones",
              "130 g de pollo · ensalada · crotones",
              "130 g de pollo · ensalada · crotones",
              "150 g de pollo · ensalada · 1 cucharada más de queso",
              "150 g de pollo · ensalada · crotones",
              "170 g de pollo · ensalada · crotones",
              "200 g de pollo · ensalada · crotones extra",
              "220 g de pollo · ensalada · crotones extra"],
 "dica": "El aderezo César tradicional es una bomba de mayonesa y aceite. Cambiarlo por yogur con mostaza y limón conserva la cremosidad y el sabor fuerte con mucha menos grasa. El pollo a la plancha convierte la ensalada en una comida de verdad, llena de proteína.",
},
{
 "nome": "Tiras de res con pimiento y arroz",
 "hook": "Tiras delgadas de res salteadas con pimientos coloridos — aromáticas, bien sazonadas y listas en el sartén en minutos.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["250 g de res magra en tiras delgadas",
          "1 pimiento rojo en tiras", "1 pimiento amarillo en tiras",
          "1 cebolla en tiras", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "comino, sal, pimienta y cilantro al gusto", "arroz para servir"],
 "passos": [
   "Sazona las tiras de res con sal, pimienta, comino, el ajo y el jugo de limón. Déjalas tomar sabor 10 minutos.",
   "Calienta un sartén grande con la mitad del aceite de oliva a fuego alto. Pon la carne poco a poco (no toda de golpe, o suelta agua) y dórala rápido, revolviendo, 3 minutos. Sácala y resérvala.",
   "En el mismo sartén, con el resto del aceite de oliva, agrega la cebolla y los pimientos. Revuelve a fuego alto 4 minutos, hasta que queden tiernos pero todavía firmes y coloridos.",
   "Regresa la carne al sartén y mezcla 1 minuto, solo para juntar los sabores.",
   "Espolvorea cilantro y sirve sobre una porción de arroz. También queda excelente enrollado en una tortilla integral."],
 "porcoes8": ["½ porción · 3 cucharadas de arroz",
              "1 porción · 4 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz",
              "1 porción · 5 cucharadas de arroz · carne extra",
              "1 porción · 5 cucharadas de arroz",
              "1 porción grande · 6 cucharadas de arroz",
              "1 porción + carne · 7 cucharadas de arroz",
              "porción doble · 8 cucharadas de arroz"],
 "dica": "Cortar la carne en tiras delgadas rinde más: una porción pequeña se ve como mucho más en el plato. Salteada rápido a fuego alto con pimientos, queda jugosa y llena de sabor sin necesidad de una salsa grasosa. Los pimientos aportan color, vitaminas y fibra por casi nada de calorías.",
},
{
 "nome": "Hamburguesa casera de res magra con ensalada",
 "hook": "La hamburguesa que mata el antojo y aun así te ayuda a bajar de peso — hecha en casa con carne magra, sin el pan grasoso.",
 "tempo": "20 min", "rende": "2 porciones", "kcal_base": 440,
 "ings": ["250 g de carne molida magra de res", "½ cebolla, finamente picada",
          "1 diente de ajo, picado", "sal, pimienta y perejil al gusto",
          "1 cucharadita de aceite de oliva", "2 panes integrales para hamburguesa",
          "hojas de lechuga, jitomate y cebolla en rodajas para armarla"],
 "passos": [
   "En un tazón, mezcla la carne molida con la cebolla picada, el ajo, sal, pimienta y perejil. Amasa con las manos solo hasta que se integre, sin trabajarla de más (o la hamburguesa queda dura).",
   "Divide la carne en dos y forma dos discos, aplanándolos bien con las manos. Haz un hoyito ligero en el centro de cada uno con el pulgar — eso evita que se inflen en medio.",
   "Calienta un sartén antiadherente con unas gotas de aceite de oliva a fuego medio-alto. Pon las hamburguesas y déjalas de 3 a 4 minutos de cada lado, sin aplastarlas con la espátula, hasta que queden doradas por fuera y al término que te guste por dentro.",
   "Si quieres, tuesta ligeramente el pan integral, abierto, en el sartén.",
   "Ármala: pan, lechuga, la hamburguesa, el jitomate y la cebolla. Ciérrala y sirve. Para una versión todavía más ligera, come la hamburguesa sin pan, con una ensalada generosa a un lado."],
 "porcoes8": ["1 hamburguesa · sin pan · ensalada",
              "1 hamburguesa · ½ pan · ensalada",
              "1 hamburguesa · 1 pan · ensalada",
              "1 hamburguesa · 1 pan · ensalada",
              "1 hamburguesa grande · 1 pan · ensalada",
              "1 hamburguesa grande · 1 pan · ensalada",
              "2 hamburguesas · 1 pan · ensalada",
              "2 hamburguesas · 1 pan · ensalada"],
 "dica": "El problema de una hamburguesa de comida rápida es la carne grasosa, la salsa y la fritura. Hecha en casa con carne magra y asada sin aceite, se vuelve proteína pura. Comiéndola con bastante ensalada y poco (o nada de) pan, matas el antojo sin disparar tus calorías.",
},
{
 "nome": "Pescado blanco con verduras y cuscús",
 "hook": "Un filete blanco delicado sobre cuscús esponjoso — ligero, elegante y listo antes de que te des cuenta.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 420,
 "ings": ["1 filete de pescado blanco (merluza, bacalao o tilapia, unos 150 g)",
          "90 g de cuscús", "120 ml de agua caliente",
          "130 g de verduras picadas (ejotes, zanahoria, chícharos)",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y perejil al gusto"],
 "passos": [
   "Pon el cuscús en un tazón con una pizca de sal, cúbrelo con el agua caliente, tápalo con un plato y déjalo 5 minutos. Después suéltalo con un tenedor hasta que quede esponjoso.",
   "Cuece las verduras picadas en una vaporera o en un poco de agua hirviendo 5 minutos, hasta que queden tiernas pero todavía firmes. Escúrrelas.",
   "Sazona el pescado con sal, pimienta y el jugo de limón.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio. Pon el filete y déjalo de 3 a 4 minutos de cada lado, volteándolo con cuidado una vez, hasta que quede dorado y se separe con el tenedor.",
   "Mezcla las verduras con el cuscús. Arma el plato con el cuscús de verduras y el filete encima. Espolvorea perejil y sirve."],
 "porcoes8": ["120 g de pescado · 60 g de cuscús · verduras",
              "150 g de pescado · 90 g de cuscús · verduras",
              "150 g de pescado · 90 g de cuscús · verduras",
              "170 g de pescado · 115 g de cuscús · un poco de aceite de oliva",
              "170 g de pescado · 115 g de cuscús · verduras",
              "200 g de pescado · 130 g de cuscús · verduras",
              "220 g de pescado · 175 g de cuscús · un poco de aceite de oliva",
              "250 g de pescado · 175 g de cuscús · un poco de aceite de oliva"],
 "dica": "Los pescados blancos como la merluza y el bacalao son extremadamente magros y ligeros, ideales para la comida de quien quiere bajar de peso. El cuscús se cocina solo con agua caliente, sin grasa, y con las verduras se vuelve una guarnición colorida, esponjosa y llena de fibra.",
},
{
 "nome": "Brochetas de pollo y verduras con arroz",
 "hook": "Coloridas y divertidas de armar, las brochetas se cocinan parejo y le dan aire de fiesta a cualquier comida.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 450,
 "ings": ["2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 pimiento en cuadros", "1 cebolla en trozos",
          "1 calabacín en rodajas gruesas", "jitomates cherry",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y paprika al gusto", "arroz para servir",
          "palillos para brocheta"],
 "passos": [
   "Sazona los cubos de pollo con sal, pimienta, paprika y el jugo de limón. Déjalos tomar sabor 10 minutos.",
   "Arma las brochetas alternando un cubo de pollo, un trozo de pimiento, uno de cebolla, una rodaja de calabacín y un jitomate cherry, hasta llenar el palillo.",
   "Unta las brochetas con el aceite de oliva.",
   "Calienta un sartén grande o una plancha a fuego medio-alto. Pon las brochetas y voltéalas cada 3 minutos, hasta que el pollo quede dorado por todos lados y blanco por dentro (unos 12 minutos en total).",
   "Sirve las brochetas sobre una porción de arroz."],
 "porcoes8": ["1 brocheta · 3 cucharadas de arroz",
              "2 brochetas · 4 cucharadas de arroz",
              "2 brochetas · 5 cucharadas de arroz",
              "2 brochetas · 5 cucharadas de arroz · pollo extra",
              "2 brochetas · 5 cucharadas de arroz",
              "3 brochetas · 6 cucharadas de arroz",
              "3 brochetas · 7 cucharadas de arroz",
              "3 brochetas grandes · 8 cucharadas de arroz"],
 "dica": "Las brochetas te ayudan a controlar la porción de forma natural y además mezclan bastante verdura con la proteína. El pollo magro asado aporta saciedad sin grasa, y las verduras coloridas llenan el plato de fibra y vitaminas por casi nada de calorías.",
},
{
 "nome": "Ensalada fit de papa con huevo y atún",
 "hook": "La ensalada de papa cremosa de las fiestas, sin la mayonesa pesada — se vuelve una comida completa y ligera.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 410,
 "ings": ["2 papas medianas en cubos", "2 huevos cocidos",
          "1 lata de atún en agua, escurrida",
          "3 cucharadas de yogur natural sin azúcar", "1 cucharadita de mostaza",
          "cebolla morada y hierbas frescas picadas",
          "sal, pimienta y jugo de ½ limón al gusto"],
 "passos": [
   "Cuece los cubos de papa en agua hirviendo con sal de 12 a 15 minutos, hasta que queden suaves pero sin deshacerse (el tenedor entra fácil). Escúrrelos y déjalos enfriar un poco.",
   "Cuece los huevos 9 minutos, ponlos bajo el chorro de agua fría, pélalos y córtalos en trozos.",
   "Prepara el aderezo: mezcla el yogur, la mostaza, el jugo de limón, sal y pimienta en un tazón grande.",
   "Agrega al tazón la papa tibia, el atún escurrido, los huevos, la cebolla morada y las hierbas frescas.",
   "Mezcla con cuidado, para no deshacer la papa. Prueba la sal y sirve de inmediato o frío."],
 "porcoes8": ["½ porción · ½ lata de atún · 1 huevo",
              "1 porción · 1 lata de atún · 2 huevos",
              "1 porción · 1 lata de atún · 2 huevos",
              "1 porción · 1 lata de atún · 2 huevos · ensalada verde",
              "1 porción · 1 lata de atún · 2 huevos",
              "1 porción grande · 1½ latas de atún · 2 huevos",
              "porción grande · 1½ latas de atún · 3 huevos",
              "porción doble · 2 latas de atún · 3 huevos"],
 "dica": "Cambiar la mayonesa por yogur con mostaza corta mucha grasa y encima suma proteína. El atún y el huevo convierten una ensalada de papa en una comida completa y saciante. La papa fría además forma una fibra especial que alimenta a las bacterias buenas de tu intestino.",
},
{
 "nome": "Pollo rostizado al horno con verduras de raíz",
 "hook": "Pon todo en una charola y deja que el horno trabaje — el pollo sale dorado y las verduras quedan suaves y dulces.",
 "tempo": "45 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["2 muslos de pollo sin piel (o 2 filetes gruesos, unos 300 g)",
          "1 papa en trozos", "1 zanahoria en trozos grandes",
          "1 trozo de calabaza en cubos", "1 cebolla en gajos",
          "2 dientes de ajo", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y romero al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta la papa, la zanahoria, la calabaza y la cebolla en trozos grandes y parecidos, para que se rosticen parejo.",
   "En una charola grande, reparte las verduras y los dientes de ajo. Sazona con sal, pimienta, romero y la mitad del aceite de oliva, y mezcla con las manos.",
   "Sazona el pollo con sal, pimienta, el jugo de limón y el resto del aceite de oliva. Pon las piezas entre las verduras.",
   "Hornea de 35 a 40 minutos, volteando las verduras a la mitad del tiempo, hasta que el pollo quede dorado y cocido por dentro (el líquido que sale al picarlo tiene que salir transparente) y las verduras suaves.",
   "Sirve directo de la charola, con todos los jugos que se formaron en el fondo."],
 "porcoes8": ["1 muslo · ½ porción de verduras",
              "1 muslo · 1 porción de verduras",
              "1 muslo grande · 1 porción de verduras",
              "2 muslos · 1 porción de verduras",
              "2 muslos · 1 porción de verduras",
              "2 muslos · 1 porción grande de verduras",
              "2 muslos · porción grande de verduras",
              "3 muslos · porción doble de verduras"],
 "dica": "Rostizar sin piel y sin mucho aceite mantiene el pollo ligero, y los jugos que suelta sazonan las verduras sin necesidad de grasa. La calabaza y la zanahoria se endulzan al rostizarse, matando el antojo de algo dulce, y llenan el plato de fibra y vitaminas por pocas calorías.",
},
{
 "nome": "Milanesa de pollo fit al horno con ensalada",
 "hook": "La milanesa crujiente y con queso de tus sueños, horneada en lugar de frita — todo el gusto, nada de fritura.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 470,
 "ings": ["2 filetes delgados de pechuga de pollo (unos 300 g)", "1 huevo",
          "4 cucharadas de pan molido integral",
          "240 ml de salsa de tomate casera",
          "3 cucharadas de mozzarella baja en grasa rallada",
          "sal, pimienta y orégano al gusto",
          "hojas verdes para la ensalada"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Sazona los filetes delgados con sal y pimienta.",
   "Bate el huevo en un plato hondo. Pon el pan molido en otro plato, mezclado con orégano.",
   "Pasa cada filete primero por el huevo y después por el pan molido, presionando para cubrir bien los dos lados.",
   "Pon los filetes en una charola antiadherente (o cubierta con papel para hornear) y hornea 15 minutos, volteándolos a la mitad, hasta que el empanizado quede dorado y crujiente.",
   "Cubre cada filete con la salsa de tomate y el queso rallado. Regrésalo al horno otros 8 minutos, hasta que el queso se derrita y burbujee.",
   "Sirve con una ensalada verde fresca a un lado."],
 "porcoes8": ["100 g de pollo · poco queso · ensalada",
              "130 g de pollo · queso · ensalada",
              "150 g de pollo · queso · ensalada",
              "150 g de pollo · queso · 3 cucharadas de arroz",
              "150 g de pollo · queso · 3 cucharadas de arroz",
              "170 g de pollo · queso · 4 cucharadas de arroz",
              "200 g de pollo · queso · 5 cucharadas de arroz",
              "220 g de pollo · queso extra · 5 cucharadas de arroz"],
 "dica": "La milanesa engorda por la fritura y el exceso de queso. Empanizada con pan molido integral y horneada, sale crujiente con una fracción de la grasa. Un poco de queso bajo en grasa encima mata el antojo de un plato gratinado, y la ensalada equilibra el plato.",
},
{
 "nome": "Bowl de arroz, edamame y salmón",
 "hook": "Inspirado en el poke hawaiano: fresco, colorido y nutritivo, armado en un bowl y saciante sin pesarte.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 480,
 "ings": ["1 filete de salmón en cubos (unos 130 g)",
          "4 cucharadas de arroz cocido",
          "80 g de edamame cocido (frijol de soya verde)",
          "½ pepino en cubos pequeños", "½ zanahoria, rallada",
          "½ aguacate en rebanadas", "1 cucharada de salsa de soya clara",
          "semillas de ajonjolí, jugo de ½ limón y cebollín al gusto"],
 "passos": [
   "Cuece el edamame en agua hirviendo 4 minutos, escúrrelo y, si está en vaina, saca los granitos.",
   "Sazona los cubos de salmón con la salsa de soya y el jugo de limón. Déjalos tomar sabor 5 minutos. (Si lo prefieres cocido, asa rápido los cubos en un sartén 3 minutos.)",
   "En un bowl, pon el arroz de un lado como base.",
   "Acomoda encima, en grupos separados, el salmón, el edamame, el pepino, la zanahoria rallada y el aguacate.",
   "Rocía con un poco más de salsa de soya, espolvorea ajonjolí y cebollín y sirve."],
 "porcoes8": ["100 g de salmón · 3 cucharadas de arroz · ¼ aguacate",
              "130 g de salmón · 4 cucharadas de arroz · ½ aguacate",
              "130 g de salmón · 5 cucharadas de arroz · ½ aguacate",
              "150 g de salmón · 5 cucharadas de arroz · ½ aguacate",
              "150 g de salmón · 5 cucharadas de arroz · ½ aguacate",
              "170 g de salmón · 6 cucharadas de arroz · ½ aguacate",
              "200 g de salmón · 7 cucharadas de arroz · aguacate",
              "220 g de salmón · 8 cucharadas de arroz · aguacate"],
 "dica": "Es un plato completo y equilibrado: proteína y omega-3 del salmón, proteína vegetal del edamame, grasa buena del aguacate y la fibra de las verduras crudas. Armado en un bowl, se ve hermoso y saciante, probando que la comida saludable puede ser una fiesta para los ojos.",
},
{
 "nome": "Sopa sustanciosa de verduras con pollo deshebrado",
 "hook": "Una sopa que es comida de verdad: cargada de pollo y verduras, calienta el cuerpo y te llena sin pesarte.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 380,
 "ings": ["1 filete de pechuga de pollo (unos 150 g)", "1 papa en cubos",
          "1 zanahoria en cubos", "1 calabacín en cubos",
          "80 g de elote o chícharos", "1 cebolla, picada",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto", "1 litro de agua"],
 "passos": [
   "En una olla grande, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos, revolviendo, hasta que se pongan transparentes.",
   "Agrega el filete de pollo entero y el agua. Deja que hierva y cocina 15 minutos, hasta que el pollo esté cocido.",
   "Saca el pollo, déjalo enfriar un poco y deshébralo con dos tenedores. Resérvalo.",
   "En la misma agua, agrega la papa, la zanahoria, el calabacín y el elote. Sazona con sal y pimienta y cocina de 12 a 15 minutos, hasta que las verduras queden suaves.",
   "Regresa el pollo deshebrado a la olla, prueba la sal y cocina otros 3 minutos. Espolvorea hierbas frescas y sirve bien caliente."],
 "porcoes8": ["1 cucharón · pollo · sin papa extra",
              "2 cucharones · pollo · verduras",
              "2 cucharones · pollo · verduras",
              "2 cucharones · pollo extra · 1 rebanada de pan",
              "2 cucharones · pollo extra · 1 rebanada de pan",
              "3 cucharones · pollo · 1 rebanada de pan",
              "3 cucharones · pollo extra · 2 rebanadas de pan",
              "3 cucharones grandes · doble pollo · 2 rebanadas de pan"],
 "dica": "Las sopas son excelentes para bajar de peso: el volumen de líquido y verduras llena el estómago con muy pocas calorías, y el calor hace que comas más despacio. Con el pollo deshebrado deja de ser solo una entrada y se vuelve una comida completa, ligera y reconfortante.",
},
{
 "nome": "Panqueque salado de avena relleno de pollo",
 "hook": "La mezcla lleva solo huevo y avena, se bate en segundos y se convierte en un panqueque dorado relleno de pollo cremoso.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 400,
 "ings": ["1 huevo", "3 cucharadas de avena", "3 cucharadas de agua",
          "1 pizca de sal",
          "1 filete de pollo cocido y deshebrado (unos 100 g)",
          "2 cucharadas de salsa de tomate", "1 cucharada de yogur natural",
          "1 cucharadita de aceite de oliva", "orégano al gusto"],
 "passos": [
   "En un tazón, bate con un tenedor el huevo, la avena, el agua y la sal hasta que quede una mezcla pareja. Déjala reposar 3 minutos para que la avena absorba el líquido.",
   "Calienta un sartén antiadherente con la mitad del aceite de oliva a fuego medio. Vierte la mezcla y repártela girando el sartén, formando un disco delgado.",
   "Déjalo 2 minutos, hasta que la orilla se despegue, voltéalo con cuidado y dora el otro lado un minuto más. Saca el panqueque.",
   "Mezcla el pollo deshebrado con la salsa de tomate, el yogur y el orégano, y caliéntalo rápido en el sartén.",
   "Rellena el panqueque con el pollo, dóblalo a la mitad o enróllalo y sirve caliente, con una ensalada a un lado si quieres."],
 "porcoes8": ["1 panqueque · 80 g de pollo",
              "1 panqueque · 100 g de pollo",
              "1 panqueque · 120 g de pollo",
              "1 panqueque · 120 g de pollo · ensalada",
              "1 panqueque · 130 g de pollo · ensalada",
              "2 panqueques · 150 g de pollo",
              "2 panqueques · 170 g de pollo · ensalada",
              "2 panqueques · 200 g de pollo · ensalada"],
 "dica": "Una mezcla de huevo y avena cambia la harina blanca por fibra y proteína, llenándote mucho más que un panqueque normal. Relleno de pollo deshebrado y una salsa ligera de yogur, se vuelve una comida práctica, sabrosa y completa, buenísima también para la cena.",
},
{
 "nome": "Camarones al ajillo con verduras y arroz",
 "hook": "Camarones rosados dorados en ajo, llenando toda la cocina con su olor — una comida ligera y especial de fin de semana.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 430,
 "ings": ["150 g de camarones limpios", "4 cucharadas de arroz cocido",
          "100 g de brócoli y ejotes", "2 dientes de ajo, picados",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y perejil al gusto"],
 "passos": [
   "Seca bien los camarones con papel absorbente y sazónalos con sal, pimienta y el jugo de limón. Déjalos tomar sabor 5 minutos.",
   "Corta el brócoli en ramitos y los ejotes en trozos. Cuécelos en una vaporera o en un poco de agua hirviendo 4 minutos, hasta que queden verdes y tiernos pero todavía firmes. Escúrrelos.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio. Agrega el ajo picado y revuelve 30 segundos, solo hasta que huela rico y empiece a dorarse — cuidado con quemarlo, o amarga.",
   "Pon los camarones y saltéalos (revuelve a fuego medio-alto) de 2 a 3 minutos, solo hasta que se pongan rosados y se enrosquen. No los cuezas de más, o quedan chiclosos.",
   "Agrega las verduras y el arroz ya cocido al sartén y mezcla 1 minuto, para que tomen el sabor del ajo. Espolvorea perejil y sirve de inmediato."],
 "porcoes8": ["120 g de camarones · 3 cucharadas de arroz · verduras",
              "150 g de camarones · 4 cucharadas de arroz · verduras",
              "150 g de camarones · 5 cucharadas de arroz · verduras",
              "170 g de camarones · 5 cucharadas de arroz · un poco de aceite de oliva",
              "170 g de camarones · 5 cucharadas de arroz · verduras",
              "200 g de camarones · 6 cucharadas de arroz · verduras",
              "220 g de camarones · 7 cucharadas de arroz · un poco de aceite de oliva",
              "250 g de camarones · 8 cucharadas de arroz · un poco de aceite de oliva"],
 "dica": "El camarón es casi todo proteína, con muy poca grasa y pocas calorías, así que puedes servirte generosamente sin culpa. Dorado en ajo gana mucho sabor con apenas un poco de aceite de oliva, y con las verduras y una porción medida de arroz se vuelve un plato ligero que parece de restaurante.",
},
{
 "nome": "Albóndigas de res en salsa con puré de papa",
 "hook": "Albóndigas suaves en una salsa de jitomate con cuerpo, sobre un puré ligero — el abrazo caliente que tu dieta sí permite.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 490,
 "ings": ["250 g de carne molida magra de res", "1 huevo",
          "2 cucharadas de avena", "1 diente de ajo, picado",
          "3 jitomates, picados (o salsa de tomate)", "1 cebolla, picada",
          "2 papas medianas", "1 cucharadita de aceite de oliva",
          "sal, pimienta y albahaca al gusto"],
 "passos": [
   "Pela y cuece las papas en agua hirviendo 15 minutos, hasta que queden muy suaves. Escúrrelas y aplástalas con un tenedor, con una pizca de sal, hasta que quede un puré terso. Si lo quieres más cremoso, agrega un poco del agua de la cocción.",
   "En un tazón, mezcla la carne molida, el huevo, la avena, la mitad del ajo, sal y pimienta. Amasa con las manos y forma bolitas del tamaño de una nuez.",
   "Calienta el aceite de oliva en una olla y dora las albóndigas por todos lados, volteándolas con cuidado, 5 minutos. Sácalas y resérvalas.",
   "En la misma olla, fríe la cebolla y el resto del ajo 2 minutos. Agrega los jitomates, sal y pimienta y cocina 8 minutos, hasta que se haga una salsa.",
   "Regresa las albóndigas a la salsa y cocina otros 8 minutos, hasta que estén cocidas por dentro. Espolvorea albahaca.",
   "Sirve las albóndigas con la salsa sobre el puré de papa."],
 "porcoes8": ["3 albóndigas · ½ porción de puré",
              "4 albóndigas · 1 porción de puré",
              "4 albóndigas · 1 porción de puré",
              "5 albóndigas · 1 porción de puré",
              "5 albóndigas · 1 porción de puré",
              "6 albóndigas · 1 porción grande de puré",
              "7 albóndigas · porción grande de puré",
              "8 albóndigas · porción doble de puré"],
 "dica": "Las albóndigas usan avena en lugar de más pan, lo que las une con fibra en vez de almidón blanco. Hechas con carne magra y cocidas en la salsa (no fritas), quedan jugosas y ligeras. El puré de papa normal, en la medida correcta, es reconfortante y saciante.",
},
{
 "nome": "Risotto ligero de pollo y verduras",
 "hook": "La cremosidad del risotto sin mantequilla y sin exceso de queso — el arroz suelta su propia crema y envuelve al pollo y a las verduras.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 480,
 "ings": ["185 g de arroz (arborio o normal)",
          "2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 zanahoria en cubos pequeños", "75 g de chícharos",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva", "1 cucharada de queso rallado",
          "sal, pimienta y perejil al gusto",
          "caldo de verduras casero o agua caliente (unos 700 ml)"],
 "passos": [
   "Sazona los cubos de pollo con sal y pimienta. Calienta el aceite de oliva en una olla y dora el pollo 5 minutos, revolviendo. Sácalo y resérvalo.",
   "En la misma olla, fríe la cebolla y el ajo 2 minutos. Agrega el arroz y revuelve 1 minuto, solo para cubrir los granos con el sazón.",
   "Empieza a agregar el caldo caliente poco a poco, un cucharón a la vez, revolviendo todo el tiempo. Solo agrega más caldo cuando el anterior casi se haya secado.",
   "A la mitad de la cocción (unos 10 minutos), agrega la zanahoria y los chícharos. Sigue revolviendo y agregando caldo.",
   "Cuando el arroz esté suave y cremoso (unos 18 a 20 minutos en total), regresa el pollo, agrega el queso rallado y revuelve. Apaga, espolvorea perejil y sirve de inmediato."],
 "porcoes8": ["½ porción · pollo",
              "1 porción · pollo",
              "1 porción · pollo",
              "1 porción · pollo extra",
              "1 porción · pollo extra",
              "1 porción grande · pollo",
              "porción grande · pollo extra",
              "porción doble · pollo extra"],
 "dica": "El risotto tradicional lleva mucha mantequilla y queso. Aquí, la cremosidad viene del propio almidón del arroz que se suelta al revolver, con apenas un toque de queso. Con bastante pollo y verduras, el plato es sustancioso y satisface, probando que puedes comer risotto sin culpa.",
},
]
