# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). ESPANHOL (America Latina).

Traducao literal de `receitas_jantar_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md:
tratamento por "tu", vocabulario LatAm com foco Mexico (calabaza, jitomate,
ejotes, calabacin, carne molida, pollo deshebrado).
⛔ METRICO: g, ml, °C — como pt/de/fr. Os numeros vem do de/fr, NUNCA de
oz/cup de volta: e o que preserva a escada das 8 faixas.
⛔ O campo `prompt` NAO e replicado: a foto e a mesma do PT (fotos/066-100).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
Metas (kcal): 340/420/480/540 · 520/590/650/720
"""

RECEITAS = [
{
 "nome": "Sopa de calabaza con pollo deshebrado",
 "hook": "Cremosa, anaranjada y reconfortante — una sopa que calienta tu noche y aun así trae la proteína del pollo para llenarte de verdad.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 340,
 "ings": ["1 trozo grande de calabaza en cubos (unos 500 g)",
          "1 filete de pechuga de pollo (unos 150 g)", "1 cebolla, picada",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y jengibre rallado al gusto",
          "hierbas frescas para terminar", "1 litro de agua"],
 "passos": [
   "En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos, revolviendo, hasta que se pongan transparentes.",
   "Agrega los cubos de calabaza, el filete de pollo entero y el agua. Deja que hierva y cocina 20 minutos, hasta que la calabaza quede muy suave.",
   "Saca el pollo, déjalo enfriar un poco y deshébralo con dos tenedores. Resérvalo.",
   "Con una licuadora de inmersión (esa de bastón) o en una licuadora normal, licúa la calabaza con el caldo hasta que quede una crema tersa. Ten cuidado con el líquido caliente.",
   "Regresa la crema a la olla, agrega el pollo deshebrado, el jengibre, sal y pimienta y calienta 3 minutos. Sirve con hierbas frescas encima."],
 "porcoes8": ["1 cucharón · poco pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo · 1 rebanada de pan",
              "2 cucharones · pollo extra · 1 rebanada de pan",
              "3 cucharones · pollo · 1 rebanada de pan",
              "3 cucharones · pollo extra · 2 rebanadas de pan",
              "3 cucharones grandes · doble pollo · 2 rebanadas de pan"],
 "dica": "La calabaza tiene mucha agua y fibra, lo que llena el estómago con muy pocas calorías. El calor de la sopa hace que comas más despacio, y el pollo deshebrado convierte la crema ligera en una comida completa que detiene el hambre hasta la hora de dormir, sin pesadez.",
},
{
 "nome": "Filete de pollo en salsa de mostaza con verduras al vapor",
 "hook": "Una salsa cremosa de mostaza y yogur viste al pollo — ligera, elegante y rápida de hacer para la cena.",
 "tempo": "25 min", "rende": "1 porción", "kcal_base": 400,
 "ings": ["1 filete de pechuga de pollo (unos 150 g)",
          "1 cucharada de yogur natural sin azúcar", "1 cucharadita de mostaza",
          "100 g de brócoli, zanahoria y ejotes", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y hierbas frescas al gusto"],
 "passos": [
   "Corta las verduras en trozos parecidos. Cuécelas en una vaporera (o en una olla tapada con un dedo de agua) 6 minutos, hasta que queden tiernas pero todavía firmes y coloridas.",
   "Sazona el pollo con sal, pimienta y el ajo. Calienta un sartén antiadherente con el aceite de oliva a fuego medio y asa el filete de 4 a 5 minutos de cada lado, hasta que quede dorado y blanco por dentro.",
   "En un tazón pequeño, mezcla el yogur, la mostaza, el jugo de limón, sal y pimienta, hasta que quede una salsa cremosa.",
   "Pon el pollo en el plato, rocíalo con la salsa de mostaza y sirve con las verduras a un lado.",
   "Espolvorea hierbas frescas y sirve caliente."],
 "porcoes8": ["120 g de pollo · verduras",
              "150 g de pollo · verduras",
              "150 g de pollo · verduras · 2 cucharadas de arroz",
              "170 g de pollo · verduras · 2 cucharadas de arroz",
              "170 g de pollo · verduras · 3 cucharadas de arroz",
              "200 g de pollo · verduras · 3 cucharadas de arroz",
              "220 g de pollo · verduras · 4 cucharadas de arroz",
              "250 g de pollo · verduras · 4 cucharadas de arroz"],
 "dica": "La salsa cremosa viene del yogur, no de la crema ni de la mantequilla, cortando mucha grasa. La mostaza aporta un sabor fuerte con casi nada de calorías. Cocer las verduras al vapor conserva los nutrientes y no usa aceite — una cena ligera que parece de restaurante.",
},
{
 "nome": "Pescado al papillote con verduras",
 "hook": "El pescado se cocina en su propio vapor dentro del papel, quedando increíblemente suave — y abres el paquete en la mesa, caliente y aromático.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 380,
 "ings": ["1 filete de pescado blanco (merluza, bacalao o tilapia, unos 150 g)",
          "½ calabacín en rodajas delgadas", "½ zanahoria en tiras delgadas",
          "jitomates cherry, cortados", "1 diente de ajo en rebanadas",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y hierbas (tomillo u orégano) al gusto",
          "1 hoja grande de papel para hornear"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). Corta el calabacín y la zanahoria en rebanadas delgadas, para que se cocinen en el mismo tiempo que el pescado.",
   "En el centro de una hoja grande de papel para hornear, haz una cama con las verduras. Sazona con un poco de sal, pimienta y la mitad del aceite de oliva.",
   "Pon el filete de pescado encima. Sazona con sal, pimienta, el ajo, las hierbas, el jugo de limón y el resto del aceite de oliva.",
   "Cierra el papel como un paquete: junta las puntas y dobla bien las orillas, dejando algo de aire adentro, para formar un paquete sellado.",
   "Hornea de 18 a 20 minutos. Ábrelo con cuidado (sale vapor caliente) y sírvelo en el papel o pásalo a un plato."],
 "porcoes8": ["120 g de pescado · verduras",
              "150 g de pescado · verduras",
              "150 g de pescado · verduras · 1 papa pequeña",
              "170 g de pescado · verduras · 1 papa",
              "170 g de pescado · verduras · 1 papa",
              "200 g de pescado · verduras · 1 papa",
              "220 g de pescado · verduras · 1 papa grande",
              "250 g de pescado · verduras · 2 papas pequeñas"],
 "dica": "Cocinar al papillote usa casi nada de grasa: el pescado y las verduras se cocinan en su propio vapor, conservando su sabor y quedando muy suaves. Es una de las formas más ligeras y saludables de cocinar pescado, perfecta para una cena sin pesadez y sin sartenes sucios.",
},
{
 "nome": "Pay de pollo con puré de coliflor",
 "hook": "Todo el consuelo de un pastel gratinado, pero la cubierta es puré de coliflor — cremoso, ligero y con muchísimas menos calorías.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 380,
 "ings": ["1 coliflor mediana",
          "2 filetes de pechuga de pollo cocidos y deshebrados (unos 300 g)",
          "1 cebolla, picada", "1 diente de ajo, picado", "1 jitomate, picado",
          "1 cucharadita de aceite de oliva",
          "2 cucharadas de queso rallado bajo en grasa",
          "sal, pimienta y hierbas frescas al gusto"],
 "passos": [
   "Corta la coliflor en trozos y cuécela en agua hirviendo 12 minutos, hasta que quede muy suave. Escúrrela muy bien (la coliflor retiene agua) y aplástala con un tenedor, con una pizca de sal, hasta que quede un puré cremoso.",
   "En un sartén, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos. Agrega el pollo deshebrado y el jitomate, sazona con sal y pimienta y cocina 5 minutos, hasta que quede un relleno suave.",
   "En un refractario, reparte el pollo en el fondo y cúbrelo con el puré de coliflor.",
   "Espolvorea el queso rallado encima.",
   "Hornea a fuego medio-alto (200 °C) por 15 minutos, hasta que la superficie quede ligeramente dorada. Espolvorea hierbas frescas y sirve."],
 "porcoes8": ["½ porción · ensalada",
              "1 porción · ensalada",
              "1 porción · ensalada",
              "1 porción · pollo extra · ensalada",
              "1 porción · pollo extra · ensalada",
              "1 porción grande · ensalada",
              "1 porción grande · pollo extra · ensalada",
              "porción doble · ensalada"],
 "dica": "La coliflor en lugar de la papa corta buena parte de las calorías y los carbohidratos, conservando la cremosidad del puré. El pollo deshebrado aporta proteína y saciedad. Es el plato reconfortante ideal para quien quiere comer algo caliente y ligero antes de dormir.",
},
{
 "nome": "Sopa de verduras con carne de res magra",
 "hook": "La sopa que sabe a hecha por la abuela: trozos de res suave y verduras en un caldo bien sazonado que llena la panza y calienta el alma.",
 "tempo": "50 min", "rende": "3 porciones", "kcal_base": 360,
 "ings": ["250 g de res magra en cubos (chambarete o pulpa)",
          "1 papa en cubos", "1 zanahoria en cubos", "1 calabacín en cubos",
          "1 jitomate, picado", "1 cebolla, picada", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto", "1,5 litros de agua"],
 "passos": [
   "En una olla, calienta el aceite de oliva y dora los cubos de res por todos lados, revolviendo, 5 minutos.",
   "Agrega la cebolla y el ajo y fríe 2 minutos. Agrega el jitomate y revuelve otros 2 minutos.",
   "Vierte el agua, sazona con sal y pimienta, tápala y cocina a fuego medio-bajo 30 minutos, hasta que la carne empiece a suavizarse.",
   "Agrega la papa, la zanahoria y el calabacín y cocina otros 15 minutos, hasta que la carne quede muy suave y las verduras estén cocidas.",
   "Prueba la sal, espolvorea hierbas frescas y sirve bien caliente."],
 "porcoes8": ["1 cucharón · poca carne",
              "2 cucharones · carne",
              "2 cucharones · carne",
              "2 cucharones · carne · 1 rebanada de pan",
              "2 cucharones · carne extra · 1 rebanada de pan",
              "3 cucharones · carne · 1 rebanada de pan",
              "3 cucharones · carne extra · 2 rebanadas de pan",
              "3 cucharones grandes · doble carne · 2 rebanadas de pan"],
 "dica": "Las sopas con bastante líquido y verduras llenan el estómago con pocas calorías, y comerlas calientes hace que comas despacio y te sientas satisfecha antes. La carne magra aporta proteína, haciendo que la sopa sea lo bastante sustanciosa para ser una cena completa.",
},
{
 "nome": "Salmón con salsa de yogur y eneldo y verduras",
 "hook": "El salmón rosado recibe una salsa fresca de yogur y eneldo — sofisticado, ligero y hecho en veinte minutos.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 430,
 "ings": ["1 filete de salmón (unos 150 g)",
          "2 cucharadas de yogur natural sin azúcar", "eneldo picado",
          "100 g de brócoli y zanahoria", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y ajo picado al gusto"],
 "passos": [
   "Corta el brócoli en ramitos y la zanahoria en rodajas. Cuécelos al vapor 6 minutos, hasta que queden tiernos pero todavía firmes.",
   "Sazona el salmón con sal, pimienta, el ajo y el jugo de limón.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio. Pon el salmón con la piel hacia abajo y déjalo 4 minutos, después voltéalo y déjalo otros 3 minutos, hasta que se ponga más claro y se separe con el tenedor.",
   "Prepara la salsa: mezcla el yogur, el eneldo picado, un poco de sal y unas gotas de limón.",
   "Arma el plato con el salmón, las verduras a un lado y la salsa de yogur encima o aparte."],
 "porcoes8": ["120 g de salmón · verduras",
              "150 g de salmón · verduras",
              "150 g de salmón · verduras · 1 papa pequeña",
              "170 g de salmón · verduras · 1 papa",
              "170 g de salmón · verduras · 1 papa",
              "200 g de salmón · verduras · 1 papa",
              "220 g de salmón · verduras · 1 papa grande",
              "250 g de salmón · verduras · 2 papas pequeñas"],
 "dica": "El salmón aporta la grasa buena (omega-3) que te llena y le hace bien a tu corazón. La salsa de yogur con eneldo reemplaza las salsas cremosas grasosas por una versión fresca y rica en proteína. Con verduras al vapor, es una cena ligera, bonita y completa.",
},
{
 "nome": "Pollo al limón con verduras rostizadas",
 "hook": "El pollo queda jugoso y apenas cítrico, rostizado junto con verduras que se caramelizan en las orillas — una charola, cero trabajo.",
 "tempo": "40 min", "rende": "2 porciones", "kcal_base": 420,
 "ings": ["2 muslos de pollo sin piel (o 2 filetes, unos 300 g)",
          "1 calabacín en trozos", "1 pimiento en trozos", "1 cebolla en gajos",
          "jitomates cherry", "2 dientes de ajo",
          "1 cucharadita de aceite de oliva", "jugo de 1 limón",
          "sal, pimienta y orégano al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). En una charola, reparte el calabacín, el pimiento, la cebolla, los jitomates cherry y los dientes de ajo.",
   "Sazona las verduras con sal, pimienta, orégano y la mitad del aceite de oliva, y mezcla.",
   "Sazona el pollo con sal, pimienta, el jugo de limón y el resto del aceite de oliva. Pon las piezas entre las verduras.",
   "Hornea 35 minutos, volteando a la mitad del tiempo, hasta que el pollo quede dorado y cocido por dentro (el líquido que sale al picarlo sale transparente) y las verduras suaves con las orillas doradas.",
   "Sirve directo de la charola, rociando con los jugos de limón que se formaron."],
 "porcoes8": ["1 muslo · verduras",
              "1 muslo · verduras",
              "1 muslo grande · verduras",
              "2 muslos · verduras",
              "2 muslos · verduras",
              "2 muslos · verduras · 1 papa",
              "2 muslos · verduras · 1 papa grande",
              "3 muslos · verduras · 1 papa grande"],
 "dica": "Rostizar sin piel y con poco aceite mantiene el pollo ligero, y el limón aporta frescura sin calorías añadidas. Las verduras rostizadas se endulzan y quedan sabrosas por sí solas, así que no necesitas salsas pesadas. Una cena práctica, colorida y ligera hecha en una sola charola.",
},
{
 "nome": "Albóndigas de pavo con calabacín en salsa",
 "hook": "Albóndigas ligeras de pavo nadando en una salsa fresca de jitomate, sobre cintas de calabacín — la pasta que no pesa en la báscula.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 380,
 "ings": ["250 g de carne molida de pechuga de pavo (o de pollo)", "1 huevo",
          "2 cucharadas de avena", "2 calabacines grandes",
          "3 jitomates maduros, picados (o salsa de tomate)",
          "1 cebolla, picada", "2 dientes de ajo, picados",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y albahaca al gusto"],
 "passos": [
   "En un tazón, mezcla la carne molida de pavo, el huevo, la avena, la mitad del ajo, sal y pimienta. Amasa con las manos y forma bolitas del tamaño de una nuez.",
   "Calienta el aceite de oliva en una olla amplia y dora las albóndigas por todos lados, volteándolas con cuidado, 5 minutos. Sácalas y resérvalas.",
   "En la misma olla, fríe la cebolla y el resto del ajo 2 minutos. Agrega los jitomates picados, sal y pimienta y cocina 10 minutos, hasta que se haga una salsa.",
   "Regresa las albóndigas a la salsa y cocina otros 8 minutos, hasta que estén cocidas por dentro.",
   "Con un pelador, haz cintas delgadas de calabacín (como fideos). Pon las cintas crudas en el plato y vierte encima las albóndigas calientes con la salsa — el calor suaviza el calabacín. Espolvorea albahaca."],
 "porcoes8": ["3 albóndigas · calabacín",
              "4 albóndigas · calabacín",
              "4 albóndigas · calabacín · 2 cucharadas de arroz",
              "5 albóndigas · calabacín · 2 cucharadas de arroz",
              "5 albóndigas · calabacín · 3 cucharadas de arroz",
              "6 albóndigas · calabacín · 3 cucharadas de arroz",
              "7 albóndigas · calabacín · 4 cucharadas de arroz",
              "8 albóndigas · calabacín · 4 cucharadas de arroz"],
 "dica": "Cambiar la pasta por cintas de calabacín corta casi todos los carbohidratos y llena el plato de fibra y agua. Las albóndigas de pavo son magras y ricas en proteína, y una salsa de jitomate hecha al momento, sin azúcar, mantiene la cena sabrosa y muy ligera.",
},
{
 "nome": "Filete de pescado con costra de hierbas y puré de papa",
 "hook": "Una costra crujiente de hierbas por fuera, pescado suave por dentro — parece plato de chef, pero es simple y ligero.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 410,
 "ings": ["1 filete de pescado blanco (merluza, bacalao o tilapia, unos 150 g)",
          "2 cucharadas de pan molido integral",
          "perejil y cebollín finamente picados", "1 papa mediana",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "1 diente de ajo, picado", "sal y pimienta al gusto"],
 "passos": [
   "Pela y cuece la papa en agua hirviendo 15 minutos, hasta que quede muy suave. Escúrrela y aplástala con un tenedor, con una pizca de sal, hasta que quede un puré terso.",
   "Pon el horno a fuego medio-alto (200 °C). Sazona el pescado con sal, pimienta, el ajo y el jugo de limón.",
   "En un tazón pequeño, mezcla el pan molido con el perejil, el cebollín y un poco de aceite de oliva, formando una mezcla húmeda de migas.",
   "Pon el pescado en una charola y cubre la parte de arriba con las migas de hierbas, presionando ligeramente para que se peguen.",
   "Hornea de 15 a 18 minutos, hasta que la costra quede dorada y crujiente y el pescado se separe en láminas. Sirve con el puré de papa."],
 "porcoes8": ["120 g de pescado · ½ porción de puré",
              "150 g de pescado · 1 porción de puré",
              "150 g de pescado · 1 porción de puré",
              "170 g de pescado · 1 porción de puré",
              "170 g de pescado · 1 porción de puré",
              "200 g de pescado · 1 porción grande de puré",
              "220 g de pescado · porción grande de puré",
              "250 g de pescado · porción doble de puré"],
 "dica": "La costra de hierbas con apenas un poco de pan molido da textura crujiente sin fritura, manteniendo el pescado ligero y lleno de sabor. El pescado blanco es extremadamente magro y rico en proteína, y el puré en la medida correcta reconforta sin excederse — una cena bonita y ligera.",
},
{
 "nome": "Bistec a la plancha con ensalada de garbanzos",
 "hook": "Un bistec en su punto junto a una ensalada tibia de garbanzos — doble proteína que llena sin pesar en la cena.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 440,
 "ings": ["1 bistec de res magro (unos 120 g)", "80 g de garbanzos cocidos",
          "½ jitomate en cubos", "cebolla morada picada", "hojas verdes",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y perejil al gusto"],
 "passos": [
   "Sazona el bistec con sal y pimienta por los dos lados.",
   "Calienta un sartén antiadherente a fuego alto con unas gotas de aceite de oliva. Asa el bistec de 2 a 3 minutos de cada lado, sin moverlo, hasta que quede dorado por fuera y al término que te guste. Déjalo reposar 2 minutos antes de cortarlo.",
   "En un tazón, mezcla los garbanzos, el jitomate, la cebolla morada y el perejil.",
   "Aliña la ensalada con el aceite de oliva, el jugo de limón, sal y pimienta.",
   "Sirve el bistec rebanado sobre una cama de hojas verdes, con la ensalada de garbanzos a un lado."],
 "porcoes8": ["100 g de carne · 55 g de garbanzos · ensalada",
              "120 g de carne · 80 g de garbanzos · ensalada",
              "130 g de carne · 80 g de garbanzos · ensalada",
              "150 g de carne · 110 g de garbanzos · ensalada",
              "150 g de carne · 110 g de garbanzos · ensalada",
              "170 g de carne · 125 g de garbanzos · ensalada",
              "200 g de carne · 165 g de garbanzos · ensalada",
              "220 g de carne · 165 g de garbanzos · ensalada"],
 "dica": "Los garbanzos suman fibra y proteína vegetal a la proteína de la carne, lo que hace el plato muy saciante con pocas calorías. Asar el bistec magro sin aceite y servirlo con una ensalada fresca es una cena ligera, llena de sabor, que detiene el hambre por horas.",
},
{
 "nome": "Crema de brócoli con pollo",
 "hook": "Verde, aterciopelada y llena de sabor — una crema de brócoli que gana cuerpo con el pollo y se vuelve una cena completa.",
 "tempo": "30 min", "rende": "3 porciones", "kcal_base": 330,
 "ings": ["1 pieza de brócoli", "1 filete de pechuga de pollo (unos 150 g)",
          "1 papa pequeña (aporta cremosidad)", "1 cebolla, picada",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y nuez moscada al gusto", "1 litro de agua"],
 "passos": [
   "En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos, revolviendo.",
   "Agrega la papa en cubos, el filete de pollo entero y el agua. Cocina 15 minutos.",
   "Saca el pollo, déjalo enfriar un poco y deshébralo. Resérvalo. Agrega el brócoli (solo los ramitos) a la olla y cocina otros 5 minutos, hasta que quede tierno pero todavía verde.",
   "Licúa la sopa con una licuadora de inmersión (de bastón) o en una licuadora normal hasta que quede una crema tersa. Ten cuidado con el líquido caliente.",
   "Regresa la crema a la olla, agrega el pollo deshebrado, sazona con sal, pimienta y un toque de nuez moscada y calienta 3 minutos. Sirve."],
 "porcoes8": ["1 cucharón · poco pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo · 1 rebanada de pan",
              "2 cucharones · pollo extra · 1 rebanada de pan",
              "3 cucharones · pollo · 1 rebanada de pan",
              "3 cucharones · pollo extra · 2 rebanadas de pan",
              "3 cucharones grandes · doble pollo · 2 rebanadas de pan"],
 "dica": "El brócoli es una de las verduras más nutritivas y de menos calorías, y licuado se convierte en una crema aterciopelada sin necesidad de crema. Un trocito de papa aporta la cremosidad, y el pollo deshebrado completa la sopa con proteína, manteniendo la cena ligera y saciante.",
},
{
 "nome": "Wrap de pavo con ensalada",
 "hook": "Rebanadas de pechuga de pavo, hojas frescas y un toque cremoso, enrollados en una tortilla suave — una cena ligera para comer con las manos.",
 "tempo": "10 min", "rende": "1 porción", "kcal_base": 360,
 "ings": ["1 tortilla integral",
          "4 rebanadas de pechuga de pavo (fiambre magro)",
          "1 cucharada de queso cottage (o queso crema light)",
          "hojas de lechuga", "½ jitomate en rebanadas",
          "zanahoria rallada", "pepino en tiras",
          "sal, pimienta y mostaza al gusto"],
 "passos": [
   "Calienta la tortilla 20 segundos en un sartén, solo para que se suavice y sea fácil de enrollar.",
   "Unta el queso cottage (o el queso crema light) por toda la tortilla, como si fuera mantequilla.",
   "Pon en el centro las hojas de lechuga, las rebanadas de pavo, el jitomate, la zanahoria rallada y el pepino.",
   "Sazona con un poco de sal, pimienta y mostaza.",
   "Dobla los lados hacia adentro y enróllala apretada, de abajo hacia arriba. Córtala a la mitad en diagonal y sirve."],
 "porcoes8": ["3 rebanadas de pavo · ½ tortilla · ensalada",
              "4 rebanadas de pavo · 1 tortilla · ensalada",
              "4 rebanadas de pavo · 1 tortilla · ensalada",
              "5 rebanadas de pavo · 1 tortilla · ensalada",
              "5 rebanadas de pavo · 1 tortilla · ensalada",
              "6 rebanadas de pavo · 1 tortilla grande · ensalada",
              "6 rebanadas de pavo · 2 tortillas · ensalada",
              "8 rebanadas de pavo · 2 tortillas · ensalada"],
 "dica": "La pechuga de pavo es una carne magra y práctica, llena de proteína. Cambiar el queso crema normal por cottage o una versión light y rellenar el wrap de hojas y verduras te da una cena ligera, rápida y saciante, perfecta para los días en que no tienes ganas de cocinar.",
},
{
 "nome": "Guisado de pollo con verduras",
 "hook": "Trozos de pollo suave en un caldo espeso y bien sazonado, con verduras que se deshacen en la boca — comida de olla que te abraza.",
 "tempo": "40 min", "rende": "3 porciones", "kcal_base": 390,
 "ings": ["2 filetes de pechuga de pollo en cubos (unos 300 g)",
          "1 papa en cubos", "1 zanahoria en rodajas", "1 calabacín en cubos",
          "1 jitomate, picado", "1 cebolla, picada",
          "2 dientes de ajo, picados", "1 cucharadita de aceite de oliva",
          "sal, pimienta, cúrcuma y hierbas frescas al gusto"],
 "passos": [
   "Sazona los cubos de pollo con sal, pimienta y un poco de cúrcuma.",
   "En una olla, calienta el aceite de oliva y dora los cubos de pollo 5 minutos, revolviendo. Agrega la cebolla y el ajo y fríe 2 minutos.",
   "Agrega el jitomate y revuelve 2 minutos, hasta que empiece a deshacerse.",
   "Agrega la papa y la zanahoria y cubre con agua (lo suficiente para cubrir todo). Sazona con sal y cocina 15 minutos.",
   "Agrega el calabacín y cocina otros 8 minutos, hasta que todo quede suave y el caldo tenga cuerpo. Espolvorea hierbas frescas y sirve solo o con un poco de arroz."],
 "porcoes8": ["½ porción · sin arroz",
              "1 porción · sin arroz",
              "1 porción · 2 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción grande · 4 cucharadas de arroz",
              "porción grande · 5 cucharadas de arroz",
              "porción doble · 5 cucharadas de arroz"],
 "dica": "El guisado cocina todo en la misma olla con poca grasa, y el propio caldo del pollo sazona las verduras. Es un plato sustancioso que te llena con pocas calorías, buenísimo para la cena porque es caliente, reconfortante y ligero al mismo tiempo.",
},
{
 "nome": "Hamburguesa de atún con ensalada",
 "hook": "Hecha con atún de lata, esta hamburguesa es barata, llena de proteína y está lista en un instante — una cena ligera y práctica.",
 "tempo": "20 min", "rende": "2 porciones", "kcal_base": 380,
 "ings": ["2 latas de atún en agua, escurridas", "1 huevo",
          "3 cucharadas de avena", "½ cebolla, finamente picada",
          "perejil picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y jugo de ½ limón al gusto",
          "hojas verdes, jitomate y pepino para la ensalada"],
 "passos": [
   "Escurre bien el atún, presionándolo para sacarle el líquido. En un tazón, mezcla el atún, el huevo, la avena, la cebolla, el perejil, sal, pimienta y el jugo de limón.",
   "Aplasta todo con un tenedor hasta que se integre. Si queda muy suave, agrega un poco más de avena.",
   "Forma dos discos con las manos, aplanándolos bien.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio. Pon las hamburguesas y déjalas 4 minutos de cada lado, sin moverlas, hasta que queden doradas y firmes. Voltéalas con cuidado.",
   "Sirve con una ensalada generosa de hojas, jitomate y pepino a un lado."],
 "porcoes8": ["1 hamburguesa · ensalada",
              "1 hamburguesa · ensalada",
              "1 hamburguesa · ensalada · ½ pan",
              "2 hamburguesas · ensalada",
              "2 hamburguesas · ensalada",
              "2 hamburguesas · ensalada · 1 pan",
              "2 hamburguesas · ensalada · 1 pan",
              "3 hamburguesas · ensalada · 1 pan"],
 "dica": "El atún de lata es una fuente barata y práctica de proteína, y ligado con huevo y avena (en lugar de mucho pan) se vuelve una hamburguesa magra y saciante. Asada sin freír y servida con bastante ensalada, es una cena ligera y económica que llena la panza.",
},
{
 "nome": "Res al horno con verduras",
 "hook": "Un trozo de res que se cocina despacio hasta deshacerse, con verduras empapadas en el caldo — la cena de domingo, en la medida correcta.",
 "tempo": "1 h 20 min", "rende": "3 porciones", "kcal_base": 440,
 "ings": ["400 g de res magra en un trozo (chambarete, bola o pulpa)",
          "2 zanahorias en trozos grandes", "2 papas en trozos grandes",
          "1 cebolla en gajos", "2 dientes de ajo", "1 jitomate, picado",
          "1 hoja de laurel", "1 cucharadita de aceite de oliva",
          "sal, pimienta y romero al gusto"],
 "passos": [
   "Sazona el trozo de res con sal y pimienta. En una olla honda, calienta el aceite de oliva y dora la carne por todos lados, volteándola, unos 6 minutos (ese dorado le da mucho sabor al caldo).",
   "Agrega la cebolla, el ajo y el jitomate y fríe 2 minutos. Agrega la hoja de laurel y agua caliente hasta cubrir la mitad de la carne.",
   "Tápala y cocina a fuego bajo 50 minutos, volteando la carne a la mitad del tiempo. Si el agua se seca demasiado, agrega un poco más de agua caliente.",
   "Agrega las zanahorias y las papas y cocina otros 25 minutos, hasta que la carne quede tan suave que se deshaga y las verduras estén cocidas.",
   "Saca la hoja de laurel. Rebana o deshebra la carne y sirve con las verduras y el caldo encima."],
 "porcoes8": ["½ porción de carne · verduras",
              "1 porción de carne · verduras",
              "1 porción de carne · verduras",
              "1 porción · verduras · 1 papa extra",
              "1 porción · verduras · 1 papa extra",
              "1 porción grande · verduras",
              "porción grande · verduras · papa extra",
              "porción doble · verduras"],
 "dica": "La cocción lenta suaviza los cortes magros y baratos sin necesidad de grasa, y el caldo que se forma sazona las verduras de forma natural. Servido con la carne en la medida correcta y bastante verdura, es un plato reconfortante de fin de semana que entra justo en tu dieta.",
},
{
 "nome": "Pollo relleno de ricotta y espinaca",
 "hook": "El filete de pollo se abre como una bolsita y guarda un relleno cremoso de ricotta y espinaca — sorprendente, jugoso y ligero.",
 "tempo": "35 min", "rende": "2 porciones", "kcal_base": 400,
 "ings": ["2 filetes gruesos de pechuga de pollo (unos 300 g)",
          "4 cucharadas de ricotta", "1 puñado grande de espinaca",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y nuez moscada al gusto",
          "palillos"],
 "passos": [
   "En un sartén, calienta unas gotas de aceite de oliva y saltea la espinaca con el ajo 1 minuto, solo hasta que se marchite (las hojas se ponen suaves). Déjala enfriar y pícala.",
   "En un tazón, mezcla la ricotta, la espinaca picada, sal, pimienta y un toque de nuez moscada, formando un relleno cremoso.",
   "Con un cuchillo, haz un corte en el costado de cada filete, abriendo una bolsita (sin cortar hasta el otro lado). Sazona el pollo con sal, pimienta y el jugo de limón.",
   "Rellena las bolsitas con la mezcla de ricotta y cierra la abertura con uno o dos palillos.",
   "Calienta el resto del aceite de oliva en un sartén a fuego medio y dora los filetes de 5 a 6 minutos de cada lado, hasta que queden dorados y cocidos por dentro. Saca los palillos antes de servir, con una ensalada a un lado."],
 "porcoes8": ["1 filete pequeño · ensalada",
              "1 filete · ensalada",
              "1 filete · ensalada · 2 cucharadas de arroz",
              "1 filete grande · ensalada · 2 cucharadas de arroz",
              "1 filete grande · ensalada · 3 cucharadas de arroz",
              "1 filete grande · ensalada · 4 cucharadas de arroz",
              "2 filetes · ensalada · 4 cucharadas de arroz",
              "2 filetes · ensalada · 5 cucharadas de arroz"],
 "dica": "La ricotta es un queso magro y cremoso, lleno de proteína y bajo en grasa, ideal para rellenar sin hacer pesado el plato. La espinaca aporta fibra y nutrientes por casi nada de calorías. El resultado es un pollo jugoso y sofisticado, lo bastante ligero para la cena.",
},
{
 "nome": "Sopa de pescado con verduras",
 "hook": "Un caldo aromático con trozos de pescado blanco y verduras — ligero, con todo el sabor del mar y reconfortante en una noche fría.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 340,
 "ings": ["400 g de filete de pescado blanco en trozos (merluza o bacalao)",
          "1 papa en cubos", "1 zanahoria en cubos", "1 jitomate, picado",
          "1 cebolla, picada", "2 dientes de ajo, picados",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta, cilantro o perejil al gusto", "1,2 litros de agua"],
 "passos": [
   "En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos. Agrega el jitomate y revuelve otros 2 minutos, hasta que se deshaga.",
   "Agrega el agua, la papa y la zanahoria. Sazona con sal y pimienta y cocina 15 minutos, hasta que las verduras queden suaves.",
   "Agrega los trozos de pescado (el pescado se cocina rápido, por eso entra al final) y cocina de 6 a 8 minutos, solo hasta que el pescado esté blanco y suave, sin deshacerse demasiado.",
   "Agrega el jugo de limón y prueba la sal.",
   "Espolvorea cilantro o perejil y sirve bien caliente."],
 "porcoes8": ["1 cucharón · pescado",
              "2 cucharones · pescado",
              "2 cucharones · pescado",
              "2 cucharones · pescado · 1 rebanada de pan",
              "2 cucharones · pescado extra · 1 rebanada de pan",
              "3 cucharones · pescado · 1 rebanada de pan",
              "3 cucharones · pescado extra · 2 rebanadas de pan",
              "3 cucharones grandes · doble pescado · 2 rebanadas de pan"],
 "dica": "El pescado blanco es extremadamente magro y se cocina en minutos, manteniendo la sopa ligera y llena de proteína. El caldo con verduras llena el estómago con muy pocas calorías, y el toque de limón levanta el sabor sin necesidad de mucha sal — una cena caliente y ligera.",
},
{
 "nome": "Escalopas de pavo en salsa de champiñones",
 "hook": "Rebanadas delgadas de pavo en una salsa cremosa de champiñones — una cena que parece cara, hecha con poca grasa en veinte minutos.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 400,
 "ings": ["2 filetes delgados de pechuga de pavo (unos 300 g)",
          "70 g de champiñones en rebanadas", "1 cebolla, picada",
          "1 diente de ajo, picado",
          "3 cucharadas de yogur natural sin azúcar",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y perejil al gusto", "arroz o puré para servir"],
 "passos": [
   "Sazona los filetes delgados de pavo con sal y pimienta.",
   "Calienta un sartén antiadherente con la mitad del aceite de oliva a fuego medio-alto y dora los filetes de 2 a 3 minutos de cada lado, hasta que queden dorados y cocidos. Sácalos y resérvalos.",
   "En el mismo sartén, con el resto del aceite de oliva, fríe la cebolla y el ajo 2 minutos. Agrega los champiñones y cocina 4 minutos, hasta que se ablanden y suelten su agua.",
   "Baja el fuego, apágalo y agrega el yogur, revolviendo — fuera del fuego no se corta (no se hace grumos). Ajusta la sal y la pimienta.",
   "Regresa los filetes al sartén para cubrirlos con la salsa. Espolvorea perejil y sirve con un poco de arroz o puré."],
 "porcoes8": ["1 filete · 2 cucharadas de arroz",
              "1 filete · 3 cucharadas de arroz",
              "1 filete grande · 3 cucharadas de arroz",
              "1 filete grande · 4 cucharadas de arroz",
              "1 filete grande · 4 cucharadas de arroz",
              "2 filetes · 4 cucharadas de arroz",
              "2 filetes · 5 cucharadas de arroz",
              "2 filetes · 6 cucharadas de arroz"],
 "dica": "El pavo es una carne blanca magra y rica en proteína. La salsa cremosa viene del yogur, no de la crema, cortando mucha grasa. Los champiñones aportan un sabor intenso y cuerpo a la salsa con muy pocas calorías — una cena sofisticada y ligera.",
},
{
 "nome": "Huevos al horno en salsa de jitomate con pollo",
 "hook": "Huevos cocidos dentro de una salsa de jitomate bien sazonada, con trocitos de pollo — una cena caliente y diferente, del sartén directo a la mesa.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 370,
 "ings": ["4 huevos",
          "1 filete de pechuga de pollo cocido y deshebrado (unos 120 g)",
          "3 jitomates maduros, picados (o salsa de tomate)",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "½ pimiento, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta, paprika y hierbas frescas al gusto",
          "pan integral para servir"],
 "passos": [
   "En un sartén que pueda ir al horno (o uno hondo), calienta el aceite de oliva y fríe la cebolla, el ajo y el pimiento 3 minutos, revolviendo.",
   "Agrega los jitomates picados, la paprika, sal y pimienta y cocina 8 minutos, hasta que se haga una salsa con cuerpo. Agrega el pollo deshebrado y mezcla.",
   "Con una cuchara, haz huecos pequeños en la salsa. Rompe un huevo en cada hueco, sin mezclar, para que las yemas queden enteras.",
   "Tapa el sartén y cocina a fuego bajo de 6 a 8 minutos, hasta que las claras cuajen y las yemas queden como te gustan. (O hornea a fuego medio 10 minutos.)",
   "Espolvorea hierbas frescas y sirve en el mismo sartén, con rebanadas de pan integral a un lado."],
 "porcoes8": ["1 huevo · pollo · salsa",
              "2 huevos · pollo · salsa",
              "2 huevos · pollo · 1 rebanada de pan",
              "2 huevos · pollo extra · 1 rebanada de pan",
              "2 huevos · pollo extra · 1 rebanada de pan",
              "2 huevos · pollo · 2 rebanadas de pan",
              "3 huevos · pollo extra · 2 rebanadas de pan",
              "3 huevos · doble pollo · 2 rebanadas de pan"],
 "dica": "Los huevos son una proteína completa y muy saciante, y cocidos en salsa de jitomate quedan ligeros, sin fritura. El pollo suma todavía más proteína y la salsa llena el plato con el volumen de los jitomates. Es una cena caliente, barata y reconfortante que llena bien.",
},
{
 "nome": "Brochetas de camarón y verduras",
 "hook": "Camarones rosados y verduras coloridas ensartados juntos, asados hasta dorarse — ligeras, bonitas y con aire de fiesta.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 360,
 "ings": ["250 g de camarones grandes limpios", "1 pimiento en cuadros",
          "1 cebolla en trozos", "1 calabacín en rodajas gruesas",
          "jitomates cherry", "2 dientes de ajo, picados",
          "1 cucharadita de aceite de oliva", "jugo de 1 limón",
          "sal, pimienta y paprika al gusto", "palillos para brocheta"],
 "passos": [
   "Sazona los camarones con sal, pimienta, paprika, el ajo y el jugo de limón. Déjalos tomar sabor 10 minutos.",
   "Arma las brochetas alternando un camarón, un cuadro de pimiento, un trozo de cebolla, una rodaja de calabacín y un jitomate cherry, hasta llenar el palillo.",
   "Unta las brochetas con el aceite de oliva.",
   "Calienta un sartén grande o una plancha a fuego medio-alto. Pon las brochetas y voltéalas cada 2 minutos, unos 8 minutos en total, solo hasta que el camarón se ponga rosado y se enrosque. No lo cuezas de más, o queda chicloso.",
   "Sirve las brochetas con una ensalada o un poco de arroz."],
 "porcoes8": ["1 brocheta · ensalada",
              "2 brochetas · ensalada",
              "2 brochetas · ensalada · 2 cucharadas de arroz",
              "2 brochetas · ensalada · 3 cucharadas de arroz",
              "2 brochetas · ensalada · 3 cucharadas de arroz",
              "3 brochetas · ensalada · 3 cucharadas de arroz",
              "3 brochetas · ensalada · 4 cucharadas de arroz",
              "3 brochetas grandes · ensalada · 4 cucharadas de arroz"],
 "dica": "El camarón es casi todo proteína, con muy poca grasa y pocas calorías. Ensartado con verduras coloridas y asado sin aceite, se vuelve una cena ligera, vistosa y sabrosa que controla la porción de forma natural y sirve hasta para ocasiones especiales.",
},
{
 "nome": "Salmón a la plancha con espárragos",
 "hook": "Dos estrellas en un plato: el salmón jugoso y los espárragos crujientes — una cena fina y ligera lista en quince minutos.",
 "tempo": "18 min", "rende": "1 porción", "kcal_base": 420,
 "ings": ["1 filete de salmón (unos 150 g)", "1 manojo de espárragos",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón",
          "sal, pimienta y ralladura de limón al gusto"],
 "passos": [
   "Lava los espárragos y rompe la punta dura de cada uno (se quiebra sola en el punto correcto cuando lo doblas).",
   "Sazona el salmón con sal, pimienta, el ajo y el jugo de limón.",
   "Calienta un sartén antiadherente con la mitad del aceite de oliva a fuego medio. Pon el salmón con la piel hacia abajo y déjalo 4 minutos, voltéalo y déjalo otros 3 minutos, hasta que se ponga más claro y se separe en láminas.",
   "Al mismo tiempo, en otro sartén (o en el mismo, después de sacar el salmón), saltea los espárragos con el resto del aceite de oliva a fuego alto 4 minutos, revolviendo, hasta que queden verdes y tiernos pero todavía crujientes.",
   "Arma el plato con el salmón y los espárragos. Termina con ralladura de limón encima."],
 "porcoes8": ["120 g de salmón · espárragos",
              "150 g de salmón · espárragos",
              "150 g de salmón · espárragos · 1 papa pequeña",
              "170 g de salmón · espárragos · 1 papa",
              "170 g de salmón · espárragos · 1 papa",
              "200 g de salmón · espárragos · 1 papa",
              "220 g de salmón · espárragos · 1 papa grande",
              "250 g de salmón · espárragos · 2 papas pequeñas"],
 "dica": "El salmón aporta proteína y omega-3, la grasa buena que te llena y protege tu corazón. Los espárragos son ligeros, llenos de fibra y ayudan a desinflamar, con muy pocas calorías. Asados juntos con poco aceite, forman una cena elegante, ligera y nutritiva.",
},
{
 "nome": "Carne molida salteada con calabacín",
 "hook": "Un salteado rápido de res con calabacín y un huevo encima — hecho en el sartén en minutos, llena sin necesidad de arroz.",
 "tempo": "20 min", "rende": "2 porciones", "kcal_base": 380,
 "ings": ["250 g de carne molida magra de res",
          "2 calabacines en cubos pequeños", "1 jitomate, picado",
          "1 cebolla, picada", "1 diente de ajo, picado", "2 huevos",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto"],
 "passos": [
   "Calienta el aceite de oliva en un sartén a fuego medio y fríe la cebolla y el ajo 2 minutos, revolviendo.",
   "Agrega la carne molida y revuelve, deshaciendo los trozos con la cuchara, hasta que pierda todo el color rosado.",
   "Agrega el jitomate y los cubos de calabacín, sazona con sal y pimienta y cocina 8 minutos, revolviendo de vez en cuando, hasta que el calabacín quede suave y suelte sus propios jugos.",
   "Mientras tanto, fríe o cuece los huevos aparte (fríelos con muy poco aceite o cuécelos 6 minutos para una yema suave).",
   "Sirve el salteado caliente con un huevo encima de cada porción y hierbas frescas espolvoreadas."],
 "porcoes8": ["½ porción · 1 huevo",
              "1 porción · 1 huevo",
              "1 porción · 1 huevo · 2 cucharadas de arroz",
              "1 porción · 1 huevo · 3 cucharadas de arroz",
              "1 porción · 2 huevos · 3 cucharadas de arroz",
              "1 porción grande · 2 huevos · 3 cucharadas de arroz",
              "porción grande · 2 huevos · 4 cucharadas de arroz",
              "porción doble · 2 huevos · 4 cucharadas de arroz"],
 "dica": "El calabacín en cubos se mezcla con la carne y da volumen al plato con muy pocas calorías, ayudándote a comer menos carne sin extrañarla. El huevo encima suma proteína y cremosidad. Sin arroz o con muy poco, es una cena ligera, rápida y muy saciante.",
},
{
 "nome": "Pollo a la pizzaiola con ensalada",
 "hook": "El sabor de la pizza sin la masa: el pollo asado recibe salsa de jitomate, queso derretido y orégano — mata el antojo y no te pesa.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 400,
 "ings": ["2 filetes de pechuga de pollo (unos 300 g)",
          "120 ml de salsa de tomate casera",
          "3 cucharadas de mozzarella baja en grasa rallada",
          "rebanadas de jitomate", "1 cucharadita de aceite de oliva",
          "orégano, sal y pimienta al gusto",
          "hojas verdes para la ensalada"],
 "passos": [
   "Sazona los filetes de pollo con sal y pimienta.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio y asa los filetes de 4 a 5 minutos de cada lado, hasta que queden dorados y blancos por dentro.",
   "Baja el fuego. Cubre cada filete con la salsa de tomate, una o dos rebanadas de jitomate y la mozzarella rallada. Espolvorea orégano.",
   "Tapa el sartén y déjalo de 3 a 4 minutos, solo hasta que el queso se derrita (ese es el truco para gratinar sin horno).",
   "Sirve con una ensalada verde fresca a un lado."],
 "porcoes8": ["100 g de pollo · poco queso · ensalada",
              "130 g de pollo · queso · ensalada",
              "150 g de pollo · queso · ensalada",
              "150 g de pollo · queso · 2 cucharadas de arroz",
              "150 g de pollo · queso · 3 cucharadas de arroz",
              "170 g de pollo · queso · 3 cucharadas de arroz",
              "200 g de pollo · queso · 4 cucharadas de arroz",
              "220 g de pollo · queso extra · 4 cucharadas de arroz"],
 "dica": "Matas el antojo de pizza con el sabor de la salsa de tomate, el queso y el orégano, pero sin la masa y sin la grasa. El pollo asado da proteína magra y saciedad, y un poco de queso derretido basta para el gusto de un gratinado. Ligero y satisfactorio.",
},
{
 "nome": "Pescado a la plancha con verduras",
 "hook": "Todo en un sartén: el pescado se dora de un lado mientras las verduras se saltean del otro — una cena ligera, rápida y sin batidero.",
 "tempo": "20 min", "rende": "1 porción", "kcal_base": 380,
 "ings": ["1 filete de pescado blanco (merluza, bacalao o tilapia, unos 150 g)",
          "1 calabacín en medias lunas", "½ pimiento en tiras",
          "jitomates cherry", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y perejil al gusto"],
 "passos": [
   "Sazona el pescado con sal, pimienta, el ajo y el jugo de limón.",
   "Calienta un sartén grande con la mitad del aceite de oliva a fuego medio-alto. De un lado, pon el filete y déjalo de 3 a 4 minutos de cada lado, volteándolo con cuidado, hasta que quede dorado y se separe en láminas.",
   "Del otro lado del sartén (o después de sacar el pescado), pon el resto del aceite de oliva y saltea el calabacín, el pimiento y los jitomates cherry de 4 a 5 minutos, revolviendo, hasta que queden tiernos pero todavía firmes.",
   "Sazona las verduras con sal y pimienta.",
   "Arma el plato con el pescado y las verduras salteadas. Espolvorea perejil y termina con un poco más de limón."],
 "porcoes8": ["120 g de pescado · verduras",
              "150 g de pescado · verduras",
              "150 g de pescado · verduras · 1 papa pequeña",
              "170 g de pescado · verduras · 1 papa",
              "170 g de pescado · verduras · 1 papa",
              "200 g de pescado · verduras · 1 papa",
              "220 g de pescado · verduras · 1 papa grande",
              "250 g de pescado · verduras · 2 papas pequeñas"],
 "dica": "El pescado blanco es ligero y se cocina en minutos, y hecho en el mismo sartén que las verduras usa muy poco aceite. Las verduras salteadas aportan color, fibra y volumen por casi nada de calorías. Es de las cenas más rápidas, ligeras y prácticas que existen.",
},
{
 "nome": "Pechuga de pavo a la plancha con puré de calabaza",
 "hook": "El pavo magro sobre un puré de calabaza anaranjado y naturalmente dulce — una cena ligera con aire acogedor.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 390,
 "ings": ["1 filete de pechuga de pavo (unos 150 g)",
          "1 trozo de calabaza en cubos (unos 300 g)",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta, salvia o romero al gusto",
          "hojas verdes para la ensalada"],
 "passos": [
   "Cuece la calabaza en agua hirviendo 15 minutos, hasta que quede muy suave. Escúrrela muy bien y aplástala con un tenedor, con una pizca de sal, hasta que quede un puré terso y cremoso.",
   "Sazona el pavo con sal, pimienta, el ajo y el jugo de limón.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio y asa el filete de 3 a 4 minutos de cada lado, hasta que quede dorado y blanco por dentro.",
   "Si quieres, termina el pavo con un poco de salvia o romero en el sartén en los últimos segundos, para perfumarlo.",
   "Arma el plato con el puré de calabaza, el pavo rebanado encima y una ensalada verde a un lado."],
 "porcoes8": ["120 g de pavo · ½ porción de puré · ensalada",
              "150 g de pavo · 1 porción de puré · ensalada",
              "150 g de pavo · 1 porción de puré · ensalada",
              "170 g de pavo · 1 porción de puré · ensalada",
              "170 g de pavo · 1 porción de puré · ensalada",
              "200 g de pavo · 1 porción grande de puré · ensalada",
              "220 g de pavo · porción grande de puré · ensalada",
              "250 g de pavo · porción doble de puré · ensalada"],
 "dica": "La pechuga de pavo es todavía más magra que el pollo, llena de proteína. La calabaza hace un puré cremoso y dulce con muy pocas calorías, matando el antojo de algo dulce y llenando el plato de fibra. Una cena ligera, reconfortante y colorida.",
},
{
 "nome": "Sopa de pollo con fideos",
 "hook": "La sopa de pollo de siempre, reforzada con bastante pollo y verduras — la cena que abraza, cura y aun así entra en tu dieta.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 360,
 "ings": ["1 filete de pechuga de pollo (unos 150 g)",
          "50 g de pasta pequeña (fideos o letritas)",
          "1 zanahoria en cubos pequeños",
          "1 tallo de apio, picado (opcional)", "1 cebolla, picada",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto", "1,2 litros de agua"],
 "passos": [
   "En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos, revolviendo.",
   "Agrega el filete de pollo entero, la zanahoria, el apio y el agua. Sazona con sal y cocina 15 minutos, hasta que el pollo esté cocido.",
   "Saca el pollo, déjalo enfriar un poco y deshébralo. Regresa el pollo deshebrado a la olla.",
   "Agrega la pasta pequeña y cocina otros 8 a 10 minutos, hasta que la pasta quede suave (revuelve de vez en cuando para que no se pegue al fondo).",
   "Prueba la sal, espolvorea hierbas frescas y sirve bien caliente."],
 "porcoes8": ["1 cucharón · pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo",
              "2 cucharones · pollo extra",
              "2 cucharones · pollo extra · pasta extra",
              "3 cucharones · pollo",
              "3 cucharones · pollo extra · pasta extra",
              "3 cucharones grandes · doble pollo"],
 "dica": "La sopa de pollo es ligera y reconfortante: el caldo con verduras llena el estómago con pocas calorías y el pollo da la proteína que te llena. Con poca pasta y mucho pollo y verduras, se vuelve una cena completa y caliente, ideal para noches frías o días sin apetito.",
},
{
 "nome": "Camarones en curry ligero con verduras",
 "hook": "Camarones bañados en una salsa dorada de curry y leche de coco light — aromática, cremosa y sorprendentemente ligera.",
 "tempo": "25 min", "rende": "2 porciones", "kcal_base": 380,
 "ings": ["300 g de camarones limpios", "1 cebolla, picada",
          "1 diente de ajo, picado", "1 pimiento en tiras",
          "1 cucharadita de curry en polvo",
          "120 ml de leche de coco light", "1 jitomate, picado",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y cilantro al gusto", "arroz para servir"],
 "passos": [
   "Sazona los camarones con sal, pimienta y el jugo de limón. Déjalos tomar sabor 5 minutos.",
   "Calienta el aceite de oliva en un sartén a fuego medio y fríe la cebolla, el ajo y el pimiento 3 minutos, revolviendo.",
   "Agrega el curry y revuelve 30 segundos, para que la especia suelte su aroma. Agrega el jitomate y cocina 3 minutos, hasta que se deshaga.",
   "Agrega la leche de coco light y deja que hierva suavemente. Pon los camarones y cocina de 3 a 4 minutos, solo hasta que se pongan rosados. No los cuezas de más, o quedan chiclosos.",
   "Espolvorea cilantro y sirve sobre una porción pequeña de arroz."],
 "porcoes8": ["120 g de camarones · 2 cucharadas de arroz",
              "150 g de camarones · 3 cucharadas de arroz",
              "150 g de camarones · 3 cucharadas de arroz",
              "170 g de camarones · 4 cucharadas de arroz",
              "170 g de camarones · 4 cucharadas de arroz",
              "200 g de camarones · 4 cucharadas de arroz",
              "220 g de camarones · 5 cucharadas de arroz",
              "250 g de camarones · 5 cucharadas de arroz"],
 "dica": "El camarón es casi proteína pura y se cocina rápido. La leche de coco light da cremosidad a la salsa con mucha menos grasa que la crema, y el curry la perfuma y da la sensación de un plato especial. Con un poco de arroz, es una cena ligera y llena de sabor.",
},
{
 "nome": "Guisado de res con papa",
 "hook": "Cubos de res que se deshacen en un caldo espeso con papa — el guisado que reconforta en una noche fría, en la porción correcta.",
 "tempo": "1 h", "rende": "3 porciones", "kcal_base": 430,
 "ings": ["300 g de res magra en cubos (chambarete o diezmillo magro)",
          "2 papas en cubos grandes", "1 zanahoria en rodajas",
          "1 cebolla, picada", "2 dientes de ajo, picados",
          "1 jitomate, picado", "1 hoja de laurel",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto"],
 "passos": [
   "Sazona los cubos de res con sal y pimienta. En una olla, calienta el aceite de oliva y dora la carne por todos lados, revolviendo, 6 minutos.",
   "Agrega la cebolla y el ajo y fríe 2 minutos. Agrega el jitomate y la hoja de laurel y revuelve 2 minutos.",
   "Cubre con agua caliente, tapa la olla y cocina a fuego bajo 35 minutos, hasta que la carne empiece a suavizarse. Si se seca, agrega más agua caliente.",
   "Agrega la papa y la zanahoria y cocina otros 20 minutos, hasta que la carne se deshaga y la papa quede suave (la papa ayuda a espesar el caldo).",
   "Saca la hoja de laurel, espolvorea hierbas frescas y sirve caliente, solo o con un poco de arroz."],
 "porcoes8": ["½ porción · sin arroz",
              "1 porción · sin arroz",
              "1 porción · 2 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción · 3 cucharadas de arroz",
              "1 porción grande · 4 cucharadas de arroz",
              "porción grande · 5 cucharadas de arroz",
              "porción doble · 5 cucharadas de arroz"],
 "dica": "La cocción lenta suaviza los cortes magros y baratos, y la papa espesa el caldo de forma natural, así que no necesitas harina ni crema. Es un plato sustancioso que te llena con calorías controladas — el consuelo de un guisado sin salirte de tu dieta.",
},
{
 "nome": "Omelette al horno con jamón magro y verduras",
 "hook": "Un omelette alto y esponjoso horneado, relleno de verduras y jamón magro — lo cortas en rebanadas y alcanza para la familia.",
 "tempo": "30 min", "rende": "3 porciones", "kcal_base": 360,
 "ings": ["6 huevos", "4 rebanadas de jamón de pavo magro, picadas",
          "½ pimiento, picado", "1 jitomate, picado",
          "un puñado de espinaca",
          "2 cucharadas de queso rallado bajo en grasa",
          "1 cucharadita de aceite de oliva",
          "cebollín, sal y pimienta al gusto"],
 "passos": [
   "Pon el horno a fuego medio (180 °C). Unta un refractario pequeño con el aceite de oliva.",
   "En un tazón, bate los huevos con sal y pimienta 30 segundos.",
   "Agrega a los huevos el jamón picado, el pimiento, el jitomate, la espinaca y el cebollín, y mezcla.",
   "Vierte la mezcla en el refractario y espolvorea el queso rallado encima.",
   "Hornea de 20 a 25 minutos, hasta que el omelette se infle, cuaje en el centro y quede ligeramente dorado arriba. Córtalo en rebanadas y sirve caliente o tibio, con una ensalada."],
 "porcoes8": ["1 rebanada · ensalada",
              "1 rebanada grande · ensalada",
              "1 rebanada grande · ensalada · 1 rebanada de pan",
              "2 rebanadas · ensalada · 1 rebanada de pan",
              "2 rebanadas · ensalada · 1 rebanada de pan",
              "2 rebanadas grandes · ensalada · 1 rebanada de pan",
              "2 rebanadas grandes · ensalada · 2 rebanadas de pan",
              "3 rebanadas · ensalada · 2 rebanadas de pan"],
 "dica": "Los huevos son una proteína completa y muy saciante, y horneados no necesitan fritura. El jamón de pavo magro suma sabor y proteína con poca grasa, y las verduras aportan volumen y fibra. Rinde mucho, se conserva bien y es una cena ligera y práctica.",
},
{
 "nome": "Tilapia al horno con jitomate y cebolla",
 "hook": "Filetes de pescado blanco horneados bajo una cama de jitomate y cebolla que se convierten en salsa natural — ligero, jugoso y sin esfuerzo.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 370,
 "ings": ["2 filetes de tilapia (u otro pescado blanco, unos 300 g)",
          "2 jitomates en rebanadas", "1 cebolla en rebanadas",
          "1 diente de ajo en rebanadas", "1 cucharadita de aceite de oliva",
          "jugo de 1 limón",
          "sal, pimienta, orégano y perejil al gusto"],
 "passos": [
   "Pon el horno a fuego medio-alto (200 °C). En un refractario, reparte la mitad de las rebanadas de jitomate y cebolla en el fondo, formando una cama.",
   "Sazona los filetes de pescado con sal, pimienta, el ajo, el orégano y el jugo de limón. Ponlos sobre la cama de jitomate y cebolla.",
   "Cubre los filetes con el resto del jitomate y la cebolla y rocía con el aceite de oliva.",
   "Hornea de 20 a 25 minutos, hasta que el pescado se separe en láminas y el jitomate y la cebolla queden suaves, soltando una salsa natural.",
   "Espolvorea perejil y sirve con la salsa encima, junto con una ensalada o un poco de arroz."],
 "porcoes8": ["120 g de pescado · verduras",
              "150 g de pescado · verduras",
              "150 g de pescado · verduras · 2 cucharadas de arroz",
              "170 g de pescado · verduras · 3 cucharadas de arroz",
              "170 g de pescado · verduras · 3 cucharadas de arroz",
              "200 g de pescado · verduras · 3 cucharadas de arroz",
              "220 g de pescado · verduras · 4 cucharadas de arroz",
              "250 g de pescado · verduras · 4 cucharadas de arroz"],
 "dica": "El pescado blanco es extremadamente magro y rico en proteína, y hornearlo bajo jitomate y cebolla crea una salsa natural sin grasa, manteniendo el filete jugoso. Es una cena ligera, barata y llena de sabor que prácticamente se hace sola en el horno.",
},
{
 "nome": "Albóndigas de pollo en sopa",
 "hook": "Bolitas suaves de pollo cocidas en un caldo ligero con verduras — una sopa divertida y completa que llena y calienta.",
 "tempo": "35 min", "rende": "3 porciones", "kcal_base": 350,
 "ings": ["300 g de carne molida de pechuga de pollo", "1 huevo",
          "2 cucharadas de avena", "1 zanahoria en cubos pequeños",
          "1 papa en cubos pequeños", "1 calabacín en cubos pequeños",
          "1 cebolla, picada", "1 diente de ajo, picado",
          "1 cucharadita de aceite de oliva",
          "sal, pimienta y hierbas frescas al gusto", "1,2 litros de agua"],
 "passos": [
   "En un tazón, mezcla la carne molida de pollo, el huevo, la avena, sal y pimienta. Amasa con las manos y forma bolitas pequeñas del tamaño de una nuez.",
   "En una olla, calienta el aceite de oliva y fríe la cebolla y el ajo 2 minutos. Agrega el agua, la zanahoria y la papa, sazona con sal y cocina 10 minutos.",
   "Con cuidado, deja caer las albóndigas crudas en el caldo hirviendo, una por una. No revuelvas durante 3 minutos, para que se firmen.",
   "Agrega el calabacín y cocina otros 10 minutos, hasta que las albóndigas estén cocidas por dentro y las verduras suaves.",
   "Prueba la sal, espolvorea hierbas frescas y sirve bien caliente."],
 "porcoes8": ["3 albóndigas · 1 cucharón de caldo",
              "4 albóndigas · 2 cucharones",
              "4 albóndigas · 2 cucharones",
              "5 albóndigas · 2 cucharones · 1 rebanada de pan",
              "5 albóndigas · 2 cucharones · 1 rebanada de pan",
              "6 albóndigas · 3 cucharones · 1 rebanada de pan",
              "7 albóndigas · 3 cucharones · 2 rebanadas de pan",
              "8 albóndigas · 3 cucharones · 2 rebanadas de pan"],
 "dica": "Las albóndigas de pollo dan la proteína que te llena, y cocidas dentro de la sopa hacen el caldo más sabroso. Todo ese líquido y las verduras llenan el estómago con pocas calorías. Es una cena completa, ligera y reconfortante que gusta hasta a quien no le gustan las sopas aguadas.",
},
{
 "nome": "Camarones a la plancha con ensalada de hojas verdes",
 "hook": "Camarones dorados en ajo sobre una ensalada fresca y crujiente — una cena ligera y elegante lista en quince minutos.",
 "tempo": "15 min", "rende": "1 porción", "kcal_base": 330,
 "ings": ["150 g de camarones grandes limpios", "hojas verdes mixtas",
          "½ jitomate en cubos", "½ pepino en rodajas",
          "cebolla morada en rebanadas delgadas",
          "2 dientes de ajo, picados", "1 cucharadita de aceite de oliva",
          "jugo de ½ limón", "sal, pimienta y perejil al gusto"],
 "passos": [
   "Seca bien los camarones con papel absorbente y sazónalos con sal, pimienta y la mitad del jugo de limón.",
   "Calienta un sartén antiadherente con el aceite de oliva a fuego medio-alto. Agrega el ajo y revuelve 30 segundos, solo hasta que huela rico.",
   "Pon los camarones y ásalos de 2 a 3 minutos de cada lado, solo hasta que se pongan rosados y dorados. No los cuezas de más.",
   "En un tazón grande o plato, arma la ensalada con las hojas verdes, el jitomate, el pepino y la cebolla morada. Aliña con el resto del limón, sal y pimienta.",
   "Pon los camarones calientes sobre la ensalada, espolvorea perejil y sirve de inmediato."],
 "porcoes8": ["120 g de camarones · ensalada",
              "150 g de camarones · ensalada",
              "150 g de camarones · ensalada · 1 rebanada de pan",
              "170 g de camarones · ensalada · 1 rebanada de pan",
              "170 g de camarones · ensalada · 2 cucharadas de arroz",
              "200 g de camarones · ensalada · 3 cucharadas de arroz",
              "220 g de camarones · ensalada · 3 cucharadas de arroz",
              "250 g de camarones · ensalada · 4 cucharadas de arroz"],
 "dica": "El camarón es casi proteína pura, con muy pocas calorías, así que llena el plato sin pesarte. Dorado en ajo y servido sobre una ensalada fresca y crujiente, es de las cenas más ligeras posibles — ideal para la noche, cuando tu cuerpo quema menos energía.",
},
{
 "nome": "Pescado guisado con leche de coco y verduras",
 "hook": "Un guisado de pescado cremoso y aromático con un toque de leche de coco — tan ligero como el mar, tan reconfortante como un abrazo.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 390,
 "ings": ["300 g de filete de pescado blanco en trozos grandes",
          "1 pimiento en tiras", "1 jitomate, picado", "1 cebolla en tiras",
          "2 dientes de ajo, picados", "120 ml de leche de coco light",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y cilantro al gusto"],
 "passos": [
   "Sazona los trozos de pescado con sal, pimienta, el ajo y el jugo de limón. Déjalos tomar sabor 5 minutos.",
   "En una olla amplia, calienta el aceite de oliva y haz una cama con la cebolla, el pimiento y el jitomate. Saltea 3 minutos, revolviendo.",
   "Pon los trozos de pescado sobre las verduras (no revuelvas mucho, para que el pescado no se deshaga).",
   "Vierte encima la leche de coco light, tapa la olla y cocina a fuego medio-bajo de 10 a 12 minutos, hasta que el pescado quede blanco y suave y el caldo tenga cuerpo.",
   "Espolvorea cilantro y sirve con una porción pequeña de arroz, para aprovechar el caldo."],
 "porcoes8": ["120 g de pescado · 2 cucharadas de arroz",
              "150 g de pescado · 3 cucharadas de arroz",
              "150 g de pescado · 3 cucharadas de arroz",
              "170 g de pescado · 4 cucharadas de arroz",
              "170 g de pescado · 4 cucharadas de arroz",
              "200 g de pescado · 4 cucharadas de arroz",
              "220 g de pescado · 5 cucharadas de arroz",
              "250 g de pescado · 5 cucharadas de arroz"],
 "dica": "El pescado blanco es magro y rico en proteína, y la leche de coco light da cremosidad al caldo con mucha menos grasa que la crema. Las verduras sueltan agua y forman una salsa ligera y aromática. Es un guisado reconfortante y ligero, perfecto para la cena.",
},
{
 "nome": "Brochetas de res y verduras",
 "hook": "Cubos jugosos de res alternados con verduras coloridas, asados hasta dorarse — sabor a asado en la medida correcta.",
 "tempo": "30 min", "rende": "2 porciones", "kcal_base": 420,
 "ings": ["250 g de res magra en cubos (sirloin o pulpa)",
          "1 pimiento en cuadros", "1 cebolla en trozos",
          "1 calabacín en rodajas gruesas", "jitomates cherry",
          "1 diente de ajo, picado", "1 cucharadita de aceite de oliva",
          "sal, pimienta y paprika al gusto", "palillos para brocheta"],
 "passos": [
   "Sazona los cubos de res con sal, pimienta, paprika y el ajo. Déjalos tomar sabor 10 minutos.",
   "Arma las brochetas alternando un cubo de res, un cuadro de pimiento, un trozo de cebolla, una rodaja de calabacín y un jitomate cherry, hasta llenar el palillo.",
   "Unta las brochetas con el aceite de oliva.",
   "Calienta un sartén grande o una plancha a fuego medio-alto. Pon las brochetas y voltéalas cada 3 minutos, unos 12 minutos en total, hasta que la res quede dorada por fuera y al término que te guste.",
   "Sirve las brochetas con una ensalada o un poco de arroz."],
 "porcoes8": ["1 brocheta · ensalada",
              "2 brochetas · ensalada",
              "2 brochetas · ensalada · 2 cucharadas de arroz",
              "2 brochetas · ensalada · 3 cucharadas de arroz",
              "2 brochetas · ensalada · 3 cucharadas de arroz",
              "3 brochetas · ensalada · 3 cucharadas de arroz",
              "3 brochetas · ensalada · 4 cucharadas de arroz",
              "3 brochetas grandes · ensalada · 4 cucharadas de arroz"],
 "dica": "Las brochetas matan el antojo de asado de forma ligera: la res magra da proteína y las verduras coloridas llenan el palillo de fibra y pocas calorías. Ensartarlas ayuda a controlar la porción de forma natural, y asarlas sin aceite mantiene todo sabroso y ligero.",
},
{
 "nome": "Ensalada tibia con pollo, huevo y papa",
 "hook": "Papas doradas, pollo asado y huevo, todo tibio sobre hojas frescas — una ensalada que es una cena completa y acogedora.",
 "tempo": "30 min", "rende": "1 porción", "kcal_base": 420,
 "ings": ["1 filete de pechuga de pollo (unos 130 g)",
          "1 papa pequeña en cubos", "2 huevos cocidos", "hojas verdes",
          "jitomates cherry", "cebolla morada en rebanadas",
          "1 cucharadita de aceite de oliva", "jugo de ½ limón",
          "sal, pimienta y mostaza al gusto"],
 "passos": [
   "Cuece los cubos de papa en agua hirviendo con sal 12 minutos, hasta que queden suaves. Escúrrelos. Si los quieres dorados, saltéalos 3 minutos en un sartén con unas gotas de aceite de oliva.",
   "Cuece los huevos 9 minutos, ponlos bajo el chorro de agua fría, pélalos y córtalos a la mitad.",
   "Sazona el pollo con sal y pimienta y ásalo en un sartén antiadherente de 4 a 5 minutos de cada lado, hasta que quede dorado. Córtalo en tiras.",
   "En un tazón o plato, haz una cama de hojas verdes y pon encima los jitomates cherry y la cebolla.",
   "Acomoda arriba la papa tibia, las tiras de pollo y los huevos. Haz un aderezo mezclando el aceite de oliva, el jugo de limón, la mostaza, sal y pimienta, rocíalo y sirve de inmediato."],
 "porcoes8": ["100 g de pollo · ½ papa · 1 huevo",
              "130 g de pollo · 1 papa pequeña · 2 huevos",
              "130 g de pollo · 1 papa · 2 huevos",
              "150 g de pollo · 1 papa · 2 huevos",
              "150 g de pollo · 1 papa · 2 huevos",
              "170 g de pollo · 1 papa grande · 2 huevos",
              "200 g de pollo · 1 papa grande · 3 huevos",
              "220 g de pollo · 2 papas pequeñas · 3 huevos"],
 "dica": "Es una ensalada que llena como una comida caliente: el pollo y el huevo dan doble proteína, la papa en la medida correcta aporta energía y las hojas llenan el plato de fibra. Servida tibia, es reconfortante y ligera al mismo tiempo — ideal para la cena.",
},
]
