# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). INGLÊS (mercado US).

Tradução literal de `receitas_jantar.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "you", medidas caseiras americanas, carne e peixe em OZ/LB,
líquido de panela em CUPS, forno em °F.
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/066-100).
Jantar = mais leve que o almoço (peixe, sopas, assados). Sem vegetariano.
porcoes8 na ordem: Mulher 120-155/156-185/186-220/220+ lb · Homem 155-185/186-220/221-265/265+ lb
Metas (kcal): 340/420/480/540 · 520/590/650/720
"""

RECEITAS = [
{
 "nome": "Pumpkin Soup with Shredded Chicken",
 "hook": "Creamy, orange and comforting — a soup that warms your evening and still brings chicken protein to really fill you up.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 340,
 "ings": ["1 large piece of pumpkin in cubes (about 1 lb)", "1 chicken breast fillet (about 5 oz)",
          "1 onion, chopped", "1 clove of garlic, chopped", "1 tsp olive oil",
          "salt, pepper and grated ginger to taste", "fresh herbs to finish", "4 cups of water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes, stirring, until they turn clear.",
   "Add the pumpkin cubes, the whole chicken fillet and the water. Bring it to a boil and cook for 20 minutes, until the pumpkin is very soft.",
   "Take the chicken out, let it cool a little and shred it with two forks. Set it aside.",
   "With a hand blender (that stick blender) or in a regular blender, blend the pumpkin with the broth until it turns into a smooth cream. Be careful with the hot liquid.",
   "Put the cream back in the pot, add the shredded chicken, the ginger, salt and pepper and warm it for 3 minutes. Serve with fresh herbs on top."],
 "porcoes8": ["1 ladle · a little chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Pumpkin has a lot of water and fiber, which fills your stomach with very few calories. The heat of the soup makes you eat more slowly, and the shredded chicken turns the light cream into a complete meal that holds hunger back until bedtime, with no heaviness.",
},
{
 "nome": "Chicken Fillet in Mustard Sauce with Steamed Vegetables",
 "hook": "A creamy mustard and yogurt sauce dresses the chicken up — light, elegant and quick to make for dinner.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 400,
 "ings": ["1 chicken breast fillet (about 5 oz)", "1 tbsp plain yogurt with no sugar",
          "1 tsp mustard", "1 cup of broccoli, carrot and green beans", "1 clove of garlic, chopped",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Cut the vegetables into similar pieces. Cook them in a steamer (or in a covered pot with a finger of water) for 6 minutes, until they are tender but still firm and colorful.",
   "Season the chicken with salt, pepper and the garlic. Heat a nonstick pan with the olive oil over medium heat and grill the fillet for 4 to 5 minutes on each side, until it is golden and white inside.",
   "In a small bowl, mix the yogurt, the mustard, the lemon juice, salt and pepper, until it turns into a creamy sauce.",
   "Put the chicken on the plate, drizzle it with the mustard sauce and serve with the vegetables on the side.",
   "Sprinkle fresh herbs and serve hot."],
 "porcoes8": ["4 oz chicken · vegetables",
              "5 oz chicken · vegetables",
              "5 oz chicken · vegetables · 2 tbsp rice",
              "6 oz chicken · vegetables · 2 tbsp rice",
              "6 oz chicken · vegetables · 3 tbsp rice",
              "7 oz chicken · vegetables · 3 tbsp rice",
              "8 oz chicken · vegetables · 4 tbsp rice",
              "9 oz chicken · vegetables · 4 tbsp rice"],
 "dica": "The creamy sauce comes from yogurt, not from cream or butter, cutting a lot of fat. Mustard brings a strong flavor with almost no calories. Steaming the vegetables keeps the nutrients and uses no oil — a light dinner that looks like restaurant food.",
},
{
 "nome": "Fish Baked in Parchment with Vegetables",
 "hook": "The fish cooks in its own steam inside the paper, coming out incredibly tender — and you open the parcel at the table, warm and fragrant.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "1/2 zucchini in thin rounds",
          "1/2 carrot in thin strips", "cherry tomatoes, cut", "1 clove of garlic, sliced", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and herbs (thyme or oregano) to taste", "1 large sheet of parchment paper"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the zucchini and the carrot into thin slices, so they cook in the same time as the fish.",
   "In the center of a large sheet of parchment paper, make a bed with the vegetables. Season with a little salt, pepper and half of the olive oil.",
   "Put the fish fillet on top. Season with salt, pepper, the garlic, the herbs, the lemon juice and the rest of the olive oil.",
   "Close the paper like a parcel: bring the ends together and fold the edges well, leaving some air space inside, to make a sealed packet.",
   "Bake for 18 to 20 minutes. Open it carefully (hot steam comes out) and serve it in the paper or move it to a plate."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 1 small potato",
              "6 oz fish · vegetables · 1 potato",
              "6 oz fish · vegetables · 1 potato",
              "7 oz fish · vegetables · 1 potato",
              "8 oz fish · vegetables · 1 large potato",
              "9 oz fish · vegetables · 2 small potatoes"],
 "dica": "Cooking in parchment uses almost no fat: the fish and the vegetables cook in their own steam, keeping their flavor and going very tender. It is one of the lightest and healthiest ways to cook fish, perfect for a dinner with no heaviness and no dirty pans.",
},
{
 "nome": "Chicken Pie with Cauliflower Mash",
 "hook": "All the comfort of a browned shepherd's pie, but the topping is cauliflower mash — creamy, light and with far fewer calories.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["1 medium cauliflower", "2 cooked and shredded chicken breast fillets (about 10 oz)", "1 onion, chopped",
          "1 clove of garlic, chopped", "1 tomato, chopped", "1 tsp olive oil",
          "2 tbsp grated low-fat cheese", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Cut the cauliflower into pieces and cook it in boiling water for 12 minutes, until it is very soft. Drain it very well (cauliflower holds water) and mash it with a fork, with a pinch of salt, until it turns into a creamy mash.",
   "In a pan, heat the olive oil and fry the onion and the garlic for 2 minutes. Add the shredded chicken and the tomato, season with salt and pepper and cook for 5 minutes, until it makes a soft filling.",
   "In a baking dish, spread the chicken on the bottom and cover it with the cauliflower mash.",
   "Sprinkle the grated cheese on top.",
   "Bake at medium-high heat (400 °F) for 15 minutes, until the surface is lightly golden. Sprinkle fresh herbs and serve."],
 "porcoes8": ["1/2 serving · salad",
              "1 serving · salad",
              "1 serving · salad",
              "1 serving · extra chicken · salad",
              "1 serving · extra chicken · salad",
              "1 large serving · salad",
              "1 large serving · extra chicken · salad",
              "double serving · salad"],
 "dica": "Cauliflower instead of potato cuts a good part of the calories and the carbs, keeping the creaminess of the mash. The shredded chicken brings protein and fullness. It is the ideal comforting plate for anyone who wants to eat something warm and light before bed.",
},
{
 "nome": "Vegetable Soup with Lean Beef",
 "hook": "The soup that tastes like grandma made it: pieces of tender beef and vegetables in a seasoned broth that fills your belly and warms your soul.",
 "tempo": "50 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["9 oz lean beef in cubes (shank or round)", "1 potato in cubes", "1 carrot in cubes",
          "1 zucchini in cubes", "1 tomato, chopped", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste", "6 cups of water"],
 "passos": [
   "In a pot, heat the olive oil and brown the beef cubes on all sides, stirring, for 5 minutes.",
   "Add the onion and the garlic and fry for 2 minutes. Add the tomato and stir for another 2 minutes.",
   "Pour in the water, season with salt and pepper, cover it and cook over medium-low heat for 30 minutes, until the meat starts to go tender.",
   "Add the potato, the carrot and the zucchini and cook for another 15 minutes, until the meat is very tender and the vegetables are done.",
   "Check the salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · a little beef",
              "2 ladles · beef",
              "2 ladles · beef",
              "2 ladles · beef · 1 slice bread",
              "2 ladles · extra beef · 1 slice bread",
              "3 ladles · beef · 1 slice bread",
              "3 ladles · extra beef · 2 slices bread",
              "3 large ladles · double beef · 2 slices bread"],
 "dica": "Soups with plenty of liquid and vegetables fill your stomach with few calories, and eating them hot makes you eat slowly and feel full sooner. The lean beef brings protein, making the soup hearty enough to be a complete dinner.",
},
{
 "nome": "Salmon with Yogurt and Dill Sauce and Vegetables",
 "hook": "The pink salmon gets a fresh yogurt and dill sauce — sophisticated, light and made in twenty minutes.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 430,
 "ings": ["1 salmon fillet (about 5 oz)", "2 tbsp plain yogurt with no sugar", "chopped dill",
          "1 cup of broccoli and carrot", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and chopped garlic to taste"],
 "passos": [
   "Cut the broccoli into florets and the carrot into rounds. Steam them for 6 minutes, until they are tender but still firm.",
   "Season the salmon with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat. Put the salmon in skin side down and leave it 4 minutes, then turn it and leave it another 3 minutes, until it turns lighter in color and flakes apart with a fork.",
   "Prepare the sauce: mix the yogurt, the chopped dill, a little salt and a few drops of lemon.",
   "Build the plate with the salmon, the vegetables on the side and the yogurt sauce on top or on the side."],
 "porcoes8": ["4 oz salmon · vegetables",
              "5 oz salmon · vegetables",
              "5 oz salmon · vegetables · 1 small potato",
              "6 oz salmon · vegetables · 1 potato",
              "6 oz salmon · vegetables · 1 potato",
              "7 oz salmon · vegetables · 1 potato",
              "8 oz salmon · vegetables · 1 large potato",
              "9 oz salmon · vegetables · 2 small potatoes"],
 "dica": "Salmon brings the good fat (omega-3) that fills you up and is good for your heart. The yogurt and dill sauce replaces greasy creamy sauces with a fresh, protein-rich version. With steamed vegetables, it is a light, pretty and complete dinner.",
},
{
 "nome": "Lemon Chicken with Roasted Vegetables",
 "hook": "The chicken stays juicy and lightly citrusy, roasted together with vegetables that caramelize at the edges — one tray, zero work.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["2 skinless chicken thighs (or 2 fillets, about 10 oz)", "1 zucchini in pieces", "1 bell pepper in pieces",
          "1 onion in wedges", "cherry tomatoes", "2 cloves of garlic", "1 tsp olive oil",
          "juice of 1 lemon", "salt, pepper and oregano to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). On a baking tray, spread the zucchini, the bell pepper, the onion, the cherry tomatoes and the cloves of garlic.",
   "Season the vegetables with salt, pepper, oregano and half of the olive oil, and mix.",
   "Season the chicken with salt, pepper, the lemon juice and the rest of the olive oil. Put the pieces among the vegetables.",
   "Bake for 35 minutes, turning halfway through, until the chicken is golden and cooked inside (the liquid that runs out when you pierce it comes out clear) and the vegetables are soft with golden edges.",
   "Serve straight from the tray, drizzling with the lemon juices that formed."],
 "porcoes8": ["1 thigh · vegetables",
              "1 thigh · vegetables",
              "1 large thigh · vegetables",
              "2 thighs · vegetables",
              "2 thighs · vegetables",
              "2 thighs · vegetables · 1 potato",
              "2 thighs · vegetables · 1 large potato",
              "3 thighs · vegetables · 1 large potato"],
 "dica": "Roasting with no skin and little oil keeps the chicken light, and the lemon brings freshness with no added calories. Roasted vegetables go sweet and tasty on their own, so you do not need heavy sauces. A practical, colorful and light dinner made on a single tray.",
},
{
 "nome": "Turkey Meatballs with Zucchini in Sauce",
 "hook": "Light turkey meatballs swimming in a fresh tomato sauce, over zucchini ribbons — the pasta that does not weigh on the scale.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["9 oz ground turkey breast (or ground chicken)", "1 egg", "2 tbsp oats",
          "2 large zucchini", "3 ripe tomatoes, chopped (or tomato sauce)", "1 onion, chopped",
          "2 cloves of garlic, chopped", "1 tsp olive oil", "salt, pepper and basil to taste"],
 "passos": [
   "In a bowl, mix the ground turkey, the egg, the oats, half of the garlic, salt and pepper. Knead it with your hands and roll balls the size of a walnut.",
   "Heat the olive oil in a wide pot and brown the meatballs on all sides, turning them carefully, for 5 minutes. Take them out and set them aside.",
   "In the same pot, fry the onion and the rest of the garlic for 2 minutes. Add the chopped tomatoes, salt and pepper and cook for 10 minutes, until it turns into a sauce.",
   "Put the meatballs back into the sauce and cook for another 8 minutes, until they are done inside.",
   "With a vegetable peeler, make thin ribbons of zucchini (like noodles). Put the raw ribbons on the plate and pour the hot meatballs with the sauce over them — the heat softens the zucchini. Sprinkle basil."],
 "porcoes8": ["3 meatballs · zucchini",
              "4 meatballs · zucchini",
              "4 meatballs · zucchini · 2 tbsp rice",
              "5 meatballs · zucchini · 2 tbsp rice",
              "5 meatballs · zucchini · 3 tbsp rice",
              "6 meatballs · zucchini · 3 tbsp rice",
              "7 meatballs · zucchini · 4 tbsp rice",
              "8 meatballs · zucchini · 4 tbsp rice"],
 "dica": "Swapping pasta for zucchini ribbons cuts almost all the carbs and fills the plate with fiber and water. Turkey meatballs are lean and rich in protein, and a tomato sauce made fresh, with no sugar, keeps the dinner tasty and very light.",
},
{
 "nome": "Herb-Crusted Fish Fillet with Mashed Potato",
 "hook": "A crisp herb crust outside, tender fish inside — it looks like a chef's plate, but it is simple and light.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 410,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "2 tbsp wholegrain breadcrumbs",
          "finely chopped parsley and chives", "1 medium potato", "1 tsp olive oil",
          "juice of 1/2 lemon", "1 clove of garlic, chopped", "salt and pepper to taste"],
 "passos": [
   "Peel and cook the potato in boiling water for 15 minutes, until it is very soft. Drain and mash it with a fork, with a pinch of salt, until it turns into a smooth mash.",
   "Turn the oven to medium-high heat (400 °F). Season the fish with salt, pepper, the garlic and the lemon juice.",
   "In a small bowl, mix the breadcrumbs with the parsley, the chives and a little olive oil, making a moist crumb mix.",
   "Put the fish on a baking tray and cover the top with the herb crumbs, pressing lightly so they stick.",
   "Bake for 15 to 18 minutes, until the crust is golden and crisp and the fish flakes apart. Serve with the mashed potato."],
 "porcoes8": ["4 oz fish · 1/2 serving mash",
              "5 oz fish · 1 serving mash",
              "5 oz fish · 1 serving mash",
              "6 oz fish · 1 serving mash",
              "6 oz fish · 1 serving mash",
              "7 oz fish · 1 large serving mash",
              "8 oz fish · large serving mash",
              "9 oz fish · double serving mash"],
 "dica": "The herb crust with just a little breadcrumb gives crunch with no frying, keeping the fish light and full of flavor. White fish is extremely lean and rich in protein, and the mash in the right measure comforts without going overboard — a pretty and light dinner.",
},
{
 "nome": "Grilled Steak with Chickpea Salad",
 "hook": "A steak cooked just right beside a warm chickpea salad — double protein that fills you up without weighing on your dinner.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 440,
 "ings": ["1 lean beef steak (about 4 oz)", "1/2 cup cooked chickpeas",
          "1/2 tomato in cubes", "chopped red onion", "green leaves", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the steak with salt and pepper on both sides.",
   "Heat a nonstick pan over high heat with a few drops of olive oil. Grill the steak for 2 to 3 minutes on each side, without moving it, until it is golden outside and done the way you like. Let it rest for 2 minutes before cutting.",
   "In a bowl, mix the chickpeas, the tomato, the red onion and the parsley.",
   "Dress the salad with the olive oil, the lemon juice, salt and pepper.",
   "Serve the sliced steak over a bed of green leaves, with the chickpea salad on the side."],
 "porcoes8": ["3.5 oz meat · 1/3 cup chickpeas · salad",
              "4 oz meat · 1/2 cup chickpeas · salad",
              "4.5 oz meat · 1/2 cup chickpeas · salad",
              "5 oz meat · 2/3 cup chickpeas · salad",
              "5 oz meat · 2/3 cup chickpeas · salad",
              "6 oz meat · 3/4 cup chickpeas · salad",
              "7 oz meat · 1 cup chickpeas · salad",
              "8 oz meat · 1 cup chickpeas · salad"],
 "dica": "Chickpeas add fiber and plant protein to the protein of the meat, which makes the plate very filling with few calories. Grilling the lean steak with no oil and serving it with a fresh salad is a light dinner, full of flavor, that holds hunger back for hours.",
},
{
 "nome": "Creamy Broccoli Soup with Chicken",
 "hook": "Green, velvety and full of flavor — a creamy broccoli soup that gains body from the chicken and becomes a complete dinner.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 330,
 "ings": ["1 bunch of broccoli", "1 chicken breast fillet (about 5 oz)", "1 small potato (it brings creaminess)",
          "1 onion, chopped", "1 clove of garlic, chopped", "1 tsp olive oil",
          "salt, pepper and nutmeg to taste", "4 cups of water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes, stirring.",
   "Add the potato in cubes, the whole chicken fillet and the water. Cook for 15 minutes.",
   "Take the chicken out, let it cool a little and shred it. Set it aside. Add the broccoli (only the florets) to the pot and cook for another 5 minutes, until it is tender but still green.",
   "Blend the soup with a hand blender (stick blender) or in a regular blender until it is a smooth cream. Be careful with the hot liquid.",
   "Put the cream back in the pot, add the shredded chicken, season with salt, pepper and a touch of nutmeg and warm it for 3 minutes. Serve."],
 "porcoes8": ["1 ladle · a little chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken · 1 slice bread",
              "2 ladles · extra chicken · 1 slice bread",
              "3 ladles · chicken · 1 slice bread",
              "3 ladles · extra chicken · 2 slices bread",
              "3 large ladles · double chicken · 2 slices bread"],
 "dica": "Broccoli is one of the most nourishing and lowest calorie vegetables, and blended it turns into a velvety cream with no need for cream. A small piece of potato brings the creaminess, and the shredded chicken completes the soup with protein, keeping the dinner light and filling.",
},
{
 "nome": "Turkey Wrap with Salad",
 "hook": "Slices of turkey breast, fresh leaves and a creamy touch, rolled in a soft flatbread — a light dinner to eat with your hands.",
 "tempo": "10 min", "rende": "1 serving", "kcal_base": 360,
 "ings": ["1 wholegrain tortilla", "4 slices of turkey breast (lean deli meat)", "1 tbsp cottage cheese (or light cream cheese)",
          "lettuce leaves", "1/2 tomato in slices", "grated carrot", "cucumber in strips",
          "salt, pepper and mustard to taste"],
 "passos": [
   "Warm the tortilla for 20 seconds in a pan, just so it goes soft and easy to roll.",
   "Spread the cottage cheese (or light cream cheese) all over the tortilla, like butter.",
   "Put the lettuce leaves, the turkey slices, the tomato, the grated carrot and the cucumber in the center.",
   "Season with a little salt, pepper and mustard.",
   "Fold the sides inward and roll it tight, from bottom to top. Cut it in half diagonally and serve."],
 "porcoes8": ["3 slices turkey · 1/2 tortilla · salad",
              "4 slices turkey · 1 tortilla · salad",
              "4 slices turkey · 1 tortilla · salad",
              "5 slices turkey · 1 tortilla · salad",
              "5 slices turkey · 1 tortilla · salad",
              "6 slices turkey · 1 large tortilla · salad",
              "6 slices turkey · 2 tortillas · salad",
              "8 slices turkey · 2 tortillas · salad"],
 "dica": "Turkey breast is a lean and practical meat, full of protein. Swapping regular cream cheese for cottage or a light version and filling the wrap with leaves and vegetables gives you a light, quick and filling dinner, perfect for days when you do not feel like cooking.",
},
{
 "nome": "Chicken Stew with Vegetables",
 "hook": "Pieces of tender chicken in a thick, seasoned broth, with vegetables that melt in your mouth — pot food that gives you a hug.",
 "tempo": "40 min", "rende": "3 servings", "kcal_base": 390,
 "ings": ["2 chicken breast fillets in cubes (about 10 oz)", "1 potato in cubes", "1 carrot in rounds",
          "1 zucchini in cubes", "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 tsp olive oil", "salt, pepper, turmeric and fresh herbs to taste"],
 "passos": [
   "Season the chicken cubes with salt, pepper and a little turmeric.",
   "In a pot, heat the olive oil and brown the chicken cubes for 5 minutes, stirring. Add the onion and the garlic and fry for 2 minutes.",
   "Add the tomato and stir for 2 minutes, until it starts to break down.",
   "Add the potato and the carrot and cover with water (enough to cover everything). Season with salt and cook for 15 minutes.",
   "Add the zucchini and cook for another 8 minutes, until everything is tender and the broth has body. Sprinkle fresh herbs and serve on its own or with a little rice."],
 "porcoes8": ["1/2 serving · no rice",
              "1 serving · no rice",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "The stew cooks everything in the same pot with little fat, and the chicken's own broth seasons the vegetables. It is a hearty plate that fills you up with few calories, great for dinner because it is warm, comforting and light at the same time.",
},
{
 "nome": "Tuna Burger with Salad",
 "hook": "Made from canned tuna, this burger is cheap, full of protein and ready in an instant — a light and practical dinner.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["2 cans of tuna in water, drained", "1 egg", "3 tbsp oats", "1/2 onion, finely chopped",
          "chopped parsley", "1 tsp olive oil", "salt, pepper and juice of 1/2 lemon to taste",
          "green leaves, tomato and cucumber for the salad"],
 "passos": [
   "Drain the tuna well, pressing it to get the liquid out. In a bowl, mix the tuna, the egg, the oats, the onion, the parsley, salt, pepper and the lemon juice.",
   "Mash everything with a fork until it holds together. If it is too soft, add a little more oats.",
   "Shape two discs with your hands, flattening them well.",
   "Heat a nonstick pan with the olive oil over medium heat. Put the burgers in and leave them 4 minutes on each side, without moving them, until they are golden and firm. Turn them carefully.",
   "Serve with a generous salad of leaves, tomato and cucumber on the side."],
 "porcoes8": ["1 burger · salad",
              "1 burger · salad",
              "1 burger · salad · 1/2 bun",
              "2 burgers · salad",
              "2 burgers · salad",
              "2 burgers · salad · 1 bun",
              "2 burgers · salad · 1 bun",
              "3 burgers · salad · 1 bun"],
 "dica": "Canned tuna is a cheap and practical source of protein, and bound with egg and oats (instead of a lot of bread) it becomes a lean and filling burger. Grilled without frying and served with plenty of salad, it is a light and cheap dinner that fills your belly.",
},
{
 "nome": "Pot Roast Beef with Vegetables",
 "hook": "A piece of beef that cooks slowly until it falls apart, with vegetables soaked in the broth — the Sunday dinner, in the right measure.",
 "tempo": "1 h 20 min", "rende": "3 servings", "kcal_base": 440,
 "ings": ["14 oz lean beef in one piece (shank, eye of round or bottom round)", "2 carrots in large pieces",
          "2 potatoes in large pieces", "1 onion in wedges", "2 cloves of garlic", "1 tomato, chopped",
          "1 bay leaf", "1 tsp olive oil", "salt, pepper and rosemary to taste"],
 "passos": [
   "Season the piece of beef with salt and pepper. In a deep pot, heat the olive oil and brown the beef on all sides, turning it, for about 6 minutes (this browning gives the broth a lot of flavor).",
   "Add the onion, the garlic and the tomato and fry for 2 minutes. Add the bay leaf and hot water until it covers half of the beef.",
   "Cover it and cook over low heat for 50 minutes, turning the beef halfway through. If the water dries up too much, add a little more hot water.",
   "Add the carrots and the potatoes and cook for another 25 minutes, until the beef is so tender it falls apart and the vegetables are done.",
   "Take out the bay leaf. Slice or shred the beef and serve with the vegetables and the broth on top."],
 "porcoes8": ["1/2 serving beef · vegetables",
              "1 serving beef · vegetables",
              "1 serving beef · vegetables",
              "1 serving · vegetables · 1 extra potato",
              "1 serving · vegetables · 1 extra potato",
              "1 large serving · vegetables",
              "large serving · vegetables · extra potato",
              "double serving · vegetables"],
 "dica": "Slow cooking makes lean and cheap cuts tender with no need for fat, and the broth that forms seasons the vegetables naturally. Served with the beef in the right measure and plenty of vegetables, it is a comforting weekend plate that fits your diet just right.",
},
{
 "nome": "Chicken Stuffed with Ricotta and Spinach",
 "hook": "The chicken fillet opens like a pocket and holds a creamy ricotta and spinach filling — surprising, juicy and light.",
 "tempo": "35 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 thick chicken breast fillets (about 10 oz)", "4 tbsp ricotta", "1 large handful of spinach",
          "1 clove of garlic, chopped", "1 tsp olive oil", "juice of 1/2 lemon",
          "salt, pepper and nutmeg to taste", "toothpicks"],
 "passos": [
   "In a pan, heat a few drops of olive oil and sauté the spinach with the garlic for 1 minute, just until it wilts (the leaves go soft). Let it cool and chop it.",
   "In a bowl, mix the ricotta, the chopped spinach, salt, pepper and a touch of nutmeg, making a creamy filling.",
   "With a knife, make a cut in the side of each fillet, opening a pocket (without cutting all the way through). Season the chicken with salt, pepper and the lemon juice.",
   "Fill the pockets with the ricotta mixture and close the opening with one or two toothpicks.",
   "Heat the rest of the olive oil in a pan over medium heat and brown the fillets for 5 to 6 minutes on each side, until they are golden and cooked inside. Take the toothpicks out before serving, with a salad on the side."],
 "porcoes8": ["1 small fillet · salad",
              "1 fillet · salad",
              "1 fillet · salad · 2 tbsp rice",
              "1 large fillet · salad · 2 tbsp rice",
              "1 large fillet · salad · 3 tbsp rice",
              "1 large fillet · salad · 4 tbsp rice",
              "2 fillets · salad · 4 tbsp rice",
              "2 fillets · salad · 5 tbsp rice"],
 "dica": "Ricotta is a lean and creamy cheese, full of protein and low in fat, ideal for stuffing without weighing things down. Spinach brings fiber and nutrients for almost no calories. The result is a juicy and sophisticated chicken, light enough for dinner.",
},
{
 "nome": "Fish Soup with Vegetables",
 "hook": "A fragrant broth with pieces of white fish and vegetables — light, full of the taste of the sea and comforting on a cold night.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 340,
 "ings": ["14 oz white fish fillet in pieces (whiting or hake)", "1 potato in cubes", "1 carrot in cubes",
          "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper, coriander or parsley to taste", "5 cups of water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes. Add the tomato and stir for another 2 minutes, until it breaks down.",
   "Add the water, the potato and the carrot. Season with salt and pepper and cook for 15 minutes, until the vegetables are soft.",
   "Add the pieces of fish (fish cooks fast, so it goes in at the end) and cook for 6 to 8 minutes, just until the fish is white and tender, without falling apart too much.",
   "Add the lemon juice and check the salt.",
   "Sprinkle coriander or parsley and serve very hot."],
 "porcoes8": ["1 ladle · fish",
              "2 ladles · fish",
              "2 ladles · fish",
              "2 ladles · fish · 1 slice bread",
              "2 ladles · extra fish · 1 slice bread",
              "3 ladles · fish · 1 slice bread",
              "3 ladles · extra fish · 2 slices bread",
              "3 large ladles · double fish · 2 slices bread"],
 "dica": "White fish is extremely lean and cooks in minutes, keeping the soup light and full of protein. The broth with vegetables fills your stomach with very few calories, and the touch of lemon lifts the flavor without too much salt — a warm and light dinner.",
},
{
 "nome": "Turkey Escalopes in Mushroom Sauce",
 "hook": "Thin slices of turkey in a creamy mushroom sauce — a dinner that looks expensive, made with little fat in twenty minutes.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 thin turkey breast fillets (about 10 oz)", "1 cup of sliced mushrooms", "1 onion, chopped",
          "1 clove of garlic, chopped", "3 tbsp plain yogurt with no sugar", "1 tsp olive oil",
          "salt, pepper and parsley to taste", "rice or mash to serve"],
 "passos": [
   "Season the thin turkey fillets with salt and pepper.",
   "Heat a nonstick pan with half of the olive oil over medium-high heat and brown the fillets for 2 to 3 minutes on each side, until they are golden and cooked. Take them out and set them aside.",
   "In the same pan, with the rest of the olive oil, fry the onion and the garlic for 2 minutes. Add the mushrooms and cook for 4 minutes, until they wilt (go soft) and release their water.",
   "Turn the heat down, turn it off and add the yogurt, stirring — off the heat it does not curdle (turn into lumps). Adjust the salt and pepper.",
   "Put the fillets back in the pan to coat them in the sauce. Sprinkle parsley and serve with a little rice or mash."],
 "porcoes8": ["1 fillet · 2 tbsp rice",
              "1 fillet · 3 tbsp rice",
              "1 large fillet · 3 tbsp rice",
              "1 large fillet · 4 tbsp rice",
              "1 large fillet · 4 tbsp rice",
              "2 fillets · 4 tbsp rice",
              "2 fillets · 5 tbsp rice",
              "2 fillets · 6 tbsp rice"],
 "dica": "Turkey is a lean white meat rich in protein. The creamy sauce comes from yogurt, not from cream, cutting a lot of fat. The mushrooms bring an intense flavor and body to the sauce with very few calories — a sophisticated and light dinner.",
},
{
 "nome": "Baked Eggs in Tomato Sauce with Chicken",
 "hook": "Eggs cooked inside a seasoned tomato sauce, with little pieces of chicken — a warm and different dinner, straight from the pan to the table.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 370,
 "ings": ["4 eggs", "1 cooked and shredded chicken breast fillet (about 4 oz)", "3 ripe tomatoes, chopped (or tomato sauce)",
          "1 onion, chopped", "1 clove of garlic, chopped", "1/2 bell pepper, chopped", "1 tsp olive oil",
          "salt, pepper, paprika and fresh herbs to taste", "wholegrain bread to serve"],
 "passos": [
   "In an oven-safe pan (or a deep one), heat the olive oil and fry the onion, the garlic and the bell pepper for 3 minutes, stirring.",
   "Add the chopped tomatoes, the paprika, salt and pepper and cook for 8 minutes, until it turns into a rich sauce. Add the shredded chicken and mix.",
   "With a spoon, make small holes in the sauce. Crack an egg into each hole, without mixing, so the yolks stay whole.",
   "Cover the pan and cook over low heat for 6 to 8 minutes, until the whites set and the yolks are the way you like them. (Or bake at medium heat for 10 minutes.)",
   "Sprinkle fresh herbs and serve in the pan itself, with slices of wholegrain bread on the side."],
 "porcoes8": ["1 egg · chicken · sauce",
              "2 eggs · chicken · sauce",
              "2 eggs · chicken · 1 slice bread",
              "2 eggs · extra chicken · 1 slice bread",
              "2 eggs · extra chicken · 1 slice bread",
              "2 eggs · chicken · 2 slices bread",
              "3 eggs · extra chicken · 2 slices bread",
              "3 eggs · double chicken · 2 slices bread"],
 "dica": "Eggs are a complete and very filling protein, and cooked in tomato sauce they stay light, with no frying. The chicken adds even more protein and the sauce fills the plate with the volume of the tomatoes. It is a warm, cheap and comforting dinner that fills you up well.",
},
{
 "nome": "Shrimp and Vegetable Skewers",
 "hook": "Pink shrimp and colorful vegetables threaded together, grilled until golden — light, pretty and with a party feel.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 360,
 "ings": ["9 oz large cleaned shrimp", "1 bell pepper in squares", "1 onion in pieces",
          "1 zucchini in thick rounds", "cherry tomatoes", "2 cloves of garlic, chopped", "1 tsp olive oil",
          "juice of 1 lemon", "salt, pepper and paprika to taste", "skewer sticks"],
 "passos": [
   "Season the shrimp with salt, pepper, paprika, the garlic and the lemon juice. Let it take in the flavor for 10 minutes.",
   "Build the skewers alternating a shrimp, a square of bell pepper, a piece of onion, a round of zucchini and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or a griddle over medium-high heat. Put the skewers on and turn them every 2 minutes, for about 8 minutes in total, just until the shrimp turns pink and curls up. Do not overcook it, or it goes rubbery.",
   "Serve the skewers with a salad or a little rice."],
 "porcoes8": ["1 skewer · salad",
              "2 skewers · salad",
              "2 skewers · salad · 2 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 4 tbsp rice",
              "3 large skewers · salad · 4 tbsp rice"],
 "dica": "Shrimp is almost all protein, with very little fat and few calories. Threaded with colorful vegetables and grilled with no oil, it becomes a light, striking and tasty dinner that controls the portion naturally and works even for special occasions.",
},
{
 "nome": "Grilled Salmon with Asparagus",
 "hook": "Two stars on one plate: the juicy salmon and the crisp asparagus — a fancy, light dinner ready in fifteen minutes.",
 "tempo": "18 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 salmon fillet (about 5 oz)", "1 bunch of asparagus", "1 clove of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and lemon zest to taste"],
 "passos": [
   "Wash the asparagus and snap off the hard bottom end of each one (it breaks naturally at the right point when you bend it).",
   "Season the salmon with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with half of the olive oil over medium heat. Put the salmon in skin side down and leave it 4 minutes, turn it and leave it another 3 minutes, until it turns lighter in color and flakes apart.",
   "At the same time, in another pan (or in the same one, after taking the salmon out), sauté the asparagus with the rest of the olive oil over high heat for 4 minutes, stirring, until it is green and tender but still crisp.",
   "Build the plate with the salmon and the asparagus. Finish with lemon zest on top."],
 "porcoes8": ["4 oz salmon · asparagus",
              "5 oz salmon · asparagus",
              "5 oz salmon · asparagus · 1 small potato",
              "6 oz salmon · asparagus · 1 potato",
              "6 oz salmon · asparagus · 1 potato",
              "7 oz salmon · asparagus · 1 potato",
              "8 oz salmon · asparagus · 1 large potato",
              "9 oz salmon · asparagus · 2 small potatoes"],
 "dica": "Salmon brings protein and omega-3, the good fat that fills you up and protects your heart. Asparagus is light, full of fiber and helps reduce bloating, with very few calories. Grilled together with little oil, they make an elegant, light and nourishing dinner.",
},
{
 "nome": "Ground Beef Sautéed with Zucchini",
 "hook": "A quick sauté of beef with zucchini and an egg on top — made in the pan in minutes, it fills you up with no need for rice.",
 "tempo": "20 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["9 oz lean ground beef", "2 zucchini in small cubes", "1 tomato, chopped", "1 onion, chopped",
          "1 clove of garlic, chopped", "2 eggs", "1 tsp olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Heat the olive oil in a pan over medium heat and fry the onion and the garlic for 2 minutes, stirring.",
   "Add the ground beef and stir, breaking up the pieces with the spoon, until it loses all its pink color.",
   "Add the tomato and the zucchini cubes, season with salt and pepper and cook for 8 minutes, stirring now and then, until the zucchini is soft and releases its own juices.",
   "Meanwhile, fry or boil the eggs separately (fry them with very little oil or boil them for 6 minutes for a soft yolk).",
   "Serve the sauté hot with an egg on top of each portion and fresh herbs sprinkled over."],
 "porcoes8": ["1/2 serving · 1 egg",
              "1 serving · 1 egg",
              "1 serving · 1 egg · 2 tbsp rice",
              "1 serving · 1 egg · 3 tbsp rice",
              "1 serving · 2 eggs · 3 tbsp rice",
              "1 large serving · 2 eggs · 3 tbsp rice",
              "large serving · 2 eggs · 4 tbsp rice",
              "double serving · 2 eggs · 4 tbsp rice"],
 "dica": "Cubed zucchini mixes into the meat and gives volume to the plate with very few calories, helping you eat less meat without missing it. The egg on top adds protein and creaminess. With no rice or very little, it is a light, fast and very filling dinner.",
},
{
 "nome": "Pizzaiolo Chicken with Salad",
 "hook": "The taste of pizza with no crust: the grilled chicken gets tomato sauce, melted cheese and oregano — it kills the craving and does not weigh you down.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["2 chicken breast fillets (about 10 oz)", "1/2 cup homemade tomato sauce", "3 tbsp grated low-fat mozzarella",
          "tomato slices", "1 tsp olive oil", "oregano, salt and pepper to taste",
          "green leaves for the salad"],
 "passos": [
   "Season the chicken fillets with salt and pepper.",
   "Heat a nonstick pan with the olive oil over medium heat and grill the fillets for 4 to 5 minutes on each side, until they are golden and white inside.",
   "Turn the heat down. Cover each fillet with the tomato sauce, one or two tomato slices and the grated mozzarella. Sprinkle oregano.",
   "Cover the pan and leave it 3 to 4 minutes, just until the cheese melts (that is the trick for a browned top with no oven).",
   "Serve with a fresh green salad on the side."],
 "porcoes8": ["3.5 oz chicken · a little cheese · salad",
              "4.5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · salad",
              "5 oz chicken · cheese · 2 tbsp rice",
              "5 oz chicken · cheese · 3 tbsp rice",
              "6 oz chicken · cheese · 3 tbsp rice",
              "7 oz chicken · cheese · 4 tbsp rice",
              "8 oz chicken · extra cheese · 4 tbsp rice"],
 "dica": "You kill the craving for pizza with the flavor of tomato sauce, cheese and oregano, but without the crust and the fat. The grilled chicken gives lean protein and fullness, and a little melted cheese is enough for the pleasure of a cheesy top. Light and satisfying.",
},
{
 "nome": "Pan-Grilled Fish with Vegetables",
 "hook": "All in one pan: the fish browns on one side while the vegetables sauté on the other — a light, quick dinner with no mess.",
 "tempo": "20 min", "rende": "1 serving", "kcal_base": 380,
 "ings": ["1 white fish fillet (whiting, hake or tilapia, about 5 oz)", "1 zucchini in half-moons",
          "1/2 bell pepper in strips", "cherry tomatoes", "1 clove of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Season the fish with salt, pepper, the garlic and the lemon juice.",
   "Heat a large pan with half of the olive oil over medium-high heat. On one side, put the fillet in and leave it 3 to 4 minutes on each side, turning it carefully, until it is golden and flakes apart.",
   "On the other side of the pan (or after taking the fish out), put the rest of the olive oil and sauté the zucchini, the bell pepper and the cherry tomatoes for 4 to 5 minutes, stirring, until they are tender but still firm.",
   "Season the vegetables with salt and pepper.",
   "Build the plate with the fish and the sautéed vegetables. Sprinkle parsley and finish with a little more lemon."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 1 small potato",
              "6 oz fish · vegetables · 1 potato",
              "6 oz fish · vegetables · 1 potato",
              "7 oz fish · vegetables · 1 potato",
              "8 oz fish · vegetables · 1 large potato",
              "9 oz fish · vegetables · 2 small potatoes"],
 "dica": "White fish is light and cooks in minutes, and made in the same pan as the vegetables it uses very little oil. The sautéed vegetables bring color, fiber and volume for almost no calories. It is one of the fastest, lightest and most practical dinners there is.",
},
{
 "nome": "Grilled Turkey Breast with Pumpkin Mash",
 "hook": "The lean turkey over a naturally sweet, orange pumpkin mash — a light dinner with a cozy feel.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 390,
 "ings": ["1 turkey breast fillet (about 5 oz)", "1 piece of pumpkin in cubes (about 10 oz)", "1 clove of garlic, chopped",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper, sage or rosemary to taste",
          "green leaves for the salad"],
 "passos": [
   "Cook the pumpkin in boiling water for 15 minutes, until it is very soft. Drain it very well and mash it with a fork, with a pinch of salt, until it turns into a smooth and creamy mash.",
   "Season the turkey with salt, pepper, the garlic and the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium heat and grill the fillet for 3 to 4 minutes on each side, until it is golden and white inside.",
   "If you like, finish the turkey with a little sage or rosemary in the pan in the last seconds, to perfume it.",
   "Build the plate with the pumpkin mash, the sliced turkey on top and a green salad on the side."],
 "porcoes8": ["4 oz turkey · 1/2 serving mash · salad",
              "5 oz turkey · 1 serving mash · salad",
              "5 oz turkey · 1 serving mash · salad",
              "6 oz turkey · 1 serving mash · salad",
              "6 oz turkey · 1 serving mash · salad",
              "7 oz turkey · 1 large serving mash · salad",
              "8 oz turkey · large serving mash · salad",
              "9 oz turkey · double serving mash · salad"],
 "dica": "Turkey breast is even leaner than chicken, full of protein. Pumpkin makes a creamy and sweet mash with very few calories, killing the craving for something sweet and filling the plate with fiber. A light, comforting and colorful dinner.",
},
{
 "nome": "Chicken Noodle Soup",
 "hook": "The usual chicken soup, boosted with plenty of chicken and vegetables — the dinner that hugs, heals and still fits your diet.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["1 chicken breast fillet (about 5 oz)", "1/2 cup small pasta (vermicelli or small rings)",
          "1 carrot in small cubes", "1 celery stalk, chopped (optional)", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste", "5 cups of water"],
 "passos": [
   "In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes, stirring.",
   "Add the whole chicken fillet, the carrot, the celery and the water. Season with salt and cook for 15 minutes, until the chicken is done.",
   "Take the chicken out, let it cool a little and shred it. Put the shredded chicken back in the pot.",
   "Add the small pasta and cook for another 8 to 10 minutes, until the pasta is soft (stir now and then so it does not stick to the bottom).",
   "Check the salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · chicken",
              "2 ladles · chicken",
              "2 ladles · chicken",
              "2 ladles · extra chicken",
              "2 ladles · extra chicken · extra pasta",
              "3 ladles · chicken",
              "3 ladles · extra chicken · extra pasta",
              "3 large ladles · double chicken"],
 "dica": "Chicken soup is light and comforting: the broth with vegetables fills your stomach with few calories and the chicken gives the protein that fills you up. With little pasta and lots of chicken and vegetables, it becomes a complete and warm dinner, ideal for cold nights or days with no appetite.",
},
{
 "nome": "Shrimp in Light Curry with Vegetables",
 "hook": "Shrimp bathed in a golden curry and light coconut milk sauce — fragrant, creamy and surprisingly light.",
 "tempo": "25 min", "rende": "2 servings", "kcal_base": 380,
 "ings": ["10 oz cleaned shrimp", "1 onion, chopped", "1 clove of garlic, chopped", "1 bell pepper in strips",
          "1 tsp curry powder", "1/2 cup light coconut milk", "1 tomato, chopped",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper and coriander to taste", "rice to serve"],
 "passos": [
   "Season the shrimp with salt, pepper and the lemon juice. Let it take in the flavor for 5 minutes.",
   "Heat the olive oil in a pan over medium heat and fry the onion, the garlic and the bell pepper for 3 minutes, stirring.",
   "Add the curry and stir for 30 seconds, so the spice releases its aroma. Add the tomato and cook for 3 minutes, until it breaks down.",
   "Add the light coconut milk and let it come to a gentle boil. Put the shrimp in and cook for 3 to 4 minutes, just until it turns pink. Do not overcook it, or it goes rubbery.",
   "Sprinkle coriander and serve over a small portion of rice."],
 "porcoes8": ["4 oz shrimp · 2 tbsp rice",
              "5 oz shrimp · 3 tbsp rice",
              "5 oz shrimp · 3 tbsp rice",
              "6 oz shrimp · 4 tbsp rice",
              "6 oz shrimp · 4 tbsp rice",
              "7 oz shrimp · 4 tbsp rice",
              "8 oz shrimp · 5 tbsp rice",
              "9 oz shrimp · 5 tbsp rice"],
 "dica": "Shrimp is almost pure protein and cooks fast. Light coconut milk gives creaminess to the sauce with far less fat than cream, and the curry perfumes it and gives the feeling of a special dish. With a little rice, it is a light dinner full of flavor.",
},
{
 "nome": "Beef Stew with Potato",
 "hook": "Cubes of beef that fall apart in a thick broth with potato — the stew that comforts on a cold night, in the right portion.",
 "tempo": "1 h", "rende": "3 servings", "kcal_base": 430,
 "ings": ["10 oz lean beef in cubes (shank or lean chuck)", "2 potatoes in large cubes", "1 carrot in rounds",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 tomato, chopped", "1 bay leaf",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste"],
 "passos": [
   "Season the beef cubes with salt and pepper. In a pot, heat the olive oil and brown the beef on all sides, stirring, for 6 minutes.",
   "Add the onion and the garlic and fry for 2 minutes. Add the tomato and the bay leaf and stir for 2 minutes.",
   "Cover with hot water, put the lid on and cook over low heat for 35 minutes, until the beef starts to go tender. If it dries up, add more hot water.",
   "Add the potato and the carrot and cook for another 20 minutes, until the beef falls apart and the potato is soft (the potato helps to thicken the broth).",
   "Take out the bay leaf, sprinkle fresh herbs and serve hot, on its own or with a little rice."],
 "porcoes8": ["1/2 serving · no rice",
              "1 serving · no rice",
              "1 serving · 2 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 serving · 3 tbsp rice",
              "1 large serving · 4 tbsp rice",
              "large serving · 5 tbsp rice",
              "double serving · 5 tbsp rice"],
 "dica": "Slow cooking makes lean and cheap cuts tender, and the potato thickens the broth naturally, so you do not need flour or cream. It is a hearty plate that fills you up with controlled calories — the comfort of a stew without leaving your diet.",
},
{
 "nome": "Oven Omelette with Lean Ham and Vegetables",
 "hook": "A tall, fluffy omelette baked in the oven, filled with vegetables and lean ham — cut it into slices and it feeds the family.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 360,
 "ings": ["6 eggs", "4 slices of lean ham (turkey), chopped", "1/2 bell pepper, chopped", "1 tomato, chopped",
          "a handful of spinach", "2 tbsp grated low-fat cheese", "1 tsp olive oil",
          "chives, salt and pepper to taste"],
 "passos": [
   "Turn the oven to medium heat (350 °F). Brush a small baking dish with the olive oil.",
   "In a bowl, beat the eggs with salt and pepper for 30 seconds.",
   "Add to the eggs the chopped ham, the bell pepper, the tomato, the spinach and the chives, and mix.",
   "Pour the mixture into the dish and sprinkle the grated cheese on top.",
   "Bake for 20 to 25 minutes, until the omelette puffs up, sets in the center and turns lightly golden on top. Cut it into slices and serve hot or warm, with a salad."],
 "porcoes8": ["1 slice · salad",
              "1 large slice · salad",
              "1 large slice · salad · 1 slice bread",
              "2 slices · salad · 1 slice bread",
              "2 slices · salad · 1 slice bread",
              "2 large slices · salad · 1 slice bread",
              "2 large slices · salad · 2 slices bread",
              "3 slices · salad · 2 slices bread"],
 "dica": "Eggs are a complete and very filling protein, and baked in the oven they need no frying. Lean turkey ham adds flavor and protein with little fat, and the vegetables bring volume and fiber. It goes a long way, keeps well and is a light and practical dinner.",
},
{
 "nome": "Baked Tilapia with Tomato and Onion",
 "hook": "White fish fillets baked under a bed of tomato and onion that turn into a natural sauce — light, juicy and effortless.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 370,
 "ings": ["2 tilapia fillets (or other white fish, about 10 oz)", "2 tomatoes in slices", "1 onion in slices",
          "1 clove of garlic, sliced", "1 tsp olive oil", "juice of 1 lemon",
          "salt, pepper, oregano and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). In a baking dish, spread half of the tomato and onion slices on the bottom, making a bed.",
   "Season the fish fillets with salt, pepper, the garlic, the oregano and the lemon juice. Put them on the bed of tomato and onion.",
   "Cover the fillets with the rest of the tomato and the onion and drizzle with the olive oil.",
   "Bake for 20 to 25 minutes, until the fish flakes apart and the tomato and onion are soft, releasing a natural sauce.",
   "Sprinkle parsley and serve with the sauce on top, along with a salad or a little rice."],
 "porcoes8": ["4 oz fish · vegetables",
              "5 oz fish · vegetables",
              "5 oz fish · vegetables · 2 tbsp rice",
              "6 oz fish · vegetables · 3 tbsp rice",
              "6 oz fish · vegetables · 3 tbsp rice",
              "7 oz fish · vegetables · 3 tbsp rice",
              "8 oz fish · vegetables · 4 tbsp rice",
              "9 oz fish · vegetables · 4 tbsp rice"],
 "dica": "White fish is extremely lean and rich in protein, and baking it under tomato and onion creates a natural sauce with no fat, keeping the fillet juicy. It is a light, cheap dinner full of flavor that practically makes itself in the oven.",
},
{
 "nome": "Chicken Meatballs in Soup",
 "hook": "Soft chicken balls cooked in a light broth with vegetables — a fun and complete soup that fills you up and warms you.",
 "tempo": "35 min", "rende": "3 servings", "kcal_base": 350,
 "ings": ["10 oz ground chicken breast", "1 egg", "2 tbsp oats", "1 carrot in small cubes",
          "1 potato in small cubes", "1 zucchini in small cubes", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tsp olive oil", "salt, pepper and fresh herbs to taste", "5 cups of water"],
 "passos": [
   "In a bowl, mix the ground chicken, the egg, the oats, salt and pepper. Knead it with your hands and roll small balls the size of a walnut.",
   "In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes. Add the water, the carrot and the potato, season with salt and cook for 10 minutes.",
   "Carefully drop the raw meatballs into the boiling broth, one by one. Do not stir for 3 minutes, so they firm up.",
   "Add the zucchini and cook for another 10 minutes, until the meatballs are done inside and the vegetables are soft.",
   "Check the salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["3 meatballs · 1 ladle broth",
              "4 meatballs · 2 ladles",
              "4 meatballs · 2 ladles",
              "5 meatballs · 2 ladles · 1 slice bread",
              "5 meatballs · 2 ladles · 1 slice bread",
              "6 meatballs · 3 ladles · 1 slice bread",
              "7 meatballs · 3 ladles · 2 slices bread",
              "8 meatballs · 3 ladles · 2 slices bread"],
 "dica": "The chicken meatballs give the protein that fills you up, and cooked inside the soup they make the broth tastier. All that liquid and the vegetables fill your stomach with few calories. It is a complete, light and comforting dinner that pleases even people who do not like thin soups.",
},
{
 "nome": "Grilled Shrimp with Leaf Salad",
 "hook": "Shrimp browned in garlic over a fresh, crisp salad — a light, elegant dinner ready in fifteen minutes.",
 "tempo": "15 min", "rende": "1 serving", "kcal_base": 330,
 "ings": ["5 oz large cleaned shrimp", "mixed green leaves", "1/2 tomato in cubes", "1/2 cucumber in rounds",
          "red onion in thin slices", "2 cloves of garlic, chopped", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and parsley to taste"],
 "passos": [
   "Dry the shrimp well with paper towel and season it with salt, pepper and half of the lemon juice.",
   "Heat a nonstick pan with the olive oil over medium-high heat. Add the garlic and stir for 30 seconds, just until it smells good.",
   "Put the shrimp in and grill it for 2 to 3 minutes on each side, just until it turns pink and golden. Do not overcook it.",
   "In a large bowl or plate, build the salad with the green leaves, the tomato, the cucumber and the red onion. Dress it with the rest of the lemon, salt and pepper.",
   "Put the hot shrimp on top of the salad, sprinkle parsley and serve right away."],
 "porcoes8": ["4 oz shrimp · salad",
              "5 oz shrimp · salad",
              "5 oz shrimp · salad · 1 slice bread",
              "6 oz shrimp · salad · 1 slice bread",
              "6 oz shrimp · salad · 2 tbsp rice",
              "7 oz shrimp · salad · 3 tbsp rice",
              "8 oz shrimp · salad · 3 tbsp rice",
              "9 oz shrimp · salad · 4 tbsp rice"],
 "dica": "Shrimp is almost pure protein, with very few calories, so it fills the plate without weighing you down. Browned in garlic and served over a fresh, crisp salad, it is one of the lightest dinners possible — ideal for the evening, when your body burns less energy.",
},
{
 "nome": "Fish Stewed with Coconut Milk and Vegetables",
 "hook": "A creamy, fragrant fish stew with a touch of coconut milk — as light as the sea, as comforting as a hug.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 390,
 "ings": ["10 oz white fish fillet in large pieces", "1 bell pepper in strips", "1 tomato, chopped", "1 onion in strips",
          "2 cloves of garlic, chopped", "1/2 cup light coconut milk", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and coriander to taste"],
 "passos": [
   "Season the pieces of fish with salt, pepper, the garlic and the lemon juice. Let them take in the flavor for 5 minutes.",
   "In a wide pot, heat the olive oil and make a bed with the onion, the bell pepper and the tomato. Sauté for 3 minutes, stirring.",
   "Put the pieces of fish on top of the vegetables (do not stir much, so the fish does not fall apart).",
   "Pour the light coconut milk over it, cover the pot and cook over medium-low heat for 10 to 12 minutes, until the fish is white and tender and the broth has body.",
   "Sprinkle coriander and serve with a small portion of rice, to make the most of the broth."],
 "porcoes8": ["4 oz fish · 2 tbsp rice",
              "5 oz fish · 3 tbsp rice",
              "5 oz fish · 3 tbsp rice",
              "6 oz fish · 4 tbsp rice",
              "6 oz fish · 4 tbsp rice",
              "7 oz fish · 4 tbsp rice",
              "8 oz fish · 5 tbsp rice",
              "9 oz fish · 5 tbsp rice"],
 "dica": "White fish is lean and rich in protein, and light coconut milk gives creaminess to the broth with far less fat than cream. The vegetables release water and form a light, fragrant sauce. It is a comforting and light stew, perfect for dinner.",
},
{
 "nome": "Beef and Vegetable Skewers",
 "hook": "Juicy beef cubes alternated with colorful vegetables, grilled until golden — barbecue flavor in the right measure.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["9 oz lean beef in cubes (sirloin or round)", "1 bell pepper in squares", "1 onion in pieces",
          "1 zucchini in thick rounds", "cherry tomatoes", "1 clove of garlic, chopped", "1 tsp olive oil",
          "salt, pepper and paprika to taste", "skewer sticks"],
 "passos": [
   "Season the beef cubes with salt, pepper, paprika and the garlic. Let them take in the flavor for 10 minutes.",
   "Build the skewers alternating a cube of beef, a square of bell pepper, a piece of onion, a round of zucchini and a cherry tomato, until the stick is full.",
   "Brush the skewers with the olive oil.",
   "Heat a large pan or a griddle over medium-high heat. Put the skewers on and turn them every 3 minutes, for about 12 minutes in total, until the beef is golden outside and done the way you like.",
   "Serve the skewers with a salad or a little rice."],
 "porcoes8": ["1 skewer · salad",
              "2 skewers · salad",
              "2 skewers · salad · 2 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "2 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 3 tbsp rice",
              "3 skewers · salad · 4 tbsp rice",
              "3 large skewers · salad · 4 tbsp rice"],
 "dica": "Skewers kill the craving for barbecue in a light way: the lean beef gives protein and the colorful vegetables fill the stick with fiber and few calories. Threading them helps to control the portion naturally, and grilling with no oil keeps everything tasty and light.",
},
{
 "nome": "Warm Salad with Chicken, Egg and Potato",
 "hook": "Golden potatoes, grilled chicken and egg, all warm over fresh leaves — a salad that is a complete and cozy dinner.",
 "tempo": "30 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["1 chicken breast fillet (about 4.5 oz)", "1 small potato in cubes", "2 boiled eggs",
          "green leaves", "cherry tomatoes", "red onion in slices", "1 tsp olive oil",
          "juice of 1/2 lemon", "salt, pepper and mustard to taste"],
 "passos": [
   "Cook the potato cubes in boiling salted water for 12 minutes, until they are soft. Drain them. If you want them browned, sauté them for 3 minutes in a pan with a few drops of olive oil.",
   "Cook the eggs for 9 minutes, run them under cold water, peel them and cut them in half.",
   "Season the chicken with salt and pepper and grill it in a nonstick pan for 4 to 5 minutes on each side, until it is golden. Cut it into strips.",
   "In a bowl or on a plate, make a bed of green leaves and put the cherry tomatoes and the onion on it.",
   "Arrange on top the warm potato, the chicken strips and the eggs. Make a dressing by mixing the olive oil, the lemon juice, the mustard, salt and pepper, drizzle it and serve right away."],
 "porcoes8": ["3.5 oz chicken · 1/2 potato · 1 egg",
              "4.5 oz chicken · 1 small potato · 2 eggs",
              "4.5 oz chicken · 1 potato · 2 eggs",
              "5 oz chicken · 1 potato · 2 eggs",
              "5 oz chicken · 1 potato · 2 eggs",
              "6 oz chicken · 1 large potato · 2 eggs",
              "7 oz chicken · 1 large potato · 3 eggs",
              "8 oz chicken · 2 small potatoes · 3 eggs"],
 "dica": "It is a salad that fills you up like a hot meal: the chicken and the egg give double protein, the potato in the right measure brings energy and the leaves fill the plate with fiber. Served warm, it is comforting and light at the same time — ideal for dinner.",
},
]
