# -*- coding: utf-8 -*-
"""35 receitas de ALMOÇO (031-065). FRANCÊS.

Tradução literal de `receitas_almoco.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ A xícara virou PESO em 13 receitas desta categoria — a cozinha francesa pesa.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/031-065).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 360/440/500/560 · 540/610/680/750
"""

RECEITAS = [
{
 "nome": "Blanc de poulet grillé, riz complet et brocoli",
 "hook": "Le plat le plus simple du monde et l'un des meilleurs pour maigrir : des protéines maigres, un bon féculent et des légumes à volonté.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 470,
 "ings": ["1 filet de blanc de poulet (environ 150 g)", "4 c. à s. de riz complet cuit",
          "1 assiette de brocoli", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel et poivre au goût"],
 "passos": [
   "Assaisonne le poulet des deux côtés avec du sel, du poivre, l'ail et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Coupe le brocoli en petits bouquets. Porte de l'eau à ébullition dans une casserole, plonge le brocoli et laisse-le seulement 3 minutes, jusqu'à ce qu'il soit vert vif et tendre mais encore ferme. Égoutte.",
   "Fais chauffer une poêle antiadhésive à feu moyen-vif avec l'huile d'olive. Pose le poulet et laisse-le 4 à 5 minutes de chaque côté, sans y toucher, jusqu'à ce qu'il soit doré dehors et blanc dedans.",
   "Pour savoir s'il est cuit, entaille le filet au centre : la chair doit être toute blanche, sans partie rosée.",
   "Réchauffe le riz complet déjà cuit. Monte l'assiette avec le riz, le poulet tranché et le brocoli à côté.",
   "Si tu veux, arrose le brocoli d'un filet d'huile d'olive et d'un peu plus de citron."],
 "porcoes8": ["100 g de poulet · 3 c. à s. de riz · brocoli à volonté",
              "120 g de poulet · 4 c. à s. de riz · brocoli à volonté",
              "130 g de poulet · 5 c. à s. de riz · brocoli à volonté",
              "150 g de poulet · 5 c. à s. de riz · un filet d'huile",
              "150 g de poulet · 5 c. à s. de riz · brocoli à volonté",
              "170 g de poulet · 6 c. à s. de riz · brocoli à volonté",
              "200 g de poulet · 7 c. à s. de riz · un filet d'huile",
              "220 g de poulet · 8 c. à s. de riz · un filet d'huile"],
 "dica": "Le blanc de poulet est presque de la protéine pure, qui rassasie beaucoup et aide à préserver le muscle pendant que tu perds de la graisse. Le riz complet contient des fibres et libère l'énergie lentement, tu n'as donc pas cette faim qui arrive une heure plus tard. Le brocoli remplit l'assiette pour presque aucune calorie.",
},
{
 "nome": "Filet de tilapia et purée de patate douce",
 "hook": "Un poisson léger et une purée naturellement sucrée — un déjeuner qui a l'air d'un plat de restaurant et qui rentre dans le régime.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 440,
 "ings": ["1 filet de tilapia (environ 150 g)", "1 patate douce moyenne", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "persil et ciboulette ciselés", "sel, poivre et paprika au goût",
          "salade verte"],
 "passos": [
   "Épluche la patate douce et coupe-la en morceaux. Fais-la cuire 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elle soit bien tendre (une fourchette entre sans effort). Égoutte.",
   "Écrase la patate encore chaude à la fourchette, ajoute une pincée de sel et la moitié de l'huile d'olive, et mélange jusqu'à obtenir une purée lisse.",
   "Assaisonne le tilapia avec du sel, du poivre, du paprika et le jus de citron.",
   "Fais chauffer une poêle antiadhésive avec le reste d'huile d'olive à feu moyen. Pose le filet et laisse 3 à 4 minutes de chaque côté, en le retournant délicatement une seule fois, jusqu'à ce qu'il soit doré et se détache facilement de la poêle.",
   "Monte l'assiette avec la purée, le filet par-dessus et une portion de salade verte à côté. Termine par les herbes."],
 "porcoes8": ["120 g de poisson · ½ patate douce · salade",
              "150 g de poisson · 1 petite patate douce · salade",
              "150 g de poisson · 1 patate douce moyenne · salade",
              "170 g de poisson · 1 patate douce moyenne · un filet d'huile",
              "170 g de poisson · 1 patate douce moyenne · salade",
              "200 g de poisson · 1 grosse patate douce · salade",
              "220 g de poisson · 1 grosse patate douce · un filet d'huile",
              "250 g de poisson · 1 grosse patate douce · un filet d'huile"],
 "dica": "Le tilapia est un poisson maigre, plein de protéines et avec très peu de graisses. La patate douce rassasie pendant des heures et, même si c'est un féculent, elle libère son énergie très lentement — c'est pour ça qu'elle est la chouchoute de ceux qui veulent maigrir sans perdre leur entrain.",
},
{
 "nome": "Steak de thon grillé, légumes et pommes de terre",
 "hook": "Le thon frais devient un steak de la mer : ferme dehors, juteux dedans, et prêt en quelques minutes.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 450,
 "ings": ["1 steak de thon frais (environ 150 g)", "1 petite pomme de terre en rondelles", "110 g de haricots verts et carottes",
          "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et origan au goût"],
 "passos": [
   "Fais cuire les rondelles de pomme de terre 10 minutes dans de l'eau bouillante salée, jusqu'à ce qu'elles soient tendres sans se défaire. Égoutte.",
   "Coupe les haricots verts en morceaux et les carottes en rondelles. Fais-les cuire à la vapeur ou dans peu d'eau bouillante 5 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes.",
   "Assaisonne le steak de thon avec du sel, du poivre, l'ail, l'origan et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu vif. Pose le steak et laisse 2 à 3 minutes de chaque côté — le thon est excellent légèrement rosé au centre ; si tu le préfères bien cuit, laisse 1 minute de plus de chaque côté.",
   "Monte l'assiette avec les pommes de terre, les légumes et le steak de thon par-dessus. Arrose d'un peu plus de citron et sers."],
 "porcoes8": ["120 g de thon · ½ pomme de terre · légumes",
              "150 g de thon · 1 petite pomme de terre · légumes",
              "150 g de thon · 1 pomme de terre · légumes",
              "170 g de thon · 1 pomme de terre · un filet d'huile",
              "170 g de thon · 1 pomme de terre · légumes",
              "200 g de thon · 1 grosse pomme de terre · légumes",
              "220 g de thon · 1 grosse pomme de terre · un filet d'huile",
              "250 g de thon · 2 petites pommes de terre · un filet d'huile"],
 "dica": "Le thon frais est l'une des chairs les plus maigres de la mer : beaucoup de protéines, des oméga-3 (la bonne graisse) et très peu de mauvaises graisses. Grillé rapidement à feu vif, il reste juteux sans huile, et avec des légumes et un peu de pomme de terre, ça devient un déjeuner noble et léger.",
},
{
 "nome": "Wrap complet au poulet effiloché",
 "hook": "Un wrap pratique à emporter au travail, garni de poulet et de salade — il coupe la faim sans peser.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 420,
 "ings": ["1 tortilla complète (ou un pain plat complet)", "1 filet de poulet cuit et effiloché (environ 120 g)",
          "1 c. à s. de yaourt nature sans sucre", "feuilles de salade", "½ tomate en rondelles",
          "carotte râpée", "sel, poivre et un peu de moutarde au goût"],
 "passos": [
   "Fais cuire le blanc de poulet dans de l'eau salée environ 15 minutes, jusqu'à ce qu'il soit blanc à l'intérieur. Laisse tiédir et effiloche-le avec deux fourchettes, en tirant la chair en filaments.",
   "Dans un bol, mélange le poulet effiloché avec le yaourt, la moutarde, du sel et du poivre, jusqu'à obtenir une garniture crémeuse.",
   "Réchauffe la tortilla 20 secondes dans une poêle, juste pour l'assouplir et pouvoir la rouler.",
   "Étale les feuilles de salade au centre de la tortilla. Ajoute le poulet crémeux, la tomate et la carotte râpée par-dessus.",
   "Replie les deux côtés vers l'intérieur et roule bien serré, de bas en haut. Coupe en deux en diagonale et sers."],
 "porcoes8": ["100 g de poulet · ½ tortilla · salade",
              "120 g de poulet · 1 tortilla · salade",
              "130 g de poulet · 1 tortilla · salade",
              "150 g de poulet · 1 tortilla · 1 c. à s. bombée de yaourt",
              "150 g de poulet · 1 tortilla · salade",
              "170 g de poulet · 1 grande tortilla · salade",
              "200 g de poulet · 2 tortillas · salade",
              "220 g de poulet · 2 tortillas · salade"],
 "dica": "Remplacer la mayonnaise par du yaourt nature supprime une bonne partie des calories et ajoute en plus des protéines. Le poulet effiloché se répartit bien et donne l'impression d'une garniture généreuse avec peu de graisse, et la tortilla complète a plus de fibres que le pain blanc, ce qui tient la faim plus longtemps.",
},
{
 "nome": "Saumon rôti aux légumes",
 "hook": "Tout sur une seule plaque : le poisson le plus noble pour le cœur, doré avec des légumes colorés.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 490,
 "ings": ["1 pavé de saumon (environ 150 g)", "1 petite pomme de terre en rondelles", "1 courgette en rondelles",
          "½ poivron en lanières", "tomates cerises", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et romarin au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe la pomme de terre en fines rondelles — ainsi elle cuit dans le même temps que le poisson.",
   "Sur une plaque, étale la pomme de terre, la courgette, le poivron et les tomates cerises. Assaisonne avec du sel, du poivre, du romarin et la moitié de l'huile d'olive, et mélange.",
   "Enfourne 10 minutes, juste pour que la pomme de terre commence à s'attendrir.",
   "Sors la plaque, fais de la place au centre et pose le saumon. Assaisonne le poisson avec du sel, du poivre, le jus de citron et le reste d'huile d'olive.",
   "Remets au four 15 minutes, jusqu'à ce que le saumon devienne plus clair et se détache en lamelles quand tu le piques à la fourchette. Sers sur la plaque ou monté dans l'assiette."],
 "porcoes8": ["120 g de saumon · ½ pomme de terre · légumes",
              "150 g de saumon · 1 petite pomme de terre · légumes",
              "150 g de saumon · 1 pomme de terre · légumes",
              "170 g de saumon · 1 pomme de terre · un filet d'huile",
              "170 g de saumon · 1 pomme de terre · légumes",
              "200 g de saumon · 1 grosse pomme de terre · légumes",
              "220 g de saumon · 1 grosse pomme de terre · un filet d'huile",
              "250 g de saumon · 2 petites pommes de terre · un filet d'huile"],
 "dica": "Le saumon est riche en bonnes graisses (oméga-3), qui aident le cœur et rassasient beaucoup. Tout rôtir ensemble sur la même plaque n'utilise presque pas d'huile et donne aux légumes un goût concentré — un plat complet, beau et léger avec le minimum d'effort.",
},
{
 "nome": "Gratin de patate douce à la viande hachée maigre",
 "hook": "Tout le réconfort d'un gratin crémeux, mais avec une purée de patate douce et de la viande maigre — pure satisfaction, sans culpabilité.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 460,
 "ings": ["2 patates douces moyennes", "250 g de viande de bœuf hachée maigre", "1 oignon haché",
          "1 gousse d'ail hachée", "1 tomate hachée", "1 c. à c. d'huile d'olive",
          "sel, poivre, persil et ciboulette au goût", "1 c. à s. de fromage râpé allégé"],
 "passos": [
   "Épluche les patates douces, coupe-les en morceaux et fais-les cuire 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elles soient bien tendres. Égoutte et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse.",
   "Dans une poêle, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail à feu moyen, en remuant, 2 minutes, jusqu'à ce qu'ils deviennent translucides.",
   "Ajoute la viande hachée et remue en défaisant les morceaux à la cuillère, jusqu'à ce qu'il n'y ait plus de rose.",
   "Ajoute la tomate, du sel et du poivre et fais cuire encore 5 minutes, jusqu'à réduction. Retire du feu et ajoute les herbes.",
   "Dans un plat à gratin, étale la moitié de la purée au fond, la viande au milieu et le reste de la purée par-dessus. Parsème de fromage râpé.",
   "Enfourne à 200 °C pendant 15 minutes, jusqu'à ce que la surface soit légèrement dorée. Sers chaud."],
 "porcoes8": ["½ portion · salade verte",
              "1 portion · salade verte",
              "1 portion · salade verte",
              "1 portion · 1 c. à s. de fromage en plus",
              "1 portion + viande en plus · salade",
              "1 grande portion · salade",
              "1 grande portion + viande · salade",
              "double portion de viande · salade"],
 "dica": "La patate douce remplace la pomme de terre classique du gratin par une version plus riche en fibres, qui rassasie davantage. La viande maigre apporte largement les protéines sans l'excès de graisse d'une viande grasse. C'est le genre de plat réconfortant qui trompe l'envie de manger n'importe quoi.",
},
{
 "nome": "Salade complète au thon, pois chiches et œuf",
 "hook": "Sans cuisson : une vraie salade, qui remplit l'assiette et le ventre, montée en cinq minutes.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 400,
 "ings": ["1 boîte de thon au naturel, égoutté", "80 g de pois chiches cuits", "2 œufs durs",
          "salade verte variée", "½ tomate en dés", "½ concombre en rondelles", "oignon rouge en fines lamelles",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel et poivre au goût"],
 "passos": [
   "Fais cuire les œufs : mets-les dans une casserole avec de l'eau, porte à ébullition et compte 9 minutes. Passe-les sous l'eau froide, écale-les et coupe-les en deux.",
   "Égoutte bien le thon et les pois chiches.",
   "Dans une assiette ou un grand saladier, étale la salade verte. Répartis par-dessus la tomate, le concombre et l'oignon.",
   "Pose le thon au centre, les pois chiches autour et les œufs sur les côtés.",
   "Arrose d'huile d'olive et de jus de citron, assaisonne avec du sel et du poivre et sers."],
 "porcoes8": ["½ boîte de thon · 55 g de pois chiches · 1 œuf",
              "1 boîte de thon · 80 g de pois chiches · 2 œufs",
              "1 boîte de thon · 80 g de pois chiches · 2 œufs",
              "1 boîte de thon · 110 g de pois chiches · 2 œufs · avocat",
              "1 boîte de thon · 110 g de pois chiches · 2 œufs",
              "1½ boîte de thon · 125 g de pois chiches · 2 œufs",
              "1½ boîte de thon · 165 g de pois chiches · 3 œufs · avocat",
              "2 boîtes de thon · 165 g de pois chiches · 3 œufs · avocat"],
 "dica": "C'est une bombe de protéines (thon, œuf et pois chiches réunis) qui ne demande presque aucun travail. Les protéines et les fibres de la salade tiennent la faim à distance pendant des heures, et comme tout est frais et rien n'est cuit dans l'huile, l'assiette reste légère même bien garnie.",
},
{
 "nome": "Émincé de poulet à la crème légère et riz",
 "hook": "Le plat crémeux de toujours, mais en remplaçant la crème par du yaourt — même plaisir, moitié moins de calories.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["2 filets de blanc de poulet en dés (environ 300 g)", "1 oignon haché", "1 gousse d'ail hachée",
          "70 g de champignons émincés", "1 c. à s. de concentré de tomate",
          "4 c. à s. de yaourt nature sans sucre", "1 c. à c. d'huile d'olive",
          "sel, poivre et moutarde au goût", "riz blanc ou complet pour servir"],
 "passos": [
   "Assaisonne les dés de poulet avec du sel et du poivre.",
   "Fais chauffer l'huile d'olive dans une casserole à feu moyen-vif et fais dorer les dés de poulet de tous les côtés, en remuant de temps en temps, 5 minutes. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et l'ail 2 minutes, en remuant, jusqu'à ce qu'ils deviennent translucides. Ajoute les champignons et poursuis 3 minutes, jusqu'à ce qu'ils retombent.",
   "Remets le poulet dans la casserole, ajoute le concentré de tomate et la moutarde, mélange et laisse 3 minutes.",
   "Retire du feu. C'est seulement là que tu ajoutes le yaourt et que tu mélanges — hors du feu, il ne tranche pas (il ne fait pas de grumeaux). Rectifie le sel et sers sur le riz."],
 "porcoes8": ["½ portion · 3 c. à s. de riz",
              "1 portion · 4 c. à s. de riz",
              "1 portion · 5 c. à s. de riz",
              "1 portion · 5 c. à s. de riz · poulet en plus",
              "1 portion · 5 c. à s. de riz",
              "1 grande portion · 6 c. à s. de riz",
              "1 portion + poulet · 7 c. à s. de riz",
              "double portion · 8 c. à s. de riz"],
 "dica": "Le secret, c'est le yaourt nature à la place de la crème : tu gardes le crémeux et le goût, mais tu supprimes de la graisse et tu gagnes des protéines. Le poulet rassasie et les champignons ajoutent du volume et du goût pour très peu de calories.",
},
{
 "nome": "Blanc de dinde et semoule aux légumes",
 "hook": "La semoule est prête rien qu'avec de l'eau chaude — le déjeuner le plus rapide et le plus léger pour les journées chargées.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 430,
 "ings": ["1 filet de blanc de dinde (environ 150 g)", "90 g de semoule (couscous, les petites billes)",
          "120 ml d'eau chaude", "½ courgette en petits dés", "½ poivron en petits dés", "tomates cerises coupées",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre et menthe au goût"],
 "passos": [
   "Mets la semoule dans un bol, ajoute une pincée de sel et l'eau chaude (l'eau doit couvrir la semoule d'un doigt). Couvre avec une assiette et laisse 5 minutes.",
   "Égraine la semoule à la fourchette, en passant dans tout le bol, jusqu'à ce qu'elle soit bien détachée et ne colle plus.",
   "Assaisonne le blanc de dinde avec du sel et du poivre. Fais chauffer une poêle antiadhésive avec la moitié de l'huile d'olive et grille la dinde 3 à 4 minutes de chaque côté, jusqu'à ce qu'elle soit dorée et blanche à l'intérieur.",
   "Ajoute à la semoule les dés crus de courgette, de poivron et de tomate, le reste d'huile d'olive, le jus de citron et la menthe. Mélange.",
   "Sers la semoule avec le blanc de dinde tranché par-dessus."],
 "porcoes8": ["120 g de dinde · 60 g de semoule · légumes",
              "150 g de dinde · 90 g de semoule · légumes",
              "150 g de dinde · 90 g de semoule · légumes",
              "170 g de dinde · 115 g de semoule · un filet d'huile",
              "170 g de dinde · 115 g de semoule · légumes",
              "200 g de dinde · 130 g de semoule · légumes",
              "220 g de dinde · 175 g de semoule · un filet d'huile",
              "250 g de dinde · 175 g de semoule · un filet d'huile"],
 "dica": "Le blanc de dinde est encore plus maigre que le poulet et plein de protéines. La semoule cuit rien qu'avec de l'eau chaude, sans matière grasse, et mélangée à des légumes crus, elle devient un plat léger, coloré et rafraîchissant — parfait pour le déjeuner.",
},
{
 "nome": "Chili de bœuf aux haricots noirs",
 "hook": "Un ragoût épicé et consistant qui réchauffe — des haricots, de la viande maigre et beaucoup de goût dans une seule casserole.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 450,
 "ings": ["300 g de viande de bœuf hachée maigre", "170 g de haricots noirs cuits (ou en boîte, égouttés)",
          "1 oignon haché", "2 gousses d'ail hachées", "1 poivron haché", "2 tomates hachées (ou sauce tomate)",
          "1 c. à c. d'huile d'olive", "1 c. à c. de cumin en poudre", "sel, poivre et paprika au goût"],
 "passos": [
   "Fais chauffer l'huile d'olive dans une casserole à feu moyen. Fais revenir l'oignon, l'ail et le poivron 3 minutes, en remuant, jusqu'à ce qu'ils s'attendrissent.",
   "Ajoute la viande hachée et remue en défaisant les morceaux à la cuillère, jusqu'à ce qu'il n'y ait plus de rose.",
   "Ajoute le cumin, le paprika, du sel et du poivre et mélange bien, pour que les épices libèrent leur arôme.",
   "Ajoute les tomates hachées et les haricots noirs. Si c'est trop sec, verse 120 ml d'eau.",
   "Baisse le feu et laisse mijoter à feu doux 15 à 20 minutes, en remuant de temps en temps, jusqu'à obtenir un ragoût onctueux. Sers nature ou avec un peu de riz."],
 "porcoes8": ["½ portion · salade",
              "1 portion · salade",
              "1 portion · 2 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 portion · 3 c. à s. de riz",
              "1 grande portion · 4 c. à s. de riz",
              "1 grande portion · 5 c. à s. de riz",
              "double portion · 5 c. à s. de riz"],
 "dica": "Le haricot noir est champion en fibres et en protéines végétales, et avec la viande maigre il rend le plat très rassasiant pour peu de calories. C'est un plat mijoté qui fait plusieurs repas, se garde bien au réfrigérateur et calme l'envie de nourriture chaude et relevée sans sortir du droit chemin.",
},
{
 "nome": "Pâtes complètes à la sauce tomate et boulettes de dinde",
 "hook": "Oui, on peut manger des pâtes en maigrissant — en version complète, avec une sauce fraîche et des boulettes maigres.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 480,
 "ings": ["150 g de pâtes complètes (poids sec)", "250 g de dinde hachée (ou poulet haché)",
          "3 tomates mûres hachées (ou sauce tomate)", "1 oignon haché", "2 gousses d'ail hachées",
          "1 œuf", "2 c. à s. de flocons d'avoine", "1 c. à c. d'huile d'olive", "sel, poivre et basilic au goût"],
 "passos": [
   "Dans un bol, mélange la dinde hachée, l'œuf, l'avoine, la moitié de l'ail, du sel et du poivre. Malaxe à la main jusqu'à ce que ça se tienne et forme des boulettes de la taille d'une noix.",
   "Fais chauffer l'huile d'olive dans une grande casserole et fais dorer les boulettes de tous les côtés, en les tournant délicatement, environ 5 minutes. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et le reste de l'ail 2 minutes. Ajoute les tomates hachées, du sel et du poivre et fais cuire 10 minutes, en remuant, jusqu'à obtenir une sauce.",
   "Remets les boulettes dans la sauce et laisse cuire encore 8 minutes, jusqu'à ce qu'elles soient cuites à cœur.",
   "Pendant ce temps, fais cuire les pâtes dans de l'eau bouillante salée selon le temps indiqué sur le paquet, jusqu'à ce qu'elles soient cuites mais encore fermes. Égoutte.",
   "Mélange les pâtes à la sauce avec les boulettes, parsème de basilic et sers."],
 "porcoes8": ["⅔ portion de pâtes · 3 boulettes",
              "1 portion · 4 boulettes",
              "1 portion · 4 boulettes",
              "1 portion · 5 boulettes",
              "1 portion · 5 boulettes",
              "1 grande portion · 6 boulettes",
              "grande portion · 7 boulettes",
              "double portion · 8 boulettes"],
 "dica": "Les pâtes complètes contiennent plus de fibres et rassasient davantage que les pâtes classiques, et les boulettes de dinde apportent des protéines maigres à la place d'une viande grasse. Une sauce tomate faite sur le moment, sans sucre et sans produits industriels, rend le plat savoureux et bien plus léger.",
},
{
 "nome": "Omelette garnie aux légumes",
 "hook": "Un déjeuner léger pour les jours sans temps : moelleux, chaud et plein de protéines, prêt à la poêle en dix minutes.",
 "tempo": "12 min", "rende": "1 portion", "kcal_base": 360,
 "ings": ["3 œufs", "½ tomate en petits dés", "½ poivron en petits dés", "1 poignée d'épinards",
          "1 c. à s. de fromage en dés", "1 c. à c. d'huile d'olive",
          "ciboulette, sel et poivre au goût", "1 tranche de pain complet (facultatif)"],
 "passos": [
   "Casse les œufs dans un bol, assaisonne avec du sel et du poivre et bats à la fourchette 30 secondes, jusqu'à ce que tout soit bien mélangé.",
   "Fais chauffer l'huile d'olive dans une poêle antiadhésive à feu moyen-doux. Ajoute le poivron et les épinards et remue 1 minute, juste le temps que les épinards retombent.",
   "Étale les légumes dans la poêle et verse les œufs par-dessus. Laisse 1 minute sans y toucher, jusqu'à ce que le bord soit pris.",
   "Dépose la tomate et le fromage sur la moitié de l'omelette. Avec une spatule, replie l'autre moitié par-dessus, en formant un demi-cercle.",
   "Laisse encore 1 minute, juste le temps que le fromage s'attendrisse. Parsème de ciboulette et sers, avec la tranche de pain si tu veux."],
 "porcoes8": ["2 œufs · légumes · ½ pain",
              "3 œufs · légumes · 1 tranche de pain",
              "3 œufs · légumes · 1 tranche de pain",
              "3 œufs · 2 c. à s. de fromage · 1 tranche de pain",
              "3 œufs · légumes · 1 tranche de pain",
              "4 œufs · légumes · 1 tranche de pain",
              "4 œufs · 2 c. à s. de fromage · 2 tranches de pain",
              "5 œufs · légumes · 2 tranches de pain"],
 "dica": "Les œufs sont des protéines de très haute qualité et très rassasiantes — ceux qui mangent des œufs au déjeuner grignotent en général moins l'après-midi. Garnie de légumes, l'omelette gagne du volume, de la couleur et des fibres presque sans ajouter de calories, ce qui en fait un repas complet et rapide.",
},
{
 "nome": "Steak maigre avec riz, haricots et chou",
 "hook": "Le plat de tous les jours, comme on l'aime — mais dans la bonne mesure, avec une viande maigre et du chou sauté léger.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 500,
 "ings": ["1 steak de bœuf maigre (environ 130 g)", "4 c. à s. de riz cuit",
          "4 c. à s. de haricots cuits", "2 feuilles de chou coupées en fines lanières",
          "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive", "sel et poivre au goût"],
 "passos": [
   "Assaisonne le steak avec du sel et du poivre des deux côtés.",
   "Fais chauffer une poêle antiadhésive à feu vif avec quelques gouttes d'huile d'olive. Pose le steak et laisse 2 à 3 minutes de chaque côté, sans y toucher, jusqu'à ce qu'il soit doré dehors et à ton goût dedans.",
   "Coupe le chou en très fines lanières. Dans une poêle, fais chauffer le reste d'huile d'olive et fais revenir l'ail 30 secondes, juste le temps qu'il embaume.",
   "Ajoute le chou et remue à feu vif 1 à 2 minutes, juste le temps qu'il retombe un peu et reste vert. Assaisonne avec du sel.",
   "Réchauffe le riz et les haricots. Monte l'assiette avec le riz, les haricots, le steak et le chou à côté."],
 "porcoes8": ["100 g de viande · 3 c. à s. de riz · 3 c. à s. de haricots",
              "130 g de viande · 4 c. à s. de riz · 4 c. à s. de haricots",
              "130 g de viande · 5 c. à s. de riz · 4 c. à s. de haricots",
              "150 g de viande · 5 c. à s. de riz · 5 c. à s. de haricots",
              "150 g de viande · 5 c. à s. de riz · 5 c. à s. de haricots",
              "170 g de viande · 6 c. à s. de riz · 5 c. à s. de haricots",
              "200 g de viande · 7 c. à s. de riz · 6 c. à s. de haricots",
              "220 g de viande · 8 c. à s. de riz · 6 c. à s. de haricots"],
 "dica": "Tu peux manger le plat traditionnel riz, haricots et viande sans sortir du régime : la clé, c'est de choisir un morceau maigre, de mesurer le riz et les haricots et de ne pas lésiner sur le chou, qui remplit l'assiette de fibres pour presque aucune calorie. Les haricots apportent en plus des fibres et des protéines qui tiennent la faim.",
},
{
 "nome": "Steak aux oignons dorés, purée et salade",
 "hook": "Le steak aux oignons dorés est un pur réconfort — sur une purée légère et à côté d'une salade fraîche, il rentre parfaitement dans le régime.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 500,
 "ings": ["1 steak de bœuf maigre (environ 130 g)", "2 pommes de terre moyennes", "1 oignon émincé",
          "1 c. à c. d'huile d'olive", "sel et poivre au goût", "salade verte et tomate pour la salade",
          "le jus de ½ citron"],
 "passos": [
   "Épluche et fais cuire les pommes de terre 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elles soient bien tendres. Égoutte et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse. Pour plus de crémeux, ajoute un peu d'eau de cuisson.",
   "Assaisonne le steak avec du sel et du poivre des deux côtés.",
   "Fais chauffer une poêle antiadhésive à feu vif avec quelques gouttes d'huile d'olive. Pose le steak et laisse 2 à 3 minutes de chaque côté, sans y toucher, jusqu'à ce qu'il soit doré dehors et à ton goût dedans. Retire et réserve.",
   "Dans la même poêle, mets les lamelles d'oignon et le reste d'huile d'olive. Remue à feu moyen 5 minutes, jusqu'à ce que l'oignon soit tendre et doré (bien sucré).",
   "Recouvre le steak d'oignons dorés. Monte l'assiette avec la purée, le steak aux oignons et une salade verte assaisonnée au citron."],
 "porcoes8": ["100 g de viande · ½ portion de purée · salade",
              "130 g de viande · 1 portion de purée · salade",
              "130 g de viande · 1 portion de purée · salade",
              "150 g de viande · 1 portion de purée · salade",
              "150 g de viande · 1 portion de purée · salade",
              "170 g de viande · 1 grande portion de purée · salade",
              "200 g de viande · grande portion de purée · salade",
              "220 g de viande · double portion de purée · salade"],
 "dica": "En choisissant un morceau maigre et en le grillant sans huile, le steak devient presque de la protéine pure. L'oignon doré donne beaucoup de goût pour très peu de calories et rend les sauces grasses inutiles. Avec la purée dans la bonne mesure et beaucoup de salade, le plat rassasie sans peser.",
},
{
 "nome": "Crevettes sautées aux légumes et au riz",
 "hook": "Les crevettes sont prêtes en un clin d'œil et légères comme peu d'autres — un déjeuner rapide qui a l'air raffiné.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 430,
 "ings": ["150 g de crevettes décortiquées", "4 c. à s. de riz complet cuit", "½ courgette en demi-lunes",
          "½ poivron en lanières", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et persil au goût"],
 "passos": [
   "Assaisonne les crevettes avec du sel, du poivre, l'ail et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Fais chauffer une grande poêle avec la moitié de l'huile d'olive à feu vif. Ajoute la courgette et le poivron et remue 3 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes. Retire et réserve.",
   "Dans la même poêle, mets le reste d'huile d'olive et les crevettes. Fais-les sauter (remue à feu vif) 2 à 3 minutes, juste le temps qu'elles rosissent et s'enroulent. Attention à ne pas trop les cuire, sinon elles deviennent caoutchouteuses.",
   "Remets les légumes dans la poêle, ajoute le riz complet déjà cuit et mélange 1 minute, juste pour tout réchauffer.",
   "Parsème de persil et sers tout de suite."],
 "porcoes8": ["120 g de crevettes · 3 c. à s. de riz · légumes",
              "150 g de crevettes · 4 c. à s. de riz · légumes",
              "150 g de crevettes · 5 c. à s. de riz · légumes",
              "170 g de crevettes · 5 c. à s. de riz · un filet d'huile",
              "170 g de crevettes · 5 c. à s. de riz · légumes",
              "200 g de crevettes · 6 c. à s. de riz · légumes",
              "220 g de crevettes · 7 c. à s. de riz · un filet d'huile",
              "250 g de crevettes · 8 c. à s. de riz · un filet d'huile"],
 "dica": "La crevette est presque entièrement de la protéine, avec très peu de graisses et de calories, tu peux donc te servir généreusement sans que ça pèse. Sautée rapidement à feu vif avec des légumes, elle garde sa texture ferme et son goût, dans un plat léger prêt en quelques minutes.",
},
{
 "nome": "Poulet sauté léger aux poivrons et riz complet",
 "hook": "Le classique chinois à la maison, en version maigre : des dés de poulet et des légumes croquants dans une sauce légère et brillante.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 460,
 "ings": ["2 filets de blanc de poulet en dés (environ 300 g)", "1 poivron en dés", "1 oignon en dés",
          "1 branche de céleri en morceaux (facultatif)", "1 gousse d'ail hachée", "1 c. à s. de sauce soja allégée",
          "1 c. à c. de fécule de maïs", "1 c. à c. d'huile d'olive", "riz complet pour servir"],
 "passos": [
   "Assaisonne les dés de poulet avec un peu de sauce soja et l'ail. Laisse prendre le goût 5 minutes.",
   "Délaye la fécule de maïs dans 120 ml d'eau avec le reste de sauce soja. Mélange bien et réserve — c'est ce qui va lier la sauce.",
   "Fais chauffer une grande poêle avec la moitié de l'huile d'olive à feu vif. Fais dorer les dés de poulet 5 minutes, en remuant, jusqu'à ce qu'ils soient blancs à l'intérieur. Retire et réserve.",
   "Dans la même poêle, mets le reste d'huile d'olive et ajoute le poivron, l'oignon et le céleri. Remue à feu vif 3 minutes, jusqu'à ce qu'ils soient tendres mais encore croquants.",
   "Remets le poulet, mélange la préparation à la fécule et verse-la dans la poêle. Remue 1 à 2 minutes, jusqu'à ce que la sauce épaississe et nappe le tout d'un voile brillant. Sers sur le riz complet."],
 "porcoes8": ["½ portion · 3 c. à s. de riz",
              "1 portion · 4 c. à s. de riz",
              "1 portion · 5 c. à s. de riz",
              "1 portion · 5 c. à s. de riz · poulet en plus",
              "1 portion · 5 c. à s. de riz",
              "1 grande portion · 6 c. à s. de riz",
              "1 portion + poulet · 7 c. à s. de riz",
              "double portion · 8 c. à s. de riz"],
 "dica": "En le faisant à la maison, tu contrôles l'huile et le sucre dont les restaurants abusent. Le poulet apporte des protéines maigres, les légumes restent croquants pour peu de calories, et un simple soupçon de fécule donne cette belle sauce sans alourdir le plat.",
},
{
 "nome": "Bol mexicain au bœuf, haricots noirs et maïs",
 "hook": "Toutes les couleurs et les saveurs du Mexique dans un bol — copieux, relevé et étonnamment léger.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 490,
 "ings": ["250 g de viande de bœuf hachée maigre", "170 g de haricots noirs cuits", "80 g de maïs",
          "4 c. à s. de riz cuit", "1 tomate en dés", "½ avocat en tranches",
          "salade verte", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "cumin, sel, poivre et coriandre au goût", "le jus de ½ citron"],
 "passos": [
   "Fais chauffer l'huile d'olive dans une poêle et fais revenir l'ail 30 secondes. Ajoute la viande hachée et remue en défaisant les morceaux, jusqu'à ce qu'il n'y ait plus de rose.",
   "Assaisonne la viande avec du cumin, du sel et du poivre et fais cuire encore 3 minutes. Ajoute les haricots noirs et le maïs et réchauffe 2 minutes.",
   "Dans un bol, fais un lit de salade verte et mets le riz d'un côté.",
   "Répartis par-dessus la viande avec les haricots et le maïs, la tomate et les tranches d'avocat.",
   "Arrose de jus de citron, parsème de coriandre et sers."],
 "porcoes8": ["½ portion · 3 c. à s. de riz · ¼ avocat",
              "1 portion · 4 c. à s. de riz · ¼ avocat",
              "1 portion · 4 c. à s. de riz · ½ avocat",
              "1 portion · 5 c. à s. de riz · ½ avocat",
              "1 portion · 5 c. à s. de riz · ½ avocat",
              "1 grande portion · 6 c. à s. de riz · ½ avocat",
              "grande portion · 7 c. à s. de riz · ½ avocat",
              "double portion · 8 c. à s. de riz · avocat"],
 "dica": "C'est un plat complet dans un seul bol : les protéines de la viande, les fibres des haricots et du maïs, et la bonne graisse de l'avocat, qui apporte du crémeux et de la satiété. Bien relevé, il satisfait l'envie de nourriture de bistrot sans l'excès de graisse.",
},
{
 "nome": "Salade de poulet grillé à la mangue",
 "hook": "Sucrée, salée et rafraîchissante : le poulet grillé encore chaud rencontre la mangue sucrée dans une salade qui n'a rien d'un régime.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 400,
 "ings": ["1 filet de blanc de poulet (environ 130 g)", "salade verte variée", "½ mangue en dés",
          "½ concombre en rondelles", "oignon rouge en fines lamelles", "1 c. à c. d'huile d'olive",
          "le jus de ½ citron", "sel, poivre et menthe au goût"],
 "passos": [
   "Assaisonne le poulet avec du sel et du poivre. Fais chauffer une poêle antiadhésive à feu moyen-vif et grille le filet 4 à 5 minutes de chaque côté, jusqu'à ce qu'il soit doré et blanc à l'intérieur. Laisse tiédir et coupe en lanières.",
   "Épluche la mangue et coupe la chair en dés. Coupe le concombre en rondelles et l'oignon en lamelles très fines.",
   "Dans un grand saladier ou une assiette creuse, étale la salade verte.",
   "Répartis par-dessus les dés de mangue, le concombre, l'oignon et les lanières de poulet.",
   "Prépare la sauce en mélangeant l'huile d'olive, le jus de citron, du sel et du poivre. Arrose la salade, parsème de menthe et sers."],
 "porcoes8": ["100 g de poulet · ¼ mangue · salade",
              "130 g de poulet · ½ mangue · salade",
              "130 g de poulet · ½ mangue · salade",
              "150 g de poulet · ½ mangue · un filet d'huile",
              "150 g de poulet · ½ mangue · salade",
              "170 g de poulet · ½ mangue · 1 c. à s. de noix",
              "200 g de poulet · 1 mangue · noix",
              "220 g de poulet · 1 mangue · noix"],
 "dica": "La mangue joue le rôle d'un sucré naturel, sans sucre ajouté, et satisfait l'envie de douceur à l'intérieur d'un repas salé. Le poulet grillé apporte les protéines qui rassasient, et le volume de feuilles et de légumes remplit l'assiette pour très peu de calories. Une salade qui est un repas complet.",
},
{
 "nome": "Filet de poulet au curry léger et riz",
 "hook": "Une sauce dorée et parfumée qui transforme le poulet de tous les jours — crémeuse sans crème, avec du lait de coco allégé.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["2 filets de blanc de poulet en dés (environ 300 g)", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. de curry en poudre", "120 ml de lait de coco allégé (ou de lait ordinaire)",
          "1 tomate hachée", "1 c. à c. d'huile d'olive", "sel et poivre au goût", "riz pour servir"],
 "passos": [
   "Assaisonne les dés de poulet avec du sel, du poivre et la moitié du curry.",
   "Fais chauffer l'huile d'olive dans une casserole à feu moyen et fais dorer les dés de poulet de tous les côtés, en remuant, 5 minutes. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et l'ail 2 minutes. Ajoute le reste du curry et remue 30 secondes, juste pour que l'épice libère son parfum.",
   "Ajoute la tomate et fais cuire 3 minutes, jusqu'à ce qu'elle se défasse. Remets le poulet et verse le lait de coco.",
   "Laisse mijoter à feu doux 8 à 10 minutes, en remuant de temps en temps, jusqu'à ce que la sauce épaississe et que le poulet soit tendre. Sers sur le riz."],
 "porcoes8": ["½ portion · 3 c. à s. de riz",
              "1 portion · 4 c. à s. de riz",
              "1 portion · 5 c. à s. de riz",
              "1 portion · 5 c. à s. de riz · poulet en plus",
              "1 portion · 5 c. à s. de riz",
              "1 grande portion · 6 c. à s. de riz",
              "1 portion + poulet · 7 c. à s. de riz",
              "double portion · 8 c. à s. de riz"],
 "dica": "Le lait de coco allégé apporte du crémeux à la sauce avec bien moins de graisse que la crème. Le curry parfume et donne l'impression d'un plat spécial, ce qui aide à manger lentement et à être satisfait avec une portion mesurée de poulet et de riz.",
},
{
 "nome": "Sardines rôties, pommes de terre et salade",
 "hook": "Bon marché, pleines d'oméga-3 et prêtes en quelques minutes — la sardine est l'une des meilleures alliées de qui veut maigrir avec peu d'argent.",
 "tempo": "30 min", "rende": "1 portion", "kcal_base": 450,
 "ings": ["3 à 4 sardines fraîches vidées (ou 1 boîte de sardines au naturel)", "1 petite pomme de terre en rondelles",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "1 gousse d'ail hachée",
          "sel, poivre et origan au goût", "salade verte et tomate pour la salade"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe la pomme de terre en fines rondelles, assaisonne avec du sel et la moitié de l'huile d'olive et étale sur une plaque.",
   "Enfourne la pomme de terre 10 minutes, pour qu'elle commence à s'attendrir.",
   "Assaisonne les sardines avec du sel, du poivre, l'ail, l'origan et le jus de citron.",
   "Sors la plaque, place les sardines entre les pommes de terre et arrose du reste d'huile d'olive.",
   "Remets au four 15 minutes, jusqu'à ce que les sardines soient dorées et la pomme de terre tendre. Sers avec une salade verte fraîche à côté.",
   "Si tu prends des sardines en boîte, saute le four pour le poisson : fais seulement rôtir la pomme de terre et monte l'assiette avec les sardines égouttées et la salade."],
 "porcoes8": ["2 sardines · ½ pomme de terre · salade",
              "3 sardines · 1 petite pomme de terre · salade",
              "3 sardines · 1 pomme de terre · salade",
              "4 sardines · 1 pomme de terre · un filet d'huile",
              "4 sardines · 1 pomme de terre · salade",
              "4 sardines · 1 grosse pomme de terre · salade",
              "5 sardines · 1 grosse pomme de terre · un filet d'huile",
              "6 sardines · 2 petites pommes de terre · salade"],
 "dica": "La sardine est un petit poisson puissant : beaucoup d'oméga-3 (la bonne graisse qui fait du bien au cœur), des protéines et du calcium, pour un prix très bas. Rôtie avec un peu de pomme de terre et une salade fraîche, elle devient un déjeuner complet, nourrissant et économique.",
},
{
 "nome": "Aubergine farcie à la viande hachée",
 "hook": "L'aubergine devient elle-même le plat — farcie de viande relevée et gratinée, elle est belle et trompe n'importe quelle envie de trop manger.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 420,
 "ings": ["1 grosse aubergine", "200 g de viande de bœuf hachée maigre", "1 oignon haché", "1 gousse d'ail hachée",
          "1 tomate hachée", "1 c. à c. d'huile d'olive", "2 c. à s. de fromage râpé allégé",
          "sel, poivre et persil au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe l'aubergine en deux dans la longueur. À la cuillère, retire une partie de la chair pour former deux « barquettes ». Hache la chair retirée.",
   "Pose les barquettes sur une plaque, arrose d'un peu d'huile d'olive et enfourne 10 minutes, juste pour les attendrir.",
   "Pendant ce temps, dans une poêle, fais revenir l'oignon et l'ail dans le reste d'huile d'olive 2 minutes. Ajoute la viande hachée et remue jusqu'à ce qu'il n'y ait plus de rose.",
   "Ajoute la tomate, la chair d'aubergine hachée, du sel et du poivre et fais cuire 5 minutes, jusqu'à obtenir une farce moelleuse.",
   "Garnis les barquettes d'aubergine avec la viande, parsème de fromage râpé et remets au four 15 minutes, jusqu'à ce que ce soit gratiné (le fromage fondu et doré). Parsème de persil et sers."],
 "porcoes8": ["½ aubergine · salade",
              "1 aubergine farcie · salade",
              "1 aubergine · 2 c. à s. de riz",
              "1 aubergine · viande en plus · salade",
              "1 aubergine · viande en plus · 2 c. à s. de riz",
              "1 grosse aubergine · 3 c. à s. de riz",
              "1 aubergine · double viande · 4 c. à s. de riz",
              "aubergine + portion de viande en plus · 4 c. à s. de riz"],
 "dica": "L'aubergine contient beaucoup d'eau et de fibres, elle remplit donc l'estomac pour très peu de calories — farcie, elle donne du volume au plat et rassasie. La viande maigre apporte les protéines, et un peu de fromage par-dessus calme l'envie de gratiné sans excès.",
},
{
 "nome": "Salade César légère au poulet grillé",
 "hook": "La salade César crémeuse que tu aimes, avec une sauce au yaourt bien pensée — tout le crémeux, aucune culpabilité.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 400,
 "ings": ["1 filet de poulet grillé en lanières (environ 130 g)", "feuilles de laitue romaine", "1 tranche de pain complet en cubes",
          "2 c. à s. de yaourt nature sans sucre", "1 c. à c. de moutarde",
          "1 c. à c. de fromage râpé", "le jus de ½ citron", "1 gousse d'ail écrasée", "sel et poivre au goût"],
 "passos": [
   "Assaisonne le poulet avec du sel et du poivre et grille-le dans une poêle antiadhésive 4 minutes de chaque côté, jusqu'à ce qu'il soit doré et blanc à l'intérieur. Coupe en lanières.",
   "Fais les croûtons : étale les cubes de pain complet sur une plaque et enfourne à four moyen 8 minutes, jusqu'à ce qu'ils soient croustillants (ou fais-les griller dans une poêle sans huile).",
   "Prépare la sauce : dans un petit bol, mélange le yaourt, la moutarde, le fromage râpé, le jus de citron, l'ail écrasé, du sel et du poivre, jusqu'à obtenir une crème.",
   "Déchire la laitue à la main et mets-la dans un grand saladier. Arrose de sauce et mélange pour bien enrober les feuilles.",
   "Ajoute les lanières de poulet et les croûtons par-dessus et sers tout de suite, pour que le pain reste croustillant."],
 "porcoes8": ["100 g de poulet · salade · quelques croûtons",
              "130 g de poulet · salade · croûtons",
              "130 g de poulet · salade · croûtons",
              "150 g de poulet · salade · 1 c. à s. de fromage en plus",
              "150 g de poulet · salade · croûtons",
              "170 g de poulet · salade · croûtons",
              "200 g de poulet · salade · croûtons en plus",
              "220 g de poulet · salade · croûtons en plus"],
 "dica": "La sauce César classique est une bombe de mayonnaise et d'huile. En la remplaçant par du yaourt avec de la moutarde et du citron, tu gardes le crémeux et le goût marqué avec beaucoup moins de graisse. Le poulet grillé transforme la salade en un vrai repas, plein de protéines.",
},
{
 "nome": "Lanières de bœuf aux poivrons et riz",
 "hook": "De fines lanières de bœuf sautées avec des poivrons colorés — parfumées, relevées et prêtes à la poêle en quelques minutes.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["250 g de bœuf maigre en fines lanières", "1 poivron rouge en lanières",
          "1 poivron jaune en lanières", "1 oignon en lanières", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "cumin, sel, poivre et coriandre au goût",
          "riz pour servir"],
 "passos": [
   "Assaisonne les lanières de bœuf avec du sel, du poivre, du cumin, l'ail et le jus de citron. Laisse prendre le goût 10 minutes.",
   "Fais chauffer une grande poêle avec la moitié de l'huile d'olive à feu vif. Mets la viande petit à petit (pas tout d'un coup, sinon elle rend son eau) et fais-la dorer rapidement, en remuant, 3 minutes. Retire et réserve.",
   "Dans la même poêle, avec le reste d'huile d'olive, ajoute l'oignon et les poivrons. Remue à feu vif 4 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes et colorés.",
   "Remets la viande dans la poêle et mélange 1 minute, juste pour réunir les saveurs.",
   "Parsème de coriandre et sers sur une portion de riz. C'est aussi excellent roulé dans une tortilla complète."],
 "porcoes8": ["½ portion · 3 c. à s. de riz",
              "1 portion · 4 c. à s. de riz",
              "1 portion · 5 c. à s. de riz",
              "1 portion · 5 c. à s. de riz · viande en plus",
              "1 portion · 5 c. à s. de riz",
              "1 grande portion · 6 c. à s. de riz",
              "1 portion + viande · 7 c. à s. de riz",
              "double portion · 8 c. à s. de riz"],
 "dica": "Couper la viande en fines lanières la fait aller plus loin : une petite portion paraît bien plus généreuse dans l'assiette. Sautée rapidement à feu vif avec des poivrons, elle reste juteuse et pleine de goût sans avoir besoin de sauce grasse. Les poivrons apportent de la couleur, des vitamines et des fibres pour presque aucune calorie.",
},
{
 "nome": "Burger maison au bœuf maigre et salade",
 "hook": "Le burger qui calme l'envie et fait quand même maigrir — fait maison avec de la viande maigre, sans pain gras.",
 "tempo": "20 min", "rende": "2 portions", "kcal_base": 440,
 "ings": ["250 g de viande de bœuf hachée maigre", "½ oignon finement haché", "1 gousse d'ail hachée",
          "sel, poivre et persil au goût", "1 c. à c. d'huile d'olive", "2 pains à burger complets",
          "feuilles de salade, tomate et oignon en rondelles pour monter"],
 "passos": [
   "Dans un bol, mélange la viande hachée avec l'oignon haché, l'ail, du sel, du poivre et du persil. Malaxe à la main juste jusqu'à ce que ça se tienne, sans travailler la viande trop longtemps (sinon le burger devient dur).",
   "Divise la viande en deux et forme deux disques, bien aplatis à la main. Fais un léger creux au centre de chacun avec le pouce — cela évite qu'ils ne gonflent au milieu.",
   "Fais chauffer une poêle antiadhésive avec quelques gouttes d'huile d'olive à feu moyen-vif. Pose les burgers et laisse 3 à 4 minutes de chaque côté, sans les écraser avec la spatule, jusqu'à ce qu'ils soient dorés dehors et à ton goût dedans.",
   "Si tu veux, fais griller légèrement le pain complet ouvert dans la poêle.",
   "Monte : le pain, la salade, le burger, la tomate et l'oignon. Referme et sers. Pour une version encore plus légère, mange le burger sans pain, avec une salade bien garnie à côté."],
 "porcoes8": ["1 burger · sans pain · salade",
              "1 burger · ½ pain · salade",
              "1 burger · 1 pain · salade",
              "1 burger · 1 pain · salade",
              "1 gros burger · 1 pain · salade",
              "1 gros burger · 1 pain · salade",
              "2 burgers · 1 pain · salade",
              "2 burgers · 1 pain · salade"],
 "dica": "Le problème du burger de fast-food, c'est la viande grasse, la sauce et la friture. Fait maison avec de la viande maigre et grillé sans huile, il devient de la protéine pure. En le mangeant avec beaucoup de salade et peu (ou pas) de pain, tu calmes l'envie sans faire exploser les calories.",
},
{
 "nome": "Poisson blanc, légumes et semoule",
 "hook": "Un filet blanc délicat sur une semoule légère — léger, élégant et prêt avant même que tu ne t'en rendes compte.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 420,
 "ings": ["1 filet de poisson blanc (merlu, cabillaud ou tilapia, environ 150 g)", "90 g de semoule",
          "120 ml d'eau chaude", "130 g de légumes en dés (haricots verts, carotte, petits pois)",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre et persil au goût"],
 "passos": [
   "Mets la semoule dans un bol avec une pincée de sel, couvre avec l'eau chaude, pose une assiette dessus et laisse 5 minutes. Égraine ensuite à la fourchette jusqu'à ce qu'elle soit bien détachée.",
   "Fais cuire les légumes en dés à la vapeur ou dans peu d'eau bouillante 5 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes. Égoutte.",
   "Assaisonne le poisson avec du sel, du poivre et le jus de citron.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen. Pose le filet et laisse 3 à 4 minutes de chaque côté, en le retournant délicatement une fois, jusqu'à ce qu'il soit doré et se détache en lamelles à la fourchette.",
   "Mélange les légumes à la semoule. Monte l'assiette avec la semoule aux légumes et le filet par-dessus. Parsème de persil et sers."],
 "porcoes8": ["120 g de poisson · 60 g de semoule · légumes",
              "150 g de poisson · 90 g de semoule · légumes",
              "150 g de poisson · 90 g de semoule · légumes",
              "170 g de poisson · 115 g de semoule · un filet d'huile",
              "170 g de poisson · 115 g de semoule · légumes",
              "200 g de poisson · 130 g de semoule · légumes",
              "220 g de poisson · 175 g de semoule · un filet d'huile",
              "250 g de poisson · 175 g de semoule · un filet d'huile"],
 "dica": "Les poissons blancs comme le merlu et le cabillaud sont très maigres et légers, idéaux pour le déjeuner de qui veut maigrir. La semoule cuit rien qu'avec de l'eau chaude, sans matière grasse, et avec les légumes elle devient un accompagnement coloré, léger et plein de fibres.",
},
{
 "nome": "Brochettes de poulet et légumes avec riz",
 "hook": "Colorées et amusantes à monter, les brochettes cuisent uniformément et donnent à n'importe quel déjeuner un air de fête.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 450,
 "ings": ["2 filets de blanc de poulet en dés (environ 300 g)", "1 poivron en carrés", "1 oignon en morceaux",
          "1 courgette en grosses rondelles", "tomates cerises", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et paprika au goût", "riz pour servir", "piques à brochette"],
 "passos": [
   "Assaisonne les dés de poulet avec du sel, du poivre, du paprika et le jus de citron. Laisse prendre le goût 10 minutes.",
   "Monte les brochettes en alternant un dé de poulet, un morceau de poivron, un d'oignon, une rondelle de courgette et une tomate cerise, jusqu'à remplir la pique.",
   "Badigeonne les brochettes d'huile d'olive.",
   "Fais chauffer une grande poêle ou un gril à feu moyen-vif. Pose les brochettes et tourne-les toutes les 3 minutes, jusqu'à ce que le poulet soit doré de tous les côtés et blanc à l'intérieur (environ 12 minutes au total).",
   "Sers les brochettes sur une portion de riz."],
 "porcoes8": ["1 brochette · 3 c. à s. de riz",
              "2 brochettes · 4 c. à s. de riz",
              "2 brochettes · 5 c. à s. de riz",
              "2 brochettes · 5 c. à s. de riz · poulet en plus",
              "2 brochettes · 5 c. à s. de riz",
              "3 brochettes · 6 c. à s. de riz",
              "3 brochettes · 7 c. à s. de riz",
              "3 grandes brochettes · 8 c. à s. de riz"],
 "dica": "Les brochettes aident naturellement à contrôler la portion et mélangent beaucoup de légumes aux protéines. Le poulet maigre grillé rassasie sans graisse, et les légumes colorés remplissent l'assiette de fibres et de vitamines pour presque aucune calorie.",
},
{
 "nome": "Salade de pommes de terre légère à l'œuf et au thon",
 "hook": "La salade de pommes de terre crémeuse des fêtes, sans la mayonnaise lourde — elle devient un repas complet et léger.",
 "tempo": "25 min", "rende": "2 portions", "kcal_base": 410,
 "ings": ["2 pommes de terre moyennes en dés", "2 œufs durs", "1 boîte de thon au naturel, égoutté",
          "3 c. à s. de yaourt nature sans sucre", "1 c. à c. de moutarde",
          "oignon rouge, persil et ciboulette ciselés", "sel, poivre et le jus de ½ citron au goût"],
 "passos": [
   "Fais cuire les dés de pomme de terre 12 à 15 minutes dans de l'eau bouillante salée, jusqu'à ce qu'ils soient tendres sans se défaire (une fourchette entre facilement). Égoutte et laisse tiédir.",
   "Fais cuire les œufs 9 minutes, passe-les sous l'eau froide, écale-les et coupe-les en morceaux.",
   "Prépare la sauce : mélange le yaourt, la moutarde, le jus de citron, du sel et du poivre dans un grand saladier.",
   "Ajoute dans le saladier les pommes de terre tièdes, le thon égoutté, les œufs, l'oignon rouge et les herbes.",
   "Mélange délicatement, pour ne pas écraser les pommes de terre. Goûte le sel et sers tout de suite ou bien frais."],
 "porcoes8": ["½ portion · ½ boîte de thon · 1 œuf",
              "1 portion · 1 boîte de thon · 2 œufs",
              "1 portion · 1 boîte de thon · 2 œufs",
              "1 portion · 1 boîte de thon · 2 œufs · salade verte",
              "1 portion · 1 boîte de thon · 2 œufs",
              "1 grande portion · 1½ boîte de thon · 2 œufs",
              "grande portion · 1½ boîte de thon · 3 œufs",
              "double portion · 2 boîtes de thon · 3 œufs"],
 "dica": "Remplacer la mayonnaise par du yaourt à la moutarde supprime beaucoup de graisse et ajoute des protéines. Le thon et l'œuf transforment une salade de pommes de terre en un repas complet et rassasiant. La pomme de terre froide forme même une fibre particulière qui nourrit les bonnes bactéries de l'intestin.",
},
{
 "nome": "Poulet rôti au four avec légumes racines",
 "hook": "Tu mets tout sur une plaque et tu laisses le four travailler — le poulet sort bien doré et les légumes deviennent tendres et sucrés.",
 "tempo": "45 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["2 hauts de cuisse de poulet sans peau (ou 2 filets épais, environ 300 g)", "1 pomme de terre en morceaux",
          "1 carotte en gros morceaux", "1 morceau de potiron en dés", "1 oignon en quartiers",
          "2 gousses d'ail", "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre et romarin au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe la pomme de terre, la carotte, le potiron et l'oignon en gros morceaux de taille similaire, pour qu'ils cuisent uniformément.",
   "Sur une grande plaque, étale les légumes et les gousses d'ail. Assaisonne avec du sel, du poivre, du romarin et la moitié de l'huile d'olive, et mélange à la main.",
   "Assaisonne le poulet avec du sel, du poivre, le jus de citron et le reste d'huile d'olive. Place les morceaux entre les légumes.",
   "Enfourne 35 à 40 minutes, en retournant les légumes à mi-cuisson, jusqu'à ce que le poulet soit doré et cuit à cœur (le jus qui s'écoule quand on le pique doit être clair) et les légumes tendres.",
   "Sers directement de la plaque, avec tout le jus qui s'est formé au fond."],
 "porcoes8": ["1 haut de cuisse · ½ portion de légumes",
              "1 haut de cuisse · 1 portion de légumes",
              "1 gros haut de cuisse · 1 portion de légumes",
              "2 hauts de cuisse · 1 portion de légumes",
              "2 hauts de cuisse · 1 portion de légumes",
              "2 hauts de cuisse · 1 grande portion de légumes",
              "2 hauts de cuisse · grande portion de légumes",
              "3 hauts de cuisse · double portion de légumes"],
 "dica": "Rôtir sans peau et sans trop d'huile garde le poulet léger, et le jus qu'il rend assaisonne les légumes sans besoin de matière grasse. Le potiron et la carotte deviennent sucrés en rôtissant, ce qui calme l'envie de sucré, et ils remplissent l'assiette de fibres et de vitamines pour peu de calories.",
},
{
 "nome": "Poulet à la parmesane au four avec salade",
 "hook": "La parmesane croustillante et gratinée de tes rêves, cuite au four au lieu d'être frite — tout le plaisir, sans la friture.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["2 filets de blanc de poulet fins (environ 300 g)", "1 œuf", "4 c. à s. de chapelure complète",
          "240 ml de sauce tomate maison", "3 c. à s. de mozzarella allégée râpée",
          "sel, poivre et origan au goût", "salade verte"],
 "passos": [
   "Préchauffe le four à 200 °C. Assaisonne les filets fins avec du sel et du poivre.",
   "Bats l'œuf dans une assiette creuse. Mets la chapelure dans une autre assiette, mélangée à l'origan.",
   "Passe chaque filet d'abord dans l'œuf, puis dans la chapelure, en appuyant pour bien couvrir les deux faces.",
   "Pose les filets sur une plaque antiadhésive (ou recouverte de papier cuisson) et enfourne 15 minutes, en les retournant à mi-cuisson, jusqu'à ce que la croûte soit dorée et croustillante.",
   "Recouvre chaque filet de sauce tomate et de fromage râpé. Remets au four 8 minutes, jusqu'à ce que le fromage fonde et bouillonne.",
   "Sers avec une salade verte fraîche à côté."],
 "porcoes8": ["100 g de poulet · peu de fromage · salade",
              "130 g de poulet · fromage · salade",
              "150 g de poulet · fromage · salade",
              "150 g de poulet · fromage · 3 c. à s. de riz",
              "150 g de poulet · fromage · 3 c. à s. de riz",
              "170 g de poulet · fromage · 4 c. à s. de riz",
              "200 g de poulet · fromage · 5 c. à s. de riz",
              "220 g de poulet · fromage en plus · 5 c. à s. de riz"],
 "dica": "La parmesane fait grossir à cause de la friture et de l'excès de fromage. Panée à la chapelure complète et cuite au four, elle reste croustillante avec une fraction de la graisse. Un peu de fromage allégé par-dessus calme l'envie de gratiné, et la salade équilibre l'assiette.",
},
{
 "nome": "Bol de riz, edamame et saumon",
 "hook": "Inspiré du poke hawaïen : frais, coloré et nourrissant, il se monte dans un bol et rassasie sans peser.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 480,
 "ings": ["1 pavé de saumon en dés (environ 130 g)", "4 c. à s. de riz cuit", "80 g d'edamame (fèves de soja) cuits",
          "½ concombre en petits dés", "½ carotte râpée", "½ avocat en tranches", "1 c. à s. de sauce soja allégée",
          "sésame, le jus de ½ citron et ciboulette au goût"],
 "passos": [
   "Fais cuire les edamame 4 minutes dans de l'eau bouillante, égoutte et, s'ils sont en cosse, sors les graines.",
   "Assaisonne les dés de saumon avec la sauce soja et le jus de citron. Laisse prendre le goût 5 minutes. (Si tu le préfères cuit, saisis rapidement les dés à la poêle 3 minutes.)",
   "Dans un bol, mets le riz d'un côté comme base.",
   "Dispose par-dessus, en groupes séparés, le saumon, les edamame, le concombre, la carotte râpée et l'avocat.",
   "Arrose d'un peu plus de sauce soja, parsème de sésame et de ciboulette et sers."],
 "porcoes8": ["100 g de saumon · 3 c. à s. de riz · ¼ avocat",
              "130 g de saumon · 4 c. à s. de riz · ½ avocat",
              "130 g de saumon · 5 c. à s. de riz · ½ avocat",
              "150 g de saumon · 5 c. à s. de riz · ½ avocat",
              "150 g de saumon · 5 c. à s. de riz · ½ avocat",
              "170 g de saumon · 6 c. à s. de riz · ½ avocat",
              "200 g de saumon · 7 c. à s. de riz · avocat",
              "220 g de saumon · 8 c. à s. de riz · avocat"],
 "dica": "C'est un plat complet et équilibré : protéines et oméga-3 du saumon, protéines végétales des edamame, bonne graisse de l'avocat et fibres des légumes crus. Monté en bol, il est beau et rassasiant, et prouve qu'une nourriture saine peut être une fête pour les yeux.",
},
{
 "nome": "Soupe consistante de légumes au poulet effiloché",
 "hook": "Une soupe qui est un vrai repas : consistante en poulet et en légumes, elle réchauffe et rassasie sans peser.",
 "tempo": "35 min", "rende": "3 portions", "kcal_base": 380,
 "ings": ["1 filet de blanc de poulet (environ 150 g)", "1 pomme de terre en dés", "1 carotte en dés",
          "1 courgette en dés", "80 g de maïs ou de petits pois", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "sel, poivre, persil et ciboulette au goût", "1 litre d'eau"],
 "passos": [
   "Dans une grande casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes, en remuant, jusqu'à ce qu'ils deviennent translucides.",
   "Ajoute le filet de poulet entier et l'eau. Porte à ébullition et laisse cuire 15 minutes, jusqu'à ce que le poulet soit cuit.",
   "Retire le poulet, laisse tiédir et effiloche-le avec deux fourchettes. Réserve.",
   "Dans la même eau, ajoute la pomme de terre, la carotte, la courgette et le maïs. Assaisonne avec du sel et du poivre et fais cuire 12 à 15 minutes, jusqu'à ce que les légumes soient tendres.",
   "Remets le poulet effiloché dans la casserole, rectifie le sel et fais cuire encore 3 minutes. Parsème d'herbes et sers bien chaud."],
 "porcoes8": ["1 louche · poulet · sans pomme de terre en plus",
              "2 louches · poulet · légumes",
              "2 louches · poulet · légumes",
              "2 louches · poulet en plus · 1 tranche de pain",
              "2 louches · poulet en plus · 1 tranche de pain",
              "3 louches · poulet · 1 tranche de pain",
              "3 louches · poulet en plus · 2 tranches de pain",
              "3 grandes louches · double poulet · 2 tranches de pain"],
 "dica": "Les soupes sont excellentes pour maigrir : le volume de liquide et de légumes remplit l'estomac pour très peu de calories, et la chaleur oblige à manger plus lentement. Avec le poulet effiloché, elle cesse d'être une entrée et devient un repas complet, léger et réconfortant.",
},
{
 "nome": "Galette salée d'avoine garnie au poulet",
 "hook": "La pâte ne contient qu'un œuf et de l'avoine, se mélange en quelques secondes et devient une galette dorée garnie de poulet crémeux.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 400,
 "ings": ["1 œuf", "3 c. à s. de flocons d'avoine", "3 c. à s. d'eau", "1 pincée de sel",
          "1 filet de poulet cuit et effiloché (environ 100 g)", "2 c. à s. de sauce tomate",
          "1 c. à s. de yaourt nature", "1 c. à c. d'huile d'olive", "origan au goût"],
 "passos": [
   "Dans un bol, bats à la fourchette l'œuf, l'avoine, l'eau et le sel jusqu'à obtenir une pâte lisse. Laisse reposer 3 minutes pour que l'avoine absorbe le liquide.",
   "Fais chauffer une poêle antiadhésive avec la moitié de l'huile d'olive à feu moyen. Verse la pâte et étale-la en tournant la poêle, pour former un disque fin.",
   "Laisse 2 minutes, jusqu'à ce que le bord se décolle, retourne délicatement et fais dorer l'autre face 1 minute. Retire la galette.",
   "Mélange le poulet effiloché avec la sauce tomate, le yaourt et l'origan, et réchauffe rapidement à la poêle.",
   "Garnis la galette de poulet, replie-la en deux ou roule-la et sers chaud, avec une salade à côté si tu veux."],
 "porcoes8": ["1 galette · 80 g de poulet",
              "1 galette · 100 g de poulet",
              "1 galette · 120 g de poulet",
              "1 galette · 120 g de poulet · salade",
              "1 galette · 130 g de poulet · salade",
              "2 galettes · 150 g de poulet",
              "2 galettes · 170 g de poulet · salade",
              "2 galettes · 200 g de poulet · salade"],
 "dica": "La pâte à l'œuf et à l'avoine remplace la farine blanche par des fibres et des protéines, ce qui rassasie bien plus qu'une galette classique. Garnie de poulet effiloché et d'une sauce légère au yaourt, elle devient un repas pratique, savoureux et complet, très bien aussi pour le dîner.",
},
{
 "nome": "Crevettes à l'ail, légumes et riz",
 "hook": "Des crevettes rosées dorées à l'ail, qui parfument toute la cuisine — un déjeuner de week-end léger et spécial.",
 "tempo": "20 min", "rende": "1 portion", "kcal_base": 430,
 "ings": ["150 g de crevettes décortiquées", "4 c. à s. de riz cuit", "100 g de brocoli et haricots verts",
          "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive", "le jus de ½ citron",
          "sel, poivre et persil au goût"],
 "passos": [
   "Sèche bien les crevettes avec du papier absorbant et assaisonne-les avec du sel, du poivre et le jus de citron. Laisse prendre le goût 5 minutes.",
   "Coupe le brocoli en bouquets et les haricots verts en morceaux. Fais-les cuire à la vapeur ou dans peu d'eau bouillante 4 minutes, jusqu'à ce qu'ils soient verts et tendres mais encore fermes. Égoutte.",
   "Fais chauffer une poêle antiadhésive avec l'huile d'olive à feu moyen. Ajoute l'ail haché et remue 30 secondes, juste le temps qu'il embaume et commence à dorer — attention à ne pas le brûler, sinon il devient amer.",
   "Ajoute les crevettes et fais-les sauter (remue à feu moyen-vif) 2 à 3 minutes, juste le temps qu'elles rosissent et s'enroulent. Ne les cuis pas trop, sinon elles deviennent caoutchouteuses.",
   "Ajoute les légumes et le riz déjà cuit dans la poêle et mélange 1 minute, pour qu'ils prennent le goût de l'ail. Parsème de persil et sers tout de suite."],
 "porcoes8": ["120 g de crevettes · 3 c. à s. de riz · légumes",
              "150 g de crevettes · 4 c. à s. de riz · légumes",
              "150 g de crevettes · 5 c. à s. de riz · légumes",
              "170 g de crevettes · 5 c. à s. de riz · un filet d'huile",
              "170 g de crevettes · 5 c. à s. de riz · légumes",
              "200 g de crevettes · 6 c. à s. de riz · légumes",
              "220 g de crevettes · 7 c. à s. de riz · un filet d'huile",
              "250 g de crevettes · 8 c. à s. de riz · un filet d'huile"],
 "dica": "La crevette est presque entièrement de la protéine, avec très peu de graisses et de calories, tu peux donc te servir sans culpabilité. Dorée à l'ail, elle gagne beaucoup de goût avec un simple filet d'huile d'olive, et avec les légumes et une portion mesurée de riz, elle devient un plat léger digne d'un restaurant.",
},
{
 "nome": "Boulettes de bœuf en sauce avec purée",
 "hook": "Des boulettes moelleuses dans une sauce tomate consistante, sur une purée légère — l'étreinte chaude que le régime autorise.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 490,
 "ings": ["250 g de viande de bœuf hachée maigre", "1 œuf", "2 c. à s. de flocons d'avoine", "1 gousse d'ail hachée",
          "3 tomates hachées (ou sauce tomate)", "1 oignon haché", "2 pommes de terre moyennes",
          "1 c. à c. d'huile d'olive", "sel, poivre et basilic au goût"],
 "passos": [
   "Épluche et fais cuire les pommes de terre 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elles soient bien tendres. Égoutte et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse. Pour plus de crémeux, ajoute un peu d'eau de cuisson.",
   "Dans un bol, mélange la viande hachée, l'œuf, l'avoine, la moitié de l'ail, du sel et du poivre. Malaxe à la main et forme des boulettes de la taille d'une noix.",
   "Fais chauffer l'huile d'olive dans une casserole et fais dorer les boulettes de tous les côtés, en les tournant délicatement, 5 minutes. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et le reste de l'ail 2 minutes. Ajoute les tomates, du sel et du poivre et fais cuire 8 minutes, jusqu'à obtenir une sauce.",
   "Remets les boulettes dans la sauce et fais cuire encore 8 minutes, jusqu'à ce qu'elles soient cuites à cœur. Parsème de basilic.",
   "Sers les boulettes avec la sauce sur la purée de pommes de terre."],
 "porcoes8": ["3 boulettes · ½ portion de purée",
              "4 boulettes · 1 portion de purée",
              "4 boulettes · 1 portion de purée",
              "5 boulettes · 1 portion de purée",
              "5 boulettes · 1 portion de purée",
              "6 boulettes · 1 grande portion de purée",
              "7 boulettes · grande portion de purée",
              "8 boulettes · double portion de purée"],
 "dica": "Les boulettes contiennent de l'avoine à la place de plus de pain, ce qui les lie avec des fibres plutôt qu'avec de l'amidon blanc. Faites avec une viande maigre et cuites dans la sauce (pas frites), elles restent juteuses et légères. La purée de pommes de terre classique, dans la bonne mesure, réconforte et rassasie bien.",
},
{
 "nome": "Risotto léger au poulet et aux légumes",
 "hook": "Le crémeux d'un risotto sans beurre ni excès de fromage — le riz libère sa propre crème et enveloppe le poulet et les légumes.",
 "tempo": "35 min", "rende": "2 portions", "kcal_base": 480,
 "ings": ["185 g de riz (à risotto ou ordinaire)", "2 filets de blanc de poulet en dés (environ 300 g)",
          "1 carotte en petits dés", "75 g de petits pois", "1 oignon haché", "1 gousse d'ail hachée",
          "1 c. à c. d'huile d'olive", "1 c. à s. de fromage râpé", "sel, poivre et persil au goût",
          "bouillon de légumes maison ou eau chaude (environ 700 ml)"],
 "passos": [
   "Assaisonne les dés de poulet avec du sel et du poivre. Fais chauffer l'huile d'olive dans une casserole et fais dorer le poulet 5 minutes, en remuant. Retire et réserve.",
   "Dans la même casserole, fais revenir l'oignon et l'ail 2 minutes. Ajoute le riz et remue 1 minute, juste pour enrober les grains des arômes.",
   "Commence à verser le bouillon chaud petit à petit, une louche à la fois, en remuant sans arrêt. N'ajoute du bouillon que lorsque le précédent est presque absorbé.",
   "À mi-cuisson (environ 10 minutes), ajoute la carotte et les petits pois. Continue de remuer et d'ajouter du bouillon.",
   "Quand le riz est tendre et crémeux (environ 18 à 20 minutes au total), remets le poulet, ajoute le fromage râpé et mélange. Retire du feu, parsème de persil et sers tout de suite."],
 "porcoes8": ["½ portion · poulet",
              "1 portion · poulet",
              "1 portion · poulet",
              "1 portion · poulet en plus",
              "1 portion · poulet en plus",
              "1 grande portion · poulet",
              "grande portion · poulet en plus",
              "double portion · poulet en plus"],
 "dica": "Le risotto traditionnel contient beaucoup de beurre et de fromage. Ici, le crémeux vient de l'amidon du riz lui-même, libéré en remuant, avec juste une touche de fromage. Avec beaucoup de poulet et de légumes, le plat devient consistant et satisfaisant, ce qui prouve qu'on peut manger du risotto sans culpabilité.",
},
]
