# -*- coding: utf-8 -*-
"""SMOOTHIE, JUICE and DETOX TEA recipes (121-150). English (US market). No sugar.
- Juices and smoothies (have calories): adjustment table -> porcoes8 (8 entries).
  Targets (cal): 90/110/130/150 · 130/150/170/190.
- Detox teas and waters (~zero calories, no sugar): field 'livre': True ->
  shows a 'free drink' band instead of the table (no porcoes8 needed).
US units: cups / tbsp / oz / °F. Photos shared with the PT edition.
"""

# standard portion for juices (targets 90/110/130/150 · 130/150/170/190)
P = ["1 glass (7 oz)", "1 glass (8 oz)", "1 large glass (10 oz)", "1 large glass · ½ fruit",
     "1 large glass (10 oz)", "1 large glass (12 oz)", "1 large glass · ½ fruit", "2 glasses or 1 extra fruit"]
# standard portion for smoothies (heartier, you can add oats)
V = ["1 glass (7 oz)", "1 glass (8 oz)", "1 large glass (10 oz)", "1 glass · 1 tbsp oats",
     "1 large glass (10 oz)", "1 large glass (12 oz)", "1 large glass · 1 tbsp oats", "1 large glass · 2 tbsp oats"]

RECEITAS = [
# ---------------- DETOX JUICES (121-130) ----------------
{
 "nome": "Detox Green Juice",
 "hook": "The classic morning detox: light, refreshing and full of chlorophyll to give your body a boost.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 90,
 "ings": ["1 kale leaf (or 1 handful of spinach)", "1 green apple, in pieces", "juice of ½ lemon",
          "1 small piece of ginger", "¾ cup cold water", "ice to taste"],
 "passos": [
   "Wash the kale and apple well. Remove the thick stem from the kale.",
   "Put everything in the blender with the cold water and blend on high for 1 minute, until fully liquid.",
   "If you prefer it without bits, strain through a sieve. Serve right away, with ice."],
 "porcoes8": P,
 "dica": "Green leaves have lots of fiber and water for very few calories, helping reduce bloating and giving fullness. Drinking it before breakfast hydrates and prepares the body for the day. With no sugar, it is one of the lightest drinks there is.",
 "prompt": "Square ultra-realistic overhead food photograph of a tall glass of fresh green detox juice with kale and green apple, a lemon slice and ice, a few kale leaves and an apple beside it, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Cucumber, Lemon and Mint Juice",
 "hook": "Pure freshness in a glass — cucumber refreshes, lemon wakes you up and mint perfumes. Hydration that helps you debloat.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 70,
 "ings": ["½ cucumber, in pieces", "juice of 1 lemon", "5 mint leaves", "1 cup cold water", "ice to taste"],
 "passos": [
   "Wash the cucumber and cut into pieces (you can leave the skin on, if it is thin).",
   "Blend the cucumber, the lemon juice, the mint and the water for 1 minute.",
   "Strain if you want it cleaner and serve well chilled, with ice."],
 "porcoes8": P,
 "dica": "Cucumber is almost all water and helps hydrate and reduce fluid retention (that puffiness). With lemon and mint, it becomes a super refreshing, practically calorie-free drink — great to sip through the day instead of soda.",
 "prompt": "Square ultra-realistic overhead food photograph of a tall glass of cucumber lemon mint water with cucumber slices, lemon and fresh mint leaves, ice cubes, on a light wooden table, soft natural light, fresh and refreshing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pineapple Juice with Mint and Ginger",
 "hook": "Sweet, tropical and digestive — pineapple with ginger is the juice that refreshes and even helps fight inflammation.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 110,
 "ings": ["2 pineapple slices, in pieces", "5 mint leaves", "1 small piece of ginger",
          "¾ cup cold water", "ice to taste"],
 "passos": [
   "Cut the pineapple into pieces, removing the skin and the hard core in the center.",
   "Blend the pineapple, the mint, the ginger and the water for 1 minute, until smooth.",
   "Strain if you like and serve well chilled, with ice and a mint leaf."],
 "porcoes8": P,
 "dica": "Pineapple has enzymes that help digestion and is rich in water and vitamin C. Ginger slightly speeds up the metabolism and fights inflammation. It is a naturally sweet juice, so it needs no sugar — the fruit already does that job.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh pineapple juice with mint and ginger, pineapple wedges and mint beside it, ice cubes, on a light wooden table, soft natural light, tropical and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Beet, Carrot and Orange Juice",
 "hook": "Vibrant red and full of energy — beet with orange is a juice that gives you a lift and colors your day.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 120,
 "ings": ["½ small raw beet, in pieces", "1 carrot, in pieces", "juice of 2 oranges",
          "⅓ cup water", "ice to taste"],
 "passos": [
   "Peel the beet and the carrot and cut into small pieces.",
   "Squeeze the oranges. Blend the beet, the carrot, the orange juice and the water for 2 minutes, until fully liquid.",
   "Strain through a sieve (beet and carrot leave fibers) and serve chilled."],
 "porcoes8": P,
 "dica": "Beet improves circulation and gives energy, carrot brings vitamin A and orange, vitamin C. Together they make a naturally sweet, nourishing juice. Since it has natural sugar from the fruit and beet, it is worth respecting the glass portion.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of vibrant red beetroot carrot orange juice, with beetroot, carrot and orange slices beside it, ice cubes, on a light wooden table, soft natural light, vibrant and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Watermelon Juice with Lemon",
 "hook": "Hydration in the form of juice: watermelon is almost all water, just sweet enough and refreshing like few others.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 80,
 "ings": ["2 large watermelon slices, no rind", "juice of ½ lemon", "5 mint leaves (optional)", "ice to taste"],
 "passos": [
   "Cut the watermelon into cubes and remove the larger seeds.",
   "Blend the watermelon with the lemon juice (and the mint, if you like) for 30 seconds — watermelon releases lots of water, so you barely need to add liquid.",
   "Serve immediately, well chilled, with ice."],
 "porcoes8": P,
 "dica": "Watermelon is over 90% water, so it hydrates a lot and fills your stomach for few calories. It is naturally sweet and refreshing, perfect for beating the craving for something sweet and cold in the heat without leaving your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh watermelon juice with a lemon slice and mint, watermelon wedges beside it, ice cubes, on a light wooden table, soft natural light, fresh and summery, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Carrot, Apple and Ginger Juice",
 "hook": "Sweet, orange and with a spicy touch of ginger — a juice that boosts immunity and wakes up the body.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 110,
 "ings": ["1 carrot, in pieces", "1 apple, in pieces", "1 small piece of ginger", "¾ cup water", "ice to taste"],
 "passos": [
   "Peel the carrot and cut the apple into pieces, removing the seeds.",
   "Blend the carrot, the apple, the ginger and the water for 2 minutes, until fully liquid.",
   "Strain through a sieve and serve chilled."],
 "porcoes8": P,
 "dica": "Carrot and apple give natural sweetness and lots of fiber, while ginger gives that warming touch that helps the metabolism. It is a vitamin-rich juice, ideal to start the day with energy and no need for sugar.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of carrot apple ginger juice, with carrot, apple and ginger beside it, ice cubes, on a light wooden table, soft natural light, fresh and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Green Juice with Spinach, Pineapple and Cucumber",
 "hook": "Green and sweet at the same time — the pineapple hides the spinach and you do not even notice you are drinking something so healthy.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 100,
 "ings": ["1 handful of spinach", "1 pineapple slice, in pieces", "½ cucumber, in pieces",
          "juice of ½ lemon", "¾ cup cold water", "ice to taste"],
 "passos": [
   "Wash the spinach and cucumber well.",
   "Blend the spinach, the pineapple, the cucumber, the lemon and the water for 1 minute, until nice and green and liquid.",
   "Strain if you like and serve chilled."],
 "porcoes8": P,
 "dica": "Spinach is very rich in iron and nutrients for almost no calories, and pineapple keeps the juice sweet and tasty with no sugar. Cucumber hydrates and helps you debloat. It is an easy, tasty way to eat more greens.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of green smoothie with spinach, pineapple and cucumber, spinach leaves and pineapple beside it, ice cubes, on a light wooden table, soft natural light, fresh and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Orange Juice with Carrot and Ginger",
 "hook": "Your daily dose of vitamin C in a bright orange glass — it boosts immunity and gives energy for the day.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 110,
 "ings": ["juice of 3 oranges", "1 carrot, in pieces", "1 small piece of ginger", "ice to taste"],
 "passos": [
   "Squeeze the oranges for the juice.",
   "Peel the carrot and cut into small pieces. Blend the carrot, the orange juice and the ginger for 2 minutes.",
   "Strain through a sieve and serve well chilled, with ice."],
 "porcoes8": P,
 "dica": "Orange and carrot are full of vitamin C and A, and ginger gives a touch that helps circulation and metabolism. It is an energizing, naturally sweet juice — just remember to respect the portion, since the fruit sugar adds calories.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of fresh orange carrot ginger juice, with orange halves, carrot and ginger beside it, ice cubes, on a light wooden table, soft natural light, bright and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Natural Grape Juice with Lemon",
 "hook": "Deep purple and full of antioxidants — grapes become a naturally sweet juice that is good for your heart.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 120,
 "ings": ["1 small bunch of seedless purple grapes (about 1½ cups)", "juice of ½ lemon",
          "⅔ cup cold water", "ice to taste"],
 "passos": [
   "Wash the grapes well and pull them off the stems.",
   "Blend the grapes with the lemon and the water for 1 minute, until they break down.",
   "Strain through a sieve, pressing well to get all the juice, and serve chilled."],
 "porcoes8": P,
 "dica": "Purple grapes are rich in antioxidants that protect the heart and skin. Made fresh, with no sugar, natural grape juice is very different from the boxed kind — just remember grapes are a very sweet fruit, so the glass portion matters.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of natural purple grape juice with a lemon slice, fresh grapes beside it, ice cubes, on a light wooden table, soft natural light, rich and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Detox Juice with Apple, Kale and Celery",
 "hook": "Ultra-light and debloating — the green combo that cleans out the body and works great before meals.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 90,
 "ings": ["1 green apple, in pieces", "1 kale leaf", "1 celery stalk", "juice of ½ lemon",
          "¾ cup cold water", "ice to taste"],
 "passos": [
   "Wash the kale, apple and celery. Remove the thick stem from the kale.",
   "Blend the apple, the kale, the celery, the lemon and the water for 1 minute.",
   "Strain and serve well chilled."],
 "porcoes8": P,
 "dica": "Celery is a diuretic and helps flush out excess fluid, kale gives fiber and nutrients and the apple sweetens naturally. It is a light, debloating green juice, great to go with a weight-loss routine.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of green detox juice with apple, kale and celery, celery stalks and green apple beside it, ice cubes, on a light wooden table, soft natural light, fresh and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- SMOOTHIES (131-140) ----------------
{
 "nome": "Banana Oat Smoothie with Cinnamon",
 "hook": "Creamy and comforting, this smoothie holds the whole morning — the liquid breakfast for busy days.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 190,
 "ings": ["1 banana", "2 tablespoons oats", "¾ cup milk (or plant milk)",
          "1 pinch of cinnamon", "ice to taste"],
 "passos": [
   "Peel the banana (if very ripe, it sweetens more).",
   "Blend the banana, the oats, the milk and the cinnamon for 1 minute, until creamy.",
   "Serve right away, with a pinch of cinnamon on top. For it colder, add ice and blend again."],
 "porcoes8": V,
 "dica": "Banana with oats is a duo that fills you for hours thanks to the fiber, and the milk brings protein. It is a smoothie that works as a complete liquid meal — perfect for breakfast or a snack when you are in a hurry, with no need for sugar.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy banana oat smoothie dusted with cinnamon, oats and a banana beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Strawberry Yogurt Smoothie",
 "hook": "Pink and creamy, with the natural sweetness of strawberry — a smoothie that looks like a milkshake, but is light and high in protein.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 150,
 "ings": ["1 cup strawberries (fresh or frozen)", "¾ cup (6 oz) plain unsweetened yogurt",
          "⅓ cup milk (or water)", "sweetener to taste (optional)", "ice to taste"],
 "passos": [
   "Wash the strawberries and remove the green tops.",
   "Blend the strawberries, the yogurt and the milk for 1 minute, into a smooth, pink cream.",
   "Taste and, if you like, sweeten a little. Serve chilled."],
 "porcoes8": V,
 "dica": "Plain yogurt brings protein and creaminess with no sugar, and strawberry sweetens naturally for very few calories. It is a filling, refreshing smoothie that beats the milkshake craving in a light, nourishing way.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy pink strawberry yogurt smoothie, fresh strawberries beside it, on a light wooden table, soft natural light, creamy and fresh, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mixed Berry Smoothie",
 "hook": "Purple, antioxidant and full of flavor — a mix of berries blended creamy, great for your skin and for fullness.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 140,
 "ings": ["1 cup mixed berries (strawberry, blueberry, raspberry)", "¾ cup (6 oz) plain unsweetened yogurt",
          "⅓ cup milk (or water)", "sweetener to taste (optional)", "ice to taste"],
 "passos": [
   "If the berries are frozen, use them straight (they make the smoothie colder and creamier).",
   "Blend the berries, the yogurt and the milk for 1 minute, into a smooth cream.",
   "Taste, sweeten if you like and serve right away."],
 "porcoes8": V,
 "dica": "Berries are champions in antioxidants, which fight aging, and they are low in sugar. With yogurt, they become a high-protein, creamy smoothie that fills you and is one of the healthiest for a snack.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy mixed berry smoothie in purple color, fresh berries beside it, on a light wooden table, soft natural light, creamy and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Green Smoothie with Banana and Spinach",
 "hook": "Green on the outside, sweet on the inside — the banana hides the spinach and delivers a creamy drink full of nutrients.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 160,
 "ings": ["1 banana", "1 handful of spinach", "½ apple, in pieces", "¾ cup milk (or coconut water)",
          "ice to taste"],
 "passos": [
   "Wash the spinach well.",
   "Blend the banana, the spinach, the apple and the milk for 1 minute, until green and creamy.",
   "Serve right away, well chilled."],
 "porcoes8": V,
 "dica": "It is a delicious way to eat more green leaves: the banana and apple sweeten naturally and hide the spinach, which comes in full of iron and fiber. Creamy and filling, it works as a nourishing liquid breakfast.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy green smoothie with banana and spinach, spinach leaves and a banana beside it, on a light wooden table, soft natural light, creamy and healthy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Avocado Smoothie",
 "hook": "Ultra creamy and comforting, with the good fat of avocado — a smoothie that truly fills you and nourishes your skin.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 190,
 "ings": ["½ ripe avocado", "¾ cup milk (or plant milk)", "sweetener to taste — or 1 teaspoon honey",
          "1 pinch of cinnamon or a few drops of lemon", "ice to taste"],
 "passos": [
   "Scoop out the avocado flesh with a spoon, using only the very soft part.",
   "Blend the avocado, the milk and the sweetener (or honey) for 1 minute, into a smooth, silky cream.",
   "Serve chilled, with a pinch of cinnamon or a few drops of lemon."],
 "porcoes8": V,
 "dica": "Avocado has good fat that is very filling and good for the heart and skin. Blended with milk, it becomes a creamy, nourishing smoothie that holds hunger for hours. Being more calorie-dense, it is a great snack option in a one-glass portion.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy avocado smoothie dusted with cinnamon, half an avocado beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mango Yogurt Smoothie",
 "hook": "Tropical, golden and creamy — mango becomes a sweet smoothie that feels like dessert and refreshes on the spot.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 150,
 "ings": ["1 ripe mango, cubed (or 1 cup frozen)", "¾ cup (6 oz) plain unsweetened yogurt",
          "⅓ cup milk (or water)", "ice to taste"],
 "passos": [
   "Peel the mango and cut the flesh into cubes.",
   "Blend the mango, the yogurt and the milk for 1 minute, into a smooth, golden cream.",
   "Serve well chilled."],
 "porcoes8": V,
 "dica": "Mango is naturally sweet and full of vitamin A and C, needing no sugar. With yogurt, the smoothie gains protein and creaminess, becoming a refreshing, filling snack — just respect the portion, since mango is a sweet fruit.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy golden mango smoothie, fresh mango cubes beside it, on a light wooden table, soft natural light, tropical and creamy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Pear Oat Smoothie",
 "hook": "Soft and delicate, the pear gives a light sweetness to the creamy oats — a calm, comforting smoothie.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 170,
 "ings": ["1 ripe pear, in pieces", "2 tablespoons oats", "¾ cup milk (or plant milk)",
          "1 pinch of cinnamon", "ice to taste"],
 "passos": [
   "Wash the pear and cut into pieces, removing the core with the seeds.",
   "Blend the pear, the oats, the milk and the cinnamon for 1 minute, until creamy.",
   "Serve right away, with a pinch of cinnamon on top."],
 "porcoes8": V,
 "dica": "Pear is a soft fruit full of fiber, and with the oats it makes a smoothie that fills you for a good while. The milk adds protein. It is a light, comforting drink, great for breakfast or a snack that holds hunger.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy pear oat smoothie dusted with cinnamon, a pear and oats beside it, on a light wooden table, soft natural light, creamy and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Banana and Cocoa Smoothie",
 "hook": "A chocolate taste in a creamy, sugar-free smoothie — the perfect fix for the afternoon sweet craving.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 180,
 "ings": ["1 banana", "1 tablespoon 100% cocoa powder", "¾ cup milk (or plant milk)",
          "1 teaspoon peanut butter (optional)", "ice to taste"],
 "passos": [
   "Peel the banana (if very ripe, it sweetens more).",
   "Blend the banana, the cocoa, the milk and the peanut butter for 1 minute, into a smooth, chocolatey cream.",
   "Serve well chilled, with ice."],
 "porcoes8": V,
 "dica": "Pure cocoa gives the chocolate flavor with no sugar, and the banana sweetens and makes the smoothie creamy. It is the tastiest way to beat the afternoon chocolate craving in a nourishing way, with the fruit's fiber and the milk's protein.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy chocolate banana smoothie, a banana and cocoa powder beside it, on a light wooden table, soft natural light, creamy and appetizing, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Apple Cinnamon Oat Smoothie",
 "hook": "The taste of an apple pie in a creamy glass — oats, apple and cinnamon blended into a comforting snack.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 170,
 "ings": ["1 apple, in pieces", "2 tablespoons oats", "¾ cup milk (or plant milk)",
          "1 teaspoon cinnamon", "ice to taste"],
 "passos": [
   "Cut the apple into pieces, removing the seeds (you can leave the skin on).",
   "Blend the apple, the oats, the milk and the cinnamon for 1 minute 30 seconds, until creamy and the apple well broken down.",
   "Serve right away, with a bit more cinnamon on top."],
 "porcoes8": V,
 "dica": "Apple with cinnamon and oats feels like a dessert, but together they become a smoothie full of fiber that fills you for hours. Cinnamon helps control the sweet craving. It is a creamy, tasty, light snack, with no added sugar.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of creamy apple cinnamon oat smoothie, an apple and cinnamon stick beside it, on a light wooden table, soft natural light, creamy and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Melon Mint Smoothie",
 "hook": "Light green, sweet and ultra-refreshing — melon with mint is pure hydration in a light smoothie.",
 "tempo": "5 min", "rende": "1 large glass", "kcal_base": 110,
 "ings": ["3 melon slices, no rind, cubed", "5 mint leaves", "½ cup plain yogurt (or ⅓ cup water)",
          "ice to taste"],
 "passos": [
   "Cut the melon into cubes, removing the seeds.",
   "Blend the melon, the mint and the yogurt (or the water) for 1 minute, until smooth.",
   "Serve well chilled, with a mint leaf."],
 "porcoes8": V,
 "dica": "Melon is rich in water and helps hydrate and debloat, with very few calories. Blended with mint, it is refreshing and light; with a bit of yogurt, it gains creaminess and protein. A perfect smoothie for hot days.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of light green melon mint smoothie, melon cubes and mint beside it, on a light wooden table, soft natural light, fresh and refreshing, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- DETOX WATERS (141-144) — FREE ----------------
{
 "nome": "Cucumber, Lemon and Mint Detox Water",
 "hook": "The water that makes you want to drink: light, fragrant and refreshing, to hydrate all day without getting tired of it.",
 "tempo": "5 min + fridge", "rende": "1 pitcher", "kcal_base": 10, "livre": True,
 "ings": ["4 cups (1 quart) water", "½ cucumber, thinly sliced", "½ lemon, sliced", "6 mint leaves", "ice to taste"],
 "passos": [
   "Wash the cucumber, the lemon and the mint.",
   "In a pitcher, put the water, the cucumber and lemon slices and the mint leaves.",
   "Refrigerate for at least 1 hour, for the water to take on the flavor. Serve chilled through the day; you can top it up with more water as you drink."],
 "dica": "Swapping soda and sugary juices for flavored water is one of the habits that most help with weight loss. Cucumber, lemon and mint add flavor with no calories, making water tastier and helping you stay hydrated all day.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass jug of infused detox water with cucumber slices, lemon and mint leaves, ice, a filled glass beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ginger and Lemon Detox Water",
 "hook": "A warm or cold water with a spicy touch that wakes up the metabolism first thing.",
 "tempo": "5 min", "rende": "1 glass", "kcal_base": 8, "livre": True,
 "ings": ["1 glass of water (warm or cold)", "juice of ½ lemon", "a few thin ginger slices", "ice to taste (if cold)"],
 "passos": [
   "Cut the ginger into very thin slices.",
   "Mix the water, the lemon juice and the ginger in a glass.",
   "Let it rest 5 minutes for the ginger to release its flavor. Drink in the morning, on an empty stomach, warm or cold."],
 "dica": "Drinking water with lemon and ginger on an empty stomach helps wake up the body and digestion. Ginger has a mild warming (metabolism-boosting) effect. With no sugar, it is a simple morning ritual that supports weight loss.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of ginger lemon water with thin ginger slices and lemon, ginger root and lemon beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Berry Detox Water",
 "hook": "Pink and pretty in the pitcher, with berries floating — a flavored water that looks like a spa drink.",
 "tempo": "5 min + fridge", "rende": "1 pitcher", "kcal_base": 15, "livre": True,
 "ings": ["4 cups (1 quart) water", "1 handful of berries (strawberry, blueberry, raspberry)", "½ lemon, sliced",
          "mint leaves", "ice to taste"],
 "passos": [
   "Wash the berries and cut the strawberries in half.",
   "In a pitcher, put the water, the berries, the lemon slices and the mint. Lightly crush the berries with a spoon to release the color and flavor.",
   "Refrigerate for 1 to 2 hours and serve chilled."],
 "dica": "Berries add color, flavor and antioxidants to water for almost no calories. It is a pretty, tasty way to drink more water through the day, replacing sugary drinks and helping with hydration and weight loss.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass jug of infused water with strawberries, blueberries, lemon slices and mint, ice, a filled glass beside it, on a light wooden table, soft natural light, fresh and pretty, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Coconut Water with Lemon and Mint",
 "hook": "The natural hydration of coconut water, boosted with lemon and mint — refreshing and full of minerals.",
 "tempo": "3 min", "rende": "1 large glass", "kcal_base": 45, "livre": True,
 "ings": ["1 large glass of coconut water", "juice of ½ lemon", "5 mint leaves", "ice to taste"],
 "passos": [
   "Mix the coconut water with the lemon juice in a glass.",
   "Add the mint leaves and the ice and stir.",
   "Serve well chilled, preferably natural (boxed coconut water often has added sugar — go for the natural kind)."],
 "dica": "Coconut water replaces minerals and hydrates very well, with few calories when it is natural. With lemon and mint, it is even more refreshing. It is great after exercise or on hot days, instead of sugary sports drinks.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of coconut water with lemon and mint leaves, ice, half a lime beside it, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
# ---------------- TEAS / INFUSIONS (145-150) — FREE ----------------
{
 "nome": "Green Tea with Lemon and Ginger",
 "hook": "The number 1 ally for anyone wanting to lose weight: green tea speeds up the metabolism, and lemon and ginger give it an extra push.",
 "tempo": "8 min", "rende": "1 cup", "kcal_base": 5, "livre": True,
 "ings": ["1 cup of water", "1 teaspoon green tea (or 1 tea bag)", "a few ginger slices", "juice of ½ lemon"],
 "passos": [
   "Boil the water and turn off the heat. Wait 1 minute (water that is too hot makes green tea bitter).",
   "Add the green tea and the ginger slices, cover and let it steep for 3 minutes.",
   "Strain, add the lemon juice and drink warm. You can also have it cold, through the day."],
 "dica": "Green tea is one of the most studied foods for weight loss: it has substances that help speed up the metabolism and burn fat. With ginger and lemon, the effect is reinforced. With no sugar, it is a free drink you can have every day.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass cup of green tea with lemon and ginger slices, ginger root and lemon beside it, on a light wooden table, soft natural light, warm and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Iced Hibiscus Tea",
 "hook": "Ruby red and lightly tart, hibiscus is famous for helping you debloat — delicious iced in the heat.",
 "tempo": "10 min + fridge", "rende": "1 pitcher", "kcal_base": 5, "livre": True,
 "ings": ["4 cups (1 quart) water", "2 tablespoons dried hibiscus flowers (or 2 tea bags)",
          "lemon slices", "mint leaves", "ice to taste"],
 "passos": [
   "Boil the water and turn off the heat. Add the hibiscus, cover and let it steep for 5 to 7 minutes.",
   "Strain and let it cool. Refrigerate.",
   "Serve well chilled, with lemon slices, mint and ice."],
 "dica": "Hibiscus tea is known for helping reduce fluid retention (bloating) and is rich in antioxidants. Iced and with no sugar, it is a refreshing, free drink, great to replace sodas and processed juices through the day.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass of iced hibiscus tea in deep red color with lemon slices and mint, ice, on a light wooden table, soft natural light, refreshing and vibrant, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Chamomile Tea with Cinnamon",
 "hook": "Warm and comforting, the tea that calms you before bed — and a good night's sleep also helps you lose weight.",
 "tempo": "8 min", "rende": "1 cup", "kcal_base": 5, "livre": True,
 "ings": ["1 cup of water", "1 tablespoon chamomile flowers (or 1 tea bag)", "1 cinnamon stick (or 1 pinch ground)"],
 "passos": [
   "Boil the water and turn off the heat.",
   "Add the chamomile and the cinnamon, cover and let it steep for 5 minutes.",
   "Strain and drink warm, preferably at night, before bed."],
 "dica": "Chamomile calms you and helps you relax, improving sleep. Sleeping well is a factor many people forget in weight loss: poorly slept nights increase hunger and the sweet craving the next day. This tea is a nighttime ritual that supports your diet.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm cup of chamomile tea with a cinnamon stick, dried chamomile flowers beside it, on a light wooden table, soft natural light, warm and calming, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Ginger, Lemon and Cinnamon Infusion",
 "hook": "A warming, fragrant infusion that heats the body and gives the metabolism a nudge.",
 "tempo": "10 min", "rende": "1 large cup", "kcal_base": 8, "livre": True,
 "ings": ["1 large cup of water", "several ginger slices", "1 cinnamon stick", "juice of ½ lemon"],
 "passos": [
   "In a small pot, boil the water with the ginger slices and the cinnamon stick for 5 minutes, over low heat.",
   "Turn off, cover and let it rest 3 more minutes.",
   "Strain, add the lemon juice and drink warm."],
 "dica": "Ginger and cinnamon have a mild warming effect, meaning they help the body spend a bit more energy. It is a warm, comforting infusion, with no sugar, that suits cold days and gives that extra support to the metabolism.",
 "prompt": "Square ultra-realistic overhead food photograph of a cup of ginger cinnamon lemon infusion with ginger slices and a cinnamon stick, lemon beside it, on a light wooden table, soft natural light, warm and cozy, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Mint Tea with Lemon",
 "hook": "Fresh and digestive, mint tea calms the stomach after meals — light and fragrant.",
 "tempo": "8 min", "rende": "1 cup", "kcal_base": 4, "livre": True,
 "ings": ["1 cup of water", "1 handful of fresh mint leaves (or 1 tea bag)", "juice of ½ lemon"],
 "passos": [
   "Boil the water and turn off the heat.",
   "Add the mint leaves, cover and let it steep for 5 minutes.",
   "Strain, add the lemon juice and drink warm or cold, preferably after meals."],
 "dica": "Mint helps digestion and reduces that heavy-stomach feeling after eating. A digestive, sugar-free tea after meals is a simple habit that helps you avoid nibbling on sweets right afterward.",
 "prompt": "Square ultra-realistic overhead food photograph of a glass cup of fresh mint tea with a lemon slice and mint leaves, on a light wooden table, soft natural light, fresh and clean, shallow depth of field, no text, no writing, 1:1 square.",
},
{
 "nome": "Fennel Tea",
 "hook": "Naturally soft and sweet, fennel calms the stomach and reduces gas — a comforting tea after eating.",
 "tempo": "8 min", "rende": "1 cup", "kcal_base": 4, "livre": True,
 "ings": ["1 cup of water", "1 teaspoon fennel seeds — or 1 tea bag"],
 "passos": [
   "Lightly crush the fennel seeds (this releases more aroma).",
   "Boil the water and turn off. Add the fennel, cover and let it steep for 5 minutes.",
   "Strain and drink warm, preferably after meals or at night."],
 "dica": "Fennel is known for calming the stomach and reducing gas and belly bloating. Naturally sweet, it needs no sugar. It is a digestive, comforting tea, great to finish a meal in a light way.",
 "prompt": "Square ultra-realistic overhead food photograph of a warm cup of fennel seed tea, fennel seeds scattered beside it, on a light wooden table, soft natural light, warm and calming, shallow depth of field, no text, no writing, 1:1 square.",
},
]
