# -*- coding: utf-8 -*-
"""BÔNUS 1 — DIETA VEGETARIANA: 8 receitas NOVAS (fotos 151-158). INGLÊS (mercado US).

Tradução literal de `receitas_bonus_veg.py`. Convenções em GLOSSARIO-TRADUCAO.md:
tratamento por "you", medidas caseiras americanas, tofu em OZ, forno em °F.
⛔ O campo `prompt` NÃO é replicado aqui: a foto é a mesma do PT (fotos/151-158).
Ovo-lacto vegetariano; proteína de leguminosas, tofu, ovos e queijos.
ALMOCOS -> tipo 'almoco' (metas 360/440/500/560 · 540/610/680/750), fotos 151-154
JANTARES -> tipo 'jantar' (metas 340/420/480/540 · 520/590/650/720), fotos 155-158
"""

ALMOCOS = [
{
 "nome": "Chickpea Bowl with Rice and Roasted Vegetables",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A colorful and generous bowl, with no meat at all — chickpeas carry you through the whole afternoon like a plate of protein.",
 "tempo": "35 min", "rende": "1 serving", "kcal_base": 500,
 "ings": ["1/2 cup cooked chickpeas (or canned, drained)", "4 tbsp cooked brown rice",
          "1 zucchini in pieces", "1/2 bell pepper in pieces", "1/2 red onion in pieces", "cherry tomatoes",
          "1 tsp olive oil", "juice of 1/2 lemon", "salt, pepper, turmeric and oregano to taste", "green leaves"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the zucchini, the bell pepper and the onion into similar bite-sized pieces.",
   "On a baking tray, spread the vegetables and the cherry tomatoes, season with salt, pepper, oregano and half of the olive oil, and mix with your hands.",
   "Bake for 20 to 25 minutes, until the vegetables are soft and golden at the edges. Turn them halfway through.",
   "In a pan, heat the rest of the olive oil and sauté the chickpeas with the turmeric, salt and pepper for 3 minutes, stirring, just to take in the flavor and brown lightly.",
   "Build the bowl: a bed of green leaves, the rice on one side, the chickpeas and the roasted vegetables on top. Drizzle with the lemon juice and serve."],
 "porcoes8": ["1/3 cup chickpeas · 3 tbsp rice · vegetables",
              "1/2 cup chickpeas · 4 tbsp rice · vegetables",
              "1/2 cup chickpeas · 5 tbsp rice · vegetables",
              "2/3 cup chickpeas · 5 tbsp rice · a little olive oil",
              "2/3 cup chickpeas · 5 tbsp rice · vegetables",
              "3/4 cup chickpeas · 6 tbsp rice · 1 tbsp nuts",
              "1 cup chickpeas · 7 tbsp rice · avocado",
              "1 cup chickpeas · 8 tbsp rice · avocado"],
 "dica": "Chickpeas combine protein and fiber that fill you up like a plate of meat, and together with brown rice they form a complete protein (the legume + grain pair that vegetarians use). Roasting the vegetables concentrates the flavor with no fat, keeping the plate light and full of taste.",
},
{
 "nome": "Lentil Pie with Mashed Potato",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "All the comfort of a browned shepherd's pie, with a seasoned lentil filling instead of meat — creamy and full of plant protein.",
 "tempo": "45 min", "rende": "2 servings", "kcal_base": 470,
 "ings": ["1 cup cooked lentils", "2 medium potatoes", "1 onion, chopped", "2 cloves of garlic, chopped",
          "1 tomato, chopped", "1 carrot, grated", "1 tsp olive oil",
          "2 tbsp grated cheese", "salt, pepper, turmeric and fresh herbs to taste"],
 "passos": [
   "Peel and cook the potatoes in boiling water for 15 minutes, until they are very soft. Drain and mash them with a fork, with a pinch of salt, until it turns into a smooth mash.",
   "In a pan, heat the olive oil and fry the onion and the garlic for 2 minutes. Add the grated carrot and the tomato and cook for 3 minutes.",
   "Add the cooked lentils, the turmeric, salt and pepper and cook for another 5 minutes, mashing the lentils a little with the spoon, until it makes a rich filling.",
   "In a baking dish, spread half of the mash on the bottom, the lentil filling in the middle and the rest of the mash on top. Sprinkle the grated cheese.",
   "Bake at medium-high heat (400 °F) for 15 minutes, until the surface is golden. Sprinkle fresh herbs and serve."],
 "porcoes8": ["1/2 serving · salad",
              "1 serving · salad",
              "1 serving · salad",
              "1 serving · 1 more tbsp cheese · salad",
              "1 serving · extra lentils · salad",
              "1 large serving · salad",
              "1 large serving · extra lentils · salad",
              "double serving · salad"],
 "dica": "Lentils are rich in iron, fiber and plant protein, a trio that fills you up a lot — in the pie, they replace meat with room to spare. With the mashed potato in the right measure and a little browned cheese, it is a comforting plate that tricks the craving for heavy food.",
},
{
 "nome": "Vegetable Frittata",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A tall, fluffy omelette, baked with colorful vegetables and cheese — egg protein in a dish you cut into slices and everyone likes.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 420,
 "ings": ["5 eggs", "1 zucchini in small cubes", "1/2 bell pepper, chopped", "1 tomato, chopped", "a handful of spinach",
          "3 tbsp white cheese in cubes", "1 tsp olive oil",
          "chives, salt and pepper to taste", "green leaves for the salad"],
 "passos": [
   "Turn the oven to medium heat (350 °F). In an oven-safe pan, heat the olive oil and sauté the zucchini and the bell pepper for 4 minutes, stirring, until they soften.",
   "Add the spinach and stir for 1 minute, just until it wilts (the leaves go soft). Spread the vegetables around the pan.",
   "In a bowl, beat the eggs with salt and pepper. Add the tomato, the cheese and the chives and mix.",
   "Pour the eggs over the vegetables in the pan and leave it 2 minutes on the heat, just to set the edge.",
   "Put the pan in the oven for 15 minutes, until the frittata puffs up, sets in the center and browns on top. Cut it into slices and serve with a green salad."],
 "porcoes8": ["1 slice · salad",
              "1 large slice · salad",
              "1 large slice · salad · 2 tbsp rice",
              "2 slices · salad · 2 tbsp rice",
              "2 slices · salad · 3 tbsp rice",
              "2 large slices · salad · 3 tbsp rice",
              "2 large slices · salad · 4 tbsp rice",
              "3 slices · salad · 4 tbsp rice"],
 "dica": "Eggs are a complete and very filling protein, ideal for a vegetarian lunch with no legumes. Baked with vegetables and a little cheese, the frittata goes a long way, keeps well in the fridge and kills hunger in a light and nourishing way.",
},
{
 "nome": "Vegetarian Bean and Chickpea Chili",
 "tag": "Vegetarian lunch", "num_label": "Bonus · Vegetarian",
 "hook": "A spicy, hearty stew with no meat at all — proof that vegetarian food also fills the plate and your belly.",
 "tempo": "30 min", "rende": "3 servings", "kcal_base": 460,
 "ings": ["1 cup cooked red beans", "1 cup cooked chickpeas", "1/2 cup corn",
          "1 onion, chopped", "2 cloves of garlic, chopped", "1 bell pepper, chopped", "2 tomatoes, chopped (or tomato sauce)",
          "1 tsp olive oil", "1 tsp cumin", "salt, pepper and paprika to taste",
          "rice to serve"],
 "passos": [
   "Heat the olive oil in a pot over medium heat. Fry the onion, the garlic and the bell pepper for 3 minutes, stirring, until they soften.",
   "Add the cumin, the paprika, salt and pepper and stir for 30 seconds, so the spices release their aroma.",
   "Add the chopped tomatoes and cook for 5 minutes, until they break down into a sauce.",
   "Add the red beans, the chickpeas and the corn. If it gets dry, add half a cup of water.",
   "Turn the heat down and cook for 15 minutes, stirring now and then, until it thickens into a creamy stew. Serve with a little rice."],
 "porcoes8": ["1/2 serving · 3 tbsp rice",
              "1 serving · 4 tbsp rice",
              "1 serving · 5 tbsp rice",
              "1 serving · 5 tbsp rice · avocado",
              "1 serving · 5 tbsp rice",
              "1 large serving · 6 tbsp rice",
              "large serving · 7 tbsp rice · avocado",
              "double serving · 8 tbsp rice"],
 "dica": "Beans and chickpeas together form a very complete plant protein, with a mountain of fiber that fills you up for hours. Served with rice, it closes the complete protein. It is a cheap plate that lasts several days and proves you can eat well with no meat.",
},
]

JANTARES = [
{
 "nome": "Hearty Lentil Soup with Vegetables",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "A soup that is a real meal: the lentils make the broth rich and full of protein, warming and filling you up on a cold night.",
 "tempo": "40 min", "rende": "3 servings", "kcal_base": 380,
 "ings": ["1 cup raw lentils", "1 potato in cubes", "1 carrot in cubes", "1 celery stalk, chopped (optional)",
          "1 tomato, chopped", "1 onion, chopped", "2 cloves of garlic, chopped", "1 tsp olive oil",
          "salt, pepper, turmeric and fresh herbs to taste", "5 cups of water"],
 "passos": [
   "Wash the lentils. In a pot, heat the olive oil and fry the onion and the garlic for 2 minutes, stirring.",
   "Add the tomato, the carrot, the potato and the celery and stir for 2 minutes.",
   "Add the lentils, the turmeric, salt, pepper and the water. Bring it to a boil.",
   "Turn the heat down and cook for 25 to 30 minutes, stirring now and then, until the lentils and the vegetables are very soft and the broth has body. If it dries up too much, add a little hot water.",
   "Check the salt, sprinkle fresh herbs and serve very hot."],
 "porcoes8": ["1 ladle · no bread",
              "2 ladles · no bread",
              "2 ladles · 1 slice bread",
              "2 ladles · 1 slice bread",
              "2 ladles · 1 slice bread",
              "3 ladles · 1 slice bread",
              "3 ladles · 2 slices bread",
              "3 large ladles · 2 slices bread"],
 "dica": "Lentils are one of the legumes richest in protein and iron, and in a soup they make the broth hearty enough to be a complete dinner with no meat. All that liquid and the vegetables fill your stomach with few calories — light, warm and comforting.",
},
{
 "nome": "Grilled Tofu with Vegetables and Rice",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "The golden tofu takes in the seasoning and turns out delicious — a meat-free option that really fills you up and is light for the evening.",
 "tempo": "25 min", "rende": "1 serving", "kcal_base": 420,
 "ings": ["5 oz firm tofu in slices", "4 tbsp cooked brown rice", "1 cup of broccoli and carrot",
          "1 tbsp light soy sauce", "1 clove of garlic, chopped", "1 tsp olive oil",
          "grated ginger (optional)", "salt and pepper to taste"],
 "passos": [
   "Dry the tofu slices well with paper towel, pressing lightly — the drier it is, the better it browns.",
   "Season the tofu with the soy sauce, the garlic and the ginger. Let it take in the flavor for 5 minutes.",
   "Heat a nonstick pan with half of the olive oil over medium-high heat. Grill the tofu slices for 3 to 4 minutes on each side, without moving them, until a golden crust forms. Take them out and set them aside.",
   "Cut the broccoli into florets and the carrot into rounds. In the same pan, with the rest of the olive oil, sauté the vegetables for 4 minutes, until they are tender but still firm.",
   "Build the plate with the brown rice, the vegetables and the grilled tofu on top. Drizzle with a little more soy sauce if you like."],
 "porcoes8": ["4 oz tofu · 3 tbsp rice · vegetables",
              "5 oz tofu · 4 tbsp rice · vegetables",
              "5 oz tofu · 5 tbsp rice · vegetables",
              "6 oz tofu · 5 tbsp rice · a little olive oil",
              "6 oz tofu · 5 tbsp rice · vegetables",
              "7 oz tofu · 6 tbsp rice · vegetables",
              "8 oz tofu · 7 tbsp rice · 1 tbsp nuts",
              "9 oz tofu · 8 tbsp rice · nuts"],
 "dica": "Tofu is made from soy and brings plant protein with little fat, making it one of the best options for a change from meat. Dried well and grilled, it gains texture and takes in the seasoning. With vegetables and brown rice, it becomes a complete, light dinner full of fiber.",
},
{
 "nome": "Eggplant Stuffed with Chickpeas and Cheese",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "The eggplant itself becomes the bowl, stuffed with seasoned chickpeas and browned with cheese — pretty, generous and meat-free.",
 "tempo": "40 min", "rende": "2 servings", "kcal_base": 400,
 "ings": ["1 large eggplant", "1 cup cooked chickpeas", "1 onion, chopped", "1 clove of garlic, chopped",
          "1 tomato, chopped", "1 tsp olive oil", "2 tbsp grated low-fat cheese",
          "salt, pepper, cumin and parsley to taste"],
 "passos": [
   "Turn the oven to medium-high heat (400 °F). Cut the eggplant in half lengthwise. With a spoon, take out part of the middle, making two 'boats'. Chop the part you took out.",
   "Put the boats on a baking tray, drizzle with a little olive oil and bake for 10 minutes, just to soften them.",
   "In a pan, heat the rest of the olive oil and fry the onion and the garlic for 2 minutes. Add the tomato, the chopped eggplant middle, the chickpeas, the cumin, salt and pepper and cook for 6 minutes, mashing the chickpeas a little, until it makes a soft filling.",
   "Fill the boats with the chickpea mixture and sprinkle the grated cheese on top.",
   "Put it back in the oven for 15 minutes, until the top browns (the cheese melts and goes golden). Sprinkle parsley and serve."],
 "porcoes8": ["1/2 eggplant · salad",
              "1 stuffed eggplant · salad",
              "1 eggplant · 2 tbsp rice",
              "1 eggplant · extra chickpeas · salad",
              "1 eggplant · extra chickpeas · 2 tbsp rice",
              "1 large eggplant · 3 tbsp rice",
              "1 eggplant · double chickpeas · 4 tbsp rice",
              "eggplant + extra portion · 4 tbsp rice"],
 "dica": "Eggplant has a lot of water and fiber, so it fills the plate with very few calories. The chickpeas bring the plant protein that replaces meat, and a little browned cheese kills the craving for a cheesy dish. A pretty, generous and light vegetarian dinner.",
},
{
 "nome": "Chickpea Curry with Rice",
 "tag": "Vegetarian dinner", "num_label": "Bonus · Vegetarian",
 "hook": "A golden, fragrant sauce wrapping around the chickpeas — creamy with light coconut milk, it is a vegetarian dinner full of flavor.",
 "tempo": "30 min", "rende": "2 servings", "kcal_base": 440,
 "ings": ["2 cups cooked chickpeas", "1 onion, chopped", "2 cloves of garlic, chopped", "1 tomato, chopped",
          "1 tsp curry powder", "1/2 cup light coconut milk", "a handful of spinach (optional)",
          "1 tsp olive oil", "salt, pepper and coriander to taste", "rice to serve"],
 "passos": [
   "Heat the olive oil in a pot over medium heat and fry the onion and the garlic for 2 minutes, stirring.",
   "Add the curry and stir for 30 seconds, so the spice releases its aroma. Add the tomato and cook for 3 minutes, until it breaks down.",
   "Add the chickpeas and the light coconut milk and mix. Season with salt and pepper.",
   "Cook over low heat for 10 minutes, stirring now and then, until the sauce thickens. If you like, add the spinach in the last 2 minutes, just until it wilts.",
   "Sprinkle coriander and serve over a portion of rice."],
 "porcoes8": ["2/3 cup chickpeas · 3 tbsp rice",
              "1 cup chickpeas · 4 tbsp rice",
              "1 cup chickpeas · 5 tbsp rice",
              "1 cup chickpeas · 5 tbsp rice · spinach",
              "1 cup chickpeas · 5 tbsp rice",
              "1 1/2 cups chickpeas · 6 tbsp rice",
              "1 1/2 cups chickpeas · 7 tbsp rice",
              "2 cups chickpeas · 8 tbsp rice"],
 "dica": "Chickpeas are rich in protein and fiber, and in a curry they turn creamy and full of flavor. Light coconut milk gives the sauce its richness with far less fat than cream. With rice, it forms a complete protein — a comforting and nourishing vegetarian dinner.",
},
]
