# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). ITALIANO.

Traducao literal de `receitas_sobremesa_en.py`. Convencoes em GLOSSARIO-TRADUCAO.md.
⛔ METRICO: `1 cup oats`->`90 g` · `1 1/2 cups oats`->`135 g` · `2 cups oats`->
   `180 g` · `2 cups milk`->`480 ml` · `3.5 oz`->`100 g` · `12 oz`->`350 g` ·
   `350 °F`->`180 °C`.
⛔ `unflavored gelatin` e' `gelatina neutra in polvere` — nao "colla di pesce",
   que e' a versao in fogli e nao se mede a cucchiaio.
⛔ O campo `prompt` NAO e' replicado: a foto e' a mesma (fotos/NNN, sem texto).
"""

RECEITAS = [
{
 "nome": "Torta al cioccolato fit senza zucchero",
 "hook": "Soffice, umida e davvero cioccolatosa — la torta che toglie la voglia di dolce senza un pizzico di zucchero, fatta con cacao vero.",
 "tempo": "40 min", "rende": "8 fette", "kcal_base": 150,
 "ings": ["3 uova", "1 banana molto matura, schiacciata",
          "4 cucchiai di cacao amaro in polvere 100 % (senza zucchero)",
          "5 cucchiai di avena frullata fino a farina (o farina integrale)",
          "dolcificante da forno q.b. (quello adatto alla cottura) — o 2 cucchiai di miele",
          "120 ml di latte (o bevanda vegetale)", "1 cucchiaio di olio",
          "1 cucchiaino di lievito per dolci"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Ungi con un po' di olio uno stampo piccolo e spolveralo con del cacao, così la torta non attacca.",
   "In una ciotola, sbatti le uova con il dolcificante (o il miele) con una forchetta o una frusta, per 1 minuto, finché non fa la schiuma.",
   "Aggiungi la banana schiacciata, il latte e l'olio e mescola bene.",
   "Aggiungi il cacao in polvere e l'avena frullata (o la farina) e mescola finché non è un impasto liscio, senza grumi asciutti.",
   "Per ultimo, aggiungi il lievito e mescola appena, giusto per amalgamare (mescolare troppo dopo il lievito rende la torta pesante).",
   "Versa nello stampo e inforna per 30 minuti. Per capire se è cotta, infila uno stecchino al centro: se esce pulito, la torta è pronta.",
   "Falla intiepidire un po' prima di sformarla e tagliarla. È ottima con frutti di bosco sopra."],
 "porcoes8": ["1 fetta sottile",
              "1 fetta",
              "1 fetta · frutti di bosco",
              "1 fetta · 1 cucchiaio di yogurt",
              "1 fetta",
              "1 fetta media",
              "1 fetta · frutti di bosco",
              "1 fetta grande · frutti di bosco"],
 "dica": "Il cacao puro ti dà tutto il sapore del cioccolato senza lo zucchero e i grassi delle bevande al cacao. La banana dolcifica in modo naturale e mantiene la torta umida, l'avena porta fibre e le uova proteine. È la prova che puoi mangiare la torta al cioccolato e continuare a dimagrire, purché la fetta sia della misura giusta.",
},
{
 "nome": "Mousse al cioccolato e avocado",
 "hook": "Cremosa come la mousse tradizionale, ma il segreto è l'avocado — nessuno se ne accorge, e non ha panna né zucchero.",
 "tempo": "10 min + frigo", "rende": "2 bicchieri", "kcal_base": 170,
 "ings": ["1 avocado maturo (o ½ avocado grande)",
          "3 cucchiai di cacao amaro in polvere 100 %",
          "dolcificante da forno q.b. — o 2 cucchiai di miele",
          "3 cucchiai di latte (o bevanda vegetale)", "1 pizzico di cannella",
          "1 pizzico di sale",
          "cioccolato 70 % grattugiato per decorare (facoltativo)"],
 "passos": [
   "Taglia l'avocado a metà, togli il nocciolo e preleva la polpa con un cucchiaio. Usa solo la parte verde e ben morbida.",
   "Metti la polpa di avocado nel frullatore o nel bicchiere del frullatore a immersione, insieme al cacao, al dolcificante (o miele), al latte, alla cannella e al sale.",
   "Frulla alla massima velocità finché non diventa una crema liscia e lucida, senza grumi. Se è troppo densa, aggiungi ancora un po' di latte.",
   "Assaggia e regola la dolcezza secondo il tuo gusto.",
   "Dividila in due bicchieri e mettila in frigo per almeno 30 minuti, per farla rassodare e raffreddare. Servi con il cioccolato grattugiato sopra."],
 "porcoes8": ["½ bicchiere piccolo",
              "1 bicchiere piccolo",
              "1 bicchiere",
              "1 bicchiere · cioccolato grattugiato",
              "1 bicchiere",
              "1 bicchiere medio",
              "1 bicchiere · cioccolato grattugiato",
              "1 bicchiere grande · cioccolato grattugiato"],
 "dica": "L'avocado dà la cremosità della mousse con grassi buoni invece della panna, ed è molto saziante. Il cacao puro porta il sapore del cioccolato senza zucchero. È un dolce ricco e appagante che, in una porzione piccola, rientra facilmente nella tua dieta.",
},
{
 "nome": "Palline di cacao fit",
 "hook": "Il dolcetto delle feste in una versione senza zucchero e senza latte condensato — arrotolato, cioccolatoso e della misura giusta per la voglia.",
 "tempo": "20 min + frigo", "rende": "10 palline", "kcal_base": 130,
 "ings": ["6 datteri denocciolati (quella frutta secca dolcissima)",
          "3 cucchiai di cacao amaro in polvere 100 %",
          "2 cucchiai di latte (o bevanda vegetale)",
          "1 cucchiaio di burro di arachidi",
          "cacao in polvere extra per rotolarle", "1 pizzico di sale"],
 "passos": [
   "Metti i datteri in ammollo in acqua tiepida per 10 minuti, così si ammorbidiscono. Scolali.",
   "Nel bicchiere del frullatore a immersione o nel frullatore, frulla i datteri con il cacao, il latte, il burro di arachidi e il sale, finché non diventa un impasto denso e omogeneo (ben amalgamato). Se serve, fermati e spingi l'impasto verso il centro con un cucchiaio.",
   "L'impasto deve essere abbastanza sodo da poter essere arrotolato. Se è morbido, mettilo in frigo per 20 minuti.",
   "Con le mani leggermente umide, prendi piccole porzioni e forma delle palline grandi come una noce.",
   "Rotola ogni pallina nel cacao in polvere per rivestirla. Conservale in frigo e servile fredde."],
 "porcoes8": ["1 pallina",
              "1 o 2 palline",
              "2 palline",
              "2 palline",
              "2 palline",
              "2 o 3 palline",
              "3 palline",
              "3 palline"],
 "dica": "I datteri sostituiscono lo zucchero e il latte condensato con dolcezza naturale e tante fibre, che tengono a bada la voglia di dolce. Il cacao puro dà il sapore del cioccolato e il burro di arachidi la cremosità. Una o due pallline tolgono la voglia senza far saltare le tue calorie.",
},
{
 "nome": "Mug cake al cioccolato",
 "hook": "Voglia di dolce la sera? In tre minuti, nel microonde, hai una tortina calda al cioccolato solo per te.",
 "tempo": "5 min", "rende": "1 tazza", "kcal_base": 190,
 "ings": ["1 uovo", "2 cucchiai di avena frullata fino a farina",
          "1 cucchiaio di cacao amaro in polvere 100 %",
          "dolcificante da forno q.b. — o 1 cucchiaio di miele",
          "2 cucchiai di latte", "½ cucchiaino di lievito per dolci",
          "1 pizzico di sale"],
 "passos": [
   "In una tazza grande (adatta al microonde), rompi l'uovo e sbattilo con la forchetta.",
   "Aggiungi l'avena frullata, il cacao, il dolcificante (o miele), il latte e il sale. Mescola bene, finché non è un impasto liscio, senza parti asciutte sui bordi.",
   "Per ultimo, aggiungi il lievito e mescola appena.",
   "Metti la tazza nel microonde alla massima potenza per 1 minuto e 30 secondi - 2 minuti. La tortina si gonfia e si rassoda; se al centro è ancora umida, dalle altri 20 secondi.",
   "Attenta, la tazza esce bollente. Falla intiepidire per 1 minuto e mangiala direttamente dalla tazza. È ottima con la frutta sopra."],
 "porcoes8": ["½ tazza",
              "1 tazza piccola",
              "1 tazza",
              "1 tazza · frutta",
              "1 tazza",
              "1 tazza",
              "1 tazza · frutta",
              "1 tazza · frutta · 1 cucchiaio di burro di arachidi"],
 "dica": "Fatta sul momento e in una porzione da una tazza sola, questa tortina controlla in modo naturale quanto ne mangi — non resta una torta intera sul tavolo a tentarti. Con avena, uovo e cacao puro, è dolce, calda e avvolgente senza zucchero, ideale per una voglia serale.",
},
{
 "nome": "Mousse di yogurt e fragole",
 "hook": "Rosa, vellutata e rinfrescante — una mousse di fragole che vuole solo tre ingredienti e nessuno zucchero.",
 "tempo": "10 min + frigo", "rende": "3 bicchieri", "kcal_base": 120,
 "ings": ["300 g di fragole (fresche o congelate)",
          "1 vasetto di yogurt naturale senza zucchero (circa 170 g)",
          "1 cucchiaio di gelatina neutra in polvere",
          "dolcificante q.b. — o 1 cucchiaio di miele",
          "3 cucchiai di acqua calda", "fragole a pezzetti per decorare"],
 "passos": [
   "Lava le fragole e togli le foglioline verdi. Tienine da parte alcune per decorare.",
   "In una tazza, sciogli la gelatina neutra nell'acqua calda, mescolando bene finché non è limpida, senza granelli. Falla intiepidire un po'.",
   "Nel frullatore, frulla le fragole con lo yogurt e il dolcificante (o miele) finché non diventa una crema rosa e liscia.",
   "Con il frullatore in funzione a bassa velocità, aggiungi la gelatina sciolta e frulla per altri 30 secondi, giusto per amalgamarla.",
   "Dividila nei bicchieri e mettila in frigo per almeno 2 ore, finché non si rassoda. Servi con le fragole a pezzetti sopra."],
 "porcoes8": ["½ bicchiere",
              "1 bicchiere piccolo",
              "1 bicchiere",
              "1 bicchiere · fragole",
              "1 bicchiere",
              "1 bicchiere medio",
              "1 bicchiere · fragole",
              "1 bicchiere grande · fragole"],
 "dica": "Le fragole sono dolci e piene di vitamina C con pochissime calorie, e lo yogurt naturale aggiunge proteine e cremosità senza zucchero. La gelatina dà alla mousse la sua consistenza senza panna. Un dolce leggero, bello e rinfrescante che soddisfa la voglia di qualcosa di dolce.",
},
{
 "nome": "Nice cream cremosa alla banana",
 "hook": "Un gelato vero, cremoso e freddo, fatto solo di banane — niente zucchero, niente latte, niente gelatiera.",
 "tempo": "5 min + freezer", "rende": "2 porzioni", "kcal_base": 120,
 "ings": ["3 banane mature",
          "1 cucchiaio di cacao amaro in polvere 100 % OPPURE 1 manciata di frutti di bosco (facoltativo, per dare sapore)",
          "1 pizzico di cannella",
          "1 cucchiaino di burro di arachidi (facoltativo)"],
 "passos": [
   "Sbuccia le banane, tagliale a rondelle e mettile in un sacchetto o in un contenitore. Congelale per almeno 3 ore, finché non sono ben dure.",
   "Tira fuori le rondelle congelate e mettile in un frullatore potente o nel bicchiere del frullatore a immersione.",
   "Frulla alla massima velocità. All'inizio si sbriciola; continua a frullare (fermandoti a spingere la banana verso il centro) finché non diventa una crema liscia, proprio come il gelato fatto in gelatiera.",
   "Se vuoi darle sapore, aggiungi il cacao o i frutti di bosco e frulla ancora un po'.",
   "Servila subito, bella cremosa, con un pizzico di cannella — oppure mettila in freezer per 1 ora per renderla più soda, come il gelato in vaschetta."],
 "porcoes8": ["½ porzione",
              "1 porzione piccola",
              "1 porzione",
              "1 porzione · 1 cucchiaio di burro di arachidi",
              "1 porzione",
              "1 porzione media",
              "1 porzione · frutta",
              "1 porzione grande · frutta · burro di arachidi"],
 "dica": "Congelata e frullata, la banana libera il suo zucchero naturale e diventa una crema identica al gelato, senza bisogno di zucchero, latte o panna. È dolce, fredda e appagante, con le fibre e il potassio della frutta — il dolce perfetto per le giornate calde, senza sensi di colpa.",
},
{
 "nome": "Budino di latte fit",
 "hook": "Lo stesso budino cremoso, con quel caramello dorato — solo senza zucchero e molto più leggero, fatto con latte e uova.",
 "tempo": "50 min", "rende": "6 fette", "kcal_base": 130,
 "ings": ["3 uova", "480 ml di latte scremato (o bevanda vegetale)",
          "dolcificante da forno q.b. (quello adatto alla cottura)",
          "1 cucchiaino di estratto di vaniglia",
          "dolcificante che caramella (facoltativo, per la salsa)",
          "acqua calda per il bagnomaria"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Se vuoi il caramello, sciogli un po' di dolcificante che caramella in un pentolino e distribuiscilo sul fondo (oppure salta il caramello).",
   "Nel frullatore, frulla le uova, il latte, il dolcificante e la vaniglia per 1 minuto, finché non è ben amalgamato.",
   "Versa il composto nello stampo.",
   "Metti lo stampo dentro una teglia più grande e riempi la teglia di acqua calda fino a metà altezza dello stampo (questo è il bagnomaria: l'acqua fa cuocere il budino in modo uniforme e lo mantiene cremoso).",
   "Inforna per 40 minuti, finché non si rassoda ma trema ancora leggermente al centro. Fallo raffreddare e poi mettilo in frigo per 3 ore prima di sformarlo."],
 "porcoes8": ["1 fetta sottile",
              "1 fetta",
              "1 fetta",
              "1 fetta · frutta",
              "1 fetta",
              "1 fetta media",
              "1 fetta · frutta",
              "1 fetta grande · frutta"],
 "dica": "Sostituendo il latte condensato e lo zucchero con latte scremato e dolcificante, il budino mantiene la sua cremosità e il sapore con una frazione delle calorie. Le uova e il latte portano anche proteine. In una fetta piccola, è un dolce classico che rientra nella tua dieta.",
},
{
 "nome": "Biscotti di avena e banana",
 "hook": "Due ingredienti, una ciotola e venti minuti: biscottini morbidi e appena dolci, senza zucchero e senza farina bianca.",
 "tempo": "20 min", "rende": "12 biscotti", "kcal_base": 110,
 "ings": ["2 banane molto mature", "135 g di fiocchi d'avena",
          "1 pizzico di cannella",
          "1 cucchiaio di uvetta o gocce di cioccolato 70 % (facoltativo)",
          "1 pizzico di sale"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Rivesti una teglia con carta da forno.",
   "In una ciotola, schiaccia bene le banane con la forchetta, finché non diventano una purea senza grumi grossi.",
   "Aggiungi l'avena, la cannella, il sale e, se ti va, l'uvetta o il cioccolato tritato. Mescola finché non forma un impasto appiccicoso.",
   "Con un cucchiaio, metti piccole porzioni sulla teglia e appiattisci ciascuna con il dorso del cucchiaio, dandole la forma di un biscotto.",
   "Inforna per 12-15 minuti, finché i bordi non sono dorati e sodi. Falli raffreddare sulla teglia (si compattano raffreddandosi) e servi."],
 "porcoes8": ["1 biscotto",
              "2 biscotti",
              "2 biscotti",
              "2 biscotti · frutta",
              "2 biscotti",
              "3 biscotti",
              "3 biscotti",
              "3 o 4 biscotti"],
 "dica": "La banana matura dolcifica e lega senza bisogno di zucchero o farina bianca, e l'avena porta fibre che saziano. Sono biscotti naturali, ottimi per uno spuntino o come dolce, che tolgono la voglia di dolce in modo leggero — ma conta quanti ne mangi, perché è facile esagerare.",
},
{
 "nome": "Mela al forno con cannella e noci",
 "hook": "La mela diventa morbida e profumata di cannella, con un ripieno croccante di noci — un dolce caldo che consola come una torta, senza la base.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 130,
 "ings": ["2 mele", "cannella in polvere q.b.",
          "1 cucchiaio di noci tritate (o altra frutta secca)",
          "1 cucchiaio di fiocchi d'avena",
          "1 cucchiaino di miele (facoltativo)",
          "1 pizzico di chiodi di garofano in polvere (facoltativo)"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Lava le mele e, con un coltello, togli il torsolo dal centro (la parte con i semi), formando un incavo, senza arrivare fino in fondo.",
   "In una ciotolina, mescola le noci tritate, l'avena, la cannella e, se ti va, il miele e i chiodi di garofano.",
   "Riempi l'incavo di ogni mela con questo composto, premendo leggermente.",
   "Metti le mele su una teglia con un dito d'acqua sul fondo (così non si seccano) e spolvera altra cannella sopra.",
   "Inforna per 25-30 minuti, finché la mela non è morbidissima (la forchetta entra facilmente) e il ripieno è dorato. Servi calda, da sola o con un cucchiaio di yogurt naturale."],
 "porcoes8": ["½ mela",
              "1 mela",
              "1 mela",
              "1 mela · 1 cucchiaio di yogurt",
              "1 mela",
              "1 mela · noci extra",
              "1 mela · yogurt",
              "2 mele · yogurt"],
 "dica": "Cuocere la mela al forno concentra la dolcezza naturale della frutta, così diventa dolce senza zucchero. La cannella esalta il sapore e aiuta a controllare la voglia di dolce, e le noci portano grassi buoni e croccantezza. È la coccola di una torta di mele con una frazione delle calorie.",
},
{
 "nome": "Gelatina di frutta fatta in casa",
 "hook": "Colorata, tremolante e rinfrescante, con pezzi di frutta vera dentro — il dolce più leggero che ci sia.",
 "tempo": "10 min + frigo", "rende": "4 bicchieri", "kcal_base": 70,
 "ings": ["1 cucchiaio di gelatina neutra in polvere",
          "480 ml di succo di frutta naturale senza zucchero (arancia, uva o fragola)",
          "120 ml di acqua",
          "150 g di frutta a pezzetti (fragola, kiwi, mango o uva)",
          "dolcificante q.b. (facoltativo)"],
 "passos": [
   "In un pentolino, metti l'acqua e spolvera sopra la gelatina neutra. Lasciala riposare 2 minuti (la gelatina si gonfia, ed è quello che si chiama idratazione).",
   "Metti sul fuoco basso e mescola per 1 minuto, giusto finché la gelatina non si scioglie completamente, senza far bollire. Spegni.",
   "Aggiungi il succo di frutta naturale (e il dolcificante, se ti va) e mescola bene.",
   "Metti la frutta a pezzetti sul fondo dei bicchieri o di una pirofila e versaci sopra il liquido.",
   "Metti in frigo per almeno 4 ore, finché non è soda. Servi ben fredda."],
 "porcoes8": ["½ bicchiere",
              "1 bicchiere piccolo",
              "1 bicchiere",
              "1 bicchiere · frutta extra",
              "1 bicchiere",
              "1 bicchiere medio",
              "1 bicchiere · frutta",
              "1 bicchiere grande · frutta"],
 "dica": "Fatta con succo naturale invece della polvere piena di zucchero e coloranti, la gelatina fatta in casa non ha praticamente calorie e porta comunque pezzi di frutta vera. È il dolce ideale per quando vuoi qualcosa di dolce e freddo senza pesare per niente sulla tua dieta.",
},
{
 "nome": "Barretta di avena con frutta secca",
 "hook": "La barretta ai cereali fatta in casa, morbida e appena dolce, senza gli zuccheri e gli sciroppi di quelle del supermercato — perfetta per la borsa.",
 "tempo": "30 min", "rende": "8 barrette", "kcal_base": 150,
 "ings": ["180 g di fiocchi d'avena", "2 banane mature, schiacciate",
          "3 cucchiai di frutta secca tritata (uvetta, albicocche o datteri)",
          "2 cucchiai di frutta a guscio tritata",
          "1 cucchiaio di miele (facoltativo)",
          "1 pizzico di cannella e sale"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Rivesti uno stampo rettangolare piccolo con carta da forno.",
   "In una ciotola, schiaccia bene le banane finché non diventano una purea.",
   "Aggiungi l'avena, la frutta secca tritata, la frutta a guscio, la cannella, il sale e, se ti va, il miele. Mescola finché non forma un impasto appiccicoso e omogeneo.",
   "Versa l'impasto nello stampo e pressalo bene con il dorso di un cucchiaio, lasciando uno strato compatto e uniforme (più lo pressi, meno la barretta si sbriciola).",
   "Inforna per 20 minuti, finché i bordi non sono dorati. Falla raffreddare completamente nello stampo prima di tagliarla a barrette (se la tagli calda, si sbriciola)."],
 "porcoes8": ["1 barretta",
              "1 barretta",
              "1 barretta",
              "1 barretta · frutta",
              "1 barretta",
              "1 o 2 barrette",
              "2 barrette",
              "2 barrette"],
 "dica": "Le barrette del supermercato hanno di solito più zucchero e sciroppo di una caramella. Fatta in casa con avena, banana e frutta secca, la barretta dolcifica in modo naturale e porta fibre ed energia che tengono a bada la fame. Ottima per uno spuntino o come dolce pratico, ma mangiane una alla volta.",
},
{
 "nome": "Yogurt ghiacciato a scaglie con frutti di bosco",
 "hook": "Una lastra croccante di yogurt ghiacciato cosparsa di frutta, che spezzi in pezzi — bella, divertente e senza zucchero.",
 "tempo": "5 min + freezer", "rende": "4 porzioni", "kcal_base": 100,
 "ings": ["1 vaschetta grande di yogurt greco naturale senza zucchero (circa 350 g)",
          "140 g di frutti di bosco (fragola, mirtillo, lampone)",
          "1 cucchiaio di miele (facoltativo)",
          "1 cucchiaio di frutta a guscio tritata (facoltativo)",
          "cioccolato 70 % grattugiato (facoltativo)"],
 "passos": [
   "Rivesti una teglia o una pirofila bassa con carta da forno.",
   "In una ciotola, mescola lo yogurt greco con il miele (se lo usi), finché non è ben liscio.",
   "Stendi lo yogurt sulla carta da forno, formando uno strato spesso circa mezzo dito.",
   "Cospargi sopra i frutti di bosco (taglia le fragole), la frutta a guscio e il cioccolato grattugiato, distribuendoli su tutta la superficie.",
   "Congela per 3-4 ore, finché non è ben duro. Spezza o taglia in pezzi irregolari e servi subito (si scioglie in fretta). Conserva il resto in freezer."],
 "porcoes8": ["1 pezzo piccolo",
              "1 pezzo",
              "1 o 2 pezzi",
              "2 pezzi",
              "2 pezzi",
              "2 pezzi",
              "2 o 3 pezzi",
              "3 pezzi"],
 "dica": "Lo yogurt greco porta proteine e cremosità senza zucchero, e congelato diventa uno sfizio freddo e croccante. I frutti di bosco dolcificano in modo naturale e lo riempiono di antiossidanti. È un dolce rinfrescante e leggero, ottimo per l'estate e per la voglia di sgranocchiare qualcosa di dolce.",
},
{
 "nome": "Tartufini al cioccolato fit",
 "hook": "Piccoli, intensi e cioccolatosi — il tartufino che si scioglie in bocca senza un grammo di zucchero, per i momenti di voglia forte.",
 "tempo": "20 min + frigo", "rende": "10 tartufini", "kcal_base": 120,
 "ings": ["100 g di cioccolato 70 % (o più fondente)",
          "4 cucchiai di latte caldo (o bevanda vegetale)",
          "2 cucchiai di cocco grattugiato senza zucchero",
          "cacao in polvere 100 % per rotolarli", "1 pizzico di sale"],
 "passos": [
   "Trita il cioccolato 70 % a pezzetti piccoli e mettilo in una ciotola.",
   "Scalda il latte finché non è quasi al bollore e versalo sul cioccolato. Aspetta 1 minuto e mescola finché il cioccolato non si scioglie completamente, diventando una crema liscia e lucida (questa è la ganache).",
   "Aggiungi il cocco grattugiato e il sale e mescola. Metti in frigo per 1 ora, finché il composto non è abbastanza sodo da essere arrotolato.",
   "Con le mani, prendi piccole porzioni e forma delle palline grandi come un'oliva grossa.",
   "Rotola ogni tartufino nel cacao in polvere per rivestirlo. Conservali in frigo e servili freddi."],
 "porcoes8": ["1 tartufino",
              "1 tartufino",
              "1 o 2 tartufini",
              "2 tartufini",
              "2 tartufini",
              "2 tartufini",
              "2 o 3 tartufini",
              "3 tartufini"],
 "dica": "Il cioccolato al 70 % o più fondente ha poco zucchero e tanto cacao, che è ricco di antiossidanti. In un tartufino piccolo, soddisfa la voglia intensa di cioccolato con molto meno zucchero di una caramella normale. Uno o due risolvono la voglia senza sabotare la tua dieta.",
},
{
 "nome": "Torta di carote fit con glassa al cacao",
 "hook": "La soffice torta di carote della tua infanzia, con una glassa al cioccolato — senza zucchero, ma con tutto il calore e il sapore.",
 "tempo": "45 min", "rende": "8 fette", "kcal_base": 160,
 "ings": ["2 carote medie, a pezzetti", "3 uova", "3 cucchiai di olio",
          "dolcificante da forno q.b. (quello adatto alla cottura)",
          "135 g di avena frullata fino a farina (o farina integrale)",
          "1 cucchiaino di lievito per dolci",
          "Glassa: 2 cucchiai di cacao in polvere 100 % + 2 cucchiai di latte + dolcificante q.b."],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Ungi uno stampo con un po' di olio e spolveralo con della farina.",
   "Nel frullatore, frulla le carote a pezzetti, le uova, l'olio e il dolcificante finché non diventa una crema arancione e liscia.",
   "Trasferisci in una ciotola, aggiungi l'avena frullata (o la farina) e mescola. Per ultimo, aggiungi il lievito e mescola appena.",
   "Versa nello stampo e inforna per 30 minuti, finché uno stecchino infilato al centro non esce pulito.",
   "Prepara la glassa: in un pentolino, mescola il cacao, il latte e il dolcificante e scalda a fuoco basso per 2 minuti, mescolando, finché non diventa una crema lucida. Stendila sulla torta ancora tiepida."],
 "porcoes8": ["1 fetta sottile",
              "1 fetta",
              "1 fetta",
              "1 fetta · frutta",
              "1 fetta",
              "1 fetta media",
              "1 fetta · frutta",
              "1 fetta grande"],
 "dica": "La carota mantiene la torta umida e naturalmente dolce, e aggiunge anche vitamina A. Sostituendo lo zucchero con il dolcificante e la farina bianca con l'avena, la torta resta leggera e piena di fibre. La glassa di cacao puro dà il tocco di cioccolato senza lo zucchero di una glassa tradizionale.",
},
{
 "nome": "Mousse al limone",
 "hook": "Acidula al punto giusto, cremosa e fredda — una rinfrescante mousse al limone che pulisce il palato e non ha zucchero.",
 "tempo": "10 min + frigo", "rende": "3 bicchieri", "kcal_base": 120,
 "ings": ["1 vasetto di yogurt naturale senza zucchero (circa 170 g)",
          "succo di 2 limoni", "scorza di 1 limone",
          "1 cucchiaio di gelatina neutra in polvere",
          "3 cucchiai di acqua calda",
          "dolcificante q.b. — o 2 cucchiai di miele"],
 "passos": [
   "Lava bene 1 limone e ricava la scorza solo dalla parte gialla della buccia (la parte bianca è amara). Spremi i 2 limoni per il succo.",
   "In una tazza, sciogli la gelatina neutra nell'acqua calda, mescolando finché non è limpida. Falla intiepidire un po'.",
   "In una ciotola, mescola lo yogurt, il succo di limone, la scorza e il dolcificante (o miele), finché non è cremoso.",
   "Aggiungi la gelatina sciolta e mescola bene e in fretta, così non si formano grumetti.",
   "Dividila nei bicchieri e mettila in frigo per almeno 2 ore, finché non si rassoda. Servi fredda, con altra scorza di limone sopra."],
 "porcoes8": ["½ bicchiere",
              "1 bicchiere piccolo",
              "1 bicchiere",
              "1 bicchiere · frutta",
              "1 bicchiere",
              "1 bicchiere medio",
              "1 bicchiere · frutta",
              "1 bicchiere grande · frutta"],
 "dica": "Il limone porta freschezza e un sapore deciso che inganna la voglia di dolce senza bisogno di molto dolcificante. Lo yogurt naturale porta proteine e cremosità, e la gelatina rassoda la mousse senza panna. Un dolce leggero e rinfrescante con quasi zero grassi.",
},
{
 "nome": "Cheesecake fit ai frutti di bosco (senza cottura)",
 "hook": "Cremosa, con una base croccante e una copertura di frutta, messa insieme senza forno — la cheesecake dei tuoi sogni in versione leggera e senza zucchero.",
 "tempo": "20 min + frigo", "rende": "6 fette", "kcal_base": 170,
 "ings": ["Base: 90 g di avena + 1 banana schiacciata + 1 cucchiaino di cannella",
          "Crema: 250 g di ricotta (o fiocchi di latte) + ½ vasetto di yogurt naturale + dolcificante q.b. + succo di ½ limone",
          "1 cucchiaio di gelatina neutra in polvere + 3 cucchiai di acqua calda",
          "Copertura: 140 g di frutti di bosco + dolcificante q.b."],
 "passos": [
   "Base: mescola l'avena, la banana schiacciata e la cannella finché non forma un impasto. Pressalo sul fondo di uno stampo piccolo (meglio se apribile), formando uno strato compatto. Mettilo in freezer per 10 minuti.",
   "Sciogli la gelatina nell'acqua calda, mescolando finché non è limpida. Falla intiepidire un po'.",
   "Crema: nel frullatore, frulla la ricotta, lo yogurt, il dolcificante e il succo di limone finché non è una crema liscissima. Aggiungi la gelatina e frulla per altri 20 secondi.",
   "Versa la crema sulla base e livella la superficie. Metti in frigo per almeno 3 ore, finché non si rassoda.",
   "Copertura: in un pentolino, cuoci i frutti di bosco con il dolcificante a fuoco basso per 5 minuti, schiacciandoli un po', finché non diventa una confettura. Falla raffreddare e stendila sulla cheesecake prima di servire."],
 "porcoes8": ["1 fetta sottile",
              "1 fetta",
              "1 fetta",
              "1 fetta · copertura extra",
              "1 fetta",
              "1 fetta media",
              "1 fetta · copertura",
              "1 fetta grande · copertura"],
 "dica": "La ricotta e i fiocchi di latte danno la cremosità del formaggio spalmabile con molti meno grassi e più proteine. La base di avena e banana sostituisce il biscotto al burro, e la copertura di frutta cotta non ha bisogno di zucchero. Una cheesecake vera che rientra nella tua dieta, in una fetta controllata.",
},
{
 "nome": "Ghiaccioli di frutta fatti in casa",
 "hook": "Rinfrescanti e pieni di frutta vera, questi ghiaccioli fatti in casa sono il dolce perfetto per il caldo — e non hanno una goccia di zucchero.",
 "tempo": "10 min + freezer", "rende": "6 ghiaccioli", "kcal_base": 60,
 "ings": ["300 g di frutta a pezzetti (fragola, mango, kiwi o anguria)",
          "240 ml di succo naturale senza zucchero (o acqua di cocco)",
          "1 vasetto di yogurt naturale senza zucchero (facoltativo, per ghiaccioli cremosi)",
          "dolcificante q.b. (facoltativo)",
          "stampi per ghiaccioli e stecchi"],
 "passos": [
   "Taglia la frutta a pezzetti piccoli, così entrano negli stampi.",
   "Scegli lo stile: per ghiaccioli di frutta, usa solo la frutta e il succo naturale; per ghiaccioli cremosi, frulla la frutta con lo yogurt nel frullatore.",
   "Metti qualche pezzetto di frutta sul fondo di ogni stampo (fa una bella figura) e riempilo con il succo o con la crema frullata, lasciando un dito di spazio in cima (il liquido si gonfia congelando).",
   "Infila uno stecco al centro di ogni ghiacciolo.",
   "Congela per almeno 5 ore, finché non sono ben sodi. Per sformarli, passa lo stampo velocemente sotto l'acqua tiepida."],
 "porcoes8": ["1 ghiacciolo",
              "1 ghiacciolo",
              "1 ghiacciolo",
              "1 o 2 ghiaccioli",
              "1 ghiacciolo",
              "1 o 2 ghiaccioli",
              "2 ghiaccioli",
              "2 ghiaccioli"],
 "dica": "I ghiaccioli del supermercato sono quasi solo acqua, zucchero e coloranti. Fatto in casa con frutta vera e succo naturale, il ghiacciolo diventa un dolce rinfrescante pieno di vitamine e praticamente senza calorie — il modo migliore di togliere la voglia di qualcosa di freddo con il caldo, senza sensi di colpa.",
},
{
 "nome": "Muffin di mela e cannella",
 "hook": "Soffici, profumati e con pezzetti di mela — muffin del pomeriggio che sembrano un peccato, ma sono leggeri e senza zucchero.",
 "tempo": "35 min", "rende": "6 muffin", "kcal_base": 140,
 "ings": ["2 uova", "1 mela grattugiata + ½ mela a cubetti piccoli",
          "135 g di avena frullata fino a farina", "3 cucchiai di olio",
          "dolcificante da forno q.b. (quello adatto alla cottura)",
          "120 ml di latte", "1 cucchiaino di cannella",
          "1 cucchiaino di lievito per dolci", "1 pizzico di sale"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Rivesti uno stampo da muffin con i pirottini di carta (o ungi con un po' di olio gli stampini).",
   "In una ciotola, sbatti le uova con il dolcificante e l'olio per 1 minuto. Aggiungi il latte e la mela grattugiata e mescola.",
   "Aggiungi l'avena frullata, la cannella e il sale e mescola finché non è un impasto omogeneo. Aggiungi i cubetti di mela e il lievito e mescola appena.",
   "Dividi l'impasto nei pirottini, riempiendoli per due terzi (crescono).",
   "Inforna per 20-25 minuti, finché non sono dorati e uno stecchino esce pulito. Falli intiepidire un po' e servi."],
 "porcoes8": ["1 muffin",
              "1 muffin",
              "1 muffin",
              "1 muffin · 1 cucchiaio di yogurt",
              "1 muffin",
              "1 o 2 muffin",
              "2 muffin",
              "2 muffin"],
 "dica": "La mela grattugiata mantiene i muffin umidi e naturalmente dolci, così non ti serve zucchero. L'avena porta fibre che saziano e la cannella esalta la dolcezza della frutta. Sono ottimi per uno spuntino o come dolce, in una porzione da un pezzo, e tolgono la voglia di pasticceria in modo leggero.",
},
{
 "nome": "Crumble di mela e avena",
 "hook": "Mela morbida sotto, una briciola croccante di avena sopra — la coccola di una torta calda, messa insieme in pochi minuti e senza zucchero.",
 "tempo": "40 min", "rende": "4 porzioni", "kcal_base": 160,
 "ings": ["3 mele a cubetti", "succo di ½ limone", "1 cucchiaino di cannella",
          "Briciola: 90 g di fiocchi d'avena + 2 cucchiai di frutta a guscio tritata + 2 cucchiai di olio di cocco (o olio normale) + dolcificante q.b.",
          "1 pizzico di sale"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). In una ciotola, mescola i cubetti di mela con il succo di limone e la cannella e distribuiscili sul fondo di una pirofila.",
   "Prepara la briciola: in un'altra ciotola, mescola l'avena, la frutta a guscio, l'olio, il dolcificante e il sale, sfregando con la punta delle dita finché non forma una briciola umida e a grumi.",
   "Distribuisci la briciola sopra le mele, coprendo tutta la superficie.",
   "Inforna per 25-30 minuti, finché la mela non sobbolle ai lati e la briciola non è dorata e croccante.",
   "Falla intiepidire 5 minuti e servi. È deliziosa con un cucchiaio di yogurt naturale o di nice cream alla banana sopra."],
 "porcoes8": ["½ porzione",
              "1 porzione piccola",
              "1 porzione",
              "1 porzione · yogurt",
              "1 porzione",
              "1 porzione media",
              "1 porzione · yogurt",
              "1 porzione grande · yogurt"],
 "dica": "La mela al forno libera la sua dolcezza, e la cannella rinforza il sapore senza zucchero. La briciola di avena e frutta a guscio dà la croccantezza di una torta con fibre e grassi buoni al posto di burro e farina bianca. È la coccola di un dolce caldo al forno, nella porzione giusta.",
},
{
 "nome": "Pera al forno con le spezie",
 "hook": "La pera diventa morbida e succosa, profumata di cannella e chiodi di garofano — un dolce caldo ed elegante, dolcificato solo dalla frutta.",
 "tempo": "35 min", "rende": "2 porzioni", "kcal_base": 110,
 "ings": ["2 pere sode", "stecca di cannella (o in polvere)",
          "2 chiodi di garofano", "scorza d'arancia (facoltativo)",
          "1 cucchiaino di miele (facoltativo)",
          "1 cucchiaio di noci o mandorle tritate"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). Lava le pere, tagliale a metà per il lungo e togli il torsolo dal centro con un cucchiaino, formando un incavo.",
   "Metti le metà di pera su una teglia, con il taglio verso l'alto. Spolvera la cannella sopra e metti un chiodo di garofano e un po' di scorza d'arancia in ogni incavo.",
   "Se ti va, fai cadere qualche goccia di miele su ogni pera.",
   "Metti un dito d'acqua sul fondo della teglia (così non si seccano) e inforna per 25 minuti, finché la pera non è morbidissima (la forchetta entra facilmente).",
   "Togli i chiodi di garofano, spolvera la frutta a guscio tritata sopra e servi calda, da sola o con un cucchiaio di yogurt naturale."],
 "porcoes8": ["1 metà",
              "1 pera (2 metà)",
              "1 pera",
              "1 pera · yogurt",
              "1 pera",
              "1 pera · noci extra",
              "1 pera · yogurt",
              "2 pere · yogurt"],
 "dica": "Cuocere la pera al forno concentra lo zucchero naturale della frutta, lasciandola dolce senza bisogno di zuccheri aggiunti. Le spezie portano un aroma avvolgente che appaga il palato, e la frutta a guscio aggiunge grassi buoni e croccantezza. Un dolce caldo, leggero e sofisticato.",
},
]
