# -*- coding: utf-8 -*-
"""BONUS 1 — DIETA VEGETARIANA. ITALIANO.

Traducao literal de `receitas_bonus_veg_en.py`. Convencoes em
GLOSSARIO-TRADUCAO.md: tratamento por "tu", vocabulario di cucina italiana
(ceci, lenticchie, zucchina, mais, curcuma, purè).
⛔ METRICO: g, ml, °C — como pt/de/fr/es. Os numeros vem do de/fr.
   `5 oz`->`150 g` · `400 °F`->`200 °C` · `350 °F`->`180 °C` ·
   `5 cups of water`->`1,2 litri`.
⛔ Duas listas, como no original: ALMOCOS (4) e JANTARES (4).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ kg · Homem 70-85/86-100/101-120/120+ kg
"""

ALMOCOS = [
{
 "nome": "Bowl di ceci con riso e verdure arrosto",
 "tag": "Pranzo vegetariano", "num_label": "Bonus · Vegetariano",
 "hook": "Una bowl colorata e abbondante, senza niente di carne — i ceci ti sostengono per tutto il pomeriggio come un piatto di proteine.",
 "tempo": "35 min", "rende": "1 porzione", "kcal_base": 500,
 "ings": ["80 g di ceci cotti (o in scatola, scolati)",
          "4 cucchiai di riso integrale cotto", "1 zucchina a pezzi",
          "½ peperone a pezzi", "½ cipolla rossa a pezzi", "pomodorini",
          "1 cucchiaino di olio d'oliva", "succo di ½ limone",
          "sale, pepe, curcuma e origano q.b.", "foglie verdi"],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la zucchina, il peperone e la cipolla a pezzi simili, della misura di un boccone.",
   "Su una teglia, distribuisci le verdure e i pomodorini, condisci con sale, pepe, origano e metà dell'olio d'oliva, e mescola con le mani.",
   "Inforna per 20-25 minuti, finché le verdure non sono morbide e dorate ai bordi. Giralle a metà cottura.",
   "In una padella, scalda il resto dell'olio d'oliva e salta i ceci con la curcuma, il sale e il pepe per 3 minuti, mescolando, giusto per insaporirli e farli dorare leggermente.",
   "Componi la bowl: un letto di foglie verdi, il riso da un lato, i ceci e le verdure arrosto sopra. Condisci con il succo di limone e servi."],
 "porcoes8": ["55 g di ceci · 3 cucchiai di riso · verdure",
              "80 g di ceci · 4 cucchiai di riso · verdure",
              "80 g di ceci · 5 cucchiai di riso · verdure",
              "110 g di ceci · 5 cucchiai di riso · un po' di olio d'oliva",
              "110 g di ceci · 5 cucchiai di riso · verdure",
              "125 g di ceci · 6 cucchiai di riso · 1 cucchiaio di noci",
              "165 g di ceci · 7 cucchiai di riso · avocado",
              "165 g di ceci · 8 cucchiai di riso · avocado"],
 "dica": "I ceci uniscono proteine e fibre che saziano come un piatto di carne, e insieme al riso integrale formano una proteina completa (la coppia legume + cereale che usano i vegetariani). Arrostire le verdure concentra il sapore senza grassi, mantenendo il piatto leggero e pieno di gusto.",
},
{
 "nome": "Pasticcio di lenticchie con purè di patate",
 "tag": "Pranzo vegetariano", "num_label": "Bonus · Vegetariano",
 "hook": "Tutta la coccola di un pasticcio gratinato, con un ripieno di lenticchie condite al posto della carne — cremoso e pieno di proteine vegetali.",
 "tempo": "45 min", "rende": "2 porzioni", "kcal_base": 470,
 "ings": ["200 g di lenticchie cotte", "2 patate medie", "1 cipolla, tritata",
          "2 spicchi d'aglio, tritati", "1 pomodoro, a pezzetti",
          "1 carota, grattugiata", "1 cucchiaino di olio d'oliva",
          "2 cucchiai di formaggio grattugiato",
          "sale, pepe, curcuma ed erbe fresche q.b."],
 "passos": [
   "Sbuccia e cuoci le patate in acqua bollente per 15 minuti, finché non sono molto morbide. Scolale e schiacciale con la forchetta, con un pizzico di sale, finché non diventa un purè liscio.",
   "In una padella, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi la carota grattugiata e il pomodoro e cuoci per 3 minuti.",
   "Aggiungi le lenticchie cotte, la curcuma, sale e pepe e cuoci per altri 5 minuti, schiacciando un po' le lenticchie con il cucchiaio, finché non diventa un ripieno ricco.",
   "In una pirofila, stendi metà del purè sul fondo, il ripieno di lenticchie al centro e il resto del purè sopra. Spolvera il formaggio grattugiato.",
   "Inforna a fuoco medio-alto (200 °C) per 15 minuti, finché la superficie non è dorata. Spolvera le erbe fresche e servi."],
 "porcoes8": ["½ porzione · insalata",
              "1 porzione · insalata",
              "1 porzione · insalata",
              "1 porzione · 1 cucchiaio in più di formaggio · insalata",
              "1 porzione · lenticchie extra · insalata",
              "1 porzione grande · insalata",
              "1 porzione grande · lenticchie extra · insalata",
              "porzione doppia · insalata"],
 "dica": "Le lenticchie sono ricche di ferro, fibre e proteine vegetali, un trio che sazia moltissimo — nel pasticcio sostituiscono la carne con abbondanza. Con il purè di patate nella misura giusta e un po' di formaggio gratinato, è un piatto avvolgente che inganna la voglia di cibo pesante.",
},
{
 "nome": "Frittata di verdure",
 "tag": "Pranzo vegetariano", "num_label": "Bonus · Vegetariano",
 "hook": "Una frittata alta e soffice, cotta al forno con verdure colorate e formaggio — le proteine dell'uovo in un piatto che tagli a fette e piace a tutti.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 420,
 "ings": ["5 uova", "1 zucchina a cubetti piccoli", "½ peperone, a pezzetti",
          "1 pomodoro, a pezzetti", "una manciata di spinaci",
          "3 cucchiai di formaggio bianco a cubetti",
          "1 cucchiaino di olio d'oliva", "erba cipollina, sale e pepe q.b.",
          "foglie verdi per l'insalata"],
 "passos": [
   "Accendi il forno a fuoco medio (180 °C). In una padella che possa andare in forno, scalda l'olio d'oliva e salta la zucchina e il peperone per 4 minuti, mescolando, finché non si ammorbidiscono.",
   "Aggiungi gli spinaci e mescola per 1 minuto, giusto finché non appassiscono (le foglie si ammorbidiscono). Distribuisci le verdure per la padella.",
   "In una ciotola, sbatti le uova con sale e pepe. Aggiungi il pomodoro, il formaggio e l'erba cipollina e mescola.",
   "Versa le uova sulle verdure nella padella e lasciala 2 minuti sul fuoco, giusto per rassodare il bordo.",
   "Metti la padella in forno per 15 minuti, finché la frittata non si gonfia, si rassoda al centro e si dora in superficie. Tagliala a fette e servi con un'insalata verde."],
 "porcoes8": ["1 fetta · insalata",
              "1 fetta grande · insalata",
              "1 fetta grande · insalata · 2 cucchiai di riso",
              "2 fette · insalata · 2 cucchiai di riso",
              "2 fette · insalata · 3 cucchiai di riso",
              "2 fette grandi · insalata · 3 cucchiai di riso",
              "2 fette grandi · insalata · 4 cucchiai di riso",
              "3 fette · insalata · 4 cucchiai di riso"],
 "dica": "Le uova sono una proteina completa e molto saziante, ideale per un pranzo vegetariano senza legumi. Cotta al forno con le verdure e un po' di formaggio, la frittata rende parecchio, si conserva bene in frigo e toglie la fame in modo leggero e nutriente.",
},
{
 "nome": "Chili vegetariano di fagioli e ceci",
 "tag": "Pranzo vegetariano", "num_label": "Bonus · Vegetariano",
 "hook": "Uno stufato piccante e sostanzioso senza niente di carne — la prova che anche il cibo vegetariano riempie il piatto e la pancia.",
 "tempo": "30 min", "rende": "3 porzioni", "kcal_base": 460,
 "ings": ["175 g di fagioli rossi cotti", "165 g di ceci cotti", "80 g di mais",
          "1 cipolla, tritata", "2 spicchi d'aglio, tritati",
          "1 peperone, a pezzetti",
          "2 pomodori, a pezzetti (o passata di pomodoro)",
          "1 cucchiaino di olio d'oliva", "1 cucchiaino di cumino",
          "sale, pepe e paprika q.b.", "riso per servire"],
 "passos": [
   "Scalda l'olio d'oliva in una pentola a fuoco medio. Fai soffriggere la cipolla, l'aglio e il peperone per 3 minuti, mescolando, finché non si ammorbidiscono.",
   "Aggiungi il cumino, la paprika, sale e pepe e mescola per 30 secondi, così le spezie liberano il loro aroma.",
   "Aggiungi i pomodori a pezzetti e cuoci per 5 minuti, finché non si disfano in un sugo.",
   "Aggiungi i fagioli rossi, i ceci e il mais. Se si asciuga, aggiungi mezzo bicchiere d'acqua.",
   "Abbassa la fiamma e cuoci per 15 minuti, mescolando ogni tanto, finché non si addensa in uno stufato cremoso. Servi con un po' di riso."],
 "porcoes8": ["½ porzione · 3 cucchiai di riso",
              "1 porzione · 4 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione · 5 cucchiai di riso · avocado",
              "1 porzione · 5 cucchiai di riso",
              "1 porzione grande · 6 cucchiai di riso",
              "porzione grande · 7 cucchiai di riso · avocado",
              "porzione doppia · 8 cucchiai di riso"],
 "dica": "I fagioli e i ceci insieme formano una proteina vegetale molto completa, con una montagna di fibre che sazia per ore. Servito con il riso, chiude la proteina completa. È un piatto economico che dura diversi giorni e dimostra che si può mangiare bene senza carne.",
},
]

JANTARES = [
{
 "nome": "Zuppa sostanziosa di lenticchie con verdure",
 "tag": "Cena vegetariana", "num_label": "Bonus · Vegetariano",
 "hook": "Una zuppa che è un pasto vero: le lenticchie rendono il brodo ricco e pieno di proteine, scaldandoti e saziandoti in una serata fredda.",
 "tempo": "40 min", "rende": "3 porzioni", "kcal_base": 380,
 "ings": ["190 g di lenticchie crude", "1 patata a cubetti",
          "1 carota a cubetti", "1 gambo di sedano, tritato (facoltativo)",
          "1 pomodoro, a pezzetti", "1 cipolla, tritata",
          "2 spicchi d'aglio, tritati", "1 cucchiaino di olio d'oliva",
          "sale, pepe, curcuma ed erbe fresche q.b.", "1,2 litri di acqua"],
 "passos": [
   "Lava le lenticchie. In una pentola, scalda l'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando.",
   "Aggiungi il pomodoro, la carota, la patata e il sedano e mescola per 2 minuti.",
   "Aggiungi le lenticchie, la curcuma, sale, pepe e l'acqua. Porta a bollore.",
   "Abbassa la fiamma e cuoci per 25-30 minuti, mescolando ogni tanto, finché le lenticchie e le verdure non sono molto morbide e il brodo non ha corpo. Se si asciuga troppo, aggiungi un po' di acqua calda.",
   "Aggiusta di sale, spolvera le erbe fresche e servi ben calda."],
 "porcoes8": ["1 mestolo · senza pane",
              "2 mestoli · senza pane",
              "2 mestoli · 1 fetta di pane",
              "2 mestoli · 1 fetta di pane",
              "2 mestoli · 1 fetta di pane",
              "3 mestoli · 1 fetta di pane",
              "3 mestoli · 2 fette di pane",
              "3 mestoli grandi · 2 fette di pane"],
 "dica": "Le lenticchie sono uno dei legumi più ricchi di proteine e ferro, e in una zuppa rendono il brodo sostanzioso quanto basta per essere una cena completa senza carne. Tutto quel liquido e le verdure riempiono lo stomaco con poche calorie — leggera, calda e avvolgente.",
},
{
 "nome": "Tofu alla griglia con verdure e riso",
 "tag": "Cena vegetariana", "num_label": "Bonus · Vegetariano",
 "hook": "Il tofu dorato prende il condimento e viene delizioso — un'opzione senza carne che sazia davvero ed è leggera per la sera.",
 "tempo": "25 min", "rende": "1 porzione", "kcal_base": 420,
 "ings": ["150 g di tofu compatto a fette",
          "4 cucchiai di riso integrale cotto", "100 g di broccoli e carota",
          "1 cucchiaio di salsa di soia chiara", "1 spicchio d'aglio, tritato",
          "1 cucchiaino di olio d'oliva", "zenzero grattugiato (facoltativo)",
          "sale e pepe q.b."],
 "passos": [
   "Asciuga bene le fette di tofu con la carta da cucina, premendo leggermente — più è asciutto, meglio si dora.",
   "Condisci il tofu con la salsa di soia, l'aglio e lo zenzero. Lascialo insaporire per 5 minuti.",
   "Scalda una padella antiaderente con metà dell'olio d'oliva a fuoco medio-alto. Cuoci le fette di tofu 3-4 minuti per lato, senza spostarle, finché non si forma una crosticina dorata. Toglile e mettile da parte.",
   "Taglia i broccoli a cimette e la carota a rondelle. Nella stessa padella, con il resto dell'olio d'oliva, salta le verdure per 4 minuti, finché non sono tenere ma ancora sode.",
   "Componi il piatto con il riso integrale, le verdure e il tofu alla griglia sopra. Condisci con ancora un po' di salsa di soia se ti va."],
 "porcoes8": ["120 g di tofu · 3 cucchiai di riso · verdure",
              "150 g di tofu · 4 cucchiai di riso · verdure",
              "150 g di tofu · 5 cucchiai di riso · verdure",
              "170 g di tofu · 5 cucchiai di riso · un po' di olio d'oliva",
              "170 g di tofu · 5 cucchiai di riso · verdure",
              "200 g di tofu · 6 cucchiai di riso · verdure",
              "220 g di tofu · 7 cucchiai di riso · 1 cucchiaio di noci",
              "250 g di tofu · 8 cucchiai di riso · noci"],
 "dica": "Il tofu è fatto di soia e porta proteine vegetali con pochi grassi, il che lo rende una delle migliori alternative alla carne. Asciugato bene e cotto alla griglia, guadagna consistenza e assorbe il condimento. Con le verdure e il riso integrale, diventa una cena completa, leggera e piena di fibre.",
},
{
 "nome": "Melanzane ripiene di ceci e formaggio",
 "tag": "Cena vegetariana", "num_label": "Bonus · Vegetariano",
 "hook": "La melanzana stessa diventa la ciotola, ripiena di ceci conditi e gratinata con il formaggio — bella, abbondante e senza carne.",
 "tempo": "40 min", "rende": "2 porzioni", "kcal_base": 400,
 "ings": ["1 melanzana grande", "165 g di ceci cotti", "1 cipolla, tritata",
          "1 spicchio d'aglio, tritato", "1 pomodoro, a pezzetti",
          "1 cucchiaino di olio d'oliva",
          "2 cucchiai di formaggio grattugiato magro",
          "sale, pepe, cumino e prezzemolo q.b."],
 "passos": [
   "Accendi il forno a fuoco medio-alto (200 °C). Taglia la melanzana a metà per il lungo. Con un cucchiaio, togli parte della polpa centrale, formando due 'barchette'. Trita la polpa che hai tolto.",
   "Metti le barchette su una teglia, condisci con un po' di olio d'oliva e inforna per 10 minuti, giusto per ammorbidirle.",
   "In una padella, scalda il resto dell'olio d'oliva e fai soffriggere la cipolla e l'aglio per 2 minuti. Aggiungi il pomodoro, la polpa di melanzana tritata, i ceci, il cumino, sale e pepe e cuoci per 6 minuti, schiacciando un po' i ceci, finché non diventa un ripieno morbido.",
   "Riempi le barchette con il composto di ceci e spolvera sopra il formaggio grattugiato.",
   "Rimetti in forno per 15 minuti, finché la superficie non si gratina (il formaggio si scioglie e si dora). Spolvera il prezzemolo e servi."],
 "porcoes8": ["½ melanzana · insalata",
              "1 melanzana ripiena · insalata",
              "1 melanzana · 2 cucchiai di riso",
              "1 melanzana · ceci extra · insalata",
              "1 melanzana · ceci extra · 2 cucchiai di riso",
              "1 melanzana grande · 3 cucchiai di riso",
              "1 melanzana · doppi ceci · 4 cucchiai di riso",
              "melanzana + porzione extra · 4 cucchiai di riso"],
 "dica": "La melanzana ha tanta acqua e fibre, quindi riempie il piatto con pochissime calorie. I ceci portano la proteina vegetale che sostituisce la carne, e un po' di formaggio gratinato toglie la voglia di un piatto filante. Una cena vegetariana bella, abbondante e leggera.",
},
{
 "nome": "Curry di ceci con riso",
 "tag": "Cena vegetariana", "num_label": "Bonus · Vegetariano",
 "hook": "Una salsa dorata e profumata che avvolge i ceci — cremosa con il latte di cocco light, è una cena vegetariana piena di sapore.",
 "tempo": "30 min", "rende": "2 porzioni", "kcal_base": 440,
 "ings": ["330 g di ceci cotti", "1 cipolla, tritata",
          "2 spicchi d'aglio, tritati", "1 pomodoro, a pezzetti",
          "1 cucchiaino di curry in polvere", "120 ml di latte di cocco light",
          "una manciata di spinaci (facoltativo)",
          "1 cucchiaino di olio d'oliva", "sale, pepe e coriandolo q.b.",
          "riso per servire"],
 "passos": [
   "Scalda l'olio d'oliva in una pentola a fuoco medio e fai soffriggere la cipolla e l'aglio per 2 minuti, mescolando.",
   "Aggiungi il curry e mescola per 30 secondi, perché la spezia liberi il suo aroma. Aggiungi il pomodoro e cuoci per 3 minuti, finché non si disfa.",
   "Aggiungi i ceci e il latte di cocco light e mescola. Aggiusta di sale e pepe.",
   "Cuoci a fuoco basso per 10 minuti, mescolando ogni tanto, finché la salsa non si addensa. Se ti va, aggiungi gli spinaci negli ultimi 2 minuti, giusto finché non appassiscono.",
   "Spolvera il coriandolo e servi su una porzione di riso."],
 "porcoes8": ["110 g di ceci · 3 cucchiai di riso",
              "165 g di ceci · 4 cucchiai di riso",
              "165 g di ceci · 5 cucchiai di riso",
              "165 g di ceci · 5 cucchiai di riso · spinaci",
              "165 g di ceci · 5 cucchiai di riso",
              "250 g di ceci · 6 cucchiai di riso",
              "250 g di ceci · 7 cucchiai di riso",
              "330 g di ceci · 8 cucchiai di riso"],
 "dica": "I ceci sono ricchi di proteine e fibre, e in un curry diventano cremosi e pieni di sapore. Il latte di cocco light dà corpo alla salsa con molti meno grassi della panna. Con il riso, formano una proteina completa — una cena vegetariana avvolgente e nutriente.",
},
]
