# -*- coding: utf-8 -*-
"""35 receitas de JANTAR (066-100). ALEMÃO.

Tradução literal de `receitas_jantar.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/066-100).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 340/420/480/540 · 520/590/650/720
"""

RECEITAS = [
{
 "nome": "Kürbissuppe mit gezupftem Hähnchen",
 "hook": "Cremig, orange und wohltuend — eine Suppe, die abends von innen wärmt und mit dem Eiweiß aus dem Hähnchen wirklich sättigt.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 340,
 "ings": ["1 großes Stück Kürbis in Würfeln (ca. 500 g)", "1 Hähnchenbrustfilet (ca. 150 g)",
          "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer und geriebener Ingwer nach Geschmack", "Petersilie und Schnittlauch zum Bestreuen", "1 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an, bis sie glasig sind.",
   "Gib die Kürbiswürfel, das ganze Hähnchenfilet und das Wasser dazu. Lass alles aufkochen und 20 Minuten garen, bis der Kürbis ganz weich ist.",
   "Nimm das Hähnchen heraus, lass es lauwarm werden und zupfe es mit zwei Gabeln auseinander. Stelle es beiseite.",
   "Püriere den Kürbis mit der Brühe mit einem Pürierstab (dem Stab zum Mixen) oder im Mixer zu einer glatten Creme. Sei vorsichtig mit der heißen Flüssigkeit.",
   "Gib die Creme zurück in den Topf, füge das gezupfte Hähnchen, den Ingwer, Salz und Pfeffer dazu und erwärme alles 3 Minuten. Serviere mit den Kräutern obendrauf."],
 "porcoes8": ["1 Kelle · wenig Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · Hähnchen · 1 Scheibe Brot",
              "2 Kellen · extra Hähnchen · 1 Scheibe Brot",
              "3 Kellen · Hähnchen · 1 Scheibe Brot",
              "3 Kellen · extra Hähnchen · 2 Scheiben Brot",
              "3 große Kellen · doppelt Hähnchen · 2 Scheiben Brot"],
 "dica": "Der Kürbis enthält viel Wasser und Ballaststoffe, das füllt den Magen mit sehr wenigen Kalorien. Die Wärme der Suppe sorgt dafür, dass man langsamer isst, und das gezupfte Hähnchen macht aus der leichten Creme eine vollständige Mahlzeit, die bis zum Schlafengehen trägt, ohne schwer zu liegen.",
},
{
 "nome": "Hähnchenfilet in Senfsoße mit Dampfgemüse",
 "hook": "Eine cremige Soße aus Senf und Joghurt macht das Hähnchen festlich — leicht, elegant und abends schnell fertig.",
 "tempo": "25 Min.", "rende": "1 Portion", "kcal_base": 400,
 "ings": ["1 Hähnchenbrustfilet (ca. 150 g)", "1 EL Naturjoghurt ohne Zucker",
          "1 TL Senf", "100 g Brokkoli, Möhren und grüne Bohnen", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack"],
 "passos": [
   "Schneide das Gemüse in ähnlich große Stücke. Gare es im Dampf (oder in einem Topf mit einem Finger breit Wasser und Deckel) 6 Minuten, bis es weich, aber noch fest und farbig ist.",
   "Würze das Hähnchen mit Salz, Pfeffer und dem Knoblauch. Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze und brate das Filet 4 bis 5 Minuten je Seite, bis es goldbraun und innen weiß ist.",
   "Verrühre in einer kleinen Schüssel den Joghurt, den Senf, den Zitronensaft, Salz und Pfeffer zu einer cremigen Soße.",
   "Lege das Hähnchen auf den Teller, gib die Senfsoße darüber und serviere das Gemüse daneben.",
   "Streue die Kräuter darüber und serviere alles warm."],
 "porcoes8": ["120 g Hähnchen · Gemüse",
              "150 g Hähnchen · Gemüse",
              "150 g Hähnchen · Gemüse · 2 EL Reis",
              "170 g Hähnchen · Gemüse · 2 EL Reis",
              "170 g Hähnchen · Gemüse · 3 EL Reis",
              "200 g Hähnchen · Gemüse · 3 EL Reis",
              "220 g Hähnchen · Gemüse · 4 EL Reis",
              "250 g Hähnchen · Gemüse · 4 EL Reis"],
 "dica": "Die cremige Soße kommt aus dem Joghurt, nicht aus Sahne oder Butter, das spart sehr viel Fett. Der Senf bringt kräftigen Geschmack bei fast keinen Kalorien. Das Gemüse im Dampf zu garen erhält die Nährstoffe und braucht kein Öl — ein leichtes Abendessen, das wie im Restaurant wirkt.",
},
{
 "nome": "Fisch im Päckchen mit Gemüse",
 "hook": "Der Fisch gart im eigenen Dampf im Papier und wird unglaublich zart — und du öffnest das Päckchen am Tisch, warm und duftend.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 380,
 "ings": ["1 Filet vom weißen Fisch (Seehecht, Kabeljau oder Tilapia, ca. 150 g)", "½ Zucchini in dünnen Scheiben",
          "½ Möhre in dünnen Streifen", "Kirschtomaten, geschnitten", "1 Knoblauchzehe in Scheiben", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Kräuter (Thymian oder Oregano) nach Geschmack", "1 großes Blatt Backpapier"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Schneide die Zucchini und die Möhre in dünne Scheiben, damit sie in derselben Zeit garen wie der Fisch.",
   "Lege in der Mitte eines großen Blattes Backpapier ein Bett aus dem Gemüse an. Würze es mit etwas Salz, Pfeffer und der Hälfte des Olivenöls.",
   "Lege das Fischfilet darauf. Würze es mit Salz, Pfeffer, dem Knoblauch, den Kräutern, dem Zitronensaft und dem restlichen Olivenöl.",
   "Verschließe das Papier wie ein Päckchen: Führe die Enden zusammen und falte die Ränder gut um, dabei etwas Luft im Inneren lassen, sodass ein geschlossenes Päckchen entsteht.",
   "Backe alles 18 bis 20 Minuten. Öffne es vorsichtig (es tritt heißer Dampf aus) und serviere es im Papier oder auf dem Teller."],
 "porcoes8": ["120 g Fisch · Gemüse",
              "150 g Fisch · Gemüse",
              "150 g Fisch · Gemüse · 1 kleine Kartoffel",
              "170 g Fisch · Gemüse · 1 Kartoffel",
              "170 g Fisch · Gemüse · 1 Kartoffel",
              "200 g Fisch · Gemüse · 1 Kartoffel",
              "220 g Fisch · Gemüse · 1 große Kartoffel",
              "250 g Fisch · Gemüse · 2 kleine Kartoffeln"],
 "dica": "Im Päckchen zu garen braucht fast kein Fett: Fisch und Gemüse garen im eigenen Dampf, behalten den Geschmack und werden sehr zart. Es ist eine der leichtesten und gesündesten Arten, Fisch zuzubereiten, perfekt für ein Abendessen ohne Schwere und ohne schmutzigen Topf.",
},
{
 "nome": "Hähnchen-Auflauf mit Blumenkohlpüree",
 "hook": "Der ganze Trost eines überbackenen Auflaufs, nur ist die Decke ein Blumenkohlpüree — cremig, leicht und mit viel weniger Kalorien.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 380,
 "ings": ["1 mittelgroßer Blumenkohl", "2 gekochte, gezupfte Hähnchenbrustfilets (ca. 300 g)", "1 Zwiebel, gehackt",
          "1 Knoblauchzehe, gehackt", "1 Tomate, gehackt", "1 TL Olivenöl",
          "2 EL magerer geriebener Käse", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack"],
 "passos": [
   "Schneide den Blumenkohl in Stücke und koche ihn 12 Minuten in kochendem Wasser, bis er ganz weich ist. Lass ihn sehr gut abtropfen (Blumenkohl hält Wasser) und zerdrücke ihn mit einer Gabel und einer Prise Salz zu einem cremigen Püree.",
   "Erhitze das Olivenöl in einer Pfanne und brate die Zwiebel und den Knoblauch 2 Minuten an. Gib das gezupfte Hähnchen und die Tomate dazu, würze mit Salz und Pfeffer und koche alles 5 Minuten, bis eine weiche Füllung entsteht.",
   "Verteile das Hähnchen in einer Auflaufform und bedecke es mit dem Blumenkohlpüree.",
   "Streue den geriebenen Käse darüber.",
   "Backe alles bei 200 °C 15 Minuten, bis die Oberfläche leicht goldbraun ist. Streue die Kräuter darüber und serviere."],
 "porcoes8": ["½ Portion · Salat",
              "1 Portion · Salat",
              "1 Portion · Salat",
              "1 Portion · extra Hähnchen · Salat",
              "1 Portion · extra Hähnchen · Salat",
              "1 große Portion · Salat",
              "1 große Portion · extra Hähnchen · Salat",
              "doppelte Portion · Salat"],
 "dica": "Der Blumenkohl anstelle der Kartoffel spart einen großen Teil der Kalorien und der Kohlenhydrate und behält trotzdem die Cremigkeit des Pürees. Das gezupfte Hähnchen bringt Eiweiß und Sättigung. Es ist das ideale wohltuende Gericht für alle, die abends warm und leicht essen wollen, bevor sie schlafen gehen.",
},
{
 "nome": "Gemüsesuppe mit magerem Rindfleisch",
 "hook": "Die Suppe, die schmeckt, als hätte Oma sie gekocht: zarte Fleischstücke und Gemüse in einer gewürzten Brühe, die den Bauch füllt und die Seele wärmt.",
 "tempo": "50 Min.", "rende": "3 Portionen", "kcal_base": 360,
 "ings": ["250 g mageres Rindfleisch in Würfeln (Wade oder Oberschale)", "1 Kartoffel in Würfeln", "1 Möhre in Würfeln",
          "1 Zucchini in Würfeln", "1 Tomate, gehackt", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack", "1,5 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf und brate die Fleischwürfel unter Rühren 5 Minuten rundherum an.",
   "Gib die Zwiebel und den Knoblauch dazu und brate alles 2 Minuten. Füge die Tomate hinzu und rühre noch 2 Minuten.",
   "Gieße das Wasser an, würze mit Salz und Pfeffer, decke den Topf ab und koche alles 30 Minuten bei mittlerer bis kleiner Hitze, bis das Fleisch weicher wird.",
   "Gib die Kartoffel, die Möhre und die Zucchini dazu und koche alles noch 15 Minuten, bis das Fleisch ganz zart und das Gemüse gar ist.",
   "Schmecke mit Salz ab, streue die Kräuter darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["1 Kelle · wenig Fleisch",
              "2 Kellen · Fleisch",
              "2 Kellen · Fleisch",
              "2 Kellen · Fleisch · 1 Scheibe Brot",
              "2 Kellen · extra Fleisch · 1 Scheibe Brot",
              "3 Kellen · Fleisch · 1 Scheibe Brot",
              "3 Kellen · extra Fleisch · 2 Scheiben Brot",
              "3 große Kellen · doppelt Fleisch · 2 Scheiben Brot"],
 "dica": "Suppen mit viel Flüssigkeit und Gemüse füllen den Magen mit wenigen Kalorien, und weil man sie heiß isst, isst man langsamer und wird früher satt. Das magere Fleisch bringt Eiweiß dazu und macht die Suppe kräftig genug für ein vollständiges Abendessen.",
},
{
 "nome": "Lachs mit Joghurt-Dill-Soße und Gemüse",
 "hook": "Der rosa Lachs bekommt eine frische Soße aus Joghurt und Dill — edel, leicht und in zwanzig Minuten gemacht.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 430,
 "ings": ["1 Lachsfilet (ca. 150 g)", "2 EL Naturjoghurt ohne Zucker", "gehackter Dill",
          "100 g Brokkoli und Möhren", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und gehackter Knoblauch nach Geschmack"],
 "passos": [
   "Schneide den Brokkoli in Röschen und die Möhre in Scheiben. Gare beides 6 Minuten im Dampf, bis es weich, aber noch fest ist.",
   "Würze den Lachs mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze. Lege den Lachs mit der Hautseite nach unten hinein und lass ihn 4 Minuten braten, wende ihn dann und lass ihn weitere 3 Minuten, bis er heller wird und sich mit der Gabel in Stücke teilen lässt.",
   "Rühre die Soße an: Vermische den Joghurt, den gehackten Dill, etwas Salz und ein paar Tropfen Zitrone.",
   "Richte den Teller mit dem Lachs an, das Gemüse daneben und die Joghurtsoße darüber oder separat."],
 "porcoes8": ["120 g Lachs · Gemüse",
              "150 g Lachs · Gemüse",
              "150 g Lachs · Gemüse · 1 kleine Kartoffel",
              "170 g Lachs · Gemüse · 1 Kartoffel",
              "170 g Lachs · Gemüse · 1 Kartoffel",
              "200 g Lachs · Gemüse · 1 Kartoffel",
              "220 g Lachs · Gemüse · 1 große Kartoffel",
              "250 g Lachs · Gemüse · 2 kleine Kartoffeln"],
 "dica": "Der Lachs bringt das gute Fett (Omega-3), das sättigt und dem Herzen guttut. Die Joghurt-Dill-Soße ersetzt fettige Sahnesoßen durch eine frische, eiweißreiche Variante. Mit Dampfgemüse ist das ein leichtes, schönes und vollständiges Abendessen.",
},
{
 "nome": "Zitronenhähnchen mit Ofengemüse",
 "hook": "Das Hähnchen bleibt saftig und leicht zitronig, zusammen gebacken mit Gemüse, das an den Spitzen karamellisiert — ein Blech, null Arbeit.",
 "tempo": "40 Min.", "rende": "2 Portionen", "kcal_base": 420,
 "ings": ["2 Hähnchenoberkeulen ohne Haut (oder 2 Filets, ca. 300 g)", "1 Zucchini in Stücken", "1 Paprika in Stücken",
          "1 Zwiebel in Spalten", "Kirschtomaten", "2 Knoblauchzehen", "1 TL Olivenöl",
          "Saft von 1 Zitrone", "Salz, Pfeffer und Oregano nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Verteile die Zucchini, die Paprika, die Zwiebel, die Kirschtomaten und die Knoblauchzehen auf einem Backblech.",
   "Würze das Gemüse mit Salz, Pfeffer, Oregano und der Hälfte des Olivenöls und vermische es.",
   "Würze das Hähnchen mit Salz, Pfeffer, dem Zitronensaft und dem restlichen Olivenöl. Lege die Stücke zwischen das Gemüse.",
   "Backe alles 35 Minuten und wende es nach der Hälfte der Zeit, bis das Hähnchen goldbraun und innen gar ist (die Flüssigkeit, die beim Einstechen austritt, ist klar) und das Gemüse weich mit goldbraunen Spitzen ist.",
   "Serviere direkt vom Blech und beträufle alles mit dem entstandenen Zitronensud."],
 "porcoes8": ["1 Oberkeule · Gemüse",
              "1 Oberkeule · Gemüse",
              "1 große Oberkeule · Gemüse",
              "2 Oberkeulen · Gemüse",
              "2 Oberkeulen · Gemüse",
              "2 Oberkeulen · Gemüse · 1 Kartoffel",
              "2 Oberkeulen · Gemüse · 1 große Kartoffel",
              "3 Oberkeulen · Gemüse · 1 große Kartoffel"],
 "dica": "Ohne Haut und mit wenig Öl gebacken bleibt das Hähnchen leicht, und die Zitrone bringt Frische ohne zusätzliche Kalorien. Das Ofengemüse wird von selbst süß und schmackhaft, schwere Soßen sind überflüssig. Ein praktisches, buntes und leichtes Abendessen von einem einzigen Blech.",
},
{
 "nome": "Putenbällchen mit Zucchini in Soße",
 "hook": "Leichte Putenbällchen, die in frischer Tomatensoße schwimmen, auf Zucchinibändern — die Pasta, die nicht auf die Waage schlägt.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 380,
 "ings": ["250 g Putenhackfleisch (oder Hähnchenhack)", "1 Ei", "2 EL Haferflocken",
          "2 große Zucchini", "3 reife Tomaten, gehackt (oder Tomatensoße)", "1 Zwiebel, gehackt",
          "2 Knoblauchzehen, gehackt", "1 TL Olivenöl", "Salz, Pfeffer und Basilikum nach Geschmack"],
 "passos": [
   "Vermische in einer Schüssel das Putenhack, das Ei, die Haferflocken, die Hälfte des Knoblauchs, Salz und Pfeffer. Knete alles mit den Händen und forme Bällchen von der Größe einer Walnuss.",
   "Erhitze das Olivenöl in einem weiten Topf und brate die Bällchen rundherum an, dabei vorsichtig drehen, 5 Minuten lang. Nimm sie heraus und stelle sie beiseite.",
   "Brate im selben Topf die Zwiebel und den restlichen Knoblauch 2 Minuten an. Gib die gehackten Tomaten, Salz und Pfeffer dazu und koche alles 10 Minuten, bis eine Soße entsteht.",
   "Gib die Bällchen zurück in die Soße und lass sie noch 8 Minuten garen, bis sie innen durch sind.",
   "Ziehe mit einem Sparschäler dünne Bänder von der Zucchini ab (wie Nudeln). Lege die rohen Bänder auf den Teller und gib die heißen Bällchen mit der Soße darüber — die Hitze macht die Zucchini weich. Streue Basilikum darüber."],
 "porcoes8": ["3 Bällchen · Zucchini",
              "4 Bällchen · Zucchini",
              "4 Bällchen · Zucchini · 2 EL Reis",
              "5 Bällchen · Zucchini · 2 EL Reis",
              "5 Bällchen · Zucchini · 3 EL Reis",
              "6 Bällchen · Zucchini · 3 EL Reis",
              "7 Bällchen · Zucchini · 4 EL Reis",
              "8 Bällchen · Zucchini · 4 EL Reis"],
 "dica": "Die Nudeln durch Zucchinibänder zu ersetzen spart fast alle Kohlenhydrate und füllt den Teller mit Ballaststoffen und Wasser. Die Putenbällchen sind mager und eiweißreich, und die frisch gekochte Tomatensoße ohne Zucker macht das Abendessen schmackhaft und sehr leicht.",
},
{
 "nome": "Fischfilet mit Kräuterkruste und Kartoffelpüree",
 "hook": "Außen eine knusprige Kräuterkruste, innen zarter Fisch — sieht aus wie vom Küchenchef, ist aber einfach und leicht.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 410,
 "ings": ["1 Filet vom weißen Fisch (Seehecht, Kabeljau oder Tilapia, ca. 150 g)", "2 EL Vollkorn-Paniermehl",
          "fein gehackte Petersilie und Schnittlauch", "1 mittelgroße Kartoffel", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "1 Knoblauchzehe, gehackt", "Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Schäle die Kartoffel und koche sie 15 Minuten in kochendem Wasser, bis sie ganz weich ist. Gieße sie ab und zerdrücke sie mit einer Gabel und einer Prise Salz zu einem glatten Püree.",
   "Heize den Backofen auf 200 °C vor. Würze den Fisch mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft.",
   "Vermische in einer kleinen Schüssel das Paniermehl mit der Petersilie, dem Schnittlauch und etwas Olivenöl zu einer feuchten Krümelmasse.",
   "Lege den Fisch auf ein Backblech und bedecke seine Oberseite mit der Kräuterkrümelmasse, dabei leicht andrücken, damit sie haftet.",
   "Backe alles 15 bis 18 Minuten, bis die Kruste goldbraun und knusprig ist und sich der Fisch in Stücke teilen lässt. Serviere mit dem Kartoffelpüree."],
 "porcoes8": ["120 g Fisch · ½ Portion Püree",
              "150 g Fisch · 1 Portion Püree",
              "150 g Fisch · 1 Portion Püree",
              "170 g Fisch · 1 Portion Püree",
              "170 g Fisch · 1 Portion Püree",
              "200 g Fisch · 1 große Portion Püree",
              "220 g Fisch · große Portion Püree",
              "250 g Fisch · doppelte Portion Püree"],
 "dica": "Die Kräuterkruste mit etwas Paniermehl gibt Knusprigkeit ohne Frittieren und lässt den Fisch leicht und voller Geschmack. Weißer Fisch ist sehr mager und eiweißreich, und das Püree im richtigen Maß tröstet, ohne zu übertreiben — ein schönes, leichtes Abendessen.",
},
{
 "nome": "Gegrilltes Steak mit Kichererbsensalat",
 "hook": "Ein Steak auf den Punkt neben einem lauwarmen Kichererbsensalat — doppeltes Eiweiß, das abends sättigt, ohne schwer zu liegen.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 440,
 "ings": ["1 mageres Rindersteak (Oberschale oder Hüfte, ca. 120 g)", "80 g gekochte Kichererbsen",
          "½ Tomate in Würfeln", "rote Zwiebel, gehackt", "Blattsalat", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Würze das Steak von beiden Seiten mit Salz und Pfeffer.",
   "Erhitze eine beschichtete Pfanne bei hoher Hitze mit ein paar Tropfen Olivenöl. Brate das Steak 2 bis 3 Minuten je Seite, ohne daran zu rühren, bis es außen goldbraun und innen nach deinem Geschmack ist. Lass es 2 Minuten ruhen, bevor du es schneidest.",
   "Vermische in einer Schüssel die Kichererbsen, die Tomate, die rote Zwiebel und die Petersilie.",
   "Würze den Salat mit dem Olivenöl, dem Zitronensaft, Salz und Pfeffer.",
   "Serviere das aufgeschnittene Steak auf einem Bett aus Blattsalat, mit dem Kichererbsensalat daneben."],
 "porcoes8": ["100 g Fleisch · 55 g Kichererbsen · Salat",
              "120 g Fleisch · 80 g Kichererbsen · Salat",
              "130 g Fleisch · 80 g Kichererbsen · Salat",
              "150 g Fleisch · 110 g Kichererbsen · Salat",
              "150 g Fleisch · 110 g Kichererbsen · Salat",
              "170 g Fleisch · 125 g Kichererbsen · Salat",
              "200 g Fleisch · 165 g Kichererbsen · Salat",
              "220 g Fleisch · 165 g Kichererbsen · Salat"],
 "dica": "Die Kichererbsen ergänzen das Eiweiß aus dem Fleisch um Ballaststoffe und pflanzliches Eiweiß, das macht den Teller bei wenigen Kalorien sehr sättigend. Ein mageres Steak ohne Öl zu braten und mit frischem Salat zu servieren ist ein leichtes Abendessen voller Geschmack, das den Hunger stundenlang fernhält.",
},
{
 "nome": "Cremige Brokkolisuppe mit Hähnchen",
 "hook": "Schön grün, samtig und voller Geschmack — eine cremige Brokkolisuppe, die mit dem Hähnchen Körper bekommt und zum vollständigen Abendessen wird.",
 "tempo": "30 Min.", "rende": "3 Portionen", "kcal_base": 330,
 "ings": ["1 Kopf Brokkoli", "1 Hähnchenbrustfilet (ca. 150 g)", "1 kleine Kartoffel (macht es cremig)",
          "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer und Muskatnuss nach Geschmack", "1 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an.",
   "Gib die Kartoffel in Würfeln, das ganze Hähnchenfilet und das Wasser dazu. Koche alles 15 Minuten.",
   "Nimm das Hähnchen heraus, lass es lauwarm werden und zupfe es auseinander. Stelle es beiseite. Gib den Brokkoli (nur die Röschen) in den Topf und koche alles noch 5 Minuten, bis er weich, aber noch grün ist.",
   "Püriere die Suppe mit einem Pürierstab (dem Stab zum Mixen) oder im Mixer zu einer glatten Creme. Sei vorsichtig mit der heißen Flüssigkeit.",
   "Gib die Creme zurück in den Topf, füge das gezupfte Hähnchen dazu, würze mit Salz, Pfeffer und einem Hauch Muskatnuss und erwärme alles 3 Minuten. Serviere."],
 "porcoes8": ["1 Kelle · wenig Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · Hähnchen · 1 Scheibe Brot",
              "2 Kellen · extra Hähnchen · 1 Scheibe Brot",
              "3 Kellen · Hähnchen · 1 Scheibe Brot",
              "3 Kellen · extra Hähnchen · 2 Scheiben Brot",
              "3 große Kellen · doppelt Hähnchen · 2 Scheiben Brot"],
 "dica": "Brokkoli ist eines der nährstoffreichsten Gemüse mit den wenigsten Kalorien, und püriert wird daraus eine samtige Creme ganz ohne Sahne. Ein kleines Stück Kartoffel gibt die Cremigkeit, und das gezupfte Hähnchen ergänzt die Suppe um Eiweiß — so bleibt das Abendessen leicht und sättigend.",
},
{
 "nome": "Puten-Wrap mit Salat",
 "hook": "Scheiben von Putenbrust, frische Blätter und ein cremiger Klecks, in weiches Brot gerollt — ein leichtes Abendessen aus der Hand.",
 "tempo": "10 Min.", "rende": "1 Portion", "kcal_base": 360,
 "ings": ["1 Vollkorn-Tortilla", "4 Scheiben Putenbrust (magerer Aufschnitt)", "1 EL Hüttenkäse (oder leichter Frischkäse)",
          "Salatblätter", "½ Tomate in Scheiben", "geriebene Möhre", "Gurke in Streifen",
          "Salz, Pfeffer und Senf nach Geschmack"],
 "passos": [
   "Erwärme die Tortilla 20 Sekunden in einer Pfanne, nur damit sie weich und leicht zu rollen wird.",
   "Streiche den Hüttenkäse (oder den leichten Frischkäse) wie Butter auf die ganze Tortilla.",
   "Lege in die Mitte die Salatblätter, die Putenscheiben, die Tomate, die geriebene Möhre und die Gurke.",
   "Würze mit etwas Salz, Pfeffer und Senf.",
   "Klappe die Seiten nach innen und rolle den Wrap von unten nach oben fest zusammen. Schneide ihn diagonal durch und serviere."],
 "porcoes8": ["3 Scheiben Pute · ½ Tortilla · Salat",
              "4 Scheiben Pute · 1 Tortilla · Salat",
              "4 Scheiben Pute · 1 Tortilla · Salat",
              "5 Scheiben Pute · 1 Tortilla · Salat",
              "5 Scheiben Pute · 1 Tortilla · Salat",
              "6 Scheiben Pute · 1 große Tortilla · Salat",
              "6 Scheiben Pute · 2 Tortillas · Salat",
              "8 Scheiben Pute · 2 Tortillas · Salat"],
 "dica": "Putenbrust ist ein mageres, praktisches Fleisch voller Eiweiß. Wenn du den normalen Frischkäse durch Hüttenkäse oder eine leichte Variante ersetzt und den Wrap mit Blättern und Gemüse füllst, hast du ein leichtes, schnelles und sättigendes Abendessen, perfekt für Tage, an denen du nicht kochen willst.",
},
{
 "nome": "Hähnchentopf mit Gemüse",
 "hook": "Zarte Hähnchenstücke in einer dicken, gewürzten Brühe, mit Gemüse, das auf der Zunge zergeht — Topfküche, die guttut.",
 "tempo": "40 Min.", "rende": "3 Portionen", "kcal_base": 390,
 "ings": ["2 Hähnchenbrustfilets in Würfeln (ca. 300 g)", "1 Kartoffel in Würfeln", "1 Möhre in Scheiben",
          "1 Zucchini in Würfeln", "1 Tomate, gehackt", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt",
          "1 TL Olivenöl", "Salz, Pfeffer, Kurkuma und Kräuter nach Geschmack"],
 "passos": [
   "Würze die Hähnchenwürfel mit Salz, Pfeffer und etwas Kurkuma.",
   "Erhitze das Olivenöl in einem Topf und brate die Hähnchenwürfel 5 Minuten unter Rühren an. Gib die Zwiebel und den Knoblauch dazu und brate alles 2 Minuten.",
   "Füge die Tomate hinzu und rühre 2 Minuten, bis sie zu zerfallen beginnt.",
   "Gib die Kartoffel und die Möhre dazu und gieße mit Wasser auf (so viel, dass alles bedeckt ist). Würze mit Salz und koche alles 15 Minuten.",
   "Gib die Zucchini dazu und koche alles noch 8 Minuten, bis alles weich ist und die Brühe sämig wird. Streue die Kräuter darüber und serviere den Topf pur oder mit etwas Reis."],
 "porcoes8": ["½ Portion · ohne Reis",
              "1 Portion · ohne Reis",
              "1 Portion · 2 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 große Portion · 4 EL Reis",
              "große Portion · 5 EL Reis",
              "doppelte Portion · 5 EL Reis"],
 "dica": "Im Topf gart alles zusammen mit wenig Fett, und die Brühe vom Hähnchen würzt das Gemüse von selbst. Es ist ein kräftiges Gericht, das mit wenigen Kalorien sättigt, ideal für abends, weil es warm, wohltuend und gleichzeitig leicht ist.",
},
{
 "nome": "Thunfisch-Frikadellen mit Salat",
 "hook": "Aus Thunfisch aus der Dose gemacht, ist diese Frikadelle günstig, voller Eiweiß und im Nu fertig — ein leichtes, praktisches Abendessen.",
 "tempo": "20 Min.", "rende": "2 Portionen", "kcal_base": 380,
 "ings": ["2 Dosen Thunfisch in Wasser, abgetropft", "1 Ei", "3 EL Haferflocken", "½ Zwiebel, fein gehackt",
          "gehackte Petersilie", "1 TL Olivenöl", "Salz, Pfeffer und Saft von ½ Zitrone nach Geschmack",
          "Blattsalat, Tomate und Gurke für den Salat"],
 "passos": [
   "Lass den Thunfisch gut abtropfen und drücke ihn aus, um die Flüssigkeit zu entfernen. Vermische in einer Schüssel den Thunfisch, das Ei, die Haferflocken, die Zwiebel, die Petersilie, Salz, Pfeffer und den Zitronensaft.",
   "Zerdrücke alles mit einer Gabel, bis es bindet. Wenn die Masse zu weich ist, gib noch etwas Haferflocken dazu.",
   "Forme mit den Händen zwei Scheiben und drücke sie gut flach.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze. Lege die Frikadellen hinein und lass sie 4 Minuten je Seite braten, ohne daran zu rühren, bis sie goldbraun und fest sind. Wende sie vorsichtig.",
   "Serviere sie mit einem gut gefüllten Salat aus Blättern, Tomate und Gurke."],
 "porcoes8": ["1 Frikadelle · Salat",
              "1 Frikadelle · Salat",
              "1 Frikadelle · Salat · ½ Brötchen",
              "2 Frikadellen · Salat",
              "2 Frikadellen · Salat",
              "2 Frikadellen · Salat · 1 Brötchen",
              "2 Frikadellen · Salat · 1 Brötchen",
              "3 Frikadellen · Salat · 1 Brötchen"],
 "dica": "Thunfisch aus der Dose ist eine günstige und praktische Eiweißquelle, und mit Ei und Haferflocken gebunden (statt mit viel Brot) wird daraus eine magere, sättigende Frikadelle. Ohne Frittieren gebraten und mit reichlich Salat serviert ist das ein leichtes, günstiges Abendessen, das den Bauch füllt.",
},
{
 "nome": "Schmorbraten aus dem Topf mit Gemüse",
 "hook": "Ein Stück Fleisch, das langsam gart, bis es zerfällt, mit Gemüse, das sich mit der Brühe vollsaugt — das Sonntagsessen, im richtigen Maß.",
 "tempo": "1 Std. 20 Min.", "rende": "3 Portionen", "kcal_base": 440,
 "ings": ["400 g mageres Rindfleisch am Stück (Wade, Oberschale oder Schwanzstück)", "2 Möhren in großen Stücken",
          "2 Kartoffeln in großen Stücken", "1 Zwiebel in Spalten", "2 Knoblauchzehen", "1 Tomate, gehackt",
          "1 Lorbeerblatt", "1 TL Olivenöl", "Salz, Pfeffer und Rosmarin nach Geschmack"],
 "passos": [
   "Würze das Fleischstück mit Salz und Pfeffer. Erhitze das Olivenöl in einem tiefen Topf und brate das Fleisch rundherum an, dabei drehen, etwa 6 Minuten lang (dieses Anbraten gibt der Brühe sehr viel Geschmack).",
   "Gib die Zwiebel, den Knoblauch und die Tomate dazu und brate alles 2 Minuten. Füge das Lorbeerblatt hinzu und gieße heißes Wasser an, bis das Fleisch zur Hälfte bedeckt ist.",
   "Decke den Topf ab und schmore alles 50 Minuten bei kleiner Hitze, dabei das Fleisch nach der Hälfte der Zeit wenden. Wenn das Wasser zu stark einkocht, gieße etwas heißes Wasser nach.",
   "Gib die Möhren und die Kartoffeln dazu und koche alles noch 25 Minuten, bis das Fleisch so zart ist, dass es zerfällt, und das Gemüse gar ist.",
   "Nimm das Lorbeerblatt heraus. Schneide oder zupfe das Fleisch und serviere es mit dem Gemüse und der Brühe darüber."],
 "porcoes8": ["½ Portion Fleisch · Gemüse",
              "1 Portion Fleisch · Gemüse",
              "1 Portion Fleisch · Gemüse",
              "1 Portion · Gemüse · 1 extra Kartoffel",
              "1 Portion · Gemüse · 1 extra Kartoffel",
              "1 große Portion · Gemüse",
              "große Portion · Gemüse · extra Kartoffel",
              "doppelte Portion · Gemüse"],
 "dica": "Das langsame Garen macht magere und günstige Stücke zart, ganz ohne Fett, und die entstehende Brühe würzt das Gemüse von selbst. Mit abgemessenem Fleisch und viel Gemüse serviert ist das ein wohltuendes Wochenendgericht, das genau in die Diät passt.",
},
{
 "nome": "Mit Ricotta und Spinat gefülltes Hähnchen",
 "hook": "Das Hähnchenfilet öffnet sich wie eine Tasche und bewahrt eine cremige Füllung aus Ricotta und Spinat — überraschend, saftig und leicht.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 400,
 "ings": ["2 dicke Hähnchenbrustfilets (ca. 300 g)", "4 EL Ricotta", "1 große Handvoll Spinat",
          "1 Knoblauchzehe, gehackt", "1 TL Olivenöl", "Saft von ½ Zitrone",
          "Salz, Pfeffer und Muskatnuss nach Geschmack", "Zahnstocher"],
 "passos": [
   "Erhitze ein paar Tropfen Olivenöl in einer Pfanne und brate den Spinat mit dem Knoblauch 1 Minute an, nur bis die Blätter zusammenfallen. Lass ihn abkühlen und hacke ihn.",
   "Vermische in einer Schüssel den Ricotta, den gehackten Spinat, Salz, Pfeffer und einen Hauch Muskatnuss zu einer cremigen Füllung.",
   "Schneide mit einem Messer seitlich in jedes Filet und öffne so eine Tasche (schneide nicht ganz durch). Würze das Hähnchen mit Salz, Pfeffer und dem Zitronensaft.",
   "Fülle die Taschen mit der Ricottamischung und verschließe die Öffnung mit ein oder zwei Zahnstochern.",
   "Erhitze das restliche Olivenöl in einer Pfanne bei mittlerer Hitze und brate die Filets 5 bis 6 Minuten je Seite, bis sie goldbraun und innen gar sind. Ziehe die Zahnstocher vor dem Servieren heraus und reiche einen Salat dazu."],
 "porcoes8": ["1 kleines Filet · Salat",
              "1 Filet · Salat",
              "1 Filet · Salat · 2 EL Reis",
              "1 großes Filet · Salat · 2 EL Reis",
              "1 großes Filet · Salat · 3 EL Reis",
              "1 großes Filet · Salat · 4 EL Reis",
              "2 Filets · Salat · 4 EL Reis",
              "2 Filets · Salat · 5 EL Reis"],
 "dica": "Ricotta ist ein magerer, cremiger Käse, voller Eiweiß und mit wenig Fett, ideal zum Füllen, ohne dass es schwer wird. Der Spinat bringt Ballaststoffe und Nährstoffe für fast keine Kalorien. Heraus kommt ein saftiges, edles Hähnchen, leicht genug für den Abend.",
},
{
 "nome": "Fischsuppe mit Gemüse",
 "hook": "Eine duftende Brühe mit Stücken von weißem Fisch und Gemüse — leicht, voller Meeresgeschmack und wohltuend an einem kalten Abend.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 340,
 "ings": ["400 g Filet vom weißen Fisch in Stücken (Seehecht oder Kabeljau)", "1 Kartoffel in Würfeln", "1 Möhre in Würfeln",
          "1 Tomate, gehackt", "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer, Koriander oder Petersilie nach Geschmack", "1,2 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten an. Gib die Tomate dazu und rühre noch 2 Minuten, bis sie zerfällt.",
   "Gieße das Wasser an und gib die Kartoffel und die Möhre dazu. Würze mit Salz und Pfeffer und koche alles 15 Minuten, bis das Gemüse weich ist.",
   "Gib die Fischstücke dazu (Fisch gart schnell, deshalb kommt er zum Schluss) und koche alles 6 bis 8 Minuten, nur bis der Fisch weiß und zart ist, ohne zu sehr zu zerfallen.",
   "Gib den Zitronensaft dazu und schmecke mit Salz ab.",
   "Streue Koriander oder Petersilie darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["1 Kelle · Fisch",
              "2 Kellen · Fisch",
              "2 Kellen · Fisch",
              "2 Kellen · Fisch · 1 Scheibe Brot",
              "2 Kellen · extra Fisch · 1 Scheibe Brot",
              "3 Kellen · Fisch · 1 Scheibe Brot",
              "3 Kellen · extra Fisch · 2 Scheiben Brot",
              "3 große Kellen · doppelt Fisch · 2 Scheiben Brot"],
 "dica": "Weißer Fisch ist sehr mager und gart in Minuten, so bleibt die Suppe leicht und voller Eiweiß. Die Brühe mit Gemüse füllt den Magen mit sehr wenigen Kalorien, und der Spritzer Zitrone hebt den Geschmack, ohne dass viel Salz nötig ist — ein warmes, leichtes Abendessen.",
},
{
 "nome": "Putenschnitzel in Champignonsoße",
 "hook": "Dünne Putenscheiben in einer cremigen Pilzsoße — ein Abendessen, das teuer wirkt, aber mit wenig Fett in zwanzig Minuten gemacht ist.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 400,
 "ings": ["2 dünne Putenbrustfilets (ca. 300 g)", "70 g Champignonscheiben", "1 Zwiebel, gehackt",
          "1 Knoblauchzehe, gehackt", "3 EL Naturjoghurt ohne Zucker", "1 TL Olivenöl",
          "Salz, Pfeffer und Petersilie nach Geschmack", "Reis oder Püree zum Servieren"],
 "passos": [
   "Würze die dünnen Putenfilets mit Salz und Pfeffer.",
   "Erhitze eine beschichtete Pfanne mit der Hälfte des Olivenöls bei mittlerer bis hoher Hitze und brate die Filets 2 bis 3 Minuten je Seite, bis sie goldbraun und gar sind. Nimm sie heraus und stelle sie beiseite.",
   "Brate in derselben Pfanne mit dem restlichen Olivenöl die Zwiebel und den Knoblauch 2 Minuten an. Gib die Champignons dazu und koche sie 4 Minuten, bis sie zusammenfallen und ihr Wasser abgeben.",
   "Stelle die Hitze klein, nimm die Pfanne vom Herd und rühre den Joghurt unter — vom Herd genommen gerinnt er nicht (bildet keine Klümpchen). Schmecke mit Salz und Pfeffer ab.",
   "Gib die Filets zurück in die Pfanne, damit sie sich mit der Soße überziehen. Streue Petersilie darüber und serviere mit etwas Reis oder Püree."],
 "porcoes8": ["1 Filet · 2 EL Reis",
              "1 Filet · 3 EL Reis",
              "1 großes Filet · 3 EL Reis",
              "1 großes Filet · 4 EL Reis",
              "1 großes Filet · 4 EL Reis",
              "2 Filets · 4 EL Reis",
              "2 Filets · 5 EL Reis",
              "2 Filets · 6 EL Reis"],
 "dica": "Pute ist ein mageres, eiweißreiches weißes Fleisch. Die cremige Soße kommt aus dem Joghurt, nicht aus Sahne, das spart sehr viel Fett. Die Champignons geben kräftigen Geschmack und Körper bei sehr wenigen Kalorien — ein edles und leichtes Abendessen.",
},
{
 "nome": "Eier im Ofen in Tomatensoße mit Hähnchen",
 "hook": "Eier, die in einer gewürzten Tomatensoße garen, mit Hähnchenstückchen — ein warmes, anderes Abendessen, direkt aus der Pfanne auf den Tisch.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 370,
 "ings": ["4 Eier", "1 gekochtes, gezupftes Hähnchenbrustfilet (ca. 120 g)", "3 reife Tomaten, gehackt (oder Tomatensoße)",
          "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt", "½ Paprika, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer, Paprikapulver und Kräuter nach Geschmack", "Vollkornbrot zum Servieren"],
 "passos": [
   "Erhitze das Olivenöl in einer ofenfesten (oder tiefen) Pfanne und brate die Zwiebel, den Knoblauch und die Paprika 3 Minuten unter Rühren an.",
   "Gib die gehackten Tomaten, das Paprikapulver, Salz und Pfeffer dazu und koche alles 8 Minuten, bis eine kräftige Soße entsteht. Rühre das gezupfte Hähnchen unter.",
   "Drücke mit einem Löffel kleine Mulden in die Soße. Schlage in jede Mulde ein Ei, ohne zu rühren, damit die Eigelbe ganz bleiben.",
   "Decke die Pfanne ab und gare alles 6 bis 8 Minuten bei kleiner Hitze, bis das Eiweiß fest ist und die Eigelbe so sind, wie du sie magst. (Oder schiebe die Pfanne 10 Minuten in den mittelheißen Ofen.)",
   "Streue die Kräuter darüber und serviere direkt aus der Pfanne, mit Scheiben Vollkornbrot dazu."],
 "porcoes8": ["1 Ei · Hähnchen · Soße",
              "2 Eier · Hähnchen · Soße",
              "2 Eier · Hähnchen · 1 Scheibe Brot",
              "2 Eier · extra Hähnchen · 1 Scheibe Brot",
              "2 Eier · extra Hähnchen · 1 Scheibe Brot",
              "2 Eier · Hähnchen · 2 Scheiben Brot",
              "3 Eier · extra Hähnchen · 2 Scheiben Brot",
              "3 Eier · doppelt Hähnchen · 2 Scheiben Brot"],
 "dica": "Eier sind vollwertiges Eiweiß und machen sehr satt, und in der Tomatensoße gegart bleiben sie leicht, ganz ohne Frittieren. Das Hähnchen bringt noch mehr Eiweiß, und die Soße füllt den Teller mit dem Volumen der Tomaten. Ein warmes, günstiges und wohltuendes Abendessen, das gut sättigt.",
},
{
 "nome": "Garnelen-Gemüse-Spieße",
 "hook": "Rosige Garnelen und buntes Gemüse zusammen aufgespießt und goldbraun gegrillt — leicht, schön und mit Festtagsstimmung.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 360,
 "ings": ["250 g geputzte große Garnelen", "1 Paprika in Quadraten", "1 Zwiebel in Stücken",
          "1 Zucchini in dicken Scheiben", "Kirschtomaten", "2 Knoblauchzehen, gehackt", "1 TL Olivenöl",
          "Saft von 1 Zitrone", "Salz, Pfeffer und Paprikapulver nach Geschmack", "Schaschlikspieße"],
 "passos": [
   "Würze die Garnelen mit Salz, Pfeffer, Paprikapulver, dem Knoblauch und dem Zitronensaft. Lass sie 10 Minuten Geschmack annehmen.",
   "Stecke die Spieße und wechsle dabei ab: eine Garnele, ein Quadrat Paprika, ein Stück Zwiebel, eine Scheibe Zucchini und eine Kirschtomate, bis der Spieß voll ist.",
   "Bestreiche die Spieße mit dem Olivenöl.",
   "Erhitze eine große Pfanne oder eine Grillpfanne bei mittlerer bis hoher Hitze. Lege die Spieße hinein und drehe sie alle 2 Minuten, insgesamt etwa 8 Minuten, nur bis die Garnelen rosa werden und sich einrollen. Lass sie nicht zu lange braten, sonst werden sie gummiartig.",
   "Serviere die Spieße mit einem Salat oder etwas Reis."],
 "porcoes8": ["1 Spieß · Salat",
              "2 Spieße · Salat",
              "2 Spieße · Salat · 2 EL Reis",
              "2 Spieße · Salat · 3 EL Reis",
              "2 Spieße · Salat · 3 EL Reis",
              "3 Spieße · Salat · 3 EL Reis",
              "3 Spieße · Salat · 4 EL Reis",
              "3 große Spieße · Salat · 4 EL Reis"],
 "dica": "Garnelen bestehen fast nur aus Eiweiß, mit sehr wenig Fett und wenigen Kalorien. Mit buntem Gemüse aufgespießt und ohne Öl gegrillt wird daraus ein leichtes, ansehnliches und schmackhaftes Abendessen, das die Portion ganz von selbst im Rahmen hält und sogar zu besonderen Anlässen passt.",
},
{
 "nome": "Gegrillter Lachs mit Spargel",
 "hook": "Zwei Stars auf einem Teller: der saftige Lachs und der bissfeste Spargel — ein schickes, leichtes Abendessen in fünfzehn Minuten.",
 "tempo": "18 Min.", "rende": "1 Portion", "kcal_base": 420,
 "ings": ["1 Lachsfilet (ca. 150 g)", "1 Bund Spargel", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Zitronenschale nach Geschmack"],
 "passos": [
   "Wasche den Spargel und brich das harte untere Ende von jeder Stange ab (sie bricht beim Biegen von selbst an der richtigen Stelle).",
   "Würze den Lachs mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft.",
   "Erhitze eine beschichtete Pfanne mit der Hälfte des Olivenöls bei mittlerer Hitze. Lege den Lachs mit der Hautseite nach unten hinein und lass ihn 4 Minuten braten, wende ihn und lass ihn weitere 3 Minuten, bis er heller wird und sich in Stücke teilen lässt.",
   "Brate gleichzeitig in einer zweiten Pfanne (oder in derselben, nachdem du den Lachs herausgenommen hast) den Spargel mit dem restlichen Olivenöl bei hoher Hitze 4 Minuten unter Rühren an, bis er grün und weich, aber noch bissfest ist.",
   "Richte den Teller mit dem Lachs und dem Spargel an. Streue zum Schluss etwas Zitronenschale darüber."],
 "porcoes8": ["120 g Lachs · Spargel",
              "150 g Lachs · Spargel",
              "150 g Lachs · Spargel · 1 kleine Kartoffel",
              "170 g Lachs · Spargel · 1 Kartoffel",
              "170 g Lachs · Spargel · 1 Kartoffel",
              "200 g Lachs · Spargel · 1 Kartoffel",
              "220 g Lachs · Spargel · 1 große Kartoffel",
              "250 g Lachs · Spargel · 2 kleine Kartoffeln"],
 "dica": "Der Lachs bringt Eiweiß und Omega-3, das gute Fett, das sättigt und das Herz schützt. Spargel ist leicht, reich an Ballaststoffen und hilft beim Entwässern, bei sehr wenigen Kalorien. Zusammen mit wenig Öl gebraten ergeben sie ein elegantes, leichtes und nahrhaftes Abendessen.",
},
{
 "nome": "Hackpfanne mit Zucchini",
 "hook": "Eine schnelle Hackpfanne mit Zucchini und einem Ei obendrauf — in Minuten gemacht, sättigt auch ohne Reis.",
 "tempo": "20 Min.", "rende": "2 Portionen", "kcal_base": 380,
 "ings": ["250 g mageres Rinderhackfleisch", "2 Zucchini in kleinen Würfeln", "1 Tomate, gehackt", "1 Zwiebel, gehackt",
          "1 Knoblauchzehe, gehackt", "2 Eier", "1 TL Olivenöl", "Salz, Pfeffer und Kräuter nach Geschmack"],
 "passos": [
   "Erhitze das Olivenöl in einer Pfanne bei mittlerer Hitze und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an.",
   "Gib das Hackfleisch dazu und rühre, dabei die Klumpen mit dem Löffel zerteilen, bis nichts mehr rosa ist.",
   "Füge die Tomate und die Zucchiniwürfel hinzu, würze mit Salz und Pfeffer und koche alles 8 Minuten unter gelegentlichem Rühren, bis die Zucchini weich ist und ihren eigenen Saft abgibt.",
   "Brate oder koche währenddessen die Eier separat (brate sie mit ganz wenig Öl oder koche sie 6 Minuten für ein weiches Eigelb).",
   "Serviere die Hackpfanne heiß mit einem Ei auf jeder Portion und den Kräutern darüber."],
 "porcoes8": ["½ Portion · 1 Ei",
              "1 Portion · 1 Ei",
              "1 Portion · 1 Ei · 2 EL Reis",
              "1 Portion · 1 Ei · 3 EL Reis",
              "1 Portion · 2 Eier · 3 EL Reis",
              "1 große Portion · 2 Eier · 3 EL Reis",
              "große Portion · 2 Eier · 4 EL Reis",
              "doppelte Portion · 2 Eier · 4 EL Reis"],
 "dica": "Die gewürfelte Zucchini mischt sich unter das Fleisch und gibt dem Gericht Volumen bei sehr wenigen Kalorien, so isst du weniger Fleisch, ohne es zu vermissen. Das Ei obendrauf bringt Eiweiß und Cremigkeit. Ohne Reis oder mit wenig davon ist das ein leichtes, schnelles und sehr sättigendes Abendessen.",
},
{
 "nome": "Hähnchen nach Pizza-Art mit Salat",
 "hook": "Der Pizzageschmack ohne den Teig: das gegrillte Hähnchen bekommt Tomatensoße, geschmolzenen Käse und Oregano — stillt die Lust, ohne schwer zu liegen.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 400,
 "ings": ["2 Hähnchenbrustfilets (ca. 300 g)", "120 ml selbst gemachte Tomatensoße", "3 EL geriebener magerer Mozzarella",
          "Tomatenscheiben", "1 TL Olivenöl", "Oregano, Salz und Pfeffer nach Geschmack",
          "Blattsalat für den Salat"],
 "passos": [
   "Würze die Hähnchenfilets mit Salz und Pfeffer.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze und brate die Filets 4 bis 5 Minuten je Seite, bis sie goldbraun und innen weiß sind.",
   "Stelle die Hitze klein. Bedecke jedes Filet mit der Tomatensoße, ein oder zwei Tomatenscheiben und dem geriebenen Mozzarella. Streue Oregano darüber.",
   "Decke die Pfanne ab und lass alles 3 bis 4 Minuten stehen, nur bis der Käse schmilzt (das ist der Trick zum Überbacken ohne Ofen).",
   "Serviere mit einem frischen grünen Salat daneben."],
 "porcoes8": ["100 g Hähnchen · wenig Käse · Salat",
              "130 g Hähnchen · Käse · Salat",
              "150 g Hähnchen · Käse · Salat",
              "150 g Hähnchen · Käse · 2 EL Reis",
              "150 g Hähnchen · Käse · 3 EL Reis",
              "170 g Hähnchen · Käse · 3 EL Reis",
              "200 g Hähnchen · Käse · 4 EL Reis",
              "220 g Hähnchen · extra Käse · 4 EL Reis"],
 "dica": "Du stillst die Lust auf Pizza mit dem Geschmack von Tomatensoße, Käse und Oregano, aber ohne den Teig und ohne das Fett. Das gegrillte Hähnchen bringt mageres Eiweiß und Sättigung, und etwas geschmolzener Käse reicht für das Vergnügen des Überbackenen. Leicht und befriedigend.",
},
{
 "nome": "Gebratener Fisch mit Gemüse aus der Pfanne",
 "hook": "Alles in einer Pfanne: Der Fisch brät auf der einen Seite, während das Gemüse auf der anderen springt — leichtes Abendessen, schnell und ohne Chaos.",
 "tempo": "20 Min.", "rende": "1 Portion", "kcal_base": 380,
 "ings": ["1 Filet vom weißen Fisch (Seehecht, Kabeljau oder Tilapia, ca. 150 g)", "1 Zucchini in Halbmonden",
          "½ Paprika in Streifen", "Kirschtomaten", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Würze den Fisch mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft.",
   "Erhitze eine große Pfanne mit der Hälfte des Olivenöls bei mittlerer bis hoher Hitze. Lege das Filet auf eine Seite und lass es 3 bis 4 Minuten je Seite braten, dabei vorsichtig wenden, bis es goldbraun ist und sich in Stücke teilen lässt.",
   "Gib auf die andere Seite der Pfanne (oder nachdem du den Fisch herausgenommen hast) das restliche Olivenöl und brate die Zucchini, die Paprika und die Kirschtomaten 4 bis 5 Minuten unter Rühren an, bis sie weich, aber noch fest sind.",
   "Würze das Gemüse mit Salz und Pfeffer.",
   "Richte den Teller mit dem Fisch und dem gebratenen Gemüse an. Streue Petersilie darüber und gib zum Schluss noch etwas Zitrone dazu."],
 "porcoes8": ["120 g Fisch · Gemüse",
              "150 g Fisch · Gemüse",
              "150 g Fisch · Gemüse · 1 kleine Kartoffel",
              "170 g Fisch · Gemüse · 1 Kartoffel",
              "170 g Fisch · Gemüse · 1 Kartoffel",
              "200 g Fisch · Gemüse · 1 Kartoffel",
              "220 g Fisch · Gemüse · 1 große Kartoffel",
              "250 g Fisch · Gemüse · 2 kleine Kartoffeln"],
 "dica": "Weißer Fisch ist leicht und gart in Minuten, und in derselben Pfanne wie das Gemüse zubereitet braucht er sehr wenig Öl. Das gebratene Gemüse gibt Farbe, Ballaststoffe und Volumen für fast keine Kalorien. Es ist eines der schnellsten, leichtesten und praktischsten Abendessen überhaupt.",
},
{
 "nome": "Gegrillte Putenbrust mit Kürbispüree",
 "hook": "Die magere Pute auf einem von Natur aus süßlichen, orangen Kürbispüree — ein leichtes Abendessen mit einer wohltuenden Note.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 390,
 "ings": ["1 Putenbrustfilet (ca. 150 g)", "1 Stück Kürbis in Würfeln (ca. 300 g)", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer, Salbei oder Rosmarin nach Geschmack",
          "Blattsalat für den Salat"],
 "passos": [
   "Koche den Kürbis 15 Minuten in kochendem Wasser, bis er ganz weich ist. Lass ihn sehr gut abtropfen und zerdrücke ihn mit einer Gabel und einer Prise Salz zu einem glatten, cremigen Püree.",
   "Würze die Pute mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer Hitze und brate das Filet 3 bis 4 Minuten je Seite, bis es goldbraun und innen weiß ist.",
   "Wenn du magst, gib in den letzten Sekunden etwas Salbei oder Rosmarin in die Pfanne, damit die Pute Aroma annimmt.",
   "Richte den Teller mit dem Kürbispüree an, lege die aufgeschnittene Pute darauf und gib einen grünen Salat daneben."],
 "porcoes8": ["120 g Pute · ½ Portion Püree · Salat",
              "150 g Pute · 1 Portion Püree · Salat",
              "150 g Pute · 1 Portion Püree · Salat",
              "170 g Pute · 1 Portion Püree · Salat",
              "170 g Pute · 1 Portion Püree · Salat",
              "200 g Pute · 1 große Portion Püree · Salat",
              "220 g Pute · große Portion Püree · Salat",
              "250 g Pute · doppelte Portion Püree · Salat"],
 "dica": "Putenbrust ist noch magerer als Hähnchen und steckt voller Eiweiß. Der Kürbis ergibt ein cremiges, süßliches Püree mit sehr wenigen Kalorien, das die Lust auf Süßes stillt und den Teller mit Ballaststoffen füllt. Ein leichtes, wohltuendes und buntes Abendessen.",
},
{
 "nome": "Hühnersuppe mit Nudeln",
 "hook": "Die Hühnersuppe wie immer, verstärkt mit reichlich Hähnchen und Gemüse — das Abendessen, das umarmt, heilt und trotzdem in die Diät passt.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 360,
 "ings": ["1 Hähnchenbrustfilet (ca. 150 g)", "50 g kleine Nudeln (Suppennudeln oder Ringelnudeln)",
          "1 Möhre in kleinen Würfeln", "1 Stange Staudensellerie, gehackt (nach Wunsch)", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack", "1,2 Liter Wasser"],
 "passos": [
   "Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten unter Rühren an.",
   "Gib das ganze Hähnchenfilet, die Möhre, den Sellerie und das Wasser dazu. Würze mit Salz und koche alles 15 Minuten, bis das Hähnchen gar ist.",
   "Nimm das Hähnchen heraus, lass es lauwarm werden und zupfe es auseinander. Gib das gezupfte Hähnchen zurück in den Topf.",
   "Gib die kleinen Nudeln dazu und koche alles noch 8 bis 10 Minuten, bis die Nudeln weich sind (rühre ab und zu um, damit nichts am Boden ansetzt).",
   "Schmecke mit Salz ab, streue die Kräuter darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["1 Kelle · Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · Hähnchen",
              "2 Kellen · extra Hähnchen",
              "2 Kellen · extra Hähnchen · extra Nudeln",
              "3 Kellen · Hähnchen",
              "3 Kellen · extra Hähnchen · extra Nudeln",
              "3 große Kellen · doppelt Hähnchen"],
 "dica": "Die Hühnersuppe ist leicht und wohltuend: Die Brühe mit Gemüse füllt den Magen mit wenigen Kalorien, und das Hähnchen bringt das Eiweiß, das sättigt. Mit wenigen Nudeln und viel Hähnchen und Gemüse wird sie zu einem vollständigen, warmen Abendessen, ideal für kalte Abende oder Tage ohne Appetit.",
},
{
 "nome": "Garnelen in leichtem Curry mit Gemüse",
 "hook": "Garnelen, umhüllt von einer goldenen Soße aus Curry und leichter Kokosmilch — duftend, cremig und überraschend leicht.",
 "tempo": "25 Min.", "rende": "2 Portionen", "kcal_base": 380,
 "ings": ["300 g geputzte Garnelen", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt", "1 Paprika in Streifen",
          "1 TL Currypulver", "120 ml leichte Kokosmilch", "1 Tomate, gehackt",
          "1 TL Olivenöl", "Saft von ½ Zitrone", "Salz, Pfeffer und Koriander nach Geschmack", "Reis zum Servieren"],
 "passos": [
   "Würze die Garnelen mit Salz, Pfeffer und dem Zitronensaft. Lass sie 5 Minuten Geschmack annehmen.",
   "Erhitze das Olivenöl in einer Pfanne bei mittlerer Hitze und brate die Zwiebel, den Knoblauch und die Paprika 3 Minuten unter Rühren an.",
   "Gib das Currypulver dazu und rühre 30 Sekunden, damit das Gewürz sein Aroma abgibt. Füge die Tomate hinzu und koche sie 3 Minuten, bis sie zerfällt.",
   "Gieße die leichte Kokosmilch an und lass alles leicht aufkochen. Gib die Garnelen hinein und koche sie 3 bis 4 Minuten, nur bis sie rosa sind. Koche sie nicht zu lange, sonst werden sie gummiartig.",
   "Streue Koriander darüber und serviere alles über einer kleinen Portion Reis."],
 "porcoes8": ["120 g Garnelen · 2 EL Reis",
              "150 g Garnelen · 3 EL Reis",
              "150 g Garnelen · 3 EL Reis",
              "170 g Garnelen · 4 EL Reis",
              "170 g Garnelen · 4 EL Reis",
              "200 g Garnelen · 4 EL Reis",
              "220 g Garnelen · 5 EL Reis",
              "250 g Garnelen · 5 EL Reis"],
 "dica": "Garnelen sind fast reines Eiweiß und garen schnell. Leichte Kokosmilch macht die Soße cremig mit deutlich weniger Fett als Sahne, und das Curry duftet und lässt das Gericht besonders wirken. Mit wenig Reis ist das ein leichtes Abendessen voller Geschmack.",
},
{
 "nome": "Rindfleischtopf mit Kartoffeln",
 "hook": "Fleischwürfel, die in einer dicken Brühe mit Kartoffeln zerfallen — der Eintopf, der an einem kalten Abend tröstet, in der richtigen Portion.",
 "tempo": "1 Std.", "rende": "3 Portionen", "kcal_base": 430,
 "ings": ["300 g mageres Rindfleisch in Würfeln (Wade oder mageres Schulterstück)", "2 Kartoffeln in großen Würfeln", "1 Möhre in Scheiben",
          "1 Zwiebel, gehackt", "2 Knoblauchzehen, gehackt", "1 Tomate, gehackt", "1 Lorbeerblatt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack"],
 "passos": [
   "Würze die Fleischwürfel mit Salz und Pfeffer. Erhitze das Olivenöl in einem Topf und brate das Fleisch unter Rühren 6 Minuten rundherum an.",
   "Gib die Zwiebel und den Knoblauch dazu und brate alles 2 Minuten. Füge die Tomate und das Lorbeerblatt hinzu und rühre 2 Minuten.",
   "Gieße mit heißem Wasser auf, decke den Topf ab und schmore alles 35 Minuten bei kleiner Hitze, bis das Fleisch weicher wird. Wenn es zu trocken wird, gieße heißes Wasser nach.",
   "Gib die Kartoffel und die Möhre dazu und koche alles noch 20 Minuten, bis das Fleisch zerfällt und die Kartoffel weich ist (die Kartoffel hilft, die Brühe zu binden).",
   "Nimm das Lorbeerblatt heraus, streue die Kräuter darüber und serviere den Topf warm, pur oder mit etwas Reis."],
 "porcoes8": ["½ Portion · ohne Reis",
              "1 Portion · ohne Reis",
              "1 Portion · 2 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 Portion · 3 EL Reis",
              "1 große Portion · 4 EL Reis",
              "große Portion · 5 EL Reis",
              "doppelte Portion · 5 EL Reis"],
 "dica": "Das langsame Garen macht magere und günstige Stücke zart, und die Kartoffel bindet die Brühe von selbst, Mehl oder Sahne sind überflüssig. Es ist ein kräftiges Gericht, das mit kontrollierten Kalorien gut sättigt — der Trost eines Eintopfs, ohne aus der Spur zu geraten.",
},
{
 "nome": "Ofenomelett mit magerem Schinken und Gemüse",
 "hook": "Ein hohes, lockeres Omelett aus dem Ofen, gefüllt mit Gemüse und magerem Schinken — du schneidest es in Stücke und es reicht für die ganze Familie.",
 "tempo": "30 Min.", "rende": "3 Portionen", "kcal_base": 360,
 "ings": ["6 Eier", "4 Scheiben magerer Putenschinken, gehackt", "½ Paprika, gehackt", "1 Tomate, gehackt",
          "1 Handvoll Spinat", "2 EL magerer geriebener Käse", "1 TL Olivenöl",
          "Schnittlauch, Salz und Pfeffer nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Bestreiche eine kleine Auflaufform mit dem Olivenöl.",
   "Verquirle die Eier in einer Schüssel 30 Sekunden mit Salz und Pfeffer.",
   "Gib den gehackten Schinken, die Paprika, die Tomate, den Spinat und den Schnittlauch zu den Eiern und vermische alles.",
   "Gieße die Masse in die Form und streue den geriebenen Käse darüber.",
   "Backe alles 20 bis 25 Minuten, bis das Omelett aufgeht, in der Mitte fest wird und oben leicht goldbraun ist. Schneide es in Stücke und serviere es warm oder lauwarm, mit einem Salat."],
 "porcoes8": ["1 Stück · Salat",
              "1 großes Stück · Salat",
              "1 großes Stück · Salat · 1 Scheibe Brot",
              "2 Stücke · Salat · 1 Scheibe Brot",
              "2 Stücke · Salat · 1 Scheibe Brot",
              "2 große Stücke · Salat · 1 Scheibe Brot",
              "2 große Stücke · Salat · 2 Scheiben Brot",
              "3 Stücke · Salat · 2 Scheiben Brot"],
 "dica": "Eier sind vollwertiges Eiweiß und machen sehr satt, und im Ofen gebacken kommen sie ohne Frittieren aus. Der magere Putenschinken bringt Geschmack und Eiweiß bei wenig Fett, und das Gemüse gibt Volumen und Ballaststoffe. Es reicht weit, hält sich gut und ist ein leichtes, praktisches Abendessen.",
},
{
 "nome": "Tilapia aus dem Ofen mit Tomate und Zwiebel",
 "hook": "Filets von weißem Fisch, gebacken unter einem Bett aus Tomate und Zwiebel, die zu einer natürlichen Soße werden — leicht, saftig und ohne Mühe.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 370,
 "ings": ["2 Tilapiafilets (oder ein anderer weißer Fisch, ca. 300 g)", "2 Tomaten in Scheiben", "1 Zwiebel in Ringen",
          "1 Knoblauchzehe in Scheiben", "1 TL Olivenöl", "Saft von 1 Zitrone",
          "Salz, Pfeffer, Oregano und Petersilie nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 200 °C vor. Verteile die Hälfte der Tomaten- und Zwiebelscheiben als Bett auf dem Boden einer Auflaufform.",
   "Würze die Fischfilets mit Salz, Pfeffer, dem Knoblauch, dem Oregano und dem Zitronensaft. Lege sie auf das Bett aus Tomate und Zwiebel.",
   "Bedecke die Filets mit der restlichen Tomate und Zwiebel und beträufle alles mit dem Olivenöl.",
   "Backe alles 20 bis 25 Minuten, bis sich der Fisch in Stücke teilen lässt und Tomate und Zwiebel weich sind und eine natürliche Soße abgeben.",
   "Streue Petersilie darüber und serviere mit der Soße obendrauf, dazu einen Salat oder etwas Reis."],
 "porcoes8": ["120 g Fisch · Gemüse",
              "150 g Fisch · Gemüse",
              "150 g Fisch · Gemüse · 2 EL Reis",
              "170 g Fisch · Gemüse · 3 EL Reis",
              "170 g Fisch · Gemüse · 3 EL Reis",
              "200 g Fisch · Gemüse · 3 EL Reis",
              "220 g Fisch · Gemüse · 4 EL Reis",
              "250 g Fisch · Gemüse · 4 EL Reis"],
 "dica": "Weißer Fisch ist sehr mager und eiweißreich, und unter Tomate und Zwiebel gebacken entsteht eine natürliche Soße ohne Fett, die das Filet saftig hält. Ein leichtes, günstiges und geschmackvolles Abendessen, das sich im Ofen praktisch von selbst macht.",
},
{
 "nome": "Hähnchenbällchen in der Suppe",
 "hook": "Weiche Hähnchenbällchen, gegart in einer leichten Brühe mit Gemüse — eine schöne, vollständige Suppe, die sättigt und wärmt.",
 "tempo": "35 Min.", "rende": "3 Portionen", "kcal_base": 350,
 "ings": ["300 g Hähnchenhackfleisch", "1 Ei", "2 EL Haferflocken", "1 Möhre in kleinen Würfeln",
          "1 Kartoffel in kleinen Würfeln", "1 Zucchini in kleinen Würfeln", "1 Zwiebel, gehackt", "1 Knoblauchzehe, gehackt",
          "1 TL Olivenöl", "Salz, Pfeffer, Petersilie und Schnittlauch nach Geschmack", "1,2 Liter Wasser"],
 "passos": [
   "Vermische in einer Schüssel das Hähnchenhack, das Ei, die Haferflocken, Salz und Pfeffer. Knete alles mit den Händen und forme kleine Bällchen von der Größe einer Walnuss.",
   "Erhitze das Olivenöl in einem Topf und brate die Zwiebel und den Knoblauch 2 Minuten an. Gieße das Wasser an und gib die Möhre und die Kartoffel dazu, würze mit Salz und koche alles 10 Minuten.",
   "Gib die rohen Bällchen vorsichtig einzeln in die kochende Brühe. Rühre 3 Minuten lang nicht, damit sie fest werden.",
   "Gib die Zucchini dazu und koche alles noch 10 Minuten, bis die Bällchen innen durch und das Gemüse weich ist.",
   "Schmecke mit Salz ab, streue die Kräuter darüber und serviere die Suppe schön heiß."],
 "porcoes8": ["3 Bällchen · 1 Kelle Brühe",
              "4 Bällchen · 2 Kellen",
              "4 Bällchen · 2 Kellen",
              "5 Bällchen · 2 Kellen · 1 Scheibe Brot",
              "5 Bällchen · 2 Kellen · 1 Scheibe Brot",
              "6 Bällchen · 3 Kellen · 1 Scheibe Brot",
              "7 Bällchen · 3 Kellen · 2 Scheiben Brot",
              "8 Bällchen · 3 Kellen · 2 Scheiben Brot"],
 "dica": "Die Hähnchenbällchen bringen das Eiweiß, das sättigt, und in der Suppe gegart machen sie die Brühe schmackhafter. Die vielen Flüssigkeiten und das Gemüse füllen den Magen mit wenigen Kalorien. Ein vollständiges, leichtes und wohltuendes Abendessen, das sogar denen schmeckt, die dünne Suppen nicht mögen.",
},
{
 "nome": "Gegrillte Garnelen auf Blattsalat",
 "hook": "Im Knoblauch goldbraun gebratene Garnelen auf einem frischen, knackigen Salat — ein leichtes, elegantes Abendessen in fünfzehn Minuten.",
 "tempo": "15 Min.", "rende": "1 Portion", "kcal_base": 330,
 "ings": ["150 g geputzte große Garnelen", "gemischter Blattsalat", "½ Tomate in Würfeln", "½ Gurke in Scheiben",
          "rote Zwiebel in dünnen Ringen", "2 Knoblauchzehen, gehackt", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Petersilie nach Geschmack"],
 "passos": [
   "Tupfe die Garnelen mit Küchenpapier gut trocken und würze sie mit Salz, Pfeffer und der Hälfte des Zitronensafts.",
   "Erhitze eine beschichtete Pfanne mit dem Olivenöl bei mittlerer bis hoher Hitze. Gib den Knoblauch dazu und rühre 30 Sekunden, nur bis er duftet.",
   "Lege die Garnelen hinein und brate sie 2 bis 3 Minuten je Seite, nur bis sie rosa und goldbraun sind. Brate sie nicht zu lange.",
   "Richte in einer großen Schüssel oder auf einem Teller den Salat mit den Blättern, der Tomate, der Gurke und der roten Zwiebel an. Würze mit dem restlichen Zitronensaft, Salz und Pfeffer.",
   "Lege die heißen Garnelen auf den Salat, streue Petersilie darüber und serviere sofort."],
 "porcoes8": ["120 g Garnelen · Salat",
              "150 g Garnelen · Salat",
              "150 g Garnelen · Salat · 1 Scheibe Brot",
              "170 g Garnelen · Salat · 1 Scheibe Brot",
              "170 g Garnelen · Salat · 2 EL Reis",
              "200 g Garnelen · Salat · 3 EL Reis",
              "220 g Garnelen · Salat · 3 EL Reis",
              "250 g Garnelen · Salat · 4 EL Reis"],
 "dica": "Garnelen sind fast reines Eiweiß mit sehr wenigen Kalorien, sie füllen den Teller also, ohne schwer zu liegen. Im Knoblauch goldbraun gebraten und auf einem frischen, knackigen Salat serviert sind sie eines der leichtesten Abendessen überhaupt — ideal für den Abend, wenn der Körper weniger Energie verbraucht.",
},
{
 "nome": "Fischtopf mit Kokosmilch und Gemüse",
 "hook": "Ein cremiger, duftender Fischtopf mit einem Hauch Kokosmilch — leicht wie das Meer, wohltuend wie eine Umarmung.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 390,
 "ings": ["300 g Filet vom weißen Fisch in großen Stücken", "1 Paprika in Streifen", "1 Tomate, gehackt", "1 Zwiebel in Streifen",
          "2 Knoblauchzehen, gehackt", "120 ml leichte Kokosmilch", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Koriander nach Geschmack"],
 "passos": [
   "Würze die Fischstücke mit Salz, Pfeffer, dem Knoblauch und dem Zitronensaft. Lass sie 5 Minuten Geschmack annehmen.",
   "Erhitze das Olivenöl in einem weiten Topf und lege ein Bett aus der Zwiebel, der Paprika und der Tomate an. Brate alles 3 Minuten unter Rühren an.",
   "Lege die Fischstücke auf das Gemüse (rühre nicht zu viel, damit der Fisch nicht zerfällt).",
   "Gieße die leichte Kokosmilch darüber, decke den Topf ab und koche alles 10 bis 12 Minuten bei mittlerer bis kleiner Hitze, bis der Fisch weiß und zart ist und die Brühe sämig wird.",
   "Streue Koriander darüber und serviere mit einer kleinen Portion Reis, um die Brühe aufzunehmen."],
 "porcoes8": ["120 g Fisch · 2 EL Reis",
              "150 g Fisch · 3 EL Reis",
              "150 g Fisch · 3 EL Reis",
              "170 g Fisch · 4 EL Reis",
              "170 g Fisch · 4 EL Reis",
              "200 g Fisch · 4 EL Reis",
              "220 g Fisch · 5 EL Reis",
              "250 g Fisch · 5 EL Reis"],
 "dica": "Weißer Fisch ist mager und eiweißreich, und leichte Kokosmilch macht die Brühe cremig mit deutlich weniger Fett als Sahne. Das Gemüse gibt Wasser ab und bildet eine leichte, duftende Soße. Ein wohltuender und leichter Topf, perfekt für den Abend.",
},
{
 "nome": "Rindfleisch-Gemüse-Spieße",
 "hook": "Saftige Fleischwürfel im Wechsel mit buntem Gemüse, goldbraun gegrillt — Grillgeschmack im richtigen Maß.",
 "tempo": "30 Min.", "rende": "2 Portionen", "kcal_base": 420,
 "ings": ["250 g mageres Rindfleisch in Würfeln (Hüfte oder Oberschale)", "1 Paprika in Quadraten", "1 Zwiebel in Stücken",
          "1 Zucchini in dicken Scheiben", "Kirschtomaten", "1 Knoblauchzehe, gehackt", "1 TL Olivenöl",
          "Salz, Pfeffer und Paprikapulver nach Geschmack", "Schaschlikspieße"],
 "passos": [
   "Würze die Fleischwürfel mit Salz, Pfeffer, Paprikapulver und dem Knoblauch. Lass sie 10 Minuten Geschmack annehmen.",
   "Stecke die Spieße und wechsle dabei ab: ein Würfel Fleisch, ein Quadrat Paprika, ein Stück Zwiebel, eine Scheibe Zucchini und eine Kirschtomate, bis der Spieß voll ist.",
   "Bestreiche die Spieße mit dem Olivenöl.",
   "Erhitze eine große Pfanne oder eine Grillpfanne bei mittlerer bis hoher Hitze. Lege die Spieße hinein und drehe sie alle 3 Minuten, insgesamt etwa 12 Minuten, bis das Fleisch außen goldbraun und innen nach deinem Geschmack ist.",
   "Serviere die Spieße mit einem Salat oder etwas Reis."],
 "porcoes8": ["1 Spieß · Salat",
              "2 Spieße · Salat",
              "2 Spieße · Salat · 2 EL Reis",
              "2 Spieße · Salat · 3 EL Reis",
              "2 Spieße · Salat · 3 EL Reis",
              "3 Spieße · Salat · 3 EL Reis",
              "3 Spieße · Salat · 4 EL Reis",
              "3 große Spieße · Salat · 4 EL Reis"],
 "dica": "Die Spieße stillen die Lust auf Gegrilltes auf leichte Art: Das magere Fleisch bringt Eiweiß, und das bunte Gemüse füllt den Spieß mit Ballaststoffen und wenigen Kalorien. Das Aufspießen hilft ganz von selbst, die Portion im Rahmen zu halten, und ohne Öl gegrillt bleibt alles schmackhaft und leicht.",
},
{
 "nome": "Warmer Salat mit Hähnchen, Ei und Kartoffeln",
 "hook": "Goldbraune Kartoffeln, gegrilltes Hähnchen und Ei, alles lauwarm auf frischen Blättern — ein Salat, der ein vollständiges, gemütliches Abendessen ist.",
 "tempo": "30 Min.", "rende": "1 Portion", "kcal_base": 420,
 "ings": ["1 Hähnchenbrustfilet (ca. 130 g)", "1 kleine Kartoffel in Würfeln", "2 gekochte Eier",
          "Blattsalat", "Kirschtomaten", "rote Zwiebel in Ringen", "1 TL Olivenöl",
          "Saft von ½ Zitrone", "Salz, Pfeffer und Senf nach Geschmack"],
 "passos": [
   "Koche die Kartoffelwürfel 12 Minuten in kochendem Salzwasser, bis sie weich sind. Gieße sie ab. Wenn du sie goldbraun magst, brate sie 3 Minuten in einer Pfanne mit ein paar Tropfen Olivenöl an.",
   "Koche die Eier 9 Minuten, halte sie unter kaltes Wasser, pelle sie und halbiere sie.",
   "Würze das Hähnchen mit Salz und Pfeffer und brate es in einer beschichteten Pfanne 4 bis 5 Minuten je Seite goldbraun. Schneide es in Streifen.",
   "Lege in einer Schüssel oder auf einem Teller ein Bett aus Blattsalat an und gib die Kirschtomaten und die Zwiebel darauf.",
   "Verteile darüber die lauwarme Kartoffel, die Hähnchenstreifen und die Eier. Rühre für das Dressing das Olivenöl, den Zitronensaft, den Senf, Salz und Pfeffer zusammen, beträufle alles damit und serviere sofort."],
 "porcoes8": ["100 g Hähnchen · ½ Kartoffel · 1 Ei",
              "130 g Hähnchen · 1 kleine Kartoffel · 2 Eier",
              "130 g Hähnchen · 1 Kartoffel · 2 Eier",
              "150 g Hähnchen · 1 Kartoffel · 2 Eier",
              "150 g Hähnchen · 1 Kartoffel · 2 Eier",
              "170 g Hähnchen · 1 große Kartoffel · 2 Eier",
              "200 g Hähnchen · 1 große Kartoffel · 3 Eier",
              "220 g Hähnchen · 2 kleine Kartoffeln · 3 Eier"],
 "dica": "Das ist ein Salat, der wie eine warme Mahlzeit sättigt: Hähnchen und Ei bringen doppeltes Eiweiß, die Kartoffel im richtigen Maß liefert Energie, und die Blätter füllen den Teller mit Ballaststoffen. Lauwarm serviert ist er wohltuend und leicht zugleich — ideal für den Abend.",
},
]
