# -*- coding: utf-8 -*-
"""20 receitas de SOBREMESA (101-120). ALEMÃO. Todas FIT e SEM AÇÚCAR.

Tradução literal de `receitas_sobremesa.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/101-120).
porcoes8 na ordem: Mulher 55-70/71-85/86-100/100+ · Homem 70-85/86-100/101-120/120+
Metas (kcal): 120/150/170/190 · 180/200/230/260 (porções pequenas de sobremesa)
"""

RECEITAS = [
{
 "nome": "Fitness-Schokoladenkuchen ohne Zucker",
 "hook": "Locker, saftig und richtig schokoladig — der Kuchen, der die Lust auf Süßes stillt, ohne eine Prise Zucker, gebacken mit echtem Kakao.",
 "tempo": "40 Min.", "rende": "8 Stücke", "kcal_base": 150,
 "ings": ["3 Eier", "1 sehr reife Banane, zerdrückt", "4 EL 100 % Kakaopulver (ohne Zucker)",
          "5 EL gemahlene Haferflocken (im Mixer zu Mehl gemahlen) oder Vollkornmehl",
          "Backsüße nach Geschmack (Süßstoff zum Backen) — oder 2 EL Honig",
          "120 ml Milch (oder Pflanzendrink)", "1 EL Öl", "1 TL Backpulver"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Streiche etwas Öl in eine kleine Form und stäube etwas Kakao hinein, damit der Kuchen nicht kleben bleibt.",
   "Schlage die Eier mit der Backsüße (oder dem Honig) in einer Schüssel 1 Minute mit einer Gabel oder einem Schneebesen auf, bis alles schaumig ist.",
   "Gib die zerdrückte Banane, die Milch und das Öl dazu und rühre alles gut um.",
   "Füge das Kakaopulver und die gemahlenen Haferflocken (oder das Mehl) hinzu und rühre, bis ein glatter Teig ohne trockene Stellen entsteht.",
   "Gib zum Schluss das Backpulver dazu und rühre nur kurz unter (zu langes Rühren nach dem Backpulver macht den Kuchen schwer).",
   "Fülle den Teig in die Form und backe ihn 30 Minuten. Um zu prüfen, ob er fertig ist, stich ein Holzstäbchen in die Mitte: Kommt es sauber heraus, ist der Kuchen durch.",
   "Lass ihn lauwarm werden, bevor du ihn aus der Form löst und schneidest. Mit Beeren obendrauf schmeckt er hervorragend."],
 "porcoes8": ["1 dünnes Stück",
              "1 Stück",
              "1 Stück · Beeren",
              "1 Stück · 1 EL Joghurt",
              "1 Stück",
              "1 mittleres Stück",
              "1 Stück · Beeren",
              "1 großes Stück · Obst"],
 "dica": "Reiner Kakao gibt den ganzen Schokoladengeschmack ohne den Zucker und das Fett von fertigem Kakaopulver. Die Banane süßt von selbst und hält den Kuchen saftig, die Haferflocken bringen Ballaststoffe und die Eier Eiweiß. Das ist der Beweis, dass du Schokoladenkuchen essen und weiter abnehmen kannst, solange das Stück die richtige Größe hat.",
},
{
 "nome": "Schokoladenmousse mit Avocado",
 "hook": "Cremig wie eine klassische Mousse, aber das Geheimnis ist die Avocado — niemand errät es, und es kommt weder Sahne noch Zucker hinein.",
 "tempo": "10 Min. + Kühlschrank", "rende": "2 Gläser", "kcal_base": 170,
 "ings": ["1 reife Avocado (oder ½ große Avocado)", "3 EL 100 % Kakaopulver",
          "Backsüße nach Geschmack — oder 2 EL Honig", "3 EL Milch (oder Pflanzendrink)",
          "1 Prise Zimt", "1 Prise Salz", "Raspeln von Zartbitterschokolade (mind. 70 %) zum Verzieren (nach Wunsch)"],
 "passos": [
   "Halbiere die Avocado, entferne den Kern und hole das Fruchtfleisch mit einem Löffel heraus. Nimm nur den ganz weichen, grünen Teil.",
   "Gib das Avocadofleisch in den Mixer oder den Becher des Pürierstabs, zusammen mit dem Kakao, der Backsüße (oder dem Honig), der Milch, dem Zimt und dem Salz.",
   "Mixe alles auf höchster Stufe zu einer glatten, glänzenden Creme ohne Stückchen. Wenn sie zu dick ist, gib noch etwas Milch dazu.",
   "Probiere und stelle die Süße nach deinem Geschmack ein.",
   "Verteile alles auf zwei Gläser und stelle sie mindestens 30 Minuten in den Kühlschrank, damit die Mousse fest und kalt wird. Serviere sie mit Schokoraspeln obendrauf."],
 "porcoes8": ["½ kleines Glas",
              "1 kleines Glas",
              "1 Glas",
              "1 Glas · Schokoraspeln",
              "1 Glas",
              "1 mittleres Glas",
              "1 Glas · Schokoraspeln",
              "1 großes Glas · Schokoraspeln"],
 "dica": "Die Avocado gibt der Mousse ihre Cremigkeit mit gutem Fett anstelle von Sahne und sättigt gut. Der reine Kakao bringt den Schokoladengeschmack ohne Zucker. Das ist ein gehaltvoller, befriedigender Nachtisch, der in kleiner Portion problemlos in die Diät passt.",
},
{
 "nome": "Schokokugeln ohne Zucker",
 "hook": "Das Partykügelchen in einer Variante ohne Zucker und ohne Kondensmilch — gerollt, schokoladig und genau in der Größe, die die Lust stillt.",
 "tempo": "20 Min. + Kühlschrank", "rende": "10 Kugeln", "kcal_base": 130,
 "ings": ["6 entsteinte Datteln (diese sehr süße Trockenfrucht)", "3 EL 100 % Kakaopulver",
          "2 EL Milch (oder Pflanzendrink)", "1 EL Erdnussmus",
          "extra Kakaopulver zum Wälzen", "1 Prise Salz"],
 "passos": [
   "Lass die Datteln 10 Minuten in warmem Wasser einweichen, damit sie weich werden. Gieße sie ab.",
   "Mixe die Datteln im Becher des Pürierstabs oder im Mixer mit dem Kakao, der Milch, dem Erdnussmus und dem Salz zu einer dicken, gut vermischten Masse. Halte bei Bedarf an und schiebe die Masse mit einem Löffel zur Mitte.",
   "Die Masse muss fest genug sein, um sie rollen zu können. Ist sie zu weich, stelle sie 20 Minuten in den Kühlschrank.",
   "Nimm mit leicht angefeuchteten Händen kleine Portionen ab und rolle Kugeln von der Größe einer Walnuss.",
   "Wälze jede Kugel im Kakaopulver, bis sie bedeckt ist. Bewahre sie im Kühlschrank auf und serviere sie schön kalt."],
 "porcoes8": ["1 Kugel",
              "1 bis 2 Kugeln",
              "2 Kugeln",
              "2 Kugeln",
              "2 Kugeln",
              "2 bis 3 Kugeln",
              "3 Kugeln",
              "3 Kugeln"],
 "dica": "Die Datteln ersetzen Zucker und Kondensmilch durch natürliche Süße und viele Ballaststoffe, die die Lust auf Süßes bremsen. Der reine Kakao bringt den Schokoladengeschmack und das Erdnussmus die Cremigkeit. Eine oder zwei Kugeln stillen das Verlangen, ohne die Kalorien zu sprengen.",
},
{
 "nome": "Schoko-Tassenkuchen",
 "hook": "Abends Lust auf Süßes? In drei Minuten hast du aus der Mikrowelle einen warmen kleinen Schokoladenkuchen, nur für dich.",
 "tempo": "5 Min.", "rende": "1 Tasse", "kcal_base": 190,
 "ings": ["1 Ei", "2 EL gemahlene Haferflocken (im Mixer zu Mehl gemahlen)", "1 EL 100 % Kakaopulver",
          "Backsüße nach Geschmack — oder 1 EL Honig", "2 EL Milch",
          "½ TL Backpulver", "1 Prise Salz"],
 "passos": [
   "Schlage das Ei in eine große mikrowellenfeste Tasse und verquirle es mit einer Gabel.",
   "Gib die gemahlenen Haferflocken, den Kakao, die Backsüße (oder den Honig), die Milch und das Salz dazu. Rühre alles gut um, bis ein glatter Teig ohne trockene Stellen am Rand entsteht.",
   "Gib zum Schluss das Backpulver dazu und rühre kurz unter.",
   "Stelle die Tasse 1 Minute 30 Sekunden bis 2 Minuten bei höchster Stufe in die Mikrowelle. Der Kuchen geht auf und wird fest; ist er in der Mitte noch feucht, gib 20 Sekunden dazu.",
   "Vorsicht, die Tasse ist heiß. Lass sie 1 Minute abkühlen und iss direkt aus der Tasse. Mit Obst obendrauf schmeckt es hervorragend."],
 "porcoes8": ["½ Tasse",
              "1 kleine Tasse",
              "1 Tasse",
              "1 Tasse · Obst",
              "1 Tasse",
              "1 Tasse",
              "1 Tasse · Obst",
              "1 Tasse · Obst · 1 EL Erdnussmus"],
 "dica": "Frisch gemacht und in der Größe einer Tasse begrenzt dieser kleine Kuchen ganz von selbst, wie viel du isst — es bleibt kein ganzer Kuchen verführerisch auf dem Tisch stehen. Mit Haferflocken, Ei und reinem Kakao ist er süß, warm und wohltuend ohne Zucker, ideal für das Verlangen am Abend.",
},
{
 "nome": "Erdbeermousse mit Joghurt",
 "hook": "Rosa, samtig und erfrischend — eine Erdbeermousse aus nur drei Zutaten und ganz ohne Zucker.",
 "tempo": "10 Min. + Kühlschrank", "rende": "3 Gläser", "kcal_base": 120,
 "ings": ["300 g Erdbeeren (frisch oder gefroren)", "1 Becher Naturjoghurt ohne Zucker (ca. 170 g)",
          "1 EL Gelatinepulver (geschmacksneutral)", "Süßstoff nach Geschmack — oder 1 EL Honig",
          "3 EL heißes Wasser", "gewürfelte Erdbeeren zum Verzieren"],
 "passos": [
   "Wasche die Erdbeeren und entferne die grünen Blättchen. Hebe ein paar zum Verzieren auf.",
   "Löse das Gelatinepulver in einer Tasse im heißen Wasser auf und rühre gut, bis es klar und ohne Körnchen ist. Lass es lauwarm werden.",
   "Mixe die Erdbeeren mit dem Joghurt und dem Süßstoff (oder Honig) im Mixer zu einer glatten, rosa Creme.",
   "Gib bei laufendem Mixer auf niedriger Stufe die aufgelöste Gelatine dazu und mixe noch 30 Sekunden, nur zum Vermischen.",
   "Verteile alles auf Gläser und stelle sie mindestens 2 Stunden in den Kühlschrank, bis die Mousse fest ist. Serviere sie mit gewürfelten Erdbeeren obendrauf."],
 "porcoes8": ["½ Glas",
              "1 kleines Glas",
              "1 Glas",
              "1 Glas · Erdbeeren",
              "1 Glas",
              "1 mittleres Glas",
              "1 Glas · Erdbeeren",
              "1 großes Glas · Erdbeeren"],
 "dica": "Die Erdbeere ist süß und voller Vitamin C bei sehr wenigen Kalorien, und der Naturjoghurt bringt Eiweiß und Cremigkeit ohne Zucker. Die Gelatine gibt die Textur einer Mousse ganz ohne Sahne. Ein leichter, schöner und erfrischender Nachtisch, der die Lust auf Süßes stillt.",
},
{
 "nome": "Cremiges Bananeneis",
 "hook": "Ein echtes Eis, cremig und eiskalt, nur aus Bananen gemacht — ohne Zucker, ohne Milch, ohne Eismaschine.",
 "tempo": "5 Min. + Gefrierfach", "rende": "2 Portionen", "kcal_base": 120,
 "ings": ["3 reife Bananen", "1 EL 100 % Kakaopulver ODER 1 Handvoll Beeren (nach Wunsch, für den Geschmack)",
          "1 Prise Zimt", "1 TL Erdnussmus (nach Wunsch)"],
 "passos": [
   "Schäle die Bananen, schneide sie in Scheiben und gib sie in einen Beutel oder ein Gefäß. Lege sie mindestens 3 Stunden ins Gefrierfach, bis sie ganz hart sind.",
   "Nimm die gefrorenen Scheiben heraus und gib sie in einen kräftigen Mixer oder den Becher des Pürierstabs.",
   "Mixe auf höchster Stufe. Zuerst entstehen kleine Stücke; mixe weiter (halte zwischendurch an und schiebe die Banane zur Mitte), bis eine glatte Creme entsteht, wie Eis aus der Maschine.",
   "Wenn du Geschmack möchtest, gib den Kakao oder die Beeren dazu und mixe noch etwas weiter.",
   "Serviere es sofort, schön cremig, mit einer Prise Zimt — oder stelle es 1 Stunde ins Gefrierfach, damit es fester wird, wie Eis aus der Packung."],
 "porcoes8": ["½ Portion",
              "1 kleine Portion",
              "1 Portion",
              "1 Portion · 1 EL Erdnussmus",
              "1 Portion",
              "1 mittlere Portion",
              "1 Portion · Obst",
              "1 große Portion · Obst · Erdnussmus"],
 "dica": "Gefroren und gemixt gibt die Banane ihren eigenen natürlichen Zucker frei und wird zu einer Creme wie Eis, ganz ohne Zucker, Milch oder Sahne. Sie ist süß, eiskalt und befriedigend, mit den Ballaststoffen und dem Kalium der Frucht — der perfekte Nachtisch für heiße Tage, ohne schlechtes Gewissen.",
},
{
 "nome": "Leichter Milchpudding",
 "hook": "Der cremige Pudding wie immer, mit der goldenen Soße obendrauf — nur ohne Zucker und viel leichter, aus Milch und Eiern.",
 "tempo": "50 Min.", "rende": "6 Stücke", "kcal_base": 130,
 "ings": ["3 Eier", "480 ml fettarme Milch (oder Pflanzendrink)", "Backsüße nach Geschmack (Süßstoff zum Backen)",
          "1 TL Vanillearoma", "Backsüße, die zu Karamell wird (nach Wunsch, für die Soße)",
          "heißes Wasser für das Wasserbad"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Wenn du eine Soße möchtest, lass etwas karamellgeeignete Backsüße in einer kleinen Form schmelzen und verteile sie auf dem Boden (oder lass die Soße weg).",
   "Mixe die Eier, die Milch, die Backsüße und das Vanillearoma 1 Minute im Mixer, bis alles gut vermischt ist.",
   "Gieße die Masse in die Form.",
   "Stelle die Form in ein größeres Backblech und fülle das Blech mit heißem Wasser bis zur halben Höhe der Form (das ist das Wasserbad: Das Wasser lässt den Pudding gleichmäßig garen und cremig werden).",
   "Backe alles 40 Minuten, bis der Pudding fest ist, in der Mitte aber noch leicht wackelt. Lass ihn abkühlen und stelle ihn dann 3 Stunden in den Kühlschrank, bevor du ihn aus der Form löst."],
 "porcoes8": ["1 dünnes Stück",
              "1 Stück",
              "1 Stück",
              "1 Stück · Obst",
              "1 Stück",
              "1 mittleres Stück",
              "1 Stück · Obst",
              "1 großes Stück · Obst"],
 "dica": "Wenn du Kondensmilch und Zucker durch fettarme Milch und Backsüße ersetzt, behält der Pudding seine Cremigkeit und seinen Geschmack bei einem Bruchteil der Kalorien. Die Eier und die Milch bringen zusätzlich Eiweiß. In einem kleinen Stück ist das ein klassischer Nachtisch, der in die Diät passt.",
},
{
 "nome": "Hafer-Bananen-Kekse",
 "hook": "Zwei Zutaten, eine Schüssel und zwanzig Minuten: weiche, süße kleine Kekse, ohne Zucker und ohne weißes Mehl.",
 "tempo": "20 Min.", "rende": "12 Kekse", "kcal_base": 110,
 "ings": ["2 sehr reife Bananen", "135 g Haferflocken", "1 Prise Zimt",
          "1 EL Rosinen oder Stückchen Zartbitterschokolade (mind. 70 %) (nach Wunsch)", "1 Prise Salz"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Lege ein Backblech mit Backpapier aus.",
   "Zerdrücke die Bananen in einer Schüssel gut mit einer Gabel zu einem Mus ohne große Stücke.",
   "Gib die Haferflocken, den Zimt, das Salz und, wenn du magst, die Rosinen oder die gehackte Schokolade dazu. Rühre, bis ein klebriger Teig entsteht.",
   "Setze mit einem Löffel kleine Portionen auf das Blech und drücke jede mit der Rückseite des Löffels zur Keksform flach.",
   "Backe alles 12 bis 15 Minuten, bis die Ränder goldbraun und fest sind. Lass die Kekse auf dem Blech abkühlen (sie werden beim Abkühlen fest) und serviere sie."],
 "porcoes8": ["1 Keks",
              "2 Kekse",
              "2 Kekse",
              "2 Kekse · Obst",
              "2 Kekse",
              "3 Kekse",
              "3 Kekse",
              "3 bis 4 Kekse"],
 "dica": "Die reife Banane süßt und bindet, ganz ohne Zucker und ohne weißes Mehl, und die Haferflocken bringen Ballaststoffe, die sättigen. Das sind natürliche Kekse, hervorragend als Snack oder Nachtisch, die die Lust auf Süßes leicht stillen — zähle aber mit, wie viele du isst, denn hier übertreibt man leicht.",
},
{
 "nome": "Gebackener Apfel mit Zimt und Walnüssen",
 "hook": "Der Apfel wird weich und duftet nach Zimt, mit einer knusprigen Walnussfüllung — ein warmer Nachtisch, der tröstet wie eine Torte, ganz ohne Teig.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 130,
 "ings": ["2 Äpfel", "gemahlener Zimt nach Geschmack", "1 EL gehackte Walnüsse (oder andere Nüsse)",
          "1 EL Haferflocken", "1 TL Honig (nach Wunsch)", "1 Prise gemahlene Nelken (nach Wunsch)"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Wasche die Äpfel und entferne mit einem Messer das Kerngehäuse in der Mitte, sodass eine Höhlung entsteht, ohne bis zum Boden durchzustechen.",
   "Vermische in einer kleinen Schüssel die gehackten Walnüsse, die Haferflocken, den Zimt und, wenn du magst, den Honig und die Nelken.",
   "Fülle die Höhlung jedes Apfels mit dieser Mischung und drücke sie leicht an.",
   "Setze die Äpfel auf ein Backblech mit einem Finger breit Wasser am Boden (damit nichts austrocknet) und stäube noch etwas Zimt darüber.",
   "Backe alles 25 bis 30 Minuten, bis der Apfel ganz weich ist (eine Gabel geht leicht hinein) und die Füllung goldbraun. Serviere ihn warm, pur oder mit einem Löffel Naturjoghurt."],
 "porcoes8": ["½ Apfel",
              "1 Apfel",
              "1 Apfel",
              "1 Apfel · 1 EL Joghurt",
              "1 Apfel",
              "1 Apfel · extra Walnüsse",
              "1 Apfel · Joghurt",
              "2 Äpfel · Joghurt"],
 "dica": "Den Apfel zu backen konzentriert die natürliche Süße der Frucht, er wird also süß ganz ohne Zucker. Der Zimt hebt den Geschmack und hilft, die Lust auf Süßes zu steuern, und die Walnüsse bringen gutes Fett und Biss. Es ist der Trost eines Apfelkuchens mit einem Bruchteil der Kalorien.",
},
{
 "nome": "Selbst gemachtes Fruchtgelee",
 "hook": "Bunt, glänzend und erfrischend, mit echten Fruchtstücken darin — der leichteste Nachtisch überhaupt.",
 "tempo": "10 Min. + Kühlschrank", "rende": "4 Gläser", "kcal_base": 70,
 "ings": ["1 EL Gelatinepulver (geschmacksneutral)", "480 ml Fruchtsaft ohne Zucker (Orange, Traube oder Erdbeere)",
          "120 ml Wasser", "150 g gewürfeltes Obst (Erdbeere, Kiwi, Mango oder Weintrauben)", "Süßstoff nach Geschmack (nach Wunsch)"],
 "passos": [
   "Gib das Wasser in einen kleinen Topf und streue das Gelatinepulver darüber. Lass alles 2 Minuten stehen (die Gelatine quillt auf, das nennt man einweichen).",
   "Erhitze alles bei kleiner Hitze und rühre 1 Minute, nur bis sich die Gelatine vollständig auflöst, ohne zu kochen. Nimm den Topf vom Herd.",
   "Gib den Fruchtsaft (und den Süßstoff, wenn du magst) dazu und rühre gut um.",
   "Verteile das gewürfelte Obst auf dem Boden von Gläsern oder einer Form und gieße die Flüssigkeit darüber.",
   "Stelle alles mindestens 4 Stunden in den Kühlschrank, bis es fest ist. Serviere es schön kalt."],
 "porcoes8": ["½ Glas",
              "1 kleines Glas",
              "1 Glas",
              "1 Glas · extra Obst",
              "1 Glas",
              "1 mittleres Glas",
              "1 Glas · Obst",
              "1 großes Glas · Obst"],
 "dica": "Mit Fruchtsaft statt mit dem Pulver voller Zucker und Farbstoff gemacht, hat selbst gemachtes Gelee praktisch keine Kalorien und enthält noch echte Fruchtstücke. Es ist der ideale Nachtisch, wenn dich die Lust auf etwas Süßes und Kaltes packt, ohne dass es der Diät in irgendeiner Weise schadet.",
},
{
 "nome": "Haferriegel mit Trockenfrüchten",
 "hook": "Der selbst gemachte Müsliriegel, saftig und süß, ohne den Zucker und die Sirupe der gekauften — perfekt für die Tasche.",
 "tempo": "30 Min.", "rende": "8 Riegel", "kcal_base": 150,
 "ings": ["180 g Haferflocken", "2 reife Bananen, zerdrückt", "3 EL gehackte Trockenfrüchte (Rosinen, getrocknete Aprikosen oder Datteln)",
          "2 EL gehackte Nüsse oder Walnüsse", "1 EL Honig (nach Wunsch)", "1 Prise Zimt und Salz"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Lege eine kleine rechteckige Form mit Backpapier aus.",
   "Zerdrücke die Bananen in einer Schüssel gut zu einem Mus.",
   "Gib die Haferflocken, die gehackten Trockenfrüchte, die Nüsse, den Zimt, das Salz und, wenn du magst, den Honig dazu. Rühre, bis ein klebriger, gleichmäßiger Teig entsteht.",
   "Gib den Teig in die Form und drücke ihn mit der Rückseite eines Löffels gut fest, sodass eine feste, gleichmäßige Schicht entsteht (je fester gedrückt, desto weniger bröselt der Riegel).",
   "Backe alles 20 Minuten, bis die Ränder goldbraun sind. Lass es in der Form vollständig auskühlen, bevor du es in Riegel schneidest (warm geschnitten bröselt es)."],
 "porcoes8": ["1 Riegel",
              "1 Riegel",
              "1 Riegel",
              "1 Riegel · Obst",
              "1 Riegel",
              "1 bis 2 Riegel",
              "2 Riegel",
              "2 Riegel"],
 "dica": "Riegel aus dem Supermarkt enthalten oft mehr Zucker und Sirup als eine Süßigkeit. Zu Hause aus Haferflocken, Banane und Trockenfrüchten gemacht, süßt der Riegel auf natürliche Weise und bringt Ballaststoffe und Energie, die den Hunger fernhalten. Hervorragend als Snack oder praktischer Nachtisch — iss aber immer nur einen.",
},
{
 "nome": "Gefrorene Joghurtplatte mit Beeren",
 "hook": "Eine knackige Platte aus gefrorenem Joghurt mit Beeren obendrauf, die du in Stücke brichst — schön, spielerisch und ohne Zucker.",
 "tempo": "5 Min. + Gefrierfach", "rende": "4 Portionen", "kcal_base": 100,
 "ings": ["1 großer Becher griechischer Naturjoghurt ohne Zucker (ca. 350 g)", "140 g Beeren (Erdbeeren, Heidelbeeren, Himbeeren)",
          "1 EL Honig (nach Wunsch)", "1 EL gehackte Nüsse (nach Wunsch)", "Raspeln von Zartbitterschokolade (mind. 70 %) (nach Wunsch)"],
 "passos": [
   "Lege ein Backblech oder eine flache Form mit Backpapier aus.",
   "Vermische den griechischen Joghurt in einer Schüssel mit dem Honig (falls du ihn nimmst), bis alles glatt ist.",
   "Streiche den Joghurt auf das Backpapier, etwa einen halben Finger dick.",
   "Streue die Beeren (schneide die Erdbeeren), die Nüsse und die Schokoraspeln darüber und verteile alles über die ganze Fläche.",
   "Stelle alles 3 bis 4 Stunden ins Gefrierfach, bis es ganz hart ist. Brich oder schneide es in unregelmäßige Stücke und serviere es sofort (es schmilzt schnell). Bewahre den Rest im Gefrierfach auf."],
 "porcoes8": ["1 kleines Stück",
              "1 Stück",
              "1 bis 2 Stücke",
              "2 Stücke",
              "2 Stücke",
              "2 Stücke",
              "2 bis 3 Stücke",
              "3 Stücke"],
 "dica": "Griechischer Joghurt bringt Eiweiß und Cremigkeit ohne Zucker, und gefroren wird daraus eine kalte, knackige Nascherei. Die Beeren süßen von selbst und stecken voller Antioxidantien. Ein erfrischender, leichter Nachtisch, hervorragend für den Sommer und für die Lust, etwas Süßes zu naschen.",
},
{
 "nome": "Fitness-Schokoladentrüffel",
 "hook": "Klein, intensiv und schokoladig — der Trüffel, der ganz ohne Zucker im Mund schmilzt, für die Momente mit starkem Verlangen.",
 "tempo": "20 Min. + Kühlschrank", "rende": "10 Trüffel", "kcal_base": 120,
 "ings": ["100 g Zartbitterschokolade (mind. 70 %, oder dunkler)", "4 EL heiße Milch (oder Pflanzendrink)",
          "2 EL Kokosraspeln ohne Zucker", "100 % Kakaopulver zum Wälzen", "1 Prise Salz"],
 "passos": [
   "Hacke die Zartbitterschokolade in kleine Stücke und gib sie in eine Schüssel.",
   "Erhitze die Milch, bis sie fast kocht, und gieße sie über die Schokolade. Warte 1 Minute und rühre, bis die Schokolade vollständig geschmolzen ist und eine glatte, glänzende Creme entsteht (das ist die Ganache).",
   "Gib die Kokosraspeln und das Salz dazu und rühre um. Stelle alles 1 Stunde in den Kühlschrank, bis die Masse fest genug zum Rollen ist.",
   "Nimm mit den Händen kleine Portionen ab und rolle Kugeln von der Größe einer großen Olive.",
   "Wälze jeden Trüffel im Kakaopulver, bis er bedeckt ist. Bewahre sie im Kühlschrank auf und serviere sie kalt."],
 "porcoes8": ["1 Trüffel",
              "1 Trüffel",
              "1 bis 2 Trüffel",
              "2 Trüffel",
              "2 Trüffel",
              "2 Trüffel",
              "2 bis 3 Trüffel",
              "3 Trüffel"],
 "dica": "Schokolade mit 70 % oder mehr Kakaoanteil enthält wenig Zucker und viel Kakao, der reich an Antioxidantien ist. Als kleiner Trüffel stillt sie das starke Verlangen nach Schokolade mit deutlich weniger Zucker als eine gewöhnliche Praline. Einer oder zwei lösen das Verlangen, ohne die Diät zu sabotieren.",
},
{
 "nome": "Fitness-Möhrenkuchen mit Kakaoguss",
 "hook": "Der lockere Möhrenkuchen aus der Kindheit, mit Schokoladenguss — ohne Zucker, aber mit der ganzen Zuwendung und dem ganzen Geschmack.",
 "tempo": "45 Min.", "rende": "8 Stücke", "kcal_base": 160,
 "ings": ["2 mittelgroße Möhren, gehackt", "3 Eier", "3 EL Öl", "Backsüße nach Geschmack (Süßstoff zum Backen)",
          "135 g gemahlene Haferflocken (im Mixer zu Mehl gemahlen) oder Vollkornmehl", "1 TL Backpulver",
          "Guss: 2 EL 100 % Kakaopulver + 2 EL Milch + Süßstoff nach Geschmack"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Streiche etwas Öl in eine Form und stäube etwas Mehl hinein.",
   "Mixe die gehackten Möhren, die Eier, das Öl und die Backsüße im Mixer zu einer glatten, orangefarbenen Creme.",
   "Gib alles in eine Schüssel, füge die gemahlenen Haferflocken (oder das Mehl) hinzu und rühre um. Gib zum Schluss das Backpulver dazu und rühre kurz unter.",
   "Fülle den Teig in die Form und backe ihn 30 Minuten, bis ein in die Mitte gestochenes Holzstäbchen sauber herauskommt.",
   "Mache den Guss: Vermische in einem kleinen Topf den Kakao, die Milch und den Süßstoff und erwärme alles 2 Minuten bei kleiner Hitze unter Rühren, bis eine glänzende Creme entsteht. Streiche sie auf den noch lauwarmen Kuchen."],
 "porcoes8": ["1 dünnes Stück",
              "1 Stück",
              "1 Stück",
              "1 Stück · Obst",
              "1 Stück",
              "1 mittleres Stück",
              "1 Stück · Obst",
              "1 großes Stück"],
 "dica": "Die Möhre hält den Kuchen saftig und macht ihn von Natur aus süß, außerdem bringt sie Vitamin A. Wenn du den Zucker durch Backsüße und das weiße Mehl durch Haferflocken ersetzt, wird der Kuchen leicht und ballaststoffreich. Der Guss aus reinem Kakao gibt die Schokoladennote ohne den Zucker der klassischen Glasur.",
},
{
 "nome": "Zitronenmousse",
 "hook": "Genau richtig säuerlich, cremig und eiskalt — eine erfrischende Zitronenmousse, die den Gaumen putzt und ohne Zucker auskommt.",
 "tempo": "10 Min. + Kühlschrank", "rende": "3 Gläser", "kcal_base": 120,
 "ings": ["1 Becher Naturjoghurt ohne Zucker (ca. 170 g)", "Saft von 2 Zitronen", "abgeriebene Schale von 1 Zitrone",
          "1 EL Gelatinepulver (geschmacksneutral)", "3 EL heißes Wasser",
          "Süßstoff nach Geschmack — oder 2 EL Honig"],
 "passos": [
   "Wasche 1 Zitrone gut ab und reibe nur den gelben Teil der Schale ab (der weiße Teil ist bitter). Presse beide Zitronen aus.",
   "Löse das Gelatinepulver in einer Tasse im heißen Wasser auf und rühre, bis es klar ist. Lass es lauwarm werden.",
   "Vermische in einer Schüssel den Joghurt, den Zitronensaft, die Schale und den Süßstoff (oder Honig) zu einer Creme.",
   "Gib die aufgelöste Gelatine dazu und rühre gut und zügig unter, damit sich keine Klümpchen bilden.",
   "Verteile alles auf Gläser und stelle sie mindestens 2 Stunden in den Kühlschrank, bis die Mousse fest ist. Serviere sie kalt, mit noch etwas Zitronenschale obendrauf."],
 "porcoes8": ["½ Glas",
              "1 kleines Glas",
              "1 Glas",
              "1 Glas · Obst",
              "1 Glas",
              "1 mittleres Glas",
              "1 Glas · Obst",
              "1 großes Glas · Obst"],
 "dica": "Die Zitrone bringt Frische und einen kräftigen Geschmack, der die Lust auf Süßes austrickst, ohne dass viel Süßstoff nötig ist. Der Naturjoghurt bringt Eiweiß und Cremigkeit, und die Gelatine macht die Mousse fest, ganz ohne Sahne. Ein leichter, erfrischender Nachtisch, der fast kein Fett enthält.",
},
{
 "nome": "Leichter Beeren-Käsekuchen (ohne Backen)",
 "hook": "Cremig, mit knuspriger Basis und Fruchtsoße, ganz ohne Ofen zusammengesetzt — der Käsekuchen deiner Träume in einer leichten Variante ohne Zucker.",
 "tempo": "20 Min. + Kühlschrank", "rende": "6 Stücke", "kcal_base": 170,
 "ings": ["Basis: 90 g Haferflocken + 1 zerdrückte Banane + 1 TL Zimt",
          "Creme: 250 g Ricotta (oder Hüttenkäse) + ½ Becher Naturjoghurt + Süßstoff nach Geschmack + Saft von ½ Zitrone",
          "1 EL Gelatinepulver (geschmacksneutral) + 3 EL heißes Wasser",
          "Soße: 140 g Beeren + Süßstoff nach Geschmack"],
 "passos": [
   "Basis: Vermische die Haferflocken, die zerdrückte Banane und den Zimt zu einem Teig. Drücke ihn auf den Boden einer kleinen Form (am besten einer Springform) zu einer festen Schicht. Stelle sie 10 Minuten ins Gefrierfach.",
   "Löse die Gelatine im heißen Wasser auf und rühre, bis sie klar ist. Lass sie lauwarm werden.",
   "Creme: Mixe den Ricotta, den Joghurt, den Süßstoff und den Zitronensaft im Mixer zu einer ganz glatten Creme. Gib die Gelatine dazu und mixe noch 20 Sekunden.",
   "Gieße die Creme auf die Basis und streiche die Oberfläche glatt. Stelle alles mindestens 3 Stunden in den Kühlschrank, bis es fest ist.",
   "Soße: Koche die Beeren in einem kleinen Topf mit dem Süßstoff 5 Minuten bei kleiner Hitze und zerdrücke sie dabei etwas, bis eine Art Konfitüre entsteht. Lass sie abkühlen und verteile sie vor dem Servieren auf dem Käsekuchen."],
 "porcoes8": ["1 dünnes Stück",
              "1 Stück",
              "1 Stück",
              "1 Stück · extra Fruchtsoße",
              "1 Stück",
              "1 mittleres Stück",
              "1 Stück · Fruchtsoße",
              "1 großes Stück · Fruchtsoße"],
 "dica": "Ricotta und Hüttenkäse geben die Cremigkeit von Frischkäse mit viel weniger Fett und mehr Eiweiß. Die Basis aus Haferflocken und Banane ersetzt den Butterkeks, und die Soße aus gekochtem Obst macht Zucker überflüssig. Ein echter Käsekuchen, der in der richtigen Stückgröße in die Diät passt.",
},
{
 "nome": "Selbst gemachtes Fruchteis am Stiel",
 "hook": "Erfrischend und voller echter Früchte ist dieses selbst gemachte Eis der perfekte Nachtisch für heiße Tage — und es enthält keinen Tropfen Zucker.",
 "tempo": "10 Min. + Gefrierfach", "rende": "6 Eis am Stiel", "kcal_base": 60,
 "ings": ["300 g gewürfeltes Obst (Erdbeere, Mango, Kiwi oder Wassermelone)", "240 ml Fruchtsaft ohne Zucker (oder Kokoswasser)",
          "1 Becher Naturjoghurt ohne Zucker (nach Wunsch, für cremiges Eis)", "Süßstoff nach Geschmack (nach Wunsch)",
          "Eisformen und Stiele"],
 "passos": [
   "Schneide das Obst in kleine Stücke, damit es in die Formen passt.",
   "Wähle die Art: Für Fruchteis nimmst du nur das Obst und den Fruchtsaft; für cremiges Eis mixt du das Obst mit dem Joghurt im Mixer.",
   "Gib ein paar Obststücke auf den Boden jeder Form (das sieht schön aus) und fülle sie mit dem Saft oder der gemixten Creme auf, dabei einen Finger breit Platz oben lassen (die Flüssigkeit dehnt sich beim Gefrieren aus).",
   "Stecke in die Mitte jedes Eises einen Stiel.",
   "Stelle alles mindestens 5 Stunden ins Gefrierfach, bis es ganz fest ist. Zum Herauslösen hältst du die Form kurz unter warmes Wasser."],
 "porcoes8": ["1 Eis",
              "1 Eis",
              "1 Eis",
              "1 bis 2 Eis",
              "1 Eis",
              "1 bis 2 Eis",
              "2 Eis",
              "2 Eis"],
 "dica": "Wassereis aus der Packung besteht fast nur aus Wasser, Zucker und Farbstoff. Zu Hause mit echtem Obst und Fruchtsaft gemacht, wird daraus ein erfrischender Nachtisch voller Vitamine und praktisch ohne Kalorien — die beste Art, die Lust auf etwas Kaltes bei Hitze zu stillen, ohne schlechtes Gewissen.",
},
{
 "nome": "Apfel-Zimt-Muffins",
 "hook": "Locker, duftend und mit Apfelstücken — Muffins für den Nachmittagskaffee, die nach Sünde aussehen, aber leicht und ohne Zucker sind.",
 "tempo": "35 Min.", "rende": "6 Muffins", "kcal_base": 140,
 "ings": ["2 Eier", "1 geriebener Apfel + ½ Apfel in kleinen Würfeln", "135 g gemahlene Haferflocken (im Mixer zu Mehl gemahlen)",
          "3 EL Öl", "Backsüße nach Geschmack (Süßstoff zum Backen)", "120 ml Milch",
          "1 TL Zimt", "1 TL Backpulver", "1 Prise Salz"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Lege eine Muffinform mit Papierförmchen aus (oder streiche etwas Öl in die Mulden).",
   "Schlage die Eier in einer Schüssel 1 Minute mit der Backsüße und dem Öl auf. Gib die Milch und den geriebenen Apfel dazu und rühre um.",
   "Füge die gemahlenen Haferflocken, den Zimt und das Salz hinzu und rühre, bis ein gleichmäßiger Teig entsteht. Gib die Apfelwürfel und das Backpulver dazu und rühre kurz unter.",
   "Verteile den Teig auf die Förmchen und fülle sie zu zwei Dritteln (sie gehen auf).",
   "Backe alles 20 bis 25 Minuten, bis die Muffins goldbraun sind und ein hineingestochenes Holzstäbchen sauber herauskommt. Lass sie lauwarm werden und serviere sie."],
 "porcoes8": ["1 Muffin",
              "1 Muffin",
              "1 Muffin",
              "1 Muffin · 1 EL Joghurt",
              "1 Muffin",
              "1 bis 2 Muffins",
              "2 Muffins",
              "2 Muffins"],
 "dica": "Der geriebene Apfel hält die Muffins saftig und macht sie von Natur aus süß, Zucker ist überflüssig. Die Haferflocken bringen Ballaststoffe, die sättigen, und der Zimt hebt die Süße der Frucht hervor. Sie sind hervorragend als Snack oder Nachtisch, in einer Portion von einem Stück, und stillen die Lust auf Gebäck auf leichte Art.",
},
{
 "nome": "Apfel-Hafer-Crumble",
 "hook": "Weicher Apfel unten, knusprige Haferstreusel oben — die Gemütlichkeit einer warmen Torte, in Minuten zusammengesetzt und ohne Zucker.",
 "tempo": "40 Min.", "rende": "4 Portionen", "kcal_base": 160,
 "ings": ["3 Äpfel in Würfeln", "Saft von ½ Zitrone", "1 TL Zimt",
          "Streusel: 90 g Haferflocken + 2 EL gehackte Nüsse + 2 EL Kokosöl (oder normales Öl) + Süßstoff nach Geschmack",
          "1 Prise Salz"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Vermische die Apfelwürfel in einer Schüssel mit dem Zitronensaft und dem Zimt und verteile sie auf dem Boden einer Auflaufform.",
   "Mache die Streusel: Vermische in einer zweiten Schüssel die Haferflocken, die Nüsse, das Öl, den Süßstoff und das Salz und reibe alles mit den Fingerspitzen, bis feuchte, zusammenhängende Streusel entstehen.",
   "Verteile die Streusel über den Äpfeln und bedecke die ganze Fläche.",
   "Backe alles 25 bis 30 Minuten, bis der Apfel an den Rändern Blasen wirft und die Streusel goldbraun und knusprig sind.",
   "Lass alles 5 Minuten lauwarm werden und serviere es. Mit einem Löffel Naturjoghurt oder Bananeneis obendrauf schmeckt es köstlich."],
 "porcoes8": ["½ Portion",
              "1 kleine Portion",
              "1 Portion",
              "1 Portion · Joghurt",
              "1 Portion",
              "1 mittlere Portion",
              "1 Portion · Joghurt",
              "1 große Portion · Joghurt"],
 "dica": "Der gebackene Apfel gibt seine eigene Süße frei, und der Zimt verstärkt den Geschmack ohne Zucker. Die Streusel aus Haferflocken und Nüssen geben den Biss einer Torte, mit Ballaststoffen und gutem Fett anstelle von Butter und weißem Mehl. Es ist der Trost eines warmen Ofennachtischs, in der richtigen Portion.",
},
{
 "nome": "Gebackene Birne mit Gewürzen",
 "hook": "Die Birne wird weich und saftig und duftet nach Zimt und Nelken — ein eleganter, warmer Nachtisch, süß allein durch die Frucht.",
 "tempo": "35 Min.", "rende": "2 Portionen", "kcal_base": 110,
 "ings": ["2 feste Birnen", "Zimtstange (oder gemahlener Zimt)", "2 Gewürznelken", "abgeriebene Orangenschale (nach Wunsch)",
          "1 TL Honig (nach Wunsch)", "1 EL gehackte Walnüsse oder Mandeln"],
 "passos": [
   "Heize den Backofen auf 180 °C vor. Wasche die Birnen, halbiere sie der Länge nach und hole das Kerngehäuse mit einem kleinen Löffel heraus, sodass eine Mulde entsteht.",
   "Lege die Birnenhälften mit der Schnittfläche nach oben auf ein Backblech. Stäube Zimt darüber und gib in jede Mulde eine Nelke und etwas Orangenschale.",
   "Wenn du magst, träufle ein paar Tropfen Honig auf jede Birne.",
   "Gieße einen Finger breit Wasser auf den Boden des Blechs (damit nichts austrocknet) und backe alles 25 Minuten, bis die Birne ganz weich ist (eine Gabel geht leicht hinein).",
   "Nimm die Nelken heraus, streue die gehackten Walnüsse darüber und serviere alles warm, pur oder mit einem Löffel Naturjoghurt."],
 "porcoes8": ["1 Hälfte",
              "1 Birne (2 Hälften)",
              "1 Birne",
              "1 Birne · Joghurt",
              "1 Birne",
              "1 Birne · extra Walnüsse",
              "1 Birne · Joghurt",
              "2 Birnen · Joghurt"],
 "dica": "Die Birne zu backen konzentriert den natürlichen Zucker der Frucht, sie wird also süß, ohne dass Zucker nötig wäre. Die Gewürze geben ein wohltuendes Aroma, das den Gaumen zufriedenstellt, und die Walnüsse bringen gutes Fett und Biss. Ein warmer, leichter und edler Nachtisch.",
},
]
