# -*- coding: utf-8 -*-
"""BÔNUS 1 — DIETA VEGETARIANA: 8 receitas NOVAS (fotos 151-158). FRANCÊS.

Tradução literal de `receitas_bonus_veg.py`. Convenções em GLOSSARIO-TRADUCAO.md.
⛔ O campo `prompt` não é replicado: a foto é a mesma do PT (fotos/151-158).
ALMOCOS -> tipo 'almoco' (metas 360/440/500/560 · 540/610/680/750), fotos 151-154
JANTARES -> tipo 'jantar' (metas 340/420/480/540 · 520/590/650/720), fotos 155-158
"""

ALMOCOS = [
{
 "nome": "Bol de pois chiches, riz et légumes rôtis",
 "tag": "Déjeuner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Un bol coloré et copieux, sans aucune viande — le pois chiche tient tout l'après-midi comme un plat de protéines.",
 "tempo": "35 min", "rende": "1 portion", "kcal_base": 500,
 "ings": ["80 g de pois chiches cuits (ou en boîte, égouttés)", "4 c. à s. de riz complet cuit",
          "1 courgette en morceaux", "½ poivron en morceaux", "½ oignon rouge en morceaux", "tomates cerises",
          "1 c. à c. d'huile d'olive", "le jus de ½ citron", "sel, poivre, curcuma et origan au goût", "salade verte"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe la courgette, le poivron et l'oignon en morceaux de taille similaire, de la taille d'une bouchée.",
   "Sur une plaque, étale les légumes et les tomates cerises, assaisonne avec du sel, du poivre, de l'origan et la moitié de l'huile d'olive, et mélange à la main.",
   "Enfourne 20 à 25 minutes, jusqu'à ce que les légumes soient tendres et dorés aux pointes. Retourne à mi-cuisson.",
   "Dans une poêle, fais chauffer le reste d'huile d'olive et fais revenir les pois chiches avec le curcuma, du sel et du poivre 3 minutes, en remuant, juste pour qu'ils prennent du goût et dorent légèrement.",
   "Monte le bol : un lit de salade verte, le riz d'un côté, les pois chiches et les légumes rôtis par-dessus. Arrose de jus de citron et sers."],
 "porcoes8": ["55 g de pois chiches · 3 c. à s. de riz · légumes",
              "80 g de pois chiches · 4 c. à s. de riz · légumes",
              "80 g de pois chiches · 5 c. à s. de riz · légumes",
              "110 g de pois chiches · 5 c. à s. de riz · un filet d'huile",
              "110 g de pois chiches · 5 c. à s. de riz · légumes",
              "125 g de pois chiches · 6 c. à s. de riz · 1 c. à s. de noix",
              "165 g de pois chiches · 7 c. à s. de riz · avocat",
              "165 g de pois chiches · 8 c. à s. de riz · avocat"],
 "dica": "Le pois chiche réunit des protéines et des fibres qui rassasient comme un plat de viande, et avec le riz complet il forme une protéine complète (le duo légumineuse + céréale qu'utilisent les végétariens). Rôtir les légumes concentre le goût sans matière grasse, ce qui laisse le plat léger et plein de saveur.",
},
{
 "nome": "Gratin de lentilles à la purée de pommes de terre",
 "tag": "Déjeuner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Tout le réconfort d'un gratin, avec une garniture de lentilles relevées à la place de la viande — crémeux et plein de protéines végétales.",
 "tempo": "45 min", "rende": "2 portions", "kcal_base": 470,
 "ings": ["200 g de lentilles cuites", "2 pommes de terre moyennes", "1 oignon haché", "2 gousses d'ail hachées",
          "1 tomate hachée", "1 carotte râpée", "1 c. à c. d'huile d'olive",
          "2 c. à s. de fromage râpé", "sel, poivre, curcuma, persil et ciboulette au goût"],
 "passos": [
   "Épluche et fais cuire les pommes de terre 15 minutes dans de l'eau bouillante, jusqu'à ce qu'elles soient bien tendres. Égoutte et écrase à la fourchette avec une pincée de sel, jusqu'à obtenir une purée lisse.",
   "Dans une poêle, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes. Ajoute la carotte râpée et la tomate et fais cuire 3 minutes.",
   "Ajoute les lentilles cuites, le curcuma, du sel et du poivre et fais cuire encore 5 minutes, en écrasant un peu les lentilles à la cuillère, jusqu'à obtenir une garniture consistante.",
   "Dans un plat à gratin, étale la moitié de la purée au fond, la garniture de lentilles au milieu et le reste de la purée par-dessus. Parsème de fromage râpé.",
   "Enfourne à 200 °C pendant 15 minutes, jusqu'à ce que la surface soit dorée. Parsème d'herbes et sers."],
 "porcoes8": ["½ portion · salade",
              "1 portion · salade",
              "1 portion · salade",
              "1 portion · 1 c. à s. de fromage en plus · salade",
              "1 portion · lentilles en plus · salade",
              "1 grande portion · salade",
              "1 grande portion · lentilles en plus · salade",
              "double portion · salade"],
 "dica": "La lentille est riche en fer, en fibres et en protéines végétales, un trio qui rassasie beaucoup — dans le gratin, elle remplace la viande largement. Avec la purée de pommes de terre dans la bonne mesure et un peu de fromage gratiné, c'est un plat réconfortant qui trompe l'envie de nourriture lourde.",
},
{
 "nome": "Frittata aux légumes",
 "tag": "Déjeuner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Une omelette haute et moelleuse, cuite avec des légumes colorés et du fromage — les protéines des œufs dans un plat qui se coupe en parts et plaît à tout le monde.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 420,
 "ings": ["5 œufs", "1 courgette en petits dés", "½ poivron haché", "1 tomate hachée", "1 poignée d'épinards",
          "3 c. à s. de fromage en dés", "1 c. à c. d'huile d'olive",
          "ciboulette, sel et poivre au goût", "salade verte"],
 "passos": [
   "Préchauffe le four à 180 °C. Dans une poêle qui peut aller au four, fais chauffer l'huile d'olive et fais revenir la courgette et le poivron 4 minutes, en remuant, jusqu'à ce qu'ils s'attendrissent.",
   "Ajoute les épinards et remue 1 minute, juste le temps que les feuilles retombent. Étale les légumes dans la poêle.",
   "Dans un bol, bats les œufs avec du sel et du poivre. Ajoute la tomate, le fromage et la ciboulette et mélange.",
   "Verse les œufs sur les légumes dans la poêle et laisse 2 minutes sur le feu, juste pour que le bord prenne.",
   "Enfourne la poêle 15 minutes, jusqu'à ce que la frittata gonfle, soit prise au centre et dorée dessus. Coupe en parts et sers avec une salade verte."],
 "porcoes8": ["1 part · salade",
              "1 grande part · salade",
              "1 grande part · salade · 2 c. à s. de riz",
              "2 parts · salade · 2 c. à s. de riz",
              "2 parts · salade · 3 c. à s. de riz",
              "2 grandes parts · salade · 3 c. à s. de riz",
              "2 grandes parts · salade · 4 c. à s. de riz",
              "3 parts · salade · 4 c. à s. de riz"],
 "dica": "Les œufs sont une protéine complète et très rassasiante, idéaux pour un déjeuner végétarien sans légumineuses. Cuite avec des légumes et un peu de fromage, la frittata fait plusieurs portions, se garde bien au réfrigérateur et calme la faim de façon légère et nourrissante.",
},
{
 "nome": "Chili végétarien aux haricots et pois chiches",
 "tag": "Déjeuner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Un ragoût épicé et consistant, sans aucune viande — la preuve qu'un plat végétarien remplit lui aussi l'assiette et le ventre.",
 "tempo": "30 min", "rende": "3 portions", "kcal_base": 460,
 "ings": ["175 g de haricots rouges cuits", "165 g de pois chiches cuits", "80 g de maïs",
          "1 oignon haché", "2 gousses d'ail hachées", "1 poivron haché", "2 tomates hachées (ou sauce tomate)",
          "1 c. à c. d'huile d'olive", "1 c. à c. de cumin", "sel, poivre et paprika au goût",
          "riz pour servir"],
 "passos": [
   "Fais chauffer l'huile d'olive dans une casserole à feu moyen. Fais revenir l'oignon, l'ail et le poivron 3 minutes, en remuant, jusqu'à ce qu'ils s'attendrissent.",
   "Ajoute le cumin, le paprika, du sel et du poivre et remue 30 secondes, pour que les épices libèrent leur arôme.",
   "Ajoute les tomates hachées et fais cuire 5 minutes, jusqu'à ce qu'elles se défassent en sauce.",
   "Ajoute les haricots rouges, les pois chiches et le maïs. Si c'est trop sec, verse 120 ml d'eau.",
   "Baisse le feu et fais cuire 15 minutes, en remuant de temps en temps, jusqu'à obtenir un ragoût onctueux. Sers avec un peu de riz."],
 "porcoes8": ["½ portion · 3 c. à s. de riz",
              "1 portion · 4 c. à s. de riz",
              "1 portion · 5 c. à s. de riz",
              "1 portion · 5 c. à s. de riz · avocat",
              "1 portion · 5 c. à s. de riz",
              "1 grande portion · 6 c. à s. de riz",
              "grande portion · 7 c. à s. de riz · avocat",
              "double portion · 8 c. à s. de riz"],
 "dica": "Haricots et pois chiches réunis forment une protéine végétale très complète, avec une montagne de fibres qui rassasie des heures. Servi avec du riz, il complète la protéine. C'est un plat bon marché, qui fait plusieurs repas et prouve qu'on peut bien manger sans viande.",
},
]

JANTARES = [
{
 "nome": "Soupe consistante de lentilles aux légumes",
 "tag": "Dîner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Une soupe qui est un vrai repas : la lentille donne du corps au bouillon et beaucoup de protéines, elle réchauffe et rassasie par une soirée fraîche.",
 "tempo": "40 min", "rende": "3 portions", "kcal_base": 380,
 "ings": ["190 g de lentilles crues", "1 pomme de terre en dés", "1 carotte en dés", "1 branche de céleri hachée (facultatif)",
          "1 tomate hachée", "1 oignon haché", "2 gousses d'ail hachées", "1 c. à c. d'huile d'olive",
          "sel, poivre, curcuma et herbes au goût", "1,2 litre d'eau"],
 "passos": [
   "Lave les lentilles. Dans une casserole, fais chauffer l'huile d'olive et fais revenir l'oignon et l'ail 2 minutes, en remuant.",
   "Ajoute la tomate, la carotte, la pomme de terre et le céleri et remue 2 minutes.",
   "Ajoute les lentilles, le curcuma, du sel, du poivre et l'eau. Porte à ébullition.",
   "Baisse le feu et fais cuire 25 à 30 minutes, en remuant de temps en temps, jusqu'à ce que les lentilles et les légumes soient bien tendres et que le bouillon prenne du corps. Si ça réduit trop, ajoute un peu d'eau chaude.",
   "Goûte le sel, parsème d'herbes et sers bien chaud."],
 "porcoes8": ["1 louche · sans pain",
              "2 louches · sans pain",
              "2 louches · 1 tranche de pain",
              "2 louches · 1 tranche de pain",
              "2 louches · 1 tranche de pain",
              "3 louches · 1 tranche de pain",
              "3 louches · 2 tranches de pain",
              "3 grandes louches · 2 tranches de pain"],
 "dica": "La lentille est l'une des légumineuses les plus riches en protéines et en fer, et dans la soupe elle rend le bouillon assez consistant pour être un dîner complet sans viande. Le liquide et les légumes en abondance remplissent l'estomac pour peu de calories — léger, chaud et réconfortant.",
},
{
 "nome": "Tofu grillé aux légumes et au riz",
 "tag": "Dîner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Le tofu doré absorbe l'assaisonnement et devient délicieux — une option sans viande qui rassasie vraiment et reste légère pour le soir.",
 "tempo": "25 min", "rende": "1 portion", "kcal_base": 420,
 "ings": ["150 g de tofu ferme en tranches", "4 c. à s. de riz complet cuit", "100 g de brocoli et carotte",
          "1 c. à s. de sauce soja allégée", "1 gousse d'ail hachée", "1 c. à c. d'huile d'olive",
          "gingembre râpé (facultatif)", "sel et poivre au goût"],
 "passos": [
   "Sèche bien les tranches de tofu avec du papier absorbant, en pressant légèrement — plus il est sec, mieux il dore.",
   "Assaisonne le tofu avec la sauce soja, l'ail et le gingembre. Laisse prendre le goût 5 minutes.",
   "Fais chauffer une poêle antiadhésive avec la moitié de l'huile d'olive à feu moyen-vif. Grille les tranches de tofu 3 à 4 minutes de chaque côté, sans y toucher, jusqu'à former une petite croûte dorée. Retire et réserve.",
   "Coupe le brocoli en bouquets et la carotte en rondelles. Dans la même poêle, avec le reste d'huile d'olive, fais sauter les légumes 4 minutes, jusqu'à ce qu'ils soient tendres mais encore fermes.",
   "Monte l'assiette avec le riz complet, les légumes et le tofu grillé par-dessus. Arrose d'un peu plus de sauce soja si tu veux."],
 "porcoes8": ["120 g de tofu · 3 c. à s. de riz · légumes",
              "150 g de tofu · 4 c. à s. de riz · légumes",
              "150 g de tofu · 5 c. à s. de riz · légumes",
              "170 g de tofu · 5 c. à s. de riz · un filet d'huile",
              "170 g de tofu · 5 c. à s. de riz · légumes",
              "200 g de tofu · 6 c. à s. de riz · légumes",
              "220 g de tofu · 7 c. à s. de riz · 1 c. à s. de noix",
              "250 g de tofu · 8 c. à s. de riz · noix"],
 "dica": "Le tofu est fait de soja et apporte des protéines végétales avec peu de graisses, c'est l'une des meilleures options pour varier de la viande. Bien séché et grillé, il gagne de la texture et absorbe les assaisonnements. Avec des légumes et du riz complet, ça devient un dîner complet, léger et plein de fibres.",
},
{
 "nome": "Aubergine farcie aux pois chiches et au fromage",
 "tag": "Dîner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "L'aubergine devient elle-même le plat, farcie de pois chiches relevés et gratinée au fromage — belle, copieuse et sans viande.",
 "tempo": "40 min", "rende": "2 portions", "kcal_base": 400,
 "ings": ["1 grosse aubergine", "165 g de pois chiches cuits", "1 oignon haché", "1 gousse d'ail hachée",
          "1 tomate hachée", "1 c. à c. d'huile d'olive", "2 c. à s. de fromage râpé allégé",
          "sel, poivre, cumin et persil au goût"],
 "passos": [
   "Préchauffe le four à 200 °C. Coupe l'aubergine en deux dans la longueur. À la cuillère, retire une partie de la chair pour former deux « barquettes ». Hache la chair retirée.",
   "Pose les barquettes sur une plaque, arrose d'un peu d'huile d'olive et enfourne 10 minutes, juste pour les attendrir.",
   "Dans une poêle, fais chauffer le reste d'huile d'olive et fais revenir l'oignon et l'ail 2 minutes. Ajoute la tomate, la chair d'aubergine hachée, les pois chiches, le cumin, du sel et du poivre et fais cuire 6 minutes, en écrasant un peu les pois chiches, jusqu'à obtenir une farce moelleuse.",
   "Garnis les barquettes avec le mélange de pois chiches et parsème de fromage râpé par-dessus.",
   "Remets au four 15 minutes, jusqu'à ce que ce soit gratiné (le fromage fondu et doré). Parsème de persil et sers."],
 "porcoes8": ["½ aubergine · salade",
              "1 aubergine farcie · salade",
              "1 aubergine · 2 c. à s. de riz",
              "1 aubergine · pois chiches en plus · salade",
              "1 aubergine · pois chiches en plus · 2 c. à s. de riz",
              "1 grosse aubergine · 3 c. à s. de riz",
              "1 aubergine · double pois chiches · 4 c. à s. de riz",
              "aubergine + portion en plus · 4 c. à s. de riz"],
 "dica": "L'aubergine contient beaucoup d'eau et de fibres, elle remplit donc l'assiette pour très peu de calories. Le pois chiche apporte la protéine végétale qui remplace la viande, et un peu de fromage gratiné calme l'envie de gratiné. Un dîner végétarien beau, copieux et léger.",
},
{
 "nome": "Curry de pois chiches au riz",
 "tag": "Dîner végétarien", "num_label": "Bonus · Végétarien",
 "hook": "Une sauce dorée et parfumée qui enveloppe les pois chiches — crémeuse au lait de coco allégé, c'est un dîner végétarien plein de goût.",
 "tempo": "30 min", "rende": "2 portions", "kcal_base": 440,
 "ings": ["330 g de pois chiches cuits", "1 oignon haché", "2 gousses d'ail hachées", "1 tomate hachée",
          "1 c. à c. de curry en poudre", "120 ml de lait de coco allégé", "1 poignée d'épinards (facultatif)",
          "1 c. à c. d'huile d'olive", "sel, poivre et coriandre au goût", "riz pour servir"],
 "passos": [
   "Fais chauffer l'huile d'olive dans une casserole à feu moyen et fais revenir l'oignon et l'ail 2 minutes, en remuant.",
   "Ajoute le curry et remue 30 secondes, pour que l'épice libère son arôme. Ajoute la tomate et fais cuire 3 minutes, jusqu'à ce qu'elle se défasse.",
   "Ajoute les pois chiches et le lait de coco allégé et mélange. Assaisonne avec du sel et du poivre.",
   "Fais cuire à feu doux 10 minutes, en remuant de temps en temps, jusqu'à ce que la sauce épaississe. Si tu veux, ajoute les épinards dans les 2 dernières minutes, juste le temps qu'ils retombent.",
   "Parsème de coriandre et sers sur une portion de riz."],
 "porcoes8": ["110 g de pois chiches · 3 c. à s. de riz",
              "165 g de pois chiches · 4 c. à s. de riz",
              "165 g de pois chiches · 5 c. à s. de riz",
              "165 g de pois chiches · 5 c. à s. de riz · épinards",
              "165 g de pois chiches · 5 c. à s. de riz",
              "250 g de pois chiches · 6 c. à s. de riz",
              "250 g de pois chiches · 7 c. à s. de riz",
              "330 g de pois chiches · 8 c. à s. de riz"],
 "dica": "Le pois chiche est riche en protéines et en fibres, et dans le curry il devient crémeux et plein de goût. Le lait de coco allégé donne de l'onctuosité à la sauce avec bien moins de graisse que la crème. Avec du riz, il forme une protéine complète — un dîner végétarien réconfortant et nourrissant.",
},
]
